\ =====================================================================
\  candidate.f - Address-free sandbox candidate module geometry
\ =====================================================================
\  The compiler publishes this bounded semantic candidate.  It is never
\  executable authority: the independent verifier must reconstruct an
\  owned sealed plan before the VM can start.
\
\  Candidate fields are little-endian and contain no native address, XT,
\  callback, allocator token, or borrowed span.  The representation keeps
\  the permanent function/import/entry/initial-memory/instruction model
\  while durable package envelopes and cryptographic identity remain above
\  the Stage 1 runtime boundary.
\ =====================================================================

REQUIRE format.f
REQUIRE ../utils/caller-span.f

PROVIDED akashic-sbx-candidate

0 CONSTANT SBOX-CANDIDATE-S-OK
1 CONSTANT SBOX-CANDIDATE-S-INVALID
2 CONSTANT SBOX-CANDIDATE-S-CAPACITY
3 CONSTANT SBOX-CANDIDATE-S-ALIAS

\ All nonempty spans owned by a public candidate operation pass through the
\ architectural caller-memory boundary before any byte or native-cell access.
\ This small status vocabulary deliberately closes every boundary rejection
\ to INVALID.
: _SCAND-SPAN-STATUS  ( address length -- status )
    DUP 0< IF 2DROP SBOX-CANDIDATE-S-INVALID EXIT THEN
    DUP 0= IF 2DROP SBOX-CANDIDATE-S-OK EXIT THEN
    OVER 0= IF 2DROP SBOX-CANDIDATE-S-INVALID EXIT THEN
    2DUP MSPAN-NONWRAPPING? 0= IF
        2DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    CALLER-SPAN-STATUS IF
        SBOX-CANDIDATE-S-INVALID
    ELSE
        SBOX-CANDIDATE-S-OK
    THEN ;

64 CONSTANT SBOX-CANDIDATE-HEADER-SIZE
16 CONSTANT SBOX-CANDIDATE-FUNCTION-SIZE
16 CONSTANT SBOX-CANDIDATE-IMPORT-SIZE
16 CONSTANT SBOX-CANDIDATE-ENTRY-SIZE
16 CONSTANT SBOX-CANDIDATE-INSTRUCTION-SIZE

\ Every scalar record is exactly 16 bytes.  These public offsets and the
\ primitive little-endian words below are shared compiler/verifier geometry;
\ they do not perform the verifier's semantic policy checks.
\
\ Function:
\   [u32 instruction-n, u16 params, u16 results,
\    u16 locals, u16 flags=0, u32 reserved=0]
 0 CONSTANT SBOX-CANDIDATE-FUNCTION-INSTRUCTION-N-OFFSET
 4 CONSTANT SBOX-CANDIDATE-FUNCTION-PARAMS-OFFSET
 6 CONSTANT SBOX-CANDIDATE-FUNCTION-RESULTS-OFFSET
 8 CONSTANT SBOX-CANDIDATE-FUNCTION-LOCALS-OFFSET
10 CONSTANT SBOX-CANDIDATE-FUNCTION-FLAGS-OFFSET
12 CONSTANT SBOX-CANDIDATE-FUNCTION-RESERVED-OFFSET

\ Import:
\   [u32 id>0, u16 params, u16 results, u32 cost, u32 flags=0]
 0 CONSTANT SBOX-CANDIDATE-IMPORT-ID-OFFSET
 4 CONSTANT SBOX-CANDIDATE-IMPORT-PARAMS-OFFSET
 6 CONSTANT SBOX-CANDIDATE-IMPORT-RESULTS-OFFSET
 8 CONSTANT SBOX-CANDIDATE-IMPORT-COST-OFFSET
12 CONSTANT SBOX-CANDIDATE-IMPORT-FLAGS-OFFSET

\ Entry:
\   [u32 name-off, u16 name-u, u16 flags=0,
\    u32 function-index, u32 reserved=0]
 0 CONSTANT SBOX-CANDIDATE-ENTRY-NAME-OFFSET
 4 CONSTANT SBOX-CANDIDATE-ENTRY-NAME-U-OFFSET
 6 CONSTANT SBOX-CANDIDATE-ENTRY-FLAGS-OFFSET
 8 CONSTANT SBOX-CANDIDATE-ENTRY-FUNCTION-INDEX-OFFSET
12 CONSTANT SBOX-CANDIDATE-ENTRY-RESERVED-OFFSET

\ Instruction:
\   [u16 opcode, u16 flags=0, u32 operand-a, u64 operand-b]
0 CONSTANT SBOX-CANDIDATE-INSTRUCTION-OPCODE-OFFSET
2 CONSTANT SBOX-CANDIDATE-INSTRUCTION-FLAGS-OFFSET
4 CONSTANT SBOX-CANDIDATE-INSTRUCTION-A-OFFSET
8 CONSTANT SBOX-CANDIDATE-INSTRUCTION-B-OFFSET

256  CONSTANT SBOX-CANDIDATE-FUNCTION-MAX
32   CONSTANT SBOX-CANDIDATE-IMPORT-MAX
32   CONSTANT SBOX-CANDIDATE-ENTRY-MAX
4096 CONSTANT SBOX-CANDIDATE-NAME-BYTES-MAX
65536 CONSTANT SBOX-CANDIDATE-INITIAL-BYTES-MAX
3072 CONSTANT SBOX-CANDIDATE-INSTRUCTION-MAX

\ The 64-byte semantic header is:
\   +0  8 bytes  ASCII "AKSBXCAN"
\   +8  u64      exact candidate byte extent
\   +16 u64      nonzero internal-profile tag
\   +24 u64      nonnegative requested linear-memory bytes
\   +32 u32      function count
\   +36 u32      import count
\   +40 u32      entry count
\   +44 u32      logical entry-name bytes
\   +48 u32      logical initial-memory bytes
\   +52 u32      instruction count
\   +56 u64      flags, exactly zero
\ Header offsets.
 0 CONSTANT _SCAND-H-MAGIC
 8 CONSTANT _SCAND-H-TOTAL
16 CONSTANT _SCAND-H-PROFILE-TAG
24 CONSTANT _SCAND-H-MEMORY-U
32 CONSTANT _SCAND-H-FUNCTION-N
36 CONSTANT _SCAND-H-IMPORT-N
40 CONSTANT _SCAND-H-ENTRY-N
44 CONSTANT _SCAND-H-NAME-U
48 CONSTANT _SCAND-H-INITIAL-U
52 CONSTANT _SCAND-H-INSTRUCTION-N
56 CONSTANT _SCAND-H-FLAGS

\ Caller-owned measured layout.  Inputs are copied into six count/length
\ cells; canonical offsets and the exact extent occupy the remaining cells.
  0 CONSTANT _SCL-MAGIC
  8 CONSTANT _SCL-SELF
 16 CONSTANT _SCL-FUNCTION-N
 24 CONSTANT _SCL-IMPORT-N
 32 CONSTANT _SCL-ENTRY-N
 40 CONSTANT _SCL-NAME-U
 48 CONSTANT _SCL-INITIAL-U
 56 CONSTANT _SCL-INSTRUCTION-N
 64 CONSTANT _SCL-FUNCTION-OFF
 72 CONSTANT _SCL-IMPORT-OFF
 80 CONSTANT _SCL-ENTRY-OFF
 88 CONSTANT _SCL-NAME-OFF
 96 CONSTANT _SCL-INITIAL-OFF
104 CONSTANT _SCL-INSTRUCTION-OFF
112 CONSTANT _SCL-TOTAL
120 CONSTANT _SCL-RESERVED
128 CONSTANT SBOX-CANDIDATE-LAYOUT-SIZE

0x534258434C41594F CONSTANT _SCAND-LAYOUT-MAGIC  \ "SBXCLAYO"

: _SCAND-L.MAGIC       ( layout -- address ) _SCL-MAGIC + ;
: _SCAND-L.SELF        ( layout -- address ) _SCL-SELF + ;
: _SCAND-L.FUNCTION-N  ( layout -- address ) _SCL-FUNCTION-N + ;
: _SCAND-L.IMPORT-N    ( layout -- address ) _SCL-IMPORT-N + ;
: _SCAND-L.ENTRY-N     ( layout -- address ) _SCL-ENTRY-N + ;
: _SCAND-L.NAME-U      ( layout -- address ) _SCL-NAME-U + ;
: _SCAND-L.INITIAL-U   ( layout -- address ) _SCL-INITIAL-U + ;
: _SCAND-L.INSTRUCTION-N
    ( layout -- address ) _SCL-INSTRUCTION-N + ;
: _SCAND-L.FUNCTION-OFF
    ( layout -- address ) _SCL-FUNCTION-OFF + ;
: _SCAND-L.IMPORT-OFF  ( layout -- address ) _SCL-IMPORT-OFF + ;
: _SCAND-L.ENTRY-OFF   ( layout -- address ) _SCL-ENTRY-OFF + ;
: _SCAND-L.NAME-OFF    ( layout -- address ) _SCL-NAME-OFF + ;
: _SCAND-L.INITIAL-OFF ( layout -- address ) _SCL-INITIAL-OFF + ;
: _SCAND-L.INSTRUCTION-OFF
    ( layout -- address ) _SCL-INSTRUCTION-OFF + ;
: _SCAND-L.TOTAL       ( layout -- address ) _SCL-TOTAL + ;
: _SCAND-L.RESERVED    ( layout -- address ) _SCL-RESERVED + ;

: _SCAND-LAYOUT-STATUS  ( layout -- status )
    DUP 0= IF DROP SBOX-CANDIDATE-S-INVALID EXIT THEN
    DUP 7 AND IF DROP SBOX-CANDIDATE-S-INVALID EXIT THEN
    SBOX-CANDIDATE-LAYOUT-SIZE _SCAND-SPAN-STATUS ;

\ Primitive wire access assumes that the owning operation has already
\ qualified a containing span of at least 2, 4, or 8 bytes respectively.
\ It is deliberately policy-neutral and works at any byte alignment.
: SBOX-CANDIDATE-U16-LE@  ( address -- value )
    DUP C@ SWAP 1+ C@ 8 LSHIFT OR ;

: SBOX-CANDIDATE-U32-LE@  ( address -- value )
    DUP SBOX-CANDIDATE-U16-LE@
    SWAP 2 + SBOX-CANDIDATE-U16-LE@ 16 LSHIFT OR ;

: SBOX-CANDIDATE-U64-LE@  ( address -- value )
    DUP SBOX-CANDIDATE-U32-LE@
    SWAP 4 + SBOX-CANDIDATE-U32-LE@ 32 LSHIFT OR ;

: SBOX-CANDIDATE-U16-LE!  ( value address -- )
    2DUP C!
    SWAP 8 RSHIFT SWAP 1+ C! ;

: SBOX-CANDIDATE-U32-LE!  ( value address -- )
    2DUP SBOX-CANDIDATE-U16-LE!
    SWAP 16 RSHIFT SWAP 2 + SBOX-CANDIDATE-U16-LE! ;

: SBOX-CANDIDATE-U64-LE!  ( value address -- )
    2DUP SBOX-CANDIDATE-U32-LE!
    SWAP 32 RSHIFT SWAP 4 + SBOX-CANDIDATE-U32-LE! ;

: _SCAND-AREA+  ( offset count element-u -- next status )
    SBOX-BYTE-LENGTH*
    DUP IF
        >R 2DROP 0 R> EXIT
    THEN
    DROP SBOX-BYTE-LENGTH+ ;

: _SCAND-PADDED+  ( offset logical-u -- next status )
    SBOX-BYTE-PAD8
    DUP IF
        >R 2DROP 0 R> EXIT
    THEN
    DROP SBOX-BYTE-LENGTH+ ;

: _SCAND-COUNT-VALID?  ( count maximum -- flag )
    >R DUP 0>= SWAP R> <= AND ;

: _SCAND-LIMIT-STATUS  ( value maximum -- status )
    >R
    DUP 0< IF
        DROP R> DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    R> U> IF
        SBOX-CANDIDATE-S-CAPACITY
    ELSE
        SBOX-CANDIDATE-S-OK
    THEN ;

: SBOX-CANDIDATE-LAYOUT-VALID?  ( layout -- flag )
    DUP _SCAND-LAYOUT-STATUS IF DROP 0 EXIT THEN
    DUP _SCAND-L.MAGIC @ _SCAND-LAYOUT-MAGIC <> IF DROP 0 EXIT THEN
    DUP _SCAND-L.SELF @ OVER <> IF DROP 0 EXIT THEN
    DUP _SCAND-L.RESERVED @ IF DROP 0 EXIT THEN
    DUP _SCAND-L.FUNCTION-N @ SBOX-CANDIDATE-FUNCTION-MAX
        _SCAND-COUNT-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SCAND-L.IMPORT-N @ SBOX-CANDIDATE-IMPORT-MAX
        _SCAND-COUNT-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SCAND-L.ENTRY-N @ SBOX-CANDIDATE-ENTRY-MAX
        _SCAND-COUNT-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SCAND-L.NAME-U @ SBOX-CANDIDATE-NAME-BYTES-MAX
        _SCAND-COUNT-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SCAND-L.INITIAL-U @ SBOX-CANDIDATE-INITIAL-BYTES-MAX
        _SCAND-COUNT-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SCAND-L.INSTRUCTION-N @ SBOX-CANDIDATE-INSTRUCTION-MAX
        _SCAND-COUNT-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SCAND-L.FUNCTION-OFF @ SBOX-CANDIDATE-HEADER-SIZE <> IF
        DROP 0 EXIT
    THEN
    DUP _SCAND-L.FUNCTION-OFF @
    OVER _SCAND-L.FUNCTION-N @ SBOX-CANDIDATE-FUNCTION-SIZE
        _SCAND-AREA+ DUP IF 2DROP DROP 0 EXIT THEN DROP
    OVER _SCAND-L.IMPORT-OFF @ <> IF DROP 0 EXIT THEN
    DUP _SCAND-L.IMPORT-OFF @
    OVER _SCAND-L.IMPORT-N @ SBOX-CANDIDATE-IMPORT-SIZE
        _SCAND-AREA+ DUP IF 2DROP DROP 0 EXIT THEN DROP
    OVER _SCAND-L.ENTRY-OFF @ <> IF DROP 0 EXIT THEN
    DUP _SCAND-L.ENTRY-OFF @
    OVER _SCAND-L.ENTRY-N @ SBOX-CANDIDATE-ENTRY-SIZE
        _SCAND-AREA+ DUP IF 2DROP DROP 0 EXIT THEN DROP
    OVER _SCAND-L.NAME-OFF @ <> IF DROP 0 EXIT THEN
    DUP _SCAND-L.NAME-OFF @
    OVER _SCAND-L.NAME-U @ _SCAND-PADDED+
        DUP IF 2DROP DROP 0 EXIT THEN DROP
    OVER _SCAND-L.INITIAL-OFF @ <> IF DROP 0 EXIT THEN
    DUP _SCAND-L.INITIAL-OFF @
    OVER _SCAND-L.INITIAL-U @ _SCAND-PADDED+
        DUP IF 2DROP DROP 0 EXIT THEN DROP
    OVER _SCAND-L.INSTRUCTION-OFF @ <> IF DROP 0 EXIT THEN
    DUP _SCAND-L.INSTRUCTION-OFF @
    OVER _SCAND-L.INSTRUCTION-N @ SBOX-CANDIDATE-INSTRUCTION-SIZE
        _SCAND-AREA+ DUP IF 2DROP DROP 0 EXIT THEN DROP
    OVER _SCAND-L.TOTAL @ = NIP ;

: _SCAND-MEASURE-FAIL  ( layout status -- status )
    >R SBOX-CANDIDATE-LAYOUT-SIZE 0 FILL R> ;

\ Measure writes only the caller-owned layout.  Once that span is admitted,
\ every ordinary failure clears it; success writes the self-bound magic last.
\ Stack: function-n import-n entry-n name-u initial-u instruction-n layout
\     -- status
: SBOX-CANDIDATE-MEASURE
    >R
    R@ _SCAND-LAYOUT-STATUS IF
        2DROP 2DROP 2DROP R> DROP
        SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    R@ SBOX-CANDIDATE-LAYOUT-SIZE 0 FILL
    R@ R@ _SCAND-L.SELF !
    R@ _SCAND-L.INSTRUCTION-N !
    R@ _SCAND-L.INITIAL-U !
    R@ _SCAND-L.NAME-U !
    R@ _SCAND-L.ENTRY-N !
    R@ _SCAND-L.IMPORT-N !
    R@ _SCAND-L.FUNCTION-N !

    R@ _SCAND-L.FUNCTION-N @ SBOX-CANDIDATE-FUNCTION-MAX
        _SCAND-LIMIT-STATUS
    DUP IF R> SWAP _SCAND-MEASURE-FAIL EXIT THEN DROP
    R@ _SCAND-L.IMPORT-N @ SBOX-CANDIDATE-IMPORT-MAX
        _SCAND-LIMIT-STATUS
    DUP IF R> SWAP _SCAND-MEASURE-FAIL EXIT THEN DROP
    R@ _SCAND-L.ENTRY-N @ SBOX-CANDIDATE-ENTRY-MAX
        _SCAND-LIMIT-STATUS
    DUP IF R> SWAP _SCAND-MEASURE-FAIL EXIT THEN DROP
    R@ _SCAND-L.NAME-U @ SBOX-CANDIDATE-NAME-BYTES-MAX
        _SCAND-LIMIT-STATUS
    DUP IF R> SWAP _SCAND-MEASURE-FAIL EXIT THEN DROP
    R@ _SCAND-L.INITIAL-U @ SBOX-CANDIDATE-INITIAL-BYTES-MAX
        _SCAND-LIMIT-STATUS
    DUP IF R> SWAP _SCAND-MEASURE-FAIL EXIT THEN DROP
    R@ _SCAND-L.INSTRUCTION-N @ SBOX-CANDIDATE-INSTRUCTION-MAX
        _SCAND-LIMIT-STATUS
    DUP IF R> SWAP _SCAND-MEASURE-FAIL EXIT THEN DROP

    SBOX-CANDIDATE-HEADER-SIZE
    DUP R@ _SCAND-L.FUNCTION-OFF !
    R@ _SCAND-L.FUNCTION-N @ SBOX-CANDIDATE-FUNCTION-SIZE
        _SCAND-AREA+ DUP IF
        >R DROP R> R> SWAP _SCAND-MEASURE-FAIL EXIT
    THEN DROP
    DUP R@ _SCAND-L.IMPORT-OFF !
    R@ _SCAND-L.IMPORT-N @ SBOX-CANDIDATE-IMPORT-SIZE
        _SCAND-AREA+ DUP IF
        >R DROP R> R> SWAP _SCAND-MEASURE-FAIL EXIT
    THEN DROP
    DUP R@ _SCAND-L.ENTRY-OFF !
    R@ _SCAND-L.ENTRY-N @ SBOX-CANDIDATE-ENTRY-SIZE
        _SCAND-AREA+ DUP IF
        >R DROP R> R> SWAP _SCAND-MEASURE-FAIL EXIT
    THEN DROP
    DUP R@ _SCAND-L.NAME-OFF !
    R@ _SCAND-L.NAME-U @ _SCAND-PADDED+ DUP IF
        >R DROP R> R> SWAP _SCAND-MEASURE-FAIL EXIT
    THEN DROP
    DUP R@ _SCAND-L.INITIAL-OFF !
    R@ _SCAND-L.INITIAL-U @ _SCAND-PADDED+ DUP IF
        >R DROP R> R> SWAP _SCAND-MEASURE-FAIL EXIT
    THEN DROP
    DUP R@ _SCAND-L.INSTRUCTION-OFF !
    R@ _SCAND-L.INSTRUCTION-N @ SBOX-CANDIDATE-INSTRUCTION-SIZE
        _SCAND-AREA+ DUP IF
        >R DROP R> R> SWAP _SCAND-MEASURE-FAIL EXIT
    THEN DROP
    DUP R@ _SCAND-L.TOTAL !
    DROP
    _SCAND-LAYOUT-MAGIC R@ _SCAND-L.MAGIC !
    R> DROP SBOX-CANDIDATE-S-OK ;

: SBOX-CANDIDATE-LAYOUT-TOTAL@  ( layout -- total|0 )
    DUP SBOX-CANDIDATE-LAYOUT-VALID? IF
        _SCAND-L.TOTAL @
    ELSE
        DROP 0
    THEN ;

: SBOX-CANDIDATE-LAYOUT-FUNCTIONS@
  ( layout -- offset|0 )
    DUP SBOX-CANDIDATE-LAYOUT-VALID? IF
        _SCAND-L.FUNCTION-OFF @
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-LAYOUT-IMPORTS@
  ( layout -- offset|0 )
    DUP SBOX-CANDIDATE-LAYOUT-VALID? IF
        _SCAND-L.IMPORT-OFF @
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-LAYOUT-ENTRIES@
  ( layout -- offset|0 )
    DUP SBOX-CANDIDATE-LAYOUT-VALID? IF
        _SCAND-L.ENTRY-OFF @
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-LAYOUT-NAMES@
  ( layout -- offset|0 )
    DUP SBOX-CANDIDATE-LAYOUT-VALID? IF
        _SCAND-L.NAME-OFF @
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-LAYOUT-INITIAL@
  ( layout -- offset|0 )
    DUP SBOX-CANDIDATE-LAYOUT-VALID? IF
        _SCAND-L.INITIAL-OFF @
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-LAYOUT-INSTRUCTIONS@
  ( layout -- offset|0 )
    DUP SBOX-CANDIDATE-LAYOUT-VALID? IF
        _SCAND-L.INSTRUCTION-OFF @
    ELSE DROP 0 THEN ;

: _SCAND-MAGIC?  ( candidate -- flag )
    DUP C@ [CHAR] A =
    OVER 1+ C@ [CHAR] K = AND
    OVER 2 + C@ [CHAR] S = AND
    OVER 3 + C@ [CHAR] B = AND
    OVER 4 + C@ [CHAR] X = AND
    OVER 5 + C@ [CHAR] C = AND
    OVER 6 + C@ [CHAR] A = AND
    SWAP 7 + C@ [CHAR] N = AND ;

: _SCAND-WRITE-MAGIC  ( candidate -- )
    [CHAR] A OVER C!
    [CHAR] K OVER 1+ C!
    [CHAR] S OVER 2 + C!
    [CHAR] B OVER 3 + C!
    [CHAR] X OVER 4 + C!
    [CHAR] C OVER 5 + C!
    [CHAR] A OVER 6 + C!
    [CHAR] N SWAP 7 + C! ;

: _SCAND-CANDIDATE-LAYOUT-OVERLAP?  ( candidate layout -- flag )
    DUP >R _SCAND-L.TOTAL @
    R> SBOX-CANDIDATE-LAYOUT-SIZE MSPAN-OVERLAP? ;

\ HEADER! initializes the complete measured candidate, including zero padding,
\ before publishing the header.  Candidate and layout must be disjoint.
: SBOX-CANDIDATE-HEADER!
  ( profile-tag memory-u layout candidate -- status )
    >R
    R@ 0= IF
        2DROP DROP R> DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    DUP SBOX-CANDIDATE-LAYOUT-VALID? 0= IF
        2DROP DROP R> DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    DUP _SCAND-L.TOTAL @ R@ SWAP
        _SCAND-SPAN-STATUS IF
        2DROP DROP R> DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    R@ OVER _SCAND-CANDIDATE-LAYOUT-OVERLAP? IF
        2DROP DROP R> DROP SBOX-CANDIDATE-S-ALIAS EXIT
    THEN
    2 PICK 0= IF
        2DROP DROP R> DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    OVER 0< IF
        2DROP DROP R> DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    \ Initialization precedes section publication and canonicalizes padding.
    R@ OVER _SCAND-L.TOTAL @ 0 FILL
    DUP _SCAND-L.TOTAL @
        R@ _SCAND-H-TOTAL + SBOX-CANDIDATE-U64-LE!
    2 PICK
        R@ _SCAND-H-PROFILE-TAG + SBOX-CANDIDATE-U64-LE!
    OVER
        R@ _SCAND-H-MEMORY-U + SBOX-CANDIDATE-U64-LE!
    DUP _SCAND-L.FUNCTION-N @
        R@ _SCAND-H-FUNCTION-N + SBOX-CANDIDATE-U32-LE!
    DUP _SCAND-L.IMPORT-N @
        R@ _SCAND-H-IMPORT-N + SBOX-CANDIDATE-U32-LE!
    DUP _SCAND-L.ENTRY-N @
        R@ _SCAND-H-ENTRY-N + SBOX-CANDIDATE-U32-LE!
    DUP _SCAND-L.NAME-U @
        R@ _SCAND-H-NAME-U + SBOX-CANDIDATE-U32-LE!
    DUP _SCAND-L.INITIAL-U @
        R@ _SCAND-H-INITIAL-U + SBOX-CANDIDATE-U32-LE!
    DUP _SCAND-L.INSTRUCTION-N @
        R@ _SCAND-H-INSTRUCTION-N + SBOX-CANDIDATE-U32-LE!
    R@ _SCAND-WRITE-MAGIC
    2DROP DROP R> DROP SBOX-CANDIDATE-S-OK ;

: _SCAND-MEASURE-HEADER  ( candidate layout -- status )
    >R >R
    R@ _SCAND-H-FUNCTION-N + SBOX-CANDIDATE-U32-LE@
    R@ _SCAND-H-IMPORT-N + SBOX-CANDIDATE-U32-LE@
    R@ _SCAND-H-ENTRY-N + SBOX-CANDIDATE-U32-LE@
    R@ _SCAND-H-NAME-U + SBOX-CANDIDATE-U32-LE@
    R@ _SCAND-H-INITIAL-U + SBOX-CANDIDATE-U32-LE@
    R@ _SCAND-H-INSTRUCTION-N + SBOX-CANDIDATE-U32-LE@
    R> DROP
    R> SBOX-CANDIDATE-MEASURE ;

\ INSPECT treats the supplied candidate extent as exact and independently
\ reconstructs the measured layout.  It validates header/section geometry,
\ not record policy.  It does not touch the destination until both spans are
\ admitted and disjoint; subsequent format failures clear that destination.
: SBOX-CANDIDATE-INSPECT
  ( candidate candidate-u layout -- status )
    >R
    R@ _SCAND-LAYOUT-STATUS IF
        2DROP R> DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    DUP 0< IF
        2DROP R> DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    OVER 0= IF
        2DROP R> DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    2DUP MSPAN-NONWRAPPING? 0= IF
        2DROP R> DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    2DUP _SCAND-SPAN-STATUS IF
        2DROP R> DROP SBOX-CANDIDATE-S-INVALID EXIT
    THEN
    2DUP R@ SBOX-CANDIDATE-LAYOUT-SIZE MSPAN-OVERLAP? IF
        2DROP R> DROP SBOX-CANDIDATE-S-ALIAS EXIT
    THEN
    DUP SBOX-CANDIDATE-HEADER-SIZE < IF
        2DROP R> SBOX-CANDIDATE-S-CAPACITY _SCAND-MEASURE-FAIL EXIT
    THEN
    OVER _SCAND-MAGIC? 0= IF
        2DROP R> SBOX-CANDIDATE-S-INVALID _SCAND-MEASURE-FAIL EXIT
    THEN
    OVER _SCAND-H-TOTAL + SBOX-CANDIDATE-U64-LE@ OVER <> IF
        2DROP R> SBOX-CANDIDATE-S-INVALID _SCAND-MEASURE-FAIL EXIT
    THEN
    OVER _SCAND-H-FLAGS + SBOX-CANDIDATE-U64-LE@ IF
        2DROP R> SBOX-CANDIDATE-S-INVALID _SCAND-MEASURE-FAIL EXIT
    THEN
    OVER _SCAND-H-PROFILE-TAG + SBOX-CANDIDATE-U64-LE@ 0= IF
        2DROP R> SBOX-CANDIDATE-S-INVALID _SCAND-MEASURE-FAIL EXIT
    THEN
    OVER _SCAND-H-MEMORY-U + SBOX-CANDIDATE-U64-LE@ 0< IF
        2DROP R> SBOX-CANDIDATE-S-INVALID _SCAND-MEASURE-FAIL EXIT
    THEN
    OVER R@ _SCAND-MEASURE-HEADER
    DUP IF
        >R 2DROP R> R> DROP EXIT
    THEN
    DROP
    R@ _SCAND-L.TOTAL @ OVER <> IF
        2DROP R> SBOX-CANDIDATE-S-INVALID _SCAND-MEASURE-FAIL EXIT
    THEN
    2DROP R> DROP SBOX-CANDIDATE-S-OK ;

: _SCAND-HEADER-ADMIT?  ( candidate -- candidate flag )
    DUP SBOX-CANDIDATE-HEADER-SIZE _SCAND-SPAN-STATUS 0= ;

: SBOX-CANDIDATE-TOTAL@  ( candidate -- total|0 )
    _SCAND-HEADER-ADMIT? IF
        _SCAND-H-TOTAL + SBOX-CANDIDATE-U64-LE@
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-PROFILE-TAG@  ( candidate -- tag|0 )
    _SCAND-HEADER-ADMIT? IF
        _SCAND-H-PROFILE-TAG + SBOX-CANDIDATE-U64-LE@
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-MEMORY-U@  ( candidate -- memory-u|0 )
    _SCAND-HEADER-ADMIT? IF
        _SCAND-H-MEMORY-U + SBOX-CANDIDATE-U64-LE@
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-FUNCTION-N@  ( candidate -- count|0 )
    _SCAND-HEADER-ADMIT? IF
        _SCAND-H-FUNCTION-N + SBOX-CANDIDATE-U32-LE@
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-IMPORT-N@  ( candidate -- count|0 )
    _SCAND-HEADER-ADMIT? IF
        _SCAND-H-IMPORT-N + SBOX-CANDIDATE-U32-LE@
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-ENTRY-N@  ( candidate -- count|0 )
    _SCAND-HEADER-ADMIT? IF
        _SCAND-H-ENTRY-N + SBOX-CANDIDATE-U32-LE@
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-NAME-U@  ( candidate -- length|0 )
    _SCAND-HEADER-ADMIT? IF
        _SCAND-H-NAME-U + SBOX-CANDIDATE-U32-LE@
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-INITIAL-U@  ( candidate -- length|0 )
    _SCAND-HEADER-ADMIT? IF
        _SCAND-H-INITIAL-U + SBOX-CANDIDATE-U32-LE@
    ELSE DROP 0 THEN ;

: SBOX-CANDIDATE-INSTRUCTION-N@  ( candidate -- count|0 )
    _SCAND-HEADER-ADMIT? IF
        _SCAND-H-INSTRUCTION-N + SBOX-CANDIDATE-U32-LE@
    ELSE DROP 0 THEN ;
