\ =====================================================================
\  atproto-author-feed-connector.f - Authenticated AT feed input owner
\ =====================================================================
\  One caller-owned instance composes the general AT author-feed target,
\  authenticated XRPC exchange, bounded Bluesky feed projection, and one
\  sealed Streams input connector.  The concrete Bluesky AppView proxy is
\  trusted composition policy here; it is not embedded in generic XRPC or
\  HTTP code.
\
\  A successful poll first decodes the detached JSON response into the
\  instance-owned BFM projection.  PUBLISH then lends that same validated
\  raw JSON page to STREAMS-FLOW-ADMIT.  Admission copies it into the
\  flow-owned carrier and closes the source event before XIO cleanup can
\  wipe the response arena.  The owned BFM projection survives XIO wipe.
\
\  The instance owns no credentials, flow, carrier, clock, service, or
\  network singleton.  Credential/session objects and request/body arenas
\  remain caller-owned and must outlive a binding.  Calls are serialized on
\  the Streams/network owner context because BFM-DECODE-FEED uses the
\  existing owner-serialized JSON adapter.
\ =====================================================================

\ Keep the KDOS module identity within 23 bytes.
PROVIDED akashic-streams-atfeed

REQUIRE ../../../utils/memory-span.f
REQUIRE ../../../utils/caller-span.f
REQUIRE ../../../math/sha3.f
REQUIRE ../../../atproto/get-author-feed.f
REQUIRE ../../../atproto/xrpc-exchange.f
REQUIRE ../../../atproto/feed-model.f
REQUIRE flow-core.f
REQUIRE atproto.f

\ =====================================================================
\  Closed public vocabulary
\ =====================================================================

0  CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-OK
1  CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-INVALID
2  CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-BUSY
3  CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-CAPACITY
4  CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-ALIAS
5  CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-CONFIG
6  CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-TARGET
7  CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-XRPC
8  CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-DECODE
9  CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-FLOW
10 CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-STATE
11 CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-RANGE
12 CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-PROTECTED
13 CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-PLATFORM
14 CONSTANT AT-AUTHOR-FEED-CONNECTOR-S-INTERNAL

: AT-AUTHOR-FEED-CONNECTOR-STATUS-VALID?  ( status -- flag )
    DUP AT-AUTHOR-FEED-CONNECTOR-S-OK >=
    SWAP AT-AUTHOR-FEED-CONNECTOR-S-INTERNAL <= AND ;

-4741 CONSTANT AT-AUTHOR-FEED-CONNECTOR-XERR-INVALID
-4742 CONSTANT AT-AUTHOR-FEED-CONNECTOR-XERR-DECODE

: AT-AUTHOR-FEED-CONNECTOR-APPVIEW-PROXY$
  ( -- address length )
    S" did:web:api.bsky.app#bsky_appview" ;

\ =====================================================================
\  Per-instance geometry
\ =====================================================================

0x4154464545444331 CONSTANT _ATAFC-MAGIC-VALUE  \ "ATFEEDC1"

1 CONSTANT _ATAFC-F-FEED
2 CONSTANT _ATAFC-F-CURRENT
4 CONSTANT _ATAFC-F-PUBLISHED
7 CONSTANT _ATAFC-F-KNOWN

 0 CONSTANT _ATAFC-MAGIC
 8 CONSTANT _ATAFC-LAST-STATUS
16 CONSTANT _ATAFC-FLAGS
24 CONSTANT _ATAFC-SEQUENCE
32 CONSTANT _ATAFC-RESERVED0
40 CONSTANT _ATAFC-RESERVED1
48 CONSTANT _ATAFC-HEADER-SIZE

_ATAFC-HEADER-SIZE CONSTANT _ATAFC-CONNECTOR-OFF
_ATAFC-CONNECTOR-OFF STREAMS-CONNECTOR-SIZE +
    CONSTANT _ATAFC-EXCHANGE-OFF
_ATAFC-EXCHANGE-OFF AT-XRPC-EXCHANGE-SIZE +
    CONSTANT _ATAFC-TARGET-OFF
_ATAFC-TARGET-OFF HTARGET-SIZE +
    CONSTANT _ATAFC-TARGET-WORK-OFF
_ATAFC-TARGET-WORK-OFF AT-GET-AUTHOR-FEED-WORKSPACE-SIZE +
    CONSTANT _ATAFC-FEED-OFF
_ATAFC-FEED-OFF BFM-FEED-SIZE +
    CONSTANT _ATAFC-EVENT-OFF
_ATAFC-EVENT-OFF STREAMS-EVENT-SIZE +
    CONSTANT AT-AUTHOR-FEED-CONNECTOR-SIZE

: ATAFC.MAGIC        ( owner -- field ) _ATAFC-MAGIC + ;
: ATAFC.LAST-STATUS  ( owner -- field ) _ATAFC-LAST-STATUS + ;
: ATAFC.FLAGS        ( owner -- field ) _ATAFC-FLAGS + ;
: ATAFC.SEQUENCE     ( owner -- field ) _ATAFC-SEQUENCE + ;

: ATAFC.CONNECTOR    ( owner -- connector ) _ATAFC-CONNECTOR-OFF + ;
: ATAFC.EXCHANGE     ( owner -- exchange ) _ATAFC-EXCHANGE-OFF + ;
: ATAFC.TARGET       ( owner -- target ) _ATAFC-TARGET-OFF + ;
: ATAFC.TARGET-WORK  ( owner -- workspace ) _ATAFC-TARGET-WORK-OFF + ;
: ATAFC.FEED         ( owner -- feed ) _ATAFC-FEED-OFF + ;
: ATAFC.EVENT        ( owner -- event ) _ATAFC-EVENT-OFF + ;

\ =====================================================================
\  Admission, validation, and status mapping
\ =====================================================================

: _ATAFC-CALLER>STATUS  ( caller-status -- status )
    DUP CALLER-SPAN-S-OK = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-OK EXIT
    THEN
    DUP CALLER-SPAN-S-RANGE = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-RANGE EXIT
    THEN
    DUP CALLER-SPAN-S-PROTECTED = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-PROTECTED EXIT
    THEN
    DROP AT-AUTHOR-FEED-CONNECTOR-S-PLATFORM ;

: _ATAFC-SPAN-STATUS  ( address length -- status )
    DUP 0< IF 2DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT THEN
    DUP 0= IF 2DROP AT-AUTHOR-FEED-CONNECTOR-S-OK EXIT THEN
    OVER 0= IF 2DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT THEN
    CALLER-SPAN-STATUS _ATAFC-CALLER>STATUS ;

: _ATAFC-REQUIRED-SPAN-STATUS  ( address length -- status )
    DUP 0> 0= IF
        2DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    OVER 0= IF
        2DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    CALLER-SPAN-STATUS _ATAFC-CALLER>STATUS ;

: _ATAFC-OPTIONAL-SPAN-STATUS  ( address length -- status )
    DUP 0< IF 2DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT THEN
    DUP 0= IF
        DROP 0= IF
            AT-AUTHOR-FEED-CONNECTOR-S-OK
        ELSE
            AT-AUTHOR-FEED-CONNECTOR-S-INVALID
        THEN
        EXIT
    THEN
    OVER 0= IF 2DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT THEN
    CALLER-SPAN-STATUS _ATAFC-CALLER>STATUS ;

: _ATAFC-FIXED-STATUS  ( address length -- status )
    OVER 0= IF 2DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT THEN
    OVER 7 AND IF 2DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT THEN
    _ATAFC-SPAN-STATUS ;

: _ATAFC-XRPC>STATUS  ( xrpc-status -- status )
    DUP AT-XRPC-EXCHANGE-S-OK = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-OK EXIT
    THEN
    DUP AT-XRPC-EXCHANGE-S-INVALID = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    DUP AT-XRPC-EXCHANGE-S-BUSY = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-BUSY EXIT
    THEN
    DUP AT-XRPC-EXCHANGE-S-CAPACITY = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-CAPACITY EXIT
    THEN
    DUP AT-XRPC-EXCHANGE-S-ALIAS = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT
    THEN
    DUP AT-XRPC-EXCHANGE-S-RANGE = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-RANGE EXIT
    THEN
    DUP AT-XRPC-EXCHANGE-S-PROTECTED = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-PROTECTED EXIT
    THEN
    DUP AT-XRPC-EXCHANGE-S-PLATFORM = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-PLATFORM EXIT
    THEN
    DROP AT-AUTHOR-FEED-CONNECTOR-S-XRPC ;

: _ATAFC-TARGET>STATUS  ( target-status -- status )
    DUP AT-GET-AUTHOR-FEED-S-OK = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-OK EXIT
    THEN
    DUP AT-GET-AUTHOR-FEED-S-CAPACITY = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-CAPACITY EXIT
    THEN
    DUP AT-GET-AUTHOR-FEED-S-ALIAS = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT
    THEN
    DUP AT-GET-AUTHOR-FEED-S-RANGE = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-RANGE EXIT
    THEN
    DUP AT-GET-AUTHOR-FEED-S-PROTECTED = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-PROTECTED EXIT
    THEN
    DUP AT-GET-AUTHOR-FEED-S-PLATFORM = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-PLATFORM EXIT
    THEN
    DUP AT-GET-AUTHOR-FEED-S-PDS =
    OVER AT-GET-AUTHOR-FEED-S-ACTOR = OR
    OVER AT-GET-AUTHOR-FEED-S-LIMIT = OR
    OVER AT-GET-AUTHOR-FEED-S-FILTER = OR
    SWAP AT-GET-AUTHOR-FEED-S-TARGET = OR IF
        AT-AUTHOR-FEED-CONNECTOR-S-TARGET
    ELSE
        AT-AUTHOR-FEED-CONNECTOR-S-INTERNAL
    THEN ;

: _ATAFC-FLOW>STATUS  ( flow-status -- status )
    DUP STREAMS-FLOW-S-OK = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-OK EXIT
    THEN
    DUP STREAMS-FLOW-S-BUSY = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-BUSY EXIT
    THEN
    DUP STREAMS-FLOW-S-FULL = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-BUSY EXIT
    THEN
    DUP STREAMS-FLOW-S-CAPACITY = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-CAPACITY EXIT
    THEN
    DUP STREAMS-FLOW-S-STALE = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-STATE EXIT
    THEN
    DUP STREAMS-FLOW-S-INVALID = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    DROP AT-AUTHOR-FEED-CONNECTOR-S-FLOW ;

: _ATAFC-FLAG?  ( mask owner -- flag )
    ATAFC.FLAGS @ AND 0<> ;

: _ATAFC-FLAG+  ( mask owner -- )
    ATAFC.FLAGS DUP @ ROT OR SWAP ! ;

: _ATAFC-FLAG-  ( mask owner -- )
    ATAFC.FLAGS DUP @ ROT INVERT AND SWAP ! ;

: _ATAFC-FEED-SHAPE?  ( owner -- flag )
    DUP ATAFC.FEED BFM.FEED.COUNT @
    DUP 0< SWAP BFM-MAX-ITEMS > OR IF DROP 0 EXIT THEN
    ATAFC.FEED BFM.FEED.CURSOR-U @
    DUP 0< SWAP BFM-CURSOR-CAP > OR 0= ;

: AT-AUTHOR-FEED-CONNECTOR-VALID?  ( owner -- flag )
    DUP AT-AUTHOR-FEED-CONNECTOR-SIZE _ATAFC-FIXED-STATUS
    AT-AUTHOR-FEED-CONNECTOR-S-OK <> IF DROP 0 EXIT THEN
    DUP ATAFC.MAGIC @ _ATAFC-MAGIC-VALUE <> IF DROP 0 EXIT THEN
    DUP ATAFC.LAST-STATUS @
        AT-AUTHOR-FEED-CONNECTOR-STATUS-VALID? 0= IF DROP 0 EXIT THEN
    DUP ATAFC.FLAGS @ DUP 0< IF 2DROP 0 EXIT THEN
    DUP _ATAFC-F-KNOWN INVERT AND IF 2DROP 0 EXIT THEN
    DROP
    DUP ATAFC.SEQUENCE @ 0< IF DROP 0 EXIT THEN
    DUP ATAFC.CONNECTOR STREAMS-CONNECTOR-VALID? 0= IF DROP 0 EXIT THEN
    DUP ATAFC.EXCHANGE AT-XRPC-EXCHANGE-VALID? 0= IF DROP 0 EXIT THEN
    DUP _ATAFC-F-CURRENT SWAP _ATAFC-FLAG? IF
        DUP _ATAFC-F-FEED SWAP _ATAFC-FLAG? 0= IF DROP 0 EXIT THEN
    THEN
    DUP _ATAFC-F-PUBLISHED SWAP _ATAFC-FLAG? IF
        DUP _ATAFC-F-CURRENT SWAP _ATAFC-FLAG? 0= IF DROP 0 EXIT THEN
        DUP ATAFC.EVENT STREAMS-EVENT-VALID? 0= IF DROP 0 EXIT THEN
    THEN
    DUP _ATAFC-F-FEED SWAP _ATAFC-FLAG? IF
        DUP _ATAFC-FEED-SHAPE? 0= IF DROP 0 EXIT THEN
    THEN
    DROP -1 ;

\ =====================================================================
\  Initialization
\ =====================================================================

VARIABLE _ATAFCI-ID
VARIABLE _ATAFCI-ENDPOINT
VARIABLE _ATAFCI-REVISION
VARIABLE _ATAFCI-REQUEST-A
VARIABLE _ATAFCI-REQUEST-CAP
VARIABLE _ATAFCI-BODY-A
VARIABLE _ATAFCI-BODY-CAP
VARIABLE _ATAFCI-OWNER

: _ATAFCI-CLEAR  ( -- )
    0 _ATAFCI-ID ! 0 _ATAFCI-ENDPOINT ! 0 _ATAFCI-REVISION !
    0 _ATAFCI-REQUEST-A ! 0 _ATAFCI-REQUEST-CAP !
    0 _ATAFCI-BODY-A ! 0 _ATAFCI-BODY-CAP ! 0 _ATAFCI-OWNER ! ;

: _ATAFCI-RETURN  ( status -- status )
    >R _ATAFCI-CLEAR R> ;

: _ATAFCI-GEOMETRY  ( -- status )
    _ATAFCI-OWNER @ AT-AUTHOR-FEED-CONNECTOR-SIZE
    _ATAFC-FIXED-STATUS ?DUP IF EXIT THEN
    _ATAFCI-ID @ RID-SIZE _ATAFC-REQUIRED-SPAN-STATUS ?DUP IF EXIT THEN
    _ATAFCI-ENDPOINT @ RID-SIZE
    _ATAFC-REQUIRED-SPAN-STATUS ?DUP IF EXIT THEN
    _ATAFCI-REQUEST-A @ _ATAFCI-REQUEST-CAP @
    _ATAFC-REQUIRED-SPAN-STATUS ?DUP IF EXIT THEN
    _ATAFCI-BODY-A @ _ATAFCI-BODY-CAP @
    _ATAFC-REQUIRED-SPAN-STATUS ?DUP IF EXIT THEN
    _ATAFCI-REVISION @ 0> 0= IF
        AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    _ATAFCI-ID @ RID-PRESENT? 0= IF
        AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    _ATAFCI-ENDPOINT @ RID-PRESENT? 0= IF
        AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN

    _ATAFCI-REQUEST-A @ _ATAFCI-REQUEST-CAP @
    _ATAFCI-BODY-A @ _ATAFCI-BODY-CAP @
    MSPAN-OVERLAP? IF AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT THEN
    _ATAFCI-REQUEST-A @ _ATAFCI-REQUEST-CAP @
    _ATAFCI-OWNER @ AT-AUTHOR-FEED-CONNECTOR-SIZE
    MSPAN-OVERLAP? IF AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT THEN
    _ATAFCI-BODY-A @ _ATAFCI-BODY-CAP @
    _ATAFCI-OWNER @ AT-AUTHOR-FEED-CONNECTOR-SIZE
    MSPAN-OVERLAP? IF AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT THEN
    _ATAFCI-ID @ RID-SIZE
    _ATAFCI-OWNER @ AT-AUTHOR-FEED-CONNECTOR-SIZE
    MSPAN-OVERLAP? IF AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT THEN
    _ATAFCI-ENDPOINT @ RID-SIZE
    _ATAFCI-OWNER @ AT-AUTHOR-FEED-CONNECTOR-SIZE
    MSPAN-OVERLAP? IF AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT THEN
    _ATAFCI-ID @ RID-SIZE
    _ATAFCI-REQUEST-A @ _ATAFCI-REQUEST-CAP @
    MSPAN-OVERLAP? IF AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT THEN
    _ATAFCI-ID @ RID-SIZE
    _ATAFCI-BODY-A @ _ATAFCI-BODY-CAP @
    MSPAN-OVERLAP? IF AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT THEN
    _ATAFCI-ENDPOINT @ RID-SIZE
    _ATAFCI-REQUEST-A @ _ATAFCI-REQUEST-CAP @
    MSPAN-OVERLAP? IF AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT THEN
    _ATAFCI-ENDPOINT @ RID-SIZE
    _ATAFCI-BODY-A @ _ATAFCI-BODY-CAP @
    MSPAN-OVERLAP? IF AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT THEN
    AT-AUTHOR-FEED-CONNECTOR-S-OK ;

: AT-AUTHOR-FEED-CONNECTOR-INIT
  ( id endpoint revision request-a request-cap body-a body-cap owner -- status )
    _ATAFCI-OWNER ! _ATAFCI-BODY-CAP ! _ATAFCI-BODY-A !
    _ATAFCI-REQUEST-CAP ! _ATAFCI-REQUEST-A !
    _ATAFCI-REVISION ! _ATAFCI-ENDPOINT ! _ATAFCI-ID !
    _ATAFCI-GEOMETRY ?DUP IF _ATAFCI-RETURN EXIT THEN

    _ATAFCI-OWNER @ AT-AUTHOR-FEED-CONNECTOR-SIZE 0 FILL
    _ATAFCI-REQUEST-A @ _ATAFCI-REQUEST-CAP @
    _ATAFCI-BODY-A @ _ATAFCI-BODY-CAP @
    _ATAFCI-OWNER @ ATAFC.EXCHANGE
    AT-XRPC-EXCHANGE-INIT _ATAFC-XRPC>STATUS
    ?DUP IF _ATAFCI-RETURN EXIT THEN

    _ATAFCI-OWNER @ ATAFC.CONNECTOR STREAMS-CONNECTOR-INIT
    STREAMS-FLOW-S-OK <> IF
        AT-AUTHOR-FEED-CONNECTOR-S-INTERNAL _ATAFCI-RETURN EXIT
    THEN
    _ATAFCI-ID @ _ATAFCI-OWNER @ ATAFC.CONNECTOR SCON.ID RID-COPY
    _ATAFCI-ENDPOINT @
        _ATAFCI-OWNER @ ATAFC.CONNECTOR SCON.ENDPOINT-ID RID-COPY
    _ATAFCI-REVISION @
        _ATAFCI-OWNER @ ATAFC.CONNECTOR SCON.REVISION !
    STREAMS-CONNECTOR-DIRECTION-INPUT
        _ATAFCI-OWNER @ ATAFC.CONNECTOR SCON.DIRECTION !
    STREAMS-PROTOCOL-ATPROTO
        _ATAFCI-OWNER @ ATAFC.CONNECTOR SCON.PROTOCOL !
    _ATAFCI-OWNER @ ATAFC.CONNECTOR STREAMS-CONNECTOR-SEAL
    STREAMS-FLOW-S-OK <> IF
        AT-AUTHOR-FEED-CONNECTOR-S-INTERNAL _ATAFCI-RETURN EXIT
    THEN
    _ATAFCI-OWNER @ ATAFC.FEED BFM-FEED-INIT
    AT-AUTHOR-FEED-CONNECTOR-S-OK
        _ATAFCI-OWNER @ ATAFC.LAST-STATUS !
    _ATAFC-MAGIC-VALUE _ATAFCI-OWNER @ ATAFC.MAGIC !
    AT-AUTHOR-FEED-CONNECTOR-S-OK _ATAFCI-RETURN ;

\ =====================================================================
\  Binding and request preparation
\ =====================================================================

VARIABLE _ATAFCB-VAULT
VARIABLE _ATAFCB-CONFIG
VARIABLE _ATAFCB-PROFILE
VARIABLE _ATAFCB-SESSION
VARIABLE _ATAFCB-OWNER

: _ATAFCB-CLEAR  ( -- )
    0 _ATAFCB-VAULT ! 0 _ATAFCB-CONFIG ! 0 _ATAFCB-PROFILE !
    0 _ATAFCB-SESSION ! 0 _ATAFCB-OWNER ! ;

: _ATAFCB-RETURN  ( status -- status )
    >R _ATAFCB-CLEAR R> ;

: _ATAFCB-OWNER-ALIAS?  ( address length -- flag )
    _ATAFCB-OWNER @ AT-AUTHOR-FEED-CONNECTOR-SIZE MSPAN-OVERLAP? ;

: AT-AUTHOR-FEED-CONNECTOR-BIND
  ( vault config profile session owner -- status )
    _ATAFCB-OWNER ! _ATAFCB-SESSION ! _ATAFCB-PROFILE !
    _ATAFCB-CONFIG ! _ATAFCB-VAULT !
    _ATAFCB-OWNER @ AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        AT-AUTHOR-FEED-CONNECTOR-S-INVALID _ATAFCB-RETURN EXIT
    THEN
    _ATAFCB-VAULT @ CVAULT-SIZE _ATAFCB-OWNER-ALIAS?
    _ATAFCB-CONFIG @ OAUTH2-CLIENT-CONFIG-SIZE
        _ATAFCB-OWNER-ALIAS? OR
    _ATAFCB-PROFILE @ AT-OAUTH-PROFILE-SIZE
        _ATAFCB-OWNER-ALIAS? OR
    _ATAFCB-SESSION @ OAUTH2-SESSION-SIZE
        _ATAFCB-OWNER-ALIAS? OR IF
        AT-AUTHOR-FEED-CONNECTOR-S-ALIAS _ATAFCB-RETURN EXIT
    THEN
    _ATAFCB-VAULT @ _ATAFCB-CONFIG @ _ATAFCB-PROFILE @
    _ATAFCB-SESSION @ _ATAFCB-OWNER @ ATAFC.EXCHANGE
    AT-XRPC-EXCHANGE-BIND _ATAFC-XRPC>STATUS
    DUP _ATAFCB-OWNER @ ATAFC.LAST-STATUS !
    _ATAFCB-RETURN ;

VARIABLE _ATAFCP-IAT
VARIABLE _ATAFCP-ACTOR-A
VARIABLE _ATAFCP-ACTOR-U
VARIABLE _ATAFCP-LIMIT
VARIABLE _ATAFCP-CURSOR-A
VARIABLE _ATAFCP-CURSOR-U
VARIABLE _ATAFCP-FILTER
VARIABLE _ATAFCP-PINS
VARIABLE _ATAFCP-OWNER
VARIABLE _ATAFCP-PDS
VARIABLE _ATAFCP-STATUS

: _ATAFCP-CLEAR  ( -- )
    0 _ATAFCP-IAT ! 0 _ATAFCP-ACTOR-A ! 0 _ATAFCP-ACTOR-U !
    0 _ATAFCP-LIMIT ! 0 _ATAFCP-CURSOR-A ! 0 _ATAFCP-CURSOR-U !
    0 _ATAFCP-FILTER ! 0 _ATAFCP-PINS ! 0 _ATAFCP-OWNER !
    0 _ATAFCP-PDS ! 0 _ATAFCP-STATUS ! ;

: _ATAFCP-RETURN  ( status -- status )
    >R _ATAFCP-CLEAR R> ;

: _ATAFCP-REPORT  ( status -- status )
    DUP _ATAFCP-OWNER @ ATAFC.LAST-STATUS !
    _ATAFCP-RETURN ;

: _ATAFCP-CLEAR-TEMP  ( owner -- )
    DUP ATAFC.TARGET HTARGET-SIZE 0 FILL
    ATAFC.TARGET-WORK AT-GET-AUTHOR-FEED-WORKSPACE-SIZE 0 FILL ;

: _ATAFCP-SPAN-MUTATED?  ( address length -- flag )
    2DUP _ATAFCP-OWNER @ ATAFC.FLAGS 8 MSPAN-OVERLAP? IF
        2DROP -1 EXIT
    THEN
    2DUP _ATAFCP-OWNER @ ATAFC.TARGET HTARGET-SIZE
        MSPAN-OVERLAP? IF 2DROP -1 EXIT THEN
    2DUP _ATAFCP-OWNER @ ATAFC.TARGET-WORK
        AT-GET-AUTHOR-FEED-WORKSPACE-SIZE
        MSPAN-OVERLAP? IF 2DROP -1 EXIT THEN
    _ATAFCP-OWNER @ ATAFC.EVENT STREAMS-EVENT-SIZE
        MSPAN-OVERLAP? ;

: _ATAFCP-INPUT-STATUS  ( -- status )
    _ATAFCP-ACTOR-A @ _ATAFCP-ACTOR-U @
    _ATAFC-REQUIRED-SPAN-STATUS ?DUP IF EXIT THEN
    _ATAFCP-CURSOR-A @ _ATAFCP-CURSOR-U @
    _ATAFC-OPTIONAL-SPAN-STATUS ?DUP IF EXIT THEN
    _ATAFCP-ACTOR-A @ _ATAFCP-ACTOR-U @
    _ATAFCP-SPAN-MUTATED? IF
        AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT
    THEN
    _ATAFCP-CURSOR-U @ IF
        _ATAFCP-CURSOR-A @ _ATAFCP-CURSOR-U @
        _ATAFCP-SPAN-MUTATED? IF
            AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT
        THEN
    THEN
    AT-AUTHOR-FEED-CONNECTOR-S-OK ;

: AT-AUTHOR-FEED-CONNECTOR-PREPARE
  ( iat actor-a actor-u limit cursor-a cursor-u filter pins owner -- status )
    _ATAFCP-OWNER ! _ATAFCP-PINS ! _ATAFCP-FILTER !
    _ATAFCP-CURSOR-U ! _ATAFCP-CURSOR-A ! _ATAFCP-LIMIT !
    _ATAFCP-ACTOR-U ! _ATAFCP-ACTOR-A ! _ATAFCP-IAT !
    _ATAFCP-OWNER @ AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        AT-AUTHOR-FEED-CONNECTOR-S-INVALID _ATAFCP-RETURN EXIT
    THEN
    _ATAFCP-OWNER @ ATAFC.EXCHANGE AT-XRPC-EXCHANGE-STATE@
    DUP AT-XRPC-EXCHANGE-S-OK <> IF
        2DROP AT-AUTHOR-FEED-CONNECTOR-S-XRPC
        _ATAFCP-REPORT EXIT
    THEN
    DROP AT-XRPC-EXCHANGE-STATE-BOUND <> IF
        AT-AUTHOR-FEED-CONNECTOR-S-STATE _ATAFCP-REPORT EXIT
    THEN
    _ATAFCP-LIMIT @ DUP 1 < SWAP BFM-MAX-ITEMS > OR IF
        AT-AUTHOR-FEED-CONNECTOR-S-CAPACITY _ATAFCP-REPORT EXIT
    THEN
    _ATAFCP-IAT @ 0< IF
        AT-AUTHOR-FEED-CONNECTOR-S-INVALID _ATAFCP-REPORT EXIT
    THEN
    _ATAFCP-INPUT-STATUS ?DUP IF _ATAFCP-REPORT EXIT THEN

    _ATAFC-F-CURRENT _ATAFC-F-PUBLISHED OR
        _ATAFCP-OWNER @ _ATAFC-FLAG-
    _ATAFCP-OWNER @ ATAFC.EVENT STREAMS-EVENT-SIZE 0 FILL
    _ATAFCP-OWNER @ _ATAFCP-CLEAR-TEMP

    _ATAFCP-OWNER @ ATAFC.EXCHANGE ATXE.PROFILE @
    AT-OAUTH-PROFILE-PDS-TARGET@
    DUP AT-OAUTH-PROFILE-S-OK <> IF
        2DROP AT-AUTHOR-FEED-CONNECTOR-S-CONFIG
        _ATAFCP-REPORT EXIT
    THEN
    DROP _ATAFCP-PDS !

    _ATAFCP-PDS @
    _ATAFCP-ACTOR-A @ _ATAFCP-ACTOR-U @ _ATAFCP-LIMIT @
    _ATAFCP-CURSOR-A @ _ATAFCP-CURSOR-U @
    _ATAFCP-FILTER @ _ATAFCP-PINS @
    _ATAFCP-OWNER @ ATAFC.TARGET
    _ATAFCP-OWNER @ ATAFC.TARGET-WORK
    AT-GET-AUTHOR-FEED-TARGET!
    _ATAFC-TARGET>STATUS DUP _ATAFCP-STATUS !
    AT-AUTHOR-FEED-CONNECTOR-S-OK <> IF
        _ATAFCP-OWNER @ _ATAFCP-CLEAR-TEMP
        _ATAFCP-STATUS @ _ATAFCP-REPORT EXIT
    THEN

    _ATAFCP-IAT @ AT-XRPC-METHOD-GET
    _ATAFCP-OWNER @ ATAFC.TARGET
    AT-AUTHOR-FEED-CONNECTOR-APPVIEW-PROXY$
    0 0
    _ATAFCP-OWNER @ ATAFC.EXCHANGE
    AT-XRPC-EXCHANGE-PREPARE _ATAFC-XRPC>STATUS
    _ATAFCP-STATUS !
    _ATAFCP-OWNER @ _ATAFCP-CLEAR-TEMP
    _ATAFCP-STATUS @ _ATAFCP-REPORT ;

\ =====================================================================
\  XIO lifecycle and semantic response admission
\ =====================================================================

VARIABLE _ATAFCX-OP
VARIABLE _ATAFCX-OWNER
VARIABLE _ATAFCX-STEP
VARIABLE _ATAFCX-BODY-A
VARIABLE _ATAFCX-BODY-U

: _ATAFCX-CLEAR  ( -- )
    0 _ATAFCX-OP ! 0 _ATAFCX-OWNER ! 0 _ATAFCX-STEP !
    0 _ATAFCX-BODY-A ! 0 _ATAFCX-BODY-U ! ;

: _ATAFCX-FAIL-INVALID  ( -- step-status )
    _ATAFCX-OP @ ?DUP IF
        DUP XIO-OP-VALID? IF
            AT-AUTHOR-FEED-CONNECTOR-XERR-INVALID SWAP XIOO.ERROR !
        ELSE
            DROP
        THEN
    THEN
    _ATAFCX-CLEAR XIO-STEP-FAILED ;

: AT-AUTHOR-FEED-CONNECTOR-XIO-START
  ( operation owner -- step-status )
    _ATAFCX-OWNER ! _ATAFCX-OP !
    _ATAFCX-OWNER @ AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        _ATAFCX-FAIL-INVALID EXIT
    THEN
    _ATAFC-F-CURRENT _ATAFC-F-PUBLISHED OR
        _ATAFCX-OWNER @ _ATAFC-FLAG-
    _ATAFCX-OP @ _ATAFCX-OWNER @ ATAFC.EXCHANGE
    AT-XRPC-EXCHANGE-XIO-START DUP _ATAFCX-STEP !
    XIO-STEP-PENDING = IF
        AT-AUTHOR-FEED-CONNECTOR-S-OK
    ELSE
        AT-AUTHOR-FEED-CONNECTOR-S-XRPC
    THEN
    _ATAFCX-OWNER @ ATAFC.LAST-STATUS !
    _ATAFCX-STEP @
    _ATAFCX-CLEAR ;

: AT-AUTHOR-FEED-CONNECTOR-XIO-POLL
  ( operation owner -- step-status )
    _ATAFCX-OWNER ! _ATAFCX-OP !
    _ATAFCX-OWNER @ AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        _ATAFCX-FAIL-INVALID EXIT
    THEN
    _ATAFCX-OP @ _ATAFCX-OWNER @ ATAFC.EXCHANGE
    AT-XRPC-EXCHANGE-XIO-POLL DUP _ATAFCX-STEP !
    DUP XIO-STEP-PENDING = IF
        DROP XIO-STEP-PENDING _ATAFCX-CLEAR EXIT
    THEN
    XIO-STEP-SUCCEEDED <> IF
        AT-AUTHOR-FEED-CONNECTOR-S-XRPC
            _ATAFCX-OWNER @ ATAFC.LAST-STATUS !
        XIO-STEP-FAILED _ATAFCX-CLEAR EXIT
    THEN
    0 _ATAFCX-OP @ XIOO.RESULT !

    _ATAFCX-OWNER @ ATAFC.EXCHANGE AT-XRPC-EXCHANGE-BODY@
    DUP AT-XRPC-EXCHANGE-S-OK <> IF
        >R 2DROP R> DROP
        AT-AUTHOR-FEED-CONNECTOR-S-XRPC
            _ATAFCX-OWNER @ ATAFC.LAST-STATUS !
        AT-AUTHOR-FEED-CONNECTOR-XERR-INVALID
            _ATAFCX-OP @ XIOO.ERROR !
        XIO-STEP-FAILED _ATAFCX-CLEAR EXIT
    THEN
    DROP _ATAFCX-BODY-U ! _ATAFCX-BODY-A !
    _ATAFCX-BODY-A @ _ATAFCX-BODY-U @
    _ATAFCX-OWNER @ ATAFC.FEED BFM-DECODE-FEED
    BFM-S-OK <> IF
        _ATAFC-F-CURRENT _ATAFCX-OWNER @ _ATAFC-FLAG-
        AT-AUTHOR-FEED-CONNECTOR-S-DECODE
            _ATAFCX-OWNER @ ATAFC.LAST-STATUS !
        AT-AUTHOR-FEED-CONNECTOR-XERR-DECODE
            _ATAFCX-OP @ XIOO.ERROR !
        XIO-STEP-FAILED _ATAFCX-CLEAR EXIT
    THEN
    _ATAFC-F-FEED _ATAFC-F-CURRENT OR
        _ATAFCX-OWNER @ _ATAFC-FLAG+
    AT-AUTHOR-FEED-CONNECTOR-S-OK
        _ATAFCX-OWNER @ ATAFC.LAST-STATUS !
    _ATAFCX-OWNER @ _ATAFCX-OP @ XIOO.RESULT !
    XIO-STEP-SUCCEEDED _ATAFCX-CLEAR ;

: AT-AUTHOR-FEED-CONNECTOR-XIO-CANCEL
  ( operation owner -- )
    DUP AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF 2DROP EXIT THEN
    ATAFC.EXCHANGE AT-XRPC-EXCHANGE-XIO-CANCEL ;

: AT-AUTHOR-FEED-CONNECTOR-XIO-WIPE
  ( operation owner -- )
    DUP AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF 2DROP EXIT THEN
    >R
    _ATAFC-F-CURRENT _ATAFC-F-PUBLISHED OR R@ _ATAFC-FLAG-
    R@ ATAFC.EVENT STREAMS-EVENT-CLOSE DROP
    R@ _ATAFCP-CLEAR-TEMP
    R@ ATAFC.EXCHANGE AT-XRPC-EXCHANGE-XIO-WIPE
    R> DROP ;

\ =====================================================================
\  Streams publication and inspection
\ =====================================================================

VARIABLE _ATAFCPB-EXPECTED
VARIABLE _ATAFCPB-NOW
VARIABLE _ATAFCPB-FLOW
VARIABLE _ATAFCPB-OWNER
VARIABLE _ATAFCPB-BODY-A
VARIABLE _ATAFCPB-BODY-U
VARIABLE _ATAFCPB-STATUS

: _ATAFCPB-CLEAR  ( -- )
    0 _ATAFCPB-EXPECTED ! 0 _ATAFCPB-NOW !
    0 _ATAFCPB-FLOW ! 0 _ATAFCPB-OWNER !
    0 _ATAFCPB-BODY-A ! 0 _ATAFCPB-BODY-U ! 0 _ATAFCPB-STATUS ! ;

: _ATAFCPB-RETURN  ( status -- status )
    >R _ATAFCPB-CLEAR R> ;

: _ATAFCPB-REPORT  ( status -- status )
    DUP _ATAFCPB-OWNER @ ATAFC.LAST-STATUS !
    _ATAFCPB-RETURN ;

: _ATAFCPB-CLOSE-EVENT  ( owner -- )
    ATAFC.EVENT STREAMS-EVENT-CLOSE DROP ;

: _ATAFCPB-GEOMETRY-STATUS  ( -- status )
    _ATAFCPB-FLOW @ STREAMS-FLOW-SIZE
    _ATAFCPB-OWNER @ AT-AUTHOR-FEED-CONNECTOR-SIZE
    MSPAN-OVERLAP? IF AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT THEN
    _ATAFCPB-BODY-A @ _ATAFCPB-BODY-U @
    _ATAFCPB-FLOW @ STREAMS-FLOW-SIZE
    MSPAN-OVERLAP? IF AT-AUTHOR-FEED-CONNECTOR-S-ALIAS EXIT THEN
    AT-AUTHOR-FEED-CONNECTOR-S-OK ;

: _ATAFCPB-METADATA  ( owner -- status )
    >R
    R@ ATAFC.EVENT STREAMS-EVENT-INIT
    STREAMS-FLOW-S-OK <> IF
        R> DROP AT-AUTHOR-FEED-CONNECTOR-S-INTERNAL EXIT
    THEN
    _ATAFCPB-BODY-A @ _ATAFCPB-BODY-U @
        R@ ATAFC.EVENT SEVT.EVENT-ID SHA3-256-HASH
    R@ ATAFC.EVENT SEVT.EVENT-ID
        R@ ATAFC.EVENT SEVT.CORRELATION-ID RID-COPY
    R@ ATAFC.EVENT SEVT.EVENT-ID
        R@ ATAFC.EVENT SEVT.IDEMPOTENCY-ID RID-COPY
    STREAMS-MEDIA-BSKY-FEED-JSON R@ ATAFC.EVENT SEVT.MEDIA !
    R@ ATAFC.SEQUENCE @ 0x7FFFFFFFFFFFFFFF = IF
        R> DROP AT-AUTHOR-FEED-CONNECTOR-S-CAPACITY EXIT
    THEN
    R@ ATAFC.SEQUENCE @ 1+
        R@ ATAFC.EVENT SEVT.SEQUENCE !
    _ATAFCPB-NOW @ R@ ATAFC.EVENT SEVT.RECEIVED-MS !
    _ATAFCPB-BODY-A @ _ATAFCPB-BODY-U @
        R@ ATAFC.EVENT STREAMS-EVENT-BORROW
    _ATAFC-FLOW>STATUS
    R> DROP ;

: AT-AUTHOR-FEED-CONNECTOR-PUBLISH
  ( expected-flow-revision now-ms flow owner -- status )
    _ATAFCPB-OWNER ! _ATAFCPB-FLOW !
    _ATAFCPB-NOW ! _ATAFCPB-EXPECTED !
    _ATAFCPB-OWNER @ AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        AT-AUTHOR-FEED-CONNECTOR-S-INVALID _ATAFCPB-RETURN EXIT
    THEN
    _ATAFCPB-NOW @ 0< IF
        AT-AUTHOR-FEED-CONNECTOR-S-INVALID _ATAFCPB-REPORT EXIT
    THEN
    _ATAFC-F-CURRENT _ATAFCPB-OWNER @ _ATAFC-FLAG? 0= IF
        AT-AUTHOR-FEED-CONNECTOR-S-STATE _ATAFCPB-REPORT EXIT
    THEN
    _ATAFC-F-PUBLISHED _ATAFCPB-OWNER @ _ATAFC-FLAG? IF
        AT-AUTHOR-FEED-CONNECTOR-S-STATE _ATAFCPB-REPORT EXIT
    THEN
    _ATAFCPB-FLOW @ STREAMS-FLOW-VALID? 0= IF
        AT-AUTHOR-FEED-CONNECTOR-S-INVALID _ATAFCPB-REPORT EXIT
    THEN
    _ATAFCPB-OWNER @ ATAFC.EXCHANGE AT-XRPC-EXCHANGE-BODY@
    DUP AT-XRPC-EXCHANGE-S-OK <> IF
        >R 2DROP R> DROP
        AT-AUTHOR-FEED-CONNECTOR-S-XRPC _ATAFCPB-REPORT EXIT
    THEN
    DROP _ATAFCPB-BODY-U ! _ATAFCPB-BODY-A !
    _ATAFCPB-GEOMETRY-STATUS ?DUP IF _ATAFCPB-REPORT EXIT THEN

    _ATAFCPB-OWNER @ _ATAFCPB-METADATA DUP _ATAFCPB-STATUS !
    AT-AUTHOR-FEED-CONNECTOR-S-OK <> IF
        _ATAFCPB-OWNER @ _ATAFCPB-CLOSE-EVENT
        _ATAFCPB-STATUS @ _ATAFCPB-REPORT EXIT
    THEN
    _ATAFCPB-OWNER @ ATAFC.CONNECTOR
    _ATAFCPB-OWNER @ ATAFC.EVENT
    _ATAFCPB-FLOW @ STREAMS-FLOW-SEAL-INGRESS
    _ATAFC-FLOW>STATUS DUP _ATAFCPB-STATUS !
    AT-AUTHOR-FEED-CONNECTOR-S-OK <> IF
        _ATAFCPB-OWNER @ _ATAFCPB-CLOSE-EVENT
        _ATAFCPB-STATUS @ _ATAFCPB-REPORT EXIT
    THEN
    _ATAFCPB-OWNER @ ATAFC.EVENT
    _ATAFCPB-EXPECTED @ _ATAFCPB-NOW @
    _ATAFCPB-FLOW @ STREAMS-FLOW-ADMIT
    _ATAFC-FLOW>STATUS DUP _ATAFCPB-STATUS !
    AT-AUTHOR-FEED-CONNECTOR-S-OK <> IF
        _ATAFCPB-OWNER @ _ATAFCPB-CLOSE-EVENT
        _ATAFCPB-STATUS @ _ATAFCPB-REPORT EXIT
    THEN
    1 _ATAFCPB-OWNER @ ATAFC.SEQUENCE +!
    _ATAFC-F-PUBLISHED _ATAFCPB-OWNER @ _ATAFC-FLAG+
    AT-AUTHOR-FEED-CONNECTOR-S-OK _ATAFCPB-REPORT ;

: AT-AUTHOR-FEED-CONNECTOR-CONNECTOR@
  ( owner -- connector status )
    DUP AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        DROP 0 AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    ATAFC.CONNECTOR AT-AUTHOR-FEED-CONNECTOR-S-OK ;

: AT-AUTHOR-FEED-CONNECTOR-FEED@
  ( owner -- feed status )
    DUP AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        DROP 0 AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    DUP _ATAFC-F-FEED SWAP _ATAFC-FLAG? 0= IF
        DROP 0 AT-AUTHOR-FEED-CONNECTOR-S-STATE EXIT
    THEN
    ATAFC.FEED AT-AUTHOR-FEED-CONNECTOR-S-OK ;

: AT-AUTHOR-FEED-CONNECTOR-BODY@
  ( owner -- body-a body-u status )
    DUP AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        DROP 0 0 AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    DUP _ATAFC-F-CURRENT SWAP _ATAFC-FLAG? 0= IF
        DROP 0 0 AT-AUTHOR-FEED-CONNECTOR-S-STATE EXIT
    THEN
    ATAFC.EXCHANGE AT-XRPC-EXCHANGE-BODY@
    DUP AT-XRPC-EXCHANGE-S-OK = IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-OK
    ELSE
        >R 2DROP R> DROP
        0 0 AT-AUTHOR-FEED-CONNECTOR-S-XRPC
    THEN ;

: AT-AUTHOR-FEED-CONNECTOR-EVENT@
  ( owner -- event status )
    DUP AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        DROP 0 AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    DUP _ATAFC-F-PUBLISHED SWAP _ATAFC-FLAG? 0= IF
        DROP 0 AT-AUTHOR-FEED-CONNECTOR-S-STATE EXIT
    THEN
    ATAFC.EVENT AT-AUTHOR-FEED-CONNECTOR-S-OK ;

: AT-AUTHOR-FEED-CONNECTOR-EXCHANGE@
  ( owner -- exchange status )
    DUP AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        DROP 0 AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    ATAFC.EXCHANGE AT-AUTHOR-FEED-CONNECTOR-S-OK ;

: AT-AUTHOR-FEED-CONNECTOR-PORT  ( owner -- port | 0 )
    DUP AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF DROP 0 EXIT THEN
    ATAFC.EXCHANGE AT-XRPC-EXCHANGE-PORT ;

: AT-AUTHOR-FEED-CONNECTOR-LAST-STATUS@
  ( owner -- status )
    DUP AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    ATAFC.LAST-STATUS @ ;

\ =====================================================================
\  Explicit authentication teardown
\ =====================================================================

: AT-AUTHOR-FEED-CONNECTOR-UNBIND  ( owner -- status )
    DUP AT-AUTHOR-FEED-CONNECTOR-VALID? 0= IF
        DROP AT-AUTHOR-FEED-CONNECTOR-S-INVALID EXIT
    THEN
    >R
    R@ ATAFC.EXCHANGE AT-XRPC-EXCHANGE-UNBIND
    _ATAFC-XRPC>STATUS DUP
    AT-AUTHOR-FEED-CONNECTOR-S-OK <> IF
        DUP R@ ATAFC.LAST-STATUS !
        R> DROP EXIT
    THEN
    DROP
    R@ ATAFC.EVENT STREAMS-EVENT-CLOSE DROP
    R@ ATAFC.EVENT STREAMS-EVENT-SIZE 0 FILL
    R@ ATAFC.FEED BFM-FEED-INIT
    R@ _ATAFCP-CLEAR-TEMP
    0 R@ ATAFC.FLAGS !
    AT-AUTHOR-FEED-CONNECTOR-S-OK R@ ATAFC.LAST-STATUS !
    R> DROP AT-AUTHOR-FEED-CONNECTOR-S-OK ;

\ =====================================================================
\  Compile-time geometry assertions
\ =====================================================================

: _ATAFC-GEOMETRY-ABORT  ( -- )
    ." AT author-feed connector geometry mismatch" CR ABORT ;

1 CELLS 8 <> [IF]
    _ATAFC-GEOMETRY-ABORT
[THEN]

_ATAFC-CONNECTOR-OFF 7 AND
_ATAFC-EXCHANGE-OFF 7 AND OR
_ATAFC-TARGET-OFF 7 AND OR
_ATAFC-TARGET-WORK-OFF 7 AND OR
_ATAFC-FEED-OFF 7 AND OR
_ATAFC-EVENT-OFF 7 AND OR [IF]
    _ATAFC-GEOMETRY-ABORT
[THEN]

_ATAFC-EVENT-OFF STREAMS-EVENT-SIZE +
AT-AUTHOR-FEED-CONNECTOR-SIZE <> [IF]
    _ATAFC-GEOMETRY-ABORT
[THEN]
