\ =====================================================================
\  migration.f - cold legacy-to-repository Streams authority migration
\ =====================================================================
\  This module performs the one supported L13 authority transition:
\
\      legacy snapshots -> hidden repository staging -> verified first root
\
\  It never dual-writes, saves, clears, or falls back to either legacy
\  snapshot.  A pre-existing valid repository root wins before legacy is
\  inspected.  Legacy ACCEPTED attempts are terminalized as INDETERMINATE
\  only in this caller-owned work copy; the exact checked-record fingerprint
\  and the checked semantic payload remain unchanged in the evidence area.
\
\  The caller supplies initialized source/observation stores, an initialized
\  repository and bound repository work, a nonzero authority RID, and one
\  migration work span.  All migration scratch and callback state is inside
\  that work span.  Work is fixed by the legacy maxima: sixteen sources,
\  sixteen retained attempt heads, forty-eight observation revisions, and
\  sixty-four native heads.
\
\  Public API:
\    STREAMS-MIGRATION-WORK-INIT
\      ( work -- status )
\    STREAMS-MIGRATION-WORK-VALID?
\      ( work -- flag )
\    STREAMS-MIGRATION-RUN
\      ( authority-id source-store observation-store repository
\        repository-work migration-work -- status )
\
\  OK means this call published and reopened the verified first root.
\  ALREADY means LOAD found an existing valid repository authority before
\  any legacy read.  Every other status leaves authority selection to a
\  subsequent repository LOAD; callers must never infer a legacy fallback
\  from a failed or uncertain commit attempt.
\ =====================================================================

PROVIDED akashic-tui-streams-migration

REQUIRE source-store.f
REQUIRE observation-store.f
REQUIRE repository.f

\ ---------------------------------------------------------------------
\ Status domain
\ ---------------------------------------------------------------------

STREAMS-REPOSITORY-S-OK          CONSTANT STREAMS-MIGRATION-S-OK
STREAMS-REPOSITORY-S-ABSENT      CONSTANT STREAMS-MIGRATION-S-ABSENT
STREAMS-REPOSITORY-S-INVALID     CONSTANT STREAMS-MIGRATION-S-INVALID
STREAMS-REPOSITORY-S-CAPACITY    CONSTANT STREAMS-MIGRATION-S-CAPACITY
STREAMS-REPOSITORY-S-IO          CONSTANT STREAMS-MIGRATION-S-IO
STREAMS-REPOSITORY-S-CORRUPT     CONSTANT STREAMS-MIGRATION-S-CORRUPT
STREAMS-REPOSITORY-S-BUSY        CONSTANT STREAMS-MIGRATION-S-BUSY
STREAMS-REPOSITORY-S-CONFLICT    CONSTANT STREAMS-MIGRATION-S-CONFLICT
STREAMS-REPOSITORY-S-UNCERTAIN   CONSTANT STREAMS-MIGRATION-S-UNCERTAIN
STREAMS-REPOSITORY-S-NOT-FOUND   CONSTANT STREAMS-MIGRATION-S-NOT-FOUND
STREAMS-REPOSITORY-S-FAULT       CONSTANT STREAMS-MIGRATION-S-FAULT
STREAMS-REPOSITORY-S-UNSUPPORTED CONSTANT STREAMS-MIGRATION-S-UNSUPPORTED

12 CONSTANT STREAMS-MIGRATION-S-ALREADY
13 CONSTANT STREAMS-MIGRATION-S-VERIFY
14 CONSTANT STREAMS-MIGRATION-S-RECOVERY

: _SMIG-STATUS?  ( status -- flag )
    DUP STREAMS-MIGRATION-S-OK >=
    SWAP STREAMS-MIGRATION-S-RECOVERY <= AND ;

\ ---------------------------------------------------------------------
\ Caller-owned work
\ ---------------------------------------------------------------------

0x5354524D4D494731 CONSTANT _SMIG-WORK-MAGIC  \ "STRMMIG1"

  0 CONSTANT _SMW-MAGIC
  8 CONSTANT _SMW-SELF
 16 CONSTANT _SMW-BUSY
 24 CONSTANT _SMW-STATUS
 32 CONSTANT _SMW-STAGE-STATUS
 40 CONSTANT _SMW-OWNER-STATUS
 48 CONSTANT _SMW-SOURCE-STORE
 56 CONSTANT _SMW-OBSERVATION-STORE
 64 CONSTANT _SMW-REPOSITORY
 72 CONSTANT _SMW-REPOSITORY-WORK
 80 CONSTANT _SMW-ADAPTER
 88 CONSTANT _SMW-ADAPTER-WORK
 96 CONSTANT _SMW-SOURCE-PRESENT
104 CONSTANT _SMW-OBSERVATION-PRESENT
112 CONSTANT _SMW-SOURCE-RECORD-U
120 CONSTANT _SMW-OBSERVATION-RECORD-U
128 CONSTANT _SMW-SOURCE-GENERATION
136 CONSTANT _SMW-OBSERVATION-GENERATION
144 CONSTANT _SMW-RECOVERED-COUNT
152 CONSTANT _SMW-PROVENANCE
160 CONSTANT _SMW-SOURCE-COMPLETENESS
168 CONSTANT _SMW-OBSERVATION-COMPLETENESS
176 CONSTANT _SMW-SOURCE-COUNT
184 CONSTANT _SMW-ATTEMPT-COUNT
192 CONSTANT _SMW-OBSERVATION-COUNT
200 CONSTANT _SMW-NATIVE-COUNT
208 CONSTANT _SMW-COMMIT-ATTEMPTED
216 CONSTANT _SMW-FLIP-CONFIRMED
224 CONSTANT _SMW-CALLBACK-A
232 CONSTANT _SMW-CALLBACK-U
240 CONSTANT _SMW-CALLBACK-OFFSET
248 CONSTANT _SMW-EXPECTED-U
256 CONSTANT _SMW-TEMP
264 CONSTANT _SMW-TEMP2

320 CONSTANT _SMW-AUTHORITY-ID
_SMW-AUTHORITY-ID RID-SIZE + CONSTANT _SMW-SOURCE-DIGEST
_SMW-SOURCE-DIGEST SHA3-256-LEN + CONSTANT _SMW-OBSERVATION-DIGEST
_SMW-OBSERVATION-DIGEST SHA3-256-LEN + CONSTANT _SMW-TEMP-DIGEST
_SMW-TEMP-DIGEST SHA3-256-LEN + CONSTANT _SMW-CANDIDATE
_SMW-CANDIDATE OCHK-CANDIDATE-SIZE + CONSTANT _SMW-KEY
_SMW-KEY STREAMS-PI-KEY-MAX + CONSTANT _SMW-REF
_SMW-REF PERSIST-REF-SIZE + CONSTANT _SMW-BLOB
_SMW-BLOB PBLOB-SIZE + CONSTANT _SMW-RECORD
_SMW-RECORD STREAMS-PERSISTENCE-RECORD-MAX + CONSTANT _SMW-READBACK
_SMW-READBACK STREAMS-PERSISTENCE-RECORD-MAX +
    CONSTANT _SMW-SOURCE-EVIDENCE
_SMW-SOURCE-EVIDENCE STREAMS-SOURCE-REGISTRY-SIZE +
    CONSTANT _SMW-OBSERVATION-EVIDENCE
_SMW-OBSERVATION-EVIDENCE STREAMS-OBSERVATION-CHECKPOINT-SIZE +
    CONSTANT _SMW-CHECKPOINT
_SMW-CHECKPOINT STREAMS-OBSERVATION-CHECKPOINT-SIZE +
    CONSTANT STREAMS-MIGRATION-WORK-SIZE

: _SMW.MAGIC                    ( work -- a ) _SMW-MAGIC + ;
: _SMW.SELF                     ( work -- a ) _SMW-SELF + ;
: _SMW.BUSY                     ( work -- a ) _SMW-BUSY + ;
: _SMW.STATUS                   ( work -- a ) _SMW-STATUS + ;
: _SMW.STAGE-STATUS             ( work -- a ) _SMW-STAGE-STATUS + ;
: _SMW.OWNER-STATUS             ( work -- a ) _SMW-OWNER-STATUS + ;
: _SMW.SOURCE-STORE             ( work -- a ) _SMW-SOURCE-STORE + ;
: _SMW.OBSERVATION-STORE        ( work -- a ) _SMW-OBSERVATION-STORE + ;
: _SMW.REPOSITORY               ( work -- a ) _SMW-REPOSITORY + ;
: _SMW.REPOSITORY-WORK          ( work -- a ) _SMW-REPOSITORY-WORK + ;
: _SMW.ADAPTER                  ( work -- a ) _SMW-ADAPTER + ;
: _SMW.ADAPTER-WORK             ( work -- a ) _SMW-ADAPTER-WORK + ;
: _SMW.SOURCE-PRESENT           ( work -- a ) _SMW-SOURCE-PRESENT + ;
: _SMW.OBSERVATION-PRESENT      ( work -- a ) _SMW-OBSERVATION-PRESENT + ;
: _SMW.SOURCE-RECORD-U          ( work -- a ) _SMW-SOURCE-RECORD-U + ;
: _SMW.OBSERVATION-RECORD-U     ( work -- a ) _SMW-OBSERVATION-RECORD-U + ;
: _SMW.SOURCE-GENERATION        ( work -- a ) _SMW-SOURCE-GENERATION + ;
: _SMW.OBSERVATION-GENERATION   ( work -- a )
    _SMW-OBSERVATION-GENERATION + ;
: _SMW.RECOVERED-COUNT          ( work -- a ) _SMW-RECOVERED-COUNT + ;
: _SMW.PROVENANCE               ( work -- a ) _SMW-PROVENANCE + ;
: _SMW.SOURCE-COMPLETENESS      ( work -- a )
    _SMW-SOURCE-COMPLETENESS + ;
: _SMW.OBSERVATION-COMPLETENESS ( work -- a )
    _SMW-OBSERVATION-COMPLETENESS + ;
: _SMW.SOURCE-COUNT             ( work -- a ) _SMW-SOURCE-COUNT + ;
: _SMW.ATTEMPT-COUNT            ( work -- a ) _SMW-ATTEMPT-COUNT + ;
: _SMW.OBSERVATION-COUNT        ( work -- a ) _SMW-OBSERVATION-COUNT + ;
: _SMW.NATIVE-COUNT             ( work -- a ) _SMW-NATIVE-COUNT + ;
: _SMW.COMMIT-ATTEMPTED         ( work -- a ) _SMW-COMMIT-ATTEMPTED + ;
: _SMW.FLIP-CONFIRMED           ( work -- a ) _SMW-FLIP-CONFIRMED + ;
: _SMW.CALLBACK-A               ( work -- a ) _SMW-CALLBACK-A + ;
: _SMW.CALLBACK-U               ( work -- a ) _SMW-CALLBACK-U + ;
: _SMW.CALLBACK-OFFSET          ( work -- a ) _SMW-CALLBACK-OFFSET + ;
: _SMW.EXPECTED-U               ( work -- a ) _SMW-EXPECTED-U + ;
: _SMW.TEMP                     ( work -- a ) _SMW-TEMP + ;
: _SMW.TEMP2                    ( work -- a ) _SMW-TEMP2 + ;
: _SMW.AUTHORITY-ID             ( work -- rid ) _SMW-AUTHORITY-ID + ;
: _SMW.SOURCE-DIGEST            ( work -- digest ) _SMW-SOURCE-DIGEST + ;
: _SMW.OBSERVATION-DIGEST       ( work -- digest )
    _SMW-OBSERVATION-DIGEST + ;
: _SMW.TEMP-DIGEST              ( work -- digest ) _SMW-TEMP-DIGEST + ;
: _SMW.CANDIDATE                ( work -- candidate ) _SMW-CANDIDATE + ;
: _SMW.KEY                      ( work -- key ) _SMW-KEY + ;
: _SMW.REF                      ( work -- ref ) _SMW-REF + ;
: _SMW.BLOB                     ( work -- blob ) _SMW-BLOB + ;
: _SMW.RECORD                   ( work -- record ) _SMW-RECORD + ;
: _SMW.READBACK                 ( work -- record ) _SMW-READBACK + ;
: _SMW.SOURCE-EVIDENCE          ( work -- record )
    _SMW-SOURCE-EVIDENCE + ;
: _SMW.OBSERVATION-EVIDENCE     ( work -- record )
    _SMW-OBSERVATION-EVIDENCE + ;
: _SMW.CHECKPOINT               ( work -- checkpoint ) _SMW-CHECKPOINT + ;

: _SMW-REGISTRY  ( work -- registry )
    _SMW.SOURCE-EVIDENCE ;

: _SMW-EVIDENCE-CHECKPOINT  ( work -- checkpoint )
    _SMW.OBSERVATION-EVIDENCE ;

: _SMIG-BOOL?  ( value -- flag )
    DUP 0= SWAP -1 = OR ;

: STREAMS-MIGRATION-WORK-VALID?  ( work -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP STREAMS-MIGRATION-WORK-SIZE
        MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP _SMW.MAGIC @ _SMIG-WORK-MAGIC <> IF DROP 0 EXIT THEN
    DUP _SMW.SELF @ OVER <> IF DROP 0 EXIT THEN
    DUP _SMW.BUSY @ _SMIG-BOOL? 0= IF DROP 0 EXIT THEN
    _SMW.STATUS @ _SMIG-STATUS? ;

: STREAMS-MIGRATION-WORK-INIT  ( work -- status )
    DUP 0= IF DROP STREAMS-MIGRATION-S-INVALID EXIT THEN
    DUP STREAMS-MIGRATION-WORK-SIZE
        MSPAN-NONWRAPPING? 0= IF DROP STREAMS-MIGRATION-S-INVALID EXIT THEN
    DUP STREAMS-MIGRATION-WORK-SIZE 0 FILL
    _SMIG-WORK-MAGIC OVER _SMW.MAGIC !
    DUP OVER _SMW.SELF !
    STREAMS-MIGRATION-S-OK OVER _SMW.STATUS !
    DUP STREAMS-MIGRATION-WORK-VALID? 0= IF
        STREAMS-MIGRATION-WORK-SIZE 0 FILL
        STREAMS-MIGRATION-S-CORRUPT
    ELSE
        DROP STREAMS-MIGRATION-S-OK
    THEN ;

: STREAMS-MIGRATION-STATUS@  ( work -- status )
    DUP STREAMS-MIGRATION-WORK-VALID?
    IF _SMW.STATUS @ ELSE DROP STREAMS-MIGRATION-S-INVALID THEN ;

: STREAMS-MIGRATION-RECOVERED-ATTEMPT-COUNT@  ( work -- count|-1 )
    DUP STREAMS-MIGRATION-WORK-VALID?
    IF _SMW.RECOVERED-COUNT @ ELSE DROP -1 THEN ;

: STREAMS-MIGRATION-COMMIT-ATTEMPTED?  ( work -- flag )
    DUP STREAMS-MIGRATION-WORK-VALID?
    IF _SMW.COMMIT-ATTEMPTED @ 0<> ELSE DROP 0 THEN ;

: STREAMS-MIGRATION-FLIP-CONFIRMED?  ( work -- flag )
    DUP STREAMS-MIGRATION-WORK-VALID?
    IF _SMW.FLIP-CONFIRMED @ 0<> ELSE DROP 0 THEN ;

\ ---------------------------------------------------------------------
\ Pure/common helpers
\ ---------------------------------------------------------------------

: _SMIG-DROP3  ( x1 x2 x3 -- ) 2DROP DROP ;
: _SMIG-DROP4  ( x1 x2 x3 x4 -- ) 2DROP 2DROP ;
: _SMIG-DROP5  ( x1 x2 x3 x4 x5 -- ) 2DROP 2DROP DROP ;
: _SMIG-DROP6  ( x1 x2 x3 x4 x5 x6 -- ) 2DROP 2DROP 2DROP ;

: _SMIG-BYTES=  ( a b u -- flag )
    DUP 0< IF DROP 2DROP 0 EXIT THEN
    DUP 0= IF DROP 2DROP -1 EXIT THEN
    2 PICK 0= 2 PICK 0= OR IF DROP 2DROP 0 EXIT THEN
    2 PICK OVER MSPAN-NONWRAPPING? 0= IF
        DROP 2DROP 0 EXIT
    THEN
    OVER OVER MSPAN-NONWRAPPING? 0= IF
        DROP 2DROP 0 EXIT
    THEN
    0 ?DO
        2DUP I + C@ SWAP I + C@ <> IF
            2DROP 0 UNLOOP EXIT
        THEN
    LOOP
    2DROP -1 ;

: _SMIG-ZERO?  ( a u -- flag )
    DUP 0< IF 2DROP 0 EXIT THEN
    DUP 0= IF 2DROP -1 EXIT THEN
    OVER 0= IF 2DROP 0 EXIT THEN
    2DUP MSPAN-NONWRAPPING? 0= IF 2DROP 0 EXIT THEN
    0 ?DO
        DUP I + C@ IF DROP 0 UNLOOP EXIT THEN
    LOOP
    DROP -1 ;

: _SMIG-$=  ( a1 u1 a2 u2 -- flag )
    2 PICK OVER <> IF _SMIG-DROP4 0 EXIT THEN
    DROP SWAP _SMIG-BYTES= ;

: _SMIG-SPANS-DISJOINT?  ( a u b v -- flag )
    2OVER MSPAN-NONWRAPPING? 0= IF _SMIG-DROP4 0 EXIT THEN
    2DUP MSPAN-NONWRAPPING? 0= IF _SMIG-DROP4 0 EXIT THEN
    MSPAN-OVERLAP? 0= ;

: _SMIG-VIEW!  ( a u address-cell length-cell -- )
    >R ROT SWAP ! R> ! ;

: _SMIG-SOURCE>STATUS  ( source-store-status -- migration-status )
    CASE
        SSSTORE-S-OK OF STREAMS-MIGRATION-S-OK ENDOF
        SSSTORE-S-ABSENT OF STREAMS-MIGRATION-S-ABSENT ENDOF
        SSSTORE-S-CORRUPT OF STREAMS-MIGRATION-S-CORRUPT ENDOF
        SSSTORE-S-UNSUPPORTED OF STREAMS-MIGRATION-S-UNSUPPORTED ENDOF
        SSSTORE-S-INVALID OF STREAMS-MIGRATION-S-INVALID ENDOF
        SSSTORE-S-CAPACITY OF STREAMS-MIGRATION-S-CAPACITY ENDOF
        SSSTORE-S-IO OF STREAMS-MIGRATION-S-IO ENDOF
        SSSTORE-S-RECOVERY OF STREAMS-MIGRATION-S-RECOVERY ENDOF
        SSSTORE-S-BUSY OF STREAMS-MIGRATION-S-BUSY ENDOF
        SSSTORE-S-CONFLICT OF STREAMS-MIGRATION-S-CONFLICT ENDOF
        STREAMS-MIGRATION-S-FAULT SWAP
    ENDCASE ;

: _SMIG-OBSERVATION>STATUS  ( observation-store-status -- migration-status )
    CASE
        OSTORE-S-OK OF STREAMS-MIGRATION-S-OK ENDOF
        OSTORE-S-ABSENT OF STREAMS-MIGRATION-S-ABSENT ENDOF
        OSTORE-S-CORRUPT OF STREAMS-MIGRATION-S-CORRUPT ENDOF
        OSTORE-S-UNSUPPORTED OF STREAMS-MIGRATION-S-UNSUPPORTED ENDOF
        OSTORE-S-INVALID OF STREAMS-MIGRATION-S-INVALID ENDOF
        OSTORE-S-CAPACITY OF STREAMS-MIGRATION-S-CAPACITY ENDOF
        OSTORE-S-IO OF STREAMS-MIGRATION-S-IO ENDOF
        OSTORE-S-RECOVERY OF STREAMS-MIGRATION-S-RECOVERY ENDOF
        OSTORE-S-BUSY OF STREAMS-MIGRATION-S-BUSY ENDOF
        OSTORE-S-CONFLICT OF STREAMS-MIGRATION-S-CONFLICT ENDOF
        STREAMS-MIGRATION-S-FAULT SWAP
    ENDCASE ;

: _SMIG-SPREC>STATUS  ( semantic-record-status -- migration-status )
    CASE
        SPREC-S-OK OF STREAMS-MIGRATION-S-OK ENDOF
        SPREC-S-CAPACITY OF STREAMS-MIGRATION-S-CAPACITY ENDOF
        SPREC-S-INVALID OF STREAMS-MIGRATION-S-CORRUPT ENDOF
        SPREC-S-CORRUPT OF STREAMS-MIGRATION-S-CORRUPT ENDOF
        STREAMS-MIGRATION-S-FAULT SWAP
    ENDCASE ;

: _SMIG-KEY>STATUS  ( key-status -- migration-status )
    STREAMS-PI-S-OK =
    IF STREAMS-MIGRATION-S-OK ELSE STREAMS-MIGRATION-S-CORRUPT THEN ;

: _SMIG-READBACK>STATUS  ( adapter-status -- migration-status )
    DUP STREAMS-PA-S-NOT-FOUND =
    OVER STREAMS-PA-S-CORRUPT = OR IF
        DROP STREAMS-MIGRATION-S-VERIFY
    THEN ;

\ ---------------------------------------------------------------------
\ Run preflight and exact legacy evidence
\ ---------------------------------------------------------------------

: _SMIG-RUN-ARGS?
  ( authority-id source-store observation-store repository repository-work migration-work -- flag )
    >R
    R@ STREAMS-MIGRATION-WORK-VALID? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    R@ _SMW.BUSY @ IF _SMIG-DROP5 R> DROP 0 EXIT THEN
    2DUP STREAMS-REPOSITORY-WORK-BOUND? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    3 PICK STREAMS-SOURCE-STORE-VALID? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    2 PICK STREAMS-OBSERVATION-STORE-VALID? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    4 PICK RID-PRESENT? 0= IF _SMIG-DROP5 R> DROP 0 EXIT THEN

    R@ STREAMS-MIGRATION-WORK-SIZE
        3 PICK 3 PICK STREAMS-REPOSITORY-SPAN-DISJOINT? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    3 PICK STREAMS-SOURCE-STORE-SIZE
        3 PICK 3 PICK STREAMS-REPOSITORY-SPAN-DISJOINT? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    2 PICK STREAMS-OBSERVATION-STORE-SIZE
        3 PICK 3 PICK STREAMS-REPOSITORY-SPAN-DISJOINT? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    4 PICK RID-SIZE
        3 PICK 3 PICK STREAMS-REPOSITORY-SPAN-DISJOINT? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN

    R@ STREAMS-MIGRATION-WORK-SIZE
        5 PICK STREAMS-SOURCE-STORE-SIZE
        _SMIG-SPANS-DISJOINT? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    R@ STREAMS-MIGRATION-WORK-SIZE
        4 PICK STREAMS-OBSERVATION-STORE-SIZE
        _SMIG-SPANS-DISJOINT? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    3 PICK STREAMS-SOURCE-STORE-SIZE
        4 PICK STREAMS-OBSERVATION-STORE-SIZE
        _SMIG-SPANS-DISJOINT? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    4 PICK RID-SIZE R@ STREAMS-MIGRATION-WORK-SIZE
        _SMIG-SPANS-DISJOINT? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    4 PICK RID-SIZE 5 PICK STREAMS-SOURCE-STORE-SIZE
        _SMIG-SPANS-DISJOINT? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    4 PICK RID-SIZE 4 PICK STREAMS-OBSERVATION-STORE-SIZE
        _SMIG-SPANS-DISJOINT? 0= IF
        _SMIG-DROP5 R> DROP 0 EXIT
    THEN
    _SMIG-DROP5 R> DROP -1 ;

: _SMIG-RUN-RESET  ( work -- )
    DUP _SMW.STAGE-STATUS
        STREAMS-MIGRATION-WORK-SIZE _SMW-STAGE-STATUS - 0 FILL
    STREAMS-MIGRATION-S-OK OVER _SMW.STATUS !
    DROP ;

: _SMIG-LOAD-SOURCE-EVIDENCE  ( work -- status )
    >R
    R@ _SMW.SOURCE-EVIDENCE STREAMS-SOURCE-REGISTRY-SIZE
    R@ _SMW.SOURCE-DIGEST R@ _SMW.SOURCE-STORE @
        STREAMS-SOURCE-STORE-LOAD-EVIDENCE
    DUP SSSTORE-S-OK = IF
        DROP
        DUP 0< IF 2DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT THEN
        DUP R@ _SMW.SOURCE-GENERATION !
        DROP
        DUP R@ _SMW.SOURCE-RECORD-U !
        STREAMS-SOURCE-STORE-RECORD-MAX <> IF
            R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
        THEN
        R@ _SMW.SOURCE-DIGEST RID-PRESENT? 0= IF
            R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
        THEN
        R@ _SMW-REGISTRY STREAMS-SOURCE-REGISTRY-VALID? 0= IF
            R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
        THEN
        R@ _SMW-REGISTRY SSREG.GENERATION @
            R@ _SMW.SOURCE-GENERATION @ <> IF
            R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
        THEN
        -1 R@ _SMW.SOURCE-PRESENT !
        R> DROP STREAMS-MIGRATION-S-OK EXIT
    THEN
    DUP SSSTORE-S-ABSENT = IF
        DROP
        OR IF R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT THEN
        R@ _SMW.SOURCE-DIGEST SHA3-256-LEN _SMIG-ZERO? 0= IF
            R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
        THEN
        R> DROP STREAMS-MIGRATION-S-OK EXIT
    THEN
    NIP NIP _SMIG-SOURCE>STATUS R> DROP ;

: _SMIG-LOAD-OBSERVATION-EVIDENCE  ( work -- status )
    >R
    R@ _SMW.OBSERVATION-EVIDENCE
        STREAMS-OBSERVATION-CHECKPOINT-SIZE
    R@ _SMW.OBSERVATION-DIGEST R@ _SMW.OBSERVATION-STORE @
        STREAMS-OBSERVATION-STORE-LOAD-EVIDENCE
    DUP OSTORE-S-OK = IF
        DROP
        DUP 0< IF 2DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT THEN
        DUP R@ _SMW.OBSERVATION-GENERATION !
        DROP
        DUP R@ _SMW.OBSERVATION-RECORD-U !
        STREAMS-OBSERVATION-STORE-RECORD-MAX <> IF
            R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
        THEN
        R@ _SMW.OBSERVATION-DIGEST RID-PRESENT? 0= IF
            R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
        THEN
        R@ _SMW-EVIDENCE-CHECKPOINT OCHK-VALID? 0= IF
            R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
        THEN
        R@ _SMW-EVIDENCE-CHECKPOINT R@ _SMW.CHECKPOINT
            STREAMS-OBSERVATION-CHECKPOINT-SIZE MOVE
        R@ _SMW.CHECKPOINT OCHK.GENERATION @
            R@ _SMW.OBSERVATION-GENERATION @ <> IF
            R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
        THEN
        -1 R@ _SMW.OBSERVATION-PRESENT !
        R> DROP STREAMS-MIGRATION-S-OK EXIT
    THEN
    DUP OSTORE-S-ABSENT = IF
        DROP
        OR IF R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT THEN
        R@ _SMW.OBSERVATION-DIGEST SHA3-256-LEN _SMIG-ZERO? 0= IF
            R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
        THEN
        R> DROP STREAMS-MIGRATION-S-OK EXIT
    THEN
    NIP NIP _SMIG-OBSERVATION>STATUS R> DROP ;

: _SMIG-LOAD-LEGACY  ( work -- status )
    DUP _SMIG-LOAD-SOURCE-EVIDENCE
    DUP IF NIP EXIT THEN DROP
    _SMIG-LOAD-OBSERVATION-EVIDENCE ;

: _SMIG-RECOVER-CALLER-CHECKPOINT  ( work -- status )
    >R
    R@ _SMW.OBSERVATION-PRESENT @ 0= IF
        R> DROP STREAMS-MIGRATION-S-OK EXIT
    THEN
    R@ _SMW.CHECKPOINT OCHK-RECOVER-INDETERMINATE
    DUP OCHK-S-OK <> IF
        2DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DROP
    DUP R@ _SMW.RECOVERED-COUNT !
    DROP
    R@ _SMW.CHECKPOINT OCHK-VALID? 0= IF
        R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    R> DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-SET-MATRIX  ( work -- )
    >R
    R@ _SMW.SOURCE-PRESENT @ IF
        R@ _SMW-REGISTRY STREAMS-SOURCE-COUNT
    ELSE
        0
    THEN
    DUP R@ _SMW.SOURCE-COUNT !
    DROP
    R@ _SMW.OBSERVATION-PRESENT @ IF
        R@ _SMW.CHECKPOINT OCHK.SOURCE-COUNT @
        R@ _SMW.CHECKPOINT OCHK.OBSERVATION-COUNT @
        R@ _SMW.CHECKPOINT OCHK.KEY-COUNT @
    ELSE
        0 0 0
    THEN
    R@ _SMW.NATIVE-COUNT !
    R@ _SMW.OBSERVATION-COUNT !
    R@ _SMW.ATTEMPT-COUNT !

    R@ _SMW.SOURCE-PRESENT @ IF
        STREAMS-AUTHORITY-COMPLETE
            R@ _SMW.SOURCE-COMPLETENESS !
    ELSE
        R@ _SMW.OBSERVATION-PRESENT @ IF
            STREAMS-AUTHORITY-UNKNOWN-LEGACY-ABSENT
                R@ _SMW.SOURCE-COMPLETENESS !
        ELSE
            STREAMS-AUTHORITY-COMPLETE
                R@ _SMW.SOURCE-COMPLETENESS !
        THEN
    THEN
    R@ _SMW.OBSERVATION-PRESENT @ IF
        STREAMS-AUTHORITY-COMPLETE
            R@ _SMW.OBSERVATION-COMPLETENESS !
    ELSE
        R@ _SMW.SOURCE-PRESENT @ IF
            STREAMS-AUTHORITY-UNKNOWN-LEGACY-ABSENT
                R@ _SMW.OBSERVATION-COMPLETENESS !
        ELSE
            STREAMS-AUTHORITY-COMPLETE
                R@ _SMW.OBSERVATION-COMPLETENESS !
        THEN
    THEN

    R@ _SMW.SOURCE-PRESENT @ IF
        R@ _SMW.OBSERVATION-PRESENT @ IF
            R@ _SMW.SOURCE-COUNT @ 0= IF
                STREAMS-AUTHORITY-PROVENANCE-LEGACY-EMPTY-SOURCES
            ELSE
                STREAMS-AUTHORITY-PROVENANCE-LEGACY-BOTH
            THEN
        ELSE
            STREAMS-AUTHORITY-PROVENANCE-LEGACY-SOURCES
        THEN
    ELSE
        R@ _SMW.OBSERVATION-PRESENT @ IF
            STREAMS-AUTHORITY-PROVENANCE-LEGACY-OBSERVATIONS
        ELSE
            STREAMS-AUTHORITY-PROVENANCE-COMPLETE-EMPTY
        THEN
    THEN
    R@ _SMW.PROVENANCE !
    R> DROP ;

\ ---------------------------------------------------------------------
\ Legacy semantic reconstruction and cross-validation
\ ---------------------------------------------------------------------

: _SMIG-CANDIDATE-FROM-KEY  ( key work -- status )
    >R
    R@ _SMW.CANDIDATE OCHK-CANDIDATE-INIT
    DUP OCK.FORMAT @ R@ _SMW.CANDIDATE OCC.FORMAT !
    DUP OCK.NATIVE-KIND @ R@ _SMW.CANDIDATE OCC.NATIVE-KIND !
    DUP R@ _SMW.CHECKPOINT OCHK-KEY-NATIVE$
        R@ _SMW.CANDIDATE OCC.NATIVE-A
        R@ _SMW.CANDIDATE OCC.NATIVE-U _SMIG-VIEW!
    DROP
    R@ _SMW.CANDIDATE SPREC-CANDIDATE-VALID?
    IF STREAMS-MIGRATION-S-OK
    ELSE STREAMS-MIGRATION-S-CORRUPT THEN
    R> DROP ;

: _SMIG-CANDIDATE-FROM-OBSERVATION  ( observation work -- status )
    >R
    DUP OCO.KEY-INDEX @ R@ _SMW.CHECKPOINT OCHK-KEY-NTH
    DUP 0= IF
        2DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    R@ _SMW.CANDIDATE OCHK-CANDIDATE-INIT
    OVER OCO.FORMAT @ R@ _SMW.CANDIDATE OCC.FORMAT !
    DUP OCK.NATIVE-KIND @ R@ _SMW.CANDIDATE OCC.NATIVE-KIND !
    DUP R@ _SMW.CHECKPOINT OCHK-KEY-NATIVE$
        R@ _SMW.CANDIDATE OCC.NATIVE-A
        R@ _SMW.CANDIDATE OCC.NATIVE-U _SMIG-VIEW!
    OVER R@ _SMW.CHECKPOINT OCHK-OBSERVATION-TITLE$
        R@ _SMW.CANDIDATE OCC.TITLE-A
        R@ _SMW.CANDIDATE OCC.TITLE-U _SMIG-VIEW!
    OVER R@ _SMW.CHECKPOINT OCHK-OBSERVATION-URL$
        R@ _SMW.CANDIDATE OCC.URL-A
        R@ _SMW.CANDIDATE OCC.URL-U _SMIG-VIEW!
    OVER R@ _SMW.CHECKPOINT OCHK-OBSERVATION-SUMMARY$
        R@ _SMW.CANDIDATE OCC.SUMMARY-A
        R@ _SMW.CANDIDATE OCC.SUMMARY-U _SMIG-VIEW!
    OVER R@ _SMW.CHECKPOINT OCHK-OBSERVATION-CONTENT$
        R@ _SMW.CANDIDATE OCC.CONTENT-A
        R@ _SMW.CANDIDATE OCC.CONTENT-U _SMIG-VIEW!
    OVER R@ _SMW.CHECKPOINT OCHK-OBSERVATION-PUBLISHED$
        R@ _SMW.CANDIDATE OCC.PUBLISHED-A
        R@ _SMW.CANDIDATE OCC.PUBLISHED-U _SMIG-VIEW!
    OVER R@ _SMW.CHECKPOINT OCHK-OBSERVATION-MODIFIED$
        R@ _SMW.CANDIDATE OCC.MODIFIED-A
        R@ _SMW.CANDIDATE OCC.MODIFIED-U _SMIG-VIEW!
    2DROP
    R@ _SMW.CANDIDATE SPREC-CANDIDATE-VALID?
    IF STREAMS-MIGRATION-S-OK
    ELSE STREAMS-MIGRATION-S-CORRUPT THEN
    R> DROP ;

: _SMIG-NATIVE-BUCKET-KEYS?  ( key1 key2 -- flag )
    >R
    DUP OCK.SOURCE-ID R@ OCK.SOURCE-ID RID= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCK.NAMESPACE R@ OCK.NAMESPACE SHA3-256-LEN
        _SMIG-BYTES= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCK.FORMAT @ R@ OCK.FORMAT @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCK.NATIVE-KIND @ R@ OCK.NATIVE-KIND @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    OCK.NATIVE-DIGEST R> OCK.NATIVE-DIGEST SHA3-256-LEN
        _SMIG-BYTES= ;

: _SMIG-NATIVE-BUCKET-PAIR?  ( index1 index2 work -- flag )
    >R
    OVER R@ _SMW.CHECKPOINT OCHK-KEY-NTH
    SWAP R@ _SMW.CHECKPOINT OCHK-KEY-NTH
    ROT DROP
    _SMIG-NATIVE-BUCKET-KEYS?
    R> DROP ;

: _SMIG-NATIVE-EXACT-KEYS?  ( key1 key2 work -- flag )
    >R
    2DUP _SMIG-NATIVE-BUCKET-KEYS? 0= IF
        2DROP R> DROP 0 EXIT
    THEN
    OVER R@ _SMW.CHECKPOINT OCHK-KEY-NATIVE$
    2 PICK R@ _SMW.CHECKPOINT OCHK-KEY-NATIVE$
    _SMIG-$=
    NIP NIP R> DROP ;

: _SMIG-NATIVE-ORDINAL  ( index work -- ordinal )
    0 OVER _SMW.TEMP !
    OVER 1+ 0 ?DO
        I 2 PICK 2 PICK _SMIG-NATIVE-BUCKET-PAIR? IF
            1 OVER _SMW.TEMP +!
        THEN
    LOOP
    NIP _SMW.TEMP @ ;

: _SMIG-CONSTRUCT-NATIVE  ( key-index work -- status )
    >R
    DUP R@ _SMIG-NATIVE-ORDINAL
    DUP 1 < OVER STREAMS-PI-NATIVE-COLLISION-MAX > OR IF
        2DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DUP R@ _SMW.TEMP2 !
    DROP
    R@ _SMW.CHECKPOINT OCHK-KEY-NTH
    DUP 0= IF DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT THEN

    R@ _SMW.RECORD SPREC-NATIVE-INIT _SMIG-SPREC>STATUS
    DUP IF NIP R> DROP EXIT THEN DROP
    DUP OCK.SOURCE-ID R@ _SMW.RECORD SPRH.SOURCE-ID RID-COPY
    DUP OCK.NAMESPACE R@ _SMW.RECORD SPRH.NAMESPACE
        SHA3-256-LEN MOVE
    DUP OCK.LATEST-REVISION @
        R@ _SMW.RECORD SPRH.LATEST-REVISION !
    DUP OCK.LAST-SEEN-SEQUENCE @
        R@ _SMW.RECORD SPRH.LAST-SEEN-SEQUENCE !
    R@ _SMW.TEMP2 @ R@ _SMW.RECORD SPRH.COLLISION-ORDINAL !

    DUP R@ _SMIG-CANDIDATE-FROM-KEY
    DUP IF NIP R> DROP EXIT THEN DROP
    R@ _SMW.CANDIDATE R@ _SMW.RECORD
        SPREC-NATIVE-CANDIDATE! _SMIG-SPREC>STATUS
    DUP IF NIP R> DROP EXIT THEN DROP
    DUP OCK.OBSERVATION-ID
        R@ _SMW.RECORD SPRH.OBSERVATION-ID RID= 0= IF
        DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    OCK.NATIVE-DIGEST R@ _SMW.RECORD SPRH.NATIVE-DIGEST
        SHA3-256-LEN _SMIG-BYTES= 0= IF
        R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    R> DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-ATTEMPT-PAIR-VALID?  ( index1 index2 work -- flag )
    >R
    OVER R@ _SMW.CHECKPOINT OCHK-SOURCE-NTH
    SWAP R@ _SMW.CHECKPOINT OCHK-SOURCE-NTH
    ROT DROP
    >R
    DUP OCS.SOURCE-ID R@ OCS.SOURCE-ID RID= IF
        DROP R> DROP R> DROP 0 EXIT
    THEN
    DUP OCS.ATTEMPT-ID R@ OCS.ATTEMPT-ID RID= IF
        DROP R> DROP R> DROP 0 EXIT
    THEN
    OCS.ATTEMPT-SEQUENCE @ R> OCS.ATTEMPT-SEQUENCE @ <>
    R> DROP ;

: _SMIG-OBSERVATION-PAIR-VALID?  ( index1 index2 work -- flag )
    >R
    OVER R@ _SMW.CHECKPOINT OCHK-OBSERVATION-NTH
    SWAP R@ _SMW.CHECKPOINT OCHK-OBSERVATION-NTH
    ROT DROP
    >R
    DUP OCO.ID R@ OCO.ID RID= IF
        DUP OCO.REVISION @ R@ OCO.REVISION @ = IF
            DROP R> DROP R> DROP 0 EXIT
        THEN
    THEN
    DROP R> DROP R> DROP -1 ;

: _SMIG-KEY-PAIR-VALID?  ( index1 index2 work -- flag )
    >R
    OVER R@ _SMW.CHECKPOINT OCHK-KEY-NTH
    SWAP R@ _SMW.CHECKPOINT OCHK-KEY-NTH
    ROT DROP
    OVER OCK.OBSERVATION-ID OVER OCK.OBSERVATION-ID RID= IF
        2DROP R> DROP 0 EXIT
    THEN
    R@ _SMIG-NATIVE-EXACT-KEYS? 0=
    R> DROP ;

: _SMIG-OBSERVATION-KEY-AGREES?  ( observation key -- flag )
    >R
    DUP OCO.SOURCE-ID R@ OCK.SOURCE-ID RID= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCO.NAMESPACE R@ OCK.NAMESPACE SHA3-256-LEN
        _SMIG-BYTES= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCO.ID R@ OCK.OBSERVATION-ID RID= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCO.FORMAT @ R@ OCK.FORMAT @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    OCO.REVISION @ R> OCK.LATEST-REVISION @ <= ;

: _SMIG-LATEST-OBSERVATION-AGREES?
  ( key-index key observation -- flag )
    >R
    R@ OCO.KEY-INDEX @ 2 PICK <> IF
        2DROP R> DROP 0 EXIT
    THEN
    R@ OVER _SMIG-OBSERVATION-KEY-AGREES? 0= IF
        2DROP R> DROP 0 EXIT
    THEN
    R@ OCO.REVISION @ OVER OCK.LATEST-REVISION @ <> IF
        2DROP R> DROP 0 EXIT
    THEN
    R@ OCO.SEQUENCE @ OVER OCK.LAST-SEEN-SEQUENCE @ <=
    NIP NIP R> DROP ;

\ Legacy stores only one current attempt head per source.  When an older
\ observation's original successful attempt is still that head, require exact
\ lineage agreement.  When a later head replaced it, admit the missing attempt
\ without inventing request evidence; sealed migration provenance records that
\ incompleteness for compaction.
: _SMIG-OBSERVATION-ATTEMPT-IF-PRESENT?  ( observation work -- flag )
    DUP _SMW.CHECKPOINT OCHK.SOURCE-COUNT @ 0 ?DO
        I OVER _SMW.CHECKPOINT OCHK-SOURCE-NTH
        2 PICK OCO.ATTEMPT-ID OVER OCS.ATTEMPT-ID RID= IF
            DUP OCS.STATE @ OCHK-ATTEMPT-SUCCEEDED <> IF
                DROP 2DROP 0 UNLOOP EXIT
            THEN
            DUP OCS.SOURCE-ID 3 PICK OCO.SOURCE-ID RID= 0= IF
                DROP 2DROP 0 UNLOOP EXIT
            THEN
            DUP OCS.NAMESPACE 3 PICK OCO.NAMESPACE SHA3-256-LEN
                _SMIG-BYTES= 0= IF
                DROP 2DROP 0 UNLOOP EXIT
            THEN
            OCS.ATTEMPT-SEQUENCE @
                2 PICK OCO.SEQUENCE @ <> IF
                2DROP 0 UNLOOP EXIT
            THEN
        ELSE
            DROP
        THEN
    LOOP
    2DROP -1 ;

\ Count every retained immutable observation version belonging to one current
\ legacy source.  The checkpoint is already fully checked and the scan is
\ bounded by the legacy maximum of forty-eight observations.  Missing
\ observation evidence means an exact current count of zero with separately
\ recorded UNKNOWN_LEGACY_ABSENT completeness; it never authorizes inventing
\ observation rows.
: _SMIG-SOURCE-OBSERVATION-COUNT
  ( source work -- count status )
    DUP _SMW.OBSERVATION-PRESENT @ 0= IF
        2DROP 0 STREAMS-MIGRATION-S-OK EXIT
    THEN
    0 SWAP
    DUP _SMW.CHECKPOINT OCHK.OBSERVATION-COUNT @
    DUP 0< OVER OCHK-OBSERVATION-MAX > OR IF
        2DROP 2DROP
        0 STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    0 ?DO
        I OVER _SMW.CHECKPOINT OCHK-OBSERVATION-NTH
        DUP 0= IF
            DROP _SMIG-DROP3
            0 STREAMS-MIGRATION-S-CORRUPT UNLOOP EXIT
        THEN
        OCO.SOURCE-ID 3 PICK SSOURCE.ID RID= IF
            SWAP 1+ SWAP
        THEN
    LOOP
    DROP NIP STREAMS-MIGRATION-S-OK ;

: _SMIG-VALIDATE-SOURCE-ONE  ( index work -- status )
    >R
    DUP 1+ DUP 0> 0= IF
        2DROP R> DROP STREAMS-MIGRATION-S-CAPACITY EXIT
    THEN
    SWAP R@ _SMW-REGISTRY STREAMS-SOURCE-NTH
    DUP R@ _SMIG-SOURCE-OBSERVATION-COUNT
    DUP IF
        >R DROP 2DROP R> R> DROP EXIT
    THEN DROP
    R@ _SMW.TEMP !
    SWAP R@ _SMW.RECORD SPREC-SOURCE-CONSTRUCT
        _SMIG-SPREC>STATUS
    DUP IF R> DROP EXIT THEN DROP
    R@ _SMW.TEMP @ R@ _SMW.RECORD SPRS.OBSERVATION-COUNT !
    R@ _SMW.RECORD SPREC-SOURCE-SEAL!
        _SMIG-SPREC>STATUS
    R> DROP ;

: _SMIG-VALIDATE-ATTEMPT-ONE  ( attempt work -- status )
    >R
    DUP OCS.ATTEMPT-SEQUENCE @
        R@ _SMW.CHECKPOINT OCHK.SEQUENCE @ > IF
        DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DUP OCS.STATE @ OCHK-ATTEMPT-ACCEPTED = IF
        DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    R@ _SMW.RECORD SPREC-ATTEMPT-CONSTRUCT
        _SMIG-SPREC>STATUS
    R> DROP ;

: _SMIG-VALIDATE-KEY-ONE  ( key-index work -- status )
    >R
    DUP R@ _SMW.EXPECTED-U !
    DUP R@ _SMW.CHECKPOINT OCHK-KEY-NTH
    DUP 0= IF
        2DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DUP OCK.LAST-SEEN-SEQUENCE @
        R@ _SMW.CHECKPOINT OCHK.SEQUENCE @ > IF
        2DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DUP OCK.LATEST-OBSERVATION @
        R@ _SMW.CHECKPOINT OCHK-OBSERVATION-NTH
    DUP 0= IF
        _SMIG-DROP3 R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    _SMIG-LATEST-OBSERVATION-AGREES? 0= IF
        R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    R@ _SMW.EXPECTED-U @ R@ _SMIG-CONSTRUCT-NATIVE
    R> DROP ;

: _SMIG-VALIDATE-OBSERVATION-ONE  ( observation work -- status )
    >R
    DUP OCO.SEQUENCE @ R@ _SMW.CHECKPOINT OCHK.SEQUENCE @ > IF
        DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DUP OCO.REVISION @ OVER OCO.SEQUENCE @ > IF
        DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DUP OCO.KEY-INDEX @ R@ _SMW.CHECKPOINT OCHK-KEY-NTH
    DUP 0= IF
        2DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    2DUP _SMIG-OBSERVATION-KEY-AGREES? 0= IF
        2DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DROP
    DUP R@ _SMIG-OBSERVATION-ATTEMPT-IF-PRESENT? 0= IF
        DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DUP R@ _SMIG-CANDIDATE-FROM-OBSERVATION
    DUP IF NIP R> DROP EXIT THEN DROP
    R@ _SMW.CANDIDATE R@ _SMW.TEMP-DIGEST
        SPREC-CANDIDATE-SEMANTIC-DIGEST! _SMIG-SPREC>STATUS
    DUP IF NIP R> DROP EXIT THEN DROP
    DUP OCO.SEMANTIC-DIGEST R@ _SMW.TEMP-DIGEST SHA3-256-LEN
        _SMIG-BYTES= 0= IF
        DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DUP OCO.KEY-INDEX @ R@ _SMIG-CONSTRUCT-NATIVE
    DUP IF NIP R> DROP EXIT THEN DROP
    OCO.ID R@ _SMW.RECORD SPRH.OBSERVATION-ID RID= 0= IF
        R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    R> DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VALIDATE-SOURCES  ( work -- status )
    DUP _SMW.SOURCE-COUNT @ 0 ?DO
        I OVER _SMIG-VALIDATE-SOURCE-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VALIDATE-ATTEMPTS  ( work -- status )
    DUP _SMW.ATTEMPT-COUNT @ 0 ?DO
        I OVER _SMW.CHECKPOINT OCHK-SOURCE-NTH
        OVER _SMIG-VALIDATE-ATTEMPT-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DUP _SMW.ATTEMPT-COUNT @ 0 ?DO
        I 0 ?DO
            J I 2 PICK _SMIG-ATTEMPT-PAIR-VALID? 0= IF
                DROP STREAMS-MIGRATION-S-CORRUPT
                UNLOOP UNLOOP EXIT
            THEN
        LOOP
    LOOP
    DUP _SMW.ATTEMPT-COUNT @
        OVER _SMW.OBSERVATION-PRESENT @ IF
            OVER _SMW.CHECKPOINT OCHK.SEQUENCE @
        ELSE
            0
        THEN
        > IF
        DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VALIDATE-KEYS  ( work -- status )
    DUP _SMW.NATIVE-COUNT @ 0 ?DO
        I OVER _SMIG-VALIDATE-KEY-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DUP _SMW.NATIVE-COUNT @ 0 ?DO
        I 0 ?DO
            J I 2 PICK _SMIG-KEY-PAIR-VALID? 0= IF
                DROP STREAMS-MIGRATION-S-CORRUPT
                UNLOOP UNLOOP EXIT
            THEN
        LOOP
    LOOP
    DUP _SMW.NATIVE-COUNT @ OVER _SMW.OBSERVATION-COUNT @ > IF
        DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VALIDATE-OBSERVATIONS  ( work -- status )
    DUP _SMW.OBSERVATION-COUNT @ 0 ?DO
        I OVER _SMW.CHECKPOINT OCHK-OBSERVATION-NTH
        OVER _SMIG-VALIDATE-OBSERVATION-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DUP _SMW.OBSERVATION-COUNT @ 0 ?DO
        I 0 ?DO
            J I 2 PICK _SMIG-OBSERVATION-PAIR-VALID? 0= IF
                DROP STREAMS-MIGRATION-S-CORRUPT
                UNLOOP UNLOOP EXIT
            THEN
        LOOP
    LOOP
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VALIDATE-LEGACY-GRAPH  ( work -- status )
    DUP _SMIG-VALIDATE-SOURCES
    DUP IF NIP EXIT THEN DROP
    DUP _SMIG-VALIDATE-ATTEMPTS
    DUP IF NIP EXIT THEN DROP
    DUP _SMIG-VALIDATE-KEYS
    DUP IF NIP EXIT THEN DROP
    _SMIG-VALIDATE-OBSERVATIONS ;

: _SMIG-PREPARE-LEGACY  ( work -- status )
    DUP _SMIG-RECOVER-CALLER-CHECKPOINT
    DUP IF NIP EXIT THEN DROP
    DUP _SMIG-SET-MATRIX
    _SMIG-VALIDATE-LEGACY-GRAPH ;

\ ---------------------------------------------------------------------
\ Bounded staging callbacks and primitive operations
\ ---------------------------------------------------------------------

: _SMIG-BLOB-SOURCE
  ( logical-offset destination-a requested-u work -- actual-u status )
    >R
    2 PICK 0< OVER 0< OR IF
        _SMIG-DROP3 R> DROP 0 PERSIST-S-INVALID EXIT
    THEN
    2 PICK R@ _SMW.CALLBACK-U @ > IF
        _SMIG-DROP3 R> DROP 0 PERSIST-S-INVALID EXIT
    THEN
    R@ _SMW.CALLBACK-U @ 3 PICK - OVER < IF
        _SMIG-DROP3 R> DROP 0 PERSIST-S-INVALID EXIT
    THEN
    DUP IF
        OVER 0= IF
            _SMIG-DROP3 R> DROP 0 PERSIST-S-INVALID EXIT
        THEN
        OVER OVER MSPAN-NONWRAPPING? 0= IF
            _SMIG-DROP3 R> DROP 0 PERSIST-S-INVALID EXIT
        THEN
    THEN
    2 PICK R@ _SMW.CALLBACK-A @ +
    2 PICK 2 PICK MOVE
    NIP NIP PERSIST-S-OK
    R> DROP ;

: _SMIG-BLOB-SINK
  ( logical-offset source-a offered-u work -- status )
    >R
    2 PICK 0< OVER 0< OR IF
        _SMIG-DROP3 R> DROP PERSIST-S-INVALID EXIT
    THEN
    2 PICK R@ _SMW.CALLBACK-OFFSET @ <> IF
        _SMIG-DROP3 R> DROP PERSIST-S-CORRUPT EXIT
    THEN
    2 PICK R@ _SMW.CALLBACK-U @ > IF
        _SMIG-DROP3 R> DROP PERSIST-S-CORRUPT EXIT
    THEN
    R@ _SMW.CALLBACK-U @ 3 PICK - OVER < IF
        _SMIG-DROP3 R> DROP PERSIST-S-CORRUPT EXIT
    THEN
    DUP IF
        OVER 0= IF
            _SMIG-DROP3 R> DROP PERSIST-S-INVALID EXIT
        THEN
        OVER OVER MSPAN-NONWRAPPING? 0= IF
            _SMIG-DROP3 R> DROP PERSIST-S-INVALID EXIT
        THEN
    THEN
    2 PICK R@ _SMW.CALLBACK-A @ +
    2 PICK 2 PICK _SMIG-BYTES= 0= IF
        _SMIG-DROP3 R> DROP PERSIST-S-CORRUPT EXIT
    THEN
    DUP R@ _SMW.CALLBACK-OFFSET +!
    _SMIG-DROP3 R> DROP PERSIST-S-OK ;

: _SMIG-APPEND-CURRENT  ( record-u work -- status )
    >R
    R@ _SMW.RECORD SWAP R@ _SMW.REF
    R@ _SMW.ADAPTER @ R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-APPEND-RECORD
    R> DROP ;

: _SMIG-PUT-CURRENT  ( key-u work -- status )
    >R
    R@ _SMW.KEY SWAP R@ _SMW.REF
    R@ _SMW.ADAPTER @ R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-STAGED-PUT
    R> DROP ;

: _SMIG-GET-CURRENT-KEY  ( key-u work -- record-u status )
    >R
    R@ _SMW.KEY SWAP
    R@ _SMW.READBACK STREAMS-PERSISTENCE-RECORD-MAX
    R@ _SMW.ADAPTER @ R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-STAGED-GET
    R> DROP ;

: _SMIG-VERIFY-CURRENT  ( key-u expected-record-u work -- status )
    >R
    DUP R@ _SMW.EXPECTED-U !
    DROP
    R@ _SMIG-GET-CURRENT-KEY
    DUP IF
        >R DROP R> _SMIG-READBACK>STATUS R> DROP EXIT
    THEN
    DROP
    R@ _SMW.EXPECTED-U @ <> IF
        R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    R@ _SMW.RECORD R@ _SMW.READBACK
        R@ _SMW.EXPECTED-U @ _SMIG-BYTES= 0= IF
        R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    R> DROP STREAMS-MIGRATION-S-OK ;

\ ---------------------------------------------------------------------
\ Semantic record construction and staged import
\ ---------------------------------------------------------------------

: _SMIG-CONSTRUCT-OBSERVATION  ( observation work -- status )
    >R
    DUP R@ _SMIG-CANDIDATE-FROM-OBSERVATION
    DUP IF NIP R> DROP EXIT THEN DROP
    R@ _SMW.CANDIDATE OCC.CONTENT-A @ R@ _SMW.CALLBACK-A !
    R@ _SMW.CANDIDATE OCC.CONTENT-U @ R@ _SMW.CALLBACK-U !
    0 R@ _SMW.CALLBACK-OFFSET !
    R@ _SMW.CALLBACK-U @ ['] _SMIG-BLOB-SOURCE R@
        R@ _SMW.BLOB R@ _SMW.ADAPTER @ R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-BLOB-WRITE
    DUP IF NIP R> DROP EXIT THEN DROP

    R@ _SMW.RECORD SPREC-OBSERVATION-INIT _SMIG-SPREC>STATUS
    DUP IF NIP R> DROP EXIT THEN DROP
    DUP OCO.ID R@ _SMW.RECORD SPRO.OBSERVATION-ID RID-COPY
    DUP OCO.SOURCE-ID R@ _SMW.RECORD SPRO.SOURCE-ID RID-COPY
    DUP OCO.NAMESPACE R@ _SMW.RECORD SPRO.NAMESPACE
        SHA3-256-LEN MOVE
    DUP OCO.ATTEMPT-ID R@ _SMW.RECORD SPRO.ATTEMPT-ID RID-COPY
    DUP OCO.SEQUENCE @
        R@ _SMW.RECORD SPRO.ACQUISITION-SEQUENCE !
    DUP OCO.REVISION @ R@ _SMW.RECORD SPRO.REVISION !

    R@ _SMW.CANDIDATE R@ _SMW.BLOB R@ _SMW.RECORD
        SPREC-OBSERVATION-CANDIDATE! _SMIG-SPREC>STATUS
    DUP IF NIP R> DROP EXIT THEN DROP
    DUP OCO.SEMANTIC-DIGEST
        R@ _SMW.RECORD SPRO.SEMANTIC-DIGEST
        SHA3-256-LEN _SMIG-BYTES= 0= IF
        DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    OCO.ID R@ _SMW.RECORD SPRO.OBSERVATION-ID RID= 0= IF
        R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    R> DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-IMPORT-SOURCE-ONE  ( index work -- status )
    >R
    R@ _SMIG-VALIDATE-SOURCE-ONE
    DUP IF R> DROP EXIT THEN DROP
    SPREC-SOURCE-SIZE R@ _SMIG-APPEND-CURRENT
    DUP IF R> DROP EXIT THEN DROP

    R@ _SMW.RECORD SPRS.ID R@ _SMW.KEY
        STREAMS-PI-SOURCE-RID-KEY _SMIG-KEY>STATUS
    DUP IF R> DROP EXIT THEN DROP
    STREAMS-PI-SOURCE-RID-KEY-SIZE R@ _SMIG-PUT-CURRENT
    DUP IF R> DROP EXIT THEN DROP

    R@ _SMW.RECORD SPRS.CREATION-SEQUENCE @
    R@ _SMW.RECORD SPRS.ID R@ _SMW.KEY
        STREAMS-PI-SOURCE-ORDER-KEY _SMIG-KEY>STATUS
    DUP IF R> DROP EXIT THEN DROP
    STREAMS-PI-SOURCE-ORDER-KEY-SIZE R@ _SMIG-PUT-CURRENT
    R> DROP ;

: _SMIG-IMPORT-ATTEMPT-ONE  ( attempt work -- status )
    >R
    R@ _SMW.RECORD SPREC-ATTEMPT-CONSTRUCT
        _SMIG-SPREC>STATUS
    DUP IF R> DROP EXIT THEN DROP
    SPREC-ATTEMPT-SIZE R@ _SMIG-APPEND-CURRENT
    DUP IF R> DROP EXIT THEN DROP
    R@ _SMW.RECORD SPRA.SOURCE-ID
    R@ _SMW.RECORD SPRA.ATTEMPT-SEQUENCE @
    R@ _SMW.RECORD SPRA.ATTEMPT-ID
    R@ _SMW.KEY STREAMS-PI-ATTEMPT-BY-SOURCE-KEY
        _SMIG-KEY>STATUS
    DUP IF R> DROP EXIT THEN DROP
    STREAMS-PI-ATTEMPT-BY-SOURCE-KEY-SIZE R@ _SMIG-PUT-CURRENT
    R> DROP ;

: _SMIG-IMPORT-NATIVE-ONE  ( key-index work -- status )
    >R
    R@ _SMIG-CONSTRUCT-NATIVE
    DUP IF R> DROP EXIT THEN DROP
    SPREC-NATIVE-HEAD-SIZE R@ _SMIG-APPEND-CURRENT
    DUP IF R> DROP EXIT THEN DROP
    R@ _SMW.RECORD SPRH.SOURCE-ID
    R@ _SMW.RECORD SPRH.NAMESPACE
    R@ _SMW.RECORD SPRH.OBSERVATION-FORMAT @
    R@ _SMW.RECORD SPRH.NATIVE-KIND @
    R@ _SMW.RECORD SPRH.NATIVE-DIGEST
    R@ _SMW.RECORD SPRH.COLLISION-ORDINAL @
    R@ _SMW.KEY STREAMS-PI-NATIVE-HEAD-KEY
        _SMIG-KEY>STATUS
    DUP IF R> DROP EXIT THEN DROP
    STREAMS-PI-NATIVE-HEAD-KEY-SIZE R@ _SMIG-PUT-CURRENT
    R> DROP ;

: _SMIG-IMPORT-OBSERVATION-ONE  ( observation work -- status )
    >R
    R@ _SMIG-CONSTRUCT-OBSERVATION
    DUP IF R> DROP EXIT THEN DROP
    SPREC-OBSERVATION-SIZE R@ _SMIG-APPEND-CURRENT
    DUP IF R> DROP EXIT THEN DROP

    R@ _SMW.RECORD SPRO.OBSERVATION-ID
    R@ _SMW.RECORD SPRO.REVISION @
    R@ _SMW.KEY STREAMS-PI-OBSERVATION-REVISION-KEY
        _SMIG-KEY>STATUS
    DUP IF R> DROP EXIT THEN DROP
    STREAMS-PI-OBSERVATION-REVISION-KEY-SIZE
        R@ _SMIG-PUT-CURRENT
    DUP IF R> DROP EXIT THEN DROP

    R@ _SMW.RECORD SPRO.ACQUISITION-SEQUENCE @
    R@ _SMW.RECORD SPRO.OBSERVATION-ID
    R@ _SMW.RECORD SPRO.REVISION @
    R@ _SMW.KEY STREAMS-PI-GLOBAL-TIME-KEY
        _SMIG-KEY>STATUS
    DUP IF R> DROP EXIT THEN DROP
    STREAMS-PI-GLOBAL-TIME-KEY-SIZE R@ _SMIG-PUT-CURRENT
    DUP IF R> DROP EXIT THEN DROP

    R@ _SMW.RECORD SPRO.SOURCE-ID
    R@ _SMW.RECORD SPRO.ACQUISITION-SEQUENCE @
    R@ _SMW.RECORD SPRO.OBSERVATION-ID
    R@ _SMW.RECORD SPRO.REVISION @
    R@ _SMW.KEY STREAMS-PI-SOURCE-TIME-KEY
        _SMIG-KEY>STATUS
    DUP IF R> DROP EXIT THEN DROP
    STREAMS-PI-SOURCE-TIME-KEY-SIZE R@ _SMIG-PUT-CURRENT
    R> DROP ;

: _SMIG-IMPORT-SOURCES  ( work -- status )
    DUP _SMW.SOURCE-COUNT @ 0 ?DO
        I OVER _SMIG-IMPORT-SOURCE-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-IMPORT-ATTEMPTS  ( work -- status )
    DUP _SMW.ATTEMPT-COUNT @ 0 ?DO
        I OVER _SMW.CHECKPOINT OCHK-SOURCE-NTH
        OVER _SMIG-IMPORT-ATTEMPT-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-IMPORT-NATIVES  ( work -- status )
    DUP _SMW.NATIVE-COUNT @ 0 ?DO
        I OVER _SMIG-IMPORT-NATIVE-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-IMPORT-OBSERVATIONS  ( work -- status )
    DUP _SMW.OBSERVATION-COUNT @ 0 ?DO
        I OVER _SMW.CHECKPOINT OCHK-OBSERVATION-NTH
        OVER _SMIG-IMPORT-OBSERVATION-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-IMPORT-ALL  ( work -- status )
    DUP _SMIG-IMPORT-SOURCES
    DUP IF NIP EXIT THEN DROP
    DUP _SMIG-IMPORT-ATTEMPTS
    DUP IF NIP EXIT THEN DROP
    DUP _SMIG-IMPORT-NATIVES
    DUP IF NIP EXIT THEN DROP
    _SMIG-IMPORT-OBSERVATIONS ;

\ ---------------------------------------------------------------------
\ Exact staged readback
\ ---------------------------------------------------------------------

: _SMIG-VERIFY-SOURCE-ONE  ( index work -- status )
    >R
    R@ _SMIG-VALIDATE-SOURCE-ONE
    DUP IF R> DROP EXIT THEN DROP
    R@ _SMW.RECORD SPRS.ID R@ _SMW.KEY
        STREAMS-PI-SOURCE-RID-KEY _SMIG-KEY>STATUS
    DUP IF R> DROP EXIT THEN DROP
    STREAMS-PI-SOURCE-RID-KEY-SIZE SPREC-SOURCE-SIZE
        R@ _SMIG-VERIFY-CURRENT
    DUP IF R> DROP EXIT THEN DROP
    R@ _SMW.RECORD SPRS.CREATION-SEQUENCE @
    R@ _SMW.RECORD SPRS.ID R@ _SMW.KEY
        STREAMS-PI-SOURCE-ORDER-KEY _SMIG-KEY>STATUS
    DUP IF R> DROP EXIT THEN DROP
    STREAMS-PI-SOURCE-ORDER-KEY-SIZE SPREC-SOURCE-SIZE
        R@ _SMIG-VERIFY-CURRENT
    R> DROP ;

: _SMIG-VERIFY-ATTEMPT-ONE  ( attempt work -- status )
    >R
    R@ _SMW.RECORD SPREC-ATTEMPT-CONSTRUCT
        _SMIG-SPREC>STATUS
    DUP IF R> DROP EXIT THEN DROP
    R@ _SMW.RECORD SPRA.SOURCE-ID
    R@ _SMW.RECORD SPRA.ATTEMPT-SEQUENCE @
    R@ _SMW.RECORD SPRA.ATTEMPT-ID
    R@ _SMW.KEY STREAMS-PI-ATTEMPT-BY-SOURCE-KEY
        _SMIG-KEY>STATUS
    DUP IF R> DROP EXIT THEN DROP
    STREAMS-PI-ATTEMPT-BY-SOURCE-KEY-SIZE SPREC-ATTEMPT-SIZE
        R@ _SMIG-VERIFY-CURRENT
    R> DROP ;

: _SMIG-VERIFY-NATIVE-ONE  ( key-index work -- status )
    >R
    R@ _SMIG-CONSTRUCT-NATIVE
    DUP IF R> DROP EXIT THEN DROP
    R@ _SMW.RECORD SPRH.SOURCE-ID
    R@ _SMW.RECORD SPRH.NAMESPACE
    R@ _SMW.RECORD SPRH.OBSERVATION-FORMAT @
    R@ _SMW.RECORD SPRH.NATIVE-KIND @
    R@ _SMW.RECORD SPRH.NATIVE-DIGEST
    R@ _SMW.RECORD SPRH.COLLISION-ORDINAL @
    R@ _SMW.KEY STREAMS-PI-NATIVE-HEAD-KEY
        _SMIG-KEY>STATUS
    DUP IF R> DROP EXIT THEN DROP
    STREAMS-PI-NATIVE-HEAD-KEY-SIZE SPREC-NATIVE-HEAD-SIZE
        R@ _SMIG-VERIFY-CURRENT
    R> DROP ;

: _SMIG-CANDIDATE-READBACK-VIEWS?  ( work -- flag )
    >R
    R@ _SMW.CANDIDATE OCC.TITLE-A @
    R@ _SMW.CANDIDATE OCC.TITLE-U @
    R@ _SMW.READBACK SPRO-TITLE$ _SMIG-$= 0= IF
        R> DROP 0 EXIT
    THEN
    R@ _SMW.CANDIDATE OCC.URL-A @
    R@ _SMW.CANDIDATE OCC.URL-U @
    R@ _SMW.READBACK SPRO-URL$ _SMIG-$= 0= IF
        R> DROP 0 EXIT
    THEN
    R@ _SMW.CANDIDATE OCC.SUMMARY-A @
    R@ _SMW.CANDIDATE OCC.SUMMARY-U @
    R@ _SMW.READBACK SPRO-SUMMARY$ _SMIG-$= 0= IF
        R> DROP 0 EXIT
    THEN
    R@ _SMW.CANDIDATE OCC.PUBLISHED-A @
    R@ _SMW.CANDIDATE OCC.PUBLISHED-U @
    R@ _SMW.READBACK SPRO-PUBLISHED$ _SMIG-$= 0= IF
        R> DROP 0 EXIT
    THEN
    R@ _SMW.CANDIDATE OCC.MODIFIED-A @
    R@ _SMW.CANDIDATE OCC.MODIFIED-U @
    R@ _SMW.READBACK SPRO-MODIFIED$ _SMIG-$= 0= IF
        R> DROP 0 EXIT
    THEN
    R> DROP -1 ;

: _SMIG-OBSERVATION-READBACK-SCALARS?  ( observation work -- flag )
    >R
    DUP OCO.ID R@ _SMW.READBACK SPRO.OBSERVATION-ID RID= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCO.SOURCE-ID R@ _SMW.READBACK SPRO.SOURCE-ID RID= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCO.NAMESPACE R@ _SMW.READBACK SPRO.NAMESPACE
        SHA3-256-LEN _SMIG-BYTES= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCO.ATTEMPT-ID R@ _SMW.READBACK SPRO.ATTEMPT-ID RID= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCO.SEMANTIC-DIGEST
        R@ _SMW.READBACK SPRO.SEMANTIC-DIGEST
        SHA3-256-LEN _SMIG-BYTES= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCO.SEQUENCE @
        R@ _SMW.READBACK SPRO.ACQUISITION-SEQUENCE @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP OCO.REVISION @ R@ _SMW.READBACK SPRO.REVISION @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    OCO.FORMAT @
        R@ _SMW.READBACK SPRO.OBSERVATION-FORMAT @ =
    R> DROP ;

: _SMIG-VERIFY-OBSERVATION-RECORD  ( observation work -- status )
    >R
    R@ _SMW.READBACK SPREC-OBSERVATION-SIZE
        SPREC-OBSERVATION-VALID? 0= IF
        DROP R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    DUP R@ _SMIG-OBSERVATION-READBACK-SCALARS? 0= IF
        DROP R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    DUP R@ _SMIG-CANDIDATE-FROM-OBSERVATION
    DUP IF NIP R> DROP EXIT THEN DROP
    R@ _SMIG-CANDIDATE-READBACK-VIEWS? 0= IF
        DROP R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    R@ _SMW.CANDIDATE OCC.CONTENT-U @
        R@ _SMW.READBACK SPRO.CONTENT-U @ <> IF
        DROP R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    R@ _SMW.CANDIDATE OCC.CONTENT-U @
        R@ _SMW.READBACK SPRO.CONTENT PBLOB-TOTAL@ <> IF
        DROP R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    R@ _SMW.CANDIDATE OCC.CONTENT-A @
    R@ _SMW.CANDIDATE OCC.CONTENT-U @
        R@ _SMW.READBACK SPRO.CONTENT-DIGEST
        SHA3-256-HASH-COMPARE 0= IF
        DROP R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN

    R@ _SMW.CANDIDATE OCC.CONTENT-A @ R@ _SMW.CALLBACK-A !
    R@ _SMW.CANDIDATE OCC.CONTENT-U @ R@ _SMW.CALLBACK-U !
    0 R@ _SMW.CALLBACK-OFFSET !
    R@ _SMW.READBACK SPRO.CONTENT
    0 R@ _SMW.CALLBACK-U @
    ['] _SMIG-BLOB-SINK R@
    R@ _SMW.ADAPTER @ R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-STAGED-BLOB-READ-RANGE
    DUP IF
        >R DROP R> _SMIG-READBACK>STATUS R> DROP EXIT
    THEN
    DROP
    R@ _SMW.CALLBACK-OFFSET @ R@ _SMW.CALLBACK-U @ <> IF
        DROP R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    DROP R> DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VERIFY-OBSERVATION-ONE  ( observation work -- status )
    >R
    DUP OCO.ID OVER OCO.REVISION @
    R@ _SMW.KEY STREAMS-PI-OBSERVATION-REVISION-KEY
        _SMIG-KEY>STATUS
    DUP IF NIP R> DROP EXIT THEN DROP
    STREAMS-PI-OBSERVATION-REVISION-KEY-SIZE
        R@ _SMIG-GET-CURRENT-KEY
    DUP IF
        >R DROP DROP R> _SMIG-READBACK>STATUS R> DROP EXIT
    THEN
    DROP
    SPREC-OBSERVATION-SIZE <> IF
        DROP R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    DUP R@ _SMIG-VERIFY-OBSERVATION-RECORD
    DUP IF NIP R> DROP EXIT THEN DROP
    R@ _SMW.READBACK R@ _SMW.RECORD
        SPREC-OBSERVATION-SIZE MOVE

    DUP OCO.SEQUENCE @ OVER OCO.ID 2 PICK OCO.REVISION @
    R@ _SMW.KEY STREAMS-PI-GLOBAL-TIME-KEY
        _SMIG-KEY>STATUS
    DUP IF NIP R> DROP EXIT THEN DROP
    STREAMS-PI-GLOBAL-TIME-KEY-SIZE SPREC-OBSERVATION-SIZE
        R@ _SMIG-VERIFY-CURRENT
    DUP IF NIP R> DROP EXIT THEN DROP

    DUP OCO.SOURCE-ID OVER OCO.SEQUENCE @
    2 PICK OCO.ID 3 PICK OCO.REVISION @
    R@ _SMW.KEY STREAMS-PI-SOURCE-TIME-KEY
        _SMIG-KEY>STATUS
    DUP IF NIP R> DROP EXIT THEN DROP
    STREAMS-PI-SOURCE-TIME-KEY-SIZE SPREC-OBSERVATION-SIZE
        R@ _SMIG-VERIFY-CURRENT
    DUP IF NIP R> DROP EXIT THEN
    DROP DROP R> DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VERIFY-CARDINALITIES  ( work -- status )
    >R
    STREAMS-PI-TREE-DIRECTORY R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-STAGED-TREE-CARDINALITY@
    R@ _SMW.SOURCE-COUNT @ 2 * <> IF
        R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    STREAMS-PI-TREE-ATTEMPTS R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-STAGED-TREE-CARDINALITY@
    R@ _SMW.ATTEMPT-COUNT @ <> IF
        R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    STREAMS-PI-TREE-IDENTITIES R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-STAGED-TREE-CARDINALITY@
    R@ _SMW.NATIVE-COUNT @ R@ _SMW.OBSERVATION-COUNT @ + <> IF
        R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    STREAMS-PI-TREE-ORDERINGS R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-STAGED-TREE-CARDINALITY@
    R@ _SMW.OBSERVATION-COUNT @ 2 * <> IF
        R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
    THEN
    R> DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VERIFY-SOURCES  ( work -- status )
    DUP _SMW.SOURCE-COUNT @ 0 ?DO
        I OVER _SMIG-VERIFY-SOURCE-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VERIFY-ATTEMPTS  ( work -- status )
    DUP _SMW.ATTEMPT-COUNT @ 0 ?DO
        I OVER _SMW.CHECKPOINT OCHK-SOURCE-NTH
        OVER _SMIG-VERIFY-ATTEMPT-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VERIFY-NATIVES  ( work -- status )
    DUP _SMW.NATIVE-COUNT @ 0 ?DO
        I OVER _SMIG-VERIFY-NATIVE-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VERIFY-OBSERVATIONS  ( work -- status )
    DUP _SMW.OBSERVATION-COUNT @ 0 ?DO
        I OVER _SMW.CHECKPOINT OCHK-OBSERVATION-NTH
        OVER _SMIG-VERIFY-OBSERVATION-ONE
        DUP IF NIP UNLOOP EXIT THEN DROP
    LOOP
    DROP STREAMS-MIGRATION-S-OK ;

: _SMIG-VERIFY-ALL  ( work -- status )
    DUP _SMIG-VERIFY-SOURCES
    DUP IF NIP EXIT THEN DROP
    DUP _SMIG-VERIFY-ATTEMPTS
    DUP IF NIP EXIT THEN DROP
    DUP _SMIG-VERIFY-NATIVES
    DUP IF NIP EXIT THEN DROP
    DUP _SMIG-VERIFY-OBSERVATIONS
    DUP IF NIP EXIT THEN DROP
    _SMIG-VERIFY-CARDINALITIES ;

\ ---------------------------------------------------------------------
\ First authority root and publication
\ ---------------------------------------------------------------------

: _SMIG-ACQUISITION-SEQUENCE@  ( work -- sequence )
    DUP _SMW.OBSERVATION-PRESENT @ IF
        _SMW.CHECKPOINT OCHK.SEQUENCE @
    ELSE
        DROP 0
    THEN ;

: _SMIG-ROOT-METADATA?  ( root work -- flag )
    >R
    DUP SAR.FLAGS @ IF DROP R> DROP 0 EXIT THEN
    DUP SAR.LOGICAL-GENERATION @ IF DROP R> DROP 0 EXIT THEN
    DUP SAR.MUTATION-SEQUENCE @
        R@ _SMW.SOURCE-COUNT @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.ACQUISITION-SEQUENCE @
        R@ _SMIG-ACQUISITION-SEQUENCE@ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.SOURCE-COUNT @ R@ _SMW.SOURCE-COUNT @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.ATTEMPT-COUNT @ R@ _SMW.ATTEMPT-COUNT @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.OBSERVATION-COUNT @
        R@ _SMW.OBSERVATION-COUNT @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.NATIVE-COUNT @ R@ _SMW.NATIVE-COUNT @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.ACTIVE-COUNT @ IF DROP R> DROP 0 EXIT THEN
    DUP SAR.PROVENANCE @ R@ _SMW.PROVENANCE @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.SOURCE-COMPLETENESS @
        R@ _SMW.SOURCE-COMPLETENESS @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.OBSERVATION-COMPLETENESS @
        R@ _SMW.OBSERVATION-COMPLETENESS @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.AUTHORITY-ID R@ _SMW.AUTHORITY-ID RID= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.LEGACY-SOURCE-PRESENT @
        R@ _SMW.SOURCE-PRESENT @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.LEGACY-SOURCE-BYTES @
        R@ _SMW.SOURCE-RECORD-U @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.LEGACY-SOURCE-DIGEST R@ _SMW.SOURCE-DIGEST
        SHA3-256-LEN _SMIG-BYTES= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.LEGACY-OBSERVATION-PRESENT @
        R@ _SMW.OBSERVATION-PRESENT @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.LEGACY-OBSERVATION-BYTES @
        R@ _SMW.OBSERVATION-RECORD-U @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAR.LEGACY-OBSERVATION-DIGEST
        R@ _SMW.OBSERVATION-DIGEST
        SHA3-256-LEN _SMIG-BYTES= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    SAR.REMOVED-SOURCE-COUNT @ 0=
    R> DROP ;

: _SMIG-EDIT-STAGED-ROOT  ( work -- status )
    >R
    R@ _SMW.ADAPTER-WORK @ STREAMS-PA-AUTHORITY-ROOT@
    DUP 0= IF DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT THEN
    0 OVER SAR.LOGICAL-GENERATION !
    R@ _SMW.SOURCE-COUNT @ OVER SAR.MUTATION-SEQUENCE !
    R@ _SMIG-ACQUISITION-SEQUENCE@
        OVER SAR.ACQUISITION-SEQUENCE !
    R@ _SMW.SOURCE-COUNT @ OVER SAR.SOURCE-COUNT !
    R@ _SMW.ATTEMPT-COUNT @ OVER SAR.ATTEMPT-COUNT !
    R@ _SMW.OBSERVATION-COUNT @ OVER SAR.OBSERVATION-COUNT !
    R@ _SMW.NATIVE-COUNT @ OVER SAR.NATIVE-COUNT !
    0 OVER SAR.ACTIVE-COUNT !
    R@ _SMW.PROVENANCE @ OVER SAR.PROVENANCE !
    R@ _SMW.SOURCE-COMPLETENESS @
        OVER SAR.SOURCE-COMPLETENESS !
    R@ _SMW.OBSERVATION-COMPLETENESS @
        OVER SAR.OBSERVATION-COMPLETENESS !
    R@ _SMW.SOURCE-PRESENT @ OVER SAR.LEGACY-SOURCE-PRESENT !
    R@ _SMW.SOURCE-RECORD-U @ OVER SAR.LEGACY-SOURCE-BYTES !
    R@ _SMW.SOURCE-DIGEST OVER SAR.LEGACY-SOURCE-DIGEST
        SHA3-256-LEN MOVE
    R@ _SMW.OBSERVATION-PRESENT @
        OVER SAR.LEGACY-OBSERVATION-PRESENT !
    R@ _SMW.OBSERVATION-RECORD-U @
        OVER SAR.LEGACY-OBSERVATION-BYTES !
    R@ _SMW.OBSERVATION-DIGEST
        OVER SAR.LEGACY-OBSERVATION-DIGEST SHA3-256-LEN MOVE
    0 OVER SAR.REMOVED-SOURCE-COUNT !

    DUP R@ _SMIG-ROOT-METADATA? 0= IF
        DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    DROP
    R@ _SMW.ADAPTER @ R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-MARK-MUTATED
    R> DROP ;

: _SMIG-STAGE-CORE  ( work -- status )
    >R
    R@ _SMW.AUTHORITY-ID
    R@ _SMW.ADAPTER @ R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-FIRST-STAGE-BEGIN
    DUP IF R> DROP EXIT THEN DROP
    R@ _SMIG-IMPORT-ALL
    DUP IF R> DROP EXIT THEN DROP
    R@ _SMIG-VERIFY-ALL
    DUP IF R> DROP EXIT THEN DROP
    R@ _SMIG-EDIT-STAGED-ROOT
    DUP IF R> DROP EXIT THEN DROP
    -1 R@ _SMW.COMMIT-ATTEMPTED !
    R@ _SMW.ADAPTER @ R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-FIRST-STAGE-COMMIT
    R> DROP ;

: _SMIG-STAGE-DISPATCH  ( work -- )
    DUP _SMIG-STAGE-CORE SWAP _SMW.STAGE-STATUS ! ;

\ The repository owner callback may return only the repository status domain.
\ A clean pre-commit discard therefore returns repository OK and leaves the
\ semantic failure in STAGE-STATUS for the outer migration call.
: _SMIG-STAGING-BODY
  ( migration-work repository repository-work -- repository-status )
    2 PICK _SMW.REPOSITORY @ 2 PICK <> IF
        _SMIG-DROP3 STREAMS-REPOSITORY-S-INVALID EXIT
    THEN
    2 PICK _SMW.REPOSITORY-WORK @ OVER <> IF
        _SMIG-DROP3 STREAMS-REPOSITORY-S-INVALID EXIT
    THEN
    OVER STREAMS-REPOSITORY-ADAPTER@
        3 PICK _SMW.ADAPTER !
    DUP STREAMS-REPOSITORY-ADAPTER-WORK@
        3 PICK _SMW.ADAPTER-WORK !
    2DROP
    >R
    R@ _SMW.ADAPTER @ 0=
    R@ _SMW.ADAPTER-WORK @ 0= OR IF
        R> DROP STREAMS-REPOSITORY-S-INVALID EXIT
    THEN
    STREAMS-MIGRATION-S-FAULT R@ _SMW.STAGE-STATUS !
    R@ ['] _SMIG-STAGE-DISPATCH CATCH
    DUP IF
        2DROP
    ELSE
        DROP
    THEN
    R@ _SMW.STAGE-STATUS @ DUP 0= IF
        DROP R> DROP STREAMS-REPOSITORY-S-OK EXIT
    THEN
    R@ _SMW.COMMIT-ATTEMPTED @ IF
        R> DROP EXIT
    THEN
    DROP
    R@ _SMW.ADAPTER @ R@ _SMW.ADAPTER-WORK @
        STREAMS-PA-FIRST-STAGE-DISCARD
    DUP STREAMS-PA-S-OK = IF
        DROP R> DROP STREAMS-REPOSITORY-S-OK EXIT
    THEN
    DUP R@ _SMW.STAGE-STATUS !
    R> DROP ;

: _SMIG-REPOSITORY-LOAD  ( work -- status )
    >R
    R@ _SMW.REPOSITORY @ R@ _SMW.REPOSITORY-WORK @
        STREAMS-REPOSITORY-LOAD
    R> DROP ;

: _SMIG-PUBLISHED-ROOT?  ( work -- flag )
    >R
    R@ _SMW.REPOSITORY-WORK @
        STREAMS-REPOSITORY-AUTHORITY-ROOT@
    DUP 0= IF DROP R> DROP 0 EXIT THEN
    DUP STREAMS-AUTHORITY-ROOT-HEADER-VALID? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    R@ _SMIG-ROOT-METADATA?
    R> DROP ;

: _SMIG-RESOLVE-AFTER-COMMIT  ( work -- status )
    >R
    R@ _SMIG-REPOSITORY-LOAD
    DUP STREAMS-REPOSITORY-S-OK = IF
        DROP
        R@ _SMIG-PUBLISHED-ROOT? 0= IF
            R> DROP STREAMS-MIGRATION-S-VERIFY EXIT
        THEN
        -1 R@ _SMW.FLIP-CONFIRMED !
        R> DROP STREAMS-MIGRATION-S-OK EXIT
    THEN
    DUP STREAMS-REPOSITORY-S-ABSENT = IF
        DROP
        R@ _SMW.STAGE-STATUS @ DUP IF
            R> DROP EXIT
        THEN
        DROP R> DROP STREAMS-MIGRATION-S-CORRUPT EXIT
    THEN
    R> DROP ;

: _SMIG-RESOLVE-PREPARE-CONFLICT  ( work -- status )
    >R
    R@ _SMIG-REPOSITORY-LOAD
    DUP STREAMS-REPOSITORY-S-OK = IF
        DROP -1 R@ _SMW.FLIP-CONFIRMED !
        R> DROP STREAMS-MIGRATION-S-ALREADY EXIT
    THEN
    DUP STREAMS-REPOSITORY-S-ABSENT = IF
        DROP R> DROP STREAMS-MIGRATION-S-CONFLICT EXIT
    THEN
    R> DROP ;

: _SMIG-WITH-STAGING-OWNER  ( work -- status )
    >R
    R@ ['] _SMIG-STAGING-BODY
    R@ _SMW.REPOSITORY @ R@ _SMW.REPOSITORY-WORK @
        STREAMS-REPOSITORY-WITH-STAGING-OWNER
    R> DROP ;

\ ---------------------------------------------------------------------
\ Idempotent cold orchestration
\ ---------------------------------------------------------------------

: _SMIG-RUN-INNER  ( work -- status )
    DUP _SMIG-REPOSITORY-LOAD
    DUP STREAMS-REPOSITORY-S-OK = IF
        DROP
        -1 OVER _SMW.FLIP-CONFIRMED !
        DROP STREAMS-MIGRATION-S-ALREADY EXIT
    THEN
    DUP STREAMS-REPOSITORY-S-ABSENT <> IF NIP EXIT THEN
    DROP

    DUP _SMIG-LOAD-LEGACY
    DUP IF NIP EXIT THEN DROP
    DUP _SMIG-PREPARE-LEGACY
    DUP IF NIP EXIT THEN DROP

    DUP _SMW.REPOSITORY @
    OVER _SMW.REPOSITORY-WORK @
        STREAMS-REPOSITORY-STAGING-PREPARE
    DUP IF
        DUP STREAMS-REPOSITORY-S-CONFLICT = IF
            DROP _SMIG-RESOLVE-PREPARE-CONFLICT EXIT
        THEN
        NIP EXIT
    THEN
    DROP

    STREAMS-MIGRATION-S-OK OVER _SMW.STAGE-STATUS !
    0 OVER _SMW.COMMIT-ATTEMPTED !
    DUP _SMIG-WITH-STAGING-OWNER
    DUP 2 PICK _SMW.OWNER-STATUS !
    OVER _SMW.COMMIT-ATTEMPTED @ IF
        DROP _SMIG-RESOLVE-AFTER-COMMIT EXIT
    THEN
    DUP IF NIP EXIT THEN
    DROP
    DUP _SMW.STAGE-STATUS @ SWAP DROP ;

: _SMIG-RUN-DISPATCH  ( work -- )
    DUP _SMIG-RUN-INNER SWAP _SMW.STATUS ! ;

: STREAMS-MIGRATION-RUN
  ( authority-id source-store observation-store repository repository-work migration-work -- status )
    DUP STREAMS-MIGRATION-WORK-VALID? 0= IF
        _SMIG-DROP6 STREAMS-MIGRATION-S-INVALID EXIT
    THEN
    DUP _SMW.BUSY @ IF
        _SMIG-DROP6 STREAMS-MIGRATION-S-BUSY EXIT
    THEN
    5 PICK 5 PICK 5 PICK 5 PICK 5 PICK 5 PICK
        _SMIG-RUN-ARGS? 0= IF
        _SMIG-DROP6 STREAMS-MIGRATION-S-INVALID EXIT
    THEN
    >R
    -1 R@ _SMW.BUSY !
    R@ _SMIG-RUN-RESET
    4 PICK R@ _SMW.AUTHORITY-ID RID-COPY
    3 PICK R@ _SMW.SOURCE-STORE !
    2 PICK R@ _SMW.OBSERVATION-STORE !
    1 PICK R@ _SMW.REPOSITORY !
    DUP R@ _SMW.REPOSITORY-WORK !
    _SMIG-DROP5

    R@ ['] _SMIG-RUN-DISPATCH CATCH
    DUP IF
        2DROP
        STREAMS-MIGRATION-S-FAULT R@ _SMW.STATUS !
    ELSE
        DROP
    THEN
    0 R@ _SMW.BUSY !
    R@ _SMW.STATUS @ R> DROP ;
