\ =====================================================================
\ payload-carrier.f - caller-owned segmented Streams payload carrier
\ =====================================================================
\ A carrier owns no allocation, I/O, persistence, or process-global
\ workspace.  The caller supplies the descriptor, a fixed segment table,
\ and every writable byte span named by that table.
\
\ Segments form one logical byte string in table order.  APPEND packs each
\ segment before advancing to the next.  SEAL hashes the used prefixes in
\ that same order and freezes the logical length.  Exact reads never expose
\ mutable segment-table entries and revalidate the whole-payload digest
\ before copying bytes.
\
\ Release callback:
\   RELEASE  ( segments-a segment-count release-context -- error )
\
\ A zero release XT means the segment geometry remains caller-owned and may
\ be RESET after CLOSE.  A nonzero release XT makes the binding one-shot:
\ CLOSE wipes when requested, calls RELEASE exactly once, and then clears
\ every live geometry and callback pointer even when RELEASE fails or throws.
\ =====================================================================

PROVIDED akashic-streams-payload-carrier

REQUIRE ../../../utils/memory-span.f
REQUIRE ../../../math/sha3.f

\ ---------------------------------------------------------------------
\ Closed status, state, and flag domains
\ ---------------------------------------------------------------------

0 CONSTANT STREAMS-PAYLOAD-S-OK
1 CONSTANT STREAMS-PAYLOAD-S-INVALID
2 CONSTANT STREAMS-PAYLOAD-S-BUSY
3 CONSTANT STREAMS-PAYLOAD-S-CAPACITY
4 CONSTANT STREAMS-PAYLOAD-S-STALE
5 CONSTANT STREAMS-PAYLOAD-S-CLEANUP
6 CONSTANT STREAMS-PAYLOAD-S-INTEGRITY

1 CONSTANT STREAMS-PAYLOAD-STATE-READY
2 CONSTANT STREAMS-PAYLOAD-STATE-BUILDING
3 CONSTANT STREAMS-PAYLOAD-STATE-SEALED
4 CONSTANT STREAMS-PAYLOAD-STATE-CLOSING
5 CONSTANT STREAMS-PAYLOAD-STATE-CLOSED
6 CONSTANT STREAMS-PAYLOAD-STATE-CLEANUP-FAILED

1 CONSTANT STREAMS-PAYLOAD-F-WIPE

0x7FFFFFFFFFFFFFFF CONSTANT _SPAY-CELL-MAX

: _SPAY-ZERO?  ( address length -- flag )
    DUP 0< IF 2DROP 0 EXIT THEN
    0 ?DO
        DUP I + C@ IF DROP 0 UNLOOP EXIT THEN
    LOOP
    DROP -1 ;

\ =====================================================================
\ Caller-owned segment table
\ =====================================================================

 0 CONSTANT _SPSEG-DATA
 8 CONSTANT _SPSEG-CAPACITY
16 CONSTANT _SPSEG-USED
24 CONSTANT STREAMS-PAYLOAD-SEGMENT-SIZE

: SPSEG.DATA      ( segment -- a ) _SPSEG-DATA + ;
: SPSEG.CAPACITY  ( segment -- a ) _SPSEG-CAPACITY + ;
: SPSEG.USED      ( segment -- a ) _SPSEG-USED + ;

-1 1 RSHIFT STREAMS-PAYLOAD-SEGMENT-SIZE /
    CONSTANT _SPAY-SEGMENT-COUNT-MAX

: STREAMS-PAYLOAD-SEGMENT-BYTES  ( count -- bytes|0 )
    DUP 1 < IF DROP 0 EXIT THEN
    DUP _SPAY-SEGMENT-COUNT-MAX U> IF DROP 0 EXIT THEN
    STREAMS-PAYLOAD-SEGMENT-SIZE * ;

: _SPAY-SEGMENT-AT  ( index segments -- segment )
    SWAP STREAMS-PAYLOAD-SEGMENT-SIZE * + ;

: STREAMS-PAYLOAD-SEGMENT-INIT  ( data-a capacity segment -- status )
    >R
    R@ 0= IF 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT THEN
    R@ STREAMS-PAYLOAD-SEGMENT-SIZE MSPAN-NONWRAPPING? 0= IF
        2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP 1 < IF 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT THEN
    OVER 0= IF 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT THEN
    2DUP MSPAN-NONWRAPPING? 0= IF
        2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    2DUP R@ STREAMS-PAYLOAD-SEGMENT-SIZE MSPAN-OVERLAP? IF
        2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ STREAMS-PAYLOAD-SEGMENT-SIZE 0 FILL
    DUP R@ SPSEG.CAPACITY !
    OVER R@ SPSEG.DATA !
    2DROP R> DROP STREAMS-PAYLOAD-S-OK ;

: _SPSEG-LIVE?  ( segment -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP STREAMS-PAYLOAD-SEGMENT-SIZE MSPAN-NONWRAPPING? 0= IF
        DROP 0 EXIT
    THEN
    DUP SPSEG.DATA @ 0= IF DROP 0 EXIT THEN
    DUP SPSEG.CAPACITY @ 1 < IF DROP 0 EXIT THEN
    DUP SPSEG.DATA @ OVER SPSEG.CAPACITY @
        MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP SPSEG.USED @ DUP 0<
        SWAP 2 PICK SPSEG.CAPACITY @ > OR IF DROP 0 EXIT THEN
    DUP SPSEG.DATA @ OVER SPSEG.CAPACITY @
        2 PICK STREAMS-PAYLOAD-SEGMENT-SIZE
        MSPAN-OVERLAP? 0= SWAP DROP ;

\ =====================================================================
\ Carrier descriptor
\ =====================================================================

0x53525041594C4421 CONSTANT _SPAY-MAGIC  \ "SRPAYLD!"

  0 CONSTANT _SPAY-MAGIC-O
  8 CONSTANT _SPAY-SIZE
 16 CONSTANT _SPAY-STATE
 24 CONSTANT _SPAY-BUSY
 32 CONSTANT _SPAY-GENERATION
 40 CONSTANT _SPAY-PROFILE
 48 CONSTANT _SPAY-FLAGS
 56 CONSTANT _SPAY-SEGMENTS
 64 CONSTANT _SPAY-SEGMENT-N
 72 CONSTANT _SPAY-BYTE-CAP
 80 CONSTANT _SPAY-BYTE-U
 88 CONSTANT _SPAY-RELEASE-XT
 96 CONSTANT _SPAY-RELEASE-CONTEXT
104 CONSTANT _SPAY-CLEANUP-ERROR
112 CONSTANT _SPAY-DIGEST
144 CONSTANT _SPAY-BINDING-EPOCH
152 CONSTANT _SPAY-GEOMETRY-DIGEST
\ Private, descriptor-owned call scratch.  Public calls clear it on return.
184 CONSTANT _SPAY-ARG-A
192 CONSTANT _SPAY-ARG-U
200 CONSTANT _SPAY-ARG-OFFSET
208 CONSTANT _SPAY-ARG-ORIGINAL-U
216 CONSTANT _SPAY-ARG-GENERATION
224 CONSTANT STREAMS-PAYLOAD-SIZE

: SPAY.MAGIC            ( payload -- a ) _SPAY-MAGIC-O + ;
: SPAY.SIZE             ( payload -- a ) _SPAY-SIZE + ;
: SPAY.STATE            ( payload -- a ) _SPAY-STATE + ;
: SPAY.BUSY             ( payload -- a ) _SPAY-BUSY + ;
: SPAY.GENERATION       ( payload -- a ) _SPAY-GENERATION + ;
: SPAY.PROFILE          ( payload -- a ) _SPAY-PROFILE + ;
: SPAY.FLAGS            ( payload -- a ) _SPAY-FLAGS + ;
: SPAY.SEGMENTS         ( payload -- a ) _SPAY-SEGMENTS + ;
: SPAY.SEGMENT-N        ( payload -- a ) _SPAY-SEGMENT-N + ;
: SPAY.BYTE-CAP         ( payload -- a ) _SPAY-BYTE-CAP + ;
: SPAY.BYTE-U           ( payload -- a ) _SPAY-BYTE-U + ;
: SPAY.RELEASE-XT       ( payload -- a ) _SPAY-RELEASE-XT + ;
: SPAY.RELEASE-CONTEXT  ( payload -- a ) _SPAY-RELEASE-CONTEXT + ;
: SPAY.CLEANUP-ERROR    ( payload -- a ) _SPAY-CLEANUP-ERROR + ;
: SPAY.DIGEST           ( payload -- digest ) _SPAY-DIGEST + ;
: SPAY.BINDING-EPOCH    ( payload -- a ) _SPAY-BINDING-EPOCH + ;
: SPAY.GEOMETRY-DIGEST  ( payload -- digest ) _SPAY-GEOMETRY-DIGEST + ;

: _SPAY.ARG-A           ( payload -- a ) _SPAY-ARG-A + ;
: _SPAY.ARG-U           ( payload -- a ) _SPAY-ARG-U + ;
: _SPAY.ARG-OFFSET      ( payload -- a ) _SPAY-ARG-OFFSET + ;
: _SPAY.ARG-ORIGINAL-U  ( payload -- a ) _SPAY-ARG-ORIGINAL-U + ;
: _SPAY.ARG-GENERATION  ( payload -- a ) _SPAY-ARG-GENERATION + ;

: _SPAY-SEGMENT  ( index payload -- segment )
    SPAY.SEGMENTS @ _SPAY-SEGMENT-AT ;

: _SPAY-HEADER?  ( payload -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP STREAMS-PAYLOAD-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP SPAY.MAGIC @ _SPAY-MAGIC =
    SWAP SPAY.SIZE @ STREAMS-PAYLOAD-SIZE = AND ;

: _SPAY-FLAGS?  ( flags -- flag )
    DUP 0< IF DROP 0 EXIT THEN
    STREAMS-PAYLOAD-F-WIPE INVERT AND 0= ;

: _SPAY-STATE?  ( state -- flag )
    DUP STREAMS-PAYLOAD-STATE-READY >=
    SWAP STREAMS-PAYLOAD-STATE-CLEANUP-FAILED <= AND ;

\ ---------------------------------------------------------------------
\ Geometry and packed-length validation
\ ---------------------------------------------------------------------

: _SPAY-PAIRWISE-DISJOINT?  ( segments count -- flag )
    DUP 0 ?DO
        I 2 PICK _SPAY-SEGMENT-AT
        DUP SPSEG.DATA @ SWAP SPSEG.CAPACITY @
        2 PICK I 1+ ?DO
            2DUP I 6 PICK _SPAY-SEGMENT-AT
            DUP SPSEG.DATA @ SWAP SPSEG.CAPACITY @
            MSPAN-OVERLAP? IF
                2DROP 2DROP 0 UNLOOP UNLOOP EXIT
            THEN
        LOOP
        2DROP
    LOOP
    2DROP -1 ;

: _SPAY-RAW-CAPACITY  ( segments count -- capacity flag )
    0
    1 PICK 0 ?DO
        I 3 PICK _SPAY-SEGMENT-AT SPSEG.CAPACITY @
        DUP _SPAY-CELL-MAX SWAP - 2 PICK SWAP > IF
            2DROP 2DROP 0 0 UNLOOP EXIT
        THEN
        +
    LOOP
    NIP NIP -1 ;

: _SPAY-RAW-GEOMETRY?  ( segments count payload -- capacity flag )
    DUP 0= IF 2DROP DROP 0 0 EXIT THEN
    2 PICK 0= IF 2DROP DROP 0 0 EXIT THEN
    OVER STREAMS-PAYLOAD-SEGMENT-BYTES DUP 0= IF
        DROP 2DROP DROP 0 0 EXIT
    THEN
    3 PICK SWAP MSPAN-NONWRAPPING? 0= IF
        2DROP DROP 0 0 EXIT
    THEN
    2 PICK 2 PICK STREAMS-PAYLOAD-SEGMENT-BYTES
        2 PICK STREAMS-PAYLOAD-SIZE MSPAN-OVERLAP? IF
        2DROP DROP 0 0 EXIT
    THEN
    OVER 0 ?DO
        I 3 PICK _SPAY-SEGMENT-AT
        DUP _SPSEG-LIVE? 0= IF
            DROP 2DROP DROP 0 0 UNLOOP EXIT
        THEN
        DUP SPSEG.DATA @ OVER SPSEG.CAPACITY @
            5 PICK 5 PICK STREAMS-PAYLOAD-SEGMENT-BYTES
            MSPAN-OVERLAP? IF
            DROP 2DROP DROP 0 0 UNLOOP EXIT
        THEN
        DUP SPSEG.DATA @ OVER SPSEG.CAPACITY @
            3 PICK STREAMS-PAYLOAD-SIZE MSPAN-OVERLAP? IF
            DROP 2DROP DROP 0 0 UNLOOP EXIT
        THEN
        DROP
    LOOP
    2 PICK 2 PICK _SPAY-PAIRWISE-DISJOINT? 0= IF
        2DROP DROP 0 0 EXIT
    THEN
    2 PICK 2 PICK _SPAY-RAW-CAPACITY
    >R >R 2DROP DROP R> R> ;

: _SPAY-USED-ZERO?  ( payload -- flag )
    DUP SPAY.SEGMENT-N @ 0 ?DO
        I OVER _SPAY-SEGMENT SPSEG.USED @ IF
            DROP 0 UNLOOP EXIT
        THEN
    LOOP
    DROP -1 ;

: _SPAY-USED-SUM  ( payload -- used flag )
    0
    OVER SPAY.SEGMENT-N @ 0 ?DO
        I 2 PICK _SPAY-SEGMENT SPSEG.USED @
        DUP _SPAY-CELL-MAX SWAP - 2 PICK SWAP > IF
            2DROP DROP 0 0 UNLOOP EXIT
        THEN
        +
    LOOP
    NIP -1 ;

: _SPAY-PACKED?  ( payload -- flag )
    0
    OVER SPAY.SEGMENT-N @ 0 ?DO
        I 2 PICK _SPAY-SEGMENT
        DUP SPSEG.USED @ SWAP SPSEG.CAPACITY @
        2 PICK IF
            OVER IF 2DROP 2DROP 0 UNLOOP EXIT THEN
        THEN
        < IF DROP -1 THEN
    LOOP
    2DROP -1 ;

: _SPAY-LIVE-GEOMETRY?  ( payload -- flag )
    DUP SPAY.SEGMENTS @
    OVER SPAY.SEGMENT-N @
    2 PICK _SPAY-RAW-GEOMETRY?
    DUP 0= IF 2DROP DROP 0 EXIT THEN
    DROP
    OVER SPAY.BYTE-CAP @ <> IF DROP 0 EXIT THEN
    DUP _SPAY-PACKED? 0= IF DROP 0 EXIT THEN
    DUP _SPAY-USED-SUM
    DUP 0= IF 2DROP DROP 0 EXIT THEN
    DROP
    OVER SPAY.BYTE-U @ = NIP ;

: _SPAY-HASH  ( destination payload -- )
    SWAP >R
    SHA3-256-BEGIN
    DUP SPAY.SEGMENT-N @ 0 ?DO
        I OVER _SPAY-SEGMENT
        DUP SPSEG.DATA @ SWAP SPSEG.USED @ SHA3-256-ADD
    LOOP
    DROP R> SHA3-256-END ;

: _SPAY-HASH-GEOMETRY  ( destination payload -- )
    SWAP >R
    SHA3-256-BEGIN
    DUP SPAY.SEGMENTS 8 SHA3-256-ADD
    DUP SPAY.SEGMENT-N 8 SHA3-256-ADD
    DUP SPAY.SEGMENT-N @ 0 ?DO
        I OVER _SPAY-SEGMENT
        DUP SPSEG.DATA 8 SHA3-256-ADD
        SPSEG.CAPACITY 8 SHA3-256-ADD
    LOOP
    DROP R> SHA3-256-END ;

: _SPAY-GEOMETRY-EXACT?  ( payload -- flag )
    SHA3-256-BEGIN
    DUP SPAY.SEGMENTS 8 SHA3-256-ADD
    DUP SPAY.SEGMENT-N 8 SHA3-256-ADD
    DUP SPAY.SEGMENT-N @ 0 ?DO
        I OVER _SPAY-SEGMENT
        DUP SPSEG.DATA 8 SHA3-256-ADD
        SPSEG.CAPACITY 8 SHA3-256-ADD
    LOOP
    DUP SPAY.GEOMETRY-DIGEST SHA3-256-END-COMPARE SWAP DROP ;

: _SPAY-DIGEST-EXACT?  ( payload -- flag )
    SHA3-256-BEGIN
    DUP SPAY.SEGMENT-N @ 0 ?DO
        I OVER _SPAY-SEGMENT
        DUP SPSEG.DATA @ SWAP SPSEG.USED @ SHA3-256-ADD
    LOOP
    DUP SPAY.DIGEST SHA3-256-END-COMPARE SWAP DROP ;

: _SPAY-LIVE-STATE?  ( state -- flag )
    DUP STREAMS-PAYLOAD-STATE-READY =
    OVER STREAMS-PAYLOAD-STATE-BUILDING = OR
    OVER STREAMS-PAYLOAD-STATE-SEALED = OR
    SWAP STREAMS-PAYLOAD-STATE-CLOSING = OR ;

: _SPAY-REINITABLE?  ( payload -- flag )
    DUP _SPAY-HEADER? 0= IF DROP 0 EXIT THEN
    DUP SPAY.BUSY @ IF DROP 0 EXIT THEN
    DUP SPAY.GENERATION @ 0< IF DROP 0 EXIT THEN
    DUP SPAY.BINDING-EPOCH @ 1 < IF DROP 0 EXIT THEN
    DUP SPAY.PROFILE @ 1 < IF DROP 0 EXIT THEN
    DUP SPAY.FLAGS @ _SPAY-FLAGS? 0= IF DROP 0 EXIT THEN
    DUP SPAY.BYTE-U @ IF DROP 0 EXIT THEN
    DUP SPAY.DIGEST SHA3-256-LEN _SPAY-ZERO? 0= IF DROP 0 EXIT THEN
    DUP SPAY.RELEASE-XT @ IF DROP 0 EXIT THEN
    DUP SPAY.RELEASE-CONTEXT @ IF DROP 0 EXIT THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-CLOSED = IF
        SPAY.CLEANUP-ERROR @ 0= EXIT
    THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-CLEANUP-FAILED = IF
        DUP SPAY.CLEANUP-ERROR @ 0<>
        OVER SPAY.SEGMENTS @ 0= AND
        OVER SPAY.SEGMENT-N @ 0= AND
        OVER SPAY.BYTE-CAP @ 0= AND
        SWAP SPAY.GEOMETRY-DIGEST SHA3-256-LEN _SPAY-ZERO? AND EXIT
    THEN
    DROP 0 ;

: STREAMS-PAYLOAD-BOUND?  ( payload -- flag )
    DUP _SPAY-HEADER? 0= IF DROP 0 EXIT THEN
    DUP SPAY.STATE @ _SPAY-STATE? 0= IF DROP 0 EXIT THEN
    DUP SPAY.BUSY @ DUP 0<> SWAP -1 <> AND IF DROP 0 EXIT THEN
    DUP SPAY.GENERATION @ 0< IF DROP 0 EXIT THEN
    DUP SPAY.PROFILE @ 1 < IF DROP 0 EXIT THEN
    DUP SPAY.FLAGS @ _SPAY-FLAGS? 0= IF DROP 0 EXIT THEN
    DUP SPAY.BINDING-EPOCH @ 1 < IF DROP 0 EXIT THEN
    DUP SPAY.RELEASE-XT @ 0=
        OVER SPAY.RELEASE-CONTEXT @ 0<> AND IF DROP 0 EXIT THEN
    DUP SPAY.STATE @ _SPAY-LIVE-STATE? IF
        DUP _SPAY-LIVE-GEOMETRY? 0= IF DROP 0 EXIT THEN
        DUP _SPAY-GEOMETRY-EXACT? 0= IF DROP 0 EXIT THEN
        DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-READY = IF
            DUP SPAY.BYTE-U @ 0=
            OVER _SPAY-USED-ZERO? AND
            OVER SPAY.DIGEST SHA3-256-LEN _SPAY-ZERO? AND
            SWAP SPAY.CLEANUP-ERROR @ 0= AND EXIT
        THEN
        DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-BUILDING = IF
            DUP SPAY.DIGEST SHA3-256-LEN _SPAY-ZERO?
            SWAP SPAY.CLEANUP-ERROR @ 0= AND EXIT
        THEN
        DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-SEALED = IF
            SPAY.CLEANUP-ERROR @ 0= EXIT
        THEN
        DROP -1 EXIT
    THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-CLEANUP-FAILED = IF
        DUP SPAY.CLEANUP-ERROR @ 0<>
        OVER SPAY.SEGMENTS @ 0= AND
        OVER SPAY.SEGMENT-N @ 0= AND
        OVER SPAY.BYTE-CAP @ 0= AND
        OVER SPAY.BYTE-U @ 0= AND
        OVER SPAY.DIGEST SHA3-256-LEN _SPAY-ZERO? AND
        OVER SPAY.GEOMETRY-DIGEST SHA3-256-LEN _SPAY-ZERO? AND
        OVER SPAY.RELEASE-XT @ 0= AND
        SWAP SPAY.RELEASE-CONTEXT @ 0= AND EXIT
    THEN
    \ CLOSED either retains reusable geometry or has cleared a one-shot bind.
    DUP SPAY.CLEANUP-ERROR @ IF DROP 0 EXIT THEN
    DUP SPAY.BYTE-U @ IF DROP 0 EXIT THEN
    DUP SPAY.DIGEST SHA3-256-LEN _SPAY-ZERO? 0= IF DROP 0 EXIT THEN
    DUP SPAY.SEGMENTS @ 0= IF
        DUP SPAY.SEGMENT-N @ 0=
        OVER SPAY.BYTE-CAP @ 0= AND
        OVER SPAY.GEOMETRY-DIGEST SHA3-256-LEN _SPAY-ZERO? AND
        OVER SPAY.RELEASE-XT @ 0= AND
        SWAP SPAY.RELEASE-CONTEXT @ 0= AND EXIT
    THEN
    DUP SPAY.RELEASE-XT @ IF DROP 0 EXIT THEN
    DUP _SPAY-LIVE-GEOMETRY? 0= IF DROP 0 EXIT THEN
    DUP _SPAY-GEOMETRY-EXACT?
    SWAP _SPAY-USED-ZERO? AND ;

: STREAMS-PAYLOAD-VALID?  ( payload -- flag )
    DUP STREAMS-PAYLOAD-BOUND? 0= IF DROP 0 EXIT THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-SEALED = IF
        _SPAY-DIGEST-EXACT? EXIT
    THEN
    DROP -1 ;

: STREAMS-PAYLOAD-UNIFORM-GEOMETRY?
  ( expected-segments expected-segment-capacity payload -- flag )
    DUP STREAMS-PAYLOAD-BOUND? 0= IF 2DROP DROP 0 EXIT THEN
    2 PICK 1 < IF 2DROP DROP 0 EXIT THEN
    OVER 1 < IF 2DROP DROP 0 EXIT THEN
    DUP SPAY.SEGMENT-N @ 3 PICK <> IF 2DROP DROP 0 EXIT THEN
    0
    BEGIN
        DUP 4 PICK <
    WHILE
        DUP 2 PICK _SPAY-SEGMENT SPSEG.CAPACITY @
            3 PICK <> IF 2DROP 2DROP 0 EXIT THEN
        1+
    REPEAT
    2DROP 2DROP -1 ;

\ ---------------------------------------------------------------------
\ Initialization and lifecycle reset
\ ---------------------------------------------------------------------

: STREAMS-PAYLOAD-INIT
  ( segments count profile flags release-xt release-context payload -- status )
    >R
    R@ 0= IF
        2DROP 2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ STREAMS-PAYLOAD-SIZE MSPAN-NONWRAPPING? 0= IF
        2DROP 2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ _SPAY-HEADER? IF
        R@ SPAY.BUSY @ IF
            2DROP 2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-BUSY EXIT
        THEN
        R@ SPAY.STATE @ DUP STREAMS-PAYLOAD-STATE-READY =
        OVER STREAMS-PAYLOAD-STATE-BUILDING = OR
        OVER STREAMS-PAYLOAD-STATE-SEALED = OR
        SWAP STREAMS-PAYLOAD-STATE-CLOSING = OR IF
            2DROP 2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-BUSY EXIT
        THEN
        R@ _SPAY-REINITABLE? 0= IF
            2DROP 2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
        THEN
        R@ SPAY.GENERATION @ _SPAY-CELL-MAX >= IF
            2DROP 2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-CAPACITY EXIT
        THEN
        R@ SPAY.BINDING-EPOCH @ _SPAY-CELL-MAX >= IF
            2DROP 2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-CAPACITY EXIT
        THEN
    THEN
    5 PICK 5 PICK R@ _SPAY-RAW-GEOMETRY?
    DUP 0= IF
        2DROP 2DROP 2DROP 2DROP R> DROP
        STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DROP
    \ The raw table must be unused at publication.
    6 PICK 6 PICK _SPAY-PAIRWISE-DISJOINT? 0= IF
        2DROP 2DROP 2DROP DROP R> DROP
        STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    6 PICK 6 PICK 0 ?DO
        I 1 PICK _SPAY-SEGMENT-AT SPSEG.USED @ IF
            2DROP 2DROP 2DROP 2DROP R> DROP
            STREAMS-PAYLOAD-S-INVALID UNLOOP EXIT
        THEN
    LOOP
    DROP
    4 PICK 1 < IF
        2DROP 2DROP 2DROP DROP R> DROP
        STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    3 PICK _SPAY-FLAGS? 0= IF
        2DROP 2DROP 2DROP DROP R> DROP
        STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    2 PICK 2 PICK
    OVER 0= IF NIP 0= ELSE 2DROP -1 THEN 0= IF
        2DROP 2DROP 2DROP DROP R> DROP
        STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ _SPAY-HEADER? IF
        R@ SPAY.GENERATION @
        R@ SPAY.BINDING-EPOCH @ 1+
    ELSE
        0 1
    THEN
    R@ STREAMS-PAYLOAD-SIZE 0 FILL
    DUP R@ SPAY.BINDING-EPOCH ! DROP
    DUP R@ SPAY.GENERATION ! DROP
    _SPAY-MAGIC R@ SPAY.MAGIC !
    STREAMS-PAYLOAD-SIZE R@ SPAY.SIZE !
    STREAMS-PAYLOAD-STATE-READY R@ SPAY.STATE !
    R@ SPAY.BYTE-CAP !
    R@ SPAY.RELEASE-CONTEXT !
    R@ SPAY.RELEASE-XT !
    R@ SPAY.FLAGS !
    R@ SPAY.PROFILE !
    R@ SPAY.SEGMENT-N !
    R@ SPAY.SEGMENTS !
    R@ SPAY.GEOMETRY-DIGEST R@ _SPAY-HASH-GEOMETRY
    R> DROP STREAMS-PAYLOAD-S-OK ;

: _SPAY-CLEAR-ARGS  ( payload -- )
    0 OVER _SPAY.ARG-A !
    0 OVER _SPAY.ARG-U !
    0 OVER _SPAY.ARG-OFFSET !
    0 OVER _SPAY.ARG-ORIGINAL-U !
    0 SWAP _SPAY.ARG-GENERATION ! ;

: _SPAY-LEAVE  ( status payload -- status )
    DUP _SPAY-CLEAR-ARGS
    0 SWAP SPAY.BUSY ! ;

: _SPAY-WIPE-BUFFERS  ( payload -- )
    DUP SPAY.SEGMENTS @ 0= IF DROP EXIT THEN
    DUP SPAY.SEGMENT-N @ 0 ?DO
        I OVER _SPAY-SEGMENT
        DUP SPSEG.DATA @ SWAP SPSEG.CAPACITY @ 0 FILL
    LOOP
    DROP ;

: _SPAY-CLEAR-CONTENT  ( payload -- )
    DUP SPAY.SEGMENTS @ IF
        DUP SPAY.SEGMENT-N @ 0 ?DO
            0 I 2 PICK _SPAY-SEGMENT SPSEG.USED !
        LOOP
    THEN
    0 OVER SPAY.BYTE-U !
    SPAY.DIGEST SHA3-256-LEN 0 FILL ;

: _SPAY-RESET-BODY  ( payload -- new-generation status )
    DUP STREAMS-PAYLOAD-VALID? 0= IF
        DROP 0 STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP _SPAY.ARG-GENERATION @ OVER SPAY.GENERATION @ <> IF
        DROP 0 STREAMS-PAYLOAD-S-STALE EXIT
    THEN
    DUP SPAY.STATE @ DUP STREAMS-PAYLOAD-STATE-READY =
        OVER STREAMS-PAYLOAD-STATE-CLOSED = OR
        OVER STREAMS-PAYLOAD-STATE-BUILDING = OR 0= IF
        2DROP 0 STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    STREAMS-PAYLOAD-STATE-BUILDING = IF
        DUP SPAY.BYTE-U @ IF
            DROP 0 STREAMS-PAYLOAD-S-INVALID EXIT
        THEN
    THEN
    DUP SPAY.SEGMENTS @ 0= IF
        DROP 0 STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP SPAY.GENERATION @ _SPAY-CELL-MAX >= IF
        DROP 0 STREAMS-PAYLOAD-S-CAPACITY EXIT
    THEN
    DUP SPAY.FLAGS @ STREAMS-PAYLOAD-F-WIPE AND IF
        DUP _SPAY-WIPE-BUFFERS
    THEN
    DUP _SPAY-CLEAR-CONTENT
    0 OVER SPAY.CLEANUP-ERROR !
    1 OVER SPAY.GENERATION +!
    STREAMS-PAYLOAD-STATE-BUILDING OVER SPAY.STATE !
    SPAY.GENERATION @ STREAMS-PAYLOAD-S-OK ;

: STREAMS-PAYLOAD-RESET  ( expected-generation payload -- new-generation status )
    >R
    R@ _SPAY-HEADER? 0= IF DROP R> DROP 0 STREAMS-PAYLOAD-S-INVALID EXIT THEN
    R@ SPAY.BUSY @ IF DROP R> DROP 0 STREAMS-PAYLOAD-S-BUSY EXIT THEN
    R@ _SPAY.ARG-GENERATION !
    -1 R@ SPAY.BUSY !
    R@ _SPAY-RESET-BODY
    R> _SPAY-LEAVE ;

\ ---------------------------------------------------------------------
\ Transactional ordered append and sealing
\ ---------------------------------------------------------------------

: _SPAY-ARG-SPAN-DISJOINT?  ( payload -- flag )
    DUP _SPAY.ARG-A @ OVER _SPAY.ARG-ORIGINAL-U @
        2 PICK STREAMS-PAYLOAD-SIZE MSPAN-OVERLAP? IF DROP 0 EXIT THEN
    DUP _SPAY.ARG-A @ OVER _SPAY.ARG-ORIGINAL-U @
        2 PICK SPAY.SEGMENTS @
        3 PICK SPAY.SEGMENT-N @ STREAMS-PAYLOAD-SEGMENT-BYTES
        MSPAN-OVERLAP? IF DROP 0 EXIT THEN
    DUP SPAY.SEGMENT-N @ 0 ?DO
        DUP _SPAY.ARG-A @ OVER _SPAY.ARG-ORIGINAL-U @
        I 3 PICK _SPAY-SEGMENT
        DUP SPSEG.DATA @ SWAP SPSEG.CAPACITY @
        MSPAN-OVERLAP? IF DROP 0 UNLOOP EXIT THEN
    LOOP
    DROP -1 ;

: _SPAY-APPEND-BODY  ( payload -- status )
    DUP STREAMS-PAYLOAD-VALID? 0= IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP _SPAY.ARG-GENERATION @ OVER SPAY.GENERATION @ <> IF
        DROP STREAMS-PAYLOAD-S-STALE EXIT
    THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-BUILDING <> IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP _SPAY.ARG-U @ DUP 0< IF
        2DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP 0> 2 PICK _SPAY.ARG-A @ 0= AND IF
        2DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    OVER _SPAY.ARG-A @ SWAP MSPAN-NONWRAPPING? 0= IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP _SPAY-ARG-SPAN-DISJOINT? 0= IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP SPAY.BYTE-CAP @ OVER SPAY.BYTE-U @ -
        OVER _SPAY.ARG-U @ < IF
        DROP STREAMS-PAYLOAD-S-CAPACITY EXIT
    THEN
    DUP SPAY.SEGMENT-N @ 0 ?DO
        DUP _SPAY.ARG-U @ 0= IF
            DROP STREAMS-PAYLOAD-S-OK UNLOOP EXIT
        THEN
        I OVER _SPAY-SEGMENT
        DUP SPSEG.CAPACITY @ OVER SPSEG.USED @ -
        2 PICK _SPAY.ARG-U @ OVER MIN >R DROP
        R@ IF
            OVER _SPAY.ARG-A @
            1 PICK SPSEG.DATA @ 2 PICK SPSEG.USED @ +
            R@ MOVE
            R@ 1 PICK SPSEG.USED +!
            R@ 2 PICK _SPAY.ARG-A +!
            R@ NEGATE 2 PICK _SPAY.ARG-U +!
            R@ 2 PICK SPAY.BYTE-U +!
        THEN
        R> DROP DROP
    LOOP
    DUP _SPAY.ARG-U @ IF
        DROP STREAMS-PAYLOAD-S-INVALID
    ELSE
        DROP STREAMS-PAYLOAD-S-OK
    THEN ;

: STREAMS-PAYLOAD-APPEND  ( source-a source-u generation payload -- status )
    >R
    R@ _SPAY-HEADER? 0= IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ SPAY.BUSY @ IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-BUSY EXIT
    THEN
    R@ STREAMS-PAYLOAD-VALID? 0= IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ _SPAY.ARG-GENERATION !
    DUP R@ _SPAY.ARG-U !
    DUP R@ _SPAY.ARG-ORIGINAL-U !
    OVER R@ _SPAY.ARG-A !
    2DROP
    -1 R@ SPAY.BUSY !
    R@ _SPAY-APPEND-BODY
    R> _SPAY-LEAVE ;

: _SPAY-SEAL-BODY  ( payload -- status )
    DUP STREAMS-PAYLOAD-VALID? 0= IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP _SPAY.ARG-GENERATION @ OVER SPAY.GENERATION @ <> IF
        DROP STREAMS-PAYLOAD-S-STALE EXIT
    THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-BUILDING <> IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP SPAY.DIGEST OVER _SPAY-HASH
    STREAMS-PAYLOAD-STATE-SEALED SWAP SPAY.STATE !
    STREAMS-PAYLOAD-S-OK ;

: STREAMS-PAYLOAD-SEAL  ( generation payload -- status )
    >R
    R@ _SPAY-HEADER? 0= IF DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT THEN
    R@ SPAY.BUSY @ IF DROP R> DROP STREAMS-PAYLOAD-S-BUSY EXIT THEN
    R@ _SPAY.ARG-GENERATION !
    -1 R@ SPAY.BUSY !
    R@ _SPAY-SEAL-BODY
    R> _SPAY-LEAVE ;

: STREAMS-PAYLOAD-EXACT?  ( generation payload -- flag )
    >R
    R@ STREAMS-PAYLOAD-BOUND? 0= IF DROP R> DROP 0 EXIT THEN
    R@ SPAY.STATE @ STREAMS-PAYLOAD-STATE-SEALED <> IF
        DROP R> DROP 0 EXIT
    THEN
    R@ SPAY.GENERATION @ <> IF R> DROP 0 EXIT THEN
    R> _SPAY-DIGEST-EXACT? ;

\ ---------------------------------------------------------------------
\ Exact range, whole-body, digest, and carrier-to-carrier copies
\ ---------------------------------------------------------------------

: _SPAY-SPAN-DISJOINT-VALID?  ( address length payload -- flag )
    2 PICK 2 PICK MSPAN-NONWRAPPING? 0= IF 2DROP DROP 0 EXIT THEN
    2 PICK 2 PICK 2 PICK STREAMS-PAYLOAD-SIZE
        MSPAN-OVERLAP? IF 2DROP DROP 0 EXIT THEN
    2 PICK 2 PICK
        2 PICK SPAY.SEGMENTS @
        3 PICK SPAY.SEGMENT-N @ STREAMS-PAYLOAD-SEGMENT-BYTES
        MSPAN-OVERLAP? IF 2DROP DROP 0 EXIT THEN
    DUP SPAY.SEGMENT-N @ 0 ?DO
        2 PICK 2 PICK
        I 3 PICK _SPAY-SEGMENT
        DUP SPSEG.DATA @ SWAP SPSEG.CAPACITY @
        MSPAN-OVERLAP? IF 2DROP DROP 0 UNLOOP EXIT THEN
    LOOP
    2DROP DROP -1 ;

: _SPAY-READ-COPY  ( payload -- )
    DUP SPAY.SEGMENT-N @ 0 ?DO
        DUP _SPAY.ARG-U @ 0= IF DROP UNLOOP EXIT THEN
        I OVER _SPAY-SEGMENT
        DUP SPSEG.USED @ 2 PICK _SPAY.ARG-OFFSET @ <= IF
            SPSEG.USED @ NEGATE OVER _SPAY.ARG-OFFSET +!
        ELSE
            DUP SPSEG.USED @ 2 PICK _SPAY.ARG-OFFSET @ -
            2 PICK _SPAY.ARG-U @ OVER MIN >R DROP
            DUP SPSEG.DATA @ 2 PICK _SPAY.ARG-OFFSET @ +
            2 PICK _SPAY.ARG-A @ R@ MOVE
            R@ 2 PICK _SPAY.ARG-A +!
            R@ NEGATE 2 PICK _SPAY.ARG-U +!
            0 2 PICK _SPAY.ARG-OFFSET !
            R> DROP DROP
        THEN
    LOOP
    DROP ;

: _SPAY-READ-BODY  ( payload -- status )
    DUP STREAMS-PAYLOAD-VALID? 0= IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP _SPAY.ARG-GENERATION @ OVER SPAY.GENERATION @ <> IF
        DROP STREAMS-PAYLOAD-S-STALE EXIT
    THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-SEALED <> IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP _SPAY.ARG-OFFSET @ 0<
    OVER _SPAY.ARG-U @ 0< OR IF DROP STREAMS-PAYLOAD-S-INVALID EXIT THEN
    DUP _SPAY.ARG-U @ 0>
        OVER _SPAY.ARG-A @ 0= AND IF DROP STREAMS-PAYLOAD-S-INVALID EXIT THEN
    DUP _SPAY.ARG-A @ OVER _SPAY.ARG-U @
        MSPAN-NONWRAPPING? 0= IF DROP STREAMS-PAYLOAD-S-INVALID EXIT THEN
    DUP _SPAY.ARG-OFFSET @ OVER SPAY.BYTE-U @ > IF
        DROP STREAMS-PAYLOAD-S-CAPACITY EXIT
    THEN
    DUP SPAY.BYTE-U @ OVER _SPAY.ARG-OFFSET @ -
        OVER _SPAY.ARG-U @ < IF DROP STREAMS-PAYLOAD-S-CAPACITY EXIT THEN
    DUP _SPAY-ARG-SPAN-DISJOINT? 0= IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP _SPAY-READ-COPY
    _SPAY.ARG-U @ IF STREAMS-PAYLOAD-S-INVALID
        ELSE STREAMS-PAYLOAD-S-OK THEN ;

: STREAMS-PAYLOAD-READ
  ( offset destination-a exact-u generation payload -- status )
    >R
    R@ _SPAY-HEADER? 0= IF
        2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ SPAY.BUSY @ IF
        2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-BUSY EXIT
    THEN
    R@ STREAMS-PAYLOAD-BOUND? 0= IF
        2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ SPAY.STATE @ STREAMS-PAYLOAD-STATE-SEALED <> IF
        2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP R@ SPAY.GENERATION @ <> IF
        2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-STALE EXIT
    THEN
    3 PICK 0< 2 PICK 0< OR IF
        2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    2 PICK 0= 2 PICK 0> AND IF
        2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    2 PICK 2 PICK MSPAN-NONWRAPPING? 0= IF
        2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    3 PICK R@ SPAY.BYTE-U @ > IF
        2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-CAPACITY EXIT
    THEN
    R@ SPAY.BYTE-U @ 4 PICK - 2 PICK < IF
        2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-CAPACITY EXIT
    THEN
    2 PICK 2 PICK R@ _SPAY-SPAN-DISJOINT-VALID? 0= IF
        2DROP 2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ _SPAY.ARG-GENERATION !
    DUP R@ _SPAY.ARG-U !
    DUP R@ _SPAY.ARG-ORIGINAL-U !
    OVER R@ _SPAY.ARG-A !
    2 PICK R@ _SPAY.ARG-OFFSET !
    2DROP DROP
    -1 R@ SPAY.BUSY !
    R@ _SPAY-READ-BODY
    R> _SPAY-LEAVE ;

: STREAMS-PAYLOAD-COPY
  ( destination-a capacity generation payload -- payload-u status )
    >R
    R@ _SPAY-HEADER? 0= IF
        2DROP DROP R> DROP 0 STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ SPAY.BUSY @ IF
        2DROP DROP R> DROP 0 STREAMS-PAYLOAD-S-BUSY EXIT
    THEN
    R@ STREAMS-PAYLOAD-BOUND? 0= IF
        2DROP DROP R> DROP 0 STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ SPAY.STATE @ STREAMS-PAYLOAD-STATE-SEALED <> IF
        2DROP DROP R> DROP 0 STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP R@ SPAY.GENERATION @ <> IF
        2DROP DROP R> DROP 0 STREAMS-PAYLOAD-S-STALE EXIT
    THEN
    OVER 0< IF
        2DROP DROP R> DROP 0 STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ SPAY.BYTE-U @ 2 PICK > IF
        2DROP DROP R> DROP 0 STREAMS-PAYLOAD-S-CAPACITY EXIT
    THEN
    2 PICK R@ SPAY.BYTE-U @ R@
        _SPAY-SPAN-DISJOINT-VALID? 0= IF
        2DROP DROP R> DROP 0 STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ _SPAY.ARG-GENERATION !
    OVER R@ _SPAY.ARG-A !
    2DROP
    R@ SPAY.BYTE-U @ DUP R@ _SPAY.ARG-U !
    DUP R@ _SPAY.ARG-ORIGINAL-U ! DROP
    0 R@ _SPAY.ARG-OFFSET !
    -1 R@ SPAY.BUSY !
    R@ SPAY.BYTE-U @
    R@ _SPAY-READ-BODY
    DUP STREAMS-PAYLOAD-S-OK <> IF
        >R DROP 0 R>
    THEN
    R> _SPAY-LEAVE ;

: _SPAY-DIGEST-BODY  ( payload -- status )
    DUP STREAMS-PAYLOAD-VALID? 0= IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP _SPAY.ARG-GENERATION @ OVER SPAY.GENERATION @ <> IF
        DROP STREAMS-PAYLOAD-S-STALE EXIT
    THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-SEALED <> IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP _SPAY-ARG-SPAN-DISJOINT? 0= IF
        DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP SPAY.DIGEST OVER _SPAY.ARG-A @ SHA3-256-LEN MOVE
    DROP STREAMS-PAYLOAD-S-OK ;

: STREAMS-PAYLOAD-DIGEST  ( destination-32 generation payload -- status )
    >R
    R@ _SPAY-HEADER? 0= IF
        2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ SPAY.BUSY @ IF
        2DROP R> DROP STREAMS-PAYLOAD-S-BUSY EXIT
    THEN
    R@ STREAMS-PAYLOAD-BOUND? 0= IF
        2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ SPAY.STATE @ STREAMS-PAYLOAD-STATE-SEALED <> IF
        2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP R@ SPAY.GENERATION @ <> IF
        2DROP R> DROP STREAMS-PAYLOAD-S-STALE EXIT
    THEN
    OVER 0= IF
        2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    OVER SHA3-256-LEN MSPAN-NONWRAPPING? 0= IF
        2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    OVER SHA3-256-LEN R@
        _SPAY-SPAN-DISJOINT-VALID? 0= IF
        2DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ _SPAY.ARG-GENERATION !
    R@ _SPAY.ARG-A !
    SHA3-256-LEN DUP R@ _SPAY.ARG-U ! R@ _SPAY.ARG-ORIGINAL-U !
    -1 R@ SPAY.BUSY !
    R@ _SPAY-DIGEST-BODY
    R> _SPAY-LEAVE ;

: STREAMS-PAYLOAD-SPAN-DISJOINT?  ( address length payload -- flag )
    DUP STREAMS-PAYLOAD-BOUND? 0= IF 2DROP DROP 0 EXIT THEN
    _SPAY-SPAN-DISJOINT-VALID? ;

: _SPAY-DISJOINT-VALID?  ( payload-a payload-b -- flag )
    OVER STREAMS-PAYLOAD-SIZE 2 PICK
        _SPAY-SPAN-DISJOINT-VALID? 0= IF 2DROP 0 EXIT THEN
    OVER SPAY.SEGMENTS @
        2 PICK SPAY.SEGMENT-N @ STREAMS-PAYLOAD-SEGMENT-BYTES
        2 PICK _SPAY-SPAN-DISJOINT-VALID? 0= IF 2DROP 0 EXIT THEN
    OVER SPAY.SEGMENT-N @ 0 ?DO
        I 2 PICK _SPAY-SEGMENT
        DUP SPSEG.DATA @ SWAP SPSEG.CAPACITY @
        2 PICK _SPAY-SPAN-DISJOINT-VALID? 0= IF
            2DROP 0 UNLOOP EXIT
        THEN
    LOOP
    2DROP -1 ;

: STREAMS-PAYLOAD-DISJOINT?  ( payload-a payload-b -- flag )
    2DUP STREAMS-PAYLOAD-BOUND? SWAP STREAMS-PAYLOAD-BOUND? AND 0= IF
        2DROP 0 EXIT
    THEN
    _SPAY-DISJOINT-VALID? ;

: _SPAY-WIPE-APPENDED-TAIL  ( payload -- )
    DUP SPAY.BYTE-U @ OVER _SPAY.ARG-OFFSET @ -
        OVER _SPAY.ARG-U !
    DUP _SPAY.ARG-OFFSET @ OVER _SPAY.ARG-ORIGINAL-U !
    DUP SPAY.SEGMENT-N @ 0 ?DO
        DUP _SPAY.ARG-U @ 0= IF DROP UNLOOP EXIT THEN
        I OVER _SPAY-SEGMENT
        DUP SPSEG.USED @ 2 PICK _SPAY.ARG-ORIGINAL-U @ <= IF
            SPSEG.USED @ NEGATE OVER _SPAY.ARG-ORIGINAL-U +!
        ELSE
            DUP SPSEG.USED @ 2 PICK _SPAY.ARG-ORIGINAL-U @ -
            2 PICK _SPAY.ARG-U @ OVER MIN >R DROP
            DUP SPSEG.DATA @ 2 PICK _SPAY.ARG-ORIGINAL-U @ +
                R@ 0 FILL
            R@ NEGATE 2 PICK _SPAY.ARG-U +!
            0 2 PICK _SPAY.ARG-ORIGINAL-U !
            R> DROP DROP
        THEN
    LOOP
    DROP ;

: _SPAY-RESTORE-PACKED-LENGTH  ( exact-u payload -- )
    OVER OVER SPAY.BYTE-U !
    DUP SPAY.SEGMENT-N @ 0 ?DO
        I OVER _SPAY-SEGMENT
        2 PICK OVER SPSEG.CAPACITY @ MIN
        DUP 2 PICK SPSEG.USED !
        >R DROP SWAP R> - SWAP
    LOOP
    2DROP ;

: _SPAY-ROLLBACK-APPEND-PAYLOAD
  ( source destination status -- status )
    >R
    DUP SPAY.FLAGS @ STREAMS-PAYLOAD-F-WIPE AND IF
        DUP _SPAY-WIPE-APPENDED-TAIL
    THEN
    DUP _SPAY.ARG-OFFSET @ OVER _SPAY-RESTORE-PACKED-LENGTH
    NIP
    R> SWAP _SPAY-LEAVE ;

: STREAMS-PAYLOAD-APPEND-PAYLOAD
  ( source-gen source-payload destination-gen destination-payload -- status )
    >R
    R@ _SPAY-HEADER? 0= IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    R@ SPAY.BUSY @ IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-BUSY EXIT
    THEN
    R@ STREAMS-PAYLOAD-VALID? 0= IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    OVER _SPAY-HEADER? 0= IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    OVER SPAY.BUSY @ IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-BUSY EXIT
    THEN
    2 PICK 2 PICK STREAMS-PAYLOAD-EXACT? 0= IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    DUP R@ SPAY.GENERATION @ <> IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-STALE EXIT
    THEN
    R@ SPAY.STATE @ STREAMS-PAYLOAD-STATE-BUILDING <> IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    OVER R@ STREAMS-PAYLOAD-DISJOINT? 0= IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT
    THEN
    OVER SPAY.BYTE-U @
        R@ SPAY.BYTE-CAP @ R@ SPAY.BYTE-U @ - > IF
        2DROP DROP R> DROP STREAMS-PAYLOAD-S-CAPACITY EXIT
    THEN
    \ The complete capacity and alias preflight above makes these internal
    \ segment appends non-failing and therefore transactional as a group.
    DUP R@ _SPAY.ARG-GENERATION !
    R@ SPAY.BYTE-U @ R@ _SPAY.ARG-OFFSET !
    DROP NIP R>                             ( source destination )
    -1 OVER SPAY.BUSY !
    OVER SPAY.SEGMENT-N @ 0 ?DO
        I 2 PICK _SPAY-SEGMENT
        DUP SPSEG.DATA @ SWAP SPSEG.USED @
        DUP 3 PICK _SPAY.ARG-U !
        DUP 3 PICK _SPAY.ARG-ORIGINAL-U !
        OVER 3 PICK _SPAY.ARG-A !
        2DROP
        DUP _SPAY-APPEND-BODY
        DUP STREAMS-PAYLOAD-S-OK <> IF
            _SPAY-ROLLBACK-APPEND-PAYLOAD
            UNLOOP EXIT
        THEN
        DROP
    LOOP
    NIP
    STREAMS-PAYLOAD-S-OK SWAP _SPAY-LEAVE ;

\ ---------------------------------------------------------------------
\ Exact-once close, optional wipe, and one-shot release
\ ---------------------------------------------------------------------

: _SPAY-RELEASE-BODY  ( payload -- )
    >R
    R@ SPAY.SEGMENTS @
    R@ SPAY.SEGMENT-N @
    R@ SPAY.RELEASE-CONTEXT @
    R@ SPAY.RELEASE-XT @ EXECUTE
    R> SPAY.CLEANUP-ERROR ! ;

: _SPAY-RELEASE-CALL  ( payload -- error )
    ['] _SPAY-RELEASE-BODY CATCH
    DUP IF NIP THEN ;

: _SPAY-CLEAR-ONE-SHOT  ( payload -- )
    0 OVER SPAY.SEGMENTS !
    0 OVER SPAY.SEGMENT-N !
    0 OVER SPAY.BYTE-CAP !
    DUP SPAY.GEOMETRY-DIGEST SHA3-256-LEN 0 FILL
    0 OVER SPAY.RELEASE-XT !
    0 SWAP SPAY.RELEASE-CONTEXT ! ;

: _SPAY-CLOSEABLE?  ( payload -- flag )
    DUP _SPAY-HEADER? 0= IF DROP 0 EXIT THEN
    DUP SPAY.STATE @ DUP STREAMS-PAYLOAD-STATE-READY =
        OVER STREAMS-PAYLOAD-STATE-BUILDING = OR
        SWAP STREAMS-PAYLOAD-STATE-SEALED = OR 0= IF DROP 0 EXIT THEN
    DUP SPAY.BUSY @ -1 <> IF DROP 0 EXIT THEN
    DUP SPAY.GENERATION @ 0< IF DROP 0 EXIT THEN
    DUP SPAY.PROFILE @ 1 < IF DROP 0 EXIT THEN
    DUP SPAY.FLAGS @ _SPAY-FLAGS? 0= IF DROP 0 EXIT THEN
    DUP SPAY.BINDING-EPOCH @ 1 < IF DROP 0 EXIT THEN
    DUP SPAY.RELEASE-XT @ 0=
        OVER SPAY.RELEASE-CONTEXT @ 0<> AND IF DROP 0 EXIT THEN
    DUP SPAY.CLEANUP-ERROR @ IF DROP 0 EXIT THEN
    DUP _SPAY-LIVE-GEOMETRY? 0= IF DROP 0 EXIT THEN
    DUP _SPAY-GEOMETRY-EXACT? 0= IF DROP 0 EXIT THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-READY = IF
        DUP SPAY.BYTE-U @ 0=
        OVER _SPAY-USED-ZERO? AND
        SWAP SPAY.DIGEST SHA3-256-LEN _SPAY-ZERO? AND EXIT
    THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-BUILDING = IF
        SPAY.DIGEST SHA3-256-LEN _SPAY-ZERO? EXIT
    THEN
    DROP -1 ;

: _SPAY-CLOSE-BODY  ( payload -- status )
    DUP _SPAY.ARG-GENERATION @ OVER SPAY.GENERATION @ <> IF
        DROP STREAMS-PAYLOAD-S-STALE EXIT
    THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-CLOSED = IF
        DUP STREAMS-PAYLOAD-VALID? IF
            DROP STREAMS-PAYLOAD-S-OK
        ELSE
            DROP STREAMS-PAYLOAD-S-INVALID
        THEN
        EXIT
    THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-CLEANUP-FAILED = IF
        DUP STREAMS-PAYLOAD-VALID? IF
            DROP STREAMS-PAYLOAD-S-CLEANUP
        ELSE
            DROP STREAMS-PAYLOAD-S-INVALID
        THEN
        EXIT
    THEN
    DUP _SPAY-CLOSEABLE? 0= IF DROP STREAMS-PAYLOAD-S-INVALID EXIT THEN
    DUP SPAY.STATE @ STREAMS-PAYLOAD-STATE-SEALED = IF
        DUP _SPAY-DIGEST-EXACT? 0=
    ELSE
        0
    THEN
    OVER _SPAY.ARG-U !
    STREAMS-PAYLOAD-STATE-CLOSING OVER SPAY.STATE !
    DUP SPAY.FLAGS @ STREAMS-PAYLOAD-F-WIPE AND IF
        DUP _SPAY-WIPE-BUFFERS
    THEN
    0 OVER SPAY.CLEANUP-ERROR !
    DUP SPAY.RELEASE-XT @ IF
        DUP _SPAY-RELEASE-CALL
        DUP IF OVER SPAY.CLEANUP-ERROR ! ELSE DROP THEN
        DUP _SPAY-CLEAR-ONE-SHOT
    THEN
    DUP _SPAY-CLEAR-CONTENT
    DUP SPAY.CLEANUP-ERROR @ IF
        STREAMS-PAYLOAD-STATE-CLEANUP-FAILED SWAP SPAY.STATE !
        STREAMS-PAYLOAD-S-CLEANUP
    ELSE
        STREAMS-PAYLOAD-STATE-CLOSED OVER SPAY.STATE !
        DUP _SPAY.ARG-U @ IF
            DROP STREAMS-PAYLOAD-S-INTEGRITY
        ELSE
            DROP STREAMS-PAYLOAD-S-OK
        THEN
    THEN ;

: STREAMS-PAYLOAD-CLOSE  ( generation payload -- status )
    >R
    R@ _SPAY-HEADER? 0= IF DROP R> DROP STREAMS-PAYLOAD-S-INVALID EXIT THEN
    R@ SPAY.BUSY @ IF DROP R> DROP STREAMS-PAYLOAD-S-BUSY EXIT THEN
    R@ _SPAY.ARG-GENERATION !
    -1 R@ SPAY.BUSY !
    R@ _SPAY-CLOSE-BODY
    R> _SPAY-LEAVE ;
