\ =====================================================================
\  persistence-adapter.f - Streams authority over neutral persistence
\ =====================================================================
\  This adapter composes one caller-supplied PSTORE into the four-tree L13
\  configured-Streams authority.  It owns physical transaction mechanics,
\  checked application-root publication, bounded work, and semantic-record
\  dereference.  It owns no paths, provider policy, refresh policy, query
\  projection, migration choice, Library documents, or public-Bluesky state.
\
\  All mutable memory is caller-owned.  One work object permanently borrows
\  its PSTORE work and shares exactly one PBTREE work, one PBLOB work, and one
\  reclamation work across four workload-separated tree descriptors.  Its one
\  PBTREE cursor is call-local navigation state; only semantic keys resume.
\  A read-only span probe lets callers qualify buffers against that complete
\  borrowed-memory graph without entering or mutating the adapter.
\ =====================================================================

PROVIDED akashic-tui-streams-persistence-adapter

REQUIRE ../../../persistence/store.f
REQUIRE ../../../persistence/btree.f
REQUIRE ../../../persistence/blob.f
REQUIRE ../../../persistence/reclaim.f
REQUIRE authority-root.f
REQUIRE index-record-agreement.f

PERSIST-S-OK        CONSTANT STREAMS-PA-S-OK
PERSIST-S-ABSENT    CONSTANT STREAMS-PA-S-ABSENT
PERSIST-S-INVALID   CONSTANT STREAMS-PA-S-INVALID
PERSIST-S-CAPACITY  CONSTANT STREAMS-PA-S-CAPACITY
PERSIST-S-IO        CONSTANT STREAMS-PA-S-IO
PERSIST-S-CORRUPT   CONSTANT STREAMS-PA-S-CORRUPT
PERSIST-S-BUSY      CONSTANT STREAMS-PA-S-BUSY
PERSIST-S-CONFLICT  CONSTANT STREAMS-PA-S-CONFLICT
PERSIST-S-UNCERTAIN CONSTANT STREAMS-PA-S-UNCERTAIN
PERSIST-S-NOT-FOUND CONSTANT STREAMS-PA-S-NOT-FOUND
PERSIST-S-FAULT     CONSTANT STREAMS-PA-S-FAULT
11                  CONSTANT STREAMS-PA-S-UNSUPPORTED

0x5354524D50413031 CONSTANT _SPA-MAGIC       \ "STRMPA01"
0x5354524D50415731 CONSTANT _SPAW-MAGIC      \ "STRMPAW1"

0 CONSTANT _SPAW-STATE-READY
1 CONSTANT _SPAW-STATE-ACTIVE
2 CONSTANT _SPAW-STATE-REOPEN

STREAMS-AUTHORITY-ROOT-TREE-COUNT CONSTANT _SPA-TREE-COUNT

0x53504101 CONSTANT _SPA-SCOPE-DIRECTORY
0x53504102 CONSTANT _SPA-SCOPE-ATTEMPTS
0x53504103 CONSTANT _SPA-SCOPE-IDENTITIES
0x53504104 CONSTANT _SPA-SCOPE-ORDERINGS

\ ---------------------------------------------------------------------
\ Descriptor and statuses
\ ---------------------------------------------------------------------

 0 CONSTANT _SPA-D-MAGIC-OFF
 8 CONSTANT _SPA-D-SELF-OFF
16 CONSTANT _SPA-D-STORE-OFF
24 CONSTANT _SPA-D-STATUS-OFF
32 CONSTANT STREAMS-PA-SIZE

: _SPA-D.MAGIC   ( adapter -- a ) _SPA-D-MAGIC-OFF + ;
: _SPA-D.SELF    ( adapter -- a ) _SPA-D-SELF-OFF + ;
: _SPA-D.STORE   ( adapter -- a ) _SPA-D-STORE-OFF + ;
: _SPA-D.STATUS  ( adapter -- a ) _SPA-D-STATUS-OFF + ;

: _SPA-DROP3  ( x1 x2 x3 -- ) 2DROP DROP ;
: _SPA-DROP4  ( x1 x2 x3 x4 -- ) 2DROP 2DROP ;
: _SPA-DROP5  ( x1 x2 x3 x4 x5 -- ) 2DROP 2DROP DROP ;
: _SPA-DROP6  ( x1 x2 x3 x4 x5 x6 -- ) 2DROP 2DROP 2DROP ;
: _SPA-DROP7  ( x1 x2 x3 x4 x5 x6 x7 -- )
    2DROP 2DROP 2DROP DROP ;
: _SPA-DROP8  ( x1 x2 x3 x4 x5 x6 x7 x8 -- )
    2DROP 2DROP 2DROP 2DROP ;
: _SPA-DROP9  ( x1 x2 x3 x4 x5 x6 x7 x8 x9 -- )
    2DROP 2DROP 2DROP 2DROP DROP ;

: _SPA-BYTES=  ( a b u -- flag )
    DUP 0< IF DROP 2DROP 0 EXIT THEN
    DUP 0= IF DROP 2DROP -1 EXIT THEN
    2 PICK 0= 2 PICK 0= OR IF DROP 2DROP 0 EXIT THEN
    2 PICK OVER MSPAN-NONWRAPPING? 0= IF
        DROP 2DROP 0 EXIT
    THEN
    OVER OVER MSPAN-NONWRAPPING? 0= IF
        DROP 2DROP 0 EXIT
    THEN
    0 ?DO
        2DUP I + C@ SWAP I + C@ <> IF
            2DROP 0 UNLOOP EXIT
        THEN
    LOOP
    2DROP -1 ;

: _SPA-ZERO?  ( a u -- flag )
    DUP 0< IF 2DROP 0 EXIT THEN
    0 ?DO
        DUP I + C@ IF DROP 0 UNLOOP EXIT THEN
    LOOP
    DROP -1 ;

: _SPA-STATUS?  ( status -- flag )
    DUP STREAMS-PA-S-OK >=
    SWAP STREAMS-PA-S-UNSUPPORTED <= AND ;

: _SPA-PERSIST>STATUS  ( persist-status -- adapter-status )
    DUP PERSIST-S-OK < OVER PERSIST-S-FAULT > OR IF
        DROP STREAMS-PA-S-FAULT
    THEN ;

: _SPA-ROOT>STATUS  ( authority-root-status -- adapter-status )
    CASE
        STREAMS-AUTHORITY-ROOT-S-OK OF
            STREAMS-PA-S-OK ENDOF
        STREAMS-AUTHORITY-ROOT-S-INVALID OF
            STREAMS-PA-S-INVALID ENDOF
        STREAMS-AUTHORITY-ROOT-S-UNSUPPORTED OF
            STREAMS-PA-S-UNSUPPORTED ENDOF
        STREAMS-AUTHORITY-ROOT-S-CORRUPT OF
            STREAMS-PA-S-CORRUPT ENDOF
        STREAMS-PA-S-FAULT SWAP
    ENDCASE ;

: STREAMS-PA-VALID?  ( adapter -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP STREAMS-PA-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP _SPA-D.MAGIC @ _SPA-MAGIC <> IF DROP 0 EXIT THEN
    DUP _SPA-D.SELF @ OVER <> IF DROP 0 EXIT THEN
    DUP _SPA-D.STATUS @ _SPA-STATUS? 0= IF DROP 0 EXIT THEN
    DUP _SPA-D.STORE @ DUP PSTORE-VALID? 0= IF 2DROP 0 EXIT THEN
    PSTORE-SIZE ROT STREAMS-PA-SIZE MSPAN-OVERLAP? 0= ;

: STREAMS-PA-INIT  ( store adapter -- status )
    >R
    DUP PSTORE-VALID? 0= IF DROP R> DROP STREAMS-PA-S-INVALID EXIT THEN
    R@ 0= IF DROP R> DROP STREAMS-PA-S-INVALID EXIT THEN
    R@ STREAMS-PA-SIZE MSPAN-NONWRAPPING? 0= IF
        DROP R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ STREAMS-PA-SIZE 2 PICK PSTORE-SPAN-DISJOINT? 0= IF
        DROP R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    DUP PSTORE-SIZE R@ STREAMS-PA-SIZE MSPAN-OVERLAP? IF
        DROP R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ STREAMS-PA-SIZE 0 FILL
    _SPA-MAGIC R@ _SPA-D.MAGIC !
    R@ R@ _SPA-D.SELF !
    DUP R@ _SPA-D.STORE !
    STREAMS-PA-S-OK R@ _SPA-D.STATUS !
    DROP R> DROP STREAMS-PA-S-OK ;

: STREAMS-PA-STATUS@  ( adapter -- status )
    DUP STREAMS-PA-VALID? IF
        _SPA-D.STATUS @
    ELSE
        DROP STREAMS-PA-S-INVALID
    THEN ;

: STREAMS-PA-PHYSICAL-GENERATION@  ( adapter -- generation|-1 )
    DUP STREAMS-PA-VALID? IF
        _SPA-D.STORE @ PSTORE-GENERATION@
    ELSE
        DROP -1
    THEN ;

\ ---------------------------------------------------------------------
\ Caller-owned bounded work
\ ---------------------------------------------------------------------

\ Range rows are complete, caller-owned semantic snapshots.  The exact
\ PBTREE key is retained so its KEY$ can be supplied as the next exclusive
\ AFTER/BEFORE key; the dereferenced SPREC copy remains valid after the
\ adapter's neutral work buffers are reused.
STREAMS-PI-RANGE-MAX CONSTANT STREAMS-PA-RANGE-MAX

 0 CONSTANT _SPAROW-KEY-U-OFF
 8 CONSTANT _SPAROW-RECORD-U-OFF
16 CONSTANT _SPAROW-KEY-OFF
_SPAROW-KEY-OFF PBTREE-KEY-MAX +
    CONSTANT _SPAROW-RECORD-OFF
_SPAROW-RECORD-OFF STREAMS-PERSISTENCE-RECORD-MAX +
    CONSTANT STREAMS-PA-RANGE-ROW-SIZE

: _SPAROW.KEY-U    ( row -- a ) _SPAROW-KEY-U-OFF + ;
: _SPAROW.RECORD-U ( row -- a ) _SPAROW-RECORD-U-OFF + ;
: _SPAROW.KEY      ( row -- a ) _SPAROW-KEY-OFF + ;
: _SPAROW.RECORD   ( row -- a ) _SPAROW-RECORD-OFF + ;

: _SPAROW-PADDING-ZERO?  ( row -- flag )
    >R
    R@ _SPAROW.KEY R@ _SPAROW.KEY-U @ +
    PBTREE-KEY-MAX R@ _SPAROW.KEY-U @ -
        _SPA-ZERO? 0= IF R> DROP 0 EXIT THEN
    R@ _SPAROW.RECORD R@ _SPAROW.RECORD-U @ +
    STREAMS-PERSISTENCE-RECORD-MAX R@ _SPAROW.RECORD-U @ -
        _SPA-ZERO?
    R> DROP ;

: STREAMS-PA-RANGE-ROW-KEY$  ( row -- key-a key-u | 0 0 )
    DUP 0= IF DROP 0 0 EXIT THEN
    DUP STREAMS-PA-RANGE-ROW-SIZE MSPAN-NONWRAPPING? 0= IF
        DROP 0 0 EXIT
    THEN
    DUP _SPAROW.KEY-U @ DUP 1 <
    SWAP PBTREE-KEY-MAX > OR IF DROP 0 0 EXIT THEN
    DUP _SPAROW.KEY SWAP _SPAROW.KEY-U @ ;

: STREAMS-PA-RANGE-ROW-RECORD$  ( row -- record-a record-u | 0 0 )
    DUP 0= IF DROP 0 0 EXIT THEN
    DUP STREAMS-PA-RANGE-ROW-SIZE MSPAN-NONWRAPPING? 0= IF
        DROP 0 0 EXIT
    THEN
    DUP _SPAROW.RECORD-U @ DUP 1 <
    SWAP STREAMS-PERSISTENCE-RECORD-MAX > OR IF
        DROP 0 0 EXIT
    THEN
    DUP _SPAROW.RECORD SWAP _SPAROW.RECORD-U @ ;

: STREAMS-PA-RANGE-ROW-VALID?  ( row -- flag )
    DUP STREAMS-PA-RANGE-ROW-KEY$ DUP 0= IF
        2DROP DROP 0 EXIT
    THEN
    STREAMS-PI-KEY-VALID? 0= IF DROP 0 EXIT THEN
    DUP STREAMS-PA-RANGE-ROW-RECORD$ DUP 0= IF
        2DROP DROP 0 EXIT
    THEN
    SPREC-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SPAROW-PADDING-ZERO? 0= IF DROP 0 EXIT THEN
    DUP STREAMS-PA-RANGE-ROW-KEY$
    2 PICK STREAMS-PA-RANGE-ROW-RECORD$
    STREAMS-PI-RECORD-AGREES? NIP ;

STREAMS-PA-RANGE-ROW-SIZE PERSIST-PAGE-PAYLOAD-SIZE > [IF]
    ABORT" Streams range row exceeds adapter swap scratch"
[THEN]

  0 CONSTANT _SPAW-MAGIC-OFF
  8 CONSTANT _SPAW-SELF-OFF
 16 CONSTANT _SPAW-BUSY-OFF
 24 CONSTANT _SPAW-STATE-OFF
 32 CONSTANT _SPAW-STATUS-OFF
 40 CONSTANT _SPAW-ADAPTER-OFF
 48 CONSTANT _SPAW-PSTORE-WORK-OFF
 56 CONSTANT _SPAW-BASE-GENERATION-OFF
 64 CONSTANT _SPAW-OLD-ROOT-PAGE-OFF
 72 CONSTANT _SPAW-APP-ROOT-PAGE-OFF
 80 CONSTANT _SPAW-TEMP-STATUS-OFF
 88 CONSTANT _SPAW-MUTATION-N-OFF
 96 CONSTANT _SPAW-PHYSICAL-ONLY-N-OFF
104 CONSTANT _SPAW-STAGING-ACTIVE-OFF
112 CONSTANT _SPAW-RECLAIM-STEP-CALLS-OFF
120 CONSTANT _SPAW-RECLAIM-MOVED-OFF
128 CONSTANT _SPAW-ARG-A-OFF
136 CONSTANT _SPAW-ARG-U-OFF
144 CONSTANT _SPAW-VALUE-A-OFF
152 CONSTANT _SPAW-VALUE-U-OFF
160 CONSTANT _SPAW-DEST-A-OFF
168 CONSTANT _SPAW-DEST-U-OFF
176 CONSTANT _SPAW-AUTHORITY-PRESENT-OFF
184 CONSTANT _SPAW-RESULT-U-OFF
192 CONSTANT _SPAW-PAGE-ID-OFF
200 CONSTANT _SPAW-SOURCE-XT-OFF
208 CONSTANT _SPAW-SOURCE-CONTEXT-OFF
216 CONSTANT _SPAW-TOTAL-U-OFF
224 CONSTANT _SPAW-RECORD-REF-OFF
248 CONSTANT _SPAW-BLOB-OFF
320 CONSTANT _SPAW-RECLAIM-OFF
_SPAW-RECLAIM-OFF RECLAIM-SIZE + CONSTANT _SPAW-RECLAIM-WORK-OFF
_SPAW-RECLAIM-WORK-OFF RECLAIM-WORK-SIZE +
    CONSTANT _SPAW-TREES-OFF
_SPAW-TREES-OFF _SPA-TREE-COUNT PBTREE-SIZE * +
    CONSTANT _SPAW-BTREE-WORK-OFF
_SPAW-BTREE-WORK-OFF PBTREE-WORK-SIZE +
    CONSTANT _SPAW-BLOB-WORK-OFF
_SPAW-BLOB-WORK-OFF PBLOB-WORK-SIZE +
    CONSTANT _SPAW-ROOTS-OFF
_SPAW-ROOTS-OFF _SPA-TREE-COUNT PBTREE-ROOT-SIZE * +
    CONSTANT _SPAW-STAGING-ROOTS-OFF
_SPAW-STAGING-ROOTS-OFF _SPA-TREE-COUNT PBTREE-ROOT-SIZE * +
    CONSTANT _SPAW-TEMP-ROOT-OFF
_SPAW-TEMP-ROOT-OFF PBTREE-ROOT-SIZE +
    CONSTANT _SPAW-CURSOR-OFF
_SPAW-CURSOR-OFF PBTREE-CURSOR-SIZE +
    CONSTANT _SPAW-KEY-OFF
_SPAW-KEY-OFF PBTREE-KEY-MAX +
    CONSTANT _SPAW-RANGE-KEY-OFF
_SPAW-RANGE-KEY-OFF PBTREE-KEY-MAX +
    CONSTANT _SPAW-RECORD-OFF
_SPAW-RECORD-OFF STREAMS-PERSISTENCE-RECORD-MAX +
    CONSTANT _SPAW-AUTHORITY-ROOT-OFF
_SPAW-AUTHORITY-ROOT-OFF STREAMS-AUTHORITY-ROOT-SIZE +
    CONSTANT _SPAW-PAGE-OFF
_SPAW-PAGE-OFF PERSIST-PAGE-PAYLOAD-SIZE +
    CONSTANT STREAMS-PA-WORK-SIZE

STREAMS-PERSISTENCE-RECORD-MAX PBLOB-CHUNK-SIZE MAX
PERSIST-RECORD-HEADER-SIZE +
    CONSTANT STREAMS-PA-RECORD-BUFFER-MIN

: _SPAW.MAGIC          ( work -- a ) _SPAW-MAGIC-OFF + ;
: _SPAW.SELF           ( work -- a ) _SPAW-SELF-OFF + ;
: _SPAW.BUSY           ( work -- a ) _SPAW-BUSY-OFF + ;
: _SPAW.STATE          ( work -- a ) _SPAW-STATE-OFF + ;
: _SPAW.STATUS         ( work -- a ) _SPAW-STATUS-OFF + ;
: _SPAW.ADAPTER        ( work -- a ) _SPAW-ADAPTER-OFF + ;
: _SPAW.PSTORE-WORK    ( work -- a ) _SPAW-PSTORE-WORK-OFF + ;
: _SPAW.BASE-GENERATION ( work -- a )
    _SPAW-BASE-GENERATION-OFF + ;
: _SPAW.OLD-ROOT-PAGE  ( work -- a ) _SPAW-OLD-ROOT-PAGE-OFF + ;
: _SPAW.APP-ROOT-PAGE  ( work -- a ) _SPAW-APP-ROOT-PAGE-OFF + ;
: _SPAW.TEMP-STATUS    ( work -- a ) _SPAW-TEMP-STATUS-OFF + ;
: _SPAW.MUTATION-N     ( work -- a ) _SPAW-MUTATION-N-OFF + ;
: _SPAW.PHYSICAL-ONLY-N ( work -- a )
    _SPAW-PHYSICAL-ONLY-N-OFF + ;
: _SPAW.STAGING-ACTIVE ( work -- a ) _SPAW-STAGING-ACTIVE-OFF + ;
: _SPAW.RECLAIM-STEP-CALLS ( work -- a )
    _SPAW-RECLAIM-STEP-CALLS-OFF + ;
: _SPAW.RECLAIM-MOVED  ( work -- a ) _SPAW-RECLAIM-MOVED-OFF + ;
: _SPAW.ARG-A          ( work -- a ) _SPAW-ARG-A-OFF + ;
: _SPAW.ARG-U          ( work -- a ) _SPAW-ARG-U-OFF + ;
: _SPAW.VALUE-A        ( work -- a ) _SPAW-VALUE-A-OFF + ;
: _SPAW.VALUE-U        ( work -- a ) _SPAW-VALUE-U-OFF + ;
: _SPAW.DEST-A         ( work -- a ) _SPAW-DEST-A-OFF + ;
: _SPAW.DEST-U         ( work -- a ) _SPAW-DEST-U-OFF + ;
: _SPAW.AUTHORITY-PRESENT ( work -- a )
    _SPAW-AUTHORITY-PRESENT-OFF + ;
: _SPAW.RESULT-U       ( work -- a ) _SPAW-RESULT-U-OFF + ;
: _SPAW.PAGE-ID        ( work -- a ) _SPAW-PAGE-ID-OFF + ;
: _SPAW.SOURCE-XT      ( work -- a ) _SPAW-SOURCE-XT-OFF + ;
: _SPAW.SOURCE-CONTEXT ( work -- a ) _SPAW-SOURCE-CONTEXT-OFF + ;
: _SPAW.TOTAL-U        ( work -- a ) _SPAW-TOTAL-U-OFF + ;
: _SPAW.RECORD-REF     ( work -- ref ) _SPAW-RECORD-REF-OFF + ;
: _SPAW.BLOB           ( work -- blob ) _SPAW-BLOB-OFF + ;
: _SPAW.RECLAIM        ( work -- reclaim ) _SPAW-RECLAIM-OFF + ;
: _SPAW.RECLAIM-WORK   ( work -- reclaim-work )
    _SPAW-RECLAIM-WORK-OFF + ;
: _SPAW.BTREE-WORK     ( work -- btree-work ) _SPAW-BTREE-WORK-OFF + ;
: _SPAW.BLOB-WORK      ( work -- blob-work ) _SPAW-BLOB-WORK-OFF + ;
: _SPAW.TEMP-ROOT      ( work -- root ) _SPAW-TEMP-ROOT-OFF + ;
: _SPAW.CURSOR         ( work -- cursor ) _SPAW-CURSOR-OFF + ;
: _SPAW.KEY            ( work -- a ) _SPAW-KEY-OFF + ;
: _SPAW.RANGE-KEY      ( work -- a ) _SPAW-RANGE-KEY-OFF + ;
: _SPAW.RECORD         ( work -- a ) _SPAW-RECORD-OFF + ;
: _SPAW.AUTHORITY-ROOT ( work -- root ) _SPAW-AUTHORITY-ROOT-OFF + ;
: _SPAW.PAGE           ( work -- page ) _SPAW-PAGE-OFF + ;

: _SPAW-TREE  ( index work -- tree )
    SWAP PBTREE-SIZE * _SPAW-TREES-OFF + + ;

: _SPAW-ROOT  ( index work -- root )
    SWAP PBTREE-ROOT-SIZE * _SPAW-ROOTS-OFF + + ;

: _SPAW-STAGING-ROOT  ( index work -- root )
    SWAP PBTREE-ROOT-SIZE * _SPAW-STAGING-ROOTS-OFF + + ;

: _SPA-SCOPE  ( index -- scope|0 )
    CASE
        STREAMS-PI-TREE-DIRECTORY OF _SPA-SCOPE-DIRECTORY ENDOF
        STREAMS-PI-TREE-ATTEMPTS OF _SPA-SCOPE-ATTEMPTS ENDOF
        STREAMS-PI-TREE-IDENTITIES OF _SPA-SCOPE-IDENTITIES ENDOF
        STREAMS-PI-TREE-ORDERINGS OF _SPA-SCOPE-ORDERINGS ENDOF
        0 SWAP
    ENDCASE ;

: _SPAW-ALLOCATE  ( work store pstore-work -- page-id status )
    2 PICK _SPAW.STAGING-ACTIVE @ IF
        2 PICK _SPAW.RECLAIM-WORK >R
        PBTREE-HIGH-WATER-ALLOCATE
        DUP IF R> DROP EXIT THEN DROP
        DUP R@ RECLAIM-CLAIM-HIGH-WATER
        DUP IF
            >R DROP -1 R> R> DROP EXIT
        THEN
        R> DROP EXIT
    THEN
    1 3 PICK _SPAW.RECLAIM-STEP-CALLS +!
    RECLAIM-MAX-BATCH 3 PICK _SPAW.RECLAIM-WORK RECLAIM-STEP
    DUP IF
        >R DROP _SPA-DROP3 -1 R> EXIT
    THEN DROP
    3 PICK _SPAW.RECLAIM-MOVED +!
    ROT _SPAW.RECLAIM-WORK -ROT RECLAIM-ALLOCATE ;

: _SPAW-INIT-TREE  ( index work -- status )
    >R
    DUP R@ _SPAW.PAGE-ID !
    _SPA-SCOPE DUP 0= IF
        DROP R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    ['] _SPAW-ALLOCATE R@
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
    PBTREE-INIT _SPA-PERSIST>STATUS
    R> DROP ;

: _SPAW-INIT-GEOMETRY?  ( pstore-work adapter work -- flag )
    2 PICK PSTORE-WORK-VALID? 0= IF _SPA-DROP3 0 EXIT THEN
    1 PICK STREAMS-PA-VALID? 0= IF _SPA-DROP3 0 EXIT THEN
    DUP STREAMS-PA-WORK-SIZE MSPAN-NONWRAPPING? 0= IF
        _SPA-DROP3 0 EXIT
    THEN
    DUP STREAMS-PA-WORK-SIZE 4 PICK PSTORE-WORK-SIZE
        MSPAN-OVERLAP? IF _SPA-DROP3 0 EXIT THEN
    DUP STREAMS-PA-WORK-SIZE 4 PICK
        PSTORE-WORK-SPAN-DISJOINT? 0= IF _SPA-DROP3 0 EXIT THEN
    DUP STREAMS-PA-WORK-SIZE 3 PICK STREAMS-PA-SIZE
        MSPAN-OVERLAP? IF _SPA-DROP3 0 EXIT THEN
    1 PICK STREAMS-PA-SIZE 4 PICK
        PSTORE-WORK-SPAN-DISJOINT? 0= IF _SPA-DROP3 0 EXIT THEN
    DUP STREAMS-PA-WORK-SIZE 3 PICK _SPA-D.STORE @
        PSTORE-SPAN-DISJOINT? 0= IF _SPA-DROP3 0 EXIT THEN
    2 PICK PSTORE-WORK-RECORD-BUFFER$
    DUP STREAMS-PA-RECORD-BUFFER-MIN < IF
        2DROP _SPA-DROP3 0 EXIT
    THEN
    2DUP 4 PICK STREAMS-PA-WORK-SIZE MSPAN-OVERLAP? IF
        2DROP _SPA-DROP3 0 EXIT
    THEN
    2DROP _SPA-DROP3 -1 ;

: STREAMS-PA-WORK-VALID?  ( work -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP STREAMS-PA-WORK-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP _SPAW.MAGIC @ _SPAW-MAGIC <> IF DROP 0 EXIT THEN
    DUP _SPAW.SELF @ OVER <> IF DROP 0 EXIT THEN
    DUP _SPAW.BUSY @ DUP 0= SWAP -1 = OR 0= IF DROP 0 EXIT THEN
    DUP _SPAW.STATE @ DUP _SPAW-STATE-READY >=
        SWAP _SPAW-STATE-REOPEN <= AND 0= IF DROP 0 EXIT THEN
    DUP _SPAW.STATUS @ _SPA-STATUS? 0= IF DROP 0 EXIT THEN
    DUP _SPAW.ADAPTER @ STREAMS-PA-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SPAW.PSTORE-WORK @ PSTORE-WORK-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SPAW.RECLAIM RECLAIM-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SPAW.RECLAIM-WORK RECLAIM-WORK-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SPAW.BTREE-WORK PBTREE-WORK-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SPAW.BLOB-WORK PBLOB-WORK-VALID? 0= IF DROP 0 EXIT THEN
    0
    BEGIN DUP _SPA-TREE-COUNT < WHILE
        DUP 2 PICK _SPAW-TREE PBTREE-VALID? 0= IF
            2DROP 0 EXIT
        THEN
        1+
    REPEAT
    DROP DROP -1 ;

: STREAMS-PA-WORK-INIT  ( pstore-work adapter work -- status )
    2 PICK 2 PICK 2 PICK _SPAW-INIT-GEOMETRY? 0= IF
        _SPA-DROP3 STREAMS-PA-S-INVALID EXIT
    THEN
    >R
    R@ STREAMS-PA-WORK-SIZE 0 FILL
    _SPAW-MAGIC R@ _SPAW.MAGIC !
    R@ R@ _SPAW.SELF !
    STREAMS-PA-S-OK R@ _SPAW.STATUS !
    OVER R@ _SPAW.PSTORE-WORK !
    DUP R@ _SPAW.ADAPTER !
    OVER R@ _SPAW.BTREE-WORK PBTREE-WORK-INIT
    DUP IF
        _SPA-PERSIST>STATUS >R 2DROP R> R> DROP EXIT
    THEN DROP
    R@ _SPAW.BLOB-WORK PBLOB-WORK-INIT
    DUP IF
        _SPA-PERSIST>STATUS >R 2DROP R> R> DROP EXIT
    THEN DROP
    R@ _SPAW.RECLAIM RECLAIM-INIT
    DUP IF
        _SPA-PERSIST>STATUS >R 2DROP R> R> DROP EXIT
    THEN DROP
    R@ _SPAW.RECLAIM-WORK RECLAIM-WORK-INIT
    DUP IF
        _SPA-PERSIST>STATUS >R 2DROP R> R> DROP EXIT
    THEN DROP
    0
    BEGIN DUP _SPA-TREE-COUNT < WHILE
        DUP R@ _SPAW-INIT-TREE
        DUP IF >R _SPA-DROP3 R> R> DROP EXIT THEN DROP
        1+
    REPEAT
    DROP
    _SPAW-STATE-REOPEN R@ _SPAW.STATE !
    -1 R@ _SPAW.APP-ROOT-PAGE !
    2DROP R> DROP STREAMS-PA-S-OK ;

: _SPA-BOUND?  ( adapter work -- flag )
    >R
    DUP STREAMS-PA-VALID? 0= IF DROP R> DROP 0 EXIT THEN
    R@ STREAMS-PA-WORK-VALID? 0= IF DROP R> DROP 0 EXIT THEN
    R@ _SPAW.ADAPTER @ OVER <> IF DROP R> DROP 0 EXIT THEN
    DUP STREAMS-PA-SIZE R@ STREAMS-PA-WORK-SIZE
        MSPAN-OVERLAP? IF DROP R> DROP 0 EXIT THEN
    DUP STREAMS-PA-SIZE R@ _SPAW.PSTORE-WORK @
        PSTORE-WORK-SPAN-DISJOINT? 0= IF DROP R> DROP 0 EXIT THEN
    R@ STREAMS-PA-WORK-SIZE R@ _SPAW.PSTORE-WORK @
        PSTORE-WORK-SPAN-DISJOINT? 0= IF DROP R> DROP 0 EXIT THEN
    DUP _SPA-D.STORE @
    R@ STREAMS-PA-WORK-SIZE 2 PICK PSTORE-SPAN-DISJOINT?
    NIP NIP R> DROP ;

: _SPAW-ENTER  ( adapter work -- status )
    2DUP _SPA-BOUND? 0= IF
        2DROP STREAMS-PA-S-INVALID EXIT
    THEN
    DUP _SPAW.BUSY @ IF 2DROP STREAMS-PA-S-BUSY EXIT THEN
    -1 OVER _SPAW.BUSY !
    STREAMS-PA-S-INVALID OVER _SPAW.STATUS !
    2DROP STREAMS-PA-S-OK ;

: _SPAW-LEAVE  ( status adapter work -- status )
    >R
    OVER OVER _SPA-D.STATUS !
    OVER R@ _SPAW.STATUS !
    0 R@ _SPAW.BUSY !
    DROP R> DROP ;

: _SPAW-WORK-CATCH  ( work body-xt -- status )
    >R DUP R> CATCH
    DUP IF
        2DROP STREAMS-PA-S-FAULT
    ELSE
        DROP NIP
    THEN ;

\ ---------------------------------------------------------------------
\ Four roots and complete application-root reconciliation
\ ---------------------------------------------------------------------

: _SPAW-ROOT-INIT-ONE  ( index work -- status )
    >R
    DUP R@ _SPAW-TREE
    SWAP R@ _SPAW-ROOT
    PBTREE-ROOT-INIT _SPA-PERSIST>STATUS
    R> DROP ;

: _SPAW-ROOTS-INIT  ( work -- status )
    >R 0
    BEGIN DUP _SPA-TREE-COUNT < WHILE
        DUP R@ _SPAW-ROOT-INIT-ONE
        DUP IF >R DROP R> R> DROP EXIT THEN DROP
        1+
    REPEAT
    DROP R> DROP STREAMS-PA-S-OK ;

: _SPAW-ROOT-CURRENT?  ( index work -- flag )
    >R
    DUP R@ _SPAW-ROOT
    OVER R@ _SPAW-TREE PBTREE-ROOT-VALID? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP R@ _SPAW-ROOT PBTREE-ROOT-GENERATION@
    R@ _SPAW.BASE-GENERATION @ =
    NIP R> DROP ;

: _SPAW-ROOTS-CURRENT?  ( work -- flag )
    >R 0
    BEGIN DUP _SPA-TREE-COUNT < WHILE
        DUP R@ _SPAW-ROOT-CURRENT? 0= IF
            DROP R> DROP 0 EXIT
        THEN
        1+
    REPEAT
    DROP R> DROP -1 ;

: _SPAW-ROOT-ADVANCE-ONE  ( index work -- status )
    >R
    DUP R@ _SPAW-ROOT PBTREE-ROOT-GENERATION@
    DUP R@ _SPAW.BASE-GENERATION @ = IF
        DROP
        DUP R@ _SPAW-ROOT
        R@ _SPAW.TEMP-ROOT
        2 PICK R@ _SPAW-TREE PBTREE-ROOT-ADVANCE
        DUP IF
            _SPA-PERSIST>STATUS >R DROP R> R> DROP EXIT
        THEN DROP
        R@ _SPAW.TEMP-ROOT
        OVER R@ _SPAW-ROOT PBTREE-ROOT-COPY
        _SPA-PERSIST>STATUS NIP R> DROP EXIT
    THEN
    R@ _SPAW.BASE-GENERATION @ 1+ <> IF
        DROP R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    DROP R> DROP STREAMS-PA-S-OK ;

: _SPAW-ROOTS-ADVANCE  ( work -- status )
    >R 0
    BEGIN DUP _SPA-TREE-COUNT < WHILE
        DUP R@ _SPAW-ROOT-ADVANCE-ONE
        DUP IF >R DROP R> R> DROP EXIT THEN DROP
        1+
    REPEAT
    DROP R> DROP STREAMS-PA-S-OK ;

: _SPAW-ROOTS>STAGING  ( work -- status )
    >R 0
    BEGIN DUP _SPA-TREE-COUNT < WHILE
        DUP R@ _SPAW-ROOT
        OVER R@ _SPAW-STAGING-ROOT
        PBTREE-ROOT-COPY
        DUP IF
            _SPA-PERSIST>STATUS >R DROP R> R> DROP EXIT
        THEN DROP
        1+
    REPEAT
    DROP
    -1 R@ _SPAW.STAGING-ACTIVE !
    R> DROP STREAMS-PA-S-OK ;

: _SPAW-STAGING-ROOT-ADVANCE-ONE  ( index work -- status )
    >R
    DUP R@ _SPAW-STAGING-ROOT PBTREE-ROOT-GENERATION@
    DUP R@ _SPAW.BASE-GENERATION @ = IF
        DROP
        DUP R@ _SPAW-STAGING-ROOT
        R@ _SPAW.TEMP-ROOT
        2 PICK R@ _SPAW-TREE PBTREE-ROOT-ADVANCE
        DUP IF
            _SPA-PERSIST>STATUS >R DROP R> R> DROP EXIT
        THEN DROP
        R@ _SPAW.TEMP-ROOT
        OVER R@ _SPAW-STAGING-ROOT PBTREE-ROOT-COPY
        _SPA-PERSIST>STATUS NIP R> DROP EXIT
    THEN
    R@ _SPAW.BASE-GENERATION @ 1+ <> IF
        DROP R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    DROP R> DROP STREAMS-PA-S-OK ;

: _SPAW-STAGING-ROOTS-ADVANCE  ( work -- status )
    >R
    R@ _SPAW.STAGING-ACTIVE @ 0= IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    0
    BEGIN DUP _SPA-TREE-COUNT < WHILE
        DUP R@ _SPAW-STAGING-ROOT-ADVANCE-ONE
        DUP IF >R DROP R> R> DROP EXIT THEN DROP
        1+
    REPEAT
    DROP R> DROP STREAMS-PA-S-OK ;

: _SPAW-STAGING>ROOTS  ( work -- status )
    >R
    R@ _SPAW.STAGING-ACTIVE @ 0= IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    0
    BEGIN DUP _SPA-TREE-COUNT < WHILE
        DUP R@ _SPAW-STAGING-ROOT
        OVER R@ _SPAW-ROOT
        PBTREE-ROOT-COPY
        DUP IF
            _SPA-PERSIST>STATUS >R DROP R> R> DROP EXIT
        THEN DROP
        1+
    REPEAT
    DROP R> DROP STREAMS-PA-S-OK ;

: _SPA-ADD?  ( nonnegative-a nonnegative-b -- sum flag )
    OVER 0< OVER 0< OR IF 2DROP 0 0 EXIT THEN
    2DUP + DUP 0< IF DROP 2DROP 0 0 EXIT THEN
    DUP PERSIST-MAX-SIGNED > IF DROP 2DROP 0 0 EXIT THEN
    DUP 3 PICK U< IF DROP 2DROP 0 0 EXIT THEN
    >R 2DROP R> -1 ;

: _SPA-MUL?  ( nonnegative-a positive-small-b -- product flag )
    OVER 0< OVER 0> 0= OR IF 2DROP 0 0 EXIT THEN
    PERSIST-MAX-SIGNED OVER / 2 PICK < IF
        2DROP 0 0 EXIT
    THEN
    * -1 ;

: _SPAW-DIRECTORY-CARDINALITY?  ( authority-root work -- flag )
    >R
    \ Current sources have source-rid plus source-order rows; removed sources
    \ retain only their source-rid tombstone; accepted attempts add active rows.
    DUP SAR.SOURCE-COUNT @ 2 _SPA-MUL?
    0= IF 2DROP R> DROP 0 EXIT THEN
    OVER SAR.REMOVED-SOURCE-COUNT @ _SPA-ADD?
    0= IF 2DROP R> DROP 0 EXIT THEN
    OVER SAR.ACTIVE-COUNT @ _SPA-ADD?
    0= IF 2DROP R> DROP 0 EXIT THEN
    STREAMS-PI-TREE-DIRECTORY R@ _SPAW-ROOT
        PBTREE-ROOT-CARDINALITY@ =
    NIP R> DROP ;

: _SPAW-ATTEMPTS-CARDINALITY?  ( authority-root work -- flag )
    >R
    DUP SAR.ATTEMPT-COUNT @
    STREAMS-PI-TREE-ATTEMPTS R@ _SPAW-ROOT
        PBTREE-ROOT-CARDINALITY@ =
    NIP R> DROP ;

: _SPAW-IDENTITIES-CARDINALITY?  ( authority-root work -- flag )
    >R
    DUP SAR.NATIVE-COUNT @ OVER SAR.OBSERVATION-COUNT @ _SPA-ADD?
    0= IF 2DROP R> DROP 0 EXIT THEN
    STREAMS-PI-TREE-IDENTITIES R@ _SPAW-ROOT
        PBTREE-ROOT-CARDINALITY@ =
    NIP R> DROP ;

\ ABI 1 has no exact configured-provider thread evidence.  The reserved
\ thread family therefore contributes zero rows: every observation has
\ exactly one global-time and one source-time ordering.
: _SPAW-ORDERINGS-CARDINALITY?  ( authority-root work -- flag )
    >R
    DUP SAR.OBSERVATION-COUNT @ 2 _SPA-MUL?
    0= IF 2DROP R> DROP 0 EXIT THEN
    STREAMS-PI-TREE-ORDERINGS R@ _SPAW-ROOT
        PBTREE-ROOT-CARDINALITY@ =
    NIP R> DROP ;

: _SPAW-CARDINALITIES?  ( work -- flag )
    >R
    R@ _SPAW.AUTHORITY-ROOT
    DUP R@ _SPAW-DIRECTORY-CARDINALITY? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP R@ _SPAW-ATTEMPTS-CARDINALITY? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP R@ _SPAW-IDENTITIES-CARDINALITY? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    R@ _SPAW-ORDERINGS-CARDINALITY?
    R> DROP ;

: _SPAW-ROOTS-PROPOSED?  ( work -- flag )
    >R 0
    BEGIN DUP _SPA-TREE-COUNT < WHILE
        DUP R@ _SPAW-ROOT
        OVER R@ _SPAW-TREE PBTREE-ROOT-VALID? 0= IF
            DROP R> DROP 0 EXIT
        THEN
        DUP R@ _SPAW-ROOT PBTREE-ROOT-GENERATION@
        R@ _SPAW.BASE-GENERATION @ 1+ <> IF
            DROP R> DROP 0 EXIT
        THEN
        1+
    REPEAT
    DROP R> DROP -1 ;

\ Seal validation is intentionally first on cold load.  Only a supported,
\ self-consistent header is copied into mutable work; bound tree scopes,
\ generations, cardinalities, and reclaim state follow in that order.
: _SPAW-ROOT>WORK  ( payload-a payload-u work -- status )
    >R
    DUP STREAMS-AUTHORITY-ROOT-SIZE <> IF
        2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    OVER STREAMS-AUTHORITY-ROOT-HEADER-CLASSIFY
        _SPA-ROOT>STATUS
    DUP IF >R 2DROP R> R> DROP EXIT THEN DROP
    OVER R@ _SPAW.AUTHORITY-ROOT STREAMS-AUTHORITY-ROOT-SIZE MOVE
    2DROP
    0
    BEGIN DUP _SPA-TREE-COUNT < WHILE
        DUP R@ _SPAW.PAGE-ID !
        R@ _SPAW.PAGE-ID @ R@ _SPAW.AUTHORITY-ROOT
            STREAMS-AUTHORITY-ROOT-TREE
        R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
        PBTREE-ROOT-COPY
        DUP IF
            _SPA-PERSIST>STATUS >R DROP R> R> DROP EXIT
        THEN DROP
        R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
        R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
            PBTREE-ROOT-VALID? 0= IF
            DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
        THEN
        R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
            PBTREE-ROOT-GENERATION@
        R@ _SPAW.ADAPTER @ _SPA-D.STORE @
            PSTORE-GENERATION@ <> IF
            DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
        THEN
        1+
    REPEAT
    DROP
    R@ _SPAW-CARDINALITIES? 0= IF
        R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    R@ _SPAW.AUTHORITY-ROOT SAR.RECLAIM-STATE
        RECLAIM-STATE-SIZE
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.RECLAIM RECLAIM-OPEN
    _SPA-PERSIST>STATUS
    DUP IF R> DROP EXIT THEN DROP
    -1 R@ _SPAW.AUTHORITY-PRESENT !
    _SPAW-STATE-READY R@ _SPAW.STATE !
    0 R@ _SPAW.STAGING-ACTIVE !
    R> DROP STREAMS-PA-S-OK ;

\ Serialization copies all physical roots and finalized reclaim state before
\ sealing.  Header validation and bound cardinality reconciliation are then
\ repeated before any page can become the PSTORE application root.
: _SPAW-WORK>ROOT  ( work -- status )
    >R
    R@ _SPAW.AUTHORITY-PRESENT @ 0= IF
        R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    R@ _SPAW-ROOTS-PROPOSED? 0= IF
        R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    0
    BEGIN DUP _SPA-TREE-COUNT < WHILE
        DUP R@ _SPAW-ROOT
        OVER R@ _SPAW.AUTHORITY-ROOT
            STREAMS-AUTHORITY-ROOT-TREE
        PBTREE-ROOT-COPY
        DUP IF
            _SPA-PERSIST>STATUS >R DROP R> R> DROP EXIT
        THEN DROP
        1+
    REPEAT
    DROP
    R@ _SPAW.AUTHORITY-ROOT SAR.RECLAIM-STATE
        RECLAIM-STATE-SIZE
    R@ _SPAW.RECLAIM-WORK RECLAIM-STATE!
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.AUTHORITY-ROOT STREAMS-AUTHORITY-ROOT-SEAL
        _SPA-ROOT>STATUS
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW.AUTHORITY-ROOT
        STREAMS-AUTHORITY-ROOT-HEADER-CLASSIFY
        _SPA-ROOT>STATUS
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW-CARDINALITIES? 0= IF
        R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    R> DROP STREAMS-PA-S-OK ;

: _SPAW-LOAD-CURRENT  ( work -- status )
    >R
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @ PSTORE-CURRENT-ROOT@
    DUP 0= IF DROP R> DROP STREAMS-PA-S-CORRUPT EXIT THEN
    PROOTV.APPLICATION-ROOT @ DUP 0< IF
        DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    R@ _SPAW.PAGE-ID !
    R@ _SPAW.PAGE-ID @ R@ _SPAW.APP-ROOT-PAGE !
    R@ _SPAW.PAGE-ID @
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-READ-PAGE
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.PSTORE-WORK @ PSTORE-PAGE-PAYLOAD$
    R> _SPAW-ROOT>WORK ;

: _SPAW-BIND-EMPTY-RECLAIM  ( work -- status )
    >R
    R@ _SPAW.PAGE RECLAIM-STATE-SIZE RECLAIM-STATE-INIT
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.PAGE RECLAIM-STATE-SIZE
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.RECLAIM RECLAIM-OPEN
    _SPA-PERSIST>STATUS
    R> DROP ;

: _SPAW-OPEN-EMPTY  ( work -- status )
    >R
    R@ _SPAW-ROOTS-INIT DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW-BIND-EMPTY-RECLAIM DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW.AUTHORITY-ROOT STREAMS-AUTHORITY-ROOT-SIZE 0 FILL
    0 R@ _SPAW.AUTHORITY-PRESENT !
    0 R@ _SPAW.STAGING-ACTIVE !
    -1 R@ _SPAW.APP-ROOT-PAGE !
    _SPAW-STATE-READY R@ _SPAW.STATE !
    R> DROP STREAMS-PA-S-ABSENT ;

: _SPAW-OPEN-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE = IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    _SPAW-STATE-REOPEN R@ _SPAW.STATE !
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-OPEN
    DUP PERSIST-S-ABSENT = IF
        DROP R> _SPAW-OPEN-EMPTY EXIT
    THEN
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @ PSTORE-CURRENT-ROOT@
    DUP 0= IF DROP R> DROP STREAMS-PA-S-CORRUPT EXIT THEN
    PROOTV.APPLICATION-ROOT @ 0< IF
        R> _SPAW-OPEN-EMPTY EXIT
    THEN
    R> _SPAW-LOAD-CURRENT ;

: STREAMS-PA-OPEN  ( adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R 2DROP R> EXIT THEN DROP
    DUP ['] _SPAW-OPEN-RUN _SPAW-WORK-CATCH
    ROT ROT _SPAW-LEAVE ;

: STREAMS-PA-REBIND  ( adapter work -- status )
    STREAMS-PA-OPEN ;

\ A failed or uncertain publication always leaves this true until OPEN has
\ resolved the atomic roots and rebuilt every borrowed physical view.
: STREAMS-PA-REOPEN-REQUIRED?  ( work -- flag )
    DUP STREAMS-PA-WORK-VALID? IF
        _SPAW.STATE @ _SPAW-STATE-REOPEN =
    ELSE
        DROP -1
    THEN ;

: _SPAW-READY?  ( work -- flag )
    DUP _SPAW.STATE @ _SPAW-STATE-READY =
    OVER _SPAW.RECLAIM RECLAIM-STORE@ 0<> AND
    SWAP DROP ;

: STREAMS-PA-ACTIVE?  ( work -- flag )
    DUP STREAMS-PA-WORK-VALID? IF
        _SPAW.STATE @ _SPAW-STATE-ACTIVE =
    ELSE
        DROP 0
    THEN ;

: STREAMS-PA-AUTHORITY-ROOT@  ( work -- root|0 )
    DUP STREAMS-PA-WORK-VALID? 0= IF DROP 0 EXIT THEN
    DUP _SPAW.STATE @ DUP _SPAW-STATE-READY =
        SWAP _SPAW-STATE-ACTIVE = OR 0= IF DROP 0 EXIT THEN
    DUP _SPAW.AUTHORITY-PRESENT @ 0= IF DROP 0 EXIT THEN
    _SPAW.AUTHORITY-ROOT ;

: STREAMS-PA-TREE-ROOT@  ( tree-index work -- root|0 )
    >R
    R@ STREAMS-PA-WORK-VALID? 0= IF DROP R> DROP 0 EXIT THEN
    DUP 0< OVER _SPA-TREE-COUNT >= OR IF
        DROP R> DROP 0 EXIT
    THEN
    R@ _SPAW.STATE @ DUP _SPAW-STATE-READY =
        SWAP _SPAW-STATE-ACTIVE = OR 0= IF
        DROP R> DROP 0 EXIT
    THEN
    R> _SPAW-ROOT ;

: STREAMS-PA-LOGICAL-GENERATION@  ( work -- generation|-1 )
    DUP STREAMS-PA-AUTHORITY-ROOT@ DUP IF
        NIP SAR.LOGICAL-GENERATION @
    ELSE
        2DROP -1
    THEN ;

: STREAMS-PA-MUTATION-SEQUENCE@  ( work -- sequence|-1 )
    DUP STREAMS-PA-AUTHORITY-ROOT@ DUP IF
        NIP SAR.MUTATION-SEQUENCE @
    ELSE
        2DROP -1
    THEN ;

\ ---------------------------------------------------------------------
\ Transaction lifetime
\ ---------------------------------------------------------------------

: _SPAW-ABORT-ACTIVE  ( primary-status work -- final-status )
    >R
    DUP R@ _SPAW.TEMP-STATUS !
    \ Keep the reclaim proposal fenced until PSTORE has abandoned its root.
    R@ _SPAW.PSTORE-WORK @ PSTORE-PROPOSED-ROOT@ IF
        R@ _SPAW.ADAPTER @ _SPA-D.STORE @
        R@ _SPAW.PSTORE-WORK @ PSTORE-ABORT
        DUP PERSIST-S-OK <> IF
            _SPA-PERSIST>STATUS R@ _SPAW.TEMP-STATUS !
        ELSE
            DROP
        THEN
    THEN
    R@ _SPAW.PSTORE-WORK @ PSTORE-PROPOSED-ROOT@ 0= IF
        R@ _SPAW.RECLAIM-WORK RECLAIM-ABORT
        DUP PERSIST-S-OK <> IF
            _SPA-PERSIST>STATUS R@ _SPAW.TEMP-STATUS !
        ELSE
            DROP
        THEN
    THEN
    _SPAW-STATE-REOPEN R@ _SPAW.STATE !
    DROP R@ _SPAW.TEMP-STATUS @ R> DROP ;

: _SPAW-FAIL-ACTIVE  ( status work -- status )
    >R
    DUP IF
        R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE = IF
            R@ _SPAW-ABORT-ACTIVE
        THEN
    THEN
    R> DROP ;

: _SPAW-ABORT-STORE-PRIMARY  ( primary-status work -- final-status )
    >R
    DUP R@ _SPAW.TEMP-STATUS !
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-ABORT
    DUP PERSIST-S-OK <> IF
        _SPA-PERSIST>STATUS R@ _SPAW.TEMP-STATUS !
    ELSE
        DROP
    THEN
    DROP R@ _SPAW.TEMP-STATUS @ R> DROP ;

: _SPAW-BEGIN-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE = IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.STATE @ _SPAW-STATE-REOPEN = IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @ PSTORE-GENERATION@
        R@ _SPAW.BASE-GENERATION !
    R@ _SPAW.RECLAIM RECLAIM-STORE@ 0= IF
        R@ _SPAW-BIND-EMPTY-RECLAIM
        DUP IF R> DROP EXIT THEN DROP
    THEN
    R@ _SPAW-ROOTS-CURRENT? 0= IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @ PSTORE-CURRENT-ROOT@
    DUP IF
        PROOTV.APPLICATION-ROOT @
    ELSE
        DROP -1
    THEN
    R@ _SPAW.OLD-ROOT-PAGE !
    0 R@ _SPAW.RECLAIM-STEP-CALLS !
    0 R@ _SPAW.RECLAIM-MOVED !
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-BEGIN
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ R@ _SPAW.RECLAIM
    R@ _SPAW.RECLAIM-WORK RECLAIM-TX-BEGIN
    DUP IF
        _SPA-PERSIST>STATUS R@ _SPAW-ABORT-STORE-PRIMARY
        R> DROP EXIT
    THEN DROP
    _SPAW-STATE-ACTIVE R@ _SPAW.STATE !
    R@ _SPAW.OLD-ROOT-PAGE @ 0>= IF
        R@ _SPAW.OLD-ROOT-PAGE 1
        R@ _SPAW.RECLAIM-WORK RECLAIM-RETIRE-BATCH
        DUP IF
            _SPA-PERSIST>STATUS R@ _SPAW-ABORT-ACTIVE
            R> DROP EXIT
        THEN DROP
    THEN
    R@ _SPAW.BASE-GENERATION @ 0= IF
        R@ _SPAW-ROOTS-INIT
        DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
    THEN
    0 R@ _SPAW.MUTATION-N !
    0 R@ _SPAW.PHYSICAL-ONLY-N !
    0 R@ _SPAW.RESULT-U !
    -1 R@ _SPAW.APP-ROOT-PAGE !
    R@ _SPAW.BLOB PBLOB-SIZE 0 FILL
    R> DROP STREAMS-PA-S-OK ;

: STREAMS-PA-BEGIN  ( adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R 2DROP R> EXIT THEN DROP
    DUP ['] _SPAW-BEGIN-RUN _SPAW-WORK-CATCH
    OVER _SPAW-FAIL-ACTIVE
    ROT ROT _SPAW-LEAVE ;

: _SPAW-ABORT-RUN  ( work -- status )
    DUP _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        DROP STREAMS-PA-S-BUSY EXIT
    THEN
    STREAMS-PA-S-OK SWAP _SPAW-ABORT-ACTIVE ;

: STREAMS-PA-ABORT  ( adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R 2DROP R> EXIT THEN DROP
    DUP ['] _SPAW-ABORT-RUN _SPAW-WORK-CATCH
    ROT ROT _SPAW-LEAVE ;

: _SPAW-MARK-MUTATED-RUN  ( work -- status )
    DUP _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        DROP STREAMS-PA-S-BUSY EXIT
    THEN
    DUP _SPAW.MUTATION-N @ PERSIST-MAX-SIGNED >= IF
        DROP STREAMS-PA-S-CAPACITY EXIT
    THEN
    1 SWAP _SPAW.MUTATION-N +!
    STREAMS-PA-S-OK ;

\ Call this after an intentional metadata-only authority-root edit.  Index,
\ record, and blob mutation entry points account for themselves.
: STREAMS-PA-MARK-MUTATED  ( adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R 2DROP R> EXIT THEN DROP
    DUP ['] _SPAW-MARK-MUTATED-RUN _SPAW-WORK-CATCH
    ROT ROT _SPAW-LEAVE ;

\ ---------------------------------------------------------------------
\ Checked semantic records and visible index mutation
\ ---------------------------------------------------------------------

: _SPAW-SPAN-SAFE?  ( a u work -- flag )
    >R
    DUP IF OVER 0= IF 2DROP R> DROP 0 EXIT THEN THEN
    2DUP MSPAN-NONWRAPPING? 0= IF 2DROP R> DROP 0 EXIT THEN
    2DUP R@ STREAMS-PA-WORK-SIZE MSPAN-OVERLAP? IF
        2DROP R> DROP 0 EXIT
    THEN
    2DUP R@ _SPAW.PSTORE-WORK @ PSTORE-WORK-SIZE
        MSPAN-OVERLAP? IF 2DROP R> DROP 0 EXIT
    THEN
    R@ _SPAW.PSTORE-WORK @ PSTORE-WORK-RECORD-BUFFER$
    2OVER MSPAN-OVERLAP? IF 2DROP R> DROP 0 EXIT THEN
    2DUP R@ _SPAW.ADAPTER @ STREAMS-PA-SIZE
        MSPAN-OVERLAP? IF 2DROP R> DROP 0 EXIT
    THEN
    2DUP R@ _SPAW.ADAPTER @ _SPA-D.STORE @
        PSTORE-SPAN-DISJOINT? 0= IF 2DROP R> DROP 0 EXIT
    THEN
    2DROP R> DROP -1 ;

: STREAMS-PA-SPAN-DISJOINT?  ( address length work -- flag )
    >R
    R@ STREAMS-PA-WORK-VALID? 0= IF
        2DROP R> DROP 0 EXIT
    THEN
    R@ _SPAW-SPAN-SAFE?
    R> DROP ;

: _SPAW-KEY-INDEX  ( key-a key-u -- tree-index|-1 )
    2DUP STREAMS-PI-KEY-VALID? 0= IF 2DROP -1 EXIT THEN
    STREAMS-PI-KEY-FAMILY@ STREAMS-PI-FAMILY-TREE ;

: _SPAW-MUTABLE-KEY?  ( key-a key-u -- flag )
    2DUP STREAMS-PI-KEY-VALID? 0= IF 2DROP 0 EXIT THEN
    STREAMS-PI-KEY-FAMILY@ STREAMS-PI-F-THREAD-TIME <> ;

: _SPAW-APPEND  ( payload-a payload-u output-ref work -- status )
    >R
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-APPEND-RECORD
    _SPA-PERSIST>STATUS R> DROP ;

: _SPAW-PUT
  ( key-a key-u value-a value-u tree-index work -- status )
    >R
    DUP 0< OVER _SPA-TREE-COUNT >= OR IF
        DROP _SPA-DROP4 R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    DUP R@ _SPAW.PAGE-ID ! DROP
    R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
    R@ _SPAW.TEMP-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
    R@ _SPAW.BTREE-WORK PBTREE-PUT
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.BTREE-WORK PBTREE-RETIRED-PAGES$
    DUP IF
        R@ _SPAW.RECLAIM-WORK RECLAIM-RELEASE-BATCH
        DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    ELSE
        2DROP
    THEN
    R@ _SPAW.TEMP-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT PBTREE-ROOT-COPY
    _SPA-PERSIST>STATUS
    R> DROP ;

: _SPAW-DELETE  ( key-a key-u tree-index work -- status )
    >R
    DUP 0< OVER _SPA-TREE-COUNT >= OR IF
        _SPA-DROP3 R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    DUP R@ _SPAW.PAGE-ID ! DROP
    R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
    R@ _SPAW.TEMP-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
    R@ _SPAW.BTREE-WORK PBTREE-DELETE
    DUP PERSIST-S-NOT-FOUND = IF
        DROP R> DROP STREAMS-PA-S-NOT-FOUND EXIT
    THEN
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.BTREE-WORK PBTREE-RETIRED-PAGES$
    DUP IF
        R@ _SPAW.RECLAIM-WORK RECLAIM-RELEASE-BATCH
        DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    ELSE
        2DROP
    THEN
    R@ _SPAW.TEMP-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT PBTREE-ROOT-COPY
    _SPA-PERSIST>STATUS
    R> DROP ;

: _SPAW-APPEND-RECORD-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @ SPREC-VALID? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.DEST-A @ PERSIST-REF-SIZE
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @ R@ _SPAW.DEST-A @
    R@ _SPAW-APPEND
    DUP IF R> DROP EXIT THEN DROP
    R> _SPAW-MARK-MUTATED-RUN ;

: STREAMS-PA-APPEND-RECORD
  ( record-a record-u output-ref adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R _SPA-DROP5 R> EXIT THEN DROP
    >R
    3 PICK R@ _SPAW.ARG-A !
    2 PICK R@ _SPAW.ARG-U !
    1 PICK R@ _SPAW.DEST-A !
    R@ ['] _SPAW-APPEND-RECORD-RUN _SPAW-WORK-CATCH
    SWAP R@ _SPAW-LEAVE
    >R _SPA-DROP3 R> R> DROP ;

: _SPAW-BLOB-WRITE-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.TOTAL-U @ 0< IF R> DROP STREAMS-PA-S-INVALID EXIT THEN
    R@ _SPAW.SOURCE-XT @ 0= IF R> DROP STREAMS-PA-S-INVALID EXIT THEN
    R@ _SPAW.DEST-A @ PBLOB-SIZE R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.TOTAL-U @
    R@ _SPAW.SOURCE-XT @ R@ _SPAW.SOURCE-CONTEXT @
    R@ _SPAW.DEST-A @
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ R@ _SPAW.BLOB-WORK PBLOB-WRITE
    _SPA-PERSIST>STATUS
    DUP IF R> DROP EXIT THEN DROP
    R> _SPAW-MARK-MUTATED-RUN ;

: STREAMS-PA-BLOB-WRITE
  ( total-u source-xt source-context output-blob adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R _SPA-DROP6 R> EXIT THEN DROP
    >R
    4 PICK R@ _SPAW.TOTAL-U !
    3 PICK R@ _SPAW.SOURCE-XT !
    2 PICK R@ _SPAW.SOURCE-CONTEXT !
    1 PICK R@ _SPAW.DEST-A !
    R@ ['] _SPAW-BLOB-WRITE-RUN _SPAW-WORK-CATCH
    SWAP R@ _SPAW-LEAVE
    >R _SPA-DROP4 R> R> DROP ;

\ Read callbacks receive
\   ( logical-offset source-a offered-u sink-context -- status )
\ and must consume the complete offered span before returning OK.  PBLOB keeps
\ the transfer chunk-bounded; this surface never materializes a whole body in
\ adapter-owned memory.  Reads intentionally use only the published READY
\ authority, never an uncommitted transaction view.
: _SPAW-BLOB-READ-RANGE-RUN  ( work -- status )
    >R
    R@ _SPAW-READY? 0= IF R> DROP STREAMS-PA-S-BUSY EXIT THEN
    R@ _SPAW.ARG-A @ PBLOB-SIZE R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ PBLOB-VALID? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @
    R@ _SPAW.PAGE-ID @ R@ _SPAW.TOTAL-U @
    R@ _SPAW.SOURCE-XT @ R@ _SPAW.SOURCE-CONTEXT @
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ R@ _SPAW.BLOB-WORK PBLOB-READ-RANGE
    _SPA-PERSIST>STATUS
    R> DROP ;

: STREAMS-PA-BLOB-READ-RANGE
  ( blob offset requested-u sink-xt sink-context adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R _SPA-DROP6 DROP R> EXIT THEN DROP
    >R
    1 PICK R@ _SPAW.SOURCE-CONTEXT !
    2 PICK R@ _SPAW.SOURCE-XT !
    3 PICK R@ _SPAW.TOTAL-U !
    4 PICK R@ _SPAW.PAGE-ID !
    5 PICK R@ _SPAW.ARG-A !
    R@ ['] _SPAW-BLOB-READ-RANGE-RUN _SPAW-WORK-CATCH
    SWAP R@ _SPAW-LEAVE
    >R _SPA-DROP5 R> R> DROP ;

\ Migration readback uses the transaction-aware PBLOB reader so exact content
\ can be verified while its descriptor and chunks are still hidden behind the
\ staging roots.  No uncommitted descriptor is accepted outside an active
\ staging transaction.
: _SPAW-STAGED-BLOB-READ-RANGE-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.STAGING-ACTIVE @ 0= IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW.ARG-A @ PBLOB-SIZE R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ PBLOB-VALID? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @
    R@ _SPAW.PAGE-ID @ R@ _SPAW.TOTAL-U @
    R@ _SPAW.SOURCE-XT @ R@ _SPAW.SOURCE-CONTEXT @
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ R@ _SPAW.BLOB-WORK PBLOB-READ-RANGE-TX
    _SPA-PERSIST>STATUS
    R> DROP ;

: STREAMS-PA-STAGED-BLOB-READ-RANGE
  ( blob offset requested-u sink-xt sink-context adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R _SPA-DROP6 DROP R> EXIT THEN DROP
    >R
    1 PICK R@ _SPAW.SOURCE-CONTEXT !
    2 PICK R@ _SPAW.SOURCE-XT !
    3 PICK R@ _SPAW.TOTAL-U !
    4 PICK R@ _SPAW.PAGE-ID !
    5 PICK R@ _SPAW.ARG-A !
    R@ ['] _SPAW-STAGED-BLOB-READ-RANGE-RUN _SPAW-WORK-CATCH
    SWAP R@ _SPAW-LEAVE
    >R _SPA-DROP5 R> R> DROP ;

: _SPAW-BLOB-STREAM-RUN  ( work -- status )
    >R
    R@ _SPAW-READY? 0= IF R> DROP STREAMS-PA-S-BUSY EXIT THEN
    R@ _SPAW.ARG-A @ PBLOB-SIZE R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ PBLOB-VALID? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.PAGE-ID @
    R@ _SPAW.SOURCE-XT @ R@ _SPAW.SOURCE-CONTEXT @
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ R@ _SPAW.BLOB-WORK PBLOB-STREAM
    _SPA-PERSIST>STATUS
    R> DROP ;

: STREAMS-PA-BLOB-STREAM
  ( blob offset sink-xt sink-context adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R _SPA-DROP6 R> EXIT THEN DROP
    >R
    1 PICK R@ _SPAW.SOURCE-CONTEXT !
    2 PICK R@ _SPAW.SOURCE-XT !
    3 PICK R@ _SPAW.PAGE-ID !
    4 PICK R@ _SPAW.ARG-A !
    R@ ['] _SPAW-BLOB-STREAM-RUN _SPAW-WORK-CATCH
    SWAP R@ _SPAW-LEAVE
    >R _SPA-DROP4 R> R> DROP ;

: _SPAW-REF-AGREES?  ( work -- status )
    >R
    R@ _SPAW.VALUE-A @
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-READ-RECORD-TX
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.PSTORE-WORK @ PSTORE-RECORD-PAYLOAD$
    2DUP SPREC-VALID? 0= IF
        2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
    3 PICK 3 PICK STREAMS-PI-RECORD-AGREES? 0= IF
        2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    2DROP R> DROP STREAMS-PA-S-OK ;

: _SPAW-PUT-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.STAGING-ACTIVE @ IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        _SPAW-MUTABLE-KEY? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.VALUE-A @ PERSIST-REF-SIZE
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.VALUE-A @ PERSIST-REF-VALID? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW-REF-AGREES?
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @ _SPAW-KEY-INDEX
    DUP R@ _SPAW.PAGE-ID ! DROP
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
    R@ _SPAW.VALUE-A @ PERSIST-REF-SIZE
    R@ _SPAW.PAGE-ID @ R@ _SPAW-PUT
    DUP IF R> DROP EXIT THEN DROP
    R> _SPAW-MARK-MUTATED-RUN ;

: STREAMS-PA-PUT
  ( key-a key-u record-ref adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R _SPA-DROP5 R> EXIT THEN DROP
    >R
    3 PICK R@ _SPAW.ARG-A !
    2 PICK R@ _SPAW.ARG-U !
    1 PICK R@ _SPAW.VALUE-A !
    R@ ['] _SPAW-PUT-RUN _SPAW-WORK-CATCH
    SWAP R@ _SPAW-LEAVE
    >R _SPA-DROP3 R> R> DROP ;

: _SPAW-DELETE-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.STAGING-ACTIVE @ IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        _SPAW-MUTABLE-KEY? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @ _SPAW-KEY-INDEX
    DUP R@ _SPAW.PAGE-ID ! DROP
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
    R@ _SPAW.PAGE-ID @ R@ _SPAW-DELETE
    DUP IF R> DROP EXIT THEN DROP
    R> _SPAW-MARK-MUTATED-RUN ;

: STREAMS-PA-DELETE  ( key-a key-u adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R _SPA-DROP4 R> EXIT THEN DROP
    >R
    2 PICK R@ _SPAW.ARG-A !
    1 PICK R@ _SPAW.ARG-U !
    R@ ['] _SPAW-DELETE-RUN _SPAW-WORK-CATCH
    SWAP R@ _SPAW-LEAVE
    >R 2DROP R> R> DROP ;

: _SPAW-GET-RUN  ( work -- status )
    >R
    R@ _SPAW-READY? 0= IF R> DROP STREAMS-PA-S-BUSY EXIT THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @ _SPAW-KEY-INDEX
    DUP 0< IF DROP R> DROP STREAMS-PA-S-INVALID EXIT THEN
    R@ _SPAW.PAGE-ID !
    R@ _SPAW.DEST-U @ DUP 0< IF
        DROP R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.DEST-A @ SWAP R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
    R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
    R@ _SPAW.BTREE-WORK PBTREE-GET
    DUP IF
        _SPA-PERSIST>STATUS >R 2DROP R> R> DROP EXIT
    THEN DROP
    DUP PERSIST-REF-SIZE <> IF
        2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    OVER PERSIST-REF-VALID? 0= IF
        2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    OVER R@ _SPAW.RECORD-REF PERSIST-REF-COPY
    2DROP
    R@ _SPAW.RECORD-REF
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-READ-RECORD
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.PSTORE-WORK @ PSTORE-RECORD-PAYLOAD$
    2DUP SPREC-VALID? 0= IF
        2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
    3 PICK 3 PICK STREAMS-PI-RECORD-AGREES? 0= IF
        2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    DUP R@ _SPAW.DEST-U @ > IF
        2DROP R> DROP STREAMS-PA-S-CAPACITY EXIT
    THEN
    DUP R@ _SPAW.RESULT-U !
    OVER R@ _SPAW.DEST-A @ 2 PICK MOVE
    2DROP R> DROP STREAMS-PA-S-OK ;

: _SPAW-COUNT-RESULT  ( status work -- record-u status )
    >R
    DUP IF 0 SWAP ELSE R@ _SPAW.RESULT-U @ SWAP THEN
    R> DROP ;

: STREAMS-PA-GET
  ( key-a key-u destination-a destination-u adapter work -- record-u status )
    2DUP _SPAW-ENTER DUP IF
        >R _SPA-DROP6 0 R> EXIT
    THEN DROP
    >R
    4 PICK R@ _SPAW.ARG-A !
    3 PICK R@ _SPAW.ARG-U !
    2 PICK R@ _SPAW.DEST-A !
    1 PICK R@ _SPAW.DEST-U !
    R@ ['] _SPAW-GET-RUN _SPAW-WORK-CATCH
    SWAP R@ _SPAW-LEAVE
    R@ _SPAW-COUNT-RESULT
    >R >R _SPA-DROP4 R> R> R> DROP ;

\ Read one exact semantic record from the caller's hidden staging roots while
\ the surrounding adapter transaction is active.  This is deliberately a
\ point lookup rather than a general uncommitted query surface: cold migration
\ already knows every canonical key it inserted and uses this word only for
\ exact readback verification before the first authority publication.
: _SPAW-STAGED-GET-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.STAGING-ACTIVE @ 0= IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @ _SPAW-KEY-INDEX
    DUP 0< IF DROP R> DROP STREAMS-PA-S-INVALID EXIT THEN
    R@ _SPAW.PAGE-ID !
    R@ _SPAW.DEST-U @ DUP 0< IF
        DROP R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.DEST-A @ SWAP R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
    R@ _SPAW.PAGE-ID @ R@ _SPAW-STAGING-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
    R@ _SPAW.BTREE-WORK PBTREE-GET-TX
    DUP IF
        _SPA-PERSIST>STATUS >R 2DROP R> R> DROP EXIT
    THEN DROP
    DUP PERSIST-REF-SIZE <> IF
        2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    OVER PERSIST-REF-VALID? 0= IF
        2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    OVER R@ _SPAW.RECORD-REF PERSIST-REF-COPY
    2DROP
    R@ _SPAW.RECORD-REF
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-READ-RECORD-TX
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.PSTORE-WORK @ PSTORE-RECORD-PAYLOAD$
    2DUP SPREC-VALID? 0= IF
        2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
    3 PICK 3 PICK STREAMS-PI-RECORD-AGREES? 0= IF
        2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    DUP R@ _SPAW.DEST-U @ > IF
        2DROP R> DROP STREAMS-PA-S-CAPACITY EXIT
    THEN
    DUP R@ _SPAW.RESULT-U !
    OVER R@ _SPAW.DEST-A @ 2 PICK MOVE
    2DROP R> DROP STREAMS-PA-S-OK ;

: STREAMS-PA-STAGED-GET
  ( key-a key-u destination-a destination-u adapter work -- record-u status )
    2DUP _SPAW-ENTER DUP IF
        >R _SPA-DROP6 0 R> EXIT
    THEN DROP
    >R
    4 PICK R@ _SPAW.ARG-A !
    3 PICK R@ _SPAW.ARG-U !
    2 PICK R@ _SPAW.DEST-A !
    1 PICK R@ _SPAW.DEST-U !
    R@ ['] _SPAW-STAGED-GET-RUN _SPAW-WORK-CATCH
    SWAP R@ _SPAW-LEAVE
    R@ _SPAW-COUNT-RESULT
    >R >R _SPA-DROP4 R> R> R> DROP ;

\ ---------------------------------------------------------------------
\ Bounded semantic ranges
\ ---------------------------------------------------------------------
\ Only the five query-bearing L13 families plus bounded ACTIVE-ATTEMPT
\ recovery are admitted here.  ACTIVE-ATTEMPT, SOURCE-ORDER, and GLOBAL-TIME
\ require their exact one-byte family prefix; ATTEMPT-BY-SOURCE,
\ OBSERVATION-REVISION, and SOURCE-TIME require their exact RID-scoped prefix.
\ THREAD-TIME is explicitly unsupported in ABI 1.
\
\ FIRST walks forward from the exact prefix.  LAST starts immediately before
\ the family's canonical seek-only upper boundary and walks backward.  AFTER
\ walks forward strictly after a complete semantic key.  BEFORE walks backward
\ strictly before a complete semantic key.  Backward results are reversed into
\ ascending key order before return.  Thus callers resume AFTER with the last
\ row's KEY$, and resume BEFORE with the first row's KEY$.  No physical cursor
\ or storage identity crosses the call boundary.

0 CONSTANT _SPA-RANGE-FIRST
1 CONSTANT _SPA-RANGE-AFTER
2 CONSTANT _SPA-RANGE-BEFORE
3 CONSTANT _SPA-RANGE-LAST

: _SPA-RANGE-MODE?  ( mode -- flag )
    DUP _SPA-RANGE-FIRST >=
    SWAP _SPA-RANGE-LAST <= AND ;

: _SPAW-RANGE-PREFIX-CLASSIFY
  ( prefix-a prefix-u work -- status )
    >R
    2DUP STREAMS-PI-ACTIVE-ATTEMPT-PREFIX-VALID? IF
        2DROP
        STREAMS-PI-TREE-DIRECTORY R@ _SPAW.PAGE-ID !
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    2DUP STREAMS-PI-SOURCE-ORDER-PREFIX-VALID? IF
        2DROP
        STREAMS-PI-TREE-DIRECTORY R@ _SPAW.PAGE-ID !
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    2DUP STREAMS-PI-ATTEMPT-BY-SOURCE-PREFIX-VALID? IF
        2DROP
        STREAMS-PI-TREE-ATTEMPTS R@ _SPAW.PAGE-ID !
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    2DUP STREAMS-PI-OBSERVATION-REVISION-PREFIX-VALID? IF
        2DROP
        STREAMS-PI-TREE-IDENTITIES R@ _SPAW.PAGE-ID !
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    2DUP STREAMS-PI-GLOBAL-TIME-PREFIX-VALID? IF
        2DROP
        STREAMS-PI-TREE-ORDERINGS R@ _SPAW.PAGE-ID !
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    2DUP STREAMS-PI-SOURCE-TIME-PREFIX-VALID? IF
        2DROP
        STREAMS-PI-TREE-ORDERINGS R@ _SPAW.PAGE-ID !
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    2DUP STREAMS-PI-THREAD-TIME-FAMILY-PREFIX-VALID? IF
        2DROP R> DROP STREAMS-PA-S-UNSUPPORTED EXIT
    THEN
    2DUP STREAMS-PI-THREAD-TIME-PREFIX-VALID? IF
        2DROP R> DROP STREAMS-PA-S-UNSUPPORTED EXIT
    THEN
    2DROP R> DROP STREAMS-PA-S-INVALID ;

: _SPAW-RANGE-RESUME?  ( work -- flag )
    >R
    R@ _SPAW.VALUE-A @ R@ _SPAW.SOURCE-CONTEXT @
        R@ _SPAW-SPAN-SAFE? 0= IF R> DROP 0 EXIT THEN
    R@ _SPAW.VALUE-A @ R@ _SPAW.SOURCE-CONTEXT @
        STREAMS-PI-KEY-VALID? 0= IF R> DROP 0 EXIT THEN
    R@ _SPAW.VALUE-A @ R@ _SPAW.SOURCE-CONTEXT @
        _SPAW-KEY-INDEX
    R@ _SPAW.PAGE-ID @ <> IF R> DROP 0 EXIT THEN
    R@ _SPAW.SOURCE-CONTEXT @ R@ _SPAW.ARG-U @ < IF
        R> DROP 0 EXIT
    THEN
    R@ _SPAW.VALUE-A @ R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        _SPA-BYTES=
    R> DROP ;

: _SPAW-RANGE-LAST-BOUNDARY  ( work -- status )
    >R
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        STREAMS-PI-SOURCE-ORDER-PREFIX-VALID? IF
        R@ _SPAW.RANGE-KEY
            STREAMS-PI-SOURCE-ORDER-LAST-BOUNDARY
        DUP IF
            DROP R> DROP STREAMS-PA-S-INVALID EXIT
        THEN DROP
        STREAMS-PI-SOURCE-ORDER-KEY-SIZE
            R@ _SPAW.SOURCE-CONTEXT !
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        STREAMS-PI-ATTEMPT-BY-SOURCE-PREFIX-VALID? IF
        R@ _SPAW.ARG-A @ 1+
        R@ _SPAW.RANGE-KEY
            STREAMS-PI-ATTEMPT-BY-SOURCE-LAST-BOUNDARY
        DUP IF
            DROP R> DROP STREAMS-PA-S-INVALID EXIT
        THEN DROP
        STREAMS-PI-ATTEMPT-BY-SOURCE-KEY-SIZE
            R@ _SPAW.SOURCE-CONTEXT !
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        STREAMS-PI-OBSERVATION-REVISION-PREFIX-VALID? IF
        R@ _SPAW.ARG-A @ 1+
        R@ _SPAW.RANGE-KEY
            STREAMS-PI-OBSERVATION-REVISION-LAST-BOUNDARY
        DUP IF
            DROP R> DROP STREAMS-PA-S-INVALID EXIT
        THEN DROP
        STREAMS-PI-OBSERVATION-REVISION-KEY-SIZE
            R@ _SPAW.SOURCE-CONTEXT !
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        STREAMS-PI-GLOBAL-TIME-PREFIX-VALID? IF
        R@ _SPAW.RANGE-KEY
            STREAMS-PI-GLOBAL-TIME-LAST-BOUNDARY
        DUP IF
            DROP R> DROP STREAMS-PA-S-INVALID EXIT
        THEN DROP
        STREAMS-PI-GLOBAL-TIME-KEY-SIZE
            R@ _SPAW.SOURCE-CONTEXT !
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        STREAMS-PI-SOURCE-TIME-PREFIX-VALID? IF
        R@ _SPAW.ARG-A @ 1+
        R@ _SPAW.RANGE-KEY
            STREAMS-PI-SOURCE-TIME-LAST-BOUNDARY
        DUP IF
            DROP R> DROP STREAMS-PA-S-INVALID EXIT
        THEN DROP
        STREAMS-PI-SOURCE-TIME-KEY-SIZE
            R@ _SPAW.SOURCE-CONTEXT !
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    R> DROP STREAMS-PA-S-INVALID ;

: _SPAW-RANGE-ARGS  ( work -- status )
    >R
    0 R@ _SPAW.RESULT-U !
    R@ _SPAW-READY? 0= IF R> DROP STREAMS-PA-S-BUSY EXIT THEN
    R@ _SPAW.SOURCE-XT @ _SPA-RANGE-MODE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        R@ _SPAW-RANGE-PREFIX-CLASSIFY
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW.SOURCE-XT @ DUP _SPA-RANGE-FIRST =
    SWAP _SPA-RANGE-LAST = OR IF
        R@ _SPAW.VALUE-A @
        R@ _SPAW.SOURCE-CONTEXT @ OR IF
            R> DROP STREAMS-PA-S-INVALID EXIT
        THEN
    ELSE
        R@ _SPAW-RANGE-RESUME? 0= IF
            R> DROP STREAMS-PA-S-INVALID EXIT
        THEN
    THEN
    R@ _SPAW.DEST-U @ DUP 1 <
    SWAP STREAMS-PA-RANGE-MAX > OR IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.DEST-U @ STREAMS-PA-RANGE-ROW-SIZE _SPA-MUL?
    0= IF DROP R> DROP STREAMS-PA-S-CAPACITY EXIT THEN
    R@ _SPAW.TOTAL-U !
    R@ _SPAW.DEST-A @ R@ _SPAW.TOTAL-U @
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.KEY PBTREE-KEY-MAX 0 FILL
    R@ _SPAW.ARG-A @ R@ _SPAW.KEY R@ _SPAW.ARG-U @ MOVE
    R@ _SPAW.RANGE-KEY PBTREE-KEY-MAX 0 FILL
    R@ _SPAW.SOURCE-XT @ _SPA-RANGE-LAST = IF
        R@ _SPAW-RANGE-LAST-BOUNDARY
        DUP IF R> DROP EXIT THEN DROP
    ELSE
        R@ _SPAW.SOURCE-XT @ _SPA-RANGE-FIRST <> IF
        R@ _SPAW.VALUE-A @ R@ _SPAW.RANGE-KEY
        R@ _SPAW.SOURCE-CONTEXT @ MOVE
        THEN
    THEN
    R@ _SPAW.KEY R@ _SPAW.ARG-A !
    R@ _SPAW.RANGE-KEY R@ _SPAW.VALUE-A !
    R@ _SPAW.DEST-A @ R@ _SPAW.TOTAL-U @ 0 FILL
    R> DROP STREAMS-PA-S-OK ;

: _SPAW-RANGE-ROW
  ( key-a key-u value-a value-u persist-status work -- status )
    >R
    DUP PERSIST-S-NOT-FOUND = IF
        DROP _SPA-DROP4 R> DROP STREAMS-PA-S-NOT-FOUND EXIT
    THEN
    DUP IF
        _SPA-PERSIST>STATUS >R
        _SPA-DROP4 R> R> DROP EXIT
    THEN
    DROP
    2 PICK R@ _SPAW.ARG-U @ < IF
        _SPA-DROP4 R> DROP STREAMS-PA-S-NOT-FOUND EXIT
    THEN
    3 PICK R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        _SPA-BYTES= 0= IF
        _SPA-DROP4 R> DROP STREAMS-PA-S-NOT-FOUND EXIT
    THEN
    3 PICK 3 PICK STREAMS-PI-KEY-VALID? 0= IF
        _SPA-DROP4 R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    DUP PERSIST-REF-SIZE <> IF
        _SPA-DROP4 R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    OVER PERSIST-REF-VALID? 0= IF
        _SPA-DROP4 R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    OVER R@ _SPAW.RECORD-REF PERSIST-REF-COPY
    2DROP
    R@ _SPAW.RECORD-REF
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-READ-RECORD
    DUP IF
        DUP PERSIST-S-NOT-FOUND = IF
            DROP 2DROP R> DROP STREAMS-PA-S-CORRUPT EXIT
        THEN
        _SPA-PERSIST>STATUS >R 2DROP R> R> DROP EXIT
    THEN
    DROP
    R@ _SPAW.PSTORE-WORK @ PSTORE-RECORD-PAYLOAD$
    2DUP SPREC-VALID? 0= IF
        _SPA-DROP4 R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    DUP STREAMS-PERSISTENCE-RECORD-MAX > IF
        _SPA-DROP4 R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    3 PICK 3 PICK 3 PICK 3 PICK
        STREAMS-PI-RECORD-AGREES? 0= IF
        _SPA-DROP4 R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    R@ _SPAW.RESULT-U @ R@ _SPAW.DEST-U @ >= IF
        _SPA-DROP4 R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    R@ _SPAW.RESULT-U @ STREAMS-PA-RANGE-ROW-SIZE *
    R@ _SPAW.DEST-A @ + R@ _SPAW.VALUE-A !
    R@ _SPAW.VALUE-A @ STREAMS-PA-RANGE-ROW-SIZE 0 FILL
    2 PICK R@ _SPAW.VALUE-A @ _SPAROW.KEY-U !
    DUP R@ _SPAW.VALUE-A @ _SPAROW.RECORD-U !
    3 PICK R@ _SPAW.VALUE-A @ _SPAROW.KEY
    4 PICK MOVE
    OVER R@ _SPAW.VALUE-A @ _SPAROW.RECORD
    2 PICK MOVE
    _SPA-DROP4
    R@ _SPAW.VALUE-A @ STREAMS-PA-RANGE-ROW-VALID? 0= IF
        R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    1 R@ _SPAW.RESULT-U +!
    R> DROP STREAMS-PA-S-OK ;

: _SPAW-RANGE-START  ( work -- status )
    >R
    R@ _SPAW.SOURCE-XT @ CASE
        _SPA-RANGE-FIRST OF
            R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
            R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
            R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
            R@ _SPAW.CURSOR R@ _SPAW.BTREE-WORK PBTREE-SEEK
        ENDOF
        _SPA-RANGE-AFTER OF
            R@ _SPAW.VALUE-A @ R@ _SPAW.SOURCE-CONTEXT @
            R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
            R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
            R@ _SPAW.CURSOR R@ _SPAW.BTREE-WORK PBTREE-RESUME
        ENDOF
        _SPA-RANGE-BEFORE OF
            R@ _SPAW.VALUE-A @ R@ _SPAW.SOURCE-CONTEXT @
            R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
            R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
            R@ _SPAW.CURSOR R@ _SPAW.BTREE-WORK
                PBTREE-SEEK-BEFORE
        ENDOF
        _SPA-RANGE-LAST OF
            R@ _SPAW.VALUE-A @ R@ _SPAW.SOURCE-CONTEXT @
            R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
            R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
            R@ _SPAW.CURSOR R@ _SPAW.BTREE-WORK
                PBTREE-SEEK-BEFORE
        ENDOF
        DROP 0 0 0 0 PERSIST-S-INVALID 0
    ENDCASE
    R@ _SPAW-RANGE-ROW
    R> DROP ;

: _SPAW-RANGE-NEXT  ( work -- status )
    >R
    R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
    R@ _SPAW.CURSOR R@ _SPAW.BTREE-WORK
    R@ _SPAW.SOURCE-XT @ DUP _SPA-RANGE-BEFORE =
    SWAP _SPA-RANGE-LAST = OR IF
        PBTREE-PREV
    ELSE
        PBTREE-NEXT
    THEN
    R@ _SPAW-RANGE-ROW
    R> DROP ;

: _SPAW-RANGE-REVERSE  ( work -- )
    >R 0
    BEGIN
        DUP R@ _SPAW.RESULT-U @ 2 / <
    WHILE
        R@ _SPAW.DEST-A @
        OVER STREAMS-PA-RANGE-ROW-SIZE * +
        R@ _SPAW.PAGE STREAMS-PA-RANGE-ROW-SIZE MOVE
        R@ _SPAW.DEST-A @
        R@ _SPAW.RESULT-U @ 1- 2 PICK -
        STREAMS-PA-RANGE-ROW-SIZE * +
        R@ _SPAW.DEST-A @
        2 PICK STREAMS-PA-RANGE-ROW-SIZE * +
        STREAMS-PA-RANGE-ROW-SIZE MOVE
        R@ _SPAW.PAGE
        R@ _SPAW.DEST-A @
        R@ _SPAW.RESULT-U @ 1- 3 PICK -
        STREAMS-PA-RANGE-ROW-SIZE * +
        STREAMS-PA-RANGE-ROW-SIZE MOVE
        1+
    REPEAT
    DROP R> DROP ;

: _SPAW-RANGE-SUCCESS  ( work -- status )
    DUP _SPAW.SOURCE-XT @ DUP _SPA-RANGE-BEFORE =
    SWAP _SPA-RANGE-LAST = OR IF
        DUP _SPAW-RANGE-REVERSE
    THEN
    DROP STREAMS-PA-S-OK ;

: _SPAW-RANGE-FAIL  ( status work -- status )
    >R
    R@ _SPAW.DEST-A @ R@ _SPAW.TOTAL-U @ 0 FILL
    0 R@ _SPAW.RESULT-U !
    R> DROP ;

: _SPAW-RANGE-RUN  ( work -- status )
    >R
    R@ _SPAW-RANGE-ARGS
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW.PAGE-ID @ R@ _SPAW-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
    R@ _SPAW.CURSOR PBTREE-CURSOR-INIT
    DUP IF
        _SPA-PERSIST>STATUS R@ _SPAW-RANGE-FAIL
        R> DROP EXIT
    THEN
    DROP
    R@ _SPAW-RANGE-START
    DUP STREAMS-PA-S-NOT-FOUND = IF
        DROP R> _SPAW-RANGE-SUCCESS EXIT
    THEN
    DUP IF R@ _SPAW-RANGE-FAIL R> DROP EXIT THEN
    DROP
    BEGIN
        R@ _SPAW.RESULT-U @ R@ _SPAW.DEST-U @ <
    WHILE
        R@ _SPAW-RANGE-NEXT
        DUP STREAMS-PA-S-NOT-FOUND = IF
            DROP R> _SPAW-RANGE-SUCCESS EXIT
        THEN
        DUP IF R@ _SPAW-RANGE-FAIL R> DROP EXIT THEN
        DROP
    REPEAT
    R> _SPAW-RANGE-SUCCESS ;

\ Internal stack:
\   prefix-a prefix-u exclusive-key-a exclusive-key-u
\   rows-a capacity mode adapter work -- count status
: _STREAMS-PA-RANGE-PUBLIC
    2DUP _SPAW-ENTER DUP IF
        >R _SPA-DROP9 0 R> EXIT
    THEN
    DROP
    >R
    1 PICK R@ _SPAW.SOURCE-XT !
    2 PICK R@ _SPAW.DEST-U !
    3 PICK R@ _SPAW.DEST-A !
    4 PICK R@ _SPAW.SOURCE-CONTEXT !
    5 PICK R@ _SPAW.VALUE-A !
    6 PICK R@ _SPAW.ARG-U !
    7 PICK R@ _SPAW.ARG-A !
    R@ ['] _SPAW-RANGE-RUN _SPAW-WORK-CATCH
    SWAP R@ _SPAW-LEAVE
    R@ _SPAW-COUNT-RESULT
    >R >R _SPA-DROP7 R> R> R> DROP ;

: STREAMS-PA-RANGE-FIRST
  ( prefix-a prefix-u rows-a capacity adapter work -- count status )
    >R >R >R >R
    0 0 R> R> _SPA-RANGE-FIRST R> R>
    _STREAMS-PA-RANGE-PUBLIC ;

: STREAMS-PA-RANGE-LAST
  ( prefix-a prefix-u rows-a capacity adapter work -- count status )
    >R >R >R >R
    0 0 R> R> _SPA-RANGE-LAST R> R>
    _STREAMS-PA-RANGE-PUBLIC ;

: STREAMS-PA-RANGE-AFTER
  ( prefix-a prefix-u exclusive-key-a exclusive-key-u rows-a capacity adapter work -- count status )
    >R >R
    _SPA-RANGE-AFTER R> R>
    _STREAMS-PA-RANGE-PUBLIC ;

: STREAMS-PA-RANGE-BEFORE
  ( prefix-a prefix-u exclusive-key-a exclusive-key-u rows-a capacity adapter work -- count status )
    >R >R
    _SPA-RANGE-BEFORE R> R>
    _STREAMS-PA-RANGE-PUBLIC ;

\ ---------------------------------------------------------------------
\ Atomic application-root publication
\ ---------------------------------------------------------------------

: _SPAW-COMMIT-DURABLE?  ( work -- flag )
    >R
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @ PSTORE-GENERATION@
    R@ _SPAW.BASE-GENERATION @ 1+ =
    R@ _SPAW.PSTORE-WORK @ PSTORE-PROPOSED-ROOT@ 0= AND
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @ PSTORE-UNCERTAIN? 0= AND
    R> DROP ;

: _SPAW-PUBLISH-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW-ROOTS-ADVANCE
    DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
    R@
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ _SPAW-ALLOCATE
    DUP IF
        _SPA-PERSIST>STATUS >R DROP R>
        R@ _SPAW-ABORT-ACTIVE R> DROP EXIT
    THEN DROP
    R@ _SPAW.APP-ROOT-PAGE !
    \ Claim the application-root slot before reclaim finalization, including
    \ when a high-water staging transaction cannot consume ready pages.
    R@ _SPAW.PAGE PERSIST-PAGE-PAYLOAD-SIZE 0 FILL
    R@ _SPAW.PAGE PERSIST-PAGE-PAYLOAD-SIZE
    R@ _SPAW.APP-ROOT-PAGE @
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-WRITE-PAGE-TX
    DUP IF
        _SPA-PERSIST>STATUS R@ _SPAW-ABORT-ACTIVE
        R> DROP EXIT
    THEN DROP
    R@ _SPAW.RECLAIM-WORK RECLAIM-FINALIZE
    DUP IF
        _SPA-PERSIST>STATUS R@ _SPAW-ABORT-ACTIVE
        R> DROP EXIT
    THEN DROP
    R@ _SPAW-WORK>ROOT
    DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
    R@ _SPAW.AUTHORITY-ROOT STREAMS-AUTHORITY-ROOT-SIZE
    R@ _SPAW.APP-ROOT-PAGE @
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-WRITE-PAGE-TX
    DUP IF
        _SPA-PERSIST>STATUS R@ _SPAW-ABORT-ACTIVE
        R> DROP EXIT
    THEN DROP
    R@ _SPAW.APP-ROOT-PAGE @
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-APPLICATION-ROOT!
    DUP IF
        _SPA-PERSIST>STATUS R@ _SPAW-ABORT-ACTIVE
        R> DROP EXIT
    THEN DROP
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-COMMIT
    _SPA-PERSIST>STATUS R@ _SPAW.TEMP-STATUS !
    R@ _SPAW-COMMIT-DURABLE? IF
        R@ _SPAW.RECLAIM-WORK R@ _SPAW.RECLAIM RECLAIM-ADOPT
        DUP IF
            _SPA-PERSIST>STATUS
            R@ _SPAW.TEMP-STATUS @ STREAMS-PA-S-OK = IF
                R@ _SPAW.TEMP-STATUS !
            ELSE
                DROP
            THEN
            _SPAW-STATE-REOPEN R@ _SPAW.STATE !
        ELSE
            DROP
            _SPAW-STATE-READY R@ _SPAW.STATE !
        THEN
    ELSE
        R@ _SPAW.TEMP-STATUS @ R@ _SPAW-ABORT-ACTIVE DROP
    THEN
    R@ _SPAW.TEMP-STATUS @ R> DROP ;

: _SPAW-INCREMENT-LOGICAL  ( work -- status )
    >R
    R@ _SPAW.AUTHORITY-ROOT SAR.LOGICAL-GENERATION @
        PERSIST-MAX-SIGNED >= IF
        R> DROP STREAMS-PA-S-CAPACITY EXIT
    THEN
    R@ _SPAW.AUTHORITY-ROOT SAR.MUTATION-SEQUENCE @
        PERSIST-MAX-SIGNED >= IF
        R> DROP STREAMS-PA-S-CAPACITY EXIT
    THEN
    1 R@ _SPAW.AUTHORITY-ROOT SAR.LOGICAL-GENERATION +!
    1 R@ _SPAW.AUTHORITY-ROOT SAR.MUTATION-SEQUENCE +!
    R> DROP STREAMS-PA-S-OK ;

: _SPAW-COMMIT-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.STAGING-ACTIVE @ IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW.MUTATION-N @ 0= IF
        STREAMS-PA-S-INVALID R@ _SPAW-ABORT-ACTIVE
        R> DROP EXIT
    THEN
    R@ _SPAW.AUTHORITY-ROOT SAR.AUTHORITY-ID RID-PRESENT? 0= IF
        STREAMS-PA-S-CORRUPT R@ _SPAW-ABORT-ACTIVE
        R> DROP EXIT
    THEN
    R@ _SPAW-INCREMENT-LOGICAL
    DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
    0 R@ _SPAW.PHYSICAL-ONLY-N !
    R@ _SPAW-PUBLISH-RUN
    R> DROP ;

: _SPAW-COMMIT-FINALIZE  ( primary-status work -- final-status )
    >R
    DUP R@ _SPAW.TEMP-STATUS !
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP EXIT
    THEN
    R@ _SPAW-COMMIT-DURABLE? IF
        R@ _SPAW.RECLAIM-WORK R@ _SPAW.RECLAIM RECLAIM-ADOPT
        DUP IF
            _SPA-PERSIST>STATUS
            R@ _SPAW.TEMP-STATUS @ STREAMS-PA-S-OK = IF
                R@ _SPAW.TEMP-STATUS !
            ELSE
                DROP
            THEN
            _SPAW-STATE-REOPEN R@ _SPAW.STATE !
        ELSE
            DROP
            _SPAW-STATE-READY R@ _SPAW.STATE !
        THEN
    ELSE
        R@ _SPAW-ABORT-ACTIVE
    THEN
    DROP R@ _SPAW.TEMP-STATUS @ R> DROP ;

: STREAMS-PA-COMMIT  ( adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R 2DROP R> EXIT THEN DROP
    DUP ['] _SPAW-COMMIT-RUN _SPAW-WORK-CATCH
    OVER _SPAW-COMMIT-FINALIZE
    ROT ROT _SPAW-LEAVE ;

\ Provision is the sole native empty-template initializer.  It publishes
\ generation-zero semantic metadata without pretending that provisioning is
\ a configured-source mutation.
: _SPAW-PROVISION-RUN  ( work -- status )
    >R
    R@ _SPAW-READY? 0= IF R> DROP STREAMS-PA-S-BUSY EXIT THEN
    R@ _SPAW.ARG-A @ RID-SIZE R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ RID-PRESENT? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.APP-ROOT-PAGE @ 0>= IF
        R@ _SPAW.ARG-A @
        R@ _SPAW.AUTHORITY-ROOT SAR.AUTHORITY-ID RID=
        IF STREAMS-PA-S-OK ELSE STREAMS-PA-S-CONFLICT THEN
        R> DROP EXIT
    THEN
    R@ _SPAW-BEGIN-RUN DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW.ARG-A @ R@ _SPAW.AUTHORITY-ROOT
        STREAMS-AUTHORITY-ROOT-TEMPLATE-INIT
        _SPA-ROOT>STATUS
    DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
    -1 R@ _SPAW.AUTHORITY-PRESENT !
    1 R@ _SPAW.MUTATION-N !
    1 R@ _SPAW.PHYSICAL-ONLY-N !
    R@ _SPAW-PUBLISH-RUN
    R> DROP ;

: STREAMS-PA-PROVISION  ( authority-id adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R _SPA-DROP3 R> EXIT THEN DROP
    >R
    OVER R@ _SPAW.ARG-A !
    R@ ['] _SPAW-PROVISION-RUN _SPAW-WORK-CATCH
    R@ _SPAW-COMMIT-FINALIZE
    SWAP R@ _SPAW-LEAVE
    >R DROP R> R> DROP ;

\ ---------------------------------------------------------------------
\ Hidden staging roots for whole-batch logical publication
\ ---------------------------------------------------------------------

\ Staged COW paths retain the pages they replace because visible roots remain
\ authoritative until final publication.  Crashed shadow paths are ordinary
\ unreachable compaction input, never entries in the live reclaim ledger.
: _SPAW-PUT-STAGED-RAW
  ( key-a key-u value-a value-u tree-index work -- status )
    >R
    R@ _SPAW.STAGING-ACTIVE @ 0= IF
        _SPA-DROP5 R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    DUP 0< OVER _SPA-TREE-COUNT >= OR IF
        DROP _SPA-DROP4 R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    DUP R@ _SPAW.PAGE-ID ! DROP
    R@ _SPAW.PAGE-ID @ R@ _SPAW-STAGING-ROOT
    R@ _SPAW.TEMP-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
    R@ _SPAW.BTREE-WORK PBTREE-PUT
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.BTREE-WORK PBTREE-RETIRED-PAGES$ 2DROP
    R@ _SPAW.TEMP-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-STAGING-ROOT PBTREE-ROOT-COPY
    _SPA-PERSIST>STATUS
    R> DROP ;

: _SPAW-DELETE-STAGED-RAW
  ( key-a key-u tree-index work -- status )
    >R
    R@ _SPAW.STAGING-ACTIVE @ 0= IF
        _SPA-DROP3 R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    DUP 0< OVER _SPA-TREE-COUNT >= OR IF
        _SPA-DROP3 R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    DUP R@ _SPAW.PAGE-ID ! DROP
    R@ _SPAW.PAGE-ID @ R@ _SPAW-STAGING-ROOT
    R@ _SPAW.TEMP-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-TREE
    R@ _SPAW.BTREE-WORK PBTREE-DELETE
    DUP PERSIST-S-NOT-FOUND = IF
        DROP R> DROP STREAMS-PA-S-NOT-FOUND EXIT
    THEN
    DUP IF _SPA-PERSIST>STATUS R> DROP EXIT THEN DROP
    R@ _SPAW.BTREE-WORK PBTREE-RETIRED-PAGES$ 2DROP
    R@ _SPAW.TEMP-ROOT
    R@ _SPAW.PAGE-ID @ R@ _SPAW-STAGING-ROOT PBTREE-ROOT-COPY
    _SPA-PERSIST>STATUS
    R> DROP ;

RECLAIM-RETIRED-MAX RECLAIM-MAX-BATCH 1- +
    RECLAIM-MAX-BATCH /
RECLAIM-DISCARD-MAX RECLAIM-MAX-BATCH 1- +
    RECLAIM-MAX-BATCH / +
    CONSTANT _SPAW-RECLAIM-FINALIZER-PAGE-MAX
2 CONSTANT _SPAW-RECLAIM-STEP-RETIRE-PAGE-MAX

: _SPAW-STAGING-MUTATION-PAGES  ( work -- count )
    0
    _SPA-TREE-COUNT 0 ?DO
        I 2 PICK _SPAW-STAGING-ROOT PBTREE-ROOT-HEIGHT@ MAX
    LOOP
    2 * 1+ NIP ;

: _SPAW-STAGE-NEXT-ROOM?  ( work -- flag )
    >R
    R@ _SPAW-STAGING-MUTATION-PAGES 1+
    _SPAW-RECLAIM-STEP-RETIRE-PAGE-MAX
    1+ _SPAW-RECLAIM-FINALIZER-PAGE-MAX +
    0 R@ _SPAW.RECLAIM-WORK RECLAIM-TX-ROOM?
    R> DROP ;

: _SPAW-STAGE-BEGIN-RUN  ( work -- status )
    >R
    R@ _SPAW.STAGING-ACTIVE @ 0= IF
        R@ _SPAW-ROOTS>STAGING
        DUP IF R> DROP EXIT THEN DROP
    THEN
    R@ _SPAW-BEGIN-RUN
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW-STAGE-NEXT-ROOM? 0= IF
        STREAMS-PA-S-CAPACITY R@ _SPAW-ABORT-ACTIVE
        R> DROP EXIT
    THEN
    R> DROP STREAMS-PA-S-OK ;

: STREAMS-PA-STAGE-BEGIN  ( adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R 2DROP R> EXIT THEN DROP
    DUP ['] _SPAW-STAGE-BEGIN-RUN _SPAW-WORK-CATCH
    OVER _SPAW-FAIL-ACTIVE
    ROT ROT _SPAW-LEAVE ;

\ Begin the one cold-import authority transaction from a neutral PSTORE whose
\ application-root is still absent.  The supplied RID initializes provisional
\ semantic metadata, but only FIRST-STAGE-COMMIT can make that metadata
\ authoritative.
: _SPAW-FIRST-STAGE-BEGIN-RUN  ( work -- status )
    >R
    R@ _SPAW-READY? 0= IF R> DROP STREAMS-PA-S-BUSY EXIT THEN
    R@ _SPAW.APP-ROOT-PAGE @ 0>=
    R@ _SPAW.AUTHORITY-PRESENT @ 0<> OR
    R@ _SPAW.STAGING-ACTIVE @ 0<> OR IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW.ARG-A @ RID-SIZE R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ RID-PRESENT? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW-ROOTS>STAGING
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW-BEGIN-RUN
    DUP IF
        0 R@ _SPAW.STAGING-ACTIVE !
        R> DROP EXIT
    THEN DROP
    R@ _SPAW.ARG-A @ R@ _SPAW.AUTHORITY-ROOT
        STREAMS-AUTHORITY-ROOT-TEMPLATE-INIT
        _SPA-ROOT>STATUS
    DUP IF
        R@ _SPAW-ABORT-ACTIVE
        0 R@ _SPAW.STAGING-ACTIVE !
        R> DROP EXIT
    THEN DROP
    -1 R@ _SPAW.AUTHORITY-PRESENT !
    1 R@ _SPAW.MUTATION-N !
    R> DROP STREAMS-PA-S-OK ;

: STREAMS-PA-FIRST-STAGE-BEGIN  ( authority-id adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R _SPA-DROP3 R> EXIT THEN DROP
    >R
    OVER R@ _SPAW.ARG-A !
    R@ ['] _SPAW-FIRST-STAGE-BEGIN-RUN _SPAW-WORK-CATCH
    R@ _SPAW-FAIL-ACTIVE
    DUP IF 0 R@ _SPAW.STAGING-ACTIVE ! THEN
    SWAP R@ _SPAW-LEAVE
    >R DROP R> R> DROP ;

\ Commit physical staging progress while the neutral PSTORE application-root
\ remains absent.  Hidden roots live only in caller-owned work until the final
\ first-stage commit; a crash here therefore cannot manufacture Streams
\ authority.  The committed extents are replaceable unreachable staging
\ evidence if the process does not continue to the final flip.
: _SPAW-PUBLISH-ABSENT-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.OLD-ROOT-PAGE @ 0>= IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW.RECLAIM-WORK RECLAIM-FINALIZE
    DUP IF
        _SPA-PERSIST>STATUS R@ _SPAW-ABORT-ACTIVE
        R> DROP EXIT
    THEN DROP
    R@ _SPAW.ADAPTER @ _SPA-D.STORE @
    R@ _SPAW.PSTORE-WORK @ PSTORE-COMMIT
    _SPA-PERSIST>STATUS R@ _SPAW.TEMP-STATUS !
    R@ _SPAW-COMMIT-DURABLE? IF
        R@ _SPAW.RECLAIM-WORK R@ _SPAW.RECLAIM RECLAIM-ADOPT
        DUP IF
            _SPA-PERSIST>STATUS
            R@ _SPAW.TEMP-STATUS @ STREAMS-PA-S-OK = IF
                R@ _SPAW.TEMP-STATUS !
            ELSE
                DROP
            THEN
            _SPAW-STATE-REOPEN R@ _SPAW.STATE !
        ELSE
            DROP
            _SPAW-STATE-READY R@ _SPAW.STATE !
        THEN
    ELSE
        R@ _SPAW.TEMP-STATUS @ R@ _SPAW-ABORT-ACTIVE DROP
    THEN
    R@ _SPAW.TEMP-STATUS @ R> DROP ;

: _SPAW-STAGE-PUBLISH  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW-STAGING-ROOTS-ADVANCE
    DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
    R@ _SPAW.OLD-ROOT-PAGE @ 0< IF
        R@ _SPAW-ROOTS-ADVANCE
        DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
        1 R@ _SPAW.PHYSICAL-ONLY-N !
        R@ _SPAW-PUBLISH-ABSENT-RUN
        R> DROP EXIT
    THEN
    1 R@ _SPAW.PHYSICAL-ONLY-N !
    R@ _SPAW-PUBLISH-RUN
    R> DROP ;

: _SPAW-STAGE-ENSURE-NEXT  ( work -- status )
    >R
    R@ _SPAW-STAGE-NEXT-ROOM? IF
        R> DROP STREAMS-PA-S-OK EXIT
    THEN
    \ Publish only rebased visible roots and physical reclaim progress.
    \ Candidate semantic counters must not be edited until all staged index
    \ operations are complete and the caller is ready for STAGE-COMMIT.
    R@ _SPAW-STAGE-PUBLISH
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW-STAGE-BEGIN-RUN
    R> DROP ;

: _SPAW-PUT-STAGED  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        _SPAW-MUTABLE-KEY? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.VALUE-A @ PERSIST-REF-SIZE
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.VALUE-A @ PERSIST-REF-VALID? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW-REF-AGREES?
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW-STAGE-NEXT-ROOM? 0= IF
        R> DROP STREAMS-PA-S-CAPACITY EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @ _SPAW-KEY-INDEX
    DUP R@ _SPAW.PAGE-ID ! DROP
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
    R@ _SPAW.VALUE-A @ PERSIST-REF-SIZE
    R@ _SPAW.PAGE-ID @ R@ _SPAW-PUT-STAGED-RAW
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW-MARK-MUTATED-RUN
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW-STAGE-ENSURE-NEXT
    R> DROP ;

: STREAMS-PA-STAGED-PUT
  ( key-a key-u record-ref adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R _SPA-DROP5 R> EXIT THEN DROP
    >R
    3 PICK R@ _SPAW.ARG-A !
    2 PICK R@ _SPAW.ARG-U !
    1 PICK R@ _SPAW.VALUE-A !
    R@ ['] _SPAW-PUT-STAGED _SPAW-WORK-CATCH
    R@ _SPAW-FAIL-ACTIVE
    SWAP R@ _SPAW-LEAVE
    >R _SPA-DROP3 R> R> DROP ;

: _SPAW-DELETE-STAGED  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        R@ _SPAW-SPAN-SAFE? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
        _SPAW-MUTABLE-KEY? 0= IF
        R> DROP STREAMS-PA-S-INVALID EXIT
    THEN
    R@ _SPAW-STAGE-NEXT-ROOM? 0= IF
        R> DROP STREAMS-PA-S-CAPACITY EXIT
    THEN
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @ _SPAW-KEY-INDEX
    DUP R@ _SPAW.PAGE-ID ! DROP
    R@ _SPAW.ARG-A @ R@ _SPAW.ARG-U @
    R@ _SPAW.PAGE-ID @ R@ _SPAW-DELETE-STAGED-RAW
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW-MARK-MUTATED-RUN
    DUP IF R> DROP EXIT THEN DROP
    R@ _SPAW-STAGE-ENSURE-NEXT
    R> DROP ;

: STREAMS-PA-STAGED-DELETE  ( key-a key-u adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R _SPA-DROP4 R> EXIT THEN DROP
    >R
    2 PICK R@ _SPAW.ARG-A !
    1 PICK R@ _SPAW.ARG-U !
    R@ ['] _SPAW-DELETE-STAGED _SPAW-WORK-CATCH
    R@ _SPAW-FAIL-ACTIVE
    SWAP R@ _SPAW-LEAVE
    >R 2DROP R> R> DROP ;

: _SPAW-STAGE-COMMIT-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.STAGING-ACTIVE @ 0= IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW-STAGING-ROOTS-ADVANCE
    DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
    R@ _SPAW-STAGING>ROOTS
    DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
    R@ _SPAW-INCREMENT-LOGICAL
    DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
    1 R@ _SPAW.MUTATION-N !
    0 R@ _SPAW.PHYSICAL-ONLY-N !
    R@ _SPAW-PUBLISH-RUN
    0 R@ _SPAW.STAGING-ACTIVE !
    R> DROP ;

: STREAMS-PA-STAGE-COMMIT  ( adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R 2DROP R> EXIT THEN DROP
    DUP ['] _SPAW-STAGE-COMMIT-RUN _SPAW-WORK-CATCH
    OVER _SPAW-COMMIT-FINALIZE
    OVER _SPAW.STAGING-ACTIVE 0 SWAP !
    ROT ROT _SPAW-LEAVE ;

\ Atomically publish the first checked Streams application-root after cold
\ import and exact staged readback.  Unlike an ordinary logical mutation,
\ migration begins at semantic generation zero; the physical PSTORE
\ generation still advances normally at the authority flip.
: _SPAW-FIRST-STAGE-COMMIT-RUN  ( work -- status )
    >R
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <> IF
        R> DROP STREAMS-PA-S-BUSY EXIT
    THEN
    R@ _SPAW.STAGING-ACTIVE @ 0= IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW.OLD-ROOT-PAGE @ 0>= IF
        R> DROP STREAMS-PA-S-CONFLICT EXIT
    THEN
    R@ _SPAW.AUTHORITY-PRESENT @ 0= IF
        R> DROP STREAMS-PA-S-CORRUPT EXIT
    THEN
    R@ _SPAW-STAGING-ROOTS-ADVANCE
    DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
    R@ _SPAW-STAGING>ROOTS
    DUP IF R@ _SPAW-ABORT-ACTIVE R> DROP EXIT THEN DROP
    1 R@ _SPAW.MUTATION-N !
    1 R@ _SPAW.PHYSICAL-ONLY-N !
    R@ _SPAW-PUBLISH-RUN
    0 R@ _SPAW.STAGING-ACTIVE !
    R> DROP ;

: STREAMS-PA-FIRST-STAGE-COMMIT  ( adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R 2DROP R> EXIT THEN DROP
    DUP ['] _SPAW-FIRST-STAGE-COMMIT-RUN _SPAW-WORK-CATCH
    OVER _SPAW-COMMIT-FINALIZE
    OVER _SPAW.STAGING-ACTIVE 0 SWAP !
    ROT ROT _SPAW-LEAVE ;

: STREAMS-PA-STAGED-TREE-CARDINALITY@  ( tree-index work -- count|-1 )
    >R
    R@ STREAMS-PA-WORK-VALID? 0= IF DROP R> DROP -1 EXIT THEN
    DUP 0< OVER _SPA-TREE-COUNT >= OR IF
        DROP R> DROP -1 EXIT
    THEN
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE <>
    R@ _SPAW.STAGING-ACTIVE @ 0= OR IF
        DROP R> DROP -1 EXIT
    THEN
    R> _SPAW-STAGING-ROOT PBTREE-ROOT-CARDINALITY@ ;

: _SPAW-STAGE-DISCARD-RUN  ( work -- status )
    >R
    STREAMS-PA-S-OK R@ _SPAW.TEMP-STATUS !
    R@ _SPAW.STATE @ _SPAW-STATE-ACTIVE = IF
        STREAMS-PA-S-OK R@ _SPAW-ABORT-ACTIVE
        R@ _SPAW.TEMP-STATUS !
    THEN
    0 R@ _SPAW.STAGING-ACTIVE !
    R@ _SPAW.STATE @ _SPAW-STATE-READY <> IF
        R@ _SPAW-OPEN-RUN
        DUP STREAMS-PA-S-OK =
        OVER STREAMS-PA-S-ABSENT = OR IF
            DROP
        ELSE
            R@ _SPAW.TEMP-STATUS !
        THEN
    THEN
    R@ _SPAW.TEMP-STATUS @ R> DROP ;

: STREAMS-PA-STAGE-DISCARD  ( adapter work -- status )
    2DUP _SPAW-ENTER DUP IF >R 2DROP R> EXIT THEN DROP
    DUP ['] _SPAW-STAGE-DISCARD-RUN _SPAW-WORK-CATCH
    ROT ROT _SPAW-LEAVE ;

: STREAMS-PA-FIRST-STAGE-DISCARD  ( adapter work -- status )
    STREAMS-PA-STAGE-DISCARD ;
