\ =====================================================================
\ rabbit-remote.f - typed remote snapshot ownership for Streams
\ =====================================================================
\ One caller-owned resource binds to one persistent Streams Rabbit
\ connector and one immutable output schema.  The caller supplies the exact
\ selector and transaction arenas; this module fixes no product capacity.
\
\ FETCH accepts a caller-owned sealed Rabbit builder.  The builder remains a
\ profile concern, while this owner verifies the exact FETCH selector,
\ nonzero Lane, copied Txn, Akashic JSON View, and Accept-View before asking
\ the connector to publish it.  Only one operation is in flight per owner.
\
\ During connector POLL the public callback retains no frame pointer.  It
\ records scalar response evidence and always commits an exactly correlated
\ terminal response, including a response rejected by this application
\ profile.  Decoding and optional validation happen later from the neutral
\ client's durable result slot, after POLL has returned.
\
\ CONSUME reports whether a poll item belonged to this owner.  A false owned
\ flag means the caller still owns and must route the original item, subject,
\ and generation.  This makes the first dedicated-connector slice compatible
\ with a later Streams operation/subscription mux instead of swallowing its
\ traffic.
\
\ A successful refresh decodes into staging, validates it, releases the exact
\ generation- and attachment-fenced operation, and only then replaces the
\ cache root.  FETCH records the cache generation from which it started, so a
\ subscription event published while that response is pending makes the older
\ snapshot stale instead of allowing it to overwrite newer application state.
\
\ Registered neutral subscription callbacks decode once into resource-owned
\ staging through CACHE-STAGE-JSON-CALLBACK.  This is the connector's matching
\ entry-callback path, not this resource's already-busy response fallback.
\ Only the returned scalar stage generation crosses the callback boundary.
\ Post-poll publication moves that exact graph without decoding or invoking
\ the application validator again; publication and discard failures retain the
\ fenced stage for explicit retry.
\ Failed refreshes and staged publications preserve the old cache and its
\ generation.
\ CACHE@ returns a borrowed CV pointer valid until the next successful
\ publication or FINI.  CACHE-CALLBACK@ is the structural read-only form used
\ while the shared connector is synchronously dispatching a callback and its
\ ordinary complete-graph validation is therefore intentionally busy.
\ Configured validators receive borrowed read-only value and owner pointers;
\ they must not mutate or retain either graph and may only use callback-safe
\ accessors while the owner is busy.
\ The connector and schema must outlive this owner.
\ =====================================================================

PROVIDED akashic-streams-rres

REQUIRE rabbit-connector.f
REQUIRE ../../../interop/codecs/json-value.f

\ =====================================================================
\ Closed status, detail, state, and profile domains
\ =====================================================================

0  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-OK
1  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID
2  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE
3  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY
4  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS
5  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-CONNECTOR
6  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-BUILDER
7  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-MESSAGE
8  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-RESPONSE
9  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-CODEC
10 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-PROFILE
11 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-CAPACITY
12 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-PENDING
13 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-DISCONNECTED
14 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP
15 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-CALLBACK
16 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-S-EMPTY

0 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE
1 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CONNECTOR
2 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-BUILDER
3 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-MESSAGE
4 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CODEC
5 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-SCHEMA
6 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-RESPONSE
7 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-VALIDATOR
8 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CALLBACK
9 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY

1  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-E-LABEL
2  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-E-VIEW-MISSING
3  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-E-VIEW-MISMATCH
4  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-E-BODY
5  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-E-CALLBACK-MISSING
6  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-E-RESULT-MISMATCH
7  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-E-OPERATION-MISMATCH
8  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-E-GENERATION
9  CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-E-PUBLISH
10 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-E-VALIDATOR-STACK
11 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-E-FALLBACK-STACK

1 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE
2 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-ST-FETCHING
3 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-ST-CLEANUP

: STREAMS-RABBIT-REMOTE-RESOURCE-STATUS-VALID?  ( status -- flag )
    DUP STREAMS-RABBIT-REMOTE-RESOURCE-S-OK >=
    SWAP STREAMS-RABBIT-REMOTE-RESOURCE-S-EMPTY <= AND ;

: STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-VALID?  ( detail -- flag )
    DUP STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE >=
    SWAP STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY <= AND ;

: STREAMS-RABBIT-REMOTE-RESOURCE-STATE-VALID?  ( state -- flag )
    DUP STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE =
    OVER STREAMS-RABBIT-REMOTE-RESOURCE-ST-FETCHING = OR
    SWAP STREAMS-RABBIT-REMOTE-RESOURCE-ST-CLEANUP = OR ;

\ =====================================================================
\ Caller-owned resource descriptor
\ =====================================================================

0x5352525245533031 CONSTANT _SRRES-MAGIC-VALUE  \ "SRRRES01"
2                  CONSTANT _SRRES-ABI-VERSION

  0 CONSTANT _SRRES-MAGIC
  8 CONSTANT _SRRES-ABI
 16 CONSTANT _SRRES-BYTES
 24 CONSTANT _SRRES-STATE
 32 CONSTANT _SRRES-LAST-STATUS
 40 CONSTANT _SRRES-DETAIL-DOMAIN
 48 CONSTANT _SRRES-DETAIL
 56 CONSTANT _SRRES-CONNECTOR
 64 CONSTANT _SRRES-SCHEMA
 72 CONSTANT _SRRES-VALIDATOR-XT
 80 CONSTANT _SRRES-VALIDATOR-CONTEXT
 88 CONSTANT _SRRES-FALLBACK-XT
 96 CONSTANT _SRRES-FALLBACK-CONTEXT
104 CONSTANT _SRRES-SELECTOR-A
112 CONSTANT _SRRES-SELECTOR-CAP
120 CONSTANT _SRRES-SELECTOR-U
128 CONSTANT _SRRES-TXN-A
136 CONSTANT _SRRES-TXN-CAP
144 CONSTANT _SRRES-TXN-U
152 CONSTANT _SRRES-LANE
160 CONSTANT _SRRES-OPERATION
168 CONSTANT _SRRES-OPERATION-GENERATION
176 CONSTANT _SRRES-ATTACHMENT-GENERATION
184 CONSTANT _SRRES-CALLBACK-SEEN
192 CONSTANT _SRRES-RESPONSE-CODE
200 CONSTANT _SRRES-RESPONSE-BYTES
208 CONSTANT _SRRES-ATTEMPT-STATUS
216 CONSTANT _SRRES-ATTEMPT-DOMAIN
224 CONSTANT _SRRES-ATTEMPT-DETAIL
232 CONSTANT _SRRES-CANDIDATE-READY
240 CONSTANT _SRRES-CACHE-GENERATION
248 CONSTANT _SRRES-CACHE-PRESENT
256 CONSTANT _SRRES-BUSY
264 CONSTANT _SRRES-FETCH-CACHE-GENERATION
272 CONSTANT _SRRES-EVENT-STAGE-STATE
280 CONSTANT _SRRES-EVENT-STAGE-GENERATION
288 CONSTANT _SRRES-EVENT-STAGE-EXPECTED-GENERATION
296 CONSTANT _SRRES-CACHE
336 CONSTANT _SRRES-STAGING
376 CONSTANT STREAMS-RABBIT-REMOTE-RESOURCE-SIZE

: SRRES.MAGIC             ( owner -- field ) _SRRES-MAGIC + ;
: SRRES.ABI               ( owner -- field ) _SRRES-ABI + ;
: SRRES.BYTES             ( owner -- field ) _SRRES-BYTES + ;
: SRRES.STATE             ( owner -- field ) _SRRES-STATE + ;
: SRRES.LAST-STATUS       ( owner -- field ) _SRRES-LAST-STATUS + ;
: SRRES.DETAIL-DOMAIN     ( owner -- field ) _SRRES-DETAIL-DOMAIN + ;
: SRRES.DETAIL            ( owner -- field ) _SRRES-DETAIL + ;
: SRRES.CONNECTOR         ( owner -- field ) _SRRES-CONNECTOR + ;
: SRRES.SCHEMA            ( owner -- field ) _SRRES-SCHEMA + ;
: SRRES.VALIDATOR-XT      ( owner -- field ) _SRRES-VALIDATOR-XT + ;
: SRRES.VALIDATOR-CONTEXT ( owner -- field ) _SRRES-VALIDATOR-CONTEXT + ;
: SRRES.FALLBACK-XT       ( owner -- field ) _SRRES-FALLBACK-XT + ;
: SRRES.FALLBACK-CONTEXT  ( owner -- field ) _SRRES-FALLBACK-CONTEXT + ;
: SRRES.SELECTOR-A        ( owner -- field ) _SRRES-SELECTOR-A + ;
: SRRES.SELECTOR-CAP      ( owner -- field ) _SRRES-SELECTOR-CAP + ;
: SRRES.SELECTOR-U        ( owner -- field ) _SRRES-SELECTOR-U + ;
: SRRES.TXN-A             ( owner -- field ) _SRRES-TXN-A + ;
: SRRES.TXN-CAP           ( owner -- field ) _SRRES-TXN-CAP + ;
: SRRES.TXN-U             ( owner -- field ) _SRRES-TXN-U + ;
: SRRES.LANE              ( owner -- field ) _SRRES-LANE + ;
: SRRES.OPERATION         ( owner -- field ) _SRRES-OPERATION + ;
: SRRES.OPERATION-GENERATION
  ( owner -- field ) _SRRES-OPERATION-GENERATION + ;
: SRRES.ATTACHMENT-GENERATION
  ( owner -- field ) _SRRES-ATTACHMENT-GENERATION + ;
: SRRES.CALLBACK-SEEN     ( owner -- field ) _SRRES-CALLBACK-SEEN + ;
: SRRES.RESPONSE-CODE     ( owner -- field ) _SRRES-RESPONSE-CODE + ;
: SRRES.RESPONSE-BYTES    ( owner -- field ) _SRRES-RESPONSE-BYTES + ;
: SRRES.ATTEMPT-STATUS    ( owner -- field ) _SRRES-ATTEMPT-STATUS + ;
: SRRES.ATTEMPT-DOMAIN    ( owner -- field ) _SRRES-ATTEMPT-DOMAIN + ;
: SRRES.ATTEMPT-DETAIL    ( owner -- field ) _SRRES-ATTEMPT-DETAIL + ;
: SRRES.CANDIDATE-READY   ( owner -- field ) _SRRES-CANDIDATE-READY + ;
: SRRES.CACHE-GENERATION  ( owner -- field ) _SRRES-CACHE-GENERATION + ;
: SRRES.CACHE-PRESENT     ( owner -- field ) _SRRES-CACHE-PRESENT + ;
: SRRES.BUSY              ( owner -- field ) _SRRES-BUSY + ;
: SRRES.FETCH-CACHE-GENERATION
  ( owner -- field ) _SRRES-FETCH-CACHE-GENERATION + ;
: SRRES.EVENT-STAGE-STATE
  ( owner -- field ) _SRRES-EVENT-STAGE-STATE + ;
: SRRES.EVENT-STAGE-GENERATION
  ( owner -- field ) _SRRES-EVENT-STAGE-GENERATION + ;
: SRRES.EVENT-STAGE-EXPECTED-GENERATION
  ( owner -- field ) _SRRES-EVENT-STAGE-EXPECTED-GENERATION + ;
: SRRES.CACHE             ( owner -- value ) _SRRES-CACHE + ;
: SRRES.STAGING           ( owner -- value ) _SRRES-STAGING + ;

GUARD _srres-guard

: _SRRES-BOOLEAN?  ( flag -- valid? )
    DUP 0= SWAP -1 = OR ;

0 CONSTANT _SRRES-EVENT-STAGE-EMPTY
1 CONSTANT _SRRES-EVENT-STAGE-READY
2 CONSTANT _SRRES-EVENT-STAGE-DISCARD

: _SRRES-EVENT-STAGE-STATE-VALID?  ( state -- flag )
    DUP _SRRES-EVENT-STAGE-EMPTY =
    OVER _SRRES-EVENT-STAGE-READY = OR
    SWAP _SRRES-EVENT-STAGE-DISCARD = OR ;

: _SRRES-HEADER?  ( owner -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP SRRES.MAGIC @ _SRRES-MAGIC-VALUE =
    OVER SRRES.ABI @ _SRRES-ABI-VERSION = AND
    SWAP SRRES.BYTES @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE = AND ;

VARIABLE _SRRESV-O

: _SRRES-IDLE-SHAPE?  ( owner -- flag )
    DUP SRRES.TXN-U @ 0=
    OVER SRRES.LANE @ 0= AND
    OVER SRRES.OPERATION @ 0= AND
    OVER SRRES.OPERATION-GENERATION @ 0= AND
    OVER SRRES.ATTACHMENT-GENERATION @ 0= AND
    OVER SRRES.CALLBACK-SEEN @ 0= AND
    OVER SRRES.CANDIDATE-READY @ 0= AND
    SWAP SRRES.FETCH-CACHE-GENERATION @ 0= AND ;

: _SRRES-LIVE-SHAPE?  ( owner -- flag )
    DUP SRRES.TXN-U @ 0>
    OVER SRRES.LANE @ 0<> AND
    OVER SRRES.OPERATION @ 0<> AND
    OVER SRRES.OPERATION-GENERATION @ 0<> AND
    SWAP SRRES.ATTACHMENT-GENERATION @ 0<> AND ;

: _SRRES-CLEANUP-SHAPE?  ( owner -- flag )
    DUP SRRES.OPERATION @ IF _SRRES-LIVE-SHAPE? EXIT THEN
    DUP SRRES.TXN-U @ 0=
    OVER SRRES.LANE @ 0= AND
    OVER SRRES.OPERATION-GENERATION @ 0= AND
    SWAP SRRES.ATTACHMENT-GENERATION @ 0= AND ;

: _SRRES-EVENT-STAGE-SHAPE?  ( owner -- flag )
    DUP SRRES.EVENT-STAGE-STATE @ CASE
        _SRRES-EVENT-STAGE-EMPTY OF
            SRRES.EVENT-STAGE-EXPECTED-GENERATION @ 0=
        ENDOF
        _SRRES-EVENT-STAGE-READY OF
            DUP SRRES.EVENT-STAGE-GENERATION @ 0<>
            OVER SRRES.EVENT-STAGE-EXPECTED-GENERATION @
            2 PICK SRRES.CACHE-GENERATION @ U> 0= AND
            SWAP SRRES.CANDIDATE-READY @ 0= AND
        ENDOF
        _SRRES-EVENT-STAGE-DISCARD OF
            DUP SRRES.EVENT-STAGE-GENERATION @ 0<>
            OVER SRRES.EVENT-STAGE-EXPECTED-GENERATION @
            2 PICK SRRES.CACHE-GENERATION @ U> 0= AND
            SWAP SRRES.CANDIDATE-READY @ 0= AND
        ENDOF
        NIP 0 SWAP
    ENDCASE ;

: _SRRES-STRUCTURAL?  ( owner -- flag )
    _SRRESV-O !
    _SRRESV-O @ _SRRES-HEADER? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.STATE @
        STREAMS-RABBIT-REMOTE-RESOURCE-STATE-VALID? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.LAST-STATUS @
        STREAMS-RABBIT-REMOTE-RESOURCE-STATUS-VALID? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.DETAIL-DOMAIN @
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-VALID? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.ATTEMPT-STATUS @
        STREAMS-RABBIT-REMOTE-RESOURCE-STATUS-VALID? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.ATTEMPT-DOMAIN @
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-VALID? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.CONNECTOR @ 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.SCHEMA @ 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.SELECTOR-CAP @ 0< IF 0 EXIT THEN
    _SRRESV-O @ SRRES.SELECTOR-U @ 0> 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.SELECTOR-U @
    _SRRESV-O @ SRRES.SELECTOR-CAP @ U> IF 0 EXIT THEN
    _SRRESV-O @ SRRES.SELECTOR-A @
    _SRRESV-O @ SRRES.SELECTOR-CAP @ MSPAN-NONWRAPPING? 0= IF
        0 EXIT
    THEN
    _SRRESV-O @ SRRES.TXN-CAP @ 0> 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.TXN-U @ 0< IF 0 EXIT THEN
    _SRRESV-O @ SRRES.TXN-U @
    _SRRESV-O @ SRRES.TXN-CAP @ U> IF 0 EXIT THEN
    _SRRESV-O @ SRRES.TXN-A @ _SRRESV-O @ SRRES.TXN-CAP @
        MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.CALLBACK-SEEN @ _SRRES-BOOLEAN? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.CANDIDATE-READY @ _SRRES-BOOLEAN? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.CACHE-PRESENT @ _SRRES-BOOLEAN? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.BUSY @ _SRRES-BOOLEAN? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.EVENT-STAGE-STATE @
        _SRRES-EVENT-STAGE-STATE-VALID? 0= IF 0 EXIT THEN
    _SRRESV-O @ _SRRES-EVENT-STAGE-SHAPE? 0= IF 0 EXIT THEN
    _SRRESV-O @ SRRES.RESPONSE-BYTES @ 0< IF 0 EXIT THEN
    _SRRESV-O @ SRRES.RESPONSE-CODE @ ?DUP IF
        DUP 100 < SWAP 599 > OR IF 0 EXIT THEN
    THEN
    _SRRESV-O @ SRRES.CACHE-PRESENT @ IF
        _SRRESV-O @ SRRES.CACHE-GENERATION @ 0= IF 0 EXIT THEN
    ELSE
        _SRRESV-O @ SRRES.CACHE-GENERATION @ IF 0 EXIT THEN
    THEN
    _SRRESV-O @ SRRES.FETCH-CACHE-GENERATION @
    _SRRESV-O @ SRRES.CACHE-GENERATION @ U> IF 0 EXIT THEN
    _SRRESV-O @ SRRES.STATE @ CASE
        STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE OF
            _SRRESV-O @ _SRRES-IDLE-SHAPE?
        ENDOF
        STREAMS-RABBIT-REMOTE-RESOURCE-ST-FETCHING OF
            _SRRESV-O @ _SRRES-LIVE-SHAPE?
            _SRRESV-O @ SRRES.CANDIDATE-READY @ 0= AND
        ENDOF
        STREAMS-RABBIT-REMOTE-RESOURCE-ST-CLEANUP OF
            _SRRESV-O @ _SRRES-CLEANUP-SHAPE?
            _SRRESV-O @ SRRES.EVENT-STAGE-STATE @
                _SRRES-EVENT-STAGE-EMPTY = AND
        ENDOF
        0 SWAP
    ENDCASE ;

\ =====================================================================
\ Complete schema graph comparison with a borrowed owner graph
\ =====================================================================

CREATE _SRRESSG-S CS-MAX-DEPTH 8 * ALLOT
VARIABLE _SRRESSG-DEPTH
VARIABLE _SRRESSG-NODES
VARIABLE _SRRESSG-OBJECT

: _SRRESSG-SLOT  ( -- address )
    _SRRESSG-DEPTH @ 8 * _SRRESSG-S + ;

: _SRRESSG-S@  ( -- schema ) _SRRESSG-SLOT @ ;
: _SRRESSG-S!  ( schema -- ) _SRRESSG-SLOT ! ;

: _SRRESSG-SPAN?  ( address bytes -- overlap? )
    _SRRESSG-OBJECT @
    STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? ;

DEFER _SRRESSG-WALK

: _SRRESSG-WALK-R  ( schema -- overlap? )
    1 _SRRESSG-NODES +!
    _SRRESSG-NODES @ CS-MAX-NODES > IF DROP -1 EXIT THEN
    1 _SRRESSG-DEPTH +!
    _SRRESSG-DEPTH @ CS-MAX-DEPTH >= IF
        DROP -1 _SRRESSG-DEPTH +! -1 EXIT
    THEN
    DUP _SRRESSG-S!
    DUP CS-SIZE _SRRESSG-SPAN? IF
        DROP -1 _SRRESSG-DEPTH +! -1 EXIT
    THEN
    DROP
    _SRRESSG-S@ CS.TYPE-MASK @ CV-T-LIST CS-TYPE-BIT AND IF
        _SRRESSG-S@ CS.ITEM @ ?DUP IF
            _SRRESSG-WALK IF -1 _SRRESSG-DEPTH +! -1 EXIT THEN
        THEN
    THEN
    _SRRESSG-S@ CS.TYPE-MASK @ CV-T-MAP CS-TYPE-BIT AND IF
        _SRRESSG-S@ CS.FIELD-N @ DUP IF
            CS-FIELD-SIZE * _SRRESSG-S@ CS.FIELDS @ SWAP
            _SRRESSG-SPAN? IF -1 _SRRESSG-DEPTH +! -1 EXIT THEN
        ELSE
            DROP
        THEN
        _SRRESSG-S@ CS.FIELD-N @ 0 ?DO
            _SRRESSG-S@ CS.FIELDS @ I CS-FIELD-SIZE * + DUP
            CSF.KEY-A @ SWAP CSF.KEY-U @ _SRRESSG-SPAN? IF
                -1 _SRRESSG-DEPTH +! -1 UNLOOP EXIT
            THEN
            _SRRESSG-S@ CS.FIELDS @ I CS-FIELD-SIZE * +
                CSF.SCHEMA @ _SRRESSG-WALK IF
                -1 _SRRESSG-DEPTH +! -1 UNLOOP EXIT
            THEN
        LOOP
    THEN
    -1 _SRRESSG-DEPTH +! 0 ;

' _SRRESSG-WALK-R IS _SRRESSG-WALK

: _SRRES-SCHEMA-GRAPH-OVERLAP?
  ( schema connector -- overlap? )
    _SRRESSG-OBJECT !
    0 _SRRESSG-NODES ! -1 _SRRESSG-DEPTH !
    _SRRESSG-WALK ;

\ =====================================================================
\ Retained graph validation
\ =====================================================================

VARIABLE _SRRESG-O

: _SRRES-RETAINED-GEOMETRY?  ( owner -- flag )
    _SRRESG-O !
    _SRRESG-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
    _SRRESG-O @ SRRES.SELECTOR-A @ _SRRESG-O @ SRRES.SELECTOR-CAP @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRRESG-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
    _SRRESG-O @ SRRES.TXN-A @ _SRRESG-O @ SRRES.TXN-CAP @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRRESG-O @ SRRES.SELECTOR-A @ _SRRESG-O @ SRRES.SELECTOR-CAP @
    _SRRESG-O @ SRRES.TXN-A @ _SRRESG-O @ SRRES.TXN-CAP @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRRESG-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        _SRRESG-O @ SRRES.SCHEMA @
        CS-SCHEMA-GRAPH-SPAN-OVERLAP? IF 0 EXIT THEN
    _SRRESG-O @ SRRES.SELECTOR-A @ _SRRESG-O @ SRRES.SELECTOR-CAP @
        _SRRESG-O @ SRRES.SCHEMA @
        CS-SCHEMA-GRAPH-SPAN-OVERLAP? IF 0 EXIT THEN
    _SRRESG-O @ SRRES.TXN-A @ _SRRESG-O @ SRRES.TXN-CAP @
        _SRRESG-O @ SRRES.SCHEMA @
        CS-SCHEMA-GRAPH-SPAN-OVERLAP? IF 0 EXIT THEN
    _SRRESG-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        _SRRESG-O @ SRRES.CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _SRRESG-O @ SRRES.SELECTOR-A @ _SRRESG-O @ SRRES.SELECTOR-CAP @
        _SRRESG-O @ SRRES.CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _SRRESG-O @ SRRES.TXN-A @ _SRRESG-O @ SRRES.TXN-CAP @
        _SRRESG-O @ SRRES.CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _SRRESG-O @ SRRES.SCHEMA @ _SRRESG-O @ SRRES.CONNECTOR @
        _SRRES-SCHEMA-GRAPH-OVERLAP? 0= ;

: _SRRES-VALID?  ( owner -- flag )
    DUP _SRRES-STRUCTURAL? 0= IF DROP 0 EXIT THEN
    DUP SRRES.BUSY @ IF DROP 0 EXIT THEN
    DUP SRRES.CONNECTOR @ STREAMS-RABBIT-CONNECTOR-VALID? 0= IF
        DROP 0 EXIT
    THEN
    DUP SRRES.SCHEMA @ IVJSON-SCHEMA-COMPATIBLE? 0= IF DROP 0 EXIT THEN
    DUP SRRES.SELECTOR-A @ OVER SRRES.SELECTOR-U @
        UTF8-VALID? 0= IF DROP 0 EXIT THEN
    _SRRES-RETAINED-GEOMETRY? ;

: STREAMS-RABBIT-REMOTE-RESOURCE-VALID?  ( owner -- flag )
    ['] _SRRES-VALID? _srres-guard WITH-GUARD ;

VARIABLE _SRRESOG-A
VARIABLE _SRRESOG-U
VARIABLE _SRRESOG-O

\ Compare a checked span with an already-validated complete resource graph.
\ CACHE and STAGING roots are inline in the descriptor; their complete
\ recursively owned CV allocations are retained spans as well.  Keeping this
\ core separate lets pairwise ownership checks validate each graph only once.
: _SRRES-RETAINED-SPAN-OVERLAP-VALID?
  ( address bytes owner -- flag )
    _SRRESOG-O ! _SRRESOG-U ! _SRRESOG-A !
    _SRRESOG-A @ _SRRESOG-U @
        _SRRESOG-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        MSPAN-OVERLAP? IF -1 EXIT THEN
    _SRRESOG-A @ _SRRESOG-U @
        _SRRESOG-O @ SRRES.SELECTOR-A @ _SRRESOG-O @ SRRES.SELECTOR-CAP @
        MSPAN-OVERLAP? IF -1 EXIT THEN
    _SRRESOG-A @ _SRRESOG-U @
        _SRRESOG-O @ SRRES.TXN-A @ _SRRESOG-O @ SRRES.TXN-CAP @
        MSPAN-OVERLAP? IF -1 EXIT THEN
    _SRRESOG-A @ _SRRESOG-U @ _SRRESOG-O @ SRRES.SCHEMA @
        CS-SCHEMA-GRAPH-SPAN-OVERLAP? IF -1 EXIT THEN
    _SRRESOG-A @ _SRRESOG-U @ _SRRESOG-O @ SRRES.CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? IF -1 EXIT THEN
    _SRRESOG-A @ _SRRESOG-U @ _SRRESOG-O @ SRRES.CACHE
        CV-OWNED-SPAN-OVERLAP? IF -1 EXIT THEN
    _SRRESOG-A @ _SRRESOG-U @ _SRRESOG-O @ SRRES.STAGING
        CV-OWNED-SPAN-OVERLAP? ;

\ Fail-closed geometry for a higher owner which retains this complete resource
\ graph.  Invalid query geometry or an invalid owner reports overlap.
: _SRRES-RETAINED-SPAN-OVERLAP?  ( address bytes owner -- flag )
    _SRRESOG-O ! _SRRESOG-U ! _SRRESOG-A !
    _SRRESOG-U @ 0< IF -1 EXIT THEN
    _SRRESOG-U @ IF _SRRESOG-A @ 0= IF -1 EXIT THEN THEN
    _SRRESOG-A @ _SRRESOG-U @ MSPAN-NONWRAPPING? 0= IF -1 EXIT THEN
    _SRRESOG-O @ _SRRES-VALID? 0= IF -1 EXIT THEN
    _SRRESOG-A @ _SRRESOG-U @ _SRRESOG-O @
        _SRRES-RETAINED-SPAN-OVERLAP-VALID? ;

: STREAMS-RABBIT-REMOTE-RESOURCE-RETAINED-SPAN-OVERLAP?
  ( address bytes owner -- flag )
    ['] _SRRES-RETAINED-SPAN-OVERLAP? _srres-guard WITH-GUARD ;

VARIABLE _SRRESBO-B
VARIABLE _SRRESBO-O
VARIABLE _SRRESBO-A
VARIABLE _SRRESBO-U
VARIABLE _SRRESBO-BS

: _SRRES-BUILDER-OVERLAP-INNER  ( -- flag )
    _SRRESBO-O @ _SRRES-VALID? 0= IF -1 EXIT THEN
    _SRRESBO-B @ RMSGB-VALID? 0= IF -1 EXIT THEN
    RMSGB-OWNED-SPAN-COUNT 0 ?DO
        I _SRRESBO-B @ RMSGB-OWNED-SPAN@
            _SRRESBO-BS ! _SRRESBO-U ! _SRRESBO-A !
        _SRRESBO-BS @ RMSGB-S-OK <> IF -1 UNLOOP EXIT THEN
        _SRRESBO-A @ _SRRESBO-U @ _SRRESBO-O @
            _SRRES-RETAINED-SPAN-OVERLAP-VALID? IF
            -1 UNLOOP EXIT
        THEN
    LOOP
    0 ;

\ Compare both complete builder allocations with every span retained through
\ this resource.  Invalid inputs and any internal geometry failure report
\ overlap conservatively; false is the sole proof of disjoint ownership.
: _SRRES-BUILDER-OVERLAP?  ( builder owner -- flag )
    _SRRESBO-O ! _SRRESBO-B !
    ['] _SRRES-BUILDER-OVERLAP-INNER CATCH ?DUP IF DROP -1 THEN ;

: STREAMS-RABBIT-REMOTE-RESOURCE-BUILDER-OVERLAP?
  ( builder owner -- flag )
    ['] _SRRES-BUILDER-OVERLAP? _srres-guard WITH-GUARD ;

\ =====================================================================
\ Evidence publication
\ =====================================================================

VARIABLE _SRRESS-O
VARIABLE _SRRESS-DOMAIN
VARIABLE _SRRESS-DETAIL

: _SRRES-STATUS!  ( status detail-domain detail owner -- status )
    _SRRESS-O ! _SRRESS-DETAIL ! _SRRESS-DOMAIN !
    DUP _SRRESS-O @ SRRES.LAST-STATUS !
    _SRRESS-DOMAIN @ _SRRESS-O @ SRRES.DETAIL-DOMAIN !
    _SRRESS-DETAIL @ _SRRESS-O @ SRRES.DETAIL ! ;

: _SRRES-ATTEMPT!  ( status detail-domain detail owner -- status )
    _SRRESS-O ! _SRRESS-DETAIL ! _SRRESS-DOMAIN !
    DUP _SRRESS-O @ SRRES.ATTEMPT-STATUS !
    _SRRESS-DOMAIN @ _SRRESS-O @ SRRES.ATTEMPT-DOMAIN !
    _SRRESS-DETAIL @ _SRRESS-O @ SRRES.ATTEMPT-DETAIL ! ;

: _SRRES-CONNECTOR>STATUS  ( connector-status -- owner-status )
    CASE
        STREAMS-RABBIT-CONNECTOR-S-PENDING OF
            STREAMS-RABBIT-REMOTE-RESOURCE-S-PENDING ENDOF
        STREAMS-RABBIT-CONNECTOR-S-DISCONNECTED OF
            STREAMS-RABBIT-REMOTE-RESOURCE-S-DISCONNECTED ENDOF
        STREAMS-RABBIT-CONNECTOR-S-CLEANUP OF
            STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP ENDOF
        STREAMS-RABBIT-CONNECTOR-S-CAPACITY OF
            STREAMS-RABBIT-REMOTE-RESOURCE-S-CAPACITY ENDOF
        STREAMS-RABBIT-CONNECTOR-S-BUSY OF
            STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY ENDOF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CONNECTOR SWAP
    ENDCASE ;

VARIABLE _SRRESCD-CS
VARIABLE _SRRESCD-O
VARIABLE _SRRESCD-DETAIL
VARIABLE _SRRESCD-READ-STATUS

: _SRRES-CONNECTOR-ATTEMPT!  ( connector-status owner -- owner-status )
    _SRRESCD-O ! _SRRESCD-CS !
    _SRRESCD-O @ SRRES.CONNECTOR @ STREAMS-RABBIT-CONNECTOR-DETAIL@
        _SRRESCD-READ-STATUS ! _SRRESCD-DETAIL !
    _SRRESCD-READ-STATUS @ STREAMS-RABBIT-CONNECTOR-S-OK <> IF
        _SRRESCD-CS @ _SRRESCD-DETAIL !
    THEN
    _SRRESCD-CS @ _SRRES-CONNECTOR>STATUS
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CONNECTOR
    _SRRESCD-DETAIL @ _SRRESCD-O @ _SRRES-ATTEMPT! ;

\ =====================================================================
\ Initialization and immutable callback configuration
\ =====================================================================

VARIABLE _SRRESI-CONNECTOR
VARIABLE _SRRESI-SA
VARIABLE _SRRESI-SU
VARIABLE _SRRESI-STORE
VARIABLE _SRRESI-SCAP
VARIABLE _SRRESI-TXN
VARIABLE _SRRESI-TCAP
VARIABLE _SRRESI-SCHEMA
VARIABLE _SRRESI-O
VARIABLE _SRRESI-CS

: _SRRES-INIT  ( connector selector-a selector-u selector-store selector-cap )
  ( txn-store txn-cap schema owner -- status )
    _SRRESI-O ! _SRRESI-SCHEMA ! _SRRESI-TCAP ! _SRRESI-TXN !
    _SRRESI-SCAP ! _SRRESI-STORE ! _SRRESI-SU ! _SRRESI-SA !
    _SRRESI-CONNECTOR !
    _SRRESI-O @ 0= IF STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT THEN
    _SRRESI-O @ 7 AND IF STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT THEN
    _SRRESI-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        MSPAN-NONWRAPPING? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESI-O @ SRRES.MAGIC @ _SRRES-MAGIC-VALUE = IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    _SRRESI-SU @ 0> 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESI-SA @ _SRRESI-SU @ MSPAN-NONWRAPPING? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESI-SA @ _SRRESI-SU @ UTF8-VALID? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESI-SCAP @ 0< IF STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT THEN
    _SRRESI-SU @ _SRRESI-SCAP @ U> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CAPACITY EXIT
    THEN
    _SRRESI-STORE @ _SRRESI-SCAP @ MSPAN-NONWRAPPING? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESI-TCAP @ 0> 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESI-TXN @ _SRRESI-TCAP @ MSPAN-NONWRAPPING? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESI-CONNECTOR @ STREAMS-RABBIT-CONNECTOR-STATE@
        _SRRESI-CS !
    _SRRESI-CS @ STREAMS-RABBIT-CONNECTOR-S-OK <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CONNECTOR EXIT
    THEN
    STREAMS-RABBIT-CONNECTOR-ST-ATTACHED <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-DISCONNECTED EXIT
    THEN
    _SRRESI-SCHEMA @ IVJSON-SCHEMA-COMPATIBLE? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-PROFILE EXIT
    THEN
    _SRRESI-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
    _SRRESI-STORE @ _SRRESI-SCAP @ MSPAN-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT
    THEN
    _SRRESI-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
    _SRRESI-TXN @ _SRRESI-TCAP @ MSPAN-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT
    THEN
    _SRRESI-STORE @ _SRRESI-SCAP @ _SRRESI-TXN @ _SRRESI-TCAP @
        MSPAN-OVERLAP? IF STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT THEN
    _SRRESI-SA @ _SRRESI-SU @
    _SRRESI-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE MSPAN-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT
    THEN
    _SRRESI-SA @ _SRRESI-SU @ _SRRESI-STORE @ _SRRESI-SCAP @
        MSPAN-OVERLAP? IF STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT THEN
    _SRRESI-SA @ _SRRESI-SU @ _SRRESI-TXN @ _SRRESI-TCAP @
        MSPAN-OVERLAP? IF STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT THEN
    _SRRESI-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE _SRRESI-SCHEMA @
        CS-SCHEMA-GRAPH-SPAN-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT
    THEN
    _SRRESI-STORE @ _SRRESI-SCAP @ _SRRESI-SCHEMA @
        CS-SCHEMA-GRAPH-SPAN-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT
    THEN
    _SRRESI-TXN @ _SRRESI-TCAP @ _SRRESI-SCHEMA @
        CS-SCHEMA-GRAPH-SPAN-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT
    THEN
    _SRRESI-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE _SRRESI-CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT
    THEN
    _SRRESI-STORE @ _SRRESI-SCAP @ _SRRESI-CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT
    THEN
    _SRRESI-TXN @ _SRRESI-TCAP @ _SRRESI-CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT
    THEN
    _SRRESI-SCHEMA @ _SRRESI-CONNECTOR @
        _SRRES-SCHEMA-GRAPH-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS EXIT
    THEN
    _SRRESI-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE 0 FILL
    _SRRESI-STORE @ _SRRESI-SCAP @ 0 FILL
    _SRRESI-TXN @ _SRRESI-TCAP @ 0 FILL
    _SRRESI-SA @ _SRRESI-STORE @ _SRRESI-SU @ MOVE
    _SRRESI-CONNECTOR @ _SRRESI-O @ SRRES.CONNECTOR !
    _SRRESI-SCHEMA @ _SRRESI-O @ SRRES.SCHEMA !
    _SRRESI-STORE @ _SRRESI-O @ SRRES.SELECTOR-A !
    _SRRESI-SCAP @ _SRRESI-O @ SRRES.SELECTOR-CAP !
    _SRRESI-SU @ _SRRESI-O @ SRRES.SELECTOR-U !
    _SRRESI-TXN @ _SRRESI-O @ SRRES.TXN-A !
    _SRRESI-TCAP @ _SRRESI-O @ SRRES.TXN-CAP !
    _SRRESI-O @ SRRES.CACHE CV-INIT
    _SRRESI-O @ SRRES.STAGING CV-INIT
    STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE _SRRESI-O @ SRRES.STATE !
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK _SRRESI-O @ SRRES.LAST-STATUS !
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK _SRRESI-O @ SRRES.ATTEMPT-STATUS !
    STREAMS-RABBIT-REMOTE-RESOURCE-SIZE _SRRESI-O @ SRRES.BYTES !
    _SRRES-ABI-VERSION _SRRESI-O @ SRRES.ABI !
    _SRRES-MAGIC-VALUE _SRRESI-O @ SRRES.MAGIC !
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: STREAMS-RABBIT-REMOTE-RESOURCE-INIT
  ( connector selector-a selector-u selector-store selector-cap )
  ( txn-store txn-cap schema owner -- status )
    ['] _SRRES-INIT _srres-guard WITH-GUARD ;

VARIABLE _SRRESCFG-XT
VARIABLE _SRRESCFG-CONTEXT
VARIABLE _SRRESCFG-O

: _SRRES-VALIDATOR!  ( validator-xt context owner -- status )
    _SRRESCFG-O ! _SRRESCFG-CONTEXT ! _SRRESCFG-XT !
    _SRRESCFG-O @ _SRRES-VALID? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESCFG-O @ SRRES.STATE @ STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE <>
        IF STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT THEN
    _SRRESCFG-O @ SRRES.EVENT-STAGE-STATE @
        _SRRES-EVENT-STAGE-EMPTY <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    _SRRESCFG-XT @ _SRRESCFG-O @ SRRES.VALIDATOR-XT !
    _SRRESCFG-XT @ IF _SRRESCFG-CONTEXT @ ELSE 0 THEN
        _SRRESCFG-O @ SRRES.VALIDATOR-CONTEXT !
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0
    _SRRESCFG-O @ _SRRES-STATUS! ;

: STREAMS-RABBIT-REMOTE-RESOURCE-VALIDATOR!
  ( validator-xt context owner -- status )
    ['] _SRRES-VALIDATOR! _srres-guard WITH-GUARD ;

: _SRRES-FALLBACK!  ( fallback-xt context owner -- status )
    _SRRESCFG-O ! _SRRESCFG-CONTEXT ! _SRRESCFG-XT !
    _SRRESCFG-O @ _SRRES-VALID? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESCFG-O @ SRRES.STATE @ STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE <>
        IF STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT THEN
    _SRRESCFG-O @ SRRES.EVENT-STAGE-STATE @
        _SRRES-EVENT-STAGE-EMPTY <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    _SRRESCFG-XT @ _SRRESCFG-O @ SRRES.FALLBACK-XT !
    _SRRESCFG-XT @ IF _SRRESCFG-CONTEXT @ ELSE 0 THEN
        _SRRESCFG-O @ SRRES.FALLBACK-CONTEXT !
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0
    _SRRESCFG-O @ _SRRES-STATUS! ;

: STREAMS-RABBIT-REMOTE-RESOURCE-FALLBACK!
  ( fallback-xt context owner -- status )
    ['] _SRRES-FALLBACK! _srres-guard WITH-GUARD ;

\ =====================================================================
\ Accessors
\ =====================================================================

: _SRRES-STATE@  ( owner -- state status )
    DUP _SRRES-VALID? 0= IF
        DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    SRRES.STATE @ STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: STREAMS-RABBIT-REMOTE-RESOURCE-STATE@  ( owner -- state status )
    ['] _SRRES-STATE@ _srres-guard WITH-GUARD ;

: _SRRES-LAST@  ( owner -- last-status detail-domain detail status )
    DUP _SRRES-VALID? 0= IF
        DROP STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    DUP SRRES.LAST-STATUS @ OVER SRRES.DETAIL-DOMAIN @
    ROT SRRES.DETAIL @ STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: STREAMS-RABBIT-REMOTE-RESOURCE-LAST@
  ( owner -- last-status detail-domain detail status )
    ['] _SRRES-LAST@ _srres-guard WITH-GUARD ;

: _SRRES-RESPONSE@  ( owner -- code required-bytes status )
    DUP _SRRES-VALID? 0= IF
        DROP 0 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    DUP SRRES.RESPONSE-CODE @ SWAP SRRES.RESPONSE-BYTES @
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: STREAMS-RABBIT-REMOTE-RESOURCE-RESPONSE@
  ( owner -- code required-bytes status )
    ['] _SRRES-RESPONSE@ _srres-guard WITH-GUARD ;

: _SRRES-CACHE@  ( owner -- value generation status )
    DUP _SRRES-VALID? 0= IF
        DROP 0 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    DUP SRRES.CACHE-PRESENT @ 0= IF
        DROP 0 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-EMPTY EXIT
    THEN
    DUP SRRES.CACHE SWAP SRRES.CACHE-GENERATION @
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: STREAMS-RABBIT-REMOTE-RESOURCE-CACHE@
  ( owner -- value generation status )
    ['] _SRRES-CACHE@ _srres-guard WITH-GUARD ;

: _SRRES-CACHE-CALLBACK@  ( owner -- value generation status )
    \ The connector is deliberately busy during application dispatch, so this
    \ read-only borrow validates only this owner's already-retained shape.
    DUP _SRRES-STRUCTURAL? 0= IF
        DROP 0 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    DUP SRRES.SCHEMA @ IVJSON-SCHEMA-COMPATIBLE? 0= IF
        DROP 0 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-PROFILE EXIT
    THEN
    DUP SRRES.CACHE-PRESENT @ 0= IF
        DROP 0 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-EMPTY EXIT
    THEN
    DUP SRRES.CACHE SWAP SRRES.CACHE-GENERATION @
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: STREAMS-RABBIT-REMOTE-RESOURCE-CACHE-CALLBACK@
  ( owner -- value generation status )
    ['] _SRRES-CACHE-CALLBACK@ _srres-guard WITH-GUARD ;

VARIABLE _SRRESST-O
VARIABLE _SRRESST-TOKEN
VARIABLE _SRRESST-STATE
VARIABLE _SRRESES-BUSY

\ Structurally compare an owner's retained stage token with this resource.
\ Token zero denotes the exact EMPTY state; a nonzero token may name READY or
\ DISCARD because cleanup failure deliberately retains the latter.  No live
\ connector, schema, or UTF-8 dependency is needed to inspect cleanup state.
: _SRRES-CACHE-STAGE-MATCH?  ( stage-generation owner -- match? status )
    _SRRESES-BUSY @ IF
        2DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    _SRRESST-O ! _SRRESST-TOKEN !
    _SRRESST-O @ _SRRES-HEADER? 0= IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESST-O @ SRRES.BUSY @ IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    _SRRESST-O @ _SRRES-STRUCTURAL? 0= IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESST-O @ SRRES.EVENT-STAGE-STATE @ _SRRESST-STATE !
    _SRRESST-TOKEN @ 0= IF
        _SRRESST-STATE @ _SRRES-EVENT-STAGE-EMPTY =
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK EXIT
    THEN
    _SRRESST-STATE @ DUP _SRRES-EVENT-STAGE-READY =
    SWAP _SRRES-EVENT-STAGE-DISCARD = OR
    _SRRESST-TOKEN @ _SRRESST-O @ SRRES.EVENT-STAGE-GENERATION @ = AND
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: STREAMS-RABBIT-REMOTE-RESOURCE-CACHE-STAGE-MATCH?
  ( stage-generation owner -- match? status )
    ['] _SRRES-CACHE-STAGE-MATCH? _srres-guard WITH-GUARD ;

\ Borrow the exact decoded READY candidate during its enclosing subscription
\ callback.  The value remains resource-owned and expires on publication,
\ discard, abandonment, or FINI.  This accessor never decodes a second time.
: _SRRES-CACHE-STAGED-CALLBACK@
  ( stage-generation owner -- value status )
    _SRRESES-BUSY @ IF
        2DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    _SRRESST-O ! _SRRESST-TOKEN !
    _SRRESST-O @ _SRRES-HEADER? 0= IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESST-O @ SRRES.BUSY @ IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    _SRRESST-O @ _SRRES-STRUCTURAL? 0= IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESST-O @ SRRES.EVENT-STAGE-STATE @
        _SRRES-EVENT-STAGE-READY <> IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    _SRRESST-TOKEN @ 0=
    _SRRESST-TOKEN @ _SRRESST-O @ SRRES.EVENT-STAGE-GENERATION @ <> OR IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    _SRRESST-O @ SRRES.STAGING STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: STREAMS-RABBIT-REMOTE-RESOURCE-CACHE-STAGED-CALLBACK@
  ( stage-generation owner -- value status )
    ['] _SRRES-CACHE-STAGED-CALLBACK@ _srres-guard WITH-GUARD ;

VARIABLE _SRRESAV-V
VARIABLE _SRRESAV-O
VARIABLE _SRRESAV-DEPTH
VARIABLE _SRRESAV-STATUS
VARIABLE _SRRESAV-THROW
VARIABLE _SRRESAV-DOMAIN
VARIABLE _SRRESAV-DETAIL

-272 CONSTANT _SRRESAV-E-VALIDATOR-STACK

: _SRRESAV-VALIDATOR-CALL  ( -- )
    DEPTH _SRRESAV-DEPTH !
    _SRRESAV-V @ _SRRESAV-O @
    _SRRESAV-O @ SRRES.VALIDATOR-CONTEXT @
    _SRRESAV-O @ SRRES.VALIDATOR-XT @ EXECUTE
    _SRRESAV-STATUS !
    DEPTH _SRRESAV-DEPTH @ <> IF
        _SRRESAV-E-VALIDATOR-STACK THROW
    THEN ;

: _SRRES-EVENT-APP-VALIDATE  ( -- status )
    _SRRESAV-O @ SRRES.VALIDATOR-XT @ 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK EXIT
    THEN
    0 _SRRESAV-STATUS ! 0 _SRRESAV-THROW !
    ['] _SRRESAV-VALIDATOR-CALL CATCH
        DUP _SRRESAV-THROW ! IF
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CALLBACK _SRRESAV-DOMAIN !
        _SRRESAV-THROW @ _SRRESAV-DETAIL !
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CALLBACK EXIT
    THEN
    _SRRESAV-STATUS @ IF
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-VALIDATOR _SRRESAV-DOMAIN !
        _SRRESAV-STATUS @ _SRRESAV-DETAIL !
        STREAMS-RABBIT-REMOTE-RESOURCE-S-PROFILE
    ELSE
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK
    THEN ;

: _SRRES-SELECTOR$  ( owner -- address length status )
    DUP _SRRES-VALID? 0= IF
        DROP 0 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    DUP SRRES.SELECTOR-A @ SWAP SRRES.SELECTOR-U @
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: STREAMS-RABBIT-REMOTE-RESOURCE-SELECTOR$
  ( owner -- address length status )
    ['] _SRRES-SELECTOR$ _srres-guard WITH-GUARD ;

: _SRRES-CONNECTOR-MATCH?  ( connector owner -- match? status )
    DUP _SRRES-VALID? 0= IF
        2DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    SRRES.CONNECTOR @ = STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: STREAMS-RABBIT-REMOTE-RESOURCE-CONNECTOR-MATCH?
  ( connector owner -- match? status )
    ['] _SRRES-CONNECTOR-MATCH? _srres-guard WITH-GUARD ;

\ =====================================================================
\ Attempt storage helpers
\ =====================================================================

VARIABLE _SRRESW-O

: _SRRES-STAGING-FREE-CALL  ( -- )
    _SRRESW-O @ SRRES.STAGING CV-FREE ;

: _SRRES-STAGING-FREE  ( owner -- throw-code )
    _SRRESW-O ! ['] _SRRES-STAGING-FREE-CALL CATCH ;

: _SRRES-CACHE-FREE-CALL  ( -- )
    _SRRESW-O @ SRRES.CACHE CV-FREE ;

: _SRRES-CACHE-FREE  ( owner -- throw-code )
    _SRRESW-O ! ['] _SRRES-CACHE-FREE-CALL CATCH ;

: _SRRES-TXN-WIPE  ( owner -- )
    DUP SRRES.TXN-A @ OVER SRRES.TXN-CAP @ 0 FILL
    0 SWAP SRRES.TXN-U ! ;

: _SRRES-CLEAR-HANDLE  ( owner -- )
    DUP _SRRES-TXN-WIPE
    0 OVER SRRES.LANE !
    0 OVER SRRES.OPERATION !
    0 OVER SRRES.OPERATION-GENERATION !
    0 OVER SRRES.ATTACHMENT-GENERATION !
    0 SWAP SRRES.CALLBACK-SEEN ! ;

: _SRRES-CLEAR-ATTEMPT-META  ( owner -- )
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK OVER SRRES.ATTEMPT-STATUS !
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE OVER SRRES.ATTEMPT-DOMAIN !
    0 OVER SRRES.ATTEMPT-DETAIL !
    0 OVER SRRES.CANDIDATE-READY !
    0 SWAP SRRES.FETCH-CACHE-GENERATION ! ;

\ =====================================================================
\ Callback-safe, resource-owned event staging
\ =====================================================================

\ A stage generation is never reused.  EMPTY retains the last generation as
\ an ABA fence while EXPECTED is cleared.  READY owns one schema- and
\ application-validated graph.  DISCARD owns a graph which may only be freed;
\ it is used when validation or an unexpected callback path could not finish
\ cleanup.  The main FETCH state and all fetch attempt fields remain
\ orthogonal to this transaction.

VARIABLE _SRRESES-A
VARIABLE _SRRESES-U
VARIABLE _SRRESES-EXPECTED
VARIABLE _SRRESES-O
VARIABLE _SRRESES-TOKEN
VARIABLE _SRRESES-RS
VARIABLE _SRRESES-DOMAIN
VARIABLE _SRRESES-DETAIL
VARIABLE _SRRESES-THROW
VARIABLE _SRRESES-CHANGED

: _SRRES-EVENT-STAGE-CLEAR  ( owner -- )
    _SRRES-EVENT-STAGE-EMPTY OVER SRRES.EVENT-STAGE-STATE !
    0 SWAP SRRES.EVENT-STAGE-EXPECTED-GENERATION ! ;

: _SRRESES-RESULT  ( scalar status detail-domain detail -- scalar status )
    _SRRESES-O @ _SRRES-STATUS! ;

: _SRRESES-STATUS-RESULT  ( status detail-domain detail -- status )
    _SRRESES-O @ _SRRES-STATUS! ;

: _SRRESES-JSON-SPAN-VALID?  ( -- flag )
    _SRRESES-U @ 0> 0= IF 0 EXIT THEN
    _SRRESES-A @ _SRRESES-U @ MSPAN-NONWRAPPING? ;

: _SRRESES-JSON-OVERLAP?  ( -- flag )
    _SRRESES-A @ _SRRESES-U @
    _SRRESES-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        MSPAN-OVERLAP? IF -1 EXIT THEN
    _SRRESES-A @ _SRRESES-U @
    _SRRESES-O @ SRRES.SELECTOR-A @ _SRRESES-O @ SRRES.SELECTOR-CAP @
        MSPAN-OVERLAP? IF -1 EXIT THEN
    _SRRESES-A @ _SRRESES-U @
    _SRRESES-O @ SRRES.TXN-A @ _SRRESES-O @ SRRES.TXN-CAP @
        MSPAN-OVERLAP? IF -1 EXIT THEN
    _SRRESES-A @ _SRRESES-U @ _SRRESES-O @ SRRES.SCHEMA @
        CS-SCHEMA-GRAPH-SPAN-OVERLAP? ;

: _SRRES-CACHE-STAGE-JSON-INNER  ( -- stage-generation status )
    _SRRESES-O @ _SRRES-STRUCTURAL? 0= IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-O @ SRRES.SCHEMA @ IVJSON-SCHEMA-COMPATIBLE? 0= IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-PROFILE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-SCHEMA 0
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-O @ SRRES.STATE @ DUP
        STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE =
    SWAP STREAMS-RABBIT-REMOTE-RESOURCE-ST-FETCHING = OR 0= IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-O @ SRRES.EVENT-STAGE-STATE @
        _SRRES-EVENT-STAGE-EMPTY <> IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-JSON-SPAN-VALID? 0= IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY 0
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-JSON-OVERLAP? IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY 0
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-EXPECTED @ _SRRESES-O @ SRRES.CACHE-GENERATION @ <> IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY
        STREAMS-RABBIT-REMOTE-RESOURCE-E-GENERATION
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-O @ SRRES.CACHE-GENERATION @ RABBIT-U64-MAX = IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-CAPACITY
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY
        STREAMS-RABBIT-REMOTE-RESOURCE-E-GENERATION
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-O @ SRRES.EVENT-STAGE-GENERATION @ RABBIT-U64-MAX = IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-CAPACITY
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY
        STREAMS-RABBIT-REMOTE-RESOURCE-E-GENERATION
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-O @ SRRES.EVENT-STAGE-GENERATION @ 1+ DUP
        _SRRESES-TOKEN !
    _SRRESES-O @ SRRES.EVENT-STAGE-GENERATION !
    _SRRESES-EXPECTED @
        _SRRESES-O @ SRRES.EVENT-STAGE-EXPECTED-GENERATION !
    _SRRES-EVENT-STAGE-DISCARD
        _SRRESES-O @ SRRES.EVENT-STAGE-STATE !
    _SRRESES-O @ _SRRES-STAGING-FREE ?DUP IF
        _SRRESES-THROW !
        _SRRESES-TOKEN @ STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CODEC _SRRESES-THROW @
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-O @ SRRES.STAGING CV-INIT
    _SRRESES-A @ _SRRESES-U @ _SRRESES-O @ SRRES.SCHEMA @
        _SRRESES-O @ SRRES.STAGING IVJSON-DECODE-AS DUP IF
        _SRRESES-RS !
        _SRRESES-O @ _SRRES-EVENT-STAGE-CLEAR
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-CODEC
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CODEC _SRRESES-RS @
        _SRRESES-RESULT EXIT
    THEN
    DROP
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE _SRRESAV-DOMAIN !
    0 _SRRESAV-DETAIL !
    _SRRESES-O @ SRRES.STAGING _SRRESAV-V !
    _SRRESES-O @ _SRRESAV-O !
    _SRRES-EVENT-APP-VALIDATE _SRRESES-RS !
    _SRRESES-RS @ STREAMS-RABBIT-REMOTE-RESOURCE-S-OK <> IF
        _SRRESAV-DOMAIN @ _SRRESES-DOMAIN !
        _SRRESAV-DETAIL @ _SRRESES-DETAIL !
        _SRRESES-O @ _SRRES-STAGING-FREE ?DUP IF
            _SRRESES-THROW !
            _SRRES-EVENT-STAGE-DISCARD
                _SRRESES-O @ SRRES.EVENT-STAGE-STATE !
            _SRRESES-TOKEN @ STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP
            STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CODEC _SRRESES-THROW @
            _SRRESES-RESULT EXIT
        THEN
        _SRRESES-O @ SRRES.STAGING CV-INIT
        _SRRESES-O @ _SRRES-EVENT-STAGE-CLEAR
        0 _SRRESES-RS @ _SRRESES-DOMAIN @ _SRRESES-DETAIL @
        _SRRESES-RESULT EXIT
    THEN
    _SRRES-EVENT-STAGE-READY _SRRESES-O @ SRRES.EVENT-STAGE-STATE !
    _SRRESES-TOKEN @ STREAMS-RABBIT-REMOTE-RESOURCE-S-OK
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0 _SRRESES-RESULT ;

: _SRRES-CACHE-STAGE-JSON-CALLBACK
  ( json-a json-u expected-cache-generation owner -- stage-generation status )
    _SRRESES-BUSY @ IF
        2DROP 2DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    DUP _SRRES-HEADER? 0= IF
        2DROP 2DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    DUP SRRES.BUSY @ IF
        2DROP 2DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    -1 OVER SRRES.BUSY !
    -1 _SRRESES-BUSY !
    _SRRESES-O ! _SRRESES-EXPECTED ! _SRRESES-U ! _SRRESES-A !
    0 _SRRESES-TOKEN ! 0 _SRRESES-THROW !
    ['] _SRRES-CACHE-STAGE-JSON-INNER CATCH DUP IF
        _SRRESES-THROW !
        _SRRESES-TOKEN @ IF
            _SRRES-EVENT-STAGE-DISCARD
                _SRRESES-O @ SRRES.EVENT-STAGE-STATE !
        THEN
        _SRRESES-TOKEN @ STREAMS-RABBIT-REMOTE-RESOURCE-S-CALLBACK
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CALLBACK
        _SRRESES-THROW @ _SRRESES-RESULT
    ELSE
        DROP
    THEN
    _SRRESES-RS ! _SRRESES-TOKEN !
    0 _SRRESES-O @ SRRES.BUSY !
    0 _SRRESES-BUSY !
    _SRRESES-TOKEN @ _SRRESES-RS @ ;

: STREAMS-RABBIT-REMOTE-RESOURCE-CACHE-STAGE-JSON-CALLBACK
  ( json-a json-u expected-cache-generation owner -- stage-generation status )
    ['] _SRRES-CACHE-STAGE-JSON-CALLBACK _srres-guard WITH-GUARD ;

: _SRRES-CACHE-PUBLISH-STAGED-INNER  ( -- changed? status )
    _SRRESES-O @ SRRES.EVENT-STAGE-STATE @
        _SRRES-EVENT-STAGE-READY <> IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-TOKEN @ _SRRESES-O @ SRRES.EVENT-STAGE-GENERATION @ <> IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY
        STREAMS-RABBIT-REMOTE-RESOURCE-E-GENERATION
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-O @ SRRES.EVENT-STAGE-EXPECTED-GENERATION @
    _SRRESES-O @ SRRES.CACHE-GENERATION @ <> IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY
        STREAMS-RABBIT-REMOTE-RESOURCE-E-GENERATION
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-O @ SRRES.CACHE-GENERATION @ RABBIT-U64-MAX = IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-CAPACITY
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY
        STREAMS-RABBIT-REMOTE-RESOURCE-E-GENERATION
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-O @ _SRRES-CACHE-FREE ?DUP IF
        _SRRESES-THROW !
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CODEC _SRRESES-THROW @
        _SRRESES-RESULT EXIT
    THEN
    _SRRESES-O @ SRRES.STAGING _SRRESES-O @ SRRES.CACHE CV-SIZE CMOVE
    _SRRESES-O @ SRRES.STAGING CV-INIT
    1 _SRRESES-O @ SRRES.CACHE-GENERATION +!
    -1 _SRRESES-O @ SRRES.CACHE-PRESENT !
    _SRRESES-O @ _SRRES-EVENT-STAGE-CLEAR
    -1 STREAMS-RABBIT-REMOTE-RESOURCE-S-OK
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0 _SRRESES-RESULT ;

: _SRRES-CACHE-PUBLISH-STAGED  ( stage-generation owner -- changed? status )
    _SRRESES-BUSY @ IF
        2DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    DUP _SRRES-HEADER? 0= IF
        2DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    DUP SRRES.BUSY @ IF
        2DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    DUP _SRRES-VALID? 0= IF
        2DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    -1 OVER SRRES.BUSY !
    -1 _SRRESES-BUSY !
    _SRRESES-O ! _SRRESES-TOKEN ! 0 _SRRESES-THROW !
    ['] _SRRES-CACHE-PUBLISH-STAGED-INNER CATCH DUP IF
        _SRRESES-THROW !
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-CALLBACK
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CALLBACK
        _SRRESES-THROW @ _SRRESES-RESULT
    ELSE
        DROP
    THEN
    _SRRESES-RS ! _SRRESES-CHANGED !
    0 _SRRESES-O @ SRRES.BUSY !
    0 _SRRESES-BUSY !
    _SRRESES-CHANGED @ _SRRESES-RS @ ;

: STREAMS-RABBIT-REMOTE-RESOURCE-CACHE-PUBLISH-STAGED
  ( stage-generation owner -- changed? status )
    ['] _SRRES-CACHE-PUBLISH-STAGED _srres-guard WITH-GUARD ;

: _SRRES-CACHE-DISCARD-STAGED-INNER  ( -- status )
    _SRRESES-O @ SRRES.EVENT-STAGE-STATE @ DUP
        _SRRES-EVENT-STAGE-READY =
    SWAP _SRRES-EVENT-STAGE-DISCARD = OR 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0
        _SRRESES-STATUS-RESULT EXIT
    THEN
    _SRRESES-TOKEN @ _SRRESES-O @ SRRES.EVENT-STAGE-GENERATION @ <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY
        STREAMS-RABBIT-REMOTE-RESOURCE-E-GENERATION
        _SRRESES-STATUS-RESULT EXIT
    THEN
    _SRRESES-O @ _SRRES-STAGING-FREE ?DUP IF
        _SRRES-EVENT-STAGE-DISCARD
            _SRRESES-O @ SRRES.EVENT-STAGE-STATE !
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CODEC ROT
        _SRRESES-STATUS-RESULT EXIT
    THEN
    _SRRESES-O @ SRRES.STAGING CV-INIT
    _SRRESES-O @ _SRRES-EVENT-STAGE-CLEAR
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0
    _SRRESES-STATUS-RESULT ;

: _SRRES-CACHE-DISCARD-STAGED  ( stage-generation owner -- status )
    _SRRESES-BUSY @ IF
        2DROP STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    DUP _SRRES-HEADER? 0= IF
        2DROP STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    DUP SRRES.BUSY @ IF
        2DROP STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    \ Discard owns only STAGING.  It deliberately needs no live connector,
    \ schema, or UTF-8 dependency: a staged graph must remain releasable after
    \ a borrowed dependency violates its lifetime contract.
    DUP _SRRES-STRUCTURAL? 0= IF
        2DROP STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    -1 OVER SRRES.BUSY !
    -1 _SRRESES-BUSY !
    _SRRESES-O ! _SRRESES-TOKEN ! 0 _SRRESES-THROW !
    ['] _SRRES-CACHE-DISCARD-STAGED-INNER CATCH DUP IF
        _SRRESES-THROW !
        _SRRESES-O @ SRRES.EVENT-STAGE-STATE @ DUP
            _SRRES-EVENT-STAGE-READY =
        SWAP _SRRES-EVENT-STAGE-DISCARD = OR IF
            _SRRES-EVENT-STAGE-DISCARD
                _SRRESES-O @ SRRES.EVENT-STAGE-STATE !
        THEN
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CALLBACK
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CALLBACK
        _SRRESES-THROW @ _SRRESES-STATUS-RESULT
    ELSE
        DROP
    THEN
    _SRRESES-RS !
    0 _SRRESES-O @ SRRES.BUSY !
    0 _SRRESES-BUSY !
    _SRRESES-RS @ ;

: STREAMS-RABBIT-REMOTE-RESOURCE-CACHE-DISCARD-STAGED
  ( stage-generation owner -- status )
    ['] _SRRES-CACHE-DISCARD-STAGED _srres-guard WITH-GUARD ;

\ =====================================================================
\ Sealed FETCH validation and publication
\ =====================================================================

VARIABLE _SRRESF-B
VARIABLE _SRRESF-F
VARIABLE _SRRESF-O
VARIABLE _SRRESF-A
VARIABLE _SRRESF-U
VARIABLE _SRRESF-PRESENT
VARIABLE _SRRESF-MS
VARIABLE _SRRESF-LANE
VARIABLE _SRRESF-TXN-A
VARIABLE _SRRESF-TXN-U
VARIABLE _SRRESF-OP
VARIABLE _SRRESF-GEN
VARIABLE _SRRESF-ATTACH-GEN
VARIABLE _SRRESF-CS

: _SRRESF-RETURN  ( status detail-domain detail -- status )
    _SRRESF-O @ _SRRES-STATUS! ;

: _SRRESF-BUILDER-FAIL  ( exact-detail -- status )
    STREAMS-RABBIT-REMOTE-RESOURCE-S-BUILDER
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-BUILDER ROT _SRRESF-RETURN ;

: _SRRESF-MESSAGE-FAIL  ( exact-detail -- status )
    STREAMS-RABBIT-REMOTE-RESOURCE-S-MESSAGE
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-MESSAGE ROT _SRRESF-RETURN ;

: _SRRESF-EXACT-VIEW?  ( address length present message-status -- flag )
    _SRRESF-MS ! _SRRESF-PRESENT ! _SRRESF-U ! _SRRESF-A !
    _SRRESF-MS @ RMSG-S-OK = _SRRESF-PRESENT @ 0<> AND
    _SRRESF-A @ _SRRESF-U @ S" application/akashic-value+json"
        STR-STR= AND ;

: _SRRESF-WITH-BUSY  ( xt owner -- status )
    _SRRESF-O !
    -1 _SRRESF-O @ SRRES.BUSY !
    CATCH
    0 _SRRESF-O @ SRRES.BUSY !
    ?DUP IF THROW THEN ;

: _SRRES-FETCH-BUSY  ( -- status )
    _SRRESF-F @ RBF-ARGS$
    _SRRESF-O @ SRRES.SELECTOR-A @ _SRRESF-O @ SRRES.SELECTOR-U @
        STR-STR= 0= IF RMSG-S-START _SRRESF-MESSAGE-FAIL EXIT THEN
    _SRRESF-F @ RMSG-LANE@
        _SRRESF-MS ! _SRRESF-PRESENT ! _SRRESF-LANE !
    _SRRESF-MS @ RMSG-S-OK <> IF _SRRESF-MS @ _SRRESF-MESSAGE-FAIL EXIT THEN
    _SRRESF-PRESENT @ 0= _SRRESF-LANE @ 0= OR IF
        RMSG-S-REQUIRED _SRRESF-MESSAGE-FAIL EXIT
    THEN
    _SRRESF-F @ RMSG-TXN$
        _SRRESF-MS ! _SRRESF-PRESENT ! _SRRESF-TXN-U ! _SRRESF-TXN-A !
    _SRRESF-MS @ RMSG-S-OK <> IF _SRRESF-MS @ _SRRESF-MESSAGE-FAIL EXIT THEN
    _SRRESF-PRESENT @ 0= _SRRESF-TXN-U @ 0= OR IF
        RMSG-S-REQUIRED _SRRESF-MESSAGE-FAIL EXIT
    THEN
    _SRRESF-TXN-U @ _SRRESF-O @ SRRES.TXN-CAP @ U> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CAPACITY
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY
        _SRRESF-TXN-U @ _SRRESF-RETURN EXIT
    THEN
    _SRRESF-F @ RMSG-VIEW$ _SRRESF-EXACT-VIEW? 0= IF
        RMSG-S-VALUE _SRRESF-MESSAGE-FAIL EXIT
    THEN
    _SRRESF-F @ RMSG-ACCEPT-VIEW$ _SRRESF-EXACT-VIEW? 0= IF
        RMSG-S-VALUE _SRRESF-MESSAGE-FAIL EXIT
    THEN
    _SRRESF-F @ RMSG-BODY$ _SRRESF-MS ! _SRRESF-U ! _SRRESF-A !
    _SRRESF-MS @ RMSG-S-OK <> IF _SRRESF-MS @ _SRRESF-MESSAGE-FAIL EXIT THEN
    _SRRESF-U @ 0= IF RMSG-S-REQUIRED _SRRESF-MESSAGE-FAIL EXIT THEN
    _SRRESF-O @ _SRRES-STAGING-FREE ?DUP IF
        STREAMS-RABBIT-REMOTE-RESOURCE-ST-CLEANUP _SRRESF-O @ SRRES.STATE !
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CODEC ROT
        _SRRESF-RETURN EXIT
    THEN
    _SRRESF-O @ SRRES.STAGING CV-INIT
    _SRRESF-O @ _SRRES-TXN-WIPE
    _SRRESF-TXN-A @ _SRRESF-O @ SRRES.TXN-A @ _SRRESF-TXN-U @ MOVE
    _SRRESF-TXN-U @ _SRRESF-O @ SRRES.TXN-U !
    _SRRESF-LANE @ _SRRESF-O @ SRRES.LANE !
    0 _SRRESF-O @ SRRES.CALLBACK-SEEN !
    0 _SRRESF-O @ SRRES.RESPONSE-CODE !
    0 _SRRESF-O @ SRRES.RESPONSE-BYTES !
    0 _SRRESF-O @ SRRES.CANDIDATE-READY !
    _SRRESF-O @ SRRES.CACHE-GENERATION @
        _SRRESF-O @ SRRES.FETCH-CACHE-GENERATION !
    STREAMS-RABBIT-REMOTE-RESOURCE-S-RESPONSE
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-RESPONSE
    STREAMS-RABBIT-REMOTE-RESOURCE-E-CALLBACK-MISSING
        _SRRESF-O @ _SRRES-ATTEMPT! DROP
    _SRRESF-B @ _SRRESF-O @ SRRES.CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-REQUEST
        _SRRESF-CS ! _SRRESF-ATTACH-GEN ! _SRRESF-GEN ! _SRRESF-OP !
    _SRRESF-CS @ STREAMS-RABBIT-CONNECTOR-S-OK <> IF
        _SRRESF-O @ _SRRES-CLEAR-HANDLE
        0 _SRRESF-O @ SRRES.FETCH-CACHE-GENERATION !
        _SRRESF-CS @ _SRRESF-O @ _SRRES-CONNECTOR-ATTEMPT! DROP
        _SRRESF-O @ SRRES.ATTEMPT-STATUS @
        _SRRESF-O @ SRRES.ATTEMPT-DOMAIN @
        _SRRESF-O @ SRRES.ATTEMPT-DETAIL @ _SRRESF-RETURN EXIT
    THEN
    _SRRESF-OP @ 0= _SRRESF-GEN @ 0= OR
    _SRRESF-ATTACH-GEN @ 0= OR IF
        _SRRESF-O @ _SRRES-CLEAR-HANDLE
        0 _SRRESF-O @ SRRES.FETCH-CACHE-GENERATION !
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CONNECTOR
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CONNECTOR
        STREAMS-RABBIT-REMOTE-RESOURCE-E-OPERATION-MISMATCH
        _SRRESF-RETURN EXIT
    THEN
    _SRRESF-OP @ _SRRESF-O @ SRRES.OPERATION !
    _SRRESF-GEN @ _SRRESF-O @ SRRES.OPERATION-GENERATION !
    _SRRESF-ATTACH-GEN @ _SRRESF-O @ SRRES.ATTACHMENT-GENERATION !
    STREAMS-RABBIT-REMOTE-RESOURCE-ST-FETCHING _SRRESF-O @ SRRES.STATE !
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0 _SRRESF-RETURN ;

: _SRRES-FETCH  ( ready-builder owner -- status )
    _SRRESF-O ! _SRRESF-B !
    _SRRESF-O @ _SRRES-VALID? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESF-O @ SRRES.STATE @ STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE <>
        IF STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT THEN
    _SRRESF-O @ SRRES.EVENT-STAGE-STATE @
        _SRRES-EVENT-STAGE-EMPTY <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    _SRRESF-O @ SRRES.CACHE-GENERATION @ RABBIT-U64-MAX = IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CAPACITY EXIT
    THEN
    _SRRESF-B @ RMSGB-VALID? 0= IF
        RMSGB-S-INVALID _SRRESF-BUILDER-FAIL EXIT
    THEN
    _SRRESF-B @ RMSGB-READY-FRAME@ DUP _SRRESF-F ! 0= IF
        RMSGB-S-STATE _SRRESF-BUILDER-FAIL EXIT
    THEN
    _SRRESF-B @ RMSGB-KIND@ RMSG-KIND-FETCH <> IF
        RMSGB-S-UNSUPPORTED _SRRESF-BUILDER-FAIL EXIT
    THEN
    _SRRESF-B @ _SRRESF-O @ _SRRES-BUILDER-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY 0
        _SRRESF-RETURN EXIT
    THEN
    ['] _SRRES-FETCH-BUSY _SRRESF-O @ _SRRESF-WITH-BUSY ;

: STREAMS-RABBIT-REMOTE-RESOURCE-FETCH  ( ready-builder owner -- status )
    ['] _SRRES-FETCH _srres-guard WITH-GUARD ;

\ =====================================================================
\ Borrowed response callback
\ =====================================================================

VARIABLE _SRRESCB-F
VARIABLE _SRRESCB-KIND
VARIABLE _SRRESCB-LANE
VARIABLE _SRRESCB-SEQ
VARIABLE _SRRESCB-EXPECTED
VARIABLE _SRRESCB-DISPOSITION
VARIABLE _SRRESCB-O
VARIABLE _SRRESCB-A
VARIABLE _SRRESCB-U
VARIABLE _SRRESCB-PRESENT
VARIABLE _SRRESCB-MS
VARIABLE _SRRESCB-CODE
VARIABLE _SRRESCB-DECISION
VARIABLE _SRRESCB-DEPTH
VARIABLE _SRRESCB-THROW

-270 CONSTANT _SRRESCB-E-FALLBACK-STACK

: _SRRESCB-DROP-ARGS
  ( frame kind lane seq expected disposition context -- )
    2DROP 2DROP 2DROP DROP ;

: _SRRESCB-DEFAULT  ( -- decision )
    _SRRESCB-KIND @ RMSG-KIND-RESPONSE = IF
        RCLIENT-DISPATCH-COMMIT
    ELSE
        RCLIENT-DISPATCH-DROP
    THEN ;

: _SRRESCB-DEFAULT-FROM-STACK
  ( frame kind lane seq expected disposition context -- decision )
    5 PICK RMSG-KIND-RESPONSE = IF
        RCLIENT-DISPATCH-COMMIT
    ELSE
        RCLIENT-DISPATCH-DROP
    THEN
    >R _SRRESCB-DROP-ARGS R> ;

: _SRRESCB-MATCH?  ( -- flag )
    _SRRESCB-O @ SRRES.STATE @
        STREAMS-RABBIT-REMOTE-RESOURCE-ST-FETCHING <> IF 0 EXIT THEN
    _SRRESCB-KIND @ RMSG-KIND-RESPONSE <> IF 0 EXIT THEN
    _SRRESCB-LANE @ _SRRESCB-O @ SRRES.LANE @ <> IF 0 EXIT THEN
    _SRRESCB-F @ RMSG-TXN$
        _SRRESCB-MS ! _SRRESCB-PRESENT ! _SRRESCB-U ! _SRRESCB-A !
    _SRRESCB-MS @ RMSG-S-OK <> _SRRESCB-PRESENT @ 0= OR IF 0 EXIT THEN
    _SRRESCB-A @ _SRRESCB-U @
    _SRRESCB-O @ SRRES.TXN-A @ _SRRESCB-O @ SRRES.TXN-U @ STR-STR= ;

: _SRRESCB-REJECT  ( owner-status detail-domain detail -- decision )
    _SRRESCB-O @ _SRRES-ATTEMPT! DROP
    RCLIENT-DISPATCH-COMMIT ;

: _SRRESCB-EXACT  ( -- decision )
    -1 _SRRESCB-O @ SRRES.CALLBACK-SEEN !
    _SRRESCB-F @ RMSG-STATUS@
        _SRRESCB-MS ! _SRRESCB-PRESENT ! _SRRESCB-CODE !
    _SRRESCB-MS @ RMSG-S-OK <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-MESSAGE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-MESSAGE _SRRESCB-MS @
        _SRRESCB-REJECT EXIT
    THEN
    _SRRESCB-PRESENT @ 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-MESSAGE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-MESSAGE RMSG-S-REQUIRED
        _SRRESCB-REJECT EXIT
    THEN
    _SRRESCB-CODE @ _SRRESCB-O @ SRRES.RESPONSE-CODE !
    _SRRESCB-F @ RMSG-BODY$
        _SRRESCB-MS ! _SRRESCB-U ! _SRRESCB-A !
    _SRRESCB-MS @ RMSG-S-OK <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-MESSAGE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-MESSAGE _SRRESCB-MS @
        _SRRESCB-REJECT EXIT
    THEN
    _SRRESCB-U @ _SRRESCB-O @ SRRES.RESPONSE-BYTES !
    _SRRESCB-CODE @ 200 <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-RESPONSE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-RESPONSE _SRRESCB-CODE @
        _SRRESCB-REJECT EXIT
    THEN
    _SRRESCB-F @ RMSG-LABEL$
        _SRRESCB-MS ! _SRRESCB-U ! _SRRESCB-A !
    _SRRESCB-MS @ RMSG-S-OK <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-MESSAGE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-MESSAGE _SRRESCB-MS @
        _SRRESCB-REJECT EXIT
    THEN
    _SRRESCB-A @ _SRRESCB-U @ S" RESULT" STR-STR= 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-RESPONSE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-RESPONSE
        STREAMS-RABBIT-REMOTE-RESOURCE-E-LABEL _SRRESCB-REJECT EXIT
    THEN
    _SRRESCB-F @ RMSG-VIEW$
        _SRRESCB-MS ! _SRRESCB-PRESENT ! _SRRESCB-U ! _SRRESCB-A !
    _SRRESCB-MS @ RMSG-S-OK <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-MESSAGE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-MESSAGE _SRRESCB-MS @
        _SRRESCB-REJECT EXIT
    THEN
    _SRRESCB-PRESENT @ 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-PROFILE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-RESPONSE
        STREAMS-RABBIT-REMOTE-RESOURCE-E-VIEW-MISSING _SRRESCB-REJECT EXIT
    THEN
    _SRRESCB-A @ _SRRESCB-U @ S" application/akashic-value+json"
        STR-STR= 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-PROFILE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-RESPONSE
        STREAMS-RABBIT-REMOTE-RESOURCE-E-VIEW-MISMATCH _SRRESCB-REJECT EXIT
    THEN
    _SRRESCB-O @ SRRES.RESPONSE-BYTES @ 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-RESPONSE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-RESPONSE
        STREAMS-RABBIT-REMOTE-RESOURCE-E-BODY _SRRESCB-REJECT EXIT
    THEN
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0
        _SRRESCB-O @ _SRRES-ATTEMPT! DROP
    RCLIENT-DISPATCH-COMMIT ;

: _SRRESCB-FALLBACK-CALL  ( -- )
    DEPTH _SRRESCB-DEPTH !
    _SRRESCB-F @ _SRRESCB-KIND @ _SRRESCB-LANE @ _SRRESCB-SEQ @
    _SRRESCB-EXPECTED @ _SRRESCB-DISPOSITION @
    _SRRESCB-O @ SRRES.FALLBACK-CONTEXT @
    _SRRESCB-O @ SRRES.FALLBACK-XT @ EXECUTE
    _SRRESCB-DECISION !
    DEPTH _SRRESCB-DEPTH @ <> IF _SRRESCB-E-FALLBACK-STACK THROW THEN ;

: _SRRESCB-DELEGATE  ( -- decision )
    _SRRESCB-O @ SRRES.FALLBACK-XT @ 0= IF _SRRESCB-DEFAULT EXIT THEN
    0 _SRRESCB-THROW !
    ['] _SRRESCB-FALLBACK-CALL CATCH DUP _SRRESCB-THROW ! IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CALLBACK
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CALLBACK
        _SRRESCB-THROW @ _SRRESCB-O @ _SRRES-STATUS! DROP
        RCLIENT-DISPATCH-DROP EXIT
    THEN
    _SRRESCB-DECISION @ RCLIENT-DISPATCH-VALID? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CALLBACK
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CALLBACK
        _SRRESCB-DECISION @ _SRRESCB-O @ _SRRES-STATUS! DROP
        RCLIENT-DISPATCH-DROP EXIT
    THEN
    _SRRESCB-DECISION @ ;

: _SRRESCB-INNER  ( -- decision )
    _SRRESCB-MATCH? IF _SRRESCB-EXACT ELSE _SRRESCB-DELEGATE THEN ;

: _SRRESCB-CLAIMED
  ( frame kind lane seq expected disposition context -- decision )
    _SRRESCB-O ! _SRRESCB-DISPOSITION ! _SRRESCB-EXPECTED !
    _SRRESCB-SEQ ! _SRRESCB-LANE ! _SRRESCB-KIND ! _SRRESCB-F !
    _SRRESCB-O @ _SRRES-STRUCTURAL? 0= IF _SRRESCB-DEFAULT EXIT THEN
    _SRRESCB-O @ SRRES.BUSY @ IF _SRRESCB-DEFAULT EXIT THEN
    -1 _SRRESCB-O @ SRRES.BUSY !
    ['] _SRRESCB-INNER CATCH DUP IF
        _SRRESCB-THROW !
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CALLBACK
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CALLBACK
        _SRRESCB-THROW @ _SRRESCB-O @ _SRRES-STATUS! DROP
        _SRRESCB-DEFAULT
    ELSE
        DROP
    THEN
    >R 0 _SRRESCB-O @ SRRES.BUSY ! R> ;

: STREAMS-RABBIT-REMOTE-RESOURCE-POLL-CALLBACK
  ( frame kind lane seq expected disposition context -- decision )
    _srres-guard GUARD-MINE? IF _SRRESCB-DEFAULT-FROM-STACK EXIT THEN
    _srres-guard GUARD-TRY-ACQUIRE 0= IF
        _SRRESCB-DEFAULT-FROM-STACK EXIT
    THEN
    ['] _SRRESCB-CLAIMED CATCH
    _srres-guard GUARD-RELEASE
    DUP IF
        DROP
        DUP _SRRES-HEADER? IF 0 OVER SRRES.BUSY ! THEN
        _SRRESCB-DEFAULT-FROM-STACK EXIT
    THEN
    DROP ;

\ =====================================================================
\ Post-poll decode, validation, release, and cache publication
\ =====================================================================

VARIABLE _SRRESC-ITEM
VARIABLE _SRRESC-SUBJECT
VARIABLE _SRRESC-GEN
VARIABLE _SRRESC-CS
VARIABLE _SRRESC-O
VARIABLE _SRRESC-STATE
VARIABLE _SRRESC-OP-STATUS
VARIABLE _SRRESC-REQUIRED
VARIABLE _SRRESC-CALLBACK-BYTES
VARIABLE _SRRESC-CODE
VARIABLE _SRRESC-A
VARIABLE _SRRESC-U
VARIABLE _SRRESC-RS
VARIABLE _SRRESC-VALIDATOR-STATUS
VARIABLE _SRRESC-VALIDATOR-THROW
VARIABLE _SRRESC-DEPTH
VARIABLE _SRRESC-CHANGED
VARIABLE _SRRESC-BUSY

-271 CONSTANT _SRRESC-E-VALIDATOR-STACK

: _SRRESC-VALIDATOR-CALL  ( -- )
    DEPTH _SRRESC-DEPTH !
    _SRRESC-O @ SRRES.STAGING _SRRESC-O @
    _SRRESC-O @ SRRES.VALIDATOR-CONTEXT @
    _SRRESC-O @ SRRES.VALIDATOR-XT @ EXECUTE
    _SRRESC-VALIDATOR-STATUS !
    DEPTH _SRRESC-DEPTH @ <> IF _SRRESC-E-VALIDATOR-STACK THROW THEN ;

: _SRRESC-VALIDATE  ( -- status )
    _SRRESC-O @ SRRES.VALIDATOR-XT @ 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK EXIT
    THEN
    0 _SRRESC-VALIDATOR-THROW !
    ['] _SRRESC-VALIDATOR-CALL CATCH
        DUP _SRRESC-VALIDATOR-THROW ! IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CALLBACK
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CALLBACK
        _SRRESC-VALIDATOR-THROW @ _SRRESC-O @ _SRRES-ATTEMPT! EXIT
    THEN
    _SRRESC-VALIDATOR-STATUS @ IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-PROFILE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-VALIDATOR
        _SRRESC-VALIDATOR-STATUS @ _SRRESC-O @ _SRRES-ATTEMPT! EXIT
    THEN
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: _SRRESC-DECODE  ( -- )
    _SRRESC-O @ SRRES.ATTEMPT-STATUS @
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK <> IF EXIT THEN
    _SRRESC-A @ _SRRESC-U @ _SRRESC-O @ SRRES.SCHEMA @
        CS-SCHEMA-GRAPH-SPAN-OVERLAP? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-ALIAS
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-SCHEMA 0
        _SRRESC-O @ _SRRES-ATTEMPT! DROP EXIT
    THEN
    _SRRESC-A @ _SRRESC-U @ _SRRESC-O @ SRRES.SCHEMA @
        _SRRESC-O @ SRRES.STAGING IVJSON-DECODE-AS DUP IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CODEC
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CODEC ROT
        _SRRESC-O @ _SRRES-ATTEMPT! DROP EXIT
    THEN
    DROP
    _SRRESC-VALIDATE STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = IF
        -1 _SRRESC-O @ SRRES.CANDIDATE-READY !
    THEN ;

: _SRRESC-ACCESS  ( -- )
    _SRRESC-O @ SRRES.RESPONSE-BYTES @ _SRRESC-CALLBACK-BYTES !
    _SRRESC-O @ SRRES.OPERATION @
    _SRRESC-O @ SRRES.OPERATION-GENERATION @
    _SRRESC-O @ SRRES.ATTACHMENT-GENERATION @
    _SRRESC-O @ SRRES.CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-OP-STATE@
        _SRRESC-CS ! _SRRESC-OP-STATUS ! _SRRESC-STATE !
    _SRRESC-CS @ STREAMS-RABBIT-CONNECTOR-S-OK <> IF
        _SRRESC-CS @ _SRRESC-O @ _SRRES-CONNECTOR-ATTEMPT! DROP EXIT
    THEN
    _SRRESC-O @ SRRES.OPERATION @
    _SRRESC-O @ SRRES.OPERATION-GENERATION @
    _SRRESC-O @ SRRES.ATTACHMENT-GENERATION @
    _SRRESC-O @ SRRES.CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-OP-REQUIRED@
        _SRRESC-CS ! _SRRESC-REQUIRED !
    _SRRESC-CS @ STREAMS-RABBIT-CONNECTOR-S-OK <> IF
        _SRRESC-CS @ _SRRESC-O @ _SRRES-CONNECTOR-ATTEMPT! DROP EXIT
    THEN
    _SRRESC-REQUIRED @ _SRRESC-O @ SRRES.RESPONSE-BYTES !
    _SRRESC-O @ SRRES.CALLBACK-SEEN @ 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-RESPONSE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-RESPONSE
        STREAMS-RABBIT-REMOTE-RESOURCE-E-CALLBACK-MISSING
        _SRRESC-O @ _SRRES-ATTEMPT! DROP
    ELSE
        _SRRESC-CALLBACK-BYTES @ _SRRESC-REQUIRED @ <> IF
            STREAMS-RABBIT-REMOTE-RESOURCE-S-RESPONSE
            STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-RESPONSE
            STREAMS-RABBIT-REMOTE-RESOURCE-E-RESULT-MISMATCH
            _SRRESC-O @ _SRRES-ATTEMPT! DROP
        THEN
    THEN
    _SRRESC-STATE @ RCLIENT-OP-FAILED = IF
        _SRRESC-OP-STATUS @ RCLIENT-S-RESULT = IF
            STREAMS-RABBIT-REMOTE-RESOURCE-S-CAPACITY
            STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CONNECTOR
            _SRRESC-REQUIRED @ _SRRESC-O @ _SRRES-ATTEMPT! DROP
        ELSE
            STREAMS-RABBIT-REMOTE-RESOURCE-S-CONNECTOR
            STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CONNECTOR
            _SRRESC-OP-STATUS @ _SRRESC-O @ _SRRES-ATTEMPT! DROP
        THEN
        EXIT
    THEN
    _SRRESC-STATE @ RCLIENT-OP-COMPLETE <>
    _SRRESC-OP-STATUS @ RCLIENT-S-OK <> OR IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CONNECTOR
        _SRRESC-OP-STATUS @ _SRRESC-O @ _SRRES-ATTEMPT! DROP EXIT
    THEN
    _SRRESC-O @ SRRES.OPERATION @
    _SRRESC-O @ SRRES.OPERATION-GENERATION @
    _SRRESC-O @ SRRES.ATTACHMENT-GENERATION @
    _SRRESC-O @ SRRES.CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-OP-RESULT@
        _SRRESC-CS ! _SRRESC-U ! _SRRESC-A ! _SRRESC-CODE !
    _SRRESC-CS @ STREAMS-RABBIT-CONNECTOR-S-OK <> IF
        _SRRESC-CS @ _SRRESC-O @ _SRRES-CONNECTOR-ATTEMPT! DROP EXIT
    THEN
    _SRRESC-CODE @ _SRRESC-O @ SRRES.RESPONSE-CODE @ <>
    _SRRESC-U @ _SRRESC-REQUIRED @ <> OR IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-RESPONSE
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-RESPONSE
        STREAMS-RABBIT-REMOTE-RESOURCE-E-RESULT-MISMATCH
        _SRRESC-O @ _SRRES-ATTEMPT! DROP EXIT
    THEN
    _SRRESC-DECODE ;

: _SRRES-PUBLISH  ( owner -- status )
    DUP _SRRESW-O !
    DUP SRRES.EVENT-STAGE-STATE @ _SRRES-EVENT-STAGE-EMPTY <> IF
        DROP STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    _SRRES-CACHE-FREE ?DUP IF
        STREAMS-RABBIT-REMOTE-RESOURCE-ST-CLEANUP _SRRESW-O @ SRRES.STATE !
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CODEC ROT
        _SRRESW-O @ _SRRES-STATUS! EXIT
    THEN
    _SRRESW-O @ SRRES.STAGING _SRRESW-O @ SRRES.CACHE CV-SIZE CMOVE
    _SRRESW-O @ SRRES.STAGING CV-INIT
    1 _SRRESW-O @ SRRES.CACHE-GENERATION +!
    -1 _SRRESW-O @ SRRES.CACHE-PRESENT !
    _SRRESW-O @ _SRRES-CLEAR-ATTEMPT-META
    STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE _SRRESW-O @ SRRES.STATE !
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-NONE 0
        _SRRESW-O @ _SRRES-STATUS! ;

VARIABLE _SRRESR-STATUS
VARIABLE _SRRESR-DOMAIN
VARIABLE _SRRESR-DETAIL

: _SRRES-FINISH-REJECTION  ( owner -- status )
    DUP _SRRESW-O !
    DUP SRRES.ATTEMPT-STATUS @ _SRRESR-STATUS !
    DUP SRRES.ATTEMPT-DOMAIN @ _SRRESR-DOMAIN !
    SRRES.ATTEMPT-DETAIL @ _SRRESR-DETAIL !
    _SRRESW-O @ _SRRES-STAGING-FREE ?DUP IF
        STREAMS-RABBIT-REMOTE-RESOURCE-ST-CLEANUP _SRRESW-O @ SRRES.STATE !
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CODEC ROT
        _SRRESW-O @ _SRRES-STATUS! EXIT
    THEN
    _SRRESW-O @ SRRES.STAGING CV-INIT
    _SRRESW-O @ _SRRES-CLEAR-ATTEMPT-META
    STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE _SRRESW-O @ SRRES.STATE !
    _SRRESR-STATUS @ _SRRESR-DOMAIN @ _SRRESR-DETAIL @
        _SRRESW-O @ _SRRES-STATUS! ;

: _SRRES-ATTACHMENT-LIVE?  ( owner -- flag )
    DUP SRRES.CONNECTOR @ STREAMS-RABBIT-CONNECTOR-STATE@
    DUP STREAMS-RABBIT-CONNECTOR-S-OK <> IF 2DROP DROP 0 EXIT THEN
    DROP STREAMS-RABBIT-CONNECTOR-ST-ATTACHED <> IF DROP 0 EXIT THEN
    DUP SRRES.CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-ATTACHMENT-GENERATION@
    DUP STREAMS-RABBIT-CONNECTOR-S-OK <> IF 2DROP DROP 0 EXIT THEN
    DROP SWAP SRRES.ATTACHMENT-GENERATION @ = ;

: _SRRESC-RELEASE  ( -- status )
    _SRRESC-O @ SRRES.OPERATION @
    _SRRESC-O @ SRRES.OPERATION-GENERATION @
    _SRRESC-O @ SRRES.ATTACHMENT-GENERATION @
    _SRRESC-O @ SRRES.CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-OP-RELEASE DUP _SRRESC-CS !
    STREAMS-RABBIT-CONNECTOR-S-OK = IF
        _SRRESC-O @ _SRRES-CLEAR-HANDLE
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK EXIT
    THEN
    _SRRESC-O @ _SRRES-ATTACHMENT-LIVE? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-DISCONNECTED
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CONNECTOR _SRRESC-CS @
        _SRRESC-O @ _SRRES-ATTEMPT! DROP
        0 _SRRESC-O @ SRRES.CANDIDATE-READY !
        _SRRESC-O @ _SRRES-CLEAR-HANDLE
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK EXIT
    THEN
    _SRRESC-CS @ _SRRESC-O @ _SRRES-CONNECTOR-ATTEMPT! DROP
    STREAMS-RABBIT-REMOTE-RESOURCE-ST-CLEANUP _SRRESC-O @ SRRES.STATE !
    STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP ;

: _SRRESC-MARK-STALE  ( -- )
    STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-GEOMETRY
    STREAMS-RABBIT-REMOTE-RESOURCE-E-GENERATION
        _SRRESC-O @ _SRRES-ATTEMPT! DROP ;

: _SRRESC-FINISH  ( -- status )
    _SRRESC-O @ SRRES.CANDIDATE-READY @ IF
        _SRRESC-O @ SRRES.CACHE-GENERATION @
        _SRRESC-O @ SRRES.FETCH-CACHE-GENERATION @ <> IF
            _SRRESC-MARK-STALE
            _SRRESC-O @ _SRRES-FINISH-REJECTION EXIT
        THEN
        _SRRESC-O @ _SRRES-PUBLISH
    ELSE
        _SRRESC-O @ _SRRES-FINISH-REJECTION
    THEN ;

: _SRRES-CONSUME  ( item subject generation connector-status owner -- )
  ( owned? changed? status )
    _SRRESC-BUSY @ IF
        2DROP 2DROP DROP
        0 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    _SRRESC-O ! _SRRESC-CS ! _SRRESC-GEN !
    _SRRESC-SUBJECT ! _SRRESC-ITEM !
    _SRRESC-O @ _SRRES-VALID? 0= IF
        0 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESC-O @ SRRES.STATE @
        STREAMS-RABBIT-REMOTE-RESOURCE-ST-FETCHING <> IF
        0 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    _SRRESC-ITEM @ RSUB-ITEM-CLIENT-OP <>
    _SRRESC-SUBJECT @ _SRRESC-O @ SRRES.OPERATION @ <> OR
    _SRRESC-GEN @ _SRRESC-O @ SRRES.OPERATION-GENERATION @ <> OR IF
        0 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-OK EXIT
    THEN
    _SRRESC-O @ SRRES.EVENT-STAGE-STATE @
        _SRRES-EVENT-STAGE-EMPTY <> IF
        -1 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    -1 _SRRESC-BUSY !
    -1 _SRRESC-O @ SRRES.BUSY !
    0 _SRRESC-O @ SRRES.CANDIDATE-READY !
    _SRRESC-O @ SRRES.CACHE-GENERATION @
    _SRRESC-O @ SRRES.FETCH-CACHE-GENERATION @ <> IF
        _SRRESC-MARK-STALE
    ELSE
        _SRRESC-ACCESS
    THEN
    _SRRESC-RELEASE STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP = IF
        0 _SRRESC-O @ SRRES.BUSY !
        0 _SRRESC-BUSY !
        -1 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP EXIT
    THEN
    _SRRESC-FINISH _SRRESC-RS !
    _SRRESC-O @ SRRES.CACHE-GENERATION @
    _SRRESC-O @ SRRES.CACHE-PRESENT @ AND 0<> _SRRESC-CHANGED !
    _SRRESC-RS @ STREAMS-RABBIT-REMOTE-RESOURCE-S-OK <> IF
        0 _SRRESC-CHANGED !
    THEN
    0 _SRRESC-O @ SRRES.BUSY !
    0 _SRRESC-BUSY !
    -1 _SRRESC-CHANGED @ _SRRESC-RS @ ;

: STREAMS-RABBIT-REMOTE-RESOURCE-CONSUME
  ( item subject generation connector-status owner -- owned? changed? status )
    ['] _SRRES-CONSUME _srres-guard WITH-GUARD ;

\ =====================================================================
\ Retryable cleanup, abandonment, and finalization
\ =====================================================================

: _SRRES-CLEANUP  ( owner -- changed? status )
    _SRRESC-BUSY @ IF
        DROP 0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    DUP _SRRESC-O !
    _SRRESC-O @ _SRRES-STRUCTURAL? 0= IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESC-O @ SRRES.BUSY @ IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    _SRRESC-O @ SRRES.EVENT-STAGE-STATE @
        _SRRES-EVENT-STAGE-EMPTY <> IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    _SRRESC-O @ SRRES.STATE @
        STREAMS-RABBIT-REMOTE-RESOURCE-ST-CLEANUP <> IF
        0 STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    -1 _SRRESC-O @ SRRES.BUSY !
    _SRRESC-O @ SRRES.OPERATION @ IF
        _SRRESC-RELEASE STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP = IF
            0 _SRRESC-O @ SRRES.BUSY !
            0 STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP EXIT
        THEN
    THEN
    _SRRESC-O @ SRRES.CANDIDATE-READY @ _SRRESC-CHANGED !
    _SRRESC-FINISH _SRRESC-RS !
    _SRRESC-RS @ STREAMS-RABBIT-REMOTE-RESOURCE-S-OK <> IF
        0 _SRRESC-CHANGED !
    THEN
    0 _SRRESC-O @ SRRES.BUSY !
    _SRRESC-CHANGED @ _SRRESC-RS @ ;

: STREAMS-RABBIT-REMOTE-RESOURCE-CLEANUP  ( owner -- changed? status )
    ['] _SRRES-CLEANUP _srres-guard WITH-GUARD ;

: _SRRES-ABANDON  ( owner -- status )
    _SRRESC-BUSY @ IF
        DROP STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    DUP _SRRESC-O !
    _SRRESC-O @ _SRRES-STRUCTURAL? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESC-O @ SRRES.BUSY @ IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    _SRRESC-O @ SRRES.EVENT-STAGE-STATE @
        _SRRES-EVENT-STAGE-EMPTY <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    _SRRESC-O @ SRRES.STATE @ STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE = IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    _SRRESC-O @ _SRRES-ATTACHMENT-LIVE? IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    -1 _SRRESC-O @ SRRES.BUSY !
    STREAMS-RABBIT-REMOTE-RESOURCE-S-DISCONNECTED
    STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CONNECTOR
    STREAMS-RABBIT-CONNECTOR-S-DISCONNECTED
        _SRRESC-O @ _SRRES-ATTEMPT! DROP
    0 _SRRESC-O @ SRRES.CANDIDATE-READY !
    _SRRESC-O @ _SRRES-CLEAR-HANDLE
    _SRRESC-O @ _SRRES-FINISH-REJECTION _SRRESC-RS !
    0 _SRRESC-O @ SRRES.BUSY !
    _SRRESC-RS @ ;

: STREAMS-RABBIT-REMOTE-RESOURCE-ABANDON  ( owner -- status )
    ['] _SRRES-ABANDON _srres-guard WITH-GUARD ;

: _SRRES-FINI-FREE  ( -- )
    _SRRESW-O @ SRRES.STAGING CV-FREE
    _SRRESW-O @ SRRES.CACHE CV-FREE ;

: _SRRES-FINI  ( owner -- status )
    _SRRESW-O !
    _SRRESW-O @ _SRRES-STRUCTURAL? 0= IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-INVALID EXIT
    THEN
    _SRRESW-O @ SRRES.BUSY @ IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-BUSY EXIT
    THEN
    _SRRESW-O @ SRRES.EVENT-STAGE-STATE @
        _SRRES-EVENT-STAGE-EMPTY <> IF
        STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT
    THEN
    _SRRESW-O @ SRRES.STATE @ STREAMS-RABBIT-REMOTE-RESOURCE-ST-IDLE <>
        IF STREAMS-RABBIT-REMOTE-RESOURCE-S-STATE EXIT THEN
    -1 _SRRESW-O @ SRRES.BUSY !
    ['] _SRRES-FINI-FREE CATCH ?DUP IF
        0 _SRRESW-O @ SRRES.BUSY !
        STREAMS-RABBIT-REMOTE-RESOURCE-S-CLEANUP
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-CODEC ROT
        _SRRESW-O @ _SRRES-STATUS! EXIT
    THEN
    _SRRESW-O @ SRRES.SELECTOR-A @
        _SRRESW-O @ SRRES.SELECTOR-CAP @ 0 FILL
    _SRRESW-O @ SRRES.TXN-A @ _SRRESW-O @ SRRES.TXN-CAP @ 0 FILL
    _SRRESW-O @ STREAMS-RABBIT-REMOTE-RESOURCE-SIZE 0 FILL
    STREAMS-RABBIT-REMOTE-RESOURCE-S-OK ;

: STREAMS-RABBIT-REMOTE-RESOURCE-FINI  ( owner -- status )
    ['] _SRRES-FINI _srres-guard WITH-GUARD ;
