\ =====================================================================
\ rabbit-facet-mount.f - exact Rabbit routes onto Practice facets
\ =====================================================================
\ One caller-owned mount binds one exact read-only Rabbit request kind and
\ selector to one exact local observe capability.  INIT registers the mount
\ as a borrowed handler context in a BUILDING neutral router.  The router
\ copies the verb and selector and must be sealed before any server can use
\ the mount.  Mutating dispatch remains out of scope until Rabbit idempotency
\ and committed-result semantics can make post-commit response failure safe.
\
\ The Burrow host is intentionally only future storage at mount construction:
\ its INIT requires that same router to be sealed.  Request handling is the
\ publication gate.  It succeeds only inside the host's dynamic callback
\ scope, where ACTIVE-BINDING@ resolves the exact admitted peer token to the
\ currently driven neutral owner, peer evidence, and Practice facet.
\
\ A facet is selection metadata, never authority.  Every request revalidates
\ the exact target generation, capability pointer, effects, invocation and
\ disclosure flags, then calls an injected authorizer.  Missing, throwing, or
\ malformed authorizers deny.  Only an explicit allow stamps the request as a
\ component principal and approved before synchronous CBUS-DISPATCH.
\
\ Input and output are ordinary schema-constrained IVJSON.  The mount owns an
\ inline reusable CBR plus an exclusive caller-provided JSON scratch arena.
\ The response builder copies successful output before the complete scratch
\ arena is wiped.  No selector, response, or application capacity is fixed by
\ this module.
\
\ The neutral Rabbit and interoperability codecs still use serialized
\ synchronous scratch.  The hosted Burrow scheduler provides the normal
\ serialization boundary; a module guard also refuses handler reentry before
\ any callback scratch is replaced.
\ =====================================================================

PROVIDED akashic-streams-rfmount

REQUIRE rabbit-burrow.f
REQUIRE ../../../interop/request-bus.f
REQUIRE ../../../interop/capability-facet.f
REQUIRE ../../../interop/codecs/json-value.f
REQUIRE ../../../net/rabbit/router.f
REQUIRE ../../../utils/memory-span.f
REQUIRE ../../../utils/string.f
REQUIRE ../../../concurrency/guard.f

\ =====================================================================
\ Closed public vocabularies
\ =====================================================================

0  CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-OK
1  CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-INVALID
2  CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-STATE
3  CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-BUSY
4  CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-ALIAS
5  CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-ROUTER
6  CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-PEER
7  CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-FACET
8  CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-DENIED
9  CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-MESSAGE
10 CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-CODEC
11 CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-BUS
12 CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-RESPONSE
13 CONSTANT STREAMS-RABBIT-FACET-MOUNT-S-CALLBACK

1 CONSTANT STREAMS-RABBIT-FACET-MOUNT-ST-BOUND

0 CONSTANT STREAMS-RABBIT-FACET-MOUNT-AUTH-DENY
1 CONSTANT STREAMS-RABBIT-FACET-MOUNT-AUTH-ALLOW

0 CONSTANT STREAMS-RABBIT-FACET-MOUNT-DETAIL-NONE
1 CONSTANT STREAMS-RABBIT-FACET-MOUNT-DETAIL-ROUTER
2 CONSTANT STREAMS-RABBIT-FACET-MOUNT-DETAIL-BURROW
3 CONSTANT STREAMS-RABBIT-FACET-MOUNT-DETAIL-SERVER
4 CONSTANT STREAMS-RABBIT-FACET-MOUNT-DETAIL-MESSAGE
5 CONSTANT STREAMS-RABBIT-FACET-MOUNT-DETAIL-IVJSON
6 CONSTANT STREAMS-RABBIT-FACET-MOUNT-DETAIL-CBUS
7 CONSTANT STREAMS-RABBIT-FACET-MOUNT-DETAIL-BUILDER
8 CONSTANT STREAMS-RABBIT-FACET-MOUNT-DETAIL-AUTHORIZER
9 CONSTANT STREAMS-RABBIT-FACET-MOUNT-DETAIL-DISCLOSURE

: STREAMS-RABBIT-FACET-MOUNT-STATUS-VALID?  ( status -- flag )
    DUP STREAMS-RABBIT-FACET-MOUNT-S-OK >=
    SWAP STREAMS-RABBIT-FACET-MOUNT-S-CALLBACK <= AND ;

: STREAMS-RABBIT-FACET-MOUNT-AUTH-VALID?  ( decision -- flag )
    DUP STREAMS-RABBIT-FACET-MOUNT-AUTH-DENY =
    SWAP STREAMS-RABBIT-FACET-MOUNT-AUTH-ALLOW = OR ;

\ =====================================================================
\ Caller-owned mount descriptor
\ =====================================================================

0x5352464D4F554E31 CONSTANT _SRFM-MAGIC-VALUE  \ "SRFMOUN1"
1                  CONSTANT _SRFM-ABI-VERSION

  0 CONSTANT _SRFM-MAGIC
  8 CONSTANT _SRFM-ABI
 16 CONSTANT _SRFM-BYTES
 24 CONSTANT _SRFM-STATE
 32 CONSTANT _SRFM-KIND
 40 CONSTANT _SRFM-ROUTE-INDEX
 48 CONSTANT _SRFM-ROUTER
 56 CONSTANT _SRFM-BUS
 64 CONSTANT _SRFM-BURROW
 72 CONSTANT _SRFM-CALLER-ID
 80 CONSTANT _SRFM-CALLER-GEN
 88 CONSTANT _SRFM-TARGET-ID
 96 CONSTANT _SRFM-TARGET-GEN
104 CONSTANT _SRFM-CAP
112 CONSTANT _SRFM-AUTH-XT
120 CONSTANT _SRFM-AUTH-CONTEXT
128 CONSTANT _SRFM-JSON-A
136 CONSTANT _SRFM-JSON-CAP
144 CONSTANT _SRFM-BUSY
152 CONSTANT _SRFM-LAST-STATUS
160 CONSTANT _SRFM-DETAIL-DOMAIN
168 CONSTANT _SRFM-DETAIL-STATUS
176 CONSTANT _SRFM-RESOURCE-ID          \ RID-SIZE bytes
208 CONSTANT _SRFM-REQUEST              \ inline CBR-SIZE bytes
720 CONSTANT STREAMS-RABBIT-FACET-MOUNT-SIZE

: SRFM.MAGIC          ( mount -- field ) _SRFM-MAGIC + ;
: SRFM.ABI            ( mount -- field ) _SRFM-ABI + ;
: SRFM.BYTES          ( mount -- field ) _SRFM-BYTES + ;
: SRFM.STATE          ( mount -- field ) _SRFM-STATE + ;
: SRFM.KIND           ( mount -- field ) _SRFM-KIND + ;
: SRFM.ROUTE-INDEX    ( mount -- field ) _SRFM-ROUTE-INDEX + ;
: SRFM.ROUTER         ( mount -- field ) _SRFM-ROUTER + ;
: SRFM.BUS            ( mount -- field ) _SRFM-BUS + ;
: SRFM.BURROW         ( mount -- field ) _SRFM-BURROW + ;
: SRFM.CALLER-ID      ( mount -- field ) _SRFM-CALLER-ID + ;
: SRFM.CALLER-GEN     ( mount -- field ) _SRFM-CALLER-GEN + ;
: SRFM.TARGET-ID      ( mount -- field ) _SRFM-TARGET-ID + ;
: SRFM.TARGET-GEN     ( mount -- field ) _SRFM-TARGET-GEN + ;
: SRFM.CAP            ( mount -- field ) _SRFM-CAP + ;
: SRFM.AUTH-XT        ( mount -- field ) _SRFM-AUTH-XT + ;
: SRFM.AUTH-CONTEXT   ( mount -- field ) _SRFM-AUTH-CONTEXT + ;
: SRFM.JSON-A         ( mount -- field ) _SRFM-JSON-A + ;
: SRFM.JSON-CAP       ( mount -- field ) _SRFM-JSON-CAP + ;
: SRFM.BUSY           ( mount -- field ) _SRFM-BUSY + ;
: SRFM.LAST-STATUS    ( mount -- field ) _SRFM-LAST-STATUS + ;
: SRFM.DETAIL-DOMAIN  ( mount -- field ) _SRFM-DETAIL-DOMAIN + ;
: SRFM.DETAIL-STATUS  ( mount -- field ) _SRFM-DETAIL-STATUS + ;
: SRFM.RESOURCE-ID    ( mount -- rid ) _SRFM-RESOURCE-ID + ;
: SRFM.REQUEST        ( mount -- request ) _SRFM-REQUEST + ;

DEFER _SRFM-HANDLE-BODY

GUARD _SRFM-GUARD

: STREAMS-RABBIT-FACET-MOUNT-HANDLE
  ( frame kind peer-token builder mount -- outcome )
    _SRFM-HANDLE-BODY ;

\ =====================================================================
\ Descriptor and route validation
\ =====================================================================

: _SRFM-KIND>VERB$  ( kind -- address length flag )
    DUP RMSG-KIND-LIST = IF DROP S" LIST" -1 EXIT THEN
    DUP RMSG-KIND-DESCRIBE = IF DROP S" DESCRIBE" -1 EXIT THEN
    DUP RMSG-KIND-FETCH = IF DROP S" FETCH" -1 EXIT THEN
    DUP RMSG-KIND-SEARCH = IF DROP S" SEARCH" -1 EXIT THEN
    DUP RMSG-KIND-PUBLISH = IF DROP S" PUBLISH" -1 EXIT THEN
    DUP RMSG-KIND-DELEGATE = IF DROP S" DELEGATE" -1 EXIT THEN
    RMSG-KIND-OFFER = IF S" OFFER" -1 EXIT THEN
    0 0 0 ;

: _SRFM-OBSERVE-KIND?  ( kind -- flag )
    DUP RMSG-KIND-LIST = IF DROP -1 EXIT THEN
    DUP RMSG-KIND-DESCRIBE = IF DROP -1 EXIT THEN
    DUP RMSG-KIND-FETCH = IF DROP -1 EXIT THEN
    RMSG-KIND-SEARCH = ;

VARIABLE _SRFMV-M
VARIABLE _SRFMV-ROUTER
VARIABLE _SRFMV-INDEX
VARIABLE _SRFMV-XT
VARIABLE _SRFMV-CONTEXT
VARIABLE _SRFMV-FLAG
VARIABLE _SRFMV-INST
VARIABLE _SRFMV-CAP
VARIABLE _SRFMV-REGISTRY

: _SRFM-REGISTRY-GEOMETRY?  ( registry -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP CREG-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    _SRFMV-REGISTRY !
    _SRFMV-REGISTRY @ CREG.TYPE-N @ DUP 0<
    SWAP CREG-MAX-TYPES > OR IF 0 EXIT THEN
    _SRFMV-REGISTRY @ CREG.INST-N @ DUP 0<
    SWAP CREG-MAX-INSTANCES > OR 0= ;

: _SRFM-BUS-GEOMETRY?  ( bus -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP CBUS-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    CBUS.REGISTRY @ _SRFM-REGISTRY-GEOMETRY? ;

: _SRFM-CAP-GEOMETRY?  ( cap -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP CAP-DESC MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    CAP-DESC-VALID? ;

: _SRFM-BINDING-VALID?  ( mount -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP STREAMS-RABBIT-FACET-MOUNT-SIZE MSPAN-NONWRAPPING? 0= IF
        DROP 0 EXIT
    THEN
    _SRFMV-M !
    _SRFMV-M @ SRFM.MAGIC @ _SRFM-MAGIC-VALUE <> IF 0 EXIT THEN
    _SRFMV-M @ SRFM.ABI @ _SRFM-ABI-VERSION <> IF 0 EXIT THEN
    _SRFMV-M @ SRFM.BYTES @ STREAMS-RABBIT-FACET-MOUNT-SIZE <> IF
        0 EXIT
    THEN
    _SRFMV-M @ SRFM.STATE @
        STREAMS-RABBIT-FACET-MOUNT-ST-BOUND <> IF 0 EXIT THEN
    _SRFMV-M @ SRFM.KIND @ _SRFM-KIND>VERB$ 0= IF
        2DROP 0 EXIT
    THEN
    2DROP
    _SRFMV-M @ SRFM.ROUTE-INDEX @ 0< IF 0 EXIT THEN
    _SRFMV-M @ SRFM.ROUTER @ 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.BUS @ DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    CBUS-SIZE MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.BURROW @ DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    STREAMS-RABBIT-BURROW-SIZE MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.BURROW @ STREAMS-RABBIT-BURROW-SIZE
        _SRFMV-M @ STREAMS-RABBIT-FACET-MOUNT-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRFMV-M @ SRFM.CALLER-ID @ 0> 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.CALLER-GEN @ 0> 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.TARGET-ID @ 0> 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.TARGET-GEN @ 0> 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.CAP @ DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    CAP-DESC MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.JSON-CAP @ 0> 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.JSON-A @ DUP 0= IF DROP 0 EXIT THEN
    _SRFMV-M @ SRFM.JSON-CAP @ MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.BURROW @ STREAMS-RABBIT-BURROW-SIZE
        _SRFMV-M @ SRFM.JSON-A @ _SRFMV-M @ SRFM.JSON-CAP @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRFMV-M @ SRFM.BUS @ CBUS-SIZE
        _SRFMV-M @ STREAMS-RABBIT-FACET-MOUNT-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRFMV-M @ SRFM.BUS @ CBUS-SIZE
        _SRFMV-M @ SRFM.JSON-A @ _SRFMV-M @ SRFM.JSON-CAP @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRFMV-M @ SRFM.BUS @ CBUS-SIZE
        _SRFMV-M @ SRFM.BURROW @ STREAMS-RABBIT-BURROW-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRFMV-M @ SRFM.CAP @ CAP-DESC
        _SRFMV-M @ STREAMS-RABBIT-FACET-MOUNT-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRFMV-M @ SRFM.CAP @ CAP-DESC
        _SRFMV-M @ SRFM.JSON-A @ _SRFMV-M @ SRFM.JSON-CAP @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRFMV-M @ SRFM.CAP @ CAP-DESC
        _SRFMV-M @ SRFM.BURROW @ STREAMS-RABBIT-BURROW-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRFMV-M @ SRFM.BUSY @ DUP 0= SWAP -1 = OR 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.LAST-STATUS @
        STREAMS-RABBIT-FACET-MOUNT-STATUS-VALID? 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.JSON-A @ _SRFMV-M @ SRFM.JSON-CAP @
        _SRFMV-M @ STREAMS-RABBIT-FACET-MOUNT-SIZE MSPAN-OVERLAP? 0= ;

: STREAMS-RABBIT-FACET-MOUNT-BINDING-VALID?  ( mount -- flag )
    ['] _SRFM-BINDING-VALID? _SRFM-GUARD WITH-GUARD ;

: _SRFM-ROUTE-BOUND?  ( mount -- flag )
    DUP _SRFMV-M ! SRFM.ROUTER @ DUP _SRFMV-ROUTER !
    RROUTER-VALID? 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.ROUTE-INDEX @ DUP _SRFMV-INDEX !
    _SRFMV-ROUTER @ RROUTER-HANDLER@
    _SRFMV-FLAG ! _SRFMV-CONTEXT ! _SRFMV-XT !
    _SRFMV-FLAG @ 0= IF 0 EXIT THEN
    _SRFMV-XT @ ['] STREAMS-RABBIT-FACET-MOUNT-HANDLE =
    _SRFMV-CONTEXT @ _SRFMV-M @ = AND ;

: _SRFM-TARGET-CAP?  ( mount -- instance|0 )
    _SRFMV-M !
    _SRFMV-M @ SRFM.BUS @ DUP _SRFM-BUS-GEOMETRY? 0= IF
        DROP 0 EXIT
    THEN
    CBUS.REGISTRY @
    _SRFMV-M @ SRFM.TARGET-ID @ _SRFMV-M @ SRFM.TARGET-GEN @
    ROT CREG-INST-FIND DUP 0= IF EXIT THEN _SRFMV-INST !
    _SRFMV-M @ SRFM.CAP @ DUP _SRFMV-CAP !
    _SRFM-CAP-GEOMETRY? 0= IF 0 EXIT THEN
    _SRFMV-CAP @ CAP-ID _SRFMV-INST @ CINST-DESC COMP-CAP-FIND
    _SRFMV-CAP @ <> IF 0 EXIT THEN
    _SRFMV-INST @ ;

: _SRFM-VALID?  ( mount -- flag )
    DUP STREAMS-RABBIT-FACET-MOUNT-BINDING-VALID? 0= IF
        DROP 0 EXIT
    THEN
    DUP _SRFMV-M ! _SRFM-ROUTE-BOUND? 0= IF 0 EXIT THEN
    _SRFMV-M @ _SRFM-TARGET-CAP? 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.KIND @ _SRFM-OBSERVE-KIND? 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.CAP @ DUP CAP.EFFECTS @ CAP-E-OBSERVE <> IF
        DROP 0 EXIT
    THEN
    DUP CAP.HANDLER-XT @ 0= IF DROP 0 EXIT THEN
    DUP CAP.IN-SCHEMA @ ?DUP 0= IF
        DROP 0 EXIT
    THEN
    IVJSON-SCHEMA-COMPATIBLE? 0= IF DROP 0 EXIT THEN
    CAP.OUT-SCHEMA @ ?DUP 0= IF 0 EXIT THEN
    IVJSON-SCHEMA-COMPATIBLE? 0= IF 0 EXIT THEN
    _SRFMV-M @ SRFM.BURROW @ DUP
        STREAMS-RABBIT-BURROW-VALID? 0= IF DROP 0 EXIT THEN
    SRBUR.ROUTER @ _SRFMV-M @ SRFM.ROUTER @ = ;

: STREAMS-RABBIT-FACET-MOUNT-VALID?  ( mount -- flag )
    ['] _SRFM-VALID? _SRFM-GUARD WITH-GUARD ;

VARIABLE _SRFMS-M
VARIABLE _SRFMS-STATUS
VARIABLE _SRFMS-DOMAIN
VARIABLE _SRFMS-DETAIL

: _SRFM-STATUS!  ( status detail-domain detail-status mount -- status )
    _SRFMS-M ! _SRFMS-DETAIL ! _SRFMS-DOMAIN ! _SRFMS-STATUS !
    _SRFMS-STATUS @ _SRFMS-M @ SRFM.LAST-STATUS !
    _SRFMS-DOMAIN @ _SRFMS-M @ SRFM.DETAIL-DOMAIN !
    _SRFMS-DETAIL @ _SRFMS-M @ SRFM.DETAIL-STATUS !
    _SRFMS-STATUS @ ;

: _SRFM-LAST@
  ( mount -- last-status detail-domain detail-status status )
    DUP STREAMS-RABBIT-FACET-MOUNT-BINDING-VALID? 0= IF
        DROP 0 0 0 STREAMS-RABBIT-FACET-MOUNT-S-INVALID EXIT
    THEN
    DUP SRFM.LAST-STATUS @ OVER SRFM.DETAIL-DOMAIN @
    ROT SRFM.DETAIL-STATUS @ STREAMS-RABBIT-FACET-MOUNT-S-OK ;

: STREAMS-RABBIT-FACET-MOUNT-LAST@
  ( mount -- last-status detail-domain detail-status status )
    ['] _SRFM-LAST@ _SRFM-GUARD WITH-GUARD ;

: _SRFM-ROUTE@
  ( mount -- kind router route-index status )
    DUP STREAMS-RABBIT-FACET-MOUNT-BINDING-VALID? 0= IF
        DROP 0 0 0 STREAMS-RABBIT-FACET-MOUNT-S-INVALID EXIT
    THEN
    DUP SRFM.KIND @ OVER SRFM.ROUTER @ ROT SRFM.ROUTE-INDEX @
    STREAMS-RABBIT-FACET-MOUNT-S-OK ;

: STREAMS-RABBIT-FACET-MOUNT-ROUTE@
  ( mount -- kind router route-index status )
    ['] _SRFM-ROUTE@ _SRFM-GUARD WITH-GUARD ;

\ =====================================================================
\ Request and callback cleanup
\ =====================================================================

VARIABLE _SRFMH-MOUNT-CLAIMED

: _SRFM-REQUEST-CLEAR  ( mount -- )
    DUP SRFM.REQUEST DUP CBR.ARGS CV-FREE
    DUP CBR.RESULT CV-FREE
    DUP CBR.TURN @ ?DUP IF
        DUP PTURN-SIZE 0 FILL FREE
    THEN
    CBR-SIZE 0 FILL DROP ;

: _SRFM-JSON-CLEAR  ( mount -- )
    DUP SRFM.JSON-A @ SWAP SRFM.JSON-CAP @ 0 FILL ;

\ =====================================================================
\ Handler scratch and exact active route checks
\ =====================================================================

VARIABLE _SRFMH-FRAME
VARIABLE _SRFMH-KIND
VARIABLE _SRFMH-TOKEN
VARIABLE _SRFMH-BUILDER
VARIABLE _SRFMH-MOUNT
VARIABLE _SRFMH-OWNER
VARIABLE _SRFMH-EVIDENCE
VARIABLE _SRFMH-FACET
VARIABLE _SRFMH-ENTRY
VARIABLE _SRFMH-CALLER-INST
VARIABLE _SRFMH-INST
VARIABLE _SRFMH-LANE
VARIABLE _SRFMH-TXN-A
VARIABLE _SRFMH-TXN-U
VARIABLE _SRFMH-PRESENT
VARIABLE _SRFMH-STATUS
VARIABLE _SRFMH-OUTCOME
VARIABLE _SRFMH-A
VARIABLE _SRFMH-U
VARIABLE _SRFMH-JSON-A
VARIABLE _SRFMH-JSON-CAP
VARIABLE _SRFMH-JSON-U
VARIABLE _SRFMH-CODE
VARIABLE _SRFMH-LABEL-A
VARIABLE _SRFMH-LABEL-U
VARIABLE _SRFMH-AUTH-DECISION
VARIABLE _SRFMH-AUTH-DEPTH
VARIABLE _SRFMH-BURROW-BYTES

-260 CONSTANT _SRFM-AUTH-E-STACK

: _SRFMH-FAIL  ( mount-status detail-domain detail-status -- )
    _SRFMH-MOUNT @ _SRFM-STATUS! DROP
    RSERVER-HANDLER-FAILED _SRFMH-OUTCOME ! ;

: _SRFMH-DENY  ( mount-status detail-domain detail-status -- )
    _SRFMH-MOUNT @ _SRFM-STATUS! DROP
    RSERVER-HANDLER-DENY _SRFMH-OUTCOME ! ;

: _SRFMH-CORRELATION?  ( -- flag )
    _SRFMH-FRAME @ RMSG-LANE@
    _SRFMH-STATUS ! _SRFMH-PRESENT ! _SRFMH-LANE !
    _SRFMH-STATUS @ RMSG-S-OK <> IF 0 EXIT THEN
    _SRFMH-PRESENT @ 0= IF 0 EXIT THEN
    _SRFMH-LANE @ 0= IF 0 EXIT THEN
    _SRFMH-FRAME @ RMSG-TXN$
    _SRFMH-STATUS ! _SRFMH-PRESENT !
    _SRFMH-TXN-U ! _SRFMH-TXN-A !
    _SRFMH-STATUS @ RMSG-S-OK <> IF 0 EXIT THEN
    _SRFMH-PRESENT @ 0<> ;

: _SRFMH-ROUTE?  ( -- flag )
    _SRFMH-MOUNT @ SRFM.ROUTER @ RROUTER-SEALED? 0= IF 0 EXIT THEN
    _SRFMH-MOUNT @ _SRFM-ROUTE-BOUND? 0= IF 0 EXIT THEN
    _SRFMH-KIND @ _SRFMH-MOUNT @ SRFM.KIND @ <> IF 0 EXIT THEN
    _SRFMH-FRAME @ RMSG-KIND@
    _SRFMH-STATUS !
    _SRFMH-STATUS @ RMSG-S-OK <> IF DROP 0 EXIT THEN
    _SRFMH-KIND @ <> IF 0 EXIT THEN
    _SRFMH-MOUNT @ SRFM.ROUTE-INDEX @
    _SRFMH-MOUNT @ SRFM.ROUTER @ RROUTER-VERB$
    _SRFMH-PRESENT ! _SRFMH-U ! _SRFMH-A !
    _SRFMH-PRESENT @ 0= IF 0 EXIT THEN
    _SRFMH-FRAME @ RBF-VERB$ _SRFMH-A @ _SRFMH-U @ STR-STR= 0= IF
        0 EXIT
    THEN
    _SRFMH-MOUNT @ SRFM.ROUTE-INDEX @
    _SRFMH-MOUNT @ SRFM.ROUTER @ RROUTER-SELECTOR$
    _SRFMH-PRESENT ! _SRFMH-U ! _SRFMH-A !
    _SRFMH-PRESENT @ 0= IF 0 EXIT THEN
    _SRFMH-FRAME @ RBF-ARGS$ _SRFMH-A @ _SRFMH-U @ STR-STR= ;

: _SRFMH-TARGET-CAP?  ( -- flag )
    _SRFMH-MOUNT @ _SRFM-TARGET-CAP? DUP _SRFMH-INST ! 0<> IF
        _SRFMH-MOUNT @ SRFM.CAP @ DUP CAP.IN-SCHEMA @ ?DUP 0= IF
            DROP 0 EXIT
        THEN
        IVJSON-SCHEMA-COMPATIBLE? 0= IF DROP 0 EXIT THEN
        CAP.OUT-SCHEMA @ ?DUP 0= IF 0 EXIT THEN
        IVJSON-SCHEMA-COMPATIBLE?
    ELSE
        0
    THEN ;

: _SRFMH-CALLER?  ( -- flag )
    _SRFMH-MOUNT @ SRFM.BUS @ DUP _SRFM-BUS-GEOMETRY? 0= IF
        DROP 0 EXIT
    THEN
    CBUS.REGISTRY @
    _SRFMH-MOUNT @ SRFM.CALLER-ID @ _SRFMH-MOUNT @ SRFM.CALLER-GEN @
    ROT CREG-INST-FIND DUP _SRFMH-CALLER-INST ! 0<> ;

: _SRFMH-WIPEABLE-ALIASES?  ( address bytes -- flag )
    2DUP _SRFMH-MOUNT @ STREAMS-RABBIT-FACET-MOUNT-SIZE
        MSPAN-OVERLAP? IF 2DROP -1 EXIT THEN
    _SRFMH-JSON-A @ _SRFMH-JSON-CAP @ MSPAN-OVERLAP? ;

: _SRFMH-ACTIVE-GEOMETRY?  ( -- flag )
    _SRFMH-MOUNT @ STREAMS-RABBIT-FACET-MOUNT-SIZE _SRFMH-OWNER @
        RABBIT-SERVER-SUBSCRIPTIONS-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _SRFMH-JSON-A @ _SRFMH-JSON-CAP @ _SRFMH-OWNER @
        RABBIT-SERVER-SUBSCRIPTIONS-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _SRFMH-FACET @ DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP CFACET-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    CFACET-SIZE _SRFMH-WIPEABLE-ALIASES? IF 0 EXIT THEN
    _SRFMH-MOUNT @ SRFM.BURROW @ SRBUR.CAPACITY @
        STREAMS-RABBIT-BURROW-PEER-BYTES DUP _SRFMH-BURROW-BYTES !
    0= IF 0 EXIT THEN
    _SRFMH-MOUNT @ SRFM.BURROW @ SRBUR.ROWS @ DUP 0= IF
        DROP 0 EXIT
    THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP _SRFMH-BURROW-BYTES @ MSPAN-NONWRAPPING? 0= IF
        DROP 0 EXIT
    THEN
    _SRFMH-BURROW-BYTES @ _SRFMH-WIPEABLE-ALIASES? 0= ;

: _SRFMH-FACET?  ( -- flag )
    _SRFMH-FACET @ CFACET-VALID? 0= IF 0 EXIT THEN
    _SRFMH-MOUNT @ SRFM.TARGET-ID @
    _SRFMH-MOUNT @ SRFM.TARGET-GEN @
    _SRFMH-MOUNT @ SRFM.CAP @ _SRFMH-FACET @ CFACET-CAP-FIND
    DUP _SRFMH-ENTRY ! 0= IF 0 EXIT THEN
    _SRFMH-MOUNT @ SRFM.CAP @ CAP.EFFECTS @
    CFENTRY-F-INVOKE CFENTRY-F-DISCLOSE-RESULT OR
    _SRFMH-ENTRY @ CFENTRY-ALLOWS? ;

\ Authorizer callback:
\   ( frame owner evidence facet entry mount context -- decision )
: _SRFMH-AUTH-CALL  ( -- )
    DEPTH _SRFMH-AUTH-DEPTH !
    _SRFMH-FRAME @ _SRFMH-OWNER @ _SRFMH-EVIDENCE @
    _SRFMH-FACET @ _SRFMH-ENTRY @ _SRFMH-MOUNT @
    _SRFMH-MOUNT @ SRFM.AUTH-CONTEXT @
    _SRFMH-MOUNT @ SRFM.AUTH-XT @ EXECUTE
    _SRFMH-AUTH-DECISION !
    DEPTH _SRFMH-AUTH-DEPTH @ <> IF _SRFM-AUTH-E-STACK THROW THEN ;

: _SRFMH-AUTHORIZED?  ( -- flag )
    STREAMS-RABBIT-FACET-MOUNT-AUTH-DENY _SRFMH-AUTH-DECISION !
    _SRFMH-MOUNT @ SRFM.AUTH-XT @ 0= IF 0 EXIT THEN
    ['] _SRFMH-AUTH-CALL CATCH DUP IF
        _SRFMH-AUTH-DECISION ! 0 EXIT
    THEN
    DROP
    _SRFMH-AUTH-DECISION @ DUP
        STREAMS-RABBIT-FACET-MOUNT-AUTH-VALID? 0= IF DROP 0 EXIT THEN
    STREAMS-RABBIT-FACET-MOUNT-AUTH-ALLOW = ;

\ =====================================================================
\ IVJSON request preparation and synchronous Desk dispatch
\ =====================================================================

: _SRFMH-VIEW?  ( -- flag )
    _SRFMH-FRAME @ RMSG-VIEW$
    _SRFMH-STATUS ! _SRFMH-PRESENT ! _SRFMH-U ! _SRFMH-A !
    _SRFMH-STATUS @ RMSG-S-OK <> IF 0 EXIT THEN
    _SRFMH-PRESENT @ 0= IF 0 EXIT THEN
    _SRFMH-A @ _SRFMH-U @ S" application/akashic-value+json" STR-STR=
    0= IF 0 EXIT THEN
    _SRFMH-FRAME @ RMSG-ACCEPT-VIEW$
    _SRFMH-STATUS ! _SRFMH-PRESENT ! _SRFMH-U ! _SRFMH-A !
    _SRFMH-STATUS @ RMSG-S-OK <> IF 0 EXIT THEN
    _SRFMH-PRESENT @ 0= IF -1 EXIT THEN
    _SRFMH-A @ _SRFMH-U @ S" application/akashic-value+json" STR-STR= ;

: _SRFMH-DECODE  ( -- ivjson-status )
    _SRFMH-FRAME @ RMSG-BODY$
    _SRFMH-STATUS ! _SRFMH-U ! _SRFMH-A !
    _SRFMH-STATUS @ RMSG-S-OK <> IF IVJSON-E-INVALID EXIT THEN
    _SRFMH-U @ 0= IF IVJSON-E-INVALID EXIT THEN
    _SRFMH-A @ _SRFMH-U @
    _SRFMH-MOUNT @ SRFM.CAP @ CAP.IN-SCHEMA @
    _SRFMH-MOUNT @ SRFM.REQUEST CBR.ARGS IVJSON-DECODE-AS ;

: _SRFMH-STAMP-REQUEST  ( -- )
    _SRFMH-MOUNT @ SRFM.REQUEST >R
    _SRFMH-MOUNT @ SRFM.CALLER-ID @ R@ CBR.CALLER-ID !
    _SRFMH-MOUNT @ SRFM.CALLER-GEN @ R@ CBR.CALLER-GEN !
    _SRFMH-MOUNT @ SRFM.TARGET-ID @ R@ CBR.TARGET-ID !
    _SRFMH-MOUNT @ SRFM.TARGET-GEN @ R@ CBR.TARGET-GEN !
    _SRFMH-MOUNT @ SRFM.CAP @ R@ CBR.CAP !
    _SRFMH-FACET @ CFACET.CONTEXT-ID @ R@ CBR.CONTEXT-ID !
    _SRFMH-FACET @ CFACET.CONTEXT-GEN @ R@ CBR.CONTEXT-GEN !
    _SRFMH-FACET @ CFACET.EPOCH @ R@ CBR.EPOCH !
    _SRFMH-FACET @ CFACET.PRACTICE-ID R@ CBR.PRACTICE-ID RID-COPY
    _SRFMH-MOUNT @ SRFM.RESOURCE-ID R@ CBR.RESOURCE-ID RID-COPY
    CPRINC-COMPONENT R@ CBR.PRINCIPAL !
    R> CBR-APPROVE ;

: _SRFMH-DISPATCH  ( -- bus-status )
    _SRFMH-MOUNT @ SRFM.REQUEST
    _SRFMH-MOUNT @ SRFM.BUS @ CBUS-DISPATCH ;

\ =====================================================================
\ Exact correlated response construction
\ =====================================================================

: _SRFMH-BEGIN-RESPONSE  ( code label-a label-u -- builder-status )
    _SRFMH-LABEL-U ! _SRFMH-LABEL-A ! _SRFMH-CODE !
    _SRFMH-CODE @ _SRFMH-LABEL-A @ _SRFMH-LABEL-U @
    _SRFMH-LANE @ _SRFMH-TXN-A @ _SRFMH-TXN-U @
    _SRFMH-BUILDER @ RMSGB-BEGIN-RESPONSE ;

: _SRFMH-BUILDER-FAIL  ( builder-status -- )
    STREAMS-RABBIT-FACET-MOUNT-S-RESPONSE
    STREAMS-RABBIT-FACET-MOUNT-DETAIL-BUILDER ROT _SRFMH-FAIL ;

: _SRFMH-BODYLESS  ( code label-a label-u -- )
    _SRFMH-BEGIN-RESPONSE DUP IF _SRFMH-BUILDER-FAIL EXIT THEN DROP
    _SRFMH-BUILDER @ RMSGB-SEAL DUP IF
        _SRFMH-BUILDER-FAIL EXIT
    THEN DROP
    RSERVER-HANDLER-RESPONSE _SRFMH-OUTCOME ! ;

: _SRFMH-SUCCESS  ( json-a json-u -- )
    _SRFMH-U ! _SRFMH-A !
    200 S" RESULT" _SRFMH-BEGIN-RESPONSE DUP IF
        _SRFMH-BUILDER-FAIL EXIT
    THEN DROP
    S" application/akashic-value+json" _SRFMH-BUILDER @ RMSGB-VIEW!
    DUP IF _SRFMH-BUILDER-FAIL EXIT THEN DROP
    _SRFMH-A @ _SRFMH-U @ _SRFMH-BUILDER @ RMSGB-BODY!
    DUP IF _SRFMH-BUILDER-FAIL EXIT THEN DROP
    _SRFMH-BUILDER @ RMSGB-SEAL DUP IF
        _SRFMH-BUILDER-FAIL EXIT
    THEN DROP
    STREAMS-RABBIT-FACET-MOUNT-S-OK
    STREAMS-RABBIT-FACET-MOUNT-DETAIL-NONE 0
    _SRFMH-MOUNT @ _SRFM-STATUS! DROP
    RSERVER-HANDLER-RESPONSE _SRFMH-OUTCOME ! ;

: _SRFMH-BUS-RESPONSE  ( bus-status -- )
    _SRFMH-STATUS !
    STREAMS-RABBIT-FACET-MOUNT-S-BUS
    STREAMS-RABBIT-FACET-MOUNT-DETAIL-CBUS _SRFMH-STATUS @
    _SRFMH-MOUNT @ _SRFM-STATUS! DROP
    _SRFMH-STATUS @ CASE
        CBUS-S-INVALID OF 400 S" BAD REQUEST" _SRFMH-BODYLESS ENDOF
        CBUS-S-NOT-FOUND OF 404 S" NOT FOUND" _SRFMH-BODYLESS ENDOF
        CBUS-S-STALE-INSTANCE OF 404 S" NOT FOUND" _SRFMH-BODYLESS ENDOF
        CBUS-S-NO-HANDLER OF 404 S" NOT FOUND" _SRFMH-BODYLESS ENDOF
        CBUS-S-STALE-REVISION OF 409 S" CONFLICT" _SRFMH-BODYLESS ENDOF
        CBUS-S-DENIED OF RSERVER-HANDLER-DENY _SRFMH-OUTCOME ! ENDOF
        CBUS-S-NEEDS-APPROVAL OF RSERVER-HANDLER-DENY _SRFMH-OUTCOME ! ENDOF
        CBUS-S-STALE-AUTHORITY OF RSERVER-HANDLER-DENY _SRFMH-OUTCOME ! ENDOF
        CBUS-S-EXPIRED-AUTHORITY OF RSERVER-HANDLER-DENY _SRFMH-OUTCOME ! ENDOF
        CBUS-S-CONSUMED-AUTHORITY OF RSERVER-HANDLER-DENY _SRFMH-OUTCOME ! ENDOF
        CBUS-S-BUSY OF 503 S" BUSY" _SRFMH-BODYLESS ENDOF
        CBUS-S-TIMEOUT OF 504 S" TIMEOUT" _SRFMH-BODYLESS ENDOF
        CBUS-S-CANCELLED OF 409 S" CANCELLED" _SRFMH-BODYLESS ENDOF
        500 S" HANDLER FAILED" _SRFMH-BODYLESS
    ENDCASE ;

: _SRFMH-ENCODE-RESULT  ( -- )
    _SRFMH-MOUNT @ SRFM.REQUEST CBR.RESULT
    _SRFMH-JSON-A @ _SRFMH-JSON-CAP @
    IVJSON-ENCODE _SRFMH-STATUS ! _SRFMH-JSON-U !
    _SRFMH-STATUS @ IF
        STREAMS-RABBIT-FACET-MOUNT-S-CODEC
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-IVJSON _SRFMH-STATUS @
        _SRFMH-FAIL EXIT
    THEN
    _SRFMH-JSON-U @ _SRFMH-ENTRY @ CFENTRY.MAX-RESULT @ U> IF
        STREAMS-RABBIT-FACET-MOUNT-S-RESPONSE
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-DISCLOSURE _SRFMH-JSON-U @
        _SRFMH-FAIL EXIT
    THEN
    _SRFMH-JSON-A @ _SRFMH-JSON-U @ _SRFMH-SUCCESS ;

\ =====================================================================
\ Handler transaction and guaranteed ordinary cleanup
\ =====================================================================

: _SRFMH-INNER  ( -- )
    _SRFMH-ROUTE? 0= IF
        STREAMS-RABBIT-FACET-MOUNT-S-ROUTER
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-ROUTER RROUTER-S-INVALID
        _SRFMH-FAIL EXIT
    THEN
    _SRFMH-CORRELATION? 0= IF
        STREAMS-RABBIT-FACET-MOUNT-S-MESSAGE
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-MESSAGE RMSG-S-REQUIRED
        _SRFMH-FAIL EXIT
    THEN
    _SRFMH-TOKEN @ _SRFMH-MOUNT @ SRFM.BURROW @
    STREAMS-RABBIT-BURROW-ACTIVE-BINDING@
    _SRFMH-STATUS ! _SRFMH-FACET ! _SRFMH-EVIDENCE ! _SRFMH-OWNER !
    _SRFMH-STATUS @ STREAMS-RABBIT-BURROW-S-OK <> IF
        STREAMS-RABBIT-FACET-MOUNT-S-PEER
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-BURROW _SRFMH-STATUS @
        _SRFMH-FAIL EXIT
    THEN
    _SRFMH-ACTIVE-GEOMETRY? 0= IF
        STREAMS-RABBIT-FACET-MOUNT-S-ALIAS
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-BURROW
        STREAMS-RABBIT-BURROW-S-ALIAS _SRFMH-FAIL EXIT
    THEN
    _SRFMH-OWNER @ RSERVSUB.SERVER @ DUP RSERVER.BUILDER @
        _SRFMH-BUILDER @ <> IF
        DROP STREAMS-RABBIT-FACET-MOUNT-S-PEER
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-SERVER RSERVER-S-INVALID
        _SRFMH-FAIL EXIT
    THEN
    RABBIT-SERVER-HELD-APP-LANE-ENSURE DUP RSERVER-S-OK <> IF
        STREAMS-RABBIT-FACET-MOUNT-S-PEER
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-SERVER ROT
        _SRFMH-FAIL EXIT
    THEN DROP
    _SRFMH-CALLER? 0= IF
        STREAMS-RABBIT-FACET-MOUNT-S-BUS
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-CBUS CBUS-S-STALE-INSTANCE
        _SRFMH-MOUNT @ _SRFM-STATUS! DROP
        404 S" NOT FOUND" _SRFMH-BODYLESS EXIT
    THEN
    _SRFMH-TARGET-CAP? 0= IF
        STREAMS-RABBIT-FACET-MOUNT-S-BUS
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-CBUS CBUS-S-STALE-INSTANCE
        _SRFMH-MOUNT @ _SRFM-STATUS! DROP
        404 S" NOT FOUND" _SRFMH-BODYLESS EXIT
    THEN
    _SRFMH-FACET? 0= IF
        STREAMS-RABBIT-FACET-MOUNT-S-FACET
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-AUTHORIZER 0
        _SRFMH-DENY EXIT
    THEN
    _SRFMH-AUTHORIZED? 0= IF
        STREAMS-RABBIT-FACET-MOUNT-S-DENIED
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-AUTHORIZER
        _SRFMH-AUTH-DECISION @ _SRFMH-DENY EXIT
    THEN
    _SRFMH-VIEW? 0= IF
        STREAMS-RABBIT-FACET-MOUNT-S-MESSAGE
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-MESSAGE RMSG-S-VALUE
        _SRFMH-MOUNT @ _SRFM-STATUS! DROP
        400 S" BAD REQUEST" _SRFMH-BODYLESS EXIT
    THEN
    _SRFMH-MOUNT @ _SRFM-REQUEST-CLEAR
    _SRFMH-DECODE DUP _SRFMH-STATUS ! IF
        STREAMS-RABBIT-FACET-MOUNT-S-CODEC
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-IVJSON _SRFMH-STATUS @
        _SRFMH-MOUNT @ _SRFM-STATUS! DROP
        _SRFMH-STATUS @ IVJSON-E-CAPACITY = IF
            413 S" PAYLOAD TOO LARGE"
        ELSE
            _SRFMH-STATUS @ IVJSON-E-NOMEM = IF
                503 S" UNAVAILABLE"
            ELSE
                400 S" BAD REQUEST"
            THEN
        THEN
        _SRFMH-BODYLESS EXIT
    THEN
    _SRFMH-STAMP-REQUEST
    _SRFMH-DISPATCH DUP CBUS-S-OK <> IF
        _SRFMH-BUS-RESPONSE EXIT
    THEN DROP
    _SRFMH-ENCODE-RESULT ;

: _SRFMH-CLEANUP  ( -- )
    _SRFMH-MOUNT @ _SRFM-REQUEST-CLEAR
    _SRFMH-JSON-A @ _SRFMH-JSON-CAP @ 0 FILL
    0 _SRFMH-MOUNT @ SRFM.BUSY !
    0 _SRFMH-MOUNT-CLAIMED ! ;

: _SRFMH-AROUND  ( -- outcome )
    RSERVER-HANDLER-FAILED _SRFMH-OUTCOME !
    ['] _SRFMH-INNER CATCH DUP IF
        STREAMS-RABBIT-FACET-MOUNT-S-CALLBACK
        STREAMS-RABBIT-FACET-MOUNT-DETAIL-NONE ROT
        _SRFMH-MOUNT @ _SRFM-STATUS! DROP
        RSERVER-HANDLER-FAILED _SRFMH-OUTCOME !
    ELSE
        DROP
    THEN
    _SRFMH-OUTCOME @ >R
    _SRFMH-CLEANUP
    R> ;

: _SRFMH-DROP-CALL  ( frame kind peer-token builder mount -- )
    2DROP 2DROP DROP ;

: _SRFM-HANDLE-CLAIMED
  ( frame kind peer-token builder mount -- outcome )
    DUP STREAMS-RABBIT-FACET-MOUNT-BINDING-VALID? 0= IF
        _SRFMH-DROP-CALL RSERVER-HANDLER-FAILED EXIT
    THEN
    DUP SRFM.BUSY @ IF
        _SRFMH-DROP-CALL RSERVER-HANDLER-FAILED EXIT
    THEN
    DUP SRFM.JSON-A @ _SRFMH-JSON-A !
    DUP SRFM.JSON-CAP @ _SRFMH-JSON-CAP !
    DUP -1 SWAP SRFM.BUSY !
    -1 _SRFMH-MOUNT-CLAIMED !
    _SRFMH-MOUNT ! _SRFMH-BUILDER ! _SRFMH-TOKEN !
    _SRFMH-KIND ! _SRFMH-FRAME !
    _SRFMH-AROUND ;

: _SRFM-HANDLE-IMPL
  ( frame kind peer-token builder mount -- outcome )
    _SRFM-GUARD GUARD-MINE? IF
        _SRFMH-DROP-CALL RSERVER-HANDLER-FAILED EXIT
    THEN
    _SRFM-GUARD GUARD-TRY-ACQUIRE 0= IF
        _SRFMH-DROP-CALL RSERVER-HANDLER-FAILED EXIT
    THEN
    0 _SRFMH-MOUNT-CLAIMED !
    ['] _SRFM-HANDLE-CLAIMED CATCH
    DUP IF
        _SRFMH-MOUNT-CLAIMED @ IF
            DUP _SRFMH-STATUS !
            _SRFMH-JSON-A @ _SRFMH-JSON-CAP @ 0 FILL
            0 _SRFMH-MOUNT @ SRFM.BUSY !
            STREAMS-RABBIT-FACET-MOUNT-S-CALLBACK
            STREAMS-RABBIT-FACET-MOUNT-DETAIL-NONE _SRFMH-STATUS @
            _SRFMH-MOUNT @ _SRFM-STATUS! DROP
            0 _SRFMH-MOUNT-CLAIMED !
        THEN
    THEN
    _SRFM-GUARD GUARD-RELEASE
    DUP IF
        DROP _SRFMH-DROP-CALL RSERVER-HANDLER-FAILED EXIT
    THEN
    DROP ;

' _SRFM-HANDLE-IMPL IS _SRFM-HANDLE-BODY

\ =====================================================================
\ Transactional route registration
\ =====================================================================

VARIABLE _SRFMI-KIND
VARIABLE _SRFMI-SELECTOR-A
VARIABLE _SRFMI-SELECTOR-U
VARIABLE _SRFMI-CALLER
VARIABLE _SRFMI-TARGET
VARIABLE _SRFMI-CAP
VARIABLE _SRFMI-RESOURCE
VARIABLE _SRFMI-BUS
VARIABLE _SRFMI-BURROW
VARIABLE _SRFMI-AUTH-XT
VARIABLE _SRFMI-AUTH-CONTEXT
VARIABLE _SRFMI-JSON-A
VARIABLE _SRFMI-JSON-CAP
VARIABLE _SRFMI-ROUTER
VARIABLE _SRFMI-MOUNT
VARIABLE _SRFMI-VERB-A
VARIABLE _SRFMI-VERB-U
VARIABLE _SRFMI-ROUTE-INDEX
VARIABLE _SRFMI-STATUS
VARIABLE _SRFMI-REGISTRY
VARIABLE _SRFMI-LIVE
VARIABLE _SRFMI-DESC
VARIABLE _SRFMI-STATE-A
VARIABLE _SRFMI-STATE-U
VARIABLE _SRFMI-CAPS-A
VARIABLE _SRFMI-CAPS-U
VARIABLE _SRFMI-OWN-A
VARIABLE _SRFMI-OWN-U
VARIABLE _SRFMI-OWN-STATUS

: _SRFMI-CINST-SPAN?  ( instance -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    COMP-INST MSPAN-NONWRAPPING? ;

: _SRFMI-LIVE-INSTANCE?  ( instance -- flag )
    DUP _SRFMI-CINST-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _SRFMI-LIVE !
    DUP CINST.ID @ 0> 0= IF DROP 0 EXIT THEN
    DUP CINST.GENERATION @ 0> 0= IF DROP 0 EXIT THEN
    DUP CINST.ID @ SWAP CINST.GENERATION @
    _SRFMI-REGISTRY @ CREG-INST-FIND _SRFMI-LIVE @ <> IF 0 EXIT THEN
    _SRFMI-LIVE @ CINST-DESC DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP COMP-DESC MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP _SRFMI-DESC ! COMP-CAPS-VALID? 0= IF 0 EXIT THEN
    _SRFMI-DESC @ COMP.STATE-SIZE @ DUP _SRFMI-STATE-U !
    0< IF 0 EXIT THEN
    _SRFMI-LIVE @ CINST-STATE DUP _SRFMI-STATE-A !
    _SRFMI-STATE-U @ 0= IF 0= EXIT THEN
    DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    _SRFMI-STATE-U @ MSPAN-NONWRAPPING? ;

: _SRFMI-ALIASES?  ( source-a source-u -- flag )
    2DUP _SRFMI-MOUNT @ STREAMS-RABBIT-FACET-MOUNT-SIZE
        MSPAN-OVERLAP? IF 2DROP -1 EXIT THEN
    _SRFMI-JSON-A @ _SRFMI-JSON-CAP @ MSPAN-OVERLAP? ;

: _SRFMI-LONG-LIVED-ALIASES?  ( source-a source-u -- flag )
    2DUP _SRFMI-ALIASES? >R
    _SRFMI-BURROW @ STREAMS-RABBIT-BURROW-SIZE MSPAN-OVERLAP?
    R> OR ;

: _SRFMI-INSTANCE-LONG-LIVED-ALIASES?  ( instance -- flag )
    DUP _SRFMI-LIVE !
    DUP COMP-INST _SRFMI-LONG-LIVED-ALIASES? IF DROP -1 EXIT THEN
    CINST-DESC DUP _SRFMI-DESC !
    DUP COMP-DESC _SRFMI-LONG-LIVED-ALIASES? IF DROP -1 EXIT THEN
    DUP COMP.CAPS-N @ CAP-DESC * _SRFMI-CAPS-U !
    COMP.CAPS-A @ _SRFMI-CAPS-A !
    _SRFMI-CAPS-U @ IF
        _SRFMI-CAPS-A @ _SRFMI-CAPS-U @
            _SRFMI-LONG-LIVED-ALIASES? IF -1 EXIT THEN
    THEN
    _SRFMI-MOUNT @ STREAMS-RABBIT-FACET-MOUNT-SIZE _SRFMI-DESC @
        COMP-CAPS-GRAPH-SPAN-OVERLAP? IF -1 EXIT THEN
    _SRFMI-JSON-A @ _SRFMI-JSON-CAP @ _SRFMI-DESC @
        COMP-CAPS-GRAPH-SPAN-OVERLAP? IF -1 EXIT THEN
    _SRFMI-BURROW @ STREAMS-RABBIT-BURROW-SIZE _SRFMI-DESC @
        COMP-CAPS-GRAPH-SPAN-OVERLAP? IF -1 EXIT THEN
    _SRFMI-DESC @ COMP.STATE-SIZE @ _SRFMI-STATE-U !
    _SRFMI-STATE-U @ IF
        _SRFMI-LIVE @ CINST-STATE _SRFMI-STATE-U @
            _SRFMI-LONG-LIVED-ALIASES? IF -1 EXIT THEN
    THEN
    0 ;

: _SRFMI-ROUTER-ALIASES?  ( address bytes -- flag )
    _SRFMI-ROUTER @ RROUTER-OWNED-SPAN-OVERLAP? ;

: _SRFMI-DESC-ROUTER-GRAPH-ALIASES?  ( comp-desc -- flag )
    _SRFMI-DESC !
    RROUTER-OWNED-SPAN-COUNT 0 ?DO
        I _SRFMI-ROUTER @ RROUTER-OWNED-SPAN@
        _SRFMI-OWN-STATUS ! _SRFMI-OWN-U ! _SRFMI-OWN-A !
        _SRFMI-OWN-STATUS @ RROUTER-S-OK <> IF -1 UNLOOP EXIT THEN
        _SRFMI-OWN-A @ _SRFMI-OWN-U @ _SRFMI-DESC @
            COMP-CAPS-GRAPH-SPAN-OVERLAP? IF -1 UNLOOP EXIT THEN
    LOOP
    0 ;

: _SRFMI-INSTANCE-ROUTER-ALIASES?  ( instance -- flag )
    DUP _SRFMI-LIVE !
    DUP COMP-INST _SRFMI-ROUTER-ALIASES? IF DROP -1 EXIT THEN
    CINST-DESC DUP _SRFMI-DESC !
    DUP COMP-DESC _SRFMI-ROUTER-ALIASES? IF DROP -1 EXIT THEN
    DUP COMP.CAPS-N @ CAP-DESC * _SRFMI-CAPS-U !
    COMP.CAPS-A @ _SRFMI-CAPS-A !
    _SRFMI-CAPS-U @ IF
        _SRFMI-CAPS-A @ _SRFMI-CAPS-U @ _SRFMI-ROUTER-ALIASES? IF
            -1 EXIT
        THEN
    THEN
    _SRFMI-DESC @ _SRFMI-DESC-ROUTER-GRAPH-ALIASES? IF -1 EXIT THEN
    _SRFMI-DESC @ COMP.STATE-SIZE @ _SRFMI-STATE-U !
    _SRFMI-STATE-U @ IF
        _SRFMI-LIVE @ CINST-STATE _SRFMI-STATE-U @
            _SRFMI-ROUTER-ALIASES? IF -1 EXIT THEN
    THEN
    0 ;

: _SRFM-ZERO-SPAN?  ( address bytes -- flag )
    0 ?DO
        DUP I + C@ IF DROP 0 UNLOOP EXIT THEN
    LOOP
    DROP -1 ;

: _SRFMI-PREFLIGHT?  ( -- flag )
    _SRFMI-MOUNT @ DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP STREAMS-RABBIT-FACET-MOUNT-SIZE MSPAN-NONWRAPPING? 0= IF
        DROP 0 EXIT
    THEN
    SRFM.MAGIC @ _SRFM-MAGIC-VALUE = IF 0 EXIT THEN
    _SRFMI-KIND @ _SRFM-OBSERVE-KIND? 0= IF 0 EXIT THEN
    _SRFMI-KIND @ _SRFM-KIND>VERB$ 0= IF 2DROP 0 EXIT THEN
    _SRFMI-VERB-U ! _SRFMI-VERB-A !
    _SRFMI-SELECTOR-U @ 0> 0= IF 0 EXIT THEN
    _SRFMI-SELECTOR-A @ _SRFMI-SELECTOR-U @
        MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _SRFMI-JSON-CAP @ 0> 0= IF 0 EXIT THEN
    _SRFMI-JSON-A @ DUP 0= IF DROP 0 EXIT THEN
    _SRFMI-JSON-CAP @ MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _SRFMI-MOUNT @ STREAMS-RABBIT-FACET-MOUNT-SIZE
    _SRFMI-JSON-A @ _SRFMI-JSON-CAP @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _SRFMI-SELECTOR-A @ _SRFMI-SELECTOR-U @ _SRFMI-ALIASES? IF 0 EXIT THEN
    _SRFMI-BURROW @ DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    STREAMS-RABBIT-BURROW-SIZE MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _SRFMI-BURROW @ STREAMS-RABBIT-BURROW-SIZE _SRFMI-ALIASES? IF
        0 EXIT
    THEN
    _SRFMI-BURROW @ STREAMS-RABBIT-BURROW-SIZE _SRFM-ZERO-SPAN? 0= IF
        0 EXIT
    THEN
    _SRFMI-BUS @ _SRFM-BUS-GEOMETRY? 0= IF 0 EXIT THEN
    _SRFMI-BUS @ CBUS.REGISTRY @ _SRFMI-REGISTRY !
    _SRFMI-BUS @ CBUS-SIZE _SRFMI-LONG-LIVED-ALIASES? IF 0 EXIT THEN
    _SRFMI-REGISTRY @ CREG-SIZE _SRFMI-LONG-LIVED-ALIASES? IF
        0 EXIT
    THEN
    _SRFMI-CALLER @ _SRFMI-LIVE-INSTANCE? 0= IF 0 EXIT THEN
    _SRFMI-TARGET @ _SRFMI-LIVE-INSTANCE? 0= IF 0 EXIT THEN
    _SRFMI-CALLER @ _SRFMI-INSTANCE-LONG-LIVED-ALIASES? IF 0 EXIT THEN
    _SRFMI-TARGET @ _SRFMI-INSTANCE-LONG-LIVED-ALIASES? IF 0 EXIT THEN
    _SRFMI-CAP @ _SRFM-CAP-GEOMETRY? 0= IF 0 EXIT THEN
    _SRFMI-CAP @ CAP.EFFECTS @ CAP-E-OBSERVE <> IF 0 EXIT THEN
    _SRFMI-CAP @ CAP.HANDLER-XT @ 0= IF 0 EXIT THEN
    _SRFMI-CAP @ CAP-DESC _SRFMI-LONG-LIVED-ALIASES? IF 0 EXIT THEN
    _SRFMI-CAP @ DUP CAP-ID
        _SRFMI-TARGET @ CINST-DESC COMP-CAP-FIND <> IF 0 EXIT THEN
    _SRFMI-CAP @ DUP CAP.IN-SCHEMA @ ?DUP 0= IF DROP 0 EXIT THEN
    IVJSON-SCHEMA-COMPATIBLE? 0= IF DROP 0 EXIT THEN
    CAP.OUT-SCHEMA @ ?DUP 0= IF 0 EXIT THEN
    IVJSON-SCHEMA-COMPATIBLE? 0= IF 0 EXIT THEN
    _SRFMI-RESOURCE @ ?DUP IF
        DUP RID-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
        DUP RID-SIZE _SRFMI-ALIASES? IF DROP 0 EXIT THEN DROP
    THEN
    _SRFMI-ROUTER @ DUP RROUTER-VALID? 0= IF DROP 0 EXIT THEN
    DUP RROUTER-STATE@ RROUTER-STATE-BUILDING <> IF DROP 0 EXIT THEN
    _SRFMI-MOUNT @ STREAMS-RABBIT-FACET-MOUNT-SIZE _SRFMI-ROUTER @
        RROUTER-OWNED-SPAN-OVERLAP? IF DROP 0 EXIT THEN
    _SRFMI-BURROW @ STREAMS-RABBIT-BURROW-SIZE _SRFMI-ROUTER @
        RROUTER-OWNED-SPAN-OVERLAP? IF DROP 0 EXIT THEN
    _SRFMI-BUS @ CBUS-SIZE _SRFMI-ROUTER @
        RROUTER-OWNED-SPAN-OVERLAP? IF DROP 0 EXIT THEN
    _SRFMI-REGISTRY @ CREG-SIZE _SRFMI-ROUTER @
        RROUTER-OWNED-SPAN-OVERLAP? IF DROP 0 EXIT THEN
    _SRFMI-CALLER @ _SRFMI-INSTANCE-ROUTER-ALIASES? IF DROP 0 EXIT THEN
    _SRFMI-TARGET @ _SRFMI-INSTANCE-ROUTER-ALIASES? IF DROP 0 EXIT THEN
    _SRFMI-CAP @ CAP-DESC _SRFMI-ROUTER @
        RROUTER-OWNED-SPAN-OVERLAP? IF DROP 0 EXIT THEN
    _SRFMI-JSON-A @ _SRFMI-JSON-CAP @ ROT
        RROUTER-OWNED-SPAN-OVERLAP? 0= ;

: _SRFMI-WIPE  ( -- )
    _SRFMI-JSON-A @ _SRFMI-JSON-CAP @ 0 FILL
    _SRFMI-MOUNT @ STREAMS-RABBIT-FACET-MOUNT-SIZE 0 FILL ;

: _SRFM-INIT
  ( kind selector-a selector-u caller target cap resource-rid|0 )
  ( bus future-burrow authorizer-xt authorizer-context )
  ( json-a json-cap building-router mount -- status )
    _SRFMI-MOUNT ! _SRFMI-ROUTER ! _SRFMI-JSON-CAP ! _SRFMI-JSON-A !
    _SRFMI-AUTH-CONTEXT ! _SRFMI-AUTH-XT ! _SRFMI-BURROW !
    _SRFMI-BUS ! _SRFMI-RESOURCE ! _SRFMI-CAP ! _SRFMI-TARGET !
    _SRFMI-CALLER ! _SRFMI-SELECTOR-U ! _SRFMI-SELECTOR-A !
    _SRFMI-KIND !
    _SRFMI-PREFLIGHT? 0= IF
        STREAMS-RABBIT-FACET-MOUNT-S-INVALID EXIT
    THEN
    _SRFMI-ROUTER @ RROUTER-COUNT@ _SRFMI-ROUTE-INDEX !
    _SRFMI-WIPE
    _SRFMI-KIND @ _SRFMI-MOUNT @ SRFM.KIND !
    _SRFMI-ROUTE-INDEX @ _SRFMI-MOUNT @ SRFM.ROUTE-INDEX !
    _SRFMI-ROUTER @ _SRFMI-MOUNT @ SRFM.ROUTER !
    _SRFMI-BUS @ _SRFMI-MOUNT @ SRFM.BUS !
    _SRFMI-BURROW @ _SRFMI-MOUNT @ SRFM.BURROW !
    _SRFMI-CALLER @ CINST.ID @ _SRFMI-MOUNT @ SRFM.CALLER-ID !
    _SRFMI-CALLER @ CINST.GENERATION @ _SRFMI-MOUNT @ SRFM.CALLER-GEN !
    _SRFMI-TARGET @ CINST.ID @ _SRFMI-MOUNT @ SRFM.TARGET-ID !
    _SRFMI-TARGET @ CINST.GENERATION @ _SRFMI-MOUNT @ SRFM.TARGET-GEN !
    _SRFMI-CAP @ _SRFMI-MOUNT @ SRFM.CAP !
    _SRFMI-AUTH-XT @ _SRFMI-MOUNT @ SRFM.AUTH-XT !
    _SRFMI-AUTH-CONTEXT @ _SRFMI-MOUNT @ SRFM.AUTH-CONTEXT !
    _SRFMI-JSON-A @ _SRFMI-MOUNT @ SRFM.JSON-A !
    _SRFMI-JSON-CAP @ _SRFMI-MOUNT @ SRFM.JSON-CAP !
    _SRFMI-RESOURCE @ ?DUP IF
        _SRFMI-MOUNT @ SRFM.RESOURCE-ID RID-COPY
    THEN
    _SRFMI-VERB-A @ _SRFMI-VERB-U @
    _SRFMI-SELECTOR-A @ _SRFMI-SELECTOR-U @
    ['] STREAMS-RABBIT-FACET-MOUNT-HANDLE _SRFMI-MOUNT @
    _SRFMI-ROUTER @ RROUTER-ADD DUP _SRFMI-STATUS !
    RROUTER-S-OK <> IF
        _SRFMI-WIPE STREAMS-RABBIT-FACET-MOUNT-S-ROUTER EXIT
    THEN
    _SRFM-MAGIC-VALUE _SRFMI-MOUNT @ SRFM.MAGIC !
    _SRFM-ABI-VERSION _SRFMI-MOUNT @ SRFM.ABI !
    STREAMS-RABBIT-FACET-MOUNT-SIZE _SRFMI-MOUNT @ SRFM.BYTES !
    STREAMS-RABBIT-FACET-MOUNT-ST-BOUND _SRFMI-MOUNT @ SRFM.STATE !
    STREAMS-RABBIT-FACET-MOUNT-S-OK _SRFMI-MOUNT @ SRFM.LAST-STATUS !
    STREAMS-RABBIT-FACET-MOUNT-S-OK ;

: STREAMS-RABBIT-FACET-MOUNT-INIT
  ( kind selector-a selector-u caller target cap resource-rid|0 )
  ( bus future-burrow authorizer-xt authorizer-context )
  ( json-a json-cap building-router mount -- status )
    ['] _SRFM-INIT _SRFM-GUARD WITH-GUARD ;

\ Router storage owns the borrowed handler pointer.  Servers and the Burrow
\ must be finalized first, then the router must be RESET or FINI before this
\ record and its JSON arena can be wiped.
: _SRFM-FINI  ( mount -- status )
    DUP STREAMS-RABBIT-FACET-MOUNT-BINDING-VALID? 0= IF
        DROP STREAMS-RABBIT-FACET-MOUNT-S-INVALID EXIT
    THEN
    DUP SRFM.BUSY @ IF DROP STREAMS-RABBIT-FACET-MOUNT-S-BUSY EXIT THEN
    DUP _SRFMV-M ! SRFM.ROUTER @ DUP RROUTER-BINDING-VALID? IF
        DUP RROUTER-VALID? 0= IF
            DROP STREAMS-RABBIT-FACET-MOUNT-S-STATE EXIT
        THEN
        _SRFMV-M @ SRFM.ROUTE-INDEX @ SWAP RROUTER-HANDLER@ IF
            SWAP ['] STREAMS-RABBIT-FACET-MOUNT-HANDLE =
            SWAP _SRFMV-M @ = AND IF
                STREAMS-RABBIT-FACET-MOUNT-S-STATE EXIT
            THEN
        ELSE 2DROP THEN
    ELSE
        DUP RROUTER-SIZE _SRFM-ZERO-SPAN? 0= IF
            DROP STREAMS-RABBIT-FACET-MOUNT-S-STATE EXIT
        THEN DROP
    THEN
    _SRFMV-M @ DUP _SRFM-REQUEST-CLEAR
    DUP _SRFM-JSON-CLEAR
    STREAMS-RABBIT-FACET-MOUNT-SIZE 0 FILL
    STREAMS-RABBIT-FACET-MOUNT-S-OK ;

: STREAMS-RABBIT-FACET-MOUNT-FINI  ( mount -- status )
    ['] _SRFM-FINI _SRFM-GUARD WITH-GUARD ;
