\ =====================================================================
\ repository-refresh-owner.f - repository-backed configured refresh
\ =====================================================================
\ This owner is the L13 runtime composition for one explicit configured
\ syndication refresh.  It coordinates one exact source snapshot, one
\ configured provider, Desk's serialized XIO service, bounded syndication
\ decode, durable acquisition acceptance/non-success, and atomic repository
\ application.  It owns no repository lifecycle, scheduler, Library document,
\ draft, output, search, or public-Bluesky policy.
\
\ The caller owns one fixed descriptor.  The descriptor embeds the XIO
\ operation, all exact request/evidence buffers, and both authority work
\ areas.  Only the configured-provider factory and syndication-decoder
\ factory allocate, under their existing bounded ownership contracts.
\
\ INIT is deliberately post-boot: the external repository owner must have
\ opened/provisioned the repository and completed acquisition recovery first.
\ INIT proves that no accepted attempt remains before it allocates a decoder
\ or provider.  RELEASE never closes, aborts, or releases the repository.
\
\ Public lifecycle:
\   STREAMS-REPOSITORY-REFRESH-OWNER-INIT
\     ( xio-service configured-factory-xt repository repo-work owner
\       -- status )
\   STREAMS-REPOSITORY-REFRESH-OWNER-START
\     ( exact-source owner-id owner-generation owner -- status )
\   STREAMS-REPOSITORY-REFRESH-OWNER-TICK
\     ( current-source|0 owner-id owner-generation owner
\       -- changed? status )
\   STREAMS-REPOSITORY-REFRESH-OWNER-CANCEL
\     ( owner-id owner-generation owner -- changed? status )
\   STREAMS-REPOSITORY-REFRESH-OWNER-RELEASE
\     ( owner -- status )
\
\ START performs provider CONFIGURE and canonical requested-URI freezing
\ before durable BEGIN.  No XIO operation is configured or submitted until
\ BEGIN has published ACCEPTED.  On successful XIO, APPLY stages decoded
\ candidates, calls this owner's cleanup/reset callback, revalidates the
\ exact runtime evidence, and publishes success atomically.
\ =====================================================================

\ Keep the module identity within KDOS's 23-byte bound.
PROVIDED akashic-streams-rfowner

REQUIRE configured-provider.f
REQUIRE source-registry.f
REQUIRE syndication-decode.f
REQUIRE acquisition-authority.f
REQUIRE apply-authority.f
REQUIRE ../../../net/external-io.f
REQUIRE ../../../math/sha3.f
REQUIRE ../../../utils/memory-span.f

\ ---------------------------------------------------------------------
\ Distinct owner status and phase domains
\ ---------------------------------------------------------------------

 0 CONSTANT SRRO-S-OK
 1 CONSTANT SRRO-S-INVALID
 2 CONSTANT SRRO-S-UNAVAILABLE
 3 CONSTANT SRRO-S-BUSY
 4 CONSTANT SRRO-S-REPOSITORY
 5 CONSTANT SRRO-S-CAPACITY
 6 CONSTANT SRRO-S-EXTERNAL
 7 CONSTANT SRRO-S-DECODE
 8 CONSTANT SRRO-S-STALE
 9 CONSTANT SRRO-S-CLEANUP
10 CONSTANT SRRO-S-BLOCKED
11 CONSTANT SRRO-S-CANCELLED
12 CONSTANT SRRO-S-INDETERMINATE

\ Phase values intentionally retain the legacy semantic numbering while all
\ names and storage remain distinct.  OFFLINE and RECOVERED are reserved for
\ integration diagnostics; this post-recovery owner initializes directly to
\ IDLE and requires an online service/provider.
 0 CONSTANT SRRO-PHASE-UNINITIALIZED
 1 CONSTANT SRRO-PHASE-OFFLINE
 2 CONSTANT SRRO-PHASE-IDLE
 3 CONSTANT SRRO-PHASE-ACTIVE
 4 CONSTANT SRRO-PHASE-SUCCEEDED
 5 CONSTANT SRRO-PHASE-FAILED
 6 CONSTANT SRRO-PHASE-CANCELLED
 7 CONSTANT SRRO-PHASE-STALE
 8 CONSTANT SRRO-PHASE-RECOVERED
 9 CONSTANT SRRO-PHASE-BLOCKED
10 CONSTANT SRRO-PHASE-CLEANUP

2 CONSTANT SRRO-PROVIDER-SYNDICATION
60000 CONSTANT STREAMS-REPOSITORY-REFRESH-TIMEOUT-MS
0x7FFFFFFFFFFFFFFF CONSTANT _SRRO-CELL-MAX
0x5352524F574E5231 CONSTANT _SRRO-MAGIC  \ "SRROWN R1"

\ ---------------------------------------------------------------------
\ Caller-owned descriptor
\ ---------------------------------------------------------------------

  0 CONSTANT _SRRO-MAGIC-OFF
  8 CONSTANT _SRRO-SELF-OFF
 16 CONSTANT _SRRO-PHASE-OFF
 24 CONSTANT _SRRO-LAST-STATUS-OFF
 32 CONSTANT _SRRO-LAST-ERROR-OFF
 40 CONSTANT _SRRO-LAST-AUTHORITY-STATUS-OFF
 48 CONSTANT _SRRO-XIO-SERVICE-OFF
 56 CONSTANT _SRRO-FACTORY-XT-OFF
 64 CONSTANT _SRRO-PROVIDER-OFF
 72 CONSTANT _SRRO-DECODER-OFF
 80 CONSTANT _SRRO-REPOSITORY-OFF
 88 CONSTANT _SRRO-REPO-WORK-OFF
 96 CONSTANT _SRRO-REQUEST-GENERATION-OFF
104 CONSTANT _SRRO-OWNER-ID-OFF
112 CONSTANT _SRRO-OWNER-GENERATION-OFF
120 CONSTANT _SRRO-ACCEPTED-OFF
128 CONSTANT _SRRO-ATTEMPT-PRESENT-OFF
136 CONSTANT _SRRO-REQUESTED-U-OFF
144 CONSTANT _SRRO-EFFECTIVE-U-OFF
152 CONSTANT _SRRO-CLEANUP-DONE-OFF
160 CONSTANT _SRRO-CLEANUP-ERROR-OFF
168 CONSTANT _SRRO-PROVIDER-OUTCOME-OFF
176 CONSTANT _SRRO-DETAIL-OFF
184 CONSTANT _SRRO-HTTP-STATUS-OFF
192 CONSTANT _SRRO-DECODE-STATUS-OFF
200 CONSTANT _SRRO-XIO-ERROR-OFF
208 CONSTANT _SRRO-CURRENT-SOURCE-OFF
216 CONSTANT _SRRO-CURRENT-OWNER-ID-OFF
224 CONSTANT _SRRO-CURRENT-OWNER-GENERATION-OFF
232 CONSTANT _SRRO-REVALIDATE-ARMED-OFF
240 CONSTANT _SRRO-LAST-ACQUISITION-STATUS-OFF
248 CONSTANT _SRRO-LAST-APPLY-STATUS-OFF
256 CONSTANT _SRRO-SCRATCH-STATUS-OFF
264 CONSTANT _SRRO-SCRATCH-STATE-OFF
272 CONSTANT _SRRO-SCRATCH-OUTCOME-OFF
280 CONSTANT _SRRO-SCRATCH-PHASE-OFF
288 CONSTANT _SRRO-SCRATCH-OWNER-STATUS-OFF
296 CONSTANT _SRRO-SCRATCH-COUNT-OFF
304 CONSTANT _SRRO-SCRATCH-CANDIDATES-OFF
312 CONSTANT _SRRO-SCRATCH-TEMP-OFF
320 CONSTANT _SRRO-NAMESPACE
_SRRO-NAMESPACE SHA3-256-LEN + CONSTANT _SRRO-XIO-OP
_SRRO-XIO-OP XIO-OP-SIZE + CONSTANT _SRRO-SOURCE
_SRRO-SOURCE STREAMS-SOURCE-SIZE + CONSTANT _SRRO-REQUESTED
_SRRO-REQUESTED OCHK-URI-MAX + CONSTANT _SRRO-EFFECTIVE
_SRRO-EFFECTIVE OCHK-URI-MAX + CONSTANT _SRRO-ATTEMPT
_SRRO-ATTEMPT OCHK-SOURCE-SIZE + CONSTANT _SRRO-BEGIN-REQUEST
_SRRO-BEGIN-REQUEST STREAMS-ACQUISITION-BEGIN-REQUEST-SIZE +
    CONSTANT _SRRO-TERMINAL-REQUEST
_SRRO-TERMINAL-REQUEST STREAMS-ACQUISITION-TERMINAL-REQUEST-SIZE +
    CONSTANT _SRRO-APPLY-REQUEST
_SRRO-APPLY-REQUEST STREAMS-APPLY-REQUEST-SIZE +
    CONSTANT _SRRO-ATTEMPT-RECORD
_SRRO-ATTEMPT-RECORD SPREC-ATTEMPT-SIZE +
    CONSTANT _SRRO-ACQUISITION-WORK
_SRRO-ACQUISITION-WORK STREAMS-ACQUISITION-WORK-SIZE +
    CONSTANT _SRRO-APPLY-WORK
_SRRO-APPLY-WORK STREAMS-APPLY-WORK-SIZE +
    CONSTANT STREAMS-REPOSITORY-REFRESH-OWNER-SIZE

: SRRO.MAGIC                    ( owner -- a )
    _SRRO-MAGIC-OFF + ;
: SRRO.SELF                     ( owner -- a )
    _SRRO-SELF-OFF + ;
: SRRO.PHASE                    ( owner -- a )
    _SRRO-PHASE-OFF + ;
: SRRO.LAST-STATUS              ( owner -- a )
    _SRRO-LAST-STATUS-OFF + ;
: SRRO.LAST-ERROR               ( owner -- a )
    _SRRO-LAST-ERROR-OFF + ;
: SRRO.LAST-AUTHORITY-STATUS    ( owner -- a )
    _SRRO-LAST-AUTHORITY-STATUS-OFF + ;
: SRRO.XIO-SERVICE              ( owner -- a )
    _SRRO-XIO-SERVICE-OFF + ;
: SRRO.FACTORY-XT               ( owner -- a )
    _SRRO-FACTORY-XT-OFF + ;
: SRRO.PROVIDER                 ( owner -- a )
    _SRRO-PROVIDER-OFF + ;
: SRRO.DECODER                  ( owner -- a )
    _SRRO-DECODER-OFF + ;
: SRRO.REPOSITORY               ( owner -- a )
    _SRRO-REPOSITORY-OFF + ;
: SRRO.REPO-WORK                ( owner -- a )
    _SRRO-REPO-WORK-OFF + ;
: SRRO.REQUEST-GENERATION       ( owner -- a )
    _SRRO-REQUEST-GENERATION-OFF + ;
: SRRO.OWNER-ID                 ( owner -- a )
    _SRRO-OWNER-ID-OFF + ;
: SRRO.OWNER-GENERATION         ( owner -- a )
    _SRRO-OWNER-GENERATION-OFF + ;
: SRRO.ACCEPTED                 ( owner -- a )
    _SRRO-ACCEPTED-OFF + ;
: SRRO.ATTEMPT-PRESENT          ( owner -- a )
    _SRRO-ATTEMPT-PRESENT-OFF + ;
: SRRO.REQUESTED-U              ( owner -- a )
    _SRRO-REQUESTED-U-OFF + ;
: SRRO.EFFECTIVE-U              ( owner -- a )
    _SRRO-EFFECTIVE-U-OFF + ;
: SRRO.CLEANUP-DONE             ( owner -- a )
    _SRRO-CLEANUP-DONE-OFF + ;
: SRRO.CLEANUP-ERROR            ( owner -- a )
    _SRRO-CLEANUP-ERROR-OFF + ;
: SRRO.PROVIDER-OUTCOME         ( owner -- a )
    _SRRO-PROVIDER-OUTCOME-OFF + ;
: SRRO.DETAIL                   ( owner -- a )
    _SRRO-DETAIL-OFF + ;
: SRRO.HTTP-STATUS              ( owner -- a )
    _SRRO-HTTP-STATUS-OFF + ;
: SRRO.DECODE-STATUS            ( owner -- a )
    _SRRO-DECODE-STATUS-OFF + ;
: SRRO.XIO-ERROR                ( owner -- a )
    _SRRO-XIO-ERROR-OFF + ;
: SRRO.CURRENT-SOURCE           ( owner -- a )
    _SRRO-CURRENT-SOURCE-OFF + ;
: SRRO.CURRENT-OWNER-ID         ( owner -- a )
    _SRRO-CURRENT-OWNER-ID-OFF + ;
: SRRO.CURRENT-OWNER-GENERATION ( owner -- a )
    _SRRO-CURRENT-OWNER-GENERATION-OFF + ;
: SRRO.REVALIDATE-ARMED         ( owner -- a )
    _SRRO-REVALIDATE-ARMED-OFF + ;
: SRRO.LAST-ACQUISITION-STATUS  ( owner -- a )
    _SRRO-LAST-ACQUISITION-STATUS-OFF + ;
: SRRO.LAST-APPLY-STATUS        ( owner -- a )
    _SRRO-LAST-APPLY-STATUS-OFF + ;
: SRRO.SCRATCH-STATUS           ( owner -- a )
    _SRRO-SCRATCH-STATUS-OFF + ;
: SRRO.SCRATCH-STATE            ( owner -- a )
    _SRRO-SCRATCH-STATE-OFF + ;
: SRRO.SCRATCH-OUTCOME          ( owner -- a )
    _SRRO-SCRATCH-OUTCOME-OFF + ;
: SRRO.SCRATCH-PHASE            ( owner -- a )
    _SRRO-SCRATCH-PHASE-OFF + ;
: SRRO.SCRATCH-OWNER-STATUS     ( owner -- a )
    _SRRO-SCRATCH-OWNER-STATUS-OFF + ;
: SRRO.SCRATCH-COUNT            ( owner -- a )
    _SRRO-SCRATCH-COUNT-OFF + ;
: SRRO.SCRATCH-CANDIDATES       ( owner -- a )
    _SRRO-SCRATCH-CANDIDATES-OFF + ;
: SRRO.SCRATCH-TEMP             ( owner -- a )
    _SRRO-SCRATCH-TEMP-OFF + ;
: SRRO.NAMESPACE                ( owner -- digest )
    _SRRO-NAMESPACE + ;
: SRRO.XIO-OP                   ( owner -- operation )
    _SRRO-XIO-OP + ;
: SRRO.SOURCE                   ( owner -- source )
    _SRRO-SOURCE + ;
: SRRO.REQUESTED                ( owner -- a )
    _SRRO-REQUESTED + ;
: SRRO.EFFECTIVE                ( owner -- a )
    _SRRO-EFFECTIVE + ;
: SRRO.ATTEMPT                  ( owner -- attempt )
    _SRRO-ATTEMPT + ;
: SRRO.BEGIN-REQUEST            ( owner -- request )
    _SRRO-BEGIN-REQUEST + ;
: SRRO.TERMINAL-REQUEST         ( owner -- request )
    _SRRO-TERMINAL-REQUEST + ;
: SRRO.APPLY-REQUEST            ( owner -- request )
    _SRRO-APPLY-REQUEST + ;
: SRRO.ATTEMPT-RECORD           ( owner -- record )
    _SRRO-ATTEMPT-RECORD + ;
: SRRO.ACQUISITION-WORK         ( owner -- work )
    _SRRO-ACQUISITION-WORK + ;
: SRRO.APPLY-WORK               ( owner -- work )
    _SRRO-APPLY-WORK + ;

: _SRRO-DROP3  ( x1 x2 x3 -- ) 2DROP DROP ;
: _SRRO-DROP4  ( x1 x2 x3 x4 -- ) 2DROP 2DROP ;

\ ---------------------------------------------------------------------
\ Public inspection
\ ---------------------------------------------------------------------

: STREAMS-REPOSITORY-REFRESH-OWNER-PHASE@  ( owner -- phase )
    SRRO.PHASE @ ;

: STREAMS-REPOSITORY-REFRESH-OWNER-STATUS@  ( owner -- status )
    SRRO.LAST-STATUS @ ;

: STREAMS-REPOSITORY-REFRESH-OWNER-ERROR@  ( owner -- error )
    SRRO.LAST-ERROR @ ;

: STREAMS-REPOSITORY-REFRESH-OWNER-AUTHORITY-STATUS@
  ( owner -- lower-status )
    SRRO.LAST-AUTHORITY-STATUS @ ;

: STREAMS-REPOSITORY-REFRESH-OWNER-ACQUISITION-STATUS@
  ( owner -- acquisition-status )
    SRRO.LAST-ACQUISITION-STATUS @ ;

: STREAMS-REPOSITORY-REFRESH-OWNER-APPLY-STATUS@
  ( owner -- apply-status )
    SRRO.LAST-APPLY-STATUS @ ;

: STREAMS-REPOSITORY-REFRESH-OWNER-REQUEST-GENERATION@
  ( owner -- generation )
    SRRO.REQUEST-GENERATION @ ;

: STREAMS-REPOSITORY-REFRESH-OWNER-SOURCE  ( owner -- source|0 )
    DUP SRRO.ATTEMPT-PRESENT @
    IF SRRO.SOURCE ELSE DROP 0 THEN ;

: STREAMS-REPOSITORY-REFRESH-OWNER-ATTEMPT  ( owner -- attempt|0 )
    DUP SRRO.ATTEMPT-PRESENT @
    IF SRRO.ATTEMPT ELSE DROP 0 THEN ;

\ ---------------------------------------------------------------------
\ Source admission and exact legacy namespace bytes
\ ---------------------------------------------------------------------

: _SRRO-SOURCE-SUPPORTED?  ( source -- flag )
    DUP STREAMS-SOURCE-VALID? 0= IF DROP 0 EXIT THEN
    DUP SSOURCE.KIND @ SSOURCE-KIND-SYNDICATION <> IF
        DROP 0 EXIT
    THEN
    DUP SSOURCE.FLAGS @ SSOURCE-F-ENABLED AND 0= IF
        DROP 0 EXIT
    THEN
    DUP SSOURCE.FORMAT @ DUP SSOURCE-FORMAT-AUTO =
        OVER SSOURCE-FORMAT-RSS = OR
        OVER SSOURCE-FORMAT-ATOM = OR
        SWAP SSOURCE-FORMAT-JSON-FEED = OR 0= IF
        DROP 0 EXIT
    THEN
    SSOURCE.PAGE-MAX @ 1 = ;

: STREAMS-REPOSITORY-REFRESH-SOURCE-SUPPORTED?
  ( source -- flag )
    _SRRO-SOURCE-SUPPORTED? ;

: _SRRO-SOURCE-SPAN-SAFE?  ( source owner -- flag )
    >R
    DUP 0= IF DROP R> DROP 0 EXIT THEN
    DUP STREAMS-SOURCE-SIZE MSPAN-NONWRAPPING? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP STREAMS-SOURCE-SIZE
    R@ STREAMS-REPOSITORY-REFRESH-OWNER-SIZE
        MSPAN-OVERLAP? IF
        DROP R> DROP 0 EXIT
    THEN
    DUP STREAMS-SOURCE-SIZE
    R@ SRRO.REPOSITORY @
    R@ SRRO.REPO-WORK @
        STREAMS-REPOSITORY-SPAN-DISJOINT? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    STREAMS-SOURCE-SIZE
    R@ SRRO.XIO-SERVICE @ XIO-SERVICE-SIZE
        MSPAN-OVERLAP? 0=
    R> DROP ;

\ Hashing a number stores the native 8-byte cell in caller-owned scratch.
\ This intentionally preserves the legacy `_SREF-HASH-N,` byte domain.
: _SRRO-HASH-N,  ( n owner -- )
    >R
    R@ SRRO.SCRATCH-TEMP !
    R@ SRRO.SCRATCH-TEMP 8 SHA3-256-ADD
    R> DROP ;

: _SRRO-HASH-$,  ( a u owner -- )
    >R
    DUP R@ _SRRO-HASH-N,
    SHA3-256-ADD
    R> DROP ;

: _SRRO-NAMESPACE!  ( owner -- )
    >R
    SHA3-256-BEGIN
    S" akashic.streams.syndication-source.v1"
        R@ _SRRO-HASH-$,
    R@ SRRO.SOURCE SSOURCE.ID SHA3-256-LEN SHA3-256-ADD
    R@ SRRO.SOURCE SSOURCE.KIND @ R@ _SRRO-HASH-N,
    R@ SRRO.SOURCE SSOURCE.FORMAT @ R@ _SRRO-HASH-N,
    R@ SRRO.SOURCE STREAMS-SOURCE-ENDPOINT$ R@ _SRRO-HASH-$,
    R@ SRRO.SOURCE STREAMS-SOURCE-CONFIG$ R@ _SRRO-HASH-$,
    R@ SRRO.SOURCE SSOURCE.REDIRECT-MAX @ R@ _SRRO-HASH-N,
    R@ SRRO.SOURCE SSOURCE.RESPONSE-MAX @ R@ _SRRO-HASH-N,
    R@ SRRO.SOURCE SSOURCE.PAGE-MAX @ R@ _SRRO-HASH-N,
    R@ SRRO.SOURCE SSOURCE.OBSERVATION-MAX @ R@ _SRRO-HASH-N,
    R@ SRRO.SOURCE SSOURCE.REVISION-MAX @ R@ _SRRO-HASH-N,
    R@ SRRO.NAMESPACE SHA3-256-END
    R> DROP ;

\ ---------------------------------------------------------------------
\ Repository and descriptor validity
\ ---------------------------------------------------------------------

: _SRRO-REPOSITORY-USABLE?  ( owner -- flag )
    >R
    R@ SRRO.REPOSITORY @ DUP STREAMS-REPOSITORY-VALID? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP STREAMS-REPOSITORY-LOADED? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP STREAMS-REPOSITORY-PROVISIONED? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    STREAMS-REPOSITORY-BLOCKED? IF
        R> DROP 0 EXIT
    THEN
    R@ SRRO.REPO-WORK @ DUP STREAMS-REPOSITORY-WORK-VALID? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    R@ SRRO.REPOSITORY @ OVER
        STREAMS-REPOSITORY-WORK-BOUND? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP STREAMS-REPOSITORY-WORK-BUSY? IF
        DROP R> DROP 0 EXIT
    THEN
    DUP STREAMS-REPOSITORY-ACTIVE? IF
        DROP R> DROP 0 EXIT
    THEN
    DUP STREAMS-REPOSITORY-REOPEN-REQUIRED? IF
        DROP R> DROP 0 EXIT
    THEN
    STREAMS-REPOSITORY-AUTHORITY-ROOT@
    DUP 0= IF DROP R> DROP 0 EXIT THEN
    STREAMS-AUTHORITY-ROOT-HEADER-VALID?
    R> DROP ;

: _SRRO-BOOT-RECOVERED?  ( owner -- flag )
    DUP _SRRO-REPOSITORY-USABLE? 0= IF DROP 0 EXIT THEN
    SRRO.REPO-WORK @ STREAMS-REPOSITORY-AUTHORITY-ROOT@
    DUP 0= IF DROP 0 EXIT THEN
    SAR.ACTIVE-COUNT @ 0= ;

: STREAMS-REPOSITORY-REFRESH-OWNER-VALID?  ( owner -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP STREAMS-REPOSITORY-REFRESH-OWNER-SIZE
        MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP SRRO.MAGIC @ _SRRO-MAGIC <> IF DROP 0 EXIT THEN
    DUP SRRO.SELF @ OVER <> IF DROP 0 EXIT THEN
    DUP SRRO.PHASE @ DUP SRRO-PHASE-OFFLINE <
        SWAP SRRO-PHASE-CLEANUP > OR IF DROP 0 EXIT THEN
    DUP SRRO.XIO-OP XIO-OP-VALID? 0= IF DROP 0 EXIT THEN
    DUP SRRO.ACQUISITION-WORK
        STREAMS-ACQUISITION-WORK-VALID? 0= IF DROP 0 EXIT THEN
    DUP SRRO.APPLY-WORK
        STREAMS-APPLY-WORK-VALID? 0= IF DROP 0 EXIT THEN
    DUP SRRO.PROVIDER @ DUP 0<> IF
        SCONF-VALID?
    ELSE
        DROP 0
    THEN 0= IF DROP 0 EXIT THEN
    DUP SRRO.DECODER @ DUP 0<> IF
        STREAMS-SYNDICATION-DECODER-VALID?
    ELSE
        DROP 0
    THEN 0= IF DROP 0 EXIT THEN
    DUP SRRO.REPOSITORY @ OVER SRRO.REPO-WORK @
        STREAMS-REPOSITORY-WORK-BOUND? 0= IF DROP 0 EXIT THEN
    DUP STREAMS-REPOSITORY-REFRESH-OWNER-SIZE
    2 PICK SRRO.REPOSITORY @
    3 PICK SRRO.REPO-WORK @
        STREAMS-REPOSITORY-SPAN-DISJOINT?
    NIP ;

: STREAMS-REPOSITORY-REFRESH-OWNER-AVAILABLE?  ( owner -- flag )
    DUP STREAMS-REPOSITORY-REFRESH-OWNER-VALID? 0= IF
        DROP 0 EXIT
    THEN
    DUP SRRO.PHASE @ DUP SRRO-PHASE-BLOCKED <>
        SWAP SRRO-PHASE-CLEANUP <> AND 0= IF
        DROP 0 EXIT
    THEN
    DUP _SRRO-REPOSITORY-USABLE? 0= IF DROP 0 EXIT THEN
    DUP SRRO.XIO-SERVICE @ DUP XIO-SERVICE-BOUND? 0= IF
        DROP DROP 0 EXIT
    THEN
    XIO-SERVICE-OWNER? 0= IF DROP 0 EXIT THEN
    SRRO.PROVIDER @ SCONF-CLEANUP-ERROR@ 0= ;

\ ---------------------------------------------------------------------
\ Status, fact, and lower-domain helpers
\ ---------------------------------------------------------------------

: _SRRO-MARK  ( phase status error owner -- status )
    >R
    DUP R@ SRRO.LAST-ERROR !
    DROP
    DUP R@ SRRO.LAST-STATUS !
    SWAP R@ SRRO.PHASE !
    R> DROP ;

: _SRRO-CLEAR-FACTS  ( owner -- )
    DUP 0 SWAP SRRO.CLEANUP-DONE !
    DUP 0 SWAP SRRO.CLEANUP-ERROR !
    DUP SCONF-O-NONE SWAP SRRO.PROVIDER-OUTCOME !
    DUP 0 SWAP SRRO.DETAIL !
    DUP 0 SWAP SRRO.HTTP-STATUS !
    DUP 0 SWAP SRRO.DECODE-STATUS !
    0 SWAP SRRO.XIO-ERROR ! ;

: _SRRO-CAPTURE-PROVIDER  ( owner -- )
    >R
    R@ SRRO.PROVIDER @ DUP SCONF-OUTCOME
        R@ SRRO.PROVIDER-OUTCOME !
    DUP SCONF-DETAIL R@ SRRO.DETAIL !
    SCONF-HTTP-STATUS R@ SRRO.HTTP-STATUS !
    R> DROP ;

: _SRRO-PROVIDER>OUTCOME  ( provider-outcome -- attempt-outcome )
    CASE
        SCONF-O-HTTP OF OCHK-O-HTTP ENDOF
        SCONF-O-REDIRECT-LIMIT OF OCHK-O-HTTP ENDOF
        SCONF-O-REDIRECT-LOOP OF OCHK-O-HTTP ENDOF
        SCONF-O-AUTHORITY-REQUIRED OF OCHK-O-HTTP ENDOF
        SCONF-O-REDIRECT-INVALID OF OCHK-O-HTTP ENDOF
        SCONF-O-HEADER OF OCHK-O-HTTP ENDOF
        SCONF-O-MEDIA OF OCHK-O-MEDIA ENDOF
        SCONF-O-CONTENT-ENCODING OF OCHK-O-MEDIA ENDOF
        SCONF-O-BODY-OVERFLOW OF OCHK-O-CAPACITY ENDOF
        SCONF-O-CANCELLED OF OCHK-O-CANCELLED ENDOF
        SCONF-O-CLEANUP OF OCHK-O-CLEANUP ENDOF
        OCHK-O-TRANSPORT SWAP
    ENDCASE ;

: _SRRO-SCONF>STATUS  ( configured-status -- owner-status )
    CASE
        SCONF-S-OK OF SRRO-S-OK ENDOF
        SCONF-S-INVALID OF SRRO-S-INVALID ENDOF
        SCONF-S-BUSY OF SRRO-S-BUSY ENDOF
        SCONF-S-CAPACITY OF SRRO-S-CAPACITY ENDOF
        SCONF-S-TRANSPORT OF SRRO-S-EXTERNAL ENDOF
        SRRO-S-UNAVAILABLE SWAP
    ENDCASE ;

: _SRRO-ACQUISITION>STATUS  ( acquisition-status -- owner-status )
    CASE
        STREAMS-ACQUISITION-S-OK OF SRRO-S-OK ENDOF
        STREAMS-ACQUISITION-S-INVALID OF SRRO-S-INVALID ENDOF
        STREAMS-ACQUISITION-S-NOT-FOUND OF SRRO-S-STALE ENDOF
        STREAMS-ACQUISITION-S-GONE OF SRRO-S-STALE ENDOF
        STREAMS-ACQUISITION-S-DISABLED OF SRRO-S-STALE ENDOF
        STREAMS-ACQUISITION-S-STALE OF SRRO-S-STALE ENDOF
        STREAMS-ACQUISITION-S-BUSY OF SRRO-S-BUSY ENDOF
        STREAMS-ACQUISITION-S-MISMATCH OF SRRO-S-STALE ENDOF
        STREAMS-ACQUISITION-S-STATE OF SRRO-S-INVALID ENDOF
        STREAMS-ACQUISITION-S-CAPACITY OF SRRO-S-CAPACITY ENDOF
        STREAMS-ACQUISITION-S-IO OF SRRO-S-REPOSITORY ENDOF
        STREAMS-ACQUISITION-S-CORRUPT OF SRRO-S-BLOCKED ENDOF
        STREAMS-ACQUISITION-S-CONFLICT OF SRRO-S-BLOCKED ENDOF
        STREAMS-ACQUISITION-S-UNCERTAIN OF SRRO-S-BLOCKED ENDOF
        STREAMS-ACQUISITION-S-FAULT OF SRRO-S-BLOCKED ENDOF
        STREAMS-ACQUISITION-S-UNSUPPORTED OF SRRO-S-BLOCKED ENDOF
        SRRO-S-BLOCKED SWAP
    ENDCASE ;

: _SRRO-APPLY>STATUS  ( apply-status -- owner-status )
    CASE
        STREAMS-APPLY-S-OK OF SRRO-S-OK ENDOF
        STREAMS-APPLY-S-INVALID OF SRRO-S-DECODE ENDOF
        STREAMS-APPLY-S-NOT-FOUND OF SRRO-S-STALE ENDOF
        STREAMS-APPLY-S-GONE OF SRRO-S-STALE ENDOF
        STREAMS-APPLY-S-STALE OF SRRO-S-STALE ENDOF
        STREAMS-APPLY-S-DUPLICATE OF SRRO-S-DECODE ENDOF
        STREAMS-APPLY-S-BUSY OF SRRO-S-BUSY ENDOF
        STREAMS-APPLY-S-MISMATCH OF SRRO-S-STALE ENDOF
        STREAMS-APPLY-S-STATE OF SRRO-S-BLOCKED ENDOF
        STREAMS-APPLY-S-CAPACITY OF SRRO-S-CAPACITY ENDOF
        STREAMS-APPLY-S-CLEANUP OF SRRO-S-CLEANUP ENDOF
        STREAMS-APPLY-S-IO OF SRRO-S-REPOSITORY ENDOF
        STREAMS-APPLY-S-CORRUPT OF SRRO-S-BLOCKED ENDOF
        STREAMS-APPLY-S-CONFLICT OF SRRO-S-BLOCKED ENDOF
        STREAMS-APPLY-S-UNCERTAIN OF SRRO-S-BLOCKED ENDOF
        STREAMS-APPLY-S-FAULT OF SRRO-S-BLOCKED ENDOF
        STREAMS-APPLY-S-UNSUPPORTED OF SRRO-S-BLOCKED ENDOF
        SRRO-S-BLOCKED SWAP
    ENDCASE ;

: _SRRO-FIRST-CLEANUP!  ( error owner -- )
    >R
    ?DUP IF
        R@ SRRO.CLEANUP-ERROR @ 0=
        IF R@ SRRO.CLEANUP-ERROR ! ELSE DROP THEN
    THEN
    R> DROP ;

\ RESET is also APPLY's cleanup callback.  It makes one retry after a thrown
\ wipe callback so XIO's wipe-once flag can release the retained operation.
\ The provider is poisoned on any lower cleanup error.
: _SRRO-RESET  ( owner -- cleanup-error )
    >R
    0 R@ SRRO.CLEANUP-DONE !
    0 R@ SRRO.CLEANUP-ERROR !
    R@ SRRO.XIO-OP XIOO.CLEANUP-ERROR @
        R@ _SRRO-FIRST-CLEANUP!
    R@ SRRO.PROVIDER @ SCONF-CLEANUP-ERROR@
        R@ _SRRO-FIRST-CLEANUP!
    R@ SRRO.XIO-SERVICE @ R@ SRRO.XIO-OP XIO-RESET
    DUP R@ SRRO.SCRATCH-STATUS !
    DUP XIO-S-CALLBACK = IF
        DROP
        R@ SRRO.XIO-OP XIOO.CLEANUP-ERROR @
            R@ _SRRO-FIRST-CLEANUP!
        R@ SRRO.PROVIDER @ SCONF-CLEANUP-ERROR@
            R@ _SRRO-FIRST-CLEANUP!
        R@ SRRO.XIO-SERVICE @ R@ SRRO.XIO-OP XIO-RESET
        DUP R@ SRRO.SCRATCH-STATUS !
    THEN
    DUP XIO-S-OK <> IF
        DUP R@ _SRRO-FIRST-CLEANUP!
    THEN
    DROP
    R@ SRRO.XIO-OP XIOO.CLEANUP-ERROR @
        R@ _SRRO-FIRST-CLEANUP!
    R@ SRRO.PROVIDER @ SCONF-CLEANUP-ERROR@
        R@ _SRRO-FIRST-CLEANUP!
    R@ SRRO.SCRATCH-STATUS @ XIO-S-OK =
    R@ SRRO.XIO-OP XIOO.STATE @ XIO-STATE-RESET = AND
    R@ SRRO.XIO-SERVICE @ XIO-ACTIVE? 0= AND
    R@ SRRO.XIO-SERVICE @ XIOS.RETAINED @ 0= AND IF
        R@ SRRO.XIO-OP XIO-OP-INIT
        -1 R@ SRRO.CLEANUP-DONE !
    THEN
    R@ SRRO.CLEANUP-ERROR @ DUP IF
        DUP R@ SRRO.PROVIDER @ SCONF-POISON
    THEN
    R> DROP ;

: _SRRO-TERMINAL-SPEC!
  ( state outcome phase owner-status owner -- )
    >R
    DUP R@ SRRO.SCRATCH-OWNER-STATUS !
    DROP
    DUP R@ SRRO.SCRATCH-PHASE !
    DROP
    DUP R@ SRRO.SCRATCH-OUTCOME !
    DROP
    R@ SRRO.SCRATCH-STATE !
    R> DROP ;

: _SRRO-TERMINAL-ERROR  ( owner -- error )
    DUP SRRO.CLEANUP-ERROR @ ?DUP IF NIP EXIT THEN
    DUP SRRO.XIO-ERROR @ ?DUP IF NIP EXIT THEN
    DUP SRRO.DECODE-STATUS @ ?DUP IF NIP EXIT THEN
    SRRO.DETAIL @ ;

: _SRRO-FINISHED-MS  ( owner -- finished-ms )
    >R
    MS@
    DUP R@ SRRO.ATTEMPT OCS.STARTED-MS @ < IF
        DROP R@ SRRO.ATTEMPT OCS.STARTED-MS @
    THEN
    R> DROP ;

\ Publish the terminal specification already stored in SCRATCH fields.
\ ACCEPTED remains set on a lower failure so boot recovery retains authority.
: _SRRO-TERMINALIZE  ( owner -- status )
    >R
    R@ SRRO.TERMINAL-REQUEST
        STREAMS-ACQUISITION-TERMINAL-REQUEST-INIT
    DUP IF
        DUP R@ SRRO.LAST-ACQUISITION-STATUS !
        DUP R@ SRRO.LAST-AUTHORITY-STATUS !
        DROP
        SRRO-PHASE-BLOCKED SRRO-S-BLOCKED SRRO-S-INVALID
        R> _SRRO-MARK EXIT
    THEN DROP
    R@ SRRO.ATTEMPT OCS.SOURCE-ID
        R@ SRRO.TERMINAL-REQUEST SATR.SOURCE-ID RID-COPY
    R@ SRRO.ATTEMPT OCS.SOURCE-REVISION @
        R@ SRRO.TERMINAL-REQUEST SATR.SOURCE-REVISION !
    R@ SRRO.ATTEMPT OCS.ATTEMPT-ID
        R@ SRRO.TERMINAL-REQUEST SATR.ATTEMPT-ID RID-COPY
    R@ SRRO.ATTEMPT OCS.REQUEST-SEAL
        R@ SRRO.TERMINAL-REQUEST SATR.REQUEST-SEAL RID-COPY
    R@ SRRO.SCRATCH-STATE @
        R@ SRRO.TERMINAL-REQUEST SATR.FACTS SACQF.STATE !
    R@ SRRO.SCRATCH-OUTCOME @
        R@ SRRO.TERMINAL-REQUEST SATR.FACTS SACQF.OUTCOME !
    R@ _SRRO-FINISHED-MS
        R@ SRRO.TERMINAL-REQUEST SATR.FACTS SACQF.FINISHED-MS !
    R@ SRRO.DETAIL @
        R@ SRRO.TERMINAL-REQUEST SATR.FACTS SACQF.DETAIL !
    R@ SRRO.HTTP-STATUS @
        R@ SRRO.TERMINAL-REQUEST SATR.FACTS SACQF.HTTP-STATUS !
    R@ SRRO.DECODE-STATUS @
        R@ SRRO.TERMINAL-REQUEST SATR.FACTS SACQF.DECODE-STATUS !
    R@ SRRO.XIO-ERROR @
        R@ SRRO.TERMINAL-REQUEST SATR.FACTS SACQF.XIO-ERROR !
    R@ SRRO.CLEANUP-ERROR @
        R@ SRRO.TERMINAL-REQUEST SATR.FACTS SACQF.CLEANUP-ERROR !
    R@ SRRO.TERMINAL-REQUEST
    R@ SRRO.ATTEMPT
    R@ SRRO.REPOSITORY @
    R@ SRRO.REPO-WORK @
    R@ SRRO.ACQUISITION-WORK
        STREAMS-ACQUISITION-TERMINAL
    DUP R@ SRRO.LAST-ACQUISITION-STATUS !
    DUP R@ SRRO.LAST-AUTHORITY-STATUS !
    DUP IF
        DROP
        SRRO-PHASE-BLOCKED SRRO-S-BLOCKED
        R@ SRRO.LAST-ACQUISITION-STATUS @
        R> _SRRO-MARK EXIT
    THEN DROP
    0 R@ SRRO.ACCEPTED !
    R@ SRRO.SCRATCH-PHASE @
    R@ SRRO.SCRATCH-OWNER-STATUS @
    R@ _SRRO-TERMINAL-ERROR
    R> _SRRO-MARK ;

\ ---------------------------------------------------------------------
\ Initialization
\ ---------------------------------------------------------------------

: _SRRO-PARTIAL-RELEASE  ( owner -- )
    >R
    R@ SRRO.PROVIDER @ ?DUP IF
        DUP SCONF-VALID? IF
            DUP SCONF-RELEASABLE?
            IF SCONF-RELEASE DROP ELSE DROP THEN
        ELSE
            DROP
        THEN
    THEN
    R@ SRRO.DECODER @ ?DUP IF
        STREAMS-SYNDICATION-DECODER-FREE DROP
    THEN
    R@ STREAMS-REPOSITORY-REFRESH-OWNER-SIZE 0 FILL
    R> DROP ;

: STREAMS-REPOSITORY-REFRESH-OWNER-INIT
  ( xio-service configured-factory-xt repository repo-work owner -- status )
    >R
    R@ 0= IF
        _SRRO-DROP4 R> DROP SRRO-S-INVALID EXIT
    THEN
    R@ STREAMS-REPOSITORY-REFRESH-OWNER-SIZE
        MSPAN-NONWRAPPING? 0= IF
        _SRRO-DROP4 R> DROP SRRO-S-INVALID EXIT
    THEN
    R@ SRRO.MAGIC @ _SRRO-MAGIC = IF
        _SRRO-DROP4 R> DROP SRRO-S-BUSY EXIT
    THEN
    3 PICK DUP 0= IF
        DROP _SRRO-DROP4 R> DROP SRRO-S-INVALID EXIT
    THEN
    DUP XIO-SERVICE-BOUND? 0= IF
        DROP _SRRO-DROP4 R> DROP SRRO-S-UNAVAILABLE EXIT
    THEN
    XIO-SERVICE-OWNER? 0= IF
        _SRRO-DROP4 R> DROP SRRO-S-UNAVAILABLE EXIT
    THEN
    2 PICK 0= IF
        _SRRO-DROP4 R> DROP SRRO-S-INVALID EXIT
    THEN
    2DUP STREAMS-REPOSITORY-WORK-BOUND? 0= IF
        _SRRO-DROP4 R> DROP SRRO-S-INVALID EXIT
    THEN
    R@ STREAMS-REPOSITORY-REFRESH-OWNER-SIZE
    3 PICK 3 PICK STREAMS-REPOSITORY-SPAN-DISJOINT? 0= IF
        _SRRO-DROP4 R> DROP SRRO-S-INVALID EXIT
    THEN
    R@ STREAMS-REPOSITORY-REFRESH-OWNER-SIZE
    5 PICK XIO-SERVICE-SIZE MSPAN-OVERLAP? IF
        _SRRO-DROP4 R> DROP SRRO-S-INVALID EXIT
    THEN

    R@ STREAMS-REPOSITORY-REFRESH-OWNER-SIZE 0 FILL
    3 PICK R@ SRRO.XIO-SERVICE !
    2 PICK R@ SRRO.FACTORY-XT !
    OVER R@ SRRO.REPOSITORY !
    DUP R@ SRRO.REPO-WORK !
    _SRRO-DROP4
    R@ SRRO.XIO-OP XIO-OP-INIT
    R@ SRRO.ACQUISITION-WORK STREAMS-ACQUISITION-WORK-INIT
    DUP IF
        DROP R@ _SRRO-PARTIAL-RELEASE
        R> DROP SRRO-S-INVALID EXIT
    THEN DROP
    R@ SRRO.APPLY-WORK STREAMS-APPLY-WORK-INIT
    DUP IF
        DROP R@ _SRRO-PARTIAL-RELEASE
        R> DROP SRRO-S-INVALID EXIT
    THEN DROP
    R@ _SRRO-BOOT-RECOVERED? 0= IF
        R@ _SRRO-PARTIAL-RELEASE
        R> DROP SRRO-S-BLOCKED EXIT
    THEN

    STREAMS-SYNDICATION-DECODER-NEW
    DUP R@ SRRO.LAST-AUTHORITY-STATUS !
    DUP SYNDEC-S-OK <> IF
        DROP DROP
        R@ _SRRO-PARTIAL-RELEASE
        R> DROP SRRO-S-CAPACITY EXIT
    THEN
    DROP
    R@ SRRO.DECODER !

    R@ SRRO.FACTORY-XT @ EXECUTE
    DUP R@ SRRO.LAST-AUTHORITY-STATUS !
    DUP SCONF-S-OK <> IF
        DUP _SRRO-SCONF>STATUS R@ SRRO.SCRATCH-STATUS !
        DROP
        ?DUP IF
            DUP SCONF-VALID? IF
                DUP SCONF-RELEASABLE?
                IF SCONF-RELEASE DROP ELSE DROP THEN
            ELSE
                DROP
            THEN
        THEN
        R@ SRRO.SCRATCH-STATUS @
        R@ _SRRO-PARTIAL-RELEASE
        R> DROP EXIT
    THEN
    DROP
    DUP SCONF-VALID? 0= IF
        DROP
        R@ _SRRO-PARTIAL-RELEASE
        R> DROP SRRO-S-UNAVAILABLE EXIT
    THEN
    R@ SRRO.PROVIDER !

    _SRRO-MAGIC R@ SRRO.MAGIC !
    R@ R@ SRRO.SELF !
    SRRO-PHASE-IDLE R@ SRRO.PHASE !
    SRRO-S-OK R@ SRRO.LAST-STATUS !
    0 R@ SRRO.LAST-ERROR !
    0 R@ SRRO.LAST-AUTHORITY-STATUS !
    R> DROP SRRO-S-OK ;

\ ---------------------------------------------------------------------
\ START: configure, durable acceptance, then XIO
\ ---------------------------------------------------------------------

: _SRRO-ACCEPTED-EXACT?  ( owner -- flag )
    >R
    R@ SRRO.ATTEMPT R@ SRRO.ATTEMPT-RECORD
        SPREC-ATTEMPT-CONSTRUCT SPREC-S-OK <> IF
        R> DROP 0 EXIT
    THEN
    R@ SRRO.ATTEMPT OCS.STATE @ OCHK-ATTEMPT-ACCEPTED <> IF
        R> DROP 0 EXIT
    THEN
    R@ SRRO.ATTEMPT OCS.SOURCE-ID
    R@ SRRO.SOURCE SSOURCE.ID RID= 0= IF R> DROP 0 EXIT THEN
    R@ SRRO.ATTEMPT OCS.SOURCE-REVISION @
    R@ SRRO.SOURCE SSOURCE.REVISION @ <> IF R> DROP 0 EXIT THEN
    R@ SRRO.ATTEMPT OCS.PROVIDER-KIND @
        SRRO-PROVIDER-SYNDICATION <> IF R> DROP 0 EXIT THEN
    R@ SRRO.ATTEMPT OCS.NAMESPACE
    R@ SRRO.NAMESPACE RID= 0= IF R> DROP 0 EXIT THEN
    R@ SRRO.ATTEMPT OCS.ATTEMPT-ID RID-PRESENT? 0= IF
        R> DROP 0 EXIT
    THEN
    R@ SRRO.ATTEMPT OCS.REQUEST-SEAL RID-PRESENT? 0= IF
        R> DROP 0 EXIT
    THEN
    R@ SRRO.ATTEMPT OCS.STARTED-MS @ 0< IF R> DROP 0 EXIT THEN
    R@ SRRO.ATTEMPT OCS.FINISHED-MS @ IF R> DROP 0 EXIT THEN
    R@ SRRO.ATTEMPT OCS.OUTCOME @ OCHK-O-NONE <> IF
        R> DROP 0 EXIT
    THEN
    R@ SRRO.ATTEMPT OCS.EFFECTIVE$ NIP IF R> DROP 0 EXIT THEN
    R@ SRRO.ATTEMPT OCS.NEW-COUNT @
    R@ SRRO.ATTEMPT OCS.REVISED-COUNT @ OR
    R@ SRRO.ATTEMPT OCS.UNCHANGED-COUNT @ OR
    R@ SRRO.ATTEMPT OCS.REJECTED-COUNT @ OR
    R@ SRRO.ATTEMPT OCS.XIO-ERROR @ OR
    R@ SRRO.ATTEMPT OCS.CLEANUP-ERROR @ OR IF
        R> DROP 0 EXIT
    THEN
    R@ SRRO.ATTEMPT OCS.REQUESTED$
    DUP R@ SRRO.REQUESTED-U @ <> IF
        2DROP R> DROP 0 EXIT
    THEN
    R@ SRRO.REQUESTED R@ SRRO.REQUESTED-U @ COMPARE 0=
    R> DROP ;

: _SRRO-BEGIN-REQUEST!  ( owner -- status )
    >R
    R@ SRRO.BEGIN-REQUEST STREAMS-ACQUISITION-BEGIN-REQUEST-INIT
    DUP IF R> DROP EXIT THEN DROP
    R@ SRRO.SOURCE SSOURCE.ID
        R@ SRRO.BEGIN-REQUEST SABR.SOURCE-ID RID-COPY
    R@ SRRO.SOURCE SSOURCE.REVISION @
        R@ SRRO.BEGIN-REQUEST SABR.SOURCE-REVISION !
    R@ SRRO.NAMESPACE
        R@ SRRO.BEGIN-REQUEST SABR.NAMESPACE RID-COPY
    SRRO-PROVIDER-SYNDICATION
        R@ SRRO.BEGIN-REQUEST SABR.PROVIDER-KIND !
    R@ SRRO.REQUESTED
        R@ SRRO.BEGIN-REQUEST SABR.REQUESTED-A !
    R@ SRRO.REQUESTED-U @
        R@ SRRO.BEGIN-REQUEST SABR.REQUESTED-U !
    R@ SRRO.BEGIN-REQUEST
        STREAMS-ACQUISITION-BEGIN-REQUEST-VALID?
    IF STREAMS-ACQUISITION-S-OK
    ELSE STREAMS-ACQUISITION-S-INVALID THEN
    R> DROP ;

: _SRRO-CURRENT-SOURCE-EXACT?  ( owner -- flag )
    >R
    R@ SRRO.CURRENT-SOURCE @ DUP 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP R@ _SRRO-SOURCE-SPAN-SAFE? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP _SRRO-SOURCE-SUPPORTED? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    STREAMS-SOURCE-SIZE
    R@ SRRO.SOURCE STREAMS-SOURCE-SIZE COMPARE 0=
    R> DROP ;

: _SRRO-START-TERMINAL  ( xio-status owner -- status )
    >R
    R@ _SRRO-CLEAR-FACTS
    DUP R@ SRRO.DETAIL !
    DUP R@ SRRO.XIO-ERROR !
    DROP
    R@ SRRO.XIO-OP XIOO.CLEANUP-ERROR @
        R@ _SRRO-FIRST-CLEANUP!
    R@ _SRRO-RESET DROP
    R@ SRRO.CLEANUP-ERROR @ IF
        OCHK-ATTEMPT-FAILED OCHK-O-CLEANUP
        SRRO-PHASE-CLEANUP SRRO-S-CLEANUP
    ELSE
        OCHK-ATTEMPT-FAILED OCHK-O-TRANSPORT
        SRRO-PHASE-FAILED SRRO-S-EXTERNAL
    THEN
    R@ _SRRO-TERMINAL-SPEC!
    R> _SRRO-TERMINALIZE ;

: STREAMS-REPOSITORY-REFRESH-OWNER-START
  ( exact-source owner-id owner-generation owner -- status )
    >R
    R@ STREAMS-REPOSITORY-REFRESH-OWNER-VALID? 0= IF
        _SRRO-DROP3 R> DROP SRRO-S-INVALID EXIT
    THEN
    DUP R@ SRRO.CURRENT-OWNER-GENERATION !
    OVER R@ SRRO.CURRENT-OWNER-ID !
    2 PICK R@ SRRO.CURRENT-SOURCE !
    _SRRO-DROP3
    R@ SRRO.PHASE @ SRRO-PHASE-BLOCKED = IF
        R> DROP SRRO-S-BLOCKED EXIT
    THEN
    R@ SRRO.PHASE @ SRRO-PHASE-CLEANUP = IF
        R> DROP SRRO-S-CLEANUP EXIT
    THEN
    R@ SRRO.PHASE @ SRRO-PHASE-ACTIVE =
    R@ SRRO.ACCEPTED @ 0<> OR IF
        R> DROP SRRO-S-BUSY EXIT
    THEN
    R@ STREAMS-REPOSITORY-REFRESH-OWNER-AVAILABLE? 0= IF
        R> DROP SRRO-S-UNAVAILABLE EXIT
    THEN
    R@ SRRO.CURRENT-OWNER-ID @ 0=
    R@ SRRO.CURRENT-OWNER-GENERATION @ 0> 0= OR IF
        R> DROP SRRO-S-INVALID EXIT
    THEN
    R@ SRRO.CURRENT-SOURCE @ DUP 0= IF
        DROP R> DROP SRRO-S-INVALID EXIT
    THEN
    DUP R@ _SRRO-SOURCE-SPAN-SAFE? 0= IF
        DROP R> DROP SRRO-S-INVALID EXIT
    THEN
    DUP _SRRO-SOURCE-SUPPORTED? 0= IF
        DROP R> DROP SRRO-S-INVALID EXIT
    THEN
    DROP
    R@ SRRO.XIO-OP XIOO.STATE @ XIO-STATE-RESET <> IF
        R> DROP SRRO-S-BUSY EXIT
    THEN
    R@ SRRO.XIO-SERVICE @ XIO-ACTIVE?
    R@ SRRO.XIO-SERVICE @ XIOS.RETAINED @ 0<> OR IF
        R> DROP SRRO-S-BUSY EXIT
    THEN
    R@ SRRO.REQUEST-GENERATION @ _SRRO-CELL-MAX >= IF
        R> DROP SRRO-S-CAPACITY EXIT
    THEN

    0 R@ SRRO.ACCEPTED !
    0 R@ SRRO.ATTEMPT-PRESENT !
    0 R@ SRRO.REQUESTED-U !
    0 R@ SRRO.EFFECTIVE-U !
    R@ SRRO.ATTEMPT OCHK-SOURCE-SIZE 0 FILL
    R@ SRRO.CURRENT-SOURCE @ R@ SRRO.SOURCE
        STREAMS-SOURCE-SIZE MOVE
    R@ SRRO.SOURCE _SRRO-SOURCE-SUPPORTED? 0= IF
        R@ SRRO.SOURCE STREAMS-SOURCE-SIZE 0 FILL
        R> DROP SRRO-S-INVALID EXIT
    THEN
    R@ _SRRO-NAMESPACE!

    R@ SRRO.SOURCE R@ SRRO.PROVIDER @ SCONF-CONFIGURE
    DUP R@ SRRO.LAST-AUTHORITY-STATUS !
    DUP SCONF-S-OK <> IF
        DUP _SRRO-SCONF>STATUS
        SWAP
        SRRO-PHASE-FAILED -ROT
        R> _SRRO-MARK EXIT
    THEN DROP
    R@ _SRRO-CURRENT-SOURCE-EXACT? 0= IF
        SRRO-PHASE-FAILED SRRO-S-STALE SCONF-S-INVALID
        R> _SRRO-MARK EXIT
    THEN
    R@ _SRRO-NAMESPACE!
    R@ SRRO.PROVIDER @ SCONF-REQUESTED$
    DUP R@ SRRO.REQUESTED-U !
    DUP 1 < OVER OCHK-URI-MAX > OR IF
        2DROP
        SRRO-PHASE-FAILED SRRO-S-CAPACITY SCONF-S-CAPACITY
        R> _SRRO-MARK EXIT
    THEN
    OVER 0= IF
        2DROP
        SRRO-PHASE-FAILED SRRO-S-INVALID SCONF-S-INVALID
        R> _SRRO-MARK EXIT
    THEN
    2DUP MSPAN-NONWRAPPING? 0= IF
        2DROP
        SRRO-PHASE-FAILED SRRO-S-INVALID SCONF-S-INVALID
        R> _SRRO-MARK EXIT
    THEN
    2DUP UTF8-VALID? 0= IF
        2DROP
        SRRO-PHASE-FAILED SRRO-S-INVALID SCONF-S-INVALID
        R> _SRRO-MARK EXIT
    THEN
    R@ SRRO.REQUESTED SWAP MOVE

    R@ _SRRO-BEGIN-REQUEST!
    DUP R@ SRRO.LAST-ACQUISITION-STATUS !
    DUP R@ SRRO.LAST-AUTHORITY-STATUS !
    DUP IF
        DUP _SRRO-ACQUISITION>STATUS
        SWAP
        SRRO-PHASE-FAILED -ROT
        R> _SRRO-MARK EXIT
    THEN DROP
    R@ SRRO.BEGIN-REQUEST
    R@ SRRO.ATTEMPT
    R@ SRRO.REPOSITORY @
    R@ SRRO.REPO-WORK @
    R@ SRRO.ACQUISITION-WORK
        STREAMS-ACQUISITION-BEGIN
    DUP R@ SRRO.LAST-ACQUISITION-STATUS !
    DUP R@ SRRO.LAST-AUTHORITY-STATUS !
    DUP IF
        DUP _SRRO-ACQUISITION>STATUS
        SWAP
        SRRO-PHASE-FAILED -ROT
        R> _SRRO-MARK EXIT
    THEN DROP

    -1 R@ SRRO.ACCEPTED !
    -1 R@ SRRO.ATTEMPT-PRESENT !
    R@ SRRO.CURRENT-OWNER-ID @ R@ SRRO.OWNER-ID !
    R@ SRRO.CURRENT-OWNER-GENERATION @
        R@ SRRO.OWNER-GENERATION !
    R@ SRRO.REQUEST-GENERATION @ 1+
        R@ SRRO.REQUEST-GENERATION !
    R@ _SRRO-ACCEPTED-EXACT? 0= IF
        R@ _SRRO-CLEAR-FACTS
        OCHK-ATTEMPT-INDETERMINATE OCHK-O-INDETERMINATE
        SRRO-PHASE-BLOCKED SRRO-S-INDETERMINATE
        R@ _SRRO-TERMINAL-SPEC!
        R> _SRRO-TERMINALIZE EXIT
    THEN

    R@ SRRO.XIO-SERVICE @
    R@ SRRO.OWNER-ID @
    R@ SRRO.OWNER-GENERATION @
    R@ SRRO.REQUEST-GENERATION @
    MS@ STREAMS-REPOSITORY-REFRESH-TIMEOUT-MS +
    R@ SRRO.PROVIDER @
    ['] SCONF-XIO-START
    ['] SCONF-XIO-POLL
    ['] SCONF-XIO-CANCEL
    ['] SCONF-XIO-WIPE
    R@ SRRO.XIO-OP XIO-OP-CONFIGURE
    DUP R@ SRRO.SCRATCH-STATUS !
    DUP XIO-S-OK <> IF
        R> _SRRO-START-TERMINAL EXIT
    THEN DROP
    R@ SRRO.XIO-SERVICE @ R@ SRRO.XIO-OP XIO-SUBMIT
    DUP R@ SRRO.SCRATCH-STATUS !
    DUP XIO-S-OK <> IF
        R> _SRRO-START-TERMINAL EXIT
    THEN DROP
    SRRO-PHASE-ACTIVE SRRO-S-OK 0
    R> _SRRO-MARK ;

\ ---------------------------------------------------------------------
\ Exact live evidence and terminal paths
\ ---------------------------------------------------------------------

: _SRRO-XIO-EXACT?  ( owner -- flag )
    >R
    R@ SRRO.OWNER-ID @
    R@ SRRO.OWNER-GENERATION @
    R@ SRRO.REQUEST-GENERATION @
    R@ SRRO.XIO-OP XIO-OP-MATCH?
    R> DROP ;

: _SRRO-SERVICE-OWNED?  ( owner -- flag )
    SRRO.XIO-SERVICE @
    DUP XIO-SERVICE-BOUND? 0= IF DROP 0 EXIT THEN
    XIO-SERVICE-OWNER? ;

: _SRRO-XIO-TOPOLOGY?  ( owner -- flag )
    >R
    R@ SRRO.XIO-OP XIOO.STATE @
    CASE
        XIO-STATE-ACTIVE OF
            R@ SRRO.XIO-SERVICE @ XIOS.ACTIVE @
                R@ SRRO.XIO-OP =
            R@ SRRO.XIO-SERVICE @ XIOS.RETAINED @ 0= AND
        ENDOF
        XIO-STATE-SUCCEEDED OF
            R@ SRRO.XIO-SERVICE @ XIOS.ACTIVE @ 0=
            R@ SRRO.XIO-SERVICE @ XIOS.RETAINED @
                R@ SRRO.XIO-OP = AND
            R@ SRRO.XIO-OP XIOO.RESULT @
                R@ SRRO.PROVIDER @ = AND
        ENDOF
        XIO-STATE-FAILED OF
            R@ SRRO.XIO-SERVICE @ XIOS.ACTIVE @ 0=
            R@ SRRO.XIO-SERVICE @ XIOS.RETAINED @ 0= AND
        ENDOF
        XIO-STATE-CANCELLED OF
            R@ SRRO.XIO-SERVICE @ XIOS.ACTIVE @ 0=
            R@ SRRO.XIO-SERVICE @ XIOS.RETAINED @ 0= AND
        ENDOF
        XIO-STATE-TIMED-OUT OF
            R@ SRRO.XIO-SERVICE @ XIOS.ACTIVE @ 0=
            R@ SRRO.XIO-SERVICE @ XIOS.RETAINED @ 0= AND
        ENDOF
        XIO-STATE-RESET OF
            R@ SRRO.XIO-SERVICE @ XIOS.ACTIVE @ 0=
            R@ SRRO.XIO-SERVICE @ XIOS.RETAINED @ 0= AND
        ENDOF
        0 SWAP
    ENDCASE
    R> DROP ;

: _SRRO-BLOCK-INDETERMINATE  ( owner -- status )
    >R
    SRRO-PHASE-BLOCKED
    SRRO-S-INDETERMINATE
    SRRO-S-INDETERMINATE
    R> _SRRO-MARK ;

: _SRRO-CANCEL-ACTIVE  ( owner -- )
    >R
    R@ SRRO.XIO-OP XIOO.STATE @ XIO-STATE-ACTIVE = IF
        R@ SRRO.XIO-SERVICE @ R@ SRRO.XIO-OP XIO-CANCEL DROP
    THEN
    R> DROP ;

: _SRRO-TERMINATE-STALE  ( owner -- status )
    >R
    R@ _SRRO-CLEAR-FACTS
    R@ _SRRO-CANCEL-ACTIVE
    R@ SRRO.XIO-OP XIOO.ERROR @ R@ SRRO.XIO-ERROR !
    R@ _SRRO-RESET DROP
    R@ SRRO.CLEANUP-ERROR @ IF
        OCHK-ATTEMPT-FAILED OCHK-O-CLEANUP
        SRRO-PHASE-CLEANUP SRRO-S-CLEANUP
    ELSE
        OCHK-ATTEMPT-FAILED OCHK-O-STALE
        SRRO-PHASE-STALE SRRO-S-STALE
    THEN
    R@ _SRRO-TERMINAL-SPEC!
    R> _SRRO-TERMINALIZE ;

: _SRRO-TERMINATE-XIO  ( owner -- status )
    >R
    R@ _SRRO-CLEAR-FACTS
    R@ _SRRO-CAPTURE-PROVIDER
    R@ SRRO.XIO-OP XIOO.STATE @ R@ SRRO.SCRATCH-STATE !
    R@ _SRRO-CANCEL-ACTIVE
    R@ SRRO.XIO-OP XIOO.ERROR @ R@ SRRO.XIO-ERROR !
    R@ _SRRO-RESET DROP
    R@ SRRO.CLEANUP-ERROR @ IF
        OCHK-ATTEMPT-FAILED OCHK-O-CLEANUP
        SRRO-PHASE-CLEANUP SRRO-S-CLEANUP
    ELSE
        R@ SRRO.SCRATCH-STATE @ XIO-STATE-CANCELLED = IF
            OCHK-ATTEMPT-CANCELLED OCHK-O-CANCELLED
            SRRO-PHASE-CANCELLED SRRO-S-CANCELLED
        ELSE
            OCHK-ATTEMPT-FAILED
            R@ SRRO.PROVIDER-OUTCOME @ _SRRO-PROVIDER>OUTCOME
            SRRO-PHASE-FAILED SRRO-S-EXTERNAL
        THEN
    THEN
    R@ _SRRO-TERMINAL-SPEC!
    R> _SRRO-TERMINALIZE ;

: _SRRO-TERMINATE-PROVIDER  ( owner -- status )
    >R
    R@ _SRRO-CLEAR-FACTS
    R@ _SRRO-CAPTURE-PROVIDER
    R@ SRRO.XIO-OP XIOO.ERROR @ R@ SRRO.XIO-ERROR !
    R@ _SRRO-RESET DROP
    R@ SRRO.DECODER @ STREAMS-SYNDICATION-DECODER-RESET DROP
    R@ SRRO.CLEANUP-ERROR @ IF
        OCHK-ATTEMPT-FAILED OCHK-O-CLEANUP
        SRRO-PHASE-CLEANUP SRRO-S-CLEANUP
    ELSE
        OCHK-ATTEMPT-FAILED
        R@ SRRO.PROVIDER-OUTCOME @ _SRRO-PROVIDER>OUTCOME
        SRRO-PHASE-FAILED SRRO-S-EXTERNAL
    THEN
    R@ _SRRO-TERMINAL-SPEC!
    R> _SRRO-TERMINALIZE ;

: _SRRO-TERMINATE-DECODE  ( decode-status owner -- status )
    >R
    R@ _SRRO-CLEAR-FACTS
    R@ _SRRO-CAPTURE-PROVIDER
    DUP R@ SRRO.DECODE-STATUS !
    DROP
    R@ SRRO.XIO-OP XIOO.ERROR @ R@ SRRO.XIO-ERROR !
    R@ _SRRO-RESET DROP
    R@ SRRO.DECODER @ STREAMS-SYNDICATION-DECODER-RESET DROP
    R@ SRRO.CLEANUP-ERROR @ IF
        OCHK-ATTEMPT-FAILED OCHK-O-CLEANUP
        SRRO-PHASE-CLEANUP SRRO-S-CLEANUP
    ELSE
        R@ SRRO.DECODE-STATUS @ SYNDEC-S-CAPACITY = IF
            OCHK-ATTEMPT-FAILED OCHK-O-CAPACITY
            SRRO-PHASE-FAILED SRRO-S-CAPACITY
        ELSE
            OCHK-ATTEMPT-FAILED OCHK-O-DECODE
            SRRO-PHASE-FAILED SRRO-S-DECODE
        THEN
    THEN
    R@ _SRRO-TERMINAL-SPEC!
    R> _SRRO-TERMINALIZE ;

: _SRRO-TERMINATE-CANCEL  ( owner -- status )
    >R
    R@ _SRRO-CLEAR-FACTS
    R@ _SRRO-CAPTURE-PROVIDER
    R@ _SRRO-CANCEL-ACTIVE
    R@ SRRO.XIO-OP XIOO.ERROR @ R@ SRRO.XIO-ERROR !
    R@ _SRRO-RESET DROP
    R@ SRRO.DECODER @ STREAMS-SYNDICATION-DECODER-RESET DROP
    R@ SRRO.CLEANUP-ERROR @ IF
        OCHK-ATTEMPT-CANCELLED OCHK-O-CLEANUP
        SRRO-PHASE-CLEANUP SRRO-S-CLEANUP
    ELSE
        OCHK-ATTEMPT-CANCELLED OCHK-O-CANCELLED
        SRRO-PHASE-CANCELLED SRRO-S-CANCELLED
    THEN
    R@ _SRRO-TERMINAL-SPEC!
    R> _SRRO-TERMINALIZE ;

\ ---------------------------------------------------------------------
\ APPLY cleanup and exact post-cleanup runtime revalidation
\ ---------------------------------------------------------------------

: _SRRO-APPLY-CLEANUP  ( owner -- cleanup-error )
    _SRRO-RESET ;

: _SRRO-APPLY-REVALIDATE  ( frozen-request owner -- exact? )
    >R
    R@ 0= IF DROP R> DROP 0 EXIT THEN
    R@ SRRO.MAGIC @ _SRRO-MAGIC <> IF DROP R> DROP 0 EXIT THEN
    R@ SRRO.SELF @ R@ <> IF DROP R> DROP 0 EXIT THEN
    R@ SRRO.REVALIDATE-ARMED @ 0= IF DROP R> DROP 0 EXIT THEN
    R@ SRRO.CLEANUP-DONE @ 0= IF DROP R> DROP 0 EXIT THEN
    R@ SRRO.PHASE @ SRRO-PHASE-ACTIVE <> IF
        DROP R> DROP 0 EXIT
    THEN
    R@ SRRO.ACCEPTED @ 0= IF DROP R> DROP 0 EXIT THEN
    R@ SRRO.CURRENT-OWNER-ID @ R@ SRRO.OWNER-ID @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    R@ SRRO.CURRENT-OWNER-GENERATION @
    R@ SRRO.OWNER-GENERATION @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    R@ _SRRO-CURRENT-SOURCE-EXACT? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    R@ _SRRO-NAMESPACE!
    R@ SRRO.NAMESPACE
    R@ SRRO.ATTEMPT OCS.NAMESPACE RID= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAPAR.COMPONENT-INSTANCE @ R@ SRRO.OWNER-ID @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAPAR.COMPONENT-GENERATION @
    R@ SRRO.OWNER-GENERATION @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAPAR.REQUEST-GENERATION @
    R@ SRRO.REQUEST-GENERATION @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAPAR.SOURCE-ID
    R@ SRRO.ATTEMPT OCS.SOURCE-ID RID= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAPAR.SOURCE-REVISION @
    R@ SRRO.ATTEMPT OCS.SOURCE-REVISION @ <> IF
        DROP R> DROP 0 EXIT
    THEN
    DUP SAPAR.ATTEMPT-ID
    R@ SRRO.ATTEMPT OCS.ATTEMPT-ID RID= 0= IF
        DROP R> DROP 0 EXIT
    THEN
    SAPAR.REQUEST-SEAL
    R@ SRRO.ATTEMPT OCS.REQUEST-SEAL RID= 0= IF
        R> DROP 0 EXIT
    THEN
    R@ SRRO.XIO-OP XIOO.STATE @ XIO-STATE-RESET <> IF
        R> DROP 0 EXIT
    THEN
    R@ SRRO.XIO-SERVICE @ DUP XIO-SERVICE-BOUND? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    XIO-SERVICE-OWNER? 0= IF
        R> DROP 0 EXIT
    THEN
    R@ SRRO.XIO-SERVICE @ XIO-ACTIVE? IF
        R> DROP 0 EXIT
    THEN
    R@ SRRO.XIO-SERVICE @ XIOS.RETAINED @ 0=
    R> DROP ;

: _SRRO-APPLY-REQUEST!  ( owner -- status )
    >R
    R@ SRRO.APPLY-REQUEST STREAMS-APPLY-REQUEST-INIT
    DUP IF R> DROP EXIT THEN DROP
    R@ SRRO.ATTEMPT OCS.SOURCE-ID
        R@ SRRO.APPLY-REQUEST SAPAR.SOURCE-ID RID-COPY
    R@ SRRO.ATTEMPT OCS.SOURCE-REVISION @
        R@ SRRO.APPLY-REQUEST SAPAR.SOURCE-REVISION !
    R@ SRRO.ATTEMPT OCS.ATTEMPT-ID
        R@ SRRO.APPLY-REQUEST SAPAR.ATTEMPT-ID RID-COPY
    R@ SRRO.ATTEMPT OCS.REQUEST-SEAL
        R@ SRRO.APPLY-REQUEST SAPAR.REQUEST-SEAL RID-COPY
    R@ SRRO.OWNER-ID @
        R@ SRRO.APPLY-REQUEST SAPAR.COMPONENT-INSTANCE !
    R@ SRRO.OWNER-GENERATION @
        R@ SRRO.APPLY-REQUEST SAPAR.COMPONENT-GENERATION !
    R@ SRRO.REQUEST-GENERATION @
        R@ SRRO.APPLY-REQUEST SAPAR.REQUEST-GENERATION !
    R@ SRRO.EFFECTIVE
        R@ SRRO.APPLY-REQUEST SAPAR.EFFECTIVE-A !
    R@ SRRO.EFFECTIVE-U @
        R@ SRRO.APPLY-REQUEST SAPAR.EFFECTIVE-U !
    R@ SRRO.SCRATCH-CANDIDATES @
        R@ SRRO.APPLY-REQUEST SAPAR.CANDIDATES-A !
    R@ SRRO.SCRATCH-COUNT @
        R@ SRRO.APPLY-REQUEST SAPAR.CANDIDATE-COUNT !
    R@ _SRRO-FINISHED-MS
        R@ SRRO.APPLY-REQUEST SAPAR.FINISHED-MS !
    R@ SRRO.DETAIL @
        R@ SRRO.APPLY-REQUEST SAPAR.DETAIL !
    R@ SRRO.HTTP-STATUS @
        R@ SRRO.APPLY-REQUEST SAPAR.HTTP-STATUS !
    SYNDEC-S-OK
        R@ SRRO.APPLY-REQUEST SAPAR.DECODE-STATUS !
    ['] _SRRO-APPLY-CLEANUP
        R@ SRRO.APPLY-REQUEST SAPAR.CLEANUP-XT !
    R@ R@ SRRO.APPLY-REQUEST SAPAR.CLEANUP-CONTEXT !
    ['] _SRRO-APPLY-REVALIDATE
        R@ SRRO.APPLY-REQUEST SAPAR.REVALIDATE-XT !
    R@ R@ SRRO.APPLY-REQUEST SAPAR.REVALIDATE-CONTEXT !
    R@ SRRO.APPLY-REQUEST STREAMS-APPLY-REQUEST-VALID?
    IF STREAMS-APPLY-S-OK ELSE STREAMS-APPLY-S-INVALID THEN
    R> DROP ;

: _SRRO-MARK-APPLY-FAILURE  ( owner -- status )
    >R
    0 R@ SRRO.ACCEPTED !
    R@ SRRO.ATTEMPT OCS.OUTCOME @ DUP OCHK-O-CLEANUP = IF
        DROP
        SRRO-PHASE-CLEANUP SRRO-S-CLEANUP
        R@ SRRO.CLEANUP-ERROR @ ?DUP
        0= IF R@ SRRO.LAST-APPLY-STATUS @ THEN
        R> _SRRO-MARK EXIT
    THEN
    DUP OCHK-O-STALE = IF
        DROP
        SRRO-PHASE-STALE SRRO-S-STALE
        R@ SRRO.LAST-APPLY-STATUS @
        R> _SRRO-MARK EXIT
    THEN
    DUP OCHK-O-CAPACITY = IF
        DROP
        SRRO-PHASE-FAILED SRRO-S-CAPACITY
        R@ SRRO.LAST-APPLY-STATUS @
        R> _SRRO-MARK EXIT
    THEN
    OCHK-O-DECODE = IF
        SRRO-PHASE-FAILED SRRO-S-DECODE
        R@ SRRO.LAST-APPLY-STATUS @
        R> _SRRO-MARK EXIT
    THEN
    SRRO-PHASE-FAILED
    R@ SRRO.LAST-APPLY-STATUS @ _SRRO-APPLY>STATUS
    R@ SRRO.LAST-APPLY-STATUS @
    R> _SRRO-MARK ;

: _SRRO-APPLY-RESULT  ( owner -- status )
    >R
    R@ SRRO.DECODER @ STREAMS-SYNDICATION-DECODER-RESET
        R@ SRRO.SCRATCH-TEMP !
    R@ SRRO.ATTEMPT OCS.STATE @
    DUP OCHK-ATTEMPT-SUCCEEDED = IF
        DROP
        0 R@ SRRO.ACCEPTED !
        R@ SRRO.SCRATCH-TEMP @ SYNDEC-S-OK <> IF
            SRRO-PHASE-CLEANUP SRRO-S-CLEANUP
            R@ SRRO.SCRATCH-TEMP @
            R> _SRRO-MARK EXIT
        THEN
        SRRO-PHASE-SUCCEEDED SRRO-S-OK 0
        R> _SRRO-MARK EXIT
    THEN
    DUP OCHK-ATTEMPT-FAILED = IF
        DROP R> _SRRO-MARK-APPLY-FAILURE EXIT
    THEN
    DROP
    R@ SRRO.CLEANUP-DONE @ 0= IF
        R@ _SRRO-RESET DROP
    THEN
    SRRO-PHASE-BLOCKED SRRO-S-BLOCKED
    R@ SRRO.CLEANUP-ERROR @ ?DUP
    0= IF R@ SRRO.LAST-APPLY-STATUS @ THEN
    R> _SRRO-MARK ;

\ ---------------------------------------------------------------------
\ Successful XIO decode and atomic APPLY
\ ---------------------------------------------------------------------

: _SRRO-SUCCESS  ( owner -- status )
    >R
    R@ _SRRO-CLEAR-FACTS
    R@ _SRRO-CAPTURE-PROVIDER
    R@ SRRO.PROVIDER-OUTCOME @ SCONF-O-OK <>
    R@ SRRO.PROVIDER @ SCONF-RESULT-VALID? 0= OR IF
        R> _SRRO-TERMINATE-PROVIDER EXIT
    THEN
    R@ SRRO.PROVIDER @ SCONF-EFFECTIVE$
    DUP R@ SRRO.EFFECTIVE-U !
    DUP 1 < OVER OCHK-URI-MAX > OR IF
        2DROP SYNDEC-S-CAPACITY R>
        _SRRO-TERMINATE-DECODE EXIT
    THEN
    OVER 0= IF
        2DROP SYNDEC-S-INVALID R>
        _SRRO-TERMINATE-DECODE EXIT
    THEN
    2DUP MSPAN-NONWRAPPING? 0= IF
        2DROP SYNDEC-S-INVALID R>
        _SRRO-TERMINATE-DECODE EXIT
    THEN
    2DUP UTF8-VALID? 0= IF
        2DROP SYNDEC-S-INVALID R>
        _SRRO-TERMINATE-DECODE EXIT
    THEN
    R@ SRRO.EFFECTIVE SWAP MOVE
    R@ SRRO.SOURCE SSOURCE.FORMAT @
    R@ SRRO.PROVIDER @
    R@ SRRO.DECODER @
        STREAMS-SYNDICATION-DECODE
    DUP R@ SRRO.DECODE-STATUS !
    DUP SYNDEC-S-OK <> IF
        R> _SRRO-TERMINATE-DECODE EXIT
    THEN DROP
    R@ SRRO.DECODER @ STREAMS-SYNDICATION-CANDIDATES
    DUP R@ SRRO.SCRATCH-COUNT !
    SWAP R@ SRRO.SCRATCH-CANDIDATES !
    DROP
    R@ SRRO.SCRATCH-COUNT @ DUP 0<
    SWAP OCHK-BATCH-MAX > OR IF
        SYNDEC-S-CAPACITY R> _SRRO-TERMINATE-DECODE EXIT
    THEN
    R@ SRRO.SCRATCH-COUNT @ 0= IF
        0 R@ SRRO.SCRATCH-CANDIDATES !
    ELSE
        R@ SRRO.SCRATCH-CANDIDATES @ 0= IF
            SYNDEC-S-INVALID R> _SRRO-TERMINATE-DECODE EXIT
        THEN
    THEN
    R@ _SRRO-APPLY-REQUEST!
    DUP R@ SRRO.LAST-APPLY-STATUS !
    DUP STREAMS-APPLY-S-OK <> IF
        DROP
        SYNDEC-S-INVALID R> _SRRO-TERMINATE-DECODE EXIT
    THEN DROP
    -1 R@ SRRO.REVALIDATE-ARMED !
    R@ SRRO.APPLY-REQUEST
    R@ SRRO.ATTEMPT
    R@ SRRO.REPOSITORY @
    R@ SRRO.REPO-WORK @
    R@ SRRO.APPLY-WORK
        STREAMS-APPLY
    DUP R@ SRRO.LAST-APPLY-STATUS !
    DUP R@ SRRO.LAST-AUTHORITY-STATUS !
    DROP
    0 R@ SRRO.REVALIDATE-ARMED !
    R> _SRRO-APPLY-RESULT ;

\ ---------------------------------------------------------------------
\ Public TICK and CANCEL
\ ---------------------------------------------------------------------

: STREAMS-REPOSITORY-REFRESH-OWNER-TICK
  ( current-source|0 owner-id owner-generation owner -- changed? status )
    >R
    R@ STREAMS-REPOSITORY-REFRESH-OWNER-VALID? 0= IF
        _SRRO-DROP3 R> DROP 0 SRRO-S-INVALID EXIT
    THEN
    DUP R@ SRRO.CURRENT-OWNER-GENERATION !
    OVER R@ SRRO.CURRENT-OWNER-ID !
    2 PICK R@ SRRO.CURRENT-SOURCE !
    _SRRO-DROP3
    R@ SRRO.PHASE @ SRRO-PHASE-ACTIVE <> IF
        R> DROP 0 SRRO-S-OK EXIT
    THEN
    R@ SRRO.ACCEPTED @ 0= IF
        R> DROP 0 SRRO-S-BLOCKED EXIT
    THEN
    R@ _SRRO-SERVICE-OWNED? 0= IF
        R> DROP 0 SRRO-S-UNAVAILABLE EXIT
    THEN
    R@ SRRO.CURRENT-OWNER-ID @ R@ SRRO.OWNER-ID @ <> IF
        R> DROP 0 SRRO-S-INVALID EXIT
    THEN
    R@ SRRO.CURRENT-OWNER-GENERATION @
    R@ SRRO.OWNER-GENERATION @ <> IF
        R> _SRRO-TERMINATE-STALE -1 SWAP EXIT
    THEN
    R@ _SRRO-CURRENT-SOURCE-EXACT? 0=
    R@ _SRRO-XIO-EXACT? 0= OR IF
        R> _SRRO-TERMINATE-STALE -1 SWAP EXIT
    THEN
    R@ _SRRO-XIO-TOPOLOGY? 0= IF
        R> _SRRO-TERMINATE-STALE -1 SWAP EXIT
    THEN
    R@ SRRO.XIO-OP XIOO.STATE @
    DUP XIO-STATE-ACTIVE = IF
        DROP
        R> DROP 0 SRRO-S-OK EXIT
    THEN
    DUP XIO-STATE-SUCCEEDED = IF
        DROP
        R> _SRRO-SUCCESS -1 SWAP EXIT
    THEN
    DUP XIO-STATE-RESET = IF
        DROP
        R> _SRRO-BLOCK-INDETERMINATE 0 SWAP EXIT
    THEN
    DROP
    R> _SRRO-TERMINATE-XIO -1 SWAP ;

: STREAMS-REPOSITORY-REFRESH-OWNER-CANCEL
  ( owner-id owner-generation owner -- changed? status )
    >R
    R@ STREAMS-REPOSITORY-REFRESH-OWNER-VALID? 0= IF
        2DROP R> DROP 0 SRRO-S-INVALID EXIT
    THEN
    DUP R@ SRRO.CURRENT-OWNER-GENERATION !
    OVER R@ SRRO.CURRENT-OWNER-ID !
    2DROP
    R@ SRRO.PHASE @ SRRO-PHASE-ACTIVE <>
    R@ SRRO.ACCEPTED @ 0= OR IF
        R> DROP 0 SRRO-S-INVALID EXIT
    THEN
    R@ _SRRO-SERVICE-OWNED? 0= IF
        R> DROP 0 SRRO-S-UNAVAILABLE EXIT
    THEN
    R@ SRRO.CURRENT-OWNER-ID @ R@ SRRO.OWNER-ID @ <>
    R@ SRRO.CURRENT-OWNER-GENERATION @
        R@ SRRO.OWNER-GENERATION @ <> OR IF
        R> DROP 0 SRRO-S-INVALID EXIT
    THEN
    R@ _SRRO-XIO-EXACT? 0= IF
        R> _SRRO-TERMINATE-STALE -1 SWAP EXIT
    THEN
    R@ _SRRO-XIO-TOPOLOGY? 0= IF
        R> _SRRO-TERMINATE-STALE -1 SWAP EXIT
    THEN
    R@ SRRO.XIO-OP XIOO.STATE @
    DUP XIO-STATE-RESET = IF
        DROP R> _SRRO-BLOCK-INDETERMINATE 0 SWAP EXIT
    THEN
    DUP XIO-STATE-FAILED =
    OVER XIO-STATE-CANCELLED = OR
    SWAP XIO-STATE-TIMED-OUT = OR IF
        R> _SRRO-TERMINATE-XIO -1 SWAP EXIT
    THEN
    R> _SRRO-TERMINATE-CANCEL -1 SWAP ;

\ ---------------------------------------------------------------------
\ RELEASE: terminalize if possible, release local resources only
\ ---------------------------------------------------------------------

: STREAMS-REPOSITORY-REFRESH-OWNER-RELEASE  ( owner -- status )
    DUP STREAMS-REPOSITORY-REFRESH-OWNER-VALID? 0= IF
        DROP SRRO-S-INVALID EXIT
    THEN
    >R
    SRRO-S-OK R@ SRRO.SCRATCH-STATUS !
    R@ SRRO.ACCEPTED @ IF
        R@ SRRO.PHASE @ SRRO-PHASE-BLOCKED = IF
            R@ SRRO.LAST-STATUS @ SRRO-S-INDETERMINATE = IF
                R> _SRRO-BLOCK-INDETERMINATE EXIT
            THEN
            R@ _SRRO-TERMINALIZE
        ELSE
            R@ _SRRO-SERVICE-OWNED? 0= IF
                R> DROP SRRO-S-UNAVAILABLE EXIT
            THEN
            R@ _SRRO-XIO-TOPOLOGY? 0= IF
                R> _SRRO-BLOCK-INDETERMINATE EXIT
            THEN
            R@ SRRO.XIO-OP XIOO.STATE @
            DUP XIO-STATE-RESET = IF
                DROP R> _SRRO-BLOCK-INDETERMINATE EXIT
            THEN
            DUP XIO-STATE-FAILED =
            OVER XIO-STATE-CANCELLED = OR
            SWAP XIO-STATE-TIMED-OUT = OR IF
                R@ _SRRO-TERMINATE-XIO
            ELSE
                R@ _SRRO-TERMINATE-CANCEL
            THEN
        THEN
        DUP SRRO-S-CLEANUP =
        OVER SRRO-S-BLOCKED = OR
        OVER SRRO-S-REPOSITORY = OR IF
            R@ SRRO.SCRATCH-STATUS !
        ELSE
            DROP
        THEN
    ELSE
        R@ SRRO.XIO-OP XIOO.STATE @ XIO-STATE-RESET <> IF
            R@ _SRRO-CLEAR-FACTS
            R@ _SRRO-CANCEL-ACTIVE
            R@ _SRRO-RESET ?DUP IF
                DROP SRRO-S-CLEANUP R@ SRRO.SCRATCH-STATUS !
            THEN
        THEN
    THEN
    R@ SRRO.PROVIDER @ ?DUP IF
        DUP SCONF-RELEASABLE? 0= IF
            DROP
            SRRO-PHASE-CLEANUP SRRO-S-CLEANUP
            R@ SRRO.CLEANUP-ERROR @
            R> _SRRO-MARK EXIT
        THEN
        SCONF-RELEASE
        DUP SCONF-S-OK <> IF
            SRRO-PHASE-CLEANUP SRRO-S-CLEANUP ROT
            R> _SRRO-MARK EXIT
        THEN
        DROP
    THEN
    0 R@ SRRO.PROVIDER !
    R@ SRRO.DECODER @ STREAMS-SYNDICATION-DECODER-FREE
    DUP SYNDEC-S-OK <> IF
        R@ STREAMS-REPOSITORY-REFRESH-OWNER-SIZE 0 FILL
        R> DROP
        DROP SRRO-S-CLEANUP EXIT
    THEN
    DROP
    0 R@ SRRO.DECODER !
    R@ SRRO.SCRATCH-STATUS @
    R@ STREAMS-REPOSITORY-REFRESH-OWNER-SIZE 0 FILL
    R> DROP ;
