\ =====================================================================
\  source-store.f - Typed source-registry snapshot adapter
\ =====================================================================
\  The shared fixed-snapshot core owns the exact 64-byte envelope, CRCs,
\  exact read, recovery, optimistic replacement, latch, and scratch wipe.
\  This adapter owns the unchanged path, status names, canonical registry
\  codec, and typed scratch.  The shared VFSNAP descriptor is embedded at
\  offset zero; typed accessors are direct views of that core state.
\ =====================================================================

PROVIDED akashic-streams-srcstore

REQUIRE source-registry.f
REQUIRE ../../../utils/fs/vfs-fixed-snapshot.f
REQUIRE ../../../concurrency/guard.f

\ =====================================================================
\  Public statuses and byte-stable V1 record
\ =====================================================================

0 CONSTANT SSSTORE-S-OK
1 CONSTANT SSSTORE-S-ABSENT
2 CONSTANT SSSTORE-S-CORRUPT
3 CONSTANT SSSTORE-S-UNSUPPORTED
4 CONSTANT SSSTORE-S-INVALID
5 CONSTANT SSSTORE-S-CAPACITY
6 CONSTANT SSSTORE-S-IO
7 CONSTANT SSSTORE-S-RECOVERY
8 CONSTANT SSSTORE-S-BUSY
9 CONSTANT SSSTORE-S-CONFLICT

1  CONSTANT STREAMS-SOURCE-STORE-FORMAT-V1
64 CONSTANT STREAMS-SOURCE-STORE-HEADER-SIZE
STREAMS-SOURCE-STORE-HEADER-SIZE STREAMS-SOURCE-REGISTRY-SIZE +
    CONSTANT STREAMS-SOURCE-STORE-RECORD-MAX

CREATE _SSSTORE-RECORD-MAGIC
65 C, 75 C, 83 C, 83 C, 83 C, 48 C, 48 C, 49 C,  \ "AKSSS001"

\ =====================================================================
\  Descriptor: embedded core, per-instance scratch
\ =====================================================================

0 CONSTANT _SSS-CORE
_SSS-CORE VFSNAP-STORE-SIZE + CONSTANT _SSS-SCRATCH
_SSS-SCRATCH STREAMS-SOURCE-STORE-RECORD-MAX +
    CONSTANT _SSS-LOAD-GENERATION
_SSS-LOAD-GENERATION 8 + CONSTANT STREAMS-SOURCE-STORE-SIZE

: STREAMS-SOURCE-STORE.CORE        ( store -- core ) _SSS-CORE + ;
: STREAMS-SOURCE-STORE.MAGIC       ( store -- a )
    STREAMS-SOURCE-STORE.CORE VFSNAP.MAGIC ;
: STREAMS-SOURCE-STORE.VFS         ( store -- a )
    STREAMS-SOURCE-STORE.CORE VFSNAP.VFS ;
: STREAMS-SOURCE-STORE.FLAGS       ( store -- a )
    STREAMS-SOURCE-STORE.CORE VFSNAP.FLAGS ;
: STREAMS-SOURCE-STORE.LAST-STATUS ( store -- a )
    STREAMS-SOURCE-STORE.CORE VFSNAP.LAST-STATUS ;
: STREAMS-SOURCE-STORE.LAST-VREPL  ( store -- a )
    STREAMS-SOURCE-STORE.CORE VFSNAP.LAST-VREPL ;
: STREAMS-SOURCE-STORE.REPLACE     ( store -- replacement )
    STREAMS-SOURCE-STORE.CORE VFSNAP.REPLACE ;
: STREAMS-SOURCE-STORE.SCRATCH     ( store -- scratch ) _SSS-SCRATCH + ;
: STREAMS-SOURCE-STORE.LOAD-GENERATION  ( store -- a )
    _SSS-LOAD-GENERATION + ;

: STREAMS-SOURCE-STORE-SCRATCH-WIPE  ( store -- )
    STREAMS-SOURCE-STORE.SCRATCH STREAMS-SOURCE-STORE-RECORD-MAX 0 FILL ;

: STREAMS-SOURCE-STORE-TARGET$  ( -- a u ) S" /streams-sources.bin" ;
: STREAMS-SOURCE-STORE-PATH$  ( store -- a u )
    STREAMS-SOURCE-STORE.CORE VFSNAP-PATH$ ;
: STREAMS-SOURCE-STORE-BLOCKED?  ( store -- flag )
    STREAMS-SOURCE-STORE.CORE VFSNAP-BLOCKED? ;

\ =====================================================================
\  Static typed specification and callback-private state
\ =====================================================================

CREATE _SSSTORE-SPEC VFSNAP-SPEC-SIZE ALLOT
_SSSTORE-SPEC VFSNAP-SPEC.PRIVATE CONSTANT _SSSTORE-PRIVATE-RANGES
_SSSTORE-SPEC VFSNAP-SPEC.PRIVATE-N CONSTANT _SSSTORE-PRIVATE-RANGE-N
CREATE _SSSTORE-PRIVATE-BEGIN 0 ALLOT

GUARD _streams-source-store-guard

VARIABLE _SSCB-CONTEXT
VARIABLE _SSCB-PAYLOAD
VARIABLE _SSCB-PAYLOAD-U
VARIABLE _SSCB-GENERATION
VARIABLE _SSSI-VFS
VARIABLE _SSSI-STORE
VARIABLE _SSSI-TARGET-A
VARIABLE _SSSI-TARGET-U
VARIABLE _SSSL-DESTINATION
VARIABLE _SSSL-CAPACITY
VARIABLE _SSSL-STORE
VARIABLE _SSSS-REGISTRY
VARIABLE _SSSS-EXPECTED
VARIABLE _SSSS-STORE

: _SSSTORE-UNUSED-SLOTS-ZERO?  ( registry -- flag )
    DUP SSREG.COUNT @ >R
    SSREG.RECORDS R@ STREAMS-SOURCE-SIZE * +
    STREAMS-SOURCE-MAX R> - STREAMS-SOURCE-SIZE * _SSOURCE-ZERO? ;

: _SSSTORE-ENCODE-PAYLOAD
  ( registry payload-a payload-u next-generation -- status )
    _SSCB-GENERATION ! _SSCB-PAYLOAD-U !
    _SSCB-PAYLOAD ! _SSCB-CONTEXT !
    _SSCB-PAYLOAD-U @ STREAMS-SOURCE-REGISTRY-SIZE <> IF
        VFSNAP-S-CAPACITY EXIT
    THEN
    _SSCB-CONTEXT @ STREAMS-SOURCE-REGISTRY-VALID? 0= IF
        VFSNAP-S-INVALID EXIT
    THEN
    _SSCB-CONTEXT @ SSREG.GENERATION @ _SSCB-GENERATION @ <> IF
        VFSNAP-S-INVALID EXIT
    THEN
    \ The core supplied an all-zero payload.  Copy the registry header and
    \ live prefix only so unused fixed slots remain canonical zero bytes.
    _SSCB-CONTEXT @ _SSCB-PAYLOAD @ _SSR-RECORDS CMOVE
    _SSCB-CONTEXT @ SSREG.RECORDS
        _SSCB-PAYLOAD @ _SSR-RECORDS +
        _SSCB-CONTEXT @ SSREG.COUNT @ STREAMS-SOURCE-SIZE * CMOVE
    VFSNAP-S-OK ;

: _SSSTORE-VALIDATE-PAYLOAD
  ( payload-a payload-u envelope-generation -- status )
    _SSCB-GENERATION ! _SSCB-PAYLOAD-U ! _SSCB-PAYLOAD !
    _SSCB-PAYLOAD-U @ STREAMS-SOURCE-REGISTRY-SIZE <> IF
        VFSNAP-S-CORRUPT EXIT
    THEN
    _SSCB-PAYLOAD @ SSREG.MAGIC @ _SSREG-MAGIC <> IF
        VFSNAP-S-CORRUPT EXIT
    THEN
    _SSCB-PAYLOAD @ SSREG.ABI @ STREAMS-SOURCE-REGISTRY-ABI <> IF
        VFSNAP-S-UNSUPPORTED EXIT
    THEN
    _SSCB-PAYLOAD @ STREAMS-SOURCE-REGISTRY-VALID? 0= IF
        VFSNAP-S-CORRUPT EXIT
    THEN
    _SSCB-PAYLOAD @ _SSSTORE-UNUSED-SLOTS-ZERO? 0= IF
        VFSNAP-S-CORRUPT EXIT
    THEN
    _SSCB-PAYLOAD @ SSREG.GENERATION @ _SSCB-GENERATION @ <> IF
        VFSNAP-S-CORRUPT EXIT
    THEN
    VFSNAP-S-OK ;

: _SSSTORE-VFSNAP>STATUS  ( snapshot-status -- source-status )
    CASE
        VFSNAP-S-OK OF SSSTORE-S-OK ENDOF
        VFSNAP-S-ABSENT OF SSSTORE-S-ABSENT ENDOF
        VFSNAP-S-CORRUPT OF SSSTORE-S-CORRUPT ENDOF
        VFSNAP-S-UNSUPPORTED OF SSSTORE-S-UNSUPPORTED ENDOF
        VFSNAP-S-INVALID OF SSSTORE-S-INVALID ENDOF
        VFSNAP-S-CAPACITY OF SSSTORE-S-CAPACITY ENDOF
        VFSNAP-S-IO OF SSSTORE-S-IO ENDOF
        VFSNAP-S-RECOVERY OF SSSTORE-S-RECOVERY ENDOF
        VFSNAP-S-BUSY OF SSSTORE-S-BUSY ENDOF
        VFSNAP-S-CONFLICT OF SSSTORE-S-CONFLICT ENDOF
        SSSTORE-S-RECOVERY SWAP
    ENDCASE ;

: _SSSTORE-SYNC  ( snapshot-status store -- source-status )
    DROP _SSSTORE-VFSNAP>STATUS ;

\ =====================================================================
\  Hostile-alias preflight
\ =====================================================================

: _SSSTORE-SPAN-VALID?  ( address length -- flag )
    DUP 0< IF 2DROP 0 EXIT THEN
    OVER 0= IF 2DROP 0 EXIT THEN
    DUP 0= IF 2DROP -1 EXIT THEN
    _VFSNAP-SPAN-VALID? ;
: _SSSTORE-RANGES-OVERLAP?  ( a1 u1 a2 u2 -- flag )
    _VFSNAP-RANGES-OVERLAP? ;

: _SSSTORE-PRIVATE-ALIASES?  ( address length -- flag )
    2DUP _SSSTORE-SPEC _VFSNAP-ALL-PRIVATE-ALIASES? IF
        2DROP -1 EXIT
    THEN
    _SSSTORE-SPEC VFSNAP-SPEC-SIZE _SSSTORE-RANGES-OVERLAP? ;

: _SSSTORE-STORE-SPAN-SAFE?  ( store -- flag )
    DUP STREAMS-SOURCE-STORE-SIZE _SSSTORE-SPAN-VALID? 0= IF
        DROP 0 EXIT
    THEN
    DUP STREAMS-SOURCE-STORE-SIZE _SSSTORE-PRIVATE-ALIASES? 0= NIP ;

: _SSSTORE-IO-ALIASES?  ( address length store -- flag )
    >R
    R@ _SSSTORE-STORE-SPAN-SAFE? 0= IF 2DROP R> DROP -1 EXIT THEN
    2DUP _SSSTORE-SPAN-VALID? 0= IF 2DROP R> DROP 0 EXIT THEN
    2DUP R@ STREAMS-SOURCE-STORE-SIZE _SSSTORE-RANGES-OVERLAP? >R
    _SSSTORE-PRIVATE-ALIASES? R> OR R> DROP ;

: _SSSTORE-IO-SPAN-SAFE?  ( address length store -- flag )
    >R
    2DUP _SSSTORE-SPAN-VALID? R@ _SSSTORE-STORE-SPAN-SAFE? AND 0= IF
        2DROP R> DROP 0 EXIT
    THEN
    R> _SSSTORE-IO-ALIASES? 0= ;

: _SSSTORE-TARGET-SPAN-SAFE?  ( target-a target-u store -- flag )
    >R
    R@ _SSSTORE-STORE-SPAN-SAFE? 0= IF 2DROP R> DROP 0 EXIT THEN
    2DUP _SSSTORE-SPAN-VALID? 0= IF 2DROP R> DROP 0 EXIT THEN
    2DUP R@ STREAMS-SOURCE-STORE-SIZE _SSSTORE-RANGES-OVERLAP? >R
    _SSSTORE-PRIVATE-ALIASES? R> OR 0= R> DROP ;

: STREAMS-SOURCE-STORE-VALID?  ( store -- flag )
    DUP _SSSTORE-STORE-SPAN-SAFE? 0= IF DROP 0 EXIT THEN
    STREAMS-SOURCE-STORE.CORE VFSNAP-VALID? ;

\ =====================================================================
\  Lifecycle and unchanged typed operations
\ =====================================================================

: _STREAMS-SOURCE-STORE-INIT-AT
  ( target-a target-u vfs store -- status )
    _SSSI-STORE ! _SSSI-VFS ! _SSSI-TARGET-U ! _SSSI-TARGET-A !
    _SSSI-TARGET-A @ 0= _SSSI-TARGET-U @ 0< OR
    _SSSI-VFS @ 0= OR _SSSI-STORE @ 0= OR IF SSSTORE-S-INVALID EXIT THEN
    _SSSI-TARGET-A @ _SSSI-TARGET-U @ _SSSI-STORE @
        _SSSTORE-TARGET-SPAN-SAFE? 0= IF SSSTORE-S-INVALID EXIT THEN
    _SSSI-STORE @ STREAMS-SOURCE-STORE-SIZE 0 FILL
    _SSSI-TARGET-A @ _SSSI-TARGET-U @
        _SSSI-STORE @ STREAMS-SOURCE-STORE.SCRATCH
        STREAMS-SOURCE-STORE-RECORD-MAX
        _SSSI-VFS @ _SSSTORE-SPEC
        _SSSI-STORE @ STREAMS-SOURCE-STORE.CORE VFSNAP-INIT-AT
        _SSSI-STORE @ _SSSTORE-SYNC ;

' _STREAMS-SOURCE-STORE-INIT-AT CONSTANT _ssstore-init-at-xt
: STREAMS-SOURCE-STORE-INIT-AT
  ( target-a target-u vfs store -- status )
    2OVER 2OVER SWAP DROP _SSSTORE-TARGET-SPAN-SAFE? 0= IF
        2DROP 2DROP SSSTORE-S-INVALID EXIT
    THEN
    _ssstore-init-at-xt _streams-source-store-guard WITH-GUARD ;
: STREAMS-SOURCE-STORE-INIT  ( vfs store -- status )
    STREAMS-SOURCE-STORE-TARGET$ 2SWAP STREAMS-SOURCE-STORE-INIT-AT ;

: _STREAMS-SOURCE-STORE-RECOVER  ( store -- status )
    DUP STREAMS-SOURCE-STORE-VALID? 0= IF DROP SSSTORE-S-INVALID EXIT THEN
    DUP >R STREAMS-SOURCE-STORE.CORE VFSNAP-RECOVER R> _SSSTORE-SYNC ;

: _STREAMS-SOURCE-STORE-LOAD  ( destination capacity store -- status )
    _SSSL-STORE ! _SSSL-CAPACITY ! _SSSL-DESTINATION !
    _SSSL-STORE @ STREAMS-SOURCE-STORE-VALID? 0= IF
        SSSTORE-S-INVALID EXIT
    THEN
    _SSSL-DESTINATION @ _SSSL-CAPACITY @
        _SSSL-STORE @ STREAMS-SOURCE-STORE.LOAD-GENERATION
        _SSSL-STORE @ STREAMS-SOURCE-STORE.CORE VFSNAP-LOAD
        _SSSL-STORE @ _SSSTORE-SYNC ;

VARIABLE _SSLT-DESTINATION
VARIABLE _SSLT-CAPACITY
VARIABLE _SSLT-STORE

: _SSLT-CALL  ( -- status )
    _SSLT-DESTINATION @ _SSLT-CAPACITY @ _SSLT-STORE @
        _STREAMS-SOURCE-STORE-LOAD ;

: _STREAMS-SOURCE-STORE-LOAD-TERMINAL
  ( destination capacity store -- status )
    _SSLT-STORE ! _SSLT-CAPACITY ! _SSLT-DESTINATION !
    ['] _SSLT-CALL CATCH
    _SSLT-STORE @ DUP STREAMS-SOURCE-STORE-VALID? IF
        STREAMS-SOURCE-STORE-SCRATCH-WIPE
    ELSE DROP THEN
    DUP IF THROW THEN DROP ;

' _STREAMS-SOURCE-STORE-LOAD-TERMINAL CONSTANT _ssstore-load-xt
: STREAMS-SOURCE-STORE-LOAD  ( destination capacity store -- status )
    2 PICK 2 PICK 2 PICK _SSSTORE-IO-SPAN-SAFE? 0= IF
        2DROP DROP SSSTORE-S-INVALID EXIT
    THEN
    _ssstore-load-xt _streams-source-store-guard WITH-GUARD ;

: _STREAMS-SOURCE-STORE-SAVE  ( registry expected-generation store -- status )
    _SSSS-STORE ! _SSSS-EXPECTED ! _SSSS-REGISTRY !
    _SSSS-STORE @ STREAMS-SOURCE-STORE-VALID? 0= IF
        SSSTORE-S-INVALID EXIT
    THEN
    _SSSS-EXPECTED @ 0< IF SSSTORE-S-INVALID EXIT THEN
    _SSSS-STORE @ STREAMS-SOURCE-STORE-BLOCKED? IF
        _SSSS-STORE @ STREAMS-SOURCE-STORE.LAST-STATUS @ EXIT
    THEN
    _SSSS-REGISTRY @ STREAMS-SOURCE-REGISTRY-VALID? 0= IF
        SSSTORE-S-INVALID EXIT
    THEN
    _SSSS-EXPECTED @ 1+ DUP 0> 0= IF DROP SSSTORE-S-CAPACITY EXIT THEN
    _SSSS-REGISTRY @ SSREG.GENERATION @ <> IF SSSTORE-S-INVALID EXIT THEN
    _SSSS-REGISTRY @ _SSSS-EXPECTED @
        _SSSS-STORE @ STREAMS-SOURCE-STORE.CORE VFSNAP-SAVE
        _SSSS-STORE @ _SSSTORE-SYNC ;

\ Private test/golden helper; shared core still constructs the envelope.
: _STREAMS-SOURCE-STORE-ENCODE-INTO
  ( registry store -- length status )
    _SSSS-STORE ! _SSSS-REGISTRY !
    _SSSS-STORE @ STREAMS-SOURCE-STORE-VALID? 0= IF
        0 SSSTORE-S-INVALID EXIT
    THEN
    _SSSS-STORE @ STREAMS-SOURCE-STORE.CORE _VFSOP-STORE !
    _SSSS-REGISTRY @ _VFSS-CONTEXT !
    _SSSS-REGISTRY @ SSREG.GENERATION @ _VFSS-NEXT !
    _VFSNAP-ENCODE STREAMS-SOURCE-STORE-RECORD-MAX SWAP
        _SSSTORE-VFSNAP>STATUS ;

VARIABLE _SSST-REGISTRY
VARIABLE _SSST-EXPECTED
VARIABLE _SSST-STORE

: _SSST-CALL  ( -- status )
    _SSST-REGISTRY @ _SSST-EXPECTED @ _SSST-STORE @
        _STREAMS-SOURCE-STORE-SAVE ;

: _STREAMS-SOURCE-STORE-SAVE-TERMINAL
  ( registry expected-generation store -- status )
    _SSST-STORE ! _SSST-EXPECTED ! _SSST-REGISTRY !
    ['] _SSST-CALL CATCH
    _SSST-STORE @ DUP STREAMS-SOURCE-STORE-VALID? IF
        STREAMS-SOURCE-STORE-SCRATCH-WIPE
    ELSE DROP THEN
    DUP IF THROW THEN DROP ;

' _STREAMS-SOURCE-STORE-SAVE-TERMINAL CONSTANT _ssstore-save-xt
: STREAMS-SOURCE-STORE-SAVE  ( registry expected-generation store -- status )
    2 PICK STREAMS-SOURCE-REGISTRY-SIZE 2 PICK
        _SSSTORE-IO-SPAN-SAFE? 0= IF
        2DROP DROP SSSTORE-S-INVALID EXIT
    THEN
    _ssstore-save-xt _streams-source-store-guard WITH-GUARD ;

VARIABLE _SSRT-STORE

: _SSRT-CALL  ( -- status )
    _SSRT-STORE @ _STREAMS-SOURCE-STORE-RECOVER ;

: _STREAMS-SOURCE-STORE-RECOVER-TERMINAL  ( store -- status )
    DUP _SSRT-STORE !
    DROP ['] _SSRT-CALL CATCH
    _SSRT-STORE @ DUP STREAMS-SOURCE-STORE-VALID? IF
        STREAMS-SOURCE-STORE-SCRATCH-WIPE
    ELSE DROP THEN
    DUP IF THROW THEN DROP ;

' _STREAMS-SOURCE-STORE-RECOVER-TERMINAL CONSTANT _ssstore-recover-xt
: STREAMS-SOURCE-STORE-RECOVER  ( store -- status )
    DUP _SSSTORE-STORE-SPAN-SAFE? 0= IF DROP SSSTORE-S-INVALID EXIT THEN
    _ssstore-recover-xt _streams-source-store-guard WITH-GUARD ;

: _STREAMS-SOURCE-STORE-FINI  ( store -- status )
    DUP STREAMS-SOURCE-STORE-VALID? 0= IF DROP SSSTORE-S-INVALID EXIT THEN
    DUP STREAMS-SOURCE-STORE.CORE VFSNAP-FINI
    DUP VFSNAP-S-OK = IF
        DROP STREAMS-SOURCE-STORE-SIZE 0 FILL SSSTORE-S-OK
    ELSE
        NIP _SSSTORE-VFSNAP>STATUS
    THEN ;
' _STREAMS-SOURCE-STORE-FINI CONSTANT _ssstore-fini-xt
: STREAMS-SOURCE-STORE-FINI  ( store -- status )
    DUP _SSSTORE-STORE-SPAN-SAFE? 0= IF DROP SSSTORE-S-INVALID EXIT THEN
    _ssstore-fini-xt _streams-source-store-guard WITH-GUARD ;

CREATE _SSSTORE-PRIVATE-END 0 ALLOT

_SSSTORE-RECORD-MAGIC 8 STREAMS-SOURCE-STORE-FORMAT-V1
    STREAMS-SOURCE-REGISTRY-SIZE
    ' _SSSTORE-ENCODE-PAYLOAD ' _SSSTORE-VALIDATE-PAYLOAD _SSSTORE-SPEC
    VFSNAP-SPEC-INIT IF -4904 THROW THEN
_SSSTORE-PRIVATE-BEGIN _SSSTORE-PRIVATE-END _SSSTORE-PRIVATE-BEGIN -
    _SSSTORE-SPEC VFSNAP-SPEC-PRIVATE-ADD IF -4904 THROW THEN
_streams-source-registry-guard _SSRD-MOVE-N 8 + OVER -
    _SSSTORE-SPEC VFSNAP-SPEC-PRIVATE-ADD IF -4904 THROW THEN
_UD-CP
[DEFINED] _utf8-guard [IF]
    _utf8-guard _GRD-SIZE-SPIN +
[ELSE]
    _UN-IDX 8 +
[THEN]
OVER - _SSSTORE-SPEC VFSNAP-SPEC-PRIVATE-ADD IF -4904 THROW THEN
_SSSTORE-SPEC VFSNAP-SPEC-SEAL IF -4904 THROW THEN
