\ =====================================================================
\ streams.f - bounded communications and subscription applet
\ =====================================================================
\ The first slice is deliberately deterministic and offline.  It proves
\ timeline/thread navigation, local search, drafts, explicit item identities,
\ and the Desk capability surface before HTTP/XRPC and credentials are trusted.
\ =====================================================================

PROVIDED akashic-tui-streams

REQUIRE ../../app-desc.f
REQUIRE ../../app-shell.f
REQUIRE ../../uidl-tui.f
REQUIRE ../../draw.f
REQUIRE ../../region.f
REQUIRE ../../keys.f
REQUIRE ../../widget.f
REQUIRE ../../widgets/prompt.f
REQUIRE ../../../utils/string.f
REQUIRE ../../../atproto/feed-model.f
REQUIRE ../../../text/utf8.f
REQUIRE ../../../runtime/state-layout.f
REQUIRE ../../../interop/capability.f
REQUIRE ../../../interop/request-bus.f
REQUIRE draft-store.f

BFM-TEXT-CAP CONSTANT _STM-DRAFT-CAP
BFM-TEXT-CAP CONSTANT _STM-PROMPT-CAP
96 CONSTANT _STM-QUERY-CAP

0 CONSTANT _STM-PM-NONE
1 CONSTANT _STM-PM-SEARCH
2 CONSTANT _STM-PM-DRAFT

0 CONSTANT _STM-V-TIMELINE
1 CONSTANT _STM-V-THREAD

\ A zero-filled CINST is deliberately volatile for direct component tests and
\ embedding contexts that have not run the app lifecycle.  Normal app init
\ moves to READY only after binding and loading the durable store.
0 CONSTANT _STM-DP-VOLATILE
1 CONSTANT _STM-DP-READY
2 CONSTANT _STM-DP-BLOCKED

VARIABLE _STM-CURRENT-STATE
VARIABLE _STM-CURRENT-INSTANCE
0 _STM-CURRENT-STATE ! 0 _STM-CURRENT-INSTANCE !

CMP-LAYOUT-BEGIN
_STM-CURRENT-STATE CMP-CELL: _STM-E-BODY
_STM-CURRENT-STATE CMP-CELL: _STM-E-SBAR
_STM-CURRENT-STATE CMP-CELL: _STM-E-SBAR-VIEW
_STM-CURRENT-STATE CMP-CELL: _STM-E-SBAR-STATE
_STM-CURRENT-STATE 40 CMP-FIELD: _STM-PANEL
_STM-CURRENT-STATE CMP-CELL: _STM-PANEL-RGN
_STM-CURRENT-STATE CMP-CELL: _STM-PROMPT
_STM-CURRENT-STATE CMP-CELL: _STM-PROMPT-RGN
_STM-CURRENT-STATE CMP-CELL: _STM-PROMPT-MODE
_STM-CURRENT-STATE _STM-PROMPT-CAP CMP-FIELD: _STM-PROMPT-BUF
_STM-CURRENT-STATE CMP-CELL: _STM-VIEW
_STM-CURRENT-STATE CMP-CELL: _STM-SELECTED
_STM-CURRENT-STATE CMP-CELL: _STM-TOP
_STM-CURRENT-STATE CMP-CELL: _STM-THREAD-TOP
_STM-CURRENT-STATE CMP-CELL: _STM-THREAD-ROOT-U
_STM-CURRENT-STATE BFM-URI-CAP CMP-FIELD: _STM-THREAD-ROOT-BUF
_STM-CURRENT-STATE _STM-QUERY-CAP CMP-FIELD: _STM-SEARCH-BUF
_STM-CURRENT-STATE CMP-CELL: _STM-SEARCH-U
_STM-CURRENT-STATE CMP-CELL: _STM-SEARCH-MATCH-N
_STM-CURRENT-STATE _STM-DRAFT-CAP CMP-FIELD: _STM-DRAFT-BUF
_STM-CURRENT-STATE CMP-CELL: _STM-DRAFT-U
_STM-CURRENT-STATE CMP-CELL: _STM-DRAFT-REV
_STM-CURRENT-STATE CMP-CELL: _STM-DRAFT-PERSIST-MODE
_STM-CURRENT-STATE CMP-CELL: _STM-DRAFT-STORE-STATUS
_STM-CURRENT-STATE STREAMS-DRAFT-STORE-SIZE CMP-FIELD: _STM-DRAFT-STORE
_STM-CURRENT-STATE BFM-FEED-SIZE CMP-FIELD: _STM-FEED
_STM-CURRENT-STATE CMP-CELL: _STM-FEED-READY
_STM-CURRENT-STATE CMP-CELL: _STM-FEED-STATUS
CMP-LAYOUT-SIZE CONSTANT _STM-STATE-SIZE

: _STM-STATE-FINI  ( state -- )
    DUP _STM-CURRENT-STATE @ = IF
        0 _STM-CURRENT-STATE ! 0 _STM-CURRENT-INSTANCE !
    THEN
    _STM-STATE-SIZE 0 FILL ;

: _STM-ACTIVATE  ( instance -- )
    DUP _STM-CURRENT-INSTANCE ! CINST-STATE _STM-CURRENT-STATE ! ;

: _STM-OWNER-TOUCH  ( -- )
    _STM-CURRENT-INSTANCE @ ?DUP IF CINST-TOUCH THEN ;

: _STM-SELECTED-OWNER!  ( index -- )
    DUP _STM-SELECTED @ <> IF
        _STM-SELECTED ! _STM-OWNER-TOUCH
    ELSE
        DROP
    THEN ;

: _STM-NONNEG  ( n -- n' )
    DUP 0< IF DROP 0 THEN ;

: _STM-DRAFT-MEMORY-CLEAR  ( -- )
    0 _STM-DRAFT-U ! 0 _STM-DRAFT-REV !
    _STM-DRAFT-BUF _STM-DRAFT-CAP 0 FILL ;

: _STM-DRAFT-BLOCK!  ( status -- )
    _STM-DRAFT-STORE-STATUS !
    _STM-DP-BLOCKED _STM-DRAFT-PERSIST-MODE ! ;

VARIABLE _STM-DSI-U
VARIABLE _STM-DSI-REV
VARIABLE _STM-DSI-STATUS

: _STM-DRAFT-STORAGE-INIT-BODY  ( -- )
    VFS-CUR DUP 0= IF
        DROP SDSTORE-S-INVALID _STM-DRAFT-BLOCK! EXIT
    THEN
    _STM-DRAFT-STORE STREAMS-DRAFT-STORE-INIT _STM-DSI-STATUS !
    _STM-DSI-STATUS @ IF
        _STM-DSI-STATUS @ _STM-DRAFT-BLOCK! EXIT
    THEN
    _STM-DRAFT-BUF _STM-DRAFT-CAP _STM-DRAFT-STORE
        STREAMS-DRAFT-STORE-LOAD
    _STM-DSI-STATUS ! _STM-DSI-REV ! _STM-DSI-U !
    _STM-DSI-STATUS @ SDSTORE-S-OK = IF
        _STM-DSI-U @ _STM-DRAFT-U !
        _STM-DSI-REV @ _STM-DRAFT-REV !
        _STM-DRAFT-BUF _STM-DRAFT-U @ +
            _STM-DRAFT-CAP _STM-DRAFT-U @ - 0 FILL
        SDSTORE-S-OK _STM-DRAFT-STORE-STATUS !
        _STM-DP-READY _STM-DRAFT-PERSIST-MODE ! EXIT
    THEN
    _STM-DSI-STATUS @ SDSTORE-S-ABSENT = IF
        SDSTORE-S-ABSENT _STM-DRAFT-STORE-STATUS !
        _STM-DP-READY _STM-DRAFT-PERSIST-MODE ! EXIT
    THEN
    _STM-DSI-STATUS @ _STM-DRAFT-BLOCK! ;

\ Bind and recover the singleton draft before enabling any mutation.  The
\ helper is intentionally non-fatal: an uncertain or unreadable store leaves
\ Streams usable for reading while draft overwrites remain blocked.
: _STM-DRAFT-STORAGE-INIT  ( -- status )
    _STM-DRAFT-MEMORY-CLEAR
    SDSTORE-S-INVALID _STM-DRAFT-BLOCK!
    ['] _STM-DRAFT-STORAGE-INIT-BODY CATCH ?DUP IF
        DROP _STM-DRAFT-MEMORY-CLEAR
        SDSTORE-S-IO _STM-DRAFT-BLOCK!
    THEN
    _STM-DRAFT-STORE-STATUS @ ;

: _STM-DRAFT-BLOCKED-TEXT  ( -- addr len )
    _STM-DRAFT-STORE-STATUS @ SDSTORE-S-CORRUPT = IF
        S" Draft storage corrupt; editing disabled" EXIT
    THEN
    _STM-DRAFT-STORE-STATUS @ SDSTORE-S-UNSUPPORTED = IF
        S" Draft format unsupported; editing disabled" EXIT
    THEN
    _STM-DRAFT-STORE-STATUS @ SDSTORE-S-RECOVERY = IF
        S" Draft recovery uncertain; editing disabled" EXIT
    THEN
    _STM-DRAFT-STORE-STATUS @ SDSTORE-S-BUSY = IF
        S" Draft storage busy; editing disabled" EXIT
    THEN
    S" Draft storage unavailable; editing disabled" ;

\ The UI and capabilities only read the owned Bluesky timeline-page model.
: _STM-ITEM-COUNT  ( -- n )
    _STM-FEED-READY @ 0= IF 0 EXIT THEN
    _STM-FEED BFM.FEED.COUNT @ DUP 0< IF DROP 0 EXIT THEN
    DUP BFM-MAX-ITEMS > IF DROP 0 THEN ;
: _STM-ITEM  ( index -- item ) _STM-FEED BFM.FEED.ITEM ;
: _STM-URI  ( index -- addr len )
    DUP 0< OVER _STM-ITEM-COUNT >= OR IF DROP S" streams:item:unknown" EXIT THEN
    _STM-ITEM BFM.ITEM.URI ;

: _STM-AUTHOR  ( index -- addr len )
    DUP 0< OVER _STM-ITEM-COUNT >= OR IF DROP S" unknown" EXIT THEN
    _STM-ITEM BFM.ITEM.HANDLE ;

: _STM-TIME  ( index -- addr len )
    DUP 0< OVER _STM-ITEM-COUNT >= OR IF DROP S" --" EXIT THEN
    _STM-ITEM BFM.ITEM.CREATED ;

: _STM-TEXT  ( index -- addr len )
    DUP 0< OVER _STM-ITEM-COUNT >= OR IF DROP S" Missing feed item" EXIT THEN
    _STM-ITEM BFM.ITEM.TEXT ;

: _STM-ROOT-URI  ( index -- addr len )
    DUP 0< OVER _STM-ITEM-COUNT >= OR IF DROP 0 0 EXIT THEN
    DUP _STM-ITEM BFM.ITEM.ROOT-URI DUP IF ROT DROP EXIT THEN
    2DROP _STM-URI ;

VARIABLE _STM-ROOT-MATCH-A
VARIABLE _STM-ROOT-MATCH-U
VARIABLE _STM-CV-THREAD-ROOT-A
VARIABLE _STM-CV-THREAD-ROOT-U

: _STM-ROOT-MEMBER?  ( index root-a root-u -- flag )
    _STM-ROOT-MATCH-U ! _STM-ROOT-MATCH-A !
    DUP _STM-URI _STM-ROOT-MATCH-A @ _STM-ROOT-MATCH-U @ STR-STR= IF
        DROP -1 EXIT
    THEN
    _STM-ITEM BFM.ITEM.ROOT-URI
    _STM-ROOT-MATCH-A @ _STM-ROOT-MATCH-U @ STR-STR= ;

: _STM-THREAD-CLEAR  ( -- )
    0 _STM-THREAD-TOP ! 0 _STM-THREAD-ROOT-U !
    _STM-THREAD-ROOT-BUF BFM-URI-CAP 0 FILL ;

: _STM-THREAD-ROOT$  ( -- addr len )
    _STM-THREAD-ROOT-BUF _STM-THREAD-ROOT-U @ ;

: _STM-THREAD-MEMBER?  ( index -- flag )
    _STM-THREAD-ROOT$ _STM-ROOT-MEMBER? ;

: _STM-THREAD-ANCHOR!  ( index -- flag )
    _STM-ROOT-URI
    DUP 0= IF 2DROP _STM-THREAD-CLEAR 0 EXIT THEN
    DUP BFM-URI-CAP > IF 2DROP _STM-THREAD-CLEAR 0 EXIT THEN
    DUP _STM-THREAD-ROOT-U !
    _STM-THREAD-ROOT-BUF SWAP MOVE
    _STM-THREAD-ROOT-BUF _STM-THREAD-ROOT-U @ +
        BFM-URI-CAP _STM-THREAD-ROOT-U @ - 0 FILL
    0 _STM-THREAD-TOP ! -1 ;

VARIABLE _STM-THREAD-SCAN-N
VARIABLE _STM-THREAD-SCAN-WANTED
VARIABLE _STM-THREAD-SCAN-INDEX

: _STM-THREAD-COUNT  ( -- count )
    0 _STM-THREAD-SCAN-N !
    _STM-ITEM-COUNT 0 ?DO
        I _STM-THREAD-MEMBER? IF 1 _STM-THREAD-SCAN-N +! THEN
    LOOP
    _STM-THREAD-SCAN-N @ ;

: _STM-THREAD-NTH  ( ordinal -- index flag )
    DUP 0< IF DROP 0 0 EXIT THEN
    _STM-THREAD-SCAN-WANTED ! 0 _STM-THREAD-SCAN-N !
    _STM-ITEM-COUNT 0 ?DO
        I _STM-THREAD-MEMBER? IF
            _STM-THREAD-SCAN-N @ _STM-THREAD-SCAN-WANTED @ = IF
                I -1 UNLOOP EXIT
            THEN
            1 _STM-THREAD-SCAN-N +!
        THEN
    LOOP
    0 0 ;

: _STM-THREAD-POSITION  ( index -- ordinal flag )
    _STM-THREAD-SCAN-INDEX ! 0 _STM-THREAD-SCAN-N !
    _STM-ITEM-COUNT 0 ?DO
        I _STM-THREAD-MEMBER? IF
            I _STM-THREAD-SCAN-INDEX @ = IF
                _STM-THREAD-SCAN-N @ -1 UNLOOP EXIT
            THEN
            1 _STM-THREAD-SCAN-N +!
        THEN
    LOOP
    0 0 ;

VARIABLE _STM-MA
VARIABLE _STM-MU
VARIABLE _STM-MI
: _STM-MATCH?  ( index query-a query-u -- flag )
    _STM-MU ! _STM-MA ! _STM-MI !
    _STM-MI @ _STM-AUTHOR _STM-MA @ _STM-MU @ STR-STRI-CONTAINS
    _STM-MI @ _STM-TEXT _STM-MA @ _STM-MU @ STR-STRI-CONTAINS OR ;

VARIABLE _STM-QA
VARIABLE _STM-QU

: _STM-INDEX-FROM-URI  ( addr len -- index flag )
    _STM-ITEM-COUNT 0 ?DO
        2DUP I _STM-URI STR-STR= IF 2DROP I -1 UNLOOP EXIT THEN
    LOOP 2DROP 0 0 ;

: _STM-SET-VIEW-LABEL  ( -- )
    _STM-E-SBAR-VIEW @ ?DUP IF
        S" text" _STM-VIEW @ _STM-V-THREAD = IF S" Context" ELSE S" Timeline" THEN
        UTUI-SET-ATTR
    THEN ;

: _STM-UPDATE-STATUS  ( -- )
    _STM-SET-VIEW-LABEL
    _STM-E-SBAR-STATE @ ?DUP IF
        S" text"
        _STM-DRAFT-PERSIST-MODE @ _STM-DP-BLOCKED = IF
            _STM-DRAFT-BLOCKED-TEXT
        ELSE
            _STM-FEED-READY @ IF
                _STM-FEED-STATUS @ BFM-S-OK = IF
                    S" Cached feed"
                ELSE
                    S" Cached feed / reload failed"
                THEN
            ELSE
                S" No feed loaded"
            THEN
        THEN
        UTUI-SET-ATTR
    THEN ;

: _STM-INVALIDATE  ( -- )
    _STM-PANEL WDG-DIRTY
    _STM-E-BODY @ ?DUP IF UIDL-DIRTY! THEN
    _STM-UPDATE-STATUS
    ASHELL-DIRTY! ;

: _STM-SELECTION-VALID?  ( -- flag )
    _STM-ITEM-COUNT 0>
    _STM-SELECTED @ 0>= AND
    _STM-SELECTED @ _STM-ITEM-COUNT < AND ;

: _STM-OPEN-THREAD  ( -- )
    _STM-SELECTION-VALID? 0= IF
        S" No cached item is selected; context is unavailable"
        2200 ASHELL-TOAST EXIT
    THEN
    _STM-SELECTED @ _STM-THREAD-ANCHOR! 0= IF
        S" Selected item has no usable context identity"
        2200 ASHELL-TOAST EXIT
    THEN
    _STM-V-THREAD _STM-VIEW ! _STM-SET-VIEW-LABEL _STM-INVALIDATE ;
: _STM-OPEN-TIMELINE  ( -- )
    _STM-V-TIMELINE _STM-VIEW ! _STM-THREAD-CLEAR
    _STM-SET-VIEW-LABEL _STM-INVALIDATE ;

\ ---------------------------------------------------------------------
\ Direct TUI
\ ---------------------------------------------------------------------

VARIABLE _STM-DW
VARIABLE _STM-DH
VARIABLE _STM-ROW

3 CONSTANT _STM-THREAD-CARD-ROWS
5 CONSTANT _STM-THREAD-FIRST-ROW

: _STM-VISIBLE-ITEMS  ( -- count )
    _STM-DH @ 3 -
    _STM-DRAFT-REV @ IF 3 - THEN
    _STM-NONNEG 3 / ;

: _STM-ENSURE-VISIBLE  ( -- )
    _STM-ITEM-COUNT DUP 0= IF DROP 0 _STM-TOP ! EXIT THEN
    _STM-SELECTED @ _STM-NONNEG OVER 1- MIN _STM-SELECTED !
    _STM-VISIBLE-ITEMS
    DUP 0= IF
        2DROP _STM-SELECTED @ _STM-TOP ! EXIT
    THEN
    _STM-SELECTED @ _STM-TOP @ < IF
        _STM-SELECTED @ _STM-TOP !
    ELSE
        _STM-SELECTED @ _STM-TOP @ 2 PICK + >= IF
            _STM-SELECTED @ OVER - 1+ _STM-TOP !
        THEN
    THEN
    SWAP OVER - _STM-NONNEG _STM-TOP @ MIN _STM-TOP ! DROP ;

: _STM-THREAD-VISIBLE-ITEMS  ( -- count )
    _STM-DH @
    _STM-DRAFT-REV @ IF 3 - THEN
    _STM-THREAD-FIRST-ROW - _STM-NONNEG
    _STM-THREAD-CARD-ROWS / ;

VARIABLE _STM-THREAD-ENSURE-COUNT
VARIABLE _STM-THREAD-ENSURE-POS
VARIABLE _STM-THREAD-ENSURE-VISIBLE-N

: _STM-THREAD-ENSURE-VISIBLE  ( -- )
    _STM-THREAD-COUNT DUP _STM-THREAD-ENSURE-COUNT ! 0= IF
        0 _STM-THREAD-TOP ! EXIT
    THEN
    _STM-SELECTED @ _STM-THREAD-POSITION 0= IF
        DROP 0 _STM-THREAD-TOP ! EXIT
    THEN
    _STM-THREAD-ENSURE-POS !
    _STM-THREAD-VISIBLE-ITEMS DUP _STM-THREAD-ENSURE-VISIBLE-N ! 0= IF
        _STM-THREAD-ENSURE-POS @ _STM-THREAD-TOP ! EXIT
    THEN
    _STM-THREAD-TOP @ _STM-NONNEG
        _STM-THREAD-ENSURE-COUNT @ 1- MIN _STM-THREAD-TOP !
    _STM-THREAD-ENSURE-POS @ _STM-THREAD-TOP @ < IF
        _STM-THREAD-ENSURE-POS @ _STM-THREAD-TOP !
    ELSE
        _STM-THREAD-ENSURE-POS @
        _STM-THREAD-TOP @ _STM-THREAD-ENSURE-VISIBLE-N @ + >= IF
            _STM-THREAD-ENSURE-POS @
            _STM-THREAD-ENSURE-VISIBLE-N @ - 1+
            _STM-NONNEG _STM-THREAD-TOP !
        THEN
    THEN
    _STM-THREAD-ENSURE-COUNT @ _STM-THREAD-ENSURE-VISIBLE-N @ -
        _STM-NONNEG _STM-THREAD-TOP @ MIN _STM-THREAD-TOP ! ;

: _STM-DRAW-ITEM  ( index row -- )
    _STM-ROW ! DUP _STM-SELECTED @ = IF 15 24 CELL-A-BOLD ELSE 253 234 0 THEN
    DRW-STYLE!
    32 _STM-ROW @ 0 3 _STM-DW @ DRW-FILL-RECT
    DUP _STM-AUTHOR _STM-ROW @ 2 DRW-TEXT-UNTRUSTED
    DUP _STM-TIME _STM-ROW @ 18 DRW-TEXT-UNTRUSTED
    DUP _STM-TEXT _STM-ROW @ 1+ 4 DRW-TEXT-UNTRUSTED
    DUP _STM-ITEM BFM.ITEM.FLAGS @ BFM-F-REPLY AND IF
        S" reply" _STM-ROW @ 2 + 4 DRW-TEXT
    THEN DROP ;

: _STM-DRAW-TIMELINE  ( -- )
    _STM-ITEM-COUNT DUP 0= IF
        DROP 244 234 0 DRW-STYLE!
        S" No feed is loaded. Streams is offline." 4 2 DRW-TEXT EXIT
    THEN
    DROP _STM-ENSURE-VISIBLE
    _STM-ITEM-COUNT _STM-TOP @ - _STM-NONNEG _STM-VISIBLE-ITEMS MIN
    0 ?DO _STM-TOP @ I + 3 I 3 * + _STM-DRAW-ITEM LOOP ;

: _STM-DRAW-THREAD  ( -- )
    244 234 0 DRW-STYLE! S" Cached timeline context (partial)" 3 2 DRW-TEXT
    S" root " 4 2 DRW-TEXT
    _STM-THREAD-ROOT$ 4 7 DRW-TEXT-UNTRUSTED
    _STM-THREAD-ENSURE-VISIBLE
    _STM-THREAD-COUNT _STM-THREAD-TOP @ - _STM-NONNEG
        _STM-THREAD-VISIBLE-ITEMS MIN
    0 ?DO
        _STM-THREAD-TOP @ I + _STM-THREAD-NTH IF
            _STM-THREAD-FIRST-ROW I _STM-THREAD-CARD-ROWS * +
                _STM-DRAW-ITEM
        ELSE
            DROP
        THEN
    LOOP ;

: _STM-PANEL-DRAW  ( widget -- )
    DUP WDG-REGION RGN-W _STM-DW ! WDG-REGION RGN-H _STM-DH !
    253 234 0 DRW-STYLE! 32 0 0 _STM-DH @ _STM-DW @ DRW-FILL-RECT
    255 24 CELL-A-BOLD DRW-STYLE! 32 0 0 1 _STM-DW @ DRW-FILL-RECT
    S" STREAMS" 0 2 DRW-TEXT
    244 234 0 DRW-STYLE!
    S" offline cache | arrows select | T thread | / search | C draft"
    _STM-DW @ 4 - _STM-NONNEG MIN 1 2 DRW-TEXT
    _STM-VIEW @ _STM-V-THREAD = IF _STM-DRAW-THREAD ELSE _STM-DRAW-TIMELINE THEN
    _STM-DRAFT-REV @ IF
        81 234 CELL-A-BOLD DRW-STYLE!
        S" Draft r" _STM-DH @ 3 - 2 DRW-TEXT
        _STM-DRAFT-REV @ NUM>STR _STM-DH @ 3 - 9 DRW-TEXT
        253 234 0 DRW-STYLE!
        _STM-DRAFT-U @ IF
            _STM-DRAFT-BUF _STM-DRAFT-U @
            _STM-DH @ 2 - 4 DRW-TEXT-UNTRUSTED
        ELSE
            S" (empty local draft)" _STM-DH @ 2 - 4 DRW-TEXT
        THEN
    THEN
    DRW-STYLE-RESET ;

: _STM-TIMELINE-MOVE  ( delta -- )
    _STM-SELECTED @ + _STM-NONNEG
    _STM-ITEM-COUNT 1- _STM-NONNEG MIN
    _STM-SELECTED-OWNER!
    _STM-ENSURE-VISIBLE _STM-INVALIDATE ;

VARIABLE _STM-THREAD-MOVE-DELTA
VARIABLE _STM-THREAD-MOVE-TARGET

: _STM-THREAD-MOVE  ( delta -- )
    _STM-THREAD-MOVE-DELTA !
    _STM-THREAD-COUNT DUP 0= IF DROP _STM-INVALIDATE EXIT THEN
    1- _STM-THREAD-MOVE-TARGET !
    _STM-SELECTED @ _STM-THREAD-POSITION 0= IF
        DROP _STM-INVALIDATE EXIT
    THEN
    _STM-THREAD-MOVE-DELTA @ + _STM-NONNEG
    _STM-THREAD-MOVE-TARGET @ MIN
    _STM-THREAD-NTH IF _STM-SELECTED-OWNER! ELSE DROP THEN
    _STM-THREAD-ENSURE-VISIBLE _STM-INVALIDATE ;

: _STM-MOVE  ( delta -- )
    _STM-VIEW @ _STM-V-THREAD = IF _STM-THREAD-MOVE EXIT THEN
    _STM-TIMELINE-MOVE ;

VARIABLE _STM-DRAFT-SAVE-A
VARIABLE _STM-DRAFT-SAVE-U
VARIABLE _STM-DRAFT-SAVE-REV
VARIABLE _STM-DRAFT-NEXT-A
VARIABLE _STM-DRAFT-NEXT-U
VARIABLE _STM-DRAFT-NEXT-REV

: _STM-DRAFT-SAVE-CALL  ( -- )
    _STM-DRAFT-SAVE-A @ _STM-DRAFT-SAVE-U @
    _STM-DRAFT-SAVE-REV @ _STM-DRAFT-STORE
        STREAMS-DRAFT-STORE-SAVE
    _STM-DRAFT-STORE-STATUS ! ;

: _STM-DRAFT-PERSIST  ( addr len revision -- flag )
    _STM-DRAFT-SAVE-REV ! _STM-DRAFT-SAVE-U ! _STM-DRAFT-SAVE-A !
    _STM-DRAFT-PERSIST-MODE @ _STM-DP-VOLATILE = IF -1 EXIT THEN
    _STM-DRAFT-PERSIST-MODE @ _STM-DP-READY <> IF
        _STM-DRAFT-PERSIST-MODE @ _STM-DP-BLOCKED <> IF
            SDSTORE-S-INVALID _STM-DRAFT-BLOCK!
        THEN
        0 EXIT
    THEN
    SDSTORE-S-IO _STM-DRAFT-STORE-STATUS !
    ['] _STM-DRAFT-SAVE-CALL CATCH ?DUP IF
        DROP SDSTORE-S-IO _STM-DRAFT-STORE-STATUS !
    THEN
    _STM-DRAFT-STORE-STATUS @ IF
        _STM-DP-BLOCKED _STM-DRAFT-PERSIST-MODE ! 0 EXIT
    THEN
    -1 ;

: _STM-DRAFT!  ( addr len -- flag )
    _STM-DRAFT-NEXT-U ! _STM-DRAFT-NEXT-A !
    _STM-DRAFT-NEXT-U @ 0<
    _STM-DRAFT-NEXT-U @ _STM-DRAFT-CAP > OR
    _STM-DRAFT-NEXT-U @ 0> _STM-DRAFT-NEXT-A @ 0= AND OR IF
        0 EXIT
    THEN
    _STM-DRAFT-NEXT-U @ IF
        _STM-DRAFT-NEXT-A @ _STM-DRAFT-NEXT-U @ UTF8-VALID? 0= IF
            0 EXIT
        THEN
    THEN
    _STM-DRAFT-REV @ CV-CELL-MAX >= IF 0 EXIT THEN
    _STM-DRAFT-REV @ 1+ _STM-DRAFT-NEXT-REV !
    _STM-DRAFT-NEXT-A @ _STM-DRAFT-NEXT-U @
        _STM-DRAFT-NEXT-REV @ _STM-DRAFT-PERSIST 0= IF 0 EXIT THEN
    _STM-DRAFT-NEXT-U @ IF
        _STM-DRAFT-NEXT-A @ _STM-DRAFT-BUF _STM-DRAFT-NEXT-U @ CMOVE
    THEN
    _STM-DRAFT-NEXT-U @ _STM-DRAFT-U !
    _STM-DRAFT-BUF _STM-DRAFT-U @ + _STM-DRAFT-CAP _STM-DRAFT-U @ -
        0 FILL
    _STM-DRAFT-NEXT-REV @ _STM-DRAFT-REV ! -1 ;

: _STM-DRAFT-OWNER!  ( addr len -- flag )
    _STM-DRAFT! DUP IF _STM-OWNER-TOUCH THEN ;

VARIABLE _STM-SHOW-MODE
VARIABLE _STM-SHOW-LA
VARIABLE _STM-SHOW-LU
VARIABLE _STM-SHOW-IA
VARIABLE _STM-SHOW-IU

: _STM-SHOW-PROMPT  ( mode label-a label-u initial-a initial-u -- )
    _STM-SHOW-IU ! _STM-SHOW-IA ! _STM-SHOW-LU ! _STM-SHOW-LA !
    _STM-SHOW-MODE !
    _STM-PROMPT @ 0= IF
        S" Streams prompt is unavailable" 1800 ASHELL-TOAST EXIT
    THEN
    _STM-SHOW-MODE @ _STM-PROMPT-MODE !
    _STM-SHOW-LA @ _STM-SHOW-LU @
    _STM-SHOW-IA @ _STM-SHOW-IU @ _STM-PROMPT @ PRM-SHOW
    ASHELL-DIRTY! ;

VARIABLE _STM-SUB-A
VARIABLE _STM-SUB-U
VARIABLE _STM-SUB-MODE
VARIABLE _STM-SEARCH-FIRST

: _STM-SEARCH-CLEAR  ( -- )
    0 _STM-SEARCH-U ! 0 _STM-SEARCH-MATCH-N !
    _STM-SEARCH-BUF _STM-QUERY-CAP 0 FILL ;

: _STM-APPLY-SEARCH  ( addr len -- )
    STR-TRIM _STM-SUB-U ! _STM-SUB-A !
    _STM-SUB-U @ 0= IF
        _STM-SEARCH-CLEAR
        S" Search query is empty; selection unchanged" 2200 ASHELL-TOAST
        EXIT
    THEN
    _STM-SUB-U @ _STM-QUERY-CAP > IF
        S" Search is limited to 96 UTF-8 bytes" 2200 ASHELL-TOAST EXIT
    THEN
    _STM-SUB-A @ _STM-SUB-U @ UTF8-VALID? 0= IF
        S" Search query is not valid UTF-8" 2200 ASHELL-TOAST EXIT
    THEN
    _STM-SUB-U @ _STM-SEARCH-U !
    _STM-SUB-A @ _STM-SEARCH-BUF _STM-SUB-U @ MOVE
    _STM-SEARCH-BUF _STM-SEARCH-U @ +
        _STM-QUERY-CAP _STM-SEARCH-U @ - 0 FILL
    0 _STM-SEARCH-MATCH-N ! -1 _STM-SEARCH-FIRST !
    _STM-ITEM-COUNT 0 ?DO
        I _STM-SEARCH-BUF _STM-SEARCH-U @ _STM-MATCH? IF
            _STM-SEARCH-FIRST @ 0< IF I _STM-SEARCH-FIRST ! THEN
            1 _STM-SEARCH-MATCH-N +!
        THEN
    LOOP
    _STM-SEARCH-MATCH-N @ 0= IF
        _STM-ITEM-COUNT 0= IF
            S" No cached feed items are available to search"
        ELSE
            S" No cached items match; selection unchanged"
        THEN
        2200 ASHELL-TOAST EXIT
    THEN
    _STM-SEARCH-FIRST @ _STM-SELECTED-OWNER!
    _STM-V-TIMELINE _STM-VIEW ! _STM-THREAD-CLEAR _STM-ENSURE-VISIBLE
    _STM-SEARCH-MATCH-N @ 1 = IF
        S" Found 1 cached item; selected it"
    ELSE
        S" Found cached items; selected the first"
    THEN
    1900 ASHELL-TOAST ;

: _STM-PROMPT-SUBMIT  ( prompt -- )
    DUP PRM-GET-TEXT _STM-SUB-U ! _STM-SUB-A !
    _STM-PROMPT-MODE @ _STM-SUB-MODE !
    _STM-PM-NONE _STM-PROMPT-MODE !
    _STM-SUB-MODE @ CASE
        _STM-PM-SEARCH OF
            _STM-SUB-A @ _STM-SUB-U @ _STM-APPLY-SEARCH
        ENDOF
        _STM-PM-DRAFT OF
            _STM-SUB-A @ _STM-SUB-U @ _STM-DRAFT-OWNER! IF
                S" Draft saved locally; nothing was published"
            ELSE
                S" Draft could not be updated locally"
            THEN
            2200 ASHELL-TOAST
        ENDOF
    ENDCASE
    PRM-WIPE
    _STM-E-BODY @ ?DUP IF UTUI-FOCUS! THEN
    _STM-INVALIDATE ;

: _STM-PROMPT-CANCEL  ( prompt -- )
    PRM-WIPE _STM-PM-NONE _STM-PROMPT-MODE !
    _STM-E-BODY @ ?DUP IF UTUI-FOCUS! THEN
    _STM-INVALIDATE ;

: _STM-BEGIN-SEARCH  ( -- )
    _STM-PM-SEARCH S" Search cached posts:"
    _STM-SEARCH-BUF _STM-SEARCH-U @ _STM-SHOW-PROMPT ;

: _STM-BEGIN-DRAFT  ( -- )
    _STM-DRAFT-PERSIST-MODE @ _STM-DP-BLOCKED = IF
        _STM-DRAFT-BLOCKED-TEXT 2600 ASHELL-TOAST EXIT
    THEN
    _STM-PM-DRAFT S" Draft:"
    _STM-DRAFT-REV @ IF _STM-DRAFT-BUF _STM-DRAFT-U @ ELSE 0 0 THEN
    _STM-SHOW-PROMPT ;

: _STM-PANEL-HANDLE  ( event widget -- consumed? )
    DROP
    DUP @ KEY-T-SPECIAL = IF
        8 + @ CASE
            KEY-UP OF -1 _STM-MOVE -1 EXIT ENDOF
            KEY-DOWN OF 1 _STM-MOVE -1 EXIT ENDOF
            KEY-ENTER OF _STM-OPEN-THREAD -1 EXIT ENDOF
            KEY-ESC OF _STM-OPEN-TIMELINE -1 EXIT ENDOF
        ENDCASE 0 EXIT
    THEN
    DUP @ KEY-T-CHAR = IF
        DUP 16 + @ 0= IF 8 + @ CASE
            [CHAR] t OF _STM-OPEN-THREAD -1 EXIT ENDOF
            [CHAR] T OF _STM-OPEN-THREAD -1 EXIT ENDOF
            [CHAR] / OF _STM-BEGIN-SEARCH -1 EXIT ENDOF
            [CHAR] c OF _STM-BEGIN-DRAFT -1 EXIT ENDOF
            [CHAR] C OF _STM-BEGIN-DRAFT -1 EXIT ENDOF
        ENDCASE THEN
    THEN DROP 0 ;

: _STM-PANEL-INIT  ( rgn -- )
    DUP _STM-PANEL-RGN ! _STM-PANEL 33 OVER ! SWAP OVER 8 + !
    ['] _STM-PANEL-DRAW OVER 16 + ! ['] _STM-PANEL-HANDLE OVER 24 + !
    WDG-F-VISIBLE WDG-F-DIRTY OR SWAP 32 + ! ;

: _STM-DO-QUIT  ( elem -- ) DROP ASHELL-QUIT ;
: _STM-DO-TIMELINE  ( elem -- ) DROP _STM-OPEN-TIMELINE ;
: _STM-DO-THREAD  ( elem -- ) DROP _STM-OPEN-THREAD ;
: _STM-DO-SEARCH  ( elem -- ) DROP _STM-BEGIN-SEARCH ;
: _STM-DO-COMPOSE  ( elem -- ) DROP _STM-BEGIN-DRAFT ;
: _STM-DO-ABOUT  ( elem -- )
    DROP S" Streams - bounded communication, subscription, and draft workbench"
    2600 ASHELL-TOAST ;

\ ---------------------------------------------------------------------
\ Lifecycle
\ ---------------------------------------------------------------------

CREATE _STM-LOAD-SELECTED-URI BFM-URI-CAP ALLOT
VARIABLE _STM-LOAD-SELECTED-U
VARIABLE _STM-LOAD-SELECTED-I
VARIABLE _STM-LOAD-OLD-STATUS

: _STM-THREAD-RECONCILE  ( -- )
    _STM-VIEW @ _STM-V-THREAD <> IF EXIT THEN
    _STM-THREAD-ROOT-U @ 0= IF
        _STM-V-TIMELINE _STM-VIEW ! _STM-THREAD-CLEAR EXIT
    THEN
    _STM-THREAD-COUNT 0= IF
        _STM-V-TIMELINE _STM-VIEW ! _STM-THREAD-CLEAR EXIT
    THEN
    _STM-SELECTED @ _STM-THREAD-POSITION IF
        DROP _STM-THREAD-ENSURE-VISIBLE EXIT
    THEN
    DROP
    0 _STM-THREAD-NTH IF
        _STM-SELECTED ! _STM-THREAD-ENSURE-VISIBLE
    ELSE
        DROP _STM-V-TIMELINE _STM-VIEW ! _STM-THREAD-CLEAR
    THEN ;

: STREAMS-LOAD-FEED-JSON  ( json-a json-u instance -- status )
    _STM-ACTIVATE
    _STM-FEED-STATUS @ _STM-LOAD-OLD-STATUS !
    0 _STM-LOAD-SELECTED-U ! _STM-SELECTED @ _STM-LOAD-SELECTED-I !
    _STM-FEED-READY @ _STM-ITEM-COUNT 0> AND IF
        _STM-SELECTED @ _STM-NONNEG _STM-ITEM-COUNT 1- MIN _STM-URI
        DUP _STM-LOAD-SELECTED-U !
        _STM-LOAD-SELECTED-URI SWAP CMOVE
    THEN
    _STM-FEED BFM-DECODE-FEED
    DUP _STM-FEED-STATUS !
    DUP BFM-S-OK = IF
        -1 _STM-FEED-READY !
        _STM-ITEM-COUNT 0= IF
            0 _STM-SELECTED !
        ELSE
            _STM-LOAD-SELECTED-U @ IF
                _STM-LOAD-SELECTED-URI _STM-LOAD-SELECTED-U @
                _STM-INDEX-FROM-URI IF
                    _STM-SELECTED !
                ELSE
                    DROP _STM-LOAD-SELECTED-I @
                    _STM-NONNEG _STM-ITEM-COUNT 1- MIN _STM-SELECTED !
                THEN
            ELSE
                _STM-LOAD-SELECTED-I @ _STM-NONNEG _STM-ITEM-COUNT 1- MIN
                    _STM-SELECTED !
            THEN
        THEN
        _STM-THREAD-RECONCILE
        _STM-OWNER-TOUCH
    ELSE
        _STM-FEED-READY @
        _STM-LOAD-OLD-STATUS @ BFM-S-OK = AND IF _STM-OWNER-TOUCH THEN
    THEN
    _STM-E-BODY @ IF _STM-INVALIDATE THEN ;

: STREAMS-INIT-CB  ( instance -- )
    _STM-ACTIVATE
    0 _STM-PANEL-RGN ! 0 _STM-PROMPT ! 0 _STM-PROMPT-RGN !
    _STM-PM-NONE _STM-PROMPT-MODE !
    _STM-V-TIMELINE _STM-VIEW !
    0 _STM-SELECTED ! 0 _STM-TOP ! _STM-THREAD-CLEAR
    0 _STM-SEARCH-U ! 0 _STM-SEARCH-MATCH-N !
    _STM-DRAFT-STORAGE-INIT DROP
    0 _STM-FEED-READY ! BFM-S-MISSING _STM-FEED-STATUS !
    _STM-FEED BFM-FEED-INIT
    S" streams-body" UTUI-BY-ID _STM-E-BODY !
    S" sbar" UTUI-BY-ID _STM-E-SBAR !
    S" sbar-view" UTUI-BY-ID _STM-E-SBAR-VIEW !
    S" sbar-state" UTUI-BY-ID _STM-E-SBAR-STATE !
    _STM-E-SBAR @ ?DUP IF
        UTUI-ELEM-RGN RGN-NEW DUP _STM-PROMPT-RGN !
        _STM-PROMPT-BUF _STM-PROMPT-CAP PRM-NEW DUP _STM-PROMPT !
        ['] _STM-PROMPT-SUBMIT OVER PRM-ON-SUBMIT
        ['] _STM-PROMPT-CANCEL OVER PRM-ON-CANCEL
        15 23 ROT PRM-COLORS!
    THEN
    _STM-E-BODY @ ?DUP IF
        UTUI-ELEM-RGN RGN-NEW _STM-PANEL-INIT
        _STM-PANEL _STM-E-BODY @ UTUI-WIDGET-SET
        _STM-E-BODY @ UTUI-FOCUS!
    THEN
    S" quit" ['] _STM-DO-QUIT UTUI-DO!
    S" timeline" ['] _STM-DO-TIMELINE UTUI-DO!
    S" thread" ['] _STM-DO-THREAD UTUI-DO!
    S" search" ['] _STM-DO-SEARCH UTUI-DO!
    S" compose" ['] _STM-DO-COMPOSE UTUI-DO!
    S" about" ['] _STM-DO-ABOUT UTUI-DO!
    _STM-UPDATE-STATUS ;

: STREAMS-EVENT-CB  ( event instance -- consumed? )
    _STM-ACTIVATE
    _STM-PROMPT @ ?DUP IF
        DUP PRM-ACTIVE? IF WDG-HANDLE EXIT THEN DROP
    THEN
    _UTUI-MENU-OPEN @ IF DROP 0 EXIT THEN _STM-PANEL WDG-HANDLE ;

: STREAMS-PAINT-CB  ( instance -- )
    _STM-ACTIVATE
    _STM-PROMPT @ ?DUP 0= IF EXIT THEN
    DUP PRM-ACTIVE? 0= IF DROP EXIT THEN DROP
    _STM-E-SBAR @ ?DUP IF
        UTUI-ELEM-RGN _STM-PROMPT @ PRM-SET-BOUNDS
    THEN
    _STM-PROMPT @ WDG-DRAW ;
: STREAMS-TICK-CB  ( instance -- ) _STM-ACTIVATE ;

: STREAMS-REQUEST-CLOSE-CB  ( reason instance -- decision )
    SWAP DROP _STM-ACTIVATE
    _STM-PROMPT @ ?DUP IF
        PRM-ACTIVE? IF
            S" Finish or cancel the Streams prompt before closing"
            2400 ASHELL-TOAST APP-CLOSE-D-CANCEL EXIT
        THEN
    THEN
    APP-CLOSE-D-ALLOW ;

: STREAMS-SHUTDOWN-CB  ( instance -- )
    _STM-ACTIVATE _STM-E-BODY @ ?DUP IF 0 SWAP UTUI-WIDGET-SET THEN
    _STM-PROMPT @ ?DUP IF DUP PRM-WIPE PRM-FREE THEN
    _STM-PROMPT-RGN @ ?DUP IF RGN-FREE THEN
    _STM-PANEL-RGN @ ?DUP IF RGN-FREE THEN
    _STM-LOAD-SELECTED-URI BFM-URI-CAP 0 FILL
    0 _STM-LOAD-SELECTED-U ! 0 _STM-LOAD-SELECTED-I !
    0 _STM-ROOT-MATCH-A ! 0 _STM-ROOT-MATCH-U !
    0 _STM-CV-THREAD-ROOT-A ! 0 _STM-CV-THREAD-ROOT-U !
    _STM-CURRENT-STATE @ _STM-STATE-FINI ;

\ ---------------------------------------------------------------------
\ Capability surface
\ ---------------------------------------------------------------------

\ Capability values are closed typed graphs.  Provider text never becomes a
\ line protocol, so embedded newlines and field-looking text remain data.
CREATE _STM-NULL-SCHEMA CS-SIZE ALLOT
CREATE _STM-BOOL-SCHEMA CS-SIZE ALLOT
CREATE _STM-COUNT-SCHEMA CS-SIZE ALLOT
CREATE _STM-REVISION-SCHEMA CS-SIZE ALLOT
CREATE _STM-META-SCHEMA CS-SIZE ALLOT
CREATE _STM-CID-SCHEMA CS-SIZE ALLOT
CREATE _STM-DID-SCHEMA CS-SIZE ALLOT
CREATE _STM-HANDLE-SCHEMA CS-SIZE ALLOT
CREATE _STM-DISPLAY-SCHEMA CS-SIZE ALLOT
CREATE _STM-TEXT-SCHEMA CS-SIZE ALLOT
CREATE _STM-DATETIME-SCHEMA CS-SIZE ALLOT
CREATE _STM-CURSOR-SCHEMA CS-SIZE ALLOT
CREATE _STM-QUERY-SCHEMA CS-SIZE ALLOT
CREATE _STM-RESOURCE-SCHEMA CS-SIZE ALLOT
CREATE _STM-NULLABLE-META-SCHEMA CS-SIZE ALLOT
CREATE _STM-NULLABLE-RESOURCE-SCHEMA CS-SIZE ALLOT

CREATE _STM-AUTHOR-SCHEMA CS-SIZE ALLOT
CREATE _STM-AUTHOR-FIELDS 3 CS-FIELD-SIZE * ALLOT
CREATE _STM-COUNTS-SCHEMA CS-SIZE ALLOT
CREATE _STM-COUNTS-FIELDS 3 CS-FIELD-SIZE * ALLOT
CREATE _STM-REPLY-SCHEMA CS-SIZE ALLOT
CREATE _STM-REPLY-FIELDS 2 CS-FIELD-SIZE * ALLOT
CREATE _STM-ITEM-SCHEMA CS-SIZE ALLOT
CREATE _STM-ITEM-FIELDS 11 CS-FIELD-SIZE * ALLOT
CREATE _STM-RESOURCE-LIST-SCHEMA CS-SIZE ALLOT
CREATE _STM-FEED-SCHEMA CS-SIZE ALLOT
CREATE _STM-FEED-FIELDS 6 CS-FIELD-SIZE * ALLOT
CREATE _STM-THREAD-SCHEMA CS-SIZE ALLOT
CREATE _STM-THREAD-FIELDS 5 CS-FIELD-SIZE * ALLOT
CREATE _STM-SEARCH-SCHEMA CS-SIZE ALLOT
CREATE _STM-SEARCH-FIELDS 3 CS-FIELD-SIZE * ALLOT
CREATE _STM-DRAFT-SCHEMA CS-SIZE ALLOT
CREATE _STM-DRAFT-FIELDS 3 CS-FIELD-SIZE * ALLOT
CREATE _STM-DRAFT-VALIDATION-SCHEMA CS-SIZE ALLOT
CREATE _STM-DRAFT-VALIDATION-FIELDS 7 CS-FIELD-SIZE * ALLOT
CREATE _STM-DRAFT-CREATE-SCHEMA CS-SIZE ALLOT
CREATE _STM-DRAFT-CREATE-FIELDS CS-FIELD-SIZE ALLOT
CREATE _STM-DRAFT-REPLACE-SCHEMA CS-SIZE ALLOT
CREATE _STM-DRAFT-REPLACE-FIELDS 3 CS-FIELD-SIZE * ALLOT

10 CONSTANT _STM-CAP-COUNT
CREATE STREAMS-CAPS _STM-CAP-COUNT CAP-DESC * ALLOT
: STREAMS-CAP-SELECTION STREAMS-CAPS ;
: STREAMS-CAP-ITEM STREAMS-CAPS CAP-DESC + ;
: STREAMS-CAP-THREAD STREAMS-CAPS CAP-DESC 2 * + ;
: STREAMS-CAP-FEED STREAMS-CAPS CAP-DESC 3 * + ;
: STREAMS-CAP-SEARCH STREAMS-CAPS CAP-DESC 4 * + ;
: STREAMS-CAP-DRAFT-CREATE STREAMS-CAPS CAP-DESC 5 * + ;
: STREAMS-CAP-DRAFT-READ STREAMS-CAPS CAP-DESC 6 * + ;
: STREAMS-CAP-DRAFT-REPLACE STREAMS-CAPS CAP-DESC 7 * + ;
: STREAMS-CAP-DRAFT-VALIDATE STREAMS-CAPS CAP-DESC 8 * + ;
: STREAMS-CAP-DRAFT-CURRENT STREAMS-CAPS CAP-DESC 9 * + ;

VARIABLE _STM-CAP-REQ
VARIABLE _STM-CAP-ARGS
VARIABLE _STM-CAP-A
VARIABLE _STM-CAP-U
VARIABLE _STM-CAP-I
VARIABLE _STM-CAP-EXPECTED

\ Transactional result construction.  Any allocation failure is remembered;
\ the outer value is then recursively freed rather than exposing a partial map.
VARIABLE _STM-CV-IOR
VARIABLE _STM-CV-INDEX
VARIABLE _STM-CV-DEST
VARIABLE _STM-CV-ITEM
VARIABLE _STM-CV-CHILD
VARIABLE _STM-CV-NEST
VARIABLE _STM-CV-LIST
VARIABLE _STM-CV-COUNT
VARIABLE _STM-CV-POS

: _STM-CV-BEGIN  ( -- ) 0 _STM-CV-IOR ! ;
: _STM-CV-FAIL!  ( ior -- )
    _STM-CV-IOR @ IF DROP ELSE _STM-CV-IOR ! THEN ;
: _STM-CV-MAP!  ( count value -- )
    _STM-CV-IOR @ IF 2DROP EXIT THEN
    CV-MAP! ?DUP IF _STM-CV-FAIL! THEN ;
: _STM-CV-LIST!  ( count value -- )
    _STM-CV-IOR @ IF 2DROP EXIT THEN
    CV-LIST! ?DUP IF _STM-CV-FAIL! THEN ;
: _STM-CV-SLOT  ( key-a key-u index map -- child | 0 )
    _STM-CV-IOR @ IF 2DROP 2DROP 0 EXIT THEN
    CV-MAP-SLOT! DUP IF
        _STM-CV-FAIL! DROP 0
    ELSE
        DROP
    THEN ;
: _STM-CV-STRING!  ( addr len value -- )
    _STM-CV-IOR @ IF 2DROP DROP EXIT THEN
    CV-STRING! ?DUP IF _STM-CV-FAIL! THEN ;
: _STM-CV-RESOURCE!  ( addr len value -- )
    _STM-CV-IOR @ IF 2DROP DROP EXIT THEN
    CV-RESOURCE! ?DUP IF _STM-CV-FAIL! THEN ;
: _STM-CV-INT!  ( n value -- )
    _STM-CV-IOR @ IF 2DROP EXIT THEN CV-INT! ;
: _STM-CV-BOOL!  ( flag value -- )
    _STM-CV-IOR @ IF 2DROP EXIT THEN CV-BOOL! ;
: _STM-CV-NULL!  ( value -- )
    _STM-CV-IOR @ IF DROP EXIT THEN CV-NULL! ;
: _STM-CV-FINISH  ( value -- status )
    _STM-CV-IOR @ IF CV-FREE CBUS-S-FAILED ELSE DROP CBUS-S-OK THEN ;

: _STM-CV-ITEM!  ( index value -- )
    _STM-CV-IOR @ IF 2DROP EXIT THEN
    _STM-CV-DEST ! _STM-CV-INDEX !
    _STM-CV-INDEX @ _STM-ITEM DUP 0= IF
        DROP CV-E-RANGE _STM-CV-FAIL! EXIT
    THEN _STM-CV-ITEM !
    11 _STM-CV-DEST @ _STM-CV-MAP!

    S" resource" 0 _STM-CV-DEST @ _STM-CV-SLOT
        _STM-CV-CHILD !
    _STM-CV-ITEM @ BFM.ITEM.URI _STM-CV-CHILD @ _STM-CV-RESOURCE!
    S" provider" 1 _STM-CV-DEST @ _STM-CV-SLOT
        S" bluesky" ROT _STM-CV-STRING!
    S" provenance" 2 _STM-CV-DEST @ _STM-CV-SLOT
        S" cache" ROT _STM-CV-STRING!
    S" cid" 3 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-CV-ITEM @ BFM.ITEM.CID _STM-CV-CHILD @ _STM-CV-STRING!

    S" author" 4 _STM-CV-DEST @ _STM-CV-SLOT DUP _STM-CV-CHILD !
    3 SWAP _STM-CV-MAP!
    S" did" 0 _STM-CV-CHILD @ _STM-CV-SLOT _STM-CV-NEST !
    _STM-CV-ITEM @ BFM.ITEM.DID _STM-CV-NEST @ _STM-CV-STRING!
    S" handle" 1 _STM-CV-CHILD @ _STM-CV-SLOT _STM-CV-NEST !
    _STM-CV-ITEM @ BFM.ITEM.HANDLE _STM-CV-NEST @ _STM-CV-STRING!
    S" display_name" 2 _STM-CV-CHILD @ _STM-CV-SLOT _STM-CV-NEST !
    _STM-CV-ITEM @ BFM.ITEM.DISPLAY _STM-CV-NEST @ _STM-CV-STRING!

    S" text" 5 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-CV-ITEM @ BFM.ITEM.TEXT _STM-CV-CHILD @ _STM-CV-STRING!
    S" created_at" 6 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-CV-ITEM @ BFM.ITEM.CREATED _STM-CV-CHILD @ _STM-CV-STRING!
    S" indexed_at" 7 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-CV-ITEM @ BFM.ITEM.INDEXED _STM-CV-CHILD @ _STM-CV-STRING!

    S" counts" 8 _STM-CV-DEST @ _STM-CV-SLOT DUP _STM-CV-CHILD !
    3 SWAP _STM-CV-MAP!
    S" likes" 0 _STM-CV-CHILD @ _STM-CV-SLOT _STM-CV-NEST !
    _STM-CV-ITEM @ BFM.ITEM.LIKES @ _STM-CV-NEST @ _STM-CV-INT!
    S" reposts" 1 _STM-CV-CHILD @ _STM-CV-SLOT _STM-CV-NEST !
    _STM-CV-ITEM @ BFM.ITEM.REPOSTS @ _STM-CV-NEST @ _STM-CV-INT!
    S" replies" 2 _STM-CV-CHILD @ _STM-CV-SLOT _STM-CV-NEST !
    _STM-CV-ITEM @ BFM.ITEM.REPLIES @ _STM-CV-NEST @ _STM-CV-INT!

    S" reply" 9 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-CV-ITEM @ BFM.ITEM.FLAGS @ BFM-F-REPLY AND IF
        2 _STM-CV-CHILD @ _STM-CV-MAP!
        S" root" 0 _STM-CV-CHILD @ _STM-CV-SLOT _STM-CV-NEST !
        _STM-CV-ITEM @ BFM.ITEM.ROOT-URI
            _STM-CV-NEST @ _STM-CV-RESOURCE!
        S" parent" 1 _STM-CV-CHILD @ _STM-CV-SLOT _STM-CV-NEST !
        _STM-CV-ITEM @ BFM.ITEM.PARENT-URI
            _STM-CV-NEST @ _STM-CV-RESOURCE!
    ELSE
        _STM-CV-CHILD @ _STM-CV-NULL!
    THEN

    S" reason" 10 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-CV-ITEM @ BFM.ITEM.FLAGS @ BFM-F-PIN AND IF
        S" pin"
    ELSE
        _STM-CV-ITEM @ BFM.ITEM.FLAGS @ BFM-F-REPOST AND IF
            S" repost"
        ELSE
            S" none"
        THEN
    THEN
    _STM-CV-CHILD @ _STM-CV-STRING! ;

: _STM-CV-FEED-STATE  ( -- addr len )
    _STM-FEED-READY @ IF
        _STM-FEED-STATUS @ BFM-S-OK = IF
            S" cached"
        ELSE
            S" cached-after-error"
        THEN
    ELSE
        S" unavailable"
    THEN ;

: _STM-CV-FEED!  ( value -- )
    _STM-CV-DEST ! 6 _STM-CV-DEST @ _STM-CV-MAP!
    S" resource" 0 _STM-CV-DEST @ _STM-CV-SLOT
        S" streams:feed:home" ROT _STM-CV-RESOURCE!
    S" provider" 1 _STM-CV-DEST @ _STM-CV-SLOT
        S" bluesky" ROT _STM-CV-STRING!
    S" provenance" 2 _STM-CV-DEST @ _STM-CV-SLOT
        S" cache" ROT _STM-CV-STRING!
    S" state" 3 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-CV-FEED-STATE _STM-CV-CHILD @ _STM-CV-STRING!
    S" cursor" 4 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-FEED-READY @ _STM-FEED BFM.FEED.CURSOR-U @ 0> AND IF
        _STM-FEED BFM.FEED.CURSOR
            _STM-FEED BFM.FEED.CURSOR-U @
            _STM-CV-CHILD @ _STM-CV-STRING!
    ELSE
        _STM-CV-CHILD @ _STM-CV-NULL!
    THEN
    S" items" 5 _STM-CV-DEST @ _STM-CV-SLOT DUP _STM-CV-LIST !
    _STM-ITEM-COUNT SWAP _STM-CV-LIST!
    _STM-ITEM-COUNT 0 ?DO
        _STM-CV-IOR @ IF LEAVE THEN
        I _STM-URI I _STM-CV-LIST @ CV-LIST-NTH _STM-CV-RESOURCE!
    LOOP ;

: _STM-CV-THREAD-SET-ROOT  ( index -- )
    _STM-ROOT-URI
    _STM-CV-THREAD-ROOT-U ! _STM-CV-THREAD-ROOT-A ! ;

: _STM-CV-THREAD-MEMBER?  ( index -- flag )
    _STM-CV-THREAD-ROOT-A @ _STM-CV-THREAD-ROOT-U @
    _STM-ROOT-MEMBER? ;

: _STM-RELATED-COUNT  ( -- count )
    0 _STM-CV-COUNT !
    _STM-ITEM-COUNT 0 ?DO
        I _STM-CV-THREAD-MEMBER? IF 1 _STM-CV-COUNT +! THEN
    LOOP
    _STM-CV-COUNT @ ;

: _STM-CV-THREAD!  ( focus-index value -- )
    _STM-CV-DEST ! DUP _STM-CV-INDEX ! _STM-CV-THREAD-SET-ROOT
    5 _STM-CV-DEST @ _STM-CV-MAP!
    S" focus" 0 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-CV-INDEX @ _STM-URI _STM-CV-CHILD @ _STM-CV-RESOURCE!
    S" root" 1 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-CV-THREAD-ROOT-A @ _STM-CV-THREAD-ROOT-U @
        _STM-CV-CHILD @ _STM-CV-RESOURCE!
    S" complete" 2 _STM-CV-DEST @ _STM-CV-SLOT
        0 SWAP _STM-CV-BOOL!
    S" provenance" 3 _STM-CV-DEST @ _STM-CV-SLOT
        S" cached-partial-context" ROT _STM-CV-STRING!
    S" items" 4 _STM-CV-DEST @ _STM-CV-SLOT DUP _STM-CV-LIST !
    _STM-RELATED-COUNT SWAP _STM-CV-LIST!
    0 _STM-CV-POS !
    _STM-ITEM-COUNT 0 ?DO
        _STM-CV-IOR @ IF LEAVE THEN
        I _STM-CV-THREAD-MEMBER? IF
            I _STM-URI _STM-CV-POS @ _STM-CV-LIST @ CV-LIST-NTH
                _STM-CV-RESOURCE!
            1 _STM-CV-POS +!
        THEN
    LOOP ;

: _STM-SEARCH-COUNT  ( -- count )
    0 _STM-CV-COUNT !
    _STM-ITEM-COUNT 0 ?DO
        I _STM-QA @ _STM-QU @ _STM-MATCH? IF 1 _STM-CV-COUNT +! THEN
    LOOP
    _STM-CV-COUNT @ ;

: _STM-CV-SEARCH!  ( query-a query-u value -- )
    _STM-CV-DEST ! _STM-QU ! _STM-QA !
    3 _STM-CV-DEST @ _STM-CV-MAP!
    S" query" 0 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-QA @ _STM-QU @ _STM-CV-CHILD @ _STM-CV-STRING!
    S" scope" 1 _STM-CV-DEST @ _STM-CV-SLOT
        S" cache" ROT _STM-CV-STRING!
    S" items" 2 _STM-CV-DEST @ _STM-CV-SLOT DUP _STM-CV-LIST !
    _STM-SEARCH-COUNT SWAP _STM-CV-LIST!
    0 _STM-CV-POS !
    _STM-ITEM-COUNT 0 ?DO
        _STM-CV-IOR @ IF LEAVE THEN
        I _STM-QA @ _STM-QU @ _STM-MATCH? IF
            I _STM-URI _STM-CV-POS @ _STM-CV-LIST @ CV-LIST-NTH
                _STM-CV-RESOURCE!
            1 _STM-CV-POS +!
        THEN
    LOOP ;

VARIABLE _STM-CV-DRAFT-A
VARIABLE _STM-CV-DRAFT-U
VARIABLE _STM-CV-DRAFT-REV

: _STM-CV-DRAFT-FROM!  ( addr len revision value -- )
    _STM-CV-DEST ! _STM-CV-DRAFT-REV !
    _STM-CV-DRAFT-U ! _STM-CV-DRAFT-A !
    3 _STM-CV-DEST @ _STM-CV-MAP!
    S" resource" 0 _STM-CV-DEST @ _STM-CV-SLOT
        S" streams:draft:local" ROT _STM-CV-RESOURCE!
    S" revision" 1 _STM-CV-DEST @ _STM-CV-SLOT
        _STM-CV-DRAFT-REV @ SWAP _STM-CV-INT!
    S" text" 2 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-CV-DRAFT-A @ _STM-CV-DRAFT-U @
        _STM-CV-CHILD @ _STM-CV-STRING! ;

: _STM-CV-DRAFT!  ( value -- )
    _STM-CV-DEST !
    _STM-DRAFT-BUF _STM-DRAFT-U @ _STM-DRAFT-REV @ _STM-CV-DEST @
        _STM-CV-DRAFT-FROM! ;

\ Draft command results are constructed away from the caller-owned result.
\ Once persistence and the in-memory commit both succeed, ownership of the
\ complete CV graph can be transferred without another allocation or failure.
CREATE _STM-DRAFT-RESULT-CANDIDATE CV-SIZE ALLOT
_STM-DRAFT-RESULT-CANDIDATE CV-INIT
VARIABLE _STM-DRAFT-RESULT-DEST

: _STM-DRAFT-RESULT-DISCARD  ( -- )
    _STM-DRAFT-RESULT-CANDIDATE CV-FREE ;

: _STM-DRAFT-RESULT-BUILD  ( addr len revision -- status )
    _STM-DRAFT-RESULT-DISCARD
    _STM-CV-BEGIN
    _STM-DRAFT-RESULT-CANDIDATE _STM-CV-DRAFT-FROM!
    _STM-DRAFT-RESULT-CANDIDATE _STM-CV-FINISH ?DUP IF EXIT THEN
    _STM-DRAFT-RESULT-CANDIDATE _STM-DRAFT-SCHEMA
        CS-VALIDATE-DEEP ?DUP IF
        DROP _STM-DRAFT-RESULT-DISCARD CBUS-S-FAILED EXIT
    THEN
    CBUS-S-OK ;

: _STM-DRAFT-RESULT-PUBLISH  ( result -- )
    _STM-DRAFT-RESULT-DEST !
    _STM-DRAFT-RESULT-DEST @ CV-FREE
    _STM-DRAFT-RESULT-CANDIDATE _STM-DRAFT-RESULT-DEST @ CV-SIZE CMOVE
    _STM-DRAFT-RESULT-CANDIDATE CV-INIT ;

: _STM-CV-DRAFT-VALIDATION!  ( value -- )
    _STM-CV-DEST ! 7 _STM-CV-DEST @ _STM-CV-MAP!
    S" resource" 0 _STM-CV-DEST @ _STM-CV-SLOT
        S" streams:draft:local" ROT _STM-CV-RESOURCE!
    S" revision" 1 _STM-CV-DEST @ _STM-CV-SLOT
        _STM-DRAFT-REV @ SWAP _STM-CV-INT!
    S" local_valid" 2 _STM-CV-DEST @ _STM-CV-SLOT
        _STM-DRAFT-U @ 0> SWAP _STM-CV-BOOL!
    S" byte_count" 3 _STM-CV-DEST @ _STM-CV-SLOT
        _STM-DRAFT-U @ SWAP _STM-CV-INT!
    S" publishability" 4 _STM-CV-DEST @ _STM-CV-SLOT
        S" unchecked" ROT _STM-CV-STRING!
    S" external_effect" 5 _STM-CV-DEST @ _STM-CV-SLOT
        S" none" ROT _STM-CV-STRING!
    S" problem" 6 _STM-CV-DEST @ _STM-CV-SLOT _STM-CV-CHILD !
    _STM-DRAFT-U @ 0= IF
        S" draft is empty" _STM-CV-CHILD @ _STM-CV-STRING!
    ELSE
        _STM-CV-CHILD @ _STM-CV-NULL!
    THEN ;

: _STM-DRAFT-RESOURCE?  ( value -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP CV-TYPE@ CV-T-RESOURCE <> IF DROP 0 EXIT THEN
    DUP CV-DATA@ SWAP CV-LEN@
    S" streams:draft:local" STR-STR= ;

: _STM-CAP-SELECTION-H  ( request instance -- status )
    _STM-ACTIVATE _STM-CAP-REQ ! _STM-CV-BEGIN
    _STM-CAP-REQ @ CBR.RESULT DUP
    _STM-ITEM-COUNT 0= _STM-SELECTED @ 0< OR
    _STM-SELECTED @ _STM-ITEM-COUNT >= OR IF
        CV-NULL!
    ELSE
        _STM-SELECTED @ _STM-URI ROT CV-RESOURCE! ?DUP IF
            _STM-CV-FAIL!
        THEN
    THEN
    _STM-CV-FINISH ;

: _STM-CAP-ITEM-H  ( request instance -- status )
    _STM-ACTIVATE DUP _STM-CAP-REQ ! CBR.ARGS _STM-CAP-ARGS !
    _STM-CAP-ARGS @ DUP CV-TYPE@ CV-T-RESOURCE <> IF
        DROP CBUS-S-INVALID EXIT
    THEN
    DUP CV-DATA@ SWAP CV-LEN@ _STM-INDEX-FROM-URI
    0= IF DROP CBUS-S-NOT-FOUND EXIT THEN _STM-CAP-I !
    _STM-CV-BEGIN
    _STM-CAP-I @ _STM-CAP-REQ @ CBR.RESULT _STM-CV-ITEM!
    _STM-CAP-REQ @ CBR.RESULT _STM-CV-FINISH ;

: _STM-CAP-THREAD-H  ( request instance -- status )
    _STM-ACTIVATE DUP _STM-CAP-REQ ! CBR.ARGS _STM-CAP-ARGS !
    _STM-CAP-ARGS @ DUP CV-TYPE@ CV-T-RESOURCE <> IF
        DROP CBUS-S-INVALID EXIT
    THEN
    DUP CV-DATA@ SWAP CV-LEN@ _STM-INDEX-FROM-URI
    0= IF DROP CBUS-S-NOT-FOUND EXIT THEN _STM-CAP-I !
    _STM-CV-BEGIN
    _STM-CAP-I @ _STM-CAP-REQ @ CBR.RESULT _STM-CV-THREAD!
    _STM-CAP-REQ @ CBR.RESULT _STM-CV-FINISH ;

: _STM-CAP-FEED-H  ( request instance -- status )
    _STM-ACTIVATE _STM-CAP-REQ ! _STM-CV-BEGIN
    _STM-CAP-REQ @ CBR.RESULT DUP _STM-CV-FEED! _STM-CV-FINISH ;

: _STM-CAP-SEARCH-H  ( request instance -- status )
    _STM-ACTIVATE DUP _STM-CAP-REQ ! CBR.ARGS _STM-CAP-ARGS !
    _STM-CAP-ARGS @ DUP CV-TYPE@ CV-T-STRING <> IF
        DROP CBUS-S-INVALID EXIT
    THEN
    DUP CV-LEN@ DUP 0< OVER _STM-QUERY-CAP > OR IF
        2DROP CBUS-S-INVALID EXIT
    THEN
    _STM-CAP-U ! CV-DATA@ _STM-CAP-A !
    _STM-CAP-A @ _STM-CAP-U @ UTF8-VALID? 0= IF CBUS-S-INVALID EXIT THEN
    _STM-CV-BEGIN
    _STM-CAP-A @ _STM-CAP-U @ _STM-CAP-REQ @ CBR.RESULT
        _STM-CV-SEARCH!
    _STM-CAP-REQ @ CBR.RESULT _STM-CV-FINISH ;

: _STM-CAP-DRAFT-CREATE-H  ( request instance -- status )
    _STM-ACTIVATE DUP _STM-CAP-REQ ! CBR.ARGS _STM-CAP-ARGS !
    _STM-DRAFT-PERSIST-MODE @ _STM-DP-BLOCKED = IF
        CBUS-S-FAILED EXIT
    THEN
    _STM-DRAFT-REV @ IF CBUS-S-BUSY EXIT THEN
    S" text" _STM-CAP-ARGS @ CV-MAP-FIND DUP 0= IF
        DROP CBUS-S-INVALID EXIT
    THEN
    DUP CV-TYPE@ CV-T-STRING <> IF DROP CBUS-S-INVALID EXIT THEN
    DUP CV-LEN@ DUP 0< OVER _STM-DRAFT-CAP > OR IF
        2DROP CBUS-S-INVALID EXIT
    THEN
    _STM-CAP-U ! CV-DATA@ _STM-CAP-A !
    _STM-CAP-A @ _STM-CAP-U @ UTF8-VALID? 0= IF
        CBUS-S-INVALID EXIT
    THEN
    _STM-CAP-A @ _STM-CAP-U @ 1 _STM-DRAFT-RESULT-BUILD
        ?DUP IF EXIT THEN
    _STM-CAP-A @ _STM-CAP-U @ _STM-DRAFT! 0= IF
        _STM-DRAFT-RESULT-DISCARD _STM-INVALIDATE
        CBUS-S-FAILED EXIT
    THEN
    _STM-CAP-REQ @ CBR.RESULT _STM-DRAFT-RESULT-PUBLISH
    _STM-INVALIDATE CBUS-S-OK ;
: _STM-CAP-DRAFT-READ-H  ( request instance -- status )
    _STM-ACTIVATE DUP _STM-CAP-REQ ! CBR.ARGS _STM-DRAFT-RESOURCE?
    0= IF CBUS-S-NOT-FOUND EXIT THEN
    _STM-DRAFT-REV @ 0= IF CBUS-S-NOT-FOUND EXIT THEN
    _STM-CV-BEGIN
    _STM-CAP-REQ @ CBR.RESULT DUP _STM-CV-DRAFT! _STM-CV-FINISH ;
: _STM-CAP-DRAFT-REPLACE-H  ( request instance -- status )
    _STM-ACTIVATE DUP _STM-CAP-REQ ! CBR.ARGS _STM-CAP-ARGS !
    _STM-DRAFT-PERSIST-MODE @ _STM-DP-BLOCKED = IF
        CBUS-S-FAILED EXIT
    THEN
    S" resource" _STM-CAP-ARGS @ CV-MAP-FIND _STM-DRAFT-RESOURCE?
    0= IF CBUS-S-NOT-FOUND EXIT THEN
    _STM-DRAFT-REV @ 0= IF CBUS-S-NOT-FOUND EXIT THEN
    S" expected_revision" _STM-CAP-ARGS @ CV-MAP-FIND DUP 0= IF
        DROP CBUS-S-INVALID EXIT
    THEN
    DUP CV-TYPE@ CV-T-INT <> IF DROP CBUS-S-INVALID EXIT THEN
    CV-DATA@ DUP 0< IF DROP CBUS-S-INVALID EXIT THEN _STM-CAP-EXPECTED !
    _STM-CAP-EXPECTED @ _STM-DRAFT-REV @ <> IF
        CBUS-S-STALE-REVISION EXIT
    THEN
    S" text" _STM-CAP-ARGS @ CV-MAP-FIND DUP 0= IF
        DROP CBUS-S-INVALID EXIT
    THEN
    DUP CV-TYPE@ CV-T-STRING <> IF DROP CBUS-S-INVALID EXIT THEN
    DUP CV-LEN@ DUP 0< OVER _STM-DRAFT-CAP > OR IF
        2DROP CBUS-S-INVALID EXIT
    THEN
    _STM-CAP-U ! CV-DATA@ _STM-CAP-A !
    _STM-CAP-A @ _STM-CAP-U @ UTF8-VALID? 0= IF
        CBUS-S-INVALID EXIT
    THEN
    _STM-DRAFT-REV @ CV-CELL-MAX >= IF CBUS-S-FAILED EXIT THEN
    _STM-CAP-A @ _STM-CAP-U @ _STM-DRAFT-REV @ 1+
        _STM-DRAFT-RESULT-BUILD ?DUP IF EXIT THEN
    _STM-CAP-A @ _STM-CAP-U @ _STM-DRAFT! 0= IF
        _STM-DRAFT-RESULT-DISCARD _STM-INVALIDATE
        CBUS-S-FAILED EXIT
    THEN
    _STM-CAP-REQ @ CBR.RESULT _STM-DRAFT-RESULT-PUBLISH
    _STM-INVALIDATE CBUS-S-OK ;
: _STM-CAP-DRAFT-VALIDATE-H  ( request instance -- status )
    _STM-ACTIVATE DUP _STM-CAP-REQ ! CBR.ARGS _STM-DRAFT-RESOURCE?
    0= IF CBUS-S-NOT-FOUND EXIT THEN
    _STM-DRAFT-REV @ 0= IF CBUS-S-NOT-FOUND EXIT THEN
    _STM-CV-BEGIN
    _STM-CAP-REQ @ CBR.RESULT DUP
        _STM-CV-DRAFT-VALIDATION! _STM-CV-FINISH ;

: _STM-CAP-DRAFT-CURRENT-H  ( request instance -- status )
    _STM-ACTIVATE _STM-CAP-REQ ! _STM-CV-BEGIN
    _STM-CAP-REQ @ CBR.RESULT DUP
    _STM-DRAFT-REV @ 0= IF
        CV-NULL!
    ELSE
        S" streams:draft:local" ROT CV-RESOURCE! ?DUP IF
            _STM-CV-FAIL!
        THEN
    THEN
    _STM-CV-FINISH ;

: _STM-CAP-COMMON  ( cap -- )
    DUP CAP-DESC-INIT CAP-F-NEEDS-TARGET SWAP CAP.FLAGS ! ;
VARIABLE _STM-MD-C
VARIABLE _STM-MD-K
VARIABLE _STM-MD-IA
VARIABLE _STM-MD-IU
VARIABLE _STM-MD-TA
VARIABLE _STM-MD-TU
VARIABLE _STM-MD-DA
VARIABLE _STM-MD-DU
: _STM-CAP-META  ( cap kind id-a id-u title-a title-u desc-a desc-u -- )
    _STM-MD-DU ! _STM-MD-DA ! _STM-MD-TU ! _STM-MD-TA !
    _STM-MD-IU ! _STM-MD-IA ! _STM-MD-K ! _STM-MD-C !
    _STM-MD-C @ _STM-CAP-COMMON
    _STM-MD-K @ _STM-MD-C @ CAP.KIND !
    _STM-MD-IA @ _STM-MD-C @ CAP.ID-A !
    _STM-MD-IU @ _STM-MD-C @ CAP.ID-U !
    _STM-MD-TA @ _STM-MD-C @ CAP.TITLE-A !
    _STM-MD-TU @ _STM-MD-C @ CAP.TITLE-U !
    _STM-MD-DA @ _STM-MD-C @ CAP.DESC-A !
    _STM-MD-DU @ _STM-MD-C @ CAP.DESC-U ! ;

VARIABLE _STM-SF-A
VARIABLE _STM-SF-U
VARIABLE _STM-SF-S
VARIABLE _STM-SF-F
VARIABLE _STM-SF-D
: _STM-SCHEMA-FIELD!  ( key-a key-u schema flags field -- )
    _STM-SF-D ! _STM-SF-F ! _STM-SF-S ! _STM-SF-U ! _STM-SF-A !
    _STM-SF-D @ CS-FIELD-SIZE 0 FILL
    _STM-SF-A @ _STM-SF-D @ CSF.KEY-A !
    _STM-SF-U @ _STM-SF-D @ CSF.KEY-U !
    _STM-SF-S @ _STM-SF-D @ CSF.SCHEMA !
    _STM-SF-F @ _STM-SF-D @ CSF.FLAGS ! ;

VARIABLE _STM-SM-F
VARIABLE _STM-SM-N
VARIABLE _STM-SM-S
: _STM-MAP-SCHEMA!  ( fields count schema -- )
    _STM-SM-S ! _STM-SM-N ! _STM-SM-F !
    _STM-SM-S @ CS-INIT CV-T-MAP _STM-SM-S @ CS-ALLOW!
    _STM-SM-N @ _STM-SM-S @ CS-MAX-LEN!
    _STM-SM-F @ _STM-SM-S @ CS.FIELDS !
    _STM-SM-N @ _STM-SM-S @ CS.FIELD-N ! ;

VARIABLE _STM-SS-N
VARIABLE _STM-SS-S
: _STM-STRING-SCHEMA!  ( max-len schema -- )
    _STM-SS-S ! _STM-SS-N !
    _STM-SS-S @ CS-INIT CV-T-STRING _STM-SS-S @ CS-ALLOW!
    _STM-SS-N @ _STM-SS-S @ CS-MAX-LEN! ;

: _STM-SCHEMA-SETUP  ( -- )
    _STM-NULL-SCHEMA CS-INIT CV-T-NULL _STM-NULL-SCHEMA CS-ALLOW!
    _STM-BOOL-SCHEMA CS-INIT CV-T-BOOL _STM-BOOL-SCHEMA CS-ALLOW!
    _STM-COUNT-SCHEMA CS-INIT CV-T-INT _STM-COUNT-SCHEMA CS-ALLOW!
    0 _STM-COUNT-SCHEMA CS-MIN!
    _STM-REVISION-SCHEMA CS-INIT CV-T-INT _STM-REVISION-SCHEMA CS-ALLOW!
    0 _STM-REVISION-SCHEMA CS-MIN!
    128 _STM-META-SCHEMA _STM-STRING-SCHEMA!
    BFM-CID-CAP _STM-CID-SCHEMA _STM-STRING-SCHEMA!
    BFM-DID-CAP _STM-DID-SCHEMA _STM-STRING-SCHEMA!
    BFM-HANDLE-CAP _STM-HANDLE-SCHEMA _STM-STRING-SCHEMA!
    BFM-DISPLAY-CAP _STM-DISPLAY-SCHEMA _STM-STRING-SCHEMA!
    _STM-DRAFT-CAP _STM-TEXT-SCHEMA _STM-STRING-SCHEMA!
    BFM-DATETIME-CAP _STM-DATETIME-SCHEMA _STM-STRING-SCHEMA!
    _STM-QUERY-CAP _STM-QUERY-SCHEMA _STM-STRING-SCHEMA!

    _STM-RESOURCE-SCHEMA CS-INIT
    CV-T-RESOURCE _STM-RESOURCE-SCHEMA CS-ALLOW!
    BFM-URI-CAP _STM-RESOURCE-SCHEMA CS-MAX-LEN!
    _STM-NULLABLE-RESOURCE-SCHEMA CS-INIT
    CV-T-NULL CS-TYPE-BIT CV-T-RESOURCE CS-TYPE-BIT OR
        _STM-NULLABLE-RESOURCE-SCHEMA CS-ALLOW-MASK!
    BFM-URI-CAP _STM-NULLABLE-RESOURCE-SCHEMA CS-MAX-LEN!
    _STM-CURSOR-SCHEMA CS-INIT
    CV-T-NULL CS-TYPE-BIT CV-T-STRING CS-TYPE-BIT OR
        _STM-CURSOR-SCHEMA CS-ALLOW-MASK!
    BFM-CURSOR-CAP _STM-CURSOR-SCHEMA CS-MAX-LEN!
    _STM-NULLABLE-META-SCHEMA CS-INIT
    CV-T-NULL CS-TYPE-BIT CV-T-STRING CS-TYPE-BIT OR
        _STM-NULLABLE-META-SCHEMA CS-ALLOW-MASK!
    128 _STM-NULLABLE-META-SCHEMA CS-MAX-LEN!

    S" did" _STM-DID-SCHEMA CSF-F-REQUIRED
        _STM-AUTHOR-FIELDS _STM-SCHEMA-FIELD!
    S" handle" _STM-HANDLE-SCHEMA CSF-F-REQUIRED
        _STM-AUTHOR-FIELDS CS-FIELD-SIZE + _STM-SCHEMA-FIELD!
    S" display_name" _STM-DISPLAY-SCHEMA CSF-F-REQUIRED
        _STM-AUTHOR-FIELDS CS-FIELD-SIZE 2 * + _STM-SCHEMA-FIELD!
    _STM-AUTHOR-FIELDS 3 _STM-AUTHOR-SCHEMA _STM-MAP-SCHEMA!

    S" likes" _STM-COUNT-SCHEMA CSF-F-REQUIRED
        _STM-COUNTS-FIELDS _STM-SCHEMA-FIELD!
    S" reposts" _STM-COUNT-SCHEMA CSF-F-REQUIRED
        _STM-COUNTS-FIELDS CS-FIELD-SIZE + _STM-SCHEMA-FIELD!
    S" replies" _STM-COUNT-SCHEMA CSF-F-REQUIRED
        _STM-COUNTS-FIELDS CS-FIELD-SIZE 2 * + _STM-SCHEMA-FIELD!
    _STM-COUNTS-FIELDS 3 _STM-COUNTS-SCHEMA _STM-MAP-SCHEMA!

    S" root" _STM-RESOURCE-SCHEMA CSF-F-REQUIRED
        _STM-REPLY-FIELDS _STM-SCHEMA-FIELD!
    S" parent" _STM-RESOURCE-SCHEMA CSF-F-REQUIRED
        _STM-REPLY-FIELDS CS-FIELD-SIZE + _STM-SCHEMA-FIELD!
    _STM-REPLY-SCHEMA CS-INIT
    CV-T-NULL CS-TYPE-BIT CV-T-MAP CS-TYPE-BIT OR
        _STM-REPLY-SCHEMA CS-ALLOW-MASK!
    2 _STM-REPLY-SCHEMA CS-MAX-LEN!
    _STM-REPLY-FIELDS _STM-REPLY-SCHEMA CS.FIELDS !
    2 _STM-REPLY-SCHEMA CS.FIELD-N !

    S" resource" _STM-RESOURCE-SCHEMA CSF-F-REQUIRED
        _STM-ITEM-FIELDS _STM-SCHEMA-FIELD!
    S" provider" _STM-META-SCHEMA CSF-F-REQUIRED
        _STM-ITEM-FIELDS CS-FIELD-SIZE + _STM-SCHEMA-FIELD!
    S" provenance" _STM-META-SCHEMA CSF-F-REQUIRED
        _STM-ITEM-FIELDS CS-FIELD-SIZE 2 * + _STM-SCHEMA-FIELD!
    S" cid" _STM-CID-SCHEMA CSF-F-REQUIRED
        _STM-ITEM-FIELDS CS-FIELD-SIZE 3 * + _STM-SCHEMA-FIELD!
    S" author" _STM-AUTHOR-SCHEMA CSF-F-REQUIRED
        _STM-ITEM-FIELDS CS-FIELD-SIZE 4 * + _STM-SCHEMA-FIELD!
    S" text" _STM-TEXT-SCHEMA CSF-F-REQUIRED
        _STM-ITEM-FIELDS CS-FIELD-SIZE 5 * + _STM-SCHEMA-FIELD!
    S" created_at" _STM-DATETIME-SCHEMA CSF-F-REQUIRED
        _STM-ITEM-FIELDS CS-FIELD-SIZE 6 * + _STM-SCHEMA-FIELD!
    S" indexed_at" _STM-DATETIME-SCHEMA CSF-F-REQUIRED
        _STM-ITEM-FIELDS CS-FIELD-SIZE 7 * + _STM-SCHEMA-FIELD!
    S" counts" _STM-COUNTS-SCHEMA CSF-F-REQUIRED
        _STM-ITEM-FIELDS CS-FIELD-SIZE 8 * + _STM-SCHEMA-FIELD!
    S" reply" _STM-REPLY-SCHEMA CSF-F-REQUIRED
        _STM-ITEM-FIELDS CS-FIELD-SIZE 9 * + _STM-SCHEMA-FIELD!
    S" reason" _STM-META-SCHEMA CSF-F-REQUIRED
        _STM-ITEM-FIELDS CS-FIELD-SIZE 10 * + _STM-SCHEMA-FIELD!
    _STM-ITEM-FIELDS 11 _STM-ITEM-SCHEMA _STM-MAP-SCHEMA!
    _STM-RESOURCE-LIST-SCHEMA CS-INIT
    CV-T-LIST _STM-RESOURCE-LIST-SCHEMA CS-ALLOW!
    BFM-MAX-ITEMS _STM-RESOURCE-LIST-SCHEMA CS-MAX-LEN!
    _STM-RESOURCE-SCHEMA _STM-RESOURCE-LIST-SCHEMA CS.ITEM !

    S" resource" _STM-RESOURCE-SCHEMA CSF-F-REQUIRED
        _STM-FEED-FIELDS _STM-SCHEMA-FIELD!
    S" provider" _STM-META-SCHEMA CSF-F-REQUIRED
        _STM-FEED-FIELDS CS-FIELD-SIZE + _STM-SCHEMA-FIELD!
    S" provenance" _STM-META-SCHEMA CSF-F-REQUIRED
        _STM-FEED-FIELDS CS-FIELD-SIZE 2 * + _STM-SCHEMA-FIELD!
    S" state" _STM-META-SCHEMA CSF-F-REQUIRED
        _STM-FEED-FIELDS CS-FIELD-SIZE 3 * + _STM-SCHEMA-FIELD!
    S" cursor" _STM-CURSOR-SCHEMA CSF-F-REQUIRED
        _STM-FEED-FIELDS CS-FIELD-SIZE 4 * + _STM-SCHEMA-FIELD!
    S" items" _STM-RESOURCE-LIST-SCHEMA CSF-F-REQUIRED
        _STM-FEED-FIELDS CS-FIELD-SIZE 5 * + _STM-SCHEMA-FIELD!
    _STM-FEED-FIELDS 6 _STM-FEED-SCHEMA _STM-MAP-SCHEMA!

    S" focus" _STM-RESOURCE-SCHEMA CSF-F-REQUIRED
        _STM-THREAD-FIELDS _STM-SCHEMA-FIELD!
    S" root" _STM-RESOURCE-SCHEMA CSF-F-REQUIRED
        _STM-THREAD-FIELDS CS-FIELD-SIZE + _STM-SCHEMA-FIELD!
    S" complete" _STM-BOOL-SCHEMA CSF-F-REQUIRED
        _STM-THREAD-FIELDS CS-FIELD-SIZE 2 * + _STM-SCHEMA-FIELD!
    S" provenance" _STM-META-SCHEMA CSF-F-REQUIRED
        _STM-THREAD-FIELDS CS-FIELD-SIZE 3 * + _STM-SCHEMA-FIELD!
    S" items" _STM-RESOURCE-LIST-SCHEMA CSF-F-REQUIRED
        _STM-THREAD-FIELDS CS-FIELD-SIZE 4 * + _STM-SCHEMA-FIELD!
    _STM-THREAD-FIELDS 5 _STM-THREAD-SCHEMA _STM-MAP-SCHEMA!

    S" query" _STM-QUERY-SCHEMA CSF-F-REQUIRED
        _STM-SEARCH-FIELDS _STM-SCHEMA-FIELD!
    S" scope" _STM-META-SCHEMA CSF-F-REQUIRED
        _STM-SEARCH-FIELDS CS-FIELD-SIZE + _STM-SCHEMA-FIELD!
    S" items" _STM-RESOURCE-LIST-SCHEMA CSF-F-REQUIRED
        _STM-SEARCH-FIELDS CS-FIELD-SIZE 2 * + _STM-SCHEMA-FIELD!
    _STM-SEARCH-FIELDS 3 _STM-SEARCH-SCHEMA _STM-MAP-SCHEMA!

    S" resource" _STM-RESOURCE-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-FIELDS _STM-SCHEMA-FIELD!
    S" revision" _STM-REVISION-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-FIELDS CS-FIELD-SIZE + _STM-SCHEMA-FIELD!
    S" text" _STM-TEXT-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-FIELDS CS-FIELD-SIZE 2 * + _STM-SCHEMA-FIELD!
    _STM-DRAFT-FIELDS 3 _STM-DRAFT-SCHEMA _STM-MAP-SCHEMA!

    S" resource" _STM-RESOURCE-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-VALIDATION-FIELDS _STM-SCHEMA-FIELD!
    S" revision" _STM-REVISION-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-VALIDATION-FIELDS CS-FIELD-SIZE + _STM-SCHEMA-FIELD!
    S" local_valid" _STM-BOOL-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-VALIDATION-FIELDS CS-FIELD-SIZE 2 * + _STM-SCHEMA-FIELD!
    S" byte_count" _STM-COUNT-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-VALIDATION-FIELDS CS-FIELD-SIZE 3 * + _STM-SCHEMA-FIELD!
    S" publishability" _STM-META-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-VALIDATION-FIELDS CS-FIELD-SIZE 4 * + _STM-SCHEMA-FIELD!
    S" external_effect" _STM-META-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-VALIDATION-FIELDS CS-FIELD-SIZE 5 * + _STM-SCHEMA-FIELD!
    S" problem" _STM-NULLABLE-META-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-VALIDATION-FIELDS CS-FIELD-SIZE 6 * + _STM-SCHEMA-FIELD!
    _STM-DRAFT-VALIDATION-FIELDS 7 _STM-DRAFT-VALIDATION-SCHEMA
        _STM-MAP-SCHEMA!

    S" text" _STM-TEXT-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-CREATE-FIELDS _STM-SCHEMA-FIELD!
    _STM-DRAFT-CREATE-FIELDS 1 _STM-DRAFT-CREATE-SCHEMA _STM-MAP-SCHEMA!
    S" resource" _STM-RESOURCE-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-REPLACE-FIELDS _STM-SCHEMA-FIELD!
    S" expected_revision" _STM-REVISION-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-REPLACE-FIELDS CS-FIELD-SIZE + _STM-SCHEMA-FIELD!
    S" text" _STM-TEXT-SCHEMA CSF-F-REQUIRED
        _STM-DRAFT-REPLACE-FIELDS CS-FIELD-SIZE 2 * + _STM-SCHEMA-FIELD!
    _STM-DRAFT-REPLACE-FIELDS 3 _STM-DRAFT-REPLACE-SCHEMA
        _STM-MAP-SCHEMA! ;

: _STM-CAP-SETUP  ( -- )
    _STM-SCHEMA-SETUP

    STREAMS-CAP-SELECTION CAP-K-RESOURCE
    S" streams.selection.current" S" Current item" S" Read the selected retained item resource if present"
    _STM-CAP-META
    _STM-NULL-SCHEMA STREAMS-CAP-SELECTION CAP.IN-SCHEMA !
    _STM-NULLABLE-RESOURCE-SCHEMA STREAMS-CAP-SELECTION CAP.OUT-SCHEMA !
    CAP-E-OBSERVE STREAMS-CAP-SELECTION CAP.EFFECTS !
    CAP-F-IDEMPOTENT CAP-F-NEEDS-TARGET OR CAP-F-CONTEXT-DEFAULT OR STREAMS-CAP-SELECTION CAP.FLAGS !
    ['] _STM-CAP-SELECTION-H STREAMS-CAP-SELECTION CAP.HANDLER-XT !

    STREAMS-CAP-ITEM CAP-K-RESOURCE
    S" streams.item.read" S" Read item" S" Read the canonical bounded map for an explicit retained item"
    _STM-CAP-META _STM-RESOURCE-SCHEMA STREAMS-CAP-ITEM CAP.IN-SCHEMA !
    _STM-ITEM-SCHEMA STREAMS-CAP-ITEM CAP.OUT-SCHEMA ! CAP-E-OBSERVE STREAMS-CAP-ITEM CAP.EFFECTS !
    CAP-F-IDEMPOTENT CAP-F-NEEDS-TARGET OR STREAMS-CAP-ITEM CAP.FLAGS !
    ['] _STM-CAP-ITEM-H STREAMS-CAP-ITEM CAP.HANDLER-XT !

    STREAMS-CAP-THREAD CAP-K-RESOURCE
    S" streams.thread.read" S" Read context" S" Read ordered resources from the retained partial context of an explicit item"
    _STM-CAP-META _STM-RESOURCE-SCHEMA STREAMS-CAP-THREAD CAP.IN-SCHEMA !
    _STM-THREAD-SCHEMA STREAMS-CAP-THREAD CAP.OUT-SCHEMA ! CAP-E-OBSERVE STREAMS-CAP-THREAD CAP.EFFECTS !
    CAP-F-IDEMPOTENT CAP-F-NEEDS-TARGET OR STREAMS-CAP-THREAD CAP.FLAGS !
    ['] _STM-CAP-THREAD-H STREAMS-CAP-THREAD CAP.HANDLER-XT !

    STREAMS-CAP-FEED CAP-K-RESOURCE
    S" streams.feed.read" S" Read feed" S" Read the bounded retained item-resource page and cache state"
    _STM-CAP-META _STM-NULL-SCHEMA STREAMS-CAP-FEED CAP.IN-SCHEMA !
    _STM-FEED-SCHEMA STREAMS-CAP-FEED CAP.OUT-SCHEMA ! CAP-E-OBSERVE STREAMS-CAP-FEED CAP.EFFECTS !
    CAP-F-IDEMPOTENT CAP-F-NEEDS-TARGET OR STREAMS-CAP-FEED CAP.FLAGS !
    ['] _STM-CAP-FEED-H STREAMS-CAP-FEED CAP.HANDLER-XT !

    STREAMS-CAP-SEARCH CAP-K-RESOURCE
    S" streams.search.local" S" Search cache" S" Find retained item resources by author and text"
    _STM-CAP-META _STM-QUERY-SCHEMA STREAMS-CAP-SEARCH CAP.IN-SCHEMA !
    _STM-SEARCH-SCHEMA STREAMS-CAP-SEARCH CAP.OUT-SCHEMA ! CAP-E-OBSERVE STREAMS-CAP-SEARCH CAP.EFFECTS !
    CAP-F-IDEMPOTENT CAP-F-NEEDS-TARGET OR STREAMS-CAP-SEARCH CAP.FLAGS !
    ['] _STM-CAP-SEARCH-H STREAMS-CAP-SEARCH CAP.HANDLER-XT !

    STREAMS-CAP-DRAFT-CREATE CAP-K-COMMAND
    S" streams.draft.create" S" Create draft" S" Create the target-scoped unpublished draft if absent"
    _STM-CAP-META _STM-DRAFT-CREATE-SCHEMA STREAMS-CAP-DRAFT-CREATE CAP.IN-SCHEMA !
    _STM-DRAFT-SCHEMA STREAMS-CAP-DRAFT-CREATE CAP.OUT-SCHEMA !
    CAP-E-MUTATE CAP-E-PERSIST OR
        STREAMS-CAP-DRAFT-CREATE CAP.EFFECTS !
    ['] _STM-CAP-DRAFT-CREATE-H STREAMS-CAP-DRAFT-CREATE CAP.HANDLER-XT !

    STREAMS-CAP-DRAFT-READ CAP-K-RESOURCE
    S" streams.draft.read" S" Read draft" S" Read the local unpublished draft and revision"
    _STM-CAP-META _STM-RESOURCE-SCHEMA STREAMS-CAP-DRAFT-READ CAP.IN-SCHEMA !
    _STM-DRAFT-SCHEMA STREAMS-CAP-DRAFT-READ CAP.OUT-SCHEMA ! CAP-E-OBSERVE STREAMS-CAP-DRAFT-READ CAP.EFFECTS !
    CAP-F-IDEMPOTENT CAP-F-NEEDS-TARGET OR STREAMS-CAP-DRAFT-READ CAP.FLAGS !
    ['] _STM-CAP-DRAFT-READ-H STREAMS-CAP-DRAFT-READ CAP.HANDLER-XT !

    STREAMS-CAP-DRAFT-REPLACE CAP-K-COMMAND
    S" streams.draft.replace" S" Replace draft" S" Replace an exact draft revision without publishing"
    _STM-CAP-META _STM-DRAFT-REPLACE-SCHEMA STREAMS-CAP-DRAFT-REPLACE CAP.IN-SCHEMA !
    _STM-DRAFT-SCHEMA STREAMS-CAP-DRAFT-REPLACE CAP.OUT-SCHEMA !
    CAP-E-MUTATE CAP-E-PERSIST OR
        STREAMS-CAP-DRAFT-REPLACE CAP.EFFECTS !
    ['] _STM-CAP-DRAFT-REPLACE-H STREAMS-CAP-DRAFT-REPLACE CAP.HANDLER-XT !

    STREAMS-CAP-DRAFT-VALIDATE CAP-K-RESOURCE
    S" streams.draft.validate" S" Validate draft" S" Validate the draft without publishing or network access"
    _STM-CAP-META _STM-RESOURCE-SCHEMA STREAMS-CAP-DRAFT-VALIDATE CAP.IN-SCHEMA !
    _STM-DRAFT-VALIDATION-SCHEMA STREAMS-CAP-DRAFT-VALIDATE CAP.OUT-SCHEMA ! CAP-E-OBSERVE STREAMS-CAP-DRAFT-VALIDATE CAP.EFFECTS !
    CAP-F-IDEMPOTENT CAP-F-NEEDS-TARGET OR STREAMS-CAP-DRAFT-VALIDATE CAP.FLAGS !
    ['] _STM-CAP-DRAFT-VALIDATE-H STREAMS-CAP-DRAFT-VALIDATE CAP.HANDLER-XT !

    STREAMS-CAP-DRAFT-CURRENT CAP-K-RESOURCE
    S" streams.draft.current" S" Current draft" S" Read the target-scoped unpublished draft resource if present"
    _STM-CAP-META
    _STM-NULL-SCHEMA STREAMS-CAP-DRAFT-CURRENT CAP.IN-SCHEMA !
    _STM-NULLABLE-RESOURCE-SCHEMA
        STREAMS-CAP-DRAFT-CURRENT CAP.OUT-SCHEMA !
    CAP-E-OBSERVE STREAMS-CAP-DRAFT-CURRENT CAP.EFFECTS !
    CAP-F-IDEMPOTENT CAP-F-NEEDS-TARGET OR CAP-F-CONTEXT-DEFAULT OR
        STREAMS-CAP-DRAFT-CURRENT CAP.FLAGS !
    ['] _STM-CAP-DRAFT-CURRENT-H
        STREAMS-CAP-DRAFT-CURRENT CAP.HANDLER-XT ! ;

CREATE STREAMS-COMP-DESC COMP-DESC ALLOT
: _STREAMS-COMP-SETUP  ( -- )
    _STM-CAP-SETUP STREAMS-COMP-DESC COMP-DESC-INIT
    S" org.akashic.streams" STREAMS-COMP-DESC COMP.ID-U ! STREAMS-COMP-DESC COMP.ID-A !
    S" 0.2.0" STREAMS-COMP-DESC COMP.VERSION-U ! STREAMS-COMP-DESC COMP.VERSION-A !
    _STM-STATE-SIZE STREAMS-COMP-DESC COMP.STATE-SIZE !
    ['] _STM-STATE-FINI STREAMS-COMP-DESC COMP.STATE-FINI-XT !
    STREAMS-CAPS STREAMS-COMP-DESC COMP.CAPS-A !
    _STM-CAP-COUNT STREAMS-COMP-DESC COMP.CAPS-N ! ;

: STREAMS-ENTRY  ( desc -- )
    _STREAMS-COMP-SETUP DUP APP-DESC-INIT
    STREAMS-COMP-DESC OVER APP.COMP-DESC !
    ['] STREAMS-INIT-CB OVER APP.INIT-XT !
    ['] STREAMS-EVENT-CB OVER APP.EVENT-XT !
    ['] STREAMS-TICK-CB OVER APP.TICK-XT !
    ['] STREAMS-PAINT-CB OVER APP.PAINT-XT !
    ['] STREAMS-SHUTDOWN-CB OVER APP.SHUTDOWN-XT !
    ['] _STM-ACTIVATE OVER APP.ACTIVATE-XT !
    ['] STREAMS-REQUEST-CLOSE-CB OVER APP.REQUEST-CLOSE-XT !
    S" tui/applets/streams/streams.uidl" ROT DUP >R APP.UIDL-FILE-U ! R@ APP.UIDL-FILE-A !
    0 R@ APP.WIDTH ! 0 R@ APP.HEIGHT !
    S" Streams" R@ APP.TITLE-U ! R> APP.TITLE-A ! ;

CREATE STREAMS-DESC APP-DESC ALLOT
: STREAMS-RUN  ( -- ) STREAMS-DESC STREAMS-ENTRY STREAMS-DESC ASHELL-RUN ;
