\ =====================================================================
\ syndication-decode.f - retained syndication result to OCHK candidates
\ =====================================================================
\ This owner-side adapter decodes one admitted configured-provider body as
\ RSS 2.0, Atom 1.0, or JSON Feed.  An AUTO source selects only the provider's
\ already-admitted explicit media kind; this layer never sniffs body bytes.
\ An explicit source format must match that admitted media kind exactly.  Its
\ sealed descriptor owns the typed model, codec scratch, shared projection,
\ and bounded candidate array.  Candidate strings therefore remain valid
\ after the provider body is wiped and through a synchronous OCHK-APPLY call.
\ They remain borrowed from the decoder and are invalidated by RESET, FREE, or
\ the next successful DECODE.
\ DECODE is an owner-context operation and, like the underlying codecs, is
\ non-reentrant; callers serialize decoder use on the owning applet thread.
\
\ OCHK's fixed candidate ABI has no author slot.  AUTHOR$ exposes the exact
\ first applicable author name in a parallel borrowed view: entry/item first,
\ then the format's feed author where that format defines inheritance.  RSS
\ has no feed-author fallback.  An author object without a name is represented
\ by an empty name rather than a synthesized URL or address.
\
\ Public ABI:
\   STREAMS-SYNDICATION-DECODER-NEW       ( -- decoder status )
\   STREAMS-SYNDICATION-DECODER-FREE      ( decoder -- status )
\   STREAMS-SYNDICATION-DECODER-VALID?    ( decoder -- flag )
\   STREAMS-SYNDICATION-DECODER-RESET     ( decoder -- status )
\   STREAMS-SYNDICATION-DECODE
\     ( source-format provider decoder -- status )
\   STREAMS-SYNDICATION-RESULT-VALID?     ( decoder -- flag )
\   STREAMS-SYNDICATION-FORMAT@           ( decoder -- source-format | 0 )
\   STREAMS-SYNDICATION-CODEC-STATUS@     ( decoder -- codec-status )
\   STREAMS-SYNDICATION-CANDIDATES        ( decoder -- candidates count )
\   STREAMS-SYNDICATION-CANDIDATE         ( index decoder -- candidate | 0 )
\   STREAMS-SYNDICATION-AUTHOR$           ( index decoder -- a u )
\
\ Codec failures return the exact SYN-S-* value.  A failed codec attempt is
\ transactional and leaves the preceding successful result available; a
\ caller must nevertheless apply only after a fresh SYNDEC-S-OK return.
\ =====================================================================

\ Keep the module identity within KDOS's 23-byte bound.
PROVIDED akashic-streams-syndec

REQUIRE configured-provider.f
REQUIRE source-registry.f
REQUIRE observation-state.f
REQUIRE ../../../syndication/json-feed.f
REQUIRE ../../../syndication/rss.f
REQUIRE ../../../syndication/atom.f

\ The first six values deliberately preserve the exact codec status ABI.
SYN-S-OK          CONSTANT SYNDEC-S-OK
SYN-S-INVALID     CONSTANT SYNDEC-S-INVALID
SYN-S-CAPACITY    CONSTANT SYNDEC-S-CAPACITY
SYN-S-MISSING     CONSTANT SYNDEC-S-MISSING
SYN-S-TYPE        CONSTANT SYNDEC-S-TYPE
SYN-S-UNSUPPORTED CONSTANT SYNDEC-S-UNSUPPORTED
6 CONSTANT SYNDEC-S-RESULT
7 CONSTANT SYNDEC-S-FORMAT
8 CONSTANT SYNDEC-S-MEDIA

OCHK-BATCH-MAX CONSTANT STREAMS-SYNDICATION-CANDIDATE-MAX

SYN-FEED-SIZE RSS-FEED-SIZE MAX ATOM-FEED-SIZE MAX
    CONSTANT _SYNDEC-MODEL-SIZE
OCHK-CANDIDATE-SIZE STREAMS-SYNDICATION-CANDIDATE-MAX *
    CONSTANT _SYNDEC-CANDIDATES-SIZE

0 CONSTANT _SYNDEC-AUTHOR-A
8 CONSTANT _SYNDEC-AUTHOR-U
16 CONSTANT _SYNDEC-AUTHOR-SIZE
_SYNDEC-AUTHOR-SIZE STREAMS-SYNDICATION-CANDIDATE-MAX *
    CONSTANT _SYNDEC-AUTHORS-SIZE

0 CONSTANT _SYNDEC-STATE-EMPTY
1 CONSTANT _SYNDEC-STATE-DECODED

0x534E444543563031 CONSTANT _SYNDEC-MAGIC  \ "SNDECV01"
1 CONSTANT _SYNDEC-ABI

 0 CONSTANT _SDD-MAGIC
 8 CONSTANT _SDD-ABI
16 CONSTANT _SDD-STATE
24 CONSTANT _SDD-FORMAT
32 CONSTANT _SDD-COUNT
40 CONSTANT _SDD-CODEC-STATUS
48 CONSTANT _SDD-MODEL
56 CONSTANT _SDD-SCRATCH
64 CONSTANT _SDD-CANDIDATES
72 CONSTANT _SDD-AUTHORS
80 CONSTANT _SDD-PROJECTION
88 CONSTANT _SYNDEC-DESCRIPTOR-SIZE

: _SYNDEC.D.MAGIC         ( decoder -- a ) _SDD-MAGIC + ;
: _SYNDEC.D.ABI           ( decoder -- a ) _SDD-ABI + ;
: _SYNDEC.D.STATE         ( decoder -- a ) _SDD-STATE + ;
: _SYNDEC.D.FORMAT        ( decoder -- a ) _SDD-FORMAT + ;
: _SYNDEC.D.COUNT         ( decoder -- a ) _SDD-COUNT + ;
: _SYNDEC.D.CODEC-STATUS  ( decoder -- a ) _SDD-CODEC-STATUS + ;
: _SYNDEC.D.MODEL         ( decoder -- a ) _SDD-MODEL + ;
: _SYNDEC.D.SCRATCH       ( decoder -- a ) _SDD-SCRATCH + ;
: _SYNDEC.D.CANDIDATES    ( decoder -- a ) _SDD-CANDIDATES + ;
: _SYNDEC.D.AUTHORS       ( decoder -- a ) _SDD-AUTHORS + ;
: _SYNDEC.D.PROJECTION    ( decoder -- a ) _SDD-PROJECTION + ;

: _SYNDEC-EXPLICIT-FORMAT?  ( source-format -- flag )
    DUP SSOURCE-FORMAT-RSS =
    OVER SSOURCE-FORMAT-ATOM = OR
    SWAP SSOURCE-FORMAT-JSON-FEED = OR ;

: _SYNDEC-FORMAT>SYN  ( source-format -- syndication-format | 0 )
    CASE
        SSOURCE-FORMAT-RSS OF SYN-FORMAT-RSS-2 ENDOF
        SSOURCE-FORMAT-ATOM OF SYN-FORMAT-ATOM-1 ENDOF
        SSOURCE-FORMAT-JSON-FEED OF SYN-FORMAT-JSON-FEED ENDOF
        0 SWAP
    ENDCASE ;

: STREAMS-SYNDICATION-DECODER-VALID?  ( decoder -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP _SYNDEC.D.MAGIC @ _SYNDEC-MAGIC <> IF DROP 0 EXIT THEN
    DUP _SYNDEC.D.ABI @ _SYNDEC-ABI <> IF DROP 0 EXIT THEN
    DUP _SYNDEC.D.MODEL @ 0= IF DROP 0 EXIT THEN
    DUP _SYNDEC.D.SCRATCH @ 0= IF DROP 0 EXIT THEN
    DUP _SYNDEC.D.CANDIDATES @ 0= IF DROP 0 EXIT THEN
    DUP _SYNDEC.D.AUTHORS @ 0= IF DROP 0 EXIT THEN
    DUP _SYNDEC.D.PROJECTION @ 0= IF DROP 0 EXIT THEN
    DUP _SYNDEC.D.STATE @ _SYNDEC-STATE-EMPTY = IF
        DUP _SYNDEC.D.FORMAT @ 0=
        SWAP _SYNDEC.D.COUNT @ 0= AND EXIT
    THEN
    DUP _SYNDEC.D.STATE @ _SYNDEC-STATE-DECODED <> IF DROP 0 EXIT THEN
    DUP _SYNDEC.D.FORMAT @ _SYNDEC-EXPLICIT-FORMAT? 0= IF
        DROP 0 EXIT
    THEN
    _SYNDEC.D.COUNT @ DUP 0< 0=
    SWAP STREAMS-SYNDICATION-CANDIDATE-MAX <= AND ;

: STREAMS-SYNDICATION-RESULT-VALID?  ( decoder -- flag )
    DUP STREAMS-SYNDICATION-DECODER-VALID? 0= IF DROP 0 EXIT THEN
    _SYNDEC.D.STATE @ _SYNDEC-STATE-DECODED = ;

: STREAMS-SYNDICATION-FORMAT@  ( decoder -- source-format | 0 )
    DUP STREAMS-SYNDICATION-RESULT-VALID? 0= IF DROP 0 EXIT THEN
    _SYNDEC.D.FORMAT @ ;

: STREAMS-SYNDICATION-CODEC-STATUS@  ( decoder -- codec-status )
    DUP STREAMS-SYNDICATION-DECODER-VALID? 0= IF
        DROP SYN-S-INVALID EXIT
    THEN
    _SYNDEC.D.CODEC-STATUS @ ;

: _SYNDEC-RESULT-INVALIDATE  ( decoder -- )
    DUP _SYNDEC.D.MODEL @ _SYNDEC-MODEL-SIZE 0 FILL
    DUP _SYNDEC.D.CANDIDATES @ _SYNDEC-CANDIDATES-SIZE 0 FILL
    DUP _SYNDEC.D.AUTHORS @ _SYNDEC-AUTHORS-SIZE 0 FILL
    DUP _SYNDEC.D.PROJECTION @ SYN-PROJECTION-SIZE 0 FILL
    0 OVER _SYNDEC.D.FORMAT !
    0 OVER _SYNDEC.D.COUNT !
    _SYNDEC-STATE-EMPTY SWAP _SYNDEC.D.STATE ! ;

: _SYNDEC-ALL-WIPE  ( decoder -- )
    DUP _SYNDEC-RESULT-INVALIDATE
    DUP _SYNDEC.D.SCRATCH @ _SYNDEC-MODEL-SIZE 0 FILL
    SYN-S-OK SWAP _SYNDEC.D.CODEC-STATUS ! ;

: STREAMS-SYNDICATION-DECODER-RESET  ( decoder -- status )
    DUP STREAMS-SYNDICATION-DECODER-VALID? 0= IF
        DROP SYNDEC-S-INVALID EXIT
    THEN
    _SYNDEC-ALL-WIPE SYNDEC-S-OK ;

VARIABLE _SYNDEC-NEW-D

: _SYNDEC-ALLOC  ( size -- address | 0 )
    ALLOCATE DUP IF 2DROP 0 ELSE DROP THEN ;

: _SYNDEC-PARTIAL-FREE  ( -- )
    _SYNDEC-NEW-D @ ?DUP 0= IF EXIT THEN
    DUP _SYNDEC.D.PROJECTION @ ?DUP IF
        DUP SYN-PROJECTION-SIZE 0 FILL FREE
    THEN
    DUP _SYNDEC.D.AUTHORS @ ?DUP IF
        DUP _SYNDEC-AUTHORS-SIZE 0 FILL FREE
    THEN
    DUP _SYNDEC.D.CANDIDATES @ ?DUP IF
        DUP _SYNDEC-CANDIDATES-SIZE 0 FILL FREE
    THEN
    DUP _SYNDEC.D.SCRATCH @ ?DUP IF
        DUP _SYNDEC-MODEL-SIZE 0 FILL FREE
    THEN
    DUP _SYNDEC.D.MODEL @ ?DUP IF
        DUP _SYNDEC-MODEL-SIZE 0 FILL FREE
    THEN
    DUP _SYNDEC-DESCRIPTOR-SIZE 0 FILL FREE
    0 _SYNDEC-NEW-D ! ;

: STREAMS-SYNDICATION-DECODER-NEW  ( -- decoder status )
    0 _SYNDEC-NEW-D !
    _SYNDEC-DESCRIPTOR-SIZE _SYNDEC-ALLOC DUP 0= IF
        SYNDEC-S-CAPACITY EXIT
    THEN
    DUP _SYNDEC-NEW-D ! _SYNDEC-DESCRIPTOR-SIZE 0 FILL

    _SYNDEC-MODEL-SIZE _SYNDEC-ALLOC DUP 0= IF
        _SYNDEC-PARTIAL-FREE SYNDEC-S-CAPACITY EXIT
    THEN
    DUP _SYNDEC-MODEL-SIZE 0 FILL _SYNDEC-NEW-D @ _SYNDEC.D.MODEL !
    _SYNDEC-MODEL-SIZE _SYNDEC-ALLOC DUP 0= IF
        _SYNDEC-PARTIAL-FREE SYNDEC-S-CAPACITY EXIT
    THEN
    DUP _SYNDEC-MODEL-SIZE 0 FILL _SYNDEC-NEW-D @ _SYNDEC.D.SCRATCH !
    _SYNDEC-CANDIDATES-SIZE _SYNDEC-ALLOC DUP 0= IF
        _SYNDEC-PARTIAL-FREE SYNDEC-S-CAPACITY EXIT
    THEN
    DUP _SYNDEC-CANDIDATES-SIZE 0 FILL
        _SYNDEC-NEW-D @ _SYNDEC.D.CANDIDATES !
    _SYNDEC-AUTHORS-SIZE _SYNDEC-ALLOC DUP 0= IF
        _SYNDEC-PARTIAL-FREE SYNDEC-S-CAPACITY EXIT
    THEN
    DUP _SYNDEC-AUTHORS-SIZE 0 FILL _SYNDEC-NEW-D @ _SYNDEC.D.AUTHORS !
    SYN-PROJECTION-SIZE _SYNDEC-ALLOC DUP 0= IF
        _SYNDEC-PARTIAL-FREE SYNDEC-S-CAPACITY EXIT
    THEN
    DUP SYN-PROJECTION-SIZE 0 FILL
        _SYNDEC-NEW-D @ _SYNDEC.D.PROJECTION !

    _SYNDEC-ABI _SYNDEC-NEW-D @ _SYNDEC.D.ABI !
    _SYNDEC-STATE-EMPTY _SYNDEC-NEW-D @ _SYNDEC.D.STATE !
    SYN-S-OK _SYNDEC-NEW-D @ _SYNDEC.D.CODEC-STATUS !
    _SYNDEC-MAGIC _SYNDEC-NEW-D @ _SYNDEC.D.MAGIC !
    _SYNDEC-NEW-D @ STREAMS-SYNDICATION-DECODER-VALID? 0= IF
        _SYNDEC-PARTIAL-FREE 0 SYNDEC-S-INVALID EXIT
    THEN
    _SYNDEC-NEW-D @ SYNDEC-S-OK ;

VARIABLE _SYNDEC-FREE-D

: STREAMS-SYNDICATION-DECODER-FREE  ( decoder -- status )
    DUP STREAMS-SYNDICATION-DECODER-VALID? 0= IF
        DROP SYNDEC-S-INVALID EXIT
    THEN
    DUP _SYNDEC-FREE-D ! _SYNDEC-ALL-WIPE
    _SYNDEC-FREE-D @ _SYNDEC.D.PROJECTION @
        DUP SYN-PROJECTION-SIZE 0 FILL FREE
    _SYNDEC-FREE-D @ _SYNDEC.D.AUTHORS @
        DUP _SYNDEC-AUTHORS-SIZE 0 FILL FREE
    _SYNDEC-FREE-D @ _SYNDEC.D.CANDIDATES @
        DUP _SYNDEC-CANDIDATES-SIZE 0 FILL FREE
    _SYNDEC-FREE-D @ _SYNDEC.D.SCRATCH @
        DUP _SYNDEC-MODEL-SIZE 0 FILL FREE
    _SYNDEC-FREE-D @ _SYNDEC.D.MODEL @
        DUP _SYNDEC-MODEL-SIZE 0 FILL FREE
    _SYNDEC-FREE-D @ DUP _SYNDEC-DESCRIPTOR-SIZE 0 FILL FREE
    SYNDEC-S-OK ;

: _SYNDEC-CANDIDATE@  ( index decoder -- candidate )
    _SYNDEC.D.CANDIDATES @ SWAP OCHK-CANDIDATE-SIZE * + ;

: _SYNDEC-AUTHOR@  ( index decoder -- author-view )
    _SYNDEC.D.AUTHORS @ SWAP _SYNDEC-AUTHOR-SIZE * + ;

: STREAMS-SYNDICATION-CANDIDATES  ( decoder -- candidates count )
    DUP STREAMS-SYNDICATION-RESULT-VALID? 0= IF DROP 0 0 EXIT THEN
    DUP _SYNDEC.D.CANDIDATES @ SWAP _SYNDEC.D.COUNT @ ;

: STREAMS-SYNDICATION-CANDIDATE  ( index decoder -- candidate | 0 )
    >R
    R@ STREAMS-SYNDICATION-RESULT-VALID? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP 0< OVER R@ _SYNDEC.D.COUNT @ >= OR IF
        DROP R> DROP 0 EXIT
    THEN
    R> _SYNDEC-CANDIDATE@ ;

: STREAMS-SYNDICATION-AUTHOR$  ( index decoder -- a u )
    >R
    R@ STREAMS-SYNDICATION-RESULT-VALID? 0= IF
        DROP R> DROP 0 0 EXIT
    THEN
    DUP 0< OVER R@ _SYNDEC.D.COUNT @ >= OR IF
        DROP R> DROP 0 0 EXIT
    THEN
    R> _SYNDEC-AUTHOR@ DUP _SYNDEC-AUTHOR-A + @
    SWAP _SYNDEC-AUTHOR-U + @ ;

VARIABLE _SYNDEC-EXPECTED
VARIABLE _SYNDEC-MEDIA
VARIABLE _SYNDEC-PROVIDER
VARIABLE _SYNDEC-DECODER
VARIABLE _SYNDEC-BODY-A
VARIABLE _SYNDEC-BODY-U
VARIABLE _SYNDEC-STATUS
VARIABLE _SYNDEC-COUNT
VARIABLE _SYNDEC-I
VARIABLE _SYNDEC-ITEM
VARIABLE _SYNDEC-CANDIDATE
VARIABLE _SYNDEC-AUTHOR-VIEW

: _SYNDEC-DECODE-BODY  ( -- codec-status )
    _SYNDEC-EXPECTED @ CASE
        SSOURCE-FORMAT-RSS OF
            _SYNDEC-BODY-A @ _SYNDEC-BODY-U @
            _SYNDEC-DECODER @ _SYNDEC.D.MODEL @
            _SYNDEC-DECODER @ _SYNDEC.D.SCRATCH @
            RSS-FEED-SCRATCH-SIZE RSS-FEED-DECODE
        ENDOF
        SSOURCE-FORMAT-ATOM OF
            _SYNDEC-BODY-A @ _SYNDEC-BODY-U @
            _SYNDEC-DECODER @ _SYNDEC.D.MODEL @
            _SYNDEC-DECODER @ _SYNDEC.D.SCRATCH @
            ATOM-FEED-SCRATCH-SIZE ATOM-FEED-DECODE
        ENDOF
        SSOURCE-FORMAT-JSON-FEED OF
            _SYNDEC-BODY-A @ _SYNDEC-BODY-U @
            _SYNDEC-DECODER @ _SYNDEC.D.MODEL @
            _SYNDEC-DECODER @ _SYNDEC.D.SCRATCH @
            JSON-FEED-SCRATCH-SIZE JSON-FEED-DECODE
        ENDOF
        SYN-S-UNSUPPORTED SWAP
    ENDCASE ;

: _SYNDEC-MODEL-COUNT  ( -- count )
    _SYNDEC-EXPECTED @ CASE
        SSOURCE-FORMAT-RSS OF
            _SYNDEC-DECODER @ _SYNDEC.D.MODEL @ RSS.FEED.COUNT @
        ENDOF
        SSOURCE-FORMAT-ATOM OF
            _SYNDEC-DECODER @ _SYNDEC.D.MODEL @ ATOM.FEED.COUNT @
        ENDOF
        SSOURCE-FORMAT-JSON-FEED OF
            _SYNDEC-DECODER @ _SYNDEC.D.MODEL @ SYN.FEED.COUNT @
        ENDOF
        0 SWAP
    ENDCASE ;

: _SYNDEC-MODEL-ITEM  ( index -- item | 0 )
    _SYNDEC-EXPECTED @ CASE
        SSOURCE-FORMAT-RSS OF
            _SYNDEC-DECODER @ _SYNDEC.D.MODEL @ RSS.FEED.ITEM
        ENDOF
        SSOURCE-FORMAT-ATOM OF
            _SYNDEC-DECODER @ _SYNDEC.D.MODEL @ ATOM.FEED.ENTRY
        ENDOF
        SSOURCE-FORMAT-JSON-FEED OF
            _SYNDEC-DECODER @ _SYNDEC.D.MODEL @ SYN.FEED.ENTRY
        ENDOF
        DROP 0 SWAP
    ENDCASE ;

: _SYNDEC-PROJECT-ITEM  ( item -- status )
    _SYNDEC-ITEM !
    _SYNDEC-EXPECTED @ CASE
        SSOURCE-FORMAT-RSS OF
            _SYNDEC-ITEM @ _SYNDEC-DECODER @ _SYNDEC.D.PROJECTION @
                RSS-FEED-PROJECT-ITEM
        ENDOF
        SSOURCE-FORMAT-ATOM OF
            _SYNDEC-ITEM @ _SYNDEC-DECODER @ _SYNDEC.D.PROJECTION @
                ATOM-FEED-PROJECT-ITEM
        ENDOF
        SSOURCE-FORMAT-JSON-FEED OF
            _SYNDEC-ITEM @ _SYNDEC-DECODER @ _SYNDEC.D.PROJECTION @
                JSON-FEED-PROJECT-ITEM
        ENDOF
        SYN-S-UNSUPPORTED SWAP
    ENDCASE ;

: _SYNDEC-PAIR!  ( a u address-cell length-cell -- )
    >R ROT SWAP ! R> ! ;

: _SYNDEC-PROJECTION>CANDIDATE  ( -- )
    _SYNDEC-CANDIDATE @ OCHK-CANDIDATE-INIT
    _SYNDEC-DECODER @ _SYNDEC.D.PROJECTION @ DUP
        SYN.PROJECTION.FORMAT _SYNDEC-CANDIDATE @ OCC.FORMAT !
    OCHK-NATIVE-PROVIDER-ID _SYNDEC-CANDIDATE @ OCC.NATIVE-KIND !
    DUP SYN.PROJECTION.NATIVE-ID
        _SYNDEC-CANDIDATE @ OCC.NATIVE-A
        _SYNDEC-CANDIDATE @ OCC.NATIVE-U _SYNDEC-PAIR!
    DUP SYN.PROJECTION.TITLE
        _SYNDEC-CANDIDATE @ OCC.TITLE-A
        _SYNDEC-CANDIDATE @ OCC.TITLE-U _SYNDEC-PAIR!
    DUP SYN.PROJECTION.URL
        _SYNDEC-CANDIDATE @ OCC.URL-A
        _SYNDEC-CANDIDATE @ OCC.URL-U _SYNDEC-PAIR!
    DUP SYN.PROJECTION.SUMMARY
        _SYNDEC-CANDIDATE @ OCC.SUMMARY-A
        _SYNDEC-CANDIDATE @ OCC.SUMMARY-U _SYNDEC-PAIR!
    DUP SYN.PROJECTION.CONTENT
        _SYNDEC-CANDIDATE @ OCC.CONTENT-A
        _SYNDEC-CANDIDATE @ OCC.CONTENT-U _SYNDEC-PAIR!
    DUP SYN.PROJECTION.PUBLISHED
        _SYNDEC-CANDIDATE @ OCC.PUBLISHED-A
        _SYNDEC-CANDIDATE @ OCC.PUBLISHED-U _SYNDEC-PAIR!
    SYN.PROJECTION.MODIFIED
        _SYNDEC-CANDIDATE @ OCC.MODIFIED-A
        _SYNDEC-CANDIDATE @ OCC.MODIFIED-U _SYNDEC-PAIR! ;

: _SYNDEC-JSON-AUTHOR$  ( item -- a u )
    DUP SYN.ENTRY.AUTHOR-COUNT @ IF
        0 SWAP SYN.ENTRY.AUTHOR
    ELSE
        DROP 0 _SYNDEC-DECODER @ _SYNDEC.D.MODEL @ SYN.FEED.AUTHOR
    THEN
    ?DUP IF SYN.AUTHOR.NAME ELSE 0 0 THEN ;

: _SYNDEC-ATOM-AUTHOR$  ( entry -- a u )
    DUP ATOM.ENTRY.PERSON-COUNT @ IF
        0 SWAP ATOM.ENTRY.PERSON
    ELSE
        DROP 0 _SYNDEC-DECODER @ _SYNDEC.D.MODEL @ ATOM.FEED.PERSON
    THEN
    ?DUP IF ATOM.PERSON.NAME ELSE 0 0 THEN ;

: _SYNDEC-ITEM-AUTHOR$  ( item -- a u )
    _SYNDEC-EXPECTED @ CASE
        SSOURCE-FORMAT-RSS OF RSS.ITEM.AUTHOR ENDOF
        SSOURCE-FORMAT-ATOM OF _SYNDEC-ATOM-AUTHOR$ ENDOF
        SSOURCE-FORMAT-JSON-FEED OF _SYNDEC-JSON-AUTHOR$ ENDOF
        DROP 0 0 ROT
    ENDCASE ;

: _SYNDEC-BUILD-CANDIDATES  ( -- status )
    _SYNDEC-MODEL-COUNT DUP _SYNDEC-COUNT !
    DUP 0< SWAP STREAMS-SYNDICATION-CANDIDATE-MAX > OR IF
        SYNDEC-S-CAPACITY EXIT
    THEN
    _SYNDEC-DECODER @ _SYNDEC.D.CANDIDATES @
        _SYNDEC-CANDIDATES-SIZE 0 FILL
    _SYNDEC-DECODER @ _SYNDEC.D.AUTHORS @ _SYNDEC-AUTHORS-SIZE 0 FILL
    0 _SYNDEC-I !
    BEGIN _SYNDEC-I @ _SYNDEC-COUNT @ < WHILE
        _SYNDEC-I @ _SYNDEC-MODEL-ITEM DUP _SYNDEC-ITEM ! 0= IF
            SYNDEC-S-INVALID EXIT
        THEN
        _SYNDEC-ITEM @ _SYNDEC-PROJECT-ITEM ?DUP IF EXIT THEN
        _SYNDEC-DECODER @ _SYNDEC.D.PROJECTION @ SYN.PROJECTION.FORMAT
        _SYNDEC-EXPECTED @ _SYNDEC-FORMAT>SYN <> IF
            SYNDEC-S-FORMAT EXIT
        THEN
        _SYNDEC-I @ _SYNDEC-DECODER @ _SYNDEC-CANDIDATE@
            _SYNDEC-CANDIDATE !
        _SYNDEC-PROJECTION>CANDIDATE
        _SYNDEC-I @ _SYNDEC-DECODER @ _SYNDEC-AUTHOR@
            _SYNDEC-AUTHOR-VIEW !
        _SYNDEC-ITEM @ _SYNDEC-ITEM-AUTHOR$
            _SYNDEC-AUTHOR-VIEW @ _SYNDEC-AUTHOR-A +
            _SYNDEC-AUTHOR-VIEW @ _SYNDEC-AUTHOR-U + _SYNDEC-PAIR!
        1 _SYNDEC-I +!
    REPEAT
    _SYNDEC-COUNT @ _SYNDEC-DECODER @ _SYNDEC.D.COUNT !
    _SYNDEC-EXPECTED @ _SYNDEC-DECODER @ _SYNDEC.D.FORMAT !
    _SYNDEC-STATE-DECODED _SYNDEC-DECODER @ _SYNDEC.D.STATE !
    SYNDEC-S-OK ;

: STREAMS-SYNDICATION-DECODE
    ( source-format provider decoder -- status )
    _SYNDEC-DECODER ! _SYNDEC-PROVIDER ! _SYNDEC-EXPECTED !
    _SYNDEC-DECODER @ STREAMS-SYNDICATION-DECODER-VALID? 0= IF
        SYNDEC-S-INVALID EXIT
    THEN
    _SYNDEC-PROVIDER @ SCONF-VALID? 0= IF SYNDEC-S-INVALID EXIT THEN
    _SYNDEC-EXPECTED @ DUP SSOURCE-FORMAT-AUTO =
        SWAP _SYNDEC-EXPLICIT-FORMAT? OR 0= IF
        SYNDEC-S-FORMAT EXIT
    THEN
    _SYNDEC-PROVIDER @ SCONF-RESULT-VALID? 0= IF SYNDEC-S-RESULT EXIT THEN
    _SYNDEC-PROVIDER @ SCONF-MEDIA-KIND DUP _SYNDEC-MEDIA !
        _SYNDEC-EXPLICIT-FORMAT? 0= IF SYNDEC-S-MEDIA EXIT THEN
    _SYNDEC-EXPECTED @ SSOURCE-FORMAT-AUTO = IF
        _SYNDEC-MEDIA @ _SYNDEC-EXPECTED !
    ELSE
        _SYNDEC-MEDIA @ _SYNDEC-EXPECTED @ <> IF SYNDEC-S-MEDIA EXIT THEN
    THEN
    _SYNDEC-PROVIDER @ SCONF-BODY$
        _SYNDEC-BODY-U ! _SYNDEC-BODY-A !
    _SYNDEC-BODY-A @ _SYNDEC-BODY-U @ SYN-SPAN-VALID? 0= IF
        SYNDEC-S-INVALID EXIT
    THEN
    _SYNDEC-BODY-U @ 0= IF SYNDEC-S-INVALID EXIT THEN

    _SYNDEC-DECODE-BODY DUP _SYNDEC-STATUS !
        _SYNDEC-DECODER @ _SYNDEC.D.CODEC-STATUS !
    _SYNDEC-STATUS @ SYN-S-OK <> IF _SYNDEC-STATUS @ EXIT THEN
    _SYNDEC-BUILD-CANDIDATES DUP IF
        _SYNDEC-DECODER @ _SYNDEC-RESULT-INVALIDATE
    THEN ;
