\ =====================================================================
\  vfs-fixed-snapshot.f - Fixed-capacity checked VFS snapshots
\ =====================================================================
\  The core owns a 64-byte envelope around one exact fixed-size payload.
\  Callers own payload encoding/validation, domain status translation, and
\  an exclusive record-sized scratch span for the complete store lifetime.
\
\  Callback ABI:
\    encode   ( context payload-a payload-u next-generation -- status )
\    validate ( payload-a payload-u envelope-generation -- status )
\
\  The payload passed to encode is exactly PAYLOAD-U zero bytes.  Neither
\  callback can address the envelope through this ABI.  Recursive entry is
\  rejected before callback-visible scratch is touched.  Distinct stores
\  own disjoint scratch and state; actual replacement/VFS work retains the
\  existing process-wide VREPL/VFS serialization boundary.
\ =====================================================================

PROVIDED akashic-vfs-fixed-snapshot

REQUIRE vfs-replace.f
REQUIRE ../memory-span.f
REQUIRE ../../math/crc.f
REQUIRE ../../concurrency/guard.f

\ =====================================================================
\  Public statuses and envelope
\ =====================================================================

0 CONSTANT VFSNAP-S-OK
1 CONSTANT VFSNAP-S-ABSENT
2 CONSTANT VFSNAP-S-CORRUPT
3 CONSTANT VFSNAP-S-UNSUPPORTED
4 CONSTANT VFSNAP-S-INVALID
5 CONSTANT VFSNAP-S-CAPACITY
6 CONSTANT VFSNAP-S-IO
7 CONSTANT VFSNAP-S-RECOVERY
8 CONSTANT VFSNAP-S-BUSY
9 CONSTANT VFSNAP-S-CONFLICT

64 CONSTANT VFSNAP-HEADER-SIZE

 0 CONSTANT _VFSN-H-MAGIC
 8 CONSTANT _VFSN-H-FORMAT
16 CONSTANT _VFSN-H-HEADER-SIZE
24 CONSTANT _VFSN-H-GENERATION
32 CONSTANT _VFSN-H-PAYLOAD-SIZE
40 CONSTANT _VFSN-H-PAYLOAD-CRC
48 CONSTANT _VFSN-H-HEADER-CRC
56 CONSTANT _VFSN-H-FLAGS

\ =====================================================================
\  Specification descriptor
\ =====================================================================

16 CONSTANT VFSNAP-SPEC-PRIVATE-MAX
16 CONSTANT _VFSN-PRIVATE-RANGE-SIZE

0x5646534E53504531 CONSTANT _VFSNAP-SPEC-MAGIC  \ "VFSNSPE1"
1 CONSTANT _VFSNAP-SPEC-F-SEALED

  0 CONSTANT _VFSNS-MAGIC
  8 CONSTANT _VFSNS-FLAGS
 16 CONSTANT _VFSNS-RECORD-MAGIC
 24 CONSTANT _VFSNS-FORMAT
 32 CONSTANT _VFSNS-PAYLOAD-U
 40 CONSTANT _VFSNS-ENCODE-XT
 48 CONSTANT _VFSNS-VALIDATE-XT
 56 CONSTANT _VFSNS-PRIVATE-N
 64 CONSTANT _VFSNS-PRIVATE
_VFSNS-PRIVATE VFSNAP-SPEC-PRIVATE-MAX _VFSN-PRIVATE-RANGE-SIZE * +
    CONSTANT VFSNAP-SPEC-SIZE

: VFSNAP-SPEC.MAGIC        ( spec -- a ) _VFSNS-MAGIC + ;
: VFSNAP-SPEC.FLAGS        ( spec -- a ) _VFSNS-FLAGS + ;
: VFSNAP-SPEC.RECORD-MAGIC ( spec -- a ) _VFSNS-RECORD-MAGIC + ;
: VFSNAP-SPEC.FORMAT       ( spec -- a ) _VFSNS-FORMAT + ;
: VFSNAP-SPEC.PAYLOAD-U    ( spec -- a ) _VFSNS-PAYLOAD-U + ;
: VFSNAP-SPEC.ENCODE-XT    ( spec -- a ) _VFSNS-ENCODE-XT + ;
: VFSNAP-SPEC.VALIDATE-XT  ( spec -- a ) _VFSNS-VALIDATE-XT + ;
: VFSNAP-SPEC.PRIVATE-N    ( spec -- a ) _VFSNS-PRIVATE-N + ;
: VFSNAP-SPEC.PRIVATE      ( spec -- a ) _VFSNS-PRIVATE + ;

: _VFSNAP-SPEC-PRIVATE-NTH  ( index spec -- range )
    VFSNAP-SPEC.PRIVATE SWAP _VFSN-PRIVATE-RANGE-SIZE * + ;

\ =====================================================================
\  Store descriptor
\ =====================================================================
\  VREPL remains first so typed adapters can retain their historical
\  +40 .REPLACE accessor while appending this core and private scratch.

0x5646534E53544F31 CONSTANT _VFSNAP-STORE-MAGIC  \ "VFSNSTO1"
1 CONSTANT _VFSNAP-STORE-F-BLOCKED
2 CONSTANT _VFSNAP-STORE-F-ACTIVE

VREPL-SIZE       CONSTANT _VFSND-MAGIC
_VFSND-MAGIC 8 + CONSTANT _VFSND-FLAGS
_VFSND-FLAGS 8 + CONSTANT _VFSND-LAST-STATUS
_VFSND-LAST-STATUS 8 + CONSTANT _VFSND-LAST-VREPL
_VFSND-LAST-VREPL 8 + CONSTANT _VFSND-SPEC
_VFSND-SPEC 8 + CONSTANT _VFSND-SCRATCH-A
_VFSND-SCRATCH-A 8 + CONSTANT _VFSND-SCRATCH-U
_VFSND-SCRATCH-U 8 + CONSTANT _VFSND-VFS
_VFSND-VFS 8 + CONSTANT _VFSND-CLOSE-XT
_VFSND-CLOSE-XT 8 + CONSTANT _VFSND-RESTORE-XT
_VFSND-RESTORE-XT 8 + CONSTANT VFSNAP-STORE-SIZE

: VFSNAP.REPLACE     ( store -- replacement ) ;
: VFSNAP.MAGIC       ( store -- a ) _VFSND-MAGIC + ;
: VFSNAP.FLAGS       ( store -- a ) _VFSND-FLAGS + ;
: VFSNAP.LAST-STATUS ( store -- a ) _VFSND-LAST-STATUS + ;
: VFSNAP.LAST-VREPL  ( store -- a ) _VFSND-LAST-VREPL + ;
: VFSNAP.SPEC        ( store -- a ) _VFSND-SPEC + ;
: VFSNAP.SCRATCH-A   ( store -- a ) _VFSND-SCRATCH-A + ;
: VFSNAP.SCRATCH-U   ( store -- a ) _VFSND-SCRATCH-U + ;
: VFSNAP.VFS         ( store -- a ) _VFSND-VFS + ;
: VFSNAP.CLOSE-XT    ( store -- a ) _VFSND-CLOSE-XT + ;
: VFSNAP.RESTORE-XT  ( store -- a ) _VFSND-RESTORE-XT + ;

: VFSNAP-SCRATCH$  ( store -- a u )
    DUP VFSNAP.SCRATCH-A @ SWAP VFSNAP.SCRATCH-U @ ;

: VFSNAP-PAYLOAD$  ( store -- a u )
    DUP VFSNAP.SCRATCH-A @ VFSNAP-HEADER-SIZE +
    SWAP VFSNAP.SPEC @ VFSNAP-SPEC.PAYLOAD-U @ ;

: VFSNAP-PATH$  ( store -- a u ) VFSNAP.REPLACE VREPL-TARGET$ ;
: VFSNAP-BLOCKED?  ( store -- flag )
    VFSNAP.FLAGS @ _VFSNAP-STORE-F-BLOCKED AND 0<> ;
: VFSNAP-LAST-STATUS@  ( store -- status ) VFSNAP.LAST-STATUS @ ;
: VFSNAP-LAST-VREPL@   ( store -- status ) VFSNAP.LAST-VREPL @ ;

\ =====================================================================
\  Overflow-safe span and hostile-alias predicates
\ =====================================================================

: _VFSNAP-SPAN-VALID?  ( address length -- flag )
    DUP 0= IF 2DROP -1 EXIT THEN
    OVER 0= IF 2DROP 0 EXIT THEN
    MSPAN-NONWRAPPING? ;

: _VFSNAP-RANGES-OVERLAP?  ( a1 u1 a2 u2 -- flag )
    MSPAN-OVERLAP? ;

CREATE _VFSNAP-PRIVATE-BEGIN 0 ALLOT
VARIABLE _VFSNAP-PRIVATE-LIMIT
GUARD _vfsnap-guard
VARIABLE _vfsnap-operation-active

: _VFSNAP-DEPENDENCY-ALIASES?  ( address length -- flag )
    2DUP _VFSNAP-PRIVATE-BEGIN _VFSNAP-PRIVATE-LIMIT @
        _VFSNAP-PRIVATE-BEGIN - _VFSNAP-RANGES-OVERLAP? IF
        2DROP -1 EXIT
    THEN
    2DUP _vrepl-guard _VRCL-REPLACE-R 8 + _vrepl-guard -
        _VFSNAP-RANGES-OVERLAP? IF 2DROP -1 EXIT THEN
    2DUP _VFS-CUR
    [DEFINED] _vfs-guard [IF]
        _vfs-guard _GRD-SIZE-SPIN +
    [ELSE]
        _VIP-POS 8 +
    [THEN]
    _VFS-CUR - _VFSNAP-RANGES-OVERLAP? IF 2DROP -1 EXIT THEN
    2DUP _CRC-HDST
    [DEFINED] _crc-guard [IF]
        _CRC-BEGIN-MODE 8 +
    [ELSE]
        _CRC-HDST 8 +
    [THEN]
    _CRC-HDST - _VFSNAP-RANGES-OVERLAP? IF 2DROP -1 EXIT THEN
    2DUP _SHA3-IPAD
    [DEFINED] _sha3-guard [IF]
        _sha3-guard _GRD-SIZE-SPIN +
    [ELSE]
        _SHA3-HDST 8 +
    [THEN]
    _SHA3-IPAD - _VFSNAP-RANGES-OVERLAP? IF 2DROP -1 EXIT THEN
    2DROP 0 ;

: _VFSNAP-SPEC-SPAN-SAFE?  ( spec -- flag )
    DUP VFSNAP-SPEC-SIZE _VFSNAP-SPAN-VALID? 0= IF DROP 0 EXIT THEN
    DUP VFSNAP-SPEC-SIZE _VFSNAP-DEPENDENCY-ALIASES? 0= NIP ;

: VFSNAP-SPEC-VALID?  ( spec -- flag )
    DUP _VFSNAP-SPEC-SPAN-SAFE? 0= IF DROP 0 EXIT THEN
    DUP VFSNAP-SPEC.MAGIC @ _VFSNAP-SPEC-MAGIC =
    OVER VFSNAP-SPEC.PAYLOAD-U @ DUP 0> SWAP VFSNAP-HEADER-SIZE +
        VFSNAP-HEADER-SIZE U> AND AND
    OVER VFSNAP-SPEC.ENCODE-XT @ 0<> AND
    OVER VFSNAP-SPEC.VALIDATE-XT @ 0<> AND
    OVER VFSNAP-SPEC.PRIVATE-N @ DUP 0>=
        SWAP VFSNAP-SPEC-PRIVATE-MAX <= AND AND
    SWAP DROP ;

: VFSNAP-SPEC-SEALED?  ( spec -- flag )
    DUP VFSNAP-SPEC-VALID? 0= IF DROP 0 EXIT THEN
    VFSNAP-SPEC.FLAGS @ _VFSNAP-SPEC-F-SEALED AND 0<> ;

: _VFSNAP-SPEC-PRIVATE-ALIASES?  ( address length spec -- flag )
    DUP VFSNAP-SPEC.PRIVATE-N @ 0 ?DO
        2 PICK 2 PICK I 3 PICK _VFSNAP-SPEC-PRIVATE-NTH
        DUP @ SWAP 8 + @ _VFSNAP-RANGES-OVERLAP? IF
            2DROP DROP -1 UNLOOP EXIT
        THEN
    LOOP
    2DROP DROP 0 ;

: _VFSNAP-ALL-PRIVATE-ALIASES?  ( address length spec -- flag )
    >R 2DUP _VFSNAP-DEPENDENCY-ALIASES? >R
    R> IF 2DROP R> DROP -1 EXIT THEN
    R> _VFSNAP-SPEC-PRIVATE-ALIASES? ;

: _VFSNAP-STORE-SPAN-SAFE?  ( store -- flag )
    DUP VFSNAP-STORE-SIZE _VFSNAP-SPAN-VALID? 0= IF DROP 0 EXIT THEN
    DUP VFSNAP-STORE-SIZE _VFSNAP-DEPENDENCY-ALIASES? 0= NIP ;

: VFSNAP-VALID?  ( store -- flag )
    DUP _VFSNAP-STORE-SPAN-SAFE? 0= IF DROP 0 EXIT THEN
    DUP VFSNAP.MAGIC @ _VFSNAP-STORE-MAGIC <> IF DROP 0 EXIT THEN
    DUP VFSNAP.VFS @ 0= IF DROP 0 EXIT THEN
    DUP VFSNAP.CLOSE-XT @ 0= IF DROP 0 EXIT THEN
    DUP VFSNAP.RESTORE-XT @ 0= IF DROP 0 EXIT THEN
    DUP VFSNAP.SPEC @ VFSNAP-SPEC-SEALED? 0= IF DROP 0 EXIT THEN
    DUP VFSNAP.REPLACE VREPL-CONFIGURED? 0= IF DROP 0 EXIT THEN
    DUP VFSNAP.VFS @ OVER VFSNAP.REPLACE VREPL.VFS @ <> IF
        DROP 0 EXIT
    THEN
    DUP VFSNAP.SCRATCH-A @ OVER VFSNAP.SCRATCH-U @
        _VFSNAP-SPAN-VALID? 0= IF DROP 0 EXIT THEN
    DUP VFSNAP.SCRATCH-U @ OVER VFSNAP.SPEC @
        VFSNAP-SPEC.PAYLOAD-U @ VFSNAP-HEADER-SIZE + <> IF
        DROP 0 EXIT
    THEN
    DUP VFSNAP.SCRATCH-A @ OVER VFSNAP.SCRATCH-U @
        2 PICK VFSNAP-STORE-SIZE _VFSNAP-RANGES-OVERLAP? IF
        DROP 0 EXIT
    THEN
    DUP VFSNAP.SCRATCH-A @ OVER VFSNAP.SCRATCH-U @
        2 PICK VFSNAP.SPEC @ _VFSNAP-ALL-PRIVATE-ALIASES? IF
        DROP 0 EXIT
    THEN
    DUP VFSNAP.SPEC @ VFSNAP-SPEC-SIZE
        2 PICK VFSNAP-STORE-SIZE _VFSNAP-RANGES-OVERLAP? IF
        DROP 0 EXIT
    THEN
    DUP VFSNAP.SPEC @ VFSNAP-SPEC-SIZE
        2 PICK VFSNAP.SCRATCH-A @ 3 PICK VFSNAP.SCRATCH-U @
        _VFSNAP-RANGES-OVERLAP? IF DROP 0 EXIT THEN
    DROP -1 ;

\ =====================================================================
\  Specification lifecycle
\ =====================================================================

VARIABLE _VSPI-MAGIC-A
VARIABLE _VSPI-MAGIC-U
VARIABLE _VSPI-FORMAT
VARIABLE _VSPI-PAYLOAD-U
VARIABLE _VSPI-ENCODE-XT
VARIABLE _VSPI-VALIDATE-XT
VARIABLE _VSPI-SPEC

: _VFSNAP-SPEC-INIT
  ( magic-a magic-u format payload-u encode-xt validate-xt spec -- status )
    _VSPI-SPEC ! _VSPI-VALIDATE-XT ! _VSPI-ENCODE-XT !
    _VSPI-PAYLOAD-U ! _VSPI-FORMAT ! _VSPI-MAGIC-U ! _VSPI-MAGIC-A !
    _VSPI-SPEC @ VFSNAP-SPEC-SIZE 0 FILL
    _VFSNAP-SPEC-MAGIC _VSPI-SPEC @ VFSNAP-SPEC.MAGIC !
    _VSPI-MAGIC-A @ _VSPI-SPEC @ VFSNAP-SPEC.RECORD-MAGIC 8 CMOVE
    _VSPI-FORMAT @ _VSPI-SPEC @ VFSNAP-SPEC.FORMAT !
    _VSPI-PAYLOAD-U @ _VSPI-SPEC @ VFSNAP-SPEC.PAYLOAD-U !
    _VSPI-ENCODE-XT @ _VSPI-SPEC @ VFSNAP-SPEC.ENCODE-XT !
    _VSPI-VALIDATE-XT @ _VSPI-SPEC @ VFSNAP-SPEC.VALIDATE-XT !
    VFSNAP-S-OK ;

' _VFSNAP-SPEC-INIT CONSTANT _vfsnap-spec-init-xt

: VFSNAP-SPEC-INIT
  ( magic-a magic-u format payload-u encode-xt validate-xt spec -- status )
    DUP _VFSNAP-SPEC-SPAN-SAFE? 0= IF
        6 0 DO DROP LOOP VFSNAP-S-INVALID EXIT
    THEN
    6 PICK 6 PICK _VFSNAP-SPAN-VALID? 0= IF
        7 0 DO DROP LOOP VFSNAP-S-INVALID EXIT
    THEN
    5 PICK 8 <> IF 7 0 DO DROP LOOP VFSNAP-S-INVALID EXIT THEN
    6 PICK 8 2 PICK VFSNAP-SPEC-SIZE _VFSNAP-RANGES-OVERLAP? IF
        7 0 DO DROP LOOP VFSNAP-S-INVALID EXIT
    THEN
    3 PICK DUP 0> SWAP VFSNAP-HEADER-SIZE + VFSNAP-HEADER-SIZE U> AND 0= IF
        7 0 DO DROP LOOP VFSNAP-S-INVALID EXIT
    THEN
    2 PICK 0= 2 PICK 0= OR IF
        7 0 DO DROP LOOP VFSNAP-S-INVALID EXIT
    THEN
    _vfsnap-operation-active @ IF
        7 0 DO DROP LOOP VFSNAP-S-BUSY EXIT
    THEN
    _vfsnap-spec-init-xt _vfsnap-guard WITH-GUARD ;

VARIABLE _VSPA-A
VARIABLE _VSPA-U
VARIABLE _VSPA-SPEC
VARIABLE _VSPA-RANGE

: _VFSNAP-SPEC-PRIVATE-ADD  ( private-a private-u spec -- status )
    _VSPA-SPEC ! _VSPA-U ! _VSPA-A !
    _VSPA-SPEC @ VFSNAP-SPEC-VALID? 0= IF VFSNAP-S-INVALID EXIT THEN
    _VSPA-SPEC @ VFSNAP-SPEC.FLAGS @ _VFSNAP-SPEC-F-SEALED AND IF
        VFSNAP-S-BUSY EXIT
    THEN
    _VSPA-SPEC @ VFSNAP-SPEC.PRIVATE-N @
        VFSNAP-SPEC-PRIVATE-MAX >= IF VFSNAP-S-CAPACITY EXIT THEN
    _VSPA-A @ _VSPA-U @ _VFSNAP-SPAN-VALID? 0= IF VFSNAP-S-INVALID EXIT THEN
    _VSPA-A @ _VSPA-U @ _VSPA-SPEC @ VFSNAP-SPEC-SIZE
        _VFSNAP-RANGES-OVERLAP? IF VFSNAP-S-INVALID EXIT THEN
    _VSPA-A @ _VSPA-U @ _VFSNAP-DEPENDENCY-ALIASES? IF
        VFSNAP-S-INVALID EXIT
    THEN
    _VSPA-A @ _VSPA-U @ _VSPA-SPEC @
        _VFSNAP-SPEC-PRIVATE-ALIASES? IF VFSNAP-S-INVALID EXIT THEN
    _VSPA-SPEC @ VFSNAP-SPEC.PRIVATE-N @ _VSPA-SPEC @
        _VFSNAP-SPEC-PRIVATE-NTH _VSPA-RANGE !
    _VSPA-A @ _VSPA-RANGE @ !
    _VSPA-U @ _VSPA-RANGE @ 8 + !
    1 _VSPA-SPEC @ VFSNAP-SPEC.PRIVATE-N +!
    VFSNAP-S-OK ;

' _VFSNAP-SPEC-PRIVATE-ADD CONSTANT _vfsnap-spec-private-add-xt

: _VFSNAP-SPEC-PRIVATE-ADD-SAFE?  ( private-a private-u spec -- flag )
    DUP _VFSNAP-SPEC-SPAN-SAFE? 0= IF 2DROP DROP 0 EXIT THEN
    2 PICK 2 PICK _VFSNAP-SPAN-VALID? 0= IF 2DROP DROP 0 EXIT THEN
    2 PICK 2 PICK 2 PICK VFSNAP-SPEC-SIZE
        _VFSNAP-RANGES-OVERLAP? IF 2DROP DROP 0 EXIT THEN
    2 PICK 2 PICK _VFSNAP-DEPENDENCY-ALIASES? IF
        2DROP DROP 0 EXIT
    THEN
    2 PICK 2 PICK 2 PICK _VFSNAP-SPEC-PRIVATE-ALIASES? IF
        2DROP DROP 0 EXIT
    THEN
    2DROP DROP -1 ;

: VFSNAP-SPEC-PRIVATE-ADD  ( private-a private-u spec -- status )
    2 PICK 2 PICK 2 PICK _VFSNAP-SPEC-PRIVATE-ADD-SAFE? 0= IF
        2DROP DROP VFSNAP-S-INVALID EXIT
    THEN
    _vfsnap-operation-active @ IF
        2DROP DROP VFSNAP-S-BUSY EXIT
    THEN
    _vfsnap-spec-private-add-xt _vfsnap-guard WITH-GUARD ;

: _VFSNAP-SPEC-SEAL  ( spec -- status )
    DUP VFSNAP-SPEC-VALID? 0= IF DROP VFSNAP-S-INVALID EXIT THEN
    _VFSNAP-SPEC-F-SEALED OVER VFSNAP-SPEC.FLAGS DUP @ ROT OR SWAP !
    DROP VFSNAP-S-OK ;

' _VFSNAP-SPEC-SEAL CONSTANT _vfsnap-spec-seal-xt
: VFSNAP-SPEC-SEAL  ( spec -- status )
    DUP _VFSNAP-SPEC-SPAN-SAFE? 0= IF DROP VFSNAP-S-INVALID EXIT THEN
    _vfsnap-operation-active @ IF DROP VFSNAP-S-BUSY EXIT THEN
    _vfsnap-spec-seal-xt _vfsnap-guard WITH-GUARD ;

\ =====================================================================
\  Store lifecycle and status mapping
\ =====================================================================

: _VFSNAP-VREPL>STATUS  ( vrepl-status -- status )
    CASE
        VREPL-S-OK OF VFSNAP-S-OK ENDOF
        VREPL-S-ROLLED-BACK OF VFSNAP-S-OK ENDOF
        VREPL-S-COMMITTED-CLEANUP OF VFSNAP-S-OK ENDOF
        VREPL-S-INVALID OF VFSNAP-S-INVALID ENDOF
        VREPL-S-CONFLICT OF VFSNAP-S-CONFLICT ENDOF
        VREPL-S-BUSY OF VFSNAP-S-BUSY ENDOF
        VREPL-S-IO OF VFSNAP-S-IO ENDOF
        VREPL-S-RECOVERY OF VFSNAP-S-RECOVERY ENDOF
        VREPL-S-MARKER-CORRUPT OF VFSNAP-S-RECOVERY ENDOF
        VREPL-S-UNCERTAIN OF VFSNAP-S-RECOVERY ENDOF
        VFSNAP-S-RECOVERY SWAP
    ENDCASE ;

: _VFSNAP-STATUS!  ( status store -- status )
    OVER SWAP VFSNAP.LAST-STATUS ! ;

VARIABLE _VFSNB-STATUS
VARIABLE _VFSNB-STORE

: _VFSNAP-BLOCK!  ( status store -- status )
    _VFSNB-STORE ! _VFSNB-STATUS !
    _VFSNB-STATUS @ _VFSNB-STORE @ VFSNAP.LAST-STATUS !
    _VFSNB-STORE @ VFSNAP.FLAGS DUP @
        _VFSNAP-STORE-F-BLOCKED OR SWAP !
    _VFSNB-STATUS @ ;

: _VFSNAP-BLOCKING-STATUS?  ( status -- flag )
    DUP VFSNAP-S-CORRUPT =
    OVER VFSNAP-S-UNSUPPORTED = OR
    OVER VFSNAP-S-IO = OR
    SWAP VFSNAP-S-RECOVERY = OR ;

VARIABLE _VFSNI-PATH-A
VARIABLE _VFSNI-PATH-U
VARIABLE _VFSNI-SCRATCH-A
VARIABLE _VFSNI-SCRATCH-U
VARIABLE _VFSNI-VFS
VARIABLE _VFSNI-SPEC
VARIABLE _VFSNI-STORE
VARIABLE _VFSNI-STATUS

: _VFSNAP-INIT-AT
  ( path-a path-u scratch-a scratch-u vfs spec store -- status )
    _VFSNI-STORE ! _VFSNI-SPEC ! _VFSNI-VFS !
    _VFSNI-SCRATCH-U ! _VFSNI-SCRATCH-A !
    _VFSNI-PATH-U ! _VFSNI-PATH-A !
    _VFSNI-STORE @ VFSNAP-STORE-SIZE 0 FILL
    _VFSNI-SCRATCH-A @ _VFSNI-SCRATCH-U @ 0 FILL
    _VFSNI-VFS @ _VFSNI-STORE @ VFSNAP.REPLACE VREPL-INIT
        DUP _VFSNI-STATUS ! VREPL-S-OK <> IF
        _VFSNI-STORE @ VFSNAP-STORE-SIZE 0 FILL
        _VFSNI-STATUS @ _VFSNAP-VREPL>STATUS EXIT
    THEN
    _VFSNI-PATH-A @ _VFSNI-PATH-U @
        _VFSNI-STORE @ VFSNAP.REPLACE VREPL-DERIVE-PATHS!
        DUP _VFSNI-STATUS ! VREPL-S-OK <> IF
        _VFSNI-STORE @ VFSNAP-STORE-SIZE 0 FILL
        _VFSNI-STATUS @ _VFSNAP-VREPL>STATUS EXIT
    THEN
    _VFSNAP-STORE-MAGIC _VFSNI-STORE @ VFSNAP.MAGIC !
    _VFSNI-VFS @ _VFSNI-STORE @ VFSNAP.VFS !
    _VFSNI-SPEC @ _VFSNI-STORE @ VFSNAP.SPEC !
    _VFSNI-SCRATCH-A @ _VFSNI-STORE @ VFSNAP.SCRATCH-A !
    _VFSNI-SCRATCH-U @ _VFSNI-STORE @ VFSNAP.SCRATCH-U !
    ['] VFS-CLOSE _VFSNI-STORE @ VFSNAP.CLOSE-XT !
    ['] VFS-USE _VFSNI-STORE @ VFSNAP.RESTORE-XT !
    VFSNAP-S-ABSENT _VFSNI-STORE @ VFSNAP.LAST-STATUS !
    VFSNAP-S-OK ;

: _VFSNAP-INIT-SPANS-SAFE?
  ( path-a path-u scratch-a scratch-u spec store -- flag )
    >R
    4 PICK 4 PICK _VFSNAP-SPAN-VALID? 0= IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    2 PICK 2 PICK _VFSNAP-SPAN-VALID? 0= IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    DUP VFSNAP-SPEC-SEALED? 0= IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    DUP VFSNAP-SPEC.PAYLOAD-U @ VFSNAP-HEADER-SIZE +
        2 PICK <> IF 2DROP 2DROP DROP R> DROP 0 EXIT THEN
    R@ VFSNAP-STORE-SIZE _VFSNAP-SPAN-VALID? 0= IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    4 PICK 4 PICK 4 PICK 4 PICK _VFSNAP-RANGES-OVERLAP? IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    4 PICK 4 PICK R@ VFSNAP-STORE-SIZE
        _VFSNAP-RANGES-OVERLAP? IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    2 PICK 2 PICK R@ VFSNAP-STORE-SIZE
        _VFSNAP-RANGES-OVERLAP? IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    DUP VFSNAP-SPEC-SIZE R@ VFSNAP-STORE-SIZE
        _VFSNAP-RANGES-OVERLAP? IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    4 PICK 4 PICK 2 PICK VFSNAP-SPEC-SIZE
        _VFSNAP-RANGES-OVERLAP? IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    2 PICK 2 PICK 2 PICK VFSNAP-SPEC-SIZE
        _VFSNAP-RANGES-OVERLAP? IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    4 PICK 4 PICK 2 PICK _VFSNAP-ALL-PRIVATE-ALIASES? IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    2 PICK 2 PICK 2 PICK _VFSNAP-ALL-PRIVATE-ALIASES? IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    R@ VFSNAP-STORE-SIZE 2 PICK _VFSNAP-ALL-PRIVATE-ALIASES? IF
        2DROP 2DROP DROP R> DROP 0 EXIT
    THEN
    2DROP 2DROP DROP R> DROP -1 ;

' _VFSNAP-INIT-AT CONSTANT _vfsnap-init-at-xt

: VFSNAP-INIT-AT
  ( path-a path-u scratch-a scratch-u vfs spec store -- status )
    6 PICK 6 PICK 6 PICK 6 PICK 5 PICK 5 PICK
        _VFSNAP-INIT-SPANS-SAFE? 0= IF
        7 0 DO DROP LOOP VFSNAP-S-INVALID EXIT
    THEN
    2 PICK 0= IF 7 0 DO DROP LOOP VFSNAP-S-INVALID EXIT THEN
    _vfsnap-operation-active @ IF
        7 0 DO DROP LOOP VFSNAP-S-BUSY EXIT
    THEN
    _vfsnap-init-at-xt _vfsnap-guard WITH-GUARD ;

VARIABLE _VFSNF-STORE

: _VFSNAP-FINI  ( store -- status )
    DUP VFSNAP-VALID? 0= IF DROP VFSNAP-S-INVALID EXIT THEN
    DUP VFSNAP.FLAGS @ _VFSNAP-STORE-F-ACTIVE AND IF
        DROP VFSNAP-S-BUSY EXIT
    THEN
    _VFSNF-STORE !
    _VFSNF-STORE @ VFSNAP-SCRATCH$ 0 FILL
    _VFSNF-STORE @ VFSNAP-STORE-SIZE 0 FILL
    VFSNAP-S-OK ;

' _VFSNAP-FINI CONSTANT _vfsnap-fini-xt
: VFSNAP-FINI  ( store -- status )
    DUP _VFSNAP-STORE-SPAN-SAFE? 0= IF DROP VFSNAP-S-INVALID EXIT THEN
    _vfsnap-operation-active @ IF DROP VFSNAP-S-BUSY EXIT THEN
    _vfsnap-fini-xt _vfsnap-guard WITH-GUARD ;

\ =====================================================================
\  Exact read and validation
\ =====================================================================

VARIABLE _VFSOP-STORE
VARIABLE _VFSRD-FD
VARIABLE _VFSRD-OLD-VFS
VARIABLE _VFSRD-HAVE-OLD-VFS
VARIABLE _VFSRD-STATUS
VARIABLE _VFSRD-FILE-U
VARIABLE _VFSRD-GENERATION
VARIABLE _VFSRD-CLEAN-FD
VARIABLE _VFSRD-CLEAN-FAILED

: _VFSNAP-RECORD  ( -- record ) _VFSOP-STORE @ VFSNAP.SCRATCH-A @ ;
: _VFSNAP-SPEC    ( -- spec ) _VFSOP-STORE @ VFSNAP.SPEC @ ;

: _VFSNAP-HEADER-CRC  ( record -- crc32 )
    CRC32-BEGIN
    DUP _VFSN-H-HEADER-CRC CRC32-ADD
    DUP _VFSN-H-FLAGS + 8 CRC32-ADD
    DROP CRC32-END ;

: _VFSNAP-PAYLOAD-CRC  ( a u -- crc32 )
    CRC32-BEGIN CRC32-ADD CRC32-END ;

: _VFSRD-CLOSE-CALL  ( -- )
    _VFSRD-CLEAN-FD @ _VFSOP-STORE @ VFSNAP.CLOSE-XT @ EXECUTE ;
: _VFSRD-RESTORE-CALL  ( -- )
    _VFSRD-OLD-VFS @ _VFSOP-STORE @ VFSNAP.RESTORE-XT @ EXECUTE ;

: _VFSRD-CLEANUP  ( -- failed? )
    0 _VFSRD-CLEAN-FAILED !
    _VFSRD-FD @ ?DUP IF
        _VFSRD-CLEAN-FD ! 0 _VFSRD-FD !
        ['] _VFSRD-CLOSE-CALL CATCH IF -1 _VFSRD-CLEAN-FAILED ! THEN
    THEN
    _VFSRD-HAVE-OLD-VFS @ IF
        0 _VFSRD-HAVE-OLD-VFS !
        ['] _VFSRD-RESTORE-CALL CATCH IF -1 _VFSRD-CLEAN-FAILED ! THEN
    THEN
    _VFSRD-CLEAN-FAILED @ ;

: _VFSRD-PARENT-LEN  ( base-offset -- length )
    DUP 1 = IF DROP 1 ELSE 1- THEN ;

: _VFSRD-NAMESPACE-STATUS  ( -- status )
    _VFSOP-STORE @ VFSNAP.REPLACE DUP VREPL.TARGET
    SWAP VREPL.TARGET-BASE @ _VFSRD-PARENT-LEN
    VFS-RP-FOLLOW-FINAL _VFSOP-STORE @ VFSNAP.VFS @
        VFS-RESOLVE-POLICY?
    IF DROP VFSNAP-S-RECOVERY EXIT THEN
    DUP 0= IF DROP VFSNAP-S-RECOVERY EXIT THEN
    IN.TYPE @ VFS-T-DIR <> IF VFSNAP-S-RECOVERY EXIT THEN

    _VFSOP-STORE @ VFSNAP-PATH$
    VFS-RP-NOFOLLOW-FINAL _VFSOP-STORE @ VFSNAP.VFS @
        VFS-RESOLVE-POLICY?
    DUP IF
        DUP VFS-IOR-REASON VFS-R-NOENT = >R
        2DROP R> IF VFSNAP-S-ABSENT ELSE VFSNAP-S-IO THEN EXIT
    THEN DROP
    DUP 0= IF DROP VFSNAP-S-IO EXIT THEN
    IN.TYPE @ VFS-T-FILE <> IF VFSNAP-S-RECOVERY EXIT THEN
    VFSNAP-S-OK ;

: _VFSRD-READ-BODY  ( -- status )
    _VFSRD-NAMESPACE-STATUS DUP IF EXIT THEN DROP
    _VFSOP-STORE @ VFSNAP-PATH$ VFS-OPEN DUP 0= IF
        DROP VFSNAP-S-IO EXIT
    THEN _VFSRD-FD !
    _VFSRD-FD @ VFS-SIZE DUP _VFSRD-FILE-U !
    DUP 0< IF DROP VFSNAP-S-IO EXIT THEN
    VFSNAP-HEADER-SIZE < IF VFSNAP-S-CORRUPT EXIT THEN
    _VFSNAP-RECORD VFSNAP-HEADER-SIZE _VFSRD-FD @
        VFS-READ-EXACT IF VFSNAP-S-IO EXIT THEN
    _VFSNAP-RECORD _VFSN-H-MAGIC + 8
        _VFSNAP-SPEC VFSNAP-SPEC.RECORD-MAGIC 8 COMPARE 0<> IF
        VFSNAP-S-CORRUPT EXIT
    THEN
    _VFSNAP-RECORD _VFSNAP-HEADER-CRC
        _VFSNAP-RECORD _VFSN-H-HEADER-CRC + @ <> IF
        VFSNAP-S-CORRUPT EXIT
    THEN
    _VFSNAP-RECORD _VFSN-H-FORMAT + @
        _VFSNAP-SPEC VFSNAP-SPEC.FORMAT @ <> IF
        VFSNAP-S-UNSUPPORTED EXIT
    THEN
    _VFSNAP-RECORD _VFSN-H-HEADER-SIZE + @ VFSNAP-HEADER-SIZE <>
    _VFSNAP-RECORD _VFSN-H-FLAGS + @ 0<> OR
    _VFSNAP-RECORD _VFSN-H-GENERATION + @ DUP _VFSRD-GENERATION !
        0> 0= OR
    _VFSNAP-RECORD _VFSN-H-PAYLOAD-SIZE + @
        _VFSNAP-SPEC VFSNAP-SPEC.PAYLOAD-U @ <> OR IF
        VFSNAP-S-CORRUPT EXIT
    THEN
    _VFSRD-FILE-U @ _VFSOP-STORE @ VFSNAP.SCRATCH-U @ <> IF
        VFSNAP-S-CORRUPT EXIT
    THEN
    _VFSNAP-RECORD VFSNAP-HEADER-SIZE +
        _VFSNAP-SPEC VFSNAP-SPEC.PAYLOAD-U @
        _VFSRD-FD @ VFS-READ-EXACT IF VFSNAP-S-IO EXIT THEN
    _VFSNAP-RECORD VFSNAP-HEADER-SIZE +
        _VFSNAP-SPEC VFSNAP-SPEC.PAYLOAD-U @ _VFSNAP-PAYLOAD-CRC
        _VFSNAP-RECORD _VFSN-H-PAYLOAD-CRC + @ <> IF
        VFSNAP-S-CORRUPT EXIT
    THEN
    _VFSNAP-RECORD VFSNAP-HEADER-SIZE +
        _VFSNAP-SPEC VFSNAP-SPEC.PAYLOAD-U @
        _VFSRD-GENERATION @
        _VFSNAP-SPEC VFSNAP-SPEC.VALIDATE-XT @ EXECUTE ;

: _VFSRD-READ-OP  ( -- )
    VFS-CUR _VFSRD-OLD-VFS ! -1 _VFSRD-HAVE-OLD-VFS !
    _VFSOP-STORE @ VFSNAP.VFS @ VFS-USE
    _VFSRD-READ-BODY _VFSRD-STATUS ! ;

: _VFSRD-READ-TRANSACTION  ( -- status )
    0 _VFSRD-FD ! 0 _VFSRD-HAVE-OLD-VFS !
    VFSNAP-S-IO _VFSRD-STATUS !
    ['] _VFSRD-READ-OP CATCH IF VFSNAP-S-IO _VFSRD-STATUS ! THEN
    _VFSRD-CLEANUP IF VFSNAP-S-IO EXIT THEN
    _VFSRD-STATUS @ ;

: _VFSRD-READ-TRANSACTION-CALL  ( -- status )
    ['] _VFSRD-READ-TRANSACTION VFS-TRANSACTION ;

: _VFSNAP-READ  ( -- status )
    ['] _VFSRD-READ-TRANSACTION-CALL CATCH ?DUP IF
        DROP VFSNAP-S-IO
    THEN ;

\ =====================================================================
\  Recovery, load, and save bodies
\ =====================================================================

VARIABLE _VFSR-VREPL
VARIABLE _VFSR-STATUS

: _VFSNAP-RECOVER-BODY  ( -- status )
    _VFSOP-STORE @ VFSNAP-BLOCKED? IF
        _VFSOP-STORE @ VFSNAP-LAST-STATUS@ EXIT
    THEN
    _VFSOP-STORE @ VFSNAP.REPLACE VREPL-RECOVER DUP _VFSR-VREPL !
    _VFSOP-STORE @ VFSNAP.LAST-VREPL !
    _VFSR-VREPL @ _VFSNAP-VREPL>STATUS DUP _VFSR-STATUS ! DROP
    _VFSR-STATUS @ VFSNAP-S-OK = IF
        _VFSR-STATUS @ _VFSOP-STORE @ _VFSNAP-STATUS! EXIT
    THEN
    _VFSR-STATUS @ _VFSNAP-BLOCKING-STATUS? IF
        _VFSR-STATUS @ _VFSOP-STORE @ _VFSNAP-BLOCK! EXIT
    THEN
    _VFSR-STATUS @ _VFSOP-STORE @ _VFSNAP-STATUS! ;

VARIABLE _VFSL-DESTINATION
VARIABLE _VFSL-CAPACITY
VARIABLE _VFSL-GENERATION-DST
VARIABLE _VFSL-STATUS

: _VFSNAP-LOAD-BODY  ( -- status )
    _VFSOP-STORE @ VFSNAP-BLOCKED? IF
        _VFSOP-STORE @ VFSNAP-LAST-STATUS@ EXIT
    THEN
    _VFSNAP-RECOVER-BODY DUP IF EXIT THEN DROP
    _VFSNAP-READ DUP _VFSL-STATUS ! DROP
    _VFSL-STATUS @ VFSNAP-S-OK = IF
        _VFSNAP-RECORD VFSNAP-HEADER-SIZE + _VFSL-DESTINATION @
            _VFSNAP-SPEC VFSNAP-SPEC.PAYLOAD-U @ CMOVE
        _VFSRD-GENERATION @ _VFSL-GENERATION-DST @ !
        _VFSL-STATUS @ _VFSOP-STORE @ _VFSNAP-STATUS! EXIT
    THEN
    _VFSL-STATUS @ VFSNAP-S-ABSENT = IF
        _VFSL-STATUS @ _VFSOP-STORE @ _VFSNAP-STATUS! EXIT
    THEN
    _VFSL-STATUS @ _VFSNAP-BLOCKING-STATUS? IF
        _VFSL-STATUS @ _VFSOP-STORE @ _VFSNAP-BLOCK! EXIT
    THEN
    _VFSL-STATUS @ _VFSOP-STORE @ _VFSNAP-STATUS! ;

VARIABLE _VFSS-CONTEXT
VARIABLE _VFSS-EXPECTED
VARIABLE _VFSS-NEXT
VARIABLE _VFSS-STATUS
VARIABLE _VFSS-VREPL

: _VFSNAP-SAVE-FAIL  ( status -- status )
    DUP _VFSNAP-BLOCKING-STATUS? IF
        _VFSOP-STORE @ _VFSNAP-BLOCK! EXIT
    THEN
    _VFSOP-STORE @ _VFSNAP-STATUS! ;

: _VFSNAP-ENCODE  ( -- status )
    _VFSNAP-RECORD _VFSOP-STORE @ VFSNAP.SCRATCH-U @ 0 FILL
    _VFSS-CONTEXT @
    _VFSNAP-RECORD VFSNAP-HEADER-SIZE +
    _VFSNAP-SPEC VFSNAP-SPEC.PAYLOAD-U @
    _VFSS-NEXT @ _VFSNAP-SPEC VFSNAP-SPEC.ENCODE-XT @ EXECUTE
    DUP IF EXIT THEN DROP
    _VFSNAP-SPEC VFSNAP-SPEC.RECORD-MAGIC
        _VFSNAP-RECORD _VFSN-H-MAGIC + 8 CMOVE
    _VFSNAP-SPEC VFSNAP-SPEC.FORMAT @
        _VFSNAP-RECORD _VFSN-H-FORMAT + !
    VFSNAP-HEADER-SIZE _VFSNAP-RECORD _VFSN-H-HEADER-SIZE + !
    _VFSS-NEXT @ _VFSNAP-RECORD _VFSN-H-GENERATION + !
    _VFSNAP-SPEC VFSNAP-SPEC.PAYLOAD-U @
        _VFSNAP-RECORD _VFSN-H-PAYLOAD-SIZE + !
    _VFSNAP-RECORD VFSNAP-HEADER-SIZE +
        _VFSNAP-SPEC VFSNAP-SPEC.PAYLOAD-U @ _VFSNAP-PAYLOAD-CRC
        _VFSNAP-RECORD _VFSN-H-PAYLOAD-CRC + !
    _VFSNAP-RECORD _VFSNAP-HEADER-CRC
        _VFSNAP-RECORD _VFSN-H-HEADER-CRC + !
    VFSNAP-S-OK ;

: _VFSNAP-SAVE-BODY  ( -- status )
    _VFSS-EXPECTED @ 0< IF VFSNAP-S-INVALID _VFSNAP-SAVE-FAIL EXIT THEN
    _VFSS-EXPECTED @ 1+ DUP _VFSS-NEXT ! 0> 0= IF
        VFSNAP-S-CAPACITY _VFSNAP-SAVE-FAIL EXIT
    THEN
    _VFSOP-STORE @ VFSNAP-BLOCKED? IF
        _VFSOP-STORE @ VFSNAP-LAST-STATUS@ EXIT
    THEN
    _VFSNAP-RECOVER-BODY DUP IF _VFSNAP-SAVE-FAIL EXIT THEN DROP
    _VFSNAP-READ DUP _VFSS-STATUS ! DROP
    _VFSS-STATUS @ VFSNAP-S-ABSENT = IF
        _VFSS-EXPECTED @ IF VFSNAP-S-CONFLICT _VFSNAP-SAVE-FAIL EXIT THEN
    ELSE
        _VFSS-STATUS @ VFSNAP-S-OK <> IF
            _VFSS-STATUS @ _VFSNAP-SAVE-FAIL EXIT
        THEN
        _VFSRD-GENERATION @ _VFSS-EXPECTED @ <> IF
            VFSNAP-S-CONFLICT _VFSNAP-SAVE-FAIL EXIT
        THEN
    THEN
    _VFSNAP-ENCODE DUP _VFSS-STATUS ! IF
        _VFSS-STATUS @ _VFSNAP-SAVE-FAIL EXIT
    THEN
    _VFSNAP-RECORD _VFSOP-STORE @ VFSNAP.SCRATCH-U @
        _VFSOP-STORE @ VFSNAP.REPLACE VREPL-REPLACE DUP _VFSS-VREPL !
    _VFSOP-STORE @ VFSNAP.LAST-VREPL !
    _VFSS-VREPL @ _VFSNAP-VREPL>STATUS DUP _VFSS-STATUS ! DROP
    _VFSS-STATUS @ VFSNAP-S-OK = IF
        _VFSS-STATUS @ _VFSOP-STORE @ _VFSNAP-STATUS! EXIT
    THEN
    _VFSS-STATUS @ _VFSNAP-SAVE-FAIL ;

\ =====================================================================
\  Public terminal wrappers
\ =====================================================================

: _VFSNAP-OP-BEGIN  ( store -- status )
    DUP VFSNAP-VALID? 0= IF DROP VFSNAP-S-INVALID EXIT THEN
    _vfsnap-operation-active @ IF DROP VFSNAP-S-BUSY EXIT THEN
    -1 _vfsnap-operation-active !
    DUP _VFSOP-STORE !
    _VFSNAP-STORE-F-ACTIVE OVER VFSNAP.FLAGS DUP @ ROT OR SWAP !
    DROP VFSNAP-S-OK ;

: _VFSNAP-OP-END  ( -- )
    _VFSOP-STORE @ VFSNAP.FLAGS DUP @
        _VFSNAP-STORE-F-ACTIVE INVERT AND SWAP !
    0 _vfsnap-operation-active ! ;

: _VFSNAP-OP-WIPE  ( -- ) _VFSOP-STORE @ VFSNAP-SCRATCH$ 0 FILL ;

VARIABLE _VFSRP-STORE

: _VFSNAP-RECOVER-CALL  ( -- status ) _VFSNAP-RECOVER-BODY ;

: _VFSNAP-RECOVER-PUBLIC  ( store -- status )
    DUP _VFSNAP-OP-BEGIN DUP IF NIP EXIT THEN DROP DROP
    ['] _VFSNAP-RECOVER-CALL CATCH
    _VFSNAP-OP-WIPE _VFSNAP-OP-END
    ?DUP IF DROP VFSNAP-S-IO _VFSOP-STORE @ _VFSNAP-BLOCK! THEN ;

' _VFSNAP-RECOVER-PUBLIC CONSTANT _vfsnap-recover-xt
: VFSNAP-RECOVER  ( store -- status )
    DUP _VFSNAP-STORE-SPAN-SAFE? 0= IF DROP VFSNAP-S-INVALID EXIT THEN
    _vfsnap-operation-active @ IF DROP VFSNAP-S-BUSY EXIT THEN
    _vfsnap-recover-xt _vfsnap-guard WITH-GUARD ;

: _VFSNAP-IO-SPANS-SAFE?
  ( destination capacity generation-dst store -- flag )
    >R
    2 PICK 0= IF 2DROP DROP R> DROP 0 EXIT THEN
    2 PICK 2 PICK _VFSNAP-SPAN-VALID? 0= IF
        2DROP DROP R> DROP 0 EXIT
    THEN
    DUP 8 _VFSNAP-SPAN-VALID? 0= IF 2DROP DROP R> DROP 0 EXIT THEN
    R@ VFSNAP-VALID? 0= IF 2DROP DROP R> DROP 0 EXIT THEN
    2 PICK 2 PICK R@ VFSNAP-STORE-SIZE
        _VFSNAP-RANGES-OVERLAP? IF 2DROP DROP R> DROP 0 EXIT THEN
    2 PICK 2 PICK R@ VFSNAP-SCRATCH$
        _VFSNAP-RANGES-OVERLAP? IF 2DROP DROP R> DROP 0 EXIT THEN
    2 PICK 2 PICK R@ VFSNAP.SPEC @ VFSNAP-SPEC-SIZE
        _VFSNAP-RANGES-OVERLAP? IF 2DROP DROP R> DROP 0 EXIT THEN
    2 PICK 2 PICK R@ VFSNAP.SPEC @ _VFSNAP-ALL-PRIVATE-ALIASES? IF
        2DROP DROP R> DROP 0 EXIT
    THEN
    DUP 8 R@ VFSNAP-STORE-SIZE _VFSNAP-RANGES-OVERLAP? IF
        2DROP DROP R> DROP 0 EXIT
    THEN
    DUP 8 R@ VFSNAP-SCRATCH$ _VFSNAP-RANGES-OVERLAP? IF
        2DROP DROP R> DROP 0 EXIT
    THEN
    DUP 8 R@ VFSNAP.SPEC @ VFSNAP-SPEC-SIZE
        _VFSNAP-RANGES-OVERLAP? IF 2DROP DROP R> DROP 0 EXIT THEN
    DUP 8 R@ VFSNAP.SPEC @ _VFSNAP-ALL-PRIVATE-ALIASES? IF
        2DROP DROP R> DROP 0 EXIT
    THEN
    2 PICK 2 PICK 2 PICK 8 _VFSNAP-RANGES-OVERLAP? IF
        2DROP DROP R> DROP 0 EXIT
    THEN
    2DROP DROP R> DROP -1 ;

: _VFSNAP-LOAD-CALL  ( -- status ) _VFSNAP-LOAD-BODY ;

: _VFSNAP-LOAD-PUBLIC
  ( destination capacity generation-dst store -- status )
    DUP _VFSNAP-OP-BEGIN DUP IF
        >R 2DROP 2DROP R> EXIT
    THEN DROP DROP
    _VFSL-GENERATION-DST ! _VFSL-CAPACITY ! _VFSL-DESTINATION !
    _VFSL-CAPACITY @ _VFSNAP-SPEC VFSNAP-SPEC.PAYLOAD-U @ < IF
        VFSNAP-S-CAPACITY
    ELSE
        ['] _VFSNAP-LOAD-CALL CATCH ?DUP IF
            DROP VFSNAP-S-IO _VFSOP-STORE @ _VFSNAP-BLOCK!
        THEN
    THEN
    _VFSNAP-OP-WIPE _VFSNAP-OP-END ;

' _VFSNAP-LOAD-PUBLIC CONSTANT _vfsnap-load-xt
: VFSNAP-LOAD
  ( payload-destination capacity generation-destination store -- status )
    3 PICK 3 PICK 3 PICK 3 PICK _VFSNAP-IO-SPANS-SAFE? 0= IF
        2DROP 2DROP VFSNAP-S-INVALID EXIT
    THEN
    _vfsnap-operation-active @ IF
        2DROP 2DROP VFSNAP-S-BUSY EXIT
    THEN
    _vfsnap-load-xt _vfsnap-guard WITH-GUARD ;

: _VFSNAP-SAVE-CALL  ( -- status ) _VFSNAP-SAVE-BODY ;

: _VFSNAP-SAVE-PUBLIC  ( encode-context expected-generation store -- status )
    DUP _VFSNAP-OP-BEGIN DUP IF
        >R 2DROP DROP R> EXIT
    THEN DROP DROP
    _VFSS-EXPECTED ! _VFSS-CONTEXT !
    ['] _VFSNAP-SAVE-CALL CATCH ?DUP IF
        DROP VFSNAP-S-IO _VFSOP-STORE @ _VFSNAP-BLOCK!
    THEN
    _VFSNAP-OP-WIPE _VFSNAP-OP-END ;

' _VFSNAP-SAVE-PUBLIC CONSTANT _vfsnap-save-xt
: VFSNAP-SAVE  ( encode-context expected-generation store -- status )
    DUP _VFSNAP-STORE-SPAN-SAFE? 0= IF
        2DROP DROP VFSNAP-S-INVALID EXIT
    THEN
    _vfsnap-operation-active @ IF
        2DROP DROP VFSNAP-S-BUSY EXIT
    THEN
    _vfsnap-save-xt _vfsnap-guard WITH-GUARD ;

HERE _VFSNAP-PRIVATE-LIMIT !
