\ =====================================================================
\  auth.f - Native ChatGPT device authentication for the Codex provider
\ =====================================================================
\  Wire behavior is pinned to openai/codex commit
\  5c19155cbd93bfa099016e7487259f61669823ff (2026-07-11).
\ =====================================================================

PROVIDED akashic-agent-codex-auth

REQUIRE ../../provider-auth.f
REQUIRE ../../../../../security/oauth2/token-set.f
REQUIRE ../../../../../security/oauth2/jwt.f
REQUIRE ../../../../../net/http-buffered.f
REQUIRE ../../../../../net/url.f

0 CONSTANT CDA-SUB-IDLE
1 CONSTANT CDA-SUB-USER-CODE
2 CONSTANT CDA-SUB-TOKEN-POLL
3 CONSTANT CDA-SUB-TOKEN-EXCHANGE
4 CONSTANT CDA-SUB-REFRESH

512 CONSTANT CDA-DEVICE-ID-CAPACITY
16384 CONSTANT CDA-REQUEST-BODY-CAPACITY
32768 CONSTANT CDA-WIRE-CAPACITY
32768 CONSTANT CDA-RESPONSE-CAPACITY
8192 CONSTANT CDA-CLAIMS-CAPACITY
900000 CONSTANT CDA-LOGIN-TIMEOUT-MS

: CODEX-AUTH-HOST  ( -- addr len ) S" auth.openai.com" ;
: CODEX-AUTH-USER-CODE-PATH  ( -- addr len )
    S" /api/accounts/deviceauth/usercode" ;
: CODEX-AUTH-TOKEN-POLL-PATH  ( -- addr len )
    S" /api/accounts/deviceauth/token" ;
: CODEX-AUTH-TOKEN-PATH  ( -- addr len ) S" /oauth/token" ;
: CODEX-AUTH-VERIFY-URI  ( -- addr len ) S" https://auth.openai.com/codex/device" ;
: CODEX-AUTH-REDIRECT-URI  ( -- addr len )
    S" https://auth.openai.com/deviceauth/callback" ;
: CODEX-AUTH-CLIENT-ID  ( -- addr len )
    S" app_EMoamEEZ73f0CkXaXp7hrann" ;

  0 CONSTANT _CDA-AUTH
_CDA-AUTH AGENT-PROVIDER-AUTH-SIZE + CONSTANT _CDA-TOKENS
_CDA-TOKENS OAUTH2-TOKEN-SET-SIZE + CONSTANT _CDA-PORT
_CDA-PORT 8 + CONSTANT _CDA-SUBSTATE
_CDA-SUBSTATE 8 + CONSTANT _CDA-STARTED-MS
_CDA-STARTED-MS 8 + CONSTANT _CDA-NEXT-POLL-MS
_CDA-NEXT-POLL-MS 8 + CONSTANT _CDA-DEVICE-ID-U
_CDA-DEVICE-ID-U 8 + CONSTANT _CDA-REQUEST-BODY-U
_CDA-REQUEST-BODY-U 8 + CONSTANT _CDA-CLAIMS-U
_CDA-CLAIMS-U 8 + CONSTANT _CDA-WORK
_CDA-WORK 8 + CONSTANT CODEX-DEVICE-AUTH-SIZE

0 CONSTANT _CDAW-REQUEST
_CDAW-REQUEST HTTP-REQUEST-SIZE + CONSTANT _CDAW-EXCHANGE
_CDAW-EXCHANGE HTTP-BUFFERED-SIZE + CONSTANT _CDAW-DEVICE-ID
_CDAW-DEVICE-ID CDA-DEVICE-ID-CAPACITY + CONSTANT _CDAW-REQUEST-BODY
_CDAW-REQUEST-BODY CDA-REQUEST-BODY-CAPACITY + CONSTANT _CDAW-WIRE
_CDAW-WIRE CDA-WIRE-CAPACITY + CONSTANT _CDAW-RESPONSE
_CDAW-RESPONSE CDA-RESPONSE-CAPACITY + CONSTANT _CDAW-CLAIMS
_CDAW-CLAIMS CDA-CLAIMS-CAPACITY + CONSTANT CODEX-DEVICE-WORK-SIZE

: CDA.AUTH           ( context -- auth ) _CDA-AUTH + ;
: CDA.TOKENS         ( context -- tokens ) _CDA-TOKENS + ;
: CDA.PORT           ( context -- a ) _CDA-PORT + ;
: CDA.SUBSTATE       ( context -- a ) _CDA-SUBSTATE + ;
: CDA.STARTED-MS     ( context -- a ) _CDA-STARTED-MS + ;
: CDA.NEXT-POLL-MS   ( context -- a ) _CDA-NEXT-POLL-MS + ;
: CDA.DEVICE-ID-U    ( context -- a ) _CDA-DEVICE-ID-U + ;
: CDA.REQUEST-BODY-U ( context -- a ) _CDA-REQUEST-BODY-U + ;
: CDA.CLAIMS-U       ( context -- a ) _CDA-CLAIMS-U + ;
: CDA.WORK           ( context -- a ) _CDA-WORK + ;
: CDA.REQUEST        ( context -- request ) CDA.WORK @ _CDAW-REQUEST + ;
: CDA.EXCHANGE       ( context -- exchange ) CDA.WORK @ _CDAW-EXCHANGE + ;
: CDA.DEVICE-ID      ( context -- buffer ) CDA.WORK @ _CDAW-DEVICE-ID + ;
: CDA.REQUEST-BODY   ( context -- buffer ) CDA.WORK @ _CDAW-REQUEST-BODY + ;
: CDA.WIRE           ( context -- buffer ) CDA.WORK @ _CDAW-WIRE + ;
: CDA.RESPONSE       ( context -- buffer ) CDA.WORK @ _CDAW-RESPONSE + ;
: CDA.CLAIMS         ( context -- buffer ) CDA.WORK @ _CDAW-CLAIMS + ;

: CODEX-DEVICE-AUTH-PORT  ( context -- auth ) CDA.AUTH ;
: CODEX-DEVICE-AUTH-TOKENS  ( context -- tokens ) CDA.TOKENS ;

VARIABLE _CDA-C
VARIABLE _CDA-STATUS
VARIABLE _CDA-A
VARIABLE _CDA-U
VARIABLE _CDA-VA
VARIABLE _CDA-VU
VARIABLE _CDA-FOUND
VARIABLE _CDA-IOR

: _CDA-WORK-FREE  ( context -- )
    DUP _CDA-C ! CDA.WORK @ ?DUP IF
        DUP _CDAW-EXCHANGE + HBUF-CANCEL DROP
        DUP _CDAW-REQUEST + HREQ-CLEAR
        DUP CODEX-DEVICE-WORK-SIZE 0 FILL FREE
        0 _CDA-C @ CDA.WORK !
    THEN ;

: _CDA-WORK-NEW  ( context -- status )
    DUP _CDA-C ! CDA.WORK @ IF AAUTH-S-OK EXIT THEN
    CODEX-DEVICE-WORK-SIZE ALLOCATE DUP IF
        2DROP AAUTH-S-CAPACITY EXIT
    THEN
    DROP DUP CODEX-DEVICE-WORK-SIZE 0 FILL
    DUP _CDA-C @ CDA.WORK ! DROP
    _CDA-C @ CDA.WIRE CDA-WIRE-CAPACITY _CDA-C @ CDA.REQUEST HREQ-INIT
    IF _CDA-C @ _CDA-WORK-FREE AAUTH-S-CAPACITY EXIT THEN
    _CDA-C @ CDA.RESPONSE CDA-RESPONSE-CAPACITY
    _CDA-C @ CDA.EXCHANGE HBUF-INIT HBUF-S-OK <> IF
        _CDA-C @ _CDA-WORK-FREE AAUTH-S-INVALID EXIT
    THEN
    -1 _CDA-C @ CDA.EXCHANGE HBUF-PERSISTENT!
    AAUTH-S-OK ;

: _CDA-AUTH-TOUCH  ( status state context -- status )
    _CDA-C ! >R DUP _CDA-C @ CDA.AUTH AAUTH.LAST-STATUS !
    R> _CDA-C @ CDA.AUTH AAUTH.STATE !
    1 _CDA-C @ CDA.AUTH AAUTH.REVISION +! ;

: _CDA-FAIL  ( status message-a message-u context -- status )
    _CDA-C ! _CDA-U ! _CDA-A ! _CDA-STATUS !
    _CDA-A @ _CDA-U @ _CDA-C @ CDA.AUTH AAUTH.ERROR CV-STRING! DROP
    _CDA-STATUS @ AAUTH-STATE-ERROR _CDA-C @ _CDA-AUTH-TOUCH ;

: _CDA-FIELD  ( object-a object-u key-a key-u -- value-a value-u flag )
    JSON-FIELD _CDA-IOR ! _CDA-FOUND ! _CDA-VU ! _CDA-VA !
    _CDA-IOR @ _CDA-FOUND @ 0= OR IF 0 0 0 EXIT THEN
    _CDA-VA @ _CDA-VU @ -1 ;

: _CDA-STRING-FIELD  ( object-a object-u key-a key-u -- value-a value-u flag )
    _CDA-FIELD 0= IF 2DROP 0 0 0 EXIT THEN
    2DUP JSON-TYPE? JSON-T-STRING <> IF 2DROP 0 0 0 EXIT THEN
    JSON-GET-STRING -1 ;

VARIABLE _CDA-BUILD-C
VARIABLE _CDA-BUILD-PATH-A
VARIABLE _CDA-BUILD-PATH-U
VARIABLE _CDA-BUILD-TYPE-A
VARIABLE _CDA-BUILD-TYPE-U

: _CDA-START-REQUEST  ( path-a path-u content-type-a content-type-u context -- status )
    _CDA-BUILD-C ! _CDA-BUILD-TYPE-U ! _CDA-BUILD-TYPE-A !
    _CDA-BUILD-PATH-U ! _CDA-BUILD-PATH-A !
    _CDA-BUILD-C @ CDA.REQUEST HREQ-CLEAR
    S" POST" _CDA-BUILD-PATH-A @ _CDA-BUILD-PATH-U @
    _CDA-BUILD-C @ CDA.REQUEST HREQ-BEGIN IF AAUTH-S-PROTOCOL EXIT THEN
    CODEX-AUTH-HOST _CDA-BUILD-C @ CDA.REQUEST HREQ-HOST
    IF AAUTH-S-PROTOCOL EXIT THEN
    _CDA-BUILD-TYPE-A @ _CDA-BUILD-TYPE-U @
    _CDA-BUILD-C @ CDA.REQUEST HREQ-CONTENT-TYPE
    IF AAUTH-S-PROTOCOL EXIT THEN
    S" application/json" _CDA-BUILD-C @ CDA.REQUEST HREQ-ACCEPT
    IF AAUTH-S-PROTOCOL EXIT THEN
    S" Akashic/1" _CDA-BUILD-C @ CDA.REQUEST HREQ-USER-AGENT
    IF AAUTH-S-PROTOCOL EXIT THEN
    _CDA-BUILD-C @ CDA.REQUEST-BODY
    _CDA-BUILD-C @ CDA.REQUEST-BODY-U @
    _CDA-BUILD-C @ CDA.REQUEST HREQ-BODY
    IF AAUTH-S-CAPACITY EXIT THEN
    _CDA-BUILD-C @ CDA.REQUEST _CDA-BUILD-C @ CDA.PORT @
    _CDA-BUILD-C @ CDA.EXCHANGE HBUF-START
    DUP HBUF-S-PENDING = IF DROP AAUTH-S-PENDING ELSE
        DROP AAUTH-S-TRANSPORT
    THEN ;

: _CDA-BUILD-USER-CODE  ( context -- status )
    _CDA-C !
    JSON-BUILD-RESET _CDA-C @ CDA.REQUEST-BODY CDA-REQUEST-BODY-CAPACITY
    JSON-SET-OUTPUT
    JSON-{ S" client_id" JSON-KEY: CODEX-AUTH-CLIENT-ID JSON-ESTR JSON-}
    JSON-OUTPUT-OK? 0= IF AAUTH-S-CAPACITY EXIT THEN
    JSON-OUTPUT-RESULT NIP _CDA-C @ CDA.REQUEST-BODY-U !
    CODEX-AUTH-USER-CODE-PATH S" application/json" _CDA-C @
    _CDA-START-REQUEST ;

: _CDA-TRANSIENT-CLEAR  ( context -- )
    DUP _CDA-C ! _CDA-WORK-FREE
    0 _CDA-C @ CDA.REQUEST-BODY-U !
    0 _CDA-C @ CDA.DEVICE-ID-U !
    0 _CDA-C @ CDA.SUBSTATE ! ;

: _CDA-BEGIN  ( context -- status )
    DUP _CDA-C ! CDA.AUTH DUP AAUTH.STATE @
    DUP AAUTH-STATE-STARTING = OVER AAUTH-STATE-PENDING = OR
    SWAP AAUTH-STATE-REFRESHING = OR IF DROP AAUTH-S-BUSY EXIT THEN
    DROP
    _CDA-C @ _CDA-WORK-NEW ?DUP IF
        S" Insufficient memory for device login" _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-C @ CDA.TOKENS O2TOK-CLEAR
    _CDA-C @ CDA.AUTH AAUTH-METADATA-CLEAR
    MS@ DUP _CDA-C @ CDA.STARTED-MS !
    CDA-LOGIN-TIMEOUT-MS + _CDA-C @ CDA.AUTH AAUTH.EXPIRES-MS !
    CDA-SUB-USER-CODE _CDA-C @ CDA.SUBSTATE !
    _CDA-C @ _CDA-BUILD-USER-CODE DUP AAUTH-S-PENDING <> IF
        S" Could not start device login" _CDA-C @ _CDA-FAIL EXIT
    THEN
    DROP AAUTH-S-PENDING AAUTH-STATE-STARTING _CDA-C @ _CDA-AUTH-TOUCH ;

VARIABLE _CDA-POLL-C

: _CDA-BUILD-TOKEN-POLL  ( context -- status )
    _CDA-C !
    JSON-BUILD-RESET _CDA-C @ CDA.REQUEST-BODY CDA-REQUEST-BODY-CAPACITY
    JSON-SET-OUTPUT
    JSON-{
    S" device_auth_id" JSON-KEY:
    _CDA-C @ CDA.DEVICE-ID _CDA-C @ CDA.DEVICE-ID-U @ JSON-ESTR
    S" user_code" JSON-KEY:
    _CDA-C @ CDA.AUTH AAUTH.USER-CODE DUP CV-DATA@ SWAP CV-LEN@ JSON-ESTR
    JSON-}
    JSON-OUTPUT-OK? 0= IF AAUTH-S-CAPACITY EXIT THEN
    JSON-OUTPUT-RESULT NIP _CDA-C @ CDA.REQUEST-BODY-U !
    CODEX-AUTH-TOKEN-POLL-PATH S" application/json" _CDA-C @
    _CDA-START-REQUEST ;

VARIABLE _CDA-FORM-A
VARIABLE _CDA-FORM-U
VARIABLE _CDA-FORM-W
VARIABLE _CDA-FORM-C

: _CDA-FORM-RAW  ( addr len -- status )
    _CDA-FORM-U ! _CDA-FORM-A !
    _CDA-FORM-W @ _CDA-FORM-U @ + CDA-REQUEST-BODY-CAPACITY > IF
        AAUTH-S-CAPACITY EXIT
    THEN
    _CDA-FORM-A @ _CDA-FORM-C @ CDA.REQUEST-BODY _CDA-FORM-W @ +
    _CDA-FORM-U @ CMOVE
    _CDA-FORM-U @ _CDA-FORM-W +! AAUTH-S-OK ;

: _CDA-FORM-VALUE  ( addr len -- status )
    _CDA-FORM-C @ CDA.REQUEST-BODY _CDA-FORM-W @ +
    CDA-REQUEST-BODY-CAPACITY _CDA-FORM-W @ - URL-ENCODE-COMPONENT
    URL-OK? 0= IF DROP AAUTH-S-CAPACITY EXIT THEN
    _CDA-FORM-W +! AAUTH-S-OK ;

VARIABLE _CDA-X-AUTH-A
VARIABLE _CDA-X-AUTH-U
VARIABLE _CDA-X-VERIFIER-A
VARIABLE _CDA-X-VERIFIER-U

: _CDA-START-TOKEN-EXCHANGE  ( authorization-a authorization-u verifier-a verifier-u context -- status )
    _CDA-FORM-C ! _CDA-X-VERIFIER-U ! _CDA-X-VERIFIER-A !
    _CDA-X-AUTH-U ! _CDA-X-AUTH-A ! 0 _CDA-FORM-W ! URL-CLEAR-ERR
    S" grant_type=authorization_code&code=" _CDA-FORM-RAW ?DUP IF EXIT THEN
    _CDA-X-AUTH-A @ _CDA-X-AUTH-U @ _CDA-FORM-VALUE ?DUP IF EXIT THEN
    S" &redirect_uri=" _CDA-FORM-RAW ?DUP IF EXIT THEN
    CODEX-AUTH-REDIRECT-URI _CDA-FORM-VALUE ?DUP IF EXIT THEN
    S" &client_id=" _CDA-FORM-RAW ?DUP IF EXIT THEN
    CODEX-AUTH-CLIENT-ID _CDA-FORM-VALUE ?DUP IF EXIT THEN
    S" &code_verifier=" _CDA-FORM-RAW ?DUP IF EXIT THEN
    _CDA-X-VERIFIER-A @ _CDA-X-VERIFIER-U @ _CDA-FORM-VALUE ?DUP IF EXIT THEN
    _CDA-FORM-W @ _CDA-FORM-C @ CDA.REQUEST-BODY-U !
    CDA-SUB-TOKEN-EXCHANGE _CDA-FORM-C @ CDA.SUBSTATE !
    CODEX-AUTH-TOKEN-PATH S" application/x-www-form-urlencoded"
    _CDA-FORM-C @ _CDA-START-REQUEST ;

VARIABLE _CDA-OBJ-A
VARIABLE _CDA-OBJ-U
VARIABLE _CDA-ID-A
VARIABLE _CDA-ID-U
VARIABLE _CDA-ACCESS-A
VARIABLE _CDA-ACCESS-U
VARIABLE _CDA-REFRESH-A
VARIABLE _CDA-REFRESH-U
VARIABLE _CDA-EXP-MS
VARIABLE _CDA-AUTHORIZATION-A
VARIABLE _CDA-AUTHORIZATION-U

: _CDA-ACCESS-EXPIRY  ( access-a access-u context -- epoch-ms )
    _CDA-C ! _CDA-ACCESS-U ! _CDA-ACCESS-A !
    _CDA-ACCESS-A @ _CDA-ACCESS-U @ _CDA-C @ CDA.CLAIMS CDA-CLAIMS-CAPACITY
    O2JWT-PAYLOAD DUP IF 2DROP EPOCH@ 3600000 + EXIT THEN
    DROP DUP _CDA-C @ CDA.CLAIMS-U !
    _CDA-C @ CDA.CLAIMS SWAP JSON-ENTER S" exp" JSON-KEY
    JSON-GET-NUMBER 1000 * ;

: _CDA-CLAIMS-METADATA  ( id-a id-u context -- status )
    _CDA-C ! _CDA-ID-U ! _CDA-ID-A !
    _CDA-ID-A @ _CDA-ID-U @ _CDA-C @ CDA.CLAIMS CDA-CLAIMS-CAPACITY
    O2JWT-PAYLOAD DUP IF 2DROP AAUTH-S-PROTOCOL EXIT THEN
    DROP _CDA-C @ CDA.CLAIMS-U !
    _CDA-C @ CDA.CLAIMS _CDA-C @ CDA.CLAIMS-U @
    S" email" _CDA-STRING-FIELD IF
        _CDA-C @ CDA.AUTH AAUTH.ACCOUNT-LABEL CV-STRING! DROP
    ELSE
        2DROP S" ChatGPT account" _CDA-C @ CDA.AUTH AAUTH.ACCOUNT-LABEL
        CV-STRING! DROP
    THEN
    _CDA-C @ CDA.CLAIMS _CDA-C @ CDA.CLAIMS-U @
    S" https://api.openai.com/auth" _CDA-FIELD 0= IF
        2DROP AAUTH-S-PROTOCOL EXIT
    THEN
    2DUP JSON-OBJECT? 0= IF 2DROP AAUTH-S-PROTOCOL EXIT THEN
    2DUP S" chatgpt_plan_type" _CDA-STRING-FIELD IF
        _CDA-C @ CDA.AUTH AAUTH.PLAN CV-STRING! DROP
    ELSE
        2DROP
    THEN
    S" chatgpt_account_id" _CDA-STRING-FIELD 0= IF
        2DROP AAUTH-S-PROTOCOL EXIT
    THEN
    _CDA-C @ CDA.AUTH AAUTH.ACCOUNT-ID CV-STRING!
    IF AAUTH-S-CAPACITY ELSE AAUTH-S-OK THEN ;

VARIABLE _CDAR-C
VARIABLE _CDAR-ID-A
VARIABLE _CDAR-ID-U
VARIABLE _CDAR-ACCESS-A
VARIABLE _CDAR-ACCESS-U
VARIABLE _CDAR-REFRESH-A
VARIABLE _CDAR-REFRESH-U
VARIABLE _CDAR-EXPIRES
VARIABLE _CDAR-STATUS

: _CDA-TOKEN-STATUS  ( token-status -- auth-status )
    CASE
        O2TOK-S-INVALID OF AAUTH-S-INVALID ENDOF
        O2TOK-S-CAPACITY OF AAUTH-S-CAPACITY ENDOF
        O2TOK-S-BUSY OF AAUTH-S-BUSY ENDOF
        DROP AAUTH-S-INVALID
    ENDCASE ;

: CODEX-DEVICE-AUTH-RESTORE  ( id-a id-u access-a access-u refresh-a refresh-u expires-ms context -- status )
    _CDAR-C ! _CDAR-EXPIRES !
    _CDAR-REFRESH-U ! _CDAR-REFRESH-A !
    _CDAR-ACCESS-U ! _CDAR-ACCESS-A !
    _CDAR-ID-U ! _CDAR-ID-A !
    _CDAR-C @ 0= IF AAUTH-S-INVALID EXIT THEN
    _CDAR-C @ _CDA-TRANSIENT-CLEAR
    _CDAR-ID-A @ _CDAR-ID-U @
    _CDAR-ACCESS-A @ _CDAR-ACCESS-U @
    _CDAR-REFRESH-A @ _CDAR-REFRESH-U @
    _CDAR-EXPIRES @ _CDAR-C @ CDA.TOKENS O2TOK-SET
    DUP O2TOK-S-OK <> IF _CDA-TOKEN-STATUS EXIT THEN DROP
    _CDAR-C @ CDA.AUTH AAUTH-METADATA-CLEAR
    _CDAR-C @ _CDA-WORK-NEW ?DUP IF
        _CDAR-C @ CDA.TOKENS O2TOK-CLEAR
        AAUTH-STATE-SIGNED-OUT _CDAR-C @ _CDA-AUTH-TOUCH EXIT
    THEN
    _CDAR-ID-A @ _CDAR-ID-U @ _CDAR-C @ _CDA-CLAIMS-METADATA
    _CDAR-STATUS !
    _CDAR-C @ _CDA-WORK-FREE
    _CDAR-STATUS @ ?DUP IF
        _CDAR-C @ CDA.TOKENS O2TOK-CLEAR
        _CDAR-C @ CDA.AUTH AAUTH-METADATA-CLEAR
        AAUTH-STATE-SIGNED-OUT _CDAR-C @ _CDA-AUTH-TOUCH EXIT
    THEN
    0 _CDAR-C @ CDA.STARTED-MS !
    0 _CDAR-C @ CDA.NEXT-POLL-MS !
    CDA-SUB-IDLE _CDAR-C @ CDA.SUBSTATE !
    AAUTH-S-OK AAUTH-STATE-READY _CDAR-C @ _CDA-AUTH-TOUCH ;

: _CDA-HANDLE-USER-CODE  ( context -- status )
    DUP _CDA-C ! CDA.EXCHANGE HBUF.HTTP-CODE @ 200 <> IF
        AAUTH-S-PROTOCOL S" Device login is unavailable" _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-C @ CDA.RESPONSE _CDA-C @ CDA.EXCHANGE HBUF.BODY-U @
    2DUP JSON-VALID? 0= IF 2DROP
        AAUTH-S-PROTOCOL S" Invalid device login response" _CDA-C @ _CDA-FAIL EXIT
    THEN
    2DUP _CDA-OBJ-U ! _CDA-OBJ-A ! 2DROP
    _CDA-OBJ-A @ _CDA-OBJ-U @ S" device_auth_id" _CDA-STRING-FIELD
    0= IF 2DROP AAUTH-S-PROTOCOL S" Missing device authorization ID"
        _CDA-C @ _CDA-FAIL EXIT THEN
    DUP CDA-DEVICE-ID-CAPACITY > IF 2DROP AAUTH-S-CAPACITY
        S" Device authorization ID is too long" _CDA-C @ _CDA-FAIL EXIT THEN
    DUP _CDA-C @ CDA.DEVICE-ID-U !
    _CDA-C @ CDA.DEVICE-ID SWAP CMOVE
    _CDA-OBJ-A @ _CDA-OBJ-U @ S" user_code" _CDA-STRING-FIELD
    0= IF 2DROP AAUTH-S-PROTOCOL S" Missing device user code"
        _CDA-C @ _CDA-FAIL EXIT THEN
    _CDA-C @ CDA.AUTH AAUTH.USER-CODE CV-STRING! IF
        AAUTH-S-CAPACITY S" Device user code is too long" _CDA-C @ _CDA-FAIL EXIT
    THEN
    CODEX-AUTH-VERIFY-URI _CDA-C @ CDA.AUTH AAUTH.VERIFY-URI CV-STRING! DROP
    _CDA-OBJ-A @ _CDA-OBJ-U @ S" interval" _CDA-STRING-FIELD IF
        STR>NUM IF 1000 * ELSE DROP 5000 THEN
    ELSE
        2DROP 5000
    THEN
    1000 MAX _CDA-C @ CDA.AUTH AAUTH.POLL-INTERVAL-MS !
    MS@ _CDA-C @ CDA.NEXT-POLL-MS !
    CDA-SUB-IDLE _CDA-C @ CDA.SUBSTATE !
    AAUTH-S-PENDING AAUTH-STATE-PENDING _CDA-C @ _CDA-AUTH-TOUCH ;

: _CDA-HANDLE-TOKEN-POLL  ( context -- status )
    DUP _CDA-C ! CDA.EXCHANGE HBUF.HTTP-CODE @ DUP 403 = SWAP 404 = OR IF
        MS@ _CDA-C @ CDA.AUTH AAUTH.POLL-INTERVAL-MS @ +
        _CDA-C @ CDA.NEXT-POLL-MS !
        CDA-SUB-IDLE _CDA-C @ CDA.SUBSTATE !
        AAUTH-S-PENDING EXIT
    THEN
    _CDA-C @ CDA.EXCHANGE HBUF.HTTP-CODE @ 200 <> IF
        AAUTH-S-PROTOCOL S" Device authorization was rejected" _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-C @ CDA.RESPONSE _CDA-C @ CDA.EXCHANGE HBUF.BODY-U @
    2DUP S" authorization_code" _CDA-STRING-FIELD 0= IF
        2DROP 2DROP AAUTH-S-PROTOCOL S" Missing authorization code"
        _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-AUTHORIZATION-U ! _CDA-AUTHORIZATION-A !
    S" code_verifier" _CDA-STRING-FIELD 0= IF
        2DROP AAUTH-S-PROTOCOL S" Missing PKCE verifier" _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-AUTHORIZATION-A @ _CDA-AUTHORIZATION-U @
    2SWAP _CDA-C @ _CDA-START-TOKEN-EXCHANGE
    DUP AAUTH-S-PENDING <> IF
        S" Could not exchange device authorization" _CDA-C @ _CDA-FAIL
    THEN ;

: _CDA-HANDLE-TOKEN-EXCHANGE  ( context -- status )
    DUP _CDA-C ! CDA.EXCHANGE HBUF.HTTP-CODE @ 200 <> IF
        AAUTH-S-PROTOCOL S" Token exchange was rejected" _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-C @ CDA.RESPONSE _CDA-C @ CDA.EXCHANGE HBUF.BODY-U @
    2DUP S" id_token" _CDA-STRING-FIELD 0= IF
        2DROP 2DROP AAUTH-S-PROTOCOL S" Missing identity token" _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-ID-U ! _CDA-ID-A !
    2DUP S" access_token" _CDA-STRING-FIELD 0= IF
        2DROP 2DROP AAUTH-S-PROTOCOL S" Missing access token" _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-ACCESS-U ! _CDA-ACCESS-A !
    S" refresh_token" _CDA-STRING-FIELD 0= IF
        2DROP AAUTH-S-PROTOCOL S" Missing refresh token" _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-REFRESH-U ! _CDA-REFRESH-A !
    _CDA-ACCESS-A @ _CDA-ACCESS-U @ _CDA-C @ _CDA-ACCESS-EXPIRY
    _CDA-EXP-MS !
    _CDA-ID-A @ _CDA-ID-U @ _CDA-ACCESS-A @ _CDA-ACCESS-U @
    _CDA-REFRESH-A @ _CDA-REFRESH-U @ _CDA-EXP-MS @ _CDA-C @ CDA.TOKENS
    O2TOK-SET ?DUP IF
        DROP AAUTH-S-CAPACITY S" OAuth tokens exceed native bounds"
        _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-ID-A @ _CDA-ID-U @ _CDA-C @ _CDA-CLAIMS-METADATA ?DUP IF
        S" Identity token lacks Codex account claims" _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-C @ _CDA-WORK-FREE
    _CDA-C @ CDA.AUTH AAUTH.USER-CODE CV-FREE
    _CDA-C @ CDA.AUTH AAUTH.VERIFY-URI CV-FREE
    0 _CDA-C @ CDA.AUTH AAUTH.EXPIRES-MS !
    CDA-SUB-IDLE _CDA-C @ CDA.SUBSTATE !
    AAUTH-S-OK AAUTH-STATE-READY _CDA-C @ _CDA-AUTH-TOUCH ;

: _CDA-HANDLE-REFRESH  ( context -- status )
    DUP _CDA-C ! CDA.EXCHANGE HBUF.HTTP-CODE @ 200 <> IF
        _CDA-C @ CDA.TOKENS O2TOK-CLEAR
        AAUTH-S-PROTOCOL S" Session refresh was rejected" _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-C @ CDA.RESPONSE _CDA-C @ CDA.EXCHANGE HBUF.BODY-U @
    2DUP S" id_token" _CDA-STRING-FIELD IF
        _CDA-ID-U ! _CDA-ID-A !
    ELSE
        2DROP 0 _CDA-ID-A ! 0 _CDA-ID-U !
    THEN
    2DUP S" access_token" _CDA-STRING-FIELD IF
        _CDA-ACCESS-U ! _CDA-ACCESS-A !
    ELSE
        2DROP 0 _CDA-ACCESS-A ! 0 _CDA-ACCESS-U !
    THEN
    S" refresh_token" _CDA-STRING-FIELD IF
        _CDA-REFRESH-U ! _CDA-REFRESH-A !
    ELSE
        2DROP 0 _CDA-REFRESH-A ! 0 _CDA-REFRESH-U !
    THEN
    _CDA-ACCESS-U @ IF
        _CDA-ACCESS-A @ _CDA-ACCESS-U @ _CDA-C @ _CDA-ACCESS-EXPIRY
    ELSE
        0
    THEN _CDA-EXP-MS !
    _CDA-ID-A @ _CDA-ID-U @ _CDA-ACCESS-A @ _CDA-ACCESS-U @
    _CDA-REFRESH-A @ _CDA-REFRESH-U @ _CDA-EXP-MS @ _CDA-C @ CDA.TOKENS
    O2TOK-UPDATE ?DUP IF
        DROP AAUTH-S-CAPACITY S" Refreshed tokens exceed native bounds"
        _CDA-C @ _CDA-FAIL EXIT
    THEN
    _CDA-ID-U @ IF
        _CDA-ID-A @ _CDA-ID-U @ _CDA-C @ _CDA-CLAIMS-METADATA ?DUP IF
            S" Refreshed identity lacks Codex account claims"
            _CDA-C @ _CDA-FAIL EXIT
        THEN
    THEN
    _CDA-C @ _CDA-WORK-FREE
    CDA-SUB-IDLE _CDA-C @ CDA.SUBSTATE !
    AAUTH-S-OK AAUTH-STATE-READY _CDA-C @ _CDA-AUTH-TOUCH ;

: _CDA-POLL  ( context -- status )
    DUP _CDA-POLL-C ! CDA.AUTH DUP AAUTH.STATE @ AAUTH-STATE-PENDING = IF
        MS@ OVER AAUTH.EXPIRES-MS @ >= IF
            DROP AAUTH-S-EXPIRED S" Device login expired" _CDA-POLL-C @
            _CDA-FAIL EXIT
        THEN
        DROP
        _CDA-POLL-C @ CDA.SUBSTATE @ CDA-SUB-IDLE =
        MS@ _CDA-POLL-C @ CDA.NEXT-POLL-MS @ >= AND IF
            CDA-SUB-TOKEN-POLL _CDA-POLL-C @ CDA.SUBSTATE !
            _CDA-POLL-C @ _CDA-BUILD-TOKEN-POLL DUP AAUTH-S-PENDING <> IF
                S" Could not poll device authorization" _CDA-POLL-C @
                _CDA-FAIL EXIT
            THEN DROP
        THEN
    ELSE
        DROP
    THEN
    _CDA-POLL-C @ CDA.SUBSTATE @ CDA-SUB-IDLE = IF AAUTH-S-PENDING EXIT THEN
    _CDA-POLL-C @ CDA.EXCHANGE HBUF-POLL DUP HBUF-S-PENDING = IF
        DROP AAUTH-S-PENDING EXIT
    THEN
    DUP HBUF-S-OK <> IF
        DROP AAUTH-S-TRANSPORT S" Authentication transport failed"
        _CDA-POLL-C @ _CDA-FAIL EXIT
    THEN DROP
    _CDA-POLL-C @ CDA.SUBSTATE @ CASE
        CDA-SUB-USER-CODE OF _CDA-POLL-C @ _CDA-HANDLE-USER-CODE ENDOF
        CDA-SUB-TOKEN-POLL OF _CDA-POLL-C @ _CDA-HANDLE-TOKEN-POLL ENDOF
        CDA-SUB-TOKEN-EXCHANGE OF
            _CDA-POLL-C @ _CDA-HANDLE-TOKEN-EXCHANGE
        ENDOF
        CDA-SUB-REFRESH OF _CDA-POLL-C @ _CDA-HANDLE-REFRESH ENDOF
        AAUTH-S-PROTOCOL
    ENDCASE ;

: _CDA-CANCEL  ( context -- status )
    DUP _CDA-C ! _CDA-TRANSIENT-CLEAR
    _CDA-C @ CDA.AUTH AAUTH.USER-CODE CV-FREE
    _CDA-C @ CDA.AUTH AAUTH.VERIFY-URI CV-FREE
    0 _CDA-C @ CDA.AUTH AAUTH.EXPIRES-MS !
    AAUTH-S-CANCELLED AAUTH-STATE-SIGNED-OUT _CDA-C @ _CDA-AUTH-TOUCH ;

: _CDA-LOGOUT  ( context -- status )
    DUP _CDA-C ! _CDA-TRANSIENT-CLEAR
    _CDA-C @ CDA.TOKENS O2TOK-CLEAR
    _CDA-C @ CDA.AUTH AAUTH-METADATA-CLEAR
    AAUTH-S-OK AAUTH-STATE-SIGNED-OUT _CDA-C @ _CDA-AUTH-TOUCH ;

VARIABLE _CDA-WITH-CB
VARIABLE _CDA-WITH-CONTEXT
VARIABLE _CDA-WITH-C

: _CDA-WITH-ACCESS  ( callback callback-context context -- status )
    _CDA-WITH-C ! _CDA-WITH-CONTEXT ! _CDA-WITH-CB !
    _CDA-WITH-CB @ _CDA-WITH-CONTEXT @ _CDA-WITH-C @ CDA.TOKENS
    O2TOK-WITH-ACCESS DUP O2TOK-S-OK = IF DROP AAUTH-S-OK ELSE
        DROP AAUTH-S-INVALID
    THEN ;

VARIABLE _CDA-REFRESH-C

: _CDA-REFRESH-BODY  ( refresh-a refresh-u context -- status )
    _CDA-REFRESH-C ! _CDA-U ! _CDA-A !
    JSON-BUILD-RESET _CDA-REFRESH-C @ CDA.REQUEST-BODY
    CDA-REQUEST-BODY-CAPACITY JSON-SET-OUTPUT
    JSON-{
    S" client_id" JSON-KEY: CODEX-AUTH-CLIENT-ID JSON-ESTR
    S" grant_type" S" refresh_token" JSON-KV-ESTR
    S" refresh_token" JSON-KEY: _CDA-A @ _CDA-U @ JSON-ESTR
    JSON-}
    JSON-OUTPUT-OK? 0= IF AAUTH-S-CAPACITY EXIT THEN
    JSON-OUTPUT-RESULT NIP _CDA-REFRESH-C @ CDA.REQUEST-BODY-U !
    AAUTH-S-OK ;

: _CDA-REFRESH  ( context -- status )
    DUP _CDA-C ! CDA.AUTH AAUTH.STATE @ AAUTH-STATE-READY <> IF
        AAUTH-S-BUSY EXIT
    THEN
    _CDA-C @ _CDA-WORK-NEW ?DUP IF EXIT THEN
    ['] _CDA-REFRESH-BODY _CDA-C @ _CDA-C @ CDA.TOKENS
    O2TOK-WITH-REFRESH ?DUP IF
        DROP _CDA-C @ _CDA-WORK-FREE AAUTH-S-INVALID EXIT
    THEN
    CDA-SUB-REFRESH _CDA-C @ CDA.SUBSTATE !
    CODEX-AUTH-TOKEN-PATH S" application/json" _CDA-C @
    _CDA-START-REQUEST DUP AAUTH-S-PENDING <> IF
        _CDA-C @ _CDA-WORK-FREE EXIT
    THEN
    DROP AAUTH-S-PENDING AAUTH-STATE-REFRESHING _CDA-C @ _CDA-AUTH-TOUCH ;

: _CDA-DISPOSE  ( context -- )
    DUP _CDA-WORK-FREE
    DUP CDA.TOKENS O2TOK-CLEAR
    DROP ;

VARIABLE _CDAN-PORT
VARIABLE _CDAN-C

: CODEX-DEVICE-AUTH-INIT  ( port context -- status )
    _CDAN-C ! _CDAN-PORT !
    _CDAN-C @ 0= _CDAN-PORT @ 0= OR IF AAUTH-S-INVALID EXIT THEN
    _CDAN-C @ CODEX-DEVICE-AUTH-SIZE 0 FILL
    _CDAN-C @ CDA.AUTH AAUTH-INIT
    _CDAN-C @ CDA.TOKENS O2TOK-INIT
    _CDAN-PORT @ _CDAN-C @ CDA.PORT !
    AAUTH-M-DEVICE _CDAN-C @ CDA.AUTH AAUTH.METHODS !
    AAUTH-STATE-SIGNED-OUT _CDAN-C @ CDA.AUTH AAUTH.STATE !
    _CDAN-C @ _CDAN-C @ CDA.AUTH AAUTH.CONTEXT !
    ['] _CDA-BEGIN _CDAN-C @ CDA.AUTH AAUTH.BEGIN-XT !
    ['] _CDA-POLL _CDAN-C @ CDA.AUTH AAUTH.POLL-XT !
    ['] _CDA-CANCEL _CDAN-C @ CDA.AUTH AAUTH.CANCEL-XT !
    ['] _CDA-LOGOUT _CDAN-C @ CDA.AUTH AAUTH.LOGOUT-XT !
    ['] _CDA-WITH-ACCESS _CDAN-C @ CDA.AUTH AAUTH.WITH-ACCESS-XT !
    ['] _CDA-REFRESH _CDAN-C @ CDA.AUTH AAUTH.REFRESH-XT !
    ['] _CDA-DISPOSE _CDAN-C @ CDA.AUTH AAUTH.DISPOSE-XT !
    AAUTH-S-OK ;
