\ =====================================================================
\  kdos-tls.f - KDOS authenticated TLS transport for net/io-port
\ =====================================================================
\  This binds Akashic's cooperative byte-stream
\  contract and KDOS DNS/TCP/TLS services. It owns no HTTP, credential,
\  provider, Agent, Desk, TUI, emulator, or host-bridge behavior.
\ =====================================================================

PROVIDED akashic-kdos-tls

REQUIRE ../io-port.f

0 CONSTANT KDOSTLS-STATE-CLOSED
1 CONSTANT KDOSTLS-STATE-OPENING
2 CONSTANT KDOSTLS-STATE-OPEN
3 CONSTANT KDOSTLS-STATE-ERROR

0 CONSTANT KDOSTLS-E-OK
1 CONSTANT KDOSTLS-E-INVALID
2 CONSTANT KDOSTLS-E-BUSY
3 CONSTANT KDOSTLS-E-NO-TRUST
4 CONSTANT KDOSTLS-E-DNS
5 CONSTANT KDOSTLS-E-CONNECT
6 CONSTANT KDOSTLS-E-AUTH
7 CONSTANT KDOSTLS-E-IO
8 CONSTANT KDOSTLS-E-FAULT

0 CONSTANT KDOSTLS-LINK-OPEN
1 CONSTANT KDOSTLS-LINK-CLOSED
2 CONSTANT KDOSTLS-LINK-FAILED

64 CONSTANT KDOSTLS-HOST-CAPACITY

  0 CONSTANT _KDOSTLS-PORT
_KDOSTLS-PORT NET-IO-PORT-SIZE + CONSTANT _KDOSTLS-STATE
_KDOSTLS-STATE 8 + CONSTANT _KDOSTLS-HOST-U
_KDOSTLS-HOST-U 8 + CONSTANT _KDOSTLS-REMOTE-PORT
_KDOSTLS-REMOTE-PORT 8 + CONSTANT _KDOSTLS-CONTEXT
_KDOSTLS-CONTEXT 8 + CONSTANT _KDOSTLS-LAST-ERROR
_KDOSTLS-LAST-ERROR 8 + CONSTANT _KDOSTLS-NATIVE-ERROR
_KDOSTLS-NATIVE-ERROR 8 + CONSTANT _KDOSTLS-LOCAL-PORT
_KDOSTLS-LOCAL-PORT 8 + CONSTANT _KDOSTLS-FLAGS
_KDOSTLS-FLAGS 8 + CONSTANT _KDOSTLS-DNS-XT
_KDOSTLS-DNS-XT 8 + CONSTANT _KDOSTLS-CONNECT-XT
_KDOSTLS-CONNECT-XT 8 + CONSTANT _KDOSTLS-SEND-XT
_KDOSTLS-SEND-XT 8 + CONSTANT _KDOSTLS-RECV-XT
_KDOSTLS-RECV-XT 8 + CONSTANT _KDOSTLS-CLOSE-XT
_KDOSTLS-CLOSE-XT 8 + CONSTANT _KDOSTLS-POLL-XT
_KDOSTLS-POLL-XT 8 + CONSTANT _KDOSTLS-STATUS-XT
_KDOSTLS-STATUS-XT 8 + CONSTANT _KDOSTLS-HOST-BUF
_KDOSTLS-HOST-BUF KDOSTLS-HOST-CAPACITY + CONSTANT KDOSTLS-SIZE

: KDOSTLS.PORT        ( adapter -- port ) _KDOSTLS-PORT + ;
: KDOSTLS.STATE       ( adapter -- a ) _KDOSTLS-STATE + ;
: KDOSTLS.HOST-U      ( adapter -- a ) _KDOSTLS-HOST-U + ;
: KDOSTLS.REMOTE-PORT ( adapter -- a ) _KDOSTLS-REMOTE-PORT + ;
: KDOSTLS.CONTEXT     ( adapter -- a ) _KDOSTLS-CONTEXT + ;
: KDOSTLS.LAST-ERROR  ( adapter -- a ) _KDOSTLS-LAST-ERROR + ;
: KDOSTLS.NATIVE-ERROR ( adapter -- a ) _KDOSTLS-NATIVE-ERROR + ;
: KDOSTLS.LOCAL-PORT  ( adapter -- a ) _KDOSTLS-LOCAL-PORT + ;
: KDOSTLS.FLAGS       ( adapter -- a ) _KDOSTLS-FLAGS + ;
: KDOSTLS.DNS-XT      ( adapter -- a ) _KDOSTLS-DNS-XT + ;
: KDOSTLS.CONNECT-XT  ( adapter -- a ) _KDOSTLS-CONNECT-XT + ;
: KDOSTLS.SEND-XT     ( adapter -- a ) _KDOSTLS-SEND-XT + ;
: KDOSTLS.RECV-XT     ( adapter -- a ) _KDOSTLS-RECV-XT + ;
: KDOSTLS.CLOSE-XT    ( adapter -- a ) _KDOSTLS-CLOSE-XT + ;
: KDOSTLS.POLL-XT     ( adapter -- a ) _KDOSTLS-POLL-XT + ;
: KDOSTLS.STATUS-XT   ( adapter -- a ) _KDOSTLS-STATUS-XT + ;
: KDOSTLS.HOST-BUF    ( adapter -- a ) _KDOSTLS-HOST-BUF + ;

: KDOSTLS-HOST  ( adapter -- addr len )
    DUP KDOSTLS.HOST-BUF SWAP KDOSTLS.HOST-U @ ;

: _KDOSTLS-DNS-DEFAULT  ( host-a host-u adapter -- ip | 0 )
    DROP DNS-RESOLVE ;

: _KDOSTLS-CONNECT-DEFAULT  ( ip remote-port local-port adapter -- ctx | 0 )
    DROP TLS-ALPN-HTTP11 TLS-CONNECT-ALPN ;

: _KDOSTLS-SEND-DEFAULT  ( ctx buffer length adapter -- count )
    DROP TLS-SEND ;

: _KDOSTLS-RECV-DEFAULT  ( ctx buffer capacity adapter -- count | -1 )
    DROP TLS-RECV ;

: _KDOSTLS-CLOSE-DEFAULT  ( ctx adapter -- )
    DROP TLS-CLOSE ;

\ Cooperative port polling must return before the caller's send/receive step.
\ KDOS's explicitly blocking TCP/TLS wait loops own their NET-IDLE calls.
: _KDOSTLS-POLL-DEFAULT  ( adapter -- )
    DROP TCP-POLL ;

: _KDOSTLS-STATUS-DEFAULT  ( ctx adapter -- link-status )
    DROP
    DUP 0= IF DROP KDOSTLS-LINK-FAILED EXIT THEN
    DUP TLS-CTX.ERROR @ TLS-E-OK <> IF DROP KDOSTLS-LINK-FAILED EXIT THEN
    DUP TLS-CTX.TCB @ DUP 0= IF 2DROP KDOSTLS-LINK-CLOSED EXIT THEN
    TCB.STATE @ TCPS-ESTABLISHED <> IF
        DROP KDOSTLS-LINK-CLOSED EXIT
    THEN
    DUP TLS-CTX.STATE @ TLSS-ESTABLISHED =
    OVER TLS-CTX.PEER-AUTH @ 1 = AND IF
        DROP KDOSTLS-LINK-OPEN EXIT
    THEN
    TLS-CTX.STATE @ DUP TLSS-CLOSING = SWAP TLSS-NONE = OR IF
        KDOSTLS-LINK-CLOSED
    ELSE
        KDOSTLS-LINK-FAILED
    THEN ;

VARIABLE _KDOSTLS-OWNER
VARIABLE _KDOSTLS-NEXT-PORT
0 _KDOSTLS-OWNER !
RANDOM32 16383 AND 49152 + _KDOSTLS-NEXT-PORT !

: _KDOSTLS-NEXT-LOCAL-PORT  ( -- port )
    _KDOSTLS-NEXT-PORT @
    DUP 1+ DUP 65535 > IF DROP 49152 THEN _KDOSTLS-NEXT-PORT ! ;

: _KDOSTLS-MARK-ERROR  ( error adapter -- )
    >R R@ KDOSTLS.LAST-ERROR ! KDOSTLS-STATE-ERROR R> KDOSTLS.STATE ! ;

: KDOSTLS-LINK@  ( adapter -- link-status )
    DUP KDOSTLS.CONTEXT @ SWAP DUP KDOSTLS.STATUS-XT @ EXECUTE ;

VARIABLE _KDTC-A

: _KDOSTLS-CLOSE-INNER  ( -- )
    _KDTC-A @ KDOSTLS.CONTEXT @ ?DUP IF
        _KDTC-A @ _KDTC-A @ KDOSTLS.CLOSE-XT @ EXECUTE
    THEN ;

: _KDOSTLS-RELEASE  ( adapter -- )
    DUP _KDTC-A !
    ['] _KDOSTLS-CLOSE-INNER CATCH DROP
    0 OVER KDOSTLS.CONTEXT !
    0 OVER KDOSTLS.LOCAL-PORT !
    KDOSTLS-STATE-CLOSED OVER KDOSTLS.STATE !
    _KDOSTLS-OWNER @ OVER = IF 0 _KDOSTLS-OWNER ! THEN
    DROP ;

VARIABLE _KDTO-A
VARIABLE _KDTO-IP
VARIABLE _KDTO-CTX

: _KDOSTLS-OPEN-FAIL  ( error -- nio-status )
    _KDTO-A @ _KDOSTLS-RELEASE
    _KDTO-A @ _KDOSTLS-MARK-ERROR
    NIO-S-FAILED ;

: _KDOSTLS-OPEN-INNER  ( -- nio-status )
    _KDTO-A @ KDOSTLS.STATE @ KDOSTLS-STATE-OPEN = IF NIO-S-OK EXIT THEN
    _KDTO-A @ KDOSTLS.HOST-U @ 0= IF KDOSTLS-E-INVALID _KDOSTLS-OPEN-FAIL EXIT THEN
    _KDOSTLS-OWNER @ ?DUP IF
        _KDTO-A @ <> IF KDOSTLS-E-BUSY _KDOSTLS-OPEN-FAIL EXIT THEN
    THEN
    TLS-TRUST-COUNT @ 0= IF KDOSTLS-E-NO-TRUST _KDOSTLS-OPEN-FAIL EXIT THEN
    _KDTO-A @ _KDOSTLS-OWNER !
    KDOSTLS-STATE-OPENING _KDTO-A @ KDOSTLS.STATE !
    KDOSTLS-E-OK _KDTO-A @ KDOSTLS.LAST-ERROR !
    TLS-CONNECT-E-OK _KDTO-A @ KDOSTLS.NATIVE-ERROR !
    TLS-CONNECT-E-OK TLS-CONNECT-LAST-ERROR !

    TLS-SNI-HOST KDOSTLS-HOST-CAPACITY 0 FILL
    _KDTO-A @ KDOSTLS.HOST-U @ DUP TLS-SNI-LEN !
    _KDTO-A @ KDOSTLS.HOST-BUF TLS-SNI-HOST ROT CMOVE

    _KDTO-A @ KDOSTLS-HOST _KDTO-A @
    _KDTO-A @ KDOSTLS.DNS-XT @ EXECUTE DUP _KDTO-IP !
    0= IF KDOSTLS-E-DNS _KDOSTLS-OPEN-FAIL EXIT THEN

    _KDOSTLS-NEXT-LOCAL-PORT DUP _KDTO-A @ KDOSTLS.LOCAL-PORT !
    _KDTO-IP @ _KDTO-A @ KDOSTLS.REMOTE-PORT @ ROT _KDTO-A @
    _KDTO-A @ KDOSTLS.CONNECT-XT @ EXECUTE DUP _KDTO-CTX !
    TLS-CONNECT-LAST-ERROR @ _KDTO-A @ KDOSTLS.NATIVE-ERROR !
    0= IF KDOSTLS-E-CONNECT _KDOSTLS-OPEN-FAIL EXIT THEN
    _KDTO-CTX @ _KDTO-A @ KDOSTLS.CONTEXT !
    _KDTO-A @ KDOSTLS-LINK@ KDOSTLS-LINK-OPEN <> IF
        KDOSTLS-E-AUTH _KDOSTLS-OPEN-FAIL EXIT
    THEN
    KDOSTLS-STATE-OPEN _KDTO-A @ KDOSTLS.STATE !
    NIO-S-OK ;

: _KDOSTLS-NIO-OPEN  ( adapter -- nio-status )
    _KDTO-A !
    ['] _KDOSTLS-OPEN-INNER CATCH ?DUP IF
        DROP _KDTO-A @ _KDOSTLS-RELEASE
        KDOSTLS-E-FAULT _KDTO-A @ _KDOSTLS-MARK-ERROR
        NIO-S-FAILED
    THEN ;

VARIABLE _KDTS-A
VARIABLE _KDTS-B
VARIABLE _KDTS-U
VARIABLE _KDTS-N

: _KDOSTLS-NIO-SEND  ( buffer length adapter -- count nio-status )
    _KDTS-A ! _KDTS-U ! _KDTS-B !
    _KDTS-A @ KDOSTLS.STATE @ KDOSTLS-STATE-OPEN <> IF
        0 NIO-S-FAILED EXIT
    THEN
    _KDTS-U @ 0< _KDTS-B @ 0= _KDTS-U @ 0> AND OR IF
        KDOSTLS-E-INVALID _KDTS-A @ _KDOSTLS-MARK-ERROR
        0 NIO-S-FAILED EXIT
    THEN
    _KDTS-U @ 0= IF 0 NIO-S-OK EXIT THEN
    _KDTS-A @ KDOSTLS.CONTEXT @ _KDTS-B @ _KDTS-U @ _KDTS-A @
    _KDTS-A @ KDOSTLS.SEND-XT @ EXECUTE DUP _KDTS-N !
    0< _KDTS-N @ _KDTS-U @ > OR IF
        KDOSTLS-E-IO _KDTS-A @ _KDOSTLS-MARK-ERROR
        0 NIO-S-FAILED EXIT
    THEN
    _KDTS-N @ 0= IF
        _KDTS-A @ KDOSTLS-LINK@ KDOSTLS-LINK-OPEN <> IF
            KDOSTLS-E-IO _KDTS-A @ _KDOSTLS-MARK-ERROR
            0 NIO-S-FAILED EXIT
        THEN
    THEN
    _KDTS-N @ NIO-S-OK ;

VARIABLE _KDTR-A
VARIABLE _KDTR-B
VARIABLE _KDTR-U
VARIABLE _KDTR-N
VARIABLE _KDTR-LINK

: _KDOSTLS-NIO-RECV  ( buffer capacity adapter -- count nio-status )
    _KDTR-A ! _KDTR-U ! _KDTR-B !
    _KDTR-A @ KDOSTLS.STATE @ KDOSTLS-STATE-OPEN <> IF
        0 NIO-S-FAILED EXIT
    THEN
    _KDTR-U @ 0> 0= _KDTR-B @ 0= OR IF
        KDOSTLS-E-INVALID _KDTR-A @ _KDOSTLS-MARK-ERROR
        0 NIO-S-FAILED EXIT
    THEN
    _KDTR-A @ KDOSTLS.CONTEXT @ _KDTR-B @ _KDTR-U @ _KDTR-A @
    _KDTR-A @ KDOSTLS.RECV-XT @ EXECUTE DUP _KDTR-N !
    0< IF
        KDOSTLS-E-IO _KDTR-A @ _KDOSTLS-MARK-ERROR
        0 NIO-S-FAILED EXIT
    THEN
    _KDTR-N @ _KDTR-U @ > IF
        KDOSTLS-E-IO _KDTR-A @ _KDOSTLS-MARK-ERROR
        0 NIO-S-FAILED EXIT
    THEN
    _KDTR-N @ IF _KDTR-N @ NIO-S-OK EXIT THEN
    _KDTR-A @ KDOSTLS-LINK@ DUP _KDTR-LINK !
    KDOSTLS-LINK-OPEN = IF 0 NIO-S-OK EXIT THEN
    _KDTR-LINK @ KDOSTLS-LINK-CLOSED = IF
        KDOSTLS-STATE-CLOSED _KDTR-A @ KDOSTLS.STATE !
        0 NIO-S-EOF EXIT
    THEN
    KDOSTLS-E-IO _KDTR-A @ _KDOSTLS-MARK-ERROR
    0 NIO-S-FAILED ;

: _KDOSTLS-NIO-POLL  ( adapter -- )
    DUP KDOSTLS.POLL-XT @ EXECUTE ;

: _KDOSTLS-NIO-CLOSE  ( adapter -- )
    _KDOSTLS-RELEASE ;

: KDOSTLS-INIT  ( adapter -- )
    DUP KDOSTLS-SIZE 0 FILL
    DUP KDOSTLS.PORT NIO-INIT
    DUP OVER KDOSTLS.PORT NIO.CONTEXT !
    ['] _KDOSTLS-NIO-OPEN OVER KDOSTLS.PORT NIO.OPEN-XT !
    ['] _KDOSTLS-NIO-SEND OVER KDOSTLS.PORT NIO.SEND-XT !
    ['] _KDOSTLS-NIO-RECV OVER KDOSTLS.PORT NIO.RECV-XT !
    ['] _KDOSTLS-NIO-POLL OVER KDOSTLS.PORT NIO.POLL-XT !
    ['] _KDOSTLS-NIO-CLOSE OVER KDOSTLS.PORT NIO.CLOSE-XT !
    ['] _KDOSTLS-DNS-DEFAULT OVER KDOSTLS.DNS-XT !
    ['] _KDOSTLS-CONNECT-DEFAULT OVER KDOSTLS.CONNECT-XT !
    ['] _KDOSTLS-SEND-DEFAULT OVER KDOSTLS.SEND-XT !
    ['] _KDOSTLS-RECV-DEFAULT OVER KDOSTLS.RECV-XT !
    ['] _KDOSTLS-CLOSE-DEFAULT OVER KDOSTLS.CLOSE-XT !
    ['] _KDOSTLS-POLL-DEFAULT OVER KDOSTLS.POLL-XT !
    ['] _KDOSTLS-STATUS-DEFAULT SWAP KDOSTLS.STATUS-XT ! ;

VARIABLE _KDTCFG-A
VARIABLE _KDTCFG-U
VARIABLE _KDTCFG-PORT
VARIABLE _KDTCFG-T

: KDOSTLS-CONFIGURE  ( host-a host-u remote-port adapter -- status )
    _KDTCFG-T ! _KDTCFG-PORT ! _KDTCFG-U ! _KDTCFG-A !
    _KDTCFG-T @ KDOSTLS.STATE @ KDOSTLS-STATE-CLOSED <> IF
        KDOSTLS-E-BUSY EXIT
    THEN
    _KDTCFG-U @ 0= _KDTCFG-U @ KDOSTLS-HOST-CAPACITY > OR
    _KDTCFG-A @ 0= OR IF KDOSTLS-E-INVALID EXIT THEN
    _KDTCFG-A @ _KDTCFG-U @ FALSE DNS-NAME-VALID? 0= IF
        KDOSTLS-E-INVALID EXIT
    THEN
    _KDTCFG-PORT @ 1 < _KDTCFG-PORT @ 65535 > OR IF
        KDOSTLS-E-INVALID EXIT
    THEN
    _KDTCFG-T @ KDOSTLS.HOST-BUF KDOSTLS-HOST-CAPACITY 0 FILL
    _KDTCFG-A @ _KDTCFG-T @ KDOSTLS.HOST-BUF _KDTCFG-U @ CMOVE
    _KDTCFG-U @ _KDTCFG-T @ KDOSTLS.HOST-U !
    _KDTCFG-PORT @ _KDTCFG-T @ KDOSTLS.REMOTE-PORT !
    KDOSTLS-E-OK _KDTCFG-T @ KDOSTLS.LAST-ERROR !
    KDOSTLS-E-OK ;

VARIABLE _KDTNEW-T
VARIABLE _KDTNEW-STATUS

: KDOSTLS-NEW  ( host-a host-u remote-port -- adapter status )
    >R KDOSTLS-SIZE ALLOCATE
    DUP IF >R DROP 2DROP R> DROP R> DROP 0 KDOSTLS-E-INVALID EXIT THEN
    DROP DUP _KDTNEW-T ! KDOSTLS-INIT
    R> _KDTNEW-T @ KDOSTLS-CONFIGURE DUP _KDTNEW-STATUS !
    IF _KDTNEW-T @ FREE 0 _KDTNEW-STATUS @ EXIT THEN
    _KDTNEW-T @ KDOSTLS-E-OK ;

: KDOSTLS-FREE  ( adapter -- )
    DUP 0= IF DROP EXIT THEN
    DUP KDOSTLS.PORT NIO-CLOSE
    DUP KDOSTLS-SIZE 0 FILL
    FREE ;

\ KDOS TLS uses shared record, handshake, SNI, and trust-store scratch. The
\ owner gate deliberately permits one active KDOS TLS adapter at a time.
\ Multiple Agent runs remain cooperatively schedulable around that boundary;
\ true concurrent TLS requires a future descriptor-owned KDOS record layer.
