\ =====================================================================
\  kdos-tls-inbound.f - Persistent XIO-driven KDOS TLS listener owner
\ =====================================================================
\  KDOS owns the TLS server engine and every lower transport authority.
\  This module owns only the Akashic composition of one persistent secure
\  listener: one caller-pumped XIO accept request, its exact lower context,
\  and a borrowed shared KDOS TLS port used to stage authenticated success.
\
\  The listener owner never publishes a plaintext accepted child and never
\  retains an established connection after returning its already-open NIO
\  port.  KDOSNET is acquired for exactly one lower handshake or raw-context
\  cleanup operation.  Established-port cleanup and adoption use the shared
\  port's own per-call KDOSNET boundary.
\
\  Public lifecycle:
\    KDOSTLSL-INIT
\      ( xio-service listener-sd listener-h1 listener-generation
\        timeout-ms early-budget owner -- status )
\    KDOSTLSL-ACCEPT  ( fresh-shared-port owner -- status )
\    KDOSTLSL-STEP    ( owner -- nio-port|0 status )
\    KDOSTLSL-CANCEL  ( owner -- status )
\    KDOSTLSL-FINI    ( owner -- status )
\
\  STEP returning PENDING means the current request still owns work.  RETRY
\  means an empty backlog or pre-claim contention completed the request and
\  the owner is ready for another ACCEPT.  The shared port passed to ACCEPT
\  must already have been initialized and be in RESET.
\ =====================================================================

PROVIDED akashic-kdos-tls-inbound

REQUIRE ../external-io.f
REQUIRE kdos-tls-port.f
REQUIRE ../../utils/memory-span.f

0 CONSTANT KDOSTLSL-S-OK
1 CONSTANT KDOSTLSL-S-INVALID
2 CONSTANT KDOSTLSL-S-BUSY
3 CONSTANT KDOSTLSL-S-STATE
4 CONSTANT KDOSTLSL-S-NOT-OWNER
5 CONSTANT KDOSTLSL-S-PENDING
6 CONSTANT KDOSTLSL-S-LOWER
7 CONSTANT KDOSTLSL-S-PLATFORM
8 CONSTANT KDOSTLSL-S-CANCELLED
9 CONSTANT KDOSTLSL-S-TIMED-OUT
10 CONSTANT KDOSTLSL-S-RETRY

-4701 CONSTANT KDOSTLSL-E-CONTENTION
-4702 CONSTANT KDOSTLSL-E-PLATFORM
-4703 CONSTANT KDOSTLSL-E-HANDSHAKE-ALERT
-4704 CONSTANT KDOSTLSL-E-STATE
-4705 CONSTANT KDOSTLSL-E-CLEANUP

0x4B44544C49535431 CONSTANT _KDOSTLSL-MAGIC-VALUE  \ "KDTLIST1"
0x7FFFFFFFFFFFFFFF CONSTANT _KDOSTLSL-CELL-MAX

\ ---------------------------------------------------------------------
\ Persistent listener/accept owner
\ ---------------------------------------------------------------------

  0 CONSTANT _KDOSTLSL-MAGIC
  8 CONSTANT _KDOSTLSL-XIO-SERVICE
 16 CONSTANT _KDOSTLSL-LISTENER-SD
 24 CONSTANT _KDOSTLSL-LISTENER-H1
 32 CONSTANT _KDOSTLSL-LISTENER-GEN
 40 CONSTANT _KDOSTLSL-TIMEOUT-MS
 48 CONSTANT _KDOSTLSL-EARLY-BUDGET
 56 CONSTANT _KDOSTLSL-OWNER-GEN
 64 CONSTANT _KDOSTLSL-REQUEST-GEN
 72 CONSTANT _KDOSTLSL-CTX
 80 CONSTANT _KDOSTLSL-CTX-GEN
 88 CONSTANT _KDOSTLSL-PHASE
 96 CONSTANT _KDOSTLSL-BORROWED-PORT
104 CONSTANT _KDOSTLSL-TERMINAL
112 CONSTANT _KDOSTLSL-STAGING-SOCKET
120 CONSTANT _KDOSTLSL-XIO-OP
_KDOSTLSL-XIO-OP XIO-OP-SIZE + CONSTANT KDOSTLSL-SIZE

0 CONSTANT _KDOSTLSL-PHASE-IDLE
1 CONSTANT _KDOSTLSL-PHASE-LISTENER-POLL
2 CONSTANT _KDOSTLSL-PHASE-CLAIM
3 CONSTANT _KDOSTLSL-PHASE-CLIENT-HELLO
4 CONSTANT _KDOSTLSL-PHASE-CLIENT-HELLO-POLL
5 CONSTANT _KDOSTLSL-PHASE-PREPARE-HELLO
6 CONSTANT _KDOSTLSL-PHASE-PREPARE-FLIGHT
7 CONSTANT _KDOSTLSL-PHASE-FLIGHT
8 CONSTANT _KDOSTLSL-PHASE-FLIGHT-POLL
9 CONSTANT _KDOSTLSL-PHASE-CLIENT-FLIGHT-BEGIN
10 CONSTANT _KDOSTLSL-PHASE-CLIENT-FLIGHT
11 CONSTANT _KDOSTLSL-PHASE-CLIENT-FLIGHT-POLL
12 CONSTANT _KDOSTLSL-PHASE-DISPOSITION
13 CONSTANT _KDOSTLSL-PHASE-DISPOSITION-POLL
14 CONSTANT _KDOSTLSL-PHASE-TERMINAL-CLOSE
15 CONSTANT _KDOSTLSL-PHASE-TERMINAL-CLOSE-POLL
16 CONSTANT _KDOSTLSL-PHASE-PUBLISH
17 CONSTANT _KDOSTLSL-PHASE-PUBLISHED
18 CONSTANT _KDOSTLSL-PHASE-ADOPTED
19 CONSTANT _KDOSTLSL-PHASE-CLEANUP

: _KDOSTLSL.MAGIC         ( owner -- a ) _KDOSTLSL-MAGIC + ;
: _KDOSTLSL.XIO-SERVICE   ( owner -- a ) _KDOSTLSL-XIO-SERVICE + ;
: _KDOSTLSL.LISTENER-SD   ( owner -- a ) _KDOSTLSL-LISTENER-SD + ;
: _KDOSTLSL.LISTENER-H1   ( owner -- a ) _KDOSTLSL-LISTENER-H1 + ;
: _KDOSTLSL.LISTENER-GEN  ( owner -- a ) _KDOSTLSL-LISTENER-GEN + ;
: _KDOSTLSL.TIMEOUT-MS    ( owner -- a ) _KDOSTLSL-TIMEOUT-MS + ;
: _KDOSTLSL.EARLY-BUDGET  ( owner -- a ) _KDOSTLSL-EARLY-BUDGET + ;
: _KDOSTLSL.OWNER-GEN     ( owner -- a ) _KDOSTLSL-OWNER-GEN + ;
: _KDOSTLSL.REQUEST-GEN   ( owner -- a ) _KDOSTLSL-REQUEST-GEN + ;
: _KDOSTLSL.CTX           ( owner -- a ) _KDOSTLSL-CTX + ;
: _KDOSTLSL.CTX-GEN       ( owner -- a ) _KDOSTLSL-CTX-GEN + ;
: _KDOSTLSL.PHASE         ( owner -- a ) _KDOSTLSL-PHASE + ;
: _KDOSTLSL.BORROWED-PORT ( owner -- a ) _KDOSTLSL-BORROWED-PORT + ;
: _KDOSTLSL.TERMINAL      ( owner -- a ) _KDOSTLSL-TERMINAL + ;
: _KDOSTLSL.STAGING-SOCKET ( owner -- a ) _KDOSTLSL-STAGING-SOCKET + ;
: _KDOSTLSL.XIO-OP        ( owner -- operation ) _KDOSTLSL-XIO-OP + ;

: _KDOSTLSL-VALID?  ( owner -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP KDOSTLSL-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP _KDOSTLSL.MAGIC @ _KDOSTLSL-MAGIC-VALUE =
    OVER _KDOSTLSL.XIO-SERVICE @ 0<> AND
    OVER _KDOSTLSL.LISTENER-SD @ 0<> AND
    OVER _KDOSTLSL.LISTENER-H1 @ 0> AND
    OVER _KDOSTLSL.LISTENER-GEN @ 0> AND
    OVER _KDOSTLSL.TIMEOUT-MS @ 0> AND
    OVER _KDOSTLSL.EARLY-BUDGET @ 0< 0= AND
    OVER _KDOSTLSL.OWNER-GEN @ 0> AND
    OVER _KDOSTLSL.REQUEST-GEN @ 0< 0= AND
    OVER _KDOSTLSL.PHASE @ DUP _KDOSTLSL-PHASE-IDLE >=
    SWAP _KDOSTLSL-PHASE-CLEANUP <= AND AND
    OVER _KDOSTLSL.TERMINAL @ DUP KDOSTLSL-S-OK >=
    SWAP KDOSTLSL-S-RETRY <= AND AND
    SWAP _KDOSTLSL.XIO-OP XIO-OP-VALID? AND ;

: _KDOSTLSL-SERVICE-READY?  ( owner -- flag )
    _KDOSTLSL.XIO-SERVICE @ DUP XIO-SERVICE-BOUND?
    SWAP XIO-SERVICE-OWNER? AND ;

: _KDOSTLSL-IDLE?  ( owner -- flag )
    DUP _KDOSTLSL.PHASE @ _KDOSTLSL-PHASE-IDLE =
    OVER _KDOSTLSL.CTX @ 0= AND
    OVER _KDOSTLSL.CTX-GEN @ 0= AND
    OVER _KDOSTLSL.BORROWED-PORT @ 0= AND
    OVER _KDOSTLSL.TERMINAL @ 0= AND
    OVER _KDOSTLSL.STAGING-SOCKET @ 0= AND
    SWAP _KDOSTLSL.XIO-OP XIOO.STATE @ XIO-STATE-RESET = AND ;

: _KDOSTLSL-XIO-EXACT?  ( owner -- flag )
    >R
    R@ R@ _KDOSTLSL.OWNER-GEN @ R@ _KDOSTLSL.REQUEST-GEN @
    R> _KDOSTLSL.XIO-OP XIO-OP-MATCH? ;

: _KDOSTLSL-XIO>STATUS  ( xio-status -- status )
    CASE
        XIO-S-OK OF KDOSTLSL-S-OK ENDOF
        XIO-S-INVALID OF KDOSTLSL-S-INVALID ENDOF
        XIO-S-BUSY OF KDOSTLSL-S-BUSY ENDOF
        XIO-S-STATE OF KDOSTLSL-S-STATE ENDOF
        XIO-S-NOT-OWNER OF KDOSTLSL-S-NOT-OWNER ENDOF
        XIO-S-CALLBACK OF KDOSTLSL-S-LOWER ENDOF
        XIO-S-PENDING OF KDOSTLSL-S-PENDING ENDOF
        KDOSTLSL-S-STATE SWAP
    ENDCASE ;

: _KDOSTLSL-PORT>STATUS  ( port-status -- status )
    CASE
        KDOSTLSP-S-OK OF KDOSTLSL-S-OK ENDOF
        KDOSTLSP-S-INVALID OF KDOSTLSL-S-INVALID ENDOF
        KDOSTLSP-S-BUSY OF KDOSTLSL-S-BUSY ENDOF
        KDOSTLSP-S-STATE OF KDOSTLSL-S-STATE ENDOF
        KDOSTLSP-S-PENDING OF KDOSTLSL-S-PENDING ENDOF
        KDOSTLSP-S-LOWER OF KDOSTLSL-S-LOWER ENDOF
        KDOSTLSP-S-PLATFORM OF KDOSTLSL-S-PLATFORM ENDOF
        KDOSTLSP-S-NOT-OWNER OF KDOSTLSL-S-NOT-OWNER ENDOF
        KDOSTLSL-S-STATE SWAP
    ENDCASE ;

VARIABLE _KDOSTLSLI-SERVICE
VARIABLE _KDOSTLSLI-SD
VARIABLE _KDOSTLSLI-H1
VARIABLE _KDOSTLSLI-GEN
VARIABLE _KDOSTLSLI-TIMEOUT
VARIABLE _KDOSTLSLI-EARLY
VARIABLE _KDOSTLSLI-OWNER
VARIABLE _KDOSTLSLI-OLD-GEN
VARIABLE _KDOSTLSLI-NEW-GEN

: KDOSTLSL-INIT
    \ ( xio-service listener-sd listener-h1 listener-generation
    \   timeout-ms early-budget owner -- status )
    _KDOSTLSLI-OWNER ! _KDOSTLSLI-EARLY ! _KDOSTLSLI-TIMEOUT !
    _KDOSTLSLI-GEN ! _KDOSTLSLI-H1 ! _KDOSTLSLI-SD !
    _KDOSTLSLI-SERVICE !
    COREID 0<> IF KDOSTLSL-S-PLATFORM EXIT THEN
    _KDOSTLSLI-OWNER @ 0=
    _KDOSTLSLI-SERVICE @ 0= OR IF KDOSTLSL-S-INVALID EXIT THEN
    _KDOSTLSLI-OWNER @ KDOSTLSL-SIZE MSPAN-NONWRAPPING? 0=
    _KDOSTLSLI-SERVICE @ XIO-SERVICE-SIZE MSPAN-NONWRAPPING? 0= OR IF
        KDOSTLSL-S-INVALID EXIT
    THEN
    _KDOSTLSLI-OWNER @ KDOSTLSL-SIZE
    _KDOSTLSLI-SERVICE @ XIO-SERVICE-SIZE MSPAN-OVERLAP? IF
        KDOSTLSL-S-INVALID EXIT
    THEN
    _KDOSTLSLI-SERVICE @ XIO-SERVICE-BOUND? 0= IF
        KDOSTLSL-S-INVALID EXIT
    THEN
    _KDOSTLSLI-SERVICE @ XIO-SERVICE-OWNER? 0= IF
        KDOSTLSL-S-NOT-OWNER EXIT
    THEN
    _KDOSTLSLI-SD @ 0=
    _KDOSTLSLI-H1 @ 0> 0= OR
    _KDOSTLSLI-GEN @ 0> 0= OR
    _KDOSTLSLI-TIMEOUT @ 0> 0= OR
    _KDOSTLSLI-EARLY @ 0< OR IF KDOSTLSL-S-INVALID EXIT THEN
    0 _KDOSTLSLI-OLD-GEN !
    _KDOSTLSLI-OWNER @ _KDOSTLSL.MAGIC @
    _KDOSTLSL-MAGIC-VALUE = IF
        _KDOSTLSLI-OWNER @ _KDOSTLSL-VALID? 0= IF
            KDOSTLSL-S-STATE EXIT
        THEN
        _KDOSTLSLI-OWNER @ _KDOSTLSL-IDLE? 0= IF
            KDOSTLSL-S-BUSY EXIT
        THEN
        _KDOSTLSLI-OWNER @ _KDOSTLSL.OWNER-GEN @
        _KDOSTLSLI-OLD-GEN !
    THEN
    _KDOSTLSLI-OLD-GEN @ DUP IF
        DUP _KDOSTLSL-CELL-MAX >= IF DROP KDOSTLSL-S-STATE EXIT THEN
        1+
    ELSE
        DROP 1
    THEN _KDOSTLSLI-NEW-GEN !
    _KDOSTLSLI-OWNER @ KDOSTLSL-SIZE 0 FILL
    _KDOSTLSL-MAGIC-VALUE _KDOSTLSLI-OWNER @ _KDOSTLSL.MAGIC !
    _KDOSTLSLI-SERVICE @ _KDOSTLSLI-OWNER @ _KDOSTLSL.XIO-SERVICE !
    _KDOSTLSLI-SD @ _KDOSTLSLI-OWNER @ _KDOSTLSL.LISTENER-SD !
    _KDOSTLSLI-H1 @ _KDOSTLSLI-OWNER @ _KDOSTLSL.LISTENER-H1 !
    _KDOSTLSLI-GEN @ _KDOSTLSLI-OWNER @ _KDOSTLSL.LISTENER-GEN !
    _KDOSTLSLI-TIMEOUT @ _KDOSTLSLI-OWNER @ _KDOSTLSL.TIMEOUT-MS !
    _KDOSTLSLI-EARLY @ _KDOSTLSLI-OWNER @ _KDOSTLSL.EARLY-BUDGET !
    _KDOSTLSLI-NEW-GEN @ _KDOSTLSLI-OWNER @ _KDOSTLSL.OWNER-GEN !
    _KDOSTLSL-PHASE-IDLE _KDOSTLSLI-OWNER @ _KDOSTLSL.PHASE !
    _KDOSTLSLI-OWNER @ _KDOSTLSL.XIO-OP XIO-OP-INIT
    KDOSTLSL-S-OK ;

\ ---------------------------------------------------------------------
\ Private XIO provider and exact lower phase driver
\ ---------------------------------------------------------------------

\ XIO and KDOSNET serialize these scratch cells.  None contains authority
\ after a callback returns; exact authority lives only in the owner fields.
VARIABLE _KDOSTLSLX-OP
VARIABLE _KDOSTLSLX-OWNER
VARIABLE _KDOSTLSLX-PORT
VARIABLE _KDOSTLSLX-PROGRESS
VARIABLE _KDOSTLSLX-ALERT
VARIABLE _KDOSTLSLX-IOR
VARIABLE _KDOSTLSLX-CTX
VARIABLE _KDOSTLSLX-GEN
VARIABLE _KDOSTLSLX-SD
VARIABLE _KDOSTLSLX-RETIRED
VARIABLE _KDOSTLSLX-STEP
VARIABLE _KDOSTLSLX-CLAIM-STATUS
VARIABLE _KDOSTLSLX-THROW
VARIABLE _KDOSTLSLX-RELEASE-STATUS
VARIABLE _KDOSTLSLX-IN-CALL
0 _KDOSTLSLX-IN-CALL !

: _KDOSTLSL-CALLBACK-BEGIN  ( operation owner -- flag )
    _KDOSTLSLX-OWNER ! _KDOSTLSLX-OP !
    _KDOSTLSLX-OWNER @ _KDOSTLSL-VALID? 0= IF 0 EXIT THEN
    _KDOSTLSLX-OP @ XIO-OP-VALID? 0= IF 0 EXIT THEN
    _KDOSTLSLX-OP @ XIOO.CONTEXT @ _KDOSTLSLX-OWNER @ =
    _KDOSTLSLX-OWNER @ _KDOSTLSL-XIO-EXACT? AND ;

: _KDOSTLSL-PRIMARY!  ( ior -- )
    ?DUP IF
        _KDOSTLSLX-OP @ XIOO.ERROR @ 0= IF
            _KDOSTLSLX-OP @ XIOO.ERROR !
        ELSE
            DROP
        THEN
    THEN ;

: _KDOSTLSL-SECONDARY!  ( ior -- )
    ?DUP IF
        _KDOSTLSLX-OP @ XIOO.CLEANUP-ERROR @ 0= IF
            _KDOSTLSLX-OP @ XIOO.CLEANUP-ERROR !
        ELSE
            DROP
        THEN
    THEN ;

: _KDOSTLSL-FAIL  ( ior -- step-status )
    DUP 0= IF DROP TLS-E-TRANSPORT THEN
    _KDOSTLSL-PRIMARY! XIO-STEP-FAILED ;

: _KDOSTLSL-TERMINAL-FAIL  ( secondary-ior -- step-status )
    _KDOSTLSL-SECONDARY!
    _KDOSTLSLX-OP @ XIOO.ERROR @ 0= IF
        TLS-E-TRANSPORT _KDOSTLSLX-OP @ XIOO.ERROR !
    THEN
    XIO-STEP-FAILED ;

: _KDOSTLSL-THROW>IOR  ( throw -- ior )
    DUP 0> IF DROP TLS-E-TRANSPORT THEN ;

: _KDOSTLSL-ALERT-VALID?  ( alert -- flag )
    DUP 0> SWAP 255 <= AND ;

: _KDOSTLSL-EARLY-ALERT  ( alert -- step-status )
    _KDOSTLSLX-OP @ XIOO.RESULT !
    KDOSTLSL-E-HANDSHAKE-ALERT _KDOSTLSLX-OP @ XIOO.ERROR !
    XIO-STEP-FAILED ;

: _KDOSTLSL-ARM-DEADLINE  ( -- )
    MS@ _KDOSTLSLX-OWNER @ _KDOSTLSL.TIMEOUT-MS @ +
    _KDOSTLSLX-OP @ XIOO.DEADLINE-MS ! ;

: _KDOSTLSL-LISTENER-POLL-STEP  ( -- step-status )
    TCP-POLL
    _KDOSTLSL-PHASE-CLAIM _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
    XIO-STEP-PENDING ;

: _KDOSTLSL-CLAIM-STEP  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.LISTENER-SD @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.LISTENER-H1 @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.LISTENER-GEN @
    TLS-SERVER-ACCEPT-CLAIM
    _KDOSTLSLX-IOR ! _KDOSTLSLX-GEN ! _KDOSTLSLX-CTX !
    _KDOSTLSLX-IOR @ IF
        _KDOSTLSLX-CTX @ _KDOSTLSLX-GEN @ OR IF
            _KDOSTLSLX-CTX @ _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX !
            _KDOSTLSLX-GEN @ _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN !
            TLS-E-TRANSPORT _KDOSTLSL-FAIL EXIT
        THEN
        _KDOSTLSLX-IOR @ _KDOSTLSL-FAIL EXIT
    THEN
    _KDOSTLSLX-CTX @ 0= _KDOSTLSLX-GEN @ 0= OR IF
        TLS-E-TRANSPORT _KDOSTLSL-FAIL EXIT
    THEN
    _KDOSTLSLX-CTX @ _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX !
    _KDOSTLSLX-GEN @ _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN !
    _KDOSTLSL-ARM-DEADLINE
    _KDOSTLSL-PHASE-CLIENT-HELLO
    _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
    XIO-STEP-PENDING ;

: _KDOSTLSL-CLIENT-HELLO-STEP  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @
    TLS-SERVER-CLIENT-HELLO-STEP
    _KDOSTLSLX-IOR ! _KDOSTLSLX-ALERT ! _KDOSTLSLX-PROGRESS !
    _KDOSTLSLX-IOR @ DUP TLS-E-WOULD-BLOCK = IF
        DROP _KDOSTLSLX-PROGRESS @ TLS-SERVER-CLIENT-HELLO-NONE =
        _KDOSTLSLX-ALERT @ 0= AND 0= IF
            TLS-E-TRANSPORT _KDOSTLSL-FAIL EXIT
        THEN
        _KDOSTLSL-PHASE-CLIENT-HELLO-POLL
        _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE ! XIO-STEP-PENDING EXIT
    THEN
    DUP TLS-E-BUSY = IF
        DROP _KDOSTLSLX-PROGRESS @ TLS-SERVER-CLIENT-HELLO-NONE =
        _KDOSTLSLX-ALERT @ 0= AND 0= IF
            TLS-E-TRANSPORT _KDOSTLSL-FAIL EXIT
        THEN
        XIO-STEP-PENDING EXIT
    THEN
    DUP IF
        >R _KDOSTLSLX-PROGRESS @ TLS-SERVER-CLIENT-HELLO-NONE =
        _KDOSTLSLX-ALERT @ 0= AND R@ 0< AND IF
            R> _KDOSTLSL-FAIL
        ELSE
            R> DROP TLS-E-TRANSPORT _KDOSTLSL-FAIL
        THEN EXIT
    THEN DROP
    _KDOSTLSLX-ALERT @ DUP IF
        DUP _KDOSTLSL-ALERT-VALID?
        _KDOSTLSLX-PROGRESS @ TLS-SERVER-CLIENT-HELLO-NONE = AND IF
            _KDOSTLSL-EARLY-ALERT
        ELSE
            DROP TLS-E-TRANSPORT _KDOSTLSL-FAIL
        THEN EXIT
    THEN DROP
    _KDOSTLSLX-PROGRESS @ DUP TLS-SERVER-CLIENT-HELLO-RECORD = IF
        DROP XIO-STEP-PENDING EXIT
    THEN
    TLS-SERVER-CLIENT-HELLO-COMPLETE = IF
        _KDOSTLSL-PHASE-PREPARE-HELLO
        _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
        XIO-STEP-PENDING EXIT
    THEN
    TLS-E-TRANSPORT _KDOSTLSL-FAIL ;

: _KDOSTLSL-PREPARE-HELLO-STEP  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @
    TLS-SERVER-PREPARE-HELLO-EXACT
    _KDOSTLSLX-IOR ! _KDOSTLSLX-ALERT !
    _KDOSTLSLX-IOR @ DUP TLS-E-BUSY = IF
        DROP _KDOSTLSLX-ALERT @ 0= IF XIO-STEP-PENDING
        ELSE TLS-E-TRANSPORT _KDOSTLSL-FAIL THEN EXIT
    THEN
    DUP IF
        >R _KDOSTLSLX-ALERT @ 0= R@ 0< AND IF
            R> _KDOSTLSL-FAIL
        ELSE
            R> DROP TLS-E-TRANSPORT _KDOSTLSL-FAIL
        THEN EXIT
    THEN DROP
    _KDOSTLSLX-ALERT @ DUP IF
        DUP _KDOSTLSL-ALERT-VALID? IF _KDOSTLSL-EARLY-ALERT
        ELSE DROP TLS-E-TRANSPORT _KDOSTLSL-FAIL THEN EXIT
    THEN DROP
    _KDOSTLSL-PHASE-PREPARE-FLIGHT
    _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
    XIO-STEP-PENDING ;

: _KDOSTLSL-PREPARE-FLIGHT-STEP  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @
    TLS-SERVER-PREPARE-FLIGHT-EXACT DUP _KDOSTLSLX-IOR !
    DUP TLS-E-BUSY = IF DROP XIO-STEP-PENDING EXIT THEN
    DUP IF
        DUP 0< IF _KDOSTLSL-FAIL
        ELSE DROP TLS-E-TRANSPORT _KDOSTLSL-FAIL THEN EXIT
    THEN DROP
    _KDOSTLSL-PHASE-FLIGHT _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
    XIO-STEP-PENDING ;

: _KDOSTLSL-FLIGHT-STEP  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @ TLS-SERVER-FLIGHT-STEP
    _KDOSTLSLX-IOR ! _KDOSTLSLX-PROGRESS !
    _KDOSTLSLX-IOR @ DUP TLS-E-BUSY = IF
        DROP _KDOSTLSLX-PROGRESS @ TLS-SERVER-EMIT-NONE = IF
            XIO-STEP-PENDING
        ELSE
            TLS-E-TRANSPORT _KDOSTLSL-FAIL
        THEN EXIT
    THEN
    DUP TLS-E-WOULD-BLOCK = IF
        DROP _KDOSTLSLX-PROGRESS @ TLS-SERVER-EMIT-NONE = IF
            _KDOSTLSL-PHASE-FLIGHT-POLL
            _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE ! XIO-STEP-PENDING
        ELSE
            TLS-E-TRANSPORT _KDOSTLSL-FAIL
        THEN EXIT
    THEN
    DUP IF
        >R _KDOSTLSLX-PROGRESS @ TLS-SERVER-EMIT-NONE = R@ 0< AND IF
            R> _KDOSTLSL-FAIL
        ELSE
            R> DROP TLS-E-TRANSPORT _KDOSTLSL-FAIL
        THEN EXIT
    THEN DROP
    _KDOSTLSLX-PROGRESS @ DUP TLS-SERVER-EMIT-RECORD = IF
        DROP XIO-STEP-PENDING EXIT
    THEN
    TLS-SERVER-EMIT-COMPLETE = IF
        _KDOSTLSL-PHASE-CLIENT-FLIGHT-BEGIN
        _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE ! XIO-STEP-PENDING EXIT
    THEN
    TLS-E-TRANSPORT _KDOSTLSL-FAIL ;

: _KDOSTLSL-CLIENT-FLIGHT-BEGIN-STEP  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.EARLY-BUDGET @
    TLS-SERVER-CLIENT-FLIGHT-BEGIN-ATTACHED DUP _KDOSTLSLX-IOR !
    DUP TLS-E-BUSY = IF DROP XIO-STEP-PENDING EXIT THEN
    DUP IF
        DUP 0< IF _KDOSTLSL-FAIL
        ELSE DROP TLS-E-TRANSPORT _KDOSTLSL-FAIL THEN EXIT
    THEN DROP
    _KDOSTLSL-PHASE-CLIENT-FLIGHT
    _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
    XIO-STEP-PENDING ;

: _KDOSTLSL-INGRESS-TERMINAL?  ( -- flag )
    _KDOSTLSLX-PROGRESS @
    DUP TLS-SERVER-INGRESS-SEND-FATAL = IF
        DROP _KDOSTLSLX-IOR @ DUP 0<
        SWAP TLS-E-PEER-ALERT <> AND
        _KDOSTLSLX-ALERT @ _KDOSTLSL-ALERT-VALID? AND EXIT
    THEN
    DUP TLS-SERVER-INGRESS-SEND-CLOSE = IF
        DROP _KDOSTLSLX-IOR @ TLS-E-PEER-ALERT =
        _KDOSTLSLX-ALERT @ 0= AND EXIT
    THEN
    TLS-SERVER-INGRESS-PEER-ALERT = IF
        _KDOSTLSLX-IOR @ TLS-E-PEER-ALERT =
        _KDOSTLSLX-ALERT @ _KDOSTLSL-ALERT-VALID? AND EXIT
    THEN
    0 ;

: _KDOSTLSL-CLIENT-FLIGHT-STEP  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @
    TLS-SERVER-CLIENT-FLIGHT-STEP
    _KDOSTLSLX-IOR ! _KDOSTLSLX-ALERT ! _KDOSTLSLX-PROGRESS !
    _KDOSTLSLX-IOR @ DUP TLS-E-BUSY = IF
        DROP _KDOSTLSLX-PROGRESS @ TLS-SERVER-INGRESS-NONE =
        _KDOSTLSLX-ALERT @ 0= AND IF XIO-STEP-PENDING
        ELSE TLS-E-TRANSPORT _KDOSTLSL-FAIL THEN EXIT
    THEN
    DUP TLS-E-WOULD-BLOCK = IF
        DROP _KDOSTLSLX-PROGRESS @ TLS-SERVER-INGRESS-NONE =
        _KDOSTLSLX-ALERT @ 0= AND IF
            _KDOSTLSL-PHASE-CLIENT-FLIGHT-POLL
            _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE ! XIO-STEP-PENDING
        ELSE
            TLS-E-TRANSPORT _KDOSTLSL-FAIL
        THEN EXIT
    THEN DROP
    _KDOSTLSLX-IOR @ IF
        _KDOSTLSL-INGRESS-TERMINAL? IF
            _KDOSTLSLX-IOR @ _KDOSTLSLX-OP @ XIOO.ERROR !
            _KDOSTLSLX-ALERT @ _KDOSTLSLX-OP @ XIOO.RESULT !
            _KDOSTLSL-PHASE-DISPOSITION
            _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
            XIO-STEP-PENDING EXIT
        THEN
        _KDOSTLSLX-PROGRESS @ TLS-SERVER-INGRESS-NONE =
        _KDOSTLSLX-ALERT @ 0= AND
        _KDOSTLSLX-IOR @ 0< AND IF
            _KDOSTLSLX-IOR @ _KDOSTLSL-FAIL
        ELSE
            TLS-E-TRANSPORT _KDOSTLSL-FAIL
        THEN EXIT
    THEN
    _KDOSTLSLX-ALERT @ IF TLS-E-TRANSPORT _KDOSTLSL-FAIL EXIT THEN
    _KDOSTLSLX-PROGRESS @ DUP TLS-SERVER-INGRESS-RECORD = IF
        DROP XIO-STEP-PENDING EXIT
    THEN
    TLS-SERVER-INGRESS-FINISHED = IF
        _KDOSTLSL-PHASE-PUBLISH
        _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
        XIO-STEP-PENDING EXIT
    THEN
    TLS-E-TRANSPORT _KDOSTLSL-FAIL ;

: _KDOSTLSL-DISPOSITION-STEP  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @
    TLS-SERVER-INGRESS-DISPOSITION-STEP
    _KDOSTLSLX-IOR ! _KDOSTLSLX-PROGRESS !
    _KDOSTLSLX-IOR @ DUP TLS-E-BUSY = IF
        DROP _KDOSTLSLX-PROGRESS @ TLS-SERVER-DISPOSITION-NONE = IF
            XIO-STEP-PENDING
        ELSE
            TLS-E-TRANSPORT _KDOSTLSL-TERMINAL-FAIL
        THEN EXIT
    THEN
    DUP TLS-E-WOULD-BLOCK = IF
        DROP _KDOSTLSLX-PROGRESS @ TLS-SERVER-DISPOSITION-NONE = IF
            _KDOSTLSL-PHASE-DISPOSITION-POLL
            _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE ! XIO-STEP-PENDING
        ELSE
            TLS-E-TRANSPORT _KDOSTLSL-TERMINAL-FAIL
        THEN EXIT
    THEN
    DUP IF _KDOSTLSL-TERMINAL-FAIL EXIT THEN DROP
    _KDOSTLSLX-PROGRESS @ TLS-SERVER-DISPOSITION-COMPLETE <> IF
        TLS-E-TRANSPORT _KDOSTLSL-TERMINAL-FAIL EXIT
    THEN
    _KDOSTLSL-PHASE-TERMINAL-CLOSE
    _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
    XIO-STEP-PENDING ;

: _KDOSTLSL-TERMINAL-CLOSE-STEP  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @
    TLS-SERVER-CLOSE-EXACT-TRY
    _KDOSTLSLX-IOR ! _KDOSTLSLX-RETIRED !
    _KDOSTLSLX-RETIRED @ IF
        0 _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX !
        0 _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN !
        _KDOSTLSLX-IOR @ _KDOSTLSL-TERMINAL-FAIL EXIT
    THEN
    _KDOSTLSLX-IOR @ DUP TLS-E-BUSY = IF DROP XIO-STEP-PENDING EXIT THEN
    TLS-E-WOULD-BLOCK = IF
        _KDOSTLSL-PHASE-TERMINAL-CLOSE-POLL
        _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE ! XIO-STEP-PENDING EXIT
    THEN
    _KDOSTLSLX-IOR @ DUP 0= IF DROP TLS-E-TRANSPORT THEN
    _KDOSTLSL-TERMINAL-FAIL ;

: _KDOSTLSL-STAGING-IN-PORT?  ( -- flag )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.BORROWED-PORT @ DUP 0= IF
        DROP 0 EXIT
    THEN
    DUP KDOSTLSP.STATE @ KDOSTLSP-STATE-PUBLISHED =
    SWAP KDOSTLSP.SOCKET-SD @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.STAGING-SOCKET @ = AND ;

: _KDOSTLSL-NORMALIZE-STAGING  ( -- )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.STAGING-SOCKET @ IF
        _KDOSTLSL-STAGING-IN-PORT? IF
            0 _KDOSTLSLX-OWNER @ _KDOSTLSL.STAGING-SOCKET !
        THEN
    THEN ;

: _KDOSTLSL-PUBLISH-STEP  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @
    TLS-SERVER-SOCKET-PUBLISH
    _KDOSTLSLX-IOR ! _KDOSTLSLX-SD !
    _KDOSTLSLX-SD @ IF
        \ The lower publication transaction has transferred authority as
        \ soon as it returns a descriptor.  Record that descriptor before
        \ staging it into the shared port so a contained throw or contract
        \ failure still has an exact cleanup path.
        _KDOSTLSLX-SD @
        _KDOSTLSLX-OWNER @ _KDOSTLSL.STAGING-SOCKET !
        0 _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX !
        0 _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN !
        _KDOSTLSLX-OWNER @ _KDOSTLSL.BORROWED-PORT @
        _KDOSTLSLX-PORT !
        _KDOSTLSLX-SD @ _KDOSTLSLX-PORT @ KDOSTLSP-PUBLISH
        DUP KDOSTLSP-S-OK <> IF
            _KDOSTLSL-NORMALIZE-STAGING
            DROP KDOSTLSL-E-STATE _KDOSTLSL-FAIL EXIT
        THEN DROP
        0 _KDOSTLSLX-OWNER @ _KDOSTLSL.STAGING-SOCKET !
        _KDOSTLSL-PHASE-PUBLISHED
        _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
        \ A nonzero descriptor is publication authority even if a malformed
        \ lower tuple also carries an error.  Stage it before failing so XIO
        \ cleanup retires the shared socket rather than stale raw authority.
        _KDOSTLSLX-IOR @ IF TLS-E-TRANSPORT _KDOSTLSL-FAIL EXIT THEN
        _KDOSTLSLX-PORT @ _KDOSTLSLX-OP @ XIOO.RESULT !
        0 _KDOSTLSLX-OP @ XIOO.ERROR !
        XIO-STEP-SUCCEEDED EXIT
    THEN
    _KDOSTLSLX-IOR @ DUP TLS-E-BUSY = IF DROP XIO-STEP-PENDING EXIT THEN
    DUP IF
        DUP 0< IF _KDOSTLSL-FAIL
        ELSE DROP TLS-E-TRANSPORT _KDOSTLSL-FAIL THEN EXIT
    THEN DROP
    TLS-E-TRANSPORT _KDOSTLSL-FAIL ;

: _KDOSTLSL-POLL-TRANSPORT-STEP  ( resume-phase -- step-status )
    TCP-POLL _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
    XIO-STEP-PENDING ;

: _KDOSTLSL-LOWER-DISPATCH  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE @ CASE
        _KDOSTLSL-PHASE-LISTENER-POLL OF
            _KDOSTLSL-LISTENER-POLL-STEP ENDOF
        _KDOSTLSL-PHASE-CLAIM OF _KDOSTLSL-CLAIM-STEP ENDOF
        _KDOSTLSL-PHASE-CLIENT-HELLO OF
            _KDOSTLSL-CLIENT-HELLO-STEP ENDOF
        _KDOSTLSL-PHASE-CLIENT-HELLO-POLL OF
            _KDOSTLSL-PHASE-CLIENT-HELLO
            _KDOSTLSL-POLL-TRANSPORT-STEP
        ENDOF
        _KDOSTLSL-PHASE-PREPARE-HELLO OF
            _KDOSTLSL-PREPARE-HELLO-STEP ENDOF
        _KDOSTLSL-PHASE-PREPARE-FLIGHT OF
            _KDOSTLSL-PREPARE-FLIGHT-STEP ENDOF
        _KDOSTLSL-PHASE-FLIGHT OF _KDOSTLSL-FLIGHT-STEP ENDOF
        _KDOSTLSL-PHASE-FLIGHT-POLL OF
            _KDOSTLSL-PHASE-FLIGHT _KDOSTLSL-POLL-TRANSPORT-STEP
        ENDOF
        _KDOSTLSL-PHASE-CLIENT-FLIGHT-BEGIN OF
            _KDOSTLSL-CLIENT-FLIGHT-BEGIN-STEP ENDOF
        _KDOSTLSL-PHASE-CLIENT-FLIGHT OF
            _KDOSTLSL-CLIENT-FLIGHT-STEP ENDOF
        _KDOSTLSL-PHASE-CLIENT-FLIGHT-POLL OF
            _KDOSTLSL-PHASE-CLIENT-FLIGHT
            _KDOSTLSL-POLL-TRANSPORT-STEP
        ENDOF
        _KDOSTLSL-PHASE-DISPOSITION OF
            _KDOSTLSL-DISPOSITION-STEP ENDOF
        _KDOSTLSL-PHASE-DISPOSITION-POLL OF
            _KDOSTLSL-PHASE-DISPOSITION
            _KDOSTLSL-POLL-TRANSPORT-STEP
        ENDOF
        _KDOSTLSL-PHASE-TERMINAL-CLOSE OF
            _KDOSTLSL-TERMINAL-CLOSE-STEP ENDOF
        _KDOSTLSL-PHASE-TERMINAL-CLOSE-POLL OF
            _KDOSTLSL-PHASE-TERMINAL-CLOSE
            _KDOSTLSL-POLL-TRANSPORT-STEP
        ENDOF
        _KDOSTLSL-PHASE-PUBLISH OF _KDOSTLSL-PUBLISH-STEP ENDOF
        KDOSTLSL-E-STATE _KDOSTLSL-FAIL SWAP
    ENDCASE ;

: _KDOSTLSL-LOWER-INNER  ( -- )
    _KDOSTLSL-LOWER-DISPATCH _KDOSTLSLX-STEP ! ;

: _KDOSTLSL-PRECLAIM?  ( -- flag )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @ OR 0=
    _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE @
    _KDOSTLSL-PHASE-CLAIM <= AND ;

: _KDOSTLSL-GUARDED-STEP  ( -- step-status )
    XIO-STEP-FAILED _KDOSTLSLX-STEP !
    -1 _KDOSTLSLX-IN-CALL !
    _KDOSTLSLX-OWNER @ ['] _KDOSTLSL-LOWER-INNER KDOSNET-WITH
    0 _KDOSTLSLX-IN-CALL !
    _KDOSTLSLX-RELEASE-STATUS !
    _KDOSTLSLX-THROW !
    _KDOSTLSLX-CLAIM-STATUS !
    _KDOSTLSLX-CLAIM-STATUS @ DUP IF
        DUP KDOSNET-S-BUSY = IF
            DROP _KDOSTLSL-PRECLAIM? IF
                KDOSTLSL-E-CONTENTION _KDOSTLSL-FAIL
            ELSE
                XIO-STEP-PENDING
            THEN EXIT
        THEN
        KDOSNET-S-PLATFORM = IF
            KDOSTLSL-E-PLATFORM _KDOSTLSL-FAIL
        ELSE
            KDOSTLSL-E-STATE _KDOSTLSL-FAIL
        THEN EXIT
    THEN DROP
    _KDOSTLSLX-THROW @ ?DUP IF
        _KDOSTLSL-THROW>IOR _KDOSTLSL-FAIL EXIT
    THEN
    _KDOSTLSLX-RELEASE-STATUS @ ?DUP IF
        _KDOSTLSL-SECONDARY!
        KDOSTLSL-E-CLEANUP _KDOSTLSL-FAIL EXIT
    THEN
    _KDOSTLSLX-STEP @ ;

: _KDOSTLSL-XIO-START  ( operation owner -- step-status )
    _KDOSTLSL-CALLBACK-BEGIN 0= IF
        KDOSTLSL-E-STATE _KDOSTLSL-FAIL EXIT
    THEN
    _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE @
    _KDOSTLSL-PHASE-LISTENER-POLL <> IF
        KDOSTLSL-E-STATE _KDOSTLSL-FAIL EXIT
    THEN
    _KDOSTLSL-GUARDED-STEP ;

: _KDOSTLSL-XIO-POLL  ( operation owner -- step-status )
    _KDOSTLSL-CALLBACK-BEGIN 0= IF
        KDOSTLSL-E-STATE _KDOSTLSL-FAIL EXIT
    THEN
    _KDOSTLSL-GUARDED-STEP ;

: _KDOSTLSL-XIO-CANCEL  ( operation owner -- )
    _KDOSTLSL-CALLBACK-BEGIN 0= IF KDOSTLSL-E-STATE THROW THEN
    _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE @
    _KDOSTLSL-PHASE-ADOPTED <> IF
        _KDOSTLSL-PHASE-CLEANUP
        _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE !
    THEN ;

\ ---------------------------------------------------------------------
\ Cooperative exact cleanup
\ ---------------------------------------------------------------------

: _KDOSTLSL-ABORT-INNER  ( -- )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @ OR IF
        _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
        _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @ TLS-ABORT-EXACT
        _KDOSTLSLX-IOR ! _KDOSTLSLX-RETIRED !
        _KDOSTLSLX-RETIRED @ IF
            0 _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX !
            0 _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN !
        THEN
        EXIT
    THEN
    _KDOSTLSLX-OWNER @ _KDOSTLSL.STAGING-SOCKET @ ?DUP IF
        SOCK-TLS-ABORT-EXACT-TRY
        _KDOSTLSLX-IOR ! _KDOSTLSLX-ALERT !
        _KDOSTLSLX-ALERT @ TLS-ABORT-S-BUSY <>
        _KDOSTLSLX-IOR @ 0= AND _KDOSTLSLX-RETIRED !
        _KDOSTLSLX-RETIRED @ IF
            0 _KDOSTLSLX-OWNER @ _KDOSTLSL.STAGING-SOCKET !
        THEN
    THEN ;

: _KDOSTLSL-ABORT-CLEANUP-STEP  ( -- step-status )
    0 _KDOSTLSLX-IOR ! 0 _KDOSTLSLX-RETIRED !
    -1 _KDOSTLSLX-IN-CALL !
    _KDOSTLSLX-OWNER @ ['] _KDOSTLSL-ABORT-INNER KDOSNET-WITH
    0 _KDOSTLSLX-IN-CALL !
    _KDOSTLSLX-RELEASE-STATUS !
    _KDOSTLSLX-THROW !
    _KDOSTLSLX-CLAIM-STATUS !
    _KDOSTLSLX-CLAIM-STATUS @ DUP IF
        DUP KDOSNET-S-BUSY = IF DROP XIO-STEP-PENDING EXIT THEN
        DUP KDOSNET-S-PLATFORM = IF
            DROP KDOSTLSL-E-PLATFORM
        ELSE
            DROP KDOSTLSL-E-CLEANUP
        THEN _KDOSTLSL-SECONDARY! XIO-STEP-PENDING EXIT
    THEN DROP
    _KDOSTLSLX-THROW @ ?DUP IF
        _KDOSTLSL-THROW>IOR _KDOSTLSL-SECONDARY!
    THEN
    _KDOSTLSLX-RELEASE-STATUS @ ?DUP IF
        _KDOSTLSL-SECONDARY! XIO-STEP-PENDING EXIT
    THEN
    _KDOSTLSLX-RETIRED @ IF
        _KDOSTLSLX-IOR @ _KDOSTLSL-SECONDARY!
        \ The exact lower authority is gone, but the caller's borrowed port
        \ is still RESERVED.  A following cleanup tick returns that record
        \ to RESET before XIO invokes the ordinary wipe callback.
        XIO-STEP-PENDING EXIT
    THEN
    _KDOSTLSLX-THROW @ IF XIO-STEP-PENDING EXIT THEN
    _KDOSTLSLX-IOR @ DUP TLS-E-BUSY = IF
        DROP XIO-STEP-PENDING EXIT
    THEN
    DUP 0= IF DROP TLS-E-TRANSPORT THEN
    _KDOSTLSL-SECONDARY! XIO-STEP-PENDING ;

: _KDOSTLSL-PORT-CLEANUP-STEP  ( -- step-status )
    _KDOSTLSLX-OWNER @ _KDOSTLSL.BORROWED-PORT @ DUP IF
        KDOSTLSP-DISCARD-STEP
        DUP KDOSTLSP-S-OK = IF DROP XIO-STEP-SUCCEEDED EXIT THEN
        DUP KDOSTLSP-S-PENDING = OVER KDOSTLSP-S-BUSY = OR IF
            DROP XIO-STEP-PENDING EXIT
        THEN
        DROP KDOSTLSL-E-CLEANUP _KDOSTLSL-SECONDARY!
        XIO-STEP-PENDING
    ELSE
        DROP XIO-STEP-SUCCEEDED
    THEN ;

: _KDOSTLSL-XIO-CLEANUP-POLL  ( operation owner -- step-status )
    _KDOSTLSL-CALLBACK-BEGIN 0= IF
        KDOSTLSL-E-STATE _KDOSTLSL-SECONDARY!
        XIO-STEP-PENDING EXIT
    THEN
    _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE @
    _KDOSTLSL-PHASE-ADOPTED = IF
        KDOSTLSL-E-STATE _KDOSTLSL-SECONDARY!
        XIO-STEP-PENDING EXIT
    THEN
    _KDOSTLSLX-OWNER @ KDOSNET-OWNER? IF
        _KDOSTLSLX-OWNER @ KDOSNET-RELEASE DUP IF
            _KDOSTLSL-SECONDARY!
        ELSE
            DROP
        THEN
        XIO-STEP-PENDING EXIT
    THEN
    _KDOSTLSL-NORMALIZE-STAGING
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @ OR
    _KDOSTLSLX-OWNER @ _KDOSTLSL.STAGING-SOCKET @ OR IF
        _KDOSTLSL-ABORT-CLEANUP-STEP EXIT
    THEN
    _KDOSTLSL-PORT-CLEANUP-STEP ;

: _KDOSTLSL-XIO-WIPE  ( operation owner -- )
    \ Adoption commits the lower socket to the caller before XIO-TAKE invokes
    \ this callback.  Keep that post-commit branch nonthrowing: TAKE is then
    \ guaranteed not to hide an already-open NIO port behind a wipe failure.
    DUP _KDOSTLSL-VALID? IF
        DUP _KDOSTLSL.PHASE @ _KDOSTLSL-PHASE-ADOPTED = IF
            NIP
            0 OVER _KDOSTLSL.BORROWED-PORT !
            _KDOSTLSL-PHASE-IDLE SWAP _KDOSTLSL.PHASE !
            EXIT
        THEN
    THEN
    _KDOSTLSL-CALLBACK-BEGIN 0= IF KDOSTLSL-E-STATE THROW THEN
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX @
    _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN @ OR IF
        KDOSTLSL-E-CLEANUP THROW
    THEN
    _KDOSTLSLX-OWNER @ _KDOSTLSL.STAGING-SOCKET @ IF
        KDOSTLSL-E-CLEANUP THROW
    THEN
    _KDOSTLSLX-OWNER @ _KDOSTLSL.BORROWED-PORT @ ?DUP IF
        KDOSTLSP.STATE @ KDOSTLSP-STATE-RESET <> IF
            KDOSTLSL-E-CLEANUP THROW
        THEN
    THEN
    0 _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX !
    0 _KDOSTLSLX-OWNER @ _KDOSTLSL.CTX-GEN !
    0 _KDOSTLSLX-OWNER @ _KDOSTLSL.STAGING-SOCKET !
    0 _KDOSTLSLX-OWNER @ _KDOSTLSL.BORROWED-PORT !
    _KDOSTLSL-PHASE-IDLE _KDOSTLSLX-OWNER @ _KDOSTLSL.PHASE ! ;

\ ---------------------------------------------------------------------
\ Persistent owner submission and publication
\ ---------------------------------------------------------------------

VARIABLE _KDOSTLSLA-PORT
VARIABLE _KDOSTLSLA-OWNER
VARIABLE _KDOSTLSLA-XIO
VARIABLE _KDOSTLSLA-PORT-STATUS

: _KDOSTLSL-ACCEPT-GEOMETRY?  ( -- flag )
    _KDOSTLSLA-PORT @ KDOSTLSP-SIZE MSPAN-NONWRAPPING?
    _KDOSTLSLA-OWNER @ KDOSTLSL-SIZE
    _KDOSTLSLA-PORT @ KDOSTLSP-SIZE MSPAN-OVERLAP? 0= AND
    _KDOSTLSLA-OWNER @ _KDOSTLSL.XIO-SERVICE @ XIO-SERVICE-SIZE
    _KDOSTLSLA-PORT @ KDOSTLSP-SIZE MSPAN-OVERLAP? 0= AND ;

: _KDOSTLSL-ROLLBACK-ACCEPT  ( status -- status )
    _KDOSTLSLA-XIO !
    _KDOSTLSLA-PORT @ KDOSTLSP-UNRESERVE
    DUP KDOSTLSP-S-OK <> IF
        _KDOSTLSL-PORT>STATUS EXIT
    THEN DROP
    0 _KDOSTLSLA-OWNER @ _KDOSTLSL.BORROWED-PORT !
    _KDOSTLSL-PHASE-IDLE _KDOSTLSLA-OWNER @ _KDOSTLSL.PHASE !
    _KDOSTLSLA-OWNER @ _KDOSTLSL.XIO-OP XIO-OP-INIT
    _KDOSTLSLA-XIO @ ;

: KDOSTLSL-ACCEPT  ( fresh-shared-port owner -- status )
    _KDOSTLSLA-OWNER ! _KDOSTLSLA-PORT !
    COREID 0<> IF KDOSTLSL-S-PLATFORM EXIT THEN
    _KDOSTLSLX-IN-CALL @ IF KDOSTLSL-S-BUSY EXIT THEN
    _KDOSTLSLA-OWNER @ _KDOSTLSL-VALID? 0= IF
        KDOSTLSL-S-INVALID EXIT
    THEN
    _KDOSTLSLA-OWNER @ _KDOSTLSL-SERVICE-READY? 0= IF
        KDOSTLSL-S-NOT-OWNER EXIT
    THEN
    _KDOSTLSLA-OWNER @ _KDOSTLSL-IDLE? 0= IF
        KDOSTLSL-S-BUSY EXIT
    THEN
    _KDOSTLSLA-PORT @ 0= IF KDOSTLSL-S-INVALID EXIT THEN
    _KDOSTLSL-ACCEPT-GEOMETRY? 0= IF KDOSTLSL-S-INVALID EXIT THEN
    _KDOSTLSLA-OWNER @ _KDOSTLSL.REQUEST-GEN @
    _KDOSTLSL-CELL-MAX >= IF KDOSTLSL-S-STATE EXIT THEN
    _KDOSTLSLA-PORT @ KDOSTLSP-RESERVE DUP _KDOSTLSLA-PORT-STATUS !
    KDOSTLSP-S-OK <> IF
        _KDOSTLSLA-PORT-STATUS @ _KDOSTLSL-PORT>STATUS EXIT
    THEN
    _KDOSTLSLA-OWNER @ _KDOSTLSL.REQUEST-GEN @ 1+
    _KDOSTLSLA-OWNER @ _KDOSTLSL.REQUEST-GEN !
    _KDOSTLSLA-PORT @ _KDOSTLSLA-OWNER @
    _KDOSTLSL.BORROWED-PORT !
    0 _KDOSTLSLA-OWNER @ _KDOSTLSL.TERMINAL !
    _KDOSTLSL-PHASE-LISTENER-POLL
    _KDOSTLSLA-OWNER @ _KDOSTLSL.PHASE !
    _KDOSTLSLA-OWNER @ _KDOSTLSL.XIO-SERVICE @
    _KDOSTLSLA-OWNER @
    _KDOSTLSLA-OWNER @ _KDOSTLSL.OWNER-GEN @
    _KDOSTLSLA-OWNER @ _KDOSTLSL.REQUEST-GEN @ 0
    _KDOSTLSLA-OWNER @
    ['] _KDOSTLSL-XIO-START ['] _KDOSTLSL-XIO-POLL
    ['] _KDOSTLSL-XIO-CANCEL ['] _KDOSTLSL-XIO-WIPE
    _KDOSTLSLA-OWNER @ _KDOSTLSL.XIO-OP XIO-OP-CONFIGURE
    DUP XIO-S-OK <> IF
        _KDOSTLSL-XIO>STATUS _KDOSTLSL-ROLLBACK-ACCEPT EXIT
    THEN DROP
    _KDOSTLSLA-OWNER @ _KDOSTLSL.XIO-SERVICE @
    _KDOSTLSLA-OWNER @
    _KDOSTLSLA-OWNER @ _KDOSTLSL.OWNER-GEN @
    _KDOSTLSLA-OWNER @ _KDOSTLSL.REQUEST-GEN @
    ['] _KDOSTLSL-XIO-CLEANUP-POLL
    _KDOSTLSLA-OWNER @ _KDOSTLSL.XIO-OP XIO-OP-CONFIGURE-CLEANUP
    DUP XIO-S-OK <> IF
        _KDOSTLSL-XIO>STATUS _KDOSTLSL-ROLLBACK-ACCEPT EXIT
    THEN DROP
    _KDOSTLSLA-OWNER @ _KDOSTLSL.XIO-SERVICE @
    _KDOSTLSLA-OWNER @ _KDOSTLSL.XIO-OP XIO-SUBMIT
    DUP XIO-S-OK <> IF
        _KDOSTLSL-XIO>STATUS _KDOSTLSL-ROLLBACK-ACCEPT EXIT
    THEN DROP
    KDOSTLSL-S-OK ;

: _KDOSTLSL-RETRY-ERROR?  ( ior -- flag )
    DUP TLS-E-WOULD-BLOCK =
    OVER TLS-E-BUSY = OR
    SWAP KDOSTLSL-E-CONTENTION = OR ;

: _KDOSTLSL-TERMINAL-STATUS  ( owner -- status )
    DUP _KDOSTLSL.XIO-OP XIOO.STATE @ CASE
        XIO-STATE-CANCELLED OF DROP KDOSTLSL-S-CANCELLED ENDOF
        XIO-STATE-TIMED-OUT OF DROP KDOSTLSL-S-TIMED-OUT ENDOF
        XIO-STATE-FAILED OF
            DUP _KDOSTLSL.XIO-OP XIOO.CLEANUP-ERROR @ IF
                DROP KDOSTLSL-S-LOWER EXIT
            THEN
            _KDOSTLSL.XIO-OP XIOO.ERROR @ DUP
            KDOSTLSL-E-PLATFORM = IF DROP KDOSTLSL-S-PLATFORM EXIT THEN
            DUP KDOSTLSL-E-STATE = IF DROP KDOSTLSL-S-STATE EXIT THEN
            _KDOSTLSL-RETRY-ERROR? IF
                KDOSTLSL-S-RETRY
            ELSE
                KDOSTLSL-S-LOWER
            THEN
        ENDOF
        DROP KDOSTLSL-S-STATE SWAP
    ENDCASE ;

VARIABLE _KDOSTLSLS-OWNER
VARIABLE _KDOSTLSLS-STATE
VARIABLE _KDOSTLSLS-STATUS
VARIABLE _KDOSTLSLS-PORT
VARIABLE _KDOSTLSLS-NIO
VARIABLE _KDOSTLSLS-TAKE-RESULT

: _KDOSTLSL-RETURN-TERMINAL  ( owner -- port|0 status )
    DUP _KDOSTLSL.TERMINAL @ DUP _KDOSTLSLS-STATUS !
    0= IF DROP 0 KDOSTLSL-S-STATE EXIT THEN
    0 SWAP _KDOSTLSL.TERMINAL !
    0 _KDOSTLSLS-STATUS @ ;

: _KDOSTLSL-CONSUME-TERMINAL  ( owner -- port|0 status )
    DUP _KDOSTLSLS-OWNER !
    DUP _KDOSTLSL-TERMINAL-STATUS
    OVER _KDOSTLSL.TERMINAL !
    DUP _KDOSTLSL.XIO-SERVICE @
    SWAP _KDOSTLSL.XIO-OP XIO-RESET
    DUP XIO-S-OK = IF
        DROP _KDOSTLSLS-OWNER @ _KDOSTLSL-RETURN-TERMINAL EXIT
    THEN
    DUP XIO-S-PENDING = IF DROP 0 KDOSTLSL-S-PENDING EXIT THEN
    _KDOSTLSL-XIO>STATUS 0 SWAP ;

: _KDOSTLSL-DISCARD-RETAINED  ( terminal-status owner -- port|0 status )
    DUP _KDOSTLSLS-OWNER ! _KDOSTLSL.TERMINAL !
    _KDOSTLSLS-OWNER @ _KDOSTLSL.XIO-SERVICE @
    _KDOSTLSLS-OWNER @ _KDOSTLSL.XIO-OP XIO-RESET
    DUP XIO-S-OK = IF
        DROP _KDOSTLSLS-OWNER @ _KDOSTLSL-RETURN-TERMINAL EXIT
    THEN
    DUP XIO-S-PENDING = IF DROP 0 KDOSTLSL-S-PENDING EXIT THEN
    _KDOSTLSL-XIO>STATUS 0 SWAP ;

: _KDOSTLSL-TAKE-ADOPTED  ( owner -- port|0 status )
    _KDOSTLSLS-OWNER !
    _KDOSTLSLS-OWNER @ _KDOSTLSL.BORROWED-PORT @
    DUP _KDOSTLSLS-PORT ! KDOSTLSP.PORT _KDOSTLSLS-NIO !
    _KDOSTLSLS-OWNER @ _KDOSTLSL.XIO-SERVICE @
    _KDOSTLSLS-OWNER @
    _KDOSTLSLS-OWNER @ _KDOSTLSL.OWNER-GEN @
    _KDOSTLSLS-OWNER @ _KDOSTLSL.REQUEST-GEN @
    _KDOSTLSLS-OWNER @ _KDOSTLSL.XIO-OP XIO-TAKE
    _KDOSTLSLS-STATUS ! _KDOSTLSLS-TAKE-RESULT !
    _KDOSTLSLS-STATUS @ XIO-S-OK <> IF
        0 _KDOSTLSLS-STATUS @ _KDOSTLSL-XIO>STATUS EXIT
    THEN
    \ Authority was committed by ADOPT-OPEN before TAKE.  Exact result and
    \ wipe invariants were validated before this point; never hide the open
    \ port merely because a corrupted XIO result cell disagrees afterward.
    _KDOSTLSLS-NIO @ KDOSTLSL-S-OK ;

: _KDOSTLSL-ADOPT-SUCCESS  ( owner -- port|0 status )
    DUP _KDOSTLSLS-OWNER !
    DUP _KDOSTLSL.PHASE @ _KDOSTLSL-PHASE-ADOPTED = IF
        DROP _KDOSTLSLS-OWNER @ _KDOSTLSL-TAKE-ADOPTED EXIT
    THEN
    DUP _KDOSTLSL.PHASE @ _KDOSTLSL-PHASE-PUBLISHED <>
    OVER _KDOSTLSL.BORROWED-PORT @ 0= OR IF
        DROP KDOSTLSL-S-STATE _KDOSTLSLS-OWNER @
        _KDOSTLSL-DISCARD-RETAINED EXIT
    THEN
    DUP _KDOSTLSL.CTX @
    OVER _KDOSTLSL.CTX-GEN @ OR
    OVER _KDOSTLSL.STAGING-SOCKET @ OR IF
        DROP KDOSTLSL-S-STATE _KDOSTLSLS-OWNER @
        _KDOSTLSL-DISCARD-RETAINED EXIT
    THEN
    DUP _KDOSTLSL.BORROWED-PORT @ DUP _KDOSTLSLS-PORT !
    OVER _KDOSTLSL.XIO-OP XIOO.RESULT @ <>
    _KDOSTLSLS-PORT @ KDOSTLSP.STATE @
        KDOSTLSP-STATE-PUBLISHED <> OR
    _KDOSTLSLS-PORT @ KDOSTLSP.SOCKET-SD @ 0= OR IF
        DROP KDOSTLSL-S-STATE _KDOSTLSLS-OWNER @
        _KDOSTLSL-DISCARD-RETAINED EXIT
    THEN DROP
    _KDOSTLSLS-PORT @ KDOSTLSP-ADOPT-OPEN
    _KDOSTLSLS-STATUS ! _KDOSTLSLS-NIO !
    _KDOSTLSLS-STATUS @ KDOSTLSP-S-OK <> IF
        _KDOSTLSLS-STATUS @ DUP KDOSTLSP-S-PENDING =
        SWAP KDOSTLSP-S-BUSY = OR IF
            0 KDOSTLSL-S-PENDING EXIT
        THEN
        _KDOSTLSLS-STATUS @ _KDOSTLSL-PORT>STATUS
        _KDOSTLSLS-OWNER @ _KDOSTLSL-DISCARD-RETAINED EXIT
    THEN
    _KDOSTLSL-PHASE-ADOPTED
    _KDOSTLSLS-OWNER @ _KDOSTLSL.PHASE !
    _KDOSTLSLS-OWNER @ _KDOSTLSL-TAKE-ADOPTED ;

: _KDOSTLSL-ACTIVE-TOPOLOGY?  ( owner -- flag )
    >R
    R@ _KDOSTLSL.XIO-SERVICE @ XIOS.ACTIVE @
    R@ _KDOSTLSL.XIO-OP =
    R@ _KDOSTLSL.XIO-SERVICE @ XIOS.RETAINED @ 0= AND
    R> _KDOSTLSL-XIO-EXACT? AND ;

: _KDOSTLSL-SUCCESS-TOPOLOGY?  ( owner -- flag )
    DUP _KDOSTLSL.XIO-SERVICE @ XIOS.ACTIVE @ 0=
    OVER _KDOSTLSL.XIO-SERVICE @ XIOS.RETAINED @
    2 PICK _KDOSTLSL.XIO-OP = AND
    SWAP _KDOSTLSL-XIO-EXACT? AND ;

: _KDOSTLSL-CLEANUP-TOPOLOGY?  ( owner -- flag )
    >R
    R@ _KDOSTLSL.XIO-SERVICE @ XIOS.ACTIVE @
    R@ _KDOSTLSL.XIO-OP =
    R@ _KDOSTLSL.XIO-SERVICE @ XIOS.RETAINED @ DUP 0=
    SWAP R@ _KDOSTLSL.XIO-OP = OR AND
    R> _KDOSTLSL-XIO-EXACT? AND ;

: KDOSTLSL-STEP  ( owner -- nio-port|0 status )
    _KDOSTLSLS-OWNER !
    COREID 0<> IF 0 KDOSTLSL-S-PLATFORM EXIT THEN
    _KDOSTLSLX-IN-CALL @ IF 0 KDOSTLSL-S-BUSY EXIT THEN
    _KDOSTLSLS-OWNER @ _KDOSTLSL-VALID? 0= IF
        0 KDOSTLSL-S-INVALID EXIT
    THEN
    _KDOSTLSLS-OWNER @ _KDOSTLSL-SERVICE-READY? 0= IF
        0 KDOSTLSL-S-NOT-OWNER EXIT
    THEN
    _KDOSTLSLS-OWNER @ _KDOSTLSL.XIO-OP XIO-CLEANUP-PENDING? IF
        _KDOSTLSLS-OWNER @ _KDOSTLSL-CLEANUP-TOPOLOGY? 0= IF
            0 KDOSTLSL-S-STATE EXIT
        THEN
        _KDOSTLSLS-OWNER @ _KDOSTLSL.XIO-SERVICE @ XIO-TICK
        0 KDOSTLSL-S-PENDING EXIT
    THEN
    _KDOSTLSLS-OWNER @ _KDOSTLSL.XIO-OP XIOO.STATE @
    DUP _KDOSTLSLS-STATE !
    XIO-STATE-RESET = IF
        _KDOSTLSLS-OWNER @ _KDOSTLSL.TERMINAL @ IF
            _KDOSTLSLS-OWNER @ _KDOSTLSL-RETURN-TERMINAL
        ELSE
            0 KDOSTLSL-S-STATE
        THEN EXIT
    THEN
    _KDOSTLSLS-STATE @ XIO-STATE-ACTIVE = IF
        _KDOSTLSLS-OWNER @ _KDOSTLSL-ACTIVE-TOPOLOGY? 0= IF
            0 KDOSTLSL-S-STATE EXIT
        THEN
        _KDOSTLSLS-OWNER @ _KDOSTLSL.XIO-SERVICE @ XIO-TICK
        \ One public STEP performs at most one lower handshake or cleanup
        \ operation.  Adoption/terminal consumption therefore begins on the
        \ following cooperative call even if this tick just completed XIO.
        0 KDOSTLSL-S-PENDING EXIT
    THEN
    _KDOSTLSLS-STATE @ XIO-STATE-SUCCEEDED = IF
        _KDOSTLSLS-OWNER @ _KDOSTLSL-SUCCESS-TOPOLOGY? 0= IF
            0 KDOSTLSL-S-STATE EXIT
        THEN
        _KDOSTLSLS-OWNER @ _KDOSTLSL-ADOPT-SUCCESS EXIT
    THEN
    _KDOSTLSLS-STATE @ DUP XIO-STATE-FAILED =
    OVER XIO-STATE-CANCELLED = OR
    SWAP XIO-STATE-TIMED-OUT = OR IF
        _KDOSTLSLS-OWNER @ _KDOSTLSL-CONSUME-TERMINAL EXIT
    THEN
    0 KDOSTLSL-S-STATE ;

VARIABLE _KDOSTLSLC-OWNER
VARIABLE _KDOSTLSLC-XIO

: KDOSTLSL-CANCEL  ( owner -- status )
    _KDOSTLSLC-OWNER !
    COREID 0<> IF KDOSTLSL-S-PLATFORM EXIT THEN
    _KDOSTLSLX-IN-CALL @ IF KDOSTLSL-S-BUSY EXIT THEN
    _KDOSTLSLC-OWNER @ _KDOSTLSL-VALID? 0= IF
        KDOSTLSL-S-INVALID EXIT
    THEN
    _KDOSTLSLC-OWNER @ _KDOSTLSL-SERVICE-READY? 0= IF
        KDOSTLSL-S-NOT-OWNER EXIT
    THEN
    _KDOSTLSLC-OWNER @ _KDOSTLSL.XIO-OP XIOO.STATE @
    DUP XIO-STATE-ACTIVE = IF
        DROP
        _KDOSTLSLC-OWNER @ _KDOSTLSL-ACTIVE-TOPOLOGY? 0= IF
            KDOSTLSL-S-STATE EXIT
        THEN
        _KDOSTLSLC-OWNER @ _KDOSTLSL.XIO-SERVICE @
        _KDOSTLSLC-OWNER @ _KDOSTLSL.XIO-OP XIO-CANCEL
        DUP _KDOSTLSLC-XIO !
        DUP XIO-S-OK = SWAP XIO-S-PENDING = OR IF
            KDOSTLSL-S-PENDING
        ELSE
            _KDOSTLSLC-XIO @ _KDOSTLSL-XIO>STATUS
        THEN EXIT
    THEN
    DUP XIO-STATE-CANCELLED = IF
        DROP KDOSTLSL-S-CANCELLED EXIT
    THEN
    XIO-STATE-SUCCEEDED = IF
        _KDOSTLSLC-OWNER @ _KDOSTLSL.PHASE @
        _KDOSTLSL-PHASE-ADOPTED = IF KDOSTLSL-S-STATE EXIT THEN
        KDOSTLSL-S-CANCELLED
        _KDOSTLSLC-OWNER @ _KDOSTLSL.TERMINAL !
        _KDOSTLSLC-OWNER @ _KDOSTLSL.XIO-SERVICE @
        _KDOSTLSLC-OWNER @ _KDOSTLSL.XIO-OP XIO-RESET
        DUP XIO-S-OK = IF DROP KDOSTLSL-S-CANCELLED EXIT THEN
        DUP XIO-S-PENDING = IF DROP KDOSTLSL-S-PENDING EXIT THEN
        _KDOSTLSL-XIO>STATUS EXIT
    THEN
    KDOSTLSL-S-STATE ;

: KDOSTLSL-FINI  ( owner -- status )
    COREID 0<> IF DROP KDOSTLSL-S-PLATFORM EXIT THEN
    _KDOSTLSLX-IN-CALL @ IF DROP KDOSTLSL-S-BUSY EXIT THEN
    DUP _KDOSTLSL-VALID? 0= IF DROP KDOSTLSL-S-INVALID EXIT THEN
    DUP _KDOSTLSL-IDLE? 0= IF DROP KDOSTLSL-S-BUSY EXIT THEN
    KDOSTLSL-SIZE 0 FILL KDOSTLSL-S-OK ;
