\ =====================================================================
\  apt1-engine.f -- neutral Akashic APT-1 rich-terminal engine
\ =====================================================================
\
\  This module is an explicitly composed owner of one caller-supplied PT
\  session.  It is not discoverable and contains no consumer or environment
\  policy.  The PT module remains the sole authority for wire framing,
\  session epochs, transaction IDs, revisions, credit, and result ordering.
\
\  Prefix:   RTAPT- (public), _RTAPT- (private)
\  Provider: akashic-tui-rtapt1

PROVIDED akashic-tui-rtapt1

REQUIRE ../../utils/memory-span.f

\ =====================================================================
\  Public status and lifecycle values
\ =====================================================================

0 CONSTANT RTAPT-S-OK
1 CONSTANT RTAPT-S-WOULD-BLOCK
2 CONSTANT RTAPT-S-SESSION-LOST
3 CONSTANT RTAPT-S-INVALID
4 CONSTANT RTAPT-S-UNSUPPORTED
5 CONSTANT RTAPT-S-CAPACITY
6 CONSTANT RTAPT-S-BUSY
7 CONSTANT RTAPT-S-REJECTED

0 CONSTANT RTAPT-OWNER-ST-FREE
1 CONSTANT RTAPT-OWNER-ST-OPEN-QUEUED
2 CONSTANT RTAPT-OWNER-ST-OPENING
3 CONSTANT RTAPT-OWNER-ST-OPEN
4 CONSTANT RTAPT-OWNER-ST-DROP-QUEUED
5 CONSTANT RTAPT-OWNER-ST-DROPPING
6 CONSTANT RTAPT-OWNER-ST-TOMBSTONE
7 CONSTANT RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED
8 CONSTANT RTAPT-OWNER-ST-TOMBSTONE-DROPPING
9 CONSTANT RTAPT-OWNER-ST-QUARANTINED
10 CONSTANT RTAPT-OWNER-ST-DROP-RETRY-QUEUED
11 CONSTANT RTAPT-OWNER-ST-DROP-RETRY-DROPPING
12 CONSTANT RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED
13 CONSTANT RTAPT-OWNER-ST-TOMBSTONE-OPENING

0 CONSTANT RTAPT-UPDATE-IDLE
1 CONSTANT RTAPT-UPDATE-CAPTURING
2 CONSTANT RTAPT-UPDATE-SEALED
3 CONSTANT RTAPT-UPDATE-CELL-OPEN
4 CONSTANT RTAPT-UPDATE-AWAITING

0 CONSTANT RTAPT-COUPLING-NONE
1 CONSTANT RTAPT-COUPLING-CELL
2 CONSTANT RTAPT-COUPLING-RETAINED

1 CONSTANT _RTAPT-OP-REGION-DEFINE
72 CONSTANT _RTAPT-REGION-DEFINE-COPY-SIZE
88 CONSTANT _RTAPT-REGION-DEFINE-FRAME-BYTES

\ The operation record stores a typed operation kind and an offset/length into
\ the separately bounded copy span.  No operation or copy capacity is compiled
\ into the engine.
24 CONSTANT RTAPT-OP-SIZE
144 CONSTANT RTAPT-OWNER-SIZE
64 CONSTANT RTAPT-CONFIG-SIZE
336 CONSTANT RTAPT-ENGINE-SIZE

: RTAPT-CONFIG-BYTES  ( -- bytes )  RTAPT-CONFIG-SIZE ;
: RTAPT-ENGINE-BYTES  ( -- bytes )  RTAPT-ENGINE-SIZE ;
: RTAPT-OWNER-BYTES   ( -- bytes )  RTAPT-OWNER-SIZE ;
: RTAPT-OP-BYTES      ( -- bytes )  RTAPT-OP-SIZE ;

0x5254415054434647 CONSTANT _RTAPT-CONFIG-MAGIC  \ "RTAPTCFG"
0x5254415054454E47 CONSTANT _RTAPT-ENGINE-MAGIC  \ "RTAPTENG"

\ =====================================================================
\  Caller-owned record layouts
\ =====================================================================

\ Configuration is a checked construction record.  This engine profile needs
\ at least one owner slot, one typed-operation slot, and one byte in its copy
\ bank; their upper bounds come only from the caller's nonempty spans.
\ RTAPT-INIT copies all fields, so configuration is not retained or discovered.
: _RTAPT-C.MAGIC      ( c -- a )       ;
: _RTAPT-C.SESSION    ( c -- a )   8 + ;
: _RTAPT-C.OWNERS-A   ( c -- a )  16 + ;
: _RTAPT-C.OWNERS-U   ( c -- a )  24 + ;
: _RTAPT-C.OPS-A      ( c -- a )  32 + ;
: _RTAPT-C.OPS-U      ( c -- a )  40 + ;
: _RTAPT-C.COPY-A     ( c -- a )  48 + ;
: _RTAPT-C.COPY-U     ( c -- a )  56 + ;

\ Owner entries are engine-private after initialization.  NEXT links a
\ caller-capacity-derived FIFO of exact lifecycle requests.  OWNER-USED counts
\ live bindings, in-flight candidates, tombstones, and quarantined evidence;
\ a successful drop releases quota fields but retains its exact tuple.
: _RTAPT-O.STATE      ( o -- a )       ;
: _RTAPT-O.OWNER      ( o -- a )   8 + ;
: _RTAPT-O.GENERATION ( o -- a )  16 + ;
: _RTAPT-O.REGIONS    ( o -- a )  24 + ;
: _RTAPT-O.RESOURCES  ( o -- a )  32 + ;
: _RTAPT-O.OBJECTS    ( o -- a )  40 + ;
: _RTAPT-O.SERIES     ( o -- a )  48 + ;
: _RTAPT-O.RES-BYTES  ( o -- a )  56 + ;
: _RTAPT-O.UTF8-BYTES ( o -- a )  64 + ;
: _RTAPT-O.SAMPLES    ( o -- a )  72 + ;
: _RTAPT-O.WIRE-STATUS ( o -- a ) 80 + ;
: _RTAPT-O.NEXT       ( o -- a )  88 + ;
: _RTAPT-O.PRIOR-GENERATION ( o -- a ) 96 + ;
: _RTAPT-O.ACTIVE-REGIONS ( o -- a ) 104 + ;
: _RTAPT-O.HIDDEN-REGIONS ( o -- a ) 112 + ;
: _RTAPT-O.REGION-HIGH ( o -- a ) 120 + ;
: _RTAPT-O.PENDING-REGIONS ( o -- a ) 128 + ;
: _RTAPT-O.PENDING-REGION-HIGH ( o -- a ) 136 + ;

\ Captured operation records contain no borrowed caller pointer.  COPY-OFF is
\ relative to the engine's caller-owned copy bank and COPY-U is exact for the
\ typed operation kind.
: _RTAPT-P.KIND       ( p -- a )       ;
: _RTAPT-P.COPY-OFF   ( p -- a )   8 + ;
: _RTAPT-P.COPY-U     ( p -- a )  16 + ;

\ REGION_DEFINE is copied as nine native cells.  The PT typed writer performs
\ the normative wire packing; this record is private retry authority only.
: _RTAPT-RD.OWNER      ( r -- a )       ;
: _RTAPT-RD.GENERATION ( r -- a )   8 + ;
: _RTAPT-RD.REGION     ( r -- a )  16 + ;
: _RTAPT-RD.X          ( r -- a )  24 + ;
: _RTAPT-RD.Y          ( r -- a )  32 + ;
: _RTAPT-RD.COLS       ( r -- a )  40 + ;
: _RTAPT-RD.ROWS       ( r -- a )  48 + ;
: _RTAPT-RD.Z          ( r -- a )  56 + ;
: _RTAPT-RD.FLAGS      ( r -- a )  64 + ;

\ Fixed engine metadata is followed by one PT completion descriptor.  The
\ descriptor is part of the engine span and is never exposed as PT authority.
: _RTAPT-E.MAGIC      ( e -- a )       ;
: _RTAPT-E.SESSION    ( e -- a )   8 + ;
: _RTAPT-E.OWNERS-A   ( e -- a )  16 + ;
: _RTAPT-E.OWNERS-U   ( e -- a )  24 + ;
: _RTAPT-E.OWNER-CAP  ( e -- a )  32 + ;
: _RTAPT-E.OWNER-USED ( e -- a )  40 + ;
: _RTAPT-E.OPS-A      ( e -- a )  48 + ;
: _RTAPT-E.OPS-U      ( e -- a )  56 + ;
: _RTAPT-E.OP-CAP     ( e -- a )  64 + ;
: _RTAPT-E.COPY-A     ( e -- a )  72 + ;
: _RTAPT-E.COPY-U     ( e -- a )  80 + ;
: _RTAPT-E.QUEUE-HEAD ( e -- a )  88 + ;
: _RTAPT-E.QUEUE-TAIL ( e -- a )  96 + ;
: _RTAPT-E.ACTIVE-O   ( e -- a ) 104 + ;
: _RTAPT-E.ACTIVE-KIND ( e -- a ) 112 + ;
: _RTAPT-E.UPDATE-STATE ( e -- a ) 120 + ;
: _RTAPT-E.COUPLING   ( e -- a ) 128 + ;
: _RTAPT-E.COLS       ( e -- a ) 136 + ;
: _RTAPT-E.ROWS       ( e -- a ) 144 + ;
: _RTAPT-E.CELL-SPANS ( e -- a ) 152 + ;
: _RTAPT-E.CELLS      ( e -- a ) 160 + ;
: _RTAPT-E.CELL-MODE  ( e -- a ) 168 + ;
: _RTAPT-E.RET-MODE   ( e -- a ) 176 + ;
: _RTAPT-E.DISPOSITION ( e -- a ) 184 + ;
: _RTAPT-E.OP-COUNT   ( e -- a ) 192 + ;
: _RTAPT-E.COPY-USED  ( e -- a ) 200 + ;
: _RTAPT-E.RET-BYTES  ( e -- a ) 208 + ;
: _RTAPT-E.SEND-INDEX ( e -- a ) 216 + ;
: _RTAPT-E.LAST-STATUS ( e -- a ) 224 + ;
: _RTAPT-E.LAST-WIRE  ( e -- a ) 232 + ;
: _RTAPT-E.LAST-DETAIL ( e -- a ) 240 + ;
: _RTAPT-E.LAST-REVISION ( e -- a ) 248 + ;
: _RTAPT-E.COMPLETION ( e -- a ) 256 + ;

0 CONSTANT _RTAPT-ACTIVE-NONE
1 CONSTANT _RTAPT-ACTIVE-OWNER-OPEN
2 CONSTANT _RTAPT-ACTIVE-OWNER-DROP
3 CONSTANT _RTAPT-ACTIVE-OUTPUT
4 CONSTANT _RTAPT-ACTIVE-QUARANTINED

\ =====================================================================
\  Checked storage geometry
\ =====================================================================

: _RTAPT-ALIGNED?  ( a -- flag )  7 AND 0= ;

VARIABLE _RTAPT-CI-C
VARIABLE _RTAPT-CI-S
VARIABLE _RTAPT-CI-OA
VARIABLE _RTAPT-CI-OU
VARIABLE _RTAPT-CI-PA
VARIABLE _RTAPT-CI-PU
VARIABLE _RTAPT-CI-CA
VARIABLE _RTAPT-CI-CU

: _RTAPT-SPAN?  ( a u -- flag )
    OVER 0<> OVER 0> AND 0= IF 2DROP 0 EXIT THEN
    OVER _RTAPT-ALIGNED? 0= IF 2DROP 0 EXIT THEN
    MSPAN-NONWRAPPING? ;

: _RTAPT-CONFIG-RANGES?  ( -- flag )
    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-CI-S @ PT-SESSION-SIZE _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-CI-OA @ _RTAPT-CI-OU @ _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-CI-PA @ _RTAPT-CI-PU @ _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-CI-CA @ _RTAPT-CI-CU @ _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-CI-OU @ RTAPT-OWNER-SIZE MOD IF 0 EXIT THEN
    _RTAPT-CI-PU @ RTAPT-OP-SIZE MOD IF 0 EXIT THEN

    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-CI-S @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-CI-OA @ _RTAPT-CI-OU @ _RTAPT-CI-S @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-CI-PA @ _RTAPT-CI-PU @ _RTAPT-CI-S @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-CI-CA @ _RTAPT-CI-CU @ _RTAPT-CI-S @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN

    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-CI-S @ PT-SESSION-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-CI-OA @ _RTAPT-CI-OU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-CI-PA @ _RTAPT-CI-PU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-CI-CA @ _RTAPT-CI-CU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-S @ PT-SESSION-SIZE _RTAPT-CI-OA @ _RTAPT-CI-OU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-S @ PT-SESSION-SIZE _RTAPT-CI-PA @ _RTAPT-CI-PU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-S @ PT-SESSION-SIZE _RTAPT-CI-CA @ _RTAPT-CI-CU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-OA @ _RTAPT-CI-OU @ _RTAPT-CI-PA @ _RTAPT-CI-PU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-OA @ _RTAPT-CI-OU @ _RTAPT-CI-CA @ _RTAPT-CI-CU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-PA @ _RTAPT-CI-PU @ _RTAPT-CI-CA @ _RTAPT-CI-CU @
        MSPAN-OVERLAP? 0= ;

: RTAPT-CONFIG-INIT  ( session owners-a owners-u ops-a ops-u copy-a copy-u
                        config -- status )
    _RTAPT-CI-C ! _RTAPT-CI-CU ! _RTAPT-CI-CA !
    _RTAPT-CI-PU ! _RTAPT-CI-PA ! _RTAPT-CI-OU ! _RTAPT-CI-OA ! _RTAPT-CI-S !
    _RTAPT-CONFIG-RANGES? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE 0 FILL
    _RTAPT-CONFIG-MAGIC _RTAPT-CI-C @ _RTAPT-C.MAGIC !
    _RTAPT-CI-S @ _RTAPT-CI-C @ _RTAPT-C.SESSION !
    _RTAPT-CI-OA @ _RTAPT-CI-C @ _RTAPT-C.OWNERS-A !
    _RTAPT-CI-OU @ _RTAPT-CI-C @ _RTAPT-C.OWNERS-U !
    _RTAPT-CI-PA @ _RTAPT-CI-C @ _RTAPT-C.OPS-A !
    _RTAPT-CI-PU @ _RTAPT-CI-C @ _RTAPT-C.OPS-U !
    _RTAPT-CI-CA @ _RTAPT-CI-C @ _RTAPT-C.COPY-A !
    _RTAPT-CI-CU @ _RTAPT-CI-C @ _RTAPT-C.COPY-U !
    RTAPT-S-OK ;

: _RTAPT-CONFIG-VALID?  ( c -- flag )
    DUP RTAPT-CONFIG-SIZE _RTAPT-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RTAPT-C.MAGIC @ _RTAPT-CONFIG-MAGIC <> IF DROP 0 EXIT THEN
    DUP _RTAPT-C.SESSION @ _RTAPT-CI-S !
    DUP _RTAPT-C.OWNERS-A @ _RTAPT-CI-OA !
    DUP _RTAPT-C.OWNERS-U @ _RTAPT-CI-OU !
    DUP _RTAPT-C.OPS-A @ _RTAPT-CI-PA !
    DUP _RTAPT-C.OPS-U @ _RTAPT-CI-PU !
    DUP _RTAPT-C.COPY-A @ _RTAPT-CI-CA !
    DUP _RTAPT-C.COPY-U @ _RTAPT-CI-CU !
    _RTAPT-CI-C ! _RTAPT-CONFIG-RANGES? ;

VARIABLE _RTAPT-I-C
VARIABLE _RTAPT-I-E

: _RTAPT-ENGINE-DISJOINT?  ( -- flag )
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-CI-S @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-I-C @ RTAPT-CONFIG-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-CI-S @ PT-SESSION-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-CI-OA @ _RTAPT-CI-OU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-CI-PA @ _RTAPT-CI-PU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-CI-CA @ _RTAPT-CI-CU @
        MSPAN-OVERLAP? 0= ;

: _RTAPT-PT>STATUS  ( pt-status -- status )
    DUP PT-S-OK = IF DROP RTAPT-S-OK EXIT THEN
    DUP PT-S-WOULD-BLOCK = IF DROP RTAPT-S-WOULD-BLOCK EXIT THEN
    DUP PT-S-SESSION-LOST = IF DROP RTAPT-S-SESSION-LOST EXIT THEN
    DUP PT-S-INVALID = IF DROP RTAPT-S-INVALID EXIT THEN
    DUP PT-S-UNSUPPORTED = IF DROP RTAPT-S-UNSUPPORTED EXIT THEN
    DROP RTAPT-S-SESSION-LOST ;

VARIABLE _RTAPT-EV-E
VARIABLE _RTAPT-EV-P

: _RTAPT-ENGINE-RANGES?  ( engine -- flag )
    _RTAPT-EV-E !
    _RTAPT-EV-E @ RTAPT-ENGINE-SIZE _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.SESSION @ PT-SESSION-SIZE
        _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OWNERS-A @
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-U @ _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OPS-A @
        _RTAPT-EV-E @ _RTAPT-E.OPS-U @ _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.COPY-A @
        _RTAPT-EV-E @ _RTAPT-E.COPY-U @ _RTAPT-SPAN? 0= IF 0 EXIT THEN

    _RTAPT-EV-E @ RTAPT-ENGINE-SIZE
        _RTAPT-EV-E @ _RTAPT-E.SESSION @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OWNERS-A @
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-U @
        _RTAPT-EV-E @ _RTAPT-E.SESSION @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OPS-A @
        _RTAPT-EV-E @ _RTAPT-E.OPS-U @
        _RTAPT-EV-E @ _RTAPT-E.SESSION @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.COPY-A @
        _RTAPT-EV-E @ _RTAPT-E.COPY-U @
        _RTAPT-EV-E @ _RTAPT-E.SESSION @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN

    _RTAPT-EV-E @ RTAPT-ENGINE-SIZE
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-A @
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-EV-E @ RTAPT-ENGINE-SIZE
        _RTAPT-EV-E @ _RTAPT-E.OPS-A @
        _RTAPT-EV-E @ _RTAPT-E.OPS-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-EV-E @ RTAPT-ENGINE-SIZE
        _RTAPT-EV-E @ _RTAPT-E.COPY-A @
        _RTAPT-EV-E @ _RTAPT-E.COPY-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OWNERS-A @
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-U @
        _RTAPT-EV-E @ _RTAPT-E.OPS-A @
        _RTAPT-EV-E @ _RTAPT-E.OPS-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OWNERS-A @
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-U @
        _RTAPT-EV-E @ _RTAPT-E.COPY-A @
        _RTAPT-EV-E @ _RTAPT-E.COPY-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OPS-A @
        _RTAPT-EV-E @ _RTAPT-E.OPS-U @
        _RTAPT-EV-E @ _RTAPT-E.COPY-A @
        _RTAPT-EV-E @ _RTAPT-E.COPY-U @ MSPAN-OVERLAP? 0= ;

: _RTAPT-OWNER-POINTER?  ( owner-record engine -- flag )
    >R
    DUP R@ _RTAPT-E.OWNERS-A @ U< IF DROP R> DROP 0 EXIT THEN
    R@ _RTAPT-E.OWNERS-A @ - DUP R@ _RTAPT-E.OWNERS-U @ U< 0= IF
        DROP R> DROP 0 EXIT
    THEN
    RTAPT-OWNER-SIZE MOD 0= R> DROP ;

: _RTAPT-OWNER-POINTER-OR-ZERO?  ( owner-record|0 engine -- flag )
    OVER 0= IF 2DROP -1 EXIT THEN _RTAPT-OWNER-POINTER? ;

: _RTAPT-U32?  ( u -- flag )  0xFFFFFFFF U> 0= ;

: _RTAPT-I32?  ( n -- flag )
    DUP -2147483648 < IF DROP 0 EXIT THEN 2147483647 > 0= ;

: _RTAPT-UADD?  ( a b -- sum flag )
    OVER + DUP ROT U< 0= ;

: _RTAPT-UMUL?  ( a b -- product flag )
    UM* DUP IF 2DROP 0 0 EXIT THEN DROP -1 ;

: _RTAPT-OP-NTH  ( index engine -- op-record )
    _RTAPT-E.OPS-A @ SWAP RTAPT-OP-SIZE * + ;

VARIABLE _RTAPT-BV-E
VARIABLE _RTAPT-BV-STATE
VARIABLE _RTAPT-BV-OFF
VARIABLE _RTAPT-BV-NEXT
VARIABLE _RTAPT-BV-RET
VARIABLE _RTAPT-BV-P

: _RTAPT-CAPTURED-BANKS?  ( engine -- flag )
    DUP _RTAPT-BV-E !
    DUP _RTAPT-E.OP-COUNT @ _RTAPT-U32? 0= IF DROP 0 EXIT THEN
    DUP _RTAPT-E.OP-COUNT @ OVER _RTAPT-E.OP-CAP @ U> IF DROP 0 EXIT THEN
    DUP _RTAPT-E.COPY-USED @ OVER _RTAPT-E.COPY-U @ U> IF DROP 0 EXIT THEN
    DUP _RTAPT-E.SEND-INDEX @ OVER _RTAPT-E.OP-COUNT @ U> IF DROP 0 EXIT THEN
    DROP
    0 _RTAPT-BV-OFF ! 0 _RTAPT-BV-RET !
    _RTAPT-BV-E @ _RTAPT-E.OP-COUNT @ 0 ?DO
        I _RTAPT-BV-E @ _RTAPT-OP-NTH DUP _RTAPT-BV-P !
        _RTAPT-P.KIND @ _RTAPT-OP-REGION-DEFINE <> IF 0 UNLOOP EXIT THEN
        _RTAPT-BV-P @ _RTAPT-P.COPY-OFF @ _RTAPT-BV-OFF @ <>
            IF 0 UNLOOP EXIT THEN
        _RTAPT-BV-P @ _RTAPT-P.COPY-U @
            _RTAPT-REGION-DEFINE-COPY-SIZE <> IF 0 UNLOOP EXIT THEN
        _RTAPT-BV-OFF @ _RTAPT-REGION-DEFINE-COPY-SIZE _RTAPT-UADD?
            0= IF DROP 0 UNLOOP EXIT THEN DUP _RTAPT-BV-NEXT !
        _RTAPT-BV-E @ _RTAPT-E.COPY-USED @ U> IF 0 UNLOOP EXIT THEN
        _RTAPT-BV-NEXT @ _RTAPT-BV-E @ _RTAPT-E.COPY-U @ U>
            IF 0 UNLOOP EXIT THEN
        _RTAPT-BV-NEXT @ _RTAPT-BV-OFF !
        _RTAPT-BV-RET @ _RTAPT-REGION-DEFINE-FRAME-BYTES _RTAPT-UADD?
            0= IF DROP 0 UNLOOP EXIT THEN _RTAPT-BV-RET !
    LOOP
    _RTAPT-BV-OFF @ _RTAPT-BV-E @ _RTAPT-E.COPY-USED @ =
    _RTAPT-BV-RET @ _RTAPT-BV-E @ _RTAPT-E.RET-BYTES @ = AND ;

: _RTAPT-MODE?  ( mode -- flag )
    DUP PT-RET-DELTA U< IF DROP 0 EXIT THEN
    PT-RET-LAYOUT-CONTINUE U> 0= ;

: _RTAPT-DISPOSITION?  ( disposition -- flag )
    DUP PT-COMMIT = SWAP PT-COMMIT-AND-REVEAL = OR ;

: _RTAPT-MODE-DISPOSITION?  ( mode disposition -- flag )
    DUP PT-COMMIT = IF 2DROP -1 EXIT THEN
    PT-COMMIT-AND-REVEAL <> IF DROP 0 EXIT THEN
    DUP PT-RET-REPLACE-CONTINUE =
    SWAP PT-RET-LAYOUT-CONTINUE = OR ;

: _RTAPT-CELL-MODE?  ( mode -- flag )
    DUP PT-CELL-DELTA = SWAP PT-CELL-REPLACE = OR ;

VARIABLE _RTAPT-CV-COLS
VARIABLE _RTAPT-CV-ROWS
VARIABLE _RTAPT-CV-SPANS
VARIABLE _RTAPT-CV-CELLS
VARIABLE _RTAPT-CV-MODE
VARIABLE _RTAPT-CV-MAX

: _RTAPT-CELL-COUNTS?  ( cols rows spans cells cell-mode -- flag )
    _RTAPT-CV-MODE ! _RTAPT-CV-CELLS ! _RTAPT-CV-SPANS !
    _RTAPT-CV-ROWS ! _RTAPT-CV-COLS !
    _RTAPT-CV-COLS @ DUP 0= SWAP _RTAPT-U32? 0= OR IF 0 EXIT THEN
    _RTAPT-CV-ROWS @ DUP 0= SWAP _RTAPT-U32? 0= OR IF 0 EXIT THEN
    _RTAPT-CV-SPANS @ _RTAPT-U32? 0= IF 0 EXIT THEN
    _RTAPT-CV-CELLS @ _RTAPT-U32? 0= IF 0 EXIT THEN
    _RTAPT-CV-MODE @ PT-CELL-NONE = IF
        _RTAPT-CV-SPANS @ 0= _RTAPT-CV-CELLS @ 0= AND EXIT
    THEN
    _RTAPT-CV-MODE @ _RTAPT-CELL-MODE? 0= IF 0 EXIT THEN
    _RTAPT-CV-COLS @ _RTAPT-CV-ROWS @ _RTAPT-UMUL? 0= IF
        DROP 0 EXIT
    THEN DUP _RTAPT-CV-MAX !
    _RTAPT-CV-CELLS @ U< IF 0 EXIT THEN
    _RTAPT-CV-MODE @ PT-CELL-REPLACE = IF
        _RTAPT-CV-SPANS @ _RTAPT-CV-ROWS @ =
        _RTAPT-CV-CELLS @ _RTAPT-CV-MAX @ = AND EXIT
    THEN
    _RTAPT-CV-SPANS @ 0= IF _RTAPT-CV-CELLS @ 0= EXIT THEN
    _RTAPT-CV-CELLS @ _RTAPT-CV-SPANS @ U< IF 0 EXIT THEN
    _RTAPT-CV-SPANS @ _RTAPT-CV-COLS @ _RTAPT-UMUL? 0= IF
        DROP 0 EXIT
    THEN _RTAPT-CV-CELLS @ U< 0= ;

: _RTAPT-ZERO-CELL-GEOMETRY?  ( engine -- flag )
    DUP _RTAPT-E.COLS @ 0=
    OVER _RTAPT-E.ROWS @ 0= AND
    OVER _RTAPT-E.CELL-SPANS @ 0= AND
    OVER _RTAPT-E.CELLS @ 0= AND
    SWAP _RTAPT-E.CELL-MODE @ PT-CELL-NONE = AND ;

: _RTAPT-UPDATE-COHERENT?  ( engine -- flag )
    DUP _RTAPT-BV-E ! _RTAPT-E.UPDATE-STATE @ DUP _RTAPT-BV-STATE !
    RTAPT-UPDATE-AWAITING U> IF 0 EXIT THEN
    _RTAPT-BV-E @ _RTAPT-CAPTURED-BANKS? 0= IF 0 EXIT THEN
    _RTAPT-BV-STATE @ RTAPT-UPDATE-IDLE = IF
        _RTAPT-BV-E @ _RTAPT-E.COUPLING @ RTAPT-COUPLING-NONE =
        _RTAPT-BV-E @ _RTAPT-E.OP-COUNT @ 0= AND
        _RTAPT-BV-E @ _RTAPT-E.COPY-USED @ 0= AND
        _RTAPT-BV-E @ _RTAPT-E.RET-BYTES @ 0= AND
        _RTAPT-BV-E @ _RTAPT-E.SEND-INDEX @ 0= AND
        _RTAPT-BV-E @ _RTAPT-E.RET-MODE @ PT-RET-NONE = AND
        _RTAPT-BV-E @ _RTAPT-E.DISPOSITION @ PT-COMMIT = AND
        _RTAPT-BV-E @ _RTAPT-ZERO-CELL-GEOMETRY? AND EXIT
    THEN
    _RTAPT-BV-STATE @ DUP RTAPT-UPDATE-CAPTURING =
    SWAP RTAPT-UPDATE-SEALED = OR IF
        _RTAPT-BV-E @ _RTAPT-E.COUPLING @ RTAPT-COUPLING-NONE <>
            IF 0 EXIT THEN
        _RTAPT-BV-E @ _RTAPT-E.RET-MODE @ _RTAPT-MODE? 0= IF 0 EXIT THEN
        _RTAPT-BV-E @ _RTAPT-E.RET-MODE @
        _RTAPT-BV-E @ _RTAPT-E.DISPOSITION @
            _RTAPT-MODE-DISPOSITION? 0=
            IF 0 EXIT THEN
        _RTAPT-BV-E @ _RTAPT-E.SEND-INDEX @ IF 0 EXIT THEN
        _RTAPT-BV-E @ _RTAPT-ZERO-CELL-GEOMETRY? 0= IF 0 EXIT THEN
        _RTAPT-BV-STATE @ RTAPT-UPDATE-SEALED = IF
            _RTAPT-BV-E @ _RTAPT-E.RET-MODE @ PT-RET-DELTA =
            _RTAPT-BV-E @ _RTAPT-E.OP-COUNT @ 0= AND IF 0 EXIT THEN
        THEN
        -1 EXIT
    THEN
    _RTAPT-BV-E @ _RTAPT-E.COLS @
    _RTAPT-BV-E @ _RTAPT-E.ROWS @
    _RTAPT-BV-E @ _RTAPT-E.CELL-SPANS @
    _RTAPT-BV-E @ _RTAPT-E.CELLS @
    _RTAPT-BV-E @ _RTAPT-E.CELL-MODE @ _RTAPT-CELL-COUNTS? 0=
        IF 0 EXIT THEN
    _RTAPT-BV-E @ _RTAPT-E.COUPLING @ RTAPT-COUPLING-CELL = IF
        _RTAPT-BV-E @ _RTAPT-E.CELL-MODE @ _RTAPT-CELL-MODE? 0=
            IF 0 EXIT THEN
        _RTAPT-BV-E @ _RTAPT-E.RET-MODE @ PT-RET-NONE = IF
            _RTAPT-BV-E @ _RTAPT-E.OP-COUNT @ 0<> IF 0 EXIT THEN
            _RTAPT-BV-E @ _RTAPT-E.COPY-USED @
            _RTAPT-BV-E @ _RTAPT-E.RET-BYTES @ OR IF 0 EXIT THEN
            _RTAPT-BV-E @ _RTAPT-E.DISPOSITION @ PT-COMMIT <>
                IF 0 EXIT THEN
        ELSE
            _RTAPT-BV-E @ _RTAPT-E.RET-MODE @ _RTAPT-MODE? 0=
                IF 0 EXIT THEN
            _RTAPT-BV-E @ _RTAPT-E.RET-MODE @ PT-RET-DELTA =
            _RTAPT-BV-E @ _RTAPT-E.OP-COUNT @ 0= AND IF 0 EXIT THEN
            _RTAPT-BV-E @ _RTAPT-E.RET-MODE @
            _RTAPT-BV-E @ _RTAPT-E.DISPOSITION @
                _RTAPT-MODE-DISPOSITION? 0=
                IF 0 EXIT THEN
        THEN
    ELSE
        _RTAPT-BV-E @ _RTAPT-E.COUPLING @ RTAPT-COUPLING-RETAINED <>
            IF 0 EXIT THEN
        _RTAPT-BV-E @ _RTAPT-E.CELL-MODE @ PT-CELL-NONE <>
        _RTAPT-BV-E @ _RTAPT-E.CELL-SPANS @ OR
        _RTAPT-BV-E @ _RTAPT-E.CELLS @ OR IF 0 EXIT THEN
        _RTAPT-BV-E @ _RTAPT-E.RET-MODE @ _RTAPT-MODE? 0= IF 0 EXIT THEN
        _RTAPT-BV-E @ _RTAPT-E.RET-MODE @ PT-RET-DELTA =
        _RTAPT-BV-E @ _RTAPT-E.OP-COUNT @ 0= AND IF 0 EXIT THEN
        _RTAPT-BV-E @ _RTAPT-E.RET-MODE @
        _RTAPT-BV-E @ _RTAPT-E.DISPOSITION @
            _RTAPT-MODE-DISPOSITION? 0=
            IF 0 EXIT THEN
    THEN
    _RTAPT-BV-STATE @ RTAPT-UPDATE-AWAITING = IF
        _RTAPT-BV-E @ _RTAPT-E.SEND-INDEX @
        _RTAPT-BV-E @ _RTAPT-E.OP-COUNT @ <> IF 0 EXIT THEN
    THEN
    -1 ;

VARIABLE _RTAPT-LV-E
VARIABLE _RTAPT-LV-PENDING
VARIABLE _RTAPT-LV-O

: _RTAPT-OWNER-LEDGERS?  ( engine -- flag )
    DUP _RTAPT-LV-E ! 0 _RTAPT-LV-PENDING !
    _RTAPT-LV-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-LV-E @ _RTAPT-E.OWNERS-A @ I RTAPT-OWNER-SIZE * +
        DUP _RTAPT-LV-O ! _RTAPT-O.STATE @ RTAPT-OWNER-ST-FREE = IF
            _RTAPT-LV-O @ _RTAPT-O.ACTIVE-REGIONS @
            _RTAPT-LV-O @ _RTAPT-O.HIDDEN-REGIONS @ OR
            _RTAPT-LV-O @ _RTAPT-O.REGION-HIGH @ OR
            _RTAPT-LV-O @ _RTAPT-O.PENDING-REGIONS @ OR
            _RTAPT-LV-O @ _RTAPT-O.PENDING-REGION-HIGH @ OR IF
                0 UNLOOP EXIT
            THEN
        ELSE
            _RTAPT-LV-O @ _RTAPT-O.ACTIVE-REGIONS @
                _RTAPT-LV-O @ _RTAPT-O.REGIONS @ U> IF 0 UNLOOP EXIT THEN
            _RTAPT-LV-O @ _RTAPT-O.HIDDEN-REGIONS @
                _RTAPT-LV-O @ _RTAPT-O.REGIONS @ U> IF 0 UNLOOP EXIT THEN
            _RTAPT-LV-O @ _RTAPT-O.PENDING-REGIONS @ DUP
                _RTAPT-LV-O @ _RTAPT-O.REGIONS @ U> IF DROP 0 UNLOOP EXIT THEN
            _RTAPT-LV-E @ _RTAPT-E.RET-MODE @ DUP PT-RET-DELTA =
            OVER PT-RET-LAYOUT-START = OR IF
                DROP _RTAPT-LV-O @ _RTAPT-O.ACTIVE-REGIONS @
            ELSE PT-RET-REPLACE-START = IF
                0
            ELSE
                _RTAPT-LV-O @ _RTAPT-O.HIDDEN-REGIONS @
            THEN THEN
            OVER _RTAPT-UADD? 0= IF 2DROP 0 UNLOOP EXIT THEN
            _RTAPT-LV-O @ _RTAPT-O.REGIONS @ U> IF DROP 0 UNLOOP EXIT THEN
            DUP 0= IF
                DROP _RTAPT-LV-O @ _RTAPT-O.PENDING-REGION-HIGH @ IF
                    0 UNLOOP EXIT
                THEN
            ELSE
                _RTAPT-LV-O @ _RTAPT-O.PENDING-REGION-HIGH @
                _RTAPT-LV-O @ _RTAPT-O.REGION-HIGH @ U< 0= IF
                    DROP 0 UNLOOP EXIT
                THEN
                _RTAPT-LV-PENDING @ SWAP _RTAPT-UADD? 0= IF
                    DROP 0 UNLOOP EXIT
                THEN _RTAPT-LV-PENDING !
            THEN
        THEN
    LOOP
    _RTAPT-LV-PENDING @ _RTAPT-LV-E @ _RTAPT-E.OP-COUNT @ = ;

VARIABLE _RTAPT-QV-E
VARIABLE _RTAPT-QV-EXPECT
VARIABLE _RTAPT-QV-OK

: _RTAPT-QUARANTINE-COHERENT?  ( engine -- flag )
    DUP _RTAPT-QV-E ! _RTAPT-E.ACTIVE-KIND @
        _RTAPT-ACTIVE-QUARANTINED = _RTAPT-QV-EXPECT !
    -1 _RTAPT-QV-OK !
    _RTAPT-QV-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-QV-E @ _RTAPT-E.OWNERS-A @ I RTAPT-OWNER-SIZE * +
        _RTAPT-O.STATE @ DUP RTAPT-OWNER-ST-FREE = IF
            DROP
        ELSE
            RTAPT-OWNER-ST-QUARANTINED = _RTAPT-QV-EXPECT @ <> IF
                0 _RTAPT-QV-OK !
            THEN
        THEN
    LOOP
    _RTAPT-QV-OK @ ;

: _RTAPT-ENGINE-VALID?  ( e -- flag )
    DUP RTAPT-ENGINE-SIZE _RTAPT-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RTAPT-E.MAGIC @ _RTAPT-ENGINE-MAGIC <> IF DROP 0 EXIT THEN
    DUP _RTAPT-ENGINE-RANGES? 0= IF DROP 0 EXIT THEN
    DUP _RTAPT-E.OWNERS-U @ RTAPT-OWNER-SIZE MOD IF DROP 0 EXIT THEN
    DUP _RTAPT-E.OPS-U @ RTAPT-OP-SIZE MOD IF DROP 0 EXIT THEN
    DUP _RTAPT-E.OWNER-CAP @ OVER _RTAPT-E.OWNERS-U @ RTAPT-OWNER-SIZE / <>
        IF DROP 0 EXIT THEN
    DUP _RTAPT-E.OP-CAP @ OVER _RTAPT-E.OPS-U @ RTAPT-OP-SIZE / <>
        IF DROP 0 EXIT THEN
    DUP _RTAPT-E.OWNER-USED @ OVER _RTAPT-E.OWNER-CAP @ U> IF DROP 0 EXIT THEN
    DUP _RTAPT-UPDATE-COHERENT? 0= IF DROP 0 EXIT THEN
    DUP _RTAPT-OWNER-LEDGERS? 0= IF DROP 0 EXIT THEN
    DUP _RTAPT-QUARANTINE-COHERENT? 0= IF DROP 0 EXIT THEN
    DUP _RTAPT-E.QUEUE-HEAD @ OVER _RTAPT-OWNER-POINTER-OR-ZERO? 0= IF
        DROP 0 EXIT
    THEN
    DUP _RTAPT-E.QUEUE-TAIL @ OVER _RTAPT-OWNER-POINTER-OR-ZERO? 0= IF
        DROP 0 EXIT
    THEN
    DUP _RTAPT-E.ACTIVE-O @ OVER _RTAPT-OWNER-POINTER-OR-ZERO? 0= IF
        DROP 0 EXIT
    THEN
    DUP _RTAPT-E.QUEUE-HEAD @ 0= OVER _RTAPT-E.QUEUE-TAIL @ 0= <> IF
        DROP 0 EXIT
    THEN
    DUP _RTAPT-E.QUEUE-HEAD @ ?DUP IF
        _RTAPT-O.STATE @ DUP RTAPT-OWNER-ST-OPEN-QUEUED =
        OVER RTAPT-OWNER-ST-DROP-QUEUED = OR
        OVER RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED = OR
        OVER RTAPT-OWNER-ST-DROP-RETRY-QUEUED = OR
        SWAP RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED = OR 0= IF
            DROP 0 EXIT
        THEN
    THEN
    DUP _RTAPT-E.QUEUE-TAIL @ ?DUP IF
        _RTAPT-O.STATE @ DUP RTAPT-OWNER-ST-OPEN-QUEUED =
        OVER RTAPT-OWNER-ST-DROP-QUEUED = OR
        OVER RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED = OR
        OVER RTAPT-OWNER-ST-DROP-RETRY-QUEUED = OR
        SWAP RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED = OR 0= IF
            DROP 0 EXIT
        THEN
    THEN
    DUP _RTAPT-E.QUEUE-TAIL @ ?DUP IF _RTAPT-O.NEXT @ IF DROP 0 EXIT THEN THEN
    DUP _RTAPT-E.ACTIVE-KIND @ DUP _RTAPT-ACTIVE-QUARANTINED U> IF
        2DROP 0 EXIT
    THEN
    DUP _RTAPT-ACTIVE-NONE = IF
        DROP
        DUP _RTAPT-E.ACTIVE-O @ IF DROP 0 EXIT THEN
    ELSE DUP _RTAPT-ACTIVE-QUARANTINED = IF
        DROP
        DUP _RTAPT-E.ACTIVE-O @ IF DROP 0 EXIT THEN
        DUP _RTAPT-E.QUEUE-HEAD @ OVER _RTAPT-E.QUEUE-TAIL @ OR IF
            DROP 0 EXIT
        THEN
        DUP _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-IDLE <> IF DROP 0 EXIT THEN
    ELSE DUP _RTAPT-ACTIVE-OUTPUT = IF
        DROP
        DUP _RTAPT-E.ACTIVE-O @ IF DROP 0 EXIT THEN
        DUP _RTAPT-E.QUEUE-HEAD @ OVER _RTAPT-E.QUEUE-TAIL @ OR IF
            DROP 0 EXIT
        THEN
    ELSE
        DROP
        DUP _RTAPT-E.ACTIVE-O @ 0= IF DROP 0 EXIT THEN
    THEN THEN THEN
    DUP _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-OWNER-OPEN = IF
        DUP _RTAPT-E.ACTIVE-O @ _RTAPT-O.STATE @ DUP
            RTAPT-OWNER-ST-OPENING =
        SWAP RTAPT-OWNER-ST-TOMBSTONE-OPENING = OR 0= IF DROP 0 EXIT THEN
    THEN
    DUP _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-OWNER-DROP = IF
        DUP _RTAPT-E.ACTIVE-O @ _RTAPT-O.STATE @ DUP
            RTAPT-OWNER-ST-DROPPING =
        OVER RTAPT-OWNER-ST-TOMBSTONE-DROPPING = OR
        SWAP RTAPT-OWNER-ST-DROP-RETRY-DROPPING = OR 0= IF DROP 0 EXIT THEN
    THEN
    DUP _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-IDLE <> IF
        DUP _RTAPT-E.QUEUE-HEAD @ OVER _RTAPT-E.QUEUE-TAIL @ OR IF
            DROP 0 EXIT
        THEN
        DUP _RTAPT-E.ACTIVE-KIND @ DUP _RTAPT-ACTIVE-NONE =
        SWAP _RTAPT-ACTIVE-OUTPUT = OR
        OVER _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = OR 0= IF
            DROP 0 EXIT
        THEN
    THEN
    DUP _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-AWAITING =
    OVER _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-OUTPUT = <> IF
        DUP _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED <> IF
            DROP 0 EXIT
        THEN
    THEN
    DROP -1 ;

: RTAPT-INIT  ( config engine -- status )
    _RTAPT-I-E ! _RTAPT-I-C !
    _RTAPT-I-C @ _RTAPT-CONFIG-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-ENGINE-DISJOINT? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-I-E @ _RTAPT-E.MAGIC @ _RTAPT-ENGINE-MAGIC = IF
        RTAPT-S-BUSY EXIT
    THEN
    _RTAPT-CI-S @ PT-RETAINED-DISCOVER _RTAPT-PT>STATUS
    DUP RTAPT-S-OK <> IF EXIT THEN DROP

    _RTAPT-CI-OA @ _RTAPT-CI-OU @ 0 FILL
    _RTAPT-CI-PA @ _RTAPT-CI-PU @ 0 FILL
    _RTAPT-CI-CA @ _RTAPT-CI-CU @ 0 FILL
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE 0 FILL
    _RTAPT-CI-S @ _RTAPT-I-E @ _RTAPT-E.SESSION !
    _RTAPT-CI-OA @ _RTAPT-I-E @ _RTAPT-E.OWNERS-A !
    _RTAPT-CI-OU @ _RTAPT-I-E @ _RTAPT-E.OWNERS-U !
    _RTAPT-CI-OU @ RTAPT-OWNER-SIZE /
        _RTAPT-I-E @ _RTAPT-E.OWNER-CAP !
    _RTAPT-CI-PA @ _RTAPT-I-E @ _RTAPT-E.OPS-A !
    _RTAPT-CI-PU @ _RTAPT-I-E @ _RTAPT-E.OPS-U !
    _RTAPT-CI-PU @ RTAPT-OP-SIZE / _RTAPT-I-E @ _RTAPT-E.OP-CAP !
    _RTAPT-CI-CA @ _RTAPT-I-E @ _RTAPT-E.COPY-A !
    _RTAPT-CI-CU @ _RTAPT-I-E @ _RTAPT-E.COPY-U !
    RTAPT-UPDATE-IDLE _RTAPT-I-E @ _RTAPT-E.UPDATE-STATE !
    RTAPT-S-OK _RTAPT-I-E @ _RTAPT-E.LAST-STATUS !
    _RTAPT-ENGINE-MAGIC _RTAPT-I-E @ _RTAPT-E.MAGIC !
    RTAPT-S-OK ;

: RTAPT-STATUS  ( engine -- status )
    DUP _RTAPT-ENGINE-VALID? 0= IF DROP RTAPT-S-INVALID EXIT THEN
    _RTAPT-E.LAST-STATUS @ ;

VARIABLE _RTAPT-QA-E
VARIABLE _RTAPT-QA-STATUS
VARIABLE _RTAPT-QA-O

\ Preserve every committed tuple, quota, high-water, and target ledger while
\ making all bindings unusable.  Uncommitted update/pending authority is
\ discarded, and queue/active reachability is detached before publication of
\ the sticky engine state, so no quarantined request can later reach PT.
: _RTAPT-QUARANTINE-ALL  ( status engine -- status )
    _RTAPT-QA-E ! _RTAPT-QA-STATUS !
    _RTAPT-QA-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-QA-E @ _RTAPT-E.OWNERS-A @ I RTAPT-OWNER-SIZE * +
        DUP _RTAPT-QA-O ! _RTAPT-O.STATE @ RTAPT-OWNER-ST-FREE <> IF
            RTAPT-OWNER-ST-QUARANTINED _RTAPT-QA-O @ _RTAPT-O.STATE !
            0 _RTAPT-QA-O @ _RTAPT-O.NEXT !
            0 _RTAPT-QA-O @ _RTAPT-O.PENDING-REGIONS !
            0 _RTAPT-QA-O @ _RTAPT-O.PENDING-REGION-HIGH !
        THEN
    LOOP
    0 _RTAPT-QA-E @ _RTAPT-E.QUEUE-HEAD !
    0 _RTAPT-QA-E @ _RTAPT-E.QUEUE-TAIL !
    0 _RTAPT-QA-E @ _RTAPT-E.ACTIVE-O !
    RTAPT-UPDATE-IDLE _RTAPT-QA-E @ _RTAPT-E.UPDATE-STATE !
    RTAPT-COUPLING-NONE _RTAPT-QA-E @ _RTAPT-E.COUPLING !
    0 _RTAPT-QA-E @ _RTAPT-E.COLS !
    0 _RTAPT-QA-E @ _RTAPT-E.ROWS !
    0 _RTAPT-QA-E @ _RTAPT-E.CELL-SPANS !
    0 _RTAPT-QA-E @ _RTAPT-E.CELLS !
    PT-CELL-NONE _RTAPT-QA-E @ _RTAPT-E.CELL-MODE !
    PT-RET-NONE _RTAPT-QA-E @ _RTAPT-E.RET-MODE !
    PT-COMMIT _RTAPT-QA-E @ _RTAPT-E.DISPOSITION !
    0 _RTAPT-QA-E @ _RTAPT-E.OP-COUNT !
    0 _RTAPT-QA-E @ _RTAPT-E.COPY-USED !
    0 _RTAPT-QA-E @ _RTAPT-E.RET-BYTES !
    0 _RTAPT-QA-E @ _RTAPT-E.SEND-INDEX !
    _RTAPT-ACTIVE-QUARANTINED _RTAPT-QA-E @ _RTAPT-E.ACTIVE-KIND !
    _RTAPT-QA-STATUS @ DUP _RTAPT-QA-E @ _RTAPT-E.LAST-STATUS ! ;

: _RTAPT-SESSION-ENDED?  ( engine -- flag )
    _RTAPT-E.SESSION @ DUP PT-STATE@ PT-ST-ANSI =
    SWAP PT-OWNS? 0= AND ;

: _RTAPT-READY-STATUS  ( engine -- status )
    DUP _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
        _RTAPT-E.LAST-STATUS @ EXIT
    THEN
    DUP _RTAPT-E.SESSION @ PT-STATE@ PT-ST-LOST = IF
        RTAPT-S-SESSION-LOST SWAP _RTAPT-QUARANTINE-ALL EXIT
    THEN
    DUP _RTAPT-E.OWNER-USED @
    OVER _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-IDLE <> OR
    OVER _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-OUTPUT = OR IF
        DUP _RTAPT-SESSION-ENDED? IF
            RTAPT-S-SESSION-LOST SWAP _RTAPT-QUARANTINE-ALL EXIT
        THEN
    THEN
    _RTAPT-E.SESSION @ PT-RETAINED-STATE@
    DUP PT-RET-ST-AVAILABLE = IF DROP RTAPT-S-OK EXIT THEN
    PT-RET-ST-CELL-ONLY = IF RTAPT-S-UNSUPPORTED ELSE
        RTAPT-S-WOULD-BLOCK
    THEN ;

: RTAPT-FINI  ( engine -- status )
    DUP _RTAPT-ENGINE-VALID? 0= IF DROP RTAPT-S-INVALID EXIT THEN
    \ Live PT ownership keeps exact tombstone/quarantine evidence resident.
    \ Only a synchronized ANSI boundary with this session unowned proves that
    \ all remote generations are gone and permits local record erasure.
    DUP _RTAPT-E.OWNER-USED @
    OVER _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-NONE <> OR
    OVER _RTAPT-E.QUEUE-HEAD @ OR OVER _RTAPT-E.QUEUE-TAIL @ OR
    OVER _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-IDLE <> OR IF
        DUP _RTAPT-SESSION-ENDED? 0= IF DROP RTAPT-S-BUSY EXIT THEN
    THEN
    DUP _RTAPT-E.OWNERS-A @ OVER _RTAPT-E.OWNERS-U @ 0 FILL
    DUP _RTAPT-E.OPS-A @ OVER _RTAPT-E.OPS-U @ 0 FILL
    DUP _RTAPT-E.COPY-A @ OVER _RTAPT-E.COPY-U @ 0 FILL
    RTAPT-ENGINE-SIZE 0 FILL RTAPT-S-OK ;

\ =====================================================================
\  Exact owner lifecycle queue
\ =====================================================================

: _RTAPT-OWNER-NTH  ( index engine -- owner-record )
    _RTAPT-E.OWNERS-A @ SWAP RTAPT-OWNER-SIZE * + ;

VARIABLE _RTAPT-OF-E
VARIABLE _RTAPT-OF-OWNER
VARIABLE _RTAPT-OF-GEN
VARIABLE _RTAPT-OF-RESULT

: _RTAPT-OWNER-FIND  ( owner generation engine -- owner-record|0 )
    _RTAPT-OF-E ! _RTAPT-OF-GEN ! _RTAPT-OF-OWNER !
    0 _RTAPT-OF-RESULT !
    _RTAPT-OF-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        I _RTAPT-OF-E @ _RTAPT-OWNER-NTH DUP _RTAPT-O.STATE @
        RTAPT-OWNER-ST-FREE <> IF
            DUP _RTAPT-O.OWNER @ _RTAPT-OF-OWNER @ =
            OVER _RTAPT-O.GENERATION @ _RTAPT-OF-GEN @ = AND IF
                _RTAPT-OF-RESULT !
            ELSE DROP THEN
        ELSE DROP THEN
    LOOP
    _RTAPT-OF-RESULT @ ;

: _RTAPT-OWNER-ID-FIND  ( owner engine -- owner-record|0 )
    _RTAPT-OF-E ! _RTAPT-OF-OWNER ! 0 _RTAPT-OF-RESULT !
    _RTAPT-OF-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-OF-RESULT @ 0= IF
            I _RTAPT-OF-E @ _RTAPT-OWNER-NTH DUP _RTAPT-O.STATE @
            RTAPT-OWNER-ST-FREE <> IF
                DUP _RTAPT-O.OWNER @ _RTAPT-OF-OWNER @ = IF
                    _RTAPT-OF-RESULT !
                ELSE DROP THEN
            ELSE DROP THEN
        THEN
    LOOP
    _RTAPT-OF-RESULT @ ;

: _RTAPT-OWNER-FREE-SLOT  ( engine -- owner-record|0 )
    DUP _RTAPT-OF-E ! 0 _RTAPT-OF-RESULT !
    _RTAPT-OF-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-OF-RESULT @ 0= IF
            I _RTAPT-OF-E @ _RTAPT-OWNER-NTH DUP _RTAPT-O.STATE @
            RTAPT-OWNER-ST-FREE = IF _RTAPT-OF-RESULT ! ELSE DROP THEN
        THEN
    LOOP
    DROP _RTAPT-OF-RESULT @ ;

VARIABLE _RTAPT-Q-O
VARIABLE _RTAPT-Q-E

: _RTAPT-QUEUE-PUSH  ( owner-record engine -- )
    _RTAPT-Q-E ! _RTAPT-Q-O !
    0 _RTAPT-Q-O @ _RTAPT-O.NEXT !
    _RTAPT-Q-E @ _RTAPT-E.QUEUE-TAIL @ ?DUP IF
        _RTAPT-Q-O @ SWAP _RTAPT-O.NEXT !
    ELSE
        _RTAPT-Q-O @ _RTAPT-Q-E @ _RTAPT-E.QUEUE-HEAD !
    THEN
    _RTAPT-Q-O @ _RTAPT-Q-E @ _RTAPT-E.QUEUE-TAIL ! ;

: _RTAPT-QUEUE-POP  ( engine -- owner-record|0 )
    DUP _RTAPT-Q-E ! _RTAPT-E.QUEUE-HEAD @ DUP 0= IF EXIT THEN
    DUP _RTAPT-O.NEXT @ _RTAPT-Q-E @ _RTAPT-E.QUEUE-HEAD !
    _RTAPT-Q-E @ _RTAPT-E.QUEUE-HEAD @ 0= IF
        0 _RTAPT-Q-E @ _RTAPT-E.QUEUE-TAIL !
    THEN
    0 OVER _RTAPT-O.NEXT ! ;

VARIABLE _RTAPT-OO-E
VARIABLE _RTAPT-OO-O
VARIABLE _RTAPT-OO-OWNER
VARIABLE _RTAPT-OO-GEN
VARIABLE _RTAPT-OO-RQ
VARIABLE _RTAPT-OO-XQ
VARIABLE _RTAPT-OO-OQ
VARIABLE _RTAPT-OO-SQ
VARIABLE _RTAPT-OO-RBQ
VARIABLE _RTAPT-OO-UQ
VARIABLE _RTAPT-OO-SLQ
VARIABLE _RTAPT-OO-REUSED
VARIABLE _RTAPT-OO-PRIOR-GEN

: RTAPT-OWNER-OPEN  ( owner generation region-q resource-q object-q series-q
                       resource-byte-q utf8-byte-q sample-slot-q engine
                       -- status )
    _RTAPT-OO-E ! _RTAPT-OO-SLQ ! _RTAPT-OO-UQ ! _RTAPT-OO-RBQ !
    _RTAPT-OO-SQ ! _RTAPT-OO-OQ ! _RTAPT-OO-XQ ! _RTAPT-OO-RQ !
    _RTAPT-OO-GEN ! _RTAPT-OO-OWNER !
    _RTAPT-OO-E @ _RTAPT-ENGINE-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-OO-E @ _RTAPT-READY-STATUS DUP RTAPT-S-OK <> IF EXIT THEN DROP
    _RTAPT-OO-E @ _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-IDLE <> IF
        RTAPT-S-BUSY EXIT
    THEN
    _RTAPT-OO-OWNER @ 0= _RTAPT-OO-GEN @ 0= OR IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-OO-RQ @ 0xFFFFFFFF U>
    _RTAPT-OO-XQ @ 0xFFFFFFFF U> OR
    _RTAPT-OO-OQ @ 0xFFFFFFFF U> OR
    _RTAPT-OO-SQ @ 0xFFFFFFFF U> OR IF RTAPT-S-INVALID EXIT THEN
    0 _RTAPT-OO-REUSED !
    0 _RTAPT-OO-PRIOR-GEN !
    _RTAPT-OO-OWNER @ _RTAPT-OO-E @ _RTAPT-OWNER-ID-FIND ?DUP IF
        DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-TOMBSTONE <> IF
            DROP RTAPT-S-BUSY EXIT
        THEN
        DUP _RTAPT-O.GENERATION @ _RTAPT-OO-GEN @ U< 0= IF
            DROP RTAPT-S-BUSY EXIT
        THEN
        DUP _RTAPT-O.GENERATION @ _RTAPT-OO-PRIOR-GEN !
        _RTAPT-OO-O ! -1 _RTAPT-OO-REUSED !
    ELSE
        _RTAPT-OO-E @ _RTAPT-OWNER-FREE-SLOT DUP 0= IF
            DROP RTAPT-S-CAPACITY EXIT
        THEN _RTAPT-OO-O !
    THEN
    _RTAPT-OO-O @ RTAPT-OWNER-SIZE 0 FILL
    _RTAPT-OO-OWNER @ _RTAPT-OO-O @ _RTAPT-O.OWNER !
    _RTAPT-OO-GEN @ _RTAPT-OO-O @ _RTAPT-O.GENERATION !
    _RTAPT-OO-RQ @ _RTAPT-OO-O @ _RTAPT-O.REGIONS !
    _RTAPT-OO-XQ @ _RTAPT-OO-O @ _RTAPT-O.RESOURCES !
    _RTAPT-OO-OQ @ _RTAPT-OO-O @ _RTAPT-O.OBJECTS !
    _RTAPT-OO-SQ @ _RTAPT-OO-O @ _RTAPT-O.SERIES !
    _RTAPT-OO-RBQ @ _RTAPT-OO-O @ _RTAPT-O.RES-BYTES !
    _RTAPT-OO-UQ @ _RTAPT-OO-O @ _RTAPT-O.UTF8-BYTES !
    _RTAPT-OO-SLQ @ _RTAPT-OO-O @ _RTAPT-O.SAMPLES !
    _RTAPT-OO-PRIOR-GEN @ _RTAPT-OO-O @ _RTAPT-O.PRIOR-GENERATION !
    _RTAPT-OO-REUSED @ IF RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED
        ELSE RTAPT-OWNER-ST-OPEN-QUEUED THEN
    _RTAPT-OO-O @ _RTAPT-O.STATE !
    _RTAPT-OO-REUSED @ 0= IF 1 _RTAPT-OO-E @ _RTAPT-E.OWNER-USED +! THEN
    _RTAPT-OO-O @ _RTAPT-OO-E @ _RTAPT-QUEUE-PUSH
    RTAPT-S-OK _RTAPT-OO-E @ _RTAPT-E.LAST-STATUS !
    RTAPT-S-OK ;

: RTAPT-OWNER-STATE@  ( owner generation engine -- owner-state status )
    DUP _RTAPT-ENGINE-VALID? 0= IF 2DROP DROP RTAPT-OWNER-ST-FREE
        RTAPT-S-INVALID EXIT
    THEN
    DUP _RTAPT-READY-STATUS DROP
    _RTAPT-OWNER-FIND DUP 0= IF
        DROP RTAPT-OWNER-ST-FREE
        _RTAPT-OF-E @ _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
            _RTAPT-OF-E @ _RTAPT-E.LAST-STATUS @
        ELSE RTAPT-S-OK THEN EXIT
    THEN
    _RTAPT-O.STATE @ DUP RTAPT-OWNER-ST-QUARANTINED = IF
        _RTAPT-OF-E @ _RTAPT-E.LAST-STATUS @
    ELSE RTAPT-S-OK THEN ;

VARIABLE _RTAPT-OD-E
VARIABLE _RTAPT-OD-O
VARIABLE _RTAPT-OD-STATE

: RTAPT-OWNER-DROP  ( owner generation engine -- status )
    DUP _RTAPT-OD-E !
    DUP _RTAPT-ENGINE-VALID? 0= IF 2DROP DROP RTAPT-S-INVALID EXIT THEN
    DUP _RTAPT-READY-STATUS DUP RTAPT-S-OK <> IF
        >R 2DROP DROP R> EXIT
    THEN DROP
    DUP _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-IDLE <> IF
        2DROP DROP RTAPT-S-BUSY EXIT
    THEN
    _RTAPT-OWNER-FIND DUP 0= IF DROP RTAPT-S-INVALID EXIT THEN
    DUP _RTAPT-OD-O ! _RTAPT-O.STATE @ DUP _RTAPT-OD-STATE !
    DUP RTAPT-OWNER-ST-OPEN = IF
        DROP RTAPT-OWNER-ST-DROP-QUEUED
    ELSE DUP RTAPT-OWNER-ST-TOMBSTONE = IF
        DROP RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED
    ELSE RTAPT-OWNER-ST-DROPPING = IF
        _RTAPT-OD-O @ _RTAPT-O.WIRE-STATUS @ DUP PT-TX-RESULT-INVALID =
        SWAP PT-TX-RESULT-STALE = OR 0= IF RTAPT-S-BUSY EXIT THEN
        RTAPT-OWNER-ST-DROP-RETRY-QUEUED
    ELSE RTAPT-S-BUSY EXIT THEN THEN THEN
    _RTAPT-OD-O @ _RTAPT-O.STATE !
    _RTAPT-OD-O @ _RTAPT-OD-E @ _RTAPT-QUEUE-PUSH
    RTAPT-S-OK _RTAPT-OD-E @ _RTAPT-E.LAST-STATUS !
    RTAPT-S-OK ;

\ =====================================================================
\  Caller-bounded retained candidate capture
\ =====================================================================

VARIABLE _RTAPT-BC-E

: _RTAPT-PENDING-CLEAR  ( engine -- )
    DUP _RTAPT-BC-E !
    _RTAPT-BC-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-BC-E @ _RTAPT-E.OWNERS-A @ I RTAPT-OWNER-SIZE * +
        DUP _RTAPT-O.PENDING-REGIONS OFF
        _RTAPT-O.PENDING-REGION-HIGH OFF
    LOOP DROP ;

: _RTAPT-UPDATE-METADATA-CLEAR  ( engine -- )
    DUP _RTAPT-E.UPDATE-STATE OFF
    DUP _RTAPT-E.COUPLING OFF
    DUP _RTAPT-E.COLS OFF
    DUP _RTAPT-E.ROWS OFF
    DUP _RTAPT-E.CELL-SPANS OFF
    DUP _RTAPT-E.CELLS OFF
    DUP _RTAPT-E.CELL-MODE OFF
    DUP _RTAPT-E.RET-MODE OFF
    DUP _RTAPT-E.DISPOSITION OFF
    DUP _RTAPT-E.OP-COUNT OFF
    DUP _RTAPT-E.COPY-USED OFF
    DUP _RTAPT-E.RET-BYTES OFF
    _RTAPT-E.SEND-INDEX OFF ;

: _RTAPT-CANDIDATE-DISCARD  ( engine -- )
    DUP _RTAPT-BC-E !
    DUP _RTAPT-E.OPS-A @ OVER _RTAPT-E.OP-COUNT @ RTAPT-OP-SIZE * 0 FILL
    DUP _RTAPT-E.COPY-A @ OVER _RTAPT-E.COPY-USED @ 0 FILL
    DUP _RTAPT-PENDING-CLEAR
    _RTAPT-UPDATE-METADATA-CLEAR ;

: _RTAPT-WIRE-REWIND  ( engine -- )
    DUP _RTAPT-E.COUPLING OFF
    DUP _RTAPT-E.COLS OFF
    DUP _RTAPT-E.ROWS OFF
    DUP _RTAPT-E.CELL-SPANS OFF
    DUP _RTAPT-E.CELLS OFF
    DUP _RTAPT-E.CELL-MODE OFF
    DUP _RTAPT-E.SEND-INDEX OFF
    DUP _RTAPT-E.RET-MODE @ PT-RET-NONE = IF
        _RTAPT-CANDIDATE-DISCARD
    ELSE
        RTAPT-UPDATE-SEALED SWAP _RTAPT-E.UPDATE-STATE !
    THEN ;

: RTAPT-USES-SESSION?  ( session engine -- flag )
    DUP _RTAPT-ENGINE-VALID? 0= IF 2DROP 0 EXIT THEN
    _RTAPT-E.SESSION @ = ;

VARIABLE _RTAPT-SD-A
VARIABLE _RTAPT-SD-U
VARIABLE _RTAPT-SD-E

: RTAPT-STORAGE-DISJOINT?  ( a u engine -- flag )
    _RTAPT-SD-E ! _RTAPT-SD-U ! _RTAPT-SD-A !
    _RTAPT-SD-E @ _RTAPT-ENGINE-VALID? 0= IF 0 EXIT THEN
    _RTAPT-SD-A @ _RTAPT-SD-U @ _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-SD-A @ _RTAPT-SD-U @ _RTAPT-SD-E @ _RTAPT-E.SESSION @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-SD-A @ _RTAPT-SD-U @ _RTAPT-SD-E @ RTAPT-ENGINE-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-SD-A @ _RTAPT-SD-U @
        _RTAPT-SD-E @ _RTAPT-E.OWNERS-A @
        _RTAPT-SD-E @ _RTAPT-E.OWNERS-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-SD-A @ _RTAPT-SD-U @
        _RTAPT-SD-E @ _RTAPT-E.OPS-A @
        _RTAPT-SD-E @ _RTAPT-E.OPS-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-SD-A @ _RTAPT-SD-U @
        _RTAPT-SD-E @ _RTAPT-E.COPY-A @
        _RTAPT-SD-E @ _RTAPT-E.COPY-U @ MSPAN-OVERLAP? 0= ;

: RTAPT-UPDATE-STATE@  ( engine -- update-state status )
    DUP _RTAPT-ENGINE-VALID? 0= IF
        DROP RTAPT-UPDATE-IDLE RTAPT-S-INVALID EXIT
    THEN
    DUP _RTAPT-E.UPDATE-STATE @ SWAP _RTAPT-E.LAST-STATUS @ ;

VARIABLE _RTAPT-RB-E
VARIABLE _RTAPT-RB-MODE

: RTAPT-RICH-BEGIN  ( retained-mode engine -- status )
    _RTAPT-RB-E ! _RTAPT-RB-MODE !
    _RTAPT-RB-E @ _RTAPT-ENGINE-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RB-E @ _RTAPT-READY-STATUS DUP RTAPT-S-OK <> IF EXIT THEN DROP
    _RTAPT-RB-E @ _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-IDLE <>
        IF RTAPT-S-BUSY EXIT THEN
    _RTAPT-RB-E @ _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-NONE <>
    _RTAPT-RB-E @ _RTAPT-E.QUEUE-HEAD @ OR
    _RTAPT-RB-E @ _RTAPT-E.QUEUE-TAIL @ OR IF RTAPT-S-BUSY EXIT THEN
    _RTAPT-RB-MODE @ _RTAPT-MODE? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RB-MODE @ _RTAPT-RB-E @ _RTAPT-E.RET-MODE !
    PT-COMMIT _RTAPT-RB-E @ _RTAPT-E.DISPOSITION !
    RTAPT-UPDATE-CAPTURING _RTAPT-RB-E @ _RTAPT-E.UPDATE-STATE !
    RTAPT-S-OK DUP _RTAPT-RB-E @ _RTAPT-E.LAST-STATUS ! ;

VARIABLE _RTAPT-RD-E
VARIABLE _RTAPT-RD-O
VARIABLE _RTAPT-RD-P
VARIABLE _RTAPT-RD-COPY
VARIABLE _RTAPT-RD-OWNER
VARIABLE _RTAPT-RD-GEN
VARIABLE _RTAPT-RD-ID
VARIABLE _RTAPT-RD-X
VARIABLE _RTAPT-RD-Y
VARIABLE _RTAPT-RD-COLS
VARIABLE _RTAPT-RD-ROWS
VARIABLE _RTAPT-RD-Z
VARIABLE _RTAPT-RD-FLAGS
VARIABLE _RTAPT-RD-NEXT-COPY
VARIABLE _RTAPT-RD-NEXT-RET
VARIABLE _RTAPT-RD-NEXT-PENDING
VARIABLE _RTAPT-RD-BASE

: _RTAPT-REGION-BASE  ( owner-record engine -- count )
    _RTAPT-RD-E ! _RTAPT-RD-O !
    _RTAPT-RD-E @ _RTAPT-E.RET-MODE @ DUP PT-RET-DELTA =
    OVER PT-RET-LAYOUT-START = OR IF
        DROP _RTAPT-RD-O @ _RTAPT-O.ACTIVE-REGIONS @ EXIT
    THEN
    PT-RET-REPLACE-START = IF 0 EXIT THEN
    _RTAPT-RD-O @ _RTAPT-O.HIDDEN-REGIONS @ ;

: RTAPT-REGION-DEFINE  ( owner generation region x y cols rows z flags engine
                           -- status )
    _RTAPT-RD-E ! _RTAPT-RD-FLAGS ! _RTAPT-RD-Z ! _RTAPT-RD-ROWS !
    _RTAPT-RD-COLS ! _RTAPT-RD-Y ! _RTAPT-RD-X ! _RTAPT-RD-ID !
    _RTAPT-RD-GEN ! _RTAPT-RD-OWNER !
    _RTAPT-RD-E @ _RTAPT-ENGINE-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RD-E @ _RTAPT-READY-STATUS DUP RTAPT-S-OK <> IF EXIT THEN DROP
    _RTAPT-RD-E @ _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-CAPTURING <>
        IF RTAPT-S-BUSY EXIT THEN
    _RTAPT-RD-OWNER @ 0= _RTAPT-RD-GEN @ 0= OR
    _RTAPT-RD-ID @ 0= OR IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RD-X @ _RTAPT-U32? 0= _RTAPT-RD-Y @ _RTAPT-U32? 0= OR
    _RTAPT-RD-COLS @ _RTAPT-U32? 0= OR
    _RTAPT-RD-ROWS @ _RTAPT-U32? 0= OR IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RD-COLS @ 0= _RTAPT-RD-ROWS @ 0= OR IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RD-X @ _RTAPT-RD-COLS @ _RTAPT-UADD? 0= IF
        DROP RTAPT-S-INVALID EXIT
    THEN 0xFFFFFFFF U> IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RD-Y @ _RTAPT-RD-ROWS @ _RTAPT-UADD? 0= IF
        DROP RTAPT-S-INVALID EXIT
    THEN 0xFFFFFFFF U> IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RD-Z @ _RTAPT-I32? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RD-FLAGS @ 3 INVERT AND IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RD-OWNER @ _RTAPT-RD-GEN @ _RTAPT-RD-E @
        _RTAPT-OWNER-FIND DUP 0= IF DROP RTAPT-S-INVALID EXIT THEN
    DUP _RTAPT-RD-O ! _RTAPT-O.STATE @ RTAPT-OWNER-ST-OPEN <>
        IF RTAPT-S-BUSY EXIT THEN
    _RTAPT-RD-ID @ _RTAPT-RD-O @ _RTAPT-O.REGION-HIGH @ U> 0=
        IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RD-ID @ _RTAPT-RD-O @ _RTAPT-O.PENDING-REGION-HIGH @ U> 0=
        IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RD-O @ _RTAPT-RD-E @ _RTAPT-REGION-BASE _RTAPT-RD-BASE !
    _RTAPT-RD-BASE @ _RTAPT-RD-O @ _RTAPT-O.PENDING-REGIONS @
        _RTAPT-UADD? 0= IF DROP RTAPT-S-CAPACITY EXIT THEN
    1 _RTAPT-UADD? 0= IF DROP RTAPT-S-CAPACITY EXIT THEN
    DUP _RTAPT-RD-NEXT-PENDING !
    _RTAPT-RD-O @ _RTAPT-O.REGIONS @ U> IF RTAPT-S-CAPACITY EXIT THEN
    \ PRESENT_BEGIN carries retained-op-count as an exact u32 wire field.
    _RTAPT-RD-E @ _RTAPT-E.OP-COUNT @ 0xFFFFFFFF U< 0=
        IF RTAPT-S-CAPACITY EXIT THEN
    _RTAPT-RD-E @ _RTAPT-E.OP-COUNT @
        _RTAPT-RD-E @ _RTAPT-E.OP-CAP @ U< 0= IF RTAPT-S-CAPACITY EXIT THEN
    _RTAPT-RD-E @ _RTAPT-E.COPY-U @
        _RTAPT-RD-E @ _RTAPT-E.COPY-USED @ -
        _RTAPT-REGION-DEFINE-COPY-SIZE U< IF RTAPT-S-CAPACITY EXIT THEN
    _RTAPT-RD-E @ _RTAPT-E.COPY-USED @
        _RTAPT-REGION-DEFINE-COPY-SIZE _RTAPT-UADD? 0= IF
        DROP RTAPT-S-CAPACITY EXIT
    THEN _RTAPT-RD-NEXT-COPY !
    _RTAPT-RD-E @ _RTAPT-E.RET-BYTES @
        _RTAPT-REGION-DEFINE-FRAME-BYTES _RTAPT-UADD? 0= IF
        DROP RTAPT-S-CAPACITY EXIT
    THEN _RTAPT-RD-NEXT-RET !
    _RTAPT-RD-E @ _RTAPT-E.OP-COUNT @ _RTAPT-RD-E @ _RTAPT-OP-NTH
        _RTAPT-RD-P !
    _RTAPT-RD-E @ _RTAPT-E.COPY-A @
        _RTAPT-RD-E @ _RTAPT-E.COPY-USED @ + _RTAPT-RD-COPY !
    _RTAPT-OP-REGION-DEFINE _RTAPT-RD-P @ _RTAPT-P.KIND !
    _RTAPT-RD-E @ _RTAPT-E.COPY-USED @
        _RTAPT-RD-P @ _RTAPT-P.COPY-OFF !
    _RTAPT-REGION-DEFINE-COPY-SIZE _RTAPT-RD-P @ _RTAPT-P.COPY-U !
    _RTAPT-RD-OWNER @ _RTAPT-RD-COPY @ _RTAPT-RD.OWNER !
    _RTAPT-RD-GEN @ _RTAPT-RD-COPY @ _RTAPT-RD.GENERATION !
    _RTAPT-RD-ID @ _RTAPT-RD-COPY @ _RTAPT-RD.REGION !
    _RTAPT-RD-X @ _RTAPT-RD-COPY @ _RTAPT-RD.X !
    _RTAPT-RD-Y @ _RTAPT-RD-COPY @ _RTAPT-RD.Y !
    _RTAPT-RD-COLS @ _RTAPT-RD-COPY @ _RTAPT-RD.COLS !
    _RTAPT-RD-ROWS @ _RTAPT-RD-COPY @ _RTAPT-RD.ROWS !
    _RTAPT-RD-Z @ _RTAPT-RD-COPY @ _RTAPT-RD.Z !
    _RTAPT-RD-FLAGS @ _RTAPT-RD-COPY @ _RTAPT-RD.FLAGS !
    _RTAPT-RD-O @ _RTAPT-O.PENDING-REGIONS @ 1+
        _RTAPT-RD-O @ _RTAPT-O.PENDING-REGIONS !
    _RTAPT-RD-ID @ _RTAPT-RD-O @ _RTAPT-O.PENDING-REGION-HIGH !
    1 _RTAPT-RD-E @ _RTAPT-E.OP-COUNT +!
    _RTAPT-RD-NEXT-COPY @ _RTAPT-RD-E @ _RTAPT-E.COPY-USED !
    _RTAPT-RD-NEXT-RET @ _RTAPT-RD-E @ _RTAPT-E.RET-BYTES !
    RTAPT-S-OK DUP _RTAPT-RD-E @ _RTAPT-E.LAST-STATUS ! ;

VARIABLE _RTAPT-RS-E
VARIABLE _RTAPT-RS-DISPOSITION

: RTAPT-RICH-SEAL  ( disposition engine -- status )
    _RTAPT-RS-E ! _RTAPT-RS-DISPOSITION !
    _RTAPT-RS-E @ _RTAPT-ENGINE-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RS-E @ _RTAPT-READY-STATUS DUP RTAPT-S-OK <> IF EXIT THEN DROP
    _RTAPT-RS-E @ _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-CAPTURING <>
        IF RTAPT-S-BUSY EXIT THEN
    _RTAPT-RS-E @ _RTAPT-E.RET-MODE @ _RTAPT-RS-DISPOSITION @
        _RTAPT-MODE-DISPOSITION? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RS-E @ _RTAPT-E.RET-MODE @ PT-RET-DELTA =
    _RTAPT-RS-E @ _RTAPT-E.OP-COUNT @ 0= AND IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-RS-DISPOSITION @ _RTAPT-RS-E @ _RTAPT-E.DISPOSITION !
    RTAPT-UPDATE-SEALED _RTAPT-RS-E @ _RTAPT-E.UPDATE-STATE !
    RTAPT-S-OK DUP _RTAPT-RS-E @ _RTAPT-E.LAST-STATUS ! ;

: RTAPT-RICH-CANCEL  ( engine -- status )
    DUP _RTAPT-ENGINE-VALID? 0= IF DROP RTAPT-S-INVALID EXIT THEN
    DUP _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
        _RTAPT-E.LAST-STATUS @ EXIT
    THEN
    DUP _RTAPT-E.UPDATE-STATE @ DUP RTAPT-UPDATE-IDLE = IF
        DROP RTAPT-S-OK DUP ROT _RTAPT-E.LAST-STATUS ! EXIT
    THEN
    DUP RTAPT-UPDATE-CAPTURING = SWAP RTAPT-UPDATE-SEALED = OR 0= IF
        DROP RTAPT-S-BUSY EXIT
    THEN
    DUP _RTAPT-CANDIDATE-DISCARD
    RTAPT-S-OK DUP ROT _RTAPT-E.LAST-STATUS ! ;

VARIABLE _RTAPT-PF-E
VARIABLE _RTAPT-PF-COLS
VARIABLE _RTAPT-PF-ROWS
VARIABLE _RTAPT-PF-O
VARIABLE _RTAPT-PF-P
VARIABLE _RTAPT-PF-COPY
VARIABLE _RTAPT-PF-COUNT
VARIABLE _RTAPT-PF-TOTAL
VARIABLE _RTAPT-PF-HIGH

: _RTAPT-REGION-COPY-SHAPE?  ( copy cols rows -- flag )
    _RTAPT-PF-ROWS ! _RTAPT-PF-COLS ! _RTAPT-PF-COPY !
    _RTAPT-PF-COPY @ _RTAPT-RD.OWNER @ 0=
    _RTAPT-PF-COPY @ _RTAPT-RD.GENERATION @ 0= OR
    _RTAPT-PF-COPY @ _RTAPT-RD.REGION @ 0= OR IF 0 EXIT THEN
    _RTAPT-PF-COPY @ _RTAPT-RD.X @ _RTAPT-U32? 0=
    _RTAPT-PF-COPY @ _RTAPT-RD.Y @ _RTAPT-U32? 0= OR
    _RTAPT-PF-COPY @ _RTAPT-RD.COLS @ _RTAPT-U32? 0= OR
    _RTAPT-PF-COPY @ _RTAPT-RD.ROWS @ _RTAPT-U32? 0= OR IF 0 EXIT THEN
    _RTAPT-PF-COPY @ _RTAPT-RD.COLS @ 0=
    _RTAPT-PF-COPY @ _RTAPT-RD.ROWS @ 0= OR IF 0 EXIT THEN
    _RTAPT-PF-COPY @ _RTAPT-RD.X @
    _RTAPT-PF-COPY @ _RTAPT-RD.COLS @ _RTAPT-UADD? 0= IF
        DROP 0 EXIT
    THEN _RTAPT-PF-COLS @ U> IF 0 EXIT THEN
    _RTAPT-PF-COPY @ _RTAPT-RD.Y @
    _RTAPT-PF-COPY @ _RTAPT-RD.ROWS @ _RTAPT-UADD? 0= IF
        DROP 0 EXIT
    THEN _RTAPT-PF-ROWS @ U> IF 0 EXIT THEN
    _RTAPT-PF-COPY @ _RTAPT-RD.Z @ _RTAPT-I32? 0= IF 0 EXIT THEN
    _RTAPT-PF-COPY @ _RTAPT-RD.FLAGS @ 3 INVERT AND 0= ;

: _RTAPT-CANDIDATE-PREFLIGHT?  ( cols rows engine -- flag )
    _RTAPT-PF-E ! _RTAPT-PF-ROWS ! _RTAPT-PF-COLS !
    0 _RTAPT-PF-TOTAL !
    _RTAPT-PF-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-PF-E @ _RTAPT-E.OWNERS-A @ I RTAPT-OWNER-SIZE * +
        DUP _RTAPT-PF-O ! _RTAPT-O.REGION-HIGH @ _RTAPT-PF-HIGH !
        0 _RTAPT-PF-COUNT !
        _RTAPT-PF-E @ _RTAPT-E.OP-COUNT @ 0 ?DO
            I _RTAPT-PF-E @ _RTAPT-OP-NTH DUP _RTAPT-PF-P !
            _RTAPT-P.COPY-OFF @ _RTAPT-PF-E @ _RTAPT-E.COPY-A @ +
                DUP _RTAPT-PF-COPY !
            DUP _RTAPT-RD.OWNER @ _RTAPT-PF-O @ _RTAPT-O.OWNER @ =
            SWAP _RTAPT-RD.GENERATION @
                _RTAPT-PF-O @ _RTAPT-O.GENERATION @ = AND IF
                _RTAPT-PF-O @ _RTAPT-O.STATE @ RTAPT-OWNER-ST-OPEN <>
                    IF 0 UNLOOP UNLOOP EXIT THEN
                _RTAPT-PF-COPY @ _RTAPT-PF-COLS @ _RTAPT-PF-ROWS @
                    _RTAPT-REGION-COPY-SHAPE? 0= IF
                    0 UNLOOP UNLOOP EXIT
                THEN
                _RTAPT-PF-COPY @ _RTAPT-RD.REGION @
                    _RTAPT-PF-HIGH @ U> 0= IF 0 UNLOOP UNLOOP EXIT THEN
                _RTAPT-PF-COPY @ _RTAPT-RD.REGION @ _RTAPT-PF-HIGH !
                1 _RTAPT-PF-COUNT +! 1 _RTAPT-PF-TOTAL +!
            THEN
        LOOP
        _RTAPT-PF-COUNT @ _RTAPT-PF-O @ _RTAPT-O.PENDING-REGIONS @ <>
            IF 0 UNLOOP EXIT THEN
        _RTAPT-PF-COUNT @ IF
            _RTAPT-PF-HIGH @
            _RTAPT-PF-O @ _RTAPT-O.PENDING-REGION-HIGH @ <> IF
                0 UNLOOP EXIT
            THEN
        THEN
    LOOP
    _RTAPT-PF-TOTAL @ _RTAPT-PF-E @ _RTAPT-E.OP-COUNT @ = ;

VARIABLE _RTAPT-CB-E
VARIABLE _RTAPT-CB-COLS
VARIABLE _RTAPT-CB-ROWS
VARIABLE _RTAPT-CB-SPANS
VARIABLE _RTAPT-CB-CELLS
VARIABLE _RTAPT-CB-MODE
VARIABLE _RTAPT-CB-STATE
VARIABLE _RTAPT-CB-STATUS

: RTAPT-CELL-BEGIN  ( cols rows span-count cell-count cell-mode engine
                        -- status )
    _RTAPT-CB-E ! _RTAPT-CB-MODE ! _RTAPT-CB-CELLS ! _RTAPT-CB-SPANS !
    _RTAPT-CB-ROWS ! _RTAPT-CB-COLS !
    _RTAPT-CB-E @ _RTAPT-ENGINE-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-CB-E @ _RTAPT-READY-STATUS DUP RTAPT-S-OK <> IF EXIT THEN DROP
    _RTAPT-CB-E @ _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-NONE <>
    _RTAPT-CB-E @ _RTAPT-E.QUEUE-HEAD @ OR
    _RTAPT-CB-E @ _RTAPT-E.QUEUE-TAIL @ OR IF RTAPT-S-BUSY EXIT THEN
    _RTAPT-CB-E @ _RTAPT-E.UPDATE-STATE @ DUP _RTAPT-CB-STATE !
    DUP RTAPT-UPDATE-IDLE = SWAP RTAPT-UPDATE-SEALED = OR 0= IF
        RTAPT-S-BUSY EXIT
    THEN
    _RTAPT-CB-COLS @ _RTAPT-CB-ROWS @ _RTAPT-CB-SPANS @ _RTAPT-CB-CELLS @
        _RTAPT-CB-MODE @ _RTAPT-CELL-COUNTS? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-CB-MODE @ PT-CELL-NONE =
    _RTAPT-CB-STATE @ RTAPT-UPDATE-SEALED <> AND IF
        RTAPT-S-INVALID EXIT
    THEN
    _RTAPT-CB-STATE @ RTAPT-UPDATE-SEALED = IF
        _RTAPT-CB-COLS @ _RTAPT-CB-ROWS @ _RTAPT-CB-E @
            _RTAPT-CANDIDATE-PREFLIGHT? 0= IF RTAPT-S-INVALID EXIT THEN
        _RTAPT-CB-COLS @ _RTAPT-CB-ROWS @
        _RTAPT-CB-SPANS @ _RTAPT-CB-CELLS @
        _RTAPT-CB-E @ _RTAPT-E.OP-COUNT @
        _RTAPT-CB-E @ _RTAPT-E.RET-BYTES @
        _RTAPT-CB-MODE @ _RTAPT-CB-E @ _RTAPT-E.RET-MODE @
        _RTAPT-CB-E @ _RTAPT-E.SESSION @ PT-PRESENT-BEGIN _RTAPT-PT>STATUS
    ELSE
        _RTAPT-CB-COLS @ _RTAPT-CB-ROWS @
        _RTAPT-CB-SPANS @ _RTAPT-CB-CELLS @ 0 0
        _RTAPT-CB-MODE @ PT-RET-NONE
        _RTAPT-CB-E @ _RTAPT-E.SESSION @ PT-PRESENT-BEGIN _RTAPT-PT>STATUS
    THEN
    DUP _RTAPT-CB-STATUS ! RTAPT-S-OK <> IF
        _RTAPT-CB-STATUS @ RTAPT-S-SESSION-LOST = IF
            RTAPT-S-SESSION-LOST _RTAPT-CB-E @ _RTAPT-QUARANTINE-ALL EXIT
        THEN
        _RTAPT-CB-STATUS @ DUP _RTAPT-CB-E @ _RTAPT-E.LAST-STATUS ! EXIT
    THEN
    _RTAPT-CB-STATE @ RTAPT-UPDATE-IDLE = IF
        PT-RET-NONE _RTAPT-CB-E @ _RTAPT-E.RET-MODE !
        PT-COMMIT _RTAPT-CB-E @ _RTAPT-E.DISPOSITION !
    THEN
    _RTAPT-CB-MODE @ PT-CELL-NONE = IF RTAPT-COUPLING-RETAINED
        ELSE RTAPT-COUPLING-CELL THEN
        _RTAPT-CB-E @ _RTAPT-E.COUPLING !
    _RTAPT-CB-COLS @ _RTAPT-CB-E @ _RTAPT-E.COLS !
    _RTAPT-CB-ROWS @ _RTAPT-CB-E @ _RTAPT-E.ROWS !
    _RTAPT-CB-SPANS @ _RTAPT-CB-E @ _RTAPT-E.CELL-SPANS !
    _RTAPT-CB-CELLS @ _RTAPT-CB-E @ _RTAPT-E.CELLS !
    _RTAPT-CB-MODE @ _RTAPT-CB-E @ _RTAPT-E.CELL-MODE !
    0 _RTAPT-CB-E @ _RTAPT-E.SEND-INDEX !
    RTAPT-UPDATE-CELL-OPEN _RTAPT-CB-E @ _RTAPT-E.UPDATE-STATE !
    RTAPT-S-OK DUP _RTAPT-CB-E @ _RTAPT-E.LAST-STATUS ! ;

VARIABLE _RTAPT-CW-E
VARIABLE _RTAPT-CW-STATUS
VARIABLE _RTAPT-CW-V0
VARIABLE _RTAPT-CW-V1
VARIABLE _RTAPT-CW-V2
VARIABLE _RTAPT-CW-V3

: _RTAPT-CELL-FEED-READY?  ( engine -- flag )
    DUP _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-CELL-OPEN =
    SWAP _RTAPT-E.COUPLING @ RTAPT-COUPLING-CELL = AND ;

: _RTAPT-FEED-RESULT  ( status engine -- status )
    _RTAPT-CW-E ! DUP _RTAPT-CW-STATUS !
    DUP RTAPT-S-SESSION-LOST = IF
        DROP RTAPT-S-SESSION-LOST _RTAPT-CW-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    DUP _RTAPT-CW-E @ _RTAPT-E.LAST-STATUS ! ;

: RTAPT-CELL-SPAN-BEGIN  ( row col count engine -- status )
    _RTAPT-CW-E ! _RTAPT-CW-V2 ! _RTAPT-CW-V1 ! _RTAPT-CW-V0 !
    _RTAPT-CW-E @ _RTAPT-ENGINE-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-CW-E @ _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
        _RTAPT-CW-E @ _RTAPT-E.LAST-STATUS @ EXIT
    THEN
    _RTAPT-CW-E @ _RTAPT-CELL-FEED-READY? 0= IF RTAPT-S-BUSY EXIT THEN
    _RTAPT-CW-V0 @ _RTAPT-CW-V1 @ _RTAPT-CW-V2 @
        _RTAPT-CW-E @ _RTAPT-E.SESSION @ PT-SPAN-BEGIN _RTAPT-PT>STATUS
        _RTAPT-CW-E @ _RTAPT-FEED-RESULT ;

: RTAPT-CELL-WRITE  ( codepoint fg bg attrs engine -- status )
    _RTAPT-CW-E ! _RTAPT-CW-V3 ! _RTAPT-CW-V2 ! _RTAPT-CW-V1 !
    _RTAPT-CW-V0 !
    _RTAPT-CW-E @ _RTAPT-ENGINE-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-CW-E @ _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
        _RTAPT-CW-E @ _RTAPT-E.LAST-STATUS @ EXIT
    THEN
    _RTAPT-CW-E @ _RTAPT-CELL-FEED-READY? 0= IF RTAPT-S-BUSY EXIT THEN
    _RTAPT-CW-V0 @ _RTAPT-CW-V1 @ _RTAPT-CW-V2 @ _RTAPT-CW-V3 @
        _RTAPT-CW-E @ _RTAPT-E.SESSION @ PT-CELL _RTAPT-PT>STATUS
        _RTAPT-CW-E @ _RTAPT-FEED-RESULT ;

: RTAPT-CELL-CURSOR  ( row col visible engine -- status )
    _RTAPT-CW-E ! _RTAPT-CW-V2 ! _RTAPT-CW-V1 ! _RTAPT-CW-V0 !
    _RTAPT-CW-E @ _RTAPT-ENGINE-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-CW-E @ _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
        _RTAPT-CW-E @ _RTAPT-E.LAST-STATUS @ EXIT
    THEN
    _RTAPT-CW-E @ _RTAPT-CELL-FEED-READY? 0= IF RTAPT-S-BUSY EXIT THEN
    _RTAPT-CW-V0 @ _RTAPT-CW-V1 @ _RTAPT-CW-V2 @
        _RTAPT-CW-E @ _RTAPT-E.SESSION @ PT-CURSOR _RTAPT-PT>STATUS
        _RTAPT-CW-E @ _RTAPT-FEED-RESULT ;

VARIABLE _RTAPT-CA-E
VARIABLE _RTAPT-CA-REASON
VARIABLE _RTAPT-CA-STATUS

: _RTAPT-ABORT-OPEN  ( reason engine -- status )
    _RTAPT-CA-E ! _RTAPT-CA-REASON !
    _RTAPT-CA-REASON @ _RTAPT-CA-E @ _RTAPT-E.SESSION @
        PT-TX-ABORT _RTAPT-PT>STATUS DUP _RTAPT-CA-STATUS !
    RTAPT-S-OK = IF
        _RTAPT-CA-E @ _RTAPT-WIRE-REWIND
        RTAPT-S-OK DUP _RTAPT-CA-E @ _RTAPT-E.LAST-STATUS ! EXIT
    THEN
    RTAPT-S-SESSION-LOST _RTAPT-CA-E @ _RTAPT-QUARANTINE-ALL ;

: RTAPT-CELL-ABORT  ( reason engine -- status )
    DUP _RTAPT-CA-E !
    DUP _RTAPT-ENGINE-VALID? 0= IF 2DROP RTAPT-S-INVALID EXIT THEN
    DUP _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
        NIP _RTAPT-E.LAST-STATUS @ EXIT
    THEN
    OVER 0xFFFF U> IF 2DROP RTAPT-S-INVALID EXIT THEN
    DUP _RTAPT-E.UPDATE-STATE @ DUP RTAPT-UPDATE-IDLE =
    SWAP RTAPT-UPDATE-SEALED = OR IF
        2DROP RTAPT-S-OK DUP _RTAPT-CA-E @ _RTAPT-E.LAST-STATUS ! EXIT
    THEN
    DUP _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-CELL-OPEN <> IF
        2DROP RTAPT-S-BUSY EXIT
    THEN
    _RTAPT-ABORT-OPEN ;

VARIABLE _RTAPT-CS-E
VARIABLE _RTAPT-CS-P
VARIABLE _RTAPT-CS-COPY

: _RTAPT-SEND-CAPTURED  ( op-record engine -- status )
    _RTAPT-CS-E ! DUP _RTAPT-CS-P !
    _RTAPT-P.COPY-OFF @ _RTAPT-CS-E @ _RTAPT-E.COPY-A @ +
        _RTAPT-CS-COPY !
    _RTAPT-CS-COPY @ _RTAPT-RD.OWNER @
    _RTAPT-CS-COPY @ _RTAPT-RD.GENERATION @
    _RTAPT-CS-COPY @ _RTAPT-RD.REGION @
    _RTAPT-CS-COPY @ _RTAPT-RD.X @
    _RTAPT-CS-COPY @ _RTAPT-RD.Y @
    _RTAPT-CS-COPY @ _RTAPT-RD.COLS @
    _RTAPT-CS-COPY @ _RTAPT-RD.ROWS @
    _RTAPT-CS-COPY @ _RTAPT-RD.Z @
    _RTAPT-CS-COPY @ _RTAPT-RD.FLAGS @
    _RTAPT-CS-E @ _RTAPT-E.SESSION @ PT-REGION-DEFINE _RTAPT-PT>STATUS ;

1 CONSTANT _RTAPT-ABORT-SERIALIZATION
VARIABLE _RTAPT-CM-E
VARIABLE _RTAPT-CM-STATUS

: _RTAPT-COMMIT-FAILED  ( original-status engine -- status )
    _RTAPT-CM-E ! _RTAPT-CM-STATUS !
    _RTAPT-ABORT-SERIALIZATION _RTAPT-CM-E @ _RTAPT-ABORT-OPEN
    DUP RTAPT-S-OK <> IF DROP
        RTAPT-S-SESSION-LOST _RTAPT-CM-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN DROP
    _RTAPT-CM-STATUS @ DUP _RTAPT-CM-E @ _RTAPT-E.LAST-STATUS ! ;

: RTAPT-CELL-COMMIT  ( engine -- status )
    DUP _RTAPT-CM-E ! _RTAPT-ENGINE-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-CM-E @ _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
        _RTAPT-CM-E @ _RTAPT-E.LAST-STATUS @ EXIT
    THEN
    _RTAPT-CM-E @ _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-CELL-OPEN <>
        IF RTAPT-S-BUSY EXIT THEN
    _RTAPT-CM-E @ _RTAPT-E.COLS @ _RTAPT-CM-E @ _RTAPT-E.ROWS @
        _RTAPT-CM-E @ _RTAPT-CANDIDATE-PREFLIGHT? 0= IF
        RTAPT-S-INVALID _RTAPT-CM-E @ _RTAPT-COMMIT-FAILED EXIT
    THEN
    BEGIN
        _RTAPT-CM-E @ _RTAPT-E.SEND-INDEX @
        _RTAPT-CM-E @ _RTAPT-E.OP-COUNT @ U<
    WHILE
        _RTAPT-CM-E @ _RTAPT-E.SEND-INDEX @ _RTAPT-CM-E @ _RTAPT-OP-NTH
        _RTAPT-CM-E @ _RTAPT-SEND-CAPTURED
        DUP RTAPT-S-OK <> IF
            _RTAPT-CM-E @ _RTAPT-COMMIT-FAILED EXIT
        THEN DROP
        1 _RTAPT-CM-E @ _RTAPT-E.SEND-INDEX +!
    REPEAT
    _RTAPT-CM-E @ _RTAPT-E.DISPOSITION @
        _RTAPT-CM-E @ _RTAPT-E.SESSION @ PT-PRESENT-COMMIT _RTAPT-PT>STATUS
    DUP RTAPT-S-OK <> IF _RTAPT-CM-E @ _RTAPT-COMMIT-FAILED EXIT THEN DROP
    RTAPT-UPDATE-AWAITING _RTAPT-CM-E @ _RTAPT-E.UPDATE-STATE !
    _RTAPT-ACTIVE-OUTPUT _RTAPT-CM-E @ _RTAPT-E.ACTIVE-KIND !
    RTAPT-S-OK DUP _RTAPT-CM-E @ _RTAPT-E.LAST-STATUS ! ;

\ =====================================================================
\  PT lifecycle completion reconciliation
\ =====================================================================

VARIABLE _RTAPT-ST-E
VARIABLE _RTAPT-ST-O
VARIABLE _RTAPT-ST-PT
VARIABLE _RTAPT-ST-HAS
VARIABLE _RTAPT-ST-TOMBSTONE
VARIABLE _RTAPT-ST-STATE

: _RTAPT-LAST-RESULT!  ( wire-status detail revision engine -- )
    >R
    R@ _RTAPT-E.LAST-REVISION !
    R@ _RTAPT-E.LAST-DETAIL !
    R> _RTAPT-E.LAST-WIRE ! ;

: _RTAPT-ACTIVE-CLEAR  ( engine -- )
    DUP _RTAPT-E.ACTIVE-O OFF
    _RTAPT-ACTIVE-NONE SWAP _RTAPT-E.ACTIVE-KIND ! ;

: _RTAPT-OWNER-CLEAR  ( owner-record engine -- )
    >R RTAPT-OWNER-SIZE 0 FILL
    R@ _RTAPT-E.OWNER-USED @ 1- R@ _RTAPT-E.OWNER-USED !
    R> DROP ;

VARIABLE _RTAPT-OT-O
VARIABLE _RTAPT-OT-OWNER
VARIABLE _RTAPT-OT-GENERATION

\ A settled tombstone carries only the exact tuple.  Quota authority and
\ transient queue/result fields are released at the successful drop boundary.
: _RTAPT-OWNER>TOMBSTONE  ( owner-record -- )
    DUP _RTAPT-OT-O !
    DUP _RTAPT-O.OWNER @ _RTAPT-OT-OWNER !
    _RTAPT-O.GENERATION @ _RTAPT-OT-GENERATION !
    _RTAPT-OT-O @ RTAPT-OWNER-SIZE 0 FILL
    _RTAPT-OT-OWNER @ _RTAPT-OT-O @ _RTAPT-O.OWNER !
    _RTAPT-OT-GENERATION @ _RTAPT-OT-O @ _RTAPT-O.GENERATION !
    RTAPT-OWNER-ST-TOMBSTONE _RTAPT-OT-O @ _RTAPT-O.STATE ! ;

\ A newer-generation open candidate does not supersede the terminal's exact
\ tombstone until RET_OK.  Any local admission failure or rejected result
\ restores the prior tuple instead of fabricating a new tombstone.
: _RTAPT-OWNER-RESTORE-TOMBSTONE  ( owner-record -- flag )
    DUP _RTAPT-O.PRIOR-GENERATION @ DUP 0= IF 2DROP 0 EXIT THEN
    _RTAPT-OT-GENERATION !
    DUP _RTAPT-O.OWNER @ _RTAPT-OT-OWNER !
    DUP RTAPT-OWNER-SIZE 0 FILL
    _RTAPT-OT-OWNER @ OVER _RTAPT-O.OWNER !
    _RTAPT-OT-GENERATION @ OVER _RTAPT-O.GENERATION !
    RTAPT-OWNER-ST-TOMBSTONE SWAP _RTAPT-O.STATE ! -1 ;

: _RTAPT-COMPLETION-IDENTITY?  ( expected-kind expected-request owner e -- flag )
    >R
    R@ _RTAPT-E.COMPLETION PT-COMPLETION-OWNER@ =
    R@ _RTAPT-E.COMPLETION PT-COMPLETION-REQUEST@ ROT = AND
    R@ _RTAPT-E.COMPLETION PT-COMPLETION-KIND@ ROT = AND
    R> DROP ;

: _RTAPT-COMPLETION-GENERATION?  ( owner-record engine -- flag )
    >R _RTAPT-O.GENERATION @
    R> _RTAPT-E.COMPLETION PT-COMPLETION-GENERATION@ = ;

: _RTAPT-RECONCILE-OPEN  ( engine -- status )
    DUP _RTAPT-ST-E ! _RTAPT-E.ACTIVE-O @ _RTAPT-ST-O !
    _RTAPT-ST-O @ _RTAPT-O.STATE @ RTAPT-OWNER-ST-TOMBSTONE-OPENING =
        _RTAPT-ST-TOMBSTONE !
    PT-COMPLETE-RET PT-REQUEST-OWNER-OPEN
    _RTAPT-ST-O @ _RTAPT-O.OWNER @ _RTAPT-ST-E @
    _RTAPT-COMPLETION-IDENTITY? 0= IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-O @ _RTAPT-ST-E @ _RTAPT-COMPLETION-GENERATION? 0= IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-STATUS@ DUP
        DUP _RTAPT-ST-PT ! _RTAPT-ST-O @ _RTAPT-O.WIRE-STATUS !
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-DETAIL@
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-REVISION@
    _RTAPT-ST-E @ _RTAPT-LAST-RESULT!
    _RTAPT-ST-PT @ PT-RET-ABORTED = IF
        RTAPT-S-SESSION-LOST _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-ACTIVE-CLEAR
    _RTAPT-ST-PT @ PT-RET-OK = IF
        0 _RTAPT-ST-O @ _RTAPT-O.PRIOR-GENERATION !
        RTAPT-OWNER-ST-OPEN _RTAPT-ST-O @ _RTAPT-O.STATE ! RTAPT-S-OK
    ELSE
        _RTAPT-ST-TOMBSTONE @ IF
            _RTAPT-ST-O @ _RTAPT-OWNER-RESTORE-TOMBSTONE 0= IF
                RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
            THEN
        ELSE _RTAPT-ST-O @ _RTAPT-ST-E @ _RTAPT-OWNER-CLEAR THEN
        RTAPT-S-REJECTED
    THEN ;

: _RTAPT-RECONCILE-DROP  ( engine -- status )
    DUP _RTAPT-ST-E ! _RTAPT-E.ACTIVE-O @ _RTAPT-ST-O !
    _RTAPT-ST-O @ _RTAPT-O.STATE @ RTAPT-OWNER-ST-TOMBSTONE-DROPPING =
        _RTAPT-ST-TOMBSTONE !
    PT-COMPLETE-TX PT-REQUEST-OWNER-DROP
    _RTAPT-ST-O @ _RTAPT-O.OWNER @ _RTAPT-ST-E @
    _RTAPT-COMPLETION-IDENTITY? 0= IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-O @ _RTAPT-ST-E @ _RTAPT-COMPLETION-GENERATION? 0= IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-STATUS@ DUP
        DUP _RTAPT-ST-PT ! _RTAPT-ST-O @ _RTAPT-O.WIRE-STATUS !
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-DETAIL@
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-REVISION@
    _RTAPT-ST-E @ _RTAPT-LAST-RESULT!
    _RTAPT-ST-PT @ PT-TX-RESULT-ABORTED = IF
        \ Crossed-reset replay is deliberately not guessed in this slice.
        RTAPT-S-SESSION-LOST _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-PT @ PT-TX-RESULT-STALE U> IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-ACTIVE-CLEAR
    _RTAPT-ST-PT @ PT-TX-RESULT-OK = IF
        _RTAPT-ST-O @ _RTAPT-OWNER>TOMBSTONE
        RTAPT-S-OK EXIT
    THEN
    _RTAPT-ST-TOMBSTONE @ IF
        _RTAPT-ST-O @ _RTAPT-OWNER>TOMBSTONE
    ELSE RTAPT-OWNER-ST-DROPPING _RTAPT-ST-O @ _RTAPT-O.STATE ! THEN
    RTAPT-S-REJECTED ;

VARIABLE _RTAPT-PR-E
VARIABLE _RTAPT-PR-O
VARIABLE _RTAPT-PR-MODE
VARIABLE _RTAPT-PR-DISPOSITION
VARIABLE _RTAPT-PR-PENDING

: _RTAPT-LIVE-OWNER?  ( owner-record -- flag )
    _RTAPT-O.STATE @ DUP RTAPT-OWNER-ST-OPEN =
    SWAP RTAPT-OWNER-ST-DROPPING = OR ;

: _RTAPT-APPLY-OUTPUT  ( engine -- )
    DUP _RTAPT-PR-E !
    DUP _RTAPT-E.RET-MODE @ _RTAPT-PR-MODE !
    _RTAPT-E.DISPOSITION @ _RTAPT-PR-DISPOSITION !
    \ START establishes its global target base for every live owner before
    \ any staged definitions are applied.  High-water is never rewound.
    _RTAPT-PR-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-PR-E @ _RTAPT-E.OWNERS-A @ I RTAPT-OWNER-SIZE * +
        DUP _RTAPT-PR-O ! _RTAPT-LIVE-OWNER? IF
            _RTAPT-PR-MODE @ PT-RET-REPLACE-START = IF
                0 _RTAPT-PR-O @ _RTAPT-O.HIDDEN-REGIONS !
            THEN
            _RTAPT-PR-MODE @ PT-RET-LAYOUT-START = IF
                _RTAPT-PR-O @ _RTAPT-O.ACTIVE-REGIONS @
                    _RTAPT-PR-O @ _RTAPT-O.HIDDEN-REGIONS !
            THEN
        THEN
    LOOP
    \ Apply every owner's staged additions to the selected committed target.
    _RTAPT-PR-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-PR-E @ _RTAPT-E.OWNERS-A @ I RTAPT-OWNER-SIZE * +
        DUP _RTAPT-PR-O ! _RTAPT-LIVE-OWNER? IF
            _RTAPT-PR-O @ _RTAPT-O.PENDING-REGIONS @
                DUP _RTAPT-PR-PENDING ! IF
                _RTAPT-PR-MODE @ PT-RET-DELTA = IF
                    _RTAPT-PR-PENDING @
                        _RTAPT-PR-O @ _RTAPT-O.ACTIVE-REGIONS +!
                ELSE
                    _RTAPT-PR-PENDING @
                        _RTAPT-PR-O @ _RTAPT-O.HIDDEN-REGIONS +!
                THEN
                _RTAPT-PR-O @ _RTAPT-O.PENDING-REGION-HIGH @
                    _RTAPT-PR-O @ _RTAPT-O.REGION-HIGH !
            THEN
            0 _RTAPT-PR-O @ _RTAPT-O.PENDING-REGIONS !
            0 _RTAPT-PR-O @ _RTAPT-O.PENDING-REGION-HIGH !
        THEN
    LOOP
    \ A successful reveal is likewise global: every live owner's complete
    \ hidden ledger becomes active and the hidden ledger is retired.
    _RTAPT-PR-DISPOSITION @ PT-COMMIT-AND-REVEAL = IF
        _RTAPT-PR-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
            _RTAPT-PR-E @ _RTAPT-E.OWNERS-A @ I RTAPT-OWNER-SIZE * +
            DUP _RTAPT-PR-O ! _RTAPT-LIVE-OWNER? IF
                _RTAPT-PR-O @ _RTAPT-O.HIDDEN-REGIONS @
                    _RTAPT-PR-O @ _RTAPT-O.ACTIVE-REGIONS !
                0 _RTAPT-PR-O @ _RTAPT-O.HIDDEN-REGIONS !
            THEN
        LOOP
    THEN ;

: _RTAPT-OUTPUT-COMPLETION?  ( engine -- flag )
    DUP _RTAPT-E.COMPLETION PT-COMPLETION-KIND@ PT-COMPLETE-TX =
    OVER _RTAPT-E.COMPLETION PT-COMPLETION-REQUEST@
        PT-REQUEST-PRESENT-COMMIT = AND
    OVER _RTAPT-E.COMPLETION PT-COMPLETION-TXID@ 0<> AND
    OVER _RTAPT-E.COMPLETION PT-COMPLETION-DETAIL@ 0= AND
    OVER _RTAPT-E.COMPLETION PT-COMPLETION-OWNER@ 0= AND
    OVER _RTAPT-E.COMPLETION PT-COMPLETION-GENERATION@ 0= AND
    OVER _RTAPT-E.COMPLETION PT-COMPLETION-ITEM@ 0= AND
    SWAP _RTAPT-E.COMPLETION PT-COMPLETION-ACCEPTED-BYTES@ 0= AND ;

: _RTAPT-RECONCILE-OUTPUT  ( engine -- status )
    DUP _RTAPT-ST-E ! _RTAPT-OUTPUT-COMPLETION? 0= IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-STATUS@ DUP
        _RTAPT-ST-PT !
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-DETAIL@
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-REVISION@
    _RTAPT-ST-E @ _RTAPT-LAST-RESULT!
    _RTAPT-ST-PT @ PT-TX-RESULT-STALE U> IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-PT @ PT-TX-RESULT-OK = IF
        _RTAPT-ST-E @ _RTAPT-ACTIVE-CLEAR
        _RTAPT-ST-E @ _RTAPT-APPLY-OUTPUT
        _RTAPT-ST-E @ _RTAPT-CANDIDATE-DISCARD
        RTAPT-S-OK EXIT
    THEN
    _RTAPT-ST-PT @ PT-TX-RESULT-ABORTED = IF
        RTAPT-S-SESSION-LOST _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.COUPLING @ RTAPT-COUPLING-RETAINED = IF
        _RTAPT-ST-E @ _RTAPT-ACTIVE-CLEAR
        _RTAPT-ST-E @ _RTAPT-WIRE-REWIND
        RTAPT-S-REJECTED EXIT
    THEN
    RTAPT-S-SESSION-LOST _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL ;

: _RTAPT-POLL-COMPLETION  ( engine -- status had-completion )
    DUP _RTAPT-ST-E !
    DUP _RTAPT-E.COMPLETION SWAP _RTAPT-E.SESSION @ PT-COMPLETION-POLL
    _RTAPT-ST-HAS ! _RTAPT-PT>STATUS _RTAPT-ST-PT !
    _RTAPT-ST-PT @ RTAPT-S-SESSION-LOST = IF
        RTAPT-S-SESSION-LOST _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL 0 EXIT
    THEN
    _RTAPT-ST-PT @ RTAPT-S-INVALID = IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL 0 EXIT
    THEN
    _RTAPT-ST-PT @ RTAPT-S-OK <> IF _RTAPT-ST-PT @ 0 EXIT THEN
    _RTAPT-ST-HAS @ 0= IF RTAPT-S-OK 0 EXIT THEN
    _RTAPT-ST-E @ _RTAPT-E.ACTIVE-KIND @
    DUP _RTAPT-ACTIVE-OWNER-OPEN = IF
        DROP _RTAPT-ST-E @ _RTAPT-RECONCILE-OPEN -1 EXIT
    THEN
    DUP _RTAPT-ACTIVE-OWNER-DROP = IF
        DROP
        _RTAPT-ST-E @ _RTAPT-RECONCILE-DROP -1 EXIT
    THEN
    _RTAPT-ACTIVE-OUTPUT = IF
        _RTAPT-ST-E @ _RTAPT-RECONCILE-OUTPUT -1 EXIT
    THEN
    RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL -1 ;

: _RTAPT-OWNER-SEND  ( owner-record engine -- status )
    _RTAPT-ST-E ! _RTAPT-ST-O !
    _RTAPT-ST-O @ _RTAPT-O.STATE @ DUP _RTAPT-ST-STATE !
    DUP RTAPT-OWNER-ST-OPEN-QUEUED =
    SWAP RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED = OR IF
        _RTAPT-ST-O @ _RTAPT-O.OWNER @
        _RTAPT-ST-O @ _RTAPT-O.GENERATION @
        _RTAPT-ST-O @ _RTAPT-O.REGIONS @
        _RTAPT-ST-O @ _RTAPT-O.RESOURCES @
        _RTAPT-ST-O @ _RTAPT-O.OBJECTS @
        _RTAPT-ST-O @ _RTAPT-O.SERIES @
        _RTAPT-ST-O @ _RTAPT-O.RES-BYTES @
        _RTAPT-ST-O @ _RTAPT-O.UTF8-BYTES @
        _RTAPT-ST-O @ _RTAPT-O.SAMPLES @
        _RTAPT-ST-E @ _RTAPT-E.SESSION @ PT-OWNER-OPEN _RTAPT-PT>STATUS
        DUP RTAPT-S-OK = IF
            DROP
            _RTAPT-ST-STATE @ RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED = IF
                RTAPT-OWNER-ST-TOMBSTONE-OPENING
            ELSE RTAPT-OWNER-ST-OPENING THEN
            _RTAPT-ST-O @ _RTAPT-O.STATE !
            _RTAPT-ST-O @ _RTAPT-ST-E @ _RTAPT-E.ACTIVE-O !
            _RTAPT-ACTIVE-OWNER-OPEN _RTAPT-ST-E @ _RTAPT-E.ACTIVE-KIND !
            RTAPT-S-OK
        THEN EXIT
    THEN
    _RTAPT-ST-O @ _RTAPT-O.STATE @ DUP _RTAPT-ST-STATE !
    DUP RTAPT-OWNER-ST-DROP-QUEUED =
    OVER RTAPT-OWNER-ST-DROP-RETRY-QUEUED = OR
    SWAP RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED = OR 0= IF
        RTAPT-S-INVALID EXIT
    THEN
    _RTAPT-ST-O @ _RTAPT-O.OWNER @
    _RTAPT-ST-O @ _RTAPT-O.GENERATION @
    _RTAPT-ST-E @ _RTAPT-E.SESSION @ PT-OWNER-DROP _RTAPT-PT>STATUS
    DUP RTAPT-S-OK = IF
        DROP
        _RTAPT-ST-STATE @ RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED = IF
            RTAPT-OWNER-ST-TOMBSTONE-DROPPING
        ELSE _RTAPT-ST-STATE @ RTAPT-OWNER-ST-DROP-RETRY-QUEUED = IF
            RTAPT-OWNER-ST-DROP-RETRY-DROPPING
        ELSE RTAPT-OWNER-ST-DROPPING THEN THEN
        _RTAPT-ST-O @ _RTAPT-O.STATE !
        _RTAPT-ST-O @ _RTAPT-ST-E @ _RTAPT-E.ACTIVE-O !
        _RTAPT-ACTIVE-OWNER-DROP _RTAPT-ST-E @ _RTAPT-E.ACTIVE-KIND !
        RTAPT-S-OK
    THEN ;

: _RTAPT-OWNER-ADMISSION-FAILED  ( owner-record engine -- flag )
    >R
    DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-OPEN-QUEUED = IF
        R> _RTAPT-OWNER-CLEAR -1 EXIT
    THEN
    DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED = IF
        _RTAPT-OWNER-RESTORE-TOMBSTONE R> DROP EXIT
    THEN
    DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-DROP-QUEUED = IF
        RTAPT-OWNER-ST-OPEN SWAP _RTAPT-O.STATE ! R> DROP -1 EXIT
    THEN
    DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-DROP-RETRY-QUEUED = IF
        RTAPT-OWNER-ST-DROPPING SWAP _RTAPT-O.STATE ! R> DROP -1 EXIT
    THEN
    DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED = IF
        RTAPT-OWNER-ST-TOMBSTONE SWAP _RTAPT-O.STATE ! R> DROP -1 EXIT
    THEN
    DROP R> DROP 0 ;

\ RTAPT-STEP performs at most one completion reconciliation or one lifecycle
\ publication.  It never calls PT-SERVICE and cannot consume input events.
: RTAPT-STEP  ( engine -- status )
    DUP _RTAPT-ENGINE-VALID? 0= IF DROP RTAPT-S-INVALID EXIT THEN
    DUP _RTAPT-ST-E !
    DUP _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
        _RTAPT-E.LAST-STATUS @ EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-NONE <> IF
        _RTAPT-ST-E @ _RTAPT-POLL-COMPLETION
        IF DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT THEN
        DUP RTAPT-S-OK <> IF
            DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT
        THEN DROP
        RTAPT-S-WOULD-BLOCK DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-READY-STATUS DUP RTAPT-S-OK <> IF
        DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT
    THEN DROP
    _RTAPT-ST-E @ _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-CELL-OPEN = IF
        RTAPT-S-BUSY DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.UPDATE-STATE @ RTAPT-UPDATE-IDLE <> IF
        \ CAPTURING and SEALED are caller-owned candidates.  STEP never
        \ promotes either one to a retained-only publication implicitly.
        RTAPT-S-OK DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.QUEUE-HEAD @ 0= IF
        RTAPT-S-OK DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.QUEUE-HEAD @ DUP 0= IF
        DROP RTAPT-S-INVALID
    ELSE
        DUP _RTAPT-ST-O ! _RTAPT-ST-E @ _RTAPT-OWNER-SEND
        DUP RTAPT-S-WOULD-BLOCK <> IF
            DUP _RTAPT-ST-PT !
            _RTAPT-ST-E @ _RTAPT-QUEUE-POP
            _RTAPT-ST-O @ <> IF
                DROP RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL
            ELSE
                DROP
                _RTAPT-ST-PT @ RTAPT-S-OK <> IF
                    _RTAPT-ST-O @ _RTAPT-ST-E @
                    _RTAPT-OWNER-ADMISSION-FAILED 0= IF
                        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL
                    ELSE _RTAPT-ST-PT @ RTAPT-S-SESSION-LOST = IF
                        RTAPT-S-SESSION-LOST _RTAPT-ST-E @
                            _RTAPT-QUARANTINE-ALL
                    ELSE _RTAPT-ST-PT @ THEN THEN
                ELSE RTAPT-S-OK THEN
            THEN
        THEN
    THEN
    DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! ;
