\ =====================================================================
\  apt1-engine.f -- neutral Akashic APT-1 rich-terminal engine
\ =====================================================================
\
\  This module is an explicitly composed owner of one caller-supplied PT
\  session.  It is not discoverable and contains no consumer or environment
\  policy.  The PT module remains the sole authority for wire framing,
\  session epochs, transaction IDs, revisions, credit, and result ordering.
\
\  Prefix:   RTAPT- (public), _RTAPT- (private)
\  Provider: akashic-tui-rtapt1

PROVIDED akashic-tui-rtapt1

REQUIRE ../../utils/memory-span.f

\ =====================================================================
\  Public status and lifecycle values
\ =====================================================================

0 CONSTANT RTAPT-S-OK
1 CONSTANT RTAPT-S-WOULD-BLOCK
2 CONSTANT RTAPT-S-SESSION-LOST
3 CONSTANT RTAPT-S-INVALID
4 CONSTANT RTAPT-S-UNSUPPORTED
5 CONSTANT RTAPT-S-CAPACITY
6 CONSTANT RTAPT-S-BUSY
7 CONSTANT RTAPT-S-REJECTED

0 CONSTANT RTAPT-OWNER-ST-FREE
1 CONSTANT RTAPT-OWNER-ST-OPEN-QUEUED
2 CONSTANT RTAPT-OWNER-ST-OPENING
3 CONSTANT RTAPT-OWNER-ST-OPEN
4 CONSTANT RTAPT-OWNER-ST-DROP-QUEUED
5 CONSTANT RTAPT-OWNER-ST-DROPPING
6 CONSTANT RTAPT-OWNER-ST-TOMBSTONE
7 CONSTANT RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED
8 CONSTANT RTAPT-OWNER-ST-TOMBSTONE-DROPPING
9 CONSTANT RTAPT-OWNER-ST-QUARANTINED
10 CONSTANT RTAPT-OWNER-ST-DROP-RETRY-QUEUED
11 CONSTANT RTAPT-OWNER-ST-DROP-RETRY-DROPPING
12 CONSTANT RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED
13 CONSTANT RTAPT-OWNER-ST-TOMBSTONE-OPENING

0 CONSTANT RTAPT-BATCH-IDLE

\ The operation record is intentionally small: future typed capture stores an
\ operation kind and an offset/length into the separately bounded copy span.
\ No capacity is compiled into the engine.
24 CONSTANT RTAPT-OP-SIZE
104 CONSTANT RTAPT-OWNER-SIZE
64 CONSTANT RTAPT-CONFIG-SIZE
336 CONSTANT RTAPT-ENGINE-SIZE

: RTAPT-CONFIG-BYTES  ( -- bytes )  RTAPT-CONFIG-SIZE ;
: RTAPT-ENGINE-BYTES  ( -- bytes )  RTAPT-ENGINE-SIZE ;
: RTAPT-OWNER-BYTES   ( -- bytes )  RTAPT-OWNER-SIZE ;
: RTAPT-OP-BYTES      ( -- bytes )  RTAPT-OP-SIZE ;

0x5254415054434647 CONSTANT _RTAPT-CONFIG-MAGIC  \ "RTAPTCFG"
0x5254415054454E47 CONSTANT _RTAPT-ENGINE-MAGIC  \ "RTAPTENG"

\ =====================================================================
\  Caller-owned record layouts
\ =====================================================================

\ Configuration is a checked construction record.  This engine profile needs
\ at least one owner slot, one typed-operation slot, and one byte in its copy
\ bank; their upper bounds come only from the caller's nonempty spans.
\ RTAPT-INIT copies all fields, so configuration is not retained or discovered.
: _RTAPT-C.MAGIC      ( c -- a )       ;
: _RTAPT-C.SESSION    ( c -- a )   8 + ;
: _RTAPT-C.OWNERS-A   ( c -- a )  16 + ;
: _RTAPT-C.OWNERS-U   ( c -- a )  24 + ;
: _RTAPT-C.OPS-A      ( c -- a )  32 + ;
: _RTAPT-C.OPS-U      ( c -- a )  40 + ;
: _RTAPT-C.COPY-A     ( c -- a )  48 + ;
: _RTAPT-C.COPY-U     ( c -- a )  56 + ;

\ Owner entries are engine-private after initialization.  NEXT links a
\ caller-capacity-derived FIFO of exact lifecycle requests.  OWNER-USED counts
\ live bindings, in-flight candidates, tombstones, and quarantined evidence;
\ a successful drop releases quota fields but retains its exact tuple.
: _RTAPT-O.STATE      ( o -- a )       ;
: _RTAPT-O.OWNER      ( o -- a )   8 + ;
: _RTAPT-O.GENERATION ( o -- a )  16 + ;
: _RTAPT-O.REGIONS    ( o -- a )  24 + ;
: _RTAPT-O.RESOURCES  ( o -- a )  32 + ;
: _RTAPT-O.OBJECTS    ( o -- a )  40 + ;
: _RTAPT-O.SERIES     ( o -- a )  48 + ;
: _RTAPT-O.RES-BYTES  ( o -- a )  56 + ;
: _RTAPT-O.UTF8-BYTES ( o -- a )  64 + ;
: _RTAPT-O.SAMPLES    ( o -- a )  72 + ;
: _RTAPT-O.WIRE-STATUS ( o -- a ) 80 + ;
: _RTAPT-O.NEXT       ( o -- a )  88 + ;
: _RTAPT-O.PRIOR-GENERATION ( o -- a ) 96 + ;

\ Fixed engine metadata is followed by one PT completion descriptor.  The
\ descriptor is part of the engine span and is never exposed as PT authority.
: _RTAPT-E.MAGIC      ( e -- a )       ;
: _RTAPT-E.SESSION    ( e -- a )   8 + ;
: _RTAPT-E.OWNERS-A   ( e -- a )  16 + ;
: _RTAPT-E.OWNERS-U   ( e -- a )  24 + ;
: _RTAPT-E.OWNER-CAP  ( e -- a )  32 + ;
: _RTAPT-E.OWNER-USED ( e -- a )  40 + ;
: _RTAPT-E.OPS-A      ( e -- a )  48 + ;
: _RTAPT-E.OPS-U      ( e -- a )  56 + ;
: _RTAPT-E.OP-CAP     ( e -- a )  64 + ;
: _RTAPT-E.COPY-A     ( e -- a )  72 + ;
: _RTAPT-E.COPY-U     ( e -- a )  80 + ;
: _RTAPT-E.QUEUE-HEAD ( e -- a )  88 + ;
: _RTAPT-E.QUEUE-TAIL ( e -- a )  96 + ;
: _RTAPT-E.ACTIVE-O   ( e -- a ) 104 + ;
: _RTAPT-E.ACTIVE-KIND ( e -- a ) 112 + ;
: _RTAPT-E.BATCH-STATE ( e -- a ) 120 + ;
: _RTAPT-E.COUPLING   ( e -- a ) 128 + ;
: _RTAPT-E.COLS       ( e -- a ) 136 + ;
: _RTAPT-E.ROWS       ( e -- a ) 144 + ;
: _RTAPT-E.CELL-SPANS ( e -- a ) 152 + ;
: _RTAPT-E.CELLS      ( e -- a ) 160 + ;
: _RTAPT-E.CELL-MODE  ( e -- a ) 168 + ;
: _RTAPT-E.RET-MODE   ( e -- a ) 176 + ;
: _RTAPT-E.DISPOSITION ( e -- a ) 184 + ;
: _RTAPT-E.OP-COUNT   ( e -- a ) 192 + ;
: _RTAPT-E.COPY-USED  ( e -- a ) 200 + ;
: _RTAPT-E.RET-BYTES  ( e -- a ) 208 + ;
: _RTAPT-E.SEND-INDEX ( e -- a ) 216 + ;
: _RTAPT-E.LAST-STATUS ( e -- a ) 224 + ;
: _RTAPT-E.LAST-WIRE  ( e -- a ) 232 + ;
: _RTAPT-E.LAST-DETAIL ( e -- a ) 240 + ;
: _RTAPT-E.LAST-REVISION ( e -- a ) 248 + ;
: _RTAPT-E.COMPLETION ( e -- a ) 256 + ;

0 CONSTANT _RTAPT-ACTIVE-NONE
1 CONSTANT _RTAPT-ACTIVE-OWNER-OPEN
2 CONSTANT _RTAPT-ACTIVE-OWNER-DROP
3 CONSTANT _RTAPT-ACTIVE-QUARANTINED

\ =====================================================================
\  Checked storage geometry
\ =====================================================================

: _RTAPT-ALIGNED?  ( a -- flag )  7 AND 0= ;

VARIABLE _RTAPT-CI-C
VARIABLE _RTAPT-CI-S
VARIABLE _RTAPT-CI-OA
VARIABLE _RTAPT-CI-OU
VARIABLE _RTAPT-CI-PA
VARIABLE _RTAPT-CI-PU
VARIABLE _RTAPT-CI-CA
VARIABLE _RTAPT-CI-CU

: _RTAPT-SPAN?  ( a u -- flag )
    OVER 0<> OVER 0> AND 0= IF 2DROP 0 EXIT THEN
    OVER _RTAPT-ALIGNED? 0= IF 2DROP 0 EXIT THEN
    MSPAN-NONWRAPPING? ;

: _RTAPT-CONFIG-RANGES?  ( -- flag )
    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-CI-S @ PT-SESSION-SIZE _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-CI-OA @ _RTAPT-CI-OU @ _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-CI-PA @ _RTAPT-CI-PU @ _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-CI-CA @ _RTAPT-CI-CU @ _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-CI-OU @ RTAPT-OWNER-SIZE MOD IF 0 EXIT THEN
    _RTAPT-CI-PU @ RTAPT-OP-SIZE MOD IF 0 EXIT THEN

    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-CI-S @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-CI-OA @ _RTAPT-CI-OU @ _RTAPT-CI-S @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-CI-PA @ _RTAPT-CI-PU @ _RTAPT-CI-S @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-CI-CA @ _RTAPT-CI-CU @ _RTAPT-CI-S @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN

    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-CI-S @ PT-SESSION-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-CI-OA @ _RTAPT-CI-OU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-CI-PA @ _RTAPT-CI-PU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE _RTAPT-CI-CA @ _RTAPT-CI-CU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-S @ PT-SESSION-SIZE _RTAPT-CI-OA @ _RTAPT-CI-OU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-S @ PT-SESSION-SIZE _RTAPT-CI-PA @ _RTAPT-CI-PU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-S @ PT-SESSION-SIZE _RTAPT-CI-CA @ _RTAPT-CI-CU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-OA @ _RTAPT-CI-OU @ _RTAPT-CI-PA @ _RTAPT-CI-PU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-OA @ _RTAPT-CI-OU @ _RTAPT-CI-CA @ _RTAPT-CI-CU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-CI-PA @ _RTAPT-CI-PU @ _RTAPT-CI-CA @ _RTAPT-CI-CU @
        MSPAN-OVERLAP? 0= ;

: RTAPT-CONFIG-INIT  ( session owners-a owners-u ops-a ops-u copy-a copy-u
                        config -- status )
    _RTAPT-CI-C ! _RTAPT-CI-CU ! _RTAPT-CI-CA !
    _RTAPT-CI-PU ! _RTAPT-CI-PA ! _RTAPT-CI-OU ! _RTAPT-CI-OA ! _RTAPT-CI-S !
    _RTAPT-CONFIG-RANGES? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-CI-C @ RTAPT-CONFIG-SIZE 0 FILL
    _RTAPT-CONFIG-MAGIC _RTAPT-CI-C @ _RTAPT-C.MAGIC !
    _RTAPT-CI-S @ _RTAPT-CI-C @ _RTAPT-C.SESSION !
    _RTAPT-CI-OA @ _RTAPT-CI-C @ _RTAPT-C.OWNERS-A !
    _RTAPT-CI-OU @ _RTAPT-CI-C @ _RTAPT-C.OWNERS-U !
    _RTAPT-CI-PA @ _RTAPT-CI-C @ _RTAPT-C.OPS-A !
    _RTAPT-CI-PU @ _RTAPT-CI-C @ _RTAPT-C.OPS-U !
    _RTAPT-CI-CA @ _RTAPT-CI-C @ _RTAPT-C.COPY-A !
    _RTAPT-CI-CU @ _RTAPT-CI-C @ _RTAPT-C.COPY-U !
    RTAPT-S-OK ;

: _RTAPT-CONFIG-VALID?  ( c -- flag )
    DUP RTAPT-CONFIG-SIZE _RTAPT-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RTAPT-C.MAGIC @ _RTAPT-CONFIG-MAGIC <> IF DROP 0 EXIT THEN
    DUP _RTAPT-C.SESSION @ _RTAPT-CI-S !
    DUP _RTAPT-C.OWNERS-A @ _RTAPT-CI-OA !
    DUP _RTAPT-C.OWNERS-U @ _RTAPT-CI-OU !
    DUP _RTAPT-C.OPS-A @ _RTAPT-CI-PA !
    DUP _RTAPT-C.OPS-U @ _RTAPT-CI-PU !
    DUP _RTAPT-C.COPY-A @ _RTAPT-CI-CA !
    DUP _RTAPT-C.COPY-U @ _RTAPT-CI-CU !
    _RTAPT-CI-C ! _RTAPT-CONFIG-RANGES? ;

VARIABLE _RTAPT-I-C
VARIABLE _RTAPT-I-E

: _RTAPT-ENGINE-DISJOINT?  ( -- flag )
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-CI-S @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-I-C @ RTAPT-CONFIG-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-CI-S @ PT-SESSION-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-CI-OA @ _RTAPT-CI-OU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-CI-PA @ _RTAPT-CI-PU @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE _RTAPT-CI-CA @ _RTAPT-CI-CU @
        MSPAN-OVERLAP? 0= ;

: _RTAPT-PT>STATUS  ( pt-status -- status )
    DUP PT-S-OK = IF DROP RTAPT-S-OK EXIT THEN
    DUP PT-S-WOULD-BLOCK = IF DROP RTAPT-S-WOULD-BLOCK EXIT THEN
    DUP PT-S-SESSION-LOST = IF DROP RTAPT-S-SESSION-LOST EXIT THEN
    DUP PT-S-INVALID = IF DROP RTAPT-S-INVALID EXIT THEN
    DUP PT-S-UNSUPPORTED = IF DROP RTAPT-S-UNSUPPORTED EXIT THEN
    DROP RTAPT-S-SESSION-LOST ;

VARIABLE _RTAPT-EV-E
VARIABLE _RTAPT-EV-P

: _RTAPT-ENGINE-RANGES?  ( engine -- flag )
    _RTAPT-EV-E !
    _RTAPT-EV-E @ RTAPT-ENGINE-SIZE _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.SESSION @ PT-SESSION-SIZE
        _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OWNERS-A @
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-U @ _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OPS-A @
        _RTAPT-EV-E @ _RTAPT-E.OPS-U @ _RTAPT-SPAN? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.COPY-A @
        _RTAPT-EV-E @ _RTAPT-E.COPY-U @ _RTAPT-SPAN? 0= IF 0 EXIT THEN

    _RTAPT-EV-E @ RTAPT-ENGINE-SIZE
        _RTAPT-EV-E @ _RTAPT-E.SESSION @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OWNERS-A @
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-U @
        _RTAPT-EV-E @ _RTAPT-E.SESSION @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OPS-A @
        _RTAPT-EV-E @ _RTAPT-E.OPS-U @
        _RTAPT-EV-E @ _RTAPT-E.SESSION @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.COPY-A @
        _RTAPT-EV-E @ _RTAPT-E.COPY-U @
        _RTAPT-EV-E @ _RTAPT-E.SESSION @
        PT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN

    _RTAPT-EV-E @ RTAPT-ENGINE-SIZE
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-A @
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-EV-E @ RTAPT-ENGINE-SIZE
        _RTAPT-EV-E @ _RTAPT-E.OPS-A @
        _RTAPT-EV-E @ _RTAPT-E.OPS-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-EV-E @ RTAPT-ENGINE-SIZE
        _RTAPT-EV-E @ _RTAPT-E.COPY-A @
        _RTAPT-EV-E @ _RTAPT-E.COPY-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OWNERS-A @
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-U @
        _RTAPT-EV-E @ _RTAPT-E.OPS-A @
        _RTAPT-EV-E @ _RTAPT-E.OPS-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OWNERS-A @
        _RTAPT-EV-E @ _RTAPT-E.OWNERS-U @
        _RTAPT-EV-E @ _RTAPT-E.COPY-A @
        _RTAPT-EV-E @ _RTAPT-E.COPY-U @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPT-EV-E @ _RTAPT-E.OPS-A @
        _RTAPT-EV-E @ _RTAPT-E.OPS-U @
        _RTAPT-EV-E @ _RTAPT-E.COPY-A @
        _RTAPT-EV-E @ _RTAPT-E.COPY-U @ MSPAN-OVERLAP? 0= ;

: _RTAPT-OWNER-POINTER?  ( owner-record engine -- flag )
    >R
    DUP R@ _RTAPT-E.OWNERS-A @ U< IF DROP R> DROP 0 EXIT THEN
    R@ _RTAPT-E.OWNERS-A @ - DUP R@ _RTAPT-E.OWNERS-U @ U< 0= IF
        DROP R> DROP 0 EXIT
    THEN
    RTAPT-OWNER-SIZE MOD 0= R> DROP ;

: _RTAPT-OWNER-POINTER-OR-ZERO?  ( owner-record|0 engine -- flag )
    OVER 0= IF 2DROP -1 EXIT THEN _RTAPT-OWNER-POINTER? ;

VARIABLE _RTAPT-QV-E
VARIABLE _RTAPT-QV-EXPECT
VARIABLE _RTAPT-QV-OK

: _RTAPT-QUARANTINE-COHERENT?  ( engine -- flag )
    DUP _RTAPT-QV-E ! _RTAPT-E.ACTIVE-KIND @
        _RTAPT-ACTIVE-QUARANTINED = _RTAPT-QV-EXPECT !
    -1 _RTAPT-QV-OK !
    _RTAPT-QV-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-QV-E @ _RTAPT-E.OWNERS-A @ I RTAPT-OWNER-SIZE * +
        _RTAPT-O.STATE @ DUP RTAPT-OWNER-ST-FREE = IF
            DROP
        ELSE
            RTAPT-OWNER-ST-QUARANTINED = _RTAPT-QV-EXPECT @ <> IF
                0 _RTAPT-QV-OK !
            THEN
        THEN
    LOOP
    _RTAPT-QV-OK @ ;

: _RTAPT-ENGINE-VALID?  ( e -- flag )
    DUP RTAPT-ENGINE-SIZE _RTAPT-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RTAPT-E.MAGIC @ _RTAPT-ENGINE-MAGIC <> IF DROP 0 EXIT THEN
    DUP _RTAPT-ENGINE-RANGES? 0= IF DROP 0 EXIT THEN
    DUP _RTAPT-E.OWNERS-U @ RTAPT-OWNER-SIZE MOD IF DROP 0 EXIT THEN
    DUP _RTAPT-E.OPS-U @ RTAPT-OP-SIZE MOD IF DROP 0 EXIT THEN
    DUP _RTAPT-E.OWNER-CAP @ OVER _RTAPT-E.OWNERS-U @ RTAPT-OWNER-SIZE / <>
        IF DROP 0 EXIT THEN
    DUP _RTAPT-E.OP-CAP @ OVER _RTAPT-E.OPS-U @ RTAPT-OP-SIZE / <>
        IF DROP 0 EXIT THEN
    DUP _RTAPT-E.OWNER-USED @ OVER _RTAPT-E.OWNER-CAP @ U> IF DROP 0 EXIT THEN
    DUP _RTAPT-QUARANTINE-COHERENT? 0= IF DROP 0 EXIT THEN
    DUP _RTAPT-E.QUEUE-HEAD @ OVER _RTAPT-OWNER-POINTER-OR-ZERO? 0= IF
        DROP 0 EXIT
    THEN
    DUP _RTAPT-E.QUEUE-TAIL @ OVER _RTAPT-OWNER-POINTER-OR-ZERO? 0= IF
        DROP 0 EXIT
    THEN
    DUP _RTAPT-E.ACTIVE-O @ OVER _RTAPT-OWNER-POINTER-OR-ZERO? 0= IF
        DROP 0 EXIT
    THEN
    DUP _RTAPT-E.QUEUE-HEAD @ 0= OVER _RTAPT-E.QUEUE-TAIL @ 0= <> IF
        DROP 0 EXIT
    THEN
    DUP _RTAPT-E.QUEUE-HEAD @ ?DUP IF
        _RTAPT-O.STATE @ DUP RTAPT-OWNER-ST-OPEN-QUEUED =
        OVER RTAPT-OWNER-ST-DROP-QUEUED = OR
        OVER RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED = OR
        OVER RTAPT-OWNER-ST-DROP-RETRY-QUEUED = OR
        SWAP RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED = OR 0= IF
            DROP 0 EXIT
        THEN
    THEN
    DUP _RTAPT-E.QUEUE-TAIL @ ?DUP IF
        _RTAPT-O.STATE @ DUP RTAPT-OWNER-ST-OPEN-QUEUED =
        OVER RTAPT-OWNER-ST-DROP-QUEUED = OR
        OVER RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED = OR
        OVER RTAPT-OWNER-ST-DROP-RETRY-QUEUED = OR
        SWAP RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED = OR 0= IF
            DROP 0 EXIT
        THEN
    THEN
    DUP _RTAPT-E.QUEUE-TAIL @ ?DUP IF _RTAPT-O.NEXT @ IF DROP 0 EXIT THEN THEN
    DUP _RTAPT-E.ACTIVE-KIND @ DUP _RTAPT-ACTIVE-QUARANTINED U> IF
        2DROP 0 EXIT
    THEN
    DUP _RTAPT-ACTIVE-NONE = IF
        DROP
        DUP _RTAPT-E.ACTIVE-O @ IF DROP 0 EXIT THEN
    ELSE DUP _RTAPT-ACTIVE-QUARANTINED = IF
        DROP
        DUP _RTAPT-E.ACTIVE-O @ IF DROP 0 EXIT THEN
        DUP _RTAPT-E.QUEUE-HEAD @ OVER _RTAPT-E.QUEUE-TAIL @ OR IF
            DROP 0 EXIT
        THEN
    ELSE
        DROP
        DUP _RTAPT-E.ACTIVE-O @ 0= IF DROP 0 EXIT THEN
    THEN THEN
    DUP _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-OWNER-OPEN = IF
        DUP _RTAPT-E.ACTIVE-O @ _RTAPT-O.STATE @ DUP
            RTAPT-OWNER-ST-OPENING =
        SWAP RTAPT-OWNER-ST-TOMBSTONE-OPENING = OR 0= IF DROP 0 EXIT THEN
    THEN
    DUP _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-OWNER-DROP = IF
        DUP _RTAPT-E.ACTIVE-O @ _RTAPT-O.STATE @ DUP
            RTAPT-OWNER-ST-DROPPING =
        OVER RTAPT-OWNER-ST-TOMBSTONE-DROPPING = OR
        SWAP RTAPT-OWNER-ST-DROP-RETRY-DROPPING = OR 0= IF DROP 0 EXIT THEN
    THEN
    DROP -1 ;

: RTAPT-INIT  ( config engine -- status )
    _RTAPT-I-E ! _RTAPT-I-C !
    _RTAPT-I-C @ _RTAPT-CONFIG-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-ENGINE-DISJOINT? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-I-E @ _RTAPT-E.MAGIC @ _RTAPT-ENGINE-MAGIC = IF
        RTAPT-S-BUSY EXIT
    THEN
    _RTAPT-CI-S @ PT-RETAINED-DISCOVER _RTAPT-PT>STATUS
    DUP RTAPT-S-OK <> IF EXIT THEN DROP

    _RTAPT-CI-OA @ _RTAPT-CI-OU @ 0 FILL
    _RTAPT-CI-PA @ _RTAPT-CI-PU @ 0 FILL
    _RTAPT-CI-CA @ _RTAPT-CI-CU @ 0 FILL
    _RTAPT-I-E @ RTAPT-ENGINE-SIZE 0 FILL
    _RTAPT-CI-S @ _RTAPT-I-E @ _RTAPT-E.SESSION !
    _RTAPT-CI-OA @ _RTAPT-I-E @ _RTAPT-E.OWNERS-A !
    _RTAPT-CI-OU @ _RTAPT-I-E @ _RTAPT-E.OWNERS-U !
    _RTAPT-CI-OU @ RTAPT-OWNER-SIZE /
        _RTAPT-I-E @ _RTAPT-E.OWNER-CAP !
    _RTAPT-CI-PA @ _RTAPT-I-E @ _RTAPT-E.OPS-A !
    _RTAPT-CI-PU @ _RTAPT-I-E @ _RTAPT-E.OPS-U !
    _RTAPT-CI-PU @ RTAPT-OP-SIZE / _RTAPT-I-E @ _RTAPT-E.OP-CAP !
    _RTAPT-CI-CA @ _RTAPT-I-E @ _RTAPT-E.COPY-A !
    _RTAPT-CI-CU @ _RTAPT-I-E @ _RTAPT-E.COPY-U !
    RTAPT-BATCH-IDLE _RTAPT-I-E @ _RTAPT-E.BATCH-STATE !
    RTAPT-S-OK _RTAPT-I-E @ _RTAPT-E.LAST-STATUS !
    _RTAPT-ENGINE-MAGIC _RTAPT-I-E @ _RTAPT-E.MAGIC !
    RTAPT-S-OK ;

: RTAPT-STATUS  ( engine -- status )
    DUP _RTAPT-ENGINE-VALID? 0= IF DROP RTAPT-S-INVALID EXIT THEN
    _RTAPT-E.LAST-STATUS @ ;

VARIABLE _RTAPT-QA-E
VARIABLE _RTAPT-QA-STATUS
VARIABLE _RTAPT-QA-O

\ Preserve every tuple and quota while making all bindings unusable.  The
\ queue and active pointer are detached before publication of the sticky
\ engine state, so no quarantined request can later reach PT accidentally.
: _RTAPT-QUARANTINE-ALL  ( status engine -- status )
    _RTAPT-QA-E ! _RTAPT-QA-STATUS !
    _RTAPT-QA-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-QA-E @ _RTAPT-E.OWNERS-A @ I RTAPT-OWNER-SIZE * +
        DUP _RTAPT-QA-O ! _RTAPT-O.STATE @ RTAPT-OWNER-ST-FREE <> IF
            RTAPT-OWNER-ST-QUARANTINED _RTAPT-QA-O @ _RTAPT-O.STATE !
            0 _RTAPT-QA-O @ _RTAPT-O.NEXT !
        THEN
    LOOP
    0 _RTAPT-QA-E @ _RTAPT-E.QUEUE-HEAD !
    0 _RTAPT-QA-E @ _RTAPT-E.QUEUE-TAIL !
    0 _RTAPT-QA-E @ _RTAPT-E.ACTIVE-O !
    _RTAPT-ACTIVE-QUARANTINED _RTAPT-QA-E @ _RTAPT-E.ACTIVE-KIND !
    _RTAPT-QA-STATUS @ DUP _RTAPT-QA-E @ _RTAPT-E.LAST-STATUS ! ;

: _RTAPT-SESSION-ENDED?  ( engine -- flag )
    _RTAPT-E.SESSION @ DUP PT-STATE@ PT-ST-ANSI =
    SWAP PT-OWNS? 0= AND ;

: _RTAPT-READY-STATUS  ( engine -- status )
    DUP _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
        _RTAPT-E.LAST-STATUS @ EXIT
    THEN
    DUP _RTAPT-E.SESSION @ PT-STATE@ PT-ST-LOST = IF
        RTAPT-S-SESSION-LOST SWAP _RTAPT-QUARANTINE-ALL EXIT
    THEN
    DUP _RTAPT-E.OWNER-USED @ IF
        DUP _RTAPT-SESSION-ENDED? IF
            RTAPT-S-SESSION-LOST SWAP _RTAPT-QUARANTINE-ALL EXIT
        THEN
    THEN
    _RTAPT-E.SESSION @ PT-RETAINED-STATE@
    DUP PT-RET-ST-AVAILABLE = IF DROP RTAPT-S-OK EXIT THEN
    PT-RET-ST-CELL-ONLY = IF RTAPT-S-UNSUPPORTED ELSE
        RTAPT-S-WOULD-BLOCK
    THEN ;

: RTAPT-FINI  ( engine -- status )
    DUP _RTAPT-ENGINE-VALID? 0= IF DROP RTAPT-S-INVALID EXIT THEN
    DUP _RTAPT-E.BATCH-STATE @ RTAPT-BATCH-IDLE <> IF
        DROP RTAPT-S-BUSY EXIT
    THEN
    \ Live PT ownership keeps exact tombstone/quarantine evidence resident.
    \ Only a synchronized ANSI boundary with this session unowned proves that
    \ all remote generations are gone and permits local record erasure.
    DUP _RTAPT-E.OWNER-USED @
    OVER _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-NONE <> OR
    OVER _RTAPT-E.QUEUE-HEAD @ OR OVER _RTAPT-E.QUEUE-TAIL @ OR IF
        DUP _RTAPT-SESSION-ENDED? 0= IF DROP RTAPT-S-BUSY EXIT THEN
    THEN
    DUP _RTAPT-E.OWNERS-A @ OVER _RTAPT-E.OWNERS-U @ 0 FILL
    DUP _RTAPT-E.OPS-A @ OVER _RTAPT-E.OPS-U @ 0 FILL
    DUP _RTAPT-E.COPY-A @ OVER _RTAPT-E.COPY-U @ 0 FILL
    RTAPT-ENGINE-SIZE 0 FILL RTAPT-S-OK ;

\ =====================================================================
\  Exact owner lifecycle queue
\ =====================================================================

: _RTAPT-OWNER-NTH  ( index engine -- owner-record )
    _RTAPT-E.OWNERS-A @ SWAP RTAPT-OWNER-SIZE * + ;

VARIABLE _RTAPT-OF-E
VARIABLE _RTAPT-OF-OWNER
VARIABLE _RTAPT-OF-GEN
VARIABLE _RTAPT-OF-RESULT

: _RTAPT-OWNER-FIND  ( owner generation engine -- owner-record|0 )
    _RTAPT-OF-E ! _RTAPT-OF-GEN ! _RTAPT-OF-OWNER !
    0 _RTAPT-OF-RESULT !
    _RTAPT-OF-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        I _RTAPT-OF-E @ _RTAPT-OWNER-NTH DUP _RTAPT-O.STATE @
        RTAPT-OWNER-ST-FREE <> IF
            DUP _RTAPT-O.OWNER @ _RTAPT-OF-OWNER @ =
            OVER _RTAPT-O.GENERATION @ _RTAPT-OF-GEN @ = AND IF
                _RTAPT-OF-RESULT !
            ELSE DROP THEN
        ELSE DROP THEN
    LOOP
    _RTAPT-OF-RESULT @ ;

: _RTAPT-OWNER-ID-FIND  ( owner engine -- owner-record|0 )
    _RTAPT-OF-E ! _RTAPT-OF-OWNER ! 0 _RTAPT-OF-RESULT !
    _RTAPT-OF-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-OF-RESULT @ 0= IF
            I _RTAPT-OF-E @ _RTAPT-OWNER-NTH DUP _RTAPT-O.STATE @
            RTAPT-OWNER-ST-FREE <> IF
                DUP _RTAPT-O.OWNER @ _RTAPT-OF-OWNER @ = IF
                    _RTAPT-OF-RESULT !
                ELSE DROP THEN
            ELSE DROP THEN
        THEN
    LOOP
    _RTAPT-OF-RESULT @ ;

: _RTAPT-OWNER-FREE-SLOT  ( engine -- owner-record|0 )
    DUP _RTAPT-OF-E ! 0 _RTAPT-OF-RESULT !
    _RTAPT-OF-E @ _RTAPT-E.OWNER-CAP @ 0 ?DO
        _RTAPT-OF-RESULT @ 0= IF
            I _RTAPT-OF-E @ _RTAPT-OWNER-NTH DUP _RTAPT-O.STATE @
            RTAPT-OWNER-ST-FREE = IF _RTAPT-OF-RESULT ! ELSE DROP THEN
        THEN
    LOOP
    DROP _RTAPT-OF-RESULT @ ;

VARIABLE _RTAPT-Q-O
VARIABLE _RTAPT-Q-E

: _RTAPT-QUEUE-PUSH  ( owner-record engine -- )
    _RTAPT-Q-E ! _RTAPT-Q-O !
    0 _RTAPT-Q-O @ _RTAPT-O.NEXT !
    _RTAPT-Q-E @ _RTAPT-E.QUEUE-TAIL @ ?DUP IF
        _RTAPT-Q-O @ SWAP _RTAPT-O.NEXT !
    ELSE
        _RTAPT-Q-O @ _RTAPT-Q-E @ _RTAPT-E.QUEUE-HEAD !
    THEN
    _RTAPT-Q-O @ _RTAPT-Q-E @ _RTAPT-E.QUEUE-TAIL ! ;

: _RTAPT-QUEUE-POP  ( engine -- owner-record|0 )
    DUP _RTAPT-Q-E ! _RTAPT-E.QUEUE-HEAD @ DUP 0= IF EXIT THEN
    DUP _RTAPT-O.NEXT @ _RTAPT-Q-E @ _RTAPT-E.QUEUE-HEAD !
    _RTAPT-Q-E @ _RTAPT-E.QUEUE-HEAD @ 0= IF
        0 _RTAPT-Q-E @ _RTAPT-E.QUEUE-TAIL !
    THEN
    0 OVER _RTAPT-O.NEXT ! ;

VARIABLE _RTAPT-OO-E
VARIABLE _RTAPT-OO-O
VARIABLE _RTAPT-OO-OWNER
VARIABLE _RTAPT-OO-GEN
VARIABLE _RTAPT-OO-RQ
VARIABLE _RTAPT-OO-XQ
VARIABLE _RTAPT-OO-OQ
VARIABLE _RTAPT-OO-SQ
VARIABLE _RTAPT-OO-RBQ
VARIABLE _RTAPT-OO-UQ
VARIABLE _RTAPT-OO-SLQ
VARIABLE _RTAPT-OO-REUSED
VARIABLE _RTAPT-OO-PRIOR-GEN

: RTAPT-OWNER-OPEN  ( owner generation region-q resource-q object-q series-q
                       resource-byte-q utf8-byte-q sample-slot-q engine
                       -- status )
    _RTAPT-OO-E ! _RTAPT-OO-SLQ ! _RTAPT-OO-UQ ! _RTAPT-OO-RBQ !
    _RTAPT-OO-SQ ! _RTAPT-OO-OQ ! _RTAPT-OO-XQ ! _RTAPT-OO-RQ !
    _RTAPT-OO-GEN ! _RTAPT-OO-OWNER !
    _RTAPT-OO-E @ _RTAPT-ENGINE-VALID? 0= IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-OO-E @ _RTAPT-READY-STATUS DUP RTAPT-S-OK <> IF EXIT THEN DROP
    _RTAPT-OO-E @ _RTAPT-E.BATCH-STATE @ RTAPT-BATCH-IDLE <> IF
        RTAPT-S-BUSY EXIT
    THEN
    _RTAPT-OO-OWNER @ 0= _RTAPT-OO-GEN @ 0= OR IF RTAPT-S-INVALID EXIT THEN
    _RTAPT-OO-RQ @ 0xFFFFFFFF U>
    _RTAPT-OO-XQ @ 0xFFFFFFFF U> OR
    _RTAPT-OO-OQ @ 0xFFFFFFFF U> OR
    _RTAPT-OO-SQ @ 0xFFFFFFFF U> OR IF RTAPT-S-INVALID EXIT THEN
    0 _RTAPT-OO-REUSED !
    0 _RTAPT-OO-PRIOR-GEN !
    _RTAPT-OO-OWNER @ _RTAPT-OO-E @ _RTAPT-OWNER-ID-FIND ?DUP IF
        DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-TOMBSTONE <> IF
            DROP RTAPT-S-BUSY EXIT
        THEN
        DUP _RTAPT-O.GENERATION @ _RTAPT-OO-GEN @ U< 0= IF
            DROP RTAPT-S-BUSY EXIT
        THEN
        DUP _RTAPT-O.GENERATION @ _RTAPT-OO-PRIOR-GEN !
        _RTAPT-OO-O ! -1 _RTAPT-OO-REUSED !
    ELSE
        _RTAPT-OO-E @ _RTAPT-OWNER-FREE-SLOT DUP 0= IF
            DROP RTAPT-S-CAPACITY EXIT
        THEN _RTAPT-OO-O !
    THEN
    _RTAPT-OO-O @ RTAPT-OWNER-SIZE 0 FILL
    _RTAPT-OO-OWNER @ _RTAPT-OO-O @ _RTAPT-O.OWNER !
    _RTAPT-OO-GEN @ _RTAPT-OO-O @ _RTAPT-O.GENERATION !
    _RTAPT-OO-RQ @ _RTAPT-OO-O @ _RTAPT-O.REGIONS !
    _RTAPT-OO-XQ @ _RTAPT-OO-O @ _RTAPT-O.RESOURCES !
    _RTAPT-OO-OQ @ _RTAPT-OO-O @ _RTAPT-O.OBJECTS !
    _RTAPT-OO-SQ @ _RTAPT-OO-O @ _RTAPT-O.SERIES !
    _RTAPT-OO-RBQ @ _RTAPT-OO-O @ _RTAPT-O.RES-BYTES !
    _RTAPT-OO-UQ @ _RTAPT-OO-O @ _RTAPT-O.UTF8-BYTES !
    _RTAPT-OO-SLQ @ _RTAPT-OO-O @ _RTAPT-O.SAMPLES !
    _RTAPT-OO-PRIOR-GEN @ _RTAPT-OO-O @ _RTAPT-O.PRIOR-GENERATION !
    _RTAPT-OO-REUSED @ IF RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED
        ELSE RTAPT-OWNER-ST-OPEN-QUEUED THEN
    _RTAPT-OO-O @ _RTAPT-O.STATE !
    _RTAPT-OO-REUSED @ 0= IF 1 _RTAPT-OO-E @ _RTAPT-E.OWNER-USED +! THEN
    _RTAPT-OO-O @ _RTAPT-OO-E @ _RTAPT-QUEUE-PUSH
    RTAPT-S-OK _RTAPT-OO-E @ _RTAPT-E.LAST-STATUS !
    RTAPT-S-OK ;

: RTAPT-OWNER-STATE@  ( owner generation engine -- owner-state status )
    DUP _RTAPT-ENGINE-VALID? 0= IF 2DROP DROP RTAPT-OWNER-ST-FREE
        RTAPT-S-INVALID EXIT
    THEN
    DUP _RTAPT-READY-STATUS DROP
    _RTAPT-OWNER-FIND DUP 0= IF
        DROP RTAPT-OWNER-ST-FREE
        _RTAPT-OF-E @ _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
            _RTAPT-OF-E @ _RTAPT-E.LAST-STATUS @
        ELSE RTAPT-S-OK THEN EXIT
    THEN
    _RTAPT-O.STATE @ DUP RTAPT-OWNER-ST-QUARANTINED = IF
        _RTAPT-OF-E @ _RTAPT-E.LAST-STATUS @
    ELSE RTAPT-S-OK THEN ;

VARIABLE _RTAPT-OD-E
VARIABLE _RTAPT-OD-O
VARIABLE _RTAPT-OD-STATE

: RTAPT-OWNER-DROP  ( owner generation engine -- status )
    DUP _RTAPT-OD-E !
    DUP _RTAPT-ENGINE-VALID? 0= IF 2DROP DROP RTAPT-S-INVALID EXIT THEN
    DUP _RTAPT-READY-STATUS DUP RTAPT-S-OK <> IF
        >R 2DROP DROP R> EXIT
    THEN DROP
    DUP _RTAPT-E.BATCH-STATE @ RTAPT-BATCH-IDLE <> IF
        2DROP DROP RTAPT-S-BUSY EXIT
    THEN
    _RTAPT-OWNER-FIND DUP 0= IF DROP RTAPT-S-INVALID EXIT THEN
    DUP _RTAPT-OD-O ! _RTAPT-O.STATE @ DUP _RTAPT-OD-STATE !
    DUP RTAPT-OWNER-ST-OPEN = IF
        DROP RTAPT-OWNER-ST-DROP-QUEUED
    ELSE DUP RTAPT-OWNER-ST-TOMBSTONE = IF
        DROP RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED
    ELSE RTAPT-OWNER-ST-DROPPING = IF
        _RTAPT-OD-O @ _RTAPT-O.WIRE-STATUS @ DUP PT-TX-RESULT-INVALID =
        SWAP PT-TX-RESULT-STALE = OR 0= IF RTAPT-S-BUSY EXIT THEN
        RTAPT-OWNER-ST-DROP-RETRY-QUEUED
    ELSE RTAPT-S-BUSY EXIT THEN THEN THEN
    _RTAPT-OD-O @ _RTAPT-O.STATE !
    _RTAPT-OD-O @ _RTAPT-OD-E @ _RTAPT-QUEUE-PUSH
    RTAPT-S-OK _RTAPT-OD-E @ _RTAPT-E.LAST-STATUS !
    RTAPT-S-OK ;

\ =====================================================================
\  PT lifecycle completion reconciliation
\ =====================================================================

VARIABLE _RTAPT-ST-E
VARIABLE _RTAPT-ST-O
VARIABLE _RTAPT-ST-PT
VARIABLE _RTAPT-ST-HAS
VARIABLE _RTAPT-ST-TOMBSTONE
VARIABLE _RTAPT-ST-STATE

: _RTAPT-LAST-RESULT!  ( wire-status detail revision engine -- )
    >R
    R@ _RTAPT-E.LAST-REVISION !
    R@ _RTAPT-E.LAST-DETAIL !
    R> _RTAPT-E.LAST-WIRE ! ;

: _RTAPT-ACTIVE-CLEAR  ( engine -- )
    DUP _RTAPT-E.ACTIVE-O OFF
    _RTAPT-ACTIVE-NONE SWAP _RTAPT-E.ACTIVE-KIND ! ;

: _RTAPT-OWNER-CLEAR  ( owner-record engine -- )
    >R RTAPT-OWNER-SIZE 0 FILL
    R@ _RTAPT-E.OWNER-USED @ 1- R@ _RTAPT-E.OWNER-USED !
    R> DROP ;

VARIABLE _RTAPT-OT-O
VARIABLE _RTAPT-OT-OWNER
VARIABLE _RTAPT-OT-GENERATION

\ A settled tombstone carries only the exact tuple.  Quota authority and
\ transient queue/result fields are released at the successful drop boundary.
: _RTAPT-OWNER>TOMBSTONE  ( owner-record -- )
    DUP _RTAPT-OT-O !
    DUP _RTAPT-O.OWNER @ _RTAPT-OT-OWNER !
    _RTAPT-O.GENERATION @ _RTAPT-OT-GENERATION !
    _RTAPT-OT-O @ RTAPT-OWNER-SIZE 0 FILL
    _RTAPT-OT-OWNER @ _RTAPT-OT-O @ _RTAPT-O.OWNER !
    _RTAPT-OT-GENERATION @ _RTAPT-OT-O @ _RTAPT-O.GENERATION !
    RTAPT-OWNER-ST-TOMBSTONE _RTAPT-OT-O @ _RTAPT-O.STATE ! ;

\ A newer-generation open candidate does not supersede the terminal's exact
\ tombstone until RET_OK.  Any local admission failure or rejected result
\ restores the prior tuple instead of fabricating a new tombstone.
: _RTAPT-OWNER-RESTORE-TOMBSTONE  ( owner-record -- flag )
    DUP _RTAPT-O.PRIOR-GENERATION @ DUP 0= IF 2DROP 0 EXIT THEN
    _RTAPT-OT-GENERATION !
    DUP _RTAPT-O.OWNER @ _RTAPT-OT-OWNER !
    DUP RTAPT-OWNER-SIZE 0 FILL
    _RTAPT-OT-OWNER @ OVER _RTAPT-O.OWNER !
    _RTAPT-OT-GENERATION @ OVER _RTAPT-O.GENERATION !
    RTAPT-OWNER-ST-TOMBSTONE SWAP _RTAPT-O.STATE ! -1 ;

: _RTAPT-COMPLETION-IDENTITY?  ( expected-kind expected-request owner e -- flag )
    >R
    R@ _RTAPT-E.COMPLETION PT-COMPLETION-OWNER@ =
    R@ _RTAPT-E.COMPLETION PT-COMPLETION-REQUEST@ ROT = AND
    R@ _RTAPT-E.COMPLETION PT-COMPLETION-KIND@ ROT = AND
    R> DROP ;

: _RTAPT-COMPLETION-GENERATION?  ( owner-record engine -- flag )
    >R _RTAPT-O.GENERATION @
    R> _RTAPT-E.COMPLETION PT-COMPLETION-GENERATION@ = ;

: _RTAPT-RECONCILE-OPEN  ( engine -- status )
    DUP _RTAPT-ST-E ! _RTAPT-E.ACTIVE-O @ _RTAPT-ST-O !
    _RTAPT-ST-O @ _RTAPT-O.STATE @ RTAPT-OWNER-ST-TOMBSTONE-OPENING =
        _RTAPT-ST-TOMBSTONE !
    PT-COMPLETE-RET PT-REQUEST-OWNER-OPEN
    _RTAPT-ST-O @ _RTAPT-O.OWNER @ _RTAPT-ST-E @
    _RTAPT-COMPLETION-IDENTITY? 0= IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-O @ _RTAPT-ST-E @ _RTAPT-COMPLETION-GENERATION? 0= IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-STATUS@ DUP
        DUP _RTAPT-ST-PT ! _RTAPT-ST-O @ _RTAPT-O.WIRE-STATUS !
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-DETAIL@
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-REVISION@
    _RTAPT-ST-E @ _RTAPT-LAST-RESULT!
    _RTAPT-ST-PT @ PT-RET-ABORTED = IF
        RTAPT-S-SESSION-LOST _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-ACTIVE-CLEAR
    _RTAPT-ST-PT @ PT-RET-OK = IF
        0 _RTAPT-ST-O @ _RTAPT-O.PRIOR-GENERATION !
        RTAPT-OWNER-ST-OPEN _RTAPT-ST-O @ _RTAPT-O.STATE ! RTAPT-S-OK
    ELSE
        _RTAPT-ST-TOMBSTONE @ IF
            _RTAPT-ST-O @ _RTAPT-OWNER-RESTORE-TOMBSTONE 0= IF
                RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
            THEN
        ELSE _RTAPT-ST-O @ _RTAPT-ST-E @ _RTAPT-OWNER-CLEAR THEN
        RTAPT-S-REJECTED
    THEN ;

: _RTAPT-RECONCILE-DROP  ( engine -- status )
    DUP _RTAPT-ST-E ! _RTAPT-E.ACTIVE-O @ _RTAPT-ST-O !
    _RTAPT-ST-O @ _RTAPT-O.STATE @ RTAPT-OWNER-ST-TOMBSTONE-DROPPING =
        _RTAPT-ST-TOMBSTONE !
    PT-COMPLETE-TX PT-REQUEST-OWNER-DROP
    _RTAPT-ST-O @ _RTAPT-O.OWNER @ _RTAPT-ST-E @
    _RTAPT-COMPLETION-IDENTITY? 0= IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-O @ _RTAPT-ST-E @ _RTAPT-COMPLETION-GENERATION? 0= IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-STATUS@ DUP
        DUP _RTAPT-ST-PT ! _RTAPT-ST-O @ _RTAPT-O.WIRE-STATUS !
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-DETAIL@
    _RTAPT-ST-E @ _RTAPT-E.COMPLETION PT-COMPLETION-REVISION@
    _RTAPT-ST-E @ _RTAPT-LAST-RESULT!
    _RTAPT-ST-PT @ PT-TX-RESULT-ABORTED = IF
        \ Crossed-reset replay is deliberately not guessed in this slice.
        RTAPT-S-SESSION-LOST _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-PT @ PT-TX-RESULT-STALE U> IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-ACTIVE-CLEAR
    _RTAPT-ST-PT @ PT-TX-RESULT-OK = IF
        _RTAPT-ST-O @ _RTAPT-OWNER>TOMBSTONE
        RTAPT-S-OK EXIT
    THEN
    _RTAPT-ST-TOMBSTONE @ IF
        _RTAPT-ST-O @ _RTAPT-OWNER>TOMBSTONE
    ELSE RTAPT-OWNER-ST-DROPPING _RTAPT-ST-O @ _RTAPT-O.STATE ! THEN
    RTAPT-S-REJECTED ;

: _RTAPT-POLL-COMPLETION  ( engine -- status had-completion )
    DUP _RTAPT-ST-E !
    DUP _RTAPT-E.COMPLETION SWAP _RTAPT-E.SESSION @ PT-COMPLETION-POLL
    _RTAPT-ST-HAS ! _RTAPT-PT>STATUS _RTAPT-ST-PT !
    _RTAPT-ST-PT @ RTAPT-S-SESSION-LOST = IF
        RTAPT-S-SESSION-LOST _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL 0 EXIT
    THEN
    _RTAPT-ST-PT @ RTAPT-S-INVALID = IF
        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL 0 EXIT
    THEN
    _RTAPT-ST-PT @ RTAPT-S-OK <> IF _RTAPT-ST-PT @ 0 EXIT THEN
    _RTAPT-ST-HAS @ 0= IF RTAPT-S-OK 0 EXIT THEN
    _RTAPT-ST-E @ _RTAPT-E.ACTIVE-KIND @
    DUP _RTAPT-ACTIVE-OWNER-OPEN = IF
        DROP _RTAPT-ST-E @ _RTAPT-RECONCILE-OPEN -1 EXIT
    THEN
    _RTAPT-ACTIVE-OWNER-DROP = IF
        _RTAPT-ST-E @ _RTAPT-RECONCILE-DROP -1 EXIT
    THEN
    RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL -1 ;

: _RTAPT-OWNER-SEND  ( owner-record engine -- status )
    _RTAPT-ST-E ! _RTAPT-ST-O !
    _RTAPT-ST-O @ _RTAPT-O.STATE @ DUP _RTAPT-ST-STATE !
    DUP RTAPT-OWNER-ST-OPEN-QUEUED =
    SWAP RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED = OR IF
        _RTAPT-ST-O @ _RTAPT-O.OWNER @
        _RTAPT-ST-O @ _RTAPT-O.GENERATION @
        _RTAPT-ST-O @ _RTAPT-O.REGIONS @
        _RTAPT-ST-O @ _RTAPT-O.RESOURCES @
        _RTAPT-ST-O @ _RTAPT-O.OBJECTS @
        _RTAPT-ST-O @ _RTAPT-O.SERIES @
        _RTAPT-ST-O @ _RTAPT-O.RES-BYTES @
        _RTAPT-ST-O @ _RTAPT-O.UTF8-BYTES @
        _RTAPT-ST-O @ _RTAPT-O.SAMPLES @
        _RTAPT-ST-E @ _RTAPT-E.SESSION @ PT-OWNER-OPEN _RTAPT-PT>STATUS
        DUP RTAPT-S-OK = IF
            DROP
            _RTAPT-ST-STATE @ RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED = IF
                RTAPT-OWNER-ST-TOMBSTONE-OPENING
            ELSE RTAPT-OWNER-ST-OPENING THEN
            _RTAPT-ST-O @ _RTAPT-O.STATE !
            _RTAPT-ST-O @ _RTAPT-ST-E @ _RTAPT-E.ACTIVE-O !
            _RTAPT-ACTIVE-OWNER-OPEN _RTAPT-ST-E @ _RTAPT-E.ACTIVE-KIND !
            RTAPT-S-OK
        THEN EXIT
    THEN
    _RTAPT-ST-O @ _RTAPT-O.STATE @ DUP _RTAPT-ST-STATE !
    DUP RTAPT-OWNER-ST-DROP-QUEUED =
    OVER RTAPT-OWNER-ST-DROP-RETRY-QUEUED = OR
    SWAP RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED = OR 0= IF
        RTAPT-S-INVALID EXIT
    THEN
    _RTAPT-ST-O @ _RTAPT-O.OWNER @
    _RTAPT-ST-O @ _RTAPT-O.GENERATION @
    _RTAPT-ST-E @ _RTAPT-E.SESSION @ PT-OWNER-DROP _RTAPT-PT>STATUS
    DUP RTAPT-S-OK = IF
        DROP
        _RTAPT-ST-STATE @ RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED = IF
            RTAPT-OWNER-ST-TOMBSTONE-DROPPING
        ELSE _RTAPT-ST-STATE @ RTAPT-OWNER-ST-DROP-RETRY-QUEUED = IF
            RTAPT-OWNER-ST-DROP-RETRY-DROPPING
        ELSE RTAPT-OWNER-ST-DROPPING THEN THEN
        _RTAPT-ST-O @ _RTAPT-O.STATE !
        _RTAPT-ST-O @ _RTAPT-ST-E @ _RTAPT-E.ACTIVE-O !
        _RTAPT-ACTIVE-OWNER-DROP _RTAPT-ST-E @ _RTAPT-E.ACTIVE-KIND !
        RTAPT-S-OK
    THEN ;

: _RTAPT-OWNER-ADMISSION-FAILED  ( owner-record engine -- flag )
    >R
    DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-OPEN-QUEUED = IF
        R> _RTAPT-OWNER-CLEAR -1 EXIT
    THEN
    DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED = IF
        _RTAPT-OWNER-RESTORE-TOMBSTONE R> DROP EXIT
    THEN
    DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-DROP-QUEUED = IF
        RTAPT-OWNER-ST-OPEN SWAP _RTAPT-O.STATE ! R> DROP -1 EXIT
    THEN
    DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-DROP-RETRY-QUEUED = IF
        RTAPT-OWNER-ST-DROPPING SWAP _RTAPT-O.STATE ! R> DROP -1 EXIT
    THEN
    DUP _RTAPT-O.STATE @ RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED = IF
        RTAPT-OWNER-ST-TOMBSTONE SWAP _RTAPT-O.STATE ! R> DROP -1 EXIT
    THEN
    DROP R> DROP 0 ;

\ RTAPT-STEP performs at most one completion reconciliation or one lifecycle
\ publication.  It never calls PT-SERVICE and cannot consume input events.
: RTAPT-STEP  ( engine -- status )
    DUP _RTAPT-ENGINE-VALID? 0= IF DROP RTAPT-S-INVALID EXIT THEN
    DUP _RTAPT-ST-E !
    DUP _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-QUARANTINED = IF
        _RTAPT-E.LAST-STATUS @ EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.ACTIVE-KIND @ _RTAPT-ACTIVE-NONE <> IF
        _RTAPT-ST-E @ _RTAPT-POLL-COMPLETION
        IF DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT THEN
        DUP RTAPT-S-OK <> IF
            DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT
        THEN DROP
        RTAPT-S-WOULD-BLOCK DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-READY-STATUS DUP RTAPT-S-OK <> IF
        DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT
    THEN DROP
    _RTAPT-ST-E @ _RTAPT-E.QUEUE-HEAD @ 0= IF
        RTAPT-S-OK DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! EXIT
    THEN
    _RTAPT-ST-E @ _RTAPT-E.QUEUE-HEAD @ DUP 0= IF
        DROP RTAPT-S-INVALID
    ELSE
        DUP _RTAPT-ST-O ! _RTAPT-ST-E @ _RTAPT-OWNER-SEND
        DUP RTAPT-S-WOULD-BLOCK <> IF
            DUP _RTAPT-ST-PT !
            _RTAPT-ST-E @ _RTAPT-QUEUE-POP
            _RTAPT-ST-O @ <> IF
                DROP RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL
            ELSE
                DROP
                _RTAPT-ST-PT @ RTAPT-S-OK <> IF
                    _RTAPT-ST-O @ _RTAPT-ST-E @
                    _RTAPT-OWNER-ADMISSION-FAILED 0= IF
                        RTAPT-S-INVALID _RTAPT-ST-E @ _RTAPT-QUARANTINE-ALL
                    ELSE _RTAPT-ST-PT @ RTAPT-S-SESSION-LOST = IF
                        RTAPT-S-SESSION-LOST _RTAPT-ST-E @
                            _RTAPT-QUARANTINE-ALL
                    ELSE _RTAPT-ST-PT @ THEN THEN
                ELSE RTAPT-S-OK THEN
            THEN
        THEN
    THEN
    DUP _RTAPT-ST-E @ _RTAPT-E.LAST-STATUS ! ;
