\ =====================================================================
\  engine-apt1.f -- RTAPT provider bridge for the neutral RTE facade
\ =====================================================================
\
\  This is the sole mapping between the generic retained-engine interface and
\  concrete APT-1 engine.  It is loaded only by an outer product composition;
\  UIDL lifecycle code depends on engine.f and never names RTAPT or PT.
\
\  Prefix:   RTAPTE- (public), _RTAPTE- (private)
\  Provider: akashic-tui-rtapte

PROVIDED akashic-tui-rtapte

REQUIRE engine.f
REQUIRE apt1-engine.f

: _RTAPTE-STATUS>RTE  ( rtapt-status -- rte-status )
    DUP RTAPT-S-OK = IF DROP RTE-S-OK EXIT THEN
    DUP RTAPT-S-WOULD-BLOCK = IF DROP RTE-S-WOULD-BLOCK EXIT THEN
    DUP RTAPT-S-BUSY = IF DROP RTE-S-WOULD-BLOCK EXIT THEN
    DUP RTAPT-S-SESSION-LOST = IF DROP RTE-S-SESSION-LOST EXIT THEN
    DUP RTAPT-S-INVALID = IF DROP RTE-S-INVALID EXIT THEN
    DUP RTAPT-S-UNSUPPORTED = IF DROP RTE-S-UNAVAILABLE EXIT THEN
    DUP RTAPT-S-CAPACITY = IF DROP RTE-S-CAPACITY EXIT THEN
    DUP RTAPT-S-REJECTED = IF DROP RTE-S-STALE EXIT THEN
    DROP RTE-S-INVALID ;

: _RTAPTE-OWNER-ST>RTE  ( rtapt-owner-state -- rte-owner-state )
    DUP RTAPT-OWNER-ST-FREE = IF DROP RTE-OWNER-ST-FREE EXIT THEN
    DUP RTAPT-OWNER-ST-OPEN-QUEUED =
    OVER RTAPT-OWNER-ST-OPENING = OR
    OVER RTAPT-OWNER-ST-TOMBSTONE-OPEN-QUEUED = OR
    OVER RTAPT-OWNER-ST-TOMBSTONE-OPENING = OR IF
        DROP RTE-OWNER-ST-OPENING EXIT
    THEN
    DUP RTAPT-OWNER-ST-OPEN = IF DROP RTE-OWNER-ST-OPEN EXIT THEN
    DUP RTAPT-OWNER-ST-DROP-QUEUED =
    OVER RTAPT-OWNER-ST-DROPPING = OR
    OVER RTAPT-OWNER-ST-TOMBSTONE-DROP-QUEUED = OR
    OVER RTAPT-OWNER-ST-TOMBSTONE-DROPPING = OR
    OVER RTAPT-OWNER-ST-DROP-RETRY-QUEUED = OR
    OVER RTAPT-OWNER-ST-DROP-RETRY-DROPPING = OR IF
        DROP RTE-OWNER-ST-DROPPING EXIT
    THEN
    DUP RTAPT-OWNER-ST-TOMBSTONE = IF
        DROP RTE-OWNER-ST-TOMBSTONE EXIT
    THEN
    RTAPT-OWNER-ST-QUARANTINED = IF
        RTE-OWNER-ST-QUARANTINED EXIT
    THEN
    RTE-OWNER-ST-FREE ;

: _RTAPTE-UPDATE-ST>RTE  ( rtapt-update-state -- rte-update-state )
    DUP RTAPT-UPDATE-IDLE = IF DROP RTE-UPDATE-IDLE EXIT THEN
    DUP RTAPT-UPDATE-CAPTURING = IF DROP RTE-UPDATE-CAPTURING EXIT THEN
    DUP RTAPT-UPDATE-SEALED = IF DROP RTE-UPDATE-SEALED EXIT THEN
    DUP RTAPT-UPDATE-CELL-OPEN = IF DROP RTE-UPDATE-PUBLISHING EXIT THEN
    RTAPT-UPDATE-AWAITING = IF RTE-UPDATE-AWAITING EXIT THEN
    RTE-UPDATE-IDLE ;

: _RTAPTE-MODE>RTAPT  ( rte-mode -- rtapt-mode flag )
    DUP RTE-RETAINED-DELTA = IF DROP RTAPT-RICH-DELTA -1 EXIT THEN
    DUP RTE-RETAINED-REPLACE-START = IF
        DROP RTAPT-RICH-REPLACE-START -1 EXIT
    THEN
    DUP RTE-RETAINED-REPLACE-CONTINUE = IF
        DROP RTAPT-RICH-REPLACE-CONTINUE -1 EXIT
    THEN
    DUP RTE-RETAINED-LAYOUT-START = IF
        DROP RTAPT-RICH-LAYOUT-START -1 EXIT
    THEN
    RTE-RETAINED-LAYOUT-CONTINUE = IF
        RTAPT-RICH-LAYOUT-CONTINUE -1 EXIT
    THEN
    0 0 ;

: _RTAPTE-DISPOSITION>RTAPT  ( rte-disposition -- rtapt-disposition flag )
    DUP RTE-COMMIT = IF DROP RTAPT-COMMIT -1 EXIT THEN
    RTE-COMMIT-AND-REVEAL = IF
        RTAPT-COMMIT-AND-REVEAL -1 EXIT
    THEN
    0 0 ;

\ Facade callbacks receive their explicit RTAPT engine as the final context.
: _RTAPTE-DISJOINT?  ( a u engine -- flag )
    RTAPT-STORAGE-DISJOINT? ;

: _RTAPTE-STATUS@  ( engine -- status )
    RTAPT-STATUS _RTAPTE-STATUS>RTE ;

: _RTAPTE-UPDATE-STATE@  ( engine -- update-state status )
    RTAPT-UPDATE-STATE@
    _RTAPTE-STATUS>RTE >R _RTAPTE-UPDATE-ST>RTE R> ;

: _RTAPTE-FEATURES>RTE  ( rtapt-features -- rte-features )
    0 SWAP
    DUP RTAPT-F-CORE AND IF SWAP RTE-F-CORE OR SWAP THEN
    DUP RTAPT-F-VECTOR AND IF SWAP RTE-F-VECTOR OR SWAP THEN
    DUP RTAPT-F-IMAGE AND IF SWAP RTE-F-IMAGE OR SWAP THEN
    DUP RTAPT-F-INSTRUMENT AND IF SWAP RTE-F-INSTRUMENT OR SWAP THEN
    DUP RTAPT-F-SERIES AND IF SWAP RTE-F-SERIES OR SWAP THEN
    DUP RTAPT-F-CADENCE AND IF SWAP RTE-F-CADENCE OR SWAP THEN
    DUP RTAPT-F-CONTROLS AND IF SWAP RTE-F-CONTROLS OR SWAP THEN
    DUP RTAPT-F-CONTROL-COLLECTIONS AND IF
        SWAP RTE-F-CONTROL-COLLECTIONS OR SWAP
    THEN
    DROP ;

VARIABLE _RTAPTE-LS-DST
VARIABLE _RTAPTE-LS-SRC
VARIABLE _RTAPTE-LS-ENGINE
VARIABLE _RTAPTE-LS-STATUS

: _RTAPTE-LIMITS-SCRUB  ( -- )
    0 _RTAPTE-LS-DST !
    0 _RTAPTE-LS-SRC !
    0 _RTAPTE-LS-ENGINE !
    0 _RTAPTE-LS-STATUS ! ;

: _RTAPTE-LIMITS-COPY  ( -- )
    _RTAPTE-LS-SRC @ _RTAPT-L.FEATURES @ _RTAPTE-FEATURES>RTE
        _RTAPTE-LS-DST @ _RTE-L.FEATURES !
    _RTAPTE-LS-SRC @ _RTAPT-L.OWNER-RECORDS @
        _RTAPTE-LS-DST @ _RTE-L.OWNER-RECORDS !
    _RTAPTE-LS-SRC @ _RTAPT-L.LIVE-OWNERS @
        _RTAPTE-LS-DST @ _RTE-L.LIVE-OWNERS !
    _RTAPTE-LS-SRC @ _RTAPT-L.REGIONS @
        _RTAPTE-LS-DST @ _RTE-L.REGIONS !
    _RTAPTE-LS-SRC @ _RTAPT-L.RESOURCES @
        _RTAPTE-LS-DST @ _RTE-L.RESOURCES !
    _RTAPTE-LS-SRC @ _RTAPT-L.OBJECTS @
        _RTAPTE-LS-DST @ _RTE-L.OBJECTS !
    _RTAPTE-LS-SRC @ _RTAPT-L.SERIES @
        _RTAPTE-LS-DST @ _RTE-L.SERIES !
    _RTAPTE-LS-SRC @ _RTAPT-L.OPS @
        _RTAPTE-LS-DST @ _RTE-L.OPS !
    _RTAPTE-LS-SRC @ _RTAPT-L.UPDATE-BYTES @
        _RTAPTE-LS-DST @ _RTE-L.UPDATE-BYTES !
    _RTAPTE-LS-SRC @ _RTAPT-L.CHUNK-BYTES @
        _RTAPTE-LS-DST @ _RTE-L.CHUNK-BYTES !
    _RTAPTE-LS-SRC @ _RTAPT-L.RESOURCE-BYTES @
        _RTAPTE-LS-DST @ _RTE-L.RESOURCE-BYTES !
    _RTAPTE-LS-SRC @ _RTAPT-L.IMAGE-WIDTH @
        _RTAPTE-LS-DST @ _RTE-L.IMAGE-WIDTH !
    _RTAPTE-LS-SRC @ _RTAPT-L.IMAGE-HEIGHT @
        _RTAPTE-LS-DST @ _RTE-L.IMAGE-HEIGHT !
    _RTAPTE-LS-SRC @ _RTAPT-L.PATH-POINTS @
        _RTAPTE-LS-DST @ _RTE-L.PATH-POINTS !
    _RTAPTE-LS-SRC @ _RTAPT-L.GLYPH-RUN-BYTES @
        _RTAPTE-LS-DST @ _RTE-L.GLYPH-RUN-BYTES !
    _RTAPTE-LS-SRC @ _RTAPT-L.UTF8-BYTES @
        _RTAPTE-LS-DST @ _RTE-L.UTF8-BYTES !
    _RTAPTE-LS-SRC @ _RTAPT-L.SAMPLES-APPEND @
        _RTAPTE-LS-DST @ _RTE-L.SAMPLES-APPEND !
    _RTAPTE-LS-SRC @ _RTAPT-L.SERIES-HISTORY @
        _RTAPTE-LS-DST @ _RTE-L.SERIES-HISTORY !
    _RTAPTE-LS-SRC @ _RTAPT-L.SAMPLE-SLOTS @
        _RTAPTE-LS-DST @ _RTE-L.SAMPLE-SLOTS !
    _RTAPTE-LS-SRC @ _RTAPT-L.MIN-INTERVAL-US @
        _RTAPTE-LS-DST @ _RTE-L.MIN-INTERVAL-US !
    _RTAPTE-LS-SRC @ _RTAPT-L.OUTBOUND-PAYLOAD @
        _RTAPTE-LS-DST @ _RTE-L.OUTBOUND-PAYLOAD ! ;

\ Facade callback.  A provider refusal never writes the caller's neutral
\ record; a successful call copies every field from the call-borrowed RTAPT
\ snapshot and retains no provider or destination pointer.
: _RTAPTE-LIMITS@  ( limits engine -- status )
    _RTAPTE-LS-ENGINE ! _RTAPTE-LS-DST !
    _RTAPTE-LS-ENGINE @ RTAPT-LIMITS@
    _RTAPTE-LS-STATUS ! _RTAPTE-LS-SRC !
    _RTAPTE-LS-STATUS @ RTAPT-S-OK <> IF
        _RTAPTE-LS-STATUS @ _RTAPTE-STATUS>RTE
        _RTAPTE-LIMITS-SCRUB EXIT
    THEN
    \ RTAPT-LIMITS@ returns one already provider-validated snapshot.  Map
    \ each field explicitly; RTE-LIMITS@ performs the sole neutral validation
    \ on this destination after the callback returns.
    _RTAPTE-LIMITS-COPY
    RTE-S-OK _RTAPTE-LIMITS-SCRUB ;

: _RTAPTE-OWNER-OPEN  ( owner generation region-q resource-q object-q series-q resource-bytes utf8-bytes sample-slots engine -- status )
    RTAPT-OWNER-OPEN _RTAPTE-STATUS>RTE ;

: _RTAPTE-OWNER-STATE@  ( owner generation engine -- owner-state status )
    RTAPT-OWNER-STATE@
    _RTAPTE-STATUS>RTE >R _RTAPTE-OWNER-ST>RTE R> ;

: _RTAPTE-RETAINED-BEGIN  ( rte-mode engine -- status )
    SWAP _RTAPTE-MODE>RTAPT 0= IF 2DROP RTE-S-INVALID EXIT THEN
    SWAP RTAPT-RICH-BEGIN _RTAPTE-STATUS>RTE ;

: _RTAPTE-REGION-DEFINE
    ( owner generation region x y cols rows z flags engine -- status )
    RTAPT-REGION-DEFINE _RTAPTE-STATUS>RTE ;

: _RTAPTE-GLYPH-RUN-PREFLIGHT  ( plan engine -- status )
    \ Neutral validation admits sparse monotone object IDs.  Pass the plan
    \ intact so RTAPT keeps ID high-water separate from count-based quota.
    RTAPT-GLYPH-RUN-PREFLIGHT _RTAPTE-STATUS>RTE ;

\ The public facade has already made one full pass over the caller's item
\ bank.  Forward its certified aggregates with O(1) header reads; neither the
\ bridge nor the provider needs to rescan that bank before the first offer.
: _RTAPTE-CONTROL-PREFLIGHT
    ( plan count variable-bytes aligned-variable max-variable last-id collection-controls semantic-items utf8-bytes engine -- status )
    >R >R >R >R >R >R >R >R >R
    DUP _RTE-CP.OWNER @ SWAP
    DUP _RTE-CP.GENERATION @ SWAP
    DUP _RTE-CP.SURFACE-COLS @ SWAP
    DUP _RTE-CP.SURFACE-ROWS @ SWAP
    DUP _RTE-CP.REGION-ID @ SWAP
    DUP _RTE-CP.REGION-X @ SWAP
    DUP _RTE-CP.REGION-Y @ SWAP
    DUP _RTE-CP.REGION-COLS @ SWAP
    DUP _RTE-CP.REGION-ROWS @ SWAP
    DUP _RTE-CP.REGION-Z @ SWAP
    DUP _RTE-CP.REGION-FLAGS @ SWAP DROP
    R> R> R> R> R> R> R> R> R>
    RTAPT-CONTROL-PREFLIGHT _RTAPTE-STATUS>RTE ;

: _RTAPTE-HYBRID-PREFLIGHT  ( checked-summary engine -- status )
    RTAPT-HYBRID-PREFLIGHT _RTAPTE-STATUS>RTE ;

: _RTAPTE-GLYPH-RUN-DEFINE  ( run engine -- status )
    >R >R
    R@ _RTE-GLYPH-RUN.OWNER @
    R@ _RTE-GLYPH-RUN.GENERATION @
    R@ _RTE-GLYPH-RUN.OBJECT @
    R@ _RTE-GLYPH-RUN.REGION @
    R@ _RTE-GLYPH-RUN.PARENT @
    R@ _RTE-GLYPH-RUN.ROW @
    R@ _RTE-GLYPH-RUN.COL @
    R@ _RTE-GLYPH-RUN.HEIGHT @
    R@ _RTE-GLYPH-RUN.WIDTH @
    R@ _RTE-GLYPH-RUN.ROOT-HEIGHT @
    R@ _RTE-GLYPH-RUN.ROOT-WIDTH @
    R@ _RTE-GLYPH-RUN.Z @
    R@ _RTE-GLYPH-RUN.VISIBLE @
    R@ _RTE-GLYPH-RUN.FG-RGBA @
    R@ _RTE-GLYPH-RUN.BG-RGBA @
    R@ _RTE-GLYPH-RUN.ATTRS @
    R@ _RTE-GLYPH-RUN.TEXT-A @
    R@ _RTE-GLYPH-RUN.TEXT-U @
    R> DROP R>
    RTAPT-GLYPH-RUN-DEFINE _RTAPTE-STATUS>RTE ;

: _RTAPTE-GLYPH-RUN-REPLACE  ( run engine -- status )
    >R >R
    R@ _RTE-GLYPH-RUN.OWNER @
    R@ _RTE-GLYPH-RUN.GENERATION @
    R@ _RTE-GLYPH-RUN.OBJECT @
    R@ _RTE-GLYPH-RUN.REGION @
    R@ _RTE-GLYPH-RUN.PARENT @
    R@ _RTE-GLYPH-RUN.ROW @
    R@ _RTE-GLYPH-RUN.COL @
    R@ _RTE-GLYPH-RUN.HEIGHT @
    R@ _RTE-GLYPH-RUN.WIDTH @
    R@ _RTE-GLYPH-RUN.ROOT-HEIGHT @
    R@ _RTE-GLYPH-RUN.ROOT-WIDTH @
    R@ _RTE-GLYPH-RUN.Z @
    R@ _RTE-GLYPH-RUN.VISIBLE @
    R@ _RTE-GLYPH-RUN.FG-RGBA @
    R@ _RTE-GLYPH-RUN.BG-RGBA @
    R@ _RTE-GLYPH-RUN.ATTRS @
    R@ _RTE-GLYPH-RUN.TEXT-A @
    R@ _RTE-GLYPH-RUN.TEXT-U @
    R> DROP R>
    RTAPT-GLYPH-RUN-REPLACE _RTAPTE-STATUS>RTE ;

: _RTAPTE-CONTROL-KIND>RTAPT  ( rte-kind -- rtapt-kind )
    DUP RTE-CONTROL-MENU-BAR = IF
        DROP RTAPT-CONTROL-MENUBAR EXIT
    THEN
    DUP RTE-CONTROL-MENU = IF DROP RTAPT-CONTROL-MENU EXIT THEN
    DUP RTE-CONTROL-MENU-ITEM = IF
        DROP RTAPT-CONTROL-ITEM EXIT
    THEN
    DUP RTE-CONTROL-MENU-SEPARATOR = IF
        DROP RTAPT-CONTROL-SEPARATOR EXIT
    THEN
    DUP RTE-CONTROL-TEXT-AREA = IF
        DROP RTAPT-CONTROL-TEXT-AREA EXIT
    THEN
    RTE-CONTROL-TEXT-GRID = IF
        RTAPT-CONTROL-TEXT-GRID EXIT
    THEN
    0 ;

: _RTAPTE-CONTROL-STATE>RTAPT  ( rte-state -- rtapt-state )
    0 SWAP
    DUP RTE-CONTROL-VISIBLE AND IF
        SWAP RTAPT-CONTROL-F-VISIBLE OR SWAP
    THEN
    DUP RTE-CONTROL-ENABLED AND IF
        SWAP RTAPT-CONTROL-F-ENABLED OR SWAP
    THEN
    DUP RTE-CONTROL-OPEN AND IF
        SWAP RTAPT-CONTROL-F-OPEN OR SWAP
    THEN
    DUP RTE-CONTROL-SELECTED AND IF
        SWAP RTAPT-CONTROL-F-SELECTED OR SWAP
    THEN
    DUP RTE-CONTROL-CHECKED AND IF
        SWAP RTAPT-CONTROL-F-CHECKED OR SWAP
    THEN
    DROP ;

\ Convert one already neutral-validated borrowed record into the provider's
\ scalar call.  No record layout, kind value, or state bit is shared by
\ implication across this boundary.
: _RTAPTE-CONTROL>RTAPT
    ( control engine -- owner generation control kind state z region parent order row col height width root-height root-width label-a label-u shortcut-a shortcut-u content-a content-u content-items content-utf8 engine )
    >R >R
    R@ _RTE-CONTROL.OWNER @
    R@ _RTE-CONTROL.GENERATION @
    R@ _RTE-CONTROL.ID @
    R@ _RTE-CONTROL.KIND @ _RTAPTE-CONTROL-KIND>RTAPT
    R@ _RTE-CONTROL.STATE @ _RTAPTE-CONTROL-STATE>RTAPT
    R@ _RTE-CONTROL.Z @
    R@ _RTE-CONTROL.REGION @
    R@ _RTE-CONTROL.PARENT @
    R@ _RTE-CONTROL.ORDER @
    R@ _RTE-CONTROL.ROW @
    R@ _RTE-CONTROL.COL @
    R@ _RTE-CONTROL.HEIGHT @
    R@ _RTE-CONTROL.WIDTH @
    R@ _RTE-CONTROL.ROOT-HEIGHT @
    R@ _RTE-CONTROL.ROOT-WIDTH @
    R@ _RTE-CONTROL.LABEL-A @
    R@ _RTE-CONTROL.LABEL-U @
    R@ _RTE-CONTROL.SHORTCUT-A @
    R@ _RTE-CONTROL.SHORTCUT-U @
    R@ _RTE-CONTROL.CONTENT-A @
    R@ _RTE-CONTROL.CONTENT-U @
    R@ _RTE-CONTROL.CONTENT-ITEMS @
    R@ _RTE-CONTROL.CONTENT-UTF8 @
    R> DROP R> ;

: _RTAPTE-CONTROL-DEFINE  ( control engine -- status )
    _RTAPTE-CONTROL>RTAPT
    RTAPT-CONTROL-DEFINE _RTAPTE-STATUS>RTE ;

: _RTAPTE-CONTROL-REPLACE  ( control engine -- status )
    _RTAPTE-CONTROL>RTAPT
    RTAPT-CONTROL-REPLACE _RTAPTE-STATUS>RTE ;

: _RTAPTE-CONTROL-DROP
    ( owner generation control engine -- status )
    RTAPT-CONTROL-DROP _RTAPTE-STATUS>RTE ;

: _RTAPTE-RETAINED-SEAL  ( rte-disposition engine -- status )
    SWAP _RTAPTE-DISPOSITION>RTAPT 0= IF
        2DROP RTE-S-INVALID EXIT
    THEN
    SWAP RTAPT-RICH-SEAL _RTAPTE-STATUS>RTE ;

: _RTAPTE-RETAINED-CANCEL  ( engine -- status )
    RTAPT-RICH-CANCEL _RTAPTE-STATUS>RTE ;

: _RTAPTE-OWNER-DROP  ( owner generation engine -- status )
    RTAPT-OWNER-DROP _RTAPTE-STATUS>RTE ;

: _RTAPTE-ZERO?  ( a u -- flag )
    0 ?DO
        DUP I + C@ IF DROP 0 UNLOOP EXIT THEN
    LOOP
    DROP -1 ;

\ The checked hybrid summary crosses a private neutral/provider ABI seam.
\ Size equality alone cannot protect a reordered field, so correlate every
\ accessor before installing the forwarding callback.
: _RTAPTE-HYBRID-LAYOUT?  ( -- flag )
    0 _RTE-HA.OWNER 0 _RTAPT-HA.OWNER =
    0 _RTE-HA.GENERATION 0 _RTAPT-HA.GENERATION = AND
    0 _RTE-HA.SURFACE-COLS 0 _RTAPT-HA.SURFACE-COLS = AND
    0 _RTE-HA.SURFACE-ROWS 0 _RTAPT-HA.SURFACE-ROWS = AND
    0 _RTE-HA.REGION-ID 0 _RTAPT-HA.REGION-ID = AND
    0 _RTE-HA.REGION-X 0 _RTAPT-HA.REGION-X = AND
    0 _RTE-HA.REGION-Y 0 _RTAPT-HA.REGION-Y = AND
    0 _RTE-HA.REGION-COLS 0 _RTAPT-HA.REGION-COLS = AND
    0 _RTE-HA.REGION-ROWS 0 _RTAPT-HA.REGION-ROWS = AND
    0 _RTE-HA.REGION-Z 0 _RTAPT-HA.REGION-Z = AND
    0 _RTE-HA.REGION-FLAGS 0 _RTAPT-HA.REGION-FLAGS = AND
    0 _RTE-HA.CONTROL-COUNT 0 _RTAPT-HA.CONTROL-COUNT = AND
    0 _RTE-HA.CONTROL-BYTES 0 _RTAPT-HA.CONTROL-BYTES = AND
    0 _RTE-HA.CONTROL-ALIGNED 0 _RTAPT-HA.CONTROL-ALIGNED = AND
    0 _RTE-HA.CONTROL-MAX 0 _RTAPT-HA.CONTROL-MAX = AND
    0 _RTE-HA.CONTROL-LAST 0 _RTAPT-HA.CONTROL-LAST = AND
    0 _RTE-HA.CONTROL-COLLECTIONS
        0 _RTAPT-HA.CONTROL-COLLECTIONS = AND
    0 _RTE-HA.CONTROL-ITEMS 0 _RTAPT-HA.CONTROL-ITEMS = AND
    0 _RTE-HA.CONTROL-UTF8 0 _RTAPT-HA.CONTROL-UTF8 = AND
    0 _RTE-HA.GLYPH-COUNT 0 _RTAPT-HA.GLYPH-COUNT = AND
    0 _RTE-HA.GLYPH-TEXT 0 _RTAPT-HA.GLYPH-TEXT = AND
    0 _RTE-HA.GLYPH-ALIGNED 0 _RTAPT-HA.GLYPH-ALIGNED = AND
    0 _RTE-HA.GLYPH-MAX 0 _RTAPT-HA.GLYPH-MAX = AND
    0 _RTE-HA.GLYPH-LAST 0 _RTAPT-HA.GLYPH-LAST = AND
    0 _RTE-HA.RESERVED 0 _RTAPT-HA.RESERVED = AND ;

: _RTAPTE-FACADE?  ( facade -- flag )
    DUP RTE-VALID? 0= IF DROP 0 EXIT THEN
    DUP _RTE-F.CONTEXT @ RTAPT-VALID? 0= IF DROP 0 EXIT THEN
    DUP _RTE-F.DISJOINT-XT @ ['] _RTAPTE-DISJOINT? =
    OVER _RTE-F.STATUS-XT @ ['] _RTAPTE-STATUS@ = AND
    OVER _RTE-F.OWNER-OPEN-XT @ ['] _RTAPTE-OWNER-OPEN = AND
    OVER _RTE-F.OWNER-STATE-XT @ ['] _RTAPTE-OWNER-STATE@ = AND
    OVER _RTE-F.RETAINED-BEGIN-XT @ ['] _RTAPTE-RETAINED-BEGIN = AND
    OVER _RTE-F.REGION-DEF-XT @ ['] _RTAPTE-REGION-DEFINE = AND
    OVER _RTE-F.RETAINED-SEAL-XT @ ['] _RTAPTE-RETAINED-SEAL = AND
    OVER _RTE-F.RETAINED-CANCEL-XT @ ['] _RTAPTE-RETAINED-CANCEL = AND
    OVER _RTE-F.OWNER-DROP-XT @ ['] _RTAPTE-OWNER-DROP = AND
    OVER _RTE-F.LIMITS-XT @ ['] _RTAPTE-LIMITS@ = AND
    OVER _RTE-F.GLYPH-RUN-DEF-XT @ ['] _RTAPTE-GLYPH-RUN-DEFINE = AND
    OVER _RTE-F.GLYPH-RUN-PREFLIGHT-XT @ ['] _RTAPTE-GLYPH-RUN-PREFLIGHT = AND
    OVER _RTE-F.UPDATE-STATE-XT @ ['] _RTAPTE-UPDATE-STATE@ = AND
    OVER _RTE-F.GLYPH-RUN-REPLACE-XT @ ['] _RTAPTE-GLYPH-RUN-REPLACE = AND
    OVER _RTE-F.CONTROL-PREFLIGHT-XT @
        ['] _RTAPTE-CONTROL-PREFLIGHT = AND
    OVER _RTE-F.CONTROL-DEF-XT @ ['] _RTAPTE-CONTROL-DEFINE = AND
    OVER _RTE-F.CONTROL-REPLACE-XT @ ['] _RTAPTE-CONTROL-REPLACE = AND
    OVER _RTE-F.CONTROL-DROP-XT @ ['] _RTAPTE-CONTROL-DROP = AND
    OVER _RTE-F.HYBRID-PREFLIGHT-XT @
        ['] _RTAPTE-HYBRID-PREFLIGHT = AND
    NIP ;

VARIABLE _RTAPTE-I-ENGINE
VARIABLE _RTAPTE-I-FACADE

: _RTAPTE-SCRUB-BORROWED  ( -- )
    0 _RTAPTE-I-ENGINE !
    0 _RTAPTE-I-FACADE ! ;

: _RTAPTE-INIT-BODY  ( engine facade -- status )
    _RTAPTE-I-FACADE ! _RTAPTE-I-ENGINE !
    RTE-GLYPH-RUN-PLAN-SIZE RTAPT-GLYPH-RUN-PLAN-SIZE <>
    RTE-GLYPH-RUN-PLAN-ITEM-SIZE RTAPT-GLYPH-RUN-PLAN-ITEM-SIZE <> OR
    RTE-HYBRID-ADMISSION-SIZE RTAPT-HYBRID-ADMISSION-SIZE <> OR
    _RTAPTE-HYBRID-LAYOUT? 0= OR IF
        RTE-S-INVALID EXIT
    THEN
    _RTAPTE-I-FACADE @ RTE-FACADE-SIZE _RTE-SPAN? 0= IF
        RTE-S-INVALID EXIT
    THEN
    _RTAPTE-I-ENGINE @ RTAPT-VALID? 0= IF RTE-S-INVALID EXIT THEN
    _RTAPTE-I-FACADE @ RTE-FACADE-SIZE _RTAPTE-I-ENGINE @
        RTAPT-STORAGE-DISJOINT? 0= IF RTE-S-INVALID EXIT THEN
    _RTAPTE-I-FACADE @ _RTE-F.MAGIC @ _RTE-MAGIC = IF
        RTE-S-WOULD-BLOCK EXIT
    THEN

    _RTAPTE-I-FACADE @ RTE-FACADE-SIZE 0 FILL
    0 _RTAPTE-I-FACADE @ _RTE-F.RESERVED !
    RTE-FACADE-SIZE _RTAPTE-I-FACADE @ _RTE-F.SIZE !
    _RTAPTE-I-FACADE @ DUP _RTE-F.SELF !
    _RTAPTE-I-ENGINE @ _RTAPTE-I-FACADE @ _RTE-F.CONTEXT !
    ['] _RTAPTE-DISJOINT? _RTAPTE-I-FACADE @ _RTE-F.DISJOINT-XT !
    ['] _RTAPTE-STATUS@ _RTAPTE-I-FACADE @ _RTE-F.STATUS-XT !
    ['] _RTAPTE-OWNER-OPEN _RTAPTE-I-FACADE @ _RTE-F.OWNER-OPEN-XT !
    ['] _RTAPTE-OWNER-STATE@ _RTAPTE-I-FACADE @ _RTE-F.OWNER-STATE-XT !
    ['] _RTAPTE-RETAINED-BEGIN
        _RTAPTE-I-FACADE @ _RTE-F.RETAINED-BEGIN-XT !
    ['] _RTAPTE-REGION-DEFINE _RTAPTE-I-FACADE @ _RTE-F.REGION-DEF-XT !
    ['] _RTAPTE-RETAINED-SEAL
        _RTAPTE-I-FACADE @ _RTE-F.RETAINED-SEAL-XT !
    ['] _RTAPTE-RETAINED-CANCEL
        _RTAPTE-I-FACADE @ _RTE-F.RETAINED-CANCEL-XT !
    ['] _RTAPTE-OWNER-DROP _RTAPTE-I-FACADE @ _RTE-F.OWNER-DROP-XT !
    ['] _RTAPTE-LIMITS@ _RTAPTE-I-FACADE @ _RTE-F.LIMITS-XT !
    ['] _RTAPTE-GLYPH-RUN-DEFINE _RTAPTE-I-FACADE @ _RTE-F.GLYPH-RUN-DEF-XT !
    ['] _RTAPTE-GLYPH-RUN-PREFLIGHT
        _RTAPTE-I-FACADE @ _RTE-F.GLYPH-RUN-PREFLIGHT-XT !
    ['] _RTAPTE-UPDATE-STATE@
        _RTAPTE-I-FACADE @ _RTE-F.UPDATE-STATE-XT !
    ['] _RTAPTE-GLYPH-RUN-REPLACE
        _RTAPTE-I-FACADE @ _RTE-F.GLYPH-RUN-REPLACE-XT !
    ['] _RTAPTE-CONTROL-PREFLIGHT
        _RTAPTE-I-FACADE @ _RTE-F.CONTROL-PREFLIGHT-XT !
    ['] _RTAPTE-CONTROL-DEFINE
        _RTAPTE-I-FACADE @ _RTE-F.CONTROL-DEF-XT !
    ['] _RTAPTE-CONTROL-REPLACE
        _RTAPTE-I-FACADE @ _RTE-F.CONTROL-REPLACE-XT !
    ['] _RTAPTE-CONTROL-DROP
        _RTAPTE-I-FACADE @ _RTE-F.CONTROL-DROP-XT !
    ['] _RTAPTE-HYBRID-PREFLIGHT
        _RTAPTE-I-FACADE @ _RTE-F.HYBRID-PREFLIGHT-XT !
    _RTE-MAGIC _RTAPTE-I-FACADE @ _RTE-F.MAGIC !
    RTE-S-OK ;

: _RTAPTE-FINI-BODY  ( facade -- status )
    DUP RTE-FACADE-SIZE _RTE-SPAN? 0= IF DROP RTE-S-INVALID EXIT THEN
    DUP RTE-FACADE-SIZE _RTAPTE-ZERO? IF DROP RTE-S-OK EXIT THEN
    DUP _RTAPTE-FACADE? 0= IF DROP RTE-S-INVALID EXIT THEN
    DUP RTE-FACADE-SIZE OVER _RTE-F.CONTEXT @
        RTAPT-STORAGE-DISJOINT? 0= IF DROP RTE-S-INVALID EXIT THEN
    RTE-FACADE-SIZE 0 FILL
    RTE-S-OK ;

: _RTAPTE-P-DO-INIT  ( -- status )
    _RTAPTE-I-ENGINE @ _RTAPTE-I-FACADE @ _RTAPTE-INIT-BODY ;

: RTAPTE-INIT  ( engine facade -- status )
    _RTAPTE-I-FACADE ! _RTAPTE-I-ENGINE !
    ['] _RTAPTE-P-DO-INIT CATCH ?DUP IF DROP RTE-S-INVALID THEN
    _RTAPTE-SCRUB-BORROWED ;

: _RTAPTE-P-DO-FINI  ( -- status )
    _RTAPTE-I-FACADE @ _RTAPTE-FINI-BODY ;

: RTAPTE-FINI  ( facade -- status )
    _RTAPTE-I-FACADE !
    ['] _RTAPTE-P-DO-FINI CATCH ?DUP IF DROP RTE-S-INVALID THEN
    _RTAPTE-SCRUB-BORROWED ;
