\ =====================================================================
\  hybrid-screen-producer.f -- first complete semantic screen producer
\ =====================================================================
\
\  This is the narrow production replacement for the temporary per-cell
\  screen plane.  It copies one completed focused UIDL snapshot, plans its
\  semantic controls, excludes their claimed cells from one coalesced glyph
\  projection of the ordinary screen, admits the combined candidate once,
\  and carries that immutable candidate through hidden START and physical
\  reveal acknowledgement.
\
\  The caller supplies one bounded arena and the real lifecycle endpoints.
\  This first vertical slice deliberately has no delta/update path: after the
\  first acknowledged frame it remains LIVE until composition teardown.
\
\  Prefix: RTHP- (public), _RTHP- (private)

PROVIDED akashic-tui-rterm-hybrid-screen-producer

REQUIRE uidl-hybrid-adapter.f
REQUIRE uidl-control-planner.f
REQUIRE uidl-claim-ledger.f
REQUIRE residual-glyph-planner.f
REQUIRE engine.f
REQUIRE ../screen.f
REQUIRE ../../utils/memory-span.f

0x3150444952425948 CONSTANT _RTHP-MAGIC  \ "HYBRIDP1"

: _RTHP.MAGIC          ( p -- a )        ;
: _RTHP.SIZE           ( p -- a )    8 + ;
: _RTHP.SELF           ( p -- a )   16 + ;
: _RTHP.ADAPTER        ( p -- a )   24 + ;
: _RTHP.FACADE         ( p -- a )   32 + ;
: _RTHP.ARENA-A        ( p -- a )   40 + ;
: _RTHP.ARENA-U        ( p -- a )   48 + ;
: _RTHP.MAX-RECORDS    ( p -- a )   56 + ;
: _RTHP.MAX-TEXT       ( p -- a )   64 + ;
: _RTHP.MAX-COLS       ( p -- a )   72 + ;
: _RTHP.MAX-ROWS       ( p -- a )   80 + ;
: _RTHP.OWNER          ( p -- a )   88 + ;
: _RTHP.OWNER-GEN      ( p -- a )   96 + ;
: _RTHP.REGION         ( p -- a )  104 + ;
: _RTHP.FIRST-OBJECT   ( p -- a )  112 + ;
: _RTHP.PHASE          ( p -- a )  120 + ;
: _RTHP.FAULT          ( p -- a )  128 + ;
: _RTHP.COLS           ( p -- a )  136 + ;
: _RTHP.ROWS           ( p -- a )  144 + ;
: _RTHP.SURFACE-GEN    ( p -- a )  152 + ;
: _RTHP.ATTEMPT        ( p -- a )  160 + ;
: _RTHP.SOURCE-GEN     ( p -- a )  168 + ;
: _RTHP.TOKEN          ( p -- a )  176 + ;
: _RTHP.SOURCE-RECS-A  ( p -- a )  184 + ;
: _RTHP.SOURCE-RECS-U  ( p -- a )  192 + ;
: _RTHP.SOURCE-USED    ( p -- a )  200 + ;
: _RTHP.SOURCE-TEXT-A  ( p -- a )  208 + ;
: _RTHP.SOURCE-TEXT-U  ( p -- a )  216 + ;
: _RTHP.SOURCE-TEXT-USED ( p -- a ) 224 + ;
: _RTHP.LOOKUP-A       ( p -- a )  232 + ;
: _RTHP.LOOKUP-U       ( p -- a )  240 + ;
: _RTHP.ORDER-A        ( p -- a )  248 + ;
: _RTHP.ORDER-U        ( p -- a )  256 + ;
: _RTHP.ORDER2-A       ( p -- a )  264 + ;
: _RTHP.ORDER2-U       ( p -- a )  272 + ;
: _RTHP.CONTROLS-A     ( p -- a )  280 + ;
: _RTHP.CONTROLS-U     ( p -- a )  288 + ;
: _RTHP.CORR-A         ( p -- a )  296 + ;
: _RTHP.CORR-U         ( p -- a )  304 + ;
: _RTHP.CLAIMS-A       ( p -- a )  312 + ;
: _RTHP.CLAIMS-U       ( p -- a )  320 + ;
: _RTHP.CLAIMS-USED    ( p -- a )  328 + ;
: _RTHP.HEADS-A        ( p -- a )  336 + ;
: _RTHP.HEADS-U        ( p -- a )  344 + ;
: _RTHP.EVENTS-A       ( p -- a )  352 + ;
: _RTHP.EVENTS-U       ( p -- a )  360 + ;
: _RTHP.DIFF-A         ( p -- a )  368 + ;
: _RTHP.DIFF-U         ( p -- a )  376 + ;
: _RTHP.GLYPH-ITEMS-A  ( p -- a )  384 + ;
: _RTHP.GLYPH-ITEMS-U  ( p -- a )  392 + ;
: _RTHP.GLYPH-REFS-A   ( p -- a )  400 + ;
: _RTHP.GLYPH-REFS-U   ( p -- a )  408 + ;
: _RTHP.GLYPH-TEXT-A   ( p -- a )  416 + ;
: _RTHP.GLYPH-TEXT-U   ( p -- a )  424 + ;
: _RTHP.GLYPH-TEXT-USED ( p -- a ) 432 + ;
: _RTHP.CONTROL-COUNT  ( p -- a )  440 + ;
: _RTHP.GLYPH-COUNT    ( p -- a )  448 + ;
: _RTHP.PHYSICAL-GEN   ( p -- a )  456 + ;
: _RTHP.LIMITS         ( p -- a )  464 + ;
: _RTHP.RUCP-Q         ( p -- a )  632 + ;
: _RTHP.RUCL-Q         ( p -- a )  880 + ;
: _RTHP.RGRP-Q         ( p -- a )  992 + ;
: _RTHP.CONTROL-PLAN   ( p -- a ) 1240 + ;
: _RTHP.GLYPH-PLAN     ( p -- a ) 1352 + ;
: _RTHP.HYBRID         ( p -- a ) 1464 + ;
: _RTHP.ADMISSION      ( p -- a ) 1560 + ;
: _RTHP.RUN            ( p -- a ) 1736 + ;
: _RTHP.TARGET0-A      ( p -- a ) 1888 + ;
: _RTHP.TARGET1-A      ( p -- a ) 1896 + ;
: _RTHP.TARGET-ACTIVE  ( p -- a ) 1904 + ;
: _RTHP.TARGET-PENDING ( p -- a ) 1912 + ;
: _RTHP.NEXT-REGION    ( p -- a ) 1920 + ;
: _RTHP.NEXT-OBJECT    ( p -- a ) 1928 + ;

1936 CONSTANT RTHP-SIZE

: RTHP-BYTES  ( -- bytes )  RTHP-SIZE ;

0 CONSTANT _RTHP-PH-WAIT
1 CONSTANT _RTHP-PH-OPENING
2 CONSTANT _RTHP-PH-READY-START
3 CONSTANT _RTHP-PH-START-SEALED
4 CONSTANT _RTHP-PH-READY-REVEAL
5 CONSTANT _RTHP-PH-REVEAL-SEALED
6 CONSTANT _RTHP-PH-LIVE
7 CONSTANT _RTHP-PH-DISABLED
8 CONSTANT _RTHP-PH-FAULT

: _RTHP-TB.OWNER       ( bank -- a )      ;
: _RTHP-TB.GENERATION  ( bank -- a )  8 + ;
: _RTHP-TB.COLS        ( bank -- a ) 16 + ;
: _RTHP-TB.ROWS        ( bank -- a ) 24 + ;
: _RTHP-TB.COUNT       ( bank -- a ) 32 + ;

40 CONSTANT _RTHP-TARGET-BANK-HEADER-SIZE

: _RTHP-TE.ID          ( entry -- a )      ;
: _RTHP-TE.ROW         ( entry -- a )  8 + ;
: _RTHP-TE.COL         ( entry -- a ) 16 + ;

24 CONSTANT _RTHP-TARGET-ENTRY-SIZE

: _RTHP-TARGET-ENTRY  ( index bank -- entry )
    SWAP _RTHP-TARGET-ENTRY-SIZE *
    _RTHP-TARGET-BANK-HEADER-SIZE + + ;

\ =====================================================================
\  Checked arena sizing
\ =====================================================================

: _RTHP-U32+?  ( a b -- sum flag )
    OVER + DUP ROT U< 0= OVER 0xFFFFFFFF U> 0= AND ;

: _RTHP-U32*?  ( a b -- product flag )
    UM* DUP IF 2DROP 0 0 EXIT THEN DROP
    DUP 0xFFFFFFFF U> 0= ;

: _RTHP-U+?  ( a b -- sum flag )
    OVER + DUP ROT U< 0= ;

: _RTHP-UMIN  ( a b -- min )
    2DUP U< IF DROP ELSE NIP THEN ;

: _RTHP-ALIGN8?  ( u -- aligned flag )
    7 _RTHP-U32+? 0= IF DROP 0 0 EXIT THEN
    7 INVERT AND -1 ;

: _RTHP-POS-U32?  ( u -- flag )
    DUP 0> SWAP 0xFFFFFFFF U> 0= AND ;

VARIABLE _RTHP-B-RECORDS
VARIABLE _RTHP-B-TEXT
VARIABLE _RTHP-B-COLS
VARIABLE _RTHP-B-ROWS
VARIABLE _RTHP-B-CELLS
VARIABLE _RTHP-B-TOTAL

: _RTHP-B-ADD  ( u -- flag )
    _RTHP-B-TOTAL @ SWAP _RTHP-U32+? 0= IF DROP 0 EXIT THEN
    _RTHP-B-TOTAL ! -1 ;

: _RTHP-B-MUL-ADD  ( count item-bytes -- flag )
    _RTHP-U32*? 0= IF DROP 0 EXIT THEN _RTHP-B-ADD ;

: _RTHP-BYTES-BODY  ( -- bytes|0 )
    _RTHP-B-RECORDS @ _RTHP-POS-U32? 0= IF 0 EXIT THEN
    _RTHP-B-TEXT @ _RTHP-POS-U32? 0= IF 0 EXIT THEN
    _RTHP-B-COLS @ _RTHP-POS-U32? 0= IF 0 EXIT THEN
    _RTHP-B-ROWS @ _RTHP-POS-U32? 0= IF 0 EXIT THEN
    _RTHP-B-COLS @ _RTHP-B-ROWS @ _RTHP-U32*?
        0= IF DROP 0 EXIT THEN DUP 0= IF DROP 0 EXIT THEN
        _RTHP-B-CELLS !
    0 _RTHP-B-TOTAL !
    _RTHP-B-RECORDS @ UMSN-RECORD-SIZE _RTHP-B-MUL-ADD
        0= IF 0 EXIT THEN
    _RTHP-B-TEXT @ _RTHP-ALIGN8? 0= IF DROP 0 EXIT THEN
        _RTHP-B-ADD 0= IF 0 EXIT THEN
    _RTHP-B-RECORDS @ RUCP-LOOKUP-ENTRY-SIZE _RTHP-B-MUL-ADD
        0= IF 0 EXIT THEN
    _RTHP-B-RECORDS @ 8 _RTHP-B-MUL-ADD 0= IF 0 EXIT THEN
    _RTHP-B-RECORDS @ 8 _RTHP-B-MUL-ADD 0= IF 0 EXIT THEN
    _RTHP-B-RECORDS @ RTE-CONTROL-SIZE _RTHP-B-MUL-ADD
        0= IF 0 EXIT THEN
    _RTHP-B-RECORDS @ RUCP-CORRELATION-SIZE _RTHP-B-MUL-ADD
        0= IF 0 EXIT THEN
    _RTHP-B-RECORDS @ RUCL-CLAIM-SIZE _RTHP-B-MUL-ADD
        0= IF 0 EXIT THEN
    _RTHP-B-ROWS @ 1 _RTHP-U32+? 0= IF DROP 0 EXIT THEN
        RGRP-ROW-HEAD-SIZE _RTHP-B-MUL-ADD 0= IF 0 EXIT THEN
    _RTHP-B-RECORDS @ 2 _RTHP-U32*? 0= IF DROP 0 EXIT THEN
        RGRP-EVENT-SIZE _RTHP-B-MUL-ADD 0= IF 0 EXIT THEN
    _RTHP-B-COLS @ 1 _RTHP-U32+? 0= IF DROP 0 EXIT THEN
        RGRP-DIFFERENCE-SIZE _RTHP-B-MUL-ADD 0= IF 0 EXIT THEN
    _RTHP-B-CELLS @ RTE-GLYPH-RUN-PLAN-ITEM-SIZE _RTHP-B-MUL-ADD
        0= IF 0 EXIT THEN
    _RTHP-B-CELLS @ RGRP-TEXT-REF-SIZE _RTHP-B-MUL-ADD
        0= IF 0 EXIT THEN
    _RTHP-B-CELLS @ 4 _RTHP-U32*? 0= IF DROP 0 EXIT THEN
        _RTHP-ALIGN8? 0= IF DROP 0 EXIT THEN
        _RTHP-B-ADD 0= IF 0 EXIT THEN
    _RTHP-TARGET-BANK-HEADER-SIZE _RTHP-B-ADD 0= IF 0 EXIT THEN
    _RTHP-B-RECORDS @ _RTHP-TARGET-ENTRY-SIZE _RTHP-B-MUL-ADD
        0= IF 0 EXIT THEN
    _RTHP-TARGET-BANK-HEADER-SIZE _RTHP-B-ADD 0= IF 0 EXIT THEN
    _RTHP-B-RECORDS @ _RTHP-TARGET-ENTRY-SIZE _RTHP-B-MUL-ADD
        0= IF 0 EXIT THEN
    _RTHP-B-TOTAL @ ;

: RTHP-STORAGE-BYTES  ( max-records max-source-text max-cols max-rows -- bytes|0 )
    _RTHP-B-ROWS ! _RTHP-B-COLS ! _RTHP-B-TEXT ! _RTHP-B-RECORDS !
    _RTHP-BYTES-BODY
    0 _RTHP-B-RECORDS ! 0 _RTHP-B-TEXT !
    0 _RTHP-B-COLS ! 0 _RTHP-B-ROWS !
    0 _RTHP-B-CELLS ! 0 _RTHP-B-TOTAL ! ;

\ =====================================================================
\  Construction and deterministic arena layout
\ =====================================================================

VARIABLE _RTHP-I-ADAPTER
VARIABLE _RTHP-I-FACADE
VARIABLE _RTHP-I-ARENA
VARIABLE _RTHP-I-ARENA-U
VARIABLE _RTHP-I-RECORDS
VARIABLE _RTHP-I-TEXT
VARIABLE _RTHP-I-COLS
VARIABLE _RTHP-I-ROWS
VARIABLE _RTHP-I-OWNER
VARIABLE _RTHP-I-GEN
VARIABLE _RTHP-I-REGION
VARIABLE _RTHP-I-FIRST
VARIABLE _RTHP-I-P
VARIABLE _RTHP-I-REQUIRED
VARIABLE _RTHP-L-CURSOR
VARIABLE _RTHP-L-BYTES

: _RTHP-L-TAKE  ( bytes -- a )
    _RTHP-L-BYTES !
    _RTHP-L-CURSOR @
    _RTHP-L-BYTES @ _RTHP-L-CURSOR +! ;

: _RTHP-LAYOUT  ( producer -- )
    DUP _RTHP.ARENA-A @ _RTHP-L-CURSOR !
    DUP _RTHP.MAX-RECORDS @ UMSN-RECORD-SIZE *
        DUP 2 PICK _RTHP.SOURCE-RECS-U !
        _RTHP-L-TAKE OVER _RTHP.SOURCE-RECS-A !
    DUP _RTHP.MAX-TEXT @
        DUP 2 PICK _RTHP.SOURCE-TEXT-U !
        _RTHP-ALIGN8? DROP _RTHP-L-TAKE
        OVER _RTHP.SOURCE-TEXT-A !
    DUP _RTHP.MAX-RECORDS @ RUCP-LOOKUP-ENTRY-SIZE *
        DUP 2 PICK _RTHP.LOOKUP-U ! _RTHP-L-TAKE
        OVER _RTHP.LOOKUP-A !
    DUP _RTHP.MAX-RECORDS @ 8 *
        DUP 2 PICK _RTHP.ORDER-U ! _RTHP-L-TAKE
        OVER _RTHP.ORDER-A !
    DUP _RTHP.MAX-RECORDS @ 8 *
        DUP 2 PICK _RTHP.ORDER2-U ! _RTHP-L-TAKE
        OVER _RTHP.ORDER2-A !
    DUP _RTHP.MAX-RECORDS @ RTE-CONTROL-SIZE *
        DUP 2 PICK _RTHP.CONTROLS-U ! _RTHP-L-TAKE
        OVER _RTHP.CONTROLS-A !
    DUP _RTHP.MAX-RECORDS @ RUCP-CORRELATION-SIZE *
        DUP 2 PICK _RTHP.CORR-U ! _RTHP-L-TAKE
        OVER _RTHP.CORR-A !
    DUP _RTHP.MAX-RECORDS @ RUCL-CLAIM-SIZE *
        DUP 2 PICK _RTHP.CLAIMS-U ! _RTHP-L-TAKE
        OVER _RTHP.CLAIMS-A !
    DUP _RTHP.MAX-ROWS @ 1+ RGRP-ROW-HEAD-SIZE *
        DUP 2 PICK _RTHP.HEADS-U ! _RTHP-L-TAKE
        OVER _RTHP.HEADS-A !
    DUP _RTHP.MAX-RECORDS @ 2 * RGRP-EVENT-SIZE *
        DUP 2 PICK _RTHP.EVENTS-U ! _RTHP-L-TAKE
        OVER _RTHP.EVENTS-A !
    DUP _RTHP.MAX-COLS @ 1+ RGRP-DIFFERENCE-SIZE *
        DUP 2 PICK _RTHP.DIFF-U ! _RTHP-L-TAKE
        OVER _RTHP.DIFF-A !
    DUP _RTHP.MAX-COLS @ OVER _RTHP.MAX-ROWS @ *
        RTE-GLYPH-RUN-PLAN-ITEM-SIZE *
        DUP 2 PICK _RTHP.GLYPH-ITEMS-U ! _RTHP-L-TAKE
        OVER _RTHP.GLYPH-ITEMS-A !
    DUP _RTHP.MAX-COLS @ OVER _RTHP.MAX-ROWS @ *
        RGRP-TEXT-REF-SIZE *
        DUP 2 PICK _RTHP.GLYPH-REFS-U ! _RTHP-L-TAKE
        OVER _RTHP.GLYPH-REFS-A !
    DUP _RTHP.MAX-COLS @ OVER _RTHP.MAX-ROWS @ * 4 *
        DUP 2 PICK _RTHP.GLYPH-TEXT-U !
        _RTHP-ALIGN8? DROP _RTHP-L-TAKE
        OVER _RTHP.GLYPH-TEXT-A !
    DUP _RTHP.MAX-RECORDS @ _RTHP-TARGET-ENTRY-SIZE *
        _RTHP-TARGET-BANK-HEADER-SIZE +
        _RTHP-L-TAKE OVER _RTHP.TARGET0-A !
    DUP _RTHP.MAX-RECORDS @ _RTHP-TARGET-ENTRY-SIZE *
        _RTHP-TARGET-BANK-HEADER-SIZE +
        _RTHP-L-TAKE OVER _RTHP.TARGET1-A !
    DROP 0 _RTHP-L-CURSOR ! 0 _RTHP-L-BYTES ! ;

VARIABLE _RTHP-V-P

: _RTHP-VALID-BODY?  ( -- flag )
    _RTHP-V-P @ DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP RTHP-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP _RTHP.MAGIC @ _RTHP-MAGIC <> IF DROP 0 EXIT THEN
    DUP _RTHP.SIZE @ RTHP-SIZE <> IF DROP 0 EXIT THEN
    DUP _RTHP.SELF @ OVER <> IF DROP 0 EXIT THEN
    DUP _RTHP.PHASE @ _RTHP-PH-FAULT U> IF DROP 0 EXIT THEN
    DUP _RTHP.FAULT @ 4 U< 0= IF DROP 0 EXIT THEN
    DUP _RTHP.ADAPTER @ RUHA-VALID? 0= IF DROP 0 EXIT THEN
    DUP _RTHP.FACADE @ RTE-VALID? 0= IF DROP 0 EXIT THEN
    DUP _RTHP.ARENA-A @ OVER _RTHP.ARENA-U @
        MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DROP -1 ;

: RTHP-VALID?  ( producer -- flag )
    _RTHP-V-P ! _RTHP-VALID-BODY? 0 _RTHP-V-P ! ;

: RTHP-LIVE?  ( producer -- flag )
    DUP RTHP-VALID? 0= IF DROP 0 EXIT THEN
    _RTHP.TARGET-ACTIVE @ 0<> ;

\ =====================================================================
\  Revision-bound native menu input targets
\ =====================================================================
\
\  CONTROL descendants intentionally carry no wire geometry: the renderer
\  lays them out from their semantic parent/order graph.  While a candidate is
\  sealed, its exact control/correlation/source relationship is reduced to a
\  compact point target in the inactive caller-bounded bank.  Only the bank
\  belonging to the exactly acknowledged reveal is published.  Its selector
\  remains untouched while a later replacement uses the other bank.

VARIABLE _RTHP-CT-P
VARIABLE _RTHP-CT-OWNER
VARIABLE _RTHP-CT-GENERATION
VARIABLE _RTHP-CT-ID
VARIABLE _RTHP-CT-CONTROL
VARIABLE _RTHP-CT-CORRELATION
VARIABLE _RTHP-CT-RECORD
VARIABLE _RTHP-CT-ORDINAL
VARIABLE _RTHP-CT-RESOLVED
VARIABLE _RTHP-CT-ROW
VARIABLE _RTHP-CT-COL
VARIABLE _RTHP-CT-H
VARIABLE _RTHP-CT-W
VARIABLE _RTHP-CT-END
VARIABLE _RTHP-CT-BYTES

: _RTHP-CT-CLEAR  ( -- )
    0 _RTHP-CT-P ! 0 _RTHP-CT-OWNER ! 0 _RTHP-CT-GENERATION !
    0 _RTHP-CT-ID ! 0 _RTHP-CT-CONTROL ! 0 _RTHP-CT-CORRELATION !
    0 _RTHP-CT-RECORD ! 0 _RTHP-CT-ORDINAL !
    0 _RTHP-CT-RESOLVED ! 0 _RTHP-CT-ROW ! 0 _RTHP-CT-COL !
    0 _RTHP-CT-H ! 0 _RTHP-CT-W ! 0 _RTHP-CT-END !
    0 _RTHP-CT-BYTES ! ;

VARIABLE _RTHP-AS-A
VARIABLE _RTHP-AS-U
VARIABLE _RTHP-AS-P

: _RTHP-ARENA-SPAN?  ( address bytes producer -- flag )
    _RTHP-AS-P ! _RTHP-AS-U ! _RTHP-AS-A !
    _RTHP-AS-A @ _RTHP-AS-U @ MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _RTHP-AS-P @ _RTHP.ARENA-A @
    _RTHP-AS-P @ _RTHP.ARENA-U @ MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _RTHP-AS-A @ _RTHP-AS-P @ _RTHP.ARENA-A @ U< IF 0 EXIT THEN
    _RTHP-AS-A @ _RTHP-AS-U @ +
    _RTHP-AS-P @ _RTHP.ARENA-A @
        _RTHP-AS-P @ _RTHP.ARENA-U @ + U> 0= ;

: _RTHP-TARGET-BANK-BYTES?  ( capacity -- bytes flag )
    _RTHP-TARGET-ENTRY-SIZE _RTHP-U32*? 0= IF DROP 0 0 EXIT THEN
    _RTHP-TARGET-BANK-HEADER-SIZE _RTHP-U32+? ;

\ Final target extraction may run long after the copied candidate was planned.
\ Re-prove every source bank before the canonical traversal so caller-owned
\ storage cannot redirect that traversal outside the producer arena.
: _RTHP-CT-CANDIDATE-SHAPE?  ( -- flag )
    _RTHP-CT-P @ _RTHP.FAULT @ SCB-S-OK <> IF 0 EXIT THEN
    _RTHP-CT-P @ _RTHP.TOKEN @ 0=
    _RTHP-CT-P @ _RTHP.SOURCE-GEN @ 0= OR
    _RTHP-CT-P @ _RTHP.FIRST-OBJECT @ 0= OR IF 0 EXIT THEN
    _RTHP-CT-P @ _RTHP.COLS @ DUP 0> SWAP
        _RTHP-CT-P @ _RTHP.MAX-COLS @ U> 0= AND 0= IF 0 EXIT THEN
    _RTHP-CT-P @ _RTHP.ROWS @ DUP 0> SWAP
        _RTHP-CT-P @ _RTHP.MAX-ROWS @ U> 0= AND 0= IF 0 EXIT THEN
    _RTHP-CT-P @ _RTHP.CONTROL-COUNT @ DUP 0> SWAP
        _RTHP-CT-P @ _RTHP.MAX-RECORDS @ U> 0= AND 0= IF 0 EXIT THEN

    _RTHP-CT-P @ _RTHP.CONTROL-COUNT @ UMSN-RECORD-SIZE
        _RTHP-U32*? 0= IF DROP 0 EXIT THEN _RTHP-CT-BYTES !
    _RTHP-CT-BYTES @ _RTHP-CT-P @ _RTHP.SOURCE-USED @ <> IF 0 EXIT THEN
    _RTHP-CT-BYTES @ _RTHP-CT-P @ _RTHP.SOURCE-RECS-U @ U> IF 0 EXIT THEN
    _RTHP-CT-P @ _RTHP.SOURCE-RECS-A @ DUP 7 AND IF DROP 0 EXIT THEN
    _RTHP-CT-BYTES @ _RTHP-CT-P @ _RTHP-ARENA-SPAN? 0= IF 0 EXIT THEN

    _RTHP-CT-P @ _RTHP.CONTROL-COUNT @ RTE-CONTROL-SIZE
        _RTHP-U32*? 0= IF DROP 0 EXIT THEN _RTHP-CT-BYTES !
    _RTHP-CT-BYTES @ _RTHP-CT-P @ _RTHP.CONTROLS-U @ U> IF 0 EXIT THEN
    _RTHP-CT-P @ _RTHP.CONTROLS-A @ DUP 7 AND IF DROP 0 EXIT THEN
    _RTHP-CT-BYTES @ _RTHP-CT-P @ _RTHP-ARENA-SPAN? 0= IF 0 EXIT THEN

    _RTHP-CT-P @ _RTHP.CONTROL-COUNT @ RUCP-CORRELATION-SIZE
        _RTHP-U32*? 0= IF DROP 0 EXIT THEN _RTHP-CT-BYTES !
    _RTHP-CT-BYTES @ _RTHP-CT-P @ _RTHP.CORR-U @ U> IF 0 EXIT THEN
    _RTHP-CT-P @ _RTHP.CORR-A @ DUP 7 AND IF DROP 0 EXIT THEN
    _RTHP-CT-BYTES @ _RTHP-CT-P @ _RTHP-ARENA-SPAN? ;

: _RTHP-CT-TARGET?  ( control -- flag )
    DUP _RTE-CONTROL.KIND @ DUP RTE-CONTROL-MENU =
        SWAP RTE-CONTROL-MENU-ITEM = OR
    SWAP _RTE-CONTROL.STATE @
        RTE-CONTROL-VISIBLE RTE-CONTROL-ENABLED OR AND
        RTE-CONTROL-VISIBLE RTE-CONTROL-ENABLED OR = AND ;

: _RTHP-CT-FIND-CONTROL?  ( -- flag )
    _RTHP-CT-ID @ _RTHP-CT-P @ _RTHP.FIRST-OBJECT @ U< IF 0 EXIT THEN
    _RTHP-CT-ID @ _RTHP-CT-P @ _RTHP.FIRST-OBJECT @ -
    DUP _RTHP-CT-P @ _RTHP.CONTROL-COUNT @ U< 0= IF DROP 0 EXIT THEN
    RTE-CONTROL-SIZE * _RTHP-CT-P @ _RTHP.CONTROLS-A @ +
        _RTHP-CT-CONTROL ! -1 ;

: _RTHP-CT-CONTROL?  ( -- flag )
    _RTHP-CT-CONTROL @ DUP _RTE-CONTROL.OWNER @
        _RTHP-CT-OWNER @ <> IF DROP 0 EXIT THEN
    DUP _RTE-CONTROL.GENERATION @
        _RTHP-CT-GENERATION @ <> IF DROP 0 EXIT THEN
    DUP _RTE-CONTROL.ID @ _RTHP-CT-ID @ <> IF DROP 0 EXIT THEN
    DUP _RTE-CONTROL.KIND @ DUP RTE-CONTROL-MENU =
        SWAP RTE-CONTROL-MENU-ITEM = OR 0= IF DROP 0 EXIT THEN
    _RTE-CONTROL.STATE @
    RTE-CONTROL-VISIBLE RTE-CONTROL-ENABLED OR AND
        RTE-CONTROL-VISIBLE RTE-CONTROL-ENABLED OR = ;

: _RTHP-CT-CORRELATION-AT?  ( ordinal -- flag )
    DUP _RTHP-CT-P @ _RTHP.CONTROL-COUNT @ U< 0= IF DROP 0 EXIT THEN
    DUP _RTHP-CT-ORDINAL !
    RUCP-CORRELATION-SIZE * _RTHP-CT-P @ _RTHP.CORR-A @ +
    DUP _RTHP-CT-CORRELATION !
    RUCP-CORRELATION-CONTROL-ID@ DUP _RTHP-CT-ID ! 0<> ;

: _RTHP-CT-CORRELATION?  ( -- flag )
    _RTHP-CT-CORRELATION @ DUP RUCP-CORRELATION-ATTACHMENT@
        _RTHP-CT-P @ _RTHP.TOKEN @ <> IF DROP 0 EXIT THEN
    DUP RUCP-CORRELATION-SOURCE@ UMSN-SOURCE-UIDL <> IF DROP 0 EXIT THEN
    DUP RUCP-CORRELATION-SUBKEY@ IF DROP 0 EXIT THEN
    DUP RUCP-CORRELATION-CONTROL-ID@ _RTHP-CT-ID @ <> IF DROP 0 EXIT THEN
    DUP RUCP-CORRELATION-INDEX@ 0< IF DROP 0 EXIT THEN
    DROP
    _RTHP-CT-ORDINAL @ _RTHP-CT-P @ _RTHP.CONTROL-COUNT @
        U< 0= IF 0 EXIT THEN
    _RTHP-CT-ORDINAL @ UMSN-RECORD-SIZE _RTHP-U32*?
        0= IF DROP 0 EXIT THEN
    _RTHP-CT-P @ _RTHP.SOURCE-RECS-A @ + _RTHP-CT-RECORD !
    -1 ;

: _RTHP-CT-STATE>RTE  ( umsn-state -- rte-state )
    0 SWAP
    DUP UMSN-F-VISIBLE AND IF SWAP RTE-CONTROL-VISIBLE OR SWAP THEN
    DUP UMSN-F-ENABLED AND IF SWAP RTE-CONTROL-ENABLED OR SWAP THEN
    DUP UMSN-F-OPEN AND IF SWAP RTE-CONTROL-OPEN OR SWAP THEN
    UMSN-F-SELECTED AND IF RTE-CONTROL-SELECTED OR THEN ;

: _RTHP-CT-RECORD?  ( -- flag )
    _RTHP-CT-RECORD @ DUP _UMSN-R.MAGIC @
        _UMSN-RECORD-MAGIC <> IF DROP 0 EXIT THEN
    DUP _UMSN-R.ABI @ _UMSN-RECORD-ABI <> IF DROP 0 EXIT THEN
    DUP _UMSN-R.BYTES @ UMSN-RECORD-SIZE <> IF DROP 0 EXIT THEN
    DUP _UMSN-R.SOURCE @ UMSN-SOURCE-UIDL <> IF DROP 0 EXIT THEN
    DUP UMSN-RECORD-GENERATION@
        _RTHP-CT-P @ _RTHP.SOURCE-GEN @ <> IF DROP 0 EXIT THEN
    DUP UMSN-RECORD-SOURCE-INDEX@
        _RTHP-CT-CORRELATION @ RUCP-CORRELATION-INDEX@ <> IF DROP 0 EXIT THEN
    DUP UMSN-RECORD-SUBKEY@
        _RTHP-CT-CORRELATION @ RUCP-CORRELATION-SUBKEY@ <> IF DROP 0 EXIT THEN
    DUP UMSN-RECORD-KIND@ DUP UMSN-K-MENU =
        SWAP UMSN-K-ITEM = OR 0= IF DROP 0 EXIT THEN
    DUP UMSN-RECORD-KIND@ UMSN-K-MENU = IF
        _RTHP-CT-CONTROL @ _RTE-CONTROL.KIND @
            RTE-CONTROL-MENU <> IF DROP 0 EXIT THEN
    ELSE
        _RTHP-CT-CONTROL @ _RTE-CONTROL.KIND @
            RTE-CONTROL-MENU-ITEM <> IF DROP 0 EXIT THEN
    THEN
    DUP UMSN-RECORD-STATE@
    _RTHP-CT-STATE>RTE
        _RTHP-CT-CONTROL @ _RTE-CONTROL.STATE @ <> IF DROP 0 EXIT THEN
    DROP -1 ;

: _RTHP-CT-GEOMETRY?  ( -- flag )
    _RTHP-CT-RECORD @ UMSN-RECORD-RESOLVED DROP _RTHP-CT-RESOLVED !
    _RTHP-CT-RESOLVED @ UTUI-RESOLVED-SIZE
        UTUI-RESOLVED-VALID? 0= IF 0 EXIT THEN
    _RTHP-CT-RESOLVED @ DUP @ _RTHP-CT-ROW !
    DUP 8 + @ _RTHP-CT-COL !
    DUP 16 + @ _RTHP-CT-H !
    24 + @ _RTHP-CT-W !
    _RTHP-CT-ROW @ 0< _RTHP-CT-COL @ 0< OR IF 0 EXIT THEN
    _RTHP-CT-H @ 0> _RTHP-CT-W @ 0> AND 0= IF 0 EXIT THEN
    _RTHP-CT-ROW @ _RTHP-CT-H @ _RTHP-U32+?
        0= IF DROP 0 EXIT THEN _RTHP-CT-END !
    _RTHP-CT-END @ _RTHP-CT-P @ _RTHP.ROWS @ U> IF 0 EXIT THEN
    _RTHP-CT-COL @ _RTHP-CT-W @ _RTHP-U32+?
        0= IF DROP 0 EXIT THEN _RTHP-CT-END !
    _RTHP-CT-END @ _RTHP-CT-P @ _RTHP.COLS @ U> IF 0 EXIT THEN
    _RTHP-CT-ROW @ _RTHP-CT-H @ 1- 2/ + _RTHP-CT-ROW !
    _RTHP-CT-COL @ _RTHP-CT-W @ 1- 2/ + _RTHP-CT-COL !
    -1 ;

VARIABLE _RTHP-TG-P
VARIABLE _RTHP-TG-BANK
VARIABLE _RTHP-TG-BYTES
VARIABLE _RTHP-TG-COUNT

: _RTHP-TG-CLEAR  ( -- )
    _RTHP-CT-CLEAR
    0 _RTHP-TG-P ! 0 _RTHP-TG-BANK !
    0 _RTHP-TG-BYTES ! 0 _RTHP-TG-COUNT ! ;

: _RTHP-TARGET-ABORT  ( producer -- )
    0 SWAP _RTHP.TARGET-PENDING ! _RTHP-TG-CLEAR ;

: _RTHP-TG-FAIL  ( -- false )
    _RTHP-TG-P @ ?DUP IF _RTHP-TARGET-ABORT ELSE _RTHP-TG-CLEAR THEN
    0 ;

: _RTHP-TARGET-INACTIVE  ( producer -- bank )
    DUP _RTHP.TARGET-ACTIVE @ OVER _RTHP.TARGET0-A @ = IF
        _RTHP.TARGET1-A @
    ELSE
        _RTHP.TARGET0-A @
    THEN ;

: _RTHP-TARGET-CANDIDATE?  ( producer -- flag )
    DUP _RTHP-TARGET-ABORT _RTHP-TG-P !
    _RTHP-TG-P @ _RTHP-TARGET-INACTIVE _RTHP-TG-BANK !
    _RTHP-TG-P @ _RTHP.MAX-RECORDS @ _RTHP-TARGET-BANK-BYTES?
        0= IF DROP _RTHP-TG-FAIL EXIT THEN _RTHP-TG-BYTES !
    _RTHP-TG-BANK @ _RTHP-TG-BYTES @ _RTHP-TG-P @
        _RTHP-ARENA-SPAN? 0= IF _RTHP-TG-FAIL EXIT THEN

    _RTHP-TG-P @ _RTHP.OWNER @ _RTHP-TG-BANK @ _RTHP-TB.OWNER !
    _RTHP-TG-P @ _RTHP.OWNER-GEN @
        _RTHP-TG-BANK @ _RTHP-TB.GENERATION !
    _RTHP-TG-P @ _RTHP.COLS @ _RTHP-TG-BANK @ _RTHP-TB.COLS !
    _RTHP-TG-P @ _RTHP.ROWS @ _RTHP-TG-BANK @ _RTHP-TB.ROWS !
    0 _RTHP-TG-BANK @ _RTHP-TB.COUNT !

    _RTHP-TG-P @ _RTHP-CT-P !
    _RTHP-TG-P @ _RTHP.OWNER @ _RTHP-CT-OWNER !
    _RTHP-TG-P @ _RTHP.OWNER-GEN @ _RTHP-CT-GENERATION !
    _RTHP-CT-CANDIDATE-SHAPE? 0= IF _RTHP-TG-FAIL EXIT THEN
    0 _RTHP-TG-COUNT !
    _RTHP-TG-P @ _RTHP.CONTROL-COUNT @ 0 ?DO
        I _RTHP-CT-CORRELATION-AT? 0= IF _RTHP-TG-FAIL UNLOOP EXIT THEN
        _RTHP-CT-FIND-CONTROL? 0= IF _RTHP-TG-FAIL UNLOOP EXIT THEN
        _RTHP-CT-CONTROL @ _RTHP-CT-TARGET? IF
            _RTHP-CT-CONTROL? 0= IF _RTHP-TG-FAIL UNLOOP EXIT THEN
            _RTHP-CT-CORRELATION? 0= IF _RTHP-TG-FAIL UNLOOP EXIT THEN
            _RTHP-CT-RECORD? 0= IF _RTHP-TG-FAIL UNLOOP EXIT THEN
            _RTHP-CT-RECORD @ UMSN-RECORD-STATE@
                UMSN-F-PAINTABLE AND IF
                _RTHP-CT-GEOMETRY? 0= IF _RTHP-TG-FAIL UNLOOP EXIT THEN
                _RTHP-TG-COUNT @ _RTHP-TG-P @ _RTHP.MAX-RECORDS @
                    U< 0= IF _RTHP-TG-FAIL UNLOOP EXIT THEN
                _RTHP-TG-COUNT @ _RTHP-TG-BANK @ _RTHP-TARGET-ENTRY
                _RTHP-CT-ID @ OVER _RTHP-TE.ID !
                _RTHP-CT-ROW @ OVER _RTHP-TE.ROW !
                _RTHP-CT-COL @ SWAP _RTHP-TE.COL !
                1 _RTHP-TG-COUNT +!
            THEN
        THEN
    LOOP
    _RTHP-TG-COUNT @ _RTHP-TG-BANK @ _RTHP-TB.COUNT !
    _RTHP-TG-BANK @ _RTHP-TG-P @ _RTHP.TARGET-PENDING !
    _RTHP-TG-CLEAR -1 ;

VARIABLE _RTHP-TV-P
VARIABLE _RTHP-TV-BANK
VARIABLE _RTHP-TV-BYTES
VARIABLE _RTHP-TV-ID
VARIABLE _RTHP-TV-ROW
VARIABLE _RTHP-TV-COL

: _RTHP-TARGET-BANK-HEADER?  ( bank producer -- flag )
    _RTHP-TV-P ! _RTHP-TV-BANK !
    _RTHP-TV-BANK @ DUP 0= SWAP 7 AND OR IF 0 EXIT THEN
    _RTHP-TV-BANK @ _RTHP-TV-P @ _RTHP.TARGET0-A @ =
    _RTHP-TV-BANK @ _RTHP-TV-P @ _RTHP.TARGET1-A @ = OR
        0= IF 0 EXIT THEN
    _RTHP-TV-P @ _RTHP.MAX-RECORDS @ _RTHP-TARGET-BANK-BYTES?
        0= IF DROP 0 EXIT THEN _RTHP-TV-BYTES !
    _RTHP-TV-BANK @ _RTHP-TV-BYTES @ _RTHP-TV-P @
        _RTHP-ARENA-SPAN? 0= IF 0 EXIT THEN
    _RTHP-TV-BANK @ _RTHP-TB.OWNER @ 0=
    _RTHP-TV-BANK @ _RTHP-TB.GENERATION @ 0= OR IF 0 EXIT THEN
    _RTHP-TV-BANK @ _RTHP-TB.COLS @ DUP 0> SWAP
        _RTHP-TV-P @ _RTHP.MAX-COLS @ U> 0= AND 0= IF 0 EXIT THEN
    _RTHP-TV-BANK @ _RTHP-TB.ROWS @ DUP 0> SWAP
        _RTHP-TV-P @ _RTHP.MAX-ROWS @ U> 0= AND 0= IF 0 EXIT THEN
    _RTHP-TV-BANK @ _RTHP-TB.COUNT @
        _RTHP-TV-P @ _RTHP.MAX-RECORDS @ U> 0= ;

: _RTHP-TARGET-BANK-ENTRIES?  ( -- flag )
    _RTHP-TV-BANK @ _RTHP-TB.COUNT @ 0 ?DO
        I _RTHP-TV-BANK @ _RTHP-TARGET-ENTRY
        DUP _RTHP-TE.ID @ DUP _RTHP-TV-ID !
        0= IF DROP 0 UNLOOP EXIT THEN
        DUP _RTHP-TE.ROW @ DUP _RTHP-TV-ROW ! 0< IF
            DROP 0 UNLOOP EXIT
        THEN
        _RTHP-TV-ROW @ _RTHP-TV-BANK @ _RTHP-TB.ROWS @ U< 0= IF
            DROP 0 UNLOOP EXIT
        THEN
        _RTHP-TE.COL @ DUP _RTHP-TV-COL ! 0< IF 0 UNLOOP EXIT THEN
        _RTHP-TV-COL @ _RTHP-TV-BANK @ _RTHP-TB.COLS @ U< 0= IF
            0 UNLOOP EXIT
        THEN
    LOOP
    -1 ;

VARIABLE _RTHP-TP-P
VARIABLE _RTHP-TP-BANK

: _RTHP-TARGET-PUBLISH?  ( producer -- flag )
    _RTHP-TP-P !
    _RTHP-TP-P @ _RTHP.PHASE @ _RTHP-PH-LIVE <> IF 0 EXIT THEN
    _RTHP-TP-P @ _RTHP.TARGET-PENDING @ DUP 0= IF DROP 0 EXIT THEN
        _RTHP-TP-BANK !
    _RTHP-TP-BANK @ _RTHP-TP-P @ _RTHP-TARGET-BANK-HEADER?
        0= IF 0 EXIT THEN
    _RTHP-TP-BANK @ _RTHP-TP-P @ _RTHP.TARGET-ACTIVE @ = IF 0 EXIT THEN
    _RTHP-TP-BANK @ _RTHP-TB.OWNER @
        _RTHP-TP-P @ _RTHP.OWNER @ <> IF 0 EXIT THEN
    _RTHP-TP-BANK @ _RTHP-TB.GENERATION @
        _RTHP-TP-P @ _RTHP.OWNER-GEN @ <> IF 0 EXIT THEN
    _RTHP-TP-BANK @ _RTHP-TB.COLS @
        _RTHP-TP-P @ _RTHP.COLS @ <> IF 0 EXIT THEN
    _RTHP-TP-BANK @ _RTHP-TB.ROWS @
        _RTHP-TP-P @ _RTHP.ROWS @ <> IF 0 EXIT THEN
    _RTHP-TARGET-BANK-ENTRIES? 0= IF 0 EXIT THEN
    0 _RTHP-TP-P @ _RTHP.TARGET-PENDING !
    _RTHP-TP-BANK @ _RTHP-TP-P @ _RTHP.TARGET-ACTIVE !
    0 _RTHP-TP-P ! 0 _RTHP-TP-BANK ! -1 ;

VARIABLE _RTHP-TL-P
VARIABLE _RTHP-TL-BANK
VARIABLE _RTHP-TL-OWNER
VARIABLE _RTHP-TL-GENERATION
VARIABLE _RTHP-TL-ID
VARIABLE _RTHP-TL-MATCHES
VARIABLE _RTHP-TL-ROW
VARIABLE _RTHP-TL-COL

: _RTHP-TL-CLEAR  ( -- )
    0 _RTHP-TL-P ! 0 _RTHP-TL-BANK ! 0 _RTHP-TL-OWNER !
    0 _RTHP-TL-GENERATION ! 0 _RTHP-TL-ID !
    0 _RTHP-TL-MATCHES ! 0 _RTHP-TL-ROW ! 0 _RTHP-TL-COL ! ;

: _RTHP-TL-FAIL  ( -- row col false )
    _RTHP-TL-CLEAR 0 0 0 ;

: _RTHP-TARGET-BANK-FIND?  ( -- flag )
    0 _RTHP-TL-MATCHES !
    _RTHP-TL-BANK @ _RTHP-TB.COUNT @ 0 ?DO
        I _RTHP-TL-BANK @ _RTHP-TARGET-ENTRY
        DUP _RTHP-TE.ID @ DUP _RTHP-TV-ID !
        0= IF DROP 0 UNLOOP EXIT THEN
        DUP _RTHP-TE.ROW @ DUP _RTHP-TV-ROW ! 0< IF
            DROP 0 UNLOOP EXIT
        THEN
        _RTHP-TV-ROW @ _RTHP-TL-BANK @ _RTHP-TB.ROWS @ U< 0= IF
            DROP 0 UNLOOP EXIT
        THEN
        DUP _RTHP-TE.COL @ DUP _RTHP-TV-COL ! 0< IF
            DROP 0 UNLOOP EXIT
        THEN
        _RTHP-TV-COL @ _RTHP-TL-BANK @ _RTHP-TB.COLS @ U< 0= IF
            DROP 0 UNLOOP EXIT
        THEN
        _RTHP-TV-ID @ _RTHP-TL-ID @ = IF
            _RTHP-TV-ROW @ _RTHP-TL-ROW !
            _RTHP-TV-COL @ _RTHP-TL-COL !
            1 _RTHP-TL-MATCHES +!
        THEN
        DROP
    LOOP
    _RTHP-TL-MATCHES @ 1 = ;

: RTHP-CONTROL-MENU-TARGET@
  ( owner generation control-id producer -- row col found? )
    _RTHP-TL-P ! _RTHP-TL-ID !
    _RTHP-TL-GENERATION ! _RTHP-TL-OWNER !
    _RTHP-TL-P @ RTHP-VALID? 0= IF _RTHP-TL-FAIL EXIT THEN
    _RTHP-TL-P @ _RTHP.TARGET-ACTIVE @ DUP 0= IF
        DROP _RTHP-TL-FAIL EXIT
    THEN _RTHP-TL-BANK !
    _RTHP-TL-BANK @ _RTHP-TL-P @ _RTHP-TARGET-BANK-HEADER?
        0= IF _RTHP-TL-FAIL EXIT THEN
    _RTHP-TL-OWNER @ _RTHP-TL-BANK @ _RTHP-TB.OWNER @ <>
    _RTHP-TL-GENERATION @
        _RTHP-TL-BANK @ _RTHP-TB.GENERATION @ <> OR
    _RTHP-TL-BANK @ _RTHP-TB.OWNER @
        _RTHP-TL-P @ _RTHP.OWNER @ <> OR
    _RTHP-TL-BANK @ _RTHP-TB.GENERATION @
        _RTHP-TL-P @ _RTHP.OWNER-GEN @ <> OR
    _RTHP-TL-ID @ 0= OR IF _RTHP-TL-FAIL EXIT THEN
    _RTHP-TARGET-BANK-FIND? 0= IF _RTHP-TL-FAIL EXIT THEN
    _RTHP-TL-ROW @ _RTHP-TL-COL @ -1
    _RTHP-TL-CLEAR ;

: RTHP-INIT
  ( adapter facade arena-a arena-u max-records max-source-text max-cols max-rows owner owner-generation region first-object producer -- scb-status )
    _RTHP-I-P ! _RTHP-I-FIRST ! _RTHP-I-REGION ! _RTHP-I-GEN !
    _RTHP-I-OWNER ! _RTHP-I-ROWS ! _RTHP-I-COLS ! _RTHP-I-TEXT !
    _RTHP-I-RECORDS ! _RTHP-I-ARENA-U ! _RTHP-I-ARENA !
    _RTHP-I-FACADE ! _RTHP-I-ADAPTER !
    _RTHP-I-ADAPTER @ RUHA-VALID? 0= IF SCB-S-INVALID EXIT THEN
    _RTHP-I-FACADE @ RTE-VALID? 0= IF SCB-S-INVALID EXIT THEN
    _RTHP-I-OWNER @ 0= _RTHP-I-GEN @ 0= OR
    _RTHP-I-REGION @ 0= OR _RTHP-I-FIRST @ 0= OR IF
        SCB-S-INVALID EXIT
    THEN
    _RTHP-I-RECORDS @ _RTHP-I-TEXT @ _RTHP-I-COLS @ _RTHP-I-ROWS @
        RTHP-STORAGE-BYTES DUP 0= IF DROP SCB-S-INVALID EXIT THEN
        _RTHP-I-REQUIRED !
    _RTHP-I-P @ 7 AND _RTHP-I-ARENA @ 7 AND OR IF
        SCB-S-INVALID EXIT
    THEN
    _RTHP-I-P @ RTHP-SIZE MSPAN-NONWRAPPING? 0= IF
        SCB-S-INVALID EXIT
    THEN
    _RTHP-I-ARENA @ _RTHP-I-ARENA-U @ MSPAN-NONWRAPPING? 0= IF
        SCB-S-INVALID EXIT
    THEN
    _RTHP-I-ARENA-U @ _RTHP-I-REQUIRED @ U< IF SCB-S-INVALID EXIT THEN
    _RTHP-I-P @ RTHP-SIZE _RTHP-I-ARENA @ _RTHP-I-REQUIRED @
        MSPAN-OVERLAP? IF SCB-S-INVALID EXIT THEN
    _RTHP-I-P @ RTHP-SIZE _RTHP-I-FACADE @
        RTE-STORAGE-DISJOINT? 0= IF SCB-S-INVALID EXIT THEN
    _RTHP-I-ARENA @ _RTHP-I-REQUIRED @ _RTHP-I-FACADE @
        RTE-STORAGE-DISJOINT? 0= IF SCB-S-INVALID EXIT THEN
    _RTHP-I-P @ RTHP-SIZE
        _RTHP-I-ADAPTER @ RUHA-SIZE MSPAN-OVERLAP? IF
        SCB-S-INVALID EXIT
    THEN
    _RTHP-I-ARENA @ _RTHP-I-REQUIRED @
        _RTHP-I-ADAPTER @ RUHA-SIZE MSPAN-OVERLAP? IF
        SCB-S-INVALID EXIT
    THEN
    _RTHP-I-P @ RTHP-SIZE 0 FILL
    RTHP-SIZE _RTHP-I-P @ _RTHP.SIZE !
    _RTHP-I-P @ DUP _RTHP.SELF !
    _RTHP-I-ADAPTER @ _RTHP-I-P @ _RTHP.ADAPTER !
    _RTHP-I-FACADE @ _RTHP-I-P @ _RTHP.FACADE !
    _RTHP-I-ARENA @ _RTHP-I-P @ _RTHP.ARENA-A !
    _RTHP-I-REQUIRED @ _RTHP-I-P @ _RTHP.ARENA-U !
    _RTHP-I-RECORDS @ _RTHP-I-P @ _RTHP.MAX-RECORDS !
    _RTHP-I-TEXT @ _RTHP-I-P @ _RTHP.MAX-TEXT !
    _RTHP-I-COLS @ _RTHP-I-P @ _RTHP.MAX-COLS !
    _RTHP-I-ROWS @ _RTHP-I-P @ _RTHP.MAX-ROWS !
    _RTHP-I-OWNER @ _RTHP-I-P @ _RTHP.OWNER !
    _RTHP-I-GEN @ _RTHP-I-P @ _RTHP.OWNER-GEN !
    _RTHP-I-REGION @ _RTHP-I-P @ _RTHP.REGION !
    _RTHP-I-FIRST @ _RTHP-I-P @ _RTHP.FIRST-OBJECT !
    _RTHP-I-REGION @ _RTHP-I-P @ _RTHP.NEXT-REGION !
    _RTHP-I-FIRST @ _RTHP-I-P @ _RTHP.NEXT-OBJECT !
    _RTHP-PH-WAIT _RTHP-I-P @ _RTHP.PHASE !
    SCB-S-OK _RTHP-I-P @ _RTHP.FAULT !
    _RTHP-I-P @ _RTHP-LAYOUT
    _RTHP-I-P @ _RTHP.TARGET0-A @
        _RTHP-TARGET-BANK-HEADER-SIZE 0 FILL
    _RTHP-I-P @ _RTHP.TARGET1-A @
        _RTHP-TARGET-BANK-HEADER-SIZE 0 FILL
    _RTHP-MAGIC _RTHP-I-P @ _RTHP.MAGIC !
    _RTHP-I-P @ RTHP-VALID? IF SCB-S-OK ELSE SCB-S-INVALID THEN ;

\ =====================================================================
\  One immutable combined candidate
\ =====================================================================

VARIABLE _RTHP-W-P
VARIABLE _RTHP-W-SNAP
VARIABLE _RTHP-W-STATUS
VARIABLE _RTHP-W-COUNT
VARIABLE _RTHP-W-TEXT
VARIABLE _RTHP-W-ALIGNED
VARIABLE _RTHP-W-MAX
VARIABLE _RTHP-W-LAST
VARIABLE _RTHP-W-GLYPH-FIRST
VARIABLE _RTHP-W-CLAIMS

: _RTHP-COPY-SNAPSHOT?  ( snapshot producer -- flag )
    _RTHP-W-P ! _RTHP-W-SNAP !
    _RTHP-W-SNAP @ RUHA-SNAPSHOT-RECORDS@
    DUP _RTHP-W-P @ _RTHP.SOURCE-RECS-U @ U> IF 2DROP 0 EXIT THEN
    2DUP _RTHP-W-P @ _RTHP.ARENA-A @
        _RTHP-W-P @ _RTHP.ARENA-U @ MSPAN-OVERLAP? IF 2DROP 0 EXIT THEN
    DUP _RTHP-W-P @ _RTHP.SOURCE-USED !
    _RTHP-W-P @ _RTHP.SOURCE-RECS-A @ SWAP MOVE
    _RTHP-W-SNAP @ RUHA-SNAPSHOT-TEXT@
    DUP _RTHP-W-P @ _RTHP.SOURCE-TEXT-U @ U> IF 2DROP 0 EXIT THEN
    2DUP _RTHP-W-P @ _RTHP.ARENA-A @
        _RTHP-W-P @ _RTHP.ARENA-U @ MSPAN-OVERLAP? IF 2DROP 0 EXIT THEN
    DUP _RTHP-W-P @ _RTHP.SOURCE-TEXT-USED !
    _RTHP-W-P @ _RTHP.SOURCE-TEXT-A @ SWAP MOVE
    _RTHP-W-SNAP @ RUHA-SNAPSHOT-GENERATION@
        DUP _RTHP-W-P @ _RTHP.SOURCE-GEN !
        _RTHP-W-P @ _RTHP.SURFACE-GEN !
    _RTHP-W-SNAP @ RUHA-SNAPSHOT-TOKEN@
        _RTHP-W-P @ _RTHP.TOKEN !
    _RTHP-W-P @ _RTHP.ATTEMPT @ 1 _RTHP-U32+?
        0= IF DROP 0 EXIT THEN
        DUP 0= IF DROP 0 EXIT THEN _RTHP-W-P @ _RTHP.ATTEMPT !
    -1 ;

: _RTHP-BUILD-CONTROLS?  ( producer -- flag )
    _RTHP-W-P !
    _RTHP-W-P @ _RTHP.RUCP-Q RUCP-REQUEST-CLEAR
    _RTHP-W-P @ _RTHP.TOKEN @
    _RTHP-W-P @ _RTHP.OWNER @ _RTHP-W-P @ _RTHP.OWNER-GEN @
    _RTHP-W-P @ _RTHP.SOURCE-GEN @
    _RTHP-W-P @ _RTHP.FIRST-OBJECT @
    _RTHP-W-P @ _RTHP.RUCP-Q RUCP-REQUEST-IDENTITY!
    _RTHP-W-P @ _RTHP.COLS @ _RTHP-W-P @ _RTHP.ROWS @
    _RTHP-W-P @ _RTHP.REGION @ 0 0
    _RTHP-W-P @ _RTHP.COLS @ _RTHP-W-P @ _RTHP.ROWS @ 0 3
    _RTHP-W-P @ _RTHP.RUCP-Q RUCP-REQUEST-REGION!
    _RTHP-W-P @ _RTHP.SOURCE-RECS-A @
    _RTHP-W-P @ _RTHP.SOURCE-USED @
    _RTHP-W-P @ _RTHP.SOURCE-TEXT-A @
    _RTHP-W-P @ _RTHP.SOURCE-TEXT-USED @
    _RTHP-W-P @ _RTHP.RUCP-Q RUCP-REQUEST-SOURCE!
    _RTHP-W-P @ _RTHP.LOOKUP-A @ _RTHP-W-P @ _RTHP.LOOKUP-U @
    _RTHP-W-P @ _RTHP.ORDER-A @ _RTHP-W-P @ _RTHP.ORDER-U @
    _RTHP-W-P @ _RTHP.ORDER2-A @ _RTHP-W-P @ _RTHP.ORDER2-U @
    _RTHP-W-P @ _RTHP.RUCP-Q RUCP-REQUEST-WORK!
    _RTHP-W-P @ _RTHP.CONTROL-PLAN RTE-CONTROL-PLAN-SIZE
    _RTHP-W-P @ _RTHP.CONTROLS-A @ _RTHP-W-P @ _RTHP.CONTROLS-U @
    _RTHP-W-P @ _RTHP.CORR-A @ _RTHP-W-P @ _RTHP.CORR-U @
    _RTHP-W-P @ _RTHP.RUCP-Q RUCP-REQUEST-OUTPUT!
    _RTHP-W-P @ _RTHP.RUCP-Q RUCP-BUILD
    _RTHP-W-STATUS ! _RTHP-W-LAST ! _RTHP-W-MAX !
    _RTHP-W-ALIGNED ! _RTHP-W-TEXT ! _RTHP-W-COUNT !
    _RTHP-W-STATUS @ RUCP-S-OK <> IF 0 EXIT THEN
    _RTHP-W-COUNT @ 0= IF 0 EXIT THEN
    _RTHP-W-COUNT @ _RTHP-W-P @ _RTHP.CONTROL-COUNT !
    _RTHP-W-LAST @ 1 _RTHP-U+? 0= IF DROP 0 EXIT THEN
        DUP 0= IF DROP 0 EXIT THEN _RTHP-W-GLYPH-FIRST !
    -1 ;

: _RTHP-BUILD-CLAIMS?  ( snapshot producer -- flag )
    _RTHP-W-P ! _RTHP-W-SNAP !
    _RTHP-W-P @ _RTHP.RUCL-Q RUCL-REQUEST-CLEAR
    _RTHP-W-P @ _RTHP.TOKEN @ _RTHP-W-P @ _RTHP.SOURCE-GEN @
    _RTHP-W-P @ _RTHP.CONTROL-COUNT @
    _RTHP-W-P @ _RTHP.RUCL-Q RUCL-REQUEST-ADMISSION!
    _RTHP-W-P @ _RTHP.COLS @ _RTHP-W-P @ _RTHP.ROWS @
    _RTHP-W-SNAP @ RUHA-SNAPSHOT-ROW@
    _RTHP-W-SNAP @ RUHA-SNAPSHOT-COL@
    _RTHP-W-SNAP @ RUHA-SNAPSHOT-HEIGHT@
    _RTHP-W-SNAP @ RUHA-SNAPSHOT-WIDTH@
    _RTHP-W-P @ _RTHP.RUCL-Q RUCL-REQUEST-GEOMETRY!
    _RTHP-W-P @ _RTHP.SOURCE-RECS-A @
    _RTHP-W-P @ _RTHP.SOURCE-USED @
    _RTHP-W-P @ _RTHP.CLAIMS-A @ _RTHP-W-P @ _RTHP.CLAIMS-U @
    _RTHP-W-P @ _RTHP.RUCL-Q RUCL-REQUEST-STORAGE!
    _RTHP-W-P @ _RTHP.RUCL-Q RUCL-BUILD
    _RTHP-W-STATUS ! _RTHP-W-CLAIMS !
    _RTHP-W-STATUS @ RUCL-S-OK <> IF 0 EXIT THEN
    _RTHP-W-CLAIMS @ RUCL-CLAIM-SIZE *
        _RTHP-W-P @ _RTHP.CLAIMS-USED !
    -1 ;

: _RTHP-BUILD-GLYPHS?  ( producer -- flag )
    _RTHP-W-P !
    _RTHP-W-P @ _RTHP.RGRP-Q RGRP-REQUEST-CLEAR
    _RTHP-W-P @ _RTHP.OWNER @ _RTHP-W-P @ _RTHP.OWNER-GEN @
    _RTHP-W-P @ _RTHP.REGION @ _RTHP-W-GLYPH-FIRST @
    _RTHP-W-P @ _RTHP.RGRP-Q RGRP-REQUEST-IDENTITY!
    _RTHP-W-P @ _RTHP.COLS @ _RTHP-W-P @ _RTHP.ROWS @ 0 0
    _RTHP-W-P @ _RTHP.COLS @ _RTHP-W-P @ _RTHP.ROWS @ 0 3 0
    _RTHP-W-P @ _RTHP.RGRP-Q RGRP-REQUEST-REGION!
    _RTHP-W-P @ _RTHP.LIMITS RTE-LIMITS-GLYPH-RUN-BYTES@
    _RTHP-W-P @ _RTHP.RGRP-Q RGRP-REQUEST-LIMIT!
    _RTHP-W-P @ _RTHP.CLAIMS-A @ _RTHP-W-P @ _RTHP.CLAIMS-USED @
    _RTHP-W-P @ _RTHP.RGRP-Q RGRP-REQUEST-CLAIMS!
    _RTHP-W-P @ _RTHP.HEADS-A @ _RTHP-W-P @ _RTHP.HEADS-U @
    _RTHP-W-P @ _RTHP.EVENTS-A @ _RTHP-W-P @ _RTHP.EVENTS-U @
    _RTHP-W-P @ _RTHP.DIFF-A @ _RTHP-W-P @ _RTHP.DIFF-U @
    _RTHP-W-P @ _RTHP.RGRP-Q RGRP-REQUEST-WORK!
    _RTHP-W-P @ _RTHP.GLYPH-PLAN RTE-GLYPH-RUN-PLAN-SIZE
    _RTHP-W-P @ _RTHP.GLYPH-ITEMS-A @
    _RTHP-W-P @ _RTHP.GLYPH-ITEMS-U @
    _RTHP-W-P @ _RTHP.GLYPH-REFS-A @
    _RTHP-W-P @ _RTHP.GLYPH-REFS-U @
    _RTHP-W-P @ _RTHP.GLYPH-TEXT-A @
    _RTHP-W-P @ _RTHP.GLYPH-TEXT-U @
    _RTHP-W-P @ _RTHP.RGRP-Q RGRP-REQUEST-OUTPUT!
    _RTHP-W-P @ _RTHP.RGRP-Q RGRP-BUILD
    _RTHP-W-STATUS ! _RTHP-W-LAST ! _RTHP-W-MAX !
    _RTHP-W-ALIGNED ! _RTHP-W-TEXT ! _RTHP-W-COUNT !
    _RTHP-W-STATUS @ RGRP-S-OK <> IF 0 EXIT THEN
    _RTHP-W-COUNT @ _RTHP-W-P @ _RTHP.GLYPH-COUNT !
    _RTHP-W-TEXT @ _RTHP-W-P @ _RTHP.GLYPH-TEXT-USED !
    -1 ;

: _RTHP-WRAP-HYBRID  ( producer -- )
    _RTHP-W-P !
    _RTHP-W-P @ _RTHP.HYBRID RTE-HYBRID-PLAN-SIZE 0 FILL
    _RTHP-W-P @ _RTHP.ATTEMPT @
        _RTHP-W-P @ _RTHP.HYBRID _RTE-HP.ATTEMPT !
    _RTHP-W-P @ _RTHP.SOURCE-GEN @
        _RTHP-W-P @ _RTHP.HYBRID _RTE-HP.SOURCE-GENERATION !
    _RTHP-W-P @ _RTHP.SURFACE-GEN @
        _RTHP-W-P @ _RTHP.HYBRID _RTE-HP.SURFACE-GENERATION !
    _RTHP-W-P @ _RTHP.CONTROL-PLAN
        _RTHP-W-P @ _RTHP.HYBRID _RTE-HP.CONTROL-PLAN !
    _RTHP-W-P @ _RTHP.GLYPH-COUNT @ IF
        _RTHP-W-P @ _RTHP.GLYPH-PLAN
            _RTHP-W-P @ _RTHP.HYBRID _RTE-HP.GLYPH-PLAN !
        _RTHP-W-P @ _RTHP.GLYPH-REFS-A @
            _RTHP-W-P @ _RTHP.HYBRID _RTE-HP.GLYPH-REFS-A !
        _RTHP-W-P @ _RTHP.GLYPH-COUNT @ RGRP-TEXT-REF-SIZE *
            _RTHP-W-P @ _RTHP.HYBRID _RTE-HP.GLYPH-REFS-U !
        _RTHP-W-P @ _RTHP.GLYPH-TEXT-A @
            _RTHP-W-P @ _RTHP.HYBRID _RTE-HP.GLYPH-TEXT-A !
        _RTHP-W-P @ _RTHP.GLYPH-TEXT-USED @
            _RTHP-W-P @ _RTHP.HYBRID _RTE-HP.GLYPH-TEXT-U !
    THEN
    _RTHP-W-P @ _RTHP.SOURCE-TEXT-A @
        _RTHP-W-P @ _RTHP.HYBRID _RTE-HP.CONTROL-TEXT-A !
    _RTHP-W-P @ _RTHP.SOURCE-TEXT-USED @
        _RTHP-W-P @ _RTHP.HYBRID _RTE-HP.CONTROL-TEXT-U ! ;

: _RTHP-RTE>SCB  ( rte-status -- scb-status )
    DUP RTE-S-OK = IF DROP SCB-S-OK EXIT THEN
    DUP RTE-S-WOULD-BLOCK = IF DROP SCB-S-WOULD-BLOCK EXIT THEN
    DUP RTE-S-SESSION-LOST = IF DROP SCB-S-SESSION-LOST EXIT THEN
    DROP SCB-S-INVALID ;

VARIABLE _RTHP-N-P
VARIABLE _RTHP-N-REGION
VARIABLE _RTHP-N-OBJECT

: _RTHP-SELECT-NEXT-IDS?  ( producer -- flag )
    _RTHP-N-P !
    _RTHP-N-P @ _RTHP.NEXT-REGION @ DUP 0= IF DROP 0 EXIT THEN
        _RTHP-N-P @ _RTHP.REGION !
    _RTHP-N-P @ _RTHP.NEXT-OBJECT @ DUP 0= IF DROP 0 EXIT THEN
        _RTHP-N-P @ _RTHP.FIRST-OBJECT !
    -1 ;

: _RTHP-CANDIDATE-LAST-OBJECT  ( producer -- object )
    DUP _RTHP.ADMISSION _RTE-HA.GLYPH-COUNT @ IF
        _RTHP.ADMISSION _RTE-HA.GLYPH-LAST @
    ELSE
        _RTHP.ADMISSION _RTE-HA.CONTROL-LAST @
    THEN ;

: _RTHP-CANDIDATE-NEXT?  ( producer -- next-region next-object flag )
    _RTHP-N-P !
    _RTHP-N-P @ _RTHP.REGION @ DUP 0= IF DROP 0 0 0 EXIT THEN
    _RTHP-N-P @ _RTHP.NEXT-REGION @ <> IF 0 0 0 EXIT THEN
    _RTHP-N-P @ _RTHP.REGION @ 1 _RTHP-U+?
        0= IF DROP 0 0 0 EXIT THEN _RTHP-N-REGION !
    _RTHP-N-P @ _RTHP.FIRST-OBJECT @ DUP 0= IF DROP 0 0 0 EXIT THEN
    _RTHP-N-P @ _RTHP.NEXT-OBJECT @ <> IF 0 0 0 EXIT THEN
    _RTHP-N-P @ _RTHP-CANDIDATE-LAST-OBJECT DUP 0= IF
        DROP 0 0 0 EXIT
    THEN
    DUP _RTHP-N-P @ _RTHP.FIRST-OBJECT @ U< IF DROP 0 0 0 EXIT THEN
    1 _RTHP-U+? 0= IF DROP 0 0 0 EXIT THEN _RTHP-N-OBJECT !
    _RTHP-N-REGION @ _RTHP-N-OBJECT @ -1 ;

: _RTHP-ADVANCE-IDS?  ( producer -- flag )
    DUP _RTHP-N-P ! _RTHP-CANDIDATE-NEXT? 0= IF 2DROP 0 EXIT THEN
    _RTHP-N-P @ _RTHP.NEXT-OBJECT !
    _RTHP-N-P @ _RTHP.NEXT-REGION !
    -1 ;

VARIABLE _RTHP-F-P
VARIABLE _RTHP-F-STATUS

: _RTHP-FAULT-RESULT  ( scb-status producer -- scb-status false false )
    _RTHP-F-P ! _RTHP-F-STATUS !
    _RTHP-F-STATUS @ _RTHP-F-P @ _RTHP.FAULT !
    _RTHP-PH-FAULT _RTHP-F-P @ _RTHP.PHASE !
    _RTHP-F-STATUS @ 0 0 ;

VARIABLE _RTHP-O-P
VARIABLE _RTHP-O-CELLS
VARIABLE _RTHP-O-OBJECTS
VARIABLE _RTHP-O-TEXT

: _RTHP-OPEN  ( producer -- rte-status )
    _RTHP-O-P !
    _RTHP-O-P @ _RTHP.MAX-COLS @ _RTHP-O-P @ _RTHP.MAX-ROWS @
        _RTHP-U32*? 0= IF DROP RTE-S-INVALID EXIT THEN
        _RTHP-O-CELLS !
    _RTHP-O-P @ _RTHP.MAX-RECORDS @ _RTHP-O-CELLS @
        _RTHP-U32+? 0= IF DROP RTE-S-INVALID EXIT THEN
    _RTHP-O-P @ _RTHP.LIMITS RTE-LIMITS-OBJECTS@ _RTHP-UMIN
        _RTHP-O-OBJECTS !
    _RTHP-O-CELLS @ 4 _RTHP-U32*? 0= IF DROP RTE-S-INVALID EXIT THEN
    _RTHP-O-P @ _RTHP.MAX-TEXT @ SWAP
        _RTHP-U32+? 0= IF DROP RTE-S-INVALID EXIT THEN
    _RTHP-O-P @ _RTHP.LIMITS RTE-LIMITS-UTF8-BYTES@ _RTHP-UMIN
        _RTHP-O-TEXT !
    _RTHP-O-OBJECTS @ 0= _RTHP-O-TEXT @ 0= OR IF RTE-S-INVALID EXIT THEN
    _RTHP-O-P @ _RTHP.OWNER @
    _RTHP-O-P @ _RTHP.OWNER-GEN @
    1 0 _RTHP-O-OBJECTS @ 0 0 _RTHP-O-TEXT @ 0
    _RTHP-O-P @ _RTHP.FACADE @ RTE-OWNER-OPEN ;

: _RTHP-TRY-CANDIDATE  ( producer -- scb-status started? )
    _RTHP-W-P !
    _RTHP-W-P @ _RTHP.ADAPTER @ RUHA-SNAPSHOT@
    _RTHP-W-STATUS ! _RTHP-W-SNAP !
    _RTHP-W-STATUS @ RUHA-S-UNAVAILABLE = IF SCB-S-OK 0 EXIT THEN
    _RTHP-W-STATUS @ RUHA-S-OK <> IF SCB-S-INVALID 0 EXIT THEN
    _RTHP-W-P @ _RTHP.LIMITS _RTHP-W-P @ _RTHP.FACADE @ RTE-LIMITS@
        DUP _RTHP-W-STATUS !
    DUP RTE-S-UNAVAILABLE = OVER RTE-S-WOULD-BLOCK = OR IF
        DROP SCB-S-OK 0 EXIT
    THEN
    RTE-S-OK <> IF _RTHP-W-STATUS @ _RTHP-RTE>SCB 0 EXIT THEN
    _RTHP-W-SNAP @ _RTHP-W-P @ _RTHP-COPY-SNAPSHOT?
        0= IF SCB-S-INVALID 0 EXIT THEN
    _RTHP-W-P @ _RTHP-SELECT-NEXT-IDS? 0= IF SCB-S-INVALID 0 EXIT THEN
    _RTHP-W-P @ _RTHP-BUILD-CONTROLS? 0= IF SCB-S-INVALID 0 EXIT THEN
    _RTHP-W-SNAP @ _RTHP-W-P @ _RTHP-BUILD-CLAIMS?
        0= IF SCB-S-INVALID 0 EXIT THEN
    _RTHP-W-P @ _RTHP-BUILD-GLYPHS? 0= IF SCB-S-INVALID 0 EXIT THEN
    _RTHP-W-P @ _RTHP-WRAP-HYBRID
    _RTHP-W-P @ _RTHP.ADMISSION RTE-HYBRID-ADMISSION-SIZE 0 FILL
    _RTHP-W-P @ _RTHP.HYBRID _RTHP-W-P @ _RTHP.ADMISSION
    _RTHP-W-P @ _RTHP.FACADE @ RTE-HYBRID-PREFLIGHT
        DUP _RTHP-W-STATUS !
    DUP RTE-S-UNAVAILABLE = OVER RTE-S-CAPACITY = OR IF
        DROP _RTHP-PH-DISABLED _RTHP-W-P @ _RTHP.PHASE !
        SCB-S-OK 0 EXIT
    THEN
    DUP RTE-S-WOULD-BLOCK = IF DROP SCB-S-OK 0 EXIT THEN
    RTE-S-OK <> IF _RTHP-W-STATUS @ _RTHP-RTE>SCB 0 EXIT THEN
    _RTHP-W-P @ _RTHP-CANDIDATE-NEXT? 0= IF
        2DROP SCB-S-INVALID 0 EXIT
    THEN 2DROP
    _RTHP-PH-OPENING _RTHP-W-P @ _RTHP.PHASE !
    _RTHP-W-P @ _RTHP-OPEN DUP _RTHP-W-STATUS !
    DUP RTE-S-OK = OVER RTE-S-WOULD-BLOCK = OR IF
        DROP SCB-S-OK -1 EXIT
    THEN
    RTE-S-SESSION-LOST = IF SCB-S-SESSION-LOST -1 EXIT THEN
    SCB-S-INVALID -1 ;

\ =====================================================================
\  STEP lifecycle
\ =====================================================================

VARIABLE _RTHP-S-P
VARIABLE _RTHP-S-COLS
VARIABLE _RTHP-S-ROWS
VARIABLE _RTHP-S-GEN
VARIABLE _RTHP-S-STATE
VARIABLE _RTHP-S-STATUS

: _RTHP-CALL-SURFACE?  ( cols rows generation producer -- flag )
    _RTHP-S-P ! _RTHP-S-GEN ! _RTHP-S-ROWS ! _RTHP-S-COLS !
    _RTHP-S-COLS @ 0> _RTHP-S-ROWS @ 0> AND
    _RTHP-S-GEN @ 0<> AND 0= IF 0 EXIT THEN
    _RTHP-S-COLS @ _RTHP-S-P @ _RTHP.MAX-COLS @ U>
    _RTHP-S-ROWS @ _RTHP-S-P @ _RTHP.MAX-ROWS @ U> OR IF 0 EXIT THEN
    SCR-W _RTHP-S-COLS @ = SCR-H _RTHP-S-ROWS @ = AND
    _RTHP-S-P @ _RTHP.PHASE @ _RTHP-PH-WAIT <> IF
        _RTHP-S-COLS @ _RTHP-S-P @ _RTHP.COLS @ = AND
        _RTHP-S-ROWS @ _RTHP-S-P @ _RTHP.ROWS @ = AND
        _RTHP-S-GEN @ _RTHP-S-P @ _RTHP.PHYSICAL-GEN @ = AND
    THEN ;

: _RTHP-STEP-OPENING  ( producer -- scb-status more? output-needed? )
    DUP _RTHP.OWNER @ OVER _RTHP.OWNER-GEN @
    2 PICK _RTHP.FACADE @ RTE-OWNER-STATE@
    _RTHP-S-STATUS ! _RTHP-S-STATE !
    _RTHP-S-STATUS @ RTE-S-SESSION-LOST = IF
        SCB-S-SESSION-LOST SWAP _RTHP-FAULT-RESULT EXIT
    THEN
    _RTHP-S-STATE @ RTE-OWNER-ST-OPEN =
    _RTHP-S-STATUS @ RTE-S-OK = AND IF
        _RTHP-PH-READY-START OVER _RTHP.PHASE !
        DROP SCB-S-OK 0 -1 EXIT
    THEN
    _RTHP-S-STATE @ RTE-OWNER-ST-OPENING = IF
        DROP SCB-S-OK -1 0 EXIT
    THEN
    _RTHP-S-STATE @ RTE-OWNER-ST-FREE =
    _RTHP-S-STATUS @ RTE-S-OK = AND IF
        DUP _RTHP-OPEN DUP _RTHP-S-STATUS !
        DUP RTE-S-OK = OVER RTE-S-WOULD-BLOCK = OR IF
            2DROP SCB-S-OK -1 0 EXIT
        THEN
        RTE-S-SESSION-LOST = IF
            SCB-S-SESSION-LOST SWAP _RTHP-FAULT-RESULT EXIT
        THEN
    THEN
    SCB-S-INVALID SWAP _RTHP-FAULT-RESULT ;

VARIABLE _RTHP-Z-P
VARIABLE _RTHP-Z-ACCEPT
VARIABLE _RTHP-Z-RETRY
VARIABLE _RTHP-Z-OUTPUT

: _RTHP-Z-ABORT-START-TARGET  ( -- )
    _RTHP-Z-ACCEPT @ _RTHP-PH-READY-REVEAL = IF
        _RTHP-Z-P @ _RTHP-TARGET-ABORT
    THEN ;

: _RTHP-STEP-SEALED
  ( accepted-phase retry-phase output-after? producer -- scb-status more? output-needed? )
    _RTHP-Z-P ! _RTHP-Z-OUTPUT ! _RTHP-Z-RETRY ! _RTHP-Z-ACCEPT !
    _RTHP-Z-P @ _RTHP.FACADE @ RTE-UPDATE-STATE@
    _RTHP-S-STATUS ! _RTHP-S-STATE !
    _RTHP-S-STATUS @ RTE-S-SESSION-LOST = IF
        _RTHP-Z-ABORT-START-TARGET
        SCB-S-SESSION-LOST _RTHP-Z-P @ _RTHP-FAULT-RESULT EXIT
    THEN
    _RTHP-S-STATE @ RTE-UPDATE-SEALED = IF SCB-S-OK 0 -1 EXIT THEN
    _RTHP-S-STATE @ RTE-UPDATE-PUBLISHING =
    _RTHP-S-STATE @ RTE-UPDATE-AWAITING = OR IF
        SCB-S-OK -1 0 EXIT
    THEN
    _RTHP-S-STATE @ RTE-UPDATE-IDLE =
    _RTHP-S-STATUS @ RTE-S-OK = AND IF
        _RTHP-Z-ACCEPT @ _RTHP-PH-READY-REVEAL = IF
            _RTHP-Z-P @ _RTHP-ADVANCE-IDS? 0= IF
                _RTHP-Z-P @ _RTHP-TARGET-ABORT
                SCB-S-INVALID _RTHP-Z-P @ _RTHP-FAULT-RESULT EXIT
            THEN
        THEN
        _RTHP-Z-ACCEPT @ _RTHP-Z-P @ _RTHP.PHASE !
        _RTHP-Z-ACCEPT @ _RTHP-PH-LIVE = IF
            _RTHP-Z-P @ _RTHP-TARGET-PUBLISH? 0= IF
                SCB-S-INVALID _RTHP-Z-P @ _RTHP-FAULT-RESULT EXIT
            THEN
        THEN
        _RTHP-Z-OUTPUT @ IF SCB-S-OK 0 -1 ELSE SCB-S-OK 0 0 THEN
        EXIT
    THEN
    _RTHP-S-STATE @ RTE-UPDATE-IDLE =
    _RTHP-S-STATUS @ RTE-S-STALE = AND IF
        _RTHP-Z-P @ _RTHP.FACADE @ RTE-RETAINED-CANCEL
        DUP RTE-S-SESSION-LOST = IF
            _RTHP-Z-ABORT-START-TARGET
            DROP SCB-S-SESSION-LOST _RTHP-Z-P @ _RTHP-FAULT-RESULT EXIT
        THEN
        RTE-S-OK <> IF
            _RTHP-Z-ABORT-START-TARGET
            SCB-S-INVALID _RTHP-Z-P @ _RTHP-FAULT-RESULT EXIT
        THEN
        _RTHP-Z-ABORT-START-TARGET
        _RTHP-Z-RETRY @ _RTHP-Z-P @ _RTHP.PHASE !
        SCB-S-OK 0 -1 EXIT
    THEN
    _RTHP-Z-ABORT-START-TARGET
    SCB-S-INVALID _RTHP-Z-P @ _RTHP-FAULT-RESULT ;

: RTHP-STEP
  ( cols rows generation budget producer -- scb-status more? output-needed? )
    _RTHP-S-P ! DROP _RTHP-S-GEN ! _RTHP-S-ROWS ! _RTHP-S-COLS !
    _RTHP-S-P @ RTHP-VALID? 0= IF SCB-S-INVALID 0 0 EXIT THEN
    _RTHP-S-COLS @ _RTHP-S-ROWS @ _RTHP-S-GEN @ _RTHP-S-P @
        _RTHP-CALL-SURFACE? 0= IF
        SCB-S-INVALID _RTHP-S-P @ _RTHP-FAULT-RESULT EXIT
    THEN
    _RTHP-S-P @ _RTHP.PHASE @ _RTHP-PH-FAULT = IF
        _RTHP-S-P @ _RTHP.FAULT @ 0 0 EXIT
    THEN
    _RTHP-S-P @ _RTHP.PHASE @ _RTHP-PH-WAIT = IF
        _RTHP-S-COLS @ _RTHP-S-P @ _RTHP.COLS !
        _RTHP-S-ROWS @ _RTHP-S-P @ _RTHP.ROWS !
        _RTHP-S-GEN @ _RTHP-S-P @ _RTHP.PHYSICAL-GEN !
        _RTHP-S-P @ _RTHP-TRY-CANDIDATE
        IF
            DUP SCB-S-OK = IF DROP SCB-S-OK -1 0 EXIT THEN
            _RTHP-S-P @ _RTHP-FAULT-RESULT EXIT
        THEN
        DUP SCB-S-OK = IF DROP SCB-S-OK 0 0 EXIT THEN
        _RTHP-S-P @ _RTHP-FAULT-RESULT EXIT
    THEN
    _RTHP-S-P @ _RTHP.PHASE @ _RTHP-PH-OPENING = IF
        _RTHP-S-P @ _RTHP-STEP-OPENING EXIT
    THEN
    _RTHP-S-P @ _RTHP.PHASE @ _RTHP-PH-READY-START = IF
        SCB-S-OK 0 -1 EXIT
    THEN
    _RTHP-S-P @ _RTHP.PHASE @ _RTHP-PH-START-SEALED = IF
        _RTHP-PH-READY-REVEAL _RTHP-PH-READY-START -1 _RTHP-S-P @
        _RTHP-STEP-SEALED EXIT
    THEN
    _RTHP-S-P @ _RTHP.PHASE @ _RTHP-PH-READY-REVEAL = IF
        SCB-S-OK 0 -1 EXIT
    THEN
    _RTHP-S-P @ _RTHP.PHASE @ _RTHP-PH-REVEAL-SEALED = IF
        _RTHP-PH-LIVE _RTHP-PH-READY-REVEAL 0 _RTHP-S-P @
        _RTHP-STEP-SEALED EXIT
    THEN
    _RTHP-S-P @ _RTHP.PHASE @ DUP _RTHP-PH-LIVE =
    SWAP _RTHP-PH-DISABLED = OR IF SCB-S-OK 0 0 EXIT THEN
    SCB-S-INVALID _RTHP-S-P @ _RTHP-FAULT-RESULT ;

\ =====================================================================
\  Final mutation-safe emission and PREPARE
\ =====================================================================

VARIABLE _RTHP-X-P

: _RTHP-FIXED-BODY?  ( -- flag )
    _RTHP-X-P @ _RTHP.REGION @
        _RTHP-X-P @ _RTHP.NEXT-REGION @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.FIRST-OBJECT @
        _RTHP-X-P @ _RTHP.NEXT-OBJECT @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.OWNER @
        _RTHP-X-P @ _RTHP.OWNER @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.GENERATION @
        _RTHP-X-P @ _RTHP.OWNER-GEN @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.SURFACE-COLS @
        _RTHP-X-P @ _RTHP.COLS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.SURFACE-ROWS @
        _RTHP-X-P @ _RTHP.ROWS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.REGION-ID @
        _RTHP-X-P @ _RTHP.REGION @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.REGION-X @ 0<> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.REGION-Y @ 0<> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.REGION-COLS @
        _RTHP-X-P @ _RTHP.COLS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.REGION-ROWS @
        _RTHP-X-P @ _RTHP.ROWS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.REGION-Z @ 0<> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.REGION-FLAGS @ 3 <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.CONTROL-COUNT @
        _RTHP-X-P @ _RTHP.CONTROL-COUNT @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.GLYPH-COUNT @
        _RTHP-X-P @ _RTHP.GLYPH-COUNT @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.ADMISSION _RTE-HA.RESERVED @ 0<> IF 0 EXIT THEN

    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.OWNER @
        _RTHP-X-P @ _RTHP.OWNER @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.GENERATION @
        _RTHP-X-P @ _RTHP.OWNER-GEN @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.SURFACE-COLS @
        _RTHP-X-P @ _RTHP.COLS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.SURFACE-ROWS @
        _RTHP-X-P @ _RTHP.ROWS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.REGION-ID @
        _RTHP-X-P @ _RTHP.REGION @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.REGION-X @ 0<> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.REGION-Y @ 0<> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.REGION-COLS @
        _RTHP-X-P @ _RTHP.COLS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.REGION-ROWS @
        _RTHP-X-P @ _RTHP.ROWS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.REGION-Z @ 0<> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.REGION-FLAGS @ 3 <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.ITEMS-A @
        _RTHP-X-P @ _RTHP.CONTROLS-A @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.ITEMS-U @
        _RTHP-X-P @ _RTHP.CONTROL-COUNT @ RTE-CONTROL-SIZE * <>
        IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.CONTROL-PLAN _RTE-CP.RESERVED @ 0<> IF 0 EXIT THEN

    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.ATTEMPT @
        _RTHP-X-P @ _RTHP.ATTEMPT @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.SOURCE-GENERATION @
        _RTHP-X-P @ _RTHP.SOURCE-GEN @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.SURFACE-GENERATION @
        _RTHP-X-P @ _RTHP.SURFACE-GEN @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.CONTROL-PLAN @
        _RTHP-X-P @ _RTHP.CONTROL-PLAN <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.CONTROL-TEXT-A @
        _RTHP-X-P @ _RTHP.SOURCE-TEXT-A @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.CONTROL-TEXT-U @
        _RTHP-X-P @ _RTHP.SOURCE-TEXT-USED @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.RESERVED @ 0<> IF 0 EXIT THEN

    _RTHP-X-P @ _RTHP.GLYPH-COUNT @ 0= IF
        _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.GLYPH-PLAN @ 0=
        _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.GLYPH-REFS-A @ 0= AND
        _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.GLYPH-REFS-U @ 0= AND
        _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.GLYPH-TEXT-A @ 0= AND
        _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.GLYPH-TEXT-U @ 0= AND EXIT
    THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.OWNER @
        _RTHP-X-P @ _RTHP.OWNER @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.GENERATION @
        _RTHP-X-P @ _RTHP.OWNER-GEN @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.SURFACE-COLS @
        _RTHP-X-P @ _RTHP.COLS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.SURFACE-ROWS @
        _RTHP-X-P @ _RTHP.ROWS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.REGION-ID @
        _RTHP-X-P @ _RTHP.REGION @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.REGION-X @ 0<> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.REGION-Y @ 0<> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.REGION-COLS @
        _RTHP-X-P @ _RTHP.COLS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.REGION-ROWS @
        _RTHP-X-P @ _RTHP.ROWS @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.REGION-Z @ 0<> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.REGION-FLAGS @ 3 <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.ITEMS-A @
        _RTHP-X-P @ _RTHP.GLYPH-ITEMS-A @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.ITEMS-U @
        _RTHP-X-P @ _RTHP.GLYPH-COUNT @ RTE-GLYPH-RUN-PLAN-ITEM-SIZE * <>
        IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.GLYPH-PLAN _RTE-LP.RESERVED @ 0<> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.GLYPH-PLAN @
        _RTHP-X-P @ _RTHP.GLYPH-PLAN <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.GLYPH-REFS-A @
        _RTHP-X-P @ _RTHP.GLYPH-REFS-A @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.GLYPH-REFS-U @
        _RTHP-X-P @ _RTHP.GLYPH-COUNT @ RGRP-TEXT-REF-SIZE * <>
        IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.GLYPH-TEXT-A @
        _RTHP-X-P @ _RTHP.GLYPH-TEXT-A @ <> IF 0 EXIT THEN
    _RTHP-X-P @ _RTHP.HYBRID _RTE-HP.GLYPH-TEXT-U @
        _RTHP-X-P @ _RTHP.GLYPH-TEXT-USED @ = ;

: _RTHP-FIXED?  ( producer -- flag )
    _RTHP-X-P ! _RTHP-FIXED-BODY? 0 _RTHP-X-P ! ;

VARIABLE _RTHP-E-P
VARIABLE _RTHP-E-ITEM
VARIABLE _RTHP-E-REF
VARIABLE _RTHP-E-TEXT
VARIABLE _RTHP-E-ALIGNED
VARIABLE _RTHP-E-MAX
VARIABLE _RTHP-E-LAST
VARIABLE _RTHP-E-NEXT
VARIABLE _RTHP-TW-A
VARIABLE _RTHP-TW-U
VARIABLE _RTHP-TW-BASE
VARIABLE _RTHP-TW-TOTAL

: _RTHP-TEXT-WITHIN?  ( a u base total -- flag )
    _RTHP-TW-TOTAL ! _RTHP-TW-BASE ! _RTHP-TW-U ! _RTHP-TW-A !
    _RTHP-TW-U @ 0= IF -1 EXIT THEN
    _RTHP-TW-A @ _RTHP-TW-U @ MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _RTHP-TW-BASE @ _RTHP-TW-TOTAL @ MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _RTHP-TW-A @ _RTHP-TW-BASE @ U< IF 0 EXIT THEN
    _RTHP-TW-A @ _RTHP-TW-U @ +
    _RTHP-TW-BASE @ _RTHP-TW-TOTAL @ + U> 0= ;

: _RTHP-E-ADD-TEXT?  ( bytes -- flag )
    _RTHP-E-NEXT !
    _RTHP-E-TEXT @ _RTHP-E-NEXT @ _RTHP-U32+?
        0= IF DROP 0 EXIT THEN _RTHP-E-TEXT !
    _RTHP-E-NEXT @ _RTHP-ALIGN8? 0= IF DROP 0 EXIT THEN
    _RTHP-E-ALIGNED @ SWAP _RTHP-U32+?
        0= IF DROP 0 EXIT THEN _RTHP-E-ALIGNED !
    _RTHP-E-MAX @ _RTHP-E-NEXT @ MAX _RTHP-E-MAX ! -1 ;

: _RTHP-EMIT-CONTROLS  ( producer -- rte-status )
    _RTHP-E-P !
    0 _RTHP-E-TEXT ! 0 _RTHP-E-ALIGNED ! 0 _RTHP-E-MAX !
    0 _RTHP-E-LAST !
    _RTHP-E-P @ _RTHP.CONTROL-COUNT @ 0 ?DO
        _RTHP-E-P @ _RTHP.CONTROLS-A @ I RTE-CONTROL-SIZE * +
            DUP _RTHP-E-ITEM !
        DUP _RTE-CONTROL.LABEL-A @ OVER _RTE-CONTROL.LABEL-U @
        _RTHP-E-P @ _RTHP.SOURCE-TEXT-A @
        _RTHP-E-P @ _RTHP.SOURCE-TEXT-USED @ _RTHP-TEXT-WITHIN?
            0= IF DROP RTE-S-INVALID UNLOOP EXIT THEN
        DUP _RTE-CONTROL.SHORTCUT-A @ OVER _RTE-CONTROL.SHORTCUT-U @
        _RTHP-E-P @ _RTHP.SOURCE-TEXT-A @
        _RTHP-E-P @ _RTHP.SOURCE-TEXT-USED @ _RTHP-TEXT-WITHIN?
            0= IF DROP RTE-S-INVALID UNLOOP EXIT THEN
        DUP _RTE-CONTROL.LABEL-U @ OVER _RTE-CONTROL.SHORTCUT-U @
            _RTHP-U32+? 0= IF 2DROP RTE-S-INVALID UNLOOP EXIT THEN
            _RTHP-E-ADD-TEXT? 0= IF DROP RTE-S-INVALID UNLOOP EXIT THEN
        DUP _RTE-CONTROL.ID @ DUP _RTHP-E-LAST @ U> 0= IF
            2DROP RTE-S-INVALID UNLOOP EXIT
        THEN _RTHP-E-LAST !
        _RTHP-E-P @ _RTHP.FACADE @ RTE-CONTROL-DEFINE
        DUP RTE-S-OK <> IF UNLOOP EXIT THEN DROP
    LOOP
    _RTHP-E-TEXT @ _RTHP-E-P @ _RTHP.ADMISSION _RTE-HA.CONTROL-TEXT @ =
    _RTHP-E-ALIGNED @ _RTHP-E-P @ _RTHP.ADMISSION
        _RTE-HA.CONTROL-ALIGNED @ = AND
    _RTHP-E-MAX @ _RTHP-E-P @ _RTHP.ADMISSION _RTE-HA.CONTROL-MAX @ = AND
    _RTHP-E-LAST @ _RTHP-E-P @ _RTHP.ADMISSION _RTE-HA.CONTROL-LAST @ = AND
    IF RTE-S-OK ELSE RTE-S-INVALID THEN ;

: _RTHP-GLYPH-RUN!  ( item ref producer -- flag )
    _RTHP-E-P ! _RTHP-E-REF ! _RTHP-E-ITEM !
    _RTHP-E-REF @ RGRP-TEXT-REF-OFFSET@
        _RTHP-E-TEXT @ <> IF 0 EXIT THEN
    _RTHP-E-REF @ RGRP-TEXT-REF-LENGTH@ DUP _RTHP-E-NEXT !
        _RTHP-E-ITEM @ _RTE-LPI.TEXT-CAPACITY @ <> IF 0 EXIT THEN
    _RTHP-E-TEXT @ _RTHP-E-P @ _RTHP.GLYPH-TEXT-USED @ U> IF 0 EXIT THEN
    _RTHP-E-NEXT @ _RTHP-E-P @ _RTHP.GLYPH-TEXT-USED @
        _RTHP-E-TEXT @ - U> IF 0 EXIT THEN
    _RTHP-E-P @ _RTHP.RUN DUP RTE-GLYPH-RUN-SIZE 0 FILL
    _RTHP-E-P @ _RTHP.OWNER @ OVER _RTE-GLYPH-RUN.OWNER !
    _RTHP-E-P @ _RTHP.OWNER-GEN @ OVER _RTE-GLYPH-RUN.GENERATION !
    _RTHP-E-ITEM @ _RTE-LPI.OBJECT @ OVER _RTE-GLYPH-RUN.OBJECT !
    _RTHP-E-P @ _RTHP.REGION @ OVER _RTE-GLYPH-RUN.REGION !
    _RTHP-E-ITEM @ 8 + OVER 32 + 96 MOVE
    _RTHP-E-P @ _RTHP.GLYPH-TEXT-A @ _RTHP-E-TEXT @ +
        OVER _RTE-GLYPH-RUN.TEXT-A !
    _RTHP-E-REF @ RGRP-TEXT-REF-LENGTH@
        SWAP _RTE-GLYPH-RUN.TEXT-U !
    -1 ;

: _RTHP-EMIT-GLYPHS  ( producer -- rte-status )
    _RTHP-E-P !
    0 _RTHP-E-TEXT ! 0 _RTHP-E-ALIGNED ! 0 _RTHP-E-MAX !
    0 _RTHP-E-LAST !
    _RTHP-E-P @ _RTHP.GLYPH-COUNT @ 0 ?DO
        _RTHP-E-P @ _RTHP.GLYPH-ITEMS-A @
            I RTE-GLYPH-RUN-PLAN-ITEM-SIZE * + _RTHP-E-ITEM !
        _RTHP-E-P @ _RTHP.GLYPH-REFS-A @
            I RGRP-TEXT-REF-SIZE * + _RTHP-E-REF !
        _RTHP-E-ITEM @ _RTHP-E-REF @ _RTHP-E-P @
            _RTHP-GLYPH-RUN! 0= IF RTE-S-INVALID UNLOOP EXIT THEN
        _RTHP-E-REF @ RGRP-TEXT-REF-LENGTH@
            _RTHP-E-ADD-TEXT? 0= IF RTE-S-INVALID UNLOOP EXIT THEN
        _RTHP-E-ITEM @ _RTE-LPI.OBJECT @ DUP _RTHP-E-LAST @ U> 0= IF
            DROP RTE-S-INVALID UNLOOP EXIT
        THEN _RTHP-E-LAST !
        _RTHP-E-P @ _RTHP.RUN _RTHP-E-P @ _RTHP.FACADE @
            RTE-GLYPH-RUN-DEFINE DUP RTE-S-OK <> IF UNLOOP EXIT THEN DROP
    LOOP
    _RTHP-E-TEXT @ _RTHP-E-P @ _RTHP.GLYPH-TEXT-USED @ =
    _RTHP-E-TEXT @ _RTHP-E-P @ _RTHP.ADMISSION _RTE-HA.GLYPH-TEXT @ = AND
    _RTHP-E-ALIGNED @ _RTHP-E-P @ _RTHP.ADMISSION
        _RTE-HA.GLYPH-ALIGNED @ = AND
    _RTHP-E-MAX @ _RTHP-E-P @ _RTHP.ADMISSION _RTE-HA.GLYPH-MAX @ = AND
    _RTHP-E-LAST @ _RTHP-E-P @ _RTHP.ADMISSION _RTE-HA.GLYPH-LAST @ = AND
    IF RTE-S-OK ELSE RTE-S-INVALID THEN ;

VARIABLE _RTHP-P-P
VARIABLE _RTHP-P-COLS
VARIABLE _RTHP-P-ROWS
VARIABLE _RTHP-P-GEN
VARIABLE _RTHP-P-STATUS
VARIABLE _RTHP-P-STATE

: _RTHP-CAPTURE-SLOT  ( producer -- scb-status )
    DUP _RTHP.FACADE @ RTE-UPDATE-STATE@
    _RTHP-P-STATUS ! _RTHP-P-STATE !
    _RTHP-P-STATUS @ RTE-S-SESSION-LOST = IF
        DROP SCB-S-SESSION-LOST EXIT
    THEN
    _RTHP-P-STATE @ RTE-UPDATE-IDLE = IF
        _RTHP-P-STATUS @ RTE-S-OK = IF DROP SCB-S-OK ELSE DROP SCB-S-INVALID THEN
        EXIT
    THEN
    _RTHP-P-STATE @ RTE-UPDATE-CAPTURING =
    _RTHP-P-STATE @ RTE-UPDATE-SEALED = OR IF
        _RTHP.FACADE @ RTE-RETAINED-CANCEL _RTHP-RTE>SCB EXIT
    THEN
    DROP SCB-S-WOULD-BLOCK ;

: _RTHP-CANCEL-STATUS  ( rte-status producer -- scb-status )
    SWAP _RTHP-P-STATUS !
    DUP _RTHP.FACADE @ RTE-RETAINED-CANCEL
    DUP RTE-S-SESSION-LOST = IF 2DROP SCB-S-SESSION-LOST EXIT THEN
    RTE-S-OK <> IF DROP SCB-S-INVALID EXIT THEN
    DROP _RTHP-P-STATUS @ _RTHP-RTE>SCB ;

: _RTHP-PREPARE-START  ( producer -- scb-status )
    _RTHP-P-P !
    _RTHP-P-P @ _RTHP-TARGET-ABORT
    _RTHP-P-P @ _RTHP-CAPTURE-SLOT DUP SCB-S-OK <> IF EXIT THEN DROP
    _RTHP-P-P @ _RTHP-FIXED? 0= IF SCB-S-INVALID EXIT THEN
    _RTHP-P-P @ _RTHP-TARGET-CANDIDATE? 0= IF SCB-S-INVALID EXIT THEN
    RTE-RETAINED-REPLACE-START _RTHP-P-P @ _RTHP.FACADE @
        RTE-RETAINED-BEGIN DUP RTE-S-OK <> IF
        _RTHP-P-P @ _RTHP-TARGET-ABORT
        _RTHP-P-P @ _RTHP-CANCEL-STATUS EXIT
    THEN DROP
    _RTHP-P-P @ _RTHP.OWNER @ _RTHP-P-P @ _RTHP.OWNER-GEN @
    _RTHP-P-P @ _RTHP.REGION @ 0 0
    _RTHP-P-P @ _RTHP.COLS @ _RTHP-P-P @ _RTHP.ROWS @ 0 3
    _RTHP-P-P @ _RTHP.FACADE @ RTE-REGION-DEFINE
    DUP RTE-S-OK <> IF
        _RTHP-P-P @ _RTHP-TARGET-ABORT
        _RTHP-P-P @ _RTHP-CANCEL-STATUS EXIT
    THEN DROP
    _RTHP-P-P @ _RTHP-EMIT-CONTROLS
    DUP RTE-S-OK <> IF
        _RTHP-P-P @ _RTHP-TARGET-ABORT
        _RTHP-P-P @ _RTHP-CANCEL-STATUS EXIT
    THEN DROP
    _RTHP-P-P @ _RTHP-EMIT-GLYPHS
    DUP RTE-S-OK <> IF
        _RTHP-P-P @ _RTHP-TARGET-ABORT
        _RTHP-P-P @ _RTHP-CANCEL-STATUS EXIT
    THEN DROP
    RTE-COMMIT _RTHP-P-P @ _RTHP.FACADE @ RTE-RETAINED-SEAL
    DUP RTE-S-OK <> IF
        _RTHP-P-P @ _RTHP-TARGET-ABORT
        _RTHP-P-P @ _RTHP-CANCEL-STATUS EXIT
    THEN DROP
    _RTHP-PH-START-SEALED _RTHP-P-P @ _RTHP.PHASE ! SCB-S-OK ;

: _RTHP-PREPARE-REVEAL  ( producer -- scb-status )
    DUP _RTHP-P-P ! _RTHP-CAPTURE-SLOT DUP SCB-S-OK <> IF EXIT THEN DROP
    RTE-RETAINED-REPLACE-CONTINUE _RTHP-P-P @ _RTHP.FACADE @
        RTE-RETAINED-BEGIN DUP RTE-S-OK <> IF
        _RTHP-P-P @ _RTHP-CANCEL-STATUS EXIT
    THEN DROP
    RTE-COMMIT-AND-REVEAL _RTHP-P-P @ _RTHP.FACADE @ RTE-RETAINED-SEAL
    DUP RTE-S-OK <> IF _RTHP-P-P @ _RTHP-CANCEL-STATUS EXIT THEN DROP
    _RTHP-PH-REVEAL-SEALED _RTHP-P-P @ _RTHP.PHASE ! SCB-S-OK ;

: RTHP-PREPARE  ( cols rows generation producer -- scb-status )
    _RTHP-P-P ! _RTHP-P-GEN ! _RTHP-P-ROWS ! _RTHP-P-COLS !
    _RTHP-P-P @ RTHP-VALID? 0= IF SCB-S-INVALID EXIT THEN
    _RTHP-P-COLS @ _RTHP-P-ROWS @ _RTHP-P-GEN @ _RTHP-P-P @
        _RTHP-CALL-SURFACE? 0= IF SCB-S-INVALID EXIT THEN
    _RTHP-P-P @ _RTHP.PHASE @ _RTHP-PH-FAULT = IF
        _RTHP-P-P @ _RTHP.FAULT @ EXIT
    THEN
    _RTHP-P-P @ _RTHP.PHASE @ _RTHP-PH-READY-START = IF
        _RTHP-P-P @ _RTHP-PREPARE-START EXIT
    THEN
    _RTHP-P-P @ _RTHP.PHASE @ _RTHP-PH-START-SEALED = IF
        SCB-S-OK EXIT
    THEN
    _RTHP-P-P @ _RTHP.PHASE @ _RTHP-PH-READY-REVEAL = IF
        _RTHP-P-P @ _RTHP-PREPARE-REVEAL EXIT
    THEN
    _RTHP-P-P @ _RTHP.PHASE @ _RTHP-PH-REVEAL-SEALED = IF
        SCB-S-OK EXIT
    THEN
    SCB-S-OK ;
