\ =====================================================================
\  screen-adapter-apt1.f — RTAPT publisher for the neutral APT screen ABI
\ =====================================================================
\
\  This is the only bridge between the generic APTSCBP callback descriptor
\  and the generic RTAPT engine.  It owns no session, engine, or capacity;
\  every range is caller-provided and borrowed for the binding lifetime.
\
\  Prefix: RTAPTSCB- (public), _RTAPTSCB- (internal)

PROVIDED akashic-tui-rtaptscb1

REQUIRE ../screen-backend-apt1.f
REQUIRE apt1-engine.f

APTSCB-PUBLISHER-SIZE CONSTANT _RTAPTSCB-O-ENGINE
APTSCB-PUBLISHER-SIZE 8 + CONSTANT _RTAPTSCB-O-MAGIC
APTSCB-PUBLISHER-SIZE 16 + CONSTANT _RTAPTSCB-O-PRODUCER-CONTEXT
APTSCB-PUBLISHER-SIZE 24 + CONSTANT _RTAPTSCB-O-PRODUCER-U
APTSCB-PUBLISHER-SIZE 32 + CONSTANT _RTAPTSCB-O-PRODUCER-BUDGET
APTSCB-PUBLISHER-SIZE 40 + CONSTANT _RTAPTSCB-O-PRODUCER-STEP-XT
APTSCB-PUBLISHER-SIZE 48 + CONSTANT _RTAPTSCB-O-PRODUCER-PREPARE-XT
APTSCB-PUBLISHER-SIZE 56 + CONSTANT _RTAPTSCB-O-ADAPTER
APTSCB-PUBLISHER-SIZE 64 + CONSTANT _RTAPTSCB-O-SURFACE-COLS
APTSCB-PUBLISHER-SIZE 72 + CONSTANT _RTAPTSCB-O-SURFACE-ROWS
APTSCB-PUBLISHER-SIZE 80 + CONSTANT _RTAPTSCB-O-SURFACE-GENERATION
APTSCB-PUBLISHER-SIZE 88 + CONSTANT _RTAPTSCB-O-MORE-WORK
APTSCB-PUBLISHER-SIZE 96 + CONSTANT _RTAPTSCB-O-OUTPUT-NEEDED
APTSCB-PUBLISHER-SIZE 104 + CONSTANT RTAPTSCB-SIZE

HEX 5254415054534342 CONSTANT _RTAPTSCB-MAGIC DECIMAL

: RTAPTSCB.ENGINE  ( publisher -- field ) _RTAPTSCB-O-ENGINE + ;
: _RTAPTSCB.MAGIC  ( publisher -- field ) _RTAPTSCB-O-MAGIC + ;
: _RTAPTSCB.PRODUCER-CONTEXT  ( publisher -- field )
    _RTAPTSCB-O-PRODUCER-CONTEXT + ;
: _RTAPTSCB.PRODUCER-U  ( publisher -- field )
    _RTAPTSCB-O-PRODUCER-U + ;
: _RTAPTSCB.PRODUCER-BUDGET  ( publisher -- field )
    _RTAPTSCB-O-PRODUCER-BUDGET + ;
: _RTAPTSCB.PRODUCER-STEP-XT  ( publisher -- field )
    _RTAPTSCB-O-PRODUCER-STEP-XT + ;
: _RTAPTSCB.PRODUCER-PREPARE-XT  ( publisher -- field )
    _RTAPTSCB-O-PRODUCER-PREPARE-XT + ;
: _RTAPTSCB.ADAPTER  ( publisher -- field ) _RTAPTSCB-O-ADAPTER + ;
: _RTAPTSCB.SURFACE-COLS  ( publisher -- field )
    _RTAPTSCB-O-SURFACE-COLS + ;
: _RTAPTSCB.SURFACE-ROWS  ( publisher -- field )
    _RTAPTSCB-O-SURFACE-ROWS + ;
: _RTAPTSCB.SURFACE-GENERATION  ( publisher -- field )
    _RTAPTSCB-O-SURFACE-GENERATION + ;
: _RTAPTSCB.MORE-WORK  ( publisher -- field )
    _RTAPTSCB-O-MORE-WORK + ;
: _RTAPTSCB.OUTPUT-NEEDED  ( publisher -- field )
    _RTAPTSCB-O-OUTPUT-NEEDED + ;

VARIABLE _RTAPTSCB-R
VARIABLE _RTAPTSCB-E
VARIABLE _RTAPTSCB-STATUS
VARIABLE _RTAPTSCB-PENDING
VARIABLE _RTAPTSCB-V0
VARIABLE _RTAPTSCB-V1
VARIABLE _RTAPTSCB-V2
VARIABLE _RTAPTSCB-V3
VARIABLE _RTAPTSCB-V4
VARIABLE _RTAPTSCB-VALID-PUBLISHER
VARIABLE _RTAPTSCB-VALID-ADAPTER
VARIABLE _RTAPTSCB-VALID-CONTEXT
VARIABLE _RTAPTSCB-VALID-CONTEXT-U

: _RTAPTSCB-BOOL?  ( value -- flag )
    DUP 0= SWAP -1 = OR ;

: _RTAPTSCB-SCB-STATUS?  ( status -- flag )
    SCB-S-INVALID U> 0= ;

: _RTAPTSCB-SPAN?  ( a u -- flag )
    OVER 0<> OVER 0> AND 0= IF 2DROP 0 EXIT THEN
    OVER 7 AND IF 2DROP 0 EXIT THEN
    MSPAN-NONWRAPPING? ;

: _RTAPTSCB-DIMENSION?  ( value -- flag )
    DUP 0> SWAP 0xFFFFFFFF U> 0= AND ;

: _RTAPTSCB-SURFACE-VALID?  ( publisher -- flag )
    DUP _RTAPTSCB.SURFACE-GENERATION @ 0= IF
        DUP _RTAPTSCB.SURFACE-COLS @ 0=
        OVER _RTAPTSCB.SURFACE-ROWS @ 0= AND
        SWAP DROP EXIT
    THEN
    DUP _RTAPTSCB.SURFACE-COLS @ _RTAPTSCB-DIMENSION?
    OVER _RTAPTSCB.SURFACE-ROWS @ _RTAPTSCB-DIMENSION? AND
    SWAP DROP ;

: _RTAPTSCB-ADAPTER-VALID?  ( publisher -- flag )
    DUP _RTAPTSCB-VALID-PUBLISHER !
    _RTAPTSCB.ADAPTER @ DUP _RTAPTSCB-VALID-ADAPTER !
    0= IF -1 EXIT THEN
    _RTAPTSCB-VALID-ADAPTER @ APTSCB-VALID? 0= IF 0 EXIT THEN
    _RTAPTSCB-VALID-ADAPTER @ APTSCB-SESSION@
        _RTAPTSCB-VALID-PUBLISHER @ APTSCBP.SESSION @ <> IF 0 EXIT THEN
    _RTAPTSCB-VALID-ADAPTER @ APTSCB.PUBLISHER @
        _RTAPTSCB-VALID-PUBLISHER @ <> IF 0 EXIT THEN
    _RTAPTSCB-VALID-PUBLISHER @ RTAPTSCB-SIZE
        _RTAPTSCB-VALID-ADAPTER @ APTSCB-SIZE MSPAN-OVERLAP? IF
        0 EXIT
    THEN
    _RTAPTSCB-VALID-ADAPTER @ APTSCB-SIZE
        _RTAPTSCB-VALID-PUBLISHER @ RTAPTSCB.ENGINE @
        RTAPT-STORAGE-DISJOINT? ;

: _RTAPTSCB-PRODUCER-VALID?  ( publisher -- flag )
    DUP _RTAPTSCB-VALID-PUBLISHER !
    DUP _RTAPTSCB.PRODUCER-CONTEXT @ _RTAPTSCB-VALID-CONTEXT !
    _RTAPTSCB.PRODUCER-U @ _RTAPTSCB-VALID-CONTEXT-U !
    _RTAPTSCB-VALID-CONTEXT @ 0= IF
        _RTAPTSCB-VALID-CONTEXT-U @ 0=
        _RTAPTSCB-VALID-PUBLISHER @ _RTAPTSCB.PRODUCER-BUDGET @ 0= AND
        _RTAPTSCB-VALID-PUBLISHER @ _RTAPTSCB.PRODUCER-STEP-XT @ 0= AND
        _RTAPTSCB-VALID-PUBLISHER @
            _RTAPTSCB.PRODUCER-PREPARE-XT @ 0= AND
        _RTAPTSCB-VALID-PUBLISHER @ _RTAPTSCB.MORE-WORK @ 0= AND
        _RTAPTSCB-VALID-PUBLISHER @ _RTAPTSCB.OUTPUT-NEEDED @ 0= AND
        EXIT
    THEN
    _RTAPTSCB-VALID-CONTEXT @ _RTAPTSCB-VALID-CONTEXT-U @
        _RTAPTSCB-SPAN? 0= IF 0 EXIT THEN
    _RTAPTSCB-VALID-PUBLISHER @ _RTAPTSCB.PRODUCER-BUDGET @
        0> 0= IF 0 EXIT THEN
    _RTAPTSCB-VALID-PUBLISHER @ _RTAPTSCB.PRODUCER-STEP-XT @ 0=
    _RTAPTSCB-VALID-PUBLISHER @
        _RTAPTSCB.PRODUCER-PREPARE-XT @ 0= OR IF 0 EXIT THEN
    _RTAPTSCB-VALID-PUBLISHER @ _RTAPTSCB.MORE-WORK @
        _RTAPTSCB-BOOL? 0=
    _RTAPTSCB-VALID-PUBLISHER @ _RTAPTSCB.OUTPUT-NEEDED @
        _RTAPTSCB-BOOL? 0= OR IF 0 EXIT THEN
    _RTAPTSCB-VALID-CONTEXT @ _RTAPTSCB-VALID-CONTEXT-U @
        _RTAPTSCB-VALID-PUBLISHER @ RTAPTSCB-SIZE
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RTAPTSCB-VALID-CONTEXT @ _RTAPTSCB-VALID-CONTEXT-U @
        _RTAPTSCB-VALID-PUBLISHER @ RTAPTSCB.ENGINE @
        RTAPT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPTSCB-VALID-PUBLISHER @ _RTAPTSCB.ADAPTER @ ?DUP IF
        _RTAPTSCB-VALID-CONTEXT @ _RTAPTSCB-VALID-CONTEXT-U @ ROT
        APTSCB-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    THEN
    -1 ;

: RTAPTSCB-VALID?  ( publisher -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP RTAPTSCB-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    _RTAPTSCB-R !
    _RTAPTSCB-R @ APTSCB-PUBLISHER-VALID? 0= IF 0 EXIT THEN
    _RTAPTSCB-R @ APTSCBP.CONTEXT @ _RTAPTSCB-R @ <> IF 0 EXIT THEN
    _RTAPTSCB-R @ _RTAPTSCB.MAGIC @ _RTAPTSCB-MAGIC <> IF 0 EXIT THEN
    _RTAPTSCB-R @ RTAPTSCB.ENGINE @ DUP _RTAPTSCB-E !
        RTAPT-VALID? 0= IF 0 EXIT THEN
    _RTAPTSCB-R @ APTSCBP.SESSION @ _RTAPTSCB-E @
        RTAPT-USES-SESSION? 0= IF 0 EXIT THEN
    _RTAPTSCB-R @ RTAPTSCB-SIZE _RTAPTSCB-E @
        RTAPT-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RTAPTSCB-R @ _RTAPTSCB-SURFACE-VALID? 0= IF 0 EXIT THEN
    _RTAPTSCB-R @ _RTAPTSCB-ADAPTER-VALID? 0= IF 0 EXIT THEN
    _RTAPTSCB-R @ _RTAPTSCB-PRODUCER-VALID? ;

: _RTAPTSCB-MAP-STATUS  ( rtapt-status -- scb-status )
    DUP RTAPT-S-OK = IF DROP SCB-S-OK EXIT THEN
    DUP RTAPT-S-WOULD-BLOCK = IF DROP SCB-S-WOULD-BLOCK EXIT THEN
    DUP RTAPT-S-BUSY = IF DROP SCB-S-WOULD-BLOCK EXIT THEN
    DUP RTAPT-S-SESSION-LOST = IF DROP SCB-S-SESSION-LOST EXIT THEN
    DROP SCB-S-INVALID ;

: _RTAPTSCB-PRODUCER-BOUND?  ( publisher -- flag )
    _RTAPTSCB.PRODUCER-CONTEXT @ 0<> ;

: _RTAPTSCB-EXACT-SCREEN?  ( publisher -- flag )
    DUP _RTAPTSCB-VALID-PUBLISHER !
    _RTAPTSCB.ADAPTER @ DUP _RTAPTSCB-VALID-ADAPTER !
    0= IF 0 EXIT THEN
    _RTAPTSCB-VALID-ADAPTER @ APTSCB-VALID? 0= IF 0 EXIT THEN
    _RTAPTSCB-VALID-ADAPTER @ APTSCB.PUBLISHER @
        _RTAPTSCB-VALID-PUBLISHER @ =
    SCR-BACKEND@ _RTAPTSCB-VALID-ADAPTER @ = AND ;

VARIABLE _RTAPTSCB-SURFACE-PUBLISHER
VARIABLE _RTAPTSCB-SURFACE-COLS
VARIABLE _RTAPTSCB-SURFACE-ROWS
VARIABLE _RTAPTSCB-SURFACE-NEXT

\ Publish a surface revision from the exact dimensions offered by one CELL
\ BEGIN.  A refused later PREPARE or engine BEGIN does not make those observed
\ dimensions stale.  Generation exhaustion refuses before changing the tuple.
: _RTAPTSCB-SURFACE-OBSERVE  ( cols rows publisher -- status )
    _RTAPTSCB-SURFACE-PUBLISHER !
    _RTAPTSCB-SURFACE-ROWS ! _RTAPTSCB-SURFACE-COLS !
    _RTAPTSCB-SURFACE-COLS @ _RTAPTSCB-DIMENSION? 0= IF
        SCB-S-INVALID EXIT
    THEN
    _RTAPTSCB-SURFACE-ROWS @ _RTAPTSCB-DIMENSION? 0= IF
        SCB-S-INVALID EXIT
    THEN
    _RTAPTSCB-SURFACE-PUBLISHER @
        _RTAPTSCB.SURFACE-GENERATION @ 0= IF
        _RTAPTSCB-SURFACE-COLS @ _RTAPTSCB-SURFACE-PUBLISHER @
            _RTAPTSCB.SURFACE-COLS !
        _RTAPTSCB-SURFACE-ROWS @ _RTAPTSCB-SURFACE-PUBLISHER @
            _RTAPTSCB.SURFACE-ROWS !
        1 _RTAPTSCB-SURFACE-PUBLISHER @
            _RTAPTSCB.SURFACE-GENERATION !
        SCB-S-OK EXIT
    THEN
    _RTAPTSCB-SURFACE-COLS @ _RTAPTSCB-SURFACE-PUBLISHER @
        _RTAPTSCB.SURFACE-COLS @ =
    _RTAPTSCB-SURFACE-ROWS @ _RTAPTSCB-SURFACE-PUBLISHER @
        _RTAPTSCB.SURFACE-ROWS @ = AND IF SCB-S-OK EXIT THEN
    _RTAPTSCB-SURFACE-PUBLISHER @ _RTAPTSCB.SURFACE-GENERATION @
        1+ DUP 0= IF DROP SCB-S-INVALID EXIT THEN
    _RTAPTSCB-SURFACE-NEXT !
    _RTAPTSCB-SURFACE-COLS @ _RTAPTSCB-SURFACE-PUBLISHER @
        _RTAPTSCB.SURFACE-COLS !
    _RTAPTSCB-SURFACE-ROWS @ _RTAPTSCB-SURFACE-PUBLISHER @
        _RTAPTSCB.SURFACE-ROWS !
    _RTAPTSCB-SURFACE-NEXT @ _RTAPTSCB-SURFACE-PUBLISHER @
        _RTAPTSCB.SURFACE-GENERATION !
    SCB-S-OK ;

: _RTAPTSCB-PRODUCER-PREPARE  ( publisher -- status )
    DUP _RTAPTSCB-R !
    _RTAPTSCB-PRODUCER-BOUND? 0= IF SCB-S-OK EXIT THEN
    _RTAPTSCB-R @ _RTAPTSCB-EXACT-SCREEN? 0= IF
        SCB-S-INVALID EXIT
    THEN
    _RTAPTSCB-R @ _RTAPTSCB.SURFACE-COLS @
    _RTAPTSCB-R @ _RTAPTSCB.SURFACE-ROWS @
    _RTAPTSCB-R @ _RTAPTSCB.SURFACE-GENERATION @
    _RTAPTSCB-R @ _RTAPTSCB.PRODUCER-CONTEXT @
    _RTAPTSCB-R @ >R
    _RTAPTSCB-R @ _RTAPTSCB.PRODUCER-PREPARE-XT @ EXECUTE
    R> _RTAPTSCB-R !
    DUP _RTAPTSCB-SCB-STATUS? 0= IF DROP SCB-S-INVALID THEN ;

: _RTAPTSCB-BEGIN  ( cols rows spans cells cell-mode context -- status )
    _RTAPTSCB-R ! _RTAPTSCB-V4 ! _RTAPTSCB-V3 !
    _RTAPTSCB-V2 ! _RTAPTSCB-V1 ! _RTAPTSCB-V0 !
    _RTAPTSCB-R @ RTAPTSCB-VALID? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCB-R @ _RTAPTSCB-PRODUCER-BOUND? IF
        _RTAPTSCB-V0 @ _RTAPTSCB-V1 @ _RTAPTSCB-R @
            _RTAPTSCB-SURFACE-OBSERVE DUP SCB-S-OK <> IF EXIT THEN DROP
        _RTAPTSCB-R @ _RTAPTSCB-PRODUCER-PREPARE
            DUP SCB-S-OK <> IF EXIT THEN DROP
    THEN
    _RTAPTSCB-V0 @ _RTAPTSCB-V1 @ _RTAPTSCB-V2 @
    _RTAPTSCB-V3 @ _RTAPTSCB-V4 @
    _RTAPTSCB-R @ RTAPTSCB.ENGINE @ RTAPT-CELL-BEGIN
    _RTAPTSCB-MAP-STATUS DUP SCB-S-OK = IF
        \ BEGIN transfers retry authority to the persistent screen request.
        \ It remains set until SCR-FLUSH? accepts COMMIT, while an abort
        \ rewinds a sealed retained candidate.  The producer latch is no
        \ longer an additional owner of this admitted observation.
        0 _RTAPTSCB-R @ _RTAPTSCB.OUTPUT-NEEDED !
    THEN ;

: _RTAPTSCB-SPAN  ( row col count context -- status )
    _RTAPTSCB-R ! _RTAPTSCB-V2 ! _RTAPTSCB-V1 ! _RTAPTSCB-V0 !
    _RTAPTSCB-R @ RTAPTSCB-VALID? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCB-V0 @ _RTAPTSCB-V1 @ _RTAPTSCB-V2 @
    _RTAPTSCB-R @ RTAPTSCB.ENGINE @ RTAPT-CELL-SPAN-BEGIN
    _RTAPTSCB-MAP-STATUS ;

: _RTAPTSCB-CELL  ( codepoint fg bg attrs context -- status )
    _RTAPTSCB-R ! _RTAPTSCB-V3 ! _RTAPTSCB-V2 !
    _RTAPTSCB-V1 ! _RTAPTSCB-V0 !
    _RTAPTSCB-R @ RTAPTSCB-VALID? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCB-V0 @ _RTAPTSCB-V1 @ _RTAPTSCB-V2 @ _RTAPTSCB-V3 @
    _RTAPTSCB-R @ RTAPTSCB.ENGINE @ RTAPT-CELL-WRITE
    _RTAPTSCB-MAP-STATUS ;

: _RTAPTSCB-CURSOR  ( row col visible context -- status )
    _RTAPTSCB-R ! _RTAPTSCB-V2 ! _RTAPTSCB-V1 ! _RTAPTSCB-V0 !
    _RTAPTSCB-R @ RTAPTSCB-VALID? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCB-V0 @ _RTAPTSCB-V1 @ _RTAPTSCB-V2 @
    _RTAPTSCB-R @ RTAPTSCB.ENGINE @ RTAPT-CELL-CURSOR
    _RTAPTSCB-MAP-STATUS ;

: _RTAPTSCB-COMMIT  ( context -- status )
    DUP RTAPTSCB-VALID? 0= IF DROP SCB-S-INVALID EXIT THEN
    RTAPTSCB.ENGINE @ RTAPT-CELL-COMMIT _RTAPTSCB-MAP-STATUS ;

: _RTAPTSCB-ABORT  ( reason context -- status )
    DUP RTAPTSCB-VALID? 0= IF 2DROP SCB-S-INVALID EXIT THEN
    RTAPTSCB.ENGINE @ RTAPT-CELL-ABORT _RTAPTSCB-MAP-STATUS ;

VARIABLE _RTAPTSCB-PRODUCER-STATUS
VARIABLE _RTAPTSCB-PRODUCER-MORE
VARIABLE _RTAPTSCB-PRODUCER-OUTPUT

: _RTAPTSCB-ENGINE-STEP  ( publisher -- status )
    _RTAPTSCB-R !
    _RTAPTSCB-R @ RTAPTSCB.ENGINE @ RTAPT-STEP _RTAPTSCB-STATUS !
    \ A rejected owner/output completion has already been reconciled and
    \ released the engine slot.  Let the producer observe that neutral state
    \ and decide whether to retire, coalesce, or retry it.
    _RTAPTSCB-STATUS @ RTAPT-S-REJECTED = IF SCB-S-OK EXIT THEN
    _RTAPTSCB-STATUS @ DUP RTAPT-S-WOULD-BLOCK =
    SWAP RTAPT-S-UNSUPPORTED = OR
    _RTAPTSCB-R @ APTSCBP.SESSION @ PT-RETAINED-AVAILABLE? 0= AND IF
        SCB-S-OK EXIT
    THEN
    _RTAPTSCB-STATUS @ _RTAPTSCB-MAP-STATUS ;

: _RTAPTSCB-PRODUCER-STEP  ( publisher -- status )
    DUP _RTAPTSCB-R !
    _RTAPTSCB-PRODUCER-BOUND? 0= IF SCB-S-OK EXIT THEN
    _RTAPTSCB-R @ _RTAPTSCB.SURFACE-GENERATION @ 0= IF
        SCB-S-OK EXIT
    THEN
    _RTAPTSCB-R @ _RTAPTSCB-EXACT-SCREEN? 0= IF
        SCB-S-INVALID EXIT
    THEN
    _RTAPTSCB-R @ _RTAPTSCB.SURFACE-COLS @
    _RTAPTSCB-R @ _RTAPTSCB.SURFACE-ROWS @
    _RTAPTSCB-R @ _RTAPTSCB.SURFACE-GENERATION @
    _RTAPTSCB-R @ _RTAPTSCB.PRODUCER-BUDGET @
    _RTAPTSCB-R @ _RTAPTSCB.PRODUCER-CONTEXT @
    _RTAPTSCB-R @ >R
    _RTAPTSCB-R @ _RTAPTSCB.PRODUCER-STEP-XT @ EXECUTE
    R> _RTAPTSCB-R !
    _RTAPTSCB-PRODUCER-OUTPUT !
    _RTAPTSCB-PRODUCER-MORE !
    _RTAPTSCB-PRODUCER-STATUS !
    _RTAPTSCB-PRODUCER-STATUS @ _RTAPTSCB-SCB-STATUS? 0= IF
        SCB-S-INVALID EXIT
    THEN
    _RTAPTSCB-PRODUCER-MORE @ _RTAPTSCB-BOOL? 0=
    _RTAPTSCB-PRODUCER-OUTPUT @ _RTAPTSCB-BOOL? 0= OR IF
        SCB-S-INVALID EXIT
    THEN
    \ A well-formed fatal result revokes all producer scheduling authority.
    \ OK and WOULD-BLOCK may both carry truthful level-triggered observations.
    _RTAPTSCB-PRODUCER-STATUS @ DUP SCB-S-SESSION-LOST =
    SWAP SCB-S-INVALID = OR IF
        0 _RTAPTSCB-R @ _RTAPTSCB.MORE-WORK !
        0 _RTAPTSCB-R @ _RTAPTSCB.OUTPUT-NEEDED !
        _RTAPTSCB-PRODUCER-STATUS @ EXIT
    THEN
    _RTAPTSCB-PRODUCER-MORE @
        _RTAPTSCB-R @ _RTAPTSCB.MORE-WORK !
    \ These are latest level-triggered observations, not sticky ownership.
    \ Once OUTPUT-NEEDED is scheduled, SCR-REQUEST-FLUSH persists through
    \ later false observations and every refusal until an accepted COMMIT.
    _RTAPTSCB-PRODUCER-OUTPUT @
        _RTAPTSCB-R @ _RTAPTSCB.OUTPUT-NEEDED !
    _RTAPTSCB-PRODUCER-STATUS @ ;

\ RTAPTSCB owns the producer-to-screen scheduling edge because only this
\ layer can re-prove that its attached adapter is the exact current backend.
\ MORE-WORK never enters this path and remains an outer scheduler hint.
: _RTAPTSCB-SCHEDULE-OUTPUT  ( publisher -- )
    DUP _RTAPTSCB-EXACT-SCREEN? 0= IF DROP EXIT THEN
    _RTAPTSCB.OUTPUT-NEEDED @ IF SCR-REQUEST-FLUSH THEN ;

\ Normal scheduling is deliberately distinct from close settlement.  During
\ discovery or a reset boundary there is no available publisher route, but an
\ already-active completion is still polled by RTAPT-STEP on every service.
\ A bound output producer receives one bounded call only after that engine
\ step.  A valid nonfatal OUTPUT-NEEDED observation schedules one neutral,
\ persistent screen request after exact-backend proof.  This bridge neither
\ starts another service loop nor forces or retransmits a CELL snapshot.
: _RTAPTSCB-STEP  ( context -- status )
    DUP _RTAPTSCB-R ! RTAPTSCB-VALID? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCB-R @ _RTAPTSCB-ENGINE-STEP
    DUP SCB-S-OK <> IF EXIT THEN DROP
    _RTAPTSCB-R @ _RTAPTSCB-PRODUCER-STEP DUP _RTAPTSCB-STATUS !
    DUP SCB-S-OK = SWAP SCB-S-WOULD-BLOCK = OR IF
        _RTAPTSCB-R @ _RTAPTSCB-SCHEDULE-OUTPUT
    THEN
    _RTAPTSCB-STATUS @ ;

\ RTAPT-SETTLE never schedules queued lifecycle work.  Once no completion is
\ pending, every engine outcome is diagnostic state rather than PT wire
\ authority: preserve it in the engine, but never let it prevent PT-CLOSE.
: _RTAPTSCB-SETTLE  ( context -- status pending? )
    DUP _RTAPTSCB-R ! RTAPTSCB-VALID? 0= IF SCB-S-INVALID 0 EXIT THEN
    _RTAPTSCB-R @ RTAPTSCB.ENGINE @ RTAPT-SETTLE
    _RTAPTSCB-PENDING ! _RTAPTSCB-STATUS !
    _RTAPTSCB-PENDING @ IF SCB-S-WOULD-BLOCK -1 EXIT THEN
    SCB-S-OK 0 ;

\ These queries expose only validated scheduler observations.  In particular,
\ OUTPUT-NEEDED? is false unless this publisher's immutable attached APTSCB is
\ also the exact current screen backend.  Normal STEP consumes that observation
\ into SCR-REQUEST-FLUSH; it never turns the flag into a CELL snapshot.
: RTAPTSCB-MORE-WORK?  ( publisher -- flag )
    DUP RTAPTSCB-VALID? 0= IF DROP 0 EXIT THEN
    _RTAPTSCB.MORE-WORK @ ;

: RTAPTSCB-OUTPUT-NEEDED?  ( publisher -- flag )
    DUP RTAPTSCB-VALID? 0= IF DROP 0 EXIT THEN
    DUP _RTAPTSCB-EXACT-SCREEN? 0= IF DROP 0 EXIT THEN
    _RTAPTSCB.OUTPUT-NEEDED @ ;

VARIABLE _RTAPTSCBOP-CONTEXT
VARIABLE _RTAPTSCBOP-CONTEXT-U
VARIABLE _RTAPTSCBOP-BUDGET
VARIABLE _RTAPTSCBOP-STEP
VARIABLE _RTAPTSCBOP-PREPARE
VARIABLE _RTAPTSCBOP-PUBLISHER

\ RTAPTSCB-OUTPUT-PRODUCER!
\   ( context-a context-u budget step-xt prepare-xt publisher -- status )
\ Install one optional, engine-neutral source of bounded output work while the
\ surface is still unobserved.  The producer span is borrowed until publisher
\ retirement.  Exact repetition is idempotent; replacement or unbinding is
\ forbidden because callbacks may retain source-free lifecycle authority.
\
\   STEP     ( cols rows generation budget context
\              -- scb-status more? output-needed? )
\   PREPARE  ( cols rows generation context -- scb-status )
: RTAPTSCB-OUTPUT-PRODUCER!
  ( context-a context-u budget step-xt prepare-xt publisher -- status )
    _RTAPTSCBOP-PUBLISHER ! _RTAPTSCBOP-PREPARE !
    _RTAPTSCBOP-STEP ! _RTAPTSCBOP-BUDGET !
    _RTAPTSCBOP-CONTEXT-U ! _RTAPTSCBOP-CONTEXT !
    _RTAPTSCBOP-PUBLISHER @ RTAPTSCB-VALID? 0= IF
        SCB-S-INVALID EXIT
    THEN
    _RTAPTSCBOP-PUBLISHER @ _RTAPTSCB.PRODUCER-CONTEXT @ IF
        _RTAPTSCBOP-PUBLISHER @ _RTAPTSCB.PRODUCER-CONTEXT @
            _RTAPTSCBOP-CONTEXT @ =
        _RTAPTSCBOP-PUBLISHER @ _RTAPTSCB.PRODUCER-U @
            _RTAPTSCBOP-CONTEXT-U @ = AND
        _RTAPTSCBOP-PUBLISHER @ _RTAPTSCB.PRODUCER-BUDGET @
            _RTAPTSCBOP-BUDGET @ = AND
        _RTAPTSCBOP-PUBLISHER @ _RTAPTSCB.PRODUCER-STEP-XT @
            _RTAPTSCBOP-STEP @ = AND
        _RTAPTSCBOP-PUBLISHER @ _RTAPTSCB.PRODUCER-PREPARE-XT @
            _RTAPTSCBOP-PREPARE @ = AND
        IF SCB-S-OK ELSE SCB-S-INVALID THEN EXIT
    THEN
    _RTAPTSCBOP-PUBLISHER @ _RTAPTSCB.SURFACE-GENERATION @ IF
        SCB-S-INVALID EXIT
    THEN
    _RTAPTSCBOP-CONTEXT @ _RTAPTSCBOP-CONTEXT-U @
        _RTAPTSCB-SPAN? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBOP-BUDGET @ 0> 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBOP-STEP @ 0= _RTAPTSCBOP-PREPARE @ 0= OR IF
        SCB-S-INVALID EXIT
    THEN
    _RTAPTSCBOP-CONTEXT @ _RTAPTSCBOP-CONTEXT-U @
        _RTAPTSCBOP-PUBLISHER @ RTAPTSCB-SIZE MSPAN-OVERLAP? IF
        SCB-S-INVALID EXIT
    THEN
    _RTAPTSCBOP-CONTEXT @ _RTAPTSCBOP-CONTEXT-U @
        _RTAPTSCBOP-PUBLISHER @ RTAPTSCB.ENGINE @
        RTAPT-STORAGE-DISJOINT? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBOP-PUBLISHER @ _RTAPTSCB.ADAPTER @ ?DUP IF
        _RTAPTSCBOP-CONTEXT @ _RTAPTSCBOP-CONTEXT-U @ ROT
        APTSCB-STORAGE-DISJOINT? 0= IF SCB-S-INVALID EXIT THEN
    THEN
    _RTAPTSCBOP-CONTEXT-U @ _RTAPTSCBOP-PUBLISHER @
        _RTAPTSCB.PRODUCER-U !
    _RTAPTSCBOP-BUDGET @ _RTAPTSCBOP-PUBLISHER @
        _RTAPTSCB.PRODUCER-BUDGET !
    _RTAPTSCBOP-STEP @ _RTAPTSCBOP-PUBLISHER @
        _RTAPTSCB.PRODUCER-STEP-XT !
    _RTAPTSCBOP-PREPARE @ _RTAPTSCBOP-PUBLISHER @
        _RTAPTSCB.PRODUCER-PREPARE-XT !
    \ CONTEXT is the immutable bound marker and becomes visible last.
    _RTAPTSCBOP-CONTEXT @ _RTAPTSCBOP-PUBLISHER @
        _RTAPTSCB.PRODUCER-CONTEXT !
    _RTAPTSCBOP-PUBLISHER @ RTAPTSCB-VALID? IF
        SCB-S-OK
    ELSE SCB-S-INVALID THEN ;

VARIABLE _RTAPTSCBI-SESSION
VARIABLE _RTAPTSCBI-ENGINE
VARIABLE _RTAPTSCBI-PUBLISHER

\ RTAPTSCB-INIT ( session engine publisher -- status )
: RTAPTSCB-INIT  ( session engine publisher -- status )
    _RTAPTSCBI-PUBLISHER ! _RTAPTSCBI-ENGINE ! _RTAPTSCBI-SESSION !
    _RTAPTSCBI-ENGINE @ RTAPT-VALID? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBI-SESSION @ _RTAPTSCBI-ENGINE @
        RTAPT-USES-SESSION? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBI-PUBLISHER @ 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBI-PUBLISHER @ 7 AND IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBI-PUBLISHER @ RTAPTSCB-SIZE
        MSPAN-NONWRAPPING? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBI-PUBLISHER @ RTAPTSCB-SIZE _RTAPTSCBI-ENGINE @
        RTAPT-STORAGE-DISJOINT? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBI-PUBLISHER @ RTAPTSCB-SIZE 0 FILL
    _RTAPTSCBI-ENGINE @ _RTAPTSCBI-PUBLISHER @ RTAPTSCB.ENGINE !
    _RTAPTSCB-MAGIC _RTAPTSCBI-PUBLISHER @ _RTAPTSCB.MAGIC !
    _RTAPTSCBI-SESSION @ _RTAPTSCBI-PUBLISHER @
    ['] _RTAPTSCB-BEGIN ['] _RTAPTSCB-SPAN ['] _RTAPTSCB-CELL
    ['] _RTAPTSCB-CURSOR ['] _RTAPTSCB-COMMIT ['] _RTAPTSCB-ABORT
    ['] _RTAPTSCB-STEP ['] _RTAPTSCB-SETTLE
    _RTAPTSCBI-PUBLISHER @ APTSCB-PUBLISHER-INIT
    DUP SCB-S-OK <> IF EXIT THEN DROP
    _RTAPTSCBI-PUBLISHER @ RTAPTSCB-VALID? IF
        SCB-S-OK
    ELSE SCB-S-INVALID THEN ;

VARIABLE _RTAPTSCBA-PUBLISHER
VARIABLE _RTAPTSCBA-ADAPTER
VARIABLE _RTAPTSCBA-STATUS

\ Attach only after proving that the neutral adapter itself is disjoint from
\ every range borrowed by the concrete engine and exact PT session.
: RTAPTSCB-ATTACH  ( publisher adapter -- status )
    _RTAPTSCBA-ADAPTER ! _RTAPTSCBA-PUBLISHER !
    _RTAPTSCBA-PUBLISHER @ RTAPTSCB-VALID? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBA-ADAPTER @ APTSCB-VALID? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBA-PUBLISHER @ APTSCBP.SESSION @
    _RTAPTSCBA-ADAPTER @ APTSCB-SESSION@ <> IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBA-PUBLISHER @ _RTAPTSCB.ADAPTER @ ?DUP IF
        _RTAPTSCBA-ADAPTER @ <> IF SCB-S-INVALID EXIT THEN
    THEN
    _RTAPTSCBA-PUBLISHER @ RTAPTSCB-SIZE
    _RTAPTSCBA-ADAPTER @ APTSCB-SIZE MSPAN-OVERLAP? IF
        SCB-S-INVALID EXIT
    THEN
    _RTAPTSCBA-ADAPTER @ APTSCB-SIZE
    _RTAPTSCBA-PUBLISHER @ RTAPTSCB.ENGINE @
        RTAPT-STORAGE-DISJOINT? 0= IF SCB-S-INVALID EXIT THEN
    _RTAPTSCBA-PUBLISHER @ _RTAPTSCB.PRODUCER-CONTEXT @ ?DUP IF
        _RTAPTSCBA-PUBLISHER @ _RTAPTSCB.PRODUCER-U @
        _RTAPTSCBA-ADAPTER @ APTSCB-STORAGE-DISJOINT? 0= IF
            SCB-S-INVALID EXIT
        THEN
    THEN
    _RTAPTSCBA-PUBLISHER @ _RTAPTSCBA-ADAPTER @ APTSCB-PUBLISHER!
        DUP _RTAPTSCBA-STATUS ! SCB-S-OK <> IF
        _RTAPTSCBA-STATUS @ EXIT
    THEN
    _RTAPTSCBA-ADAPTER @ _RTAPTSCBA-PUBLISHER @ _RTAPTSCB.ADAPTER !
    _RTAPTSCBA-PUBLISHER @ RTAPTSCB-VALID? IF
        SCB-S-OK
    ELSE SCB-S-INVALID THEN ;
