\ Optional shell candidate paired with the aggregate producer's exact ACK bank.
\ Complete immutable copies only.  Refusal never changes the legacy candidate.
PROVIDED akashic-tui-rshsp
REQUIRE hybrid-screen-producer.f
REQUIRE shell-membership.f
REQUIRE shell-family-clone.f
REQUIRE family-batch.f
REQUIRE shell-family-emit.f

240 CONSTANT RSHSP-SIZE
128 CONSTANT RSHSP-BANK-HEADER-SIZE
0x5253485350303031 CONSTANT _RSHSP-MAGIC
: _RSHSP.MAGIC ( s -- a ) ;
: _RSHSP.SIZE ( s -- a ) 8 + ;
: _RSHSP.SELF ( s -- a ) 16 + ;
: _RSHSP.PRODUCER ( s -- a ) 24 + ;
: _RSHSP.SOURCE ( s -- a ) 32 + ;
: _RSHSP.SHELL ( s -- a ) 40 + ;
: _RSHSP.WORK ( s -- a ) 48 + ;
: _RSHSP.WORK-U ( s -- a ) 56 + ;
: _RSHSP.A ( s -- a ) 64 + ;
: _RSHSP.A-U ( s -- a ) 72 + ;
: _RSHSP.B ( s -- a ) 80 + ;
: _RSHSP.B-U ( s -- a ) 88 + ;
: _RSHSP.ACTIVE ( s -- a ) 96 + ;
: _RSHSP.PENDING ( s -- a ) 104 + ;
: _RSHSP.ACTIVE-TARGET ( s -- a ) 112 + ;
: _RSHSP.PENDING-TARGET ( s -- a ) 120 + ;
: _RSHSP.ACTIVE-DRAW ( s -- a ) 128 + ;
: _RSHSP.PENDING-DRAW ( s -- a ) 136 + ;
: _RSHSP.BANK-BYTES ( s -- a ) 144 + ;
: _RSHSP.WORK-USED ( s -- a ) 152 + ;
: _RSHSP.MAX-ENTRIES ( s -- a ) 160 + ;
: _RSHSP.MAX-TEXT ( s -- a ) 168 + ;
: _RSHSP.EXTENSION ( s -- a ) 176 + ;
: RSHSP-BYTES ( -- n ) RSHSP-SIZE ;
: RSHSP-WORK-USED@ ( s -- n ) _RSHSP.WORK-USED @ ;
: RSHSP-BANK-BYTES@ ( s -- n ) _RSHSP.BANK-BYTES @ ;
: RSHSP-BANK.USED ( b -- a ) ;
: RSHSP-BANK.BATCH ( b -- a ) 8 + ;
: RSHSP-BANK.MODEL ( b -- a ) 16 + ;
: RSHSP-BANK.MODEL-U ( b -- a ) 24 + ;
: RSHSP-BANK.CORRELATIONS ( b -- a ) 32 + ;
: RSHSP-BANK.CORRELATIONS-U ( b -- a ) 40 + ;
: RSHSP-BANK.ACTIONS ( b -- a ) 48 + ;
: RSHSP-BANK.ACTIONS-U ( b -- a ) 56 + ;
: RSHSP-BANK.MEMBERSHIP ( b -- a ) 64 + ;
: RSHSP-BANK.MEMBERSHIP-U ( b -- a ) 72 + ;
: RSHSP-BANK.TARGET ( b -- a ) 80 + ;
: RSHSP-BANK.DRAW ( b -- a ) 88 + ;
: RSHSP-BANK.OWNER ( b -- a ) 96 + ;
: RSHSP-BANK.GENERATION ( b -- a ) 104 + ;
: RSHSP-BANK.NEXT-REGION ( b -- a ) 112 + ;
: RSHSP-BANK.NEXT-OBJECT ( b -- a ) 120 + ;

CREATE _RSHSP-OWNED-START VARIABLE _RSHSP-OWNED-LIMIT
: RSHSP-STORAGE-DISJOINT? ( a u -- flag )
    2DUP MSPAN-NONWRAPPING? 0= IF 2DROP 0 EXIT THEN
    2DUP _RSHSP-OWNED-START _RSHSP-OWNED-LIMIT @ _RSHSP-OWNED-START -
        MSPAN-OVERLAP? IF 2DROP 0 EXIT THEN
    2DUP RTHP-MODULE-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP RSHMM-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP RSHFC-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    RTE-FAMILY-EMIT-STORAGE-DISJOINT? ;
: _RSHSP-SPAN? ( a u -- flag )
    OVER 0= OVER 0> 0= OR IF 2DROP 0 EXIT THEN
    OVER 7 AND IF 2DROP 0 EXIT THEN RSHSP-STORAGE-DISJOINT? ;

VARIABLE _RSHSP-S VARIABLE _RSHSP-P VARIABLE _RSHSP-CURSOR VARIABLE _RSHSP-END
VARIABLE _RSHSP-M VARIABLE _RSHSP-MU VARIABLE _RSHSP-N VARIABLE _RSHSP-E
VARIABLE _RSHSP-Q VARIABLE _RSHSP-RESULT VARIABLE _RSHSP-ELIGIBLE
VARIABLE _RSHSP-REGIONS VARIABLE _RSHSP-PANES VARIABLE _RSHSP-CONTROLS
VARIABLE _RSHSP-TEXT VARIABLE _RSHSP-CORR VARIABLE _RSHSP-CLAIMS VARIABLE _RSHSP-ACTIONS
VARIABLE _RSHSP-MAP VARIABLE _RSHSP-MAP-U
VARIABLE _RSHSP-CATALOG VARIABLE _RSHSP-BATCH VARIABLE _RSHSP-ADMISSION
VARIABLE _RSHSP-FAMILIES VARIABLE _RSHSP-FAMILY-N VARIABLE _RSHSP-FAMILY-CAP
VARIABLE _RSHSP-REGION-N VARIABLE _RSHSP-FIRST-REGION VARIABLE _RSHSP-NEXT-ID
VARIABLE _RSHSP-SHELL-CONTROLS VARIABLE _RSHSP-BANDS VARIABLE _RSHSP-CONTENT-Z
VARIABLE _RSHSP-ITEM VARIABLE _RSHSP-OUT VARIABLE _RSHSP-BYTES VARIABLE _RSHSP-START
VARIABLE _RSHSP-KIND VARIABLE _RSHSP-COUNT VARIABLE _RSHSP-STRIDE
VARIABLE _RSHSP-REGION VARIABLE _RSHSP-FAMILY VARIABLE _RSHSP-PLAN
VARIABLE _RSHSP-I VARIABLE _RSHSP-J VARIABLE _RSHSP-RUN VARIABLE _RSHSP-MEMBER
VARIABLE _RSHSP-TEMP VARIABLE _RSHSP-SAVED VARIABLE _RSHSP-NEW
VARIABLE _RSHSP-CLAIM-BANK VARIABLE _RSHSP-CLAIM-U VARIABLE _RSHSP-BASE-CLAIM-U
VARIABLE _RSHSP-HEADS VARIABLE _RSHSP-EVENTS VARIABLE _RSHSP-EVENTS-U
VARIABLE _RSHSP-DIFF VARIABLE _RSHSP-GQ
VARIABLE _RSHSP-GITEMS VARIABLE _RSHSP-GREFS VARIABLE _RSHSP-GTEXT
VARIABLE _RSHSP-GCOUNT VARIABLE _RSHSP-GUSED VARIABLE _RSHSP-GLIMIT VARIABLE _RSHSP-GCELLS
VARIABLE _RSHSP-BANK VARIABLE _RSHSP-BANK-CAP VARIABLE _RSHSP-BANK-END
VARIABLE _RSHSP-STATUS

: _RSHSP-FAIL ( -- ) RTE-S-UNAVAILABLE THROW ;
: _RSHSP-CHECK ( flag -- ) 0= IF _RSHSP-FAIL THEN ;
: _RSHSP-ADD ( n n -- n ) _RTHP-U32+? 0= IF DROP RTE-S-CAPACITY THROW THEN ;
: _RSHSP-MUL ( n n -- n ) _RTHP-U32*? 0= IF DROP RTE-S-CAPACITY THROW THEN ;
: _RSHSP-ALIGN ( n -- n ) 7 _RSHSP-ADD -8 AND ;
: _RSHSP-TAKE ( n -- a )
    _RSHSP-ALIGN
    DUP _RSHSP-CURSOR @ _RSHSP-S @ _RSHSP.WORK @ - _RSHSP-ADD
        _RSHSP-S @ _RSHSP.WORK-USED @ MAX _RSHSP-S @ _RSHSP.WORK-USED !
    DUP _RSHSP-END @ _RSHSP-CURSOR @ - U> IF DROP RTE-S-CAPACITY THROW THEN
    _RSHSP-CURSOR @ SWAP DUP _RSHSP-CURSOR +! OVER SWAP 0 FILL ;
: _RSHSP-COPY ( a u -- dst ) DUP _RSHSP-TAKE DUP >R SWAP MOVE R> ;
: _RSHSP-ZSPAN ( a u -- a|0 u ) DUP 0= IF NIP 0 SWAP THEN ;
: _RSHSP-REGION@ ( id -- row ) _RSHSP-CATALOG @ RTE-REGION-CATALOG-FIND DUP _RSHSP-CHECK ;
: _RSHSP-MEMBER@ ( token -- row ) _RSHSP-MAP @ _RSHSP-MAP-U @ RSHMM-FIND DUP _RSHSP-CHECK ;
: _RSHSP-CLEAR-RECT ( row col h w -- )
    _RSHSP-P @ _RTHP.SOURCE-DRAW @ _RSHSP-S @ _RSHSP.SOURCE @ SHSN-RECT-CLEAR?
    SHSN-S-OK = _RSHSP-CHECK _RSHSP-CHECK ;
: _RSHSP-ENTRY ( i -- e ) _RSHSP-M @ SHM-ENTRY ;
: _RSHSP-CONTENT-RECT ( e -- row col h w )
    >R R@ SHME.CONTENT-ROW @ R@ SHME.CONTENT-COL @
    R@ SHME.CONTENT-H @ R> SHME.CONTENT-W @ ;
: _RSHSP-OVERLAP? ( e e -- flag )
    >R DUP SHME.CONTENT-ROW @ R@ SHME.CONTENT-ROW @ R@ SHME.CONTENT-H @ + <
    OVER SHME.CONTENT-ROW @ 2 PICK SHME.CONTENT-H @ + R@ SHME.CONTENT-ROW @ > AND
    OVER SHME.CONTENT-COL @ R@ SHME.CONTENT-COL @ R@ SHME.CONTENT-W @ + < AND
    SWAP DUP SHME.CONTENT-COL @ SWAP SHME.CONTENT-W @ + R> SHME.CONTENT-COL @ > AND ;
: _RSHSP-ELIGIBILITY ( -- )
    _RSHSP-N @ 0 ?DO I _RSHSP-ENTRY DUP SHME.KIND @ SHM-K-PANE = IF
        DUP _RSHSP-E ! >R R@ SHME.ROW @ R@ SHME.COL @
        R@ SHME.HEIGHT @ R> SHME.WIDTH @ _RSHSP-CLEAR-RECT
        I 0 ?DO I _RSHSP-ENTRY DUP SHME.KIND @ SHM-K-PANE = IF
            _RSHSP-E @ _RSHSP-OVERLAP? 0= _RSHSP-CHECK ELSE DROP THEN LOOP
        1 _RSHSP-ELIGIBLE @ I 8 * + !
    ELSE DROP THEN LOOP ;
: _RSHSP-GAP-BLANK? ( row col h w -- flag )
    _RSHSP-BYTES ! DROP _RSHSP-START ! _RSHSP-TEMP !
    _RSHSP-BYTES @ 0 ?DO _RSHSP-TEMP @ _RSHSP-START @ I + SCR-GET
        DUP _SCR-C-PAIR AND IF DROP 0 UNLOOP EXIT THEN
        CELL-CP@ DUP 0= SWAP 32 = OR 0= IF 0 UNLOOP EXIT THEN LOOP -1 ;
: _RSHSP-BAND? ( kind -- flag )
    _RSHSP-KIND !
    _RSHSP-KIND @ _RSHSP-M @ _RSHSP-MU @ RSHPL-BAND-BOUNDS
    RSHPL-S-OK <> IF 2DROP 2DROP 0 EXIT THEN
    _RSHSP-P @ _RTHP.SOURCE-DRAW @ _RSHSP-S @ _RSHSP.SOURCE @ SHSN-RECT-CLEAR?
    SHSN-S-OK <> IF DROP 0 EXIT THEN 0= IF 0 EXIT THEN
    0 _RSHSP-I ! BEGIN
        _RSHSP-I @ _RSHSP-KIND @ _RSHSP-M @ _RSHSP-MU @ RSHPL-GAP-BOUNDS
        DUP RSHPL-S-END = IF DROP 2DROP 2DROP -1 EXIT THEN
        RSHPL-S-OK <> IF 2DROP 2DROP 0 EXIT THEN
        _RSHSP-GAP-BLANK? 0= IF 0 EXIT THEN 1 _RSHSP-I +!
    AGAIN ;

: _RSHSP-ALLOCATE-PLAN ( -- )
    _RSHSP-N @ 8 _RSHSP-MUL _RSHSP-TAKE _RSHSP-ELIGIBLE !
    RSHPL-REQUEST-SIZE _RSHSP-TAKE _RSHSP-Q !
    RSHPL-RESULT-SIZE _RSHSP-TAKE _RSHSP-RESULT !
    _RSHSP-N @ 2 _RSHSP-ADD 96 _RSHSP-MUL _RSHSP-TAKE _RSHSP-REGIONS !
    _RSHSP-N @ RTE-PANE-SIZE _RSHSP-MUL _RSHSP-TAKE _RSHSP-PANES !
    _RSHSP-N @ 2 _RSHSP-ADD RTE-CONTROL-SIZE _RSHSP-MUL _RSHSP-TAKE _RSHSP-CONTROLS !
    _RSHSP-MU @ _RSHSP-TAKE _RSHSP-TEXT !
    _RSHSP-N @ 2 _RSHSP-ADD RSHPL-CORRELATION-SIZE _RSHSP-MUL _RSHSP-TAKE _RSHSP-CORR !
    _RSHSP-N @ 4 _RSHSP-MUL 2 _RSHSP-ADD RSHPL-CLAIM-SIZE _RSHSP-MUL _RSHSP-TAKE _RSHSP-CLAIMS !
    _RSHSP-MU @ _RSHSP-TAKE _RSHSP-ACTIONS !
    _RSHSP-N @ RSHMM-ENTRY-SIZE _RSHSP-MUL _RSHSP-TAKE _RSHSP-MAP !
    _RSHSP-ELIGIBILITY
    0 _RSHSP-BANDS !
    SHM-K-TASK _RSHSP-BAND? IF 1 _RSHSP-BANDS +! THEN
    SHM-K-LAUNCHER _RSHSP-BAND? IF 2 _RSHSP-BANDS +! THEN
    _RSHSP-N @ 0 ?DO I _RSHSP-ENTRY SHME.KIND @
        DUP SHM-K-TASK = IF _RSHSP-BANDS @ 1 AND 0= IF 0 _RSHSP-BANDS ! THEN THEN
        SHM-K-LAUNCHER = IF _RSHSP-BANDS @ 2 AND 0= IF 0 _RSHSP-BANDS ! THEN THEN
    LOOP
    _RSHSP-P @ _RTHP.ADMISSION _RTE-HA.REGION-Z @ DUP 2147483644 > IF DROP _RSHSP-FAIL THEN
        _RSHSP-CONTENT-Z !
    _RSHSP-P @ _RTHP.REGION @ _RSHSP-P @ _RTHP.INSTRUMENT-REGION-COUNT @ _RSHSP-ADD
        1 _RSHSP-ADD _RSHSP-FIRST-REGION !
    _RSHSP-M @ _RSHSP-MU @ _RSHSP-M @ SHM.OWNER-ID @
    _RSHSP-P @ _RTHP.SOURCE-DRAW @ _RSHSP-ELIGIBLE @ _RSHSP-N @ 8 *
    _RSHSP-BANDS @ _RSHSP-Q @ RSHPL-REQUEST-SOURCE!
    _RSHSP-P @ _RTHP.OWNER @ _RSHSP-P @ _RTHP.OWNER-GEN @ _RSHSP-FIRST-REGION @
    _RSHSP-P @ _RTHP.FIRST-OBJECT @ _RSHSP-P @ _RTHP.CONTROL-COUNT @ _RSHSP-ADD
        _RSHSP-P @ _RTHP.INSTRUMENT-LAST @ 1 _RSHSP-ADD MAX
        _RSHSP-P @ _RTHP.STATIC-LAST @ 1 _RSHSP-ADD MAX
        _RSHSP-N @ _RSHSP-ADD 2 _RSHSP-ADD
    _RSHSP-P @ _RTHP.FIRST-OBJECT @ _RSHSP-P @ _RTHP.CONTROL-COUNT @ _RSHSP-ADD
    _RSHSP-Q @ RSHPL-REQUEST-IDENTITY!
    -3 _RSHSP-CONTENT-Z @ _RSHSP-CONTENT-Z @ 1+ _RSHSP-Q @ RSHPL-REQUEST-Z!
    _RSHSP-REGIONS @ _RSHSP-N @ 2 + 96 *
    _RSHSP-PANES @ _RSHSP-N @ RTE-PANE-SIZE *
    _RSHSP-CONTROLS @ _RSHSP-N @ 2 + RTE-CONTROL-SIZE *
    _RSHSP-TEXT @ _RSHSP-MU @
    _RSHSP-CORR @ _RSHSP-N @ 2 + RSHPL-CORRELATION-SIZE *
    _RSHSP-CLAIMS @ _RSHSP-N @ 4 * 2 + RSHPL-CLAIM-SIZE *
    _RSHSP-ACTIONS @ _RSHSP-MU @ _RSHSP-RESULT @ RSHPL-RESULT-SIZE
    _RSHSP-Q @ RSHPL-REQUEST-OUTPUT!
    _RSHSP-Q @ RSHPL-BUILD RSHPL-S-OK = _RSHSP-CHECK
    _RSHSP-RESULT @ RSHPL-RESULT.PANES @
    _RSHSP-RESULT @ RSHPL-RESULT.TASKBARS @ OR _RSHSP-CHECK
    _RSHSP-RESULT @ RSHPL-RESULT.CONTROLS @ _RSHSP-SHELL-CONTROLS !
    _RSHSP-Q @ _RSHPL-Q.FIRST-OBJECT @
        _RSHSP-RESULT @ RSHPL-RESULT.PANES @ _RSHSP-ADD _RSHSP-NEXT-ID !
    _RSHSP-M @ _RSHSP-MU @
    _RSHSP-P @ _RTHP.SOURCE-DIR-A @ _RSHSP-P @ _RTHP.SOURCE-DIR-USED @
    _RSHSP-CORR @ _RSHSP-RESULT @ RSHPL-RESULT.CORRELATIONS @ RSHPL-CORRELATION-SIZE *
    _RSHSP-MAP @ _RSHSP-N @ RSHMM-ENTRY-SIZE * RSHMM-BUILD
        RSHMM-S-OK = _RSHSP-CHECK _RSHSP-MAP-U ! DROP ;

: _RSHSP-INSTRUMENT-CLIP! ( copied-region -- )
    \ RUIP omits an explicit clip when it equals the complete logical root.
    \ Shell ownership uses the same physical rectangle in explicit form.
    DUP _RTE-IR.FLAGS @ RTE-REGION-CLIPPED AND IF DROP EXIT THEN
    DUP _RTE-IR.X @ OVER _RTE-IR.CLIP-X !
    DUP _RTE-IR.Y @ OVER _RTE-IR.CLIP-Y !
    DUP _RTE-IR.COLS @ OVER _RTE-IR.CLIP-COLS !
    DUP _RTE-IR.ROWS @ OVER _RTE-IR.CLIP-ROWS !
    DUP _RTE-IR.FLAGS @ RTE-REGION-CLIPPED OR SWAP _RTE-IR.FLAGS ! ;

: _RSHSP-CATALOG! ( -- )
    RTE-REGION-CATALOG-SIZE _RSHSP-TAKE _RSHSP-CATALOG !
    _RSHSP-P @ _RTHP.OWNER @ _RSHSP-CATALOG @ _RTE-RC.OWNER !
    _RSHSP-P @ _RTHP.OWNER-GEN @ _RSHSP-CATALOG @ _RTE-RC.GENERATION !
    _RSHSP-P @ _RTHP.COLS @ _RSHSP-CATALOG @ _RTE-RC.SURFACE-COLS !
    _RSHSP-P @ _RTHP.ROWS @ _RSHSP-CATALOG @ _RTE-RC.SURFACE-ROWS !
    _RSHSP-P @ _RTHP.INSTRUMENT-REGION-COUNT @
    _RSHSP-RESULT @ RSHPL-RESULT.REGIONS @ _RSHSP-ADD 1 _RSHSP-ADD _RSHSP-REGION-N !
    _RSHSP-REGION-N @ 96 _RSHSP-MUL _RSHSP-TAKE _RSHSP-OUT !
    _RSHSP-OUT @ _RSHSP-CATALOG @ _RTE-RC.REGIONS-A !
    _RSHSP-REGION-N @ 96 * _RSHSP-CATALOG @ _RTE-RC.REGIONS-U !
    _RSHSP-P @ _RTHP.REGION @ _RSHSP-OUT @ _RTE-IR.ID !
    _RSHSP-P @ _RTHP.COLS @ _RSHSP-OUT @ _RTE-IR.COLS !
    _RSHSP-P @ _RTHP.ROWS @ _RSHSP-OUT @ _RTE-IR.ROWS !
    -2 _RSHSP-OUT @ _RTE-IR.Z !
    RTE-REGION-VISIBLE _RSHSP-OUT @ _RTE-IR.FLAGS !
    _RSHSP-P @ _RTHP.INSTRUMENT-REGIONS-A @ _RSHSP-OUT @ 96 +
        _RSHSP-P @ _RTHP.INSTRUMENT-REGION-COUNT @ 96 * MOVE
    _RSHSP-P @ _RTHP.INSTRUMENT-REGION-COUNT @ 0 ?DO
        _RSHSP-OUT @ I 1+ 96 * + _RSHSP-INSTRUMENT-CLIP!
    LOOP
    _RSHSP-REGIONS @ _RSHSP-OUT @ _RSHSP-P @ _RTHP.INSTRUMENT-REGION-COUNT @ 1+ 96 * +
        _RSHSP-RESULT @ RSHPL-RESULT.REGIONS @ 96 * MOVE
    _RSHSP-CATALOG @ RTE-REGION-CATALOG-VALID? _RSHSP-CHECK
    _RSHSP-P @ _RTHP.CONTROL-COUNT @ _RSHSP-P @ _RTHP.STATIC-COUNT @ _RSHSP-ADD
    _RSHSP-N @ _RSHSP-ADD 6 _RSHSP-ADD _RSHSP-FAMILY-CAP !
    _RSHSP-FAMILY-CAP @ RTE-FAMILY-ENTRY-SIZE _RSHSP-MUL _RSHSP-TAKE _RSHSP-FAMILIES !
    0 _RSHSP-FAMILY-N !
    RTE-FAMILY-BATCH-SIZE _RSHSP-TAKE _RSHSP-BATCH !
    RTE-FAMILY-ADMISSION-SIZE _RSHSP-TAKE _RSHSP-ADMISSION ! ;

\ A new family starts with a copied catalog row.  Text is compacted in item
\ order so the immutable clone never retains a containing source arena.
: _RSHSP-FAMILY! ( kind -- )
    _RSHSP-KIND !
    _RSHSP-FAMILY-N @ _RSHSP-FAMILY-CAP @ U< _RSHSP-CHECK
    _RSHSP-FAMILIES @ _RSHSP-FAMILY-N @ RTE-FAMILY-ENTRY-SIZE * + _RSHSP-FAMILY !
    1 _RSHSP-FAMILY-N +!
    _RSHSP-KIND @ _RSHSP-FAMILY @ _RTE-FE.KIND !
    _RSHSP-KIND @ RTE-FAMILY-PLAN-SIZE DUP _RSHSP-FAMILY @ _RTE-FE.PLAN-U !
        _RSHSP-TAKE DUP _RSHSP-PLAN ! _RSHSP-FAMILY @ _RTE-FE.PLAN-A !
    _RSHSP-CATALOG @ _RSHSP-PLAN @ 32 MOVE ;
: _RSHSP-PLAN-REGION! ( id -- )
    _RSHSP-REGION@ _RSHSP-PLAN @ 32 + 88 MOVE ;
: _RSHSP-PLAN-ITEMS! ( a u -- )
    _RSHSP-PLAN @ _RTE-CP.ITEMS-U ! _RSHSP-PLAN @ _RTE-CP.ITEMS-A ! ;
: _RSHSP-FAMILY-BYTES! ( a u -- )
    _RSHSP-ZSPAN _RSHSP-FAMILY @ _RTE-FE.BYTES-U ! _RSHSP-FAMILY @ _RTE-FE.BYTES-A ! ;
: _RSHSP-DENSE! ( pointer-field -- )
    DUP 8 + @ DUP IF
        _RSHSP-TEMP ! DUP @ _RSHSP-CURSOR @ _RSHSP-TEMP @ MOVE
        _RSHSP-CURSOR @ SWAP ! _RSHSP-TEMP @ _RSHSP-CURSOR +!
    ELSE 2DROP THEN ;
: _RSHSP-TEXT-MEASURE ( items n stride -- bytes )
    _RSHSP-STRIDE ! _RSHSP-COUNT ! _RSHSP-ITEM ! 0
    _RSHSP-COUNT @ 0 ?DO
        _RSHSP-KIND @ RTE-FAMILY-CONTROL = IF
            _RSHSP-ITEM @ _RTE-CONTROL.LABEL-U @ _RSHSP-ADD
            _RSHSP-ITEM @ _RTE-CONTROL.SHORTCUT-U @ _RSHSP-ADD
            _RSHSP-ITEM @ _RTE-CONTROL.CONTENT-U @ _RSHSP-ADD
        ELSE
            _RSHSP-ITEM @ _RTE-STATIC.LABEL-U @ _RSHSP-ADD
            _RSHSP-ITEM @ _RTE-STATIC.VALUE-U @ _RSHSP-ADD
        THEN _RSHSP-STRIDE @ _RSHSP-ITEM +!
    LOOP ;
: _RSHSP-COPY-RUN ( a n kind region -- )
    _RSHSP-REGION ! _RSHSP-FAMILY! _RSHSP-COUNT ! _RSHSP-START !
    _RSHSP-REGION @ _RSHSP-PLAN-REGION!
    _RSHSP-KIND @ RTE-FAMILY-ITEM-SIZE _RSHSP-STRIDE !
    _RSHSP-START @ _RSHSP-COUNT @ _RSHSP-STRIDE @ _RSHSP-MUL
        DUP _RSHSP-BYTES ! _RSHSP-COPY _RSHSP-OUT !
    _RSHSP-OUT @ _RSHSP-BYTES @ _RSHSP-PLAN-ITEMS!
    _RSHSP-OUT @ _RSHSP-COUNT @ _RSHSP-STRIDE @ _RSHSP-TEXT-MEASURE
        DUP _RSHSP-BYTES ! _RSHSP-TAKE _RSHSP-START !
    _RSHSP-CURSOR @ _RSHSP-SAVED ! _RSHSP-START @ _RSHSP-CURSOR !
    _RSHSP-COUNT @ 0 ?DO
        _RSHSP-OUT @ I _RSHSP-STRIDE @ * + _RSHSP-ITEM !
        _RSHSP-KIND @ RTE-FAMILY-CONTROL = IF
            _RSHSP-REGION @ _RSHSP-ITEM @ _RTE-CONTROL.REGION !
            _RSHSP-ITEM @ _RTE-CONTROL.LABEL-A _RSHSP-DENSE!
            _RSHSP-ITEM @ _RTE-CONTROL.SHORTCUT-A _RSHSP-DENSE!
            _RSHSP-ITEM @ _RTE-CONTROL.CONTENT-A _RSHSP-DENSE!
        ELSE
            _RSHSP-REGION @ _RSHSP-ITEM @ _RTE-STATIC.REGION !
            _RSHSP-SHELL-CONTROLS @ _RSHSP-ITEM @ _RTE-STATIC.ID +!
            _RSHSP-ITEM @ _RTE-STATIC.LABEL-A _RSHSP-DENSE!
            _RSHSP-ITEM @ _RTE-STATIC.VALUE-A _RSHSP-DENSE!
        THEN
    LOOP
    _RSHSP-SAVED @ _RSHSP-CURSOR ! _RSHSP-START @ _RSHSP-BYTES @ _RSHSP-FAMILY-BYTES! ;
: _RSHSP-CONTROL-MEMBER ( index -- region )
    RUCP-CORRELATION-SIZE * _RSHSP-P @ _RTHP.CORR-A @ +
        RUCP-CORRELATION-ATTACHMENT@ _RSHSP-MEMBER@ RSHMM.CONTENT-REGION @ ;
: _RSHSP-APP-CONTROLS ( -- )
    0 _RSHSP-I ! BEGIN _RSHSP-I @ _RSHSP-P @ _RTHP.CONTROL-COUNT @ U< WHILE
        _RSHSP-I @ _RSHSP-CONTROL-MEMBER _RSHSP-MEMBER !
        _RSHSP-I @ _RSHSP-J !
        -1 _RSHSP-RUN !
        BEGIN _RSHSP-J @ _RSHSP-P @ _RTHP.CONTROL-COUNT @ U< _RSHSP-RUN @ AND WHILE
            _RSHSP-J @ _RSHSP-CONTROL-MEMBER _RSHSP-MEMBER @ <> IF 0 _RSHSP-RUN !
            ELSE 1 _RSHSP-J +! THEN
        REPEAT
        _RSHSP-P @ _RTHP.CONTROLS-A @ _RSHSP-I @ RTE-CONTROL-SIZE * +
        _RSHSP-J @ _RSHSP-I @ - RTE-FAMILY-CONTROL _RSHSP-MEMBER @ _RSHSP-COPY-RUN
        _RSHSP-J @ _RSHSP-I !
    REPEAT
    _RSHSP-SHELL-CONTROLS @ IF
        \ Both canonical roots belong to the planner's one taskbar region.
        \ Refuse a changed planner contract before COPY-RUN rewrites regions.
        _RSHSP-SHELL-CONTROLS @ 0 ?DO
            _RSHSP-CONTROLS @ I RTE-CONTROL-SIZE * + _RTE-CONTROL.REGION @
            _RSHSP-CONTROLS @ _RTE-CONTROL.REGION @ = _RSHSP-CHECK
        LOOP
        _RSHSP-CONTROLS @ _RSHSP-SHELL-CONTROLS @ RTE-FAMILY-CONTROL
        _RSHSP-CONTROLS @ _RTE-CONTROL.REGION @ _RSHSP-COPY-RUN
    THEN ;
: _RSHSP-STATICS ( -- )
    _RSHSP-P @ _RTHP.STATIC-COUNT @ 0 ?DO
        _RSHSP-P @ _RTHP.STATIC-CORR-A @ I _RTHP-STATIC-CORR-SIZE * + @
            _RSHSP-MEMBER@ RSHMM.CONTENT-REGION @ _RSHSP-MEMBER !
        _RSHSP-P @ _RTHP.STATICS-A @ I RTE-STATIC-SIZE * +
            1 RTE-FAMILY-STATIC _RSHSP-MEMBER @ _RSHSP-COPY-RUN
    LOOP ;

: _RSHSP-SERIES ( -- )
    _RSHSP-P @ _RTHP.SERIES-COUNT @ 0= IF EXIT THEN
    RTE-FAMILY-SERIES _RSHSP-FAMILY!
    _RSHSP-P @ _RTHP.SERIES-PLAN _RSHSP-PLAN @ RTE-SERIES-PLAN-SIZE MOVE
    _RSHSP-P @ _RTHP.SERIES-SAMPLES-A @ _RSHSP-P @ _RTHP.SERIES-SAMPLES-USED @
        _RSHSP-FAMILY-BYTES! ;
: _RSHSP-INSTRUMENTS ( -- )
    _RSHSP-P @ _RTHP.INSTRUMENT-COUNT @ 0= IF EXIT THEN
    RTE-FAMILY-INSTRUMENT _RSHSP-FAMILY!
    _RSHSP-P @ _RTHP.INSTRUMENT-PLAN _RSHSP-PLAN @ RTE-INSTRUMENT-PLAN-SIZE MOVE
    \ Family source spans are pairwise disjoint. Copy the normalized rows
    \ rather than borrowing the catalog's overlapping region subspan.
    _RSHSP-P @ _RTHP.INSTRUMENT-REGION-COUNT @ 96 *
        DUP _RSHSP-PLAN @ _RTE-IP.REGIONS-U !
    _RSHSP-CATALOG @ _RTE-RC.REGIONS-A @ 96 + SWAP
        _RSHSP-COPY _RSHSP-PLAN @ _RTE-IP.REGIONS-A !
    _RSHSP-P @ _RTHP.INSTRUMENTS-A @ _RSHSP-P @ _RTHP.INSTRUMENT-COUNT @ RTE-INSTRUMENT-SIZE *
        _RSHSP-COPY _RSHSP-OUT !
    _RSHSP-OUT @ _RSHSP-PLAN @ _RTE-IP.ITEMS-A !
    _RSHSP-P @ _RTHP.INSTRUMENT-COUNT @ 0 ?DO
        _RSHSP-OUT @ I RTE-INSTRUMENT-SIZE * + _RSHSP-ITEM !
        _RSHSP-SHELL-CONTROLS @ _RSHSP-ITEM @ _RTE-INSTRUMENT.ID +!
        _RSHSP-P @ _RTHP.INSTRUMENT-CORR-A @ I RUIP-CORRELATION-SIZE * +
            RUIP-CORRELATION-ATTACHMENT@ _RSHSP-MEMBER@ _RSHSP-MEMBER !
        _RSHSP-ITEM @ _RTE-INSTRUMENT.REGION @ _RSHSP-REGION@ _RSHSP-REGION !
        _RSHSP-REGION @ _RTE-IR.FLAGS @ RTE-REGION-CLIPPED AND _RSHSP-CHECK
        _RSHSP-REGION @ _RTE-IR.Z @ -3 > _RSHSP-CHECK
        _RSHSP-REGION @ _RTE-IR.Z @ _RSHSP-CONTENT-Z @ < _RSHSP-CHECK
        _RSHSP-REGION @ _RTE-IR.CLIP-Y @ _RSHSP-MEMBER @ RSHMM.ROW @ >= _RSHSP-CHECK
        _RSHSP-REGION @ _RTE-IR.CLIP-X @ _RSHSP-MEMBER @ RSHMM.COL @ >= _RSHSP-CHECK
        _RSHSP-REGION @ _RTE-IR.CLIP-Y @ _RSHSP-REGION @ _RTE-IR.CLIP-ROWS @ +
            _RSHSP-MEMBER @ RSHMM.ROW @ _RSHSP-MEMBER @ RSHMM.HEIGHT @ + <= _RSHSP-CHECK
        _RSHSP-REGION @ _RTE-IR.CLIP-X @ _RSHSP-REGION @ _RTE-IR.CLIP-COLS @ +
            _RSHSP-MEMBER @ RSHMM.COL @ _RSHSP-MEMBER @ RSHMM.WIDTH @ + <= _RSHSP-CHECK
    LOOP
    _RSHSP-P @ _RTHP.INSTRUMENT-UNITS-A @ _RSHSP-P @ _RTHP.INSTRUMENT-UNITS-USED @
        _RSHSP-FAMILY-BYTES! ;
: _RSHSP-PANE-FAMILY ( -- )
    _RSHSP-RESULT @ RSHPL-RESULT.PANES @ 0= IF EXIT THEN
    RTE-FAMILY-PANE _RSHSP-FAMILY!
    _RSHSP-PANES @ _RTE-PANE.REGION @ _RSHSP-PLAN-REGION!
    _RSHSP-PANES @ _RSHSP-RESULT @ RSHPL-RESULT.PANES @ RTE-PANE-SIZE * _RSHSP-PLAN-ITEMS!
    _RSHSP-TEXT @ _RSHSP-RESULT @ RSHPL-RESULT.PANE-UTF8 @ _RSHSP-FAMILY-BYTES! ;

\ Existing menu claims remain a nonopaque prefix. Shell claims and the pane
\ exclusion rectangles appended after them are opaque, exact source geometry.
: _RSHSP-CLAIM-RECT ( index row col h w -- )
    _RSHSP-BYTES ! _RSHSP-COUNT ! _RSHSP-START ! _RSHSP-TEMP ! _RSHSP-J !
    _RSHSP-M @ SHM.OWNER-ID @ _RSHSP-P @ _RTHP.SOURCE-GEN @ 1
    _RSHSP-J @ _RSHSP-J @ 1+ 0
    _RSHSP-TEMP @ _RSHSP-START @ _RSHSP-TEMP @ _RSHSP-COUNT @ +
    _RSHSP-START @ _RSHSP-BYTES @ +
    _RSHSP-CLAIM-BANK @ _RSHSP-CLAIM-U @ + RUCL-ADMITTED-RECTANGLE!
        RUCL-S-OK = _RSHSP-CHECK
    RUCL-CLAIM-SIZE _RSHSP-CLAIM-U +! ;
: _RSHSP-GLYPH-WORK ( -- )
    _RSHSP-P @ _RTHP.CLAIMS-USED @
    _RSHSP-RESULT @ RSHPL-RESULT.CLAIMS @ _RSHSP-N @ _RSHSP-ADD RUCL-CLAIM-SIZE _RSHSP-MUL
        _RSHSP-ADD DUP _RSHSP-BYTES ! _RSHSP-TAKE _RSHSP-CLAIM-BANK !
    _RSHSP-P @ _RTHP.CLAIMS-A @ _RSHSP-CLAIM-BANK @ _RSHSP-P @ _RTHP.CLAIMS-USED @ MOVE
    _RSHSP-P @ _RTHP.CLAIMS-USED @ _RSHSP-CLAIM-U !
    _RSHSP-RESULT @ RSHPL-RESULT.CLAIMS @ 0 ?DO
        _RSHSP-CLAIMS @ I RSHPL-CLAIM-SIZE * + _RSHSP-ITEM !
        I _RSHSP-ITEM @ RSHPL-CLAIM.ROW @ _RSHSP-ITEM @ RSHPL-CLAIM.COL @
        _RSHSP-ITEM @ RSHPL-CLAIM.HEIGHT @ _RSHSP-ITEM @ RSHPL-CLAIM.WIDTH @ _RSHSP-CLAIM-RECT
    LOOP
    _RSHSP-CLAIM-U @ _RSHSP-BASE-CLAIM-U !
    _RSHSP-N @ 0 ?DO I _RSHSP-ENTRY DUP SHME.KIND @ SHM-K-PANE = IF
        I SWAP _RSHSP-CONTENT-RECT _RSHSP-CLAIM-RECT ELSE DROP THEN LOOP
    _RSHSP-P @ _RTHP.ROWS @ 1+ 8 _RSHSP-MUL _RSHSP-TAKE _RSHSP-HEADS !
    _RSHSP-CLAIM-U @ RUCL-CLAIM-SIZE / 2 _RSHSP-MUL RGRP-EVENT-SIZE _RSHSP-MUL
        DUP _RSHSP-EVENTS-U ! _RSHSP-TAKE _RSHSP-EVENTS !
    _RSHSP-P @ _RTHP.COLS @ 1+ 16 _RSHSP-MUL _RSHSP-TAKE _RSHSP-DIFF !
    RGRP-REQUEST-SIZE _RSHSP-TAKE _RSHSP-GQ ! ;

: _RSHSP-GLYPH ( region -- )
    _RSHSP-REGION !
    RTE-FAMILY-GLYPH _RSHSP-FAMILY!
    _RSHSP-CURSOR @ _RSHSP-SAVED !
    _RSHSP-REGION @ _RTE-IR.FLAGS @ RTE-REGION-CLIPPED AND IF
        _RSHSP-REGION @ _RTE-IR.CLIP-COLS @ _RSHSP-REGION @ _RTE-IR.CLIP-ROWS @
    ELSE _RSHSP-P @ _RTHP.COLS @ _RSHSP-P @ _RTHP.ROWS @ THEN
        _RSHSP-MUL _RSHSP-GCELLS !
    _RSHSP-GCELLS @ RTE-GLYPH-RUN-PLAN-ITEM-SIZE _RSHSP-MUL _RSHSP-TAKE _RSHSP-GITEMS !
    _RSHSP-GCELLS @ 16 _RSHSP-MUL _RSHSP-TAKE _RSHSP-GREFS !
    _RSHSP-GCELLS @ 4 _RSHSP-MUL
        _RSHSP-P @ _RTHP.GLYPH-TEXT-U @ MIN _RSHSP-GLIMIT !
    _RSHSP-GLIMIT @ _RSHSP-TAKE _RSHSP-GTEXT !
    _RSHSP-GQ @ RGRP-REQUEST-CLEAR
    _RSHSP-P @ _RTHP.OWNER @ _RSHSP-P @ _RTHP.OWNER-GEN @
    _RSHSP-REGION @ _RTE-IR.ID @ _RSHSP-NEXT-ID @ _RSHSP-GQ @ RGRP-REQUEST-IDENTITY!
    _RSHSP-P @ _RTHP.COLS @ _RSHSP-P @ _RTHP.ROWS @
    _RSHSP-REGION @ _RTE-IR.X @ _RSHSP-REGION @ _RTE-IR.Y @
    _RSHSP-REGION @ _RTE-IR.COLS @ _RSHSP-REGION @ _RTE-IR.ROWS @
    _RSHSP-REGION @ _RTE-IR.CLIP-X @ _RSHSP-REGION @ _RTE-IR.CLIP-Y @
    _RSHSP-REGION @ _RTE-IR.CLIP-COLS @ _RSHSP-REGION @ _RTE-IR.CLIP-ROWS @
    _RSHSP-REGION @ _RTE-IR.Z @ _RSHSP-REGION @ _RTE-IR.FLAGS @
    0 _RSHSP-GQ @ RGRP-REQUEST-REGION!
    _RSHSP-P @ _RTHP.LIMITS RTE-LIMITS-GLYPH-RUN-BYTES@ _RSHSP-GQ @ RGRP-REQUEST-LIMIT!
    _RSHSP-CLAIM-BANK @ _RSHSP-CLAIM-U @ _RSHSP-GQ @ RGRP-REQUEST-CLAIMS!
    _RSHSP-HEADS @ _RSHSP-P @ _RTHP.ROWS @ 1+ 8 *
    _RSHSP-EVENTS @ _RSHSP-EVENTS-U @
    _RSHSP-DIFF @ _RSHSP-P @ _RTHP.COLS @ 1+ 16 *
    _RSHSP-GQ @ RGRP-REQUEST-WORK!
    _RSHSP-PLAN @ RTE-GLYPH-RUN-PLAN-SIZE
    _RSHSP-GITEMS @ _RSHSP-GCELLS @ RTE-GLYPH-RUN-PLAN-ITEM-SIZE *
    _RSHSP-GREFS @ _RSHSP-GCELLS @ 16 * _RSHSP-GTEXT @ _RSHSP-GLIMIT @
    _RSHSP-GQ @ RGRP-REQUEST-OUTPUT!
    \ MENU-CLAIMS already counts records; CLAIMS-USED is the byte extent.
    _RSHSP-P @ _RTHP.MENU-CLAIMS @
    _RSHSP-GQ @ RGRP-BUILD-PAIRED RGRP-S-OK = _RSHSP-CHECK
    DUP IF 1 _RSHSP-ADD _RSHSP-NEXT-ID ! ELSE DROP THEN
    2DROP _RSHSP-GUSED ! _RSHSP-GCOUNT !
    _RSHSP-GCOUNT @ 0= IF
        -1 _RSHSP-FAMILY-N +! _RSHSP-SAVED @ RTE-GLYPH-RUN-PLAN-SIZE - _RSHSP-CURSOR ! EXIT
    THEN
    \ Compact the transient worst-case slots in place. MOVE is overlap-safe;
    \ every destination is at or before its corresponding source.
    _RSHSP-GITEMS @ _RSHSP-GCOUNT @ RTE-GLYPH-RUN-PLAN-ITEM-SIZE * + _RSHSP-NEW !
    _RSHSP-GREFS @ _RSHSP-NEW @ _RSHSP-GCOUNT @ 16 * MOVE
    _RSHSP-NEW @ _RSHSP-FAMILY @ _RTE-FE.REFS-A !
    _RSHSP-GCOUNT @ 16 * _RSHSP-FAMILY @ _RTE-FE.REFS-U !
    _RSHSP-NEW @ _RSHSP-GCOUNT @ 16 * + _RSHSP-NEW !
    _RSHSP-GTEXT @ _RSHSP-NEW @ _RSHSP-GUSED @ MOVE
    _RSHSP-NEW @ _RSHSP-GUSED @ _RSHSP-FAMILY-BYTES!
    _RSHSP-NEW @ _RSHSP-GUSED @ _RSHSP-ALIGN + _RSHSP-CURSOR ! ;
: _RSHSP-GLYPHS ( -- )
    _RSHSP-GLYPH-WORK
    _RSHSP-P @ _RTHP.REGION @ _RSHSP-REGION@ _RSHSP-GLYPH
    _RSHSP-GCOUNT @ 0= IF
        _RSHSP-CATALOG @ _RTE-RC.REGIONS-A @ DUP 96 + SWAP
            _RSHSP-CATALOG @ _RTE-RC.REGIONS-U @ 96 - MOVE
        -96 _RSHSP-CATALOG @ _RTE-RC.REGIONS-U +!
    THEN
    _RSHSP-BASE-CLAIM-U @ _RSHSP-CLAIM-U !
    _RSHSP-MAP-U @ RSHMM-ENTRY-SIZE / 0 ?DO
        _RSHSP-MAP @ I RSHMM-ENTRY-SIZE * + RSHMM.CONTENT-REGION @ _RSHSP-REGION@ _RSHSP-GLYPH
    LOOP ;

VARIABLE _RSHSP-BANK-USED VARIABLE _RSHSP-CLONE-U
VARIABLE _RSHSP-META-U VARIABLE _RSHSP-PACK-A VARIABLE _RSHSP-PACK-U
VARIABLE _RSHSP-V-S VARIABLE _RSHSP-V-B VARIABLE _RSHSP-V-CAP
VARIABLE _RSHSP-V-U VARIABLE _RSHSP-V-BATCH VARIABLE _RSHSP-V-CAT
VARIABLE _RSHSP-V-ENTRY VARIABLE _RSHSP-V-PLAN
VARIABLE _RSHSP-V-NEXT VARIABLE _RSHSP-V-OBJECT VARIABLE _RSHSP-V-STRIDE
: _RSHSP-CAPACITY ( bank sidecar -- capacity|0 )
    >R DUP R@ _RSHSP.A @ = IF DROP R> _RSHSP.A-U @ EXIT THEN
    R@ _RSHSP.B @ = IF R> _RSHSP.B-U @ ELSE R> DROP 0 THEN ;
: _RSHSP-IN-BANK? ( a u -- flag )
    DUP 0= IF DROP 0= EXIT THEN
    2DUP MSPAN-NONWRAPPING? 0= IF 2DROP 0 EXIT THEN
    OVER _RSHSP-V-B @ DUP RSHSP-BANK.BATCH @ + U< IF 2DROP 0 EXIT THEN
    + _RSHSP-V-B @ _RSHSP-V-U @ + U> 0= ;
: _RSHSP-OFFSET-SPAN? ( offset bytes -- flag )
    DUP 0= IF DROP 0= EXIT THEN
    OVER RSHSP-BANK-HEADER-SIZE U< IF 2DROP 0 EXIT THEN
    OVER _RSHSP-V-U @ U> IF 2DROP 0 EXIT THEN
    _RSHSP-V-U @ ROT - U> 0= ;
: _RSHSP-BANK-GRAPH? ( -- flag )
    _RSHSP-V-B @ RSHSP-BANK.BATCH @ DUP 7 AND IF DROP 0 EXIT THEN
    DUP RTE-FAMILY-BATCH-SIZE _RSHSP-OFFSET-SPAN? 0= IF DROP 0 EXIT THEN
    _RSHSP-V-B @ + _RSHSP-V-BATCH !
    _RSHSP-V-BATCH @ _RTE-FB.CATALOG-U @ RTE-REGION-CATALOG-SIZE <> IF 0 EXIT THEN
    _RSHSP-V-BATCH @ _RTE-FB.CATALOG-A @ DUP RTE-REGION-CATALOG-SIZE
        _RSHSP-IN-BANK? 0= IF DROP 0 EXIT THEN _RSHSP-V-CAT !
    _RSHSP-V-CAT @ DUP _RTE-RC.REGIONS-A @ SWAP _RTE-RC.REGIONS-U @
        _RSHSP-IN-BANK? 0= IF 0 EXIT THEN
    _RSHSP-V-BATCH @ DUP _RTE-FB.FAMILIES-A @ SWAP _RTE-FB.FAMILIES-U @
        _RSHSP-IN-BANK? 0= IF 0 EXIT THEN
    _RSHSP-V-BATCH @ _RTE-FB.FAMILIES-U @ RTE-FAMILY-ENTRY-SIZE MOD IF 0 EXIT THEN
    _RSHSP-V-BATCH @ _RTE-FB.FAMILIES-U @ RTE-FAMILY-ENTRY-SIZE / 0 ?DO
        _RSHSP-V-BATCH @ _RTE-FB.FAMILIES-A @ I RTE-FAMILY-ENTRY-SIZE * + _RSHSP-V-ENTRY !
        _RSHSP-V-ENTRY @ _RTE-FE.KIND @ RTE-FAMILY-PLAN-SIZE DUP 0= IF DROP 0 UNLOOP EXIT THEN
        _RSHSP-V-ENTRY @ _RTE-FE.PLAN-U @ <> IF 0 UNLOOP EXIT THEN
        _RSHSP-V-ENTRY @ DUP _RTE-FE.PLAN-A @ SWAP _RTE-FE.PLAN-U @
            _RSHSP-IN-BANK? 0= IF 0 UNLOOP EXIT THEN
        _RSHSP-V-ENTRY @ RTE-FAMILY-ITEMS@ _RSHSP-IN-BANK? 0= IF 0 UNLOOP EXIT THEN
        _RSHSP-V-ENTRY @ DUP _RTE-FE.BYTES-A @ SWAP _RTE-FE.BYTES-U @
            _RSHSP-IN-BANK? 0= IF 0 UNLOOP EXIT THEN
        _RSHSP-V-ENTRY @ DUP _RTE-FE.REFS-A @ SWAP _RTE-FE.REFS-U @
            _RSHSP-IN-BANK? 0= IF 0 UNLOOP EXIT THEN
        _RSHSP-V-ENTRY @ RTE-FAMILY-REGIONS@ _RSHSP-IN-BANK? 0= IF 0 UNLOOP EXIT THEN
    LOOP
    _RSHSP-V-BATCH @ RTE-FAMILY-BATCH-VALID? ;
: _RSHSP-BANK-FRONTIERS? ( -- flag )
    _RSHSP-V-CAT @ _RTE-RC.REGIONS-U @ 96 U< IF 0 EXIT THEN
    _RSHSP-V-CAT @ DUP _RTE-RC.REGIONS-A @ SWAP _RTE-RC.REGIONS-U @ + 96 - _RTE-IR.ID @
        1 _RTHP-U32+? 0= IF DROP 0 EXIT THEN
    _RSHSP-V-B @ RSHSP-BANK.NEXT-REGION @ <> IF 0 EXIT THEN
    0 _RSHSP-V-OBJECT !
    _RSHSP-V-BATCH @ _RTE-FB.FAMILIES-U @ RTE-FAMILY-ENTRY-SIZE / 0 ?DO
        _RSHSP-V-BATCH @ _RTE-FB.FAMILIES-A @ I RTE-FAMILY-ENTRY-SIZE * + _RSHSP-V-ENTRY !
        _RSHSP-V-ENTRY @ _RTE-FE.KIND @ RTE-FAMILY-SERIES <> IF
            _RSHSP-V-ENTRY @ _RTE-FE.KIND @ RTE-FAMILY-ITEM-SIZE _RSHSP-V-STRIDE !
            _RSHSP-V-ENTRY @ RTE-FAMILY-ITEMS@ _RSHSP-V-STRIDE @ / 0 ?DO
                DUP I _RSHSP-V-STRIDE @ * +
                _RSHSP-V-ENTRY @ _RTE-FE.KIND @ RTE-FAMILY-GLYPH <> IF 16 + THEN
                @ DUP _RTHP-U32? 0= IF DROP DROP 0 UNLOOP UNLOOP EXIT THEN
                _RSHSP-V-OBJECT @ MAX _RSHSP-V-OBJECT !
            LOOP DROP
        THEN
    LOOP
    _RSHSP-V-OBJECT @ 1 _RTHP-U32+? 0= IF DROP 0 EXIT THEN
    _RSHSP-V-B @ RSHSP-BANK.NEXT-OBJECT @ = ;

: _RSHSP-BANK-VALID? ( bank sidecar -- flag )
    _RSHSP-V-S ! _RSHSP-V-B !
    _RSHSP-V-B @ _RSHSP-V-S @ _RSHSP-CAPACITY DUP RSHSP-BANK-HEADER-SIZE U< IF DROP 0 EXIT THEN
        _RSHSP-V-CAP !
    _RSHSP-V-B @ RSHSP-BANK.USED @ DUP _RSHSP-V-U !
    DUP RSHSP-BANK-HEADER-SIZE U< SWAP _RSHSP-V-CAP @ U> OR IF 0 EXIT THEN
    _RSHSP-V-U @ DUP 7 AND SWAP _RTHP-U32? 0= OR IF 0 EXIT THEN
    _RSHSP-V-B @ RSHSP-BANK.TARGET @ 0=
    _RSHSP-V-B @ RSHSP-BANK.DRAW @ 0= OR
    _RSHSP-V-B @ RSHSP-BANK.OWNER @ 0= OR
    _RSHSP-V-B @ RSHSP-BANK.GENERATION @ 0= OR IF 0 EXIT THEN
    RSHSP-BANK-HEADER-SIZE _RSHSP-V-NEXT !
    80 16 DO
        _RSHSP-V-B @ I + DUP @ SWAP 8 + @
        2DUP _RSHSP-OFFSET-SPAN? 0= IF 2DROP 0 UNLOOP EXIT THEN
        DUP IF
            SWAP _RSHSP-V-NEXT @ <> IF DROP 0 UNLOOP EXIT THEN
            7 + -8 AND _RSHSP-V-NEXT +!
        ELSE 2DROP THEN
    16 +LOOP
    _RSHSP-V-B @ RSHSP-BANK.BATCH @ _RSHSP-V-NEXT @ <> IF 0 EXIT THEN
    _RSHSP-V-B @ RSHSP-BANK.CORRELATIONS-U @ RSHPL-CORRELATION-SIZE MOD
    _RSHSP-V-B @ RSHSP-BANK.MEMBERSHIP-U @ RSHMM-ENTRY-SIZE MOD OR IF 0 EXIT THEN
    _RSHSP-V-B @ RSHSP-BANK.MODEL @ _RSHSP-V-B @ +
    _RSHSP-V-B @ RSHSP-BANK.MODEL-U @ SHSN-FROZEN-VALIDATE SHSN-S-OK <> IF 0 EXIT THEN
    _RSHSP-BANK-GRAPH? 0= IF 0 EXIT THEN
    _RSHSP-V-B @ DUP RSHSP-BANK.MODEL @ +
    DUP SHM.WIDTH @ _RSHSP-V-CAT @ _RTE-RC.SURFACE-COLS @ <>
    SWAP SHM.HEIGHT @ _RSHSP-V-CAT @ _RTE-RC.SURFACE-ROWS @ <> OR IF 0 EXIT THEN
    _RSHSP-V-BATCH @ RSHFC-MEASURE RSHFC-S-OK <> IF DROP 0 EXIT THEN
        _RSHSP-V-NEXT @ + _RSHSP-V-U @ <> IF 0 EXIT THEN
    _RSHSP-BANK-FRONTIERS? 0= IF 0 EXIT THEN
    _RSHSP-V-CAT @ _RTE-RC.OWNER @ _RSHSP-V-B @ RSHSP-BANK.OWNER @ <>
    _RSHSP-V-CAT @ _RTE-RC.GENERATION @ _RSHSP-V-B @ RSHSP-BANK.GENERATION @ <> OR
    _RSHSP-V-BATCH @ _RTE-FB.SURFACE-GENERATION @ _RSHSP-V-B @ RSHSP-BANK.DRAW @ <> OR 0= ;

: _RSHSP-PACK ( source bytes offset-field -- )
    >R _RSHSP-PACK-U ! _RSHSP-PACK-A !
    _RSHSP-PACK-U @ R@ 8 + !
    _RSHSP-PACK-U @ IF
        _RSHSP-BANK-USED @ R@ !
        _RSHSP-PACK-A @ _RSHSP-BANK @ _RSHSP-BANK-USED @ + _RSHSP-PACK-U @ MOVE
        _RSHSP-PACK-U @ _RSHSP-ALIGN _RSHSP-BANK-USED +!
    ELSE 0 R@ ! THEN R> DROP ;
: _RSHSP-FREEZE ( -- )
    _RSHSP-BATCH @ RSHFC-MEASURE RSHFC-S-OK = _RSHSP-CHECK _RSHSP-CLONE-U !
    RSHSP-BANK-HEADER-SIZE _RSHSP-MU @ _RSHSP-ALIGN _RSHSP-ADD
    _RSHSP-RESULT @ RSHPL-RESULT.CORRELATIONS @ RSHPL-CORRELATION-SIZE _RSHSP-MUL _RSHSP-ADD
    _RSHSP-RESULT @ RSHPL-RESULT.ACTION-BYTES @ _RSHSP-ALIGN _RSHSP-ADD
    _RSHSP-MAP-U @ _RSHSP-ALIGN _RSHSP-ADD DUP _RSHSP-META-U !
    _RSHSP-CLONE-U @ _RSHSP-ADD DUP _RSHSP-S @ _RSHSP.BANK-BYTES !
    DUP _RSHSP-BANK-CAP @ U> IF DROP RTE-S-CAPACITY THROW THEN
    _RSHSP-BANK @ SWAP 0 FILL
    RSHSP-BANK-HEADER-SIZE _RSHSP-BANK-USED !
    _RSHSP-M @ _RSHSP-MU @ _RSHSP-BANK @ RSHSP-BANK.MODEL _RSHSP-PACK
    _RSHSP-CORR @ _RSHSP-RESULT @ RSHPL-RESULT.CORRELATIONS @ RSHPL-CORRELATION-SIZE *
        _RSHSP-BANK @ RSHSP-BANK.CORRELATIONS _RSHSP-PACK
    _RSHSP-ACTIONS @ _RSHSP-RESULT @ RSHPL-RESULT.ACTION-BYTES @
        _RSHSP-BANK @ RSHSP-BANK.ACTIONS _RSHSP-PACK
    _RSHSP-MAP @ _RSHSP-MAP-U @ _RSHSP-BANK @ RSHSP-BANK.MEMBERSHIP _RSHSP-PACK
    _RSHSP-BANK-USED @ _RSHSP-BANK @ RSHSP-BANK.BATCH !
    _RSHSP-BATCH @ _RSHSP-BANK @ _RSHSP-BANK-USED @ +
        _RSHSP-BANK-CAP @ _RSHSP-BANK-USED @ - RSHFC-COPY
        RSHFC-S-OK = _RSHSP-CHECK _RSHSP-BANK-USED +!
    _RSHSP-P @ _RTHP.TARGET-PENDING @ _RSHSP-BANK @ RSHSP-BANK.TARGET !
    _RSHSP-P @ _RTHP.SOURCE-DRAW @ _RSHSP-BANK @ RSHSP-BANK.DRAW !
    _RSHSP-P @ _RTHP.OWNER @ _RSHSP-BANK @ RSHSP-BANK.OWNER !
    _RSHSP-P @ _RTHP.OWNER-GEN @ _RSHSP-BANK @ RSHSP-BANK.GENERATION !
    _RSHSP-ADMISSION @ _RTE-FA.LAST-REGION @ 1 _RSHSP-ADD _RSHSP-BANK @ RSHSP-BANK.NEXT-REGION !
    _RSHSP-ADMISSION @ _RTE-FA.OBJECT-LAST @ 1 _RSHSP-ADD _RSHSP-BANK @ RSHSP-BANK.NEXT-OBJECT !
    _RSHSP-BANK-USED @ _RSHSP-BANK @ RSHSP-BANK.USED !
    _RSHSP-BANK @ _RSHSP-S @ _RSHSP-BANK-VALID? _RSHSP-CHECK ;
: _RSHSP-BUILD ( -- )
    _RSHSP-P @ _RTHP.TARGET-PENDING @ _RSHSP-CHECK
    0 _RSHSP-S @ _RSHSP.WORK-USED ! 0 _RSHSP-S @ _RSHSP.BANK-BYTES !
    _RSHSP-S @ _RSHSP.WORK @ _RSHSP-CURSOR !
    _RSHSP-S @ _RSHSP.WORK @ _RSHSP-S @ _RSHSP.WORK-U @ + _RSHSP-END !
    _RSHSP-P @ _RTHP.SOURCE-DRAW @ _RSHSP-S @ _RSHSP.SOURCE @ SHSN-SNAPSHOT-FOR@
        SHSN-S-OK = _RSHSP-CHECK _RSHSP-MU ! _RSHSP-M !
    _RSHSP-M @ SHM.ENTRY-LIMIT @ _RSHSP-S @ _RSHSP.MAX-ENTRIES @ U> IF RTE-S-CAPACITY THROW THEN
    _RSHSP-MU @ _RSHSP-M @ SHM.ENTRY-LIMIT @ SHM-ENTRY-SIZE * SHM-HEADER-SIZE + -
        _RSHSP-S @ _RSHSP.MAX-TEXT @ U> IF RTE-S-CAPACITY THROW THEN
    _RSHSP-M @ SHM.COUNT @ DUP _RSHSP-N ! _RSHSP-S @ _RSHSP.MAX-ENTRIES @ U> IF RTE-S-CAPACITY THROW THEN
    _RSHSP-M @ SHM.WIDTH @ _RSHSP-P @ _RTHP.COLS @ = _RSHSP-CHECK
    _RSHSP-M @ SHM.HEIGHT @ _RSHSP-P @ _RTHP.ROWS @ = _RSHSP-CHECK
    _RSHSP-M @ _RSHSP-MU @ _RSHSP-COPY _RSHSP-M !
    _RSHSP-ALLOCATE-PLAN _RSHSP-CATALOG!
    _RSHSP-APP-CONTROLS _RSHSP-SERIES _RSHSP-INSTRUMENTS _RSHSP-STATICS _RSHSP-PANE-FAMILY
    _RSHSP-GLYPHS
    1 _RSHSP-BATCH @ _RTE-FB.ABI !
    _RSHSP-CATALOG @ _RSHSP-BATCH @ _RTE-FB.CATALOG-A !
    RTE-REGION-CATALOG-SIZE _RSHSP-BATCH @ _RTE-FB.CATALOG-U !
    _RSHSP-FAMILIES @ _RSHSP-BATCH @ _RTE-FB.FAMILIES-A !
    _RSHSP-FAMILY-N @ RTE-FAMILY-ENTRY-SIZE * _RSHSP-BATCH @ _RTE-FB.FAMILIES-U !
    _RSHSP-P @ _RTHP.ATTEMPT @ _RSHSP-BATCH @ _RTE-FB.ATTEMPT !
    _RSHSP-P @ _RTHP.SOURCE-GEN @ _RSHSP-BATCH @ _RTE-FB.SOURCE-GENERATION !
    _RSHSP-P @ _RTHP.SOURCE-DRAW @ _RSHSP-BATCH @ _RTE-FB.SURFACE-GENERATION !
    _RSHSP-BATCH @ _RSHSP-ADMISSION @ _RSHSP-S @ _RSHSP.SHELL @
        RTE-FAMILY-BATCH-PREFLIGHT DUP IF THROW ELSE DROP THEN
    _RSHSP-FREEZE ;

\ Full caller capacities are protected, including inactive banks.  Guards
\ precede every constructor store and are repeated before a new preparation.
CREATE _RSHSP-SPANS 64 ALLOT
VARIABLE _RSHSP-LIVE-PROOF
VARIABLE _RSHSP-IA VARIABLE _RSHSP-IU VARIABLE _RSHSP-ISOURCE VARIABLE _RSHSP-ISHELL
VARIABLE _RSHSP-IWORK VARIABLE _RSHSP-IWORKU VARIABLE _RSHSP-IBA VARIABLE _RSHSP-IBAU
VARIABLE _RSHSP-IBB VARIABLE _RSHSP-IBBU VARIABLE _RSHSP-IEMAX VARIABLE _RSHSP-ITMAX
: _RSHSP-12DROP ( x x x x x x x x x x x x -- ) 2DROP 2DROP 2DROP 2DROP 2DROP 2DROP ;
: _RSHSP-SPAN! ( a u i -- ) 16 * _RSHSP-SPANS + >R R@ 8 + ! R> ! ;
: _RSHSP-SPAN@ ( i -- a u ) 16 * _RSHSP-SPANS + DUP @ SWAP 8 + @ ;
: _RSHSP-DISJOINT? ( a u -- flag ) _RSHSP-IA @ _RSHSP-IU @ MSPAN-OVERLAP? 0= ;
: _RSHSP-EXTERNAL? ( a u -- flag )
    _RSHSP-IU ! _RSHSP-IA !
    _RSHSP-IA @ _RSHSP-IU @ _RSHSP-P @ RTHP-SIZE MSPAN-OVERLAP? IF 0 EXIT THEN
    _RSHSP-IA @ _RSHSP-IU @ _RSHSP-P @ DUP _RTHP.ARENA-A @ SWAP _RTHP.ARENA-U @
        MSPAN-OVERLAP? IF 0 EXIT THEN
    _RSHSP-IA @ _RSHSP-IU @ _RSHSP-ISHELL @ RTE-SHELL-FACADE-SIZE MSPAN-OVERLAP? IF 0 EXIT THEN
    _RSHSP-IA @ _RSHSP-IU @ _RSHSP-P @ _RTHP.FACADE @ RTE-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    _RSHSP-LIVE-PROOF @ IF
        _RSHSP-IA @ _RSHSP-IU @ _RSHSP-ISOURCE @ SHSN-LIVE-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
        _RSHSP-IA @ _RSHSP-IU @ _SHSN-I-AUTHORITY? 0= IF 0 EXIT THEN
    ELSE
        _RSHSP-IA @ _RSHSP-IU @ _RSHSP-ISOURCE @ SHSN-SOURCE-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    THEN
    _RSHSP-P @ _RTHP.ADAPTER @ ['] _RSHSP-DISJOINT? _RUHA-SAFE-PROVE? ;
: _RSHSP-SPANS? ( -- flag )
    4 0 DO
        I _RSHSP-SPAN@ _RSHSP-SPAN? 0= IF 0 UNLOOP EXIT THEN
        I _RSHSP-SPAN@ _RSHSP-EXTERNAL? 0= IF 0 UNLOOP EXIT THEN
        I 0 ?DO I _RSHSP-SPAN@ _RSHSP-IA @ _RSHSP-IU @ MSPAN-OVERLAP? IF
            0 UNLOOP UNLOOP EXIT THEN LOOP
    LOOP -1 ;
: _RSHSP-HEADER? ( sidecar -- flag )
    DUP RSHSP-SIZE _RSHSP-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RSHSP.MAGIC @ _RSHSP-MAGIC <>
    OVER _RSHSP.SIZE @ RSHSP-SIZE <> OR
    OVER _RSHSP.SELF @ 2 PICK <> OR IF DROP 0 EXIT THEN
    DUP _RSHSP.PRODUCER @ RTHP-SIZE _RSHSP-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RSHSP.SOURCE @ SHSN-SIZE _RSHSP-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RSHSP.SHELL @ RTE-SHELL-FACADE-SIZE _RSHSP-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RSHSP.MAX-ENTRIES @ _RTHP-POS-U32? 0=
    OVER _RSHSP.MAX-TEXT @ _RTHP-POS-U32? 0= OR IF DROP 0 EXIT THEN
    DUP _RSHSP.WORK @ OVER _RSHSP.WORK-U @ _RSHSP-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RSHSP.A @ OVER _RSHSP.A-U @ _RSHSP-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RSHSP.B @ OVER _RSHSP.B-U @ _RSHSP-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RSHSP.A-U @ RSHSP-BANK-HEADER-SIZE U<
    OVER _RSHSP.B-U @ RSHSP-BANK-HEADER-SIZE U< OR IF DROP 0 EXIT THEN
    DUP _RSHSP.ACTIVE @ ?DUP IF OVER _RSHSP-CAPACITY 0= IF DROP 0 EXIT THEN THEN
    DUP _RSHSP.PENDING @ ?DUP IF
        OVER _RSHSP-CAPACITY 0= IF DROP 0 EXIT THEN
        DUP _RSHSP.PENDING @ OVER _RSHSP.ACTIVE @ = IF DROP 0 EXIT THEN
    THEN
    DUP _RSHSP.ACTIVE @ 0= OVER _RSHSP.ACTIVE-TARGET @ 0= <>
    OVER _RSHSP.ACTIVE @ 0= 2 PICK _RSHSP.ACTIVE-DRAW @ 0= <> OR
    OVER _RSHSP.PENDING @ 0= 2 PICK _RSHSP.PENDING-TARGET @ 0= <> OR
    OVER _RSHSP.PENDING @ 0= 2 PICK _RSHSP.PENDING-DRAW @ 0= <> OR IF DROP 0 EXIT THEN
    DROP -1 ;
: _RSHSP-AUTHORITY? ( sidecar -- flag )
    DUP _RSHSP-HEADER? 0= IF DROP 0 EXIT THEN
    DUP _RSHSP.PRODUCER @ RTHP-SIZE _RSHSP-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RSHSP.SOURCE @ SHSN-SIZE _RSHSP-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RSHSP.SHELL @ RTE-SHELL-FACADE-SIZE _RSHSP-SPAN? 0= IF DROP 0 EXIT THEN
    _RSHSP-S !
    _RSHSP-S @ _RSHSP.PRODUCER @ _RSHSP-P !
    _RSHSP-S @ _RSHSP.SOURCE @ _RSHSP-ISOURCE !
    _RSHSP-S @ _RSHSP.SHELL @ _RSHSP-ISHELL !
    _RSHSP-P @ RTHP-SIZE _RSHSP-SPAN? 0= IF 0 EXIT THEN
    _RSHSP-ISOURCE @ SHSN-SIZE _RSHSP-SPAN? 0= IF 0 EXIT THEN
    _RSHSP-ISHELL @ RTE-SHELL-FACADE-SIZE _RSHSP-SPAN? 0= IF 0 EXIT THEN
    _RSHSP-P @ DUP _RTHP.MAGIC @ _RTHP-MAGIC <>
    OVER _RTHP.SIZE @ RTHP-SIZE <> OR
    OVER _RTHP.SELF @ 2 PICK <> OR IF DROP 0 EXIT THEN DROP
    _RSHSP-P @ DUP _RTHP.ARENA-A @ SWAP _RTHP.ARENA-U @ _RSHSP-SPAN? 0= IF 0 EXIT THEN
    _RSHSP-P @ _RTHP.FACADE @ RTE-VALID? 0= IF 0 EXIT THEN
    _RSHSP-P @ _RTHP.ADAPTER @ RUHA-VALID? 0= IF 0 EXIT THEN
    _RSHSP-ISOURCE @ SHSN-VALID? 0= IF 0 EXIT THEN
    _RSHSP-ISHELL @ RTE-SHELL-VALID? 0= IF 0 EXIT THEN
    _RSHSP-ISHELL @ _RTE-SH.BASE @ _RSHSP-P @ _RTHP.FACADE @ <> IF 0 EXIT THEN
    _RSHSP-S @ RSHSP-SIZE 0 _RSHSP-SPAN!
    _RSHSP-S @ DUP _RSHSP.WORK @ SWAP _RSHSP.WORK-U @ 1 _RSHSP-SPAN!
    _RSHSP-S @ DUP _RSHSP.A @ SWAP _RSHSP.A-U @ 2 _RSHSP-SPAN!
    _RSHSP-S @ DUP _RSHSP.B @ SWAP _RSHSP.B-U @ 3 _RSHSP-SPAN!
    _RSHSP-SPANS? ;
: RSHSP-VALID? ( sidecar -- flag )
    DUP _RSHSP-HEADER? 0= IF DROP 0 EXIT THEN
    0 _RSHSP-LIVE-PROOF ! _RSHSP-AUTHORITY? ;

: _RSHSP-ABORT ( sidecar -- )
    0 OVER _RSHSP.PENDING ! 0 OVER _RSHSP.PENDING-TARGET ! 0 SWAP _RSHSP.PENDING-DRAW ! ;
: _RSHSP-RETIRE ( sidecar -- )
    DUP _RSHSP-ABORT 0 OVER _RSHSP.ACTIVE !
    0 OVER _RSHSP.ACTIVE-TARGET ! 0 SWAP _RSHSP.ACTIVE-DRAW ! ;
: _RSHSP-PENDING? ( -- flag )
    _RSHSP-S @ _RSHSP.PENDING @ DUP 0= IF DROP -1 EXIT THEN _RSHSP-BANK !
    _RSHSP-BANK @ _RSHSP-S @ _RSHSP-BANK-VALID? 0= IF 0 EXIT THEN
    _RSHSP-S @ _RSHSP.PENDING-TARGET @ _RSHSP-P @ _RTHP.TARGET-PENDING @ <>
    _RSHSP-BANK @ RSHSP-BANK.TARGET @ _RSHSP-P @ _RTHP.TARGET-PENDING @ <> OR
    _RSHSP-S @ _RSHSP.PENDING-DRAW @ _RSHSP-P @ _RTHP.SOURCE-DRAW @ <> OR
    _RSHSP-BANK @ RSHSP-BANK.DRAW @ _RSHSP-P @ _RTHP.SOURCE-DRAW @ <> OR
    _RSHSP-BANK @ RSHSP-BANK.OWNER @ _RSHSP-P @ _RTHP.OWNER @ <> OR
    _RSHSP-BANK @ RSHSP-BANK.GENERATION @ _RSHSP-P @ _RTHP.OWNER-GEN @ <> OR 0= ;
: _RSHSP-FRONTIERS! ( -- )
    \ Hidden acknowledged objects have consumed their IDs even when a newer
    \ draw supersedes them before reveal. Base projection may reserve more
    \ IDs than the shell projection, so neither frontier may move backwards.
    _RSHSP-BANK @ RSHSP-BANK.NEXT-REGION @
    _RSHSP-P @ _RTHP.NEXT-REGION @ MAX _RSHSP-P @ _RTHP.NEXT-REGION !
    _RSHSP-BANK @ RSHSP-BANK.NEXT-OBJECT @
    _RSHSP-P @ _RTHP.NEXT-OBJECT @ MAX _RSHSP-P @ _RTHP.NEXT-OBJECT ! ;
: _RSHSP-START-ACK ( -- status )
    _RSHSP-PENDING? 0= IF RTE-S-INVALID EXIT THEN
    _RSHSP-S @ _RSHSP.PENDING @ IF _RSHSP-FRONTIERS! THEN
    RTE-S-OK ;
: _RSHSP-PUBLISH ( -- )
    \ PUBLISH-CHECK already proved the old pending target. Core has now
    \ installed that exact target. Only bounded scalar stores remain.
    _RSHSP-S @ _RSHSP.PENDING @ DUP 0= IF DROP _RSHSP-S @ _RSHSP-RETIRE EXIT THEN
    _RSHSP-BANK !
    _RSHSP-S @ _RSHSP.PENDING-TARGET @ _RSHSP-P @ _RTHP.TARGET-ACTIVE @ <> IF
        _RSHSP-S @ _RSHSP-RETIRE EXIT THEN
    _RSHSP-BANK @ _RSHSP-S @ _RSHSP.ACTIVE !
    _RSHSP-S @ _RSHSP.PENDING-TARGET @ _RSHSP-S @ _RSHSP.ACTIVE-TARGET !
    _RSHSP-S @ _RSHSP.PENDING-DRAW @ _RSHSP-S @ _RSHSP.ACTIVE-DRAW !
    _RSHSP-FRONTIERS!
    _RSHSP-S @ _RSHSP-ABORT ;
: _RSHSP-CURRENT? ( -- flag )
    _RSHSP-S @ _RSHSP.ACTIVE @ DUP 0= IF DROP -1 EXIT THEN _RSHSP-BANK !
    _RSHSP-BANK @ _RSHSP-S @ _RSHSP-BANK-VALID? 0= IF 0 EXIT THEN
    _RSHSP-S @ _RSHSP.ACTIVE-TARGET @ _RSHSP-P @ _RTHP.TARGET-ACTIVE @ <>
    _RSHSP-BANK @ RSHSP-BANK.TARGET @ _RSHSP-P @ _RTHP.TARGET-ACTIVE @ <> OR
    _RSHSP-S @ _RSHSP.ACTIVE-DRAW @ _RSHSP-P @ _RTHP.ACTIVE-DRAW @ <> OR
    _RSHSP-BANK @ RSHSP-BANK.DRAW @ _RSHSP-S @ _RSHSP.ACTIVE-DRAW @ <> OR
    _RSHSP-BANK @ RSHSP-BANK.DRAW @ SCR-DRAW-GENERATION@ <> OR
    _RSHSP-BANK @ RSHSP-BANK.OWNER @ _RSHSP-P @ _RTHP.OWNER @ <> OR
    _RSHSP-BANK @ RSHSP-BANK.GENERATION @ _RSHSP-P @ _RTHP.OWNER-GEN @ <> OR IF 0 EXIT THEN
    _RSHSP-BANK @ RSHSP-BANK.DRAW @ _RSHSP-S @ _RSHSP.SOURCE @ SHSN-SNAPSHOT-FOR@
        SHSN-S-OK <> IF 2DROP 0 EXIT THEN
    _RSHSP-BANK @ RSHSP-BANK.MODEL @ _RSHSP-BANK @ +
    _RSHSP-BANK @ RSHSP-BANK.MODEL-U @ COMPARE 0= ;
: _RSHSP-PREPARE ( -- status )
    _RSHSP-S @ _RSHSP-ABORT
    _RSHSP-S @ _RSHSP.ACTIVE @ _RSHSP-S @ _RSHSP.A @ = IF
        _RSHSP-S @ _RSHSP.B @ ELSE _RSHSP-S @ _RSHSP.A @ THEN _RSHSP-BANK !
    _RSHSP-BANK @ _RSHSP-S @ _RSHSP-CAPACITY _RSHSP-BANK-CAP !
    ['] _RSHSP-BUILD CATCH DUP IF
        _RSHSP-S @ _RSHSP-ABORT EXIT THEN DROP
    _RSHSP-BANK @ _RSHSP-S @ _RSHSP.PENDING !
    _RSHSP-P @ _RTHP.TARGET-PENDING @ _RSHSP-S @ _RSHSP.PENDING-TARGET !
    _RSHSP-P @ _RTHP.SOURCE-DRAW @ _RSHSP-S @ _RSHSP.PENDING-DRAW ! RTE-S-OK ;
: _RSHSP-DISPATCH ( event producer sidecar -- rte-status )
    DUP _RSHSP-HEADER? 0= IF DROP 2DROP RTE-S-INVALID EXIT THEN
    2 PICK RTHPX-PREPARE = _RSHSP-LIVE-PROOF !
    DUP _RSHSP-AUTHORITY? 0= IF DROP 2DROP RTE-S-INVALID EXIT THEN
    DROP _RSHSP-P @ <> IF DROP RTE-S-INVALID EXIT THEN
    _RSHSP-S @ _RSHSP.EXTENSION _RSHSP-P @ _RTHP.EXTENSION @ <> IF DROP RTE-S-INVALID EXIT THEN
    DUP RTHPX-PREPARE = IF DROP _RSHSP-PREPARE EXIT THEN
    DUP RTHPX-EMIT = IF DROP
        _RSHSP-S @ _RSHSP.PENDING @ 0= IF RTE-S-UNAVAILABLE EXIT THEN
        _RSHSP-PENDING? 0= IF RTE-S-INVALID EXIT THEN
        _RSHSP-BANK @ DUP RSHSP-BANK.BATCH @ + _RSHSP-S @ _RSHSP.SHELL @
            RTE-FAMILY-BATCH-EMIT EXIT THEN
    DUP RTHPX-PUBLISH-CHECK = IF DROP _RSHSP-PENDING? IF RTE-S-OK ELSE RTE-S-INVALID THEN EXIT THEN
    DUP RTHPX-START-ACK = IF DROP _RSHSP-START-ACK EXIT THEN
    DUP RTHPX-PUBLISH = IF DROP _RSHSP-PUBLISH RTE-S-OK EXIT THEN
    DUP RTHPX-ABORT = IF DROP _RSHSP-S @ _RSHSP-ABORT RTE-S-OK EXIT THEN
    DUP RTHPX-RETIRE = IF DROP _RSHSP-S @ _RSHSP-RETIRE RTE-S-OK EXIT THEN
    RTHPX-CURRENT = IF _RSHSP-CURRENT? IF RTE-S-OK ELSE RTE-S-UNAVAILABLE THEN EXIT THEN
    RTE-S-INVALID ;

: RSHSP-INIT
\ source shell-facade producer max-entries max-text work-a/u bank-a/u bank-b/u sidecar -- status
    DUP RSHSP-SIZE _RSHSP-SPAN? 0= IF _RSHSP-12DROP RTE-S-INVALID EXIT THEN
    2 PICK 2 PICK _RSHSP-SPAN? 0= IF _RSHSP-12DROP RTE-S-INVALID EXIT THEN
    4 PICK 4 PICK _RSHSP-SPAN? 0= IF _RSHSP-12DROP RTE-S-INVALID EXIT THEN
    6 PICK 6 PICK _RSHSP-SPAN? 0= IF _RSHSP-12DROP RTE-S-INVALID EXIT THEN
    9 PICK RTHP-SIZE _RSHSP-SPAN? 0= IF _RSHSP-12DROP RTE-S-INVALID EXIT THEN
    10 PICK RTE-SHELL-FACADE-SIZE _RSHSP-SPAN? 0= IF _RSHSP-12DROP RTE-S-INVALID EXIT THEN
    11 PICK SHSN-SIZE _RSHSP-SPAN? 0= IF _RSHSP-12DROP RTE-S-INVALID EXIT THEN
    _RSHSP-S ! _RSHSP-IBBU ! _RSHSP-IBB ! _RSHSP-IBAU ! _RSHSP-IBA !
    _RSHSP-IWORKU ! _RSHSP-IWORK ! _RSHSP-ITMAX ! _RSHSP-IEMAX !
    _RSHSP-P ! _RSHSP-ISHELL ! _RSHSP-ISOURCE !
    _RSHSP-IEMAX @ _RTHP-POS-U32? 0= _RSHSP-ITMAX @ _RTHP-POS-U32? 0= OR IF RTE-S-INVALID EXIT THEN
    _RSHSP-IEMAX @ 2 _RTHP-U32*? 0= IF DROP RTE-S-INVALID EXIT THEN
        3 _RTHP-U32+? 0= IF DROP RTE-S-INVALID EXIT THEN DROP
    _RSHSP-IBAU @ RSHSP-BANK-HEADER-SIZE U<
    _RSHSP-IBBU @ RSHSP-BANK-HEADER-SIZE U< OR IF RTE-S-INVALID EXIT THEN
    _RSHSP-P @ RTHP-VALID? 0= IF RTE-S-INVALID EXIT THEN
    _RSHSP-P @ _RTHP.PHASE @ _RTHP-PH-WAIT <> IF RTE-S-UNAVAILABLE EXIT THEN
    _RSHSP-P @ _RTHP.EXTENSION @ IF RTE-S-UNAVAILABLE EXIT THEN
    _RSHSP-ISHELL @ RTE-SHELL-VALID? 0= IF RTE-S-INVALID EXIT THEN
    _RSHSP-ISHELL @ _RTE-SH.BASE @ _RSHSP-P @ _RTHP.FACADE @ <> IF RTE-S-INVALID EXIT THEN
    _RSHSP-ISOURCE @ SHSN-VALID? 0= IF RTE-S-INVALID EXIT THEN
    _RSHSP-S @ RSHSP-SIZE 0 _RSHSP-SPAN!
    _RSHSP-IWORK @ _RSHSP-IWORKU @ 1 _RSHSP-SPAN!
    _RSHSP-IBA @ _RSHSP-IBAU @ 2 _RSHSP-SPAN!
    _RSHSP-IBB @ _RSHSP-IBBU @ 3 _RSHSP-SPAN!
    -1 _RSHSP-LIVE-PROOF ! _RSHSP-SPANS? 0= IF RTE-S-INVALID EXIT THEN
    _RSHSP-S @ RSHSP-SIZE 0 FILL
    _RSHSP-MAGIC _RSHSP-S @ _RSHSP.MAGIC ! RSHSP-SIZE _RSHSP-S @ _RSHSP.SIZE !
    _RSHSP-S @ DUP _RSHSP.SELF !
    _RSHSP-P @ _RSHSP-S @ _RSHSP.PRODUCER !
    _RSHSP-ISOURCE @ _RSHSP-S @ _RSHSP.SOURCE !
    _RSHSP-ISHELL @ _RSHSP-S @ _RSHSP.SHELL !
    _RSHSP-IWORK @ _RSHSP-S @ _RSHSP.WORK ! _RSHSP-IWORKU @ _RSHSP-S @ _RSHSP.WORK-U !
    _RSHSP-IBA @ _RSHSP-S @ _RSHSP.A ! _RSHSP-IBAU @ _RSHSP-S @ _RSHSP.A-U !
    _RSHSP-IBB @ _RSHSP-S @ _RSHSP.B ! _RSHSP-IBBU @ _RSHSP-S @ _RSHSP.B-U !
    _RSHSP-IEMAX @ _RSHSP-S @ _RSHSP.MAX-ENTRIES ! _RSHSP-ITMAX @ _RSHSP-S @ _RSHSP.MAX-TEXT !
    _RSHSP-S @ _RSHSP.EXTENSION DUP _RSHSP-OUT !
    _RTHP-EXTENSION-MAGIC OVER RTHPX.MAGIC ! RTHP-EXTENSION-SIZE OVER RTHPX.SIZE !
    DUP DUP RTHPX.SELF !
    _RSHSP-S @ OVER RTHPX.CONTEXT ! ['] _RSHSP-DISPATCH OVER RTHPX.DISPATCH !
    _RSHSP-IEMAX @ 3 + OVER RTHPX.EXTRA-REGIONS !
    _RSHSP-IEMAX @ 2 * 2 + OVER RTHPX.EXTRA-OBJECTS !
    _RSHSP-ITMAX @ SWAP RTHPX.EXTRA-UTF8 !
    RTE-S-OK ;
: RSHSP-INSTALL ( sidecar -- rte-status )
    DUP RSHSP-VALID? 0= IF DROP RTE-S-INVALID EXIT THEN
    DUP _RSHSP.EXTENSION SWAP _RSHSP.PRODUCER @ RTHP-EXTENSION-INSTALL
        SCB-S-OK = IF RTE-S-OK ELSE RTE-S-UNAVAILABLE THEN ;

\ Caller has revoked the producer/input callbacks and drained/stopped the
\ transport (the Desk APTAS-UNINSTALL boundary). No wire authority is changed.
: RSHSP-UNINSTALL-AFTER-STOP ( sidecar -- rte-status )
    DUP RSHSP-VALID? 0= IF DROP RTE-S-INVALID EXIT THEN DROP
    _RSHSP-P @ _RTHP.FACADE @ RTE-UPDATE-STATE@
        RTE-S-OK <> IF DROP RTE-S-UNAVAILABLE EXIT THEN
    RTE-UPDATE-IDLE <> IF RTE-S-WOULD-BLOCK EXIT THEN
    _RSHSP-P @ _RTHP.EXTENSION @ DUP IF
        _RSHSP-S @ _RSHSP.EXTENSION <> IF RTE-S-UNAVAILABLE EXIT THEN
        0 _RSHSP-P @ _RTHP.EXTENSION !
    ELSE DROP THEN
    _RSHSP-S @ _RSHSP-RETIRE RTE-S-OK ;

VARIABLE _RSHSP-INPUT-OWNER VARIABLE _RSHSP-INPUT-GEN VARIABLE _RSHSP-INPUT-ID
VARIABLE _RSHSP-INPUT-INTENT VARIABLE _RSHSP-INPUT-CONTROL VARIABLE _RSHSP-INPUT-CORR
VARIABLE _RSHSP-INPUT-MODEL VARIABLE _RSHSP-INPUT-ENTRY VARIABLE _RSHSP-INPUT-MATCHES
: _RSHSP-INPUT-NONE ( -- row col revision false ) 0 0 0 0 ;
: _RSHSP-CONTROL-FIND ( -- item|0 )
    0 _RSHSP-INPUT-MATCHES ! 0 _RSHSP-INPUT-CONTROL !
    _RSHSP-V-BATCH @ _RTE-FB.FAMILIES-U @ RTE-FAMILY-ENTRY-SIZE / 0 ?DO
        _RSHSP-V-BATCH @ _RTE-FB.FAMILIES-A @ I RTE-FAMILY-ENTRY-SIZE * +
        DUP _RTE-FE.KIND @ RTE-FAMILY-CONTROL = IF
            RTE-FAMILY-ITEMS@ RTE-CONTROL-SIZE / 0 ?DO
                DUP I RTE-CONTROL-SIZE * + DUP _RTE-CONTROL.ID @ _RSHSP-INPUT-ID @ = IF
                    _RSHSP-INPUT-CONTROL ! 1 _RSHSP-INPUT-MATCHES +! ELSE DROP THEN
            LOOP DROP
        ELSE DROP THEN
    LOOP
    _RSHSP-INPUT-MATCHES @ 1 = IF _RSHSP-INPUT-CONTROL @ ELSE 0 THEN ;
: _RSHSP-CORRELATION-FIND ( -- correlation|0 )
    0 _RSHSP-INPUT-MATCHES ! 0 _RSHSP-INPUT-CORR !
    _RSHSP-BANK @ RSHSP-BANK.CORRELATIONS-U @ RSHPL-CORRELATION-SIZE / 0 ?DO
        _RSHSP-BANK @ DUP RSHSP-BANK.CORRELATIONS @ + I RSHPL-CORRELATION-SIZE * +
        DUP RSHPL-CORRELATION.ID @ _RSHSP-INPUT-ID @ = IF
            _RSHSP-INPUT-CORR ! 1 _RSHSP-INPUT-MATCHES +! ELSE DROP THEN
    LOOP
    _RSHSP-INPUT-MATCHES @ 1 = IF _RSHSP-INPUT-CORR @ ELSE 0 THEN ;
VARIABLE _RSHSP-INPUT-ROOT VARIABLE _RSHSP-INPUT-CHILD VARIABLE _RSHSP-INPUT-SAVED-ID
: _RSHSP-TARGET-GEOMETRY? ( -- flag )
    _RSHSP-INPUT-CONTROL @ _RSHSP-INPUT-CHILD !
    _RSHSP-INPUT-ID @ _RSHSP-INPUT-SAVED-ID !
    _RSHSP-INPUT-CONTROL @ _RTE-CONTROL.PARENT @ _RSHSP-INPUT-ID !
    _RSHSP-CONTROL-FIND _RSHSP-INPUT-ROOT !
    _RSHSP-INPUT-SAVED-ID @ _RSHSP-INPUT-ID !
    _RSHSP-INPUT-CHILD @ _RSHSP-INPUT-CONTROL !
    _RSHSP-INPUT-ROOT @ 0= IF 0 EXIT THEN
    _RSHSP-INPUT-ROOT @ _RTE-CONTROL.KIND @ RTE-CONTROL-TASKBAR <>
    _RSHSP-INPUT-ROOT @ _RTE-CONTROL.PARENT @ 0<> OR
    _RSHSP-INPUT-ROOT @ _RTE-CONTROL.REGION @ _RSHSP-INPUT-CONTROL @ _RTE-CONTROL.REGION @ <> OR IF 0 EXIT THEN
    _RSHSP-INPUT-ENTRY @ SHME.KIND @ SHM-K-TASK = IF RTE-CONTROL-TASK ELSE RTE-CONTROL-LAUNCHER THEN
        _RSHSP-INPUT-CONTROL @ _RTE-CONTROL.KIND @ <> IF 0 EXIT THEN
    _RSHSP-INPUT-CONTROL @ _RTE-CONTROL.ORDER @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.INDEX @ <>
    _RSHSP-INPUT-CONTROL @ _RTE-CONTROL.REGION @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.REGION @ <> OR
    _RSHSP-INPUT-CONTROL @ _RTE-CONTROL.ROW @ _RSHSP-INPUT-ROOT @ _RTE-CONTROL.ROW @ +
        _RSHSP-INPUT-ENTRY @ SHME.ROW @ <> OR
    _RSHSP-INPUT-CONTROL @ _RTE-CONTROL.COL @ _RSHSP-INPUT-ROOT @ _RTE-CONTROL.COL @ +
        _RSHSP-INPUT-ENTRY @ SHME.COL @ <> OR
    _RSHSP-INPUT-CONTROL @ _RTE-CONTROL.WIDTH @ _RSHSP-INPUT-ENTRY @ SHME.WIDTH @ <> OR
    _RSHSP-INPUT-CONTROL @ _RTE-CONTROL.HEIGHT @ _RSHSP-INPUT-ENTRY @ SHME.HEIGHT @ <> OR IF 0 EXIT THEN
    _RSHSP-INPUT-ENTRY @ SHME.KIND @ _RSHSP-INPUT-MODEL @
        _RSHSP-BANK @ RSHSP-BANK.MODEL-U @ RSHPL-BAND-BOUNDS
    RSHPL-S-OK <> IF 2DROP 2DROP 0 EXIT THEN
    _RSHSP-INPUT-ROOT @ _RTE-CONTROL.WIDTH @ <> IF DROP 2DROP 0 EXIT THEN
    _RSHSP-INPUT-ROOT @ _RTE-CONTROL.HEIGHT @ <> IF 2DROP 0 EXIT THEN
    _RSHSP-INPUT-ROOT @ _RTE-CONTROL.COL @ <> IF DROP 0 EXIT THEN
    _RSHSP-INPUT-ROOT @ _RTE-CONTROL.ROW @ <> IF 0 EXIT THEN
    _RSHSP-INPUT-ENTRY @ _RSHSP-INPUT-MODEL @ SHME-LABEL$
    _RSHSP-INPUT-CONTROL @ DUP _RTE-CONTROL.LABEL-A @ SWAP _RTE-CONTROL.LABEL-U @ COMPARE 0= ;
: _RSHSP-SHELL-TARGET? ( -- flag )
    _RSHSP-INPUT-INTENT @ RTE-INTENT-ACTIVATE <> IF 0 EXIT THEN
    _RSHSP-INPUT-CONTROL @ _RTE-CONTROL.STATE @
        RTE-CONTROL-VISIBLE RTE-CONTROL-ENABLED OR AND
        RTE-CONTROL-VISIBLE RTE-CONTROL-ENABLED OR <> IF 0 EXIT THEN
    _RSHSP-CORRELATION-FIND DUP 0= IF DROP 0 EXIT THEN _RSHSP-INPUT-CORR !
    _RSHSP-BANK @ DUP RSHSP-BANK.MODEL @ + _RSHSP-INPUT-MODEL !
    _RSHSP-INPUT-MODEL @ SHM.FLAGS @ SHM-F-INPUT-BLOCKED AND IF 0 EXIT THEN
    _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.INDEX @
        DUP _RSHSP-INPUT-MODEL @ SHM.COUNT @ U< 0= IF DROP 0 EXIT THEN
        _RSHSP-INPUT-MODEL @ SHM-ENTRY _RSHSP-INPUT-ENTRY !
    _RSHSP-INPUT-ENTRY @ SHME.KIND @ DUP SHM-K-TASK <> SWAP SHM-K-LAUNCHER <> AND IF 0 EXIT THEN
    _RSHSP-INPUT-ENTRY @ SHME.KIND @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.KIND @ <>
    _RSHSP-INPUT-ENTRY @ SHME.KEY @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.KEY @ <> OR
    _RSHSP-INPUT-ENTRY @ SHME.IDENTITY @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.IDENTITY @ <> OR
    _RSHSP-INPUT-ENTRY @ SHME.OWNER-ID @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.OWNER @ <> OR
    _RSHSP-INPUT-ENTRY @ SHME.OWNER-GEN @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.GENERATION @ <> OR
    _RSHSP-INPUT-ENTRY @ SHME.ACTION @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.ACTION @ <> OR
    _RSHSP-INPUT-ENTRY @ SHME.FLAGS @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.FLAGS @ <> OR IF 0 EXIT THEN
    _RSHSP-INPUT-ENTRY @ SHME.ROW @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.ROW @ <>
    _RSHSP-INPUT-ENTRY @ SHME.COL @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.COL @ <> OR
    _RSHSP-INPUT-ENTRY @ SHME.HEIGHT @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.HEIGHT @ <> OR
    _RSHSP-INPUT-ENTRY @ SHME.WIDTH @ _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.WIDTH @ <> OR IF 0 EXIT THEN
    _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.SOURCE-OWNER @ _RSHSP-INPUT-MODEL @ SHM.OWNER-ID @ <>
    _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.SOURCE-GENERATION @ _RSHSP-INPUT-MODEL @ SHM.OWNER-GEN @ <> OR
    _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.EPOCH @ _RSHSP-INPUT-MODEL @ SHM.EPOCH @ <> OR
    _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.DRAW @ _RSHSP-BANK @ RSHSP-BANK.DRAW @ <> OR
    _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.ATTACHMENT @ _RSHSP-INPUT-MODEL @ SHM.OWNER-ID @ <> OR IF 0 EXIT THEN
    _RSHSP-TARGET-GEOMETRY? 0= IF 0 EXIT THEN
    _RSHSP-INPUT-ENTRY @ SHME.FLAGS @ SHM-F-DISABLED AND IF 0 EXIT THEN
    _RSHSP-INPUT-ENTRY @ SHME.KIND @ SHM-K-LAUNCHER = IF
        _RSHSP-INPUT-ENTRY @ SHME.ACTION @ 0= IF 0 EXIT THEN
    THEN
    _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.ACTION-OFFSET @
    _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.ACTION-BYTES @ _RTHP-U32+? 0= IF DROP 0 EXIT THEN
    _RSHSP-BANK @ RSHSP-BANK.ACTIONS-U @ U> IF 0 EXIT THEN
    _RSHSP-INPUT-ENTRY @ _RSHSP-INPUT-MODEL @ SHME-ACTION$
    _RSHSP-BANK @ DUP RSHSP-BANK.ACTIONS @ +
        _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.ACTION-OFFSET @ +
    _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.ACTION-BYTES @ COMPARE 0= ;
: RSHSP-CONTROL-TARGET@
\ owner generation control-id intent sidecar -- row col revision found?
    DUP _RSHSP-HEADER? 0= IF DROP 2DROP 2DROP _RSHSP-INPUT-NONE EXIT THEN
    DUP RSHSP-VALID? 0= IF DROP 2DROP 2DROP _RSHSP-INPUT-NONE EXIT THEN DROP
    _RSHSP-INPUT-INTENT ! _RSHSP-INPUT-ID ! _RSHSP-INPUT-GEN ! _RSHSP-INPUT-OWNER !
    _RSHSP-S @ _RSHSP.EXTENSION _RSHSP-P @ _RTHP.EXTENSION @ <> IF _RSHSP-INPUT-NONE EXIT THEN
    _RSHSP-S @ _RSHSP.ACTIVE @ 0= IF
        _RSHSP-INPUT-OWNER @ _RSHSP-INPUT-GEN @ _RSHSP-INPUT-ID @ _RSHSP-INPUT-INTENT @
        _RSHSP-P @ RTHP-CONTROL-TARGET@ EXIT THEN
    _RSHSP-CURRENT? 0= IF _RSHSP-INPUT-NONE EXIT THEN
    _RSHSP-INPUT-OWNER @ _RSHSP-BANK @ RSHSP-BANK.OWNER @ <>
    _RSHSP-INPUT-GEN @ _RSHSP-BANK @ RSHSP-BANK.GENERATION @ <> OR IF _RSHSP-INPUT-NONE EXIT THEN
    _RSHSP-CONTROL-FIND DUP 0= IF DROP _RSHSP-INPUT-NONE EXIT THEN _RSHSP-INPUT-CONTROL !
    _RSHSP-INPUT-CONTROL @ _RTE-CONTROL.KIND @ DUP RTE-CONTROL-TASK = SWAP RTE-CONTROL-LAUNCHER = OR IF
        _RSHSP-SHELL-TARGET? 0= IF _RSHSP-INPUT-NONE EXIT THEN
        _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.ROW @
        _RSHSP-INPUT-CORR @ RSHPL-CORRELATION.COL @ _RSHSP-INPUT-MODEL @ SHM.EPOCH @ -1 EXIT
    THEN
    _RSHSP-INPUT-OWNER @ _RSHSP-INPUT-GEN @ _RSHSP-INPUT-ID @ _RSHSP-INPUT-INTENT @
    _RSHSP-P @ RTHP-CONTROL-TARGET@ ;

HERE _RSHSP-OWNED-LIMIT !
