\ =====================================================================
\ shell-planner.f -- frozen canonical shell to renderer-neutral records
\ =====================================================================
\ Pure, synchronous and caller bounded. The publisher supplies a validated
\ completed SHSN copy and proof of which pane memberships and taskbar bands
\ can be represented. It must have checked final-writer overlap and ordinary
\ blank spacing before selecting a band. Outputs are tentative until the
\ complete owner transaction is admitted; this module never publishes.
\ All display/action strings are copied. Correlations and claims contain
\ offsets/scalars only; neutral text pointers borrow the caller text bank.
PROVIDED akashic-tui-rterm-shplan
REQUIRE ../shell-snapshot.f
REQUIRE engine.f
REQUIRE ../../utils/memory-span.f

0 CONSTANT RSHPL-S-OK
1 CONSTANT RSHPL-S-CAPACITY
2 CONSTANT RSHPL-S-INVALID
1 CONSTANT RSHPL-BAND-TASKS
2 CONSTANT RSHPL-BAND-LAUNCHERS
4 CONSTANT RSHPL-K-TASKBAR-TASKS
5 CONSTANT RSHPL-K-TASKBAR-LAUNCHERS
1 CONSTANT RSHPL-CLAIM-PANE
2 CONSTANT RSHPL-CLAIM-TASKBAR
256 CONSTANT RSHPL-REQUEST-SIZE
152 CONSTANT RSHPL-RESULT-SIZE
192 CONSTANT RSHPL-CORRELATION-SIZE
64 CONSTANT RSHPL-CLAIM-SIZE
: _RSHPL-Q.MODEL-A ( record -- a )  ;
: _RSHPL-Q.MODEL-U ( record -- a ) 8 + ;
: _RSHPL-Q.OWNER ( record -- a ) 16 + ;
: _RSHPL-Q.GENERATION ( record -- a ) 24 + ;
: _RSHPL-Q.ATTACHMENT ( record -- a ) 32 + ;
: _RSHPL-Q.DRAW ( record -- a ) 40 + ;
: _RSHPL-Q.FIRST-REGION ( record -- a ) 48 + ;
: _RSHPL-Q.FIRST-OBJECT ( record -- a ) 56 + ;
: _RSHPL-Q.FIRST-CONTROL ( record -- a ) 64 + ;
: _RSHPL-Q.CHROME-Z ( record -- a ) 72 + ;
: _RSHPL-Q.CONTENT-Z ( record -- a ) 80 + ;
: _RSHPL-Q.TASKBAR-Z ( record -- a ) 88 + ;
: _RSHPL-Q.BANDS ( record -- a ) 96 + ;
: _RSHPL-Q.ELIGIBLE-A ( record -- a ) 104 + ;
: _RSHPL-Q.ELIGIBLE-U ( record -- a ) 112 + ;
: _RSHPL-Q.REGIONS-A ( record -- a ) 120 + ;
: _RSHPL-Q.REGIONS-U ( record -- a ) 128 + ;
: _RSHPL-Q.PANES-A ( record -- a ) 136 + ;
: _RSHPL-Q.PANES-U ( record -- a ) 144 + ;
: _RSHPL-Q.CONTROLS-A ( record -- a ) 152 + ;
: _RSHPL-Q.CONTROLS-U ( record -- a ) 160 + ;
: _RSHPL-Q.TEXT-A ( record -- a ) 168 + ;
: _RSHPL-Q.TEXT-U ( record -- a ) 176 + ;
: _RSHPL-Q.CORRELATIONS-A ( record -- a ) 184 + ;
: _RSHPL-Q.CORRELATIONS-U ( record -- a ) 192 + ;
: _RSHPL-Q.CLAIMS-A ( record -- a ) 200 + ;
: _RSHPL-Q.CLAIMS-U ( record -- a ) 208 + ;
: _RSHPL-Q.RESULT-A ( record -- a ) 216 + ;
: _RSHPL-Q.RESULT-U ( record -- a ) 224 + ;
: _RSHPL-Q.ACTIONS-A ( record -- a ) 232 + ;
: _RSHPL-Q.ACTIONS-U ( record -- a ) 240 + ;
: _RSHPL-Q.RESERVED ( record -- a ) 248 + ;
: RSHPL-RESULT.REGIONS ( record -- a )  ;
: RSHPL-RESULT.PANES ( record -- a ) 8 + ;
: RSHPL-RESULT.CONTROLS ( record -- a ) 16 + ;
: RSHPL-RESULT.TEXT-BYTES ( record -- a ) 24 + ;
: RSHPL-RESULT.CORRELATIONS ( record -- a ) 32 + ;
: RSHPL-RESULT.CLAIMS ( record -- a ) 40 + ;
: RSHPL-RESULT.LAST-REGION ( record -- a ) 48 + ;
: RSHPL-RESULT.LAST-OBJECT ( record -- a ) 56 + ;
: RSHPL-RESULT.LAST-CONTROL ( record -- a ) 64 + ;
: RSHPL-RESULT.TASKBARS ( record -- a ) 72 + ;
: RSHPL-RESULT.EPOCH ( record -- a ) 80 + ;
: RSHPL-RESULT.SOURCE-OWNER ( record -- a ) 88 + ;
: RSHPL-RESULT.SOURCE-GENERATION ( record -- a ) 96 + ;
: RSHPL-RESULT.DRAW ( record -- a ) 104 + ;
: RSHPL-RESULT.ATTACHMENT ( record -- a ) 112 + ;
: RSHPL-RESULT.PANE-UTF8 ( record -- a ) 120 + ;
: RSHPL-RESULT.CONTROL-UTF8 ( record -- a ) 128 + ;
: RSHPL-RESULT.ACTION-BYTES ( record -- a ) 136 + ;
: RSHPL-RESULT.RESERVED ( record -- a ) 144 + ;
: RSHPL-CORRELATION.INDEX ( record -- a )  ;
: RSHPL-CORRELATION.KIND ( record -- a ) 8 + ;
: RSHPL-CORRELATION.KEY ( record -- a ) 16 + ;
: RSHPL-CORRELATION.IDENTITY ( record -- a ) 24 + ;
: RSHPL-CORRELATION.OWNER ( record -- a ) 32 + ;
: RSHPL-CORRELATION.GENERATION ( record -- a ) 40 + ;
: RSHPL-CORRELATION.ID ( record -- a ) 48 + ;
: RSHPL-CORRELATION.REGION ( record -- a ) 56 + ;
: RSHPL-CORRELATION.CONTENT-REGION ( record -- a ) 64 + ;
: RSHPL-CORRELATION.SOURCE-OWNER ( record -- a ) 72 + ;
: RSHPL-CORRELATION.SOURCE-GENERATION ( record -- a ) 80 + ;
: RSHPL-CORRELATION.EPOCH ( record -- a ) 88 + ;
: RSHPL-CORRELATION.DRAW ( record -- a ) 96 + ;
: RSHPL-CORRELATION.ATTACHMENT ( record -- a ) 104 + ;
: RSHPL-CORRELATION.ACTION ( record -- a ) 112 + ;
: RSHPL-CORRELATION.ACTION-OFFSET ( record -- a ) 120 + ;
: RSHPL-CORRELATION.ACTION-BYTES ( record -- a ) 128 + ;
: RSHPL-CORRELATION.ROW ( record -- a ) 136 + ;
: RSHPL-CORRELATION.COL ( record -- a ) 144 + ;
: RSHPL-CORRELATION.HEIGHT ( record -- a ) 152 + ;
: RSHPL-CORRELATION.WIDTH ( record -- a ) 160 + ;
: RSHPL-CORRELATION.TEXT-OFFSET ( record -- a ) 168 + ;
: RSHPL-CORRELATION.TEXT-BYTES ( record -- a ) 176 + ;
: RSHPL-CORRELATION.FLAGS ( record -- a ) 184 + ;
: RSHPL-CLAIM.INDEX ( record -- a )  ;
: RSHPL-CLAIM.KIND ( record -- a ) 8 + ;
: RSHPL-CLAIM.ID ( record -- a ) 16 + ;
: RSHPL-CLAIM.ROW ( record -- a ) 24 + ;
: RSHPL-CLAIM.COL ( record -- a ) 32 + ;
: RSHPL-CLAIM.HEIGHT ( record -- a ) 40 + ;
: RSHPL-CLAIM.WIDTH ( record -- a ) 48 + ;
: RSHPL-CLAIM.REGION ( record -- a ) 56 + ;
: RSHPL-REQUEST-CLEAR ( q -- ) RSHPL-REQUEST-SIZE 0 FILL ;
: RSHPL-REQUEST-SOURCE! ( model bytes attachment draw eligible-a eligible-u bands q -- )
    >R R@ _RSHPL-Q.BANDS ! R@ _RSHPL-Q.ELIGIBLE-U ! R@ _RSHPL-Q.ELIGIBLE-A !
    R@ _RSHPL-Q.DRAW ! R@ _RSHPL-Q.ATTACHMENT ! R@ _RSHPL-Q.MODEL-U !
    R> _RSHPL-Q.MODEL-A ! ;
: RSHPL-REQUEST-IDENTITY! ( owner gen first-region first-object first-control q -- )
    >R R@ _RSHPL-Q.FIRST-CONTROL ! R@ _RSHPL-Q.FIRST-OBJECT !
    R@ _RSHPL-Q.FIRST-REGION ! R@ _RSHPL-Q.GENERATION ! R> _RSHPL-Q.OWNER ! ;
: RSHPL-REQUEST-Z! ( chrome content taskbar q -- )
    >R R@ _RSHPL-Q.TASKBAR-Z ! R@ _RSHPL-Q.CONTENT-Z ! R> _RSHPL-Q.CHROME-Z ! ;
: RSHPL-REQUEST-OUTPUT!
    ( regions-a/u panes-a/u controls-a/u text-a/u correlations-a/u claims-a/u actions-a/u result-a/u q -- )
    >R R@ _RSHPL-Q.RESULT-U ! R@ _RSHPL-Q.RESULT-A !
    R@ _RSHPL-Q.ACTIONS-U ! R@ _RSHPL-Q.ACTIONS-A !
    R@ _RSHPL-Q.CLAIMS-U ! R@ _RSHPL-Q.CLAIMS-A !
    R@ _RSHPL-Q.CORRELATIONS-U ! R@ _RSHPL-Q.CORRELATIONS-A !
    R@ _RSHPL-Q.TEXT-U ! R@ _RSHPL-Q.TEXT-A !
    R@ _RSHPL-Q.CONTROLS-U ! R@ _RSHPL-Q.CONTROLS-A !
    R@ _RSHPL-Q.PANES-U ! R@ _RSHPL-Q.PANES-A !
    R@ _RSHPL-Q.REGIONS-U ! R> _RSHPL-Q.REGIONS-A ! ;

CREATE _RSHPL-OWNED-START
VARIABLE _RSHPL-OWNED-LIMIT 0 _RSHPL-OWNED-LIMIT !
VARIABLE _RSHPL-Q VARIABLE _RSHPL-M VARIABLE _RSHPL-E
VARIABLE _RSHPL-I VARIABLE _RSHPL-J VARIABLE _RSHPL-N
VARIABLE _RSHPL-R VARIABLE _RSHPL-C VARIABLE _RSHPL-P VARIABLE _RSHPL-X
VARIABLE _RSHPL-REGIONS VARIABLE _RSHPL-PANES VARIABLE _RSHPL-CONTROLS
VARIABLE _RSHPL-TEXT VARIABLE _RSHPL-CORRS VARIABLE _RSHPL-CLAIMS
VARIABLE _RSHPL-ROOTS VARIABLE _RSHPL-CHROME VARIABLE _RSHPL-TBREG
VARIABLE _RSHPL-NEXT-R VARIABLE _RSHPL-NEXT-O VARIABLE _RSHPL-NEXT-C
VARIABLE _RSHPL-ID VARIABLE _RSHPL-CONTENT VARIABLE _RSHPL-PARENT
VARIABLE _RSHPL-BAND VARIABLE _RSHPL-BAND-C VARIABLE _RSHPL-BAND-W
VARIABLE _RSHPL-TASK-N VARIABLE _RSHPL-LAUNCH-N VARIABLE _RSHPL-K
VARIABLE _RSHPL-TEXT-O VARIABLE _RSHPL-ACTION-O
VARIABLE _RSHPL-CROW VARIABLE _RSHPL-CCOL VARIABLE _RSHPL-CH VARIABLE _RSHPL-CW
VARIABLE _RSHPL-STATUS
VARIABLE _RSHPL-ACTIONS VARIABLE _RSHPL-PANE-UTF8 VARIABLE _RSHPL-CONTROL-UTF8
VARIABLE _RSHPL-OTHER VARIABLE _RSHPL-LEFT VARIABLE _RSHPL-RIGHT
VARIABLE _RSHPL-TOP VARIABLE _RSHPL-BOTTOM
CREATE _RSHPL-SPANS 11 16 * ALLOT
: _RSHPL-U32? ( n -- flag ) 0xFFFFFFFF U> 0= ;
: _RSHPL-I32? ( n -- flag ) DUP -2147483648 >= SWAP 2147483647 <= AND ;
: RSHPL-STORAGE-DISJOINT? ( a u -- flag )
    DUP 0< IF 2DROP 0 EXIT THEN DUP 0= IF 2DROP -1 EXIT THEN
    OVER 0= IF 2DROP 0 EXIT THEN
    2DUP MSPAN-NONWRAPPING? 0= IF 2DROP 0 EXIT THEN
    2DUP _RSHPL-OWNED-START _RSHPL-OWNED-LIMIT @ _RSHPL-OWNED-START -
        MSPAN-OVERLAP? IF 2DROP 0 EXIT THEN
    2DUP RTE-ADMISSION-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    SHSN-STORAGE-DISJOINT? ;
: _RSHPL-SPAN? ( a u -- flag )
    DUP _RSHPL-U32? 0= IF 2DROP 0 EXIT THEN
    DUP 0= IF DROP 0= EXIT THEN RSHPL-STORAGE-DISJOINT? ;
: _RSHPL-ALIGNED? ( a u -- flag )
    2DUP _RSHPL-SPAN? 0= IF 2DROP 0 EXIT THEN DROP 7 AND 0= ;
: _RSHPL-S@ ( index -- a u ) 16 * _RSHPL-SPANS + DUP @ SWAP 8 + @ ;
: _RSHPL-S! ( a u index -- ) 16 * _RSHPL-SPANS + >R R@ 8 + ! R> ! ;
: _RSHPL-SPANS? ( q -- flag )
    DUP RSHPL-REQUEST-SIZE _RSHPL-ALIGNED? 0= IF DROP 0 EXIT THEN
    _RSHPL-Q !
    _RSHPL-Q @ _RSHPL-Q.MODEL-A @ _RSHPL-Q @ _RSHPL-Q.MODEL-U @
        _RSHPL-ALIGNED? 0= IF 0 EXIT THEN
    _RSHPL-Q @ _RSHPL-Q.ELIGIBLE-A @ _RSHPL-Q @ _RSHPL-Q.ELIGIBLE-U @
        _RSHPL-ALIGNED? 0= IF 0 EXIT THEN
    7 0 DO
        _RSHPL-Q @ 120 I 16 * + + DUP @ SWAP 8 + @
        I 3 = IF _RSHPL-SPAN? ELSE _RSHPL-ALIGNED? THEN
        0= IF 0 UNLOOP EXIT THEN
    LOOP
    _RSHPL-Q @ _RSHPL-Q.ACTIONS-A @ _RSHPL-Q @ _RSHPL-Q.ACTIONS-U @
        _RSHPL-SPAN? 0= IF 0 EXIT THEN
    _RSHPL-Q @ RSHPL-REQUEST-SIZE 0 _RSHPL-S!
    _RSHPL-Q @ _RSHPL-Q.MODEL-A @ _RSHPL-Q @ _RSHPL-Q.MODEL-U @ 1 _RSHPL-S!
    _RSHPL-Q @ _RSHPL-Q.ELIGIBLE-A @ _RSHPL-Q @ _RSHPL-Q.ELIGIBLE-U @ 2 _RSHPL-S!
    7 0 DO _RSHPL-Q @ 120 I 16 * + + DUP @ SWAP 8 + @ I 3 + _RSHPL-S! LOOP
    _RSHPL-Q @ _RSHPL-Q.ACTIONS-A @ _RSHPL-Q @ _RSHPL-Q.ACTIONS-U @ 10 _RSHPL-S!
    11 0 DO I 0 ?DO J _RSHPL-S@ I _RSHPL-S@ MSPAN-OVERLAP? IF
        0 UNLOOP UNLOOP EXIT
    THEN LOOP LOOP -1 ;
: _RSHPL-CLEAR-OUTPUTS ( -- ) 11 3 DO I _RSHPL-S@ 0 FILL LOOP ;
: _RSHPL-ENTRY ( index -- e ) _RSHPL-M @ SHM-ENTRY ;
: _RSHPL-PANE? ( index -- flag )
    _RSHPL-Q @ _RSHPL-Q.ELIGIBLE-U @ 0= IF DROP 0 EXIT THEN
    8 * _RSHPL-Q @ _RSHPL-Q.ELIGIBLE-A @ + @ ;
: _RSHPL-BAND? ( kind -- flag )
    SHM-K-TASK = IF 1 ELSE 2 THEN _RSHPL-Q @ _RSHPL-Q.BANDS @ AND 0<> ;
: _RSHPL-RESET ( -- )
    0 _RSHPL-REGIONS ! 0 _RSHPL-PANES ! 0 _RSHPL-CONTROLS ! 0 _RSHPL-TEXT !
    0 _RSHPL-CORRS ! 0 _RSHPL-CLAIMS ! 0 _RSHPL-ROOTS !
    0 _RSHPL-TASK-N ! 0 _RSHPL-LAUNCH-N !
    0 _RSHPL-ACTIONS ! 0 _RSHPL-PANE-UTF8 ! 0 _RSHPL-CONTROL-UTF8 ! ;

\ Exact two source-authored bands. A band with no entries is not emitted.
\ TASKS occupy [0, divider), LAUNCHERS [divider+2, end), or [0,end)
\ when the source has no divider. Every selected entry must fit its band.
: _RSHPL-BAND-BOUNDS ( kind -- col width )
    SHM-K-TASK = IF
        0 _RSHPL-M @ SHM.DIVIDER-COL @ DUP 0< IF
            DROP _RSHPL-M @ SHM.END-COL @
        THEN
    ELSE
        _RSHPL-M @ SHM.DIVIDER-COL @ DUP 0< IF DROP 0 ELSE 2 + THEN
        DUP _RSHPL-M @ SHM.END-COL @ SWAP -
    THEN ;
: _RSHPL-BAND-FITS? ( e -- flag )
    DUP SHME.KIND @ _RSHPL-BAND-BOUNDS _RSHPL-BAND-W ! _RSHPL-BAND-C !
    _RSHPL-BAND-W @ 0> 0= IF DROP 0 EXIT THEN
    _RSHPL-BAND-C @ _RSHPL-BAND-W @ + _RSHPL-M @ SHM.END-COL @ > IF DROP 0 EXIT THEN
    _RSHPL-BAND-C @ _RSHPL-I32? 0= IF DROP 0 EXIT THEN
    _RSHPL-M @ SHM.HEIGHT @ 1- _RSHPL-I32? 0= IF DROP 0 EXIT THEN
    DUP SHME.COL @ _RSHPL-BAND-C @ < IF DROP 0 EXIT THEN
    DUP SHME.COL @ SWAP SHME.WIDTH @ + _RSHPL-BAND-C @ _RSHPL-BAND-W @ + <= ;

\ The public bound helpers validate the frozen model on every call. Their
\ internal -PROVED peers skip only SHSN-FROZEN-VALIDATE, for a caller that
\ validated the model and has not written it since.
VARIABLE _RSHPL-PROVED
: _RSHPL-MODEL-OK? ( model bytes -- flag )
    2DUP RSHPL-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    _RSHPL-PROVED @ IF 2DROP -1 EXIT THEN
    SHSN-FROZEN-VALIDATE SHSN-S-OK = ;

\ Geometry-only helper; validates frozen bytes and returns the canonical
\ band, without asserting any final-writer or blank-cell proof.
: _RSHPL-BAND-BOUNDS-OF ( kind model bytes -- row col height width status )
    2DUP _RSHPL-MODEL-OK? 0= IF
        2DROP DROP 0 0 0 0 RSHPL-S-INVALID EXIT
    THEN DROP _RSHPL-M !
    DUP SHM-K-TASK = OVER SHM-K-LAUNCHER = OR 0= IF
        DROP 0 0 0 0 RSHPL-S-INVALID EXIT
    THEN
    _RSHPL-BAND-BOUNDS _RSHPL-BAND-W ! _RSHPL-BAND-C !
    _RSHPL-BAND-W @ 0< _RSHPL-BAND-C @ _RSHPL-I32? 0= OR
    _RSHPL-BAND-C @ _RSHPL-BAND-W @ + _RSHPL-M @ SHM.END-COL @ > OR
    _RSHPL-M @ SHM.HEIGHT @ 1- _RSHPL-I32? 0= OR IF
        0 0 0 0 RSHPL-S-INVALID EXIT
    THEN
    _RSHPL-M @ SHM.HEIGHT @ 1- _RSHPL-BAND-C @ 1 _RSHPL-BAND-W @ RSHPL-S-OK ;
: RSHPL-BAND-BOUNDS ( kind model bytes -- row col height width status )
    0 _RSHPL-PROVED ! _RSHPL-BAND-BOUNDS-OF ;
: _RSHPL-BAND-BOUNDS-PROVED ( kind model bytes -- row col height width status )
    -1 _RSHPL-PROVED ! _RSHPL-BAND-BOUNDS-OF 0 _RSHPL-PROVED ! ;

\ Deep source validation precedes every count or record dereference.
: _RSHPL-SOURCE? ( -- flag )
    _RSHPL-Q @ _RSHPL-Q.MODEL-A @ _RSHPL-Q @ _RSHPL-Q.MODEL-U @
        SHSN-FROZEN-VALIDATE SHSN-S-OK <> IF 0 EXIT THEN
    _RSHPL-Q @ _RSHPL-Q.MODEL-A @ _RSHPL-M !
    _RSHPL-Q @ _RSHPL-Q.RESERVED @ IF 0 EXIT THEN
    _RSHPL-Q @ _RSHPL-Q.OWNER @ 0= _RSHPL-Q @ _RSHPL-Q.GENERATION @ 0= OR
    _RSHPL-Q @ _RSHPL-Q.ATTACHMENT @ 0= OR _RSHPL-Q @ _RSHPL-Q.DRAW @ 0= OR
        IF 0 EXIT THEN
    _RSHPL-Q @ _RSHPL-Q.BANDS @ 3 INVERT AND IF 0 EXIT THEN
    _RSHPL-Q @ _RSHPL-Q.CHROME-Z @ _RSHPL-I32? 0=
    _RSHPL-Q @ _RSHPL-Q.CONTENT-Z @ _RSHPL-I32? 0= OR
    _RSHPL-Q @ _RSHPL-Q.TASKBAR-Z @ _RSHPL-I32? 0= OR IF 0 EXIT THEN
    _RSHPL-Q @ _RSHPL-Q.CONTENT-Z @ _RSHPL-Q @ _RSHPL-Q.CHROME-Z @ < IF 0 EXIT THEN
    _RSHPL-Q @ _RSHPL-Q.RESULT-U @ RSHPL-RESULT-SIZE < IF 0 EXIT THEN
    _RSHPL-Q @ _RSHPL-Q.ELIGIBLE-U @ ?DUP IF
        _RSHPL-M @ SHM.COUNT @ 8 * <> IF 0 EXIT THEN
        _RSHPL-M @ SHM.COUNT @ 0 ?DO
            I _RSHPL-PANE? DUP 1 U> IF DROP 0 UNLOOP EXIT THEN
            I _RSHPL-ENTRY SHME.KIND @ SHM-K-PANE <> AND IF 0 UNLOOP EXIT THEN
        LOOP
    THEN -1 ;

: _RSHPL-CHROME-COUNT ( e -- count )
    DUP SHME.CONTENT-ROW @ OVER SHME.ROW @ > IF 1 ELSE 0 THEN
    OVER DUP SHME.CONTENT-ROW @ SWAP SHME.CONTENT-H @ +
    2 PICK DUP SHME.ROW @ SWAP SHME.HEIGHT @ + < IF 1+ THEN
    OVER SHME.CONTENT-COL @ 2 PICK SHME.COL @ > IF 1+ THEN
    OVER DUP SHME.CONTENT-COL @ SWAP SHME.CONTENT-W @ +
    2 PICK DUP SHME.COL @ SWAP SHME.WIDTH @ + < IF 1+ THEN NIP ;
: _RSHPL-BAND-EXCLUSIVE? ( kind -- flag )
    DUP _RSHPL-K ! _RSHPL-BAND-BOUNDS _RSHPL-BAND-W ! _RSHPL-BAND-C !
    _RSHPL-M @ SHM.COUNT @ 0 ?DO
        I _RSHPL-ENTRY DUP SHME.KIND @ DUP SHM-K-PANE <>
        SWAP _RSHPL-K @ <> AND IF
            DUP SHME.COL @ _RSHPL-BAND-C @ _RSHPL-BAND-W @ + <
            OVER SHME.COL @ ROT SHME.WIDTH @ + _RSHPL-BAND-C @ > AND IF
                0 UNLOOP EXIT
            THEN
        ELSE DROP THEN
    LOOP -1 ;
: _RSHPL-CHROME-UNOBSCURED? ( -- flag )
    _RSHPL-M @ SHM.COUNT @ 0 ?DO
        I _RSHPL-PANE? IF
            I _RSHPL-ENTRY _RSHPL-OTHER !
            _RSHPL-E @ SHME.COL @ _RSHPL-OTHER @ SHME.CONTENT-COL @ MAX _RSHPL-LEFT !
            _RSHPL-E @ SHME.COL @ _RSHPL-E @ SHME.WIDTH @ +
            _RSHPL-OTHER @ SHME.CONTENT-COL @ _RSHPL-OTHER @ SHME.CONTENT-W @ +
                MIN _RSHPL-RIGHT !
            _RSHPL-E @ SHME.ROW @ _RSHPL-OTHER @ SHME.CONTENT-ROW @ MAX _RSHPL-TOP !
            _RSHPL-E @ SHME.ROW @ _RSHPL-E @ SHME.HEIGHT @ +
            _RSHPL-OTHER @ SHME.CONTENT-ROW @ _RSHPL-OTHER @ SHME.CONTENT-H @ +
                MIN _RSHPL-BOTTOM !
            _RSHPL-RIGHT @ _RSHPL-LEFT @ > _RSHPL-BOTTOM @ _RSHPL-TOP @ > AND IF
                _RSHPL-LEFT @ _RSHPL-E @ SHME.CONTENT-COL @ <
                _RSHPL-RIGHT @ _RSHPL-E @ SHME.CONTENT-COL @ _RSHPL-E @ SHME.CONTENT-W @ + > OR
                _RSHPL-TOP @ _RSHPL-E @ SHME.CONTENT-ROW @ < OR
                _RSHPL-BOTTOM @ _RSHPL-E @ SHME.CONTENT-ROW @ _RSHPL-E @ SHME.CONTENT-H @ + > OR
                    IF 0 UNLOOP EXIT THEN
            THEN
        THEN
    LOOP -1 ;
: _RSHPL-COUNT? ( -- flag )
    _RSHPL-RESET
    _RSHPL-M @ SHM.COUNT @ 0 ?DO
        I _RSHPL-ENTRY _RSHPL-E !
        _RSHPL-E @ SHME.KIND @ SHM-K-PANE = IF
            I _RSHPL-PANE? IF
                _RSHPL-CHROME-UNOBSCURED? 0= IF 0 UNLOOP EXIT THEN
                _RSHPL-E @ SHME.ROW @ _RSHPL-I32? 0=
                _RSHPL-E @ SHME.COL @ _RSHPL-I32? 0= OR
                _RSHPL-E @ SHME.CONTENT-ROW @ _RSHPL-I32? 0= OR
                _RSHPL-E @ SHME.CONTENT-COL @ _RSHPL-I32? 0= OR
                    IF 0 UNLOOP EXIT THEN
                1 _RSHPL-PANES +!
                _RSHPL-E @ SHME.TITLE-U @ DUP _RSHPL-TEXT +! _RSHPL-PANE-UTF8 +!
                _RSHPL-E @ _RSHPL-CHROME-COUNT _RSHPL-CLAIMS +!
                _RSHPL-E @ SHME.FLAGS @ SHM-F-OVERLAY AND IF
                    _RSHPL-Q @ _RSHPL-Q.CONTENT-Z @ 2147483647 = IF 0 UNLOOP EXIT THEN
                THEN
            THEN
        ELSE
            _RSHPL-E @ SHME.KIND @ _RSHPL-BAND? IF
                _RSHPL-M @ SHM.FLAGS @ SHM-F-TASKBAR-HIDDEN AND 0= IF
                    _RSHPL-E @ _RSHPL-BAND-FITS? 0= IF 0 UNLOOP EXIT THEN
                    _RSHPL-E @ SHME.KIND @ SHM-K-TASK = IF
                        1 _RSHPL-TASK-N +!
                    ELSE 1 _RSHPL-LAUNCH-N +! THEN
                    1 _RSHPL-CONTROLS +!
                    _RSHPL-E @ SHME.LABEL-U @ DUP _RSHPL-TEXT +! _RSHPL-CONTROL-UTF8 +!
                    _RSHPL-E @ SHME.ACTION-U @ _RSHPL-ACTIONS +!
                THEN
            THEN
        THEN
    LOOP
    _RSHPL-TASK-N @ IF SHM-K-TASK _RSHPL-BAND-EXCLUSIVE? 0= IF 0 EXIT THEN THEN
    _RSHPL-LAUNCH-N @ IF SHM-K-LAUNCHER _RSHPL-BAND-EXCLUSIVE? 0= IF 0 EXIT THEN THEN
    _RSHPL-TASK-N @ 0<> IF 1 _RSHPL-ROOTS +! THEN
    _RSHPL-LAUNCH-N @ 0<> IF 1 _RSHPL-ROOTS +! THEN
    _RSHPL-ROOTS @ _RSHPL-CONTROLS +!
    _RSHPL-ROOTS @ _RSHPL-CLAIMS +!
    _RSHPL-PANES @ DUP IF 1+ THEN
    _RSHPL-ROOTS @ IF 1+ THEN _RSHPL-REGIONS !
    _RSHPL-PANES @ _RSHPL-CONTROLS @ + _RSHPL-CORRS ! -1 ;
: _RSHPL-IDS? ( first count -- flag )
    DUP 0= IF 2DROP -1 EXIT THEN OVER 0= IF 2DROP 0 EXIT THEN
    1- OVER + SWAP U< 0= ;
: _RSHPL-CAPACITY? ( -- flag )
    _RSHPL-REGIONS @ RTE-INSTRUMENT-REGION-SIZE * _RSHPL-Q @ _RSHPL-Q.REGIONS-U @ U>
    _RSHPL-PANES @ RTE-PANE-SIZE * _RSHPL-Q @ _RSHPL-Q.PANES-U @ U> OR
    _RSHPL-CONTROLS @ RTE-CONTROL-SIZE * _RSHPL-Q @ _RSHPL-Q.CONTROLS-U @ U> OR
    _RSHPL-TEXT @ _RSHPL-Q @ _RSHPL-Q.TEXT-U @ U> OR
    _RSHPL-ACTIONS @ _RSHPL-Q @ _RSHPL-Q.ACTIONS-U @ U> OR
    _RSHPL-CORRS @ RSHPL-CORRELATION-SIZE * _RSHPL-Q @ _RSHPL-Q.CORRELATIONS-U @ U> OR
    _RSHPL-CLAIMS @ RSHPL-CLAIM-SIZE * _RSHPL-Q @ _RSHPL-Q.CLAIMS-U @ U> OR IF 0 EXIT THEN
    _RSHPL-Q @ _RSHPL-Q.FIRST-REGION @ _RSHPL-REGIONS @ _RSHPL-IDS?
    _RSHPL-Q @ _RSHPL-Q.FIRST-OBJECT @ _RSHPL-PANES @ _RSHPL-IDS? AND
    _RSHPL-Q @ _RSHPL-Q.FIRST-CONTROL @ _RSHPL-CONTROLS @ _RSHPL-IDS? AND ;

VARIABLE _RSHPL-TEXT-N VARIABLE _RSHPL-ACTION-N VARIABLE _RSHPL-RID
VARIABLE _RSHPL-Z VARIABLE _RSHPL-GAP-N VARIABLE _RSHPL-GAP-I
VARIABLE _RSHPL-GAP-C VARIABLE _RSHPL-GAP-END
3 CONSTANT RSHPL-S-END

\ Enumerate only the source's blank-spacing rectangles. The publisher must
\ check these exact cells are ordinary spaces and that the entire selected
\ band is clear under SHSN-RECT-CLEAR? for the completed draw. END returns
\ canonical zero geometry. No source text is interpreted.
: _RSHPL-GAP-TAKE? ( end-col -- found? )
    _RSHPL-GAP-C @ > IF
        _RSHPL-GAP-I @ _RSHPL-GAP-N @ = IF -1 EXIT THEN
        1 _RSHPL-GAP-I +!
    THEN 0 ;
: _RSHPL-GAP-RETURN ( end-col -- row col height width status )
    _RSHPL-GAP-C @ - >R
    _RSHPL-M @ SHM.HEIGHT @ 1- _RSHPL-GAP-C @ 1 R> RSHPL-S-OK ;
: _RSHPL-GAP-BOUNDS-OF ( ordinal kind model bytes -- row col height width status )
    2DUP _RSHPL-MODEL-OK? 0= IF
        2DROP 2DROP 0 0 0 0 RSHPL-S-INVALID EXIT
    THEN DROP _RSHPL-M ! _RSHPL-K ! _RSHPL-GAP-N !
    _RSHPL-K @ DUP SHM-K-TASK = SWAP SHM-K-LAUNCHER = OR 0=
    _RSHPL-GAP-N @ 0< OR IF 0 0 0 0 RSHPL-S-INVALID EXIT THEN
    _RSHPL-K @ _RSHPL-BAND-BOUNDS OVER + _RSHPL-GAP-END ! _RSHPL-GAP-C !
    0 _RSHPL-GAP-I !
    _RSHPL-M @ SHM.COUNT @ 0 ?DO
        I _RSHPL-ENTRY _RSHPL-E !
        _RSHPL-E @ SHME.KIND @ _RSHPL-K @ = IF
            _RSHPL-E @ _RSHPL-BAND-FITS? 0= IF
                0 0 0 0 RSHPL-S-INVALID UNLOOP EXIT
            THEN
            _RSHPL-E @ SHME.COL @ DUP _RSHPL-GAP-TAKE? IF
                _RSHPL-GAP-RETURN UNLOOP EXIT
            THEN DROP
            _RSHPL-E @ SHME.COL @ _RSHPL-E @ SHME.WIDTH @ + _RSHPL-GAP-C !
        THEN
    LOOP
    _RSHPL-GAP-END @ DUP _RSHPL-GAP-TAKE? IF _RSHPL-GAP-RETURN EXIT THEN
    DROP 0 0 0 0 RSHPL-S-END ;
: RSHPL-GAP-BOUNDS ( ordinal kind model bytes -- row col height width status )
    0 _RSHPL-PROVED ! _RSHPL-GAP-BOUNDS-OF ;
: _RSHPL-GAP-BOUNDS-PROVED ( ordinal kind model bytes -- row col height width status )
    -1 _RSHPL-PROVED ! _RSHPL-GAP-BOUNDS-OF 0 _RSHPL-PROVED ! ;

: _RSHPL-REGION ( z row col height width -- id )
    _RSHPL-CW ! _RSHPL-CH ! _RSHPL-CCOL ! _RSHPL-CROW ! _RSHPL-Z !
    _RSHPL-REGIONS @ RTE-INSTRUMENT-REGION-SIZE * _RSHPL-Q @ _RSHPL-Q.REGIONS-A @ +
        DUP _RSHPL-R ! RTE-INSTRUMENT-REGION-SIZE 0 FILL
    _RSHPL-NEXT-R @ _RSHPL-R @ _RTE-IR.ID !
    _RSHPL-M @ SHM.WIDTH @ _RSHPL-R @ _RTE-IR.COLS !
    _RSHPL-M @ SHM.HEIGHT @ _RSHPL-R @ _RTE-IR.ROWS !
    _RSHPL-CCOL @ _RSHPL-R @ _RTE-IR.CLIP-X !
    _RSHPL-CROW @ _RSHPL-R @ _RTE-IR.CLIP-Y !
    _RSHPL-CW @ _RSHPL-R @ _RTE-IR.CLIP-COLS !
    _RSHPL-CH @ _RSHPL-R @ _RTE-IR.CLIP-ROWS !
    _RSHPL-Z @ _RSHPL-R @ _RTE-IR.Z !
    RTE-REGION-VISIBLE RTE-REGION-CLIPPED OR _RSHPL-R @ _RTE-IR.FLAGS !
    1 _RSHPL-REGIONS +! _RSHPL-NEXT-R @ 1 _RSHPL-NEXT-R +! ;
: _RSHPL-COPY$ ( a u -- offset )
    _RSHPL-TEXT @ >R
    DUP IF
        DUP >R _RSHPL-Q @ _RSHPL-Q.TEXT-A @ _RSHPL-TEXT @ + SWAP CMOVE
        R> _RSHPL-TEXT +!
    ELSE 2DROP THEN R> ;
: _RSHPL-COPY-ACTION$ ( a u -- offset )
    _RSHPL-ACTIONS @ >R
    DUP IF
        DUP >R _RSHPL-Q @ _RSHPL-Q.ACTIONS-A @ _RSHPL-ACTIONS @ + SWAP CMOVE
        R> _RSHPL-ACTIONS +!
    ELSE 2DROP THEN R> ;
: _RSHPL-TEXT$ ( offset bytes -- a u )
    DUP 0= IF 2DROP 0 0 ELSE SWAP _RSHPL-Q @ _RSHPL-Q.TEXT-A @ + SWAP THEN ;
: _RSHPL-CORRELATE ( kind -- )
    _RSHPL-CORRS @ RSHPL-CORRELATION-SIZE * _RSHPL-Q @ _RSHPL-Q.CORRELATIONS-A @ +
        DUP _RSHPL-X ! RSHPL-CORRELATION-SIZE 0 FILL
    _RSHPL-X @ RSHPL-CORRELATION.KIND !
    _RSHPL-I @ _RSHPL-X @ RSHPL-CORRELATION.INDEX !
    _RSHPL-ID @ _RSHPL-X @ RSHPL-CORRELATION.ID !
    _RSHPL-RID @ _RSHPL-X @ RSHPL-CORRELATION.REGION !
    _RSHPL-CONTENT @ _RSHPL-X @ RSHPL-CORRELATION.CONTENT-REGION !
    _RSHPL-M @ SHM.OWNER-ID @ _RSHPL-X @ RSHPL-CORRELATION.SOURCE-OWNER !
    _RSHPL-M @ SHM.OWNER-GEN @ _RSHPL-X @ RSHPL-CORRELATION.SOURCE-GENERATION !
    _RSHPL-M @ SHM.EPOCH @ _RSHPL-X @ RSHPL-CORRELATION.EPOCH !
    _RSHPL-Q @ _RSHPL-Q.DRAW @ _RSHPL-X @ RSHPL-CORRELATION.DRAW !
    _RSHPL-Q @ _RSHPL-Q.ATTACHMENT @ _RSHPL-X @ RSHPL-CORRELATION.ATTACHMENT !
    _RSHPL-I @ 0>= IF
        _RSHPL-E @ SHME.KEY @ _RSHPL-X @ RSHPL-CORRELATION.KEY !
        _RSHPL-E @ SHME.IDENTITY @ _RSHPL-X @ RSHPL-CORRELATION.IDENTITY !
        _RSHPL-E @ SHME.OWNER-ID @ _RSHPL-X @ RSHPL-CORRELATION.OWNER !
        _RSHPL-E @ SHME.OWNER-GEN @ _RSHPL-X @ RSHPL-CORRELATION.GENERATION !
        _RSHPL-E @ SHME.ACTION @ _RSHPL-X @ RSHPL-CORRELATION.ACTION !
        _RSHPL-E @ SHME.FLAGS @ _RSHPL-X @ RSHPL-CORRELATION.FLAGS !
        _RSHPL-E @ SHME.ROW @ _RSHPL-X @ RSHPL-CORRELATION.ROW !
        _RSHPL-E @ SHME.COL @ _RSHPL-X @ RSHPL-CORRELATION.COL !
        _RSHPL-E @ SHME.HEIGHT @ _RSHPL-X @ RSHPL-CORRELATION.HEIGHT !
        _RSHPL-E @ SHME.WIDTH @ _RSHPL-X @ RSHPL-CORRELATION.WIDTH !
    ELSE
        _RSHPL-M @ SHM.OWNER-ID @ _RSHPL-X @ RSHPL-CORRELATION.OWNER !
        _RSHPL-M @ SHM.OWNER-GEN @ _RSHPL-X @ RSHPL-CORRELATION.GENERATION !
        _RSHPL-M @ SHM.FLAGS @ _RSHPL-X @ RSHPL-CORRELATION.FLAGS !
        _RSHPL-M @ SHM.HEIGHT @ 1- _RSHPL-X @ RSHPL-CORRELATION.ROW !
        _RSHPL-BAND-C @ _RSHPL-X @ RSHPL-CORRELATION.COL !
        1 _RSHPL-X @ RSHPL-CORRELATION.HEIGHT !
        _RSHPL-BAND-W @ _RSHPL-X @ RSHPL-CORRELATION.WIDTH !
    THEN
    _RSHPL-TEXT-O @ _RSHPL-X @ RSHPL-CORRELATION.TEXT-OFFSET !
    _RSHPL-TEXT-N @ _RSHPL-X @ RSHPL-CORRELATION.TEXT-BYTES !
    _RSHPL-ACTION-O @ _RSHPL-X @ RSHPL-CORRELATION.ACTION-OFFSET !
    _RSHPL-ACTION-N @ _RSHPL-X @ RSHPL-CORRELATION.ACTION-BYTES !
    1 _RSHPL-CORRS +! ;
: _RSHPL-CLAIM ( row col height width -- )
    DUP 0= 2 PICK 0= OR IF 2DROP 2DROP EXIT THEN
    _RSHPL-CLAIMS @ RSHPL-CLAIM-SIZE * _RSHPL-Q @ _RSHPL-Q.CLAIMS-A @ +
        DUP _RSHPL-X ! RSHPL-CLAIM-SIZE 0 FILL
    _RSHPL-X @ RSHPL-CLAIM.WIDTH ! _RSHPL-X @ RSHPL-CLAIM.HEIGHT !
    _RSHPL-X @ RSHPL-CLAIM.COL ! _RSHPL-X @ RSHPL-CLAIM.ROW !
    _RSHPL-I @ _RSHPL-X @ RSHPL-CLAIM.INDEX !
    _RSHPL-K @ _RSHPL-X @ RSHPL-CLAIM.KIND !
    _RSHPL-ID @ _RSHPL-X @ RSHPL-CLAIM.ID !
    _RSHPL-RID @ _RSHPL-X @ RSHPL-CLAIM.REGION !
    1 _RSHPL-CLAIMS +! ;
: _RSHPL-PANE-CLAIMS ( -- )
    RSHPL-CLAIM-PANE _RSHPL-K !
    _RSHPL-E @ SHME.ROW @ _RSHPL-E @ SHME.COL @
    _RSHPL-E @ SHME.CONTENT-ROW @ _RSHPL-E @ SHME.ROW @ -
    _RSHPL-E @ SHME.WIDTH @ _RSHPL-CLAIM
    _RSHPL-E @ SHME.CONTENT-ROW @ _RSHPL-E @ SHME.CONTENT-H @ +
    _RSHPL-E @ SHME.COL @
    _RSHPL-E @ SHME.ROW @ _RSHPL-E @ SHME.HEIGHT @ +
        _RSHPL-E @ SHME.CONTENT-ROW @ _RSHPL-E @ SHME.CONTENT-H @ + -
    _RSHPL-E @ SHME.WIDTH @ _RSHPL-CLAIM
    _RSHPL-E @ SHME.CONTENT-ROW @ _RSHPL-E @ SHME.COL @
    _RSHPL-E @ SHME.CONTENT-H @
    _RSHPL-E @ SHME.CONTENT-COL @ _RSHPL-E @ SHME.COL @ - _RSHPL-CLAIM
    _RSHPL-E @ SHME.CONTENT-ROW @
    _RSHPL-E @ SHME.CONTENT-COL @ _RSHPL-E @ SHME.CONTENT-W @ +
    _RSHPL-E @ SHME.CONTENT-H @
    _RSHPL-E @ SHME.COL @ _RSHPL-E @ SHME.WIDTH @ +
        _RSHPL-E @ SHME.CONTENT-COL @ _RSHPL-E @ SHME.CONTENT-W @ + -
    _RSHPL-CLAIM ;
: _RSHPL-PANE ( -- )
    _RSHPL-Q @ _RSHPL-Q.CONTENT-Z @
    _RSHPL-E @ SHME.FLAGS @ SHM-F-OVERLAY AND IF 1+ THEN
    _RSHPL-E @ SHME.CONTENT-ROW @ _RSHPL-E @ SHME.CONTENT-COL @
    _RSHPL-E @ SHME.CONTENT-H @ _RSHPL-E @ SHME.CONTENT-W @
    _RSHPL-REGION _RSHPL-CONTENT !
    _RSHPL-PANES @ RTE-PANE-SIZE * _RSHPL-Q @ _RSHPL-Q.PANES-A @ +
        DUP _RSHPL-P ! RTE-PANE-SIZE 0 FILL
    _RSHPL-NEXT-O @ _RSHPL-ID ! 1 _RSHPL-NEXT-O +!
    _RSHPL-Q @ _RSHPL-Q.OWNER @ _RSHPL-P @ _RTE-PANE.OWNER !
    _RSHPL-Q @ _RSHPL-Q.GENERATION @ _RSHPL-P @ _RTE-PANE.GENERATION !
    _RSHPL-ID @ _RSHPL-P @ _RTE-PANE.ID !
    RTE-PANE-STANDARD _RSHPL-P @ _RTE-PANE.KIND !
    -1 _RSHPL-P @ _RTE-PANE.VISIBLE !
    _RSHPL-CHROME @ DUP _RSHPL-RID ! _RSHPL-P @ _RTE-PANE.REGION !
    _RSHPL-E @ SHME.ROW @ _RSHPL-P @ _RTE-PANE.ROW !
    _RSHPL-E @ SHME.COL @ _RSHPL-P @ _RTE-PANE.COL !
    _RSHPL-E @ SHME.HEIGHT @ _RSHPL-P @ _RTE-PANE.HEIGHT !
    _RSHPL-E @ SHME.WIDTH @ _RSHPL-P @ _RTE-PANE.WIDTH !
    _RSHPL-M @ SHM.HEIGHT @ _RSHPL-P @ _RTE-PANE.ROOT-HEIGHT !
    _RSHPL-M @ SHM.WIDTH @ _RSHPL-P @ _RTE-PANE.ROOT-WIDTH !
    _RSHPL-CONTENT @ _RSHPL-P @ _RTE-PANE.CONTENT-REGION !
    _RSHPL-E @ SHME.CONTENT-ROW @ _RSHPL-E @ SHME.ROW @ -
        _RSHPL-P @ _RTE-PANE.CONTENT-ROW !
    _RSHPL-E @ SHME.CONTENT-COL @ _RSHPL-E @ SHME.COL @ -
        _RSHPL-P @ _RTE-PANE.CONTENT-COL !
    _RSHPL-E @ SHME.CONTENT-H @ _RSHPL-P @ _RTE-PANE.CONTENT-HEIGHT !
    _RSHPL-E @ SHME.CONTENT-W @ _RSHPL-P @ _RTE-PANE.CONTENT-WIDTH !
    _RSHPL-E @ SHME.FLAGS @ SHM-F-SELECTED AND IF -1 ELSE 0 THEN
        _RSHPL-P @ _RTE-PANE.FOCUSED !
    _RSHPL-E @ SHME.TITLE-U @ _RSHPL-TEXT-N !
    _RSHPL-E @ _RSHPL-M @ SHME-TITLE$ _RSHPL-COPY$ _RSHPL-TEXT-O !
    _RSHPL-TEXT-O @ _RSHPL-TEXT-N @ _RSHPL-TEXT$
        _RSHPL-P @ _RTE-PANE.TITLE-U ! _RSHPL-P @ _RTE-PANE.TITLE-A !
    0 _RSHPL-ACTION-O ! 0 _RSHPL-ACTION-N !
    SHM-K-PANE _RSHPL-CORRELATE _RSHPL-PANE-CLAIMS 1 _RSHPL-PANES +! ;

: _RSHPL-CONTROL ( -- )
    _RSHPL-CONTROLS @ RTE-CONTROL-SIZE * _RSHPL-Q @ _RSHPL-Q.CONTROLS-A @ +
        DUP _RSHPL-C ! RTE-CONTROL-SIZE 0 FILL
    _RSHPL-NEXT-C @ _RSHPL-ID ! 1 _RSHPL-NEXT-C +!
    _RSHPL-Q @ _RSHPL-Q.OWNER @ _RSHPL-C @ _RTE-CONTROL.OWNER !
    _RSHPL-Q @ _RSHPL-Q.GENERATION @ _RSHPL-C @ _RTE-CONTROL.GENERATION !
    _RSHPL-ID @ _RSHPL-C @ _RTE-CONTROL.ID !
    _RSHPL-TBREG @ DUP _RSHPL-RID ! _RSHPL-C @ _RTE-CONTROL.REGION !
    _RSHPL-M @ SHM.HEIGHT @ _RSHPL-C @ _RTE-CONTROL.ROOT-HEIGHT !
    _RSHPL-M @ SHM.WIDTH @ _RSHPL-C @ _RTE-CONTROL.ROOT-WIDTH !
    1 _RSHPL-C @ _RTE-CONTROL.HEIGHT !
    0 _RSHPL-CONTENT ! 1 _RSHPL-CONTROLS +! ;
: _RSHPL-ROOT ( kind -- )
    DUP _RSHPL-BAND ! _RSHPL-BAND-BOUNDS _RSHPL-BAND-W ! _RSHPL-BAND-C !
    _RSHPL-CONTROL _RSHPL-ID @ _RSHPL-PARENT !
    RTE-CONTROL-TASKBAR _RSHPL-C @ _RTE-CONTROL.KIND !
    1 _RSHPL-M @ SHM.FLAGS @ SHM-F-INPUT-BLOCKED AND 0= IF 2 OR THEN
        _RSHPL-C @ _RTE-CONTROL.STATE !
    _RSHPL-M @ SHM.HEIGHT @ 1- _RSHPL-C @ _RTE-CONTROL.ROW !
    _RSHPL-BAND-C @ _RSHPL-C @ _RTE-CONTROL.COL !
    _RSHPL-BAND-W @ _RSHPL-C @ _RTE-CONTROL.WIDTH !
    0 _RSHPL-TEXT-O ! 0 _RSHPL-TEXT-N ! 0 _RSHPL-ACTION-O ! 0 _RSHPL-ACTION-N !
    _RSHPL-BAND @ SHM-K-TASK = IF
        -1 _RSHPL-I ! RSHPL-K-TASKBAR-TASKS
    ELSE -2 _RSHPL-I ! RSHPL-K-TASKBAR-LAUNCHERS THEN _RSHPL-CORRELATE
    RSHPL-CLAIM-TASKBAR _RSHPL-K !
    _RSHPL-M @ SHM.HEIGHT @ 1- _RSHPL-BAND-C @ 1 _RSHPL-BAND-W @ _RSHPL-CLAIM
    1 _RSHPL-ROOTS +! ;
: _RSHPL-CHILD ( -- )
    _RSHPL-CONTROL
    _RSHPL-PARENT @ _RSHPL-C @ _RTE-CONTROL.PARENT !
    _RSHPL-I @ _RSHPL-C @ _RTE-CONTROL.ORDER !
    _RSHPL-E @ SHME.COL @ _RSHPL-BAND-C @ - _RSHPL-C @ _RTE-CONTROL.COL !
    _RSHPL-E @ SHME.WIDTH @ _RSHPL-C @ _RTE-CONTROL.WIDTH !
    _RSHPL-E @ SHME.KIND @ SHM-K-TASK = IF
        RTE-CONTROL-TASK _RSHPL-C @ _RTE-CONTROL.KIND !
        3 _RSHPL-E @ SHME.FLAGS @ SHM-F-SELECTED AND IF 8 OR THEN
        _RSHPL-E @ SHME.FLAGS @ SHM-F-MINIMIZED AND IF 32 OR THEN
    ELSE
        RTE-CONTROL-LAUNCHER _RSHPL-C @ _RTE-CONTROL.KIND !
        1 _RSHPL-E @ SHME.FLAGS @ SHM-F-DISABLED AND
        _RSHPL-E @ SHME.ACTION @ 0= OR 0= IF 2 OR THEN
    THEN _RSHPL-C @ _RTE-CONTROL.STATE !
    _RSHPL-E @ SHME.LABEL-U @ _RSHPL-TEXT-N !
    _RSHPL-E @ _RSHPL-M @ SHME-LABEL$ _RSHPL-COPY$ _RSHPL-TEXT-O !
    _RSHPL-TEXT-O @ _RSHPL-TEXT-N @ _RSHPL-TEXT$
        _RSHPL-C @ _RTE-CONTROL.LABEL-U ! _RSHPL-C @ _RTE-CONTROL.LABEL-A !
    _RSHPL-E @ SHME.ACTION-U @ _RSHPL-ACTION-N !
    _RSHPL-ACTION-N @ IF
        _RSHPL-E @ _RSHPL-M @ SHME-ACTION$ _RSHPL-COPY-ACTION$ _RSHPL-ACTION-O !
    ELSE 0 _RSHPL-ACTION-O ! THEN
    _RSHPL-E @ SHME.KIND @ _RSHPL-CORRELATE ;
: _RSHPL-BAND-EMIT ( kind -- )
    _RSHPL-ROOT
    _RSHPL-M @ SHM.COUNT @ 0 ?DO
        I _RSHPL-ENTRY _RSHPL-E !
        _RSHPL-E @ SHME.KIND @ _RSHPL-BAND @ = IF
            I _RSHPL-I ! _RSHPL-CHILD
        THEN
    LOOP ;
: _RSHPL-EMIT ( -- )
    _RSHPL-PANES @ _RSHPL-N !
    _RSHPL-Q @ _RSHPL-Q.FIRST-REGION @ _RSHPL-NEXT-R !
    _RSHPL-Q @ _RSHPL-Q.FIRST-OBJECT @ _RSHPL-NEXT-O !
    _RSHPL-Q @ _RSHPL-Q.FIRST-CONTROL @ _RSHPL-NEXT-C !
    0 _RSHPL-REGIONS ! 0 _RSHPL-PANES ! 0 _RSHPL-CONTROLS ! 0 _RSHPL-TEXT !
    0 _RSHPL-CORRS ! 0 _RSHPL-CLAIMS ! 0 _RSHPL-ROOTS ! 0 _RSHPL-ACTIONS !
    _RSHPL-N @ IF
        _RSHPL-Q @ _RSHPL-Q.CHROME-Z @ 0 0
        _RSHPL-M @ SHM.HEIGHT @ _RSHPL-M @ SHM.WIDTH @
        _RSHPL-REGION _RSHPL-CHROME !
        _RSHPL-M @ SHM.COUNT @ 0 ?DO
            I _RSHPL-PANE? IF
                I _RSHPL-I ! I _RSHPL-ENTRY _RSHPL-E ! _RSHPL-PANE
            THEN
        LOOP
    THEN
    _RSHPL-TASK-N @ _RSHPL-LAUNCH-N @ OR IF
        _RSHPL-Q @ _RSHPL-Q.TASKBAR-Z @
        _RSHPL-M @ SHM.HEIGHT @ 1- 0 1 _RSHPL-M @ SHM.END-COL @
        _RSHPL-REGION _RSHPL-TBREG !
        _RSHPL-TASK-N @ IF SHM-K-TASK _RSHPL-BAND-EMIT THEN
        _RSHPL-LAUNCH-N @ IF SHM-K-LAUNCHER _RSHPL-BAND-EMIT THEN
    THEN ;
: _RSHPL-LAST ( next count -- last ) IF 1- ELSE DROP 0 THEN ;
: _RSHPL-RESULT ( -- )
    _RSHPL-Q @ _RSHPL-Q.RESULT-A @ _RSHPL-R !
    _RSHPL-REGIONS @ _RSHPL-R @ RSHPL-RESULT.REGIONS !
    _RSHPL-PANES @ _RSHPL-R @ RSHPL-RESULT.PANES !
    _RSHPL-CONTROLS @ _RSHPL-R @ RSHPL-RESULT.CONTROLS !
    _RSHPL-TEXT @ _RSHPL-R @ RSHPL-RESULT.TEXT-BYTES !
    _RSHPL-CORRS @ _RSHPL-R @ RSHPL-RESULT.CORRELATIONS !
    _RSHPL-CLAIMS @ _RSHPL-R @ RSHPL-RESULT.CLAIMS !
    _RSHPL-NEXT-R @ _RSHPL-REGIONS @ _RSHPL-LAST _RSHPL-R @ RSHPL-RESULT.LAST-REGION !
    _RSHPL-NEXT-O @ _RSHPL-PANES @ _RSHPL-LAST _RSHPL-R @ RSHPL-RESULT.LAST-OBJECT !
    _RSHPL-NEXT-C @ _RSHPL-CONTROLS @ _RSHPL-LAST _RSHPL-R @ RSHPL-RESULT.LAST-CONTROL !
    _RSHPL-ROOTS @ _RSHPL-R @ RSHPL-RESULT.TASKBARS !
    _RSHPL-M @ SHM.EPOCH @ _RSHPL-R @ RSHPL-RESULT.EPOCH !
    _RSHPL-M @ SHM.OWNER-ID @ _RSHPL-R @ RSHPL-RESULT.SOURCE-OWNER !
    _RSHPL-M @ SHM.OWNER-GEN @ _RSHPL-R @ RSHPL-RESULT.SOURCE-GENERATION !
    _RSHPL-Q @ _RSHPL-Q.DRAW @ _RSHPL-R @ RSHPL-RESULT.DRAW !
    _RSHPL-Q @ _RSHPL-Q.ATTACHMENT @ _RSHPL-R @ RSHPL-RESULT.ATTACHMENT !
    _RSHPL-PANE-UTF8 @ _RSHPL-R @ RSHPL-RESULT.PANE-UTF8 !
    _RSHPL-CONTROL-UTF8 @ _RSHPL-R @ RSHPL-RESULT.CONTROL-UTF8 !
    _RSHPL-ACTIONS @ _RSHPL-R @ RSHPL-RESULT.ACTION-BYTES ! ;
: _RSHPL-BODY ( -- status )
    _RSHPL-SOURCE? 0= IF RSHPL-S-INVALID EXIT THEN
    _RSHPL-COUNT? 0= IF RSHPL-S-INVALID EXIT THEN
    _RSHPL-CAPACITY? 0= IF RSHPL-S-CAPACITY EXIT THEN
    _RSHPL-EMIT _RSHPL-RESULT RSHPL-S-OK ;
: RSHPL-BUILD ( q -- status )
    _RSHPL-SPANS? 0= IF RSHPL-S-INVALID EXIT THEN
    _RSHPL-CLEAR-OUTPUTS
    ['] _RSHPL-BODY CATCH ?DUP IF
        DROP _RSHPL-CLEAR-OUTPUTS RSHPL-S-INVALID EXIT
    THEN DUP RSHPL-S-OK <> IF _RSHPL-CLEAR-OUTPUTS THEN ;
HERE _RSHPL-OWNED-LIMIT !
