\ =====================================================================
\  uidl-driver.f -- caller-bounded UIDL rich-terminal lifecycle driver
\ =====================================================================
\
\  This optional adapter owns private host bindings above a future neutral
\  semantic engine facade.  It is deliberately wire-inert until complete
\  UIDL semantic projectors and their truthful capacity admission exist.
\  Applications, Desk, and the baseline UIDL closure do not load this module.
\
\  Prefix:   RTERM- (contract), RTERM-UIDL- (driver construction)
\  Provider: akashic-tui-rterm-uidl1

PROVIDED akashic-tui-rterm-uidl1

REQUIRE ../applet-host/host.f
REQUIRE ../../utils/memory-span.f

\ =====================================================================
\  Stable host/driver statuses
\ =====================================================================

0 CONSTANT RTERM-S-OK
1 CONSTANT RTERM-S-WOULD-BLOCK
2 CONSTANT RTERM-S-UNAVAILABLE
3 CONSTANT RTERM-S-CAPACITY
4 CONSTANT RTERM-S-STALE
5 CONSTANT RTERM-S-INVALID
6 CONSTANT RTERM-S-SESSION-LOST
7 CONSTANT RTERM-S-SOURCE

: RTERM-STATUS-VALID?  ( status -- flag )
    8 U< ;

\ =====================================================================
\  Immutable call-borrowed host binding
\ =====================================================================

1 CONSTANT _RTERM-HB-ABI
0x5254484F53544231 CONSTANT _RTERM-HB-MAGIC  \ "RTHOSTB1"

 0 CONSTANT _RTERM-HB-O-MAGIC
 8 CONSTANT _RTERM-HB-O-ABI
16 CONSTANT _RTERM-HB-O-SIZE
24 CONSTANT _RTERM-HB-O-HOST
32 CONSTANT _RTERM-HB-O-SLOT
40 CONSTANT _RTERM-HB-O-SLOT-ID
48 CONSTANT _RTERM-HB-O-INST
56 CONSTANT _RTERM-HB-O-INST-ID
64 CONSTANT _RTERM-HB-O-INST-GEN
72 CONSTANT _RTERM-HB-O-UCTX
80 CONSTANT _RTERM-HB-O-REGION
88 CONSTANT _RTERM-HB-O-RESERVED
96 CONSTANT RTERM-HOST-BINDING-SIZE

: _RTERM-HB.MAGIC     ( hb -- a ) _RTERM-HB-O-MAGIC + ;
: _RTERM-HB.ABI       ( hb -- a ) _RTERM-HB-O-ABI + ;
: _RTERM-HB.SIZE      ( hb -- a ) _RTERM-HB-O-SIZE + ;
: _RTERM-HB.HOST      ( hb -- a ) _RTERM-HB-O-HOST + ;
: _RTERM-HB.SLOT      ( hb -- a ) _RTERM-HB-O-SLOT + ;
: _RTERM-HB.SLOT-ID   ( hb -- a ) _RTERM-HB-O-SLOT-ID + ;
: _RTERM-HB.INST      ( hb -- a ) _RTERM-HB-O-INST + ;
: _RTERM-HB.INST-ID   ( hb -- a ) _RTERM-HB-O-INST-ID + ;
: _RTERM-HB.INST-GEN  ( hb -- a ) _RTERM-HB-O-INST-GEN + ;
: _RTERM-HB.UCTX      ( hb -- a ) _RTERM-HB-O-UCTX + ;
: _RTERM-HB.REGION    ( hb -- a ) _RTERM-HB-O-REGION + ;
: _RTERM-HB.RESERVED  ( hb -- a ) _RTERM-HB-O-RESERVED + ;

\ =====================================================================
\  Caller-owned driver and binding records
\ =====================================================================

1 CONSTANT _RTERM-UIDL-ABI
0x52545549444C4231 CONSTANT _RTERM-UIDL-MAGIC  \ "RTUIDLB1"

0 CONSTANT _RTERM-BINDING-ST-FREE
1 CONSTANT _RTERM-BINDING-ST-ATTACHED
2 CONSTANT _RTERM-BINDING-ST-QUIESCED
3 CONSTANT _RTERM-BINDING-ST-DETACHED

\ A detached record retains only TOKEN, ISSUER, LAST-STATUS, and state.  It is
\ immediately idempotent but may be reclaimed by a later attach with a fresh
\ globally nonreused token.
: _RTERM-R.STATE       ( r -- a )       ;
: _RTERM-R.TOKEN       ( r -- a )   8 + ;
: _RTERM-R.ISSUER      ( r -- a )  16 + ;
: _RTERM-R.HOST        ( r -- a )  24 + ;
: _RTERM-R.SLOT        ( r -- a )  32 + ;
: _RTERM-R.SLOT-ID     ( r -- a )  40 + ;
: _RTERM-R.INST        ( r -- a )  48 + ;
: _RTERM-R.INST-ID     ( r -- a )  56 + ;
: _RTERM-R.INST-GEN    ( r -- a )  64 + ;
: _RTERM-R.UCTX        ( r -- a )  72 + ;
: _RTERM-R.REGION      ( r -- a )  80 + ;
: _RTERM-R.VISIBLE     ( r -- a )  88 + ;
: _RTERM-R.ROW         ( r -- a )  96 + ;
: _RTERM-R.COL         ( r -- a ) 104 + ;
: _RTERM-R.HEIGHT      ( r -- a ) 112 + ;
: _RTERM-R.WIDTH       ( r -- a ) 120 + ;
: _RTERM-R.LAST-STATUS ( r -- a ) 128 + ;
: _RTERM-R.RESERVED    ( r -- a ) 136 + ;

144 CONSTANT RTERM-UIDL-BINDING-SIZE

: _RTERM-B.MAGIC      ( b -- a )       ;
: _RTERM-B.ABI        ( b -- a )   8 + ;
: _RTERM-B.SIZE       ( b -- a )  16 + ;
: _RTERM-B.SELF       ( b -- a )  24 + ;
: _RTERM-B.HOST       ( b -- a )  32 + ;
: _RTERM-B.RECORDS-A  ( b -- a )  40 + ;
: _RTERM-B.RECORDS-U  ( b -- a )  48 + ;
: _RTERM-B.CAPACITY   ( b -- a )  56 + ;
: _RTERM-B.ACTIVE     ( b -- a )  64 + ;
: _RTERM-B.STATUS     ( b -- a )  72 + ;
: _RTERM-B.INSTALLED  ( b -- a )  80 + ;
: _RTERM-B.RESERVED   ( b -- a )  88 + ;

96 CONSTANT RTERM-UIDL-BACKEND-SIZE

: RTERM-UIDL-BINDING-BYTES  ( -- bytes )
    RTERM-UIDL-BINDING-SIZE ;

: RTERM-UIDL-BACKEND-BYTES  ( -- bytes )
    RTERM-UIDL-BACKEND-SIZE ;

\ =====================================================================
\  Checked geometry and storage
\ =====================================================================

: _RTERM-ALIGNED?  ( a -- flag )
    7 AND 0= ;

: _RTERM-SPAN?  ( a u -- flag )
    OVER 0<> OVER 0> AND 0= IF 2DROP 0 EXIT THEN
    OVER _RTERM-ALIGNED? 0= IF 2DROP 0 EXIT THEN
    MSPAN-NONWRAPPING? ;

: _RTERM-BOOL?  ( x -- flag )
    DUP 0= SWAP -1 = OR ;

: _RTERM-ZERO?  ( a u -- flag )
    0 ?DO
        DUP I + C@ IF DROP 0 UNLOOP EXIT THEN
    LOOP
    DROP -1 ;

: _RTERM-DISJOINT?  ( a u b v -- flag )
    MSPAN-OVERLAP? 0= ;

VARIABLE _RTERM-G-ROW
VARIABLE _RTERM-G-COL
VARIABLE _RTERM-G-HEIGHT
VARIABLE _RTERM-G-WIDTH
VARIABLE _RTERM-G-REGION

: _RTERM-GEOMETRY?  ( row col height width -- flag )
    _RTERM-G-WIDTH ! _RTERM-G-HEIGHT !
    _RTERM-G-COL ! _RTERM-G-ROW !
    _RTERM-G-ROW @ 0< IF 0 EXIT THEN
    _RTERM-G-COL @ 0< IF 0 EXIT THEN
    _RTERM-G-HEIGHT @ 0> 0= IF 0 EXIT THEN
    _RTERM-G-WIDTH @ 0> 0= IF 0 EXIT THEN
    _RTERM-G-ROW @ _RTERM-G-HEIGHT @ MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _RTERM-G-COL @ _RTERM-G-WIDTH @ MSPAN-NONWRAPPING? ;

: _RTERM-REGION-SANE?  ( region -- flag )
    DUP RGN-SIZE _RTERM-SPAN? 0= IF DROP 0 EXIT THEN
    _RTERM-G-REGION !
    _RTERM-G-REGION @ RGN-ROW
    _RTERM-G-REGION @ RGN-COL
    _RTERM-G-REGION @ RGN-H
    _RTERM-G-REGION @ RGN-W
    _RTERM-GEOMETRY? ;

: _RTERM-REGION>GEOMETRY  ( region -- )
    DUP RGN-ROW _RTERM-G-ROW !
    DUP RGN-COL _RTERM-G-COL !
    DUP RGN-H _RTERM-G-HEIGHT !
    RGN-W _RTERM-G-WIDTH ! ;

VARIABLE _RTERM-I-HOST
VARIABLE _RTERM-I-RECORDS-A
VARIABLE _RTERM-I-RECORDS-U
VARIABLE _RTERM-I-BACKEND

: _RTERM-UIDL-RANGES?  ( -- flag )
    _RTERM-I-HOST @ AHOST-SIZE _RTERM-SPAN? 0= IF 0 EXIT THEN
    _RTERM-I-RECORDS-A @ _RTERM-I-RECORDS-U @ _RTERM-SPAN? 0= IF 0 EXIT THEN
    _RTERM-I-BACKEND @ RTERM-UIDL-BACKEND-SIZE
        _RTERM-SPAN? 0= IF 0 EXIT THEN
    _RTERM-I-RECORDS-U @ RTERM-UIDL-BINDING-SIZE MOD IF 0 EXIT THEN
    _RTERM-I-RECORDS-U @ RTERM-UIDL-BINDING-SIZE / 0= IF 0 EXIT THEN
    _RTERM-I-HOST @ AHOST-SIZE
        _RTERM-I-RECORDS-A @ _RTERM-I-RECORDS-U @
        _RTERM-DISJOINT? 0= IF 0 EXIT THEN
    _RTERM-I-HOST @ AHOST-SIZE
        _RTERM-I-BACKEND @ RTERM-UIDL-BACKEND-SIZE
        _RTERM-DISJOINT? 0= IF 0 EXIT THEN
    _RTERM-I-RECORDS-A @ _RTERM-I-RECORDS-U @
        _RTERM-I-BACKEND @ RTERM-UIDL-BACKEND-SIZE
        _RTERM-DISJOINT? ;

: _RTERM-UIDL-INIT-BODY  ( host records-a records-u backend -- status )
    _RTERM-I-BACKEND ! _RTERM-I-RECORDS-U !
    _RTERM-I-RECORDS-A ! _RTERM-I-HOST !
    _RTERM-UIDL-RANGES? 0= IF RTERM-S-INVALID EXIT THEN
    _RTERM-I-BACKEND @ _RTERM-B.MAGIC @ _RTERM-UIDL-MAGIC = IF
        RTERM-S-INVALID EXIT
    THEN
    _RTERM-I-RECORDS-A @ _RTERM-I-RECORDS-U @ 0 FILL
    _RTERM-I-BACKEND @ RTERM-UIDL-BACKEND-SIZE 0 FILL
    _RTERM-UIDL-ABI _RTERM-I-BACKEND @ _RTERM-B.ABI !
    RTERM-UIDL-BACKEND-SIZE _RTERM-I-BACKEND @ _RTERM-B.SIZE !
    _RTERM-I-BACKEND @ DUP _RTERM-B.SELF !
    _RTERM-I-HOST @ _RTERM-I-BACKEND @ _RTERM-B.HOST !
    _RTERM-I-RECORDS-A @ _RTERM-I-BACKEND @ _RTERM-B.RECORDS-A !
    _RTERM-I-RECORDS-U @ _RTERM-I-BACKEND @ _RTERM-B.RECORDS-U !
    _RTERM-I-RECORDS-U @ RTERM-UIDL-BINDING-SIZE /
        _RTERM-I-BACKEND @ _RTERM-B.CAPACITY !
    _RTERM-UIDL-MAGIC _RTERM-I-BACKEND @ _RTERM-B.MAGIC !
    RTERM-S-OK ;

: _RTERM-RECORD-AT  ( index backend -- record )
    _RTERM-B.RECORDS-A @ SWAP RTERM-UIDL-BINDING-SIZE * + ;

VARIABLE _RTERM-RV-RECORD
VARIABLE _RTERM-RV-BACKEND

: _RTERM-RECORD-DETACHED?  ( -- flag )
    _RTERM-RV-RECORD @ _RTERM-R.TOKEN @ 0<>
    _RTERM-RV-RECORD @ _RTERM-R.ISSUER @ _RTERM-RV-BACKEND @ = AND
    _RTERM-RV-RECORD @ _RTERM-R.HOST 104 _RTERM-ZERO? AND
    _RTERM-RV-RECORD @ _RTERM-R.LAST-STATUS @
        RTERM-STATUS-VALID? AND
    _RTERM-RV-RECORD @ _RTERM-R.RESERVED @ 0= AND ;

: _RTERM-RECORD-LIVE?  ( -- flag )
    _RTERM-RV-RECORD @ _RTERM-R.TOKEN @ 0<>
    _RTERM-RV-RECORD @ _RTERM-R.ISSUER @ _RTERM-RV-BACKEND @ = AND
    _RTERM-RV-RECORD @ _RTERM-R.HOST @
        _RTERM-RV-BACKEND @ _RTERM-B.HOST @ = AND
    _RTERM-RV-RECORD @ _RTERM-R.HOST @ AHOST-SIZE _RTERM-SPAN? AND
    _RTERM-RV-RECORD @ _RTERM-R.SLOT @ AHS-SIZE _RTERM-SPAN? AND
    _RTERM-RV-RECORD @ _RTERM-R.SLOT-ID @ 0<> AND
    _RTERM-RV-RECORD @ _RTERM-R.INST @ COMP-INST _RTERM-SPAN? AND
    _RTERM-RV-RECORD @ _RTERM-R.INST-ID @ 0<> AND
    _RTERM-RV-RECORD @ _RTERM-R.INST-GEN @ 0<> AND
    _RTERM-RV-RECORD @ _RTERM-R.UCTX @ UCTX-TOTAL _RTERM-SPAN? AND
    _RTERM-RV-RECORD @ _RTERM-R.VISIBLE @ _RTERM-BOOL? AND
    _RTERM-RV-RECORD @ _RTERM-R.LAST-STATUS @
        RTERM-STATUS-VALID? AND
    _RTERM-RV-RECORD @ _RTERM-R.RESERVED @ 0= AND
    0= IF 0 EXIT THEN
    _RTERM-RV-RECORD @ _RTERM-R.VISIBLE @ IF
        _RTERM-RV-RECORD @ _RTERM-R.REGION @ RGN-SIZE
            _RTERM-SPAN? 0= IF 0 EXIT THEN
        _RTERM-RV-RECORD @ _RTERM-R.ROW @
        _RTERM-RV-RECORD @ _RTERM-R.COL @
        _RTERM-RV-RECORD @ _RTERM-R.HEIGHT @
        _RTERM-RV-RECORD @ _RTERM-R.WIDTH @
        _RTERM-GEOMETRY?
    ELSE
        _RTERM-RV-RECORD @ _RTERM-R.REGION 48 _RTERM-ZERO?
    THEN ;

: _RTERM-RECORD-VALID?  ( record backend -- flag )
    _RTERM-RV-BACKEND ! _RTERM-RV-RECORD !
    _RTERM-RV-RECORD @ _RTERM-R.STATE @ DUP
    _RTERM-BINDING-ST-FREE = IF
        DROP _RTERM-RV-RECORD @ RTERM-UIDL-BINDING-SIZE _RTERM-ZERO? EXIT
    THEN
    DUP _RTERM-BINDING-ST-ATTACHED =
    SWAP _RTERM-BINDING-ST-QUIESCED = OR IF
        _RTERM-RECORD-LIVE? EXIT
    THEN
    _RTERM-RV-RECORD @ _RTERM-R.STATE @
        _RTERM-BINDING-ST-DETACHED = IF
        _RTERM-RECORD-DETACHED? EXIT
    THEN
    0 ;

VARIABLE _RTERM-V-BACKEND
VARIABLE _RTERM-V-ACTIVE

: _RTERM-UIDL-VALID-BODY?  ( backend -- flag )
    DUP RTERM-UIDL-BACKEND-SIZE _RTERM-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RTERM-B.MAGIC @ _RTERM-UIDL-MAGIC <> IF DROP 0 EXIT THEN
    DUP _RTERM-B.ABI @ _RTERM-UIDL-ABI <> IF DROP 0 EXIT THEN
    DUP _RTERM-B.SIZE @ RTERM-UIDL-BACKEND-SIZE <> IF DROP 0 EXIT THEN
    DUP _RTERM-B.SELF @ OVER <> IF DROP 0 EXIT THEN
    DUP _RTERM-B.STATUS @ RTERM-STATUS-VALID? 0= IF DROP 0 EXIT THEN
    DUP _RTERM-B.INSTALLED @ _RTERM-BOOL? 0= IF DROP 0 EXIT THEN
    DUP _RTERM-B.RESERVED @ IF DROP 0 EXIT THEN
    DUP _RTERM-V-BACKEND !
    DUP _RTERM-B.HOST @ _RTERM-I-HOST !
    DUP _RTERM-B.RECORDS-A @ _RTERM-I-RECORDS-A !
    DUP _RTERM-B.RECORDS-U @ _RTERM-I-RECORDS-U !
    _RTERM-I-BACKEND !
    _RTERM-UIDL-RANGES? 0= IF 0 EXIT THEN
    _RTERM-I-RECORDS-U @ RTERM-UIDL-BINDING-SIZE /
        _RTERM-V-BACKEND @ _RTERM-B.CAPACITY @ <> IF 0 EXIT THEN
    _RTERM-V-BACKEND @ _RTERM-B.ACTIVE @ DUP 0< IF DROP 0 EXIT THEN
    _RTERM-V-BACKEND @ _RTERM-B.CAPACITY @ > IF 0 EXIT THEN
    0 _RTERM-V-ACTIVE !
    _RTERM-V-BACKEND @ _RTERM-B.CAPACITY @ 0 ?DO
        I _RTERM-V-BACKEND @ _RTERM-RECORD-AT
        DUP _RTERM-V-BACKEND @ _RTERM-RECORD-VALID? 0= IF
            DROP 0 UNLOOP EXIT
        THEN
        _RTERM-R.STATE @ DUP _RTERM-BINDING-ST-ATTACHED =
        SWAP _RTERM-BINDING-ST-QUIESCED = OR IF
            1 _RTERM-V-ACTIVE +!
        THEN
    LOOP
    _RTERM-V-ACTIVE @ _RTERM-V-BACKEND @ _RTERM-B.ACTIVE @ = ;

VARIABLE _RTERM-SD-A
VARIABLE _RTERM-SD-U
VARIABLE _RTERM-SD-B

: _RTERM-UIDL-STORAGE-DISJOINT-BODY?  ( a u backend -- flag )
    _RTERM-SD-B ! _RTERM-SD-U ! _RTERM-SD-A !
    _RTERM-SD-B @ _RTERM-UIDL-VALID-BODY? 0= IF 0 EXIT THEN
    _RTERM-SD-A @ _RTERM-SD-U @ _RTERM-SPAN? 0= IF 0 EXIT THEN
    _RTERM-SD-A @ _RTERM-SD-U @
        _RTERM-SD-B @ RTERM-UIDL-BACKEND-SIZE
        _RTERM-DISJOINT? 0= IF 0 EXIT THEN
    _RTERM-SD-A @ _RTERM-SD-U @
        _RTERM-SD-B @ _RTERM-B.HOST @ AHOST-SIZE
        _RTERM-DISJOINT? 0= IF 0 EXIT THEN
    _RTERM-SD-A @ _RTERM-SD-U @
        _RTERM-SD-B @ _RTERM-B.RECORDS-A @
        _RTERM-SD-B @ _RTERM-B.RECORDS-U @ _RTERM-DISJOINT? ;

: _RTERM-NOTE  ( status backend -- status )
    OVER DUP RTERM-S-CAPACITY =
    OVER RTERM-S-INVALID = OR
    OVER RTERM-S-SESSION-LOST = OR
    SWAP RTERM-S-SOURCE = OR IF
        DUP _RTERM-B.STATUS @ RTERM-S-OK = IF
            OVER OVER _RTERM-B.STATUS !
        THEN
    THEN
    DROP ;

: _RTERM-UIDL-STATUS-BODY@  ( backend -- status )
    DUP _RTERM-UIDL-VALID-BODY? 0= IF DROP RTERM-S-INVALID EXIT THEN
    _RTERM-B.STATUS @ ;

: _RTERM-UIDL-ACTIVE-BODY@  ( backend -- count status )
    DUP _RTERM-UIDL-VALID-BODY? 0= IF DROP 0 RTERM-S-INVALID EXIT THEN
    _RTERM-B.ACTIVE @ RTERM-S-OK ;

\ =====================================================================
\  Exact host membership and live authority
\ =====================================================================

: _RTERM-SLOT-NEXT?  ( slot -- next flag )
    DUP 0= IF DROP 0 -1 EXIT THEN
    DUP AHS-SIZE _RTERM-SPAN? 0= IF DROP 0 0 EXIT THEN
    AHS.NEXT @ DUP 0= IF -1 EXIT THEN
    DUP AHS-SIZE _RTERM-SPAN? ;

VARIABLE _RTERM-LIST-SLOW
VARIABLE _RTERM-LIST-FAST

: _RTERM-HOST-LIST-ACYCLIC?  ( host -- flag )
    DUP AHOST-SIZE _RTERM-SPAN? 0= IF DROP 0 EXIT THEN
    AHOST.HEAD @ DUP _RTERM-LIST-SLOW ! _RTERM-LIST-FAST !
    BEGIN
        _RTERM-LIST-FAST @ 0= IF -1 EXIT THEN
        _RTERM-LIST-FAST @ _RTERM-SLOT-NEXT? 0= IF DROP 0 EXIT THEN
        _RTERM-LIST-FAST !
        _RTERM-LIST-FAST @ 0= IF -1 EXIT THEN
        _RTERM-LIST-FAST @ _RTERM-SLOT-NEXT? 0= IF DROP 0 EXIT THEN
        _RTERM-LIST-FAST !
        _RTERM-LIST-FAST @ 0= IF -1 EXIT THEN
        _RTERM-LIST-SLOW @ _RTERM-SLOT-NEXT? 0= IF DROP 0 EXIT THEN
        _RTERM-LIST-SLOW !
        _RTERM-LIST-SLOW @ _RTERM-LIST-FAST @ = IF 0 EXIT THEN
    AGAIN ;

VARIABLE _RTERM-HX-HOST
VARIABLE _RTERM-HX-SLOT
VARIABLE _RTERM-HX-ID
VARIABLE _RTERM-HX-MATCHES

: _RTERM-HOST-EXACT-SLOT?  ( host slot slot-id -- flag )
    _RTERM-HX-ID ! _RTERM-HX-SLOT ! _RTERM-HX-HOST !
    _RTERM-HX-ID @ 0= IF 0 EXIT THEN
    _RTERM-HX-SLOT @ AHS-SIZE _RTERM-SPAN? 0= IF 0 EXIT THEN
    _RTERM-HX-HOST @ _RTERM-HOST-LIST-ACYCLIC? 0= IF 0 EXIT THEN
    0 _RTERM-HX-MATCHES !
    _RTERM-HX-HOST @ AHOST.HEAD @
    BEGIN ?DUP WHILE
        DUP _RTERM-HX-SLOT @ =
        OVER AHS.ID @ _RTERM-HX-ID @ = OR IF
            DUP _RTERM-HX-SLOT @ =
            OVER AHS.ID @ _RTERM-HX-ID @ = AND 0= IF
                DROP 0 EXIT
            THEN
            1 _RTERM-HX-MATCHES +!
        THEN
        AHS.NEXT @
    REPEAT
    _RTERM-HX-MATCHES @ 1 = ;

VARIABLE _RTERM-L-HOST
VARIABLE _RTERM-L-SLOT
VARIABLE _RTERM-L-SLOT-ID
VARIABLE _RTERM-L-INST
VARIABLE _RTERM-L-INST-ID
VARIABLE _RTERM-L-INST-GEN
VARIABLE _RTERM-L-UCTX
VARIABLE _RTERM-L-REGION
VARIABLE _RTERM-L-APP-DESC
VARIABLE _RTERM-L-APP-SIZE
VARIABLE _RTERM-L-COMP-DESC
VARIABLE _RTERM-L-COMP-SIZE
VARIABLE _RTERM-L-STATE
VARIABLE _RTERM-L-STATE-SIZE

: _RTERM-LIVE-LOAD-HB  ( hb -- )
    DUP _RTERM-HB.HOST @ _RTERM-L-HOST !
    DUP _RTERM-HB.SLOT @ _RTERM-L-SLOT !
    DUP _RTERM-HB.SLOT-ID @ _RTERM-L-SLOT-ID !
    DUP _RTERM-HB.INST @ _RTERM-L-INST !
    DUP _RTERM-HB.INST-ID @ _RTERM-L-INST-ID !
    DUP _RTERM-HB.INST-GEN @ _RTERM-L-INST-GEN !
    DUP _RTERM-HB.UCTX @ _RTERM-L-UCTX !
    _RTERM-HB.REGION @ _RTERM-L-REGION ! ;

: _RTERM-LIVE-LOAD-RECORD  ( record -- )
    DUP _RTERM-R.HOST @ _RTERM-L-HOST !
    DUP _RTERM-R.SLOT @ _RTERM-L-SLOT !
    DUP _RTERM-R.SLOT-ID @ _RTERM-L-SLOT-ID !
    DUP _RTERM-R.INST @ _RTERM-L-INST !
    DUP _RTERM-R.INST-ID @ _RTERM-L-INST-ID !
    DUP _RTERM-R.INST-GEN @ _RTERM-L-INST-GEN !
    DUP _RTERM-R.UCTX @ _RTERM-L-UCTX !
    _RTERM-R.REGION @ _RTERM-L-REGION ! ;

: _RTERM-LIVE-BASE-RANGES?  ( -- flag )
    _RTERM-L-HOST @ AHOST-SIZE _RTERM-SPAN?
    _RTERM-L-SLOT @ AHS-SIZE _RTERM-SPAN? AND
    _RTERM-L-SLOT-ID @ 0<> AND
    _RTERM-L-INST @ COMP-INST _RTERM-SPAN? AND
    _RTERM-L-INST-ID @ 0<> AND
    _RTERM-L-INST-GEN @ 0<> AND
    _RTERM-L-UCTX @ UCTX-TOTAL _RTERM-SPAN? AND ;

: _RTERM-LIVE-IDENTITY?  ( -- flag )
    _RTERM-LIVE-BASE-RANGES? 0= IF 0 EXIT THEN
    _RTERM-L-HOST @ _RTERM-L-SLOT @ _RTERM-L-SLOT-ID @
        _RTERM-HOST-EXACT-SLOT? 0= IF 0 EXIT THEN
    _RTERM-L-SLOT @ AHS.STATE @ DUP AHS-S-RUNNING =
    OVER AHS-S-MINIMIZED = OR
    SWAP AHS-S-FOCUSED = OR 0= IF 0 EXIT THEN
    _RTERM-L-SLOT @ AHS.HAS-UIDL @ -1 <> IF 0 EXIT THEN
    _RTERM-L-SLOT @ AHS.ID @ _RTERM-L-SLOT-ID @ <> IF 0 EXIT THEN
    _RTERM-L-SLOT @ AHS.INST @ _RTERM-L-INST @ <> IF 0 EXIT THEN
    _RTERM-L-SLOT @ AHS.UCTX @ _RTERM-L-UCTX @ <> IF 0 EXIT THEN
    _RTERM-L-SLOT @ AHS.DESC @ DUP APP-DESC _RTERM-SPAN? 0= IF
        DROP 0 EXIT
    THEN
    DUP _RTERM-L-APP-DESC ! APP.COMP-DESC @
    DUP COMP-DESC _RTERM-SPAN? 0= IF DROP 0 EXIT THEN
    _RTERM-L-COMP-DESC !
    _RTERM-L-APP-DESC @ APP-DESC-VALID? 0= IF 0 EXIT THEN
    _RTERM-L-INST @ CINST.DESC @ _RTERM-L-COMP-DESC @ <> IF 0 EXIT THEN
    _RTERM-L-INST @ CINST.ID @ _RTERM-L-INST-ID @ <> IF 0 EXIT THEN
    _RTERM-L-INST @ CINST.GENERATION @
        _RTERM-L-INST-GEN @ <> IF 0 EXIT THEN
    _RTERM-L-APP-DESC @ APP.SIZE @ DUP _RTERM-L-APP-SIZE !
    DUP APP-DESC < IF DROP 0 EXIT THEN
    _RTERM-L-APP-DESC @ SWAP _RTERM-SPAN? 0= IF 0 EXIT THEN
    _RTERM-L-COMP-DESC @ COMP.SIZE @ DUP _RTERM-L-COMP-SIZE !
    DUP COMP-DESC < IF DROP 0 EXIT THEN
    _RTERM-L-COMP-DESC @ SWAP _RTERM-SPAN? 0= IF 0 EXIT THEN
    _RTERM-L-COMP-DESC @ COMP.STATE-SIZE @
        DUP _RTERM-L-STATE-SIZE !
    DUP 0< IF DROP 0 EXIT THEN
    _RTERM-L-INST @ CINST.STATE @ _RTERM-L-STATE !
    0= IF _RTERM-L-STATE @ 0= EXIT THEN
    _RTERM-L-STATE @ _RTERM-L-STATE-SIZE @ _RTERM-SPAN? ;

: _RTERM-LIVE-ACTIVE?  ( -- flag )
    ASHELL-ACTIVE-CTX _RTERM-L-UCTX @ = ;

: _RTERM-LIVE-CORE-DISJOINT?  ( -- flag )
    _RTERM-L-HOST @ AHOST-SIZE _RTERM-L-SLOT @ AHS-SIZE _RTERM-DISJOINT?
    _RTERM-L-HOST @ AHOST-SIZE _RTERM-L-INST @ COMP-INST
        _RTERM-DISJOINT? AND
    _RTERM-L-HOST @ AHOST-SIZE _RTERM-L-UCTX @ UCTX-TOTAL
        _RTERM-DISJOINT? AND
    _RTERM-L-SLOT @ AHS-SIZE _RTERM-L-INST @ COMP-INST
        _RTERM-DISJOINT? AND
    _RTERM-L-SLOT @ AHS-SIZE _RTERM-L-UCTX @ UCTX-TOTAL
        _RTERM-DISJOINT? AND
    _RTERM-L-INST @ COMP-INST _RTERM-L-UCTX @ UCTX-TOTAL
        _RTERM-DISJOINT? AND
    _RTERM-L-APP-DESC @ _RTERM-L-APP-SIZE @
        _RTERM-L-HOST @ AHOST-SIZE
        _RTERM-DISJOINT? AND
    _RTERM-L-APP-DESC @ _RTERM-L-APP-SIZE @
        _RTERM-L-SLOT @ AHS-SIZE
        _RTERM-DISJOINT? AND
    _RTERM-L-APP-DESC @ _RTERM-L-APP-SIZE @
        _RTERM-L-INST @ COMP-INST
        _RTERM-DISJOINT? AND
    _RTERM-L-APP-DESC @ _RTERM-L-APP-SIZE @
        _RTERM-L-UCTX @ UCTX-TOTAL
        _RTERM-DISJOINT? AND
    _RTERM-L-COMP-DESC @ _RTERM-L-COMP-SIZE @
        _RTERM-L-HOST @ AHOST-SIZE
        _RTERM-DISJOINT? AND
    _RTERM-L-COMP-DESC @ _RTERM-L-COMP-SIZE @
        _RTERM-L-SLOT @ AHS-SIZE
        _RTERM-DISJOINT? AND
    _RTERM-L-COMP-DESC @ _RTERM-L-COMP-SIZE @
        _RTERM-L-INST @ COMP-INST
        _RTERM-DISJOINT? AND
    _RTERM-L-COMP-DESC @ _RTERM-L-COMP-SIZE @
        _RTERM-L-UCTX @ UCTX-TOTAL
        _RTERM-DISJOINT? AND
    _RTERM-L-APP-DESC @ _RTERM-L-APP-SIZE @
        _RTERM-L-COMP-DESC @ _RTERM-L-COMP-SIZE @
        _RTERM-DISJOINT? AND
    _RTERM-L-STATE @ _RTERM-L-STATE-SIZE @
        _RTERM-L-HOST @ AHOST-SIZE _RTERM-DISJOINT? AND
    _RTERM-L-STATE @ _RTERM-L-STATE-SIZE @
        _RTERM-L-SLOT @ AHS-SIZE _RTERM-DISJOINT? AND
    _RTERM-L-STATE @ _RTERM-L-STATE-SIZE @
        _RTERM-L-INST @ COMP-INST _RTERM-DISJOINT? AND
    _RTERM-L-STATE @ _RTERM-L-STATE-SIZE @
        _RTERM-L-UCTX @ UCTX-TOTAL _RTERM-DISJOINT? AND
    _RTERM-L-STATE @ _RTERM-L-STATE-SIZE @
        _RTERM-L-APP-DESC @ _RTERM-L-APP-SIZE @ _RTERM-DISJOINT? AND
    _RTERM-L-STATE @ _RTERM-L-STATE-SIZE @
        _RTERM-L-COMP-DESC @ _RTERM-L-COMP-SIZE @ _RTERM-DISJOINT? ;

: _RTERM-LIVE-OBJECTS-DISJOINT?  ( -- flag )
    _RTERM-LIVE-CORE-DISJOINT? 0= IF 0 EXIT THEN
    _RTERM-L-REGION @ RGN-SIZE _RTERM-SPAN? 0= IF 0 EXIT THEN
    _RTERM-L-REGION @ RGN-SIZE _RTERM-L-HOST @ AHOST-SIZE
        _RTERM-DISJOINT?
    _RTERM-L-REGION @ RGN-SIZE _RTERM-L-SLOT @ AHS-SIZE
        _RTERM-DISJOINT? AND
    _RTERM-L-REGION @ RGN-SIZE _RTERM-L-INST @ COMP-INST
        _RTERM-DISJOINT? AND
    _RTERM-L-REGION @ RGN-SIZE _RTERM-L-UCTX @ UCTX-TOTAL
        _RTERM-DISJOINT? AND
    _RTERM-L-REGION @ RGN-SIZE
        _RTERM-L-APP-DESC @ _RTERM-L-APP-SIZE @
        _RTERM-DISJOINT? AND
    _RTERM-L-REGION @ RGN-SIZE
        _RTERM-L-COMP-DESC @ _RTERM-L-COMP-SIZE @
        _RTERM-DISJOINT? AND
    _RTERM-L-REGION @ RGN-SIZE
        _RTERM-L-STATE @ _RTERM-L-STATE-SIZE @ _RTERM-DISJOINT? ;

: _RTERM-LIVE-ATTACH?  ( -- flag )
    _RTERM-LIVE-IDENTITY? 0= IF 0 EXIT THEN
    _RTERM-LIVE-ACTIVE? 0= IF 0 EXIT THEN
    _RTERM-L-SLOT @ AHS-VISIBLE? 0= IF 0 EXIT THEN
    _RTERM-L-SLOT @ AHS.RGN @ _RTERM-L-REGION @ <> IF 0 EXIT THEN
    _RTERM-L-REGION @ _RTERM-REGION-SANE? ;

: _RTERM-HB-DISJOINT-LIVE?  ( hb -- flag )
    DUP RTERM-HOST-BINDING-SIZE _RTERM-L-HOST @ AHOST-SIZE
        _RTERM-DISJOINT?
    OVER RTERM-HOST-BINDING-SIZE _RTERM-L-SLOT @ AHS-SIZE
        _RTERM-DISJOINT? AND
    OVER RTERM-HOST-BINDING-SIZE _RTERM-L-INST @ COMP-INST
        _RTERM-DISJOINT? AND
    OVER RTERM-HOST-BINDING-SIZE _RTERM-L-UCTX @ UCTX-TOTAL
        _RTERM-DISJOINT? AND
    OVER RTERM-HOST-BINDING-SIZE _RTERM-L-REGION @ RGN-SIZE
        _RTERM-DISJOINT? AND
    OVER RTERM-HOST-BINDING-SIZE
        _RTERM-L-APP-DESC @ _RTERM-L-APP-SIZE @
        _RTERM-DISJOINT? AND
    OVER RTERM-HOST-BINDING-SIZE
        _RTERM-L-COMP-DESC @ _RTERM-L-COMP-SIZE @
        _RTERM-DISJOINT? AND
    SWAP RTERM-HOST-BINDING-SIZE
        _RTERM-L-STATE @ _RTERM-L-STATE-SIZE @
        _RTERM-DISJOINT? AND ;

VARIABLE _RTERM-DB-BACKEND

: _RTERM-LIVE-DISJOINT-BACKEND-CORE?  ( backend -- flag )
    _RTERM-DB-BACKEND !
    _RTERM-L-SLOT @ AHS-SIZE _RTERM-DB-BACKEND @
        _RTERM-UIDL-STORAGE-DISJOINT-BODY?
    _RTERM-L-INST @ COMP-INST _RTERM-DB-BACKEND @
        _RTERM-UIDL-STORAGE-DISJOINT-BODY? AND
    _RTERM-L-UCTX @ UCTX-TOTAL _RTERM-DB-BACKEND @
        _RTERM-UIDL-STORAGE-DISJOINT-BODY? AND
    _RTERM-L-APP-DESC @ _RTERM-L-APP-SIZE @ _RTERM-DB-BACKEND @
        _RTERM-UIDL-STORAGE-DISJOINT-BODY? AND
    _RTERM-L-COMP-DESC @ _RTERM-L-COMP-SIZE @ _RTERM-DB-BACKEND @
        _RTERM-UIDL-STORAGE-DISJOINT-BODY? AND
    _RTERM-L-STATE-SIZE @ IF
        _RTERM-L-STATE @ _RTERM-L-STATE-SIZE @ _RTERM-DB-BACKEND @
        _RTERM-UIDL-STORAGE-DISJOINT-BODY? AND
    THEN ;

: _RTERM-LIVE-DISJOINT-BACKEND?  ( backend -- flag )
    DUP _RTERM-LIVE-DISJOINT-BACKEND-CORE? 0= IF DROP 0 EXIT THEN
    _RTERM-DB-BACKEND !
    _RTERM-L-REGION @ RGN-SIZE _RTERM-DB-BACKEND @
    _RTERM-UIDL-STORAGE-DISJOINT-BODY? ;

\ =====================================================================
\  Host-binding construction
\ =====================================================================

: RTERM-HOST-BINDING-INIT  ( host-binding -- )
    DUP RTERM-HOST-BINDING-SIZE 0 FILL
    _RTERM-HB-ABI OVER _RTERM-HB.ABI !
    RTERM-HOST-BINDING-SIZE OVER _RTERM-HB.SIZE !
    _RTERM-HB-MAGIC SWAP _RTERM-HB.MAGIC ! ;

: _RTERM-HOST-BINDING-HEADER?  ( hb -- flag )
    DUP RTERM-HOST-BINDING-SIZE _RTERM-SPAN? 0= IF DROP 0 EXIT THEN
    DUP _RTERM-HB.MAGIC @ _RTERM-HB-MAGIC =
    OVER _RTERM-HB.ABI @ _RTERM-HB-ABI = AND
    OVER _RTERM-HB.SIZE @ RTERM-HOST-BINDING-SIZE = AND
    OVER _RTERM-HB.HOST @ 0<> AND
    OVER _RTERM-HB.SLOT @ 0<> AND
    OVER _RTERM-HB.SLOT-ID @ 0<> AND
    OVER _RTERM-HB.INST @ 0<> AND
    OVER _RTERM-HB.INST-ID @ 0<> AND
    OVER _RTERM-HB.INST-GEN @ 0<> AND
    OVER _RTERM-HB.UCTX @ 0<> AND
    OVER _RTERM-HB.REGION @ 0<> AND
    SWAP _RTERM-HB.RESERVED @ 0= AND ;

: _RTERM-HOST-BINDING-VALID-BODY?  ( hb -- flag )
    DUP _RTERM-HOST-BINDING-HEADER? 0= IF DROP 0 EXIT THEN
    DUP _RTERM-LIVE-LOAD-HB
    _RTERM-LIVE-ATTACH? 0= IF DROP 0 EXIT THEN
    _RTERM-LIVE-OBJECTS-DISJOINT? 0= IF DROP 0 EXIT THEN
    _RTERM-HB-DISJOINT-LIVE? ;

VARIABLE _RTERM-HC-HOST
VARIABLE _RTERM-HC-SLOT
VARIABLE _RTERM-HC-BINDING

: _RTERM-HOST-BINDING-CAPTURE-BODY  ( host slot binding -- status )
    _RTERM-HC-BINDING ! _RTERM-HC-SLOT ! _RTERM-HC-HOST !
    _RTERM-HC-HOST @ AHOST-SIZE _RTERM-SPAN? 0= IF
        RTERM-S-INVALID EXIT
    THEN
    _RTERM-HC-SLOT @ AHS-SIZE _RTERM-SPAN? 0= IF
        RTERM-S-INVALID EXIT
    THEN
    _RTERM-HC-BINDING @ RTERM-HOST-BINDING-SIZE
        _RTERM-SPAN? 0= IF RTERM-S-INVALID EXIT THEN
    _RTERM-HC-HOST @ AHOST-SIZE _RTERM-HC-SLOT @ AHS-SIZE
        _RTERM-DISJOINT? 0= IF RTERM-S-INVALID EXIT THEN
    _RTERM-HC-BINDING @ RTERM-HOST-BINDING-SIZE
        _RTERM-HC-HOST @ AHOST-SIZE _RTERM-DISJOINT? 0= IF
        RTERM-S-INVALID EXIT
    THEN
    _RTERM-HC-BINDING @ RTERM-HOST-BINDING-SIZE
        _RTERM-HC-SLOT @ AHS-SIZE _RTERM-DISJOINT? 0= IF
        RTERM-S-INVALID EXIT
    THEN
    _RTERM-HC-SLOT @ AHS.ID @ DUP 0= IF DROP RTERM-S-INVALID EXIT THEN
    DUP _RTERM-L-SLOT-ID !
    _RTERM-HC-HOST @ _RTERM-HC-SLOT @ ROT
        _RTERM-HOST-EXACT-SLOT? 0= IF RTERM-S-INVALID EXIT THEN
    _RTERM-HC-HOST @ _RTERM-L-HOST !
    _RTERM-HC-SLOT @ DUP _RTERM-L-SLOT !
    DUP AHS.INST @ _RTERM-L-INST !
    DUP AHS.UCTX @ _RTERM-L-UCTX !
    AHS.RGN @ _RTERM-L-REGION !
    _RTERM-L-INST @ COMP-INST _RTERM-SPAN? 0= IF
        RTERM-S-INVALID EXIT
    THEN
    _RTERM-L-INST @ CINST.ID @ _RTERM-L-INST-ID !
    _RTERM-L-INST @ CINST.GENERATION @ _RTERM-L-INST-GEN !
    _RTERM-LIVE-ATTACH? 0= IF RTERM-S-INVALID EXIT THEN
    _RTERM-LIVE-OBJECTS-DISJOINT? 0= IF RTERM-S-INVALID EXIT THEN
    _RTERM-HC-BINDING @ _RTERM-HB-DISJOINT-LIVE? 0= IF
        RTERM-S-INVALID EXIT
    THEN
    _RTERM-HC-BINDING @ RTERM-HOST-BINDING-SIZE 0 FILL
    _RTERM-HB-ABI _RTERM-HC-BINDING @ _RTERM-HB.ABI !
    RTERM-HOST-BINDING-SIZE _RTERM-HC-BINDING @ _RTERM-HB.SIZE !
    _RTERM-L-HOST @ _RTERM-HC-BINDING @ _RTERM-HB.HOST !
    _RTERM-L-SLOT @ _RTERM-HC-BINDING @ _RTERM-HB.SLOT !
    _RTERM-L-SLOT-ID @ _RTERM-HC-BINDING @ _RTERM-HB.SLOT-ID !
    _RTERM-L-INST @ _RTERM-HC-BINDING @ _RTERM-HB.INST !
    _RTERM-L-INST-ID @ _RTERM-HC-BINDING @ _RTERM-HB.INST-ID !
    _RTERM-L-INST-GEN @ _RTERM-HC-BINDING @ _RTERM-HB.INST-GEN !
    _RTERM-L-UCTX @ _RTERM-HC-BINDING @ _RTERM-HB.UCTX !
    _RTERM-L-REGION @ _RTERM-HC-BINDING @ _RTERM-HB.REGION !
    _RTERM-HB-MAGIC _RTERM-HC-BINDING @ _RTERM-HB.MAGIC !
    RTERM-S-OK ;

\ =====================================================================
\  Opaque tokens and bounded lookup
\ =====================================================================

VARIABLE _RTERM-NEXT-TOKEN
1 _RTERM-NEXT-TOKEN !

: _RTERM-TAKE-TOKEN  ( -- token|0 )
    _RTERM-NEXT-TOKEN @ DUP 0= IF EXIT THEN
    DUP 1+ _RTERM-NEXT-TOKEN ! ;

VARIABLE _RTERM-LK-TOKEN
VARIABLE _RTERM-LK-BACKEND
VARIABLE _RTERM-LK-RECORD
VARIABLE _RTERM-LK-MATCHES

: _RTERM-LOOKUP  ( token backend -- record status )
    _RTERM-LK-BACKEND ! _RTERM-LK-TOKEN !
    _RTERM-LK-BACKEND @ _RTERM-UIDL-VALID-BODY? 0= IF
        0 RTERM-S-INVALID EXIT
    THEN
    _RTERM-LK-TOKEN @ 0= IF 0 RTERM-S-INVALID EXIT THEN
    0 _RTERM-LK-RECORD ! 0 _RTERM-LK-MATCHES !
    _RTERM-LK-BACKEND @ _RTERM-B.CAPACITY @ 0 ?DO
        I _RTERM-LK-BACKEND @ _RTERM-RECORD-AT
        DUP _RTERM-R.TOKEN @ _RTERM-LK-TOKEN @ = IF
            DUP _RTERM-R.ISSUER @ _RTERM-LK-BACKEND @ <> IF
                DROP 0 RTERM-S-INVALID UNLOOP EXIT
            THEN
            DUP _RTERM-LK-RECORD !
            1 _RTERM-LK-MATCHES +!
        THEN
        DROP
    LOOP
    _RTERM-LK-MATCHES @ 0= IF 0 RTERM-S-STALE EXIT THEN
    _RTERM-LK-MATCHES @ 1 <> IF 0 RTERM-S-INVALID EXIT THEN
    _RTERM-LK-RECORD @ RTERM-S-OK ;

\ =====================================================================
\  Attach admission
\ =====================================================================

VARIABLE _RTERM-A-HB
VARIABLE _RTERM-A-BACKEND
VARIABLE _RTERM-A-EXACT
VARIABLE _RTERM-A-FREE
VARIABLE _RTERM-A-DETACHED
VARIABLE _RTERM-A-COLLISION
VARIABLE _RTERM-A-TOKEN
VARIABLE _RTERM-A-COMPARE-HB

: _RTERM-RECORD=HB?  ( record hb -- flag )
    _RTERM-A-COMPARE-HB !
    DUP _RTERM-R.HOST @ _RTERM-A-COMPARE-HB @ _RTERM-HB.HOST @ =
    OVER _RTERM-R.SLOT @ _RTERM-A-COMPARE-HB @ _RTERM-HB.SLOT @ = AND
    OVER _RTERM-R.SLOT-ID @
        _RTERM-A-COMPARE-HB @ _RTERM-HB.SLOT-ID @ = AND
    OVER _RTERM-R.INST @ _RTERM-A-COMPARE-HB @ _RTERM-HB.INST @ = AND
    OVER _RTERM-R.INST-ID @
        _RTERM-A-COMPARE-HB @ _RTERM-HB.INST-ID @ = AND
    OVER _RTERM-R.INST-GEN @
        _RTERM-A-COMPARE-HB @ _RTERM-HB.INST-GEN @ = AND
    OVER _RTERM-R.UCTX @ _RTERM-A-COMPARE-HB @ _RTERM-HB.UCTX @ = AND
    SWAP _RTERM-R.REGION @
        _RTERM-A-COMPARE-HB @ _RTERM-HB.REGION @ = AND ;

: _RTERM-RECORD-COLLIDES-HB?  ( record hb -- flag )
    _RTERM-A-COMPARE-HB !
    DUP _RTERM-R.HOST @ _RTERM-A-COMPARE-HB @ _RTERM-HB.HOST @ = IF
        DUP _RTERM-R.SLOT @ _RTERM-A-COMPARE-HB @ _RTERM-HB.SLOT @ =
        OVER _RTERM-R.SLOT-ID @
            _RTERM-A-COMPARE-HB @ _RTERM-HB.SLOT-ID @ = OR IF
            DROP -1 EXIT
        THEN
    THEN
    DUP _RTERM-R.INST @ _RTERM-A-COMPARE-HB @ _RTERM-HB.INST @ =
    OVER _RTERM-R.INST-ID @
        _RTERM-A-COMPARE-HB @ _RTERM-HB.INST-ID @ = OR
    OVER _RTERM-R.UCTX @ _RTERM-A-COMPARE-HB @ _RTERM-HB.UCTX @ = OR
    NIP ;

: _RTERM-ATTACH-SCAN  ( -- )
    0 _RTERM-A-EXACT ! 0 _RTERM-A-FREE !
    0 _RTERM-A-DETACHED ! 0 _RTERM-A-COLLISION !
    _RTERM-A-BACKEND @ _RTERM-B.CAPACITY @ 0 ?DO
        I _RTERM-A-BACKEND @ _RTERM-RECORD-AT
        DUP _RTERM-R.STATE @ _RTERM-BINDING-ST-FREE = IF
            _RTERM-A-FREE @ 0= IF DUP _RTERM-A-FREE ! THEN
        ELSE
            DUP _RTERM-R.STATE @ _RTERM-BINDING-ST-DETACHED = IF
                _RTERM-A-DETACHED @ 0= IF DUP _RTERM-A-DETACHED ! THEN
            ELSE
                DUP _RTERM-A-HB @ _RTERM-RECORD=HB? IF
                    _RTERM-A-EXACT @ IF
                        -1 _RTERM-A-COLLISION !
                    ELSE
                        DUP _RTERM-A-EXACT !
                    THEN
                ELSE
                    DUP _RTERM-A-HB @ _RTERM-RECORD-COLLIDES-HB? IF
                        -1 _RTERM-A-COLLISION !
                    THEN
                THEN
            THEN
        THEN
        DROP
    LOOP ;

: _RTERM-ATTACH-FAIL  ( status -- token status )
    _RTERM-A-BACKEND @ _RTERM-NOTE 0 SWAP ;

: _RTERM-ATTACH-POPULATE  ( record -- token status )
    DUP RTERM-UIDL-BINDING-SIZE 0 FILL
    _RTERM-A-TOKEN @ OVER _RTERM-R.TOKEN !
    _RTERM-A-BACKEND @ OVER _RTERM-R.ISSUER !
    _RTERM-A-HB @ _RTERM-HB.HOST @ OVER _RTERM-R.HOST !
    _RTERM-A-HB @ _RTERM-HB.SLOT @ OVER _RTERM-R.SLOT !
    _RTERM-A-HB @ _RTERM-HB.SLOT-ID @ OVER _RTERM-R.SLOT-ID !
    _RTERM-A-HB @ _RTERM-HB.INST @ OVER _RTERM-R.INST !
    _RTERM-A-HB @ _RTERM-HB.INST-ID @ OVER _RTERM-R.INST-ID !
    _RTERM-A-HB @ _RTERM-HB.INST-GEN @ OVER _RTERM-R.INST-GEN !
    _RTERM-A-HB @ _RTERM-HB.UCTX @ OVER _RTERM-R.UCTX !
    _RTERM-A-HB @ _RTERM-HB.REGION @ DUP _RTERM-REGION>GEOMETRY
    OVER _RTERM-R.REGION !
    -1 OVER _RTERM-R.VISIBLE !
    _RTERM-G-ROW @ OVER _RTERM-R.ROW !
    _RTERM-G-COL @ OVER _RTERM-R.COL !
    _RTERM-G-HEIGHT @ OVER _RTERM-R.HEIGHT !
    _RTERM-G-WIDTH @ OVER _RTERM-R.WIDTH !
    RTERM-S-OK OVER _RTERM-R.LAST-STATUS !
    _RTERM-BINDING-ST-ATTACHED SWAP _RTERM-R.STATE !
    1 _RTERM-A-BACKEND @ _RTERM-B.ACTIVE +!
    _RTERM-A-TOKEN @ RTERM-S-OK ;

: _RTERM-UCTX-ATTACH-BODY  ( host-binding backend -- binding-token status )
    _RTERM-A-BACKEND ! _RTERM-A-HB !
    _RTERM-A-BACKEND @ _RTERM-UIDL-VALID-BODY? 0= IF
        0 RTERM-S-INVALID EXIT
    THEN
    _RTERM-A-HB @ _RTERM-HOST-BINDING-VALID-BODY? 0= IF
        RTERM-S-INVALID _RTERM-ATTACH-FAIL EXIT
    THEN
    _RTERM-A-HB @ _RTERM-HB.HOST @
        _RTERM-A-BACKEND @ _RTERM-B.HOST @ <> IF
        RTERM-S-INVALID _RTERM-ATTACH-FAIL EXIT
    THEN
    _RTERM-A-HB @ RTERM-HOST-BINDING-SIZE _RTERM-A-BACKEND @
        _RTERM-UIDL-STORAGE-DISJOINT-BODY? 0= IF
        RTERM-S-INVALID _RTERM-ATTACH-FAIL EXIT
    THEN
    _RTERM-A-HB @ _RTERM-LIVE-LOAD-HB
    _RTERM-A-BACKEND @ _RTERM-LIVE-DISJOINT-BACKEND? 0= IF
        RTERM-S-INVALID _RTERM-ATTACH-FAIL EXIT
    THEN
    _RTERM-ATTACH-SCAN
    _RTERM-A-COLLISION @ IF RTERM-S-STALE _RTERM-ATTACH-FAIL EXIT THEN
    _RTERM-A-EXACT @ ?DUP IF
        DUP _RTERM-R.STATE @ _RTERM-BINDING-ST-ATTACHED <> IF
            DROP RTERM-S-STALE _RTERM-ATTACH-FAIL EXIT
        THEN
        _RTERM-R.TOKEN @ RTERM-S-OK EXIT
    THEN
    _RTERM-A-FREE @ ?DUP 0= IF _RTERM-A-DETACHED @ THEN
    DUP 0= IF DROP RTERM-S-CAPACITY _RTERM-ATTACH-FAIL EXIT THEN
    _RTERM-TAKE-TOKEN DUP 0= IF
        DROP DROP RTERM-S-CAPACITY _RTERM-ATTACH-FAIL EXIT
    THEN
    _RTERM-A-TOKEN !
    _RTERM-ATTACH-POPULATE ;

\ =====================================================================
\  Projection, geometry, and teardown lifecycle
\ =====================================================================

VARIABLE _RTERM-C-RECORD
VARIABLE _RTERM-C-STATUS
VARIABLE _RTERM-C-BACKEND

: _RTERM-CALL-LOOKUP  ( token backend -- flag )
    DUP _RTERM-C-BACKEND ! _RTERM-LOOKUP
    _RTERM-C-STATUS ! _RTERM-C-RECORD !
    _RTERM-C-STATUS @ RTERM-S-OK = ;

: _RTERM-CALL-FAIL  ( status -- status )
    _RTERM-C-BACKEND @ _RTERM-UIDL-VALID-BODY? 0= IF
        DROP RTERM-S-INVALID EXIT
    THEN
    _RTERM-C-BACKEND @ _RTERM-NOTE ;

: _RTERM-CALL-LIVE?  ( -- flag )
    _RTERM-C-RECORD @ _RTERM-LIVE-LOAD-RECORD
    _RTERM-LIVE-IDENTITY? 0= IF 0 EXIT THEN
    _RTERM-LIVE-ACTIVE? 0= IF 0 EXIT THEN
    _RTERM-LIVE-CORE-DISJOINT? 0= IF 0 EXIT THEN
    _RTERM-C-BACKEND @ _RTERM-LIVE-DISJOINT-BACKEND-CORE? ;

: _RTERM-UCTX-PROJECT-BODY  ( binding-token backend -- status )
    2DUP _RTERM-CALL-LOOKUP 0= IF
        2DROP _RTERM-C-STATUS @ _RTERM-CALL-FAIL EXIT
    THEN
    2DROP
    _RTERM-C-RECORD @ _RTERM-R.STATE @
        _RTERM-BINDING-ST-ATTACHED <> IF
        RTERM-S-STALE _RTERM-CALL-FAIL EXIT
    THEN
    _RTERM-CALL-LIVE? 0= IF RTERM-S-STALE _RTERM-CALL-FAIL EXIT THEN
    RTERM-S-UNAVAILABLE _RTERM-C-RECORD @ _RTERM-R.LAST-STATUS !
    RTERM-S-UNAVAILABLE ;

VARIABLE _RTERM-RL-VISIBLE
VARIABLE _RTERM-RL-REGION
VARIABLE _RTERM-RL-TOKEN
VARIABLE _RTERM-RL-BACKEND

: _RTERM-RELAYOUT-VISIBLE?  ( -- flag )
    _RTERM-L-SLOT @ AHS-VISIBLE? 0= IF 0 EXIT THEN
    _RTERM-RL-REGION @ 0= IF 0 EXIT THEN
    _RTERM-L-SLOT @ AHS.RGN @ _RTERM-RL-REGION @ <> IF 0 EXIT THEN
    _RTERM-RL-REGION @ _RTERM-REGION-SANE? 0= IF 0 EXIT THEN
    _RTERM-RL-REGION @ _RTERM-L-REGION !
    _RTERM-LIVE-OBJECTS-DISJOINT? 0= IF 0 EXIT THEN
    _RTERM-RL-BACKEND @ _RTERM-LIVE-DISJOINT-BACKEND? ;

: _RTERM-RELAYOUT-HIDDEN?  ( -- flag )
    _RTERM-RL-REGION @ IF 0 EXIT THEN
    _RTERM-L-SLOT @ AHS-VISIBLE? 0= ;

: _RTERM-RELAYOUT-COMMIT  ( -- )
    _RTERM-RL-VISIBLE @ IF
        _RTERM-RL-REGION @ DUP _RTERM-REGION>GEOMETRY
        _RTERM-C-RECORD @ _RTERM-R.REGION !
        _RTERM-G-ROW @ _RTERM-C-RECORD @ _RTERM-R.ROW !
        _RTERM-G-COL @ _RTERM-C-RECORD @ _RTERM-R.COL !
        _RTERM-G-HEIGHT @ _RTERM-C-RECORD @ _RTERM-R.HEIGHT !
        _RTERM-G-WIDTH @ _RTERM-C-RECORD @ _RTERM-R.WIDTH !
        -1 _RTERM-C-RECORD @ _RTERM-R.VISIBLE !
    ELSE
        _RTERM-C-RECORD @ _RTERM-R.REGION 48 0 FILL
    THEN ;

: _RTERM-UCTX-RELAYOUT-BODY
    ( visible region binding-token backend -- status )
    _RTERM-RL-BACKEND ! _RTERM-RL-TOKEN !
    _RTERM-RL-REGION ! _RTERM-RL-VISIBLE !
    _RTERM-RL-VISIBLE @ _RTERM-BOOL? 0= IF RTERM-S-INVALID EXIT THEN
    _RTERM-RL-TOKEN @ _RTERM-RL-BACKEND @
        _RTERM-CALL-LOOKUP 0= IF
        _RTERM-C-STATUS @ _RTERM-CALL-FAIL EXIT
    THEN
    _RTERM-C-RECORD @ _RTERM-R.STATE @
        _RTERM-BINDING-ST-ATTACHED <> IF
        RTERM-S-STALE _RTERM-CALL-FAIL EXIT
    THEN
    _RTERM-CALL-LIVE? 0= IF RTERM-S-STALE _RTERM-CALL-FAIL EXIT THEN
    _RTERM-RL-VISIBLE @ IF
        _RTERM-RELAYOUT-VISIBLE? 0= IF
            RTERM-S-INVALID _RTERM-CALL-FAIL EXIT
        THEN
    ELSE
        _RTERM-RELAYOUT-HIDDEN? 0= IF
            RTERM-S-INVALID _RTERM-CALL-FAIL EXIT
        THEN
    THEN
    _RTERM-RELAYOUT-COMMIT
    RTERM-S-OK ;

: _RTERM-UCTX-QUIESCE-BODY  ( binding-token backend -- status )
    2DUP _RTERM-CALL-LOOKUP 0= IF
        2DROP _RTERM-C-STATUS @ _RTERM-CALL-FAIL EXIT
    THEN
    2DROP
    _RTERM-C-RECORD @ _RTERM-R.STATE @
        _RTERM-BINDING-ST-DETACHED = IF RTERM-S-OK EXIT THEN
    _RTERM-C-RECORD @ _RTERM-R.STATE @ DUP
        _RTERM-BINDING-ST-ATTACHED = SWAP
        _RTERM-BINDING-ST-QUIESCED = OR 0= IF
        RTERM-S-INVALID _RTERM-CALL-FAIL EXIT
    THEN
    _RTERM-CALL-LIVE? 0= IF RTERM-S-STALE _RTERM-CALL-FAIL EXIT THEN
    RTERM-S-OK _RTERM-C-RECORD @ _RTERM-R.LAST-STATUS !
    _RTERM-BINDING-ST-QUIESCED _RTERM-C-RECORD @ _RTERM-R.STATE !
    RTERM-S-OK ;

VARIABLE _RTERM-D-TOKEN

: _RTERM-UCTX-DETACH-BODY  ( binding-token backend -- status )
    2DUP _RTERM-CALL-LOOKUP 0= IF
        2DROP _RTERM-C-STATUS @ _RTERM-CALL-FAIL EXIT
    THEN
    2DROP
    _RTERM-C-RECORD @ _RTERM-R.STATE @
        _RTERM-BINDING-ST-DETACHED = IF RTERM-S-OK EXIT THEN
    _RTERM-C-RECORD @ _RTERM-R.STATE @
        _RTERM-BINDING-ST-QUIESCED <> IF
        RTERM-S-INVALID _RTERM-CALL-FAIL EXIT
    THEN
    _RTERM-CALL-LIVE? 0= IF RTERM-S-STALE _RTERM-CALL-FAIL EXIT THEN
    _RTERM-C-BACKEND @ _RTERM-B.ACTIVE @ 0= IF
        RTERM-S-INVALID _RTERM-CALL-FAIL EXIT
    THEN
    _RTERM-C-RECORD @ _RTERM-R.TOKEN @ _RTERM-D-TOKEN !
    _RTERM-C-RECORD @ RTERM-UIDL-BINDING-SIZE 0 FILL
    _RTERM-D-TOKEN @ _RTERM-C-RECORD @ _RTERM-R.TOKEN !
    _RTERM-C-BACKEND @ _RTERM-C-RECORD @ _RTERM-R.ISSUER !
    RTERM-S-OK _RTERM-C-RECORD @ _RTERM-R.LAST-STATUS !
    _RTERM-BINDING-ST-DETACHED _RTERM-C-RECORD @ _RTERM-R.STATE !
    -1 _RTERM-C-BACKEND @ _RTERM-B.ACTIVE +!
    RTERM-S-OK ;

\ =====================================================================
\  Host-facing wrappers and borrowed-authority scrubbing
\ =====================================================================
\
\  The implementation uses module scratch because callbacks execute only on
\  the UI owner and the UIDL seam rejects reentry.  No borrowed descriptor,
\  slot, CINST, UCTX, region, or application descriptor address may remain in
\  that scratch after a public call, including when a callback throws.

VARIABLE _RTERM-P-A0
VARIABLE _RTERM-P-A1
VARIABLE _RTERM-P-A2
VARIABLE _RTERM-P-A3
VARIABLE _RTERM-INSTALL-BACKEND

: _RTERM-SCRUB-BORROWED  ( -- )
    0 _RTERM-G-ROW ! 0 _RTERM-G-COL !
    0 _RTERM-G-HEIGHT ! 0 _RTERM-G-WIDTH ! 0 _RTERM-G-REGION !
    0 _RTERM-I-HOST ! 0 _RTERM-I-RECORDS-A !
    0 _RTERM-I-RECORDS-U ! 0 _RTERM-I-BACKEND !
    0 _RTERM-RV-RECORD ! 0 _RTERM-RV-BACKEND !
    0 _RTERM-V-BACKEND ! 0 _RTERM-V-ACTIVE !
    0 _RTERM-SD-A ! 0 _RTERM-SD-U ! 0 _RTERM-SD-B !
    0 _RTERM-LIST-SLOW ! 0 _RTERM-LIST-FAST !
    0 _RTERM-HX-HOST ! 0 _RTERM-HX-SLOT !
    0 _RTERM-HX-ID ! 0 _RTERM-HX-MATCHES !
    0 _RTERM-L-HOST ! 0 _RTERM-L-SLOT ! 0 _RTERM-L-SLOT-ID !
    0 _RTERM-L-INST ! 0 _RTERM-L-INST-ID ! 0 _RTERM-L-INST-GEN !
    0 _RTERM-L-UCTX ! 0 _RTERM-L-REGION !
    0 _RTERM-L-APP-DESC ! 0 _RTERM-L-APP-SIZE !
    0 _RTERM-L-COMP-DESC ! 0 _RTERM-L-COMP-SIZE !
    0 _RTERM-L-STATE ! 0 _RTERM-L-STATE-SIZE !
    0 _RTERM-DB-BACKEND !
    0 _RTERM-HC-HOST ! 0 _RTERM-HC-SLOT ! 0 _RTERM-HC-BINDING !
    0 _RTERM-LK-TOKEN ! 0 _RTERM-LK-BACKEND !
    0 _RTERM-LK-RECORD ! 0 _RTERM-LK-MATCHES !
    0 _RTERM-A-HB ! 0 _RTERM-A-BACKEND ! 0 _RTERM-A-EXACT !
    0 _RTERM-A-FREE ! 0 _RTERM-A-DETACHED !
    0 _RTERM-A-COLLISION ! 0 _RTERM-A-TOKEN !
    0 _RTERM-A-COMPARE-HB !
    0 _RTERM-C-RECORD ! 0 _RTERM-C-STATUS ! 0 _RTERM-C-BACKEND !
    0 _RTERM-RL-VISIBLE ! 0 _RTERM-RL-REGION !
    0 _RTERM-RL-TOKEN ! 0 _RTERM-RL-BACKEND !
    0 _RTERM-D-TOKEN !
    0 _RTERM-INSTALL-BACKEND !
    0 _RTERM-P-A0 ! 0 _RTERM-P-A1 ! 0 _RTERM-P-A2 ! 0 _RTERM-P-A3 ! ;

: _RTERM-P-DO-UIDL-INIT  ( -- status )
    _RTERM-P-A0 @ _RTERM-P-A1 @ _RTERM-P-A2 @ _RTERM-P-A3 @
    _RTERM-UIDL-INIT-BODY ;

: RTERM-UIDL-INIT  ( host records-a records-u backend -- status )
    _RTERM-P-A3 ! _RTERM-P-A2 ! _RTERM-P-A1 ! _RTERM-P-A0 !
    ['] _RTERM-P-DO-UIDL-INIT CATCH ?DUP IF
        DROP RTERM-S-INVALID
    THEN
    _RTERM-SCRUB-BORROWED ;

: _RTERM-P-DO-UIDL-VALID  ( -- flag )
    _RTERM-P-A0 @ _RTERM-UIDL-VALID-BODY? ;

: RTERM-UIDL-VALID?  ( backend -- flag )
    _RTERM-P-A0 !
    ['] _RTERM-P-DO-UIDL-VALID CATCH ?DUP IF DROP 0 THEN
    _RTERM-SCRUB-BORROWED ;

: _RTERM-P-DO-UIDL-STORAGE-DISJOINT  ( -- flag )
    _RTERM-P-A0 @ _RTERM-P-A1 @ _RTERM-P-A2 @
    _RTERM-UIDL-STORAGE-DISJOINT-BODY? ;

: RTERM-UIDL-STORAGE-DISJOINT?  ( a u backend -- flag )
    _RTERM-P-A2 ! _RTERM-P-A1 ! _RTERM-P-A0 !
    ['] _RTERM-P-DO-UIDL-STORAGE-DISJOINT CATCH ?DUP IF DROP 0 THEN
    _RTERM-SCRUB-BORROWED ;

: _RTERM-P-DO-UIDL-STATUS  ( -- status )
    _RTERM-P-A0 @ _RTERM-UIDL-STATUS-BODY@ ;

: RTERM-UIDL-STATUS@  ( backend -- status )
    _RTERM-P-A0 !
    ['] _RTERM-P-DO-UIDL-STATUS CATCH ?DUP IF
        DROP RTERM-S-INVALID
    THEN
    _RTERM-SCRUB-BORROWED ;

: _RTERM-P-DO-UIDL-ACTIVE  ( -- count status )
    _RTERM-P-A0 @ _RTERM-UIDL-ACTIVE-BODY@ ;

: RTERM-UIDL-ACTIVE@  ( backend -- count status )
    _RTERM-P-A0 !
    ['] _RTERM-P-DO-UIDL-ACTIVE CATCH ?DUP IF
        DROP 0 RTERM-S-INVALID
    THEN
    _RTERM-SCRUB-BORROWED ;

: _RTERM-P-DO-HB-VALID  ( -- flag )
    _RTERM-P-A0 @ _RTERM-HOST-BINDING-VALID-BODY? ;

: RTERM-HOST-BINDING-VALID?  ( host-binding -- flag )
    _RTERM-P-A0 !
    ['] _RTERM-P-DO-HB-VALID CATCH ?DUP IF DROP 0 THEN
    _RTERM-SCRUB-BORROWED ;

: _RTERM-P-DO-HB-CAPTURE  ( -- status )
    _RTERM-P-A0 @ _RTERM-P-A1 @ _RTERM-P-A2 @
    _RTERM-HOST-BINDING-CAPTURE-BODY ;

: RTERM-HOST-BINDING-CAPTURE  ( host slot host-binding -- status )
    _RTERM-P-A2 ! _RTERM-P-A1 ! _RTERM-P-A0 !
    ['] _RTERM-P-DO-HB-CAPTURE CATCH ?DUP IF
        DROP RTERM-S-INVALID
    THEN
    _RTERM-SCRUB-BORROWED ;

: _RTERM-P-DO-ATTACH  ( -- binding-token status )
    _RTERM-P-A0 @ _RTERM-P-A1 @ _RTERM-UCTX-ATTACH-BODY ;

: RTERM-UCTX-ATTACH  ( host-binding backend -- binding-token status )
    _RTERM-P-A1 ! _RTERM-P-A0 !
    ['] _RTERM-P-DO-ATTACH CATCH ?DUP IF
        DROP 0 RTERM-S-INVALID
    THEN
    _RTERM-SCRUB-BORROWED ;

: _RTERM-P-DO-PROJECT  ( -- status )
    _RTERM-P-A0 @ _RTERM-P-A1 @ _RTERM-UCTX-PROJECT-BODY ;

: RTERM-UCTX-PROJECT  ( binding-token backend -- status )
    _RTERM-P-A1 ! _RTERM-P-A0 !
    ['] _RTERM-P-DO-PROJECT CATCH ?DUP IF
        DROP RTERM-S-INVALID
    THEN
    _RTERM-SCRUB-BORROWED ;

: _RTERM-P-DO-RELAYOUT  ( -- status )
    _RTERM-P-A0 @ _RTERM-P-A1 @ _RTERM-P-A2 @ _RTERM-P-A3 @
    _RTERM-UCTX-RELAYOUT-BODY ;

: RTERM-UCTX-RELAYOUT  ( visible region binding-token backend -- status )
    _RTERM-P-A3 ! _RTERM-P-A2 ! _RTERM-P-A1 ! _RTERM-P-A0 !
    ['] _RTERM-P-DO-RELAYOUT CATCH ?DUP IF
        DROP RTERM-S-INVALID
    THEN
    _RTERM-SCRUB-BORROWED ;

: _RTERM-P-DO-QUIESCE  ( -- status )
    _RTERM-P-A0 @ _RTERM-P-A1 @ _RTERM-UCTX-QUIESCE-BODY ;

: RTERM-UCTX-QUIESCE  ( binding-token backend -- status )
    _RTERM-P-A1 ! _RTERM-P-A0 !
    ['] _RTERM-P-DO-QUIESCE CATCH ?DUP IF
        DROP RTERM-S-INVALID
    THEN
    _RTERM-SCRUB-BORROWED ;

: _RTERM-P-DO-DETACH  ( -- status )
    _RTERM-P-A0 @ _RTERM-P-A1 @ _RTERM-UCTX-DETACH-BODY ;

: RTERM-UCTX-DETACH  ( binding-token backend -- status )
    _RTERM-P-A1 ! _RTERM-P-A0 !
    ['] _RTERM-P-DO-DETACH CATCH ?DUP IF
        DROP RTERM-S-INVALID
    THEN
    _RTERM-SCRUB-BORROWED ;

\ =====================================================================
\  Immutable UIDL composition install
\ =====================================================================

: _RTERM-UIDL-INSTALL-BODY  ( backend -- status )
    DUP _RTERM-UIDL-VALID-BODY? 0= IF DROP RTERM-S-INVALID EXIT THEN
    DUP _RTERM-INSTALL-BACKEND !
    DUP
    ['] RTERM-UCTX-ATTACH
    ['] RTERM-UCTX-PROJECT
    ['] RTERM-UCTX-RELAYOUT
    ['] RTERM-UCTX-QUIESCE
    ['] RTERM-UCTX-DETACH
    _UTUI-RICH-TERM-DRIVER! 0= IF
        DROP RTERM-S-INVALID _RTERM-INSTALL-BACKEND @ _RTERM-NOTE EXIT
    THEN
    -1 SWAP _RTERM-B.INSTALLED !
    RTERM-S-OK ;

: _RTERM-P-DO-UIDL-INSTALL  ( -- status )
    _RTERM-P-A0 @ _RTERM-UIDL-INSTALL-BODY ;

: RTERM-UIDL-INSTALL  ( backend -- status )
    _RTERM-P-A0 !
    ['] _RTERM-P-DO-UIDL-INSTALL CATCH ?DUP IF
        DROP RTERM-S-INVALID
    THEN
    _RTERM-SCRUB-BORROWED ;
