\ =====================================================================
\  component-adapter.f - Akashic component catalogs over native MCP
\ =====================================================================
\  This is the sole mapping layer between MCP and Akashic's registry,
\  schemas, effects, policy, and request bus. The adapter owns the server
\  catalog it populates. It never depends on Desk, TUI, providers, network,
\  Python, or emulator services.
\ =====================================================================

PROVIDED akashic-mcp-component-adapter

REQUIRE server.f
REQUIRE ../request-bus.f
REQUIRE ../codecs/capability-json.f

0 CONSTANT MCPA-REVIEW-DENY
1 CONSTANT MCPA-REVIEW-ALLOW
2 CONSTANT MCPA-REVIEW-CANCEL

64 CONSTANT MCPA-MAX-BINDINGS

 0 CONSTANT _MCB-ADAPTER
 8 CONSTANT _MCB-INST-ID
16 CONSTANT _MCB-INST-GEN
24 CONSTANT _MCB-CAP
32 CONSTANT _MCB-NAME-U
40 CONSTANT _MCB-URI-U
48 CONSTANT _MCB-TOOL
_MCB-TOOL MCP-TOOL-DESC-SIZE + CONSTANT _MCB-RESOURCE
_MCB-RESOURCE MCP-RESOURCE-DESC-SIZE + CONSTANT _MCB-NAME-BUF
_MCB-NAME-BUF MCP-MAX-NAME + CONSTANT _MCB-URI-BUF
_MCB-URI-BUF MCP-MAX-URI + CONSTANT MCPA-BINDING-SIZE

: MCPB.ADAPTER    ( binding -- a ) _MCB-ADAPTER + ;
: MCPB.INST-ID    ( binding -- a ) _MCB-INST-ID + ;
: MCPB.INST-GEN   ( binding -- a ) _MCB-INST-GEN + ;
: MCPB.CAP        ( binding -- a ) _MCB-CAP + ;
: MCPB.NAME-U     ( binding -- a ) _MCB-NAME-U + ;
: MCPB.URI-U      ( binding -- a ) _MCB-URI-U + ;
: MCPB.TOOL       ( binding -- tool ) _MCB-TOOL + ;
: MCPB.RESOURCE   ( binding -- resource ) _MCB-RESOURCE + ;
: MCPB.NAME-BUF   ( binding -- buffer ) _MCB-NAME-BUF + ;
: MCPB.URI-BUF    ( binding -- buffer ) _MCB-URI-BUF + ;

 0 CONSTANT _MCA-REGISTRY
 8 CONSTANT _MCA-BUS
16 CONSTANT _MCA-SERVER
24 CONSTANT _MCA-PRINCIPAL
32 CONSTANT _MCA-REVIEW-XT       \ ( request context -- decision )
40 CONSTANT _MCA-REVIEW-CONTEXT
48 CONSTANT _MCA-BINDING-N
56 CONSTANT _MCA-BINDINGS
_MCA-BINDINGS MCPA-MAX-BINDINGS 8 * + CONSTANT MCPA-SIZE

: MCPA.REGISTRY       ( adapter -- a ) _MCA-REGISTRY + ;
: MCPA.BUS            ( adapter -- a ) _MCA-BUS + ;
: MCPA.SERVER         ( adapter -- a ) _MCA-SERVER + ;
: MCPA.PRINCIPAL      ( adapter -- a ) _MCA-PRINCIPAL + ;
: MCPA.REVIEW-XT      ( adapter -- a ) _MCA-REVIEW-XT + ;
: MCPA.REVIEW-CONTEXT ( adapter -- a ) _MCA-REVIEW-CONTEXT + ;
: MCPA.BINDING-N      ( adapter -- a ) _MCA-BINDING-N + ;
: MCPA.BINDINGS       ( adapter -- a ) _MCA-BINDINGS + ;

VARIABLE _MCAN-R
VARIABLE _MCAN-B
VARIABLE _MCAN-S

: MCPA-NEW  ( registry bus server -- adapter ior )
    _MCAN-S ! _MCAN-B ! _MCAN-R !
    _MCAN-R @ 0= _MCAN-B @ 0= OR _MCAN-S @ 0= OR IF
        0 MCP-S-INVALID EXIT
    THEN
    MCPA-SIZE ALLOCATE
    DUP IF SWAP DROP 0 SWAP EXIT THEN
    DROP DUP MCPA-SIZE 0 FILL
    _MCAN-R @ OVER MCPA.REGISTRY !
    _MCAN-B @ OVER MCPA.BUS !
    _MCAN-S @ OVER MCPA.SERVER !
    CPRINC-AGENT OVER MCPA.PRINCIPAL !
    0 ;

: MCPA-BINDING-NTH  ( index adapter -- binding | 0 )
    >R DUP 0< OVER R@ MCPA.BINDING-N @ >= OR IF
        DROP R> DROP 0 EXIT
    THEN
    8 * R> MCPA.BINDINGS + @ ;

: MCPA-CATALOG-CLEAR  ( adapter -- )
    DUP MCPA.SERVER @ MCP-SERVER-CATALOG-CLEAR
    DUP MCPA.BINDING-N @ 0 ?DO
        I OVER MCPA-BINDING-NTH ?DUP IF FREE THEN
    LOOP
    DUP MCPA.BINDINGS MCPA-MAX-BINDINGS 8 * 0 FILL
    0 SWAP MCPA.BINDING-N ! ;

: MCPA-FREE  ( adapter -- )
    DUP 0= IF DROP EXIT THEN
    DUP MCPA-CATALOG-CLEAR FREE ;

VARIABLE _MCAR-XT
VARIABLE _MCAR-CONTEXT
VARIABLE _MCAR-A

: MCPA-REVIEWER!  ( reviewer-xt context adapter -- )
    _MCAR-A ! _MCAR-CONTEXT ! _MCAR-XT !
    _MCAR-XT @ _MCAR-A @ MCPA.REVIEW-XT !
    _MCAR-CONTEXT @ _MCAR-A @ MCPA.REVIEW-CONTEXT ! ;

\ =====================================================================
\  Binding construction
\ =====================================================================

VARIABLE _MCBN-B
VARIABLE _MCBN-I
VARIABLE _MCBN-A
VARIABLE _MCBN-U
VARIABLE _MCBN-N
VARIABLE _MCBN-CAP-A
VARIABLE _MCBN-CAP-U

: _MCPA-BUILD-NAME  ( binding -- status )
    _MCBN-B !
    _MCBN-B @ MCPB.CAP @ CAP-ID _MCBN-U ! _MCBN-A !
    _MCBN-B @ MCPB.INST-ID @ NUM>STR _MCBN-N ! _MCBN-I !
    _MCBN-U @ 2 + _MCBN-N @ + MCP-MAX-NAME > IF MCP-S-CAPACITY EXIT THEN
    _MCBN-A @ _MCBN-B @ MCPB.NAME-BUF _MCBN-U @ CMOVE
    46 _MCBN-B @ MCPB.NAME-BUF _MCBN-U @ + C!
    105 _MCBN-B @ MCPB.NAME-BUF _MCBN-U @ 1+ + C!
    _MCBN-I @ _MCBN-B @ MCPB.NAME-BUF _MCBN-U @ 2 + + _MCBN-N @ CMOVE
    _MCBN-U @ 2 + _MCBN-N @ + DUP _MCBN-B @ MCPB.NAME-U !
    _MCBN-B @ MCPB.NAME-BUF SWAP MCP-TOOL-NAME-VALID? 0= IF
        MCP-S-INVALID
    ELSE
        MCP-S-OK
    THEN ;

: _MCPA-BUILD-URI  ( binding -- status )
    _MCBN-B !
    S" akashic://instance/" _MCBN-U ! _MCBN-A !
    _MCBN-B @ MCPB.INST-ID @ NUM>STR _MCBN-N ! _MCBN-I !
    _MCBN-B @ MCPB.CAP @ CAP-ID _MCBN-CAP-U ! _MCBN-CAP-A !
    _MCBN-U @ _MCBN-N @ + 1+ _MCBN-CAP-U @ + MCP-MAX-URI > IF
        MCP-S-CAPACITY EXIT
    THEN
    _MCBN-A @ _MCBN-B @ MCPB.URI-BUF _MCBN-U @ CMOVE
    _MCBN-I @ _MCBN-B @ MCPB.URI-BUF _MCBN-U @ + _MCBN-N @ CMOVE
    47 _MCBN-B @ MCPB.URI-BUF _MCBN-U @ _MCBN-N @ + + C!
    _MCBN-CAP-A @ _MCBN-B @ MCPB.URI-BUF
    _MCBN-U @ _MCBN-N @ + 1+ + _MCBN-CAP-U @ CMOVE
    _MCBN-U @ _MCBN-N @ + 1+ _MCBN-CAP-U @ +
    DUP _MCBN-B @ MCPB.URI-U !
    _MCBN-B @ MCPB.URI-BUF SWAP MCP-URI-VALID? 0= IF
        MCP-S-INVALID
    ELSE
        MCP-S-OK
    THEN ;

: _MCPA-TOOL-FLAGS  ( cap -- flags )
    0 SWAP
    DUP CAP.EFFECTS @ CAP-E-OBSERVE = IF
        SWAP MCP-TOOL-F-READ-ONLY OR SWAP
    THEN
    DUP CAP.EFFECTS @ CAP-E-DESTRUCTIVE AND IF
        SWAP MCP-TOOL-F-DESTRUCTIVE OR SWAP
    THEN
    DUP CAP.FLAGS @ CAP-F-IDEMPOTENT AND IF
        SWAP MCP-TOOL-F-IDEMPOTENT OR SWAP
    THEN
    CAP.EFFECTS @ CAP-E-EXTERNAL AND IF
        MCP-TOOL-F-OPEN-WORLD OR
    THEN ;

: _MCPA-MIME  ( schema -- addr len )
    DUP 0= IF DROP S" text/plain" EXIT THEN
    CS.TYPE-MASK @
    DUP CV-T-BYTES CS-TYPE-BIT AND IF DROP S" application/octet-stream" EXIT THEN
    DUP CV-T-RESOURCE CS-TYPE-BIT AND IF DROP S" text/uri-list" EXIT THEN
    DUP CV-T-MAP CS-TYPE-BIT AND IF DROP S" application/json" EXIT THEN
    CV-T-LIST CS-TYPE-BIT AND IF S" application/json" ELSE S" text/plain" THEN ;

VARIABLE _MCBI-B
VARIABLE _MCBI-INST
VARIABLE _MCBI-CAP
VARIABLE _MCBI-A

DEFER _MCPA-TOOL-CALL
DEFER _MCPA-RESOURCE-READ

: _MCPA-BINDING-NEW  ( instance cap adapter -- binding status )
    _MCBI-A ! _MCBI-CAP ! _MCBI-INST !
    MCPA-BINDING-SIZE ALLOCATE
    DUP IF 2DROP 0 MCP-S-CAPACITY EXIT THEN
    DROP DUP _MCBI-B ! MCPA-BINDING-SIZE 0 FILL
    _MCBI-A @ _MCBI-B @ MCPB.ADAPTER !
    _MCBI-INST @ CINST.ID @ _MCBI-B @ MCPB.INST-ID !
    _MCBI-INST @ CINST.GENERATION @ _MCBI-B @ MCPB.INST-GEN !
    _MCBI-CAP @ _MCBI-B @ MCPB.CAP !
    _MCBI-B @ _MCPA-BUILD-NAME ?DUP IF
        _MCBI-B @ FREE 0 SWAP EXIT
    THEN
    _MCBI-B @ _MCPA-BUILD-URI ?DUP IF
        _MCBI-B @ FREE 0 SWAP EXIT
    THEN

    _MCBI-B @ MCPB.TOOL DUP MCP-TOOL-INIT
    _MCBI-B @ MCPB.NAME-BUF OVER MTOOL.NAME-A !
    _MCBI-B @ MCPB.NAME-U @ OVER MTOOL.NAME-U !
    _MCBI-CAP @ CAP.TITLE-A @ OVER MTOOL.TITLE-A !
    _MCBI-CAP @ CAP.TITLE-U @ OVER MTOOL.TITLE-U !
    _MCBI-CAP @ CAP.DESC-A @ OVER MTOOL.DESC-A !
    _MCBI-CAP @ CAP.DESC-U @ OVER MTOOL.DESC-U !
    _MCBI-CAP @ CAP.IN-SCHEMA @ OVER MTOOL.IN-SCHEMA !
    _MCBI-CAP @ CAP.OUT-SCHEMA @ OVER MTOOL.OUT-SCHEMA !
    _MCBI-CAP @ _MCPA-TOOL-FLAGS OVER MTOOL.FLAGS !
    _MCBI-CAP @ CAP.EFFECTS @ OVER MTOOL.EFFECTS !
    ['] _MCPA-TOOL-CALL OVER MTOOL.CALL-XT !
    _MCBI-B @ SWAP MTOOL.CONTEXT !

    _MCBI-CAP @ CAP.KIND @ CAP-K-RESOURCE = IF
        _MCBI-B @ MCPB.RESOURCE DUP MCP-RESOURCE-INIT
        _MCBI-B @ MCPB.URI-BUF OVER MRES.URI-A !
        _MCBI-B @ MCPB.URI-U @ OVER MRES.URI-U !
        _MCBI-CAP @ CAP.ID-A @ OVER MRES.NAME-A !
        _MCBI-CAP @ CAP.ID-U @ OVER MRES.NAME-U !
        _MCBI-CAP @ CAP.TITLE-A @ OVER MRES.TITLE-A !
        _MCBI-CAP @ CAP.TITLE-U @ OVER MRES.TITLE-U !
        _MCBI-CAP @ CAP.DESC-A @ OVER MRES.DESC-A !
        _MCBI-CAP @ CAP.DESC-U @ OVER MRES.DESC-U !
        _MCBI-CAP @ CAP.OUT-SCHEMA @ _MCPA-MIME
        2 PICK MRES.MIME-U ! OVER MRES.MIME-A !
        ['] _MCPA-RESOURCE-READ OVER MRES.READ-XT !
        _MCBI-B @ SWAP MRES.CONTEXT !
    THEN
    _MCBI-B @ MCP-S-OK ;

VARIABLE _MCAF-A
VARIABLE _MCAF-INST
VARIABLE _MCAF-CAP
VARIABLE _MCAF-BIND

: _MCPA-ADD-CAPABILITY  ( instance cap adapter -- status )
    _MCAF-A ! _MCAF-CAP ! _MCAF-INST !
    _MCAF-CAP @ CAP.HANDLER-XT @ 0= IF MCP-S-OK EXIT THEN
    _MCAF-CAP @ CAP.KIND @ DUP CAP-K-COMMAND < SWAP CAP-K-RESOURCE > OR IF
        MCP-S-OK EXIT
    THEN
    _MCAF-A @ MCPA.BINDING-N @ MCPA-MAX-BINDINGS >= IF
        MCP-S-CAPACITY EXIT
    THEN
    _MCAF-INST @ _MCAF-CAP @ _MCAF-A @ _MCPA-BINDING-NEW
    DUP IF NIP EXIT THEN DROP _MCAF-BIND !
    _MCAF-BIND @
    _MCAF-A @ MCPA.BINDING-N @ 8 * _MCAF-A @ MCPA.BINDINGS + !
    1 _MCAF-A @ MCPA.BINDING-N +!
    _MCAF-BIND @ MCPB.TOOL _MCAF-A @ MCPA.SERVER @ MCP-SERVER-TOOL+
    ?DUP IF EXIT THEN
    _MCAF-CAP @ CAP.KIND @ CAP-K-RESOURCE = IF
        _MCAF-BIND @ MCPB.RESOURCE
        _MCAF-A @ MCPA.SERVER @ MCP-SERVER-RESOURCE+ ?DUP IF EXIT THEN
    THEN
    MCP-S-OK ;

VARIABLE _MCAREF-A
VARIABLE _MCAREF-INST
VARIABLE _MCAREF-DESC

: MCPA-REFRESH  ( adapter -- status )
    DUP _MCAREF-A ! MCPA-CATALOG-CLEAR
    _MCAREF-A @ MCPA.REGISTRY @ CREG.INST-N @ 0 ?DO
        I _MCAREF-A @ MCPA.REGISTRY @ CREG-INST-NTH DUP _MCAREF-INST !
        CINST-DESC _MCAREF-DESC !
        _MCAREF-DESC @ COMP.CAPS-N @ 0 ?DO
            I _MCAREF-DESC @ COMP-CAP-NTH
            _MCAREF-INST @ SWAP _MCAREF-A @ _MCPA-ADD-CAPABILITY
            ?DUP IF
                _MCAREF-A @ MCPA-CATALOG-CLEAR UNLOOP UNLOOP EXIT
            THEN
        LOOP
    LOOP
    MCP-S-OK ;

\ =====================================================================
\  Request execution
\ =====================================================================

VARIABLE _MCAD-BIND
VARIABLE _MCAD-ARGS
VARIABLE _MCAD-RESULT
VARIABLE _MCAD-REQ
VARIABLE _MCAD-INST
VARIABLE _MCAD-STATUS
VARIABLE _MCAD-ERR-A
VARIABLE _MCAD-ERR-U

: _MCPA-BUS-STATUS  ( bus-status -- mcp-status )
    CASE
        CBUS-S-OK OF MCP-S-OK ENDOF
        CBUS-S-INVALID OF MCP-S-INVALID ENDOF
        CBUS-S-NOT-FOUND OF MCP-S-NOT-FOUND ENDOF
        CBUS-S-STALE-INSTANCE OF MCP-S-NOT-FOUND ENDOF
        CBUS-S-STALE-REVISION OF MCP-S-NOT-FOUND ENDOF
        CBUS-S-DENIED OF MCP-S-DENIED ENDOF
        CBUS-S-NEEDS-APPROVAL OF MCP-S-APPROVAL ENDOF
        CBUS-S-BUSY OF MCP-S-BUSY ENDOF
        CBUS-S-TIMEOUT OF MCP-S-TIMEOUT ENDOF
        CBUS-S-CANCELLED OF MCP-S-CANCELLED ENDOF
        DROP MCP-S-FAILED
    ENDCASE ;

VARIABLE _MCADV-A
VARIABLE _MCADV-XT
VARIABLE _MCADV-DECISION

: _MCPA-REVIEW-CALL  ( -- )
    _MCAD-REQ @ _MCADV-A @ MCPA.REVIEW-CONTEXT @
    _MCADV-XT @ EXECUTE _MCADV-DECISION ! ;

: _MCPA-DISPATCH  ( binding args-value result-value -- status )
    _MCAD-RESULT ! _MCAD-ARGS ! _MCAD-BIND !
    0 _MCAD-REQ ! 0 _MCAD-ERR-A ! 0 _MCAD-ERR-U !
    _MCAD-BIND @ MCPB.ADAPTER @ _MCADV-A !
    _MCAD-BIND @ MCPB.INST-ID @ _MCAD-BIND @ MCPB.INST-GEN @
    _MCADV-A @ MCPA.REGISTRY @ CREG-INST-FIND DUP 0= IF
        DROP MCP-S-NOT-FOUND EXIT
    THEN
    _MCAD-INST !
    CBR-NEW DUP IF 2DROP MCP-S-CAPACITY EXIT THEN DROP _MCAD-REQ !
    _MCAD-ARGS @ _MCAD-REQ @ CBR.ARGS CV-COPY ?DUP IF
        DROP _MCAD-REQ @ CBR-FREE MCP-S-INVALID EXIT
    THEN
    _MCADV-A @ MCPA.PRINCIPAL @ _MCAD-REQ @ CBR.PRINCIPAL !
    _MCAD-BIND @ MCPB.INST-ID @ _MCAD-REQ @ CBR.TARGET-ID !
    _MCAD-BIND @ MCPB.INST-GEN @ _MCAD-REQ @ CBR.TARGET-GEN !
    _MCAD-BIND @ MCPB.CAP @ _MCAD-REQ @ CBR.CAP !
    _MCAD-BIND @ MCPB.CAP @ CAP.MAX-MS @ ?DUP IF
        MS@ + _MCAD-REQ @ CBR.DEADLINE !
    THEN
    _MCAD-REQ @ _MCADV-A @ MCPA.BUS @ CBUS-DISPATCH _MCAD-STATUS !
    _MCAD-STATUS @ CBUS-S-NEEDS-APPROVAL = IF
        _MCADV-A @ MCPA.REVIEW-XT @ DUP _MCADV-XT ! IF
            MCPA-REVIEW-DENY _MCADV-DECISION !
            ['] _MCPA-REVIEW-CALL CATCH IF
                MCPA-REVIEW-DENY _MCADV-DECISION !
            THEN
            _MCADV-DECISION @ MCPA-REVIEW-ALLOW = IF
                _MCAD-REQ @ CBR-APPROVE
                _MCAD-REQ @ _MCADV-A @ MCPA.BUS @ CBUS-DISPATCH
                _MCAD-STATUS !
            ELSE
                _MCADV-DECISION @ MCPA-REVIEW-CANCEL = IF
                    CBUS-S-CANCELLED _MCAD-STATUS !
                ELSE
                    CBUS-S-DENIED _MCAD-STATUS !
                THEN
            THEN
        THEN
    THEN
    _MCAD-REQ @ CBR.ERROR-A @ _MCAD-ERR-A !
    _MCAD-REQ @ CBR.ERROR-U @ _MCAD-ERR-U !
    _MCAD-STATUS @ CBUS-S-OK = IF
        _MCAD-REQ @ CBR.RESULT _MCAD-RESULT @ CV-COPY ?DUP IF
            DROP CBUS-S-FAILED _MCAD-STATUS !
        THEN
    THEN
    _MCAD-REQ @ CBR-FREE
    _MCAD-STATUS @ _MCPA-BUS-STATUS ;

VARIABLE _MCAT-CALL
VARIABLE _MCAT-BIND
CREATE _MCAT-ARGS CV-SIZE ALLOT

: _MCPA-TOOL-CALL-R  ( call binding -- status )
    _MCAT-BIND ! _MCAT-CALL ! _MCAT-ARGS CV-INIT
    _MCAT-CALL @ DUP MCALL.ARGS-A @ SWAP MCALL.ARGS-U @
    _MCAT-BIND @ MCPB.CAP @ CAP.IN-SCHEMA @ _MCAT-ARGS
    CAPJSON-DECODE-INPUT
    DUP IF
        DROP _MCAT-ARGS CV-FREE MCP-S-INVALID EXIT
    THEN
    DROP _MCAT-BIND @ _MCAT-ARGS _MCAT-CALL @ MCALL.RESULT _MCPA-DISPATCH
    DUP MCP-S-OK <> IF
        _MCAD-ERR-U @ IF
            _MCAD-ERR-A @ _MCAD-ERR-U @ _MCAT-CALL @ MCP-CALL-ERROR!
        THEN
    THEN
    _MCAT-ARGS CV-FREE ;

' _MCPA-TOOL-CALL-R IS _MCPA-TOOL-CALL

VARIABLE _MCARR-READ
VARIABLE _MCARR-BIND
CREATE _MCARR-ARGS CV-SIZE ALLOT

: _MCPA-RESOURCE-READ-R  ( read binding -- status )
    _MCARR-BIND ! _MCARR-READ ! _MCARR-ARGS CV-INIT
    _MCARR-ARGS CV-NULL!
    _MCARR-BIND @ _MCARR-ARGS _MCARR-READ @ MREAD.CONTENT _MCPA-DISPATCH
    DUP MCP-S-OK <> IF
        _MCAD-ERR-U @ IF
            _MCAD-ERR-A @ _MCAD-ERR-U @ _MCARR-READ @ MCP-READ-ERROR!
        THEN
    THEN
    _MCARR-ARGS CV-FREE ;

' _MCPA-RESOURCE-READ-R IS _MCPA-RESOURCE-READ
