\ =====================================================================
\  client-config.f - Immutable provider-neutral OAuth client selection
\ =====================================================================
\  This caller-owned record resolves one opaque durable binding to the
\  exact client values selected for an authorization-code flow.  It copies
\  every retained byte and contains no private key, token, endpoint, HTTP,
\  browser, provider, AT Protocol, or Streams state.
\
\  A higher owner resolves the binding to any client-authentication and
\  DPoP key material used with this selection.  The binding is deliberately
\  opaque here: it is an identity, not a private key container.
\ =====================================================================

PROVIDED akashic-oauth2-client-config

REQUIRE ../../utils/memory-span.f
REQUIRE ../../utils/caller-span.f

\ =====================================================================
\  Public status, flags, and capacities
\ =====================================================================

0 CONSTANT OAUTH2-CLIENT-CONFIG-S-OK
1 CONSTANT OAUTH2-CLIENT-CONFIG-S-INVALID
2 CONSTANT OAUTH2-CLIENT-CONFIG-S-CAPACITY
3 CONSTANT OAUTH2-CLIENT-CONFIG-S-ALIAS
4 CONSTANT OAUTH2-CLIENT-CONFIG-S-STATE
5 CONSTANT OAUTH2-CLIENT-CONFIG-S-RANGE
6 CONSTANT OAUTH2-CLIENT-CONFIG-S-PROTECTED
7 CONSTANT OAUTH2-CLIENT-CONFIG-S-PLATFORM

: OAUTH2-CLIENT-CONFIG-STATUS-VALID?  ( status -- flag )
    DUP OAUTH2-CLIENT-CONFIG-S-OK >=
    SWAP OAUTH2-CLIENT-CONFIG-S-PLATFORM <= AND ;

0 CONSTANT OAUTH2-CLIENT-CONFIG-APPLICATION-WEB
1 CONSTANT OAUTH2-CLIENT-CONFIG-APPLICATION-NATIVE

1 CONSTANT OAUTH2-CLIENT-CONFIG-F-NATIVE
2 CONSTANT OAUTH2-CLIENT-CONFIG-F-REFRESH
4 CONSTANT OAUTH2-CLIENT-CONFIG-F-DPOP-BOUND
7 CONSTANT _O2CC-FLAGS-KNOWN

256  CONSTANT OAUTH2-CLIENT-CONFIG-BINDING-CAPACITY
2048 CONSTANT OAUTH2-CLIENT-CONFIG-CLIENT-ID-CAPACITY
4096 CONSTANT OAUTH2-CLIENT-CONFIG-REDIRECT-URI-CAPACITY
4096 CONSTANT OAUTH2-CLIENT-CONFIG-SCOPE-CAPACITY
256  CONSTANT OAUTH2-CLIENT-CONFIG-AUTH-METHOD-CAPACITY
256  CONSTANT OAUTH2-CLIENT-CONFIG-AUTH-ALGORITHM-CAPACITY

\ =====================================================================
\  Input descriptor
\ =====================================================================

 0 CONSTANT _O2CCI-BINDING-A
 8 CONSTANT _O2CCI-BINDING-U
16 CONSTANT _O2CCI-CLIENT-ID-A
24 CONSTANT _O2CCI-CLIENT-ID-U
32 CONSTANT _O2CCI-REDIRECT-A
40 CONSTANT _O2CCI-REDIRECT-U
48 CONSTANT _O2CCI-SCOPE-A
56 CONSTANT _O2CCI-SCOPE-U
64 CONSTANT _O2CCI-AUTH-METHOD-A
72 CONSTANT _O2CCI-AUTH-METHOD-U
80 CONSTANT _O2CCI-AUTH-ALGORITHM-A
88 CONSTANT _O2CCI-AUTH-ALGORITHM-U
96 CONSTANT _O2CCI-FLAGS
104 CONSTANT OAUTH2-CLIENT-CONFIG-INPUT-SIZE

: OAUTH2-CLIENT-CONFIG-I.BINDING-A
  ( input -- field-address )
    _O2CCI-BINDING-A + ;
: OAUTH2-CLIENT-CONFIG-I.BINDING-U
  ( input -- field-address )
    _O2CCI-BINDING-U + ;
: OAUTH2-CLIENT-CONFIG-I.CLIENT-ID-A
  ( input -- field-address )
    _O2CCI-CLIENT-ID-A + ;
: OAUTH2-CLIENT-CONFIG-I.CLIENT-ID-U
  ( input -- field-address )
    _O2CCI-CLIENT-ID-U + ;
: OAUTH2-CLIENT-CONFIG-I.REDIRECT-URI-A
  ( input -- field-address )
    _O2CCI-REDIRECT-A + ;
: OAUTH2-CLIENT-CONFIG-I.REDIRECT-URI-U
  ( input -- field-address )
    _O2CCI-REDIRECT-U + ;
: OAUTH2-CLIENT-CONFIG-I.SCOPE-A
  ( input -- field-address )
    _O2CCI-SCOPE-A + ;
: OAUTH2-CLIENT-CONFIG-I.SCOPE-U
  ( input -- field-address )
    _O2CCI-SCOPE-U + ;
: OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-A
  ( input -- field-address )
    _O2CCI-AUTH-METHOD-A + ;
: OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-U
  ( input -- field-address )
    _O2CCI-AUTH-METHOD-U + ;
: OAUTH2-CLIENT-CONFIG-I.AUTH-ALGORITHM-A
  ( input -- field-address )
    _O2CCI-AUTH-ALGORITHM-A + ;
: OAUTH2-CLIENT-CONFIG-I.AUTH-ALGORITHM-U
  ( input -- field-address )
    _O2CCI-AUTH-ALGORITHM-U + ;
: OAUTH2-CLIENT-CONFIG-I.FLAGS
  ( input -- field-address )
    _O2CCI-FLAGS + ;

\ =====================================================================
\  Address-free immutable record
\ =====================================================================

0x4F32434C43464731 CONSTANT _O2CC-MAGIC-VALUE  \ "O2CLCFG1"

 0 CONSTANT _O2CC-MAGIC
 8 CONSTANT _O2CC-FLAGS
16 CONSTANT _O2CC-BINDING-U
24 CONSTANT _O2CC-CLIENT-ID-U
32 CONSTANT _O2CC-REDIRECT-U
40 CONSTANT _O2CC-SCOPE-U
48 CONSTANT _O2CC-AUTH-METHOD-U
56 CONSTANT _O2CC-AUTH-ALGORITHM-U
64 CONSTANT _O2CC-HEADER-SIZE

_O2CC-HEADER-SIZE CONSTANT _O2CC-BINDING-OFF
_O2CC-BINDING-OFF OAUTH2-CLIENT-CONFIG-BINDING-CAPACITY +
    CONSTANT _O2CC-CLIENT-ID-OFF
_O2CC-CLIENT-ID-OFF OAUTH2-CLIENT-CONFIG-CLIENT-ID-CAPACITY +
    CONSTANT _O2CC-REDIRECT-OFF
_O2CC-REDIRECT-OFF OAUTH2-CLIENT-CONFIG-REDIRECT-URI-CAPACITY +
    CONSTANT _O2CC-SCOPE-OFF
_O2CC-SCOPE-OFF OAUTH2-CLIENT-CONFIG-SCOPE-CAPACITY +
    CONSTANT _O2CC-AUTH-METHOD-OFF
_O2CC-AUTH-METHOD-OFF OAUTH2-CLIENT-CONFIG-AUTH-METHOD-CAPACITY +
    CONSTANT _O2CC-AUTH-ALGORITHM-OFF
_O2CC-AUTH-ALGORITHM-OFF
    OAUTH2-CLIENT-CONFIG-AUTH-ALGORITHM-CAPACITY +
    CONSTANT OAUTH2-CLIENT-CONFIG-SIZE

: _O2CC.MAGIC           ( config -- address ) _O2CC-MAGIC + ;
: _O2CC.FLAGS           ( config -- address ) _O2CC-FLAGS + ;
: _O2CC.BINDING-U       ( config -- address ) _O2CC-BINDING-U + ;
: _O2CC.CLIENT-ID-U     ( config -- address ) _O2CC-CLIENT-ID-U + ;
: _O2CC.REDIRECT-U      ( config -- address ) _O2CC-REDIRECT-U + ;
: _O2CC.SCOPE-U         ( config -- address ) _O2CC-SCOPE-U + ;
: _O2CC.AUTH-METHOD-U   ( config -- address ) _O2CC-AUTH-METHOD-U + ;
: _O2CC.AUTH-ALGORITHM-U
  ( config -- address )
    _O2CC-AUTH-ALGORITHM-U + ;

: _O2CC.BINDING         ( config -- address ) _O2CC-BINDING-OFF + ;
: _O2CC.CLIENT-ID       ( config -- address ) _O2CC-CLIENT-ID-OFF + ;
: _O2CC.REDIRECT        ( config -- address ) _O2CC-REDIRECT-OFF + ;
: _O2CC.SCOPE           ( config -- address ) _O2CC-SCOPE-OFF + ;
: _O2CC.AUTH-METHOD     ( config -- address )
    _O2CC-AUTH-METHOD-OFF + ;
: _O2CC.AUTH-ALGORITHM  ( config -- address )
    _O2CC-AUTH-ALGORITHM-OFF + ;

\ =====================================================================
\  Caller-memory admission
\ =====================================================================

: _O2CC-CALLER>STATUS  ( caller-status -- status )
    DUP CALLER-SPAN-S-OK = IF
        DROP OAUTH2-CLIENT-CONFIG-S-OK EXIT
    THEN
    DUP CALLER-SPAN-S-RANGE = IF
        DROP OAUTH2-CLIENT-CONFIG-S-RANGE EXIT
    THEN
    DUP CALLER-SPAN-S-PROTECTED = IF
        DROP OAUTH2-CLIENT-CONFIG-S-PROTECTED EXIT
    THEN
    DUP CALLER-SPAN-S-PLATFORM = IF
        DROP OAUTH2-CLIENT-CONFIG-S-PLATFORM EXIT
    THEN
    DROP OAUTH2-CLIENT-CONFIG-S-PLATFORM ;

: _O2CC-ADMIT-SPAN  ( address length -- status )
    CALLER-SPAN-STATUS _O2CC-CALLER>STATUS ;

: _O2CC-FIXED-STATUS  ( address length -- status )
    OVER 0= IF 2DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT THEN
    OVER 7 AND IF 2DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT THEN
    _O2CC-ADMIT-SPAN ;

: _O2CC-REQUIRED-LENGTH-STATUS
  ( length capacity -- status )
    OVER 1 < IF
        2DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT
    THEN
    U> IF
        OAUTH2-CLIENT-CONFIG-S-CAPACITY
    ELSE
        OAUTH2-CLIENT-CONFIG-S-OK
    THEN ;

: _O2CC-OPTIONAL-LENGTH-STATUS
  ( length capacity -- status )
    OVER 0< IF
        2DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT
    THEN
    U> IF
        OAUTH2-CLIENT-CONFIG-S-CAPACITY
    ELSE
        OAUTH2-CLIENT-CONFIG-S-OK
    THEN ;

: _O2CC-OPTIONAL-PAIR?  ( address length -- flag )
    DUP 0= IF
        SWAP 0= SWAP DROP EXIT
    THEN
    DROP 0<> ;

\ =====================================================================
\  Exact-value syntax
\ =====================================================================

: _O2CC-VSCHAR?  ( address length -- flag )
    BEGIN DUP WHILE
        OVER C@ 32 127 WITHIN 0= IF
            2DROP 0 EXIT
        THEN
        1- SWAP 1+ SWAP
    REPEAT
    2DROP -1 ;

: _O2CC-URI-CHAR?  ( address length -- flag )
    BEGIN DUP WHILE
        OVER C@ 33 127 WITHIN 0= IF
            2DROP 0 EXIT
        THEN
        1- SWAP 1+ SWAP
    REPEAT
    2DROP -1 ;

: _O2CC-SCOPE-TOKEN-CHAR?  ( character -- flag )
    DUP 33 = IF DROP -1 EXIT THEN
    DUP 35 92 WITHIN IF DROP -1 EXIT THEN
    93 127 WITHIN ;

: _O2CC-SCOPE?  ( address length -- flag )
    DUP 0= IF 2DROP -1 EXIT THEN
    OVER C@ BL = IF 2DROP 0 EXIT THEN
    2DUP + 1- C@ BL = IF 2DROP 0 EXIT THEN
    BEGIN DUP WHILE
        OVER C@ DUP BL = IF
            DROP
            DUP 1 <= IF 2DROP 0 EXIT THEN
            OVER 1+ C@ BL = IF 2DROP 0 EXIT THEN
        ELSE
            _O2CC-SCOPE-TOKEN-CHAR? 0= IF
                2DROP 0 EXIT
            THEN
        THEN
        1- SWAP 1+ SWAP
    REPEAT
    2DROP -1 ;

: _O2CC-BYTES=  ( first-a first-u second-a second-u -- flag )
    2SWAP COMPARE 0= ;

\ =====================================================================
\  Canonical record validation
\ =====================================================================

: _O2CC-ZERO?  ( address length -- flag )
    BEGIN DUP WHILE
        OVER C@ IF 2DROP 0 EXIT THEN
        1- SWAP 1+ SWAP
    REPEAT
    2DROP -1 ;

: _O2CC-CANONICAL-ARENA?  ( address used capacity -- flag )
    >R
    DUP >R
    +
    R> R> SWAP -
    _O2CC-ZERO? ;

: _O2CC-FLAGS?  ( flags -- flag )
    DUP 0< IF DROP 0 EXIT THEN
    _O2CC-FLAGS-KNOWN INVERT AND 0= ;

: _O2CC-LENGTHS?  ( config -- flag )
    DUP _O2CC.BINDING-U @
    OAUTH2-CLIENT-CONFIG-BINDING-CAPACITY
        _O2CC-REQUIRED-LENGTH-STATUS
        OAUTH2-CLIENT-CONFIG-S-OK <> IF DROP 0 EXIT THEN
    DUP _O2CC.CLIENT-ID-U @
    OAUTH2-CLIENT-CONFIG-CLIENT-ID-CAPACITY
        _O2CC-REQUIRED-LENGTH-STATUS
        OAUTH2-CLIENT-CONFIG-S-OK <> IF DROP 0 EXIT THEN
    DUP _O2CC.REDIRECT-U @
    OAUTH2-CLIENT-CONFIG-REDIRECT-URI-CAPACITY
        _O2CC-REQUIRED-LENGTH-STATUS
        OAUTH2-CLIENT-CONFIG-S-OK <> IF DROP 0 EXIT THEN
    DUP _O2CC.SCOPE-U @
    OAUTH2-CLIENT-CONFIG-SCOPE-CAPACITY
        _O2CC-OPTIONAL-LENGTH-STATUS
        OAUTH2-CLIENT-CONFIG-S-OK <> IF DROP 0 EXIT THEN
    DUP _O2CC.AUTH-METHOD-U @
    OAUTH2-CLIENT-CONFIG-AUTH-METHOD-CAPACITY
        _O2CC-REQUIRED-LENGTH-STATUS
        OAUTH2-CLIENT-CONFIG-S-OK <> IF DROP 0 EXIT THEN
    _O2CC.AUTH-ALGORITHM-U @
    OAUTH2-CLIENT-CONFIG-AUTH-ALGORITHM-CAPACITY
        _O2CC-OPTIONAL-LENGTH-STATUS
        OAUTH2-CLIENT-CONFIG-S-OK = ;

: _O2CC-CONTENT?  ( config -- flag )
    DUP _O2CC.CLIENT-ID OVER _O2CC.CLIENT-ID-U @
        _O2CC-VSCHAR? 0= IF DROP 0 EXIT THEN
    DUP _O2CC.REDIRECT OVER _O2CC.REDIRECT-U @
        _O2CC-URI-CHAR? 0= IF DROP 0 EXIT THEN
    DUP _O2CC.SCOPE OVER _O2CC.SCOPE-U @
        _O2CC-SCOPE? 0= IF DROP 0 EXIT THEN
    DUP _O2CC.AUTH-METHOD OVER _O2CC.AUTH-METHOD-U @
        _O2CC-URI-CHAR? 0= IF DROP 0 EXIT THEN
    DUP _O2CC.AUTH-ALGORITHM OVER _O2CC.AUTH-ALGORITHM-U @
        _O2CC-URI-CHAR? 0= IF DROP 0 EXIT THEN
    DUP _O2CC.AUTH-METHOD OVER _O2CC.AUTH-METHOD-U @
    S" none" _O2CC-BYTES= IF
        _O2CC.AUTH-ALGORITHM-U @ 0=
    ELSE
        DROP -1
    THEN ;

: _O2CC-PADDING?  ( config -- flag )
    DUP _O2CC.BINDING OVER _O2CC.BINDING-U @
    OAUTH2-CLIENT-CONFIG-BINDING-CAPACITY
        _O2CC-CANONICAL-ARENA? 0= IF DROP 0 EXIT THEN
    DUP _O2CC.CLIENT-ID OVER _O2CC.CLIENT-ID-U @
    OAUTH2-CLIENT-CONFIG-CLIENT-ID-CAPACITY
        _O2CC-CANONICAL-ARENA? 0= IF DROP 0 EXIT THEN
    DUP _O2CC.REDIRECT OVER _O2CC.REDIRECT-U @
    OAUTH2-CLIENT-CONFIG-REDIRECT-URI-CAPACITY
        _O2CC-CANONICAL-ARENA? 0= IF DROP 0 EXIT THEN
    DUP _O2CC.SCOPE OVER _O2CC.SCOPE-U @
    OAUTH2-CLIENT-CONFIG-SCOPE-CAPACITY
        _O2CC-CANONICAL-ARENA? 0= IF DROP 0 EXIT THEN
    DUP _O2CC.AUTH-METHOD OVER _O2CC.AUTH-METHOD-U @
    OAUTH2-CLIENT-CONFIG-AUTH-METHOD-CAPACITY
        _O2CC-CANONICAL-ARENA? 0= IF DROP 0 EXIT THEN
    DUP _O2CC.AUTH-ALGORITHM SWAP _O2CC.AUTH-ALGORITHM-U @
    OAUTH2-CLIENT-CONFIG-AUTH-ALGORITHM-CAPACITY
        _O2CC-CANONICAL-ARENA? ;

: _O2CC-SHAPE?  ( config -- flag )
    DUP _O2CC.MAGIC @ _O2CC-MAGIC-VALUE <> IF DROP 0 EXIT THEN
    DUP _O2CC.FLAGS @ _O2CC-FLAGS? 0= IF DROP 0 EXIT THEN
    DUP _O2CC-LENGTHS? 0= IF DROP 0 EXIT THEN
    DUP _O2CC-CONTENT? 0= IF DROP 0 EXIT THEN
    _O2CC-PADDING? ;

: _O2CC-OBJECT-STATUS  ( config -- status )
    DUP OAUTH2-CLIENT-CONFIG-SIZE _O2CC-FIXED-STATUS
    ?DUP IF NIP EXIT THEN
    _O2CC-SHAPE? IF
        OAUTH2-CLIENT-CONFIG-S-OK
    ELSE
        OAUTH2-CLIENT-CONFIG-S-INVALID
    THEN ;

: OAUTH2-CLIENT-CONFIG-VALID?  ( config -- flag )
    _O2CC-OBJECT-STATUS OAUTH2-CLIENT-CONFIG-S-OK = ;

\ =====================================================================
\  Input validation and construction
\ =====================================================================

: OAUTH2-CLIENT-CONFIG-INPUT-CLEAR  ( input -- status )
    DUP OAUTH2-CLIENT-CONFIG-INPUT-SIZE _O2CC-FIXED-STATUS
    ?DUP IF NIP EXIT THEN
    OAUTH2-CLIENT-CONFIG-INPUT-SIZE 0 FILL
    OAUTH2-CLIENT-CONFIG-S-OK ;

: _O2CC-REQUIRED-SOURCE-STATUS
  ( address length capacity -- status )
    >R
    DUP R> _O2CC-REQUIRED-LENGTH-STATUS ?DUP IF
        >R 2DROP R> EXIT
    THEN
    OVER 0= IF
        2DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT
    THEN
    _O2CC-ADMIT-SPAN ;

: _O2CC-OPTIONAL-SOURCE-STATUS
  ( address length capacity -- status )
    >R
    2DUP _O2CC-OPTIONAL-PAIR? 0= IF
        2DROP R> DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT
    THEN
    DUP R> _O2CC-OPTIONAL-LENGTH-STATUS ?DUP IF
        >R 2DROP R> EXIT
    THEN
    DUP 0= IF
        2DROP OAUTH2-CLIENT-CONFIG-S-OK EXIT
    THEN
    _O2CC-ADMIT-SPAN ;

: _O2CC-INPUT-SOURCES-STATUS  ( input -- status )
    DUP OAUTH2-CLIENT-CONFIG-I.BINDING-A @
    OVER OAUTH2-CLIENT-CONFIG-I.BINDING-U @
    OAUTH2-CLIENT-CONFIG-BINDING-CAPACITY
        _O2CC-REQUIRED-SOURCE-STATUS ?DUP IF NIP EXIT THEN
    DUP OAUTH2-CLIENT-CONFIG-I.CLIENT-ID-A @
    OVER OAUTH2-CLIENT-CONFIG-I.CLIENT-ID-U @
    OAUTH2-CLIENT-CONFIG-CLIENT-ID-CAPACITY
        _O2CC-REQUIRED-SOURCE-STATUS ?DUP IF NIP EXIT THEN
    DUP OAUTH2-CLIENT-CONFIG-I.REDIRECT-URI-A @
    OVER OAUTH2-CLIENT-CONFIG-I.REDIRECT-URI-U @
    OAUTH2-CLIENT-CONFIG-REDIRECT-URI-CAPACITY
        _O2CC-REQUIRED-SOURCE-STATUS ?DUP IF NIP EXIT THEN
    DUP OAUTH2-CLIENT-CONFIG-I.SCOPE-A @
    OVER OAUTH2-CLIENT-CONFIG-I.SCOPE-U @
    OAUTH2-CLIENT-CONFIG-SCOPE-CAPACITY
        _O2CC-OPTIONAL-SOURCE-STATUS ?DUP IF NIP EXIT THEN
    DUP OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-A @
    OVER OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-U @
    OAUTH2-CLIENT-CONFIG-AUTH-METHOD-CAPACITY
        _O2CC-REQUIRED-SOURCE-STATUS ?DUP IF NIP EXIT THEN
    DUP OAUTH2-CLIENT-CONFIG-I.AUTH-ALGORITHM-A @
    OVER OAUTH2-CLIENT-CONFIG-I.AUTH-ALGORITHM-U @
    OAUTH2-CLIENT-CONFIG-AUTH-ALGORITHM-CAPACITY
        _O2CC-OPTIONAL-SOURCE-STATUS ?DUP IF NIP EXIT THEN
    DROP OAUTH2-CLIENT-CONFIG-S-OK ;

: _O2CC-INPUT-CONTENT-STATUS  ( input -- status )
    DUP OAUTH2-CLIENT-CONFIG-I.FLAGS @ _O2CC-FLAGS? 0= IF
        DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT
    THEN
    DUP OAUTH2-CLIENT-CONFIG-I.CLIENT-ID-A @
    OVER OAUTH2-CLIENT-CONFIG-I.CLIENT-ID-U @
        _O2CC-VSCHAR? 0= IF
        DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT
    THEN
    DUP OAUTH2-CLIENT-CONFIG-I.REDIRECT-URI-A @
    OVER OAUTH2-CLIENT-CONFIG-I.REDIRECT-URI-U @
        _O2CC-URI-CHAR? 0= IF
        DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT
    THEN
    DUP OAUTH2-CLIENT-CONFIG-I.SCOPE-A @
    OVER OAUTH2-CLIENT-CONFIG-I.SCOPE-U @
        _O2CC-SCOPE? 0= IF
        DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT
    THEN
    DUP OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-A @
    OVER OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-U @
        _O2CC-URI-CHAR? 0= IF
        DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT
    THEN
    DUP OAUTH2-CLIENT-CONFIG-I.AUTH-ALGORITHM-A @
    OVER OAUTH2-CLIENT-CONFIG-I.AUTH-ALGORITHM-U @
        _O2CC-URI-CHAR? 0= IF
        DROP OAUTH2-CLIENT-CONFIG-S-INVALID EXIT
    THEN
    DUP OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-A @
    OVER OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-U @
    S" none" _O2CC-BYTES= IF
        OAUTH2-CLIENT-CONFIG-I.AUTH-ALGORITHM-U @
        IF OAUTH2-CLIENT-CONFIG-S-INVALID
        ELSE OAUTH2-CLIENT-CONFIG-S-OK THEN
    ELSE
        DROP OAUTH2-CLIENT-CONFIG-S-OK
    THEN ;

: _O2CC-INPUT-STATUS  ( input -- status )
    DUP OAUTH2-CLIENT-CONFIG-INPUT-SIZE _O2CC-FIXED-STATUS
    ?DUP IF NIP EXIT THEN
    _O2CC-INPUT-SOURCES-STATUS ;

: _O2CC-SOURCE-OVERLAP?
  ( address length config -- flag )
    >R
    DUP 0= IF 2DROP R> DROP 0 EXIT THEN
    R@ OAUTH2-CLIENT-CONFIG-SIZE MSPAN-OVERLAP?
    R> DROP ;

: _O2CC-INPUT-ALIASES-CONFIG?  ( input config -- flag )
    >R
    DUP OAUTH2-CLIENT-CONFIG-INPUT-SIZE
    R@ OAUTH2-CLIENT-CONFIG-SIZE MSPAN-OVERLAP? IF
        DROP R> DROP -1 EXIT
    THEN
    DUP OAUTH2-CLIENT-CONFIG-I.BINDING-A @
    OVER OAUTH2-CLIENT-CONFIG-I.BINDING-U @
    R@ _O2CC-SOURCE-OVERLAP? IF DROP R> DROP -1 EXIT THEN
    DUP OAUTH2-CLIENT-CONFIG-I.CLIENT-ID-A @
    OVER OAUTH2-CLIENT-CONFIG-I.CLIENT-ID-U @
    R@ _O2CC-SOURCE-OVERLAP? IF DROP R> DROP -1 EXIT THEN
    DUP OAUTH2-CLIENT-CONFIG-I.REDIRECT-URI-A @
    OVER OAUTH2-CLIENT-CONFIG-I.REDIRECT-URI-U @
    R@ _O2CC-SOURCE-OVERLAP? IF DROP R> DROP -1 EXIT THEN
    DUP OAUTH2-CLIENT-CONFIG-I.SCOPE-A @
    OVER OAUTH2-CLIENT-CONFIG-I.SCOPE-U @
    R@ _O2CC-SOURCE-OVERLAP? IF DROP R> DROP -1 EXIT THEN
    DUP OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-A @
    OVER OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-U @
    R@ _O2CC-SOURCE-OVERLAP? IF DROP R> DROP -1 EXIT THEN
    DUP OAUTH2-CLIENT-CONFIG-I.AUTH-ALGORITHM-A @
    OVER OAUTH2-CLIENT-CONFIG-I.AUTH-ALGORITHM-U @
    R@ _O2CC-SOURCE-OVERLAP?
    SWAP DROP R> DROP ;

: _O2CC-INIT-STATUS  ( input config -- status )
    DUP OAUTH2-CLIENT-CONFIG-SIZE _O2CC-FIXED-STATUS
    ?DUP IF >R 2DROP R> EXIT THEN
    OVER _O2CC-INPUT-STATUS ?DUP IF
        >R 2DROP R> EXIT
    THEN
    2DUP _O2CC-INPUT-ALIASES-CONFIG? IF
        2DROP OAUTH2-CLIENT-CONFIG-S-ALIAS EXIT
    THEN
    DUP OAUTH2-CLIENT-CONFIG-SIZE _O2CC-ZERO? 0= IF
        2DROP OAUTH2-CLIENT-CONFIG-S-STATE EXIT
    THEN
    OVER _O2CC-INPUT-CONTENT-STATUS ?DUP IF
        >R 2DROP R> EXIT
    THEN
    2DROP OAUTH2-CLIENT-CONFIG-S-OK ;

: _O2CC-COPY-REQUIRED
  ( source-address source-length destination length-field -- )
    >R
    OVER R@ !
    SWAP MOVE
    R> DROP ;

: _O2CC-COPY-OPTIONAL
  ( source-address source-length destination length-field -- )
    >R
    OVER R@ !
    OVER IF SWAP MOVE ELSE 2DROP DROP THEN
    R> DROP ;

: _O2CC-PUBLISH  ( input config -- )
    >R
    R@ OAUTH2-CLIENT-CONFIG-SIZE 0 FILL

    DUP OAUTH2-CLIENT-CONFIG-I.BINDING-A @
    OVER OAUTH2-CLIENT-CONFIG-I.BINDING-U @
    R@ _O2CC.BINDING R@ _O2CC.BINDING-U
        _O2CC-COPY-REQUIRED
    DUP OAUTH2-CLIENT-CONFIG-I.CLIENT-ID-A @
    OVER OAUTH2-CLIENT-CONFIG-I.CLIENT-ID-U @
    R@ _O2CC.CLIENT-ID R@ _O2CC.CLIENT-ID-U
        _O2CC-COPY-REQUIRED
    DUP OAUTH2-CLIENT-CONFIG-I.REDIRECT-URI-A @
    OVER OAUTH2-CLIENT-CONFIG-I.REDIRECT-URI-U @
    R@ _O2CC.REDIRECT R@ _O2CC.REDIRECT-U
        _O2CC-COPY-REQUIRED
    DUP OAUTH2-CLIENT-CONFIG-I.SCOPE-A @
    OVER OAUTH2-CLIENT-CONFIG-I.SCOPE-U @
    R@ _O2CC.SCOPE R@ _O2CC.SCOPE-U
        _O2CC-COPY-OPTIONAL
    DUP OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-A @
    OVER OAUTH2-CLIENT-CONFIG-I.AUTH-METHOD-U @
    R@ _O2CC.AUTH-METHOD R@ _O2CC.AUTH-METHOD-U
        _O2CC-COPY-REQUIRED
    DUP OAUTH2-CLIENT-CONFIG-I.AUTH-ALGORITHM-A @
    OVER OAUTH2-CLIENT-CONFIG-I.AUTH-ALGORITHM-U @
    R@ _O2CC.AUTH-ALGORITHM R@ _O2CC.AUTH-ALGORITHM-U
        _O2CC-COPY-OPTIONAL

    OAUTH2-CLIENT-CONFIG-I.FLAGS @ R@ _O2CC.FLAGS !
    _O2CC-MAGIC-VALUE R@ _O2CC.MAGIC !
    R> DROP ;

: OAUTH2-CLIENT-CONFIG-INIT  ( input config -- status )
    2DUP _O2CC-INIT-STATUS ?DUP IF
        >R 2DROP R> EXIT
    THEN
    _O2CC-PUBLISH
    OAUTH2-CLIENT-CONFIG-S-OK ;

: OAUTH2-CLIENT-CONFIG-WIPE  ( config -- status )
    DUP OAUTH2-CLIENT-CONFIG-SIZE _O2CC-FIXED-STATUS
    ?DUP IF NIP EXIT THEN
    OAUTH2-CLIENT-CONFIG-SIZE 0 FILL
    OAUTH2-CLIENT-CONFIG-S-OK ;

\ =====================================================================
\  Fail-closed read-only accessors
\ =====================================================================

: _O2CC-STRING-FAIL  ( config status -- address length status )
    >R DROP 0 0 R> ;

: OAUTH2-CLIENT-CONFIG-BINDING@
  ( config -- address length status )
    DUP _O2CC-OBJECT-STATUS ?DUP IF
        _O2CC-STRING-FAIL EXIT
    THEN
    DUP _O2CC.BINDING SWAP _O2CC.BINDING-U @
    OAUTH2-CLIENT-CONFIG-S-OK ;

: OAUTH2-CLIENT-CONFIG-CLIENT-ID@
  ( config -- address length status )
    DUP _O2CC-OBJECT-STATUS ?DUP IF
        _O2CC-STRING-FAIL EXIT
    THEN
    DUP _O2CC.CLIENT-ID SWAP _O2CC.CLIENT-ID-U @
    OAUTH2-CLIENT-CONFIG-S-OK ;

: OAUTH2-CLIENT-CONFIG-REDIRECT-URI@
  ( config -- address length status )
    DUP _O2CC-OBJECT-STATUS ?DUP IF
        _O2CC-STRING-FAIL EXIT
    THEN
    DUP _O2CC.REDIRECT SWAP _O2CC.REDIRECT-U @
    OAUTH2-CLIENT-CONFIG-S-OK ;

: OAUTH2-CLIENT-CONFIG-SCOPE@
  ( config -- address length status )
    DUP _O2CC-OBJECT-STATUS ?DUP IF
        _O2CC-STRING-FAIL EXIT
    THEN
    DUP _O2CC.SCOPE-U @ DUP 0= IF
        2DROP 0 0 OAUTH2-CLIENT-CONFIG-S-OK EXIT
    THEN
    >R _O2CC.SCOPE R>
    OAUTH2-CLIENT-CONFIG-S-OK ;

: OAUTH2-CLIENT-CONFIG-AUTH-METHOD@
  ( config -- address length status )
    DUP _O2CC-OBJECT-STATUS ?DUP IF
        _O2CC-STRING-FAIL EXIT
    THEN
    DUP _O2CC.AUTH-METHOD SWAP _O2CC.AUTH-METHOD-U @
    OAUTH2-CLIENT-CONFIG-S-OK ;

: OAUTH2-CLIENT-CONFIG-AUTH-ALGORITHM@
  ( config -- address length status )
    DUP _O2CC-OBJECT-STATUS ?DUP IF
        _O2CC-STRING-FAIL EXIT
    THEN
    DUP _O2CC.AUTH-ALGORITHM-U @ DUP 0= IF
        2DROP 0 0 OAUTH2-CLIENT-CONFIG-S-OK EXIT
    THEN
    >R _O2CC.AUTH-ALGORITHM R>
    OAUTH2-CLIENT-CONFIG-S-OK ;

: OAUTH2-CLIENT-CONFIG-FLAGS@
  ( config -- flags status )
    DUP _O2CC-OBJECT-STATUS ?DUP IF
        >R DROP 0 R> EXIT
    THEN
    _O2CC.FLAGS @ OAUTH2-CLIENT-CONFIG-S-OK ;

: OAUTH2-CLIENT-CONFIG-APPLICATION-TYPE@
  ( config -- application-type status )
    OAUTH2-CLIENT-CONFIG-FLAGS@
    DUP IF NIP 0 SWAP EXIT THEN
    DROP
    OAUTH2-CLIENT-CONFIG-F-NATIVE AND IF
        OAUTH2-CLIENT-CONFIG-APPLICATION-NATIVE
    ELSE
        OAUTH2-CLIENT-CONFIG-APPLICATION-WEB
    THEN
    OAUTH2-CLIENT-CONFIG-S-OK ;

: OAUTH2-CLIENT-CONFIG-REFRESH?
  ( config -- flag status )
    OAUTH2-CLIENT-CONFIG-FLAGS@
    DUP IF NIP 0 SWAP EXIT THEN
    DROP
    OAUTH2-CLIENT-CONFIG-F-REFRESH AND 0<>
    OAUTH2-CLIENT-CONFIG-S-OK ;

: OAUTH2-CLIENT-CONFIG-DPOP-BOUND?
  ( config -- flag status )
    OAUTH2-CLIENT-CONFIG-FLAGS@
    DUP IF NIP 0 SWAP EXIT THEN
    DROP
    OAUTH2-CLIENT-CONFIG-F-DPOP-BOUND AND 0<>
    OAUTH2-CLIENT-CONFIG-S-OK ;

\ =====================================================================
\  Compile-time geometry assertions
\ =====================================================================

OAUTH2-CLIENT-CONFIG-SIZE 11072 <> [IF]
    ." OAuth client config geometry mismatch" CR ABORT
[THEN]

OAUTH2-CLIENT-CONFIG-INPUT-SIZE 104 <> [IF]
    ." OAuth client config input geometry mismatch" CR ABORT
[THEN]
