\ =====================================================================
\  qualified-locator.f - Closed durable semantic resource locators
\ =====================================================================
\  QLOC is pointer-free durable identity/evidence.  It deliberately keeps
\  the embedded RREF at revision zero: positive RREF revisions come from a
\  live component and are not durable domain-history evidence unless an
\  owner separately qualifies that relationship.
\
\  Exact-domain-state locators carry a positive domain revision, one typed
\  SHA3-256 digest, and a projection-contract ID.  They never contain an
\  LBIND, component handle, acquisition token, path, capability, or grant.
\ =====================================================================

PROVIDED akashic-interop-qualified-locator

REQUIRE schema-common.f
REQUIRE ../math/sha3.f
REQUIRE ../concurrency/guard.f

0 CONSTANT QLOC-S-OK
1 CONSTANT QLOC-S-INVALID
2 CONSTANT QLOC-S-CAPACITY
3 CONSTANT QLOC-S-TYPE
4 CONSTANT QLOC-S-NOMEM

1 CONSTANT QLOC-M-IDENTITY
2 CONSTANT QLOC-M-EXACT-DOMAIN

0 CONSTANT QLOC-DK-NONE
1 CONSTANT QLOC-DK-SEMANTIC-STATE
2 CONSTANT QLOC-DK-PROJECTION-CONTENT

64 CONSTANT QLOC-OWNER-MAX
64 CONSTANT QLOC-PROJECTION-MAX

0x434F4C51 CONSTANT QLOC-MAGIC       \ "QLOC"
1          CONSTANT QLOC-ABI-VERSION

  0 CONSTANT _QL-MAGIC
  8 CONSTANT _QL-ABI
 16 CONSTANT _QL-SIZE
 24 CONSTANT _QL-MODE
 32 CONSTANT _QL-DIGEST-KIND
 40 CONSTANT _QL-FLAGS
 48 CONSTANT _QL-OWNER-U
 56 CONSTANT _QL-OWNER                  \ 64 bytes
120 CONSTANT _QL-REF                    \ RREF-SIZE bytes
200 CONSTANT _QL-DOMAIN-REVISION
208 CONSTANT _QL-STATE-DIGEST           \ SHA3-256-LEN bytes
240 CONSTANT _QL-PROJECTION-U
248 CONSTANT _QL-PROJECTION             \ 64 bytes
312 CONSTANT _QL-RESERVED
320 CONSTANT QLOC-SIZE

: QLOC.MAGIC            ( locator -- a ) _QL-MAGIC + ;
: QLOC.ABI              ( locator -- a ) _QL-ABI + ;
: QLOC.SIZE             ( locator -- a ) _QL-SIZE + ;
: QLOC.MODE             ( locator -- a ) _QL-MODE + ;
: QLOC.DIGEST-KIND      ( locator -- a ) _QL-DIGEST-KIND + ;
: QLOC.FLAGS            ( locator -- a ) _QL-FLAGS + ;
: QLOC.OWNER-U          ( locator -- a ) _QL-OWNER-U + ;
: QLOC.OWNER            ( locator -- a ) _QL-OWNER + ;
: QLOC.REF              ( locator -- ref ) _QL-REF + ;
: QLOC.DOMAIN-REVISION  ( locator -- a ) _QL-DOMAIN-REVISION + ;
: QLOC.STATE-DIGEST     ( locator -- digest ) _QL-STATE-DIGEST + ;
: QLOC.PROJECTION-U     ( locator -- a ) _QL-PROJECTION-U + ;
: QLOC.PROJECTION       ( locator -- a ) _QL-PROJECTION + ;

: QLOC-OWNER$  ( locator -- addr len )
    DUP QLOC.OWNER SWAP QLOC.OWNER-U @ ;

: QLOC-PROJECTION$  ( locator -- addr len )
    DUP QLOC.PROJECTION SWAP QLOC.PROJECTION-U @ ;

: QLOC-INIT  ( locator -- )
    DUP QLOC-SIZE 0 FILL
    QLOC-MAGIC OVER QLOC.MAGIC !
    QLOC-ABI-VERSION OVER QLOC.ABI !
    QLOC-SIZE SWAP QLOC.SIZE ! ;

VARIABLE _QLZ-A
VARIABLE _QLZ-U
VARIABLE _QLZ-C

: _QLOC-ZERO?  ( addr len -- flag )
    _QLZ-U ! _QLZ-A !
    _QLZ-U @ 0 ?DO
        _QLZ-A @ I + C@ IF 0 UNLOOP EXIT THEN
    LOOP
    -1 ;

: _QLOC-TAIL-ZERO?  ( addr used capacity -- flag )
    _QLZ-C ! _QLZ-U ! _QLZ-A !
    _QLZ-A @ _QLZ-U @ + _QLZ-C @ _QLZ-U @ - _QLOC-ZERO? ;

: _QLOC-TEXT-VALID?  ( addr len capacity -- flag )
    _QLZ-C ! _QLZ-U ! _QLZ-A !
    _QLZ-A @ 0= IF 0 EXIT THEN
    _QLZ-U @ 1 < _QLZ-U @ _QLZ-C @ > OR IF 0 EXIT THEN
    _QLZ-A @ _QLZ-U @ UTF8-VALID? 0= IF 0 EXIT THEN
    _QLZ-A @ _QLZ-U @ _QLZ-C @ _QLOC-TAIL-ZERO? ;

VARIABLE _QLV-L
VARIABLE _QLV-M
VARIABLE _QLV-DK

: QLOC-VALID?  ( locator -- flag )
    DUP 0= IF DROP 0 EXIT THEN _QLV-L !
    _QLV-L @ QLOC.MAGIC @ QLOC-MAGIC <> IF 0 EXIT THEN
    _QLV-L @ QLOC.ABI @ QLOC-ABI-VERSION <> IF 0 EXIT THEN
    _QLV-L @ QLOC.SIZE @ QLOC-SIZE <> IF 0 EXIT THEN
    _QLV-L @ QLOC.FLAGS @ IF 0 EXIT THEN
    _QLV-L @ _QL-RESERVED + @ IF 0 EXIT THEN
    _QLV-L @ QLOC-OWNER$ QLOC-OWNER-MAX _QLOC-TEXT-VALID? 0= IF
        0 EXIT
    THEN
    _QLV-L @ QLOC.REF RREF-VALID? 0= IF 0 EXIT THEN
    _QLV-L @ QLOC.REF RREF.SIZE @ RREF-SIZE <> IF 0 EXIT THEN
    _QLV-L @ QLOC.REF 72 + @ IF 0 EXIT THEN
    _QLV-L @ QLOC.REF RREF.REVISION @ IF 0 EXIT THEN
    _QLV-L @ QLOC.MODE @ DUP _QLV-M !
    DUP QLOC-M-IDENTITY = SWAP QLOC-M-EXACT-DOMAIN = OR 0= IF
        0 EXIT
    THEN
    _QLV-L @ QLOC.DIGEST-KIND @ _QLV-DK !
    _QLV-M @ QLOC-M-IDENTITY = IF
        _QLV-DK @ QLOC-DK-NONE <> IF 0 EXIT THEN
        _QLV-L @ QLOC.DOMAIN-REVISION @ IF 0 EXIT THEN
        _QLV-L @ QLOC.STATE-DIGEST SHA3-256-LEN _QLOC-ZERO? 0= IF
            0 EXIT
        THEN
        _QLV-L @ QLOC.PROJECTION-U @ IF 0 EXIT THEN
        _QLV-L @ QLOC.PROJECTION QLOC-PROJECTION-MAX _QLOC-ZERO?
        EXIT
    THEN
    _QLV-DK @ QLOC-DK-SEMANTIC-STATE =
    _QLV-DK @ QLOC-DK-PROJECTION-CONTENT = OR 0= IF 0 EXIT THEN
    _QLV-L @ QLOC.DOMAIN-REVISION @ 0> 0= IF 0 EXIT THEN
    _QLV-L @ QLOC-PROJECTION$ QLOC-PROJECTION-MAX
        _QLOC-TEXT-VALID? ;

VARIABLE _QLB-OA
VARIABLE _QLB-OU
VARIABLE _QLB-R
VARIABLE _QLB-L

: _QLOC-BEGIN  ( owner-a owner-u reference locator -- status )
    _QLB-L ! _QLB-R ! _QLB-OU ! _QLB-OA !
    _QLB-L @ 0= IF QLOC-S-INVALID EXIT THEN
    _QLB-L @ QLOC-INIT
    _QLB-R @ RREF-VALID? 0= IF QLOC-S-INVALID EXIT THEN
    _QLB-R @ RREF.REVISION @ IF QLOC-S-INVALID EXIT THEN
    _QLB-OA @ 0= _QLB-OU @ 1 < OR IF QLOC-S-INVALID EXIT THEN
    _QLB-OU @ QLOC-OWNER-MAX > IF QLOC-S-CAPACITY EXIT THEN
    _QLB-OA @ _QLB-OU @ UTF8-VALID? 0= IF QLOC-S-INVALID EXIT THEN
    _QLB-OU @ _QLB-L @ QLOC.OWNER-U !
    _QLB-OA @ _QLB-L @ QLOC.OWNER _QLB-OU @ CMOVE
    _QLB-R @ _QLB-L @ QLOC.REF RREF-COPY RREF-S-OK <> IF
        QLOC-S-INVALID EXIT
    THEN
    QLOC-S-OK ;

: QLOC-IDENTITY!  ( owner-a owner-u reference locator -- status )
    _QLB-L ! _QLB-R ! _QLB-OU ! _QLB-OA !
    _QLB-OA @ _QLB-OU @ _QLB-R @ _QLB-L @ _QLOC-BEGIN
        ?DUP IF EXIT THEN
    QLOC-M-IDENTITY _QLB-L @ QLOC.MODE !
    _QLB-L @ QLOC-VALID? IF QLOC-S-OK ELSE QLOC-S-INVALID THEN ;

VARIABLE _QLE-OA
VARIABLE _QLE-OU
VARIABLE _QLE-R
VARIABLE _QLE-REV
VARIABLE _QLE-DIGEST
VARIABLE _QLE-DK
VARIABLE _QLE-PA
VARIABLE _QLE-PU
VARIABLE _QLE-L

: QLOC-EXACT!  ( oa ou ref rev digest kind pa pu locator -- status )
    _QLE-L ! _QLE-PU ! _QLE-PA ! _QLE-DK ! _QLE-DIGEST !
    _QLE-REV ! _QLE-R ! _QLE-OU ! _QLE-OA !
    _QLE-OA @ _QLE-OU @ _QLE-R @ _QLE-L @ _QLOC-BEGIN ?DUP IF EXIT THEN
    _QLE-REV @ 0> 0= _QLE-DIGEST @ 0= OR IF QLOC-S-INVALID EXIT THEN
    _QLE-DK @ QLOC-DK-SEMANTIC-STATE =
    _QLE-DK @ QLOC-DK-PROJECTION-CONTENT = OR 0= IF
        QLOC-S-INVALID EXIT
    THEN
    _QLE-PA @ 0= _QLE-PU @ 1 < OR IF QLOC-S-INVALID EXIT THEN
    _QLE-PU @ QLOC-PROJECTION-MAX > IF QLOC-S-CAPACITY EXIT THEN
    _QLE-PA @ _QLE-PU @ UTF8-VALID? 0= IF QLOC-S-INVALID EXIT THEN
    QLOC-M-EXACT-DOMAIN _QLE-L @ QLOC.MODE !
    _QLE-DK @ _QLE-L @ QLOC.DIGEST-KIND !
    _QLE-REV @ _QLE-L @ QLOC.DOMAIN-REVISION !
    _QLE-DIGEST @ _QLE-L @ QLOC.STATE-DIGEST SHA3-256-LEN CMOVE
    _QLE-PU @ _QLE-L @ QLOC.PROJECTION-U !
    _QLE-PA @ _QLE-L @ QLOC.PROJECTION _QLE-PU @ CMOVE
    _QLE-L @ QLOC-VALID? IF QLOC-S-OK ELSE QLOC-S-INVALID THEN ;

: QLOC-COPY  ( source destination -- status )
    DUP 0= IF 2DROP QLOC-S-INVALID EXIT THEN
    OVER QLOC-VALID? 0= IF NIP QLOC-INIT QLOC-S-INVALID EXIT THEN
    2DUP = IF 2DROP QLOC-S-OK EXIT THEN
    QLOC-SIZE MOVE QLOC-S-OK ;

: QLOC=  ( a b -- flag )
    DUP QLOC-VALID? 0= IF 2DROP 0 EXIT THEN
    OVER QLOC-VALID? 0= IF 2DROP 0 EXIT THEN
    SWAP QLOC-SIZE ROT QLOC-SIZE STR-STR= ;

\ =====================================================================
\  Closed interoperability value representation
\ =====================================================================

CREATE _QLS-OWNER CS-SIZE ALLOT
CREATE _QLS-RESOURCE CS-SIZE ALLOT
CREATE _QLS-MODE CS-SIZE ALLOT
CREATE _QLS-REVISION CS-SIZE ALLOT
CREATE _QLS-DIGEST-KIND CS-SIZE ALLOT
CREATE _QLS-DIGEST CS-SIZE ALLOT
CREATE _QLS-PROJECTION CS-SIZE ALLOT
CREATE _QLS-FIELDS 7 CS-FIELD-SIZE * ALLOT
CREATE QLOC-VALUE-SCHEMA CS-SIZE ALLOT

VARIABLE _QLSF-A
VARIABLE _QLSF-U
VARIABLE _QLSF-S
VARIABLE _QLSF-I

: _QLOC-SCHEMA-FIELD!  ( key-a key-u schema index -- )
    _QLSF-I ! _QLSF-S ! _QLSF-U ! _QLSF-A !
    _QLS-FIELDS _QLSF-I @ CS-FIELD-SIZE * + DUP CS-FIELD-SIZE 0 FILL
    _QLSF-A @ OVER CSF.KEY-A !
    _QLSF-U @ OVER CSF.KEY-U !
    _QLSF-S @ OVER CSF.SCHEMA !
    CSF-F-REQUIRED SWAP CSF.FLAGS ! ;

: _QLOC-SCHEMA-SETUP  ( -- )
    QLOC-OWNER-MAX _QLS-OWNER CSC-UTF8!
    _QLS-RESOURCE CSC-SEMANTIC-RREF!
    18 _QLS-MODE CSC-UTF8!
    _QLS-REVISION CSC-NONNEG-INT!
    18 _QLS-DIGEST-KIND CSC-UTF8!
    _QLS-DIGEST CS-INIT CV-T-BYTES _QLS-DIGEST CS-ALLOW!
    SHA3-256-LEN _QLS-DIGEST CS-MAX-LEN!
    QLOC-PROJECTION-MAX _QLS-PROJECTION CSC-UTF8!
    S" owner" _QLS-OWNER 0 _QLOC-SCHEMA-FIELD!
    S" resource" _QLS-RESOURCE 1 _QLOC-SCHEMA-FIELD!
    S" mode" _QLS-MODE 2 _QLOC-SCHEMA-FIELD!
    S" domain_revision" _QLS-REVISION 3 _QLOC-SCHEMA-FIELD!
    S" digest_kind" _QLS-DIGEST-KIND 4 _QLOC-SCHEMA-FIELD!
    S" state_digest" _QLS-DIGEST 5 _QLOC-SCHEMA-FIELD!
    S" projection" _QLS-PROJECTION 6 _QLOC-SCHEMA-FIELD!
    QLOC-VALUE-SCHEMA CS-INIT
    CV-T-MAP QLOC-VALUE-SCHEMA CS-ALLOW!
    7 QLOC-VALUE-SCHEMA CS-MAX-LEN!
    _QLS-FIELDS QLOC-VALUE-SCHEMA CS.FIELDS !
    7 QLOC-VALUE-SCHEMA CS.FIELD-N ! ;

_QLOC-SCHEMA-SETUP

VARIABLE _QLW-L
VARIABLE _QLW-V
VARIABLE _QLW-C
VARIABLE _QLW-S

: _QLOC-WRITE-SLOT  ( key-a key-u index -- child status )
    _QLW-V @ CV-MAP-SLOT! DUP IF
        NIP
    ELSE
        DROP _QLW-C ! 0
    THEN ;

: _QLOC-WRITE-FAIL  ( -- status )
    _QLW-V @ CV-FREE QLOC-S-NOMEM ;

: QLOC-VALUE!  ( locator value -- status )
    _QLW-V ! _QLW-L !
    _QLW-V @ 0= _QLW-L @ QLOC-VALID? 0= OR IF QLOC-S-INVALID EXIT THEN
    7 _QLW-V @ CV-MAP! ?DUP IF DROP QLOC-S-NOMEM EXIT THEN
    S" owner" 0 _QLOC-WRITE-SLOT IF _QLOC-WRITE-FAIL EXIT THEN
    _QLW-L @ QLOC-OWNER$ _QLW-C @ CV-STRING! IF _QLOC-WRITE-FAIL EXIT THEN
    S" resource" 1 _QLOC-WRITE-SLOT IF _QLOC-WRITE-FAIL EXIT THEN
    _QLW-L @ QLOC.REF _QLW-C @ IRES-RREF! IRES-S-OK <> IF
        _QLOC-WRITE-FAIL EXIT
    THEN
    S" mode" 2 _QLOC-WRITE-SLOT IF _QLOC-WRITE-FAIL EXIT THEN
    _QLW-L @ QLOC.MODE @ QLOC-M-IDENTITY = IF
        S" identity"
    ELSE
        S" exact-domain-state"
    THEN _QLW-C @ CV-STRING! IF _QLOC-WRITE-FAIL EXIT THEN
    S" domain_revision" 3 _QLOC-WRITE-SLOT IF _QLOC-WRITE-FAIL EXIT THEN
    _QLW-L @ QLOC.DOMAIN-REVISION @ _QLW-C @ CV-INT!
    S" digest_kind" 4 _QLOC-WRITE-SLOT IF _QLOC-WRITE-FAIL EXIT THEN
    _QLW-L @ QLOC.DIGEST-KIND @ CASE
        QLOC-DK-NONE OF S" none" ENDOF
        QLOC-DK-SEMANTIC-STATE OF S" semantic-state" ENDOF
        QLOC-DK-PROJECTION-CONTENT OF S" projection-content" ENDOF
    ENDCASE
    _QLW-C @ CV-STRING! IF _QLOC-WRITE-FAIL EXIT THEN
    S" state_digest" 5 _QLOC-WRITE-SLOT IF _QLOC-WRITE-FAIL EXIT THEN
    _QLW-L @ QLOC.STATE-DIGEST
    _QLW-L @ QLOC.MODE @ QLOC-M-IDENTITY = IF 0 ELSE SHA3-256-LEN THEN
    _QLW-C @ CV-BYTES! IF _QLOC-WRITE-FAIL EXIT THEN
    S" projection" 6 _QLOC-WRITE-SLOT IF _QLOC-WRITE-FAIL EXIT THEN
    _QLW-L @ QLOC-PROJECTION$ _QLW-C @ CV-STRING! IF
        _QLOC-WRITE-FAIL EXIT
    THEN
    QLOC-S-OK ;

CREATE _QLR-REF RREF-SIZE ALLOT
VARIABLE _QLR-V
VARIABLE _QLR-L
VARIABLE _QLR-OWNER
VARIABLE _QLR-RESOURCE
VARIABLE _QLR-MODE
VARIABLE _QLR-REV
VARIABLE _QLR-DK
VARIABLE _QLR-DIGEST
VARIABLE _QLR-PROJECTION
VARIABLE _QLR-OA
VARIABLE _QLR-OU
VARIABLE _QLR-MA
VARIABLE _QLR-MU
VARIABLE _QLR-PA
VARIABLE _QLR-PU

: _QLOC-READ-FIELD  ( key-a key-u -- value | 0 )
    _QLR-V @ CV-MAP-FIND ;

: _QLOC-TEXT-VALUE$  ( value -- addr len flag )
    DUP 0= IF DROP 0 0 0 EXIT THEN
    DUP CV-TYPE@ CV-T-STRING <> IF DROP 0 0 0 EXIT THEN
    DUP CV-DATA@ SWAP CV-LEN@ -1 ;

: _QLOC-DIGEST-KIND@  ( value -- kind flag )
    _QLOC-TEXT-VALUE$ 0= IF 2DROP 0 0 EXIT THEN
    2DUP S" none" STR-STR= IF 2DROP QLOC-DK-NONE -1 EXIT THEN
    2DUP S" semantic-state" STR-STR= IF
        2DROP QLOC-DK-SEMANTIC-STATE -1 EXIT
    THEN
    S" projection-content" STR-STR= IF
        QLOC-DK-PROJECTION-CONTENT -1
    ELSE
        0 0
    THEN ;

: QLOC-VALUE@  ( value locator -- status )
    _QLR-L ! _QLR-V !
    _QLR-L @ 0= IF QLOC-S-INVALID EXIT THEN
    _QLR-L @ QLOC-INIT
    _QLR-V @ QLOC-VALUE-SCHEMA CS-VALIDATE-DEEP IF QLOC-S-TYPE EXIT THEN
    S" owner" _QLOC-READ-FIELD DUP _QLR-OWNER ! 0= IF QLOC-S-TYPE EXIT THEN
    S" resource" _QLOC-READ-FIELD DUP _QLR-RESOURCE ! 0= IF QLOC-S-TYPE EXIT THEN
    S" mode" _QLOC-READ-FIELD DUP _QLR-MODE ! 0= IF QLOC-S-TYPE EXIT THEN
    S" domain_revision" _QLOC-READ-FIELD DUP _QLR-REV ! 0= IF QLOC-S-TYPE EXIT THEN
    S" digest_kind" _QLOC-READ-FIELD DUP _QLR-DK ! 0= IF QLOC-S-TYPE EXIT THEN
    S" state_digest" _QLOC-READ-FIELD DUP _QLR-DIGEST ! 0= IF QLOC-S-TYPE EXIT THEN
    S" projection" _QLOC-READ-FIELD DUP _QLR-PROJECTION ! 0= IF QLOC-S-TYPE EXIT THEN
    _QLR-RESOURCE @ _QLR-REF IRES-RREF@ IRES-S-OK <> IF QLOC-S-TYPE EXIT THEN
    _QLR-REF RREF.REVISION @ IF QLOC-S-INVALID EXIT THEN
    _QLR-REV @ CV-TYPE@ CV-T-INT <> IF QLOC-S-TYPE EXIT THEN
    _QLR-DIGEST @ CV-TYPE@ CV-T-BYTES <> IF QLOC-S-TYPE EXIT THEN
    _QLR-DK @ _QLOC-DIGEST-KIND@ 0= IF DROP QLOC-S-INVALID EXIT THEN _QLR-DK !
    _QLR-OWNER @ _QLOC-TEXT-VALUE$ 0= IF 2DROP QLOC-S-TYPE EXIT THEN
    _QLR-OU ! _QLR-OA !
    _QLR-MODE @ _QLOC-TEXT-VALUE$ 0= IF 2DROP QLOC-S-TYPE EXIT THEN
    _QLR-MU ! _QLR-MA !
    _QLR-PROJECTION @ _QLOC-TEXT-VALUE$ 0= IF 2DROP QLOC-S-TYPE EXIT THEN
    _QLR-PU ! _QLR-PA !
    _QLR-MA @ _QLR-MU @ S" identity" STR-STR= IF
        _QLR-DK @ QLOC-DK-NONE <> IF QLOC-S-INVALID EXIT THEN
        _QLR-DIGEST @ CV-LEN@ IF QLOC-S-INVALID EXIT THEN
        _QLR-REV @ CV-DATA@ IF QLOC-S-INVALID EXIT THEN
        _QLR-PU @ IF QLOC-S-INVALID EXIT THEN
        _QLR-OA @ _QLR-OU @ _QLR-REF _QLR-L @ QLOC-IDENTITY! EXIT
    THEN
    _QLR-MA @ _QLR-MU @ S" exact-domain-state" STR-STR= 0= IF
        QLOC-S-INVALID EXIT
    THEN
    _QLR-DIGEST @ CV-LEN@ SHA3-256-LEN <> IF QLOC-S-INVALID EXIT THEN
    _QLR-OA @ _QLR-OU @ _QLR-REF _QLR-REV @ CV-DATA@
    _QLR-DIGEST @ CV-DATA@ _QLR-DK @
    _QLR-PA @ _QLR-PU @ _QLR-L @ QLOC-EXACT! ;

\ Public words share module scratch; recursive guarding preserves nested
\ value/RREF helpers without exposing a caller-held lock.
' QLOC-INIT       CONSTANT _QLOC-INIT-XT
' QLOC-VALID?     CONSTANT _QLOC-VALID-XT
' QLOC-IDENTITY!  CONSTANT _QLOC-IDENTITY-XT
' QLOC-EXACT!     CONSTANT _QLOC-EXACT-XT
' QLOC-COPY       CONSTANT _QLOC-COPY-XT
' QLOC=           CONSTANT _QLOC-EQUAL-XT
' QLOC-VALUE!     CONSTANT _QLOC-VALUE-STORE-XT
' QLOC-VALUE@     CONSTANT _QLOC-VALUE-FETCH-XT

GUARD _QLOC-GUARD

: QLOC-INIT       ( locator -- )
    _QLOC-INIT-XT _QLOC-GUARD WITH-GUARD ;
: QLOC-VALID?     ( locator -- flag )
    _QLOC-VALID-XT _QLOC-GUARD WITH-GUARD ;
: QLOC-IDENTITY!  ( owner-a owner-u reference locator -- status )
    _QLOC-IDENTITY-XT _QLOC-GUARD WITH-GUARD ;
: QLOC-EXACT!     ( oa ou ref rev digest kind pa pu locator -- status )
    _QLOC-EXACT-XT _QLOC-GUARD WITH-GUARD ;
: QLOC-COPY       ( source destination -- status )
    _QLOC-COPY-XT _QLOC-GUARD WITH-GUARD ;
: QLOC=           ( a b -- flag )
    _QLOC-EQUAL-XT _QLOC-GUARD WITH-GUARD ;
: QLOC-VALUE!     ( locator value -- status )
    _QLOC-VALUE-STORE-XT _QLOC-GUARD WITH-GUARD ;
: QLOC-VALUE@     ( value locator -- status )
    _QLOC-VALUE-FETCH-XT _QLOC-GUARD WITH-GUARD ;
