\ =====================================================================
\  resource-client.f - Activation-local typed common-resource client
\ =====================================================================
\  Descriptor discovery caches no authority.  Every operation is stamped
\  from an LBIND and dispatched through the ordinary request bus, where
\  policy/approval/authority is enforced.  Advanced callers may PREPARE,
\  add a reviewed invocation handle/mandate, then call the typed DISPATCH.
\ =====================================================================

PROVIDED akashic-interop-rclient

REQUIRE resource-contract.f
REQUIRE resource-acquisition.f

100 CONSTANT RCLI-S-INVALID
101 CONSTANT RCLI-S-NO-DESCRIBE
102 CONSTANT RCLI-S-NO-SNAPSHOT
103 CONSTANT RCLI-S-READONLY
104 CONSTANT RCLI-S-RESULT-TYPE
105 CONSTANT RCLI-S-RESULT-MISMATCH
106 CONSTANT RCLI-S-RELEASE
107 CONSTANT RCLI-S-STALE

1 CONSTANT RCLI-F-REPLACE

0x494C4352 CONSTANT RCLI-MAGIC       \ "RCLI"
1          CONSTANT RCLI-ABI-VERSION

  0 CONSTANT _RCI-MAGIC
  8 CONSTANT _RCI-ABI
 16 CONSTANT _RCI-SIZE
 24 CONSTANT _RCI-FLAGS
 32 CONSTANT _RCI-CONTEXT
 40 CONSTANT _RCI-BUS
 48 CONSTANT _RCI-ACQUISITION
 56 CONSTANT _RCI-BIND               \ LBIND-SIZE bytes
208 CONSTANT _RCI-OWNER
216 CONSTANT _RCI-DESCRIBE
224 CONSTANT _RCI-SNAPSHOT
232 CONSTANT _RCI-REPLACE
240 CONSTANT _RCI-RESERVED
248 CONSTANT RCLI-SIZE

: RCLI.MAGIC       ( client -- a ) _RCI-MAGIC + ;
: RCLI.ABI         ( client -- a ) _RCI-ABI + ;
: RCLI.SIZE        ( client -- a ) _RCI-SIZE + ;
: RCLI.FLAGS       ( client -- a ) _RCI-FLAGS + ;
: RCLI.CONTEXT     ( client -- a ) _RCI-CONTEXT + ;
: RCLI.BUS         ( client -- a ) _RCI-BUS + ;
: RCLI.ACQUISITION ( client -- a ) _RCI-ACQUISITION + ;
: RCLI.BIND        ( client -- binding ) _RCI-BIND + ;
: RCLI.OWNER       ( client -- a ) _RCI-OWNER + ;
: RCLI.DESCRIBE    ( client -- a ) _RCI-DESCRIBE + ;
: RCLI.SNAPSHOT    ( client -- a ) _RCI-SNAPSHOT + ;
: RCLI.REPLACE     ( client -- a ) _RCI-REPLACE + ;

: RCLI-CLEAR  ( client -- )
    DUP RCLI-SIZE 0 FILL
    RCLI-MAGIC OVER RCLI.MAGIC !
    RCLI-ABI-VERSION OVER RCLI.ABI !
    RCLI-SIZE OVER RCLI.SIZE !
    RCLI.BIND LBIND-INIT ;

: RCLI-REPLACE?  ( client -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    RCLI.FLAGS @ RCLI-F-REPLACE AND 0<> ;

VARIABLE _RCIX-CAP
VARIABLE _RCIX-KIND
VARIABLE _RCIX-EFFECTS
VARIABLE _RCIX-IN
VARIABLE _RCIX-OUT

: _RCLI-CAP-EXACT?  ( cap kind effects in-schema out-schema -- flag )
    _RCIX-OUT ! _RCIX-IN ! _RCIX-EFFECTS ! _RCIX-KIND ! _RCIX-CAP !
    _RCIX-CAP @ CAP-DESC-VALID? 0= IF 0 EXIT THEN
    _RCIX-CAP @ CAP.KIND @ _RCIX-KIND @ =
    _RCIX-CAP @ CAP.EFFECTS @ _RCIX-EFFECTS @ = AND
    _RCIX-CAP @ CAP.IN-SCHEMA @ _RCIX-IN @ = AND
    _RCIX-CAP @ CAP.OUT-SCHEMA @ _RCIX-OUT @ = AND ;

VARIABLE _RCIV-C
VARIABLE _RCIV-R
VARIABLE _RCIV-I
VARIABLE _RCIV-D

: RCLI-VALID?  ( client -- flag )
    DUP 0= IF DROP 0 EXIT THEN _RCIV-C !
    _RCIV-C @ RCLI.MAGIC @ RCLI-MAGIC <> IF 0 EXIT THEN
    _RCIV-C @ RCLI.ABI @ RCLI-ABI-VERSION <> IF 0 EXIT THEN
    _RCIV-C @ RCLI.SIZE @ RCLI-SIZE <> IF 0 EXIT THEN
    _RCIV-C @ RCLI.FLAGS @ RCLI-F-REPLACE INVERT AND IF 0 EXIT THEN
    _RCIV-C @ _RCI-RESERVED + @ IF 0 EXIT THEN
    _RCIV-C @ RCLI.CONTEXT @ CTX-VALID? 0= IF 0 EXIT THEN
    _RCIV-C @ RCLI.CONTEXT @ _RCIV-C @ RCLI.BIND
        LBIND-CONTEXT? 0= IF 0 EXIT THEN
    _RCIV-C @ RCLI.BUS @ _RCIV-R !
    _RCIV-R @ 0= IF 0 EXIT THEN
    _RCIV-R @ CBUS.REGISTRY @ 0= IF 0 EXIT THEN
    _RCIV-C @ RCLI.CONTEXT @ CTX.QUEUE @ _RCIV-R @ <> IF 0 EXIT THEN
    _RCIV-C @ RCLI.ACQUISITION @ _RCIV-R !
    _RCIV-R @ RACQ-RESULT-VALID? 0= IF 0 EXIT THEN
    _RCIV-R @ RACQ.RESULT-REF RREF.ID
        _RCIV-C @ RCLI.BIND LBIND.RESOURCE-ID
        RID= 0= IF 0 EXIT THEN
    _RCIV-C @ RCLI.OWNER @ _RCIV-I !
    _RCIV-I @ 0= IF 0 EXIT THEN
    _RCIV-I @ CINST.ID @ _RCIV-C @ RCLI.BIND LBIND.TARGET-ID @ <> IF
        0 EXIT
    THEN
    _RCIV-I @ CINST.GENERATION @
        _RCIV-C @ RCLI.BIND LBIND.TARGET-GEN @ <> IF
        0 EXIT
    THEN
    _RCIV-I @ CINST-DESC DUP COMP-CAPS-VALID? 0= IF DROP 0 EXIT THEN
        _RCIV-D !
    S" resource.describe" _RCIV-D @ COMP-CAP-FIND
        _RCIV-C @ RCLI.DESCRIBE @ <> IF 0 EXIT THEN
    _RCIV-C @ RCLI.DESCRIBE @ DUP 0= IF DROP 0 EXIT THEN
        CAP-K-RESOURCE CAP-E-OBSERVE
        RCON-DESCRIBE-IN-SCHEMA RCON-DESCRIBE-OUT-SCHEMA
        _RCLI-CAP-EXACT? 0= IF 0 EXIT THEN
    S" resource.snapshot" _RCIV-D @ COMP-CAP-FIND
        _RCIV-C @ RCLI.SNAPSHOT @ <> IF 0 EXIT THEN
    _RCIV-C @ RCLI.SNAPSHOT @ DUP 0= IF DROP 0 EXIT THEN
        CAP-K-RESOURCE CAP-E-OBSERVE
        RCON-SNAPSHOT-IN-SCHEMA RCON-SNAPSHOT-OUT-SCHEMA
        _RCLI-CAP-EXACT? 0= IF 0 EXIT THEN
    _RCIV-C @ RCLI-REPLACE? IF
        S" resource.replace" _RCIV-D @ COMP-CAP-FIND
            _RCIV-C @ RCLI.REPLACE @ <> IF 0 EXIT THEN
        _RCIV-C @ RCLI.REPLACE @ DUP 0= IF DROP 0 EXIT THEN
            CAP-K-COMMAND CAP-E-MUTATE CAP-E-PERSIST OR
            RCON-REPLACE-IN-SCHEMA RCON-REPLACE-OUT-SCHEMA
            _RCLI-CAP-EXACT? 0= IF 0 EXIT THEN
    ELSE
        _RCIV-C @ RCLI.REPLACE @ IF 0 EXIT THEN
    THEN
    -1 ;

VARIABLE _RCII-O
VARIABLE _RCII-B
VARIABLE _RCII-C
VARIABLE _RCII-BUS
VARIABLE _RCII-I
VARIABLE _RCII-D
VARIABLE _RCII-CAP

: RCLI-INIT  ( acquisition binding context bus client -- status )
    _RCII-O ! _RCII-BUS ! _RCII-C ! _RCII-B ! _RCII-I !
    _RCII-O @ 0= IF RCLI-S-INVALID EXIT THEN
    _RCII-O @ RCLI-CLEAR
    _RCII-I @ RACQ-RESULT-VALID? 0= IF RCLI-S-INVALID EXIT THEN
    _RCII-B @ LBIND-VALID? 0= _RCII-C @ CTX-VALID? 0= OR IF
        RCLI-S-INVALID EXIT
    THEN
    _RCII-C @ _RCII-B @ LBIND-CONTEXT? 0= IF RCLI-S-INVALID EXIT THEN
    _RCII-BUS @ 0= IF RCLI-S-INVALID EXIT THEN
    _RCII-C @ CTX.QUEUE @ _RCII-BUS @ <> IF RCLI-S-INVALID EXIT THEN
    _RCII-I @ RACQ.RESULT-REF RREF.ID _RCII-B @ LBIND.RESOURCE-ID
        RID= 0= IF RCLI-S-INVALID EXIT THEN
    _RCII-B @ LBIND.TARGET-ID @ _RCII-B @ LBIND.TARGET-GEN @
        _RCII-BUS @ CBUS.REGISTRY @ CREG-INST-FIND DUP 0= IF
        DROP RCLI-S-INVALID EXIT
    THEN _RCII-D !
    _RCII-D @ CINST-DESC DUP COMP-CAPS-VALID? 0= IF
        DROP RCLI-S-INVALID EXIT
    THEN _RCII-CAP !
    S" resource.describe" _RCII-CAP @ COMP-CAP-FIND DUP 0= IF
        DROP RCLI-S-NO-DESCRIBE EXIT
    THEN
    DUP CAP-K-RESOURCE CAP-E-OBSERVE
        RCON-DESCRIBE-IN-SCHEMA RCON-DESCRIBE-OUT-SCHEMA
        _RCLI-CAP-EXACT? 0= IF
        DROP RCLI-S-NO-DESCRIBE EXIT
    THEN _RCII-O @ RCLI.DESCRIBE !
    S" resource.snapshot" _RCII-CAP @ COMP-CAP-FIND DUP 0= IF
        DROP RCLI-S-NO-SNAPSHOT EXIT
    THEN
    DUP CAP-K-RESOURCE CAP-E-OBSERVE
        RCON-SNAPSHOT-IN-SCHEMA RCON-SNAPSHOT-OUT-SCHEMA
        _RCLI-CAP-EXACT? 0= IF
        DROP RCLI-S-NO-SNAPSHOT EXIT
    THEN _RCII-O @ RCLI.SNAPSHOT !
    S" resource.replace" _RCII-CAP @ COMP-CAP-FIND ?DUP IF
        DUP CAP-K-COMMAND CAP-E-MUTATE CAP-E-PERSIST OR
            RCON-REPLACE-IN-SCHEMA RCON-REPLACE-OUT-SCHEMA
            _RCLI-CAP-EXACT? 0= IF DROP RCLI-S-INVALID EXIT THEN
        _RCII-O @ RCLI.REPLACE !
        RCLI-F-REPLACE _RCII-O @ RCLI.FLAGS !
    THEN
    _RCII-C @ _RCII-O @ RCLI.CONTEXT !
    _RCII-BUS @ _RCII-O @ RCLI.BUS !
    _RCII-I @ _RCII-O @ RCLI.ACQUISITION !
    _RCII-D @ _RCII-O @ RCLI.OWNER !
    _RCII-B @ _RCII-O @ RCLI.BIND LBIND-COPY
        LBIND-S-OK <> IF _RCII-O @ RCLI-CLEAR RCLI-S-INVALID EXIT THEN
    _RCII-O @ RCLI-VALID? IF CBUS-S-OK ELSE RCLI-S-INVALID THEN ;

VARIABLE _RCIP-P
VARIABLE _RCIP-Q
VARIABLE _RCIP-C
VARIABLE _RCIP-CAP

: _RCLI-PREPARE  ( principal request cap client -- status )
    _RCIP-C ! _RCIP-CAP ! _RCIP-Q ! _RCIP-P !
    _RCIP-C @ RCLI-VALID? 0= IF RCLI-S-INVALID EXIT THEN
    _RCIP-Q @ 0= IF RCLI-S-INVALID EXIT THEN
    _RCIP-P @ CPRINC-USER < _RCIP-P @ CPRINC-AGENT > OR IF
        RCLI-S-INVALID EXIT
    THEN
    _RCIP-C @ RCLI.BIND _RCIP-C @ RCLI.CONTEXT @ _RCIP-Q @
        LBIND-REQUEST! LBIND-S-OK <> IF RCLI-S-STALE EXIT THEN
    _RCIP-P @ _RCIP-Q @ CBR.PRINCIPAL !
    _RCIP-CAP @ _RCIP-Q @ CBR.CAP !
    CBUS-S-OK ;

: RCLI-DESCRIBE-PREPARE  ( principal request client -- status )
    DUP RCLI.DESCRIBE @ SWAP _RCLI-PREPARE DUP IF EXIT THEN
    DROP _RCIP-Q @ CBR.ARGS CV-NULL! CBUS-S-OK ;

VARIABLE _RCIS-L

: RCLI-SNAPSHOT-PREPARE  ( locator principal request client -- status )
    _RCIP-C ! _RCIP-Q ! _RCIP-P ! _RCIS-L !
    _RCIS-L @ QLOC-VALID? 0= IF RCLI-S-INVALID EXIT THEN
    _RCIS-L @ QLOC.REF RREF.ID _RCIP-C @ RCLI.BIND LBIND.RESOURCE-ID
        RID= 0= IF RCLI-S-RESULT-MISMATCH EXIT THEN
    _RCIP-P @ _RCIP-Q @ _RCIP-C @ RCLI.SNAPSHOT @ _RCIP-C @
        _RCLI-PREPARE DUP IF EXIT THEN DROP
    _RCIS-L @ _RCIP-Q @ CBR.ARGS RCON-SNAPSHOT-ARGS!
        RCON-S-OK = IF CBUS-S-OK ELSE RCLI-S-INVALID THEN ;

VARIABLE _RCIR-A
VARIABLE _RCIR-U
VARIABLE _RCIR-D

: RCLI-REPLACE-PREPARE  ( locator content-a content-u digest principal request client -- status )
    _RCIP-C ! _RCIP-Q ! _RCIP-P ! _RCIR-D ! _RCIR-U ! _RCIR-A ! _RCIS-L !
    _RCIP-C @ RCLI-REPLACE? 0= IF RCLI-S-READONLY EXIT THEN
    _RCIS-L @ QLOC-VALID? 0= IF RCLI-S-INVALID EXIT THEN
    _RCIS-L @ QLOC.REF RREF.ID _RCIP-C @ RCLI.BIND LBIND.RESOURCE-ID
        RID= 0= IF RCLI-S-RESULT-MISMATCH EXIT THEN
    _RCIP-P @ _RCIP-Q @ _RCIP-C @ RCLI.REPLACE @ _RCIP-C @
        _RCLI-PREPARE DUP IF EXIT THEN DROP
    _RCIS-L @ _RCIR-A @ _RCIR-U @ _RCIR-D @ _RCIP-Q @ CBR.ARGS
        RCON-REPLACE-ARGS!
        RCON-S-OK = IF CBUS-S-OK ELSE RCLI-S-INVALID THEN ;

CREATE _RCID-REF RREF-SIZE ALLOT
CREATE _RCID-CONTENT-DIGEST SHA3-256-LEN ALLOT
VARIABLE _RCID-Q
VARIABLE _RCID-C
VARIABLE _RCID-S

: _RCLI-DISPATCH  ( request expected-cap client -- status )
    _RCID-C ! >R _RCID-Q !
    _RCID-C @ RCLI-VALID? 0= IF R> DROP RCLI-S-INVALID EXIT THEN
    _RCID-Q @ 0= IF R> DROP RCLI-S-INVALID EXIT THEN
    _RCID-Q @ CBR.CAP @ R> <> IF RCLI-S-INVALID EXIT THEN
    _RCID-Q @ _RCID-C @ RCLI.BUS @ CBUS-DISPATCH ;

: RCLI-DESCRIBE-DISPATCH  ( request client -- status )
    DUP _RCID-C ! RCLI.DESCRIBE @ _RCID-C @ _RCLI-DISPATCH
        DUP IF EXIT THEN DROP
    _RCID-Q @ CBR.RESULT RCON-DESCRIBE-RESULT? 0= IF
        RCLI-S-RESULT-TYPE EXIT
    THEN
    S" resource" _RCID-Q @ CBR.RESULT CV-MAP-FIND
        _RCID-REF IRES-RREF@ IRES-S-OK <> IF RCLI-S-RESULT-TYPE EXIT THEN
    _RCID-REF RREF.ID _RCID-C @ RCLI.BIND LBIND.RESOURCE-ID
        RID= 0= IF RCLI-S-RESULT-MISMATCH EXIT THEN
    S" owner" _RCID-Q @ CBR.RESULT CV-MAP-FIND DUP CV-DATA@ SWAP CV-LEN@
    _RCID-C @ RCLI.ACQUISITION @ RACQ.RESULT-TOKEN RACQ.TOKEN-ROOT @
        RACQ-ROOT-OWNER$ STR-STR= 0= IF RCLI-S-RESULT-MISMATCH EXIT THEN
    CBUS-S-OK ;

: RCLI-SNAPSHOT-DISPATCH  ( locator request client -- status )
    _RCID-C ! _RCID-Q ! _RCIS-L !
    _RCID-Q @ _RCID-C @ RCLI.SNAPSHOT @ _RCID-C @ _RCLI-DISPATCH
        DUP IF EXIT THEN DROP
    _RCIS-L @ _RCID-Q @ CBR.RESULT RCON-SNAPSHOT-RESULT? IF
        CBUS-S-OK
    ELSE
        RCLI-S-RESULT-MISMATCH
    THEN ;

: _RCLI-REPLACE-DIGEST!  ( -- flag )
    S" content_digest" _RCID-Q @ CBR.ARGS CV-MAP-FIND DUP 0= IF
        DROP 0 EXIT
    THEN
    DUP CV-TYPE@ CV-T-BYTES <> IF DROP 0 EXIT THEN
    DUP CV-LEN@ SHA3-256-LEN <> IF DROP 0 EXIT THEN
    CV-DATA@ DUP 0= IF DROP 0 EXIT THEN
    _RCID-CONTENT-DIGEST SHA3-256-LEN MOVE -1 ;

: RCLI-REPLACE-DISPATCH  ( old-locator request client -- status )
    _RCID-C ! _RCID-Q ! _RCIS-L !
    _RCID-C @ RCLI-REPLACE? 0= IF RCLI-S-READONLY EXIT THEN
    _RCLI-REPLACE-DIGEST! 0= IF RCLI-S-INVALID EXIT THEN
    _RCID-Q @ _RCID-C @ RCLI.REPLACE @ _RCID-C @ _RCLI-DISPATCH
        DUP IF EXIT THEN DROP
    _RCIS-L @ _RCID-CONTENT-DIGEST _RCID-Q @ CBR.RESULT
        RCON-REPLACE-RESULT? 0= IF
        RCLI-S-RESULT-MISMATCH EXIT
    THEN
    _RCID-Q @ _RCID-C @ RCLI.CONTEXT @ _RCID-C @ RCLI.BIND LBIND-ADVANCE
        LBIND-S-OK = IF CBUS-S-OK ELSE RCLI-S-STALE THEN ;

VARIABLE _RCIC-L
VARIABLE _RCIC-A
VARIABLE _RCIC-U
VARIABLE _RCIC-D
VARIABLE _RCIC-P
VARIABLE _RCIC-Q
VARIABLE _RCIC-C

: RCLI-DESCRIBE  ( principal request client -- status )
    _RCIC-C ! _RCIC-Q ! _RCIC-P !
    _RCIC-P @ _RCIC-Q @ _RCIC-C @ RCLI-DESCRIBE-PREPARE
        ?DUP IF EXIT THEN
    _RCIC-Q @ _RCIC-C @ RCLI-DESCRIBE-DISPATCH ;

: RCLI-SNAPSHOT-CALL  ( locator principal request client -- status )
    _RCIC-C ! _RCIC-Q ! _RCIC-P ! _RCIC-L !
    _RCIC-L @ _RCIC-P @ _RCIC-Q @ _RCIC-C @ RCLI-SNAPSHOT-PREPARE
        ?DUP IF EXIT THEN
    _RCIC-L @ _RCIC-Q @ _RCIC-C @ RCLI-SNAPSHOT-DISPATCH ;

: RCLI-REPLACE-CALL  ( locator content-a content-u digest principal request client -- status )
    \ Consequential/Agent callers normally use PREPARE, stamp authority,
    \ then DISPATCH.  This convenience path still traverses bus policy.
    _RCIC-C ! _RCIC-Q ! _RCIC-P ! _RCIC-D !
    _RCIC-U ! _RCIC-A ! _RCIC-L !
    _RCIC-L @ _RCIC-A @ _RCIC-U @ _RCIC-D @
        _RCIC-P @ _RCIC-Q @ _RCIC-C @ RCLI-REPLACE-PREPARE
        ?DUP IF EXIT THEN
    _RCIC-L @ _RCIC-Q @ _RCIC-C @ RCLI-REPLACE-DISPATCH ;

VARIABLE _RCIF-C
VARIABLE _RCIF-S

: RCLI-FINI  ( client -- status )
    DUP _RCIF-C ! RCLI-VALID? 0= IF RCLI-S-INVALID EXIT THEN
    _RCIF-C @ RCLI.BIND _RCIF-C @ RCLI.ACQUISITION @ RACQ-DETACH
        DUP _RCIF-S !
    _RCIF-S @ RACQ-S-OK = IF
        DROP _RCIF-C @ RCLI-CLEAR CBUS-S-OK
    ELSE
        DROP RCLI-S-RELEASE
    THEN ;

' RCLI-CLEAR               CONSTANT _RCLI-CLEAR-XT
' RCLI-VALID?              CONSTANT _RCLI-VALID-XT
' RCLI-INIT                CONSTANT _RCLI-INIT-XT
' RCLI-DESCRIBE-PREPARE    CONSTANT _RCLI-DESC-PREP-XT
' RCLI-SNAPSHOT-PREPARE    CONSTANT _RCLI-SNAP-PREP-XT
' RCLI-REPLACE-PREPARE     CONSTANT _RCLI-REPL-PREP-XT
' RCLI-DESCRIBE-DISPATCH   CONSTANT _RCLI-DESC-DISP-XT
' RCLI-SNAPSHOT-DISPATCH   CONSTANT _RCLI-SNAP-DISP-XT
' RCLI-REPLACE-DISPATCH    CONSTANT _RCLI-REPL-DISP-XT
' RCLI-DESCRIBE            CONSTANT _RCLI-DESC-CALL-XT
' RCLI-SNAPSHOT-CALL       CONSTANT _RCLI-SNAP-CALL-XT
' RCLI-REPLACE-CALL        CONSTANT _RCLI-REPL-CALL-XT
' RCLI-FINI                CONSTANT _RCLI-FINI-XT

GUARD _RCLI-GUARD

: RCLI-CLEAR  ( client -- ) _RCLI-CLEAR-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-VALID?  ( client -- flag ) _RCLI-VALID-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-INIT  ( acquisition binding context bus client -- status )
    _RCLI-INIT-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-DESCRIBE-PREPARE  ( principal request client -- status )
    _RCLI-DESC-PREP-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-SNAPSHOT-PREPARE  ( locator principal request client -- status )
    _RCLI-SNAP-PREP-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-REPLACE-PREPARE  ( locator content-a content-u digest principal request client -- status )
    _RCLI-REPL-PREP-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-DESCRIBE-DISPATCH  ( request client -- status )
    _RCLI-DESC-DISP-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-SNAPSHOT-DISPATCH  ( locator request client -- status )
    _RCLI-SNAP-DISP-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-REPLACE-DISPATCH  ( old-locator request client -- status )
    _RCLI-REPL-DISP-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-DESCRIBE  ( principal request client -- status )
    _RCLI-DESC-CALL-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-SNAPSHOT-CALL  ( locator principal request client -- status )
    _RCLI-SNAP-CALL-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-REPLACE-CALL  ( locator content-a content-u digest principal request client -- status )
    _RCLI-REPL-CALL-XT _RCLI-GUARD WITH-GUARD ;
: RCLI-FINI  ( client -- status ) _RCLI-FINI-XT _RCLI-GUARD WITH-GUARD ;
