\ =====================================================================
\  device-flow.f - Deterministic account and run-settings demo source
\ =====================================================================
\  Native development fixture for exercising account and catalog UX.
\  Production code depends only on the provider-neutral ports it simulates.
\ =====================================================================

PROVIDED akashic-agent-devtools-device-flow

REQUIRE scripted.f
REQUIRE ../../run-settings.f

0 CONSTANT _DF-SOURCE
_DF-SOURCE AGENT-PROVIDER-SOURCE-SIZE + CONSTANT _DF-AUTH
_DF-AUTH AGENT-PROVIDER-AUTH-SIZE + CONSTANT _DF-SETTINGS
_DF-SETTINGS AGENT-RUN-SETTINGS-SIZE + CONSTANT _DF-MODELS
_DF-MODELS 2 AGENT-RUN-MODEL-SIZE * + CONSTANT _DF-MODEL-PTRS
_DF-MODEL-PTRS 16 + CONSTANT _DF-EFFORTS
_DF-EFFORTS 4 AGENT-RUN-CHOICE-SIZE * + CONSTANT _DF-EFFORT-PTRS
_DF-EFFORT-PTRS 32 + CONSTANT _DF-TIERS
_DF-TIERS AGENT-RUN-CHOICE-SIZE + CONSTANT _DF-TIER-PTRS
_DF-TIER-PTRS 8 + CONSTANT _DF-AUTH-READY-MS
_DF-AUTH-READY-MS 8 + CONSTANT _DF-SETTINGS-READY-MS
_DF-SETTINGS-READY-MS 8 + CONSTANT DEVFLOW-SOURCE-SIZE

: DFSRC.AUTH       ( source -- auth ) _DF-AUTH + ;
: DFSRC.SETTINGS   ( source -- settings ) _DF-SETTINGS + ;
: DFSRC.MODELS     ( source -- a ) _DF-MODELS + ;
: DFSRC.MODEL-PTRS ( source -- a ) _DF-MODEL-PTRS + ;
: DFSRC.EFFORTS    ( source -- a ) _DF-EFFORTS + ;
: DFSRC.EFFORT-PTRS ( source -- a ) _DF-EFFORT-PTRS + ;
: DFSRC.TIERS      ( source -- a ) _DF-TIERS + ;
: DFSRC.TIER-PTRS  ( source -- a ) _DF-TIER-PTRS + ;
: DFSRC.AUTH-READY-MS ( source -- a ) _DF-AUTH-READY-MS + ;
: DFSRC.SETTINGS-READY-MS ( source -- a ) _DF-SETTINGS-READY-MS + ;

: _DFS-MODEL  ( index source -- model )
    DFSRC.MODELS SWAP AGENT-RUN-MODEL-SIZE * + ;

: _DFS-EFFORT  ( index source -- choice )
    DFSRC.EFFORTS SWAP AGENT-RUN-CHOICE-SIZE * + ;

VARIABLE _DFA-S

: _DFA-METADATA  ( source -- status )
    _DFA-S ! _DFA-S @ DFSRC.AUTH AAUTH-METADATA-CLEAR
    S" account-fixture" _DFA-S @ DFSRC.AUTH AAUTH.ACCOUNT-ID CV-STRING! IF
        AAUTH-S-CAPACITY EXIT
    THEN
    S" developer@example.com"
    _DFA-S @ DFSRC.AUTH AAUTH.ACCOUNT-LABEL CV-STRING! IF
        AAUTH-S-CAPACITY EXIT
    THEN
    S" pro" _DFA-S @ DFSRC.AUTH AAUTH.PLAN CV-STRING! IF
        AAUTH-S-CAPACITY EXIT
    THEN
    AAUTH-S-OK ;

: _DFA-BEGIN  ( source -- status )
    DUP _DFA-S ! DFSRC.AUTH AAUTH-PENDING? IF
        AAUTH-S-BUSY EXIT
    THEN
    _DFA-S @ DFSRC.AUTH AAUTH-METADATA-CLEAR
    S" AKASHIC-7H2K" _DFA-S @ DFSRC.AUTH AAUTH.USER-CODE CV-STRING! IF
        AAUTH-S-CAPACITY EXIT
    THEN
    S" https://auth.openai.com/codex/device"
    _DFA-S @ DFSRC.AUTH AAUTH.VERIFY-URI CV-STRING! IF
        AAUTH-S-CAPACITY EXIT
    THEN
    AAUTH-STATE-PENDING _DFA-S @ DFSRC.AUTH AAUTH.STATE !
    1 _DFA-S @ DFSRC.AUTH AAUTH.REVISION +!
    1500 MS@ + _DFA-S @ DFSRC.AUTH-READY-MS !
    AAUTH-S-PENDING ;

: _DFA-POLL  ( source -- status )
    DUP _DFA-S ! DFSRC.AUTH DUP AAUTH.STATE @
    AAUTH-STATE-PENDING <> IF DROP AAUTH-S-OK EXIT THEN
    MS@ _DFA-S @ DFSRC.AUTH-READY-MS @ < IF DROP AAUTH-S-PENDING EXIT THEN
    DROP _DFA-S @ _DFA-METADATA DUP IF EXIT THEN
    AAUTH-STATE-READY _DFA-S @ DFSRC.AUTH AAUTH.STATE !
    1 _DFA-S @ DFSRC.AUTH AAUTH.REVISION +! AAUTH-S-OK ;

: _DFA-CANCEL  ( source -- status )
    DFSRC.AUTH DUP AAUTH-METADATA-CLEAR
    AAUTH-STATE-SIGNED-OUT OVER AAUTH.STATE !
    1 SWAP AAUTH.REVISION +! AAUTH-S-CANCELLED ;

: _DFA-LOGOUT  ( source -- status )
    _DFA-CANCEL DROP AAUTH-S-OK ;

: _DFA-REFRESH  ( source -- status )
    DUP _DFA-S ! DFSRC.AUTH AAUTH-READY? 0= IF AAUTH-S-INVALID EXIT THEN
    _DFA-S @ _DFA-METADATA ;

VARIABLE _DFS-S
VARIABLE _DFS-I
VARIABLE _DFS-M
VARIABLE _DFS-C

: _DFS-MODEL-SELECT  ( index source -- status )
    _DFS-S ! _DFS-I !
    _DFS-I @ 0< _DFS-I @ 2 >= OR IF ARSET-S-INVALID EXIT THEN
    2 0 DO
        I _DFS-S @ _DFS-MODEL DUP ARMODEL.FLAGS @
        ARMODEL-F-SELECTED INVERT AND SWAP ARMODEL.FLAGS !
    LOOP
    _DFS-I @ _DFS-S @ _DFS-MODEL _DFS-M !
    ARMODEL-F-SELECTED _DFS-M @ ARMODEL.FLAGS +!
    _DFS-I @ _DFS-S @ DFSRC.SETTINGS ARSET.SELECTED !
    _DFS-M @ ARMODEL.EFFORTS-N @ 0 ?DO
        I _DFS-M @ ARMODEL-EFFORT-NTH DUP ARCH.FLAGS @
        ARCH-F-SELECTED INVERT AND SWAP ARCH.FLAGS !
    LOOP
    _DFS-M @ ARMODEL.EFFORTS-N @ 0 ?DO
        I _DFS-M @ ARMODEL-EFFORT-NTH DUP ARCH.FLAGS @
        ARCH-F-DEFAULT AND IF ARCH-F-SELECTED SWAP ARCH.FLAGS +! LEAVE THEN
        DROP
    LOOP
    _DFS-M @ ARMODEL.TIERS-N @ 0 ?DO
        I _DFS-M @ ARMODEL-TIER-NTH DUP ARCH.FLAGS @
        ARCH-F-SELECTED INVERT AND SWAP ARCH.FLAGS !
    LOOP
    ARVERB-AUTO _DFS-S @ DFSRC.SETTINGS ARSET.VERBOSITY !
    1 _DFS-S @ DFSRC.SETTINGS ARSET.REVISION +! ARSET-S-OK ;

: _DFS-EFFORT-SELECT  ( index source -- status )
    _DFS-S ! _DFS-I !
    _DFS-S @ DFSRC.SETTINGS ARSET-SELECTED-MODEL DUP 0= IF
        DROP ARSET-S-INVALID EXIT
    THEN
    DUP _DFS-M ! ARMODEL.EFFORTS-N @
    _DFS-I @ <= _DFS-I @ 0< OR IF ARSET-S-INVALID EXIT THEN
    _DFS-M @ ARMODEL.EFFORTS-N @ 0 ?DO
        I _DFS-M @ ARMODEL-EFFORT-NTH DUP ARCH.FLAGS @
        ARCH-F-SELECTED INVERT AND SWAP ARCH.FLAGS !
    LOOP
    _DFS-I @ _DFS-M @ ARMODEL-EFFORT-NTH
    ARCH-F-SELECTED SWAP ARCH.FLAGS +!
    1 _DFS-S @ DFSRC.SETTINGS ARSET.REVISION +! ARSET-S-OK ;

: _DFS-TIER-SELECT  ( index source -- status )
    _DFS-S ! _DFS-I !
    _DFS-S @ DFSRC.SETTINGS ARSET-SELECTED-MODEL DUP 0= IF
        DROP ARSET-S-INVALID EXIT
    THEN
    _DFS-M !
    _DFS-I @ -1 <
    _DFS-I @ _DFS-M @ ARMODEL.TIERS-N @ >= OR IF ARSET-S-INVALID EXIT THEN
    _DFS-M @ ARMODEL.TIERS-N @ 0 ?DO
        I _DFS-M @ ARMODEL-TIER-NTH DUP ARCH.FLAGS @
        ARCH-F-SELECTED INVERT AND SWAP ARCH.FLAGS !
    LOOP
    _DFS-I @ 0>= IF
        _DFS-I @ _DFS-M @ ARMODEL-TIER-NTH
        ARCH-F-SELECTED SWAP ARCH.FLAGS +!
    THEN
    1 _DFS-S @ DFSRC.SETTINGS ARSET.REVISION +! ARSET-S-OK ;

: _DFS-VERBOSITY  ( verbosity source -- status )
    _DFS-S ! _DFS-I !
    _DFS-I @ 0< _DFS-I @ ARVERB-HIGH > OR IF ARSET-S-INVALID EXIT THEN
    _DFS-I @ _DFS-S @ DFSRC.SETTINGS ARSET.VERBOSITY !
    1 _DFS-S @ DFSRC.SETTINGS ARSET.REVISION +! ARSET-S-OK ;

: _DFS-REFRESH  ( source -- status )
    DUP _DFS-S ! DFSRC.AUTH AAUTH-READY? 0= IF ARSET-S-AUTH EXIT THEN
    ARSET-STATE-LOADING _DFS-S @ DFSRC.SETTINGS ARSET.STATE !
    1 _DFS-S @ DFSRC.SETTINGS ARSET.REVISION +!
    800 MS@ + _DFS-S @ DFSRC.SETTINGS-READY-MS ! ARSET-S-PENDING ;

: _DFS-POLL  ( source -- status )
    DUP _DFS-S ! DFSRC.SETTINGS ARSET.STATE @
    ARSET-STATE-LOADING <> IF ARSET-S-INVALID EXIT THEN
    MS@ _DFS-S @ DFSRC.SETTINGS-READY-MS @ < IF ARSET-S-PENDING EXIT THEN
    ARSET-STATE-READY _DFS-S @ DFSRC.SETTINGS ARSET.STATE !
    0 _DFS-S @ _DFS-MODEL-SELECT DROP
    1 _DFS-S @ DFSRC.SETTINGS ARSET.REVISION +! ARSET-S-OK ;

: _DFS-CANCEL  ( source -- status )
    DFSRC.SETTINGS DUP ARSET-STATE-EMPTY SWAP ARSET.STATE !
    DUP -1 SWAP ARSET.SELECTED !
    1 SWAP ARSET.REVISION +! ARSET-S-CANCELLED ;

: _DFS-CHOICE  ( id-a id-u label-a label-u desc-a desc-u flags choice -- )
    >R R@ AGENT-RUN-CHOICE-SIZE 0 FILL
    R@ ARCH.FLAGS !
    R@ ARCH.DESC-U ! R@ ARCH.DESC-A !
    R@ ARCH.LABEL-U ! R@ ARCH.LABEL-A !
    R@ ARCH.ID-U ! R> ARCH.ID-A ! ;

: _DFS-MODEL-DESC  ( id-a id-u label-a label-u desc-a desc-u flags priority model -- )
    >R R@ AGENT-RUN-MODEL-SIZE 0 FILL
    R@ ARMODEL.PRIORITY ! R@ ARMODEL.FLAGS !
    R@ ARMODEL.DESC-U ! R@ ARMODEL.DESC-A !
    R@ ARMODEL.LABEL-U ! R@ ARMODEL.LABEL-A !
    R@ ARMODEL.ID-U ! R> ARMODEL.ID-A ! ;

: _DFS-INIT-DESCRIPTORS  ( source -- )
    DUP _DFS-S !
    S" low" S" Low" S" Fast responses" ARCH-F-DEFAULT
    0 _DFS-S @ _DFS-EFFORT _DFS-CHOICE
    S" medium" S" Medium" S" Balanced reasoning" 0
    1 _DFS-S @ _DFS-EFFORT _DFS-CHOICE
    S" low" S" Low" S" Fast responses" 0
    2 _DFS-S @ _DFS-EFFORT _DFS-CHOICE
    S" high" S" High" S" Deeper reasoning" ARCH-F-DEFAULT
    3 _DFS-S @ _DFS-EFFORT _DFS-CHOICE
    S" priority" S" Fast" S" Faster responses" 0
    _DFS-S @ DFSRC.TIERS _DFS-CHOICE
    0 _DFS-S @ _DFS-EFFORT
    _DFS-S @ DFSRC.EFFORT-PTRS !
    1 _DFS-S @ _DFS-EFFORT
    _DFS-S @ DFSRC.EFFORT-PTRS 8 + !
    2 _DFS-S @ _DFS-EFFORT
    _DFS-S @ DFSRC.EFFORT-PTRS 16 + !
    3 _DFS-S @ _DFS-EFFORT
    _DFS-S @ DFSRC.EFFORT-PTRS 24 + !
    _DFS-S @ DFSRC.TIERS _DFS-S @ DFSRC.TIER-PTRS !
    S" gpt-fast" S" Swift" S" Fast everyday work"
    ARMODEL-F-TEXT ARMODEL-F-IMAGE OR ARMODEL-F-VERBOSITY OR
    ARMODEL-F-RESPONSES-LITE OR ARMODEL-F-DEFAULT OR
    1 0 _DFS-S @ _DFS-MODEL _DFS-MODEL-DESC
    _DFS-S @ DFSRC.EFFORT-PTRS
    0 _DFS-S @ _DFS-MODEL ARMODEL.EFFORTS-A !
    2 0 _DFS-S @ _DFS-MODEL ARMODEL.EFFORTS-N !
    S" gpt-slow" S" Deliberate" S" Careful general work"
    ARMODEL-F-TEXT ARMODEL-F-IMAGE OR ARMODEL-F-VERBOSITY OR
    2 1 _DFS-S @ _DFS-MODEL _DFS-MODEL-DESC
    _DFS-S @ DFSRC.EFFORT-PTRS 16 +
    1 _DFS-S @ _DFS-MODEL ARMODEL.EFFORTS-A !
    2 1 _DFS-S @ _DFS-MODEL ARMODEL.EFFORTS-N !
    _DFS-S @ DFSRC.TIER-PTRS
    1 _DFS-S @ _DFS-MODEL ARMODEL.TIERS-A !
    1 1 _DFS-S @ _DFS-MODEL ARMODEL.TIERS-N !
    0 _DFS-S @ _DFS-MODEL _DFS-S @ DFSRC.MODEL-PTRS !
    1 _DFS-S @ _DFS-MODEL _DFS-S @ DFSRC.MODEL-PTRS 8 + ! ;

VARIABLE _DFNEW-S
VARIABLE _DFNEW-P
VARIABLE _DFNEW-STATUS

: _DFS-CREATE  ( source -- provider status )
    _DFNEW-S ! SCRIPTED-PROVIDER-NEW
    _DFNEW-STATUS ! _DFNEW-P !
    _DFNEW-STATUS @ IF _DFNEW-P @ _DFNEW-STATUS @ EXIT THEN
    _DFNEW-S @ DFSRC.AUTH _DFNEW-P @ APROV.AUTH !
    _DFNEW-S @ DFSRC.SETTINGS _DFNEW-P @ APROV.RUN-SETTINGS !
    _DFNEW-P @ APROV.FEATURES DUP @ APROV-F-AUTH OR SWAP !
    S" org.akashic.agent.testing.device-flow"
    _DFNEW-P @ APROV.ID-U ! _DFNEW-P @ APROV.ID-A !
    _DFNEW-P @ 0 ;

: DEVFLOW-SOURCE-FREE  ( source -- )
    DUP DFSRC.SETTINGS ARSET-DESTROY
    DUP DFSRC.AUTH AAUTH-DESTROY
    DUP DEVFLOW-SOURCE-SIZE 0 FILL FREE ;

: DEVFLOW-SOURCE-NEW  ( -- source status )
    DEVFLOW-SOURCE-SIZE ALLOCATE
    DUP IF 2DROP 0 APSOURCE-S-NOMEM EXIT THEN
    DROP DUP _DFNEW-S ! DEVFLOW-SOURCE-SIZE 0 FILL
    _DFNEW-S @ APSOURCE-INIT
    _DFNEW-S @ DFSRC.AUTH AAUTH-INIT
    AAUTH-M-DEVICE _DFNEW-S @ DFSRC.AUTH AAUTH.METHODS !
    AAUTH-STATE-SIGNED-OUT _DFNEW-S @ DFSRC.AUTH AAUTH.STATE !
    _DFNEW-S @ _DFNEW-S @ DFSRC.AUTH AAUTH.CONTEXT !
    ['] _DFA-BEGIN _DFNEW-S @ DFSRC.AUTH AAUTH.BEGIN-XT !
    ['] _DFA-POLL _DFNEW-S @ DFSRC.AUTH AAUTH.POLL-XT !
    ['] _DFA-CANCEL _DFNEW-S @ DFSRC.AUTH AAUTH.CANCEL-XT !
    ['] _DFA-LOGOUT _DFNEW-S @ DFSRC.AUTH AAUTH.LOGOUT-XT !
    ['] _DFA-REFRESH _DFNEW-S @ DFSRC.AUTH AAUTH.REFRESH-XT !
    _DFNEW-S @ DFSRC.SETTINGS ARSET-INIT
    _DFNEW-S @ _DFNEW-S @ DFSRC.SETTINGS ARSET.CONTEXT !
    _DFNEW-S @ DFSRC.MODEL-PTRS
    _DFNEW-S @ DFSRC.SETTINGS ARSET.MODELS-A !
    2 _DFNEW-S @ DFSRC.SETTINGS ARSET.MODELS-N !
    ['] _DFS-REFRESH _DFNEW-S @ DFSRC.SETTINGS ARSET.REFRESH-XT !
    ['] _DFS-POLL _DFNEW-S @ DFSRC.SETTINGS ARSET.POLL-XT !
    ['] _DFS-CANCEL _DFNEW-S @ DFSRC.SETTINGS ARSET.CANCEL-XT !
    ['] _DFS-MODEL-SELECT _DFNEW-S @ DFSRC.SETTINGS ARSET.MODEL-XT !
    ['] _DFS-EFFORT-SELECT _DFNEW-S @ DFSRC.SETTINGS ARSET.EFFORT-XT !
    ['] _DFS-TIER-SELECT _DFNEW-S @ DFSRC.SETTINGS ARSET.TIER-XT !
    ['] _DFS-VERBOSITY _DFNEW-S @ DFSRC.SETTINGS ARSET.VERBOSITY-XT !
    _DFNEW-S @ _DFS-INIT-DESCRIPTORS
    _DFNEW-S @ _DFNEW-S @ APSOURCE.CONTEXT !
    S" org.akashic.agent.source.testing.device-flow"
    _DFNEW-S @ APSOURCE.ID-U ! _DFNEW-S @ APSOURCE.ID-A !
    ['] _DFS-CREATE _DFNEW-S @ APSOURCE.NEW-XT !
    ['] DEVFLOW-SOURCE-FREE _DFNEW-S @ APSOURCE.FREE-XT !
    _DFNEW-S @ APSOURCE-S-OK ;
