\ rss.f - bounded transactional RSS 2.0 codec and typed model

PROVIDED akashic-syndication-rss

REQUIRE xml-common.f
REQUIRE ../utils/string.f

1 CONSTANT RSS-IDENTITY-GUID
2 CONSTANT RSS-IDENTITY-LINK
1 CONSTANT RSS-GUID-IS-PERMALINK
1 CONSTANT RSS-ENCLOSURE-HAS-LENGTH

0 CONSTANT _RSS-CAT-VALUE-U
8 CONSTANT _RSS-CAT-VALUE
_RSS-CAT-VALUE SYN-TAG-CAP + CONSTANT _RSS-CAT-DOMAIN-U
_RSS-CAT-DOMAIN-U 8 + CONSTANT _RSS-CAT-DOMAIN
_RSS-CAT-DOMAIN 256 + CONSTANT RSS-CATEGORY-SIZE

: RSS.CATEGORY.VALUE  ( category -- a u )
    DUP _RSS-CAT-VALUE + SWAP _RSS-CAT-VALUE-U + @ ;
: RSS.CATEGORY.DOMAIN  ( category -- a u )
    DUP _RSS-CAT-DOMAIN + SWAP _RSS-CAT-DOMAIN-U + @ ;

0 CONSTANT _RSS-ENC-FLAGS
8 CONSTANT _RSS-ENC-LENGTH
16 CONSTANT _RSS-ENC-URL-U
24 CONSTANT _RSS-ENC-URL
_RSS-ENC-URL SYN-URL-CAP + CONSTANT _RSS-ENC-TYPE-U
_RSS-ENC-TYPE-U 8 + CONSTANT _RSS-ENC-TYPE
_RSS-ENC-TYPE SYN-MIME-CAP + CONSTANT RSS-ENCLOSURE-SIZE

: RSS.ENCLOSURE.FLAGS  ( enclosure -- a ) _RSS-ENC-FLAGS + ;
: RSS.ENCLOSURE.LENGTH  ( enclosure -- a ) _RSS-ENC-LENGTH + ;
: RSS.ENCLOSURE.URL  ( enclosure -- a u )
    DUP _RSS-ENC-URL + SWAP _RSS-ENC-URL-U + @ ;
: RSS.ENCLOSURE.TYPE  ( enclosure -- a u )
    DUP _RSS-ENC-TYPE + SWAP _RSS-ENC-TYPE-U + @ ;

0 CONSTANT _RSS-ITEM-IDENTITY-KIND
8 CONSTANT _RSS-ITEM-GUID-FLAGS
16 CONSTANT _RSS-ITEM-CATEGORY-COUNT
24 CONSTANT _RSS-ITEM-HAS-ENCLOSURE
32 CONSTANT _RSS-ITEM-GUID-U
40 CONSTANT _RSS-ITEM-GUID
_RSS-ITEM-GUID SYN-ID-CAP + CONSTANT _RSS-ITEM-TITLE-U
_RSS-ITEM-TITLE-U 8 + CONSTANT _RSS-ITEM-TITLE
_RSS-ITEM-TITLE SYN-TITLE-CAP + CONSTANT _RSS-ITEM-LINK-U
_RSS-ITEM-LINK-U 8 + CONSTANT _RSS-ITEM-LINK
_RSS-ITEM-LINK SYN-URL-CAP + CONSTANT _RSS-ITEM-DESCRIPTION-U
_RSS-ITEM-DESCRIPTION-U 8 + CONSTANT _RSS-ITEM-DESCRIPTION
_RSS-ITEM-DESCRIPTION SYN-CONTENT-CAP + CONSTANT _RSS-ITEM-AUTHOR-U
_RSS-ITEM-AUTHOR-U 8 + CONSTANT _RSS-ITEM-AUTHOR
_RSS-ITEM-AUTHOR 256 + CONSTANT _RSS-ITEM-PUBDATE-U
_RSS-ITEM-PUBDATE-U 8 + CONSTANT _RSS-ITEM-PUBDATE
_RSS-ITEM-PUBDATE SYN-DATETIME-CAP + CONSTANT _RSS-ITEM-CATEGORIES
_RSS-ITEM-CATEGORIES SYN-MAX-TAGS RSS-CATEGORY-SIZE * +
    CONSTANT _RSS-ITEM-ENCLOSURE
_RSS-ITEM-ENCLOSURE RSS-ENCLOSURE-SIZE + CONSTANT RSS-ITEM-SIZE

: RSS.ITEM.IDENTITY-KIND  ( item -- a ) _RSS-ITEM-IDENTITY-KIND + ;
: RSS.ITEM.GUID-FLAGS  ( item -- a ) _RSS-ITEM-GUID-FLAGS + ;
: RSS.ITEM.CATEGORY-COUNT  ( item -- a ) _RSS-ITEM-CATEGORY-COUNT + ;
: RSS.ITEM.GUID  ( item -- a u )
    DUP _RSS-ITEM-GUID + SWAP _RSS-ITEM-GUID-U + @ ;
: RSS.ITEM.TITLE  ( item -- a u )
    DUP _RSS-ITEM-TITLE + SWAP _RSS-ITEM-TITLE-U + @ ;
: RSS.ITEM.LINK  ( item -- a u )
    DUP _RSS-ITEM-LINK + SWAP _RSS-ITEM-LINK-U + @ ;
: RSS.ITEM.DESCRIPTION  ( item -- a u )
    DUP _RSS-ITEM-DESCRIPTION + SWAP _RSS-ITEM-DESCRIPTION-U + @ ;
: RSS.ITEM.AUTHOR  ( item -- a u )
    DUP _RSS-ITEM-AUTHOR + SWAP _RSS-ITEM-AUTHOR-U + @ ;
: RSS.ITEM.PUBDATE  ( item -- a u )
    DUP _RSS-ITEM-PUBDATE + SWAP _RSS-ITEM-PUBDATE-U + @ ;
: RSS.ITEM.CATEGORY  ( index item -- category | 0 )
    >R DUP 0< OVER SYN-MAX-TAGS >= OR IF DROP R> DROP 0 EXIT THEN
    R@ RSS.ITEM.CATEGORY-COUNT @ OVER <= IF DROP R> DROP 0 EXIT THEN
    RSS-CATEGORY-SIZE * R> _RSS-ITEM-CATEGORIES + + ;
: RSS.ITEM.ENCLOSURE  ( item -- enclosure | 0 )
    DUP _RSS-ITEM-HAS-ENCLOSURE + @ IF _RSS-ITEM-ENCLOSURE + ELSE DROP 0 THEN ;

0 CONSTANT _RSS-FEED-COUNT
8 CONSTANT _RSS-FEED-CATEGORY-COUNT
16 CONSTANT _RSS-FEED-TITLE-U
24 CONSTANT _RSS-FEED-TITLE
_RSS-FEED-TITLE SYN-TITLE-CAP + CONSTANT _RSS-FEED-LINK-U
_RSS-FEED-LINK-U 8 + CONSTANT _RSS-FEED-LINK
_RSS-FEED-LINK SYN-URL-CAP + CONSTANT _RSS-FEED-DESCRIPTION-U
_RSS-FEED-DESCRIPTION-U 8 + CONSTANT _RSS-FEED-DESCRIPTION
_RSS-FEED-DESCRIPTION SYN-DESCRIPTION-CAP + CONSTANT _RSS-FEED-LANGUAGE-U
_RSS-FEED-LANGUAGE-U 8 + CONSTANT _RSS-FEED-LANGUAGE
_RSS-FEED-LANGUAGE 64 + CONSTANT _RSS-FEED-BUILDDATE-U
_RSS-FEED-BUILDDATE-U 8 + CONSTANT _RSS-FEED-BUILDDATE
_RSS-FEED-BUILDDATE SYN-DATETIME-CAP + CONSTANT _RSS-FEED-PUBDATE-U
_RSS-FEED-PUBDATE-U 8 + CONSTANT _RSS-FEED-PUBDATE
_RSS-FEED-PUBDATE SYN-DATETIME-CAP + CONSTANT _RSS-FEED-GENERATOR-U
_RSS-FEED-GENERATOR-U 8 + CONSTANT _RSS-FEED-GENERATOR
_RSS-FEED-GENERATOR SYN-TITLE-CAP + CONSTANT _RSS-FEED-NEXT-U
_RSS-FEED-NEXT-U 8 + CONSTANT _RSS-FEED-NEXT
_RSS-FEED-NEXT SYN-URL-CAP + CONSTANT _RSS-FEED-CATEGORIES
_RSS-FEED-CATEGORIES SYN-MAX-TAGS RSS-CATEGORY-SIZE * +
    CONSTANT _RSS-FEED-ITEMS
_RSS-FEED-ITEMS SYN-MAX-ENTRIES RSS-ITEM-SIZE * + CONSTANT RSS-FEED-SIZE
RSS-FEED-SIZE CONSTANT RSS-FEED-SCRATCH-SIZE

: RSS.FEED.COUNT  ( feed -- a ) _RSS-FEED-COUNT + ;
: RSS.FEED.CATEGORY-COUNT  ( feed -- a ) _RSS-FEED-CATEGORY-COUNT + ;
: RSS.FEED.TITLE  ( feed -- a u )
    DUP _RSS-FEED-TITLE + SWAP _RSS-FEED-TITLE-U + @ ;
: RSS.FEED.LINK  ( feed -- a u )
    DUP _RSS-FEED-LINK + SWAP _RSS-FEED-LINK-U + @ ;
: RSS.FEED.DESCRIPTION  ( feed -- a u )
    DUP _RSS-FEED-DESCRIPTION + SWAP _RSS-FEED-DESCRIPTION-U + @ ;
: RSS.FEED.LANGUAGE  ( feed -- a u )
    DUP _RSS-FEED-LANGUAGE + SWAP _RSS-FEED-LANGUAGE-U + @ ;
: RSS.FEED.LAST-BUILD-DATE  ( feed -- a u )
    DUP _RSS-FEED-BUILDDATE + SWAP _RSS-FEED-BUILDDATE-U + @ ;
: RSS.FEED.PUBDATE  ( feed -- a u )
    DUP _RSS-FEED-PUBDATE + SWAP _RSS-FEED-PUBDATE-U + @ ;
: RSS.FEED.GENERATOR  ( feed -- a u )
    DUP _RSS-FEED-GENERATOR + SWAP _RSS-FEED-GENERATOR-U + @ ;
: RSS.FEED.NEXT-URL  ( feed -- a u )
    DUP _RSS-FEED-NEXT + SWAP _RSS-FEED-NEXT-U + @ ;
: RSS.FEED.CATEGORY  ( index feed -- category | 0 )
    >R DUP 0< OVER SYN-MAX-TAGS >= OR IF DROP R> DROP 0 EXIT THEN
    R@ RSS.FEED.CATEGORY-COUNT @ OVER <= IF DROP R> DROP 0 EXIT THEN
    RSS-CATEGORY-SIZE * R> _RSS-FEED-CATEGORIES + + ;
: _RSS-FEED-ITEM  ( index feed -- item )
    SWAP RSS-ITEM-SIZE * _RSS-FEED-ITEMS + + ;
: RSS.FEED.ITEM  ( index feed -- item | 0 )
    >R DUP 0< OVER SYN-MAX-ENTRIES >= OR IF DROP R> DROP 0 EXIT THEN
    R@ RSS.FEED.COUNT @ OVER <= IF DROP R> DROP 0 EXIT THEN
    R> _RSS-FEED-ITEM ;
: RSS-FEED-INIT  ( feed -- ) RSS-FEED-SIZE 0 FILL ;

VARIABLE _RSS-CUR-A
VARIABLE _RSS-CUR-U
VARIABLE _RSS-NA
VARIABLE _RSS-NU
VARIABLE _RSS-DEST
VARIABLE _RSS-STATUS
VARIABLE _RSS-FLAGS
VARIABLE _RSS-COUNT
VARIABLE _RSS-COUNT2
VARIABLE _RSS-ITEM
VARIABLE _RSS-ITEM-CUR-A
VARIABLE _RSS-ITEM-CUR-U
VARIABLE _RSS-ITEM-FLAGS
VARIABLE _RSS-ITEM-COUNT
VARIABLE _RSS-CAT
VARIABLE _RSS-ENC
VARIABLE _RSS-TMP
VARIABLE _RSS-DIGIT
VARIABLE _RSS-ROOT-A
VARIABLE _RSS-ROOT-U
VARIABLE _RSS-ELEM-A
VARIABLE _RSS-ELEM-U
VARIABLE _RSS-IN-A
VARIABLE _RSS-IN-U
CREATE _RSS-ATTR-TMP 64 ALLOT

: _RSS-CHILD  ( cursor-a cursor-u -- child-a child-u name-a name-u flag status )
    BEGIN
        MU-SKIP-WS
        DUP 0= IF 2DROP 0 0 0 0 0 SYN-S-INVALID EXIT THEN
        2DUP MU-TAG-TYPE
        DUP MU-T-CLOSE = IF DROP 2DROP 0 0 0 0 0 SYN-S-OK EXIT THEN
        DUP MU-T-COMMENT = IF
            DROP MU-SKIP-COMMENT
        ELSE
            DUP MU-T-OPEN = OVER MU-T-SELF-CLOSE = OR 0= IF
                DROP 2DROP 0 0 0 0 0 SYN-S-INVALID EXIT
            THEN
            DROP 2DUP MU-GET-TAG-NAME _RSS-NU ! _RSS-NA ! 2DROP
            _RSS-NA @ _RSS-NU @ -1 SYN-S-OK EXIT
        THEN
    AGAIN ;

: _RSS-COPY  ( element-a element-u dest cap length-cell -- status )
    SX-ELEMENT-TEXT ;

: _RSS-ATTR-TO
    ( element-a element-u key-a key-u dest cap len-cell -- found status )
    SX-ATTR-COPY ;

: _RSS-ELEMENT-NO-NS  ( element-a element-u -- status )
    S" xmlns" _RSS-ATTR-TMP 64 _RSS-TMP _RSS-ATTR-TO
    DUP IF NIP EXIT THEN DROP
    0= IF SYN-S-OK EXIT THEN
    _RSS-TMP @ 0= IF SYN-S-OK ELSE SYN-S-UNSUPPORTED THEN ;

: _RSS-ATOM-BINDING  ( element-a element-u -- binding status )
    S" xmlns:atom" _RSS-ATTR-TMP 64 _RSS-TMP _RSS-ATTR-TO
    DUP IF NIP 0 SWAP EXIT THEN DROP
    0= IF 0 SYN-S-OK EXIT THEN
    _RSS-ATTR-TMP _RSS-TMP @ S" http://www.w3.org/2005/Atom" STR-STR= IF
        1
    ELSE
        2
    THEN
    SYN-S-OK ;

: _RSS-PARSE-UINT  ( a u -- n status )
    DUP 0= IF 2DROP 0 SYN-S-INVALID EXIT THEN
    0 _RSS-TMP !
    0 ?DO
        DUP I + C@ DUP 48 < OVER 57 > OR IF
            2DROP 0 SYN-S-INVALID UNLOOP EXIT
        THEN
        48 - _RSS-DIGIT !
        _RSS-TMP @ 0x7FFFFFFFFFFFFFFF _RSS-DIGIT @ - 10 / > IF
            DROP 0 SYN-S-CAPACITY UNLOOP EXIT
        THEN
        _RSS-TMP @ 10 * _RSS-DIGIT @ + _RSS-TMP !
    LOOP DROP _RSS-TMP @ SYN-S-OK ;

: _RSS-DECODE-CATEGORY  ( element-a element-u category -- status )
    >R _RSS-ELEM-U ! _RSS-ELEM-A !
    _RSS-ELEM-A @ _RSS-ELEM-U @ R@ _RSS-CAT-VALUE + SYN-TAG-CAP
        R@ _RSS-CAT-VALUE-U + _RSS-COPY ?DUP IF R> DROP EXIT THEN
    R@ _RSS-CAT-VALUE-U + @ 0= IF R> DROP SYN-S-INVALID EXIT THEN
    _RSS-ELEM-A @ _RSS-ELEM-U @ S" domain"
        R@ _RSS-CAT-DOMAIN + 256 R@ _RSS-CAT-DOMAIN-U +
        _RSS-ATTR-TO DUP IF NIP R> DROP EXIT THEN DROP DROP
    R> DROP SYN-S-OK ;

: _RSS-DECODE-ENCLOSURE  ( element-a element-u enclosure -- status )
    >R _RSS-ELEM-U ! _RSS-ELEM-A !
    _RSS-ELEM-A @ _RSS-ELEM-U @ S" url"
        R@ _RSS-ENC-URL + SYN-URL-CAP R@ _RSS-ENC-URL-U +
        _RSS-ATTR-TO DUP IF NIP R> DROP EXIT THEN
    DROP 0= IF R> DROP SYN-S-MISSING EXIT THEN
    _RSS-ELEM-A @ _RSS-ELEM-U @ S" type"
        R@ _RSS-ENC-TYPE + SYN-MIME-CAP R@ _RSS-ENC-TYPE-U +
        _RSS-ATTR-TO DUP IF NIP R> DROP EXIT THEN
    DROP 0= IF R> DROP SYN-S-MISSING EXIT THEN
    _RSS-ELEM-A @ _RSS-ELEM-U @ S" length"
        _RSS-ATTR-TMP 64 _RSS-TMP _RSS-ATTR-TO
        DUP IF NIP R> DROP EXIT THEN
    DROP 0= IF R> DROP SYN-S-MISSING EXIT THEN
    _RSS-ATTR-TMP _RSS-TMP @ _RSS-PARSE-UINT
        DUP IF NIP R> DROP EXIT THEN DROP R@ _RSS-ENC-LENGTH + !
    RSS-ENCLOSURE-HAS-LENGTH R@ _RSS-ENC-FLAGS + !
    R> DROP SYN-S-OK ;

: _RSS-DECODE-GUID  ( element-a element-u item -- status )
    >R _RSS-ELEM-U ! _RSS-ELEM-A !
    _RSS-ELEM-A @ _RSS-ELEM-U @
        R@ _RSS-ITEM-GUID + SYN-ID-CAP R@ _RSS-ITEM-GUID-U +
        _RSS-COPY ?DUP IF R> DROP EXIT THEN
    R@ _RSS-ITEM-GUID-U + @ 0= IF R> DROP SYN-S-INVALID EXIT THEN
    RSS-GUID-IS-PERMALINK R@ _RSS-ITEM-GUID-FLAGS + !
    _RSS-ELEM-A @ _RSS-ELEM-U @ S" isPermaLink"
        _RSS-ATTR-TMP 64 _RSS-TMP _RSS-ATTR-TO
        DUP IF NIP R> DROP EXIT THEN
    DROP
    IF
        _RSS-ATTR-TMP _RSS-TMP @ S" true" STR-STR= IF
            RSS-GUID-IS-PERMALINK R@ _RSS-ITEM-GUID-FLAGS + !
        ELSE _RSS-ATTR-TMP _RSS-TMP @ S" false" STR-STR= IF
            0 R@ _RSS-ITEM-GUID-FLAGS + !
        ELSE R> DROP SYN-S-INVALID EXIT THEN THEN
    THEN
    R> DROP SYN-S-OK ;

: _RSS-DECODE-ITEM  ( element-a element-u item -- status )
    _RSS-ITEM ! 0 _RSS-ITEM-FLAGS ! 0 _RSS-ITEM-COUNT !
    MU-ENTER _RSS-ITEM-CUR-U ! _RSS-ITEM-CUR-A !
    BEGIN
        _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @ _RSS-CHILD
        DUP IF >R 2DROP 2DROP DROP R> EXIT THEN DROP
        0= IF
            2DROP 2DROP
            _RSS-ITEM-COUNT @ _RSS-ITEM @ _RSS-ITEM-CATEGORY-COUNT + !
            _RSS-ITEM @ _RSS-ITEM-GUID-U + @ IF
                RSS-IDENTITY-GUID
                    _RSS-ITEM @ _RSS-ITEM-IDENTITY-KIND + !
            ELSE _RSS-ITEM @ _RSS-ITEM-LINK-U + @ IF
                RSS-IDENTITY-LINK
                    _RSS-ITEM @ _RSS-ITEM-IDENTITY-KIND + !
            ELSE SYN-S-MISSING EXIT THEN THEN
            _RSS-ITEM @ _RSS-ITEM-TITLE-U + @
            _RSS-ITEM @ _RSS-ITEM-DESCRIPTION-U + @ OR 0= IF
                SYN-S-MISSING EXIT
            THEN
            SYN-S-OK EXIT
        THEN
        _RSS-NU ! _RSS-NA ! _RSS-ITEM-CUR-U ! _RSS-ITEM-CUR-A !
        _RSS-NA @ _RSS-NU @ S" guid" STR-STR= IF
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-ITEM-FLAGS @ 1 AND IF SYN-S-INVALID EXIT THEN
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @
                _RSS-ITEM @ _RSS-DECODE-GUID
                ?DUP IF EXIT THEN 1 _RSS-ITEM-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" title" STR-STR= IF
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-ITEM-FLAGS @ 2 AND IF SYN-S-INVALID EXIT THEN
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @
                _RSS-ITEM @ _RSS-ITEM-TITLE +
                SYN-TITLE-CAP _RSS-ITEM @ _RSS-ITEM-TITLE-U + _RSS-COPY
                ?DUP IF EXIT THEN 2 _RSS-ITEM-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" link" STR-STR= IF
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-ITEM-FLAGS @ 4 AND IF SYN-S-INVALID EXIT THEN
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @
                _RSS-ITEM @ _RSS-ITEM-LINK +
                SYN-URL-CAP _RSS-ITEM @ _RSS-ITEM-LINK-U + _RSS-COPY
                ?DUP IF EXIT THEN 4 _RSS-ITEM-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" description" STR-STR= IF
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-ITEM-FLAGS @ 8 AND IF SYN-S-INVALID EXIT THEN
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @
                _RSS-ITEM @ _RSS-ITEM-DESCRIPTION +
                SYN-CONTENT-CAP _RSS-ITEM @ _RSS-ITEM-DESCRIPTION-U +
                _RSS-COPY ?DUP IF EXIT THEN 8 _RSS-ITEM-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" author" STR-STR= IF
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-ITEM-FLAGS @ 16 AND IF SYN-S-INVALID EXIT THEN
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @
                _RSS-ITEM @ _RSS-ITEM-AUTHOR + 256
                _RSS-ITEM @ _RSS-ITEM-AUTHOR-U + _RSS-COPY
                ?DUP IF EXIT THEN 16 _RSS-ITEM-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" pubDate" STR-STR= IF
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-ITEM-FLAGS @ 32 AND IF SYN-S-INVALID EXIT THEN
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @
                _RSS-ITEM @ _RSS-ITEM-PUBDATE +
                SYN-DATETIME-CAP _RSS-ITEM @ _RSS-ITEM-PUBDATE-U +
                _RSS-COPY ?DUP IF EXIT THEN 32 _RSS-ITEM-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" category" STR-STR= IF
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-ITEM-COUNT @ SYN-MAX-TAGS >= IF SYN-S-CAPACITY EXIT THEN
            _RSS-ITEM-COUNT @ RSS-CATEGORY-SIZE *
                _RSS-ITEM @ _RSS-ITEM-CATEGORIES + + _RSS-CAT !
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @
                _RSS-CAT @ _RSS-DECODE-CATEGORY
                ?DUP IF EXIT THEN 1 _RSS-ITEM-COUNT +!
        ELSE _RSS-NA @ _RSS-NU @ S" enclosure" STR-STR= IF
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-ITEM @ _RSS-ITEM-HAS-ENCLOSURE + @ IF
                SYN-S-INVALID EXIT
            THEN
            _RSS-ITEM @ _RSS-ITEM-ENCLOSURE + _RSS-ENC !
            _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @
                _RSS-ENC @ _RSS-DECODE-ENCLOSURE
                ?DUP IF EXIT THEN -1 _RSS-ITEM @ _RSS-ITEM-HAS-ENCLOSURE + !
        THEN THEN THEN THEN THEN THEN THEN THEN
        _RSS-ITEM-CUR-A @ _RSS-ITEM-CUR-U @ MU-SKIP-ELEMENT
            _RSS-ITEM-CUR-U ! _RSS-ITEM-CUR-A !
    AGAIN ;

\ The uniqueness loop is kept explicit to avoid exposing provider identity
\ policy through a shared projection.
VARIABLE _RSS-U-I
VARIABLE _RSS-U-FEED
VARIABLE _RSS-U-ITEM
VARIABLE _RSS-U-A
VARIABLE _RSS-U-U
: _RSS-UNIQUE?  ( index feed -- flag )
    _RSS-U-FEED ! _RSS-U-I !
    _RSS-U-I @ _RSS-U-FEED @ _RSS-FEED-ITEM DUP _RSS-U-ITEM !
    RSS.ITEM.IDENTITY-KIND @ RSS-IDENTITY-GUID = IF
        _RSS-U-ITEM @ RSS.ITEM.GUID
    ELSE _RSS-U-ITEM @ RSS.ITEM.LINK THEN
    _RSS-U-U ! _RSS-U-A !
    _RSS-U-I @ 0 ?DO
        I _RSS-U-FEED @ _RSS-FEED-ITEM DUP RSS.ITEM.IDENTITY-KIND @
            RSS-IDENTITY-GUID = IF RSS.ITEM.GUID ELSE RSS.ITEM.LINK THEN
        _RSS-U-A @ _RSS-U-U @ STR-STR= IF 0 UNLOOP EXIT THEN
    LOOP -1 ;

VARIABLE _RSS-ROOT-CUR-A
VARIABLE _RSS-ROOT-CUR-U
VARIABLE _RSS-CHANNEL-A
VARIABLE _RSS-CHANNEL-U
VARIABLE _RSS-CHANNELS
VARIABLE _RSS-ATOM-ROOT
VARIABLE _RSS-ATOM-CHANNEL
VARIABLE _RSS-ATOM-LOCAL

: _RSS-SCAN-ROOT  ( root-a root-u -- status )
    0 _RSS-CHANNELS ! 0 _RSS-ATOM-CHANNEL !
    MU-ENTER _RSS-ROOT-CUR-U ! _RSS-ROOT-CUR-A !
    BEGIN
        _RSS-ROOT-CUR-A @ _RSS-ROOT-CUR-U @ _RSS-CHILD
        DUP IF >R 2DROP 2DROP DROP R> EXIT THEN DROP
        0= IF
            2DROP 2DROP
            _RSS-CHANNELS @ 1 = IF SYN-S-OK ELSE SYN-S-MISSING THEN
            EXIT
        THEN
        _RSS-NU ! _RSS-NA !
        _RSS-ROOT-CUR-U ! _RSS-ROOT-CUR-A !
        _RSS-NA @ _RSS-NU @ S" channel" STR-STR= IF
            _RSS-ROOT-CUR-A @ _RSS-ROOT-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-CHANNELS @ IF SYN-S-INVALID EXIT THEN
            _RSS-ROOT-CUR-A @ _RSS-CHANNEL-A !
            _RSS-ROOT-CUR-U @ _RSS-CHANNEL-U !
            _RSS-ROOT-CUR-A @ _RSS-ROOT-CUR-U @ _RSS-ATOM-BINDING
            DUP IF NIP EXIT THEN DROP _RSS-ATOM-CHANNEL !
            1 _RSS-CHANNELS +!
        THEN
        _RSS-ROOT-CUR-A @ _RSS-ROOT-CUR-U @ MU-SKIP-ELEMENT
            _RSS-ROOT-CUR-U ! _RSS-ROOT-CUR-A !
    AGAIN ;

: _RSS-ATOM-LINK-NS  ( element-a element-u -- status )
    _RSS-ATOM-BINDING DUP IF NIP EXIT THEN DROP _RSS-ATOM-LOCAL !
    _RSS-ATOM-LOCAL @ 0= IF
        _RSS-ATOM-CHANNEL @ DUP 0= IF DROP _RSS-ATOM-ROOT @ THEN
    ELSE
        _RSS-ATOM-LOCAL @
    THEN
    1 = IF SYN-S-OK ELSE SYN-S-UNSUPPORTED THEN ;

: _RSS-DECODE-INTO  ( document-a document-u feed -- status )
    _RSS-DEST ! _RSS-IN-U ! _RSS-IN-A !
    _RSS-IN-A @ _RSS-IN-U @ SX-VALIDATE ?DUP IF EXIT THEN
    _RSS-IN-A @ _RSS-IN-U @ SX-ROOT
    DUP IF >R 2DROP R> EXIT THEN DROP
    _RSS-ROOT-U ! _RSS-ROOT-A !
    _RSS-ROOT-A @ _RSS-ROOT-U @ MU-GET-TAG-NAME
        _RSS-NU ! _RSS-NA ! 2DROP
    _RSS-NA @ _RSS-NU @ S" rss" STR-STR= 0= IF
        SYN-S-UNSUPPORTED EXIT
    THEN
    _RSS-ROOT-A @ _RSS-ROOT-U @ S" version"
        _RSS-ATTR-TMP 64 _RSS-TMP _RSS-ATTR-TO
        DUP IF NIP EXIT THEN DROP
    0= IF SYN-S-MISSING EXIT THEN
    _RSS-ATTR-TMP _RSS-TMP @ S" 2.0" STR-STR= 0= IF
        SYN-S-UNSUPPORTED EXIT
    THEN
    _RSS-ROOT-A @ _RSS-ROOT-U @ _RSS-ELEMENT-NO-NS ?DUP IF EXIT THEN
    _RSS-ROOT-A @ _RSS-ROOT-U @ _RSS-ATOM-BINDING
        DUP IF NIP EXIT THEN DROP _RSS-ATOM-ROOT !
    _RSS-ROOT-A @ _RSS-ROOT-U @ _RSS-SCAN-ROOT ?DUP IF EXIT THEN
    0 _RSS-FLAGS ! 0 _RSS-COUNT ! 0 _RSS-COUNT2 !
    _RSS-CHANNEL-A @ _RSS-CHANNEL-U @ MU-ENTER
        _RSS-CUR-U ! _RSS-CUR-A !
    BEGIN
        _RSS-CUR-A @ _RSS-CUR-U @ _RSS-CHILD
        DUP IF >R 2DROP 2DROP DROP R> EXIT THEN DROP
        0= IF
            2DROP 2DROP
            _RSS-FLAGS @ 7 AND 7 <> IF SYN-S-MISSING EXIT THEN
            _RSS-COUNT @ _RSS-DEST @ RSS.FEED.COUNT !
            _RSS-COUNT2 @ _RSS-DEST @ RSS.FEED.CATEGORY-COUNT !
            SYN-S-OK EXIT
        THEN
        _RSS-NU ! _RSS-NA ! _RSS-CUR-U ! _RSS-CUR-A !
        _RSS-NA @ _RSS-NU @ S" title" STR-STR= IF
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-FLAGS @ 1 AND IF SYN-S-INVALID EXIT THEN
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-DEST @ _RSS-FEED-TITLE +
                SYN-TITLE-CAP _RSS-DEST @ _RSS-FEED-TITLE-U + _RSS-COPY
                ?DUP IF EXIT THEN 1 _RSS-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" link" STR-STR= IF
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-FLAGS @ 2 AND IF SYN-S-INVALID EXIT THEN
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-DEST @ _RSS-FEED-LINK +
                SYN-URL-CAP _RSS-DEST @ _RSS-FEED-LINK-U + _RSS-COPY
                ?DUP IF EXIT THEN 2 _RSS-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" description" STR-STR= IF
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-FLAGS @ 4 AND IF SYN-S-INVALID EXIT THEN
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-DEST @ _RSS-FEED-DESCRIPTION +
                SYN-DESCRIPTION-CAP _RSS-DEST @ _RSS-FEED-DESCRIPTION-U +
                _RSS-COPY ?DUP IF EXIT THEN 4 _RSS-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" language" STR-STR= IF
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-FLAGS @ 8 AND IF SYN-S-INVALID EXIT THEN
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-DEST @ _RSS-FEED-LANGUAGE + 64
                _RSS-DEST @ _RSS-FEED-LANGUAGE-U + _RSS-COPY
                ?DUP IF EXIT THEN 8 _RSS-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" lastBuildDate" STR-STR= IF
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-FLAGS @ 16 AND IF SYN-S-INVALID EXIT THEN
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-DEST @ _RSS-FEED-BUILDDATE +
                SYN-DATETIME-CAP _RSS-DEST @ _RSS-FEED-BUILDDATE-U +
                _RSS-COPY ?DUP IF EXIT THEN 16 _RSS-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" pubDate" STR-STR= IF
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-FLAGS @ 32 AND IF SYN-S-INVALID EXIT THEN
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-DEST @ _RSS-FEED-PUBDATE +
                SYN-DATETIME-CAP _RSS-DEST @ _RSS-FEED-PUBDATE-U +
                _RSS-COPY ?DUP IF EXIT THEN 32 _RSS-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" generator" STR-STR= IF
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-FLAGS @ 64 AND IF SYN-S-INVALID EXIT THEN
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-DEST @ _RSS-FEED-GENERATOR +
                SYN-TITLE-CAP _RSS-DEST @ _RSS-FEED-GENERATOR-U +
                _RSS-COPY ?DUP IF EXIT THEN 64 _RSS-FLAGS +!
        ELSE _RSS-NA @ _RSS-NU @ S" category" STR-STR= IF
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-COUNT2 @ SYN-MAX-TAGS >= IF SYN-S-CAPACITY EXIT THEN
            _RSS-COUNT2 @ RSS-CATEGORY-SIZE *
                _RSS-DEST @ _RSS-FEED-CATEGORIES + + _RSS-CAT !
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-CAT @ _RSS-DECODE-CATEGORY
                ?DUP IF EXIT THEN 1 _RSS-COUNT2 +!
        ELSE _RSS-NA @ _RSS-NU @ S" atom:link" STR-STR= IF
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-ATOM-LINK-NS
                ?DUP IF EXIT THEN
            _RSS-CUR-A @ _RSS-CUR-U @ S" rel" _RSS-ATTR-TMP 64 _RSS-TMP
                _RSS-ATTR-TO DUP IF NIP EXIT THEN
            DROP
            IF _RSS-ATTR-TMP _RSS-TMP @ S" next" STR-STR= IF
                _RSS-DEST @ _RSS-FEED-NEXT-U + @ IF SYN-S-INVALID EXIT THEN
                _RSS-CUR-A @ _RSS-CUR-U @ S" href"
                    _RSS-DEST @ _RSS-FEED-NEXT + SYN-URL-CAP
                    _RSS-DEST @ _RSS-FEED-NEXT-U + _RSS-ATTR-TO
                    DUP IF NIP EXIT THEN DROP
                    0= IF SYN-S-MISSING EXIT THEN
            THEN THEN
        ELSE _RSS-NA @ _RSS-NU @ S" item" STR-STR= IF
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-ELEMENT-NO-NS
                ?DUP IF EXIT THEN
            _RSS-COUNT @ SYN-MAX-ENTRIES >= IF SYN-S-CAPACITY EXIT THEN
            _RSS-COUNT @ _RSS-DEST @ _RSS-FEED-ITEM _RSS-ITEM !
            _RSS-CUR-A @ _RSS-CUR-U @ _RSS-ITEM @ _RSS-DECODE-ITEM
                ?DUP IF EXIT THEN
            _RSS-COUNT @ _RSS-DEST @ _RSS-UNIQUE? 0= IF SYN-S-INVALID EXIT THEN
            1 _RSS-COUNT +!
        THEN THEN THEN THEN THEN THEN THEN THEN THEN THEN
        _RSS-CUR-A @ _RSS-CUR-U @ MU-SKIP-ELEMENT
            _RSS-CUR-U ! _RSS-CUR-A !
    AGAIN ;

VARIABLE _RSS-DOC-A
VARIABLE _RSS-DOC-U
VARIABLE _RSS-OUT
VARIABLE _RSS-SCRATCH
VARIABLE _RSS-SCRATCH-U

: _RSS-DECODE-PREFLIGHT
    ( document-a document-u feed scratch scratch-u -- same status )
    3 PICK 0< IF SYN-S-INVALID EXIT THEN
    DUP 0< IF SYN-S-INVALID EXIT THEN
    3 PICK SYN-XML-DOCUMENT-CAP > IF SYN-S-CAPACITY EXIT THEN
    DUP RSS-FEED-SCRATCH-SIZE < IF SYN-S-CAPACITY EXIT THEN
    4 PICK 4 PICK SYN-SPAN-VALID? 0= IF SYN-S-INVALID EXIT THEN
    2 PICK RSS-FEED-SIZE SYN-SPAN-VALID? 0= IF SYN-S-INVALID EXIT THEN
    2DUP SYN-SPAN-VALID? 0= IF SYN-S-INVALID EXIT THEN
    4 PICK 4 PICK 3 PICK 3 PICK
        SYN-RANGES-OVERLAP? IF SYN-S-INVALID EXIT THEN
    2 PICK RSS-FEED-SIZE 3 PICK 3 PICK
        SYN-RANGES-OVERLAP? IF SYN-S-INVALID EXIT THEN
    SYN-S-OK ;

: RSS-FEED-DECODE
    ( document-a document-u feed scratch scratch-u -- status )
    _RSS-DECODE-PREFLIGHT DUP IF
        _SYN-DECODE-ARGS>STATUS EXIT
    THEN DROP
    _RSS-SCRATCH-U ! _RSS-SCRATCH ! _RSS-OUT ! _RSS-DOC-U ! _RSS-DOC-A !
    _RSS-SCRATCH @ RSS-FEED-INIT
    _RSS-DOC-A @ _RSS-DOC-U @ _RSS-SCRATCH @ _RSS-DECODE-INTO
        _RSS-STATUS !
    _RSS-STATUS @ SYN-S-OK = IF
        _RSS-SCRATCH @ _RSS-OUT @ RSS-FEED-SIZE CMOVE
    THEN
    _RSS-SCRATCH @ RSS-FEED-SCRATCH-SIZE 0 FILL _RSS-STATUS @ ;

VARIABLE _RSSP-ITEM
VARIABLE _RSSP-VIEW

: RSS-FEED-PROJECT-ITEM  ( item view -- status )
    _RSSP-VIEW ! _RSSP-ITEM !
    _RSSP-ITEM @ 0= _RSSP-VIEW @ 0= OR IF SYN-S-INVALID EXIT THEN
    _RSSP-VIEW @ SYN-PROJECTION-INIT
    SYN-FORMAT-RSS-2 _RSSP-VIEW @ _SYN-PROJ-FORMAT + !
    _RSSP-ITEM @ RSS.ITEM.IDENTITY-KIND @ RSS-IDENTITY-GUID = IF
        _RSSP-ITEM @ RSS.ITEM.GUID
    ELSE
        _RSSP-ITEM @ RSS.ITEM.LINK
    THEN
    _RSSP-VIEW @ _SYN-PROJ-ID-U + ! _RSSP-VIEW @ _SYN-PROJ-ID-A + !
    _RSSP-ITEM @ RSS.ITEM.TITLE
        _RSSP-VIEW @ _SYN-PROJ-TITLE-U + !
        _RSSP-VIEW @ _SYN-PROJ-TITLE-A + !
    _RSSP-ITEM @ RSS.ITEM.LINK
        _RSSP-VIEW @ _SYN-PROJ-URL-U + !
        _RSSP-VIEW @ _SYN-PROJ-URL-A + !
    _RSSP-ITEM @ RSS.ITEM.DESCRIPTION
        _RSSP-VIEW @ _SYN-PROJ-CONTENT-U + !
        _RSSP-VIEW @ _SYN-PROJ-CONTENT-A + !
    _RSSP-ITEM @ RSS.ITEM.PUBDATE
        _RSSP-VIEW @ _SYN-PROJ-PUBLISHED-U + !
        _RSSP-VIEW @ _SYN-PROJ-PUBLISHED-A + !
    SYN-S-OK ;
