\ =====================================================================
\  bluesky-text-record.f - Exact caller-owned Bluesky text post record
\ =====================================================================
\  Encodes one app.bsky.feed.post text record into caller-owned storage.
\  Trusted Unix epoch milliseconds are injected by the caller and formatted
\  as canonical whole-second UTC RFC3339.  A caller-owned staging workspace
\  makes every public failure destination-atomic, including subordinate
\  formatter/writer failures.
\ =====================================================================

REQUIRE ../utils/memory-span.f
REQUIRE ../utils/caller-span.f
REQUIRE ../utils/buffer-writer.f
REQUIRE ../utils/json-writer.f
REQUIRE ../utils/datetime.f

PROVIDED akashic-bsky-text-rec

0 CONSTANT BSKY-TEXT-RECORD-S-OK
1 CONSTANT BSKY-TEXT-RECORD-S-INVALID
2 CONSTANT BSKY-TEXT-RECORD-S-CAPACITY
3 CONSTANT BSKY-TEXT-RECORD-S-ALIAS
4 CONSTANT BSKY-TEXT-RECORD-S-UTF8
5 CONSTANT BSKY-TEXT-RECORD-S-TEXT
6 CONSTANT BSKY-TEXT-RECORD-S-RANGE
7 CONSTANT BSKY-TEXT-RECORD-S-PROTECTED
8 CONSTANT BSKY-TEXT-RECORD-S-PLATFORM
9 CONSTANT BSKY-TEXT-RECORD-S-INTERNAL

3000 CONSTANT BSKY-TEXT-RECORD-TEXT-MAX

\ A valid raw byte can expand to at most six JSON bytes (a C0 control).
\ The empty record is 75 bytes, including its two text quotes.
BSKY-TEXT-RECORD-TEXT-MAX 6 * 75 +
    CONSTANT BSKY-TEXT-RECORD-BODY-MAX

DT-EPOCH-S-MAX 1000 * 999 + CONSTANT _BSKYTR-EPOCH-MS-MAX
73 CONSTANT _BSKYTR-FIXED-BYTES

 0 CONSTANT _BSKYTRW-EPOCH-MS
 8 CONSTANT _BSKYTRW-TEXT-A
16 CONSTANT _BSKYTRW-TEXT-U
24 CONSTANT _BSKYTRW-DESTINATION
32 CONSTANT _BSKYTRW-CAPACITY
40 CONSTANT _BSKYTRW-BODY-U
48 CONSTANT _BSKYTRW-HEADER-SIZE

_BSKYTRW-HEADER-SIZE CONSTANT _BSKYTRW-WRITER-OFF
_BSKYTRW-WRITER-OFF CBW-SIZE + CONSTANT _BSKYTRW-TIMESTAMP-OFF
_BSKYTRW-TIMESTAMP-OFF DT-RFC3339-UTC-S-LENGTH +
    CONSTANT _BSKYTRW-STAGING-OFF
_BSKYTRW-STAGING-OFF BSKY-TEXT-RECORD-BODY-MAX + 7 + -8 AND
    CONSTANT BSKY-TEXT-RECORD-WORKSPACE-SIZE

: _BSKYTRW.EPOCH-MS     ( workspace -- field ) _BSKYTRW-EPOCH-MS + ;
: _BSKYTRW.TEXT-A       ( workspace -- field ) _BSKYTRW-TEXT-A + ;
: _BSKYTRW.TEXT-U       ( workspace -- field ) _BSKYTRW-TEXT-U + ;
: _BSKYTRW.DESTINATION  ( workspace -- field ) _BSKYTRW-DESTINATION + ;
: _BSKYTRW.CAPACITY     ( workspace -- field ) _BSKYTRW-CAPACITY + ;
: _BSKYTRW.BODY-U       ( workspace -- field ) _BSKYTRW-BODY-U + ;
: _BSKYTRW.WRITER       ( workspace -- writer ) _BSKYTRW-WRITER-OFF + ;
: _BSKYTRW.TIMESTAMP    ( workspace -- address ) _BSKYTRW-TIMESTAMP-OFF + ;
: _BSKYTRW.STAGING      ( workspace -- address ) _BSKYTRW-STAGING-OFF + ;

: BSKY-TEXT-RECORD-STATUS-VALID?  ( status -- flag )
    DUP BSKY-TEXT-RECORD-S-OK >=
    SWAP BSKY-TEXT-RECORD-S-INTERNAL <= AND ;

: _BSKYTR-6DUP  ( x1 x2 x3 x4 x5 x6 -- x1 x2 x3 x4 x5 x6 x1 x2 x3 x4 x5 x6 )
    5 PICK 5 PICK 5 PICK 5 PICK 5 PICK 5 PICK ;

: _BSKYTR-DROP6  ( x1 x2 x3 x4 x5 x6 -- )
    2DROP 2DROP 2DROP ;

: _BSKYTR-RETURN6  ( x1 x2 x3 x4 x5 x6 status -- status )
    >R _BSKYTR-DROP6 R> ;

: _BSKYTR-WIPE  ( workspace -- )
    BSKY-TEXT-RECORD-WORKSPACE-SIZE 0 FILL ;

: _BSKYTR-CALLER>STATUS  ( caller-status -- status )
    DUP CALLER-SPAN-S-OK = IF DROP BSKY-TEXT-RECORD-S-OK EXIT THEN
    DUP CALLER-SPAN-S-RANGE = IF DROP BSKY-TEXT-RECORD-S-RANGE EXIT THEN
    DUP CALLER-SPAN-S-PROTECTED = IF
        DROP BSKY-TEXT-RECORD-S-PROTECTED EXIT
    THEN
    DROP BSKY-TEXT-RECORD-S-PLATFORM ;

: _BSKYTR-FIXED-STATUS  ( address length -- status )
    OVER 0= IF 2DROP BSKY-TEXT-RECORD-S-INVALID EXIT THEN
    OVER 7 AND IF 2DROP BSKY-TEXT-RECORD-S-INVALID EXIT THEN
    CALLER-SPAN-STATUS _BSKYTR-CALLER>STATUS ;

: _BSKYTR-OUTPUT-STATUS  ( address capacity -- status )
    DUP 0< IF 2DROP BSKY-TEXT-RECORD-S-INVALID EXIT THEN
    DUP 0= IF 2DROP BSKY-TEXT-RECORD-S-CAPACITY EXIT THEN
    OVER 0= IF 2DROP BSKY-TEXT-RECORD-S-INVALID EXIT THEN
    CALLER-SPAN-STATUS _BSKYTR-CALLER>STATUS ;

: _BSKYTR-TEXT-STATUS  ( address length -- status )
    DUP 0< IF 2DROP BSKY-TEXT-RECORD-S-INVALID EXIT THEN
    DUP BSKY-TEXT-RECORD-TEXT-MAX > IF
        2DROP BSKY-TEXT-RECORD-S-TEXT EXIT
    THEN
    DUP 0= IF 2DROP BSKY-TEXT-RECORD-S-OK EXIT THEN
    OVER 0= IF 2DROP BSKY-TEXT-RECORD-S-INVALID EXIT THEN
    2DUP CALLER-SPAN-STATUS _BSKYTR-CALLER>STATUS
    DUP IF >R 2DROP R> EXIT THEN DROP
    UTF8-VALID? IF
        BSKY-TEXT-RECORD-S-OK
    ELSE
        BSKY-TEXT-RECORD-S-UTF8
    THEN ;

: BSKY-TEXT-RECORD-MEASURE  ( text-a text-u -- written status )
    2DUP _BSKYTR-TEXT-STATUS
    DUP IF >R 2DROP 0 R> EXIT THEN DROP
    JSONW-STRING-MEASURE
    DUP IF
        >R DROP 0
        R> CBW-S-CAPACITY = IF
            BSKY-TEXT-RECORD-S-CAPACITY
        ELSE
            BSKY-TEXT-RECORD-S-INTERNAL
        THEN
        EXIT
    THEN
    DROP _BSKYTR-FIXED-BYTES + BSKY-TEXT-RECORD-S-OK ;

: _BSKYTR-EPOCH-MS-VALID?  ( epoch-ms -- flag )
    DUP 0< IF DROP 0 EXIT THEN
    _BSKYTR-EPOCH-MS-MAX <= ;

: _BSKYTR-GEOMETRY
  \ ( epoch-ms text-a text-u destination capacity workspace -- status )
    DUP BSKY-TEXT-RECORD-WORKSPACE-SIZE _BSKYTR-FIXED-STATUS
    ?DUP IF _BSKYTR-RETURN6 EXIT THEN
    4 PICK 4 PICK _BSKYTR-TEXT-STATUS
    ?DUP IF _BSKYTR-RETURN6 EXIT THEN
    5 PICK _BSKYTR-EPOCH-MS-VALID? 0= IF
        _BSKYTR-DROP6 BSKY-TEXT-RECORD-S-RANGE EXIT
    THEN
    OVER 0< IF _BSKYTR-DROP6 BSKY-TEXT-RECORD-S-INVALID EXIT THEN
    4 PICK 4 PICK BSKY-TEXT-RECORD-MEASURE
    DUP IF
        >R DROP R> _BSKYTR-RETURN6 EXIT
    THEN
    DROP
    2 PICK OVER < IF
        DROP _BSKYTR-DROP6 BSKY-TEXT-RECORD-S-CAPACITY EXIT
    THEN
    DROP
    2 PICK 2 PICK _BSKYTR-OUTPUT-STATUS
    ?DUP IF _BSKYTR-RETURN6 EXIT THEN

    2 PICK 2 PICK 2 PICK BSKY-TEXT-RECORD-WORKSPACE-SIZE
    MSPAN-OVERLAP? IF
        _BSKYTR-DROP6 BSKY-TEXT-RECORD-S-ALIAS EXIT
    THEN
    4 PICK 4 PICK 4 PICK 4 PICK MSPAN-OVERLAP? IF
        _BSKYTR-DROP6 BSKY-TEXT-RECORD-S-ALIAS EXIT
    THEN
    4 PICK 4 PICK 2 PICK BSKY-TEXT-RECORD-WORKSPACE-SIZE
    MSPAN-OVERLAP? IF
        _BSKYTR-DROP6 BSKY-TEXT-RECORD-S-ALIAS EXIT
    THEN
    _BSKYTR-DROP6 BSKY-TEXT-RECORD-S-OK ;

: BSKY-TEXT-RECORD-WORKSPACE-CLEAR  ( workspace -- status )
    DUP BSKY-TEXT-RECORD-WORKSPACE-SIZE _BSKYTR-FIXED-STATUS
    DUP IF NIP EXIT THEN DROP
    _BSKYTR-WIPE BSKY-TEXT-RECORD-S-OK ;

: _BSKYTR-SUBORDINATE-STATUS  ( writer-status -- status )
    CBW-S-OK = IF
        BSKY-TEXT-RECORD-S-OK
    ELSE
        BSKY-TEXT-RECORD-S-INTERNAL
    THEN ;

: _BSKYTR-CHAR  ( character workspace -- status )
    _BSKYTRW.WRITER CBW-CHAR _BSKYTR-SUBORDINATE-STATUS ;

: _BSKYTR-STRING  ( address length workspace -- status )
    _BSKYTRW.WRITER JSONW-STRING _BSKYTR-SUBORDINATE-STATUS ;

: _BSKYTR-ENCODE-STAGING  ( workspace -- status )
    >R
    [CHAR] { R@ _BSKYTR-CHAR ?DUP IF R> DROP EXIT THEN
    S" $type" R@ _BSKYTR-STRING ?DUP IF R> DROP EXIT THEN
    [CHAR] : R@ _BSKYTR-CHAR ?DUP IF R> DROP EXIT THEN
    S" app.bsky.feed.post" R@ _BSKYTR-STRING ?DUP IF R> DROP EXIT THEN
    [CHAR] , R@ _BSKYTR-CHAR ?DUP IF R> DROP EXIT THEN
    S" text" R@ _BSKYTR-STRING ?DUP IF R> DROP EXIT THEN
    [CHAR] : R@ _BSKYTR-CHAR ?DUP IF R> DROP EXIT THEN
    R@ _BSKYTRW.TEXT-A @ R@ _BSKYTRW.TEXT-U @
    R@ _BSKYTR-STRING ?DUP IF R> DROP EXIT THEN
    [CHAR] , R@ _BSKYTR-CHAR ?DUP IF R> DROP EXIT THEN
    S" createdAt" R@ _BSKYTR-STRING ?DUP IF R> DROP EXIT THEN
    [CHAR] : R@ _BSKYTR-CHAR ?DUP IF R> DROP EXIT THEN
    R@ _BSKYTRW.TIMESTAMP DT-RFC3339-UTC-S-LENGTH
    R@ _BSKYTR-STRING ?DUP IF R> DROP EXIT THEN
    [CHAR] } R@ _BSKYTR-CHAR ?DUP IF R> DROP EXIT THEN
    R> DROP BSKY-TEXT-RECORD-S-OK ;

: _BSKYTR-SAVE  ( epoch-ms text-a text-u destination capacity workspace -- workspace )
    DUP _BSKYTR-WIPE
    DUP >R DROP
    R@ _BSKYTRW.CAPACITY !
    R@ _BSKYTRW.DESTINATION !
    R@ _BSKYTRW.TEXT-U !
    R@ _BSKYTRW.TEXT-A !
    R@ _BSKYTRW.EPOCH-MS !
    R> ;

: _BSKYTR-OP  ( workspace -- written status )
    >R
    R@ _BSKYTRW.EPOCH-MS @ 1000 /
    R@ _BSKYTRW.TIMESTAMP DT-RFC3339-UTC-S-LENGTH
    DT-RFC3339-UTC-S
    DUP IF
        2DROP R> DROP 0 BSKY-TEXT-RECORD-S-INTERNAL EXIT
    THEN
    DROP DT-RFC3339-UTC-S-LENGTH <> IF
        R> DROP 0 BSKY-TEXT-RECORD-S-INTERNAL EXIT
    THEN

    R@ _BSKYTRW.STAGING BSKY-TEXT-RECORD-BODY-MAX
    R@ _BSKYTRW.WRITER CBW-INIT CBW-S-OK <> IF
        R> DROP 0 BSKY-TEXT-RECORD-S-INTERNAL EXIT
    THEN
    R@ _BSKYTR-ENCODE-STAGING ?DUP IF
        R> DROP 0 SWAP EXIT
    THEN
    R@ _BSKYTRW.WRITER CBW-RESULT
    DUP CBW-S-OK <> IF
        DROP 2DROP R> DROP 0 BSKY-TEXT-RECORD-S-INTERNAL EXIT
    THEN
    DROP
    DUP R@ _BSKYTRW.BODY-U @ <> IF
        2DROP R> DROP 0 BSKY-TEXT-RECORD-S-INTERNAL EXIT
    THEN
    OVER R@ _BSKYTRW.DESTINATION @ 2 PICK MOVE
    NIP R> DROP BSKY-TEXT-RECORD-S-OK ;

: BSKY-TEXT-RECORD-ENCODE
  \ ( epoch-ms text-a text-u destination capacity workspace -- written status )
    _BSKYTR-6DUP _BSKYTR-GEOMETRY
    DUP IF >R _BSKYTR-DROP6 0 R> EXIT THEN DROP
    _BSKYTR-SAVE
    DUP _BSKYTRW.TEXT-A @ OVER _BSKYTRW.TEXT-U @
    BSKY-TEXT-RECORD-MEASURE
    DUP IF
        >R DROP _BSKYTR-WIPE 0 R> EXIT
    THEN
    DROP OVER _BSKYTRW.BODY-U !
    DUP _BSKYTR-OP
    2>R _BSKYTR-WIPE 2R> ;
