\ =====================================================================
\  oauth-remote-hres.f - Retained remote-JWKS AT OAuth deployment
\ =====================================================================
\  This state-free adapter derives a bounded HTTPS jwks_uri target from one
\  retained Client Identifier Metadata HRES result, then composes that
\  metadata result and one separately retained JWK Set HRES result with the
\  provider-neutral published P-256 key owner.
\
\  The caller owns both HRES lifecycles, both complete response buffers, the
\  derived target, the credential vault, and all workspaces.  This module
\  performs no DNS, HTTP, TLS, deadlines, leases, redirects, PAR, browser,
\  token, session, XRPC, or Streams work.
\
\  Public API:
\    AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
\    AT-OAUTH-REMOTE-HRES-WORKSPACE-CLEAR
\    AT-OAUTH-REMOTE-HRES-SPEC-POLICY!
\    AT-OAUTH-REMOTE-HRES-STATUS-VALID?
\    AT-OAUTH-REMOTE-HRES-JWKS-TARGET!
\    AT-OAUTH-REMOTE-HRES-WITH
\ =====================================================================

\ KDOS module identities are bounded to 23 bytes.
PROVIDED akashic-at-oauth-rhres

REQUIRE ../utils/memory-span.f
REQUIRE ../utils/caller-span.f
REQUIRE ../net/http-target.f
REQUIRE ../security/credential-vault.f
REQUIRE ../security/oauth2/client-config.f
REQUIRE ../security/oauth2/client-metadata.f
REQUIRE ../security/oauth2/published-key-p256.f
REQUIRE oauth-hres.f
REQUIRE oauth-profile.f
REQUIRE oauth-deployment.f

\ =====================================================================
\  Public status vocabulary
\ =====================================================================

0  CONSTANT AT-OAUTH-REMOTE-HRES-S-OK
1  CONSTANT AT-OAUTH-REMOTE-HRES-S-INVALID
2  CONSTANT AT-OAUTH-REMOTE-HRES-S-CAPACITY
3  CONSTANT AT-OAUTH-REMOTE-HRES-S-ALIAS
4  CONSTANT AT-OAUTH-REMOTE-HRES-S-CONFIG
5  CONSTANT AT-OAUTH-REMOTE-HRES-S-PROFILE
6  CONSTANT AT-OAUTH-REMOTE-HRES-S-METADATA
7  CONSTANT AT-OAUTH-REMOTE-HRES-S-CLIENT-ID
8  CONSTANT AT-OAUTH-REMOTE-HRES-S-APPLICATION
9  CONSTANT AT-OAUTH-REMOTE-HRES-S-GRANT
10 CONSTANT AT-OAUTH-REMOTE-HRES-S-RESPONSE
11 CONSTANT AT-OAUTH-REMOTE-HRES-S-REDIRECT
12 CONSTANT AT-OAUTH-REMOTE-HRES-S-SCOPE
13 CONSTANT AT-OAUTH-REMOTE-HRES-S-AUTH-METHOD
14 CONSTANT AT-OAUTH-REMOTE-HRES-S-AUTH-ALGORITHM
15 CONSTANT AT-OAUTH-REMOTE-HRES-S-DPOP
16 CONSTANT AT-OAUTH-REMOTE-HRES-S-KEY-SOURCE
17 CONSTANT AT-OAUTH-REMOTE-HRES-S-BINDING
18 CONSTANT AT-OAUTH-REMOTE-HRES-S-JWKS
19 CONSTANT AT-OAUTH-REMOTE-HRES-S-NOT-FOUND
20 CONSTANT AT-OAUTH-REMOTE-HRES-S-ABSENT
21 CONSTANT AT-OAUTH-REMOTE-HRES-S-REVOKED
22 CONSTANT AT-OAUTH-REMOTE-HRES-S-CONFLICT
23 CONSTANT AT-OAUTH-REMOTE-HRES-S-BUSY
24 CONSTANT AT-OAUTH-REMOTE-HRES-S-LOCKED
25 CONSTANT AT-OAUTH-REMOTE-HRES-S-ENTROPY
26 CONSTANT AT-OAUTH-REMOTE-HRES-S-CRYPTO
27 CONSTANT AT-OAUTH-REMOTE-HRES-S-AUTH
28 CONSTANT AT-OAUTH-REMOTE-HRES-S-CORRUPT
29 CONSTANT AT-OAUTH-REMOTE-HRES-S-UNSUPPORTED
30 CONSTANT AT-OAUTH-REMOTE-HRES-S-IO
31 CONSTANT AT-OAUTH-REMOTE-HRES-S-RECOVERY
32 CONSTANT AT-OAUTH-REMOTE-HRES-S-ROLLBACK
33 CONSTANT AT-OAUTH-REMOTE-HRES-S-FORMAT
34 CONSTANT AT-OAUTH-REMOTE-HRES-S-KEY
35 CONSTANT AT-OAUTH-REMOTE-HRES-S-MISMATCH
36 CONSTANT AT-OAUTH-REMOTE-HRES-S-DISTINCT
37 CONSTANT AT-OAUTH-REMOTE-HRES-S-CALLBACK
38 CONSTANT AT-OAUTH-REMOTE-HRES-S-INTERNAL
39 CONSTANT AT-OAUTH-REMOTE-HRES-S-RANGE
40 CONSTANT AT-OAUTH-REMOTE-HRES-S-PROTECTED
41 CONSTANT AT-OAUTH-REMOTE-HRES-S-PLATFORM
42 CONSTANT AT-OAUTH-REMOTE-HRES-S-METADATA-HTTP
43 CONSTANT AT-OAUTH-REMOTE-HRES-S-JWKS-TARGET
44 CONSTANT AT-OAUTH-REMOTE-HRES-S-JWKS-HTTP

: AT-OAUTH-REMOTE-HRES-STATUS-VALID?  ( status -- flag )
    DUP AT-OAUTH-REMOTE-HRES-S-OK >=
    SWAP AT-OAUTH-REMOTE-HRES-S-JWKS-HTTP <= AND ;

: AT-OAUTH-REMOTE-HRES-SPEC-POLICY!  ( spec -- hres-status )
    AT-OAUTH-HRES-SPEC-POLICY! ;

\ =====================================================================
\  Caller-owned workspaces
\ =====================================================================

  0 CONSTANT _ATORW-METADATA-RESOURCE
  8 CONSTANT _ATORW-JWKS-RESOURCE
 16 CONSTANT _ATORW-CONFIG
 24 CONSTANT _ATORW-PROFILE
 32 CONSTANT _ATORW-VAULT
 40 CONSTANT _ATORW-CALLBACK
 48 CONSTANT _ATORW-CONTEXT
56 CONSTANT _ATORW-TARGET-OUTPUT
64 CONSTANT _ATORW-CONFIG-VIEW
72 CONSTANT _ATORW-METADATA-VIEW
80 CONSTANT _ATORW-CALLBACK-RESULT
88 CONSTANT _ATORW-APPLICATION-DEPTH

96 CONSTANT _ATORW-STAGED-TARGET-OFF
_ATORW-STAGED-TARGET-OFF HTARGET-SIZE +
    CONSTANT _ATORW-DEPLOYMENT-OFF
_ATORW-DEPLOYMENT-OFF AT-OAUTH-DEPLOYMENT-WORKSPACE-SIZE +
    CONSTANT _ATORW-PUBLISHED-OFF
_ATORW-PUBLISHED-OFF OAUTH2-P256-PUBLISHED-WORKSPACE-SIZE +
    CONSTANT AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE

: _ATORW.METADATA-RESOURCE  ( workspace -- field )
    _ATORW-METADATA-RESOURCE + ;
: _ATORW.JWKS-RESOURCE  ( workspace -- field )
    _ATORW-JWKS-RESOURCE + ;
: _ATORW.CONFIG  ( workspace -- field ) _ATORW-CONFIG + ;
: _ATORW.PROFILE  ( workspace -- field ) _ATORW-PROFILE + ;
: _ATORW.VAULT  ( workspace -- field ) _ATORW-VAULT + ;
: _ATORW.CALLBACK  ( workspace -- field ) _ATORW-CALLBACK + ;
: _ATORW.CONTEXT  ( workspace -- field ) _ATORW-CONTEXT + ;
: _ATORW.TARGET-OUTPUT  ( workspace -- field )
    _ATORW-TARGET-OUTPUT + ;
: _ATORW.CONFIG-VIEW  ( workspace -- field ) _ATORW-CONFIG-VIEW + ;
: _ATORW.METADATA-VIEW  ( workspace -- field )
    _ATORW-METADATA-VIEW + ;
: _ATORW.CALLBACK-RESULT  ( workspace -- field )
    _ATORW-CALLBACK-RESULT + ;
: _ATORW.APPLICATION-DEPTH  ( workspace -- field )
    _ATORW-APPLICATION-DEPTH + ;

: _ATORW.STAGED-TARGET  ( workspace -- target )
    _ATORW-STAGED-TARGET-OFF + ;
: _ATORW.DEPLOYMENT  ( workspace -- child-workspace )
    _ATORW-DEPLOYMENT-OFF + ;
: _ATORW.PUBLISHED  ( workspace -- child-workspace )
    _ATORW-PUBLISHED-OFF + ;

: _ATOR-WIPE  ( workspace -- )
    AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE 0 FILL ;

\ =====================================================================
\  Small stack and byte helpers
\ =====================================================================

: _ATOR-DROP3  ( x1 x2 x3 -- ) 2DROP DROP ;
: _ATOR-DROP4  ( x1 x2 x3 x4 -- ) 2DROP 2DROP ;
: _ATOR-DROP5  ( five-values -- ) 2DROP 2DROP DROP ;
: _ATOR-DROP6  ( six-values -- ) 2DROP 2DROP 2DROP ;
: _ATOR-DROP8  ( eight-values -- ) 2DROP 2DROP 2DROP 2DROP ;

: _ATOR-5DUP  ( five-values -- the-same-five-values twice )
    4 PICK 4 PICK 4 PICK 4 PICK 4 PICK ;

: _ATOR-8DUP  ( eight-values -- the-same-eight-values twice )
    7 PICK 7 PICK 7 PICK 7 PICK
    7 PICK 7 PICK 7 PICK 7 PICK ;

: _ATOR-RETURN5  ( five-values status -- status )
    >R _ATOR-DROP5 R> ;

: _ATOR-RETURN5-FAIL
  ( five-values status -- status )
    _ATOR-RETURN5 ;

: _ATOR-RETURN8  ( eight-values status -- status )
    >R _ATOR-DROP8 R> ;

: _ATOR-RETURN8-FAIL
  ( eight-values status -- callback-result status )
    >R _ATOR-DROP8 0 R> ;

: _ATOR-BYTES=  ( first-a first-u second-a second-u -- flag )
    COMPARE 0= ;

: _ATOR-BODY-OVERLAP?
  ( resource object-a object-u -- flag )
    >R >R HRES-BODY-STORAGE@ R> R> MSPAN-OVERLAP? ;

: _ATOR-BODIES-OVERLAP?  ( first-resource second-resource -- flag )
    >R HRES-BODY-STORAGE@ R> HRES-BODY-STORAGE@
    MSPAN-OVERLAP? ;

\ =====================================================================
\  Explicit subordinate status mappings
\ =====================================================================

: _ATOR-CALLER>STATUS  ( caller-status -- status )
    CASE
        CALLER-SPAN-S-OK OF AT-OAUTH-REMOTE-HRES-S-OK ENDOF
        CALLER-SPAN-S-RANGE OF AT-OAUTH-REMOTE-HRES-S-RANGE ENDOF
        CALLER-SPAN-S-PROTECTED OF
            AT-OAUTH-REMOTE-HRES-S-PROTECTED
        ENDOF
        CALLER-SPAN-S-PLATFORM OF
            AT-OAUTH-REMOTE-HRES-S-PLATFORM
        ENDOF
        AT-OAUTH-REMOTE-HRES-S-PLATFORM SWAP
    ENDCASE ;

: _ATOR-CVAULT>STATUS  ( vault-status -- status )
    CASE
        CVAULT-S-OK OF AT-OAUTH-REMOTE-HRES-S-OK ENDOF
        CVAULT-S-INVALID OF AT-OAUTH-REMOTE-HRES-S-INVALID ENDOF
        CVAULT-S-BUSY OF AT-OAUTH-REMOTE-HRES-S-BUSY ENDOF
        CVAULT-S-RANGE OF AT-OAUTH-REMOTE-HRES-S-RANGE ENDOF
        CVAULT-S-PROTECTED OF
            AT-OAUTH-REMOTE-HRES-S-PROTECTED
        ENDOF
        CVAULT-S-PLATFORM OF
            AT-OAUTH-REMOTE-HRES-S-PLATFORM
        ENDOF
        AT-OAUTH-REMOTE-HRES-S-INTERNAL SWAP
    ENDCASE ;

: _ATOR-CONFIG>STATUS  ( config-status -- status )
    CASE
        OAUTH2-CLIENT-CONFIG-S-INVALID OF
            AT-OAUTH-REMOTE-HRES-S-CONFIG
        ENDOF
        OAUTH2-CLIENT-CONFIG-S-RANGE OF
            AT-OAUTH-REMOTE-HRES-S-RANGE
        ENDOF
        OAUTH2-CLIENT-CONFIG-S-PROTECTED OF
            AT-OAUTH-REMOTE-HRES-S-PROTECTED
        ENDOF
        OAUTH2-CLIENT-CONFIG-S-PLATFORM OF
            AT-OAUTH-REMOTE-HRES-S-PLATFORM
        ENDOF
        AT-OAUTH-REMOTE-HRES-S-INTERNAL SWAP
    ENDCASE ;

: _ATOR-DEPLOYMENT>STATUS  ( deployment-status -- status )
    CASE
        AT-OAUTH-DEPLOYMENT-S-OK OF
            AT-OAUTH-REMOTE-HRES-S-OK
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-INVALID OF
            AT-OAUTH-REMOTE-HRES-S-INVALID
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-CAPACITY OF
            AT-OAUTH-REMOTE-HRES-S-CAPACITY
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-ALIAS OF
            AT-OAUTH-REMOTE-HRES-S-ALIAS
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-CONFIG OF
            AT-OAUTH-REMOTE-HRES-S-CONFIG
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-PROFILE OF
            AT-OAUTH-REMOTE-HRES-S-PROFILE
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-METADATA OF
            AT-OAUTH-REMOTE-HRES-S-METADATA
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-CLIENT-ID OF
            AT-OAUTH-REMOTE-HRES-S-CLIENT-ID
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-APPLICATION OF
            AT-OAUTH-REMOTE-HRES-S-APPLICATION
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-GRANT OF
            AT-OAUTH-REMOTE-HRES-S-GRANT
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-RESPONSE OF
            AT-OAUTH-REMOTE-HRES-S-RESPONSE
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-REDIRECT OF
            AT-OAUTH-REMOTE-HRES-S-REDIRECT
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-SCOPE OF
            AT-OAUTH-REMOTE-HRES-S-SCOPE
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-AUTH-METHOD OF
            AT-OAUTH-REMOTE-HRES-S-AUTH-METHOD
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-AUTH-ALGORITHM OF
            AT-OAUTH-REMOTE-HRES-S-AUTH-ALGORITHM
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-DPOP OF
            AT-OAUTH-REMOTE-HRES-S-DPOP
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-KEY-SOURCE OF
            AT-OAUTH-REMOTE-HRES-S-KEY-SOURCE
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-CALLBACK OF
            AT-OAUTH-REMOTE-HRES-S-INTERNAL
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-INTERNAL OF
            AT-OAUTH-REMOTE-HRES-S-INTERNAL
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-RANGE OF
            AT-OAUTH-REMOTE-HRES-S-RANGE
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-PROTECTED OF
            AT-OAUTH-REMOTE-HRES-S-PROTECTED
        ENDOF
        AT-OAUTH-DEPLOYMENT-S-PLATFORM OF
            AT-OAUTH-REMOTE-HRES-S-PLATFORM
        ENDOF
        AT-OAUTH-REMOTE-HRES-S-INTERNAL SWAP
    ENDCASE ;

: _ATOR-PUBLISHED>STATUS  ( published-status -- status )
    CASE
        OAUTH2-P256-PUBLISHED-S-OK OF
            AT-OAUTH-REMOTE-HRES-S-OK
        ENDOF
        OAUTH2-P256-PUBLISHED-S-INVALID OF
            AT-OAUTH-REMOTE-HRES-S-INTERNAL
        ENDOF
        OAUTH2-P256-PUBLISHED-S-CAPACITY OF
            AT-OAUTH-REMOTE-HRES-S-CAPACITY
        ENDOF
        OAUTH2-P256-PUBLISHED-S-ALIAS OF
            AT-OAUTH-REMOTE-HRES-S-ALIAS
        ENDOF
        OAUTH2-P256-PUBLISHED-S-BINDING OF
            AT-OAUTH-REMOTE-HRES-S-BINDING
        ENDOF
        OAUTH2-P256-PUBLISHED-S-JWKS OF
            AT-OAUTH-REMOTE-HRES-S-JWKS
        ENDOF
        OAUTH2-P256-PUBLISHED-S-NOT-FOUND OF
            AT-OAUTH-REMOTE-HRES-S-NOT-FOUND
        ENDOF
        OAUTH2-P256-PUBLISHED-S-ABSENT OF
            AT-OAUTH-REMOTE-HRES-S-ABSENT
        ENDOF
        OAUTH2-P256-PUBLISHED-S-REVOKED OF
            AT-OAUTH-REMOTE-HRES-S-REVOKED
        ENDOF
        OAUTH2-P256-PUBLISHED-S-CONFLICT OF
            AT-OAUTH-REMOTE-HRES-S-CONFLICT
        ENDOF
        OAUTH2-P256-PUBLISHED-S-BUSY OF
            AT-OAUTH-REMOTE-HRES-S-BUSY
        ENDOF
        OAUTH2-P256-PUBLISHED-S-LOCKED OF
            AT-OAUTH-REMOTE-HRES-S-LOCKED
        ENDOF
        OAUTH2-P256-PUBLISHED-S-ENTROPY OF
            AT-OAUTH-REMOTE-HRES-S-ENTROPY
        ENDOF
        OAUTH2-P256-PUBLISHED-S-CRYPTO OF
            AT-OAUTH-REMOTE-HRES-S-CRYPTO
        ENDOF
        OAUTH2-P256-PUBLISHED-S-AUTH OF
            AT-OAUTH-REMOTE-HRES-S-AUTH
        ENDOF
        OAUTH2-P256-PUBLISHED-S-CORRUPT OF
            AT-OAUTH-REMOTE-HRES-S-CORRUPT
        ENDOF
        OAUTH2-P256-PUBLISHED-S-UNSUPPORTED OF
            AT-OAUTH-REMOTE-HRES-S-UNSUPPORTED
        ENDOF
        OAUTH2-P256-PUBLISHED-S-IO OF
            AT-OAUTH-REMOTE-HRES-S-IO
        ENDOF
        OAUTH2-P256-PUBLISHED-S-RECOVERY OF
            AT-OAUTH-REMOTE-HRES-S-RECOVERY
        ENDOF
        OAUTH2-P256-PUBLISHED-S-ROLLBACK OF
            AT-OAUTH-REMOTE-HRES-S-ROLLBACK
        ENDOF
        OAUTH2-P256-PUBLISHED-S-FORMAT OF
            AT-OAUTH-REMOTE-HRES-S-FORMAT
        ENDOF
        OAUTH2-P256-PUBLISHED-S-KEY OF
            AT-OAUTH-REMOTE-HRES-S-KEY
        ENDOF
        OAUTH2-P256-PUBLISHED-S-MISMATCH OF
            AT-OAUTH-REMOTE-HRES-S-MISMATCH
        ENDOF
        OAUTH2-P256-PUBLISHED-S-DISTINCT OF
            AT-OAUTH-REMOTE-HRES-S-DISTINCT
        ENDOF
        OAUTH2-P256-PUBLISHED-S-CALLBACK OF
            AT-OAUTH-REMOTE-HRES-S-CALLBACK
        ENDOF
        OAUTH2-P256-PUBLISHED-S-INTERNAL OF
            AT-OAUTH-REMOTE-HRES-S-INTERNAL
        ENDOF
        OAUTH2-P256-PUBLISHED-S-RANGE OF
            AT-OAUTH-REMOTE-HRES-S-RANGE
        ENDOF
        OAUTH2-P256-PUBLISHED-S-PROTECTED OF
            AT-OAUTH-REMOTE-HRES-S-PROTECTED
        ENDOF
        OAUTH2-P256-PUBLISHED-S-PLATFORM OF
            AT-OAUTH-REMOTE-HRES-S-PLATFORM
        ENDOF
        AT-OAUTH-REMOTE-HRES-S-INTERNAL SWAP
    ENDCASE ;

\ =====================================================================
\  Caller-memory admission
\ =====================================================================

: _ATOR-SPAN-STATUS  ( address length -- status )
    DUP 0< IF
        2DROP AT-OAUTH-REMOTE-HRES-S-INVALID EXIT
    THEN
    DUP 0= IF
        2DROP AT-OAUTH-REMOTE-HRES-S-OK EXIT
    THEN
    OVER 0= IF
        2DROP AT-OAUTH-REMOTE-HRES-S-INVALID EXIT
    THEN
    CALLER-SPAN-STATUS _ATOR-CALLER>STATUS ;

: _ATOR-FIXED-STATUS  ( address length -- status )
    OVER 0= IF
        2DROP AT-OAUTH-REMOTE-HRES-S-INVALID EXIT
    THEN
    OVER 7 AND IF
        2DROP AT-OAUTH-REMOTE-HRES-S-INVALID EXIT
    THEN
    _ATOR-SPAN-STATUS ;

: _ATOR-EXTERNAL-STATUS  ( address length vault -- status )
    CVAULT-EXTERNAL-SPAN-STATUS _ATOR-CVAULT>STATUS ;

: AT-OAUTH-REMOTE-HRES-WORKSPACE-CLEAR  ( workspace -- status )
    DUP AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    _ATOR-FIXED-STATUS
    ?DUP IF NIP EXIT THEN
    _ATOR-WIPE
    AT-OAUTH-REMOTE-HRES-S-OK ;

\ Stack on entry is metadata-resource, config, profile, target, workspace.
: _ATOR-TARGET-GEOMETRY
  ( metadata-resource config profile target workspace -- status )
    4 PICK HTTP-RESOURCE-SIZE _ATOR-SPAN-STATUS
    ?DUP IF _ATOR-RETURN5 EXIT THEN
    3 PICK OAUTH2-CLIENT-CONFIG-SIZE _ATOR-FIXED-STATUS
    ?DUP IF _ATOR-RETURN5 EXIT THEN
    2 PICK AT-OAUTH-PROFILE-SIZE _ATOR-FIXED-STATUS
    ?DUP IF _ATOR-RETURN5 EXIT THEN
    1 PICK HTARGET-SIZE _ATOR-FIXED-STATUS
    ?DUP IF _ATOR-RETURN5 EXIT THEN
    DUP AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    _ATOR-FIXED-STATUS
    ?DUP IF _ATOR-RETURN5 EXIT THEN

    4 PICK HRES-VALID? 0= IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-METADATA-HTTP EXIT
    THEN
    4 PICK HRES-BODY-STORAGE@ _ATOR-SPAN-STATUS
    ?DUP IF _ATOR-RETURN5 EXIT THEN

    4 PICK HTTP-RESOURCE-SIZE
    5 PICK OAUTH2-CLIENT-CONFIG-SIZE MSPAN-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    4 PICK HTTP-RESOURCE-SIZE
    4 PICK AT-OAUTH-PROFILE-SIZE MSPAN-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    4 PICK HTTP-RESOURCE-SIZE
    3 PICK HTARGET-SIZE MSPAN-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    4 PICK HTTP-RESOURCE-SIZE
    2 PICK AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    MSPAN-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN

    3 PICK OAUTH2-CLIENT-CONFIG-SIZE
    3 PICK HTARGET-SIZE MSPAN-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    3 PICK OAUTH2-CLIENT-CONFIG-SIZE
    2 PICK AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    MSPAN-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    2 PICK AT-OAUTH-PROFILE-SIZE
    3 PICK HTARGET-SIZE MSPAN-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    2 PICK AT-OAUTH-PROFILE-SIZE
    2 PICK AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    MSPAN-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    1 PICK HTARGET-SIZE
    2 PICK AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    MSPAN-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN

    4 PICK 5 PICK HTTP-RESOURCE-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    4 PICK 4 PICK OAUTH2-CLIENT-CONFIG-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    4 PICK 3 PICK AT-OAUTH-PROFILE-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    4 PICK 2 PICK HTARGET-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    4 PICK 1 PICK AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN

    _ATOR-DROP5 AT-OAUTH-REMOTE-HRES-S-OK ;

\ Stack is metadata-resource, jwks-resource, config, profile, vault,
\ callback, context, workspace.
: _ATOR-GEOMETRY
  ( metadata-resource jwks-resource config profile vault callback context workspace -- status )
    7 PICK HTTP-RESOURCE-SIZE _ATOR-SPAN-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    6 PICK HTTP-RESOURCE-SIZE _ATOR-SPAN-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    5 PICK OAUTH2-CLIENT-CONFIG-SIZE _ATOR-FIXED-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    4 PICK AT-OAUTH-PROFILE-SIZE _ATOR-FIXED-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    3 PICK CVAULT-SIZE _ATOR-SPAN-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    DUP AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    _ATOR-FIXED-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    2 PICK 0= IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-INVALID EXIT
    THEN

    7 PICK HRES-VALID? 0= IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-METADATA-HTTP EXIT
    THEN
    6 PICK HRES-VALID? 0= IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-JWKS-HTTP EXIT
    THEN

    7 PICK HRES-BODY-STORAGE@ _ATOR-SPAN-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    6 PICK HRES-BODY-STORAGE@ _ATOR-SPAN-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN

    7 PICK HTTP-RESOURCE-SIZE 5 PICK _ATOR-EXTERNAL-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    6 PICK HTTP-RESOURCE-SIZE 5 PICK _ATOR-EXTERNAL-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    5 PICK OAUTH2-CLIENT-CONFIG-SIZE
    5 PICK _ATOR-EXTERNAL-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    4 PICK AT-OAUTH-PROFILE-SIZE 5 PICK
    _ATOR-EXTERNAL-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    DUP AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    5 PICK _ATOR-EXTERNAL-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    7 PICK HRES-BODY-STORAGE@
    5 PICK _ATOR-EXTERNAL-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN
    6 PICK HRES-BODY-STORAGE@
    5 PICK _ATOR-EXTERNAL-STATUS
    ?DUP IF _ATOR-RETURN8 EXIT THEN

    7 PICK HTTP-RESOURCE-SIZE
    8 PICK HTTP-RESOURCE-SIZE MSPAN-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    7 PICK HTTP-RESOURCE-SIZE
    7 PICK OAUTH2-CLIENT-CONFIG-SIZE MSPAN-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    7 PICK HTTP-RESOURCE-SIZE
    6 PICK AT-OAUTH-PROFILE-SIZE MSPAN-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    7 PICK HTTP-RESOURCE-SIZE
    2 PICK AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    MSPAN-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN

    6 PICK HTTP-RESOURCE-SIZE
    7 PICK OAUTH2-CLIENT-CONFIG-SIZE MSPAN-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    6 PICK HTTP-RESOURCE-SIZE
    6 PICK AT-OAUTH-PROFILE-SIZE MSPAN-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    6 PICK HTTP-RESOURCE-SIZE
    2 PICK AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    MSPAN-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN

    5 PICK OAUTH2-CLIENT-CONFIG-SIZE
    2 PICK AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    MSPAN-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    4 PICK AT-OAUTH-PROFILE-SIZE
    2 PICK AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    MSPAN-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN

    7 PICK 8 PICK HTTP-RESOURCE-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    7 PICK 7 PICK HTTP-RESOURCE-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    7 PICK 6 PICK OAUTH2-CLIENT-CONFIG-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    7 PICK 5 PICK AT-OAUTH-PROFILE-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    7 PICK 1 PICK AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN

    6 PICK 8 PICK HTTP-RESOURCE-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    6 PICK 7 PICK HTTP-RESOURCE-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    6 PICK 6 PICK OAUTH2-CLIENT-CONFIG-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    6 PICK 5 PICK AT-OAUTH-PROFILE-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN
    6 PICK 1 PICK AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE
    _ATOR-BODY-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN

    7 PICK 7 PICK _ATOR-BODIES-OVERLAP? IF
        _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-ALIAS EXIT
    THEN

    _ATOR-DROP8 AT-OAUTH-REMOTE-HRES-S-OK ;

\ =====================================================================
\  Retained-resource provenance and remote source admission
\ =====================================================================

: _ATOR-METADATA-ENVELOPE-STATUS
  ( metadata-resource config -- status )
    DUP OAUTH2-CLIENT-CONFIG-CLIENT-ID@
    DUP OAUTH2-CLIENT-CONFIG-S-OK <> IF
        >R 2DROP 2DROP R> _ATOR-CONFIG>STATUS EXIT
    THEN
    DROP
    2SWAP DROP -ROT
    AT-OAUTH-HRES-URI-ENVELOPE?
    IF
        AT-OAUTH-REMOTE-HRES-S-OK
    ELSE
        AT-OAUTH-REMOTE-HRES-S-METADATA-HTTP
    THEN ;

: _ATOR-TARGET>STATUS  ( target-status -- status )
    CASE
        HTARGET-S-OK OF AT-OAUTH-REMOTE-HRES-S-OK ENDOF
        HTARGET-S-CAPACITY OF AT-OAUTH-REMOTE-HRES-S-CAPACITY ENDOF
        HTARGET-S-INVALID OF
            AT-OAUTH-REMOTE-HRES-S-JWKS-TARGET
        ENDOF
        HTARGET-S-SCHEME OF
            AT-OAUTH-REMOTE-HRES-S-JWKS-TARGET
        ENDOF
        HTARGET-S-AUTHORITY OF
            AT-OAUTH-REMOTE-HRES-S-JWKS-TARGET
        ENDOF
        HTARGET-S-HOST OF
            AT-OAUTH-REMOTE-HRES-S-JWKS-TARGET
        ENDOF
        HTARGET-S-PORT OF
            AT-OAUTH-REMOTE-HRES-S-JWKS-TARGET
        ENDOF
        HTARGET-S-PATH OF
            AT-OAUTH-REMOTE-HRES-S-JWKS-TARGET
        ENDOF
        HTARGET-S-AUTHORITY-REQUIRED OF
            AT-OAUTH-REMOTE-HRES-S-INTERNAL
        ENDOF
        HTARGET-S-REDIRECT-LIMIT OF
            AT-OAUTH-REMOTE-HRES-S-INTERNAL
        ENDOF
        HTARGET-S-LOOP OF
            AT-OAUTH-REMOTE-HRES-S-INTERNAL
        ENDOF
        AT-OAUTH-REMOTE-HRES-S-INTERNAL SWAP
    ENDCASE ;

: _ATOR-REMOTE-PREP
  ( config-view metadata-view workspace -- status )
    >R
    DUP R@ _ATORW.METADATA-VIEW !
    SWAP R@ _ATORW.CONFIG-VIEW !
    DROP

    R@ _ATORW.CONFIG-VIEW @
    OAUTH2-CLIENT-VIEW-AUTH-METHOD@
    S" private_key_jwt" _ATOR-BYTES= 0= IF
        R> DROP AT-OAUTH-REMOTE-HRES-S-KEY-SOURCE EXIT
    THEN

    R@ _ATORW.METADATA-VIEW @
    OAUTH2-CLIENT-METADATA-VIEW-PRESENCE@
    DUP OAUTH2-CLIENT-METADATA-S-OK <> IF
        2DROP R> DROP AT-OAUTH-REMOTE-HRES-S-INTERNAL EXIT
    THEN
    DROP
    DUP OAUTH2-CLIENT-METADATA-P-JWKS-URI AND 0= IF
        DROP R> DROP AT-OAUTH-REMOTE-HRES-S-KEY-SOURCE EXIT
    THEN
    DUP OAUTH2-CLIENT-METADATA-P-JWKS AND IF
        DROP R> DROP AT-OAUTH-REMOTE-HRES-S-KEY-SOURCE EXIT
    THEN
    DROP

    R@ _ATORW.METADATA-VIEW @
    OAUTH2-CLIENT-METADATA-VIEW-JWKS-URI@
    DUP OAUTH2-CLIENT-METADATA-S-OK <> IF
        _ATOR-DROP3 R> DROP
        AT-OAUTH-REMOTE-HRES-S-INTERNAL EXIT
    THEN
    DROP
    DUP 0> 0= IF
        2DROP R> DROP AT-OAUTH-REMOTE-HRES-S-JWKS-TARGET EXIT
    THEN
    2DUP R@ _ATORW.STAGED-TARGET HTARGET-PARSE
    DUP HTARGET-S-OK <> IF
        _ATOR-TARGET>STATUS >R
        2DROP R> R> DROP EXIT
    THEN
    \ HTARGET owns URI normalization.  Final provenance compares the
    \ freshly parsed canonical target with both retained HRES targets.
    DROP 2DROP

    R> DROP AT-OAUTH-REMOTE-HRES-S-OK ;

\ =====================================================================
\  Exported jwks_uri target derivation
\ =====================================================================

: _ATOR-TARGET-DEPLOYMENT-CALLBACK
  ( config-view metadata-view workspace -- callback-result )
    _ATOR-REMOTE-PREP ;

: _ATOR-TARGET-DEPLOYMENT-CALL
  ( workspace -- composition-status deployment-status )
    >R
    R@ _ATORW.METADATA-RESOURCE @ HRES-BODY@
    R@ _ATORW.CONFIG @
    R@ _ATORW.PROFILE @
    ['] _ATOR-TARGET-DEPLOYMENT-CALLBACK
    R@
    R@ _ATORW.DEPLOYMENT
    AT-OAUTH-DEPLOYMENT-WITH
    R> DROP ;

: _ATOR-TARGET-DEPLOYMENT-SAFE  ( workspace -- status )
    ['] _ATOR-TARGET-DEPLOYMENT-CALL CATCH
    DUP IF
        2DROP AT-OAUTH-REMOTE-HRES-S-INTERNAL EXIT
    THEN
    DROP
    DUP AT-OAUTH-DEPLOYMENT-S-OK <> IF
        _ATOR-DEPLOYMENT>STATUS
        NIP EXIT
    THEN
    DROP
    DUP AT-OAUTH-REMOTE-HRES-STATUS-VALID? 0= IF
        DROP AT-OAUTH-REMOTE-HRES-S-INTERNAL
    THEN ;

: _ATOR-TARGET-CLEAN  ( status workspace -- status )
    DUP _ATOR-WIPE DROP ;

: _ATOR-TARGET-WITH-OP
  ( metadata-resource config profile target workspace -- status )
    4 PICK 4 PICK _ATOR-METADATA-ENVELOPE-STATUS
    ?DUP IF _ATOR-RETURN5-FAIL EXIT THEN

    DUP >R
    R@ _ATOR-WIPE
    4 PICK R@ _ATORW.METADATA-RESOURCE !
    3 PICK R@ _ATORW.CONFIG !
    2 PICK R@ _ATORW.PROFILE !
    1 PICK R@ _ATORW.TARGET-OUTPUT !
    _ATOR-DROP5

    R@ _ATOR-TARGET-DEPLOYMENT-SAFE
    DUP AT-OAUTH-REMOTE-HRES-S-OK <> IF
        R> _ATOR-TARGET-CLEAN EXIT
    THEN
    DROP
    R@ _ATORW.STAGED-TARGET
    R@ _ATORW.TARGET-OUTPUT @
    HTARGET-SIZE CMOVE
    AT-OAUTH-REMOTE-HRES-S-OK
    R> _ATOR-TARGET-CLEAN ;

: _ATOR-TARGET-WITH-CALL
  ( five-values operation-xt -- status )
    1 PICK >R
    CATCH
    DUP IF
        DROP
        R@ _ATOR-WIPE
        _ATOR-DROP5
        R> DROP
        AT-OAUTH-REMOTE-HRES-S-INTERNAL EXIT
    THEN
    DROP R> DROP ;

: AT-OAUTH-REMOTE-HRES-JWKS-TARGET!
  ( metadata-resource config profile target workspace -- status )
    _ATOR-5DUP _ATOR-TARGET-GEOMETRY
    ?DUP IF _ATOR-RETURN5-FAIL EXIT THEN
    ['] _ATOR-TARGET-WITH-OP _ATOR-TARGET-WITH-CALL ;

\ =====================================================================
\  Generic published-key bridge and final application callback
\ =====================================================================

-19871 CONSTANT _ATOR-E-CALLBACK-STACK
0x41544F5243414C31 CONSTANT _ATOR-CALLBACK-GUARD

: _ATOR-PUBLISHED-CALLBACK
  ( kid-a kid-u client-pub-a client-thumb-a dpop-pub-a dpop-thumb-a workspace -- result )
    >R
    DEPTH R@ _ATORW.APPLICATION-DEPTH !
    _ATOR-CALLBACK-GUARD
    R@ _ATORW.CONFIG-VIEW @
    R@ _ATORW.METADATA-VIEW @
    8 PICK 8 PICK 8 PICK 8 PICK 8 PICK 8 PICK
    R@ _ATORW.CONTEXT @
    R@ _ATORW.CALLBACK @ EXECUTE
    DEPTH R@ _ATORW.APPLICATION-DEPTH @ 2 + <> IF
        _ATOR-E-CALLBACK-STACK THROW
    THEN
    1 PICK _ATOR-CALLBACK-GUARD <> IF
        _ATOR-E-CALLBACK-STACK THROW
    THEN
    NIP
    >R _ATOR-DROP6 R> R> DROP ;

: _ATOR-PUBLISHED-CALL
  ( workspace -- callback-result published-status )
    >R
    R@ _ATORW.JWKS-RESOURCE @ HRES-BODY@
    R@ _ATORW.CONFIG-VIEW @ OAUTH2-CLIENT-VIEW-BINDING@
    R@ _ATORW.VAULT @
    ['] _ATOR-PUBLISHED-CALLBACK
    R@
    R@ _ATORW.PUBLISHED
    OAUTH2-P256-PUBLISHED-WITH
    R> DROP ;

: _ATOR-PUBLISHED-SAFE  ( workspace -- callback-result status )
    ['] _ATOR-PUBLISHED-CALL CATCH
    DUP IF
        2DROP 0 AT-OAUTH-REMOTE-HRES-S-INTERNAL EXIT
    THEN
    DROP _ATOR-PUBLISHED>STATUS ;

\ =====================================================================
\  Remote deployment callback and two-resource binding
\ =====================================================================

: _ATOR-DEPLOYMENT-CALLBACK-RUN
  ( config-view metadata-view workspace -- composition-status )
    DUP >R
    _ATOR-REMOTE-PREP
    ?DUP IF R> DROP EXIT THEN

    R@ _ATORW.JWKS-RESOURCE @
    R@ _ATORW.STAGED-TARGET
    AT-OAUTH-HRES-TARGET-ENVELOPE? 0= IF
        R> DROP AT-OAUTH-REMOTE-HRES-S-JWKS-HTTP EXIT
    THEN

    R@ _ATORW.JWKS-RESOURCE @ HRES-BODY@
    DUP 0> 0= IF
        2DROP R> DROP AT-OAUTH-REMOTE-HRES-S-JWKS EXIT
    THEN
    \ The generic published-key owner admits the used JWK Set span and
    \ owns its document bound; this layer only binds remote provenance.
    2DROP

    R@ _ATOR-PUBLISHED-SAFE
    DUP AT-OAUTH-REMOTE-HRES-S-OK <> IF
        SWAP DROP R> DROP EXIT
    THEN
    DROP
    R@ _ATORW.CALLBACK-RESULT !
    R> DROP AT-OAUTH-REMOTE-HRES-S-OK ;

: _ATOR-DEPLOYMENT-CALLBACK
  ( config-view metadata-view workspace -- callback-result )
    ['] _ATOR-DEPLOYMENT-CALLBACK-RUN CATCH
    DUP IF
        DROP _ATOR-DROP3 AT-OAUTH-REMOTE-HRES-S-INTERNAL
    ELSE
        DROP
    THEN ;

: _ATOR-DEPLOYMENT-CALL
  ( workspace -- composition-status deployment-status )
    >R
    R@ _ATORW.METADATA-RESOURCE @ HRES-BODY@
    R@ _ATORW.CONFIG @
    R@ _ATORW.PROFILE @
    ['] _ATOR-DEPLOYMENT-CALLBACK
    R@
    R@ _ATORW.DEPLOYMENT
    AT-OAUTH-DEPLOYMENT-WITH
    R> DROP ;

: _ATOR-DEPLOYMENT-SAFE
  ( workspace -- composition-status status )
    ['] _ATOR-DEPLOYMENT-CALL CATCH
    DUP IF
        2DROP 0 AT-OAUTH-REMOTE-HRES-S-INTERNAL EXIT
    THEN
    DROP
    DUP AT-OAUTH-DEPLOYMENT-S-OK <> IF
        _ATOR-DEPLOYMENT>STATUS
        >R DROP 0 R> EXIT
    THEN
    DROP AT-OAUTH-REMOTE-HRES-S-OK ;

\ =====================================================================
\  Final composition and mandatory cleanup
\ =====================================================================

: _ATOR-CLEAN-RESULT
  ( callback-result status workspace -- callback-result status )
    DUP _ATOR-WIPE DROP ;

: _ATOR-WITH-OP
  ( metadata-resource jwks-resource config profile vault callback context workspace -- callback-result status )
    7 PICK 6 PICK _ATOR-METADATA-ENVELOPE-STATUS
    ?DUP IF _ATOR-RETURN8-FAIL EXIT THEN

    DUP >R
    R@ _ATOR-WIPE
    7 PICK R@ _ATORW.METADATA-RESOURCE !
    6 PICK R@ _ATORW.JWKS-RESOURCE !
    5 PICK R@ _ATORW.CONFIG !
    4 PICK R@ _ATORW.PROFILE !
    3 PICK R@ _ATORW.VAULT !
    2 PICK R@ _ATORW.CALLBACK !
    1 PICK R@ _ATORW.CONTEXT !
    _ATOR-DROP8

    R@ _ATOR-DEPLOYMENT-SAFE
    DUP AT-OAUTH-REMOTE-HRES-S-OK <> IF
        SWAP DROP 0 SWAP
        R> _ATOR-CLEAN-RESULT EXIT
    THEN
    DROP
    DUP AT-OAUTH-REMOTE-HRES-STATUS-VALID? 0= IF
        DROP 0 AT-OAUTH-REMOTE-HRES-S-INTERNAL
        R> _ATOR-CLEAN-RESULT EXIT
    THEN
    ?DUP IF
        0 SWAP R> _ATOR-CLEAN-RESULT EXIT
    THEN

    R@ _ATORW.CALLBACK-RESULT @
    AT-OAUTH-REMOTE-HRES-S-OK
    R> _ATOR-CLEAN-RESULT ;

: _ATOR-WITH-CALL
  ( eight-values operation-xt -- callback-result status )
    1 PICK >R
    CATCH
    DUP IF
        DROP
        R@ _ATOR-WIPE
        _ATOR-DROP8
        R> DROP
        0 AT-OAUTH-REMOTE-HRES-S-INTERNAL EXIT
    THEN
    DROP R> DROP ;

: AT-OAUTH-REMOTE-HRES-WITH
  ( metadata-resource jwks-resource config profile vault callback context workspace -- callback-result status )
    _ATOR-8DUP _ATOR-GEOMETRY
    ?DUP IF _ATOR-RETURN8-FAIL EXIT THEN
    ['] _ATOR-WITH-OP _ATOR-WITH-CALL ;

\ =====================================================================
\  Compile-time geometry assertions
\ =====================================================================

: _ATOR-GEOMETRY-ABORT  ( -- )
    ." AT OAuth remote HRES geometry mismatch" CR ABORT ;

1 CELLS 8 <> [IF]
    _ATOR-GEOMETRY-ABORT
[THEN]

HTARGET-SIZE 3424 <> [IF]
    _ATOR-GEOMETRY-ABORT
[THEN]

AT-OAUTH-DEPLOYMENT-WORKSPACE-SIZE 53760 <> [IF]
    _ATOR-GEOMETRY-ABORT
[THEN]

OAUTH2-P256-PUBLISHED-WORKSPACE-SIZE 58056 <> [IF]
    _ATOR-GEOMETRY-ABORT
[THEN]

_ATORW-STAGED-TARGET-OFF 96 <> [IF]
    _ATOR-GEOMETRY-ABORT
[THEN]

_ATORW-STAGED-TARGET-OFF HTARGET-SIZE +
_ATORW-DEPLOYMENT-OFF <> [IF]
    _ATOR-GEOMETRY-ABORT
[THEN]

_ATORW-DEPLOYMENT-OFF AT-OAUTH-DEPLOYMENT-WORKSPACE-SIZE +
_ATORW-PUBLISHED-OFF <> [IF]
    _ATOR-GEOMETRY-ABORT
[THEN]

_ATORW-PUBLISHED-OFF OAUTH2-P256-PUBLISHED-WORKSPACE-SIZE +
AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE <> [IF]
    _ATOR-GEOMETRY-ABORT
[THEN]

AT-OAUTH-REMOTE-HRES-WORKSPACE-SIZE 115336 <> [IF]
    _ATOR-GEOMETRY-ABORT
[THEN]
