\ =====================================================================
\  oauth-profile.f - AT Protocol OAuth discovery-profile composition
\ =====================================================================
\  This module binds a resolved AT Protocol identity to the OAuth
\  authorization server selected by its PDS.  It performs no HTTP, DNS,
\  browser, token, DPoP, session, vault, XRPC, or application work.
\
\  The caller supplies already-validated generic metadata objects:
\    1. BEGIN copies a resolved DID and canonical PDS origin.
\    2. RESOURCE! binds RFC 9728 protected-resource metadata exactly to
\       that PDS and selects its one canonical authorization-server origin.
\    3. AUTHORIZATION-SERVER! binds RFC 8414 metadata exactly to that
\       selected issuer and enforces the AT Protocol OAuth profile.
\
\  All retained bytes and parsed HTTPS targets live in one caller-owned
\  object.  Semantic trust-chain failures wipe partial results and publish
\  a terminal FAILED phase.  Caller geometry and state errors do not alter
\  the object.  Reinitialization is the only transition out of FAILED.
\
\  Public API:
\    AT-OAUTH-PROFILE-SIZE
\    AT-OAUTH-PROFILE-STATUS-VALID?
\    AT-OAUTH-PROFILE-INIT
\    AT-OAUTH-PROFILE-WIPE
\    AT-OAUTH-PROFILE-VALID?
\    AT-OAUTH-PROFILE-READY?
\    AT-OAUTH-PROFILE-BEGIN
\    AT-OAUTH-PROFILE-RESOURCE!
\    AT-OAUTH-PROFILE-AUTHORIZATION-SERVER!
\    AT-OAUTH-PROFILE-PHASE@
\    AT-OAUTH-PROFILE-STATUS@
\    AT-OAUTH-PROFILE-DID@
\    AT-OAUTH-PROFILE-RESOURCE@
\    AT-OAUTH-PROFILE-PDS-TARGET@
\    AT-OAUTH-PROFILE-RESOURCE-METADATA-TARGET@
\    AT-OAUTH-PROFILE-ISSUER@
\    AT-OAUTH-PROFILE-AUTHORIZATION-SERVER-TARGET@
\    AT-OAUTH-PROFILE-AUTHORIZATION-SERVER-METADATA-TARGET@
\    AT-OAUTH-PROFILE-AUTHORIZATION-TARGET@
\    AT-OAUTH-PROFILE-TOKEN-TARGET@
\    AT-OAUTH-PROFILE-PAR-TARGET@
\ =====================================================================

\ KDOS module identities are bounded to 23 bytes.
PROVIDED akashic-at-oauth-prof

REQUIRE ../utils/memory-span.f
REQUIRE ../utils/caller-span.f
REQUIRE ../net/http-target.f
REQUIRE ../security/oauth2/resource-metadata.f
REQUIRE ../security/oauth2/metadata.f
REQUIRE did.f
REQUIRE identity.f

\ =====================================================================
\  Public status and phase vocabulary
\ =====================================================================

0  CONSTANT AT-OAUTH-PROFILE-S-OK
1  CONSTANT AT-OAUTH-PROFILE-S-INVALID
2  CONSTANT AT-OAUTH-PROFILE-S-CAPACITY
3  CONSTANT AT-OAUTH-PROFILE-S-ALIAS
4  CONSTANT AT-OAUTH-PROFILE-S-STATE
5  CONSTANT AT-OAUTH-PROFILE-S-IDENTITY
6  CONSTANT AT-OAUTH-PROFILE-S-RESOURCE-METADATA
7  CONSTANT AT-OAUTH-PROFILE-S-RESOURCE-BINDING
8  CONSTANT AT-OAUTH-PROFILE-S-AUTHORIZATION-SERVER
9  CONSTANT AT-OAUTH-PROFILE-S-ISSUER-BINDING
10 CONSTANT AT-OAUTH-PROFILE-S-PROFILE
11 CONSTANT AT-OAUTH-PROFILE-S-ENDPOINT
12 CONSTANT AT-OAUTH-PROFILE-S-HTTP
13 CONSTANT AT-OAUTH-PROFILE-S-INTERNAL
14 CONSTANT AT-OAUTH-PROFILE-S-RANGE
15 CONSTANT AT-OAUTH-PROFILE-S-PROTECTED
16 CONSTANT AT-OAUTH-PROFILE-S-PLATFORM

: AT-OAUTH-PROFILE-STATUS-VALID?  ( status -- flag )
    DUP AT-OAUTH-PROFILE-S-OK >=
    SWAP AT-OAUTH-PROFILE-S-PLATFORM <= AND ;

0 CONSTANT AT-OAUTH-PROFILE-PHASE-EMPTY
1 CONSTANT AT-OAUTH-PROFILE-PHASE-RESOURCE-METADATA
2 CONSTANT AT-OAUTH-PROFILE-PHASE-AUTHORIZATION-SERVER-METADATA
3 CONSTANT AT-OAUTH-PROFILE-PHASE-READY
4 CONSTANT AT-OAUTH-PROFILE-PHASE-FAILED

: AT-OAUTH-PROFILE-PHASE-VALID?  ( phase -- flag )
    DUP AT-OAUTH-PROFILE-PHASE-EMPTY >=
    SWAP AT-OAUTH-PROFILE-PHASE-FAILED <= AND ;

DID-LENGTH-MAX CONSTANT AT-OAUTH-PROFILE-DID-CAPACITY

\ =====================================================================
\  Caller-owned profile geometry
\ =====================================================================

0x41544F4155544831 CONSTANT _ATOP-MAGIC-VALUE  \ "ATOAUTH1"

 0 CONSTANT _ATOP-MAGIC
 8 CONSTANT _ATOP-PHASE
16 CONSTANT _ATOP-STATUS
24 CONSTANT _ATOP-DID-U
32 CONSTANT _ATOP-RESERVED
40 CONSTANT _ATOP-HEADER-SIZE

_ATOP-HEADER-SIZE CONSTANT _ATOP-DID-OFF
_ATOP-DID-OFF AT-OAUTH-PROFILE-DID-CAPACITY +
    CONSTANT _ATOP-PDS-OFF
_ATOP-PDS-OFF HTARGET-SIZE +
    CONSTANT _ATOP-PDS-CHECK-OFF
_ATOP-PDS-CHECK-OFF 8 +
    CONSTANT _ATOP-RESOURCE-METADATA-OFF
_ATOP-RESOURCE-METADATA-OFF HTARGET-SIZE +
    CONSTANT _ATOP-RESOURCE-METADATA-CHECK-OFF
_ATOP-RESOURCE-METADATA-CHECK-OFF 8 +
    CONSTANT _ATOP-AUTHORIZATION-SERVER-OFF
_ATOP-AUTHORIZATION-SERVER-OFF HTARGET-SIZE +
    CONSTANT _ATOP-AUTHORIZATION-SERVER-CHECK-OFF
_ATOP-AUTHORIZATION-SERVER-CHECK-OFF 8 +
    CONSTANT _ATOP-AUTHORIZATION-SERVER-METADATA-OFF
_ATOP-AUTHORIZATION-SERVER-METADATA-OFF HTARGET-SIZE +
    CONSTANT _ATOP-AUTHORIZATION-SERVER-METADATA-CHECK-OFF
_ATOP-AUTHORIZATION-SERVER-METADATA-CHECK-OFF 8 +
    CONSTANT _ATOP-AUTHORIZATION-OFF
_ATOP-AUTHORIZATION-OFF HTARGET-SIZE +
    CONSTANT _ATOP-AUTHORIZATION-CHECK-OFF
_ATOP-AUTHORIZATION-CHECK-OFF 8 +
    CONSTANT _ATOP-TOKEN-OFF
_ATOP-TOKEN-OFF HTARGET-SIZE +
    CONSTANT _ATOP-TOKEN-CHECK-OFF
_ATOP-TOKEN-CHECK-OFF 8 +
    CONSTANT _ATOP-PAR-OFF
_ATOP-PAR-OFF HTARGET-SIZE +
    CONSTANT _ATOP-PAR-CHECK-OFF
_ATOP-PAR-CHECK-OFF 8 +
    CONSTANT _ATOP-SCRATCH-OFF
_ATOP-SCRATCH-OFF HTARGET-URI-CAPACITY +
    CONSTANT AT-OAUTH-PROFILE-SIZE

: _ATOP.MAGIC       ( profile -- field ) _ATOP-MAGIC + ;
: _ATOP.PHASE       ( profile -- field ) _ATOP-PHASE + ;
: _ATOP.STATUS      ( profile -- field ) _ATOP-STATUS + ;
: _ATOP.DID-U       ( profile -- field ) _ATOP-DID-U + ;
: _ATOP.RESERVED    ( profile -- field ) _ATOP-RESERVED + ;

: _ATOP.DID         ( profile -- address ) _ATOP-DID-OFF + ;
: _ATOP.PDS         ( profile -- target ) _ATOP-PDS-OFF + ;
: _ATOP.PDS-CHECK
  ( profile -- field ) _ATOP-PDS-CHECK-OFF + ;
: _ATOP.RESOURCE-METADATA
  ( profile -- target ) _ATOP-RESOURCE-METADATA-OFF + ;
: _ATOP.RESOURCE-METADATA-CHECK
  ( profile -- field ) _ATOP-RESOURCE-METADATA-CHECK-OFF + ;
: _ATOP.AUTHORIZATION-SERVER
  ( profile -- target ) _ATOP-AUTHORIZATION-SERVER-OFF + ;
: _ATOP.AUTHORIZATION-SERVER-CHECK
  ( profile -- field ) _ATOP-AUTHORIZATION-SERVER-CHECK-OFF + ;
: _ATOP.AUTHORIZATION-SERVER-METADATA
  ( profile -- target ) _ATOP-AUTHORIZATION-SERVER-METADATA-OFF + ;
: _ATOP.AUTHORIZATION-SERVER-METADATA-CHECK
  ( profile -- field )
    _ATOP-AUTHORIZATION-SERVER-METADATA-CHECK-OFF + ;
: _ATOP.AUTHORIZATION
  ( profile -- target ) _ATOP-AUTHORIZATION-OFF + ;
: _ATOP.AUTHORIZATION-CHECK
  ( profile -- field ) _ATOP-AUTHORIZATION-CHECK-OFF + ;
: _ATOP.TOKEN       ( profile -- target ) _ATOP-TOKEN-OFF + ;
: _ATOP.TOKEN-CHECK
  ( profile -- field ) _ATOP-TOKEN-CHECK-OFF + ;
: _ATOP.PAR         ( profile -- target ) _ATOP-PAR-OFF + ;
: _ATOP.PAR-CHECK
  ( profile -- field ) _ATOP-PAR-CHECK-OFF + ;
: _ATOP.SCRATCH     ( profile -- address ) _ATOP-SCRATCH-OFF + ;

\ =====================================================================
\  Admission and immutable helpers
\ =====================================================================

: _ATOP-CALLER>STATUS  ( caller-status -- status )
    DUP CALLER-SPAN-S-OK = IF
        DROP AT-OAUTH-PROFILE-S-OK EXIT
    THEN
    DUP CALLER-SPAN-S-RANGE = IF
        DROP AT-OAUTH-PROFILE-S-RANGE EXIT
    THEN
    DUP CALLER-SPAN-S-PROTECTED = IF
        DROP AT-OAUTH-PROFILE-S-PROTECTED EXIT
    THEN
    DUP CALLER-SPAN-S-PLATFORM = IF
        DROP AT-OAUTH-PROFILE-S-PLATFORM EXIT
    THEN
    DROP AT-OAUTH-PROFILE-S-PLATFORM ;

: _ATOP-SPAN-STATUS  ( address length -- status )
    DUP 0< IF 2DROP AT-OAUTH-PROFILE-S-INVALID EXIT THEN
    DUP 0= IF 2DROP AT-OAUTH-PROFILE-S-OK EXIT THEN
    OVER 0= IF 2DROP AT-OAUTH-PROFILE-S-INVALID EXIT THEN
    CALLER-SPAN-STATUS _ATOP-CALLER>STATUS ;

: _ATOP-FIXED-STATUS  ( address size -- status )
    OVER 0= IF 2DROP AT-OAUTH-PROFILE-S-INVALID EXIT THEN
    OVER 7 AND IF 2DROP AT-OAUTH-PROFILE-S-INVALID EXIT THEN
    _ATOP-SPAN-STATUS ;

: _ATOP-OBJECT-STATUS  ( profile -- status )
    AT-OAUTH-PROFILE-SIZE _ATOP-FIXED-STATUS ;

: _ATOP-ZERO?  ( address length -- flag )
    BEGIN
        DUP
    WHILE
        OVER C@ IF 2DROP 0 EXIT THEN
        1 /STRING
    REPEAT
    2DROP -1 ;

: _ATOP-PAD-ZERO?  ( base used capacity -- flag )
    >R
    2DUP +
    R> ROT -
    _ATOP-ZERO?
    NIP ;

: _ATOP-BITS-CONTAIN?  ( actual required -- flag )
    TUCK AND = ;

: _ATOP-TARGET-HASH  ( target -- hash )
    0xCBF29CE484222325
    HTARGET-SIZE 0 ?DO
        OVER I + C@ XOR
        0x100000001B3 *
    LOOP
    NIP ;

: _ATOP-TARGET-CHECK!  ( target check-field -- )
    SWAP _ATOP-TARGET-HASH SWAP ! ;

: _ATOP-TARGET-CHECKED?  ( target check-field -- flag )
    @ SWAP _ATOP-TARGET-HASH = ;

: _ATOP-ORIGIN-TARGET?  ( target -- flag )
    DUP HTARGET-VALID? 0= IF DROP 0 EXIT THEN
    DUP HTARGET-REDIRECT-COUNT@ IF DROP 0 EXIT THEN
    DUP HTARGET-URI$
    DUP 0= IF 2DROP DROP 0 EXIT THEN
    2DUP + 1- C@ [CHAR] / <> IF 2DROP DROP 0 EXIT THEN
    2DROP
    HTARGET-REQUEST-TARGET$ S" /" COMPARE 0= ;

\ Return the canonical OAuth resource/issuer serialization.  HTARGET keeps
\ an origin target as ".../"; AT OAuth and RFC exact binding use the same
\ canonical origin without that sole root slash.
: _ATOP-ORIGIN$  ( target -- address length )
    HTARGET-URI$ 1- ;

: _ATOP-CANONICAL-ORIGIN?  ( address length target -- flag )
    >R
    R@ _ATOP-ORIGIN-TARGET? 0= IF
        2DROP R> DROP 0 EXIT
    THEN
    R@ _ATOP-ORIGIN$
    2SWAP COMPARE 0=
    R> DROP ;

: _ATOP-RESOURCE-TARGET?  ( profile -- flag )
    DUP _ATOP.PDS
    OVER _ATOP.RESOURCE-METADATA
    HTARGET-SAME-ORIGIN? 0= IF DROP 0 EXIT THEN
    _ATOP.RESOURCE-METADATA HTARGET-REQUEST-TARGET$
    S" /.well-known/oauth-protected-resource"
    COMPARE 0= ;

: _ATOP-AS-METADATA-TARGET?  ( profile -- flag )
    DUP _ATOP.AUTHORIZATION-SERVER
    OVER _ATOP.AUTHORIZATION-SERVER-METADATA
    HTARGET-SAME-ORIGIN? 0= IF DROP 0 EXIT THEN
    _ATOP.AUTHORIZATION-SERVER-METADATA HTARGET-REQUEST-TARGET$
    S" /.well-known/oauth-authorization-server"
    COMPARE 0= ;

\ =====================================================================
\  Structural validity and lifecycle
\ =====================================================================

: _ATOP-PAYLOAD-ZERO?  ( profile -- flag )
    _ATOP-DID-U +
    AT-OAUTH-PROFILE-SIZE _ATOP-DID-U -
    _ATOP-ZERO? ;

: _ATOP-EMPTY-SHAPE?  ( profile -- flag )
    DUP _ATOP.STATUS @ AT-OAUTH-PROFILE-S-OK <> IF
        DROP 0 EXIT
    THEN
    _ATOP-PAYLOAD-ZERO? ;

: _ATOP-IDENTITY-SHAPE?  ( profile -- flag )
    DUP _ATOP.STATUS @ AT-OAUTH-PROFILE-S-OK <> IF
        DROP 0 EXIT
    THEN
    DUP _ATOP.RESERVED @ IF DROP 0 EXIT THEN
    DUP _ATOP.DID-U @
    DUP 0> 0= SWAP AT-OAUTH-PROFILE-DID-CAPACITY > OR IF
        DROP 0 EXIT
    THEN
    DUP _ATOP.DID OVER _ATOP.DID-U @
    DID-VALID? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.DID OVER _ATOP.DID-U @
    AT-OAUTH-PROFILE-DID-CAPACITY
    _ATOP-PAD-ZERO? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.PDS OVER _ATOP.PDS-CHECK
    _ATOP-TARGET-CHECKED? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.RESOURCE-METADATA
    OVER _ATOP.RESOURCE-METADATA-CHECK
    _ATOP-TARGET-CHECKED? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.PDS _ATOP-ORIGIN-TARGET? 0= IF DROP 0 EXIT THEN
    DUP _ATOP-RESOURCE-TARGET? 0= IF DROP 0 EXIT THEN
    DROP -1 ;

: _ATOP-AUTHORITY-SHAPE?  ( profile -- flag )
    DUP _ATOP-IDENTITY-SHAPE? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.AUTHORIZATION-SERVER
    OVER _ATOP.AUTHORIZATION-SERVER-CHECK
    _ATOP-TARGET-CHECKED? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.AUTHORIZATION-SERVER-METADATA
    OVER _ATOP.AUTHORIZATION-SERVER-METADATA-CHECK
    _ATOP-TARGET-CHECKED? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.AUTHORIZATION-SERVER
    _ATOP-ORIGIN-TARGET? 0= IF DROP 0 EXIT THEN
    DUP _ATOP-AS-METADATA-TARGET? 0= IF DROP 0 EXIT THEN
    DROP -1 ;

: _ATOP-RESOURCE-PHASE-SHAPE?  ( profile -- flag )
    DUP _ATOP-IDENTITY-SHAPE? 0= IF DROP 0 EXIT THEN
    _ATOP.AUTHORIZATION-SERVER
    AT-OAUTH-PROFILE-SIZE
    _ATOP-AUTHORIZATION-SERVER-OFF -
    _ATOP-ZERO? ;

: _ATOP-AS-PHASE-SHAPE?  ( profile -- flag )
    DUP _ATOP-AUTHORITY-SHAPE? 0= IF DROP 0 EXIT THEN
    _ATOP.AUTHORIZATION
    AT-OAUTH-PROFILE-SIZE _ATOP-AUTHORIZATION-OFF -
    _ATOP-ZERO? ;

: _ATOP-READY-SHAPE?  ( profile -- flag )
    DUP _ATOP-AUTHORITY-SHAPE? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.AUTHORIZATION OVER _ATOP.AUTHORIZATION-CHECK
    _ATOP-TARGET-CHECKED? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.TOKEN OVER _ATOP.TOKEN-CHECK
    _ATOP-TARGET-CHECKED? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.PAR OVER _ATOP.PAR-CHECK
    _ATOP-TARGET-CHECKED? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.AUTHORIZATION HTARGET-VALID? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.AUTHORIZATION HTARGET-REDIRECT-COUNT@ IF
        DROP 0 EXIT
    THEN
    DUP _ATOP.TOKEN HTARGET-VALID? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.TOKEN HTARGET-REDIRECT-COUNT@ IF DROP 0 EXIT THEN
    DUP _ATOP.PAR HTARGET-VALID? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.PAR HTARGET-REDIRECT-COUNT@ IF DROP 0 EXIT THEN
    _ATOP.SCRATCH HTARGET-URI-CAPACITY _ATOP-ZERO? ;

: _ATOP-FAILED-SHAPE?  ( profile -- flag )
    DUP _ATOP.STATUS @
    DUP AT-OAUTH-PROFILE-STATUS-VALID? 0= IF
        2DROP 0 EXIT
    THEN
    AT-OAUTH-PROFILE-S-OK = IF DROP 0 EXIT THEN
    _ATOP-PAYLOAD-ZERO? ;

: AT-OAUTH-PROFILE-VALID?  ( profile -- flag )
    DUP _ATOP-OBJECT-STATUS ?DUP IF 2DROP 0 EXIT THEN
    DUP _ATOP.MAGIC @ _ATOP-MAGIC-VALUE <> IF DROP 0 EXIT THEN
    DUP _ATOP.PHASE @
    AT-OAUTH-PROFILE-PHASE-VALID? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.STATUS @
    AT-OAUTH-PROFILE-STATUS-VALID? 0= IF DROP 0 EXIT THEN
    DUP _ATOP.PHASE @
    DUP AT-OAUTH-PROFILE-PHASE-EMPTY = IF
        DROP _ATOP-EMPTY-SHAPE? EXIT
    THEN
    DUP AT-OAUTH-PROFILE-PHASE-RESOURCE-METADATA = IF
        DROP _ATOP-RESOURCE-PHASE-SHAPE? EXIT
    THEN
    DUP AT-OAUTH-PROFILE-PHASE-AUTHORIZATION-SERVER-METADATA = IF
        DROP _ATOP-AS-PHASE-SHAPE? EXIT
    THEN
    DUP AT-OAUTH-PROFILE-PHASE-READY = IF
        DROP _ATOP-READY-SHAPE? EXIT
    THEN
    AT-OAUTH-PROFILE-PHASE-FAILED = IF
        _ATOP-FAILED-SHAPE? EXIT
    THEN
    DROP 0 ;

: AT-OAUTH-PROFILE-READY?  ( profile -- flag )
    DUP AT-OAUTH-PROFILE-VALID? IF
        _ATOP.PHASE @ AT-OAUTH-PROFILE-PHASE-READY =
    ELSE
        DROP 0
    THEN ;

: AT-OAUTH-PROFILE-INIT  ( profile -- status )
    DUP _ATOP-OBJECT-STATUS ?DUP IF NIP EXIT THEN
    DUP AT-OAUTH-PROFILE-SIZE 0 FILL
    _ATOP-MAGIC-VALUE OVER _ATOP.MAGIC !
    DROP AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-WIPE  ( profile -- status )
    DUP _ATOP-OBJECT-STATUS ?DUP IF NIP EXIT THEN
    AT-OAUTH-PROFILE-SIZE 0 FILL
    AT-OAUTH-PROFILE-S-OK ;

: _ATOP-FAIL  ( status profile -- status )
    >R
    DUP AT-OAUTH-PROFILE-STATUS-VALID? 0=
    OVER AT-OAUTH-PROFILE-S-OK = OR IF
        DROP AT-OAUTH-PROFILE-S-INTERNAL
    THEN
    R@ AT-OAUTH-PROFILE-SIZE 0 FILL
    _ATOP-MAGIC-VALUE R@ _ATOP.MAGIC !
    AT-OAUTH-PROFILE-PHASE-FAILED R@ _ATOP.PHASE !
    DUP R@ _ATOP.STATUS !
    R> DROP ;

\ =====================================================================
\  Well-known target construction
\ =====================================================================

: _ATOP-BUILD-RESOURCE-METADATA-TARGET  ( profile -- status )
    DUP _ATOP.SCRATCH HTARGET-URI-CAPACITY 0 FILL
    DUP _ATOP.PDS HTARGET-URI$
    DUP S" .well-known/oauth-protected-resource" NIP +
    HTARGET-URI-CAPACITY U> IF
        2DROP
        DUP _ATOP.SCRATCH HTARGET-URI-CAPACITY 0 FILL
        DROP AT-OAUTH-PROFILE-S-CAPACITY EXIT
    THEN
    2 PICK _ATOP.SCRATCH SWAP MOVE

    S" .well-known/oauth-protected-resource"
    2 PICK _ATOP.PDS HTARGET-URI$ NIP
    3 PICK _ATOP.SCRATCH + SWAP MOVE

    DUP _ATOP.SCRATCH
    OVER _ATOP.PDS HTARGET-URI$ NIP
    S" .well-known/oauth-protected-resource" NIP +
    2 PICK _ATOP.RESOURCE-METADATA
    HTARGET-PARSE
    HTARGET-S-OK <> IF
        DUP _ATOP.SCRATCH HTARGET-URI-CAPACITY 0 FILL
        DROP AT-OAUTH-PROFILE-S-INTERNAL EXIT
    THEN
    DUP _ATOP.RESOURCE-METADATA
    OVER _ATOP.RESOURCE-METADATA-CHECK
    _ATOP-TARGET-CHECK!
    DUP _ATOP.SCRATCH HTARGET-URI-CAPACITY 0 FILL
    DROP AT-OAUTH-PROFILE-S-OK ;

: _ATOP-BUILD-AS-METADATA-TARGET  ( profile -- status )
    DUP _ATOP.SCRATCH HTARGET-URI-CAPACITY 0 FILL
    DUP _ATOP.AUTHORIZATION-SERVER HTARGET-URI$
    DUP S" .well-known/oauth-authorization-server" NIP +
    HTARGET-URI-CAPACITY U> IF
        2DROP
        DUP _ATOP.SCRATCH HTARGET-URI-CAPACITY 0 FILL
        DROP AT-OAUTH-PROFILE-S-CAPACITY EXIT
    THEN
    2 PICK _ATOP.SCRATCH SWAP MOVE

    S" .well-known/oauth-authorization-server"
    2 PICK _ATOP.AUTHORIZATION-SERVER HTARGET-URI$ NIP
    3 PICK _ATOP.SCRATCH + SWAP MOVE

    DUP _ATOP.SCRATCH
    OVER _ATOP.AUTHORIZATION-SERVER HTARGET-URI$ NIP
    S" .well-known/oauth-authorization-server" NIP +
    2 PICK _ATOP.AUTHORIZATION-SERVER-METADATA
    HTARGET-PARSE
    HTARGET-S-OK <> IF
        DUP _ATOP.SCRATCH HTARGET-URI-CAPACITY 0 FILL
        DROP AT-OAUTH-PROFILE-S-INTERNAL EXIT
    THEN
    DUP _ATOP.AUTHORIZATION-SERVER-METADATA
    OVER _ATOP.AUTHORIZATION-SERVER-METADATA-CHECK
    _ATOP-TARGET-CHECK!
    DUP _ATOP.SCRATCH HTARGET-URI-CAPACITY 0 FILL
    DROP AT-OAUTH-PROFILE-S-OK ;

\ =====================================================================
\  Identity and protected-resource transitions
\ =====================================================================

: _ATOP-BEGIN-ADMITTED  ( identity-result profile -- status )
    >R
    DUP ATID-DID@
    DUP ATID-S-OK <> IF
        >R 2DROP DROP R> DROP
        AT-OAUTH-PROFILE-S-IDENTITY R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    DROP
    DUP AT-OAUTH-PROFILE-DID-CAPACITY U> IF
        2DROP DROP
        AT-OAUTH-PROFILE-S-CAPACITY R@ _ATOP-FAIL
        R> DROP EXIT
    THEN

    2 PICK ATID-PDS-TARGET@
    DUP ATID-S-OK <> IF
        >R DROP 2DROP DROP R> DROP
        AT-OAUTH-PROFILE-S-IDENTITY R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    DROP
    DUP _ATOP-ORIGIN-TARGET? 0= IF
        DROP 2DROP DROP
        AT-OAUTH-PROFILE-S-IDENTITY R@ _ATOP-FAIL
        R> DROP EXIT
    THEN

    DUP HTARGET-URI$ R@ _ATOP.PDS HTARGET-PARSE
    HTARGET-S-OK <> IF
        DROP 2DROP DROP
        AT-OAUTH-PROFILE-S-INTERNAL R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    DROP

    R@ _ATOP.PDS R@ _ATOP.PDS-CHECK
    _ATOP-TARGET-CHECK!
    DUP R@ _ATOP.DID-U !
    2DUP R@ _ATOP.DID SWAP MOVE
    2DROP DROP

    R@ _ATOP-BUILD-RESOURCE-METADATA-TARGET
    DUP AT-OAUTH-PROFILE-S-OK <> IF
        R@ _ATOP-FAIL R> DROP EXIT
    THEN
    DROP
    AT-OAUTH-PROFILE-PHASE-RESOURCE-METADATA
    R@ _ATOP.PHASE !
    R> DROP
    AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-BEGIN  ( identity-result profile -- status )
    DUP _ATOP-OBJECT-STATUS ?DUP IF
        >R 2DROP R> EXIT
    THEN
    DUP AT-OAUTH-PROFILE-VALID? 0= IF
        2DROP AT-OAUTH-PROFILE-S-INVALID EXIT
    THEN
    DUP _ATOP.PHASE @ AT-OAUTH-PROFILE-PHASE-EMPTY <> IF
        2DROP AT-OAUTH-PROFILE-S-STATE EXIT
    THEN
    >R

    DUP ATID-RESULT-SIZE _ATOP-FIXED-STATUS ?DUP IF
        SWAP DROP R> DROP EXIT
    THEN
    DUP ATID-RESULT-SIZE
    R@ AT-OAUTH-PROFILE-SIZE MSPAN-OVERLAP? IF
        DROP R> DROP AT-OAUTH-PROFILE-S-ALIAS EXIT
    THEN
    DUP ATID-RESULT-READY? 0= IF
        DROP
        AT-OAUTH-PROFILE-S-IDENTITY R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    R> _ATOP-BEGIN-ADMITTED ;

: _ATOP-RESOURCE-ADMITTED
  ( resource-metadata profile -- status )
    >R
    DUP OAUTH2-RESOURCE-METADATA-RESOURCE@
    DUP OAUTH2-RESOURCE-METADATA-S-OK <> IF
        >R 2DROP DROP R> DROP
        AT-OAUTH-PROFILE-S-RESOURCE-METADATA R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    DROP
    2DUP R@ _ATOP.PDS _ATOP-CANONICAL-ORIGIN? 0= IF
        2DROP DROP
        AT-OAUTH-PROFILE-S-RESOURCE-BINDING R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    2DROP

    DUP OAUTH2-RESOURCE-METADATA-AUTHORIZATION-SERVER-COUNT@
    DUP OAUTH2-RESOURCE-METADATA-S-OK <> IF
        >R DROP DROP R> DROP
        AT-OAUTH-PROFILE-S-AUTHORIZATION-SERVER R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    DROP
    1 <> IF
        DROP
        AT-OAUTH-PROFILE-S-AUTHORIZATION-SERVER R@ _ATOP-FAIL
        R> DROP EXIT
    THEN

    0 OVER OAUTH2-RESOURCE-METADATA-AUTHORIZATION-SERVER@
    DUP OAUTH2-RESOURCE-METADATA-S-OK <> IF
        >R 2DROP DROP R> DROP
        AT-OAUTH-PROFILE-S-AUTHORIZATION-SERVER R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    DROP
    2DUP R@ _ATOP.AUTHORIZATION-SERVER HTARGET-PARSE
    HTARGET-S-OK <> IF
        2DROP DROP
        AT-OAUTH-PROFILE-S-AUTHORIZATION-SERVER R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    R@ _ATOP.AUTHORIZATION-SERVER
    R@ _ATOP.AUTHORIZATION-SERVER-CHECK
    _ATOP-TARGET-CHECK!
    2DUP R@ _ATOP.AUTHORIZATION-SERVER
    _ATOP-CANONICAL-ORIGIN? 0= IF
        2DROP DROP
        AT-OAUTH-PROFILE-S-AUTHORIZATION-SERVER R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    2DROP DROP

    R@ _ATOP-BUILD-AS-METADATA-TARGET
    DUP AT-OAUTH-PROFILE-S-OK <> IF
        R@ _ATOP-FAIL R> DROP EXIT
    THEN
    DROP
    AT-OAUTH-PROFILE-PHASE-AUTHORIZATION-SERVER-METADATA
    R@ _ATOP.PHASE !
    R> DROP
    AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-RESOURCE!
  ( resource-metadata profile -- status )
    DUP _ATOP-OBJECT-STATUS ?DUP IF
        >R 2DROP R> EXIT
    THEN
    DUP AT-OAUTH-PROFILE-VALID? 0= IF
        2DROP AT-OAUTH-PROFILE-S-INVALID EXIT
    THEN
    DUP _ATOP.PHASE @
    AT-OAUTH-PROFILE-PHASE-RESOURCE-METADATA <> IF
        2DROP AT-OAUTH-PROFILE-S-STATE EXIT
    THEN
    >R

    DUP OAUTH2-RESOURCE-METADATA-SIZE _ATOP-FIXED-STATUS
    ?DUP IF SWAP DROP R> DROP EXIT THEN
    DUP OAUTH2-RESOURCE-METADATA-SIZE
    R@ AT-OAUTH-PROFILE-SIZE MSPAN-OVERLAP? IF
        DROP R> DROP AT-OAUTH-PROFILE-S-ALIAS EXIT
    THEN
    DUP OAUTH2-RESOURCE-METADATA-VALID? 0= IF
        DROP
        AT-OAUTH-PROFILE-S-RESOURCE-METADATA R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    R> _ATOP-RESOURCE-ADMITTED ;

\ =====================================================================
\  Authorization-server profile and final transition
\ =====================================================================

OAUTH2-METADATA-P-ISSUER
OAUTH2-METADATA-P-AUTHORIZATION-ENDPOINT OR
OAUTH2-METADATA-P-TOKEN-ENDPOINT OR
OAUTH2-METADATA-P-PAR-ENDPOINT OR
OAUTH2-METADATA-P-REQUIRE-PAR OR
OAUTH2-METADATA-P-RESPONSE-TYPES OR
OAUTH2-METADATA-P-GRANT-TYPES OR
OAUTH2-METADATA-P-CODE-CHALLENGE-METHODS OR
OAUTH2-METADATA-P-DPOP-ALGORITHMS OR
OAUTH2-METADATA-P-TOKEN-AUTH-METHODS OR
OAUTH2-METADATA-P-SCOPES OR
OAUTH2-METADATA-P-TOKEN-AUTH-SIGNING-ALGORITHMS OR
OAUTH2-METADATA-P-AUTHORIZATION-RESPONSE-ISS OR
OAUTH2-METADATA-P-CLIENT-ID-METADATA-DOCUMENT OR
CONSTANT _ATOP-REQUIRED-PRESENCE

OAUTH2-METADATA-F-PAR-REQUIRED
OAUTH2-METADATA-F-RESPONSE-CODE OR
OAUTH2-METADATA-F-GRANT-AUTHORIZATION-CODE OR
OAUTH2-METADATA-F-GRANT-REFRESH-TOKEN OR
OAUTH2-METADATA-F-PKCE-S256 OR
OAUTH2-METADATA-F-DPOP-ES256 OR
OAUTH2-METADATA-F-TOKEN-AUTH-NONE OR
OAUTH2-METADATA-F-TOKEN-AUTH-PRIVATE-KEY-JWT OR
OAUTH2-METADATA-F-TOKEN-AUTH-SIGNING-ES256 OR
OAUTH2-METADATA-F-AUTHORIZATION-RESPONSE-ISS OR
OAUTH2-METADATA-F-CLIENT-ID-METADATA-DOCUMENT OR
CONSTANT _ATOP-REQUIRED-FLAGS

: _ATOP-METADATA-PROFILE?  ( metadata -- flag )
    DUP OAUTH2-METADATA-PRESENCE@
    DUP OAUTH2-METADATA-S-OK <> IF
        2DROP DROP 0 EXIT
    THEN
    DROP
    OVER OAUTH2-METADATA-FLAGS@
    DUP OAUTH2-METADATA-S-OK <> IF
        2DROP 2DROP 0 EXIT
    THEN
    DROP

    OVER _ATOP-REQUIRED-PRESENCE
    _ATOP-BITS-CONTAIN? 0= IF
        2DROP DROP 0 EXIT
    THEN
    DUP _ATOP-REQUIRED-FLAGS
    _ATOP-BITS-CONTAIN? 0= IF
        2DROP DROP 0 EXIT
    THEN

    OVER OAUTH2-METADATA-P-REQUIRE-REQUEST-URI-REGISTRATION
    AND IF
        DUP OAUTH2-METADATA-F-REQUIRE-REQUEST-URI-REGISTRATION
        AND 0= IF
            2DROP DROP 0 EXIT
        THEN
    THEN
    2DROP

    S" atproto" 2 PICK OAUTH2-METADATA-SCOPE?
    DUP OAUTH2-METADATA-S-OK <> IF
        2DROP DROP 0 EXIT
    THEN
    DROP 0= IF DROP 0 EXIT THEN

    S" none" 2 PICK
    OAUTH2-METADATA-TOKEN-AUTH-SIGNING-ALG?
    DUP OAUTH2-METADATA-S-OK <> IF
        2DROP DROP 0 EXIT
    THEN
    DROP IF DROP 0 EXIT THEN
    DROP -1 ;

: _ATOP-PARSE-ENDPOINT
  ( metadata accessor-xt target check-field -- status )
    2>R EXECUTE
    DUP OAUTH2-METADATA-S-OK <> IF
        2DROP DROP
        2R> 2DROP
        AT-OAUTH-PROFILE-S-ENDPOINT EXIT
    THEN
    DROP
    2R@ DROP HTARGET-PARSE
    HTARGET-S-OK <> IF
        2R> 2DROP
        AT-OAUTH-PROFILE-S-ENDPOINT EXIT
    THEN
    2R> _ATOP-TARGET-CHECK!
    AT-OAUTH-PROFILE-S-OK ;

: _ATOP-AS-ADMITTED  ( metadata profile -- status )
    >R
    DUP OAUTH2-METADATA-ISSUER@
    DUP OAUTH2-METADATA-S-OK <> IF
        >R 2DROP DROP R> DROP
        AT-OAUTH-PROFILE-S-AUTHORIZATION-SERVER R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    DROP
    2DUP R@ _ATOP.AUTHORIZATION-SERVER
    _ATOP-CANONICAL-ORIGIN? 0= IF
        2DROP DROP
        AT-OAUTH-PROFILE-S-ISSUER-BINDING R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    2DROP

    DUP _ATOP-METADATA-PROFILE? 0= IF
        DROP
        AT-OAUTH-PROFILE-S-PROFILE R@ _ATOP-FAIL
        R> DROP EXIT
    THEN

    DUP ['] OAUTH2-METADATA-AUTHORIZATION-ENDPOINT@
    R@ _ATOP.AUTHORIZATION
    R@ _ATOP.AUTHORIZATION-CHECK
    _ATOP-PARSE-ENDPOINT
    DUP AT-OAUTH-PROFILE-S-OK <> IF
        SWAP DROP R@ _ATOP-FAIL R> DROP EXIT
    THEN
    DROP

    DUP ['] OAUTH2-METADATA-TOKEN-ENDPOINT@
    R@ _ATOP.TOKEN R@ _ATOP.TOKEN-CHECK
    _ATOP-PARSE-ENDPOINT
    DUP AT-OAUTH-PROFILE-S-OK <> IF
        SWAP DROP R@ _ATOP-FAIL R> DROP EXIT
    THEN
    DROP

    DUP ['] OAUTH2-METADATA-PAR-ENDPOINT@
    R@ _ATOP.PAR R@ _ATOP.PAR-CHECK
    _ATOP-PARSE-ENDPOINT
    DUP AT-OAUTH-PROFILE-S-OK <> IF
        SWAP DROP R@ _ATOP-FAIL R> DROP EXIT
    THEN
    DROP DROP

    AT-OAUTH-PROFILE-PHASE-READY R@ _ATOP.PHASE !
    R> DROP
    AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-AUTHORIZATION-SERVER!
  ( metadata profile -- status )
    DUP _ATOP-OBJECT-STATUS ?DUP IF
        >R 2DROP R> EXIT
    THEN
    DUP AT-OAUTH-PROFILE-VALID? 0= IF
        2DROP AT-OAUTH-PROFILE-S-INVALID EXIT
    THEN
    DUP _ATOP.PHASE @
    AT-OAUTH-PROFILE-PHASE-AUTHORIZATION-SERVER-METADATA <> IF
        2DROP AT-OAUTH-PROFILE-S-STATE EXIT
    THEN
    >R

    DUP OAUTH2-METADATA-SIZE _ATOP-FIXED-STATUS
    ?DUP IF SWAP DROP R> DROP EXIT THEN
    DUP OAUTH2-METADATA-SIZE
    R@ AT-OAUTH-PROFILE-SIZE MSPAN-OVERLAP? IF
        DROP R> DROP AT-OAUTH-PROFILE-S-ALIAS EXIT
    THEN
    DUP OAUTH2-METADATA-VALID? 0= IF
        DROP
        AT-OAUTH-PROFILE-S-AUTHORIZATION-SERVER R@ _ATOP-FAIL
        R> DROP EXIT
    THEN
    R> _ATOP-AS-ADMITTED ;

\ =====================================================================
\  Phase-gated trusted accessors
\ =====================================================================

: _ATOP-IDENTITY-ACCESS-STATUS  ( profile -- status )
    DUP AT-OAUTH-PROFILE-VALID? 0= IF
        DROP AT-OAUTH-PROFILE-S-INVALID EXIT
    THEN
    DUP _ATOP.PHASE @ AT-OAUTH-PROFILE-PHASE-FAILED = IF
        _ATOP.STATUS @ EXIT
    THEN
    _ATOP.PHASE @
    DUP AT-OAUTH-PROFILE-PHASE-RESOURCE-METADATA >=
    SWAP AT-OAUTH-PROFILE-PHASE-READY <= AND IF
        AT-OAUTH-PROFILE-S-OK
    ELSE
        AT-OAUTH-PROFILE-S-STATE
    THEN ;

: _ATOP-AUTHORITY-ACCESS-STATUS  ( profile -- status )
    DUP AT-OAUTH-PROFILE-VALID? 0= IF
        DROP AT-OAUTH-PROFILE-S-INVALID EXIT
    THEN
    DUP _ATOP.PHASE @ AT-OAUTH-PROFILE-PHASE-FAILED = IF
        _ATOP.STATUS @ EXIT
    THEN
    _ATOP.PHASE @
    DUP AT-OAUTH-PROFILE-PHASE-AUTHORIZATION-SERVER-METADATA >=
    SWAP AT-OAUTH-PROFILE-PHASE-READY <= AND IF
        AT-OAUTH-PROFILE-S-OK
    ELSE
        AT-OAUTH-PROFILE-S-STATE
    THEN ;

: _ATOP-READY-ACCESS-STATUS  ( profile -- status )
    DUP AT-OAUTH-PROFILE-VALID? 0= IF
        DROP AT-OAUTH-PROFILE-S-INVALID EXIT
    THEN
    DUP _ATOP.PHASE @ AT-OAUTH-PROFILE-PHASE-FAILED = IF
        _ATOP.STATUS @ EXIT
    THEN
    _ATOP.PHASE @ AT-OAUTH-PROFILE-PHASE-READY = IF
        AT-OAUTH-PROFILE-S-OK
    ELSE
        AT-OAUTH-PROFILE-S-STATE
    THEN ;

: AT-OAUTH-PROFILE-PHASE@  ( profile -- phase status )
    DUP AT-OAUTH-PROFILE-VALID? 0= IF
        DROP 0 AT-OAUTH-PROFILE-S-INVALID EXIT
    THEN
    _ATOP.PHASE @ AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-STATUS@  ( profile -- status )
    DUP AT-OAUTH-PROFILE-VALID? 0= IF
        DROP AT-OAUTH-PROFILE-S-INVALID EXIT
    THEN
    _ATOP.STATUS @ ;

: AT-OAUTH-PROFILE-DID@
  ( profile -- address length status )
    DUP _ATOP-IDENTITY-ACCESS-STATUS ?DUP IF
        >R DROP 0 0 R> EXIT
    THEN
    DUP _ATOP.DID SWAP _ATOP.DID-U @
    AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-RESOURCE@
  ( profile -- address length status )
    DUP _ATOP-IDENTITY-ACCESS-STATUS ?DUP IF
        >R DROP 0 0 R> EXIT
    THEN
    _ATOP.PDS _ATOP-ORIGIN$
    AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-PDS-TARGET@  ( profile -- target status )
    DUP _ATOP-IDENTITY-ACCESS-STATUS ?DUP IF
        >R DROP 0 R> EXIT
    THEN
    _ATOP.PDS AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-RESOURCE-METADATA-TARGET@
  ( profile -- target status )
    DUP _ATOP-IDENTITY-ACCESS-STATUS ?DUP IF
        >R DROP 0 R> EXIT
    THEN
    _ATOP.RESOURCE-METADATA AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-ISSUER@
  ( profile -- address length status )
    DUP _ATOP-AUTHORITY-ACCESS-STATUS ?DUP IF
        >R DROP 0 0 R> EXIT
    THEN
    _ATOP.AUTHORIZATION-SERVER _ATOP-ORIGIN$
    AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-AUTHORIZATION-SERVER-TARGET@
  ( profile -- target status )
    DUP _ATOP-AUTHORITY-ACCESS-STATUS ?DUP IF
        >R DROP 0 R> EXIT
    THEN
    _ATOP.AUTHORIZATION-SERVER AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-AUTHORIZATION-SERVER-METADATA-TARGET@
  ( profile -- target status )
    DUP _ATOP-AUTHORITY-ACCESS-STATUS ?DUP IF
        >R DROP 0 R> EXIT
    THEN
    _ATOP.AUTHORIZATION-SERVER-METADATA
    AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-AUTHORIZATION-TARGET@
  ( profile -- target status )
    DUP _ATOP-READY-ACCESS-STATUS ?DUP IF
        >R DROP 0 R> EXIT
    THEN
    _ATOP.AUTHORIZATION AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-TOKEN-TARGET@
  ( profile -- target status )
    DUP _ATOP-READY-ACCESS-STATUS ?DUP IF
        >R DROP 0 R> EXIT
    THEN
    _ATOP.TOKEN AT-OAUTH-PROFILE-S-OK ;

: AT-OAUTH-PROFILE-PAR-TARGET@
  ( profile -- target status )
    DUP _ATOP-READY-ACCESS-STATUS ?DUP IF
        >R DROP 0 R> EXIT
    THEN
    _ATOP.PAR AT-OAUTH-PROFILE-S-OK ;

\ =====================================================================
\  Compile-time geometry assertions
\ =====================================================================

: _ATOP-GEOMETRY-ABORT  ( -- )
    ." AT OAuth profile geometry mismatch" CR ABORT ;

1 CELLS 8 <> [IF]
    _ATOP-GEOMETRY-ABORT
[THEN]

_ATOP-DID-OFF AT-OAUTH-PROFILE-DID-CAPACITY +
_ATOP-PDS-OFF <> [IF]
    _ATOP-GEOMETRY-ABORT
[THEN]

_ATOP-SCRATCH-OFF HTARGET-URI-CAPACITY +
AT-OAUTH-PROFILE-SIZE <> [IF]
    _ATOP-GEOMETRY-ABORT
[THEN]
