\ =====================================================================
\ public-author-feed.f - bounded public Bluesky author-feed exchange
\ =====================================================================
\ This provider owns one request, buffered response exchange, and KDOS TLS
\ adapter per descriptor.  It performs wire admission only: callers decode
\ and commit the retained response through a separate feed-model boundary.
\ =====================================================================

PROVIDED akashic-atproto-public-author-feed

REQUIRE ../net/external-io.f
REQUIRE ../net/http-buffered.f
REQUIRE ../net/transports/kdos-tls.f
REQUIRE did.f

2048 CONSTANT PAF-ACTOR-CAPACITY
7168 CONSTANT PAF-PATH-CAPACITY
8192 CONSTANT PAF-REQUEST-CAPACITY
262144 CONSTANT PAF-BODY-CAPACITY

0 CONSTANT PAF-S-OK
1 CONSTANT PAF-S-INVALID
2 CONSTANT PAF-S-BUSY
3 CONSTANT PAF-S-CAPACITY
4 CONSTANT PAF-S-TRANSPORT

0 CONSTANT PAF-STATE-IDLE
1 CONSTANT PAF-STATE-CONFIGURED
2 CONSTANT PAF-STATE-ACTIVE
3 CONSTANT PAF-STATE-READY
4 CONSTANT PAF-STATE-FAILED
5 CONSTANT PAF-STATE-CANCELLED
6 CONSTANT PAF-STATE-RELEASED

0 CONSTANT PAF-ERR-NONE
1 CONSTANT PAF-ERR-CONFIG
2 CONSTANT PAF-ERR-UNSUPPORTED
3 CONSTANT PAF-ERR-CAPACITY
4 CONSTANT PAF-ERR-TRANSPORT
5 CONSTANT PAF-ERR-HTTP
6 CONSTANT PAF-ERR-MEDIA-TYPE
7 CONSTANT PAF-ERR-CONTENT-ENCODING
8 CONSTANT PAF-ERR-CLEANUP
9 CONSTANT PAF-ERR-STATE

1 CONSTANT PAF-CODE-ACTOR
2 CONSTANT PAF-CODE-REQUEST
3 CONSTANT PAF-CODE-ALLOCATE
4 CONSTANT PAF-CODE-NONCOOPERATIVE
5 CONSTANT PAF-CODE-CONTENT-TYPE-MISSING
6 CONSTANT PAF-CODE-CONTENT-TYPE-DUPLICATE
7 CONSTANT PAF-CODE-CONTENT-TYPE-MISMATCH
8 CONSTANT PAF-CODE-CONTENT-ENCODING-DUPLICATE
9 CONSTANT PAF-CODE-CONTENT-ENCODING-MISMATCH
10 CONSTANT PAF-CODE-BODY-OVERFLOW
11 CONSTANT PAF-CODE-CLEANUP

-4701 CONSTANT PAF-XERR-INVALID
-4702 CONSTANT PAF-XERR-UNSUPPORTED
-4703 CONSTANT PAF-XERR-CAPACITY
-4704 CONSTANT PAF-XERR-TRANSPORT
-4705 CONSTANT PAF-XERR-HTTP
-4706 CONSTANT PAF-XERR-MEDIA-TYPE
-4707 CONSTANT PAF-XERR-CONTENT-ENCODING
-4708 CONSTANT PAF-XERR-CLEANUP
-4709 CONSTANT PAF-XERR-STATE

1 CONSTANT _PAF-F-CANCEL-CALLED
2 CONSTANT _PAF-F-WIPE-CALLED
4 CONSTANT _PAF-F-BODY-OWNED

0x46415042 CONSTANT PAF-MAGIC  \ "BPAF" in memory

   0 CONSTANT _PAF-MAGIC
   8 CONSTANT _PAF-STATE
  16 CONSTANT _PAF-ACTOR-U
  24 CONSTANT _PAF-BODY-A
  32 CONSTANT _PAF-BODY-U
  40 CONSTANT _PAF-ERROR-KIND
  48 CONSTANT _PAF-ERROR-CODE
  56 CONSTANT _PAF-CLEANUP-ERROR
  64 CONSTANT _PAF-HTTP-CODE
  72 CONSTANT _PAF-FLAGS
  80 CONSTANT _PAF-PATH-U
  88 CONSTANT _PAF-ACTOR
_PAF-ACTOR PAF-ACTOR-CAPACITY + CONSTANT _PAF-PATH
_PAF-PATH PAF-PATH-CAPACITY + CONSTANT _PAF-WIRE
_PAF-WIRE PAF-REQUEST-CAPACITY + CONSTANT _PAF-TRANSPORT
_PAF-TRANSPORT KDOSTLS-SIZE + CONSTANT _PAF-REQUEST
_PAF-REQUEST HTTP-REQUEST-SIZE + CONSTANT _PAF-EXCHANGE
_PAF-EXCHANGE HTTP-BUFFERED-SIZE + CONSTANT PUBLIC-AUTHOR-FEED-SIZE

: PAF.MAGIC          ( provider -- a ) _PAF-MAGIC + ;
: PAF.STATE          ( provider -- a ) _PAF-STATE + ;
: PAF.ACTOR-U        ( provider -- a ) _PAF-ACTOR-U + ;
: PAF.BODY-A         ( provider -- a ) _PAF-BODY-A + ;
: PAF.BODY-U         ( provider -- a ) _PAF-BODY-U + ;
: PAF.ERROR-KIND     ( provider -- a ) _PAF-ERROR-KIND + ;
: PAF.ERROR-CODE     ( provider -- a ) _PAF-ERROR-CODE + ;
: PAF.CLEANUP-ERROR  ( provider -- a ) _PAF-CLEANUP-ERROR + ;
: PAF.HTTP-CODE      ( provider -- a ) _PAF-HTTP-CODE + ;
: PAF.FLAGS          ( provider -- a ) _PAF-FLAGS + ;
: PAF.PATH-U         ( provider -- a ) _PAF-PATH-U + ;
: PAF.ACTOR          ( provider -- a ) _PAF-ACTOR + ;
: PAF.PATH           ( provider -- a ) _PAF-PATH + ;
: PAF.WIRE           ( provider -- a ) _PAF-WIRE + ;
: PAF.TRANSPORT      ( provider -- transport ) _PAF-TRANSPORT + ;
: PAF.PORT           ( provider -- port ) PAF.TRANSPORT KDOSTLS.PORT ;
: PAF.REQUEST        ( provider -- request ) _PAF-REQUEST + ;
: PAF.EXCHANGE       ( provider -- exchange ) _PAF-EXCHANGE + ;

: PAF-ACTOR@  ( provider -- addr len )
    DUP PAF.ACTOR SWAP PAF.ACTOR-U @ ;

: PAF-PATH@  ( provider -- addr len )
    DUP PAF.PATH SWAP PAF.PATH-U @ ;

: PAF-BODY@  ( provider -- addr len )
    DUP PAF.BODY-A @ SWAP PAF.BODY-U @ ;

: PAF-VALID?  ( provider -- flag )
    DUP 0= IF DROP 0 EXIT THEN PAF.MAGIC @ PAF-MAGIC = ;

: PAF-PUBLIC-HOST  ( -- addr len ) S" public.api.bsky.app" ;

: _PAF-UNRESERVED?  ( c -- flag )
    DUP 65 >= OVER 90 <= AND IF DROP -1 EXIT THEN
    DUP 97 >= OVER 122 <= AND IF DROP -1 EXIT THEN
    DUP 48 >= OVER 57 <= AND IF DROP -1 EXIT THEN
    DUP 45 = OVER 46 = OR OVER 95 = OR SWAP 126 = OR ;

: _PAF-DID-ID-CHAR?  ( c -- flag )
    DUP 65 >= OVER 90 <= AND >R
    DUP 97 >= OVER 122 <= AND R> OR >R
    DUP 48 >= OVER 57 <= AND R> OR >R
    DUP 46 = OVER 95 = OR OVER 58 = OR
    OVER 37 = OR SWAP 45 = OR R> OR ;

: _PAF-DID-END-CHAR?  ( c -- flag )
    DUP 65 >= OVER 90 <= AND >R
    DUP 97 >= OVER 122 <= AND R> OR >R
    DUP 48 >= OVER 57 <= AND R> OR >R
    DUP 46 = OVER 95 = OR SWAP 45 = OR R> OR ;

: _PAF-HEX-CHAR?  ( c -- flag )
    DUP 48 >= OVER 57 <= AND IF DROP -1 EXIT THEN
    DUP 65 >= OVER 70 <= AND IF DROP -1 EXIT THEN
    DUP 97 >= SWAP 102 <= AND ;

VARIABLE _PAFVA-A
VARIABLE _PAFVA-U

: _PAF-DID-CHARS?  ( addr len -- flag )
    _PAFVA-U ! _PAFVA-A !
    _PAFVA-U @ 9 < IF 0 EXIT THEN
    _PAFVA-U @ 8 ?DO
        _PAFVA-A @ I + C@ DUP 37 = IF
            DROP I 2 + _PAFVA-U @ >= IF 0 UNLOOP EXIT THEN
            _PAFVA-A @ I + 1+ C@ _PAF-HEX-CHAR? 0= IF
                0 UNLOOP EXIT
            THEN
            _PAFVA-A @ I + 2 + C@ _PAF-HEX-CHAR? 0= IF
                0 UNLOOP EXIT
            THEN
        ELSE
            _PAF-DID-ID-CHAR? 0= IF 0 UNLOOP EXIT THEN
        THEN
    LOOP -1 ;

: _PAF-ACTOR-VALID?  ( addr len -- flag )
    DUP 0= OVER PAF-ACTOR-CAPACITY > OR IF 2DROP 0 EXIT THEN
    2DUP DID-VALID? IF
        2DUP _PAF-DID-CHARS? 0= IF 2DROP 0 EXIT THEN
        1- + C@ _PAF-DID-END-CHAR? EXIT
    THEN
    FALSE DNS-NAME-VALID? ;

VARIABLE _PAFE-KIND
VARIABLE _PAFE-CODE
VARIABLE _PAFE-XERR
VARIABLE _PAFE-OP
VARIABLE _PAFE-P

: _PAF-ERROR!  ( kind code provider -- )
    >R R@ PAF.ERROR-CODE ! R> PAF.ERROR-KIND ! ;

: _PAF-STEP-FAIL  ( kind code xerr operation provider -- step-status )
    _PAFE-P ! _PAFE-OP ! _PAFE-XERR ! _PAFE-CODE ! _PAFE-KIND !
    _PAFE-KIND @ _PAFE-CODE @ _PAFE-P @ _PAF-ERROR!
    PAF-STATE-FAILED _PAFE-P @ PAF.STATE !
    _PAFE-XERR @ _PAFE-OP @ XIOO.ERROR !
    XIO-STEP-FAILED ;

: _PAF-HEX  ( nibble -- c )
    DUP 10 < IF 48 + ELSE 10 - 65 + THEN ;

VARIABLE _PAFB-P
VARIABLE _PAFB-A
VARIABLE _PAFB-U

: _PAF-PATH-C!  ( c -- flag )
    _PAFB-P @ PAF.PATH-U @ PAF-PATH-CAPACITY >= IF DROP 0 EXIT THEN
    _PAFB-P @ PAF.PATH _PAFB-P @ PAF.PATH-U @ + C!
    1 _PAFB-P @ PAF.PATH-U +! -1 ;

: _PAF-PATH-APPEND  ( addr len -- flag )
    _PAFB-U ! _PAFB-A !
    _PAFB-P @ PAF.PATH-U @ _PAFB-U @ + PAF-PATH-CAPACITY > IF 0 EXIT THEN
    _PAFB-A @ _PAFB-P @ PAF.PATH _PAFB-P @ PAF.PATH-U @ +
    _PAFB-U @ CMOVE
    _PAFB-U @ _PAFB-P @ PAF.PATH-U +! -1 ;

: _PAF-ACTOR-ENCODE  ( -- flag )
    _PAFB-P @ PAF-ACTOR@ 0 ?DO
        DUP I + C@ DUP _PAF-UNRESERVED? IF
            _PAF-PATH-C! 0= IF DROP 0 UNLOOP EXIT THEN
        ELSE
            37 _PAF-PATH-C! 0= IF 2DROP 0 UNLOOP EXIT THEN
            DUP 4 RSHIFT _PAF-HEX _PAF-PATH-C! 0= IF
                2DROP 0 UNLOOP EXIT
            THEN
            15 AND _PAF-HEX _PAF-PATH-C! 0= IF DROP 0 UNLOOP EXIT THEN
        THEN
    LOOP DROP -1 ;

: _PAF-BUILD-PATH  ( provider -- flag )
    DUP _PAFB-P ! DUP PAF.PATH PAF-PATH-CAPACITY 0 FILL
    0 SWAP PAF.PATH-U !
    S" /xrpc/app.bsky.feed.getAuthorFeed?actor=" _PAF-PATH-APPEND 0= IF 0 EXIT THEN
    _PAF-ACTOR-ENCODE 0= IF 0 EXIT THEN
    S" &limit=8&filter=posts_no_replies&includePins=false" _PAF-PATH-APPEND ;

VARIABLE _PAFR-P
VARIABLE _PAFR-S

: _PAF-BUILD-REQUEST  ( provider -- status )
    _PAFR-P !
    _PAFR-P @ PAF.WIRE PAF-REQUEST-CAPACITY
    _PAFR-P @ PAF.REQUEST HREQ-INIT DUP IF EXIT THEN DROP
    _PAFR-P @ _PAF-BUILD-PATH 0= IF HREQ-S-CAPACITY EXIT THEN
    S" GET" _PAFR-P @ PAF-PATH@
    _PAFR-P @ PAF.REQUEST HREQ-BEGIN ?DUP IF EXIT THEN
    PAF-PUBLIC-HOST _PAFR-P @ PAF.REQUEST HREQ-HOST ?DUP IF EXIT THEN
    S" application/json" _PAFR-P @ PAF.REQUEST HREQ-ACCEPT ?DUP IF EXIT THEN
    S" Accept-Encoding" S" identity" _PAFR-P @ PAF.REQUEST HREQ-HEADER
    ?DUP IF EXIT THEN
    S" Akashic-Streams/0.3" _PAFR-P @ PAF.REQUEST HREQ-USER-AGENT
    ?DUP IF EXIT THEN
    _PAFR-P @ PAF.REQUEST HREQ-CONNECTION-CLOSE ?DUP IF EXIT THEN
    _PAFR-P @ PAF.REQUEST HREQ-SEAL ;

: _PAF-COOPERATIVE-PORT?  ( provider -- flag )
    PAF.PORT
    DUP NIO.OPEN-START-XT @ 0<>
    OVER NIO.OPEN-POLL-XT @ 0<> AND
    SWAP NIO.CANCEL-XT @ 0<> AND ;

: _PAF-ALLOCATE-BODY  ( provider -- status )
    DUP PAF.BODY-A @ IF DROP PAF-S-BUSY EXIT THEN
    PAF-BODY-CAPACITY ALLOCATE DUP IF
        >R 2DROP R> DROP PAF-S-CAPACITY EXIT
    THEN DROP
    DUP PAF-BODY-CAPACITY 0 FILL
    OVER PAF.BODY-A !
    0 OVER PAF.BODY-U !
    DUP PAF.FLAGS DUP @ _PAF-F-BODY-OWNED OR SWAP !
    DROP PAF-S-OK ;

: _PAF-CLEAR-PRIMARY  ( provider -- )
    DUP 0 SWAP PAF.ERROR-KIND !
    DUP 0 SWAP PAF.ERROR-CODE !
    DUP 0 SWAP PAF.HTTP-CODE !
    DUP 0 SWAP PAF.BODY-U !
    DUP PAF.FLAGS DUP @
    _PAF-F-CANCEL-CALLED _PAF-F-WIPE-CALLED OR INVERT AND SWAP !
    DROP ;

VARIABLE _PAFS-OP
VARIABLE _PAFS-P
VARIABLE _PAFS-STATUS

: PAF-XIO-START  ( operation provider -- step-status )
    _PAFS-P ! _PAFS-OP !
    _PAFS-P @ PAF-VALID? 0= IF
        PAF-XERR-INVALID _PAFS-OP @ XIOO.ERROR ! XIO-STEP-FAILED EXIT
    THEN
    _PAFS-P @ PAF.CLEANUP-ERROR @ IF
        PAF-ERR-CLEANUP PAF-CODE-CLEANUP PAF-XERR-CLEANUP
        _PAFS-OP @ _PAFS-P @ _PAF-STEP-FAIL EXIT
    THEN
    _PAFS-P @ PAF.STATE @ DUP PAF-STATE-CONFIGURED =
    SWAP PAF-STATE-RELEASED = OR 0= IF
        PAF-ERR-STATE PAF-S-BUSY PAF-XERR-STATE
        _PAFS-OP @ _PAFS-P @ _PAF-STEP-FAIL EXIT
    THEN
    _PAFS-P @ _PAF-COOPERATIVE-PORT? 0= IF
        PAF-ERR-UNSUPPORTED PAF-CODE-NONCOOPERATIVE PAF-XERR-UNSUPPORTED
        _PAFS-OP @ _PAFS-P @ _PAF-STEP-FAIL EXIT
    THEN
    _PAFS-P @ _PAF-CLEAR-PRIMARY
    _PAFS-P @ _PAF-ALLOCATE-BODY DUP PAF-S-OK <> IF
        DROP PAF-ERR-CAPACITY PAF-CODE-ALLOCATE PAF-XERR-CAPACITY
        _PAFS-OP @ _PAFS-P @ _PAF-STEP-FAIL EXIT
    THEN DROP
    _PAFS-P @ _PAF-BUILD-REQUEST DUP _PAFS-STATUS ! IF
        PAF-ERR-CAPACITY _PAFS-STATUS @ PAF-XERR-CAPACITY
        _PAFS-OP @ _PAFS-P @ _PAF-STEP-FAIL EXIT
    THEN
    _PAFS-P @ PAF.BODY-A @ PAF-BODY-CAPACITY
    _PAFS-P @ PAF.EXCHANGE HBUF-INIT HBUF-S-OK <> IF
        PAF-ERR-CAPACITY PAF-CODE-ALLOCATE PAF-XERR-CAPACITY
        _PAFS-OP @ _PAFS-P @ _PAF-STEP-FAIL EXIT
    THEN
    PAF-BODY-CAPACITY _PAFS-P @ PAF.EXCHANGE HBUF.PARSER HSTR-BODY-LIMIT!
    _PAFS-P @ PAF.REQUEST _PAFS-P @ PAF.PORT
    _PAFS-P @ PAF.EXCHANGE HBUF-START DUP _PAFS-STATUS !
    HBUF-S-PENDING = IF
        PAF-STATE-ACTIVE _PAFS-P @ PAF.STATE ! XIO-STEP-PENDING EXIT
    THEN
    PAF-ERR-TRANSPORT _PAFS-STATUS @ PAF-XERR-TRANSPORT
    _PAFS-OP @ _PAFS-P @ _PAF-STEP-FAIL ;

VARIABLE _PAFA-P
VARIABLE _PAFA-COUNT

VARIABLE _PAFMT-BASE-A
VARIABLE _PAFMT-BASE-U
VARIABLE _PAFMT-PARAM-A
VARIABLE _PAFMT-PARAM-U
VARIABLE _PAFMT-FOUND

: _PAF-MEDIA-PARAMS-SAFE?  ( addr len -- flag )
    STR-TRIM DUP 0= IF 2DROP 0 EXIT THEN
    0 ?DO
        DUP I + C@ DUP 9 = IF
            DROP
        ELSE
            DUP 32 < SWAP 126 > OR IF DROP 0 UNLOOP EXIT THEN
        THEN
    LOOP DROP -1 ;

: _PAF-APPLICATION-JSON?  ( addr len -- flag )
    STR-TRIM [CHAR] ; STR-SPLIT
    _PAFMT-FOUND ! _PAFMT-PARAM-U ! _PAFMT-PARAM-A !
    _PAFMT-BASE-U ! _PAFMT-BASE-A !
    _PAFMT-BASE-A @ _PAFMT-BASE-U @ STR-TRIM
    S" application/json" STR-STRI= 0= IF 0 EXIT THEN
    _PAFMT-FOUND @ 0= IF -1 EXIT THEN
    _PAFMT-PARAM-A @ _PAFMT-PARAM-U @ _PAF-MEDIA-PARAMS-SAFE? ;

: _PAF-ADMIT-CONTENT-TYPE  ( provider -- xerr | 0 )
    DUP _PAFA-P ! DROP
    S" content-type" _PAFA-P @ PAF.EXCHANGE HBUF.PARSER
    HSTR-HEADER-COUNT DUP _PAFA-COUNT !
    0= IF
        PAF-ERR-MEDIA-TYPE PAF-CODE-CONTENT-TYPE-MISSING _PAFA-P @ _PAF-ERROR!
        PAF-XERR-MEDIA-TYPE EXIT
    THEN
    _PAFA-COUNT @ 1 <> IF
        PAF-ERR-MEDIA-TYPE PAF-CODE-CONTENT-TYPE-DUPLICATE _PAFA-P @ _PAF-ERROR!
        PAF-XERR-MEDIA-TYPE EXIT
    THEN
    S" content-type" _PAFA-P @ PAF.EXCHANGE HBUF.PARSER HSTR-HEADER IF
        _PAF-APPLICATION-JSON? IF 0 EXIT THEN
    ELSE
        2DROP
    THEN
    PAF-ERR-MEDIA-TYPE PAF-CODE-CONTENT-TYPE-MISMATCH _PAFA-P @ _PAF-ERROR!
    PAF-XERR-MEDIA-TYPE ;

: _PAF-ADMIT-CONTENT-ENCODING  ( provider -- xerr | 0 )
    DUP _PAFA-P ! DROP
    S" content-encoding" _PAFA-P @ PAF.EXCHANGE HBUF.PARSER
    HSTR-HEADER-COUNT DUP _PAFA-COUNT !
    0= IF 0 EXIT THEN
    _PAFA-COUNT @ 1 <> IF
        PAF-ERR-CONTENT-ENCODING PAF-CODE-CONTENT-ENCODING-DUPLICATE
        _PAFA-P @ _PAF-ERROR! PAF-XERR-CONTENT-ENCODING EXIT
    THEN
    S" content-encoding" _PAFA-P @ PAF.EXCHANGE HBUF.PARSER HSTR-HEADER IF
        S" identity" STR-STRI= IF 0 EXIT THEN
    ELSE
        2DROP
    THEN
    PAF-ERR-CONTENT-ENCODING PAF-CODE-CONTENT-ENCODING-MISMATCH
    _PAFA-P @ _PAF-ERROR! PAF-XERR-CONTENT-ENCODING ;

: _PAF-ADMIT  ( operation provider -- step-status )
    _PAFS-P ! _PAFS-OP !
    _PAFS-P @ PAF.EXCHANGE HBUF.HTTP-CODE @ DUP
    _PAFS-P @ PAF.HTTP-CODE ! 200 <> IF
        PAF-ERR-HTTP _PAFS-P @ PAF.HTTP-CODE @ PAF-XERR-HTTP
        _PAFS-OP @ _PAFS-P @ _PAF-STEP-FAIL EXIT
    THEN
    _PAFS-P @ _PAF-ADMIT-CONTENT-TYPE ?DUP IF
        DUP _PAFS-OP @ XIOO.ERROR ! DROP
        PAF-STATE-FAILED _PAFS-P @ PAF.STATE ! XIO-STEP-FAILED EXIT
    THEN
    _PAFS-P @ _PAF-ADMIT-CONTENT-ENCODING ?DUP IF
        DUP _PAFS-OP @ XIOO.ERROR ! DROP
        PAF-STATE-FAILED _PAFS-P @ PAF.STATE ! XIO-STEP-FAILED EXIT
    THEN
    _PAFS-P @ PAF.EXCHANGE HBUF.BODY-U @ _PAFS-P @ PAF.BODY-U !
    _PAFS-P @ _PAFS-OP @ XIOO.RESULT !
    PAF-STATE-READY _PAFS-P @ PAF.STATE ! XIO-STEP-SUCCEEDED ;

: PAF-XIO-POLL  ( operation provider -- step-status )
    _PAFS-P ! _PAFS-OP !
    _PAFS-P @ PAF-VALID? 0= IF
        PAF-XERR-INVALID _PAFS-OP @ XIOO.ERROR ! XIO-STEP-FAILED EXIT
    THEN
    _PAFS-P @ PAF.STATE @ PAF-STATE-ACTIVE <> IF
        PAF-ERR-STATE PAF-S-BUSY PAF-XERR-STATE
        _PAFS-OP @ _PAFS-P @ _PAF-STEP-FAIL EXIT
    THEN
    _PAFS-P @ PAF.EXCHANGE HBUF-POLL DUP _PAFS-STATUS !
    DUP HBUF-S-PENDING = IF DROP XIO-STEP-PENDING EXIT THEN
    HBUF-S-OK = IF _PAFS-OP @ _PAFS-P @ _PAF-ADMIT EXIT THEN
    _PAFS-P @ PAF.EXCHANGE HBUF.PARSER HSTR.STATUS @
    HSTR-S-BODY-OVERFLOW = IF
        PAF-ERR-CAPACITY PAF-CODE-BODY-OVERFLOW PAF-XERR-CAPACITY
    ELSE
        PAF-ERR-TRANSPORT _PAFS-STATUS @ PAF-XERR-TRANSPORT
    THEN
    _PAFS-OP @ _PAFS-P @ _PAF-STEP-FAIL ;

: _PAF-FLAG?  ( flag provider -- flag ) PAF.FLAGS @ AND 0<> ;
: _PAF-FLAG!  ( flag provider -- ) PAF.FLAGS DUP @ ROT OR SWAP ! ;

VARIABLE _PAFC-OP
VARIABLE _PAFC-P

: PAF-XIO-CANCEL  ( operation provider -- )
    _PAFC-P ! _PAFC-OP !
    _PAFC-P @ PAF-VALID? 0= IF EXIT THEN
    _PAF-F-CANCEL-CALLED _PAFC-P @ _PAF-FLAG? IF
        _PAFC-P @ PAF.CLEANUP-ERROR @ ?DUP IF THROW THEN EXIT
    THEN
    _PAF-F-CANCEL-CALLED _PAFC-P @ _PAF-FLAG!
    _PAFC-P @ PAF.EXCHANGE HBUF-CANCEL HBUF-S-OK <> IF
        PAF-XERR-CLEANUP _PAFC-P @ PAF.CLEANUP-ERROR !
        _PAFC-P @ PAF.ERROR-KIND @ 0= IF
            PAF-ERR-CLEANUP PAF-CODE-CLEANUP _PAFC-P @ _PAF-ERROR!
        THEN
        PAF-STATE-FAILED _PAFC-P @ PAF.STATE ! PAF-XERR-CLEANUP THROW
    THEN
    _PAFC-P @ PAF.ERROR-KIND @ 0= IF
        PAF-STATE-CANCELLED _PAFC-P @ PAF.STATE !
    THEN ;

VARIABLE _PAFW-OP
VARIABLE _PAFW-P
VARIABLE _PAFW-CLEANUP

: _PAF-FREE-BODY  ( provider -- )
    DUP PAF.BODY-A @ ?DUP IF
        DUP PAF-BODY-CAPACITY 0 FILL FREE
        0 OVER PAF.BODY-A !
    THEN
    DUP 0 SWAP PAF.BODY-U !
    DUP PAF.FLAGS DUP @ _PAF-F-BODY-OWNED INVERT AND SWAP ! DROP ;

: PAF-XIO-WIPE  ( operation provider -- )
    _PAFW-P ! _PAFW-OP !
    _PAFW-P @ PAF-VALID? 0= IF EXIT THEN
    _PAF-F-WIPE-CALLED _PAFW-P @ _PAF-FLAG? IF
        _PAFW-P @ PAF.CLEANUP-ERROR @ ?DUP IF THROW THEN EXIT
    THEN
    _PAF-F-WIPE-CALLED _PAFW-P @ _PAF-FLAG!
    0 _PAFW-CLEANUP !
    _PAFW-P @ PAF.EXCHANGE HBUF-RESET
    _PAFW-P @ PAF.EXCHANGE HBUF.PORT @ IF
        PAF-XERR-CLEANUP _PAFW-CLEANUP !
    THEN
    _PAFW-P @ _PAF-FREE-BODY
    0 _PAFW-P @ PAF.EXCHANGE HBUF.BODY-A !
    0 _PAFW-P @ PAF.EXCHANGE HBUF.BODY-CAP !
    0 _PAFW-P @ PAF.EXCHANGE HBUF.BODY-U !
    _PAFW-P @ PAF.EXCHANGE HBUF.RECV HBUF-RECV-CAPACITY 0 FILL
    _PAFW-P @ PAF.REQUEST HREQ-CLEAR
    _PAFW-P @ PAF.PATH PAF-PATH-CAPACITY 0 FILL
    0 _PAFW-P @ PAF.PATH-U !
    _PAFW-CLEANUP @ ?DUP IF
        DUP _PAFW-P @ PAF.CLEANUP-ERROR !
        _PAFW-P @ PAF.ERROR-KIND @ 0= IF
            PAF-ERR-CLEANUP PAF-CODE-CLEANUP _PAFW-P @ _PAF-ERROR!
        THEN
        PAF-STATE-FAILED _PAFW-P @ PAF.STATE ! THROW
    THEN
    _PAFW-P @ PAF.CLEANUP-ERROR @ IF
        PAF-STATE-FAILED
    ELSE
        PAF-STATE-RELEASED
    THEN _PAFW-P @ PAF.STATE ! ;

VARIABLE _PAFI-P
VARIABLE _PAFI-STATUS

: PAF-INIT  ( provider -- status )
    DUP 0= IF DROP PAF-S-INVALID EXIT THEN
    DUP _PAFI-P ! PUBLIC-AUTHOR-FEED-SIZE 0 FILL
    PAF-MAGIC _PAFI-P @ PAF.MAGIC !
    _PAFI-P @ PAF.TRANSPORT KDOSTLS-INIT
    PAF-PUBLIC-HOST 443 _PAFI-P @ PAF.TRANSPORT KDOSTLS-CONFIGURE
    DUP _PAFI-STATUS ! KDOSTLS-E-OK <> IF
        PAF-ERR-CONFIG _PAFI-STATUS @ _PAFI-P @ _PAF-ERROR!
        PAF-STATE-FAILED _PAFI-P @ PAF.STATE ! PAF-S-TRANSPORT EXIT
    THEN
    _PAFI-P @ PAF.WIRE PAF-REQUEST-CAPACITY
    _PAFI-P @ PAF.REQUEST HREQ-INIT DUP IF
        PAF-ERR-CONFIG SWAP _PAFI-P @ _PAF-ERROR!
        PAF-STATE-FAILED _PAFI-P @ PAF.STATE ! PAF-S-INVALID EXIT
    THEN DROP
    PAF-STATE-IDLE _PAFI-P @ PAF.STATE ! PAF-S-OK ;

VARIABLE _PAFCFG-A
VARIABLE _PAFCFG-U
VARIABLE _PAFCFG-P

: PAF-CONFIGURE  ( actor-a actor-u provider -- status )
    _PAFCFG-P ! _PAFCFG-U ! _PAFCFG-A !
    _PAFCFG-P @ PAF-VALID? 0= IF PAF-S-INVALID EXIT THEN
    _PAFCFG-P @ PAF.CLEANUP-ERROR @ IF PAF-S-TRANSPORT EXIT THEN
    _PAFCFG-P @ PAF.STATE @ DUP PAF-STATE-IDLE =
    OVER PAF-STATE-CONFIGURED = OR
    SWAP PAF-STATE-RELEASED = OR 0= IF PAF-S-BUSY EXIT THEN
    _PAFCFG-P @ PAF.BODY-A @ IF PAF-S-BUSY EXIT THEN
    _PAFCFG-A @ _PAFCFG-U @ _PAF-ACTOR-VALID? 0= IF
        PAF-ERR-CONFIG PAF-CODE-ACTOR _PAFCFG-P @ _PAF-ERROR!
        PAF-S-INVALID EXIT
    THEN
    _PAFCFG-P @ PAF.ACTOR PAF-ACTOR-CAPACITY 0 FILL
    _PAFCFG-A @ _PAFCFG-P @ PAF.ACTOR _PAFCFG-U @ CMOVE
    _PAFCFG-U @ _PAFCFG-P @ PAF.ACTOR-U !
    0 _PAFCFG-P @ PAF.ERROR-KIND ! 0 _PAFCFG-P @ PAF.ERROR-CODE !
    PAF-STATE-CONFIGURED _PAFCFG-P @ PAF.STATE ! PAF-S-OK ;
