\ =====================================================================
\  vfs-practice-head.f - Dual-generation VFS Practice-head storage
\ =====================================================================
\  Each slot contains a fixed, checksummed envelope around the pointer-
\  free PHEAD record.  Saves replace only the inactive slot and publish
\  the new in-memory generation after VFS-SYNC succeeds.
\
\  This is a corruption/torn-write boundary, not an authentication
\  boundary.  Practice activation must still authenticate committed
\  roots and enforce schema, manifest, export, and grant policy.
\
\  Pending grants, invocation handles, leases, queue entries, execution
\  tokens, and runtime pointers have no representation in this format.
\
\  Public API:
\    PHEADVFS-INIT          ( vfs store -- status )
\    PHEADVFS-SAVE          ( head store -- status )
\    PHEADVFS-LOAD          ( destination store -- status )
\    PHEADVFS-LOAD-VALIDATED
\      ( destination rejected validator-xt validator-data store -- status )
\    PHEADVFS-REINITIALIZE  ( head recovery-store -- status )
\    PHEADVFS-READONLY? / PHEADVFS-RECOVERY? / PHEADVFS-FALLBACK?
\
\  PHEADVFS-REINITIALIZE is deliberately available only after LOAD has
\  entered recovery.  It replaces both generations with a caller-supplied
\  valid, writable head; it does not silently bless recovered data.
\ =====================================================================

PROVIDED akashic-runtime-vfs-practice-head

REQUIRE practice-head.f
REQUIRE ../math/crc.f
REQUIRE ../utils/fs/vfs.f
REQUIRE ../utils/generation-pair.f

0 CONSTANT PHEADVFS-S-OK
1 CONSTANT PHEADVFS-S-INVALID
2 CONSTANT PHEADVFS-S-CHECKSUM
3 CONSTANT PHEADVFS-S-IO
4 CONSTANT PHEADVFS-S-NOT-FOUND
5 CONSTANT PHEADVFS-S-NOMEM
6 CONSTANT PHEADVFS-S-READONLY
7 CONSTANT PHEADVFS-S-RECOVERY

1 CONSTANT PHEADVFS-F-READONLY
2 CONSTANT PHEADVFS-F-RECOVERY
4 CONSTANT PHEADVFS-F-FALLBACK

1  CONSTANT PHEADVFS-FORMAT-V1
64 CONSTANT PHEADVFS-HEADER-SIZE
PHEADVFS-HEADER-SIZE PHEAD-SIZE + CONSTANT PHEADVFS-SNAPSHOT-SIZE

CREATE _PHEADVFS-MAGIC
65 C, 75 C, 80 C, 72 C, 83 C, 48 C, 48 C, 49 C,  \ "AKPHS001"

 0 CONSTANT _PHSV-H-MAGIC
 8 CONSTANT _PHSV-H-FORMAT
16 CONSTANT _PHSV-H-HEADER-SIZE
24 CONSTANT _PHSV-H-GENERATION
32 CONSTANT _PHSV-H-PAYLOAD-SIZE
40 CONSTANT _PHSV-H-CRC32
48 CONSTANT _PHSV-H-FLAGS
56 CONSTANT _PHSV-H-RESERVED

0   CONSTANT _PHSV-VFS
8   CONSTANT _PHSV-FLAGS
16  CONSTANT _PHSV-REJECTED-GENERATION
24  CONSTANT _PHSV-REJECTED-STATUS
32  CONSTANT _PHSV-PAIR
_PHSV-PAIR GPAIR-SIZE + CONSTANT _PHSV-CANDIDATE-A
_PHSV-CANDIDATE-A GPAIR-CANDIDATE-SIZE +
    CONSTANT _PHSV-CANDIDATE-B
_PHSV-CANDIDATE-B GPAIR-CANDIDATE-SIZE + CONSTANT PHEADVFS-SIZE

: PHEADVFS.VFS          ( store -- a ) _PHSV-VFS + ;
: PHEADVFS.FLAGS        ( store -- a ) _PHSV-FLAGS + ;
: PHEADVFS.REJECTED-GENERATION  ( store -- a )
    _PHSV-REJECTED-GENERATION + ;
: PHEADVFS.REJECTED-STATUS  ( store -- a ) _PHSV-REJECTED-STATUS + ;

: _PHEADVFS.PAIR  ( store -- pair ) _PHSV-PAIR + ;
: _PHEADVFS.CANDIDATE-A  ( store -- candidate ) _PHSV-CANDIDATE-A + ;
: _PHEADVFS.CANDIDATE-B  ( store -- candidate ) _PHSV-CANDIDATE-B + ;

\ Keep the established typed-store accessors while mapping them directly to
\ the neutral pair state rather than retaining duplicate authority cells.
: PHEADVFS.GENERATION  ( store -- a )
    _PHEADVFS.PAIR GPAIR.GENERATION ;

: PHEADVFS.ACTIVE-SLOT  ( store -- a )
    _PHEADVFS.PAIR GPAIR.ACTIVE-SLOT ;

: PHEADVFS-READONLY?  ( store -- flag )
    PHEADVFS.FLAGS @ PHEADVFS-F-READONLY AND 0<> ;

: PHEADVFS-RECOVERY?  ( store -- flag )
    PHEADVFS.FLAGS @ PHEADVFS-F-RECOVERY AND 0<> ;

: PHEADVFS-FALLBACK?  ( store -- flag )
    PHEADVFS.FLAGS @ PHEADVFS-F-FALLBACK AND 0<> ;

: _PHEADVFS-PATH-A  ( -- address length )
    S" /practice-head-a.bin" ;

: _PHEADVFS-PATH-B  ( -- address length )
    S" /practice-head-b.bin" ;

VARIABLE _PHEADVFS-EQUAL-A
VARIABLE _PHEADVFS-EQUAL-B

: _PHEADVFS-EQUAL-HEADS!  ( head-a head-b -- )
    _PHEADVFS-EQUAL-B ! _PHEADVFS-EQUAL-A ! ;

: _PHEADVFS-EQUAL-CLEAR  ( -- )
    0 _PHEADVFS-EQUAL-A ! 0 _PHEADVFS-EQUAL-B ! ;

: _PHEADVFS-EQUAL  ( candidate-a candidate-b store -- equal? detail )
    \ Candidate values are stable descriptor identities.  Decoded heads are
    \ transient consumer buffers supplied around the selection operation.
    DROP 2DROP
    _PHEADVFS-EQUAL-A @ PHEAD-SIZE
    _PHEADVFS-EQUAL-B @ PHEAD-SIZE COMPARE 0= PHEADVFS-S-OK ;

: _PHEADVFS-CANDIDATE!  ( head generation status candidate -- status )
    >R
    DUP PHEADVFS-S-OK = IF
        DROP NIP R@ SWAP 0 R> GPAIR-CANDIDATE-VALUE! EXIT
    THEN
    DUP PHEADVFS-S-NOT-FOUND = IF
        >R 2DROP R> R> GPAIR-CANDIDATE-ABSENT! EXIT
    THEN
    >R 2DROP R> R> GPAIR-CANDIDATE-CORRUPT! ;

VARIABLE _PHE-GENERATION
VARIABLE _PHE-HEAD
VARIABLE _PHE-BUFFER
VARIABLE _PHE-CAPACITY

: _PHEADVFS-CHECKSUM  ( buffer -- crc32 )
    CRC32-BEGIN
    DUP _PHSV-H-CRC32 CRC32-ADD
    DUP _PHSV-H-CRC32 + 8 +
    PHEADVFS-SNAPSHOT-SIZE _PHSV-H-CRC32 - 8 - CRC32-ADD
    DROP
    CRC32-END ;

: _PHEADVFS-ENCODE  ( generation head buffer capacity -- length status )
    _PHE-CAPACITY ! _PHE-BUFFER ! _PHE-HEAD ! _PHE-GENERATION !
    _PHE-GENERATION @ 0> 0=
    _PHE-HEAD @ 0= OR
    _PHE-BUFFER @ 0= OR IF
        0 PHEADVFS-S-INVALID EXIT
    THEN
    _PHE-CAPACITY @ PHEADVFS-SNAPSHOT-SIZE < IF
        0 PHEADVFS-S-INVALID EXIT
    THEN
    _PHE-HEAD @ PHEAD-VALID? 0= IF
        0 PHEADVFS-S-INVALID EXIT
    THEN
    \ PHEAD V1 is an exact fixed payload; a future larger record needs a
    \ new envelope codec rather than leaking bytes past this boundary.
    _PHE-HEAD @ PHEAD.SIZE @ PHEAD-SIZE <> IF
        0 PHEADVFS-S-INVALID EXIT
    THEN
    _PHE-BUFFER @ PHEADVFS-SNAPSHOT-SIZE 0 FILL
    _PHEADVFS-MAGIC _PHE-BUFFER @ _PHSV-H-MAGIC + 8 CMOVE
    PHEADVFS-FORMAT-V1 _PHE-BUFFER @ _PHSV-H-FORMAT + !
    PHEADVFS-HEADER-SIZE _PHE-BUFFER @ _PHSV-H-HEADER-SIZE + !
    _PHE-GENERATION @ _PHE-BUFFER @ _PHSV-H-GENERATION + !
    PHEAD-SIZE _PHE-BUFFER @ _PHSV-H-PAYLOAD-SIZE + !
    _PHE-HEAD @ _PHE-BUFFER @ PHEADVFS-HEADER-SIZE + PHEAD-COPY
    _PHE-BUFFER @ _PHEADVFS-CHECKSUM
    _PHE-BUFFER @ _PHSV-H-CRC32 + !
    PHEADVFS-SNAPSHOT-SIZE PHEADVFS-S-OK ;

VARIABLE _PHD-BUFFER
VARIABLE _PHD-LENGTH
VARIABLE _PHD-DESTINATION
VARIABLE _PHD-PAYLOAD

: _PHEADVFS-DECODE  ( buffer length destination -- generation status )
    _PHD-DESTINATION ! _PHD-LENGTH ! _PHD-BUFFER !
    _PHD-BUFFER @ 0= _PHD-DESTINATION @ 0= OR IF
        0 PHEADVFS-S-INVALID EXIT
    THEN
    _PHD-LENGTH @ PHEADVFS-SNAPSHOT-SIZE <> IF
        0 PHEADVFS-S-INVALID EXIT
    THEN
    _PHD-BUFFER @ _PHSV-H-MAGIC + 8 _PHEADVFS-MAGIC 8 COMPARE 0<> IF
        0 PHEADVFS-S-INVALID EXIT
    THEN
    _PHD-BUFFER @ _PHSV-H-FORMAT + @ PHEADVFS-FORMAT-V1 <>
    _PHD-BUFFER @ _PHSV-H-HEADER-SIZE + @ PHEADVFS-HEADER-SIZE <> OR
    _PHD-BUFFER @ _PHSV-H-PAYLOAD-SIZE + @ PHEAD-SIZE <> OR
    _PHD-BUFFER @ _PHSV-H-GENERATION + @ 0> 0= OR
    _PHD-BUFFER @ _PHSV-H-FLAGS + @ 0<> OR
    _PHD-BUFFER @ _PHSV-H-RESERVED + @ 0<> OR IF
        0 PHEADVFS-S-INVALID EXIT
    THEN
    _PHD-BUFFER @ PHEADVFS-HEADER-SIZE + _PHD-PAYLOAD !
    _PHD-BUFFER @ _PHEADVFS-CHECKSUM
    _PHD-BUFFER @ _PHSV-H-CRC32 + @ <> IF
        0 PHEADVFS-S-CHECKSUM EXIT
    THEN
    _PHD-PAYLOAD @ PHEAD-VALID? 0= IF
        0 PHEADVFS-S-INVALID EXIT
    THEN
    _PHD-PAYLOAD @ PHEAD.SIZE @ PHEAD-SIZE <> IF
        0 PHEADVFS-S-INVALID EXIT
    THEN
    _PHD-PAYLOAD @ _PHD-DESTINATION @ PHEAD-COPY
    _PHD-BUFFER @ _PHSV-H-GENERATION + @ PHEADVFS-S-OK ;

VARIABLE _PHR-PATH-A
VARIABLE _PHR-PATH-U
VARIABLE _PHR-STORE
VARIABLE _PHR-OLD-VFS
VARIABLE _PHR-FD
VARIABLE _PHR-BUFFER
VARIABLE _PHR-HEAD
VARIABLE _PHR-ACTUAL
VARIABLE _PHR-GENERATION
VARIABLE _PHR-STATUS

: _PHEADVFS-READ-SLOT  ( path-a path-u store -- head generation status )
    _PHR-STORE ! _PHR-PATH-U ! _PHR-PATH-A !
    0 _PHR-FD ! 0 _PHR-BUFFER ! 0 _PHR-HEAD !
    VFS-CUR _PHR-OLD-VFS !
    _PHR-STORE @ PHEADVFS.VFS @ VFS-USE
    _PHR-PATH-A @ _PHR-PATH-U @ VFS-OPEN _PHR-FD !
    _PHR-OLD-VFS @ VFS-USE
    _PHR-FD @ 0= IF
        0 0 PHEADVFS-S-NOT-FOUND EXIT
    THEN
    _PHR-FD @ VFS-SIZE PHEADVFS-SNAPSHOT-SIZE <> IF
        _PHR-FD @ VFS-CLOSE
        0 0 PHEADVFS-S-INVALID EXIT
    THEN
    PHEADVFS-SNAPSHOT-SIZE ALLOCATE DUP IF
        2DROP _PHR-FD @ VFS-CLOSE
        0 0 PHEADVFS-S-NOMEM EXIT
    THEN
    DROP _PHR-BUFFER !
    _PHR-BUFFER @ PHEADVFS-SNAPSHOT-SIZE _PHR-FD @ VFS-READ
    _PHR-ACTUAL !
    _PHR-FD @ VFS-CLOSE
    _PHR-ACTUAL @ PHEADVFS-SNAPSHOT-SIZE <> IF
        _PHR-BUFFER @ FREE
        0 0 PHEADVFS-S-IO EXIT
    THEN
    PHEAD-SIZE ALLOCATE DUP IF
        2DROP _PHR-BUFFER @ FREE
        0 0 PHEADVFS-S-NOMEM EXIT
    THEN
    DROP _PHR-HEAD !
    _PHR-BUFFER @ PHEADVFS-SNAPSHOT-SIZE _PHR-HEAD @
    _PHEADVFS-DECODE _PHR-STATUS ! _PHR-GENERATION !
    _PHR-BUFFER @ FREE
    _PHR-STATUS @ PHEADVFS-S-OK <> IF
        _PHR-HEAD @ FREE
        0 0 _PHR-STATUS @ EXIT
    THEN
    _PHR-HEAD @ _PHR-GENERATION @ PHEADVFS-S-OK ;

VARIABLE _PHL-DESTINATION
VARIABLE _PHL-STORE
VARIABLE _PHL-A-HEAD
VARIABLE _PHL-A-GENERATION
VARIABLE _PHL-A-STATUS
VARIABLE _PHL-B-HEAD
VARIABLE _PHL-B-GENERATION
VARIABLE _PHL-B-STATUS
VARIABLE _PHL-RESULT

: _PHEADVFS-LOAD-FREE  ( -- )
    _PHEADVFS-EQUAL-CLEAR
    _PHL-A-HEAD @ ?DUP IF FREE THEN
    _PHL-B-HEAD @ ?DUP IF FREE THEN
    0 _PHL-A-HEAD ! 0 _PHL-B-HEAD ! ;

: _PHEADVFS-RECOVERY!  ( destination store -- status )
    >R
    DUP PHEAD-INIT
    PHEAD-F-READONLY PHEAD-F-RECOVERY OR OVER PHEAD.FLAGS !
    DROP
    PHEADVFS-F-READONLY PHEADVFS-F-RECOVERY OR R> PHEADVFS.FLAGS !
    PHEADVFS-S-RECOVERY ;

: _PHEADVFS-LOAD-RECOVERY  ( -- status )
    _PHEADVFS-LOAD-FREE
    _PHL-DESTINATION @ _PHL-STORE @ _PHEADVFS-RECOVERY! ;

: PHEADVFS-LOAD  ( destination store -- status )
    OVER 0= OVER 0= OR IF 2DROP PHEADVFS-S-INVALID EXIT THEN
    DUP PHEADVFS.VFS @ 0= IF 2DROP PHEADVFS-S-INVALID EXIT THEN
    _PHL-STORE ! _PHL-DESTINATION !
    _PHL-STORE @ _PHEADVFS.PAIR GPAIR-RESET
        GPAIR-S-OK <> IF PHEADVFS-S-INVALID EXIT THEN
    0 _PHL-STORE @ PHEADVFS.FLAGS !
    0 _PHL-STORE @ PHEADVFS.REJECTED-GENERATION !
    0 _PHL-STORE @ PHEADVFS.REJECTED-STATUS !
    _PHEADVFS-PATH-A _PHL-STORE @ _PHEADVFS-READ-SLOT
    _PHL-A-STATUS ! _PHL-A-GENERATION ! _PHL-A-HEAD !
    _PHEADVFS-PATH-B _PHL-STORE @ _PHEADVFS-READ-SLOT
    _PHL-B-STATUS ! _PHL-B-GENERATION ! _PHL-B-HEAD !

    _PHL-A-HEAD @ _PHL-A-GENERATION @ _PHL-A-STATUS @
        _PHL-STORE @ _PHEADVFS.CANDIDATE-A _PHEADVFS-CANDIDATE!
        GPAIR-S-OK <> IF _PHEADVFS-LOAD-RECOVERY EXIT THEN
    _PHL-B-HEAD @ _PHL-B-GENERATION @ _PHL-B-STATUS @
        _PHL-STORE @ _PHEADVFS.CANDIDATE-B _PHEADVFS-CANDIDATE!
        GPAIR-S-OK <> IF _PHEADVFS-LOAD-RECOVERY EXIT THEN
    _PHL-A-HEAD @ _PHL-B-HEAD @ _PHEADVFS-EQUAL-HEADS!
    _PHL-STORE @ _PHEADVFS.CANDIDATE-A
    _PHL-STORE @ _PHEADVFS.CANDIDATE-B
    _PHL-STORE @ _PHEADVFS.PAIR GPAIR-SELECT
    _PHEADVFS-EQUAL-CLEAR
    DUP GPAIR-S-OK <> IF
        2DROP _PHEADVFS-LOAD-RECOVERY EXIT
    THEN
    DROP _PHL-RESULT !
    _PHL-RESULT @ GPAIR-R-FALLBACK =
    _PHL-RESULT @ GPAIR-R-NEWEST = OR
    _PHL-RESULT @ GPAIR-R-EQUAL = OR IF
        _PHL-STORE @ _PHEADVFS.PAIR GPAIR-SELECTED@
        _PHL-STORE @ _PHEADVFS.CANDIDATE-A = IF
            _PHL-A-HEAD @
        ELSE
            _PHL-B-HEAD @
        THEN
        _PHL-DESTINATION @ PHEAD-COPY
        _PHL-RESULT @ GPAIR-R-FALLBACK = IF
            PHEADVFS-F-FALLBACK _PHL-STORE @ PHEADVFS.FLAGS !
        THEN
        _PHEADVFS-LOAD-FREE PHEADVFS-S-OK EXIT
    THEN
    _PHL-RESULT @ GPAIR-R-AMBIGUOUS = IF
        \ Split-brain generation is evidence, never publication authority.
        _PHL-A-GENERATION @
            _PHL-STORE @ PHEADVFS.REJECTED-GENERATION !
        PHEADVFS-S-INVALID _PHL-STORE @ PHEADVFS.REJECTED-STATUS !
    THEN
    _PHEADVFS-LOAD-RECOVERY ;

\ =====================================================================
\  Semantic validation and last-known-good selection
\ =====================================================================
\  The ordinary loader above remains the structural/CRC entry point.
\  This variant also lets an activation layer reject a structurally valid
\  newest head (for example, for a missing manifest or incompatible schema)
\  and try the older valid generation.  The rejected newest head is copied
\  into caller-owned storage before any fallback or recovery decision.
\
\  validator-xt has stack effect ( head validator-data -- status ); zero
\  accepts.  The callback must treat HEAD as borrowed and must not mutate it.
\  A callback THROW fails closed as PHEADVFS-S-INVALID.

VARIABLE _PHV-DESTINATION
VARIABLE _PHV-REJECTED
VARIABLE _PHV-VALIDATOR
VARIABLE _PHV-DATA
VARIABLE _PHV-STORE
VARIABLE _PHV-A-HEAD
VARIABLE _PHV-A-GENERATION
VARIABLE _PHV-A-STATUS
VARIABLE _PHV-B-HEAD
VARIABLE _PHV-B-GENERATION
VARIABLE _PHV-B-STATUS
VARIABLE _PHV-NEWEST
VARIABLE _PHV-NEWEST-GENERATION
VARIABLE _PHV-NEWEST-SLOT
VARIABLE _PHV-OLDER
VARIABLE _PHV-OLDER-GENERATION
VARIABLE _PHV-OLDER-SLOT
VARIABLE _PHV-SINGLE
VARIABLE _PHV-CHECK-HEAD
VARIABLE _PHV-CHECK-STATUS

: _PHEADVFS-VALIDATOR-CALL  ( -- )
    _PHV-CHECK-HEAD @ _PHV-DATA @ _PHV-VALIDATOR @ EXECUTE
    _PHV-CHECK-STATUS ! ;

: _PHEADVFS-VALIDATE-CANDIDATE  ( head -- status )
    DUP 0= IF DROP PHEADVFS-S-INVALID EXIT THEN
    _PHV-CHECK-HEAD !
    PHEADVFS-S-INVALID _PHV-CHECK-STATUS !
    ['] _PHEADVFS-VALIDATOR-CALL CATCH ?DUP IF
        DROP PHEADVFS-S-INVALID
    ELSE
        _PHV-CHECK-STATUS @
    THEN ;

: _PHEADVFS-VALIDATED-FREE  ( -- )
    _PHEADVFS-EQUAL-CLEAR
    _PHV-A-HEAD @ ?DUP IF FREE THEN
    _PHV-B-HEAD @ ?DUP IF FREE THEN
    0 _PHV-A-HEAD ! 0 _PHV-B-HEAD ! ;

: _PHEADVFS-REJECT-COPY  ( head generation status -- )
    _PHV-STORE @ PHEADVFS.REJECTED-STATUS !
    DUP _PHV-STORE @ PHEADVFS.REJECTED-GENERATION !
    DROP
    _PHV-REJECTED @ ?DUP IF PHEAD-COPY ELSE DROP THEN ;

: _PHEADVFS-VALIDATED-RECOVERY  ( -- status )
    _PHEADVFS-VALIDATED-FREE
    _PHV-STORE @ _PHEADVFS.PAIR GPAIR-RESET DROP
    _PHV-DESTINATION @ _PHV-STORE @ _PHEADVFS-RECOVERY! ;

: _PHEADVFS-VALIDATED-ACCEPT  ( head flags -- status )
    _PHV-STORE @ PHEADVFS.FLAGS !
    _PHV-DESTINATION @ PHEAD-COPY
    _PHEADVFS-VALIDATED-FREE
    PHEADVFS-S-OK ;

: _PHEADVFS-CANDIDATE-FOR-SLOT  ( slot store -- candidate )
    SWAP GPAIR-SLOT-A = IF
        _PHEADVFS.CANDIDATE-A
    ELSE
        _PHEADVFS.CANDIDATE-B
    THEN ;

: _PHEADVFS-PUBLISH-OLDER  ( -- flag )
    \ Semantic rejection changes the candidate classification, then the
    \ neutral pair performs the authoritative fallback publication itself.
    _PHV-STORE @ PHEADVFS.REJECTED-STATUS @
    _PHV-NEWEST-SLOT @ _PHV-STORE @ _PHEADVFS-CANDIDATE-FOR-SLOT
        GPAIR-CANDIDATE-CORRUPT! GPAIR-S-OK <> IF 0 EXIT THEN
    _PHV-STORE @ _PHEADVFS.CANDIDATE-A
    _PHV-STORE @ _PHEADVFS.CANDIDATE-B
    _PHV-STORE @ _PHEADVFS.PAIR GPAIR-SELECT
    DUP GPAIR-S-OK <> IF 2DROP 0 EXIT THEN
    DROP GPAIR-R-FALLBACK <> IF 0 EXIT THEN
    _PHV-STORE @ _PHEADVFS.PAIR GPAIR-SELECTED@
    _PHV-OLDER-SLOT @ _PHV-STORE @ _PHEADVFS-CANDIDATE-FOR-SLOT =
    _PHV-STORE @ _PHEADVFS.PAIR GPAIR-GENERATION@
        _PHV-OLDER-GENERATION @ = AND
    _PHV-STORE @ _PHEADVFS.PAIR GPAIR-ACTIVE-SLOT@
        _PHV-OLDER-SLOT @ = AND ;

: _PHEADVFS-ORDER-CANDIDATES  ( -- )
    0 _PHV-NEWEST ! 0 _PHV-OLDER ! 0 _PHV-SINGLE !
    _PHV-STORE @ _PHEADVFS.PAIR GPAIR-RESULT@
    DUP GPAIR-R-FALLBACK = IF
        DROP
        _PHV-STORE @ _PHEADVFS.PAIR GPAIR-SELECTED@
        _PHV-STORE @ _PHEADVFS.CANDIDATE-A = IF
            _PHV-A-HEAD @ _PHV-NEWEST !
            _PHV-A-GENERATION @ _PHV-NEWEST-GENERATION !
            GPAIR-SLOT-A _PHV-NEWEST-SLOT !
        ELSE
            _PHV-B-HEAD @ _PHV-NEWEST !
            _PHV-B-GENERATION @ _PHV-NEWEST-GENERATION !
            GPAIR-SLOT-B _PHV-NEWEST-SLOT !
        THEN
        -1 _PHV-SINGLE !
        EXIT
    THEN
    DUP GPAIR-R-NEWEST = IF
        DROP
        _PHV-STORE @ PHEADVFS.ACTIVE-SLOT @ GPAIR-SLOT-B = IF
            _PHV-B-HEAD @ _PHV-NEWEST !
            _PHV-B-GENERATION @ _PHV-NEWEST-GENERATION !
            GPAIR-SLOT-B _PHV-NEWEST-SLOT !
            _PHV-A-HEAD @ _PHV-OLDER !
            _PHV-A-GENERATION @ _PHV-OLDER-GENERATION !
            GPAIR-SLOT-A _PHV-OLDER-SLOT !
        ELSE
            _PHV-A-HEAD @ _PHV-NEWEST !
            _PHV-A-GENERATION @ _PHV-NEWEST-GENERATION !
            GPAIR-SLOT-A _PHV-NEWEST-SLOT !
            _PHV-B-HEAD @ _PHV-OLDER !
            _PHV-B-GENERATION @ _PHV-OLDER-GENERATION !
            GPAIR-SLOT-B _PHV-OLDER-SLOT !
        THEN
        EXIT
    THEN
    GPAIR-R-EQUAL = IF
        _PHV-A-HEAD @ _PHV-NEWEST !
        _PHV-A-GENERATION @ _PHV-NEWEST-GENERATION !
        GPAIR-SLOT-A _PHV-NEWEST-SLOT !
        _PHV-B-HEAD @ _PHV-OLDER !
        _PHV-B-GENERATION @ _PHV-OLDER-GENERATION !
        GPAIR-SLOT-B _PHV-OLDER-SLOT !
    THEN ;

: PHEADVFS-LOAD-VALIDATED
  ( destination rejected validator-xt validator-data store -- status )
    _PHV-STORE ! _PHV-DATA ! _PHV-VALIDATOR !
    _PHV-REJECTED ! _PHV-DESTINATION !
    _PHV-DESTINATION @ 0= _PHV-REJECTED @ 0= OR
    _PHV-VALIDATOR @ 0= OR _PHV-STORE @ 0= OR IF
        PHEADVFS-S-INVALID EXIT
    THEN
    _PHV-STORE @ PHEADVFS.VFS @ 0= IF PHEADVFS-S-INVALID EXIT THEN
    _PHV-REJECTED @ PHEAD-SIZE 0 FILL
    _PHV-STORE @ _PHEADVFS.PAIR GPAIR-RESET
        GPAIR-S-OK <> IF PHEADVFS-S-INVALID EXIT THEN
    0 _PHV-STORE @ PHEADVFS.FLAGS !
    0 _PHV-STORE @ PHEADVFS.REJECTED-GENERATION !
    0 _PHV-STORE @ PHEADVFS.REJECTED-STATUS !
    _PHEADVFS-PATH-A _PHV-STORE @ _PHEADVFS-READ-SLOT
    _PHV-A-STATUS ! _PHV-A-GENERATION ! _PHV-A-HEAD !
    _PHEADVFS-PATH-B _PHV-STORE @ _PHEADVFS-READ-SLOT
    _PHV-B-STATUS ! _PHV-B-GENERATION ! _PHV-B-HEAD !

    _PHV-A-HEAD @ _PHV-A-GENERATION @ _PHV-A-STATUS @
        _PHV-STORE @ _PHEADVFS.CANDIDATE-A _PHEADVFS-CANDIDATE!
        GPAIR-S-OK <> IF _PHEADVFS-VALIDATED-RECOVERY EXIT THEN
    _PHV-B-HEAD @ _PHV-B-GENERATION @ _PHV-B-STATUS @
        _PHV-STORE @ _PHEADVFS.CANDIDATE-B _PHEADVFS-CANDIDATE!
        GPAIR-S-OK <> IF _PHEADVFS-VALIDATED-RECOVERY EXIT THEN
    _PHV-A-HEAD @ _PHV-B-HEAD @ _PHEADVFS-EQUAL-HEADS!
    _PHV-STORE @ _PHEADVFS.CANDIDATE-A
    _PHV-STORE @ _PHEADVFS.CANDIDATE-B
    _PHV-STORE @ _PHEADVFS.PAIR GPAIR-SELECT
    _PHEADVFS-EQUAL-CLEAR
    DUP GPAIR-S-OK <> IF
        2DROP _PHEADVFS-VALIDATED-RECOVERY EXIT
    THEN
    DROP
    GPAIR-R-AMBIGUOUS = IF
        _PHV-A-HEAD @ _PHV-A-GENERATION @ PHEADVFS-S-INVALID
            _PHEADVFS-REJECT-COPY
        _PHEADVFS-VALIDATED-RECOVERY EXIT
    THEN

    _PHEADVFS-ORDER-CANDIDATES
    _PHV-NEWEST @ 0= IF _PHEADVFS-VALIDATED-RECOVERY EXIT THEN

    _PHV-NEWEST @ _PHEADVFS-VALIDATE-CANDIDATE DUP 0= IF
        DROP _PHV-NEWEST @
        _PHV-SINGLE @ IF PHEADVFS-F-FALLBACK ELSE 0 THEN
        _PHEADVFS-VALIDATED-ACCEPT EXIT
    THEN
    _PHV-NEWEST @ _PHV-NEWEST-GENERATION @ ROT
        _PHEADVFS-REJECT-COPY

    _PHV-OLDER @ ?DUP IF
        DUP _PHEADVFS-VALIDATE-CANDIDATE 0= IF
            DROP
            _PHEADVFS-PUBLISH-OLDER 0= IF
                _PHEADVFS-VALIDATED-RECOVERY EXIT
            THEN
            _PHV-OLDER @ PHEADVFS-F-FALLBACK
                _PHEADVFS-VALIDATED-ACCEPT EXIT
        THEN
        DROP
    THEN
    _PHEADVFS-VALIDATED-RECOVERY ;

VARIABLE _PHW-HEAD
VARIABLE _PHW-STORE
VARIABLE _PHW-PAIR
VARIABLE _PHW-GENERATION
VARIABLE _PHW-SLOT
VARIABLE _PHW-PATH-A
VARIABLE _PHW-PATH-U
VARIABLE _PHW-BUFFER
VARIABLE _PHW-LENGTH
VARIABLE _PHW-STATUS
VARIABLE _PHW-FD
VARIABLE _PHW-OLD-VFS
VARIABLE _PHW-ACTUAL
VARIABLE _PHW-HAD-ACTIVE
VARIABLE _PHW-PAIR-STATUS
VARIABLE _PHW-OUTCOME

: _PHEADVFS-SELECT-WRITE-PATH  ( slot -- )
    IF _PHEADVFS-PATH-B ELSE _PHEADVFS-PATH-A THEN
    _PHW-PATH-U ! _PHW-PATH-A ! ;

: _PHEADVFS-OPEN-WRITE  ( -- fd | 0 )
    VFS-CUR _PHW-OLD-VFS !
    _PHW-STORE @ PHEADVFS.VFS @ VFS-USE
    _PHW-PATH-A @ _PHW-PATH-U @ VFS-OPEN DUP 0= IF
        DROP
        _PHW-PATH-A @ _PHW-PATH-U @
        _PHW-STORE @ PHEADVFS.VFS @ VFS-CREATE
        DUP 0= IF
            DROP _PHW-OLD-VFS @ VFS-USE 0 EXIT
        THEN
        DROP _PHW-PATH-A @ _PHW-PATH-U @ VFS-OPEN
    THEN
    _PHW-OLD-VFS @ VFS-USE ;

: _PHEADVFS-SAVE-CALLBACK
  ( head slot generation pair store -- detail )
    _PHW-STORE ! _PHW-PAIR ! _PHW-GENERATION !
    _PHW-SLOT ! _PHW-HEAD !
    _PHW-SLOT @ _PHEADVFS-SELECT-WRITE-PATH
    PHEADVFS-SNAPSHOT-SIZE ALLOCATE DUP IF
        2DROP PHEADVFS-S-NOMEM EXIT
    THEN
    DROP _PHW-BUFFER !
    _PHW-GENERATION @ _PHW-HEAD @ _PHW-BUFFER @
    PHEADVFS-SNAPSHOT-SIZE _PHEADVFS-ENCODE
    _PHW-STATUS ! _PHW-LENGTH !
    _PHW-STATUS @ PHEADVFS-S-OK <> IF
        _PHW-BUFFER @ FREE _PHW-STATUS @ EXIT
    THEN
    _PHW-PAIR @ GPAIR-SAVE-MAYBE! GPAIR-S-OK <> IF
        _PHW-BUFFER @ FREE PHEADVFS-S-INVALID EXIT
    THEN
    _PHEADVFS-OPEN-WRITE DUP _PHW-FD ! 0= IF
        _PHW-BUFFER @ FREE PHEADVFS-S-IO EXIT
    THEN
    _PHW-FD @ VFS-REWIND
    0 _PHW-FD @ VFS-TRUNCATE IF
        _PHW-FD @ VFS-CLOSE _PHW-BUFFER @ FREE
        PHEADVFS-S-IO EXIT
    THEN
    _PHW-BUFFER @ _PHW-LENGTH @ _PHW-FD @ VFS-WRITE _PHW-ACTUAL !
    _PHW-FD @ VFS-CLOSE
    _PHW-BUFFER @ FREE
    _PHW-ACTUAL @ _PHW-LENGTH @ <> IF PHEADVFS-S-IO EXIT THEN
    _PHW-STORE @ PHEADVFS.VFS @ VFS-SYNC IF PHEADVFS-S-IO EXIT THEN
    _PHW-PAIR @ GPAIR-SAVE-DURABLE! GPAIR-S-OK <> IF
        PHEADVFS-S-INVALID EXIT
    THEN
    PHEADVFS-S-OK ;

: PHEADVFS-INIT  ( vfs store -- status )
    OVER 0= OVER 0= OR IF 2DROP PHEADVFS-S-INVALID EXIT THEN
    DUP PHEADVFS-SIZE 0 FILL
    SWAP OVER PHEADVFS.VFS !
    >R
    ['] _PHEADVFS-EQUAL ['] _PHEADVFS-SAVE-CALLBACK
        R@ R@ _PHEADVFS.PAIR GPAIR-INIT
    R> DROP
    GPAIR-S-OK = IF PHEADVFS-S-OK ELSE PHEADVFS-S-INVALID THEN ;

: PHEADVFS-SAVE  ( head store -- status )
    OVER 0= OVER 0= OR IF 2DROP PHEADVFS-S-INVALID EXIT THEN
    DUP PHEADVFS.VFS @ 0= IF 2DROP PHEADVFS-S-INVALID EXIT THEN
    _PHW-STORE ! _PHW-HEAD !
    _PHW-STORE @ _PHEADVFS.PAIR GPAIR-VALID? 0= IF
        PHEADVFS-S-INVALID EXIT
    THEN
    _PHW-STORE @ PHEADVFS-READONLY? IF PHEADVFS-S-READONLY EXIT THEN
    _PHW-HEAD @ PHEAD-READONLY? IF PHEADVFS-S-READONLY EXIT THEN
    _PHW-HEAD @ PHEAD-VALID? 0= IF PHEADVFS-S-INVALID EXIT THEN
    _PHW-STORE @ PHEADVFS.ACTIVE-SLOT @ 0>= _PHW-HAD-ACTIVE !
    _PHW-HEAD @ _PHW-STORE @ _PHEADVFS.PAIR GPAIR-SAVE
    _PHW-PAIR-STATUS ! _PHW-OUTCOME !
    _PHW-PAIR-STATUS @ GPAIR-S-OK <> IF
        _PHW-PAIR-STATUS @ GPAIR-S-CALLBACK = IF
            \ VFS convenience words historically exposed their exact THROW
            \ through this API.  The neutral pair contains it; do not turn
            \ that pre-existing fault surface into a new Practice status.
            _PHW-STORE @ _PHEADVFS.PAIR GPAIR-CALLBACK-THROW@ THROW
        THEN
        PHEADVFS-S-INVALID EXIT
    THEN
    _PHW-STORE @ _PHEADVFS.PAIR GPAIR-DETAIL@ DUP
    PHEADVFS-S-OK <> IF EXIT THEN DROP
    _PHW-OUTCOME @ GPAIR-W-DURABLE <> IF PHEADVFS-S-IO EXIT THEN
    _PHW-HAD-ACTIVE @ IF
        0 _PHW-STORE @ PHEADVFS.FLAGS !
    ELSE
        PHEADVFS-F-FALLBACK _PHW-STORE @ PHEADVFS.FLAGS !
    THEN
    PHEADVFS-S-OK ;

VARIABLE _PHX-HEAD
VARIABLE _PHX-STORE

: PHEADVFS-REINITIALIZE  ( head store -- status )
    _PHX-STORE ! _PHX-HEAD !
    _PHX-HEAD @ 0= _PHX-STORE @ 0= OR IF
        PHEADVFS-S-INVALID EXIT
    THEN
    _PHX-STORE @ PHEADVFS.VFS @ 0= IF PHEADVFS-S-INVALID EXIT THEN
    _PHX-STORE @ PHEADVFS-RECOVERY? 0= IF PHEADVFS-S-INVALID EXIT THEN
    _PHX-HEAD @ PHEAD-VALID? 0= IF PHEADVFS-S-INVALID EXIT THEN
    _PHX-HEAD @ PHEAD-READONLY? IF PHEADVFS-S-READONLY EXIT THEN
    _PHX-STORE @ _PHEADVFS.PAIR GPAIR-RESET
        GPAIR-S-OK <> IF PHEADVFS-S-INVALID EXIT THEN
    0 _PHX-STORE @ PHEADVFS.FLAGS !
    _PHX-HEAD @ _PHX-STORE @ PHEADVFS-SAVE DUP IF
        PHEADVFS-F-READONLY PHEADVFS-F-RECOVERY OR
        _PHX-STORE @ PHEADVFS.FLAGS !
        EXIT
    THEN
    DROP
    _PHX-HEAD @ _PHX-STORE @ PHEADVFS-SAVE DUP IF
        PHEADVFS-F-READONLY PHEADVFS-F-RECOVERY OR
        _PHX-STORE @ PHEADVFS.FLAGS !
    THEN ;
