\ =====================================================================
\  megapad.f - Owned OpenAI provider environment for physical MegaPad
\ =====================================================================
\  This composition owns the native credential and MegaPad TLS adapter
\  that must outlive an OpenAI Responses provider. It does not provision
\  trust roots, persist credentials, or depend on Desk or any TUI module.
\ =====================================================================

PROVIDED akashic-agent-openai-megapad

REQUIRE ../../provider-source.f
REQUIRE responses.f
REQUIRE ../../auth/api-key.f
REQUIRE ../../../net/transports/megapad-tls.f

0 CONSTANT _OAIMP-SOURCE
_OAIMP-SOURCE AGENT-PROVIDER-SOURCE-SIZE + CONSTANT _OAIMP-CONFIG
_OAIMP-CONFIG OPENAI-CONFIG-SIZE + CONSTANT _OAIMP-CREDENTIAL
_OAIMP-CREDENTIAL CREDENTIAL-SIZE + CONSTANT _OAIMP-AUTH
_OAIMP-AUTH APIKEY-AUTH-SIZE + CONSTANT _OAIMP-TRANSPORT
_OAIMP-TRANSPORT MPTLS-SIZE + CONSTANT OPENAI-MEGAPAD-SOURCE-SIZE

: OPENAI-MEGAPAD-SOURCE-CONFIG  ( source -- config )
    _OAIMP-CONFIG + ;

: OPENAI-MEGAPAD-SOURCE-CREDENTIAL  ( source -- credential )
    _OAIMP-CREDENTIAL + ;

: OPENAI-MEGAPAD-SOURCE-AUTH  ( source -- adapter )
    _OAIMP-AUTH + ;

: OPENAI-MEGAPAD-SOURCE-TRANSPORT  ( source -- adapter )
    _OAIMP-TRANSPORT + ;

VARIABLE _OAIMPC-SOURCE
VARIABLE _OAIMPC-STATUS

: _OPENAI-MEGAPAD-CONFIGURE  ( source -- status )
    DUP _OAIMPC-SOURCE !
    OPENAI-MEGAPAD-SOURCE-CONFIG OAIC-HOST
    _OAIMPC-SOURCE @ OPENAI-MEGAPAD-SOURCE-CONFIG OAIC.PORT @
    _OAIMPC-SOURCE @ OPENAI-MEGAPAD-SOURCE-TRANSPORT MPTLS-CONFIGURE ;

: _OPENAI-MEGAPAD-CREATE  ( source -- provider status )
    DUP _OAIMPC-SOURCE ! _OPENAI-MEGAPAD-CONFIGURE ?DUP IF
        DROP 0 APSOURCE-S-INVALID EXIT
    THEN
    _OAIMPC-SOURCE @ OPENAI-MEGAPAD-SOURCE-CONFIG
    _OAIMPC-SOURCE @ OPENAI-MEGAPAD-SOURCE-AUTH APIKEY-AUTH.PORT
    _OAIMPC-SOURCE @ OPENAI-MEGAPAD-SOURCE-TRANSPORT MPTLS.PORT
    OPENAI-PROVIDER-NEW ;

: OPENAI-MEGAPAD-SOURCE-FREE  ( source -- )
    DUP 0= IF DROP EXIT THEN
    DUP OPENAI-MEGAPAD-SOURCE-TRANSPORT MPTLS.PORT NIO-CLOSE
    DUP OPENAI-MEGAPAD-SOURCE-AUTH APIKEY-AUTH.PORT AAUTH-DESTROY
    DUP OPENAI-MEGAPAD-SOURCE-CREDENTIAL CRED-CLEAR
    DUP OPENAI-MEGAPAD-SOURCE-SIZE 0 FILL
    FREE ;

VARIABLE _OAIMPN-SOURCE

: OPENAI-MEGAPAD-SOURCE-NEW  ( -- source status )
    OPENAI-MEGAPAD-SOURCE-SIZE ALLOCATE
    DUP IF 2DROP 0 APSOURCE-S-NOMEM EXIT THEN
    DROP DUP _OAIMPN-SOURCE ! OPENAI-MEGAPAD-SOURCE-SIZE 0 FILL
    _OAIMPN-SOURCE @ APSOURCE-INIT
    _OAIMPN-SOURCE @ OPENAI-MEGAPAD-SOURCE-CONFIG OAIC-INIT
    _OAIMPN-SOURCE @ OPENAI-MEGAPAD-SOURCE-CREDENTIAL CRED-INIT
    _OAIMPN-SOURCE @ OPENAI-MEGAPAD-SOURCE-CREDENTIAL
    _OAIMPN-SOURCE @ OPENAI-MEGAPAD-SOURCE-AUTH APIKEY-AUTH-INIT
    DROP
    _OAIMPN-SOURCE @ OPENAI-MEGAPAD-SOURCE-TRANSPORT MPTLS-INIT
    _OAIMPN-SOURCE @ _OPENAI-MEGAPAD-CONFIGURE DUP _OAIMPC-STATUS ! IF
        _OAIMPN-SOURCE @ OPENAI-MEGAPAD-SOURCE-FREE
        0 _OAIMPC-STATUS @ EXIT
    THEN
    _OAIMPN-SOURCE @ _OAIMPN-SOURCE @ APSOURCE.CONTEXT !
    S" org.akashic.agent.source.openai.megapad"
    _OAIMPN-SOURCE @ APSOURCE.ID-U ! _OAIMPN-SOURCE @ APSOURCE.ID-A !
    ['] _OPENAI-MEGAPAD-CREATE _OAIMPN-SOURCE @ APSOURCE.NEW-XT !
    ['] OPENAI-MEGAPAD-SOURCE-FREE _OAIMPN-SOURCE @ APSOURCE.FREE-XT !
    _OAIMPN-SOURCE @ APSOURCE-S-OK ;
