\ =====================================================================
\  uidl-field-snapshot.f -- mounted canonical FIELD snapshot
\ =====================================================================
\
\  One coherent UIDL-TUI observation captures mounted FLD widgets into a separate caller-owned native UFLD bank and
\  pointer-free descriptors. Records are canonical by unsigned source index
\  and relation root key. Native field keys remain application-owned.
\
\  Only complete fields whose exact clip equals their full geometry
\  are admitted. Unsupported or partially clipped roots remain CELL-owned;
\  a capacity failure clears every dirtied descriptor/native output byte.
\  Caller banks must be pairwise disjoint and disjoint from module scratch,
\  UIDL authority, and every live semantic widget and backing model.
\
\  UFLSN-CAPTURE ( descriptors-a descriptors-u native-a native-u
\                  -- descriptor-count native-used status )
\  UFLSN-FROZEN-WORK-BYTES ( descriptor-count -- bytes|0 )
\  UFLSN-FROZEN-VALIDATE ( work-a work-u descriptors-a descriptors-u
\                          native-a native-u -- status )
\
\  Frozen validation never consults the live tree. It validates every UFLD,
\  checks complete descriptor geometry and counts, and sorts caller-owned
\  offsets to prove exact native-bank coverage without overlap or gaps.
\  Prefix: UFLSN- (public), _UFLSN- (private).

PROVIDED akashic-tui-uidl-field-snapshot

REQUIRE uidl-tui.f
REQUIRE field-model.f
REQUIRE widgets/field.f
REQUIRE ../utils/memory-span.f

0 CONSTANT UFLSN-S-OK
1 CONSTANT UFLSN-S-CAPACITY
2 CONSTANT UFLSN-S-UNAVAILABLE
3 CONSTANT UFLSN-S-INVALID

: UFLSN-STATUS-VALID?  ( status -- flag )  4 U< ;

\ The native FIELD bank remains separate from collection and graph banks.
1 CONSTANT UFLSN-SOURCE-UIDL

\ Descriptor fields are native cells and contain no pointer.
\
\   +0   source kind
\   +8   UIDL pool source index
\   +16  source generation (positive closed mounted relation)
\   +24  closed mounted relation root key
\   +32  native field offset relative to this document's native bank
\   +40  translated root row
\   +48  translated root column
\   +56  complete root height
\   +64  complete root width
\   +72  clip row
\   +80  clip column
\   +88  clip height
\   +96  clip width
\   +104 resolved UIDL paint z
\   +112 native entry bytes
\   +120 total outer label, TEXT, and choice label UTF-8 bytes

: _UFLSN-D.SOURCE       ( descriptor -- address )       ;
: _UFLSN-D.INDEX        ( descriptor -- address )   8 + ;
: _UFLSN-D.GENERATION   ( descriptor -- address )  16 + ;
: _UFLSN-D.ROOT-KEY     ( descriptor -- address )  24 + ;
: _UFLSN-D.NATIVE-O     ( descriptor -- address )  32 + ;
: _UFLSN-D.ROW          ( descriptor -- address )  40 + ;
: _UFLSN-D.COLUMN       ( descriptor -- address )  48 + ;
: _UFLSN-D.HEIGHT       ( descriptor -- address )  56 + ;
: _UFLSN-D.WIDTH        ( descriptor -- address )  64 + ;
: _UFLSN-D.CLIP-ROW     ( descriptor -- address )  72 + ;
: _UFLSN-D.CLIP-COLUMN  ( descriptor -- address )  80 + ;
: _UFLSN-D.CLIP-HEIGHT  ( descriptor -- address )  88 + ;
: _UFLSN-D.CLIP-WIDTH   ( descriptor -- address )  96 + ;
: _UFLSN-D.Z            ( descriptor -- address ) 104 + ;
: _UFLSN-D.ENTRY-U      ( descriptor -- address ) 112 + ;
: _UFLSN-D.UTF8-U       ( descriptor -- address ) 120 + ;

128 CONSTANT UFLSN-DESCRIPTOR-SIZE

: UFLSN-DESCRIPTOR-BYTES  ( -- bytes )  UFLSN-DESCRIPTOR-SIZE ;
: UFLSN-DESCRIPTOR-SOURCE@  ( descriptor -- value )
    _UFLSN-D.SOURCE @ ;
: UFLSN-DESCRIPTOR-SOURCE-INDEX@  ( descriptor -- value )
    _UFLSN-D.INDEX @ ;
: UFLSN-DESCRIPTOR-SOURCE-GENERATION@  ( descriptor -- value )
    _UFLSN-D.GENERATION @ ;
: UFLSN-DESCRIPTOR-ROOT-KEY@  ( descriptor -- value )
    _UFLSN-D.ROOT-KEY @ ;
: UFLSN-DESCRIPTOR-NATIVE-OFFSET@  ( descriptor -- value )
    _UFLSN-D.NATIVE-O @ ;
: UFLSN-DESCRIPTOR-ROW@  ( descriptor -- value )
    _UFLSN-D.ROW @ ;
: UFLSN-DESCRIPTOR-COLUMN@  ( descriptor -- value )
    _UFLSN-D.COLUMN @ ;
: UFLSN-DESCRIPTOR-HEIGHT@  ( descriptor -- value )
    _UFLSN-D.HEIGHT @ ;
: UFLSN-DESCRIPTOR-WIDTH@  ( descriptor -- value )
    _UFLSN-D.WIDTH @ ;
: UFLSN-DESCRIPTOR-CLIP-ROW@  ( descriptor -- value )
    _UFLSN-D.CLIP-ROW @ ;
: UFLSN-DESCRIPTOR-CLIP-COLUMN@  ( descriptor -- value )
    _UFLSN-D.CLIP-COLUMN @ ;
: UFLSN-DESCRIPTOR-CLIP-HEIGHT@  ( descriptor -- value )
    _UFLSN-D.CLIP-HEIGHT @ ;
: UFLSN-DESCRIPTOR-CLIP-WIDTH@  ( descriptor -- value )
    _UFLSN-D.CLIP-WIDTH @ ;
: UFLSN-DESCRIPTOR-Z@  ( descriptor -- value )
    _UFLSN-D.Z @ ;
: UFLSN-DESCRIPTOR-ENTRY-BYTES@  ( descriptor -- value )
    _UFLSN-D.ENTRY-U @ ;
: UFLSN-DESCRIPTOR-UTF8-BYTES@  ( descriptor -- value )
    _UFLSN-D.UTF8-U @ ;
: UFLSN-DESCRIPTOR-NATIVE  ( descriptor native-base -- field bytes )
    OVER UFLSN-DESCRIPTOR-NATIVE-OFFSET@ +
    SWAP UFLSN-DESCRIPTOR-ENTRY-BYTES@ ;

-1 1 RSHIFT CONSTANT _UFLSN-SIGNED-MAX

: _UFLSN-SIZED-BYTES  ( count stride -- bytes|0 )
    OVER 0< IF 2DROP 0 EXIT THEN
    OVER 0= IF 2DROP 0 EXIT THEN
    _UFLSN-SIGNED-MAX OVER / 2 PICK U< IF 2DROP 0 EXIT THEN
    * ;

: UFLSN-DESCRIPTOR-BANK-BYTES  ( descriptor-capacity -- bytes|0 )
    UFLSN-DESCRIPTOR-SIZE _UFLSN-SIZED-BYTES ;

8 CONSTANT UFLSN-FROZEN-WORK-ENTRY-SIZE

: UFLSN-FROZEN-WORK-BYTES  ( descriptor-count -- bytes|0 )
    DUP 0< IF DROP 0 EXIT THEN
    DUP 0= IF DROP 0 EXIT THEN
    UFLSN-FROZEN-WORK-ENTRY-SIZE _UFLSN-SIZED-BYTES ;

CREATE _UFLSN-OWNED-START

VARIABLE _UFLSN-DESCRIPTORS-A
VARIABLE _UFLSN-DESCRIPTORS-U
VARIABLE _UFLSN-DESCRIPTOR-CAP
VARIABLE _UFLSN-NATIVE-A
VARIABLE _UFLSN-NATIVE-U
VARIABLE _UFLSN-RANGES-VALID

VARIABLE _UFLSN-STATUS
VARIABLE _UFLSN-COUNT
VARIABLE _UFLSN-NATIVE-USED
VARIABLE _UFLSN-DIRTY-DESCRIPTOR-U
VARIABLE _UFLSN-DIRTY-NATIVE-U

VARIABLE _UFLSN-V-INDEX
VARIABLE _UFLSN-V-GENERATION
VARIABLE _UFLSN-V-ROOT-KEY
VARIABLE _UFLSN-V-RESOLVED-A
VARIABLE _UFLSN-V-RESOLVED-U
VARIABLE _UFLSN-V-DESCRIPTOR
VARIABLE _UFLSN-V-ENTRY
VARIABLE _UFLSN-V-ENTRY-U
VARIABLE _UFLSN-V-NEXT-NATIVE
VARIABLE _UFLSN-V-REMAINING
VARIABLE _UFLSN-V-ORIGIN-ROW
VARIABLE _UFLSN-V-ORIGIN-COLUMN
VARIABLE _UFLSN-V-EXTENT-HEIGHT
VARIABLE _UFLSN-V-EXTENT-WIDTH
VARIABLE _UFLSN-V-ROW
VARIABLE _UFLSN-V-COLUMN
VARIABLE _UFLSN-V-HEIGHT
VARIABLE _UFLSN-V-WIDTH
VARIABLE _UFLSN-V-CLIP-ROW
VARIABLE _UFLSN-V-CLIP-COLUMN
VARIABLE _UFLSN-V-CLIP-HEIGHT
VARIABLE _UFLSN-V-CLIP-WIDTH
VARIABLE _UFLSN-V-Z

VARIABLE _UFLSN-PRIOR-INDEX
VARIABLE _UFLSN-PRIOR-GENERATION
VARIABLE _UFLSN-PRIOR-ROOT
VARIABLE _UFLSN-HAVE-PRIOR
VARIABLE _UFLSN-OWNED-LIMIT

VARIABLE _UFLSN-F-WORK-A
VARIABLE _UFLSN-F-WORK-U
VARIABLE _UFLSN-F-WORK-NEED
VARIABLE _UFLSN-F-DESCRIPTORS-A
VARIABLE _UFLSN-F-DESCRIPTORS-U
VARIABLE _UFLSN-F-NATIVE-A
VARIABLE _UFLSN-F-NATIVE-U
VARIABLE _UFLSN-F-COUNT
VARIABLE _UFLSN-F-I
VARIABLE _UFLSN-F-J
VARIABLE _UFLSN-F-VALUE
VARIABLE _UFLSN-F-HEAP-ROOT
VARIABLE _UFLSN-F-HEAP-END
VARIABLE _UFLSN-F-HEAP-CHILD
VARIABLE _UFLSN-F-HEAP-LARGEST
VARIABLE _UFLSN-F-HEAP-A
VARIABLE _UFLSN-F-HEAP-B
VARIABLE _UFLSN-F-DESCRIPTOR
VARIABLE _UFLSN-F-FIELD
VARIABLE _UFLSN-F-FIELD-U
VARIABLE _UFLSN-F-OFFSET
VARIABLE _UFLSN-F-CURSOR
VARIABLE _UFLSN-F-INDEX
VARIABLE _UFLSN-F-GENERATION
VARIABLE _UFLSN-F-RELATION
VARIABLE _UFLSN-F-PRIOR-INDEX
VARIABLE _UFLSN-F-PRIOR-GENERATION
VARIABLE _UFLSN-F-PRIOR-RELATION
VARIABLE _UFLSN-F-HAVE-PRIOR
VARIABLE _UFLSN-F-RANGES-VALID

: _UFLSN-ALIGNED?  ( address -- flag )  7 AND 0= ;

: _UFLSN-OPTIONAL-SPAN?  ( address bytes -- flag )
    DUP 0< IF 2DROP 0 EXIT THEN
    DUP 0= IF DROP 0= EXIT THEN
    OVER 0< IF 2DROP 0 EXIT THEN
    OVER 0= IF 2DROP 0 EXIT THEN
    MSPAN-NONWRAPPING? ;

: _UFLSN-DISJOINT?  ( a1 u1 a2 u2 -- flag )
    2 PICK 0= OVER 0= OR IF 2DROP 2DROP -1 EXIT THEN
    MSPAN-OVERLAP? 0= ;

: _UFLSN-OWNED-DISJOINT?  ( address bytes -- flag )
    DUP 0= IF 2DROP -1 EXIT THEN
    _UFLSN-OWNED-LIMIT @ DUP _UFLSN-OWNED-START U< IF
        DROP 2DROP 0 EXIT
    THEN
    _UFLSN-OWNED-START - >R
    2DUP _UFLSN-OWNED-START R> MSPAN-OVERLAP? 0= NIP NIP ;

\ Pure preflight for owners that reserve snapshot banks inside larger arenas.
: UFLSN-STORAGE-DISJOINT?  ( address bytes -- flag )
    2DUP _UFLSN-OPTIONAL-SPAN? 0= IF 2DROP 0 EXIT THEN
    _UFLSN-OWNED-DISJOINT? ;

\ Runs inside the outer resolved observation before the unified iterator.
\ The final seam includes hidden/direct/nested live widget authority.
: _UFLSN-AUTHORITY-DISJOINT?  ( address bytes -- flag )
    DUP 0= IF 2DROP -1 EXIT THEN
    2DUP _UFLSN-OWNED-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP UFLD-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP FLD-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP USF-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP USCOL-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP UDG-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP DGF-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP _UTUI-STORAGE-DISJOINT-BODY? 0= IF 2DROP 0 EXIT THEN
    _UTUI-FIELD-STORAGE-DISJOINT-OBSERVED?
    DUP UFLD-S-OK <> IF 2DROP 0 EXIT THEN
    DROP ;
CREATE _UFLSN-PROOF-SPANS 2 MSPAN-SET-BYTES ALLOT

\ Collect the two caller spans for one enclosed authority proof.  Their
\ shapes are admitted first, and the prover skips empty optional spans.
: _UFLSN-PROOF-SPANS?  ( -- flag )
    2 _UFLSN-PROOF-SPANS MSPAN-SET-INIT MSPAN-SET-S-OK <> IF 0 EXIT THEN
    _UFLSN-DESCRIPTORS-A @ _UFLSN-DESCRIPTORS-U @
        _UFLSN-PROOF-SPANS MSPAN-SET-PUSH MSPAN-SET-S-OK <> IF 0 EXIT THEN
    _UFLSN-NATIVE-A @ _UFLSN-NATIVE-U @ _UFLSN-PROOF-SPANS MSPAN-SET-PUSH
        MSPAN-SET-S-OK = ;
\ Caller span shapes and mutual disjointness.  Authority is proved
\ separately, before the first live FIELD visit.
: _UFLSN-SHAPES?  ( -- flag )
    _UFLSN-DESCRIPTORS-A @ _UFLSN-DESCRIPTORS-U @
        _UFLSN-OPTIONAL-SPAN? 0= IF 0 EXIT THEN
    _UFLSN-DESCRIPTORS-U @ UFLSN-DESCRIPTOR-SIZE MOD IF 0 EXIT THEN
    _UFLSN-DESCRIPTORS-U @ IF
        _UFLSN-DESCRIPTORS-A @ _UFLSN-ALIGNED? 0= IF 0 EXIT THEN
    THEN
    _UFLSN-NATIVE-A @ _UFLSN-NATIVE-U @
        _UFLSN-OPTIONAL-SPAN? 0= IF 0 EXIT THEN
    _UFLSN-NATIVE-U @ IF
        _UFLSN-NATIVE-A @ _UFLSN-ALIGNED? 0= IF 0 EXIT THEN
    THEN
    _UFLSN-DESCRIPTORS-A @ _UFLSN-DESCRIPTORS-U @
        _UFLSN-NATIVE-A @ _UFLSN-NATIVE-U @ _UFLSN-DISJOINT? ;
\ Each authority query walks the document's storage.  Clustered caller spans
\ need one enclosed query instead of one per span.
: _UFLSN-AUTHORITY?  ( -- flag )
    _UFLSN-PROOF-SPANS? 0= IF 0 EXIT THEN
    _UFLSN-PROOF-SPANS ['] _UFLSN-AUTHORITY-DISJOINT?
        MSPAN-SET-PROVE-DISJOINT? ;

: _UFLSN-DESCRIPTOR-AT  ( ordinal -- descriptor )
    UFLSN-DESCRIPTOR-SIZE * _UFLSN-DESCRIPTORS-A @ + ;

: _UFLSN-SET-CAPACITY  ( -- )
    _UFLSN-STATUS @ UFLSN-S-OK = IF
        UFLSN-S-CAPACITY _UFLSN-STATUS !
    THEN ;

: _UFLSN-SET-UNAVAILABLE  ( -- )
    _UFLSN-STATUS @ UFLSN-S-OK = IF
        UFLSN-S-UNAVAILABLE _UFLSN-STATUS !
    THEN ;

: _UFLSN-SET-INVALID  ( -- )
    UFLSN-S-INVALID _UFLSN-STATUS ! ;

: _UFLSN-MAP-UFLD  ( status -- )
    DUP UFLD-S-OK = IF DROP EXIT THEN
    DUP UFLD-S-CAPACITY = IF DROP _UFLSN-SET-CAPACITY EXIT THEN
    DUP UFLD-S-UNSUPPORTED = IF DROP _UFLSN-SET-UNAVAILABLE EXIT THEN
    DROP _UFLSN-SET-INVALID ;
: _UFLSN-MAP-MOUNTED  ( status -- )
    DUP _UTUI-MC-S-OK = IF DROP EXIT THEN
    DUP _UTUI-MC-S-UNAVAILABLE = IF
        DROP _UFLSN-SET-UNAVAILABLE
    ELSE
        DROP _UFLSN-SET-INVALID
    THEN ;

: _UFLSN-CLEAR-OUTPUT  ( -- )
    _UFLSN-RANGES-VALID @ 0= IF EXIT THEN
    _UFLSN-DIRTY-DESCRIPTOR-U @ ?DUP IF
        _UFLSN-DESCRIPTORS-A @ SWAP 0 FILL
    THEN
    _UFLSN-DIRTY-NATIVE-U @ ?DUP IF
        _UFLSN-NATIVE-A @ SWAP 0 FILL
    THEN ;


: _UFLSN-GENERATION?  ( generation -- flag )  DUP 0<> SWAP -1 <> AND ;
\ =====================================================================
\  One canonical mounted FIELD visit
\ =====================================================================

: _UFLSN-V-ARGS?  ( -- flag )
    _UFLSN-V-INDEX @ 0< IF 0 EXIT THEN
    UIDL-ELEM-COUNT DUP 0> 0= IF DROP 0 EXIT THEN
    _UFLSN-V-INDEX @ SWAP U< 0= IF 0 EXIT THEN
    _UFLSN-V-GENERATION @ _UFLSN-GENERATION? 0= IF 0 EXIT THEN
    _UFLSN-V-ROOT-KEY @ 0= IF 0 EXIT THEN
    _UFLSN-V-RESOLVED-U @ UTUI-RESOLVED-SIZE <> IF 0 EXIT THEN
    _UFLSN-V-RESOLVED-A @ _UFLSN-V-RESOLVED-U @
        UTUI-RESOLVED-VALID? ;

: _UFLSN-V-ORDER?  ( -- flag )
    _UFLSN-HAVE-PRIOR @ IF
        _UFLSN-V-INDEX @ _UFLSN-PRIOR-INDEX @ U< IF 0 EXIT THEN
        _UFLSN-V-INDEX @ _UFLSN-PRIOR-INDEX @ = IF
            _UFLSN-PRIOR-ROOT @ _UFLSN-V-ROOT-KEY @ U< 0= IF
                0 EXIT
            THEN
            _UFLSN-V-GENERATION @ _UFLSN-PRIOR-GENERATION @ <> IF
                0 EXIT
            THEN
        THEN
    THEN
    _UFLSN-V-INDEX @ _UFLSN-PRIOR-INDEX !
    _UFLSN-V-GENERATION @ _UFLSN-PRIOR-GENERATION !
    _UFLSN-V-ROOT-KEY @ _UFLSN-PRIOR-ROOT !
    -1 _UFLSN-HAVE-PRIOR !
    -1 ;

: _UFLSN-V-TAKE-GEOMETRY?  ( geometry-fields status -- flag )
    DUP UFLD-S-OK <> IF
        >R 2DROP 2DROP 2DROP 2DROP R> _UFLSN-MAP-UFLD 0 EXIT
    THEN
    DROP
    _UFLSN-V-CLIP-WIDTH ! _UFLSN-V-CLIP-HEIGHT !
    _UFLSN-V-CLIP-COLUMN ! _UFLSN-V-CLIP-ROW !
    _UFLSN-V-EXTENT-WIDTH ! _UFLSN-V-EXTENT-HEIGHT !
    _UFLSN-V-ORIGIN-COLUMN ! _UFLSN-V-ORIGIN-ROW !
    -1 ;

: _UFLSN-V-GEOMETRY?  ( -- flag )
    _UTUI-FIELD-GEOMETRY _UFLSN-V-TAKE-GEOMETRY? 0= IF 0 EXIT THEN
    _UFLSN-V-EXTENT-HEIGHT @ 0> 0=
    _UFLSN-V-EXTENT-WIDTH @ 0> 0= OR
    _UFLSN-V-ORIGIN-ROW @ 0< OR _UFLSN-V-ORIGIN-COLUMN @ 0< OR
    _UFLSN-V-CLIP-ROW @ _UFLSN-V-ORIGIN-ROW @ <> OR
    _UFLSN-V-CLIP-COLUMN @ _UFLSN-V-ORIGIN-COLUMN @ <> OR
    _UFLSN-V-CLIP-HEIGHT @ _UFLSN-V-EXTENT-HEIGHT @ <> OR
    _UFLSN-V-CLIP-WIDTH @ _UFLSN-V-EXTENT-WIDTH @ <> OR IF
        _UFLSN-SET-UNAVAILABLE 0 EXIT
    THEN
    -1 ;
: _UFLSN-V-PRODUCE  ( destination capacity -- bytes status )
    _UTUI-FIELD-CAPTURE-PREFLIGHTED ;
: _UFLSN-IADD-NONNEG?  ( signed nonnegative -- sum flag )
    DUP 0< IF 2DROP 0 0 EXIT THEN
    >R
    DUP _UFLSN-SIGNED-MAX R@ - > IF
        DROP R> DROP 0 0 EXIT
    THEN
    R> + -1 ;


: _UFLSN-V-ROOT-FIT?  ( -- flag )
    _UFLSN-V-ENTRY @ UFLD-WIDTH@ DUP _UFLSN-V-WIDTH !
        _UFLSN-V-EXTENT-WIDTH @ <> IF 0 EXIT THEN
    _UFLSN-V-ENTRY @ UFLD-HEIGHT@ DUP _UFLSN-V-HEIGHT !
        _UFLSN-V-EXTENT-HEIGHT @ <> IF 0 EXIT THEN
    _UFLSN-V-ORIGIN-ROW @ DUP _UFLSN-V-ROW !
        _UFLSN-V-HEIGHT @ _UFLSN-IADD-NONNEG? 0= IF DROP 0 EXIT THEN DROP
    _UFLSN-V-ORIGIN-COLUMN @ DUP _UFLSN-V-COLUMN !
        _UFLSN-V-WIDTH @ _UFLSN-IADD-NONNEG? 0= IF DROP 0 EXIT THEN DROP
    _UFLSN-V-RESOLVED-A @ 64 + @ DUP _UFLSN-V-Z !
        255 U> IF 0 EXIT THEN
    -1 ;
: _UFLSN-V-VALIDATE?  ( -- flag )
    _UFLSN-V-ENTRY @ _UFLSN-V-ENTRY-U @ UFLD-VALIDATE
    DUP UFLD-S-OK <> IF _UFLSN-MAP-UFLD 0 EXIT THEN DROP
    _UFLSN-V-ENTRY @ UFLD-STATE@ UFLD-STATE-VISIBLE AND 0= IF
        _UFLSN-SET-UNAVAILABLE 0 EXIT
    THEN
    _UFLSN-V-ENTRY @ UFLD-BYTES@ _UFLSN-V-ENTRY-U @ <> IF
        _UFLSN-SET-INVALID 0 EXIT
    THEN
    _UFLSN-V-ROOT-FIT? 0= IF _UFLSN-SET-INVALID 0 EXIT THEN
    -1 ;
: _UFLSN-V-CAPACITY?  ( -- flag )
    _UFLSN-COUNT @ _UFLSN-DESCRIPTOR-CAP @ U< 0= IF
        _UFLSN-SET-CAPACITY 0 EXIT
    THEN
    _UFLSN-COUNT @ _UFLSN-DESCRIPTOR-AT _UFLSN-V-DESCRIPTOR !
    _UFLSN-COUNT @ 1+ UFLSN-DESCRIPTOR-SIZE *
        _UFLSN-DIRTY-DESCRIPTOR-U !
    _UFLSN-V-DESCRIPTOR @ UFLSN-DESCRIPTOR-SIZE 0 FILL
    -1 ;

: _UFLSN-V-WRITE-METADATA  ( -- )
    UFLSN-SOURCE-UIDL _UFLSN-V-DESCRIPTOR @ _UFLSN-D.SOURCE !
    _UFLSN-V-INDEX @ _UFLSN-V-DESCRIPTOR @ _UFLSN-D.INDEX !
    _UFLSN-V-GENERATION @
        _UFLSN-V-DESCRIPTOR @ _UFLSN-D.GENERATION !
    _UFLSN-V-ROOT-KEY @
        _UFLSN-V-DESCRIPTOR @ _UFLSN-D.ROOT-KEY !
    _UFLSN-NATIVE-USED @ _UFLSN-V-DESCRIPTOR @ _UFLSN-D.NATIVE-O !
    _UFLSN-V-ROW @ _UFLSN-V-DESCRIPTOR @ _UFLSN-D.ROW !
    _UFLSN-V-COLUMN @ _UFLSN-V-DESCRIPTOR @ _UFLSN-D.COLUMN !
    _UFLSN-V-HEIGHT @ _UFLSN-V-DESCRIPTOR @ _UFLSN-D.HEIGHT !
    _UFLSN-V-WIDTH @ _UFLSN-V-DESCRIPTOR @ _UFLSN-D.WIDTH !
    _UFLSN-V-CLIP-ROW @ _UFLSN-V-DESCRIPTOR @ _UFLSN-D.CLIP-ROW !
    _UFLSN-V-CLIP-COLUMN @
        _UFLSN-V-DESCRIPTOR @ _UFLSN-D.CLIP-COLUMN !
    _UFLSN-V-CLIP-HEIGHT @
        _UFLSN-V-DESCRIPTOR @ _UFLSN-D.CLIP-HEIGHT !
    _UFLSN-V-CLIP-WIDTH @
        _UFLSN-V-DESCRIPTOR @ _UFLSN-D.CLIP-WIDTH !
    _UFLSN-V-Z @ _UFLSN-V-DESCRIPTOR @ _UFLSN-D.Z !
    _UFLSN-V-ENTRY-U @ _UFLSN-V-DESCRIPTOR @ _UFLSN-D.ENTRY-U !
    _UFLSN-V-ENTRY @ UFLD-UTF8-BYTES@
        _UFLSN-V-DESCRIPTOR @ _UFLSN-D.UTF8-U ! ;

: _UFLSN-V-ROLLBACK-CLIPPED  ( -- )
    _UFLSN-V-ENTRY @ _UFLSN-V-ENTRY-U @ 0 FILL
    _UFLSN-V-DESCRIPTOR @ UFLSN-DESCRIPTOR-SIZE 0 FILL
    _UFLSN-NATIVE-USED @ _UFLSN-DIRTY-NATIVE-U !
    _UFLSN-COUNT @ UFLSN-DESCRIPTOR-SIZE *
        _UFLSN-DIRTY-DESCRIPTOR-U ! ;

\ _UFLSN-V-REFUSED ( -- )
\   A root's own widget could not publish it.  Leave that root out, so CELL
\   draws its area and the snapshot keeps its other roots, and keep nothing
\   of it: its entry bytes and descriptor are cleared as a fully clipped
\   root's are.  A capacity refusal stays the snapshot's.
: _UFLSN-V-REFUSED  ( -- )
    _UFLSN-STATUS @ DUP UFLSN-S-UNAVAILABLE = SWAP UFLSN-S-INVALID = OR
        0= IF EXIT THEN
    _UFLSN-V-DESCRIPTOR @ IF _UFLSN-V-ROLLBACK-CLIPPED THEN
    UFLSN-S-OK _UFLSN-STATUS ! ;

: _UFLSN-V-CAPTURE  ( -- )
    _UFLSN-V-CLIP-HEIGHT @ 0= _UFLSN-V-CLIP-WIDTH @ 0= OR IF
        EXIT
    THEN
    _UFLSN-V-CAPACITY? 0= IF EXIT THEN
    _UFLSN-NATIVE-USED @ _UFLSN-NATIVE-U @ U> IF
        _UFLSN-SET-INVALID EXIT
    THEN
    _UFLSN-NATIVE-U @ _UFLSN-NATIVE-USED @ - DUP 0= IF
        DROP _UFLSN-SET-CAPACITY EXIT
    THEN
    _UFLSN-V-REMAINING !
    0 _UFLSN-V-ENTRY-U !

    \ Measure through the exact same current widget before touching
    \ the native bank.  The captured byte count must remain identical.
    0 0 _UFLSN-V-PRODUCE
    DUP UFLD-S-OK <> IF
        >R DROP R> _UFLSN-MAP-UFLD _UFLSN-V-REFUSED EXIT
    THEN
    DROP
    DUP 0> 0= OVER 7 AND OR IF
        DROP _UFLSN-SET-INVALID _UFLSN-V-REFUSED EXIT
    THEN
    DUP _UFLSN-V-REMAINING @ U> IF
        DROP _UFLSN-SET-CAPACITY EXIT
    THEN
    _UFLSN-V-ENTRY-U !

    _UFLSN-NATIVE-A @ _UFLSN-NATIVE-USED @ + _UFLSN-V-ENTRY !
    _UFLSN-NATIVE-USED @ _UFLSN-V-ENTRY-U @ + DUP
        _UFLSN-V-NEXT-NATIVE ! _UFLSN-DIRTY-NATIVE-U !
    _UFLSN-V-ENTRY @ _UFLSN-V-ENTRY-U @ _UFLSN-V-PRODUCE
    DUP UFLD-S-OK <> IF
        >R DROP R> _UFLSN-MAP-UFLD _UFLSN-V-REFUSED EXIT
    THEN
    DROP _UFLSN-V-ENTRY-U @ <> IF
        _UFLSN-SET-INVALID _UFLSN-V-REFUSED EXIT
    THEN

    _UFLSN-V-VALIDATE? 0= IF _UFLSN-V-REFUSED EXIT THEN
    _UFLSN-V-CLIP-HEIGHT @ 0= _UFLSN-V-CLIP-WIDTH @ 0= OR IF
        _UFLSN-V-ROLLBACK-CLIPPED EXIT
    THEN
    _UFLSN-V-WRITE-METADATA
    _UFLSN-V-NEXT-NATIVE @ _UFLSN-NATIVE-USED !
    1 _UFLSN-COUNT +! ;

: _UFLSN-VISITOR
    ( source-index source-generation root-key resolved-a resolved-u -- )
    _UFLSN-V-RESOLVED-U ! _UFLSN-V-RESOLVED-A !
    _UFLSN-V-ROOT-KEY ! _UFLSN-V-GENERATION ! _UFLSN-V-INDEX !
    _UFLSN-STATUS @ UFLSN-S-OK <> IF EXIT THEN
    _UFLSN-V-ARGS? 0= IF _UFLSN-SET-INVALID EXIT THEN
    _UFLSN-V-ORDER? 0= IF _UFLSN-SET-INVALID EXIT THEN
    0 _UFLSN-V-DESCRIPTOR ! 0 _UFLSN-V-ENTRY-U !
    _UFLSN-V-GEOMETRY? 0= IF _UFLSN-V-REFUSED EXIT THEN
    _UFLSN-V-CAPTURE ;

\ =====================================================================
\  Capture orchestration
\ =====================================================================

: _UFLSN-FAIL-RESULT  ( -- 0 0 status )
    _UFLSN-CLEAR-OUTPUT
    0 0 _UFLSN-STATUS @ ;

: _UFLSN-CAPTURE-BODY  ( -- descriptor-count native-used status )
    UFLSN-S-OK _UFLSN-STATUS !
    0 _UFLSN-COUNT ! 0 _UFLSN-NATIVE-USED !
    0 _UFLSN-DIRTY-DESCRIPTOR-U ! 0 _UFLSN-DIRTY-NATIVE-U !
    0 _UFLSN-HAVE-PRIOR !
    ['] _UFLSN-VISITOR
        _UTUI-FIELD-EACH-PREFLIGHTED
        _UFLSN-MAP-MOUNTED
    _UFLSN-STATUS @ UFLSN-S-OK <> IF _UFLSN-FAIL-RESULT EXIT THEN
    _UFLSN-COUNT @ _UFLSN-NATIVE-USED @ UFLSN-S-OK ;

: _UFLSN-CAPTURE-OBSERVED  ( -- descriptor-count native-used status )
    UFLSN-S-OK _UFLSN-STATUS !
    0 _UFLSN-RANGES-VALID !
    0 _UFLSN-DIRTY-DESCRIPTOR-U ! 0 _UFLSN-DIRTY-NATIVE-U !
    _UFLSN-SHAPES? 0= IF 0 0 UFLSN-S-INVALID EXIT THEN
    _UFLSN-AUTHORITY? 0= IF 0 0 UFLSN-S-INVALID EXIT THEN
    _UFLSN-DESCRIPTORS-U @ UFLSN-DESCRIPTOR-SIZE /
        _UFLSN-DESCRIPTOR-CAP !
    -1 _UFLSN-RANGES-VALID !
    _UFLSN-CAPTURE-BODY ;

: _UFLSN-CAPTURE-OBSERVED-CATCH
    ( -- descriptor-count native-used status )
    ['] _UFLSN-CAPTURE-OBSERVED CATCH ?DUP IF
        DROP _UFLSN-SET-INVALID _UFLSN-FAIL-RESULT
    THEN ;

: _UFLSN-CAPTURE-CALL  ( -- descriptor-count native-used status )
    ['] _UFLSN-CAPTURE-OBSERVED-CATCH UTUI-RESOLVED-OBSERVE ;

: _UFLSN-SCRUB  ( -- )
    0 _UFLSN-DESCRIPTORS-A ! 0 _UFLSN-DESCRIPTORS-U !
    0 _UFLSN-DESCRIPTOR-CAP !
    0 _UFLSN-NATIVE-A ! 0 _UFLSN-NATIVE-U !
    0 _UFLSN-RANGES-VALID !
    0 _UFLSN-STATUS ! 0 _UFLSN-COUNT ! 0 _UFLSN-NATIVE-USED !
    0 _UFLSN-DIRTY-DESCRIPTOR-U ! 0 _UFLSN-DIRTY-NATIVE-U !
    0 _UFLSN-V-INDEX ! 0 _UFLSN-V-GENERATION !
    0 _UFLSN-V-ROOT-KEY !
    0 _UFLSN-V-RESOLVED-A ! 0 _UFLSN-V-RESOLVED-U !
    0 _UFLSN-V-DESCRIPTOR ! 0 _UFLSN-V-ENTRY !
    0 _UFLSN-V-ENTRY-U ! 0 _UFLSN-V-NEXT-NATIVE !
    0 _UFLSN-V-REMAINING !
    0 _UFLSN-V-ORIGIN-ROW ! 0 _UFLSN-V-ORIGIN-COLUMN !
    0 _UFLSN-V-EXTENT-HEIGHT ! 0 _UFLSN-V-EXTENT-WIDTH !
    0 _UFLSN-V-ROW ! 0 _UFLSN-V-COLUMN !
    0 _UFLSN-V-HEIGHT ! 0 _UFLSN-V-WIDTH !
    0 _UFLSN-V-CLIP-ROW ! 0 _UFLSN-V-CLIP-COLUMN !
    0 _UFLSN-V-CLIP-HEIGHT ! 0 _UFLSN-V-CLIP-WIDTH !
    0 _UFLSN-V-Z !
    0 _UFLSN-PRIOR-INDEX ! 0 _UFLSN-PRIOR-GENERATION !
    0 _UFLSN-PRIOR-ROOT ! 0 _UFLSN-HAVE-PRIOR !
    _UFLSN-PROOF-SPANS 2 MSPAN-SET-BYTES 0 FILL ;

: UFLSN-CAPTURE
    ( descriptors-a descriptors-u native-a native-u -- descriptor-count native-used status )
    3 PICK 3 PICK UFLSN-STORAGE-DISJOINT? 0= IF
        2DROP 2DROP 0 0 UFLSN-S-INVALID EXIT
    THEN
    2DUP UFLSN-STORAGE-DISJOINT? 0= IF
        2DROP 2DROP 0 0 UFLSN-S-INVALID EXIT
    THEN
    _UFLSN-NATIVE-U ! _UFLSN-NATIVE-A !
    _UFLSN-DESCRIPTORS-U ! _UFLSN-DESCRIPTORS-A !
    0 _UFLSN-RANGES-VALID !
    ['] _UFLSN-CAPTURE-CALL CATCH ?DUP IF
        DROP _UFLSN-SET-INVALID _UFLSN-FAIL-RESULT
    THEN
    _UFLSN-SCRUB ;

\ =====================================================================
\  Read-only validation of one frozen per-document bank
\ =====================================================================

: _UFLSN-F-UADD?  ( a b -- sum flag )
    OVER + DUP ROT U< 0= ;

: _UFLSN-F-WORK-AT  ( ordinal -- address )
    UFLSN-FROZEN-WORK-ENTRY-SIZE * _UFLSN-F-WORK-A @ + ;

: _UFLSN-F-DESCRIPTOR-AT  ( ordinal -- descriptor )
    UFLSN-DESCRIPTOR-SIZE * _UFLSN-F-DESCRIPTORS-A @ + ;

: _UFLSN-F-CLEAR-SCRATCH  ( -- )
    _UFLSN-F-RANGES-VALID @ IF
        _UFLSN-F-WORK-NEED @ ?DUP IF
            _UFLSN-F-WORK-A @ SWAP 0 FILL
        THEN
    THEN ;

: _UFLSN-F-SCRUB  ( -- )
    0 _UFLSN-F-WORK-A ! 0 _UFLSN-F-WORK-U !
    0 _UFLSN-F-WORK-NEED !
    0 _UFLSN-F-DESCRIPTORS-A ! 0 _UFLSN-F-DESCRIPTORS-U !
    0 _UFLSN-F-NATIVE-A ! 0 _UFLSN-F-NATIVE-U !
    0 _UFLSN-F-COUNT ! 0 _UFLSN-F-I ! 0 _UFLSN-F-J !
    0 _UFLSN-F-VALUE ! 0 _UFLSN-F-DESCRIPTOR !
    0 _UFLSN-F-HEAP-ROOT ! 0 _UFLSN-F-HEAP-END !
    0 _UFLSN-F-HEAP-CHILD ! 0 _UFLSN-F-HEAP-LARGEST !
    0 _UFLSN-F-HEAP-A ! 0 _UFLSN-F-HEAP-B !
    0 _UFLSN-F-FIELD ! 0 _UFLSN-F-FIELD-U !
    0 _UFLSN-F-OFFSET ! 0 _UFLSN-F-CURSOR !
    0 _UFLSN-F-INDEX ! 0 _UFLSN-F-GENERATION !
    0 _UFLSN-F-RELATION ! 0 _UFLSN-F-PRIOR-INDEX !
    0 _UFLSN-F-PRIOR-GENERATION ! 0 _UFLSN-F-PRIOR-RELATION !
    0 _UFLSN-F-HAVE-PRIOR !
    0 _UFLSN-F-RANGES-VALID ! ;

: _UFLSN-F-AUTHORITY-DISJOINT?  ( address bytes -- flag )
    DUP 0= IF 2DROP -1 EXIT THEN
    2DUP _UFLSN-OWNED-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP USCOL-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP UDG-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP DGF-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP FLD-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP USF-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    UFLD-STORAGE-DISJOINT? ;

: _UFLSN-F-RANGES  ( -- status )
    _UFLSN-F-DESCRIPTORS-A @ _UFLSN-F-DESCRIPTORS-U @
        _UFLSN-OPTIONAL-SPAN? 0= IF UFLSN-S-INVALID EXIT THEN
    _UFLSN-F-DESCRIPTORS-U @ UFLSN-DESCRIPTOR-SIZE MOD IF
        UFLSN-S-INVALID EXIT
    THEN
    _UFLSN-F-NATIVE-A @ _UFLSN-F-NATIVE-U @
        _UFLSN-OPTIONAL-SPAN? 0= IF UFLSN-S-INVALID EXIT THEN
    _UFLSN-F-DESCRIPTORS-U @ 0=
        _UFLSN-F-NATIVE-U @ 0= <> IF UFLSN-S-INVALID EXIT THEN
    _UFLSN-F-DESCRIPTORS-U @ IF
        _UFLSN-F-DESCRIPTORS-A @ _UFLSN-ALIGNED? 0= IF
            UFLSN-S-INVALID EXIT
        THEN
        _UFLSN-F-NATIVE-A @ _UFLSN-ALIGNED? 0= IF
            UFLSN-S-INVALID EXIT
        THEN
        _UFLSN-F-NATIVE-U @ 7 AND IF UFLSN-S-INVALID EXIT THEN
    THEN

    _UFLSN-F-DESCRIPTORS-U @ UFLSN-DESCRIPTOR-SIZE /
        DUP _UFLSN-F-COUNT !
    UFLSN-FROZEN-WORK-BYTES DUP _UFLSN-F-WORK-NEED !
    _UFLSN-F-COUNT @ IF
        DUP 0= IF DROP UFLSN-S-INVALID EXIT THEN
    THEN DROP
    _UFLSN-F-WORK-A @ _UFLSN-F-WORK-U @
        _UFLSN-OPTIONAL-SPAN? 0= IF UFLSN-S-INVALID EXIT THEN
    _UFLSN-F-WORK-U @ IF
        _UFLSN-F-WORK-A @ _UFLSN-ALIGNED? 0= IF
            UFLSN-S-INVALID EXIT
        THEN
    THEN
    _UFLSN-F-WORK-U @ _UFLSN-F-WORK-NEED @ U< IF
        UFLSN-S-CAPACITY EXIT
    THEN

    _UFLSN-F-WORK-A @ _UFLSN-F-WORK-U @
        _UFLSN-F-AUTHORITY-DISJOINT? 0= IF UFLSN-S-INVALID EXIT THEN
    _UFLSN-F-DESCRIPTORS-A @ _UFLSN-F-DESCRIPTORS-U @
        _UFLSN-F-AUTHORITY-DISJOINT? 0= IF UFLSN-S-INVALID EXIT THEN
    _UFLSN-F-NATIVE-A @ _UFLSN-F-NATIVE-U @
        _UFLSN-F-AUTHORITY-DISJOINT? 0= IF UFLSN-S-INVALID EXIT THEN

    _UFLSN-F-WORK-A @ _UFLSN-F-WORK-U @
        _UFLSN-F-DESCRIPTORS-A @ _UFLSN-F-DESCRIPTORS-U @
        _UFLSN-DISJOINT? 0= IF UFLSN-S-INVALID EXIT THEN
    _UFLSN-F-WORK-A @ _UFLSN-F-WORK-U @
        _UFLSN-F-NATIVE-A @ _UFLSN-F-NATIVE-U @
        _UFLSN-DISJOINT? 0= IF UFLSN-S-INVALID EXIT THEN
    _UFLSN-F-DESCRIPTORS-A @ _UFLSN-F-DESCRIPTORS-U @
        _UFLSN-F-NATIVE-A @ _UFLSN-F-NATIVE-U @
        _UFLSN-DISJOINT? 0= IF UFLSN-S-INVALID EXIT THEN

    -1 _UFLSN-F-RANGES-VALID !
    _UFLSN-F-CLEAR-SCRATCH
    UFLSN-S-OK ;

: _UFLSN-F-ORDER?  ( -- flag )
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-SOURCE@
        UFLSN-SOURCE-UIDL <> IF 0 EXIT THEN
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-SOURCE-INDEX@
        DUP 0< IF DROP 0 EXIT THEN _UFLSN-F-INDEX !
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-SOURCE-GENERATION@
        DUP _UFLSN-GENERATION? 0= IF DROP 0 EXIT THEN
        _UFLSN-F-GENERATION !
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-ROOT-KEY@
        DUP 0= IF DROP 0 EXIT THEN _UFLSN-F-RELATION !
    _UFLSN-F-HAVE-PRIOR @ IF
        _UFLSN-F-INDEX @ _UFLSN-F-PRIOR-INDEX @ U< IF 0 EXIT THEN
        _UFLSN-F-INDEX @ _UFLSN-F-PRIOR-INDEX @ = IF
            _UFLSN-F-PRIOR-RELATION @ _UFLSN-F-RELATION @
                U< 0= IF 0 EXIT THEN
            _UFLSN-F-GENERATION @ _UFLSN-F-PRIOR-GENERATION @
                <> IF 0 EXIT THEN
        THEN
    THEN
    _UFLSN-F-INDEX @ _UFLSN-F-PRIOR-INDEX !
    _UFLSN-F-GENERATION @ _UFLSN-F-PRIOR-GENERATION !
    _UFLSN-F-RELATION @ _UFLSN-F-PRIOR-RELATION !
    -1 _UFLSN-F-HAVE-PRIOR !
    -1 ;

: _UFLSN-F-GEOMETRY?  ( -- flag )
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-HEIGHT@
        _UFLSN-F-FIELD @ UFLD-HEIGHT@ <> IF 0 EXIT THEN
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-WIDTH@
        _UFLSN-F-FIELD @ UFLD-WIDTH@ <> IF 0 EXIT THEN
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-ROW@ DUP 0< IF
        DROP 0 EXIT
    THEN
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-HEIGHT@
        _UFLSN-IADD-NONNEG? 0= IF DROP 0 EXIT THEN DROP
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-COLUMN@ DUP 0< IF
        DROP 0 EXIT
    THEN
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-WIDTH@
        _UFLSN-IADD-NONNEG? 0= IF DROP 0 EXIT THEN DROP
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-CLIP-ROW@
        _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-ROW@ <> IF 0 EXIT THEN
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-CLIP-COLUMN@
        _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-COLUMN@ <> IF 0 EXIT THEN
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-CLIP-HEIGHT@
        _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-HEIGHT@ <> IF 0 EXIT THEN
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-CLIP-WIDTH@
        _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-WIDTH@ <> IF 0 EXIT THEN
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-Z@ 255 U> IF 0 EXIT THEN
    -1 ;
: _UFLSN-F-ENTRY?  ( -- flag )
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-NATIVE-OFFSET@
        DUP 0< IF DROP 0 EXIT THEN
        DUP 7 AND IF DROP 0 EXIT THEN
        DUP _UFLSN-F-OFFSET !
    _UFLSN-F-NATIVE-U @ U> IF 0 EXIT THEN
    _UFLSN-F-NATIVE-U @ _UFLSN-F-OFFSET @ -
        UFLD-HEADER-SIZE U< IF 0 EXIT THEN
    _UFLSN-F-NATIVE-A @ _UFLSN-F-OFFSET @ +
        DUP _UFLSN-F-FIELD !
    UFLD-BYTES@ DUP _UFLSN-F-FIELD-U !
    DUP UFLD-HEADER-SIZE U< OVER 7 AND OR IF DROP 0 EXIT THEN
    _UFLSN-F-NATIVE-U @ _UFLSN-F-OFFSET @ - U> IF 0 EXIT THEN
    _UFLSN-F-FIELD @ _UFLSN-F-FIELD-U @ UFLD-VALIDATE
        UFLD-S-OK <> IF 0 EXIT THEN
    _UFLSN-F-FIELD @ UFLD-STATE@ UFLD-STATE-VISIBLE AND 0= IF 0 EXIT THEN
    _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-ENTRY-BYTES@
        _UFLSN-F-FIELD-U @ <> IF 0 EXIT THEN
    _UFLSN-F-FIELD @ UFLD-UTF8-BYTES@
        _UFLSN-F-DESCRIPTOR @ UFLSN-DESCRIPTOR-UTF8-BYTES@ <> IF 0 EXIT THEN
    _UFLSN-F-GEOMETRY? 0= IF 0 EXIT THEN
    _UFLSN-F-OFFSET @ _UFLSN-F-I @ _UFLSN-F-WORK-AT !
    -1 ;
: _UFLSN-F-SWAP-OFFSETS  ( ordinal-a ordinal-b -- )
    _UFLSN-F-HEAP-B ! _UFLSN-F-HEAP-A !
    _UFLSN-F-HEAP-A @ _UFLSN-F-WORK-AT @ _UFLSN-F-VALUE !
    _UFLSN-F-HEAP-B @ _UFLSN-F-WORK-AT @
        _UFLSN-F-HEAP-A @ _UFLSN-F-WORK-AT !
    _UFLSN-F-VALUE @ _UFLSN-F-HEAP-B @ _UFLSN-F-WORK-AT ! ;

\ Restore one unsigned max-heap below the exclusive END ordinal.  The
\ caller-bounded ledger makes this O(n log n) at the configured ceiling.
: _UFLSN-F-SIFT-DOWN  ( root end -- )
    _UFLSN-F-HEAP-END ! _UFLSN-F-HEAP-ROOT !
    BEGIN
        _UFLSN-F-HEAP-ROOT @ 2 * 1+ DUP _UFLSN-F-HEAP-CHILD !
        _UFLSN-F-HEAP-END @ U<
    WHILE
        _UFLSN-F-HEAP-ROOT @ _UFLSN-F-HEAP-LARGEST !
        _UFLSN-F-HEAP-LARGEST @ _UFLSN-F-WORK-AT @
        _UFLSN-F-HEAP-CHILD @ _UFLSN-F-WORK-AT @ U< IF
            _UFLSN-F-HEAP-CHILD @ _UFLSN-F-HEAP-LARGEST !
        THEN
        _UFLSN-F-HEAP-CHILD @ 1+ DUP _UFLSN-F-HEAP-CHILD !
        _UFLSN-F-HEAP-END @ U< IF
            _UFLSN-F-HEAP-LARGEST @ _UFLSN-F-WORK-AT @
            _UFLSN-F-HEAP-CHILD @ _UFLSN-F-WORK-AT @ U< IF
                _UFLSN-F-HEAP-CHILD @ _UFLSN-F-HEAP-LARGEST !
            THEN
        THEN
        _UFLSN-F-HEAP-LARGEST @ _UFLSN-F-HEAP-ROOT @ = IF EXIT THEN
        _UFLSN-F-HEAP-ROOT @ _UFLSN-F-HEAP-LARGEST @
            _UFLSN-F-SWAP-OFFSETS
        _UFLSN-F-HEAP-LARGEST @ _UFLSN-F-HEAP-ROOT !
    REPEAT ;

: _UFLSN-F-SORT-OFFSETS  ( -- )
    _UFLSN-F-COUNT @ 2 / _UFLSN-F-I !
    BEGIN _UFLSN-F-I @ 0> WHILE
        -1 _UFLSN-F-I +!
        _UFLSN-F-I @ _UFLSN-F-COUNT @ _UFLSN-F-SIFT-DOWN
    REPEAT
    _UFLSN-F-COUNT @ _UFLSN-F-J !
    BEGIN _UFLSN-F-J @ 1 > WHILE
        -1 _UFLSN-F-J +!
        0 _UFLSN-F-J @ _UFLSN-F-SWAP-OFFSETS
        0 _UFLSN-F-J @ _UFLSN-F-SIFT-DOWN
    REPEAT ;

: _UFLSN-F-COVERAGE?  ( -- flag )
    0 _UFLSN-F-CURSOR ! 0 _UFLSN-F-I !
    BEGIN _UFLSN-F-I @ _UFLSN-F-COUNT @ U< WHILE
        _UFLSN-F-I @ _UFLSN-F-WORK-AT @ DUP _UFLSN-F-OFFSET !
        _UFLSN-F-CURSOR @ <> IF 0 EXIT THEN
        _UFLSN-F-OFFSET @ _UFLSN-F-NATIVE-U @ U> IF 0 EXIT THEN
        _UFLSN-F-NATIVE-U @ _UFLSN-F-OFFSET @ -
            UFLD-HEADER-SIZE U< IF 0 EXIT THEN
        _UFLSN-F-NATIVE-A @ _UFLSN-F-OFFSET @ + UFLD-BYTES@
            DUP UFLD-HEADER-SIZE U< OVER 7 AND OR IF DROP 0 EXIT THEN
        _UFLSN-F-CURSOR @ SWAP _UFLSN-F-UADD?
            0= IF DROP 0 EXIT THEN
        DUP _UFLSN-F-NATIVE-U @ U> IF DROP 0 EXIT THEN
            _UFLSN-F-CURSOR !
        1 _UFLSN-F-I +!
    REPEAT
    _UFLSN-F-CURSOR @ _UFLSN-F-NATIVE-U @ = ;

: _UFLSN-F-VALIDATE-BODY  ( -- status )
    _UFLSN-F-RANGES DUP UFLSN-S-OK <> IF EXIT THEN DROP
    _UFLSN-F-COUNT @ 0= IF UFLSN-S-OK EXIT THEN
    0 _UFLSN-F-PRIOR-INDEX ! 0 _UFLSN-F-PRIOR-GENERATION !
    0 _UFLSN-F-PRIOR-RELATION ! 0 _UFLSN-F-HAVE-PRIOR !
    0 _UFLSN-F-I !
    BEGIN _UFLSN-F-I @ _UFLSN-F-COUNT @ U< WHILE
        _UFLSN-F-I @ _UFLSN-F-DESCRIPTOR-AT
            _UFLSN-F-DESCRIPTOR !
        _UFLSN-F-ORDER? 0= IF UFLSN-S-INVALID EXIT THEN
        _UFLSN-F-ENTRY? 0= IF UFLSN-S-INVALID EXIT THEN
        1 _UFLSN-F-I +!
    REPEAT
    _UFLSN-F-SORT-OFFSETS
    _UFLSN-F-COVERAGE? 0= IF UFLSN-S-INVALID EXIT THEN
    UFLSN-S-OK ;

: _UFLSN-F-VALIDATE-CALL  ( -- status )
    ['] _UFLSN-F-VALIDATE-BODY CATCH ?DUP IF
        DROP UFLSN-S-INVALID
    THEN
    _UFLSN-F-CLEAR-SCRATCH
    _UFLSN-F-SCRUB ;

: UFLSN-FROZEN-VALIDATE
    ( offset-work-a offset-work-u descriptors-a descriptors-u native-a native-u -- status )
    5 PICK 5 PICK UFLSN-STORAGE-DISJOINT? 0= IF
        2DROP 2DROP 2DROP UFLSN-S-INVALID EXIT
    THEN
    3 PICK 3 PICK UFLSN-STORAGE-DISJOINT? 0= IF
        2DROP 2DROP 2DROP UFLSN-S-INVALID EXIT
    THEN
    2DUP UFLSN-STORAGE-DISJOINT? 0= IF
        2DROP 2DROP 2DROP UFLSN-S-INVALID EXIT
    THEN
    _UFLSN-F-NATIVE-U ! _UFLSN-F-NATIVE-A !
    _UFLSN-F-DESCRIPTORS-U ! _UFLSN-F-DESCRIPTORS-A !
    _UFLSN-F-WORK-U ! _UFLSN-F-WORK-A !
    0 _UFLSN-F-WORK-NEED ! 0 _UFLSN-F-RANGES-VALID !
    ['] _UFLSN-F-VALIDATE-CALL CATCH ?DUP IF
        DROP
        _UFLSN-F-CLEAR-SCRATCH
        _UFLSN-F-SCRUB
        UFLSN-S-INVALID
    THEN ;

CREATE _UFLSN-OWNED-END
_UFLSN-OWNED-END _UFLSN-OWNED-LIMIT !
