\ =====================================================================
\  uidl-status-field-snapshot.f -- direct and mounted status-field snapshot
\ =====================================================================
\
\  One coherent UIDL-TUI observation captures ordinary direct status labels
\  and mounted SFIELD widgets into a separate caller-owned native USF bank and
\  pointer-free descriptors. Records are canonical by unsigned source index
\  and relation root key. Native field keys remain application-owned.
\
\  Only complete one-row fields whose exact clip equals their full geometry
\  are admitted. Unsupported or partially clipped roots remain CELL-owned;
\  a capacity failure clears every dirtied descriptor/native output byte.
\  Caller banks must be pairwise disjoint and disjoint from module scratch,
\  UIDL authority, and every live semantic widget and backing model.
\
\  USFSN-CAPTURE ( descriptors-a descriptors-u native-a native-u
\                  -- descriptor-count native-used status )
\  USFSN-FROZEN-WORK-BYTES ( descriptor-count -- bytes|0 )
\  USFSN-FROZEN-VALIDATE ( work-a work-u descriptors-a descriptors-u
\                          native-a native-u -- status )
\
\  Frozen validation never consults the live tree. It validates every USF,
\  checks complete descriptor geometry and counts, and sorts caller-owned
\  offsets to prove exact native-bank coverage without overlap or gaps.
\  Prefix: USFSN- (public), _USFSN- (private).

PROVIDED akashic-tui-uidl-status-field-snapshot

REQUIRE uidl-tui.f
REQUIRE status-field-model.f
REQUIRE widgets/status-field.f
REQUIRE ../utils/memory-span.f

0 CONSTANT USFSN-S-OK
1 CONSTANT USFSN-S-CAPACITY
2 CONSTANT USFSN-S-UNAVAILABLE
3 CONSTANT USFSN-S-INVALID

: USFSN-STATUS-VALID?  ( status -- flag )  4 U< ;

\ The native status-field bank remains separate from collection and graph banks.
1 CONSTANT USFSN-SOURCE-UIDL

\ Descriptor fields are native cells and contain no pointer.
\
\   +0   source kind
\   +8   UIDL pool source index
\   +16  source generation (zero for direct UIDL fields)
\   +24  relation root key (one for direct UIDL fields)
\   +32  native field offset relative to this document's native bank
\   +40  translated root row
\   +48  translated root column
\   +56  complete root height
\   +64  complete root width
\   +72  clip row
\   +80  clip column
\   +88  clip height
\   +96  clip width
\   +104 resolved UIDL paint z
\   +112 native entry bytes
\   +120 total label/value UTF-8 bytes

: _USFSN-D.SOURCE       ( descriptor -- address )       ;
: _USFSN-D.INDEX        ( descriptor -- address )   8 + ;
: _USFSN-D.GENERATION   ( descriptor -- address )  16 + ;
: _USFSN-D.ROOT-KEY     ( descriptor -- address )  24 + ;
: _USFSN-D.NATIVE-O     ( descriptor -- address )  32 + ;
: _USFSN-D.ROW          ( descriptor -- address )  40 + ;
: _USFSN-D.COLUMN       ( descriptor -- address )  48 + ;
: _USFSN-D.HEIGHT       ( descriptor -- address )  56 + ;
: _USFSN-D.WIDTH        ( descriptor -- address )  64 + ;
: _USFSN-D.CLIP-ROW     ( descriptor -- address )  72 + ;
: _USFSN-D.CLIP-COLUMN  ( descriptor -- address )  80 + ;
: _USFSN-D.CLIP-HEIGHT  ( descriptor -- address )  88 + ;
: _USFSN-D.CLIP-WIDTH   ( descriptor -- address )  96 + ;
: _USFSN-D.Z            ( descriptor -- address ) 104 + ;
: _USFSN-D.ENTRY-U      ( descriptor -- address ) 112 + ;
: _USFSN-D.UTF8-U       ( descriptor -- address ) 120 + ;

128 CONSTANT USFSN-DESCRIPTOR-SIZE

: USFSN-DESCRIPTOR-BYTES  ( -- bytes )  USFSN-DESCRIPTOR-SIZE ;
: USFSN-DESCRIPTOR-SOURCE@  ( descriptor -- value )
    _USFSN-D.SOURCE @ ;
: USFSN-DESCRIPTOR-SOURCE-INDEX@  ( descriptor -- value )
    _USFSN-D.INDEX @ ;
: USFSN-DESCRIPTOR-SOURCE-GENERATION@  ( descriptor -- value )
    _USFSN-D.GENERATION @ ;
: USFSN-DESCRIPTOR-ROOT-KEY@  ( descriptor -- value )
    _USFSN-D.ROOT-KEY @ ;
: USFSN-DESCRIPTOR-NATIVE-OFFSET@  ( descriptor -- value )
    _USFSN-D.NATIVE-O @ ;
: USFSN-DESCRIPTOR-ROW@  ( descriptor -- value )
    _USFSN-D.ROW @ ;
: USFSN-DESCRIPTOR-COLUMN@  ( descriptor -- value )
    _USFSN-D.COLUMN @ ;
: USFSN-DESCRIPTOR-HEIGHT@  ( descriptor -- value )
    _USFSN-D.HEIGHT @ ;
: USFSN-DESCRIPTOR-WIDTH@  ( descriptor -- value )
    _USFSN-D.WIDTH @ ;
: USFSN-DESCRIPTOR-CLIP-ROW@  ( descriptor -- value )
    _USFSN-D.CLIP-ROW @ ;
: USFSN-DESCRIPTOR-CLIP-COLUMN@  ( descriptor -- value )
    _USFSN-D.CLIP-COLUMN @ ;
: USFSN-DESCRIPTOR-CLIP-HEIGHT@  ( descriptor -- value )
    _USFSN-D.CLIP-HEIGHT @ ;
: USFSN-DESCRIPTOR-CLIP-WIDTH@  ( descriptor -- value )
    _USFSN-D.CLIP-WIDTH @ ;
: USFSN-DESCRIPTOR-Z@  ( descriptor -- value )
    _USFSN-D.Z @ ;
: USFSN-DESCRIPTOR-ENTRY-BYTES@  ( descriptor -- value )
    _USFSN-D.ENTRY-U @ ;
: USFSN-DESCRIPTOR-UTF8-BYTES@  ( descriptor -- value )
    _USFSN-D.UTF8-U @ ;
: USFSN-DESCRIPTOR-NATIVE  ( descriptor native-base -- field bytes )
    OVER USFSN-DESCRIPTOR-NATIVE-OFFSET@ +
    SWAP USFSN-DESCRIPTOR-ENTRY-BYTES@ ;

-1 1 RSHIFT CONSTANT _USFSN-SIGNED-MAX

: _USFSN-SIZED-BYTES  ( count stride -- bytes|0 )
    OVER 0< IF 2DROP 0 EXIT THEN
    OVER 0= IF 2DROP 0 EXIT THEN
    _USFSN-SIGNED-MAX OVER / 2 PICK U< IF 2DROP 0 EXIT THEN
    * ;

: USFSN-DESCRIPTOR-BANK-BYTES  ( descriptor-capacity -- bytes|0 )
    USFSN-DESCRIPTOR-SIZE _USFSN-SIZED-BYTES ;

8 CONSTANT USFSN-FROZEN-WORK-ENTRY-SIZE

: USFSN-FROZEN-WORK-BYTES  ( descriptor-count -- bytes|0 )
    DUP 0< IF DROP 0 EXIT THEN
    DUP 0= IF DROP 0 EXIT THEN
    USFSN-FROZEN-WORK-ENTRY-SIZE _USFSN-SIZED-BYTES ;

CREATE _USFSN-OWNED-START

VARIABLE _USFSN-DESCRIPTORS-A
VARIABLE _USFSN-DESCRIPTORS-U
VARIABLE _USFSN-DESCRIPTOR-CAP
VARIABLE _USFSN-NATIVE-A
VARIABLE _USFSN-NATIVE-U
VARIABLE _USFSN-RANGES-VALID

VARIABLE _USFSN-STATUS
VARIABLE _USFSN-COUNT
VARIABLE _USFSN-NATIVE-USED
VARIABLE _USFSN-DIRTY-DESCRIPTOR-U
VARIABLE _USFSN-DIRTY-NATIVE-U

VARIABLE _USFSN-V-INDEX
VARIABLE _USFSN-V-GENERATION
VARIABLE _USFSN-V-ROOT-KEY
VARIABLE _USFSN-V-RESOLVED-A
VARIABLE _USFSN-V-RESOLVED-U
VARIABLE _USFSN-V-DESCRIPTOR
VARIABLE _USFSN-V-ENTRY
VARIABLE _USFSN-V-ENTRY-U
VARIABLE _USFSN-V-NEXT-NATIVE
VARIABLE _USFSN-V-REMAINING
VARIABLE _USFSN-V-ORIGIN-ROW
VARIABLE _USFSN-V-ORIGIN-COLUMN
VARIABLE _USFSN-V-EXTENT-HEIGHT
VARIABLE _USFSN-V-EXTENT-WIDTH
VARIABLE _USFSN-V-ROW
VARIABLE _USFSN-V-COLUMN
VARIABLE _USFSN-V-HEIGHT
VARIABLE _USFSN-V-WIDTH
VARIABLE _USFSN-V-CLIP-ROW
VARIABLE _USFSN-V-CLIP-COLUMN
VARIABLE _USFSN-V-CLIP-HEIGHT
VARIABLE _USFSN-V-CLIP-WIDTH
VARIABLE _USFSN-V-Z

VARIABLE _USFSN-PRIOR-INDEX
VARIABLE _USFSN-PRIOR-GENERATION
VARIABLE _USFSN-PRIOR-ROOT
VARIABLE _USFSN-HAVE-PRIOR
VARIABLE _USFSN-OWNED-LIMIT

VARIABLE _USFSN-F-WORK-A
VARIABLE _USFSN-F-WORK-U
VARIABLE _USFSN-F-WORK-NEED
VARIABLE _USFSN-F-DESCRIPTORS-A
VARIABLE _USFSN-F-DESCRIPTORS-U
VARIABLE _USFSN-F-NATIVE-A
VARIABLE _USFSN-F-NATIVE-U
VARIABLE _USFSN-F-COUNT
VARIABLE _USFSN-F-I
VARIABLE _USFSN-F-J
VARIABLE _USFSN-F-VALUE
VARIABLE _USFSN-F-HEAP-ROOT
VARIABLE _USFSN-F-HEAP-END
VARIABLE _USFSN-F-HEAP-CHILD
VARIABLE _USFSN-F-HEAP-LARGEST
VARIABLE _USFSN-F-HEAP-A
VARIABLE _USFSN-F-HEAP-B
VARIABLE _USFSN-F-DESCRIPTOR
VARIABLE _USFSN-F-FIELD
VARIABLE _USFSN-F-FIELD-U
VARIABLE _USFSN-F-OFFSET
VARIABLE _USFSN-F-CURSOR
VARIABLE _USFSN-F-INDEX
VARIABLE _USFSN-F-GENERATION
VARIABLE _USFSN-F-RELATION
VARIABLE _USFSN-F-PRIOR-INDEX
VARIABLE _USFSN-F-PRIOR-GENERATION
VARIABLE _USFSN-F-PRIOR-RELATION
VARIABLE _USFSN-F-HAVE-PRIOR
VARIABLE _USFSN-F-RANGES-VALID

: _USFSN-ALIGNED?  ( address -- flag )  7 AND 0= ;

: _USFSN-OPTIONAL-SPAN?  ( address bytes -- flag )
    DUP 0< IF 2DROP 0 EXIT THEN
    DUP 0= IF DROP 0= EXIT THEN
    OVER 0< IF 2DROP 0 EXIT THEN
    OVER 0= IF 2DROP 0 EXIT THEN
    MSPAN-NONWRAPPING? ;

: _USFSN-DISJOINT?  ( a1 u1 a2 u2 -- flag )
    2 PICK 0= OVER 0= OR IF 2DROP 2DROP -1 EXIT THEN
    MSPAN-OVERLAP? 0= ;

: _USFSN-OWNED-DISJOINT?  ( address bytes -- flag )
    DUP 0= IF 2DROP -1 EXIT THEN
    _USFSN-OWNED-LIMIT @ DUP _USFSN-OWNED-START U< IF
        DROP 2DROP 0 EXIT
    THEN
    _USFSN-OWNED-START - >R
    2DUP _USFSN-OWNED-START R> MSPAN-OVERLAP? 0= NIP NIP ;

\ Pure preflight for owners that reserve snapshot banks inside larger arenas.
: USFSN-STORAGE-DISJOINT?  ( address bytes -- flag )
    2DUP _USFSN-OPTIONAL-SPAN? 0= IF 2DROP 0 EXIT THEN
    _USFSN-OWNED-DISJOINT? ;

\ Runs inside the outer resolved observation before the unified iterator.
\ The final seam includes hidden/direct/nested live widget authority.
: _USFSN-AUTHORITY-DISJOINT?  ( address bytes -- flag )
    DUP 0= IF 2DROP -1 EXIT THEN
    2DUP _USFSN-OWNED-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP USF-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP SFIELD-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP USCOL-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP UDG-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP DGF-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP _UTUI-STORAGE-DISJOINT-BODY? 0= IF 2DROP 0 EXIT THEN
    _UTUI-STATUS-FIELD-STORAGE-DISJOINT-OBSERVED?
    DUP USF-S-OK <> IF 2DROP 0 EXIT THEN
    DROP ;
CREATE _USFSN-PROOF-SPANS 2 MSPAN-SET-BYTES ALLOT

\ Collect the two caller spans for one enclosed authority proof.  Their
\ shapes are admitted first, and the prover skips empty optional spans.
: _USFSN-PROOF-SPANS?  ( -- flag )
    2 _USFSN-PROOF-SPANS MSPAN-SET-INIT MSPAN-SET-S-OK <> IF 0 EXIT THEN
    _USFSN-DESCRIPTORS-A @ _USFSN-DESCRIPTORS-U @
        _USFSN-PROOF-SPANS MSPAN-SET-PUSH MSPAN-SET-S-OK <> IF 0 EXIT THEN
    _USFSN-NATIVE-A @ _USFSN-NATIVE-U @ _USFSN-PROOF-SPANS MSPAN-SET-PUSH
        MSPAN-SET-S-OK = ;
\ Caller span shapes and mutual disjointness.  Authority is proved
\ separately, before the first live status-field visit.
: _USFSN-SHAPES?  ( -- flag )
    _USFSN-DESCRIPTORS-A @ _USFSN-DESCRIPTORS-U @
        _USFSN-OPTIONAL-SPAN? 0= IF 0 EXIT THEN
    _USFSN-DESCRIPTORS-U @ USFSN-DESCRIPTOR-SIZE MOD IF 0 EXIT THEN
    _USFSN-DESCRIPTORS-U @ IF
        _USFSN-DESCRIPTORS-A @ _USFSN-ALIGNED? 0= IF 0 EXIT THEN
    THEN
    _USFSN-NATIVE-A @ _USFSN-NATIVE-U @
        _USFSN-OPTIONAL-SPAN? 0= IF 0 EXIT THEN
    _USFSN-NATIVE-U @ IF
        _USFSN-NATIVE-A @ _USFSN-ALIGNED? 0= IF 0 EXIT THEN
    THEN
    _USFSN-DESCRIPTORS-A @ _USFSN-DESCRIPTORS-U @
        _USFSN-NATIVE-A @ _USFSN-NATIVE-U @ _USFSN-DISJOINT? ;
\ Each authority query walks the document's storage.  Clustered caller spans
\ need one enclosed query instead of one per span.
: _USFSN-AUTHORITY?  ( -- flag )
    _USFSN-PROOF-SPANS? 0= IF 0 EXIT THEN
    _USFSN-PROOF-SPANS ['] _USFSN-AUTHORITY-DISJOINT?
        MSPAN-SET-PROVE-DISJOINT? ;

: _USFSN-DESCRIPTOR-AT  ( ordinal -- descriptor )
    USFSN-DESCRIPTOR-SIZE * _USFSN-DESCRIPTORS-A @ + ;

: _USFSN-SET-CAPACITY  ( -- )
    _USFSN-STATUS @ USFSN-S-OK = IF
        USFSN-S-CAPACITY _USFSN-STATUS !
    THEN ;

: _USFSN-SET-UNAVAILABLE  ( -- )
    _USFSN-STATUS @ USFSN-S-OK = IF
        USFSN-S-UNAVAILABLE _USFSN-STATUS !
    THEN ;

: _USFSN-SET-INVALID  ( -- )
    USFSN-S-INVALID _USFSN-STATUS ! ;

: _USFSN-MAP-USF  ( status -- )
    DUP USF-S-OK = IF DROP EXIT THEN
    DUP USF-S-CAPACITY = IF DROP _USFSN-SET-CAPACITY EXIT THEN
    DUP USF-S-UNSUPPORTED = IF DROP _USFSN-SET-UNAVAILABLE EXIT THEN
    DROP _USFSN-SET-INVALID ;
: _USFSN-MAP-MOUNTED  ( status -- )
    DUP _UTUI-MC-S-OK = IF DROP EXIT THEN
    DUP _UTUI-MC-S-UNAVAILABLE = IF
        DROP _USFSN-SET-UNAVAILABLE
    ELSE
        DROP _USFSN-SET-INVALID
    THEN ;

: _USFSN-CLEAR-OUTPUT  ( -- )
    _USFSN-RANGES-VALID @ 0= IF EXIT THEN
    _USFSN-DIRTY-DESCRIPTOR-U @ ?DUP IF
        _USFSN-DESCRIPTORS-A @ SWAP 0 FILL
    THEN
    _USFSN-DIRTY-NATIVE-U @ ?DUP IF
        _USFSN-NATIVE-A @ SWAP 0 FILL
    THEN ;


: _USFSN-GENERATION?  ( generation -- flag )  -1 <> ;
\ =====================================================================
\  One canonical direct or mounted status-field visit
\ =====================================================================

: _USFSN-V-ARGS?  ( -- flag )
    _USFSN-V-INDEX @ 0< IF 0 EXIT THEN
    UIDL-ELEM-COUNT DUP 0> 0= IF DROP 0 EXIT THEN
    _USFSN-V-INDEX @ SWAP U< 0= IF 0 EXIT THEN
    _USFSN-V-GENERATION @ _USFSN-GENERATION? 0= IF 0 EXIT THEN
    _USFSN-V-ROOT-KEY @ 0= IF 0 EXIT THEN
    _USFSN-V-GENERATION @ 0= IF
        _USFSN-V-ROOT-KEY @ 1 <> IF 0 EXIT THEN
    THEN
    _USFSN-V-RESOLVED-U @ UTUI-RESOLVED-SIZE <> IF 0 EXIT THEN
    _USFSN-V-RESOLVED-A @ _USFSN-V-RESOLVED-U @
        UTUI-RESOLVED-VALID? ;

: _USFSN-V-ORDER?  ( -- flag )
    _USFSN-HAVE-PRIOR @ IF
        _USFSN-V-INDEX @ _USFSN-PRIOR-INDEX @ U< IF 0 EXIT THEN
        _USFSN-V-INDEX @ _USFSN-PRIOR-INDEX @ = IF
            _USFSN-PRIOR-ROOT @ _USFSN-V-ROOT-KEY @ U< 0= IF
                0 EXIT
            THEN
            _USFSN-V-GENERATION @ _USFSN-PRIOR-GENERATION @ <> IF
                0 EXIT
            THEN
        THEN
    THEN
    _USFSN-V-INDEX @ _USFSN-PRIOR-INDEX !
    _USFSN-V-GENERATION @ _USFSN-PRIOR-GENERATION !
    _USFSN-V-ROOT-KEY @ _USFSN-PRIOR-ROOT !
    -1 _USFSN-HAVE-PRIOR !
    -1 ;

: _USFSN-V-TAKE-GEOMETRY?  ( geometry-fields status -- flag )
    DUP USF-S-OK <> IF
        >R 2DROP 2DROP 2DROP 2DROP R> _USFSN-MAP-USF 0 EXIT
    THEN
    DROP
    _USFSN-V-CLIP-WIDTH ! _USFSN-V-CLIP-HEIGHT !
    _USFSN-V-CLIP-COLUMN ! _USFSN-V-CLIP-ROW !
    _USFSN-V-EXTENT-WIDTH ! _USFSN-V-EXTENT-HEIGHT !
    _USFSN-V-ORIGIN-COLUMN ! _USFSN-V-ORIGIN-ROW !
    -1 ;

: _USFSN-V-GEOMETRY?  ( -- flag )
    _UTUI-STATUS-FIELD-GEOMETRY _USFSN-V-TAKE-GEOMETRY? 0= IF 0 EXIT THEN
    _USFSN-V-EXTENT-HEIGHT @ 1 <>
    _USFSN-V-EXTENT-WIDTH @ 0> 0= OR
    _USFSN-V-ORIGIN-ROW @ 0< OR _USFSN-V-ORIGIN-COLUMN @ 0< OR
    _USFSN-V-CLIP-ROW @ _USFSN-V-ORIGIN-ROW @ <> OR
    _USFSN-V-CLIP-COLUMN @ _USFSN-V-ORIGIN-COLUMN @ <> OR
    _USFSN-V-CLIP-HEIGHT @ 1 <> OR
    _USFSN-V-CLIP-WIDTH @ _USFSN-V-EXTENT-WIDTH @ <> OR IF
        _USFSN-SET-UNAVAILABLE 0 EXIT
    THEN
    -1 ;
: _USFSN-V-PRODUCE  ( destination capacity -- bytes status )
    _UTUI-STATUS-FIELD-CAPTURE-PREFLIGHTED ;
: _USFSN-IADD-NONNEG?  ( signed nonnegative -- sum flag )
    DUP 0< IF 2DROP 0 0 EXIT THEN
    >R
    DUP _USFSN-SIGNED-MAX R@ - > IF
        DROP R> DROP 0 0 EXIT
    THEN
    R> + -1 ;


: _USFSN-V-ROOT-FIT?  ( -- flag )
    _USFSN-V-ENTRY @ USF-WIDTH@ DUP _USFSN-V-WIDTH !
        _USFSN-V-EXTENT-WIDTH @ <> IF 0 EXIT THEN
    1 _USFSN-V-HEIGHT !
    _USFSN-V-ORIGIN-ROW @ DUP _USFSN-V-ROW !
        1 _USFSN-IADD-NONNEG? 0= IF DROP 0 EXIT THEN DROP
    _USFSN-V-ORIGIN-COLUMN @ DUP _USFSN-V-COLUMN !
        _USFSN-V-WIDTH @ _USFSN-IADD-NONNEG? 0= IF DROP 0 EXIT THEN DROP
    _USFSN-V-RESOLVED-A @ 64 + @ DUP _USFSN-V-Z !
        255 U> IF 0 EXIT THEN
    -1 ;
: _USFSN-V-VALIDATE?  ( -- flag )
    _USFSN-V-ENTRY @ _USFSN-V-ENTRY-U @ USF-VALIDATE
    DUP USF-S-OK <> IF _USFSN-MAP-USF 0 EXIT THEN DROP
    _USFSN-V-ENTRY @ USF-FLAGS@ USF-F-VISIBLE AND 0= IF
        _USFSN-SET-UNAVAILABLE 0 EXIT
    THEN
    _USFSN-V-ENTRY @ USF-BYTES@ _USFSN-V-ENTRY-U @ <> IF
        _USFSN-SET-INVALID 0 EXIT
    THEN
    _USFSN-V-ROOT-FIT? 0= IF _USFSN-SET-INVALID 0 EXIT THEN
    -1 ;
: _USFSN-V-CAPACITY?  ( -- flag )
    _USFSN-COUNT @ _USFSN-DESCRIPTOR-CAP @ U< 0= IF
        _USFSN-SET-CAPACITY 0 EXIT
    THEN
    _USFSN-COUNT @ _USFSN-DESCRIPTOR-AT _USFSN-V-DESCRIPTOR !
    _USFSN-COUNT @ 1+ USFSN-DESCRIPTOR-SIZE *
        _USFSN-DIRTY-DESCRIPTOR-U !
    _USFSN-V-DESCRIPTOR @ USFSN-DESCRIPTOR-SIZE 0 FILL
    -1 ;

: _USFSN-V-WRITE-METADATA  ( -- )
    USFSN-SOURCE-UIDL _USFSN-V-DESCRIPTOR @ _USFSN-D.SOURCE !
    _USFSN-V-INDEX @ _USFSN-V-DESCRIPTOR @ _USFSN-D.INDEX !
    _USFSN-V-GENERATION @
        _USFSN-V-DESCRIPTOR @ _USFSN-D.GENERATION !
    _USFSN-V-ROOT-KEY @
        _USFSN-V-DESCRIPTOR @ _USFSN-D.ROOT-KEY !
    _USFSN-NATIVE-USED @ _USFSN-V-DESCRIPTOR @ _USFSN-D.NATIVE-O !
    _USFSN-V-ROW @ _USFSN-V-DESCRIPTOR @ _USFSN-D.ROW !
    _USFSN-V-COLUMN @ _USFSN-V-DESCRIPTOR @ _USFSN-D.COLUMN !
    _USFSN-V-HEIGHT @ _USFSN-V-DESCRIPTOR @ _USFSN-D.HEIGHT !
    _USFSN-V-WIDTH @ _USFSN-V-DESCRIPTOR @ _USFSN-D.WIDTH !
    _USFSN-V-CLIP-ROW @ _USFSN-V-DESCRIPTOR @ _USFSN-D.CLIP-ROW !
    _USFSN-V-CLIP-COLUMN @
        _USFSN-V-DESCRIPTOR @ _USFSN-D.CLIP-COLUMN !
    _USFSN-V-CLIP-HEIGHT @
        _USFSN-V-DESCRIPTOR @ _USFSN-D.CLIP-HEIGHT !
    _USFSN-V-CLIP-WIDTH @
        _USFSN-V-DESCRIPTOR @ _USFSN-D.CLIP-WIDTH !
    _USFSN-V-Z @ _USFSN-V-DESCRIPTOR @ _USFSN-D.Z !
    _USFSN-V-ENTRY-U @ _USFSN-V-DESCRIPTOR @ _USFSN-D.ENTRY-U !
    _USFSN-V-ENTRY @ USF-LABEL-BYTES@
    _USFSN-V-ENTRY @ USF-VALUE-BYTES@ +
        _USFSN-V-DESCRIPTOR @ _USFSN-D.UTF8-U ! ;

: _USFSN-V-ROLLBACK-CLIPPED  ( -- )
    _USFSN-V-ENTRY @ _USFSN-V-ENTRY-U @ 0 FILL
    _USFSN-V-DESCRIPTOR @ USFSN-DESCRIPTOR-SIZE 0 FILL
    _USFSN-NATIVE-USED @ _USFSN-DIRTY-NATIVE-U !
    _USFSN-COUNT @ USFSN-DESCRIPTOR-SIZE *
        _USFSN-DIRTY-DESCRIPTOR-U ! ;

\ _USFSN-V-REFUSED ( -- )
\   A root's own widget could not publish it.  Leave that root out, so CELL
\   draws its area and the snapshot keeps its other roots, and keep nothing
\   of it: its entry bytes and descriptor are cleared as a fully clipped
\   root's are.  A capacity refusal stays the snapshot's.
: _USFSN-V-REFUSED  ( -- )
    _USFSN-STATUS @ DUP USFSN-S-UNAVAILABLE = SWAP USFSN-S-INVALID = OR
        0= IF EXIT THEN
    _USFSN-V-DESCRIPTOR @ IF _USFSN-V-ROLLBACK-CLIPPED THEN
    USFSN-S-OK _USFSN-STATUS ! ;

: _USFSN-V-CAPTURE  ( -- )
    _USFSN-V-CLIP-HEIGHT @ 0= _USFSN-V-CLIP-WIDTH @ 0= OR IF
        EXIT
    THEN
    _USFSN-V-CAPACITY? 0= IF EXIT THEN
    _USFSN-NATIVE-USED @ _USFSN-NATIVE-U @ U> IF
        _USFSN-SET-INVALID EXIT
    THEN
    _USFSN-NATIVE-U @ _USFSN-NATIVE-USED @ - DUP 0= IF
        DROP _USFSN-SET-CAPACITY EXIT
    THEN
    _USFSN-V-REMAINING !
    0 _USFSN-V-ENTRY-U !

    \ Measure through the exact same current widget before touching
    \ the native bank.  The captured byte count must remain identical.
    0 0 _USFSN-V-PRODUCE
    DUP USF-S-OK <> IF
        >R DROP R> _USFSN-MAP-USF _USFSN-V-REFUSED EXIT
    THEN
    DROP
    DUP 0> 0= OVER 7 AND OR IF
        DROP _USFSN-SET-INVALID _USFSN-V-REFUSED EXIT
    THEN
    DUP _USFSN-V-REMAINING @ U> IF
        DROP _USFSN-SET-CAPACITY EXIT
    THEN
    _USFSN-V-ENTRY-U !

    _USFSN-NATIVE-A @ _USFSN-NATIVE-USED @ + _USFSN-V-ENTRY !
    _USFSN-NATIVE-USED @ _USFSN-V-ENTRY-U @ + DUP
        _USFSN-V-NEXT-NATIVE ! _USFSN-DIRTY-NATIVE-U !
    _USFSN-V-ENTRY @ _USFSN-V-ENTRY-U @ _USFSN-V-PRODUCE
    DUP USF-S-OK <> IF
        >R DROP R> _USFSN-MAP-USF _USFSN-V-REFUSED EXIT
    THEN
    DROP _USFSN-V-ENTRY-U @ <> IF
        _USFSN-SET-INVALID _USFSN-V-REFUSED EXIT
    THEN

    _USFSN-V-VALIDATE? 0= IF _USFSN-V-REFUSED EXIT THEN
    _USFSN-V-CLIP-HEIGHT @ 0= _USFSN-V-CLIP-WIDTH @ 0= OR IF
        _USFSN-V-ROLLBACK-CLIPPED EXIT
    THEN
    _USFSN-V-WRITE-METADATA
    _USFSN-V-NEXT-NATIVE @ _USFSN-NATIVE-USED !
    1 _USFSN-COUNT +! ;

: _USFSN-VISITOR
    ( source-index source-generation root-key resolved-a resolved-u -- )
    _USFSN-V-RESOLVED-U ! _USFSN-V-RESOLVED-A !
    _USFSN-V-ROOT-KEY ! _USFSN-V-GENERATION ! _USFSN-V-INDEX !
    _USFSN-STATUS @ USFSN-S-OK <> IF EXIT THEN
    _USFSN-V-ARGS? 0= IF _USFSN-SET-INVALID EXIT THEN
    _USFSN-V-ORDER? 0= IF _USFSN-SET-INVALID EXIT THEN
    0 _USFSN-V-DESCRIPTOR ! 0 _USFSN-V-ENTRY-U !
    _USFSN-V-GEOMETRY? 0= IF _USFSN-V-REFUSED EXIT THEN
    _USFSN-V-CAPTURE ;

\ =====================================================================
\  Capture orchestration
\ =====================================================================

: _USFSN-FAIL-RESULT  ( -- 0 0 status )
    _USFSN-CLEAR-OUTPUT
    0 0 _USFSN-STATUS @ ;

: _USFSN-CAPTURE-BODY  ( -- descriptor-count native-used status )
    USFSN-S-OK _USFSN-STATUS !
    0 _USFSN-COUNT ! 0 _USFSN-NATIVE-USED !
    0 _USFSN-DIRTY-DESCRIPTOR-U ! 0 _USFSN-DIRTY-NATIVE-U !
    0 _USFSN-HAVE-PRIOR !
    ['] _USFSN-VISITOR
        _UTUI-STATUS-FIELD-EACH-PREFLIGHTED
        _USFSN-MAP-MOUNTED
    _USFSN-STATUS @ USFSN-S-OK <> IF _USFSN-FAIL-RESULT EXIT THEN
    _USFSN-COUNT @ _USFSN-NATIVE-USED @ USFSN-S-OK ;

: _USFSN-CAPTURE-OBSERVED  ( -- descriptor-count native-used status )
    USFSN-S-OK _USFSN-STATUS !
    0 _USFSN-RANGES-VALID !
    0 _USFSN-DIRTY-DESCRIPTOR-U ! 0 _USFSN-DIRTY-NATIVE-U !
    _USFSN-SHAPES? 0= IF 0 0 USFSN-S-INVALID EXIT THEN
    _USFSN-AUTHORITY? 0= IF 0 0 USFSN-S-INVALID EXIT THEN
    _USFSN-DESCRIPTORS-U @ USFSN-DESCRIPTOR-SIZE /
        _USFSN-DESCRIPTOR-CAP !
    -1 _USFSN-RANGES-VALID !
    _USFSN-CAPTURE-BODY ;

: _USFSN-CAPTURE-OBSERVED-CATCH
    ( -- descriptor-count native-used status )
    ['] _USFSN-CAPTURE-OBSERVED CATCH ?DUP IF
        DROP _USFSN-SET-INVALID _USFSN-FAIL-RESULT
    THEN ;

: _USFSN-CAPTURE-CALL  ( -- descriptor-count native-used status )
    ['] _USFSN-CAPTURE-OBSERVED-CATCH UTUI-RESOLVED-OBSERVE ;

: _USFSN-SCRUB  ( -- )
    0 _USFSN-DESCRIPTORS-A ! 0 _USFSN-DESCRIPTORS-U !
    0 _USFSN-DESCRIPTOR-CAP !
    0 _USFSN-NATIVE-A ! 0 _USFSN-NATIVE-U !
    0 _USFSN-RANGES-VALID !
    0 _USFSN-STATUS ! 0 _USFSN-COUNT ! 0 _USFSN-NATIVE-USED !
    0 _USFSN-DIRTY-DESCRIPTOR-U ! 0 _USFSN-DIRTY-NATIVE-U !
    0 _USFSN-V-INDEX ! 0 _USFSN-V-GENERATION !
    0 _USFSN-V-ROOT-KEY !
    0 _USFSN-V-RESOLVED-A ! 0 _USFSN-V-RESOLVED-U !
    0 _USFSN-V-DESCRIPTOR ! 0 _USFSN-V-ENTRY !
    0 _USFSN-V-ENTRY-U ! 0 _USFSN-V-NEXT-NATIVE !
    0 _USFSN-V-REMAINING !
    0 _USFSN-V-ORIGIN-ROW ! 0 _USFSN-V-ORIGIN-COLUMN !
    0 _USFSN-V-EXTENT-HEIGHT ! 0 _USFSN-V-EXTENT-WIDTH !
    0 _USFSN-V-ROW ! 0 _USFSN-V-COLUMN !
    0 _USFSN-V-HEIGHT ! 0 _USFSN-V-WIDTH !
    0 _USFSN-V-CLIP-ROW ! 0 _USFSN-V-CLIP-COLUMN !
    0 _USFSN-V-CLIP-HEIGHT ! 0 _USFSN-V-CLIP-WIDTH !
    0 _USFSN-V-Z !
    0 _USFSN-PRIOR-INDEX ! 0 _USFSN-PRIOR-GENERATION !
    0 _USFSN-PRIOR-ROOT ! 0 _USFSN-HAVE-PRIOR !
    _USFSN-PROOF-SPANS 2 MSPAN-SET-BYTES 0 FILL ;

: USFSN-CAPTURE
    ( descriptors-a descriptors-u native-a native-u -- descriptor-count native-used status )
    3 PICK 3 PICK USFSN-STORAGE-DISJOINT? 0= IF
        2DROP 2DROP 0 0 USFSN-S-INVALID EXIT
    THEN
    2DUP USFSN-STORAGE-DISJOINT? 0= IF
        2DROP 2DROP 0 0 USFSN-S-INVALID EXIT
    THEN
    _USFSN-NATIVE-U ! _USFSN-NATIVE-A !
    _USFSN-DESCRIPTORS-U ! _USFSN-DESCRIPTORS-A !
    0 _USFSN-RANGES-VALID !
    ['] _USFSN-CAPTURE-CALL CATCH ?DUP IF
        DROP _USFSN-SET-INVALID _USFSN-FAIL-RESULT
    THEN
    _USFSN-SCRUB ;

\ =====================================================================
\  Read-only validation of one frozen per-document bank
\ =====================================================================

: _USFSN-F-UADD?  ( a b -- sum flag )
    OVER + DUP ROT U< 0= ;

: _USFSN-F-WORK-AT  ( ordinal -- address )
    USFSN-FROZEN-WORK-ENTRY-SIZE * _USFSN-F-WORK-A @ + ;

: _USFSN-F-DESCRIPTOR-AT  ( ordinal -- descriptor )
    USFSN-DESCRIPTOR-SIZE * _USFSN-F-DESCRIPTORS-A @ + ;

: _USFSN-F-CLEAR-SCRATCH  ( -- )
    _USFSN-F-RANGES-VALID @ IF
        _USFSN-F-WORK-NEED @ ?DUP IF
            _USFSN-F-WORK-A @ SWAP 0 FILL
        THEN
    THEN ;

: _USFSN-F-SCRUB  ( -- )
    0 _USFSN-F-WORK-A ! 0 _USFSN-F-WORK-U !
    0 _USFSN-F-WORK-NEED !
    0 _USFSN-F-DESCRIPTORS-A ! 0 _USFSN-F-DESCRIPTORS-U !
    0 _USFSN-F-NATIVE-A ! 0 _USFSN-F-NATIVE-U !
    0 _USFSN-F-COUNT ! 0 _USFSN-F-I ! 0 _USFSN-F-J !
    0 _USFSN-F-VALUE ! 0 _USFSN-F-DESCRIPTOR !
    0 _USFSN-F-HEAP-ROOT ! 0 _USFSN-F-HEAP-END !
    0 _USFSN-F-HEAP-CHILD ! 0 _USFSN-F-HEAP-LARGEST !
    0 _USFSN-F-HEAP-A ! 0 _USFSN-F-HEAP-B !
    0 _USFSN-F-FIELD ! 0 _USFSN-F-FIELD-U !
    0 _USFSN-F-OFFSET ! 0 _USFSN-F-CURSOR !
    0 _USFSN-F-INDEX ! 0 _USFSN-F-GENERATION !
    0 _USFSN-F-RELATION ! 0 _USFSN-F-PRIOR-INDEX !
    0 _USFSN-F-PRIOR-GENERATION ! 0 _USFSN-F-PRIOR-RELATION !
    0 _USFSN-F-HAVE-PRIOR !
    0 _USFSN-F-RANGES-VALID ! ;

: _USFSN-F-AUTHORITY-DISJOINT?  ( address bytes -- flag )
    DUP 0= IF 2DROP -1 EXIT THEN
    2DUP _USFSN-OWNED-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP USCOL-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP UDG-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP DGF-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    2DUP SFIELD-STORAGE-DISJOINT? 0= IF 2DROP 0 EXIT THEN
    USF-STORAGE-DISJOINT? ;

: _USFSN-F-RANGES  ( -- status )
    _USFSN-F-DESCRIPTORS-A @ _USFSN-F-DESCRIPTORS-U @
        _USFSN-OPTIONAL-SPAN? 0= IF USFSN-S-INVALID EXIT THEN
    _USFSN-F-DESCRIPTORS-U @ USFSN-DESCRIPTOR-SIZE MOD IF
        USFSN-S-INVALID EXIT
    THEN
    _USFSN-F-NATIVE-A @ _USFSN-F-NATIVE-U @
        _USFSN-OPTIONAL-SPAN? 0= IF USFSN-S-INVALID EXIT THEN
    _USFSN-F-DESCRIPTORS-U @ 0=
        _USFSN-F-NATIVE-U @ 0= <> IF USFSN-S-INVALID EXIT THEN
    _USFSN-F-DESCRIPTORS-U @ IF
        _USFSN-F-DESCRIPTORS-A @ _USFSN-ALIGNED? 0= IF
            USFSN-S-INVALID EXIT
        THEN
        _USFSN-F-NATIVE-A @ _USFSN-ALIGNED? 0= IF
            USFSN-S-INVALID EXIT
        THEN
        _USFSN-F-NATIVE-U @ 7 AND IF USFSN-S-INVALID EXIT THEN
    THEN

    _USFSN-F-DESCRIPTORS-U @ USFSN-DESCRIPTOR-SIZE /
        DUP _USFSN-F-COUNT !
    USFSN-FROZEN-WORK-BYTES DUP _USFSN-F-WORK-NEED !
    _USFSN-F-COUNT @ IF
        DUP 0= IF DROP USFSN-S-INVALID EXIT THEN
    THEN DROP
    _USFSN-F-WORK-A @ _USFSN-F-WORK-U @
        _USFSN-OPTIONAL-SPAN? 0= IF USFSN-S-INVALID EXIT THEN
    _USFSN-F-WORK-U @ IF
        _USFSN-F-WORK-A @ _USFSN-ALIGNED? 0= IF
            USFSN-S-INVALID EXIT
        THEN
    THEN
    _USFSN-F-WORK-U @ _USFSN-F-WORK-NEED @ U< IF
        USFSN-S-CAPACITY EXIT
    THEN

    _USFSN-F-WORK-A @ _USFSN-F-WORK-U @
        _USFSN-F-AUTHORITY-DISJOINT? 0= IF USFSN-S-INVALID EXIT THEN
    _USFSN-F-DESCRIPTORS-A @ _USFSN-F-DESCRIPTORS-U @
        _USFSN-F-AUTHORITY-DISJOINT? 0= IF USFSN-S-INVALID EXIT THEN
    _USFSN-F-NATIVE-A @ _USFSN-F-NATIVE-U @
        _USFSN-F-AUTHORITY-DISJOINT? 0= IF USFSN-S-INVALID EXIT THEN

    _USFSN-F-WORK-A @ _USFSN-F-WORK-U @
        _USFSN-F-DESCRIPTORS-A @ _USFSN-F-DESCRIPTORS-U @
        _USFSN-DISJOINT? 0= IF USFSN-S-INVALID EXIT THEN
    _USFSN-F-WORK-A @ _USFSN-F-WORK-U @
        _USFSN-F-NATIVE-A @ _USFSN-F-NATIVE-U @
        _USFSN-DISJOINT? 0= IF USFSN-S-INVALID EXIT THEN
    _USFSN-F-DESCRIPTORS-A @ _USFSN-F-DESCRIPTORS-U @
        _USFSN-F-NATIVE-A @ _USFSN-F-NATIVE-U @
        _USFSN-DISJOINT? 0= IF USFSN-S-INVALID EXIT THEN

    -1 _USFSN-F-RANGES-VALID !
    _USFSN-F-CLEAR-SCRATCH
    USFSN-S-OK ;

: _USFSN-F-ORDER?  ( -- flag )
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-SOURCE@
        USFSN-SOURCE-UIDL <> IF 0 EXIT THEN
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-SOURCE-INDEX@
        DUP 0< IF DROP 0 EXIT THEN _USFSN-F-INDEX !
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-SOURCE-GENERATION@
        DUP _USFSN-GENERATION? 0= IF DROP 0 EXIT THEN
        _USFSN-F-GENERATION !
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-ROOT-KEY@
        DUP 0= IF DROP 0 EXIT THEN _USFSN-F-RELATION !
    _USFSN-F-GENERATION @ 0= IF
        _USFSN-F-RELATION @ 1 <> IF 0 EXIT THEN
    THEN
    _USFSN-F-HAVE-PRIOR @ IF
        _USFSN-F-INDEX @ _USFSN-F-PRIOR-INDEX @ U< IF 0 EXIT THEN
        _USFSN-F-INDEX @ _USFSN-F-PRIOR-INDEX @ = IF
            _USFSN-F-PRIOR-RELATION @ _USFSN-F-RELATION @
                U< 0= IF 0 EXIT THEN
            _USFSN-F-GENERATION @ _USFSN-F-PRIOR-GENERATION @
                <> IF 0 EXIT THEN
        THEN
    THEN
    _USFSN-F-INDEX @ _USFSN-F-PRIOR-INDEX !
    _USFSN-F-GENERATION @ _USFSN-F-PRIOR-GENERATION !
    _USFSN-F-RELATION @ _USFSN-F-PRIOR-RELATION !
    -1 _USFSN-F-HAVE-PRIOR !
    -1 ;

: _USFSN-F-GEOMETRY?  ( -- flag )
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-HEIGHT@ 1 <> IF 0 EXIT THEN
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-WIDTH@
        _USFSN-F-FIELD @ USF-WIDTH@ <> IF 0 EXIT THEN
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-ROW@ DUP 0< IF
        DROP 0 EXIT
    THEN
    1 _USFSN-IADD-NONNEG? 0= IF DROP 0 EXIT THEN DROP
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-COLUMN@ DUP 0< IF
        DROP 0 EXIT
    THEN
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-WIDTH@
        _USFSN-IADD-NONNEG? 0= IF DROP 0 EXIT THEN DROP
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-CLIP-ROW@
        _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-ROW@ <> IF 0 EXIT THEN
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-CLIP-COLUMN@
        _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-COLUMN@ <> IF 0 EXIT THEN
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-CLIP-HEIGHT@ 1 <> IF 0 EXIT THEN
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-CLIP-WIDTH@
        _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-WIDTH@ <> IF 0 EXIT THEN
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-Z@ 255 U> IF 0 EXIT THEN
    -1 ;
: _USFSN-F-ENTRY?  ( -- flag )
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-NATIVE-OFFSET@
        DUP 0< IF DROP 0 EXIT THEN
        DUP 7 AND IF DROP 0 EXIT THEN
        DUP _USFSN-F-OFFSET !
    _USFSN-F-NATIVE-U @ U> IF 0 EXIT THEN
    _USFSN-F-NATIVE-U @ _USFSN-F-OFFSET @ -
        USF-HEADER-SIZE U< IF 0 EXIT THEN
    _USFSN-F-NATIVE-A @ _USFSN-F-OFFSET @ +
        DUP _USFSN-F-FIELD !
    USF-BYTES@ DUP _USFSN-F-FIELD-U !
    DUP USF-HEADER-SIZE U< OVER 7 AND OR IF DROP 0 EXIT THEN
    _USFSN-F-NATIVE-U @ _USFSN-F-OFFSET @ - U> IF 0 EXIT THEN
    _USFSN-F-FIELD @ _USFSN-F-FIELD-U @ USF-VALIDATE
        USF-S-OK <> IF 0 EXIT THEN
    _USFSN-F-FIELD @ USF-FLAGS@ USF-F-VISIBLE AND 0= IF 0 EXIT THEN
    _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-ENTRY-BYTES@
        _USFSN-F-FIELD-U @ <> IF 0 EXIT THEN
    _USFSN-F-FIELD @ USF-LABEL-BYTES@
    _USFSN-F-FIELD @ USF-VALUE-BYTES@ +
        _USFSN-F-DESCRIPTOR @ USFSN-DESCRIPTOR-UTF8-BYTES@ <> IF 0 EXIT THEN
    _USFSN-F-GEOMETRY? 0= IF 0 EXIT THEN
    _USFSN-F-OFFSET @ _USFSN-F-I @ _USFSN-F-WORK-AT !
    -1 ;
: _USFSN-F-SWAP-OFFSETS  ( ordinal-a ordinal-b -- )
    _USFSN-F-HEAP-B ! _USFSN-F-HEAP-A !
    _USFSN-F-HEAP-A @ _USFSN-F-WORK-AT @ _USFSN-F-VALUE !
    _USFSN-F-HEAP-B @ _USFSN-F-WORK-AT @
        _USFSN-F-HEAP-A @ _USFSN-F-WORK-AT !
    _USFSN-F-VALUE @ _USFSN-F-HEAP-B @ _USFSN-F-WORK-AT ! ;

\ Restore one unsigned max-heap below the exclusive END ordinal.  The
\ caller-bounded ledger makes this O(n log n) at the configured ceiling.
: _USFSN-F-SIFT-DOWN  ( root end -- )
    _USFSN-F-HEAP-END ! _USFSN-F-HEAP-ROOT !
    BEGIN
        _USFSN-F-HEAP-ROOT @ 2 * 1+ DUP _USFSN-F-HEAP-CHILD !
        _USFSN-F-HEAP-END @ U<
    WHILE
        _USFSN-F-HEAP-ROOT @ _USFSN-F-HEAP-LARGEST !
        _USFSN-F-HEAP-LARGEST @ _USFSN-F-WORK-AT @
        _USFSN-F-HEAP-CHILD @ _USFSN-F-WORK-AT @ U< IF
            _USFSN-F-HEAP-CHILD @ _USFSN-F-HEAP-LARGEST !
        THEN
        _USFSN-F-HEAP-CHILD @ 1+ DUP _USFSN-F-HEAP-CHILD !
        _USFSN-F-HEAP-END @ U< IF
            _USFSN-F-HEAP-LARGEST @ _USFSN-F-WORK-AT @
            _USFSN-F-HEAP-CHILD @ _USFSN-F-WORK-AT @ U< IF
                _USFSN-F-HEAP-CHILD @ _USFSN-F-HEAP-LARGEST !
            THEN
        THEN
        _USFSN-F-HEAP-LARGEST @ _USFSN-F-HEAP-ROOT @ = IF EXIT THEN
        _USFSN-F-HEAP-ROOT @ _USFSN-F-HEAP-LARGEST @
            _USFSN-F-SWAP-OFFSETS
        _USFSN-F-HEAP-LARGEST @ _USFSN-F-HEAP-ROOT !
    REPEAT ;

: _USFSN-F-SORT-OFFSETS  ( -- )
    _USFSN-F-COUNT @ 2 / _USFSN-F-I !
    BEGIN _USFSN-F-I @ 0> WHILE
        -1 _USFSN-F-I +!
        _USFSN-F-I @ _USFSN-F-COUNT @ _USFSN-F-SIFT-DOWN
    REPEAT
    _USFSN-F-COUNT @ _USFSN-F-J !
    BEGIN _USFSN-F-J @ 1 > WHILE
        -1 _USFSN-F-J +!
        0 _USFSN-F-J @ _USFSN-F-SWAP-OFFSETS
        0 _USFSN-F-J @ _USFSN-F-SIFT-DOWN
    REPEAT ;

: _USFSN-F-COVERAGE?  ( -- flag )
    0 _USFSN-F-CURSOR ! 0 _USFSN-F-I !
    BEGIN _USFSN-F-I @ _USFSN-F-COUNT @ U< WHILE
        _USFSN-F-I @ _USFSN-F-WORK-AT @ DUP _USFSN-F-OFFSET !
        _USFSN-F-CURSOR @ <> IF 0 EXIT THEN
        _USFSN-F-OFFSET @ _USFSN-F-NATIVE-U @ U> IF 0 EXIT THEN
        _USFSN-F-NATIVE-U @ _USFSN-F-OFFSET @ -
            USF-HEADER-SIZE U< IF 0 EXIT THEN
        _USFSN-F-NATIVE-A @ _USFSN-F-OFFSET @ + USF-BYTES@
            DUP USF-HEADER-SIZE U< OVER 7 AND OR IF DROP 0 EXIT THEN
        _USFSN-F-CURSOR @ SWAP _USFSN-F-UADD?
            0= IF DROP 0 EXIT THEN
        DUP _USFSN-F-NATIVE-U @ U> IF DROP 0 EXIT THEN
            _USFSN-F-CURSOR !
        1 _USFSN-F-I +!
    REPEAT
    _USFSN-F-CURSOR @ _USFSN-F-NATIVE-U @ = ;

: _USFSN-F-VALIDATE-BODY  ( -- status )
    _USFSN-F-RANGES DUP USFSN-S-OK <> IF EXIT THEN DROP
    _USFSN-F-COUNT @ 0= IF USFSN-S-OK EXIT THEN
    0 _USFSN-F-PRIOR-INDEX ! 0 _USFSN-F-PRIOR-GENERATION !
    0 _USFSN-F-PRIOR-RELATION ! 0 _USFSN-F-HAVE-PRIOR !
    0 _USFSN-F-I !
    BEGIN _USFSN-F-I @ _USFSN-F-COUNT @ U< WHILE
        _USFSN-F-I @ _USFSN-F-DESCRIPTOR-AT
            _USFSN-F-DESCRIPTOR !
        _USFSN-F-ORDER? 0= IF USFSN-S-INVALID EXIT THEN
        _USFSN-F-ENTRY? 0= IF USFSN-S-INVALID EXIT THEN
        1 _USFSN-F-I +!
    REPEAT
    _USFSN-F-SORT-OFFSETS
    _USFSN-F-COVERAGE? 0= IF USFSN-S-INVALID EXIT THEN
    USFSN-S-OK ;

: _USFSN-F-VALIDATE-CALL  ( -- status )
    ['] _USFSN-F-VALIDATE-BODY CATCH ?DUP IF
        DROP USFSN-S-INVALID
    THEN
    _USFSN-F-CLEAR-SCRATCH
    _USFSN-F-SCRUB ;

: USFSN-FROZEN-VALIDATE
    ( offset-work-a offset-work-u descriptors-a descriptors-u native-a native-u -- status )
    5 PICK 5 PICK USFSN-STORAGE-DISJOINT? 0= IF
        2DROP 2DROP 2DROP USFSN-S-INVALID EXIT
    THEN
    3 PICK 3 PICK USFSN-STORAGE-DISJOINT? 0= IF
        2DROP 2DROP 2DROP USFSN-S-INVALID EXIT
    THEN
    2DUP USFSN-STORAGE-DISJOINT? 0= IF
        2DROP 2DROP 2DROP USFSN-S-INVALID EXIT
    THEN
    _USFSN-F-NATIVE-U ! _USFSN-F-NATIVE-A !
    _USFSN-F-DESCRIPTORS-U ! _USFSN-F-DESCRIPTORS-A !
    _USFSN-F-WORK-U ! _USFSN-F-WORK-A !
    0 _USFSN-F-WORK-NEED ! 0 _USFSN-F-RANGES-VALID !
    ['] _USFSN-F-VALIDATE-CALL CATCH ?DUP IF
        DROP
        _USFSN-F-CLEAR-SCRATCH
        _USFSN-F-SCRUB
        USFSN-S-INVALID
    THEN ;

CREATE _USFSN-OWNED-END
_USFSN-OWNED-END _USFSN-OWNED-LIMIT !
