\ =====================================================================
\ worlds.f - deterministic Worlds vertical-slice applet
\ =====================================================================

PROVIDED akashic-tui-worlds

REQUIRE ../../widgets/text-grid.f
REQUIRE ../../app-desc.f
REQUIRE ../../app-shell.f
REQUIRE ../../uidl-tui.f
REQUIRE ../../draw.f
REQUIRE ../../region.f
REQUIRE ../../keys.f
REQUIRE ../../widget.f
REQUIRE ../../../runtime/state-layout.f
REQUIRE ../../../interop/endpoint.f
REQUIRE ../../../utils/fmt.f
REQUIRE run.f

64 CONSTANT _WORLD-DEMO-HORIZON
250 CONSTANT _WORLD-AUTO-INTERVAL-MS

\ The ordinary Worlds view has always shown the four most recent canonical
\ transitions.  Preserve that genuine visible limit while giving the journal
\ one renderer-neutral model shared by CELL drawing and rich observation.
 4 CONSTANT _WORLD-JOURNAL-RECORD-ROWS
 5 CONSTANT _WORLD-JOURNAL-ROWS
 4 CONSTANT _WORLD-JOURNAL-COLUMNS
 5 CONSTANT _WORLD-JOURNAL-HEIGHT
52 CONSTANT _WORLD-JOURNAL-WIDTH
20 CONSTANT _WORLD-JOURNAL-TEXT-CAP
 1 CONSTANT _WORLD-JOURNAL-ROOT-KEY
 2 CONSTANT _WORLD-JOURNAL-HEADER-KEY-BASE
16 CONSTANT _WORLD-JOURNAL-RECORD-KEY-BASE

_WORLD-JOURNAL-TEXT-CAP USCOL-TEXT-ITEM-BYTES
    CONSTANT _WORLD-JOURNAL-ITEM-CAP
USCOL-TEXT-FIXED-SIZE
    _WORLD-JOURNAL-COLUMNS _WORLD-JOURNAL-ITEM-CAP * +
    _WORLD-JOURNAL-RECORD-ROWS _WORLD-JOURNAL-COLUMNS *
        _WORLD-JOURNAL-ITEM-CAP * +
    CONSTANT _WORLD-JOURNAL-BANK-CAP
_WORLD-JOURNAL-ROWS _WORLD-JOURNAL-COLUMNS * 8 *
    CONSTANT _WORLD-JOURNAL-WORK-CAP

VARIABLE _WORLD-CURRENT-STATE
VARIABLE _WORLD-CURRENT-INSTANCE
0 _WORLD-CURRENT-STATE !
0 _WORLD-CURRENT-INSTANCE !

CMP-LAYOUT-BEGIN
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-E-BODY
_WORLD-CURRENT-STATE 40 CMP-FIELD: _WORLD-PANEL
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-PANEL-RGN
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-JOURNAL-WIDGET
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-JOURNAL-RGN
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-JOURNAL-ACTIVE-A
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-JOURNAL-ACTIVE-U
_WORLD-CURRENT-STATE _WORLD-JOURNAL-BANK-CAP
    CMP-FIELD: _WORLD-JOURNAL-BANK-A
_WORLD-CURRENT-STATE _WORLD-JOURNAL-BANK-CAP
    CMP-FIELD: _WORLD-JOURNAL-BANK-B
_WORLD-CURRENT-STATE USCOL-BUILDER-SIZE CMP-FIELD: _WORLD-JOURNAL-BUILDER
_WORLD-CURRENT-STATE _WORLD-JOURNAL-WORK-CAP CMP-FIELD: _WORLD-JOURNAL-WORK
_WORLD-CURRENT-STATE USCOL-SUMMARY-SIZE CMP-FIELD: _WORLD-JOURNAL-SUMMARY
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-JOURNAL
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-TELEMETRY
_WORLD-CURRENT-STATE WRUN-CHECKPOINT-SIZE CMP-FIELD: _WORLD-CHECKPOINT
_WORLD-CURRENT-STATE WRUN-SIZE CMP-FIELD: _WORLD-RUN
_WORLD-CURRENT-STATE WRUN-SIZE CMP-FIELD: _WORLD-REPLAY
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-RUNNING
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-LAST-AUTO-MS
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-LAST-STATUS
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-REPLAY-STATUS
_WORLD-CURRENT-STATE CMP-CELL: _WORLD-NEXT-BRANCH
CMP-LAYOUT-SIZE CONSTANT _WORLD-STATE-SIZE

: _WORLD-ACTIVATE  ( instance -- )
    DUP _WORLD-CURRENT-INSTANCE !
    CINST-STATE _WORLD-CURRENT-STATE ! ;

: _WORLD-STATE-FINI  ( state -- )
    _WORLD-CURRENT-STATE !
    _WORLD-JOURNAL @ ?DUP IF FREE THEN
    _WORLD-TELEMETRY @ ?DUP IF FREE THEN
    0 _WORLD-JOURNAL ! 0 _WORLD-TELEMETRY ! ;

: _WORLD-INVALIDATE  ( -- )
    _WORLD-PANEL WDG-DIRTY
    _WORLD-E-BODY @ ?DUP IF UIDL-DIRTY! THEN
    ASHELL-DIRTY! ;

DEFER _WORLD-JOURNAL-REBUILD-D
' NOOP IS _WORLD-JOURNAL-REBUILD-D

: _WORLD-TOUCHED  ( -- )
    _WORLD-CURRENT-INSTANCE @ ?DUP IF CINST-TOUCH THEN
    _WORLD-INVALIDATE ;

: _WORLD-STATUS$  ( status -- address length )
    CASE
        WRUN-S-OK OF S" ready" ENDOF
        WRUN-S-INVALID OF S" invalid action refused" ENDOF
        WRUN-S-STALE OF S" stale revision refused" ENDOF
        WRUN-S-CAPACITY OF S" configured horizon full" ENDOF
        WRUN-S-NO-CHECKPOINT OF S" create a checkpoint first" ENDOF
        WRUN-S-CORRUPT OF S" replay mismatch / corrupt evidence" ENDOF
        WRUN-S-OVERFLOW OF S" revision or tick exhausted" ENDOF
        DROP S" unavailable"
    ENDCASE ;

: _WORLD-APPLY-STATUS  ( status -- )
    DUP _WORLD-LAST-STATUS !
    DUP WRUN-S-OK = IF
        DROP _WORLD-JOURNAL-REBUILD-D _WORLD-TOUCHED
    ELSE
        DUP WRUN-S-CAPACITY = IF 0 _WORLD-RUNNING ! THEN
        _WORLD-INVALIDATE DROP
    THEN ;

: _WORLD-STEP  ( -- )
    _WORLD-RUN WRUN.REVISION @ _WORLD-RUN WRUN-STEP
        _WORLD-APPLY-STATUS ;

VARIABLE _WORLD-NEXT-VALVE

: _WORLD-SET-NEXT-VALVE  ( -- )
    _WORLD-RUN WRUN.VALVE @ 250 + DUP 1000 > IF DROP 0 THEN
        _WORLD-NEXT-VALVE !
    _WORLD-NEXT-VALVE @ _WORLD-RUN WRUN.REVISION @
        _WORLD-RUN WRUN-VALVE-SET _WORLD-APPLY-STATUS ;

: _WORLD-CHECKPOINT-ACTION  ( -- )
    _WORLD-RUN WRUN.REVISION @ _WORLD-RUN WRUN-CHECKPOINT
        _WORLD-APPLY-STATUS ;

: _WORLD-BRANCH-ACTION  ( -- )
    _WORLD-NEXT-BRANCH @ _WORLD-RUN WRUN.REVISION @
        _WORLD-RUN WRUN-BRANCH
    DUP WRUN-S-OK = IF 1 _WORLD-NEXT-BRANCH +! THEN
    _WORLD-APPLY-STATUS ;

: _WORLD-REPLAY-ACTION  ( -- )
    _WORLD-REPLAY _WORLD-RUN WRUN-REPLAY
    DUP _WORLD-REPLAY-STATUS ! _WORLD-APPLY-STATUS ;

: _WORLD-TOGGLE-RUN  ( -- )
    _WORLD-RUNNING @ 0= _WORLD-RUNNING !
    MS@ _WORLD-LAST-AUTO-MS !
    WRUN-S-OK _WORLD-LAST-STATUS ! _WORLD-TOUCHED ;

\ Closed binary request contract shared semantically, not by importing the
\ Observatory applet.  The receiver validates every field and both digests.
0x4F42535754533031 CONSTANT _WORLD-TS-MAGIC
1 CONSTANT _WORLD-TS-VERSION
1 CONSTANT _WORLD-TS-OWNER-WORLDS
1 CONSTANT _WORLD-TS-X-TICK
1 CONSTANT _WORLD-TS-Y-UPPER-AMOUNT
1000 CONSTANT _WORLD-TS-Y-SCALE
144 CONSTANT _WORLD-TS-HEADER-SIZE
16 CONSTANT _WORLD-TS-SAMPLE-SIZE

  0 CONSTANT _WTS.MAGIC
  8 CONSTANT _WTS.VERSION
 16 CONSTANT _WTS.OWNER-KIND
 24 CONSTANT _WTS.RUN-ID
 32 CONSTANT _WTS.BRANCH-ID
 40 CONSTANT _WTS.REVISION
 48 CONSTANT _WTS.X-KIND
 56 CONSTANT _WTS.Y-KIND
 64 CONSTANT _WTS.Y-SCALE
 72 CONSTANT _WTS.COUNT
 80 CONSTANT _WTS.CONTENT-DIGEST
112 CONSTANT _WTS.STATE-DIGEST
144 CONSTANT _WTS.SAMPLES

VARIABLE _WORLD-SNAP-RUN
VARIABLE _WORLD-SNAP-A
VARIABLE _WORLD-SNAP-CAP
VARIABLE _WORLD-SNAP-N
VARIABLE _WORLD-SNAP-U
VARIABLE _WORLD-SNAP-I
VARIABLE _WORLD-SNAP-X
VARIABLE _WORLD-SNAP-Y
VARIABLE _WORLD-SNAP-OK
CREATE _WORLD-SNAP-DIGEST SHA3-256-LEN ALLOT

: WORLD-TELEMETRY-SNAPSHOT-SIZE  ( run -- bytes status )
    DUP WRUN-VALID? 0= IF DROP 0 WRUN-S-INVALID EXIT THEN
    WRUN.TELEMETRY-N @ DUP 0> 0= IF DROP 0 WRUN-S-INVALID EXIT THEN
    DUP 65536 _WORLD-TS-HEADER-SIZE - _WORLD-TS-SAMPLE-SIZE / > IF
        DROP 0 WRUN-S-CAPACITY EXIT
    THEN
    _WORLD-TS-SAMPLE-SIZE * _WORLD-TS-HEADER-SIZE + WRUN-S-OK ;

: _WORLD-SNAPSHOT-CONTENT-DIGEST  ( snapshot count destination -- )
    >R _WORLD-SNAP-N ! _WORLD-SNAP-A !
    SHA3-256-BEGIN
    S" org.akashic.worlds.telemetry.upper.v1" SHA3-256-ADD
    _WORLD-SNAP-A @ _WTS.CONTENT-DIGEST SHA3-256-ADD
    _WORLD-SNAP-A @ _WTS.STATE-DIGEST + SHA3-256-LEN SHA3-256-ADD
    _WORLD-SNAP-A @ _WTS.SAMPLES +
        _WORLD-SNAP-N @ _WORLD-TS-SAMPLE-SIZE * SHA3-256-ADD
    R> SHA3-256-END ;

: WORLD-TELEMETRY-SNAPSHOT  ( run destination capacity -- bytes status )
    _WORLD-SNAP-CAP ! _WORLD-SNAP-A ! _WORLD-SNAP-RUN !
    _WORLD-SNAP-RUN @ WORLD-TELEMETRY-SNAPSHOT-SIZE
    DUP IF NIP 0 SWAP EXIT THEN DROP _WORLD-SNAP-U !
    _WORLD-SNAP-A @ 0=
    _WORLD-SNAP-U @ _WORLD-SNAP-CAP @ > OR IF
        0 WRUN-S-CAPACITY EXIT
    THEN
    _WORLD-SNAP-A @ _WORLD-SNAP-U @ 0 FILL
    _WORLD-TS-MAGIC _WORLD-SNAP-A @ _WTS.MAGIC + WRUN-BE64!
    _WORLD-TS-VERSION _WORLD-SNAP-A @ _WTS.VERSION + WRUN-BE64!
    _WORLD-TS-OWNER-WORLDS _WORLD-SNAP-A @ _WTS.OWNER-KIND + WRUN-BE64!
    _WORLD-SNAP-RUN @ WRUN.RUN-ID @
        _WORLD-SNAP-A @ _WTS.RUN-ID + WRUN-BE64!
    _WORLD-SNAP-RUN @ WRUN.BRANCH-ID @
        _WORLD-SNAP-A @ _WTS.BRANCH-ID + WRUN-BE64!
    _WORLD-SNAP-RUN @ WRUN.REVISION @
        _WORLD-SNAP-A @ _WTS.REVISION + WRUN-BE64!
    _WORLD-TS-X-TICK _WORLD-SNAP-A @ _WTS.X-KIND + WRUN-BE64!
    _WORLD-TS-Y-UPPER-AMOUNT _WORLD-SNAP-A @ _WTS.Y-KIND + WRUN-BE64!
    _WORLD-TS-Y-SCALE _WORLD-SNAP-A @ _WTS.Y-SCALE + WRUN-BE64!
    _WORLD-SNAP-RUN @ WRUN.TELEMETRY-N @ DUP _WORLD-SNAP-N !
        _WORLD-SNAP-A @ _WTS.COUNT + WRUN-BE64!
    _WORLD-SNAP-RUN @ WRUN.STATE-DIGEST
        _WORLD-SNAP-A @ _WTS.STATE-DIGEST + SHA3-256-LEN CMOVE
    _WORLD-SNAP-N @ 0 DO
        I _WORLD-SNAP-RUN @ WRUN-SAMPLE@
        _WORLD-SNAP-OK ! _WORLD-SNAP-Y ! _WORLD-SNAP-X !
        _WORLD-SNAP-OK @ 0= IF 0 WRUN-S-CORRUPT UNLOOP EXIT THEN
        _WORLD-SNAP-X @ _WORLD-SNAP-A @ _WTS.SAMPLES +
            I _WORLD-TS-SAMPLE-SIZE * + WRUN-BE64!
        _WORLD-SNAP-Y @ _WORLD-SNAP-A @ _WTS.SAMPLES +
            I _WORLD-TS-SAMPLE-SIZE * + 8 + WRUN-BE64!
    LOOP
    _WORLD-SNAP-A @ _WORLD-SNAP-N @ _WORLD-SNAP-DIGEST
        _WORLD-SNAPSHOT-CONTENT-DIGEST
    _WORLD-SNAP-DIGEST _WORLD-SNAP-A @ _WTS.CONTENT-DIGEST +
        SHA3-256-LEN CMOVE
    _WORLD-SNAP-U @ WRUN-S-OK ;

VARIABLE _WORLD-ANALYZE-REQ
VARIABLE _WORLD-ANALYZE-SNAPSHOT
VARIABLE _WORLD-ANALYZE-U
VARIABLE _WORLD-ANALYZE-HEX
VARIABLE _WORLD-ANALYZE-HEX-U

\ Typed IVJSON intentionally has no BYTES representation.  Lowercase hex is
\ therefore the canonical request envelope for the exact binary projection.
\ A typed string adds exactly 13 bytes of JSON syntax around an all-ASCII hex
\ payload; derive the bound from the request-bus contract rather than setting
\ an applet-specific sample ceiling.
CBR-ARGS-CANONICAL-MAX 13 - CONSTANT _WORLD-TS-HEX-MAX

: _WORLD-ANALYZE-COMPLETE  ( request -- )
    DUP CBR.STATUS @ CBUS-S-OK = IF
        S" Observatory accepted the exact telemetry snapshot"
    ELSE
        S" Observatory refused the telemetry snapshot"
    THEN
    2200 ASHELL-TOAST CBR-FREE ;

: _WORLD-ANALYZE-ACTION  ( -- )
    _WORLD-RUN WORLD-TELEMETRY-SNAPSHOT-SIZE
    DUP IF
        2DROP S" Current telemetry cannot be represented" 2200 ASHELL-TOAST EXIT
    THEN DROP _WORLD-ANALYZE-U !
    _WORLD-ANALYZE-U @ ALLOCATE DUP IF
        2DROP S" Could not allocate telemetry snapshot" 2200 ASHELL-TOAST EXIT
    THEN DROP _WORLD-ANALYZE-SNAPSHOT !
    _WORLD-RUN _WORLD-ANALYZE-SNAPSHOT @ _WORLD-ANALYZE-U @
        WORLD-TELEMETRY-SNAPSHOT
    DUP IF
        2DROP _WORLD-ANALYZE-SNAPSHOT @ FREE
        S" Telemetry snapshot construction failed" 2200 ASHELL-TOAST EXIT
    THEN DROP DROP
    _WORLD-ANALYZE-U @ 2* DUP _WORLD-ANALYZE-HEX-U !
    DUP _WORLD-TS-HEX-MAX > IF
        DROP _WORLD-ANALYZE-SNAPSHOT @ FREE
        S" Snapshot exceeds the typed request envelope" 2200 ASHELL-TOAST EXIT
    THEN
    ALLOCATE DUP IF
        2DROP _WORLD-ANALYZE-SNAPSHOT @ FREE
        S" Could not allocate telemetry envelope" 2200 ASHELL-TOAST EXIT
    THEN DROP _WORLD-ANALYZE-HEX !
    _WORLD-ANALYZE-SNAPSHOT @ _WORLD-ANALYZE-U @
        _WORLD-ANALYZE-HEX @ FMT->HEX
    _WORLD-ANALYZE-HEX-U @ <> IF
        _WORLD-ANALYZE-HEX @ FREE _WORLD-ANALYZE-SNAPSHOT @ FREE
        S" Telemetry envelope construction failed" 2200 ASHELL-TOAST EXIT
    THEN
    CBR-NEW DUP IF
        2DROP _WORLD-ANALYZE-HEX @ FREE _WORLD-ANALYZE-SNAPSHOT @ FREE
        S" Could not allocate analysis request" 2200 ASHELL-TOAST EXIT
    THEN DROP _WORLD-ANALYZE-REQ !
    CPRINC-COMPONENT _WORLD-ANALYZE-REQ @ CBR.PRINCIPAL !
    _WORLD-ANALYZE-HEX @ _WORLD-ANALYZE-HEX-U @
        _WORLD-ANALYZE-REQ @ CBR.ARGS CV-STRING!
    _WORLD-ANALYZE-HEX @ FREE
    _WORLD-ANALYZE-SNAPSHOT @ FREE
    IF
        _WORLD-ANALYZE-REQ @ CBR-FREE
        S" Could not own analysis arguments" 2200 ASHELL-TOAST EXIT
    THEN
    ['] _WORLD-ANALYZE-COMPLETE
        _WORLD-ANALYZE-REQ @ CBR.COMPLETE-XT !
    _WORLD-ANALYZE-REQ @ CBR-ARGS-SEAL! CBUS-S-OK <> IF
        _WORLD-ANALYZE-REQ @ CBR-FREE
        S" Could not seal analysis arguments" 2200 ASHELL-TOAST EXIT
    THEN
    S" dataset.analyze" _WORLD-ANALYZE-REQ @
        _WORLD-CURRENT-INSTANCE @ CINST-POST-INTENT
    CBUS-S-OK <> IF
        _WORLD-ANALYZE-REQ @ CBR-FREE
        S" Launch Observatory once in Desk before Analyze"
            2600 ASHELL-TOAST
    THEN ;

\ =====================================================================
\  Canonical recent-transition TEXT_GRID
\ =====================================================================

: _WORLD-JOURNAL-INACTIVE  ( -- address )
    _WORLD-JOURNAL-ACTIVE-A @ _WORLD-JOURNAL-BANK-A = IF
        _WORLD-JOURNAL-BANK-B
    ELSE
        _WORLD-JOURNAL-BANK-A
    THEN ;

: _WORLD-JOURNAL-HEADER$  ( column -- address bytes )
    CASE
        0 OF S" revision" ENDOF
        1 OF S" tick" ENDOF
        2 OF S" transition" ENDOF
        3 OF S" value" ENDOF
        S" ?" ROT
    ENDCASE ;

: _WORLD-JOURNAL-KIND$  ( record -- address bytes )
    WRUN-RECORD-KIND@ CASE
        WRUN-EVENT-STEP OF S" step transfer" ENDOF
        WRUN-EVENT-VALVE-SET OF S" valve.set" ENDOF
        S" unknown" ROT
    ENDCASE ;

: _WORLD-JOURNAL-VALUE@  ( record -- value )
    DUP WRUN-RECORD-KIND@ WRUN-EVENT-STEP = IF
        WRUN-RECORD-ACTUAL@
    ELSE
        WRUN-RECORD-ARGUMENT@
    THEN ;

: _WORLD-JOURNAL-RECORD-KEY  ( visible-row-index column -- key )
    \ Keys identify stable viewport cells.  Domain records legitimately move
    \ between rows as the newest-first window advances or a branch resets.
    SWAP _WORLD-JOURNAL-COLUMNS * + _WORLD-JOURNAL-RECORD-KEY-BASE + ;

VARIABLE _WORLD-JI-KEY
VARIABLE _WORLD-JI-ROW
VARIABLE _WORLD-JI-COLUMN
VARIABLE _WORLD-JI-ROLE
VARIABLE _WORLD-JI-TEXT-A
VARIABLE _WORLD-JI-TEXT-U

: _WORLD-JOURNAL-ITEM
    ( key row column role text-a text-u -- status )
    _WORLD-JI-TEXT-U ! _WORLD-JI-TEXT-A ! _WORLD-JI-ROLE !
    _WORLD-JI-COLUMN ! _WORLD-JI-ROW ! _WORLD-JI-KEY !
    _WORLD-JI-KEY @ _WORLD-JI-ROW @ _WORLD-JI-COLUMN @ 1 1
        _WORLD-JI-ROLE @ 0 _WORLD-JI-TEXT-A @ _WORLD-JI-TEXT-U @
        _WORLD-JOURNAL-BUILDER USCOL-TEXT-ITEM ;

: _WORLD-JOURNAL-EMIT-HEADERS  ( -- status )
    _WORLD-JOURNAL-COLUMNS 0 DO
        _WORLD-JOURNAL-HEADER-KEY-BASE I +
            0 I USCOL-ROLE-COLUMN-HEADER I _WORLD-JOURNAL-HEADER$
            _WORLD-JOURNAL-ITEM
        DUP USCOL-S-OK <> IF UNLOOP EXIT THEN DROP
    LOOP
    USCOL-S-OK ;

VARIABLE _WORLD-JG-INDEX
VARIABLE _WORLD-JG-RECORD

: _WORLD-JOURNAL-EMIT-RECORDS  ( -- status )
    _WORLD-RUN WRUN.JOURNAL-N @ _WORLD-JOURNAL-RECORD-ROWS MIN 0 ?DO
        _WORLD-RUN WRUN.JOURNAL-N @ 1- I - DUP _WORLD-JG-INDEX !
            _WORLD-RUN WRUN-RECORD@
        DUP 0= IF DROP USCOL-S-INVALID UNLOOP EXIT THEN
        _WORLD-JG-RECORD !
        I 0 _WORLD-JOURNAL-RECORD-KEY
            I 1+ 0 USCOL-ROLE-ROW-HEADER
            _WORLD-JG-RECORD @ WRUN-RECORD-REVISION@ NUM>STR
            _WORLD-JOURNAL-ITEM
        DUP USCOL-S-OK <> IF UNLOOP EXIT THEN DROP
        I 1 _WORLD-JOURNAL-RECORD-KEY
            I 1+ 1 USCOL-ROLE-CONTENT
            _WORLD-JG-RECORD @ WRUN-RECORD-TICK@ NUM>STR
            _WORLD-JOURNAL-ITEM
        DUP USCOL-S-OK <> IF UNLOOP EXIT THEN DROP
        I 2 _WORLD-JOURNAL-RECORD-KEY
            I 1+ 2 USCOL-ROLE-CONTENT
            _WORLD-JG-RECORD @ _WORLD-JOURNAL-KIND$
            _WORLD-JOURNAL-ITEM
        DUP USCOL-S-OK <> IF UNLOOP EXIT THEN DROP
        I 3 _WORLD-JOURNAL-RECORD-KEY
            I 1+ 3 USCOL-ROLE-CONTENT
            _WORLD-JG-RECORD @ _WORLD-JOURNAL-VALUE@ NUM>STR
            _WORLD-JOURNAL-ITEM
        DUP USCOL-S-OK <> IF UNLOOP EXIT THEN DROP
    LOOP
    USCOL-S-OK ;

VARIABLE _WORLD-JG-DEST
VARIABLE _WORLD-JG-U

: _WORLD-JOURNAL-REBUILD  ( -- status )
    _WORLD-JOURNAL-WIDGET @ 0= IF USCOL-S-UNAVAILABLE EXIT THEN
    _WORLD-RUN WRUN-VALID? 0= IF USCOL-S-INVALID EXIT THEN
    _WORLD-JOURNAL-INACTIVE DUP _WORLD-JG-DEST !
        _WORLD-JOURNAL-BANK-CAP _WORLD-JOURNAL-BUILDER
        USCOL-BUILDER-INIT
    DUP USCOL-S-OK <> IF EXIT THEN DROP
    USCOL-F-TEXT-GRID _WORLD-JOURNAL-ROOT-KEY
        0 0 _WORLD-JOURNAL-HEIGHT _WORLD-JOURNAL-WIDTH
        USCOL-STATE-VISIBLE USCOL-STATE-ENABLED OR
        _WORLD-JOURNAL-BUILDER USCOL-TEXT-BEGIN
    DUP USCOL-S-OK <> IF EXIT THEN DROP
    USCOL-CONTENT-READ-ONLY
        _WORLD-JOURNAL-ROWS _WORLD-JOURNAL-COLUMNS
        0 0 _WORLD-JOURNAL-ROWS _WORLD-JOURNAL-COLUMNS
        _WORLD-JOURNAL-BUILDER USCOL-TEXT-SHAPE
    DUP USCOL-S-OK <> IF EXIT THEN DROP
    0 0 0 0 _WORLD-JOURNAL-BUILDER USCOL-TEXT-POSITIONS
    DUP USCOL-S-OK <> IF EXIT THEN DROP
    _WORLD-JOURNAL-EMIT-HEADERS DUP USCOL-S-OK <> IF EXIT THEN DROP
    _WORLD-JOURNAL-EMIT-RECORDS DUP USCOL-S-OK <> IF EXIT THEN DROP
    _WORLD-JOURNAL-BUILDER USCOL-TEXT-END
    DUP USCOL-S-OK <> IF EXIT THEN DROP
    _WORLD-JOURNAL-BUILDER USCOL-BUILDER-FINISH
    DUP USCOL-S-OK <> IF NIP EXIT THEN DROP _WORLD-JG-U !
    _WORLD-JG-DEST @ _WORLD-JG-U @
        _WORLD-JOURNAL-WORK _WORLD-JOURNAL-WORK-CAP
        _WORLD-JOURNAL-SUMMARY _WORLD-JOURNAL-WIDGET @ TGRID-BIND
    DUP USCOL-S-OK <> IF EXIT THEN DROP
    _WORLD-JG-DEST @ _WORLD-JOURNAL-ACTIVE-A !
    _WORLD-JG-U @ _WORLD-JOURNAL-ACTIVE-U !
    USCOL-S-OK ;

: _WORLD-JOURNAL-REBUILD!  ( -- )
    _WORLD-JOURNAL-WIDGET @ ?DUP IF
        DROP _WORLD-JOURNAL-REBUILD USCOL-S-OK <>
            ABORT" worlds: journal grid rebuild"
    THEN ;

' _WORLD-JOURNAL-REBUILD! IS _WORLD-JOURNAL-REBUILD-D

: _WORLD-JOURNAL-LAYOUT  ( -- )
    _WORLD-PANEL-RGN @ RGN-ROW 15 +
    _WORLD-PANEL-RGN @ RGN-COL 2 +
    _WORLD-JOURNAL-HEIGHT _WORLD-JOURNAL-WIDTH _WORLD-JOURNAL-RGN @
    RGN-BOUNDS! ;

VARIABLE _WORLD-DW
VARIABLE _WORLD-DH
VARIABLE _WORLD-BAR-W
VARIABLE _WORLD-BAR-N
VARIABLE _WORLD-ROW

: _WORLD-DRAW-BAR  ( amount capacity row color -- )
    >R _WORLD-ROW !
    _WORLD-DW @ 24 - 4 MAX 52 MIN _WORLD-BAR-W !
    SWAP _WORLD-BAR-W @ * SWAP / _WORLD-BAR-N !
    239 234 0 DRW-STYLE!
    9472 _WORLD-ROW @ 20 _WORLD-BAR-W @ DRW-HLINE
    R> 234 CELL-A-BOLD DRW-STYLE!
    9608 _WORLD-ROW @ 20 _WORLD-BAR-N @ DRW-HLINE ;

: _WORLD-DRAW-IDENTITY  ( -- )
    253 234 0 DRW-STYLE!
    S" Model" 3 2 DRW-TEXT
    S" two-reservoir-facility@1" 3 14 DRW-TEXT
    S" Run" 4 2 DRW-TEXT
    _WORLD-RUN WRUN.RUN-ID @ NUM>STR 4 14 DRW-TEXT
    S" branch" 4 25 DRW-TEXT
    _WORLD-RUN WRUN.BRANCH-ID @ NUM>STR 4 33 DRW-TEXT
    S" parent" 4 43 DRW-TEXT
    _WORLD-RUN WRUN.PARENT-BRANCH-ID @ NUM>STR 4 51 DRW-TEXT
    S" Revision" 5 2 DRW-TEXT
    _WORLD-RUN WRUN.REVISION @ NUM>STR 5 14 DRW-TEXT
    S" tick" 5 25 DRW-TEXT
    _WORLD-RUN WRUN.TICK @ NUM>STR 5 31 DRW-TEXT
    S" journal" 5 43 DRW-TEXT
    _WORLD-RUN WRUN.JOURNAL-N @ NUM>STR 5 51 DRW-TEXT
    S" samples" 5 59 DRW-TEXT
    _WORLD-RUN WRUN.TELEMETRY-N @ NUM>STR 5 67 DRW-TEXT ;

: _WORLD-DRAW-RESERVOIRS  ( -- )
    244 234 0 DRW-STYLE!
    S" Entity" 7 2 DRW-TEXT S" amount / capacity" 7 20 DRW-TEXT
    253 234 0 DRW-STYLE!
    S" upper" 8 2 DRW-TEXT
    _WORLD-RUN WRUN.UPPER @ NUM>STR 8 10 DRW-TEXT
    S" /" 8 16 DRW-TEXT
    _WORLD-RUN WRUN.UPPER-CAP @ NUM>STR 8 18 DRW-TEXT
    _WORLD-RUN WRUN.UPPER @ _WORLD-RUN WRUN.UPPER-CAP @ 8 81
        _WORLD-DRAW-BAR
    S" lower" 10 2 DRW-TEXT
    _WORLD-RUN WRUN.LOWER @ NUM>STR 10 10 DRW-TEXT
    S" /" 10 16 DRW-TEXT
    _WORLD-RUN WRUN.LOWER-CAP @ NUM>STR 10 18 DRW-TEXT
    _WORLD-RUN WRUN.LOWER @ _WORLD-RUN WRUN.LOWER-CAP @ 10 45
        _WORLD-DRAW-BAR
    244 234 0 DRW-STYLE!
    S" relation: upper feeds lower" 12 2 DRW-TEXT
    S" valve" 12 34 DRW-TEXT
    _WORLD-RUN WRUN.VALVE @ NUM>STR 12 41 DRW-TEXT
    S" milliunits/tick" 12 47 DRW-TEXT ;

: _WORLD-DRAW-JOURNAL  ( -- )
    \ Heading, five-row grid, and footer must not overwrite one another.
    _WORLD-DH @ 22 < IF EXIT THEN
    244 234 0 DRW-STYLE!
    S" Recent canonical transitions" 14 2 DRW-TEXT
    _WORLD-JOURNAL-WIDGET @ ?DUP IF
        _WORLD-JOURNAL-LAYOUT
        WDG-DRAW
        _WORLD-PANEL-RGN @ RGN-USE
    THEN ;

: _WORLD-PANEL-DRAW  ( widget -- )
    DUP WDG-REGION RGN-W _WORLD-DW !
    WDG-REGION RGN-H _WORLD-DH !
    253 234 0 DRW-STYLE!
    32 0 0 _WORLD-DH @ _WORLD-DW @ DRW-FILL-RECT
    255 24 CELL-A-BOLD DRW-STYLE!
    32 0 0 1 _WORLD-DW @ DRW-FILL-RECT
    S" WORLDS / RESERVOIR FACILITY" 0 2 DRW-TEXT
    244 234 0 DRW-STYLE!
    S" S step | Space run/pause | V valve | C checkpoint | B branch | R replay | A analyze"
        _WORLD-DW @ 4 - 0 MAX MIN 1 2 DRW-TEXT
    _WORLD-DRAW-IDENTITY
    _WORLD-DRAW-RESERVOIRS
    _WORLD-DRAW-JOURNAL
    _WORLD-DH @ 2 - 0 MAX _WORLD-ROW !
    203 234 CELL-A-DIM DRW-STYLE!
    _WORLD-RUNNING @ IF S" RUNNING fixed-step" ELSE S" PAUSED" THEN
        _WORLD-ROW @ 2 DRW-TEXT
    S" |" _WORLD-ROW @ 23 DRW-TEXT
    _WORLD-LAST-STATUS @ _WORLD-STATUS$ _WORLD-ROW @ 26 DRW-TEXT
    _WORLD-REPLAY-STATUS @ WRUN-S-OK = IF
        S" replay: exact" _WORLD-ROW @ 57 DRW-TEXT
    THEN
    DRW-STYLE-RESET ;

VARIABLE _WORLD-H-WIDGET

: _WORLD-PANEL-HANDLE  ( event widget -- consumed? )
    _WORLD-H-WIDGET !
    DUP @ KEY-T-SPECIAL = IF
        8 + @ CASE
            KEY-LEFT OF _WORLD-SET-NEXT-VALVE -1 EXIT ENDOF
            KEY-RIGHT OF _WORLD-SET-NEXT-VALVE -1 EXIT ENDOF
        ENDCASE
        0 EXIT
    THEN
    DUP @ KEY-T-CHAR = IF
        DUP 16 + @ 0= IF
            8 + @ CASE
                [CHAR] s OF _WORLD-STEP -1 EXIT ENDOF
                BL OF _WORLD-TOGGLE-RUN -1 EXIT ENDOF
                [CHAR] v OF _WORLD-SET-NEXT-VALVE -1 EXIT ENDOF
                [CHAR] c OF _WORLD-CHECKPOINT-ACTION -1 EXIT ENDOF
                [CHAR] b OF _WORLD-BRANCH-ACTION -1 EXIT ENDOF
                [CHAR] r OF _WORLD-REPLAY-ACTION -1 EXIT ENDOF
                [CHAR] a OF _WORLD-ANALYZE-ACTION -1 EXIT ENDOF
            ENDCASE
            0 EXIT
        THEN
    THEN
    DROP 0 ;

: _WORLD-PANEL-INIT  ( region -- )
    DUP _WORLD-PANEL-RGN !
    _WORLD-PANEL 30 ROT
        ['] _WORLD-PANEL-DRAW ['] _WORLD-PANEL-HANDLE WDG-INIT ;

: _WORLD-DO-STEP       ( elem -- ) DROP _WORLD-STEP ;
: _WORLD-DO-RUN        ( elem -- ) DROP _WORLD-TOGGLE-RUN ;
: _WORLD-DO-VALVE      ( elem -- ) DROP _WORLD-SET-NEXT-VALVE ;
: _WORLD-DO-CHECKPOINT ( elem -- ) DROP _WORLD-CHECKPOINT-ACTION ;
: _WORLD-DO-BRANCH     ( elem -- ) DROP _WORLD-BRANCH-ACTION ;
: _WORLD-DO-REPLAY     ( elem -- ) DROP _WORLD-REPLAY-ACTION ;
: _WORLD-DO-ANALYZE    ( elem -- ) DROP _WORLD-ANALYZE-ACTION ;
: _WORLD-DO-QUIT       ( elem -- ) DROP ASHELL-QUIT ;

: WORLDS-INIT-CB  ( instance -- )
    _WORLD-ACTIVATE
    0 _WORLD-PANEL-RGN !
    0 _WORLD-JOURNAL-WIDGET ! 0 _WORLD-JOURNAL-RGN !
    0 _WORLD-JOURNAL-ACTIVE-A ! 0 _WORLD-JOURNAL-ACTIVE-U !
    0 _WORLD-JOURNAL ! 0 _WORLD-TELEMETRY !
    0 _WORLD-RUNNING ! 0 _WORLD-REPLAY-STATUS !
    WRUN-S-OK _WORLD-LAST-STATUS ! 2 _WORLD-NEXT-BRANCH !
    WRUN-RECORD-SIZE _WORLD-DEMO-HORIZON * ALLOCATE
        0<> ABORT" worlds: journal allocation failed" _WORLD-JOURNAL !
    _WORLD-DEMO-HORIZON 1+ 8 * ALLOCATE
        0<> ABORT" worlds: telemetry allocation failed" _WORLD-TELEMETRY !
    _WORLD-JOURNAL @ _WORLD-DEMO-HORIZON
        _WORLD-TELEMETRY @ _WORLD-DEMO-HORIZON 1+
        _WORLD-CHECKPOINT _WORLD-CURRENT-INSTANCE @ CINST.ID @ _WORLD-RUN
        WRUN-INIT 0<> ABORT" worlds: run initialization failed"
    S" worlds-body" UTUI-BY-ID _WORLD-E-BODY !
    _WORLD-E-BODY @ ?DUP IF
        UTUI-ELEM-RGN RGN-NEW _WORLD-PANEL-INIT
        _WORLD-PANEL-RGN @ 15 2
            _WORLD-JOURNAL-HEIGHT _WORLD-JOURNAL-WIDTH
            RGN-SUB DUP _WORLD-JOURNAL-RGN !
        _WORLD-JOURNAL-LAYOUT
        TGRID-NEW _WORLD-JOURNAL-WIDGET !
        _WORLD-JOURNAL-REBUILD USCOL-S-OK <>
            ABORT" worlds: initial journal grid"
        _WORLD-PANEL _WORLD-E-BODY @ UTUI-WIDGET-SET
        _WORLD-E-BODY @ UTUI-FOCUS!
    THEN
    S" step" ['] _WORLD-DO-STEP UTUI-DO!
    S" run" ['] _WORLD-DO-RUN UTUI-DO!
    S" valve" ['] _WORLD-DO-VALVE UTUI-DO!
    S" checkpoint" ['] _WORLD-DO-CHECKPOINT UTUI-DO!
    S" branch" ['] _WORLD-DO-BRANCH UTUI-DO!
    S" replay" ['] _WORLD-DO-REPLAY UTUI-DO!
    S" analyze" ['] _WORLD-DO-ANALYZE UTUI-DO!
    S" quit" ['] _WORLD-DO-QUIT UTUI-DO! ;

: WORLDS-EVENT-CB  ( event instance -- consumed? )
    _WORLD-ACTIVATE
    _UTUI-MENU-OPEN @ IF DROP 0 EXIT THEN
    _WORLD-PANEL WDG-HANDLE ;

: WORLDS-PAINT-CB  ( instance -- ) _WORLD-ACTIVATE ;

: WORLDS-TICK-CB  ( instance -- )
    _WORLD-ACTIVATE
    _WORLD-RUNNING @ 0= IF EXIT THEN
    MS@ DUP _WORLD-LAST-AUTO-MS @ - _WORLD-AUTO-INTERVAL-MS >= IF
        _WORLD-LAST-AUTO-MS ! _WORLD-STEP
    ELSE DROP THEN ;

: WORLDS-REQUEST-CLOSE-CB  ( reason instance -- decision )
    SWAP DROP _WORLD-ACTIVATE APP-CLOSE-D-ALLOW ;

: WORLDS-SHUTDOWN-CB  ( instance -- )
    _WORLD-ACTIVATE
    _WORLD-E-BODY @ ?DUP IF 0 SWAP UTUI-WIDGET-SET THEN
    _WORLD-JOURNAL-WIDGET @ ?DUP IF TGRID-FREE THEN
    _WORLD-JOURNAL-RGN @ ?DUP IF RGN-FREE THEN
    _WORLD-PANEL-RGN @ ?DUP IF RGN-FREE THEN
    0 _WORLD-JOURNAL-WIDGET ! 0 _WORLD-JOURNAL-RGN !
    0 _WORLD-JOURNAL-ACTIVE-A ! 0 _WORLD-JOURNAL-ACTIVE-U !
    0 _WORLD-PANEL-RGN ! ;

CREATE WORLDS-COMP-DESC COMP-DESC ALLOT

: _WORLDS-COMP-SETUP  ( -- )
    WORLDS-COMP-DESC COMP-DESC-INIT
    S" org.akashic.worlds"
        WORLDS-COMP-DESC COMP.ID-U ! WORLDS-COMP-DESC COMP.ID-A !
    S" 0.1.0"
        WORLDS-COMP-DESC COMP.VERSION-U ! WORLDS-COMP-DESC COMP.VERSION-A !
    _WORLD-STATE-SIZE WORLDS-COMP-DESC COMP.STATE-SIZE !
    ['] _WORLD-STATE-FINI WORLDS-COMP-DESC COMP.STATE-FINI-XT ! ;

: WORLDS-ENTRY  ( descriptor -- )
    _WORLDS-COMP-SETUP
    DUP APP-DESC-INIT
    WORLDS-COMP-DESC OVER APP.COMP-DESC !
    ['] WORLDS-INIT-CB OVER APP.INIT-XT !
    ['] WORLDS-EVENT-CB OVER APP.EVENT-XT !
    ['] WORLDS-TICK-CB OVER APP.TICK-XT !
    ['] WORLDS-PAINT-CB OVER APP.PAINT-XT !
    ['] WORLDS-SHUTDOWN-CB OVER APP.SHUTDOWN-XT !
    ['] _WORLD-ACTIVATE OVER APP.ACTIVATE-XT !
    ['] WORLDS-REQUEST-CLOSE-CB OVER APP.REQUEST-CLOSE-XT !
    APP-F-TICK-WHEN-CLEAN OVER APP.FLAGS !
    S" tui/applets/worlds/worlds.uidl"
        ROT DUP >R APP.UIDL-FILE-U ! R@ APP.UIDL-FILE-A !
    0 R@ APP.WIDTH ! 0 R@ APP.HEIGHT !
    S" Worlds" R@ APP.TITLE-U ! R> APP.TITLE-A ! ;

CREATE WORLDS-DESC APP-DESC ALLOT

: WORLDS-RUN  ( -- )
    WORLDS-DESC WORLDS-ENTRY
    WORLDS-DESC ASHELL-RUN ;
