\ vfs-ext4-dirhash.f — ext4 directory-name and half-MD4 policy
\
\ Internal dependency of the vfs-ext4.f public facade.

PROVIDED akashic-ext4-dirhash
REQUIRE vfs-ext4-admission.f

: _EXT4-DIRENT-NAME-VALID?  ( addr len -- flag )
    0 ?DO
        DUP I + C@ DUP 0= SWAP [CHAR] / = OR IF
            DROP FALSE UNLOOP EXIT
        THEN
    LOOP DROP TRUE ;

\ =====================================================================
\  Exact half-MD4 directory hashing for HTree mutation
\ =====================================================================

1 CONSTANT _EXT4-DX-HASH-HALF-MD4
1 CONSTANT _EXT4-SB-FL-SIGNED-HASH
2 CONSTANT _EXT4-SB-FL-UNSIGNED-HASH
3 CONSTANT _EXT4-SB-FL-HASH-MASK

CREATE _EXT4-DH-WORDS 8 CELLS ALLOT
CREATE _EXT4-DH-STATE 4 CELLS ALLOT
VARIABLE _EXT4-DH-MSG
VARIABLE _EXT4-DH-LEN
VARIABLE _EXT4-DH-SEED
VARIABLE _EXT4-DH-UNSIGNED
VARIABLE _EXT4-DH-PAD
VARIABLE _EXT4-DH-VALUE
VARIABLE _EXT4-DH-USE
VARIABLE _EXT4-DH-A
VARIABLE _EXT4-DH-B
VARIABLE _EXT4-DH-C
VARIABLE _EXT4-DH-D
VARIABLE _EXT4-DH-TARGET
VARIABLE _EXT4-DH-RB
VARIABLE _EXT4-DH-RC
VARIABLE _EXT4-DH-RD
VARIABLE _EXT4-DH-X
VARIABLE _EXT4-DH-SHIFT
VARIABLE _EXT4-DHP-CTX
VARIABLE _EXT4-DHP-VERSION

: _EXT4-DH-WORD@  ( index -- value )
    CELLS _EXT4-DH-WORDS + @ ;

: _EXT4-DH-STATE@  ( index -- value )
    CELLS _EXT4-DH-STATE + @ ;

: _EXT4-DH-ROL32  ( value shift -- value )
    _EXT4-DH-SHIFT ! 0xFFFFFFFF AND DUP
    _EXT4-DH-SHIFT @ LSHIFT SWAP
    32 _EXT4-DH-SHIFT @ - RSHIFT OR 0xFFFFFFFF AND ;

: _EXT4-DH-ROUND-F  ( target b c d x shift -- )
    _EXT4-DH-SHIFT ! _EXT4-DH-X ! _EXT4-DH-RD !
    _EXT4-DH-RC ! _EXT4-DH-RB ! _EXT4-DH-TARGET !
    _EXT4-DH-TARGET @ @
    _EXT4-DH-RD @ _EXT4-DH-RB @
    _EXT4-DH-RC @ _EXT4-DH-RD @ XOR AND XOR
    + 0xFFFFFFFF AND
    _EXT4-DH-X @ + 0xFFFFFFFF AND
    _EXT4-DH-SHIFT @ _EXT4-DH-ROL32 _EXT4-DH-TARGET @ ! ;

: _EXT4-DH-ROUND-G  ( target b c d x shift -- )
    _EXT4-DH-SHIFT ! _EXT4-DH-X ! _EXT4-DH-RD !
    _EXT4-DH-RC ! _EXT4-DH-RB ! _EXT4-DH-TARGET !
    _EXT4-DH-TARGET @ @
    _EXT4-DH-RB @ _EXT4-DH-RC @ AND
    _EXT4-DH-RB @ _EXT4-DH-RC @ XOR _EXT4-DH-RD @ AND
    + 0xFFFFFFFF AND + 0xFFFFFFFF AND
    _EXT4-DH-X @ + 0xFFFFFFFF AND
    _EXT4-DH-SHIFT @ _EXT4-DH-ROL32 _EXT4-DH-TARGET @ ! ;

: _EXT4-DH-ROUND-H  ( target b c d x shift -- )
    _EXT4-DH-SHIFT ! _EXT4-DH-X ! _EXT4-DH-RD !
    _EXT4-DH-RC ! _EXT4-DH-RB ! _EXT4-DH-TARGET !
    _EXT4-DH-TARGET @ @ _EXT4-DH-RB @ _EXT4-DH-RC @ XOR
    _EXT4-DH-RD @ XOR + 0xFFFFFFFF AND
    _EXT4-DH-X @ + 0xFFFFFFFF AND
    _EXT4-DH-SHIFT @ _EXT4-DH-ROL32 _EXT4-DH-TARGET @ ! ;

: _EXT4-DH-BUILD-WORDS  ( addr remaining unsigned? -- )
    _EXT4-DH-UNSIGNED ! _EXT4-DH-LEN ! _EXT4-DH-MSG !
    _EXT4-DH-LEN @ DUP 8 LSHIFT OR
    DUP 16 LSHIFT OR 0xFFFFFFFF AND DUP _EXT4-DH-PAD !
    8 0 DO DUP _EXT4-DH-WORDS I CELLS + ! LOOP DROP
    _EXT4-DH-LEN @ DUP 32 U> IF DROP 32 THEN _EXT4-DH-USE !
    _EXT4-DH-PAD @ _EXT4-DH-VALUE !
    _EXT4-DH-USE @ 0 ?DO
        I 3 AND 0= IF _EXT4-DH-PAD @ _EXT4-DH-VALUE ! THEN
        _EXT4-DH-MSG @ I + C@
        _EXT4-DH-UNSIGNED @ 0= IF
            DUP 0x80 AND IF 256 - THEN
        THEN
        _EXT4-DH-VALUE @ 8 LSHIFT + 0xFFFFFFFF AND
        DUP _EXT4-DH-VALUE !
        _EXT4-DH-WORDS I 4 / CELLS + !
    LOOP ;

: _EXT4-DH-ACCUMULATE  ( value address -- )
    DUP @ ROT + 0xFFFFFFFF AND SWAP ! ;

: _EXT4-DH-TRANSFORM  ( -- )
    0 _EXT4-DH-STATE@ _EXT4-DH-A !
    1 _EXT4-DH-STATE@ _EXT4-DH-B !
    2 _EXT4-DH-STATE@ _EXT4-DH-C !
    3 _EXT4-DH-STATE@ _EXT4-DH-D !

    _EXT4-DH-A _EXT4-DH-B @ _EXT4-DH-C @ _EXT4-DH-D @
    0 _EXT4-DH-WORD@ 3 _EXT4-DH-ROUND-F
    _EXT4-DH-D _EXT4-DH-A @ _EXT4-DH-B @ _EXT4-DH-C @
    1 _EXT4-DH-WORD@ 7 _EXT4-DH-ROUND-F
    _EXT4-DH-C _EXT4-DH-D @ _EXT4-DH-A @ _EXT4-DH-B @
    2 _EXT4-DH-WORD@ 11 _EXT4-DH-ROUND-F
    _EXT4-DH-B _EXT4-DH-C @ _EXT4-DH-D @ _EXT4-DH-A @
    3 _EXT4-DH-WORD@ 19 _EXT4-DH-ROUND-F
    _EXT4-DH-A _EXT4-DH-B @ _EXT4-DH-C @ _EXT4-DH-D @
    4 _EXT4-DH-WORD@ 3 _EXT4-DH-ROUND-F
    _EXT4-DH-D _EXT4-DH-A @ _EXT4-DH-B @ _EXT4-DH-C @
    5 _EXT4-DH-WORD@ 7 _EXT4-DH-ROUND-F
    _EXT4-DH-C _EXT4-DH-D @ _EXT4-DH-A @ _EXT4-DH-B @
    6 _EXT4-DH-WORD@ 11 _EXT4-DH-ROUND-F
    _EXT4-DH-B _EXT4-DH-C @ _EXT4-DH-D @ _EXT4-DH-A @
    7 _EXT4-DH-WORD@ 19 _EXT4-DH-ROUND-F

    _EXT4-DH-A _EXT4-DH-B @ _EXT4-DH-C @ _EXT4-DH-D @
    1 _EXT4-DH-WORD@ 0x5A827999 + 0xFFFFFFFF AND 3 _EXT4-DH-ROUND-G
    _EXT4-DH-D _EXT4-DH-A @ _EXT4-DH-B @ _EXT4-DH-C @
    3 _EXT4-DH-WORD@ 0x5A827999 + 0xFFFFFFFF AND 5 _EXT4-DH-ROUND-G
    _EXT4-DH-C _EXT4-DH-D @ _EXT4-DH-A @ _EXT4-DH-B @
    5 _EXT4-DH-WORD@ 0x5A827999 + 0xFFFFFFFF AND 9 _EXT4-DH-ROUND-G
    _EXT4-DH-B _EXT4-DH-C @ _EXT4-DH-D @ _EXT4-DH-A @
    7 _EXT4-DH-WORD@ 0x5A827999 + 0xFFFFFFFF AND 13 _EXT4-DH-ROUND-G
    _EXT4-DH-A _EXT4-DH-B @ _EXT4-DH-C @ _EXT4-DH-D @
    0 _EXT4-DH-WORD@ 0x5A827999 + 0xFFFFFFFF AND 3 _EXT4-DH-ROUND-G
    _EXT4-DH-D _EXT4-DH-A @ _EXT4-DH-B @ _EXT4-DH-C @
    2 _EXT4-DH-WORD@ 0x5A827999 + 0xFFFFFFFF AND 5 _EXT4-DH-ROUND-G
    _EXT4-DH-C _EXT4-DH-D @ _EXT4-DH-A @ _EXT4-DH-B @
    4 _EXT4-DH-WORD@ 0x5A827999 + 0xFFFFFFFF AND 9 _EXT4-DH-ROUND-G
    _EXT4-DH-B _EXT4-DH-C @ _EXT4-DH-D @ _EXT4-DH-A @
    6 _EXT4-DH-WORD@ 0x5A827999 + 0xFFFFFFFF AND 13 _EXT4-DH-ROUND-G

    _EXT4-DH-A _EXT4-DH-B @ _EXT4-DH-C @ _EXT4-DH-D @
    3 _EXT4-DH-WORD@ 0x6ED9EBA1 + 0xFFFFFFFF AND 3 _EXT4-DH-ROUND-H
    _EXT4-DH-D _EXT4-DH-A @ _EXT4-DH-B @ _EXT4-DH-C @
    7 _EXT4-DH-WORD@ 0x6ED9EBA1 + 0xFFFFFFFF AND 9 _EXT4-DH-ROUND-H
    _EXT4-DH-C _EXT4-DH-D @ _EXT4-DH-A @ _EXT4-DH-B @
    2 _EXT4-DH-WORD@ 0x6ED9EBA1 + 0xFFFFFFFF AND 11 _EXT4-DH-ROUND-H
    _EXT4-DH-B _EXT4-DH-C @ _EXT4-DH-D @ _EXT4-DH-A @
    6 _EXT4-DH-WORD@ 0x6ED9EBA1 + 0xFFFFFFFF AND 15 _EXT4-DH-ROUND-H
    _EXT4-DH-A _EXT4-DH-B @ _EXT4-DH-C @ _EXT4-DH-D @
    1 _EXT4-DH-WORD@ 0x6ED9EBA1 + 0xFFFFFFFF AND 3 _EXT4-DH-ROUND-H
    _EXT4-DH-D _EXT4-DH-A @ _EXT4-DH-B @ _EXT4-DH-C @
    5 _EXT4-DH-WORD@ 0x6ED9EBA1 + 0xFFFFFFFF AND 9 _EXT4-DH-ROUND-H
    _EXT4-DH-C _EXT4-DH-D @ _EXT4-DH-A @ _EXT4-DH-B @
    0 _EXT4-DH-WORD@ 0x6ED9EBA1 + 0xFFFFFFFF AND 11 _EXT4-DH-ROUND-H
    _EXT4-DH-B _EXT4-DH-C @ _EXT4-DH-D @ _EXT4-DH-A @
    4 _EXT4-DH-WORD@ 0x6ED9EBA1 + 0xFFFFFFFF AND 15 _EXT4-DH-ROUND-H

    _EXT4-DH-A @ _EXT4-DH-STATE _EXT4-DH-ACCUMULATE
    _EXT4-DH-B @ _EXT4-DH-STATE 1 CELLS + _EXT4-DH-ACCUMULATE
    _EXT4-DH-C @ _EXT4-DH-STATE 2 CELLS + _EXT4-DH-ACCUMULATE
    _EXT4-DH-D @ _EXT4-DH-STATE 3 CELLS + _EXT4-DH-ACCUMULATE ;

: _EXT4-DH-INIT  ( seed -- )
    DUP _EXT4-DH-SEED !
    DUP L@ OVER 4 + L@ OR OVER 8 + L@ OR SWAP 12 + L@ OR IF
        _EXT4-DH-SEED @ L@ _EXT4-DH-STATE !
        _EXT4-DH-SEED @ 4 + L@ _EXT4-DH-STATE 1 CELLS + !
        _EXT4-DH-SEED @ 8 + L@ _EXT4-DH-STATE 2 CELLS + !
        _EXT4-DH-SEED @ 12 + L@ _EXT4-DH-STATE 3 CELLS + !
    ELSE
        0x67452301 _EXT4-DH-STATE !
        0xEFCDAB89 _EXT4-DH-STATE 1 CELLS + !
        0x98BADCFE _EXT4-DH-STATE 2 CELLS + !
        0x10325476 _EXT4-DH-STATE 3 CELLS + !
    THEN ;

: _EXT4-HALF-MD4-DIRHASH  ( addr len seed unsigned? -- hash minor )
    _EXT4-DH-UNSIGNED ! _EXT4-DH-SEED !
    _EXT4-DH-LEN ! _EXT4-DH-MSG !
    _EXT4-DH-SEED @ _EXT4-DH-INIT
    BEGIN _EXT4-DH-LEN @ 0> WHILE
        _EXT4-DH-MSG @ _EXT4-DH-LEN @ _EXT4-DH-UNSIGNED @
        _EXT4-DH-BUILD-WORDS _EXT4-DH-TRANSFORM
        32 _EXT4-DH-MSG +! -32 _EXT4-DH-LEN +!
    REPEAT
    1 _EXT4-DH-STATE@ 0xFFFFFFFE AND
    DUP 0xFFFFFFFE = IF DROP 0xFFFFFFFC THEN
    2 _EXT4-DH-STATE@ ;

: _EXT4-DIRHASH-POLICY  ( ctx root-version -- unsigned? ior )
    _EXT4-DHP-VERSION ! DUP _EXT4-DHP-CTX !
    _EXT4-DHP-VERSION @ _EXT4-DX-HASH-HALF-MD4 <> IF
        DROP FALSE EXT4-D-WRITE-POLICY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-C.SB + _EXT4-SB.FLAGS + L@ _EXT4-SB-FL-HASH-MASK AND
    DUP _EXT4-SB-FL-SIGNED-HASH = IF DROP FALSE 0 EXIT THEN
    _EXT4-SB-FL-UNSIGNED-HASH = IF TRUE 0 EXIT THEN
    FALSE EXT4-D-WRITE-POLICY _EXT4-UNSUPPORTED ;

: _EXT4-HALF-MD4-DIRHASH?  ( addr len root-version ctx -- hash minor ior )
    _EXT4-DHP-CTX ! _EXT4-DHP-VERSION !
    _EXT4-DH-LEN ! _EXT4-DH-MSG !
    _EXT4-DH-LEN @ DUP 0= SWAP 255 U> OR IF
        0 0 VFS-E-INVALID EXIT
    THEN
    _EXT4-DH-MSG @ _EXT4-DH-LEN @ _EXT4-DIRENT-NAME-VALID? 0= IF
        0 0 VFS-E-INVALID EXIT
    THEN
    _EXT4-DHP-CTX @ _EXT4-DHP-VERSION @ _EXT4-DIRHASH-POLICY
    DUP IF NIP 0 0 ROT EXIT THEN DROP _EXT4-DH-UNSIGNED !
    _EXT4-DH-MSG @ _EXT4-DH-LEN @
    _EXT4-DHP-CTX @ _EXT4-C.SB + _EXT4-SB.HASH-SEED +
    _EXT4-DH-UNSIGNED @ _EXT4-HALF-MD4-DIRHASH 0 ;
