\ vfs-ext4-admission.f — ext4 profile and primary-super admission
\
\ Internal foundation for vfs-ext4.f. The public entry point remains:
\ REQUIRE utils/fs/drivers/vfs-ext4.f

PROVIDED akashic-ext4-admission
REQUIRE ../../vfs.f
REQUIRE ../../../../math/crc.f

\ =====================================================================
\  Profile constants and on-disk offsets
\ =====================================================================

512  CONSTANT _EXT4-SECTOR
1024 CONSTANT _EXT4-SB-SIZE
4096 CONSTANT _EXT4-MAX-BLOCK
256  CONSTANT _EXT4-MAX-INODE
64   CONSTANT _EXT4-DESC-SIZE

0xEF53     CONSTANT _EXT4-MAGIC
0xF30A     CONSTANT _EXT4-EXTENT-MAGIC
0xC03B3998 CONSTANT _EXT4-JBD2-MAGIC
1          CONSTANT _EXT4-JBD2-DESCRIPTOR
2          CONSTANT _EXT4-JBD2-COMMIT
4          CONSTANT _EXT4-JBD2-SUPER-V2
5          CONSTANT _EXT4-JBD2-REVOKE

0x01 CONSTANT _EXT4-JBD2-F-ESCAPE
0x02 CONSTANT _EXT4-JBD2-F-SAME-UUID
0x08 CONSTANT _EXT4-JBD2-F-LAST
0x0F CONSTANT _EXT4-JBD2-F-ALL

0x01 CONSTANT _EXT4-JBD2-I-REVOKE
0x12 CONSTANT _EXT4-JBD2-I-RECOVERY
0x13 CONSTANT _EXT4-JBD2-I-RECOVERY-REVOKE
4    CONSTANT _EXT4-JBD2-CRC32C
16   CONSTANT _EXT4-JBD2-TAG3-SIZE
4    CONSTANT _EXT4-JBD2-TAIL-SIZE

0 CONSTANT _EXT4-JSCAN-PREFLIGHT
1 CONSTANT _EXT4-JSCAN-REVOKES
2 CONSTANT _EXT4-JSCAN-REPLAY
3 CONSTANT _EXT4-JSCAN-BINDING

0x0000103C CONSTANT _EXT4-COMPAT-V1
0x0000046B CONSTANT _EXT4-RO-V1
0x0000042B CONSTANT _EXT4-RO-I128-V1
0x00001000 CONSTANT _EXT4-RO-READONLY
0x00010000 CONSTANT _EXT4-RO-ORPHAN-PRESENT
0x0000EB94 CONSTANT _EXT4-RO-REFUSED
0x000022C2 CONSTANT _EXT4-INCOMPAT-V1
0x00000004 CONSTANT _EXT4-INCOMPAT-RECOVER

0x00080000 CONSTANT _EXT4-EXTENTS-FL
0x00001000 CONSTANT _EXT4-INDEX-FL
0x00040000 CONSTANT _EXT4-HUGE-FILE-FL
0x00004000 CONSTANT _EXT4-JOURNAL-DATA-FL
5          CONSTANT _EXT4-MAX-EXTENT-DEPTH
65000      CONSTANT _EXT4-LINK-MAX
12         CONSTANT _EXT4-NDIRECT
15         CONSTANT _EXT4-N-BLOCK-PTRS
1 CONSTANT _EXT4-BG-INODE-UNINIT
2 CONSTANT _EXT4-BG-BLOCK-UNINIT

\ Superblock offsets (all ext4 fields are little-endian).
0x000 CONSTANT _EXT4-SB.INODES
0x004 CONSTANT _EXT4-SB.BLOCKS-LO
0x008 CONSTANT _EXT4-SB.RBLOCKS-LO
0x00C CONSTANT _EXT4-SB.FREE-BLOCKS-LO
0x010 CONSTANT _EXT4-SB.FREE-INODES
0x014 CONSTANT _EXT4-SB.FIRST-DATA
0x018 CONSTANT _EXT4-SB.LOG-BLOCK
0x01C CONSTANT _EXT4-SB.LOG-CLUSTER
0x020 CONSTANT _EXT4-SB.BPG
0x024 CONSTANT _EXT4-SB.CPG
0x028 CONSTANT _EXT4-SB.IPG
0x038 CONSTANT _EXT4-SB.MAGIC
0x03A CONSTANT _EXT4-SB.STATE
0x03C CONSTANT _EXT4-SB.ERRORS
0x048 CONSTANT _EXT4-SB.CREATOR
0x04C CONSTANT _EXT4-SB.REVISION
0x054 CONSTANT _EXT4-SB.FIRST-INO
0x058 CONSTANT _EXT4-SB.INODE-SIZE
0x05A CONSTANT _EXT4-SB.GROUP-NR
0x05C CONSTANT _EXT4-SB.COMPAT
0x060 CONSTANT _EXT4-SB.INCOMPAT
0x064 CONSTANT _EXT4-SB.RO-COMPAT
0x068 CONSTANT _EXT4-SB.UUID
0x0CE CONSTANT _EXT4-SB.RESERVED-GDT
0x0E0 CONSTANT _EXT4-SB.JOURNAL-INO
0x0E8 CONSTANT _EXT4-SB.LAST-ORPHAN
0x0EC CONSTANT _EXT4-SB.HASH-SEED
0x0FC CONSTANT _EXT4-SB.DEFAULT-HASH
0x0FD CONSTANT _EXT4-SB.JOURNAL-BACKUP-TYPE
0x0FE CONSTANT _EXT4-SB.DESC-SIZE
0x10C CONSTANT _EXT4-SB.JOURNAL-BLOCKS
0x150 CONSTANT _EXT4-SB.BLOCKS-HI
0x154 CONSTANT _EXT4-SB.RBLOCKS-HI
0x158 CONSTANT _EXT4-SB.FREE-BLOCKS-HI
0x15C CONSTANT _EXT4-SB.MIN-EXTRA
0x15E CONSTANT _EXT4-SB.WANT-EXTRA
0x160 CONSTANT _EXT4-SB.FLAGS
0x174 CONSTANT _EXT4-SB.LOG-FLEX
0x175 CONSTANT _EXT4-SB.CSUM-TYPE
0x270 CONSTANT _EXT4-SB.CSUM-SEED
0x280 CONSTANT _EXT4-SB.ORPHAN-INO
0x3FC CONSTANT _EXT4-SB.CHECKSUM

1 CONSTANT _EXT4-JOURNAL-BACKUP-BLOCKS
8 CONSTANT _EXT4-JOURNAL-INODE

\ JBD2 superblock offsets (all JBD2 fields are big-endian).
0x00 CONSTANT _EXT4-JS.MAGIC
0x04 CONSTANT _EXT4-JS.TYPE
0x08 CONSTANT _EXT4-JS.HEADER-SEQUENCE
0x0C CONSTANT _EXT4-JS.BLOCK-SIZE
0x10 CONSTANT _EXT4-JS.MAXLEN
0x14 CONSTANT _EXT4-JS.FIRST
0x18 CONSTANT _EXT4-JS.SEQUENCE
0x1C CONSTANT _EXT4-JS.START
0x20 CONSTANT _EXT4-JS.ERRNO
0x24 CONSTANT _EXT4-JS.COMPAT
0x28 CONSTANT _EXT4-JS.INCOMPAT
0x2C CONSTANT _EXT4-JS.RO-COMPAT
0x30 CONSTANT _EXT4-JS.UUID
0x40 CONSTANT _EXT4-JS.NR-USERS
0x44 CONSTANT _EXT4-JS.DYNSUPER
0x48 CONSTANT _EXT4-JS.MAX-TRANSACTION
0x4C CONSTANT _EXT4-JS.MAX-TRANS-DATA
0x50 CONSTANT _EXT4-JS.CHECKSUM-TYPE
0x54 CONSTANT _EXT4-JS.FC-BLOCKS
0x58 CONSTANT _EXT4-JS.HEAD
0x5C CONSTANT _EXT4-JS.RECOVERY-MAGIC
0x60 CONSTANT _EXT4-JS.RECOVERY-CHECKSUM
0x64 CONSTANT _EXT4-JS.RECOVERY-CHECKSUM-XOR
0x68 CONSTANT _EXT4-JS.RECOVERY-ANCHOR
0x6C CONSTANT _EXT4-JS.RECOVERY-ANCHOR-XOR
0x70 CONSTANT _EXT4-JS.ACTIVATION-CHECKSUM
0x74 CONSTANT _EXT4-JS.ACTIVATION-CHECKSUM-XOR
0x78 CONSTANT _EXT4-JS.ACTIVATION-OLD-INCOMPAT
0x7C CONSTANT _EXT4-JS.ACTIVATION-OLD-HEAD
0x80 CONSTANT _EXT4-JS.ACTIVATION-OLD-CSUM-TYPE
0x84 CONSTANT _EXT4-JS.ACTIVATION-OLD-CHECKSUM
0xFC CONSTANT _EXT4-JS.CHECKSUM

0x414B5231 CONSTANT _EXT4-JBD2-RECOVERY-MAGIC  \ "AKR1"
0x414B5731 CONSTANT _EXT4-JBD2-ACTIVATION-MAGIC \ "AKW1"
0x414B4731 CONSTANT _EXT4-JBD2-ACTIVE-RESET-MAGIC \ "AKG1"
0x414B4531 CONSTANT _EXT4-JBD2-EMPTY-RESET-MAGIC \ "AKE1"

0 CONSTANT _EXT4-JW-NONE
1 CONSTANT _EXT4-JW-RECOVERY
2 CONSTANT _EXT4-JW-ACTIVATION

0 CONSTANT _EXT4-JC-NONE
1 CONSTANT _EXT4-JC-STANDARD
2 CONSTANT _EXT4-JC-ANCHOR
3 CONSTANT _EXT4-JC-ACTIVE

\ 64-byte group descriptor offsets.
0x00 CONSTANT _EXT4-GD.BLOCK-BITMAP-LO
0x04 CONSTANT _EXT4-GD.INODE-BITMAP-LO
0x08 CONSTANT _EXT4-GD.INODE-TABLE-LO
0x0C CONSTANT _EXT4-GD.FREE-BLOCKS-LO
0x0E CONSTANT _EXT4-GD.FREE-INODES-LO
0x10 CONSTANT _EXT4-GD.USED-DIRS-LO
0x12 CONSTANT _EXT4-GD.FLAGS
0x18 CONSTANT _EXT4-GD.BLOCK-CSUM-LO
0x1A CONSTANT _EXT4-GD.INODE-CSUM-LO
0x1C CONSTANT _EXT4-GD.ITABLE-UNUSED-LO
0x1E CONSTANT _EXT4-GD.CHECKSUM
0x20 CONSTANT _EXT4-GD.BLOCK-BITMAP-HI
0x24 CONSTANT _EXT4-GD.INODE-BITMAP-HI
0x28 CONSTANT _EXT4-GD.INODE-TABLE-HI
0x2C CONSTANT _EXT4-GD.FREE-BLOCKS-HI
0x2E CONSTANT _EXT4-GD.FREE-INODES-HI
0x30 CONSTANT _EXT4-GD.USED-DIRS-HI
0x32 CONSTANT _EXT4-GD.ITABLE-UNUSED-HI
0x38 CONSTANT _EXT4-GD.BLOCK-CSUM-HI
0x3A CONSTANT _EXT4-GD.INODE-CSUM-HI

\ Inode offsets.
0x00 CONSTANT _EXT4-I.MODE
0x02 CONSTANT _EXT4-I.UID-LO
0x04 CONSTANT _EXT4-I.SIZE-LO
0x08 CONSTANT _EXT4-I.ATIME
0x0C CONSTANT _EXT4-I.CTIME
0x10 CONSTANT _EXT4-I.MTIME
0x14 CONSTANT _EXT4-I.DTIME
0x18 CONSTANT _EXT4-I.GID-LO
0x1A CONSTANT _EXT4-I.LINKS
0x1C CONSTANT _EXT4-I.BLOCKS-LO
0x20 CONSTANT _EXT4-I.FLAGS
0x28 CONSTANT _EXT4-I.BLOCK
0x64 CONSTANT _EXT4-I.GENERATION
0x68 CONSTANT _EXT4-I.FILE-ACL-LO
0x6C CONSTANT _EXT4-I.SIZE-HI
0x74 CONSTANT _EXT4-I.BLOCKS-HI
0x76 CONSTANT _EXT4-I.FILE-ACL-HI
0x78 CONSTANT _EXT4-I.UID-HI
0x7A CONSTANT _EXT4-I.GID-HI
0x7C CONSTANT _EXT4-I.CSUM-LO
0x80 CONSTANT _EXT4-I.EXTRA-SIZE
0x82 CONSTANT _EXT4-I.CSUM-HI
0x84 CONSTANT _EXT4-I.CTIME-EXTRA
0x88 CONSTANT _EXT4-I.MTIME-EXTRA
0x8C CONSTANT _EXT4-I.ATIME-EXTRA
0x90 CONSTANT _EXT4-I.CRTIME
0x94 CONSTANT _EXT4-I.CRTIME-EXTRA
0x9C CONSTANT _EXT4-I.PROJECT-ID

\ Ext4 result-detail values.  The public reason/domain/flags remain the stable
\ interface; detail identifies the validation or operation-policy stage.
1  CONSTANT EXT4-D-MAGIC
2  CONSTANT EXT4-D-SUPER-CHECKSUM
3  CONSTANT EXT4-D-GEOMETRY
4  CONSTANT EXT4-D-FEATURE
5  CONSTANT EXT4-D-RECOVERY
6  CONSTANT EXT4-D-DESC-CHECKSUM
7  CONSTANT EXT4-D-BITMAP-CHECKSUM
8  CONSTANT EXT4-D-BOUNDS
9  CONSTANT EXT4-D-BACKUP-SUPER
10 CONSTANT EXT4-D-INODE-CHECKSUM
11 CONSTANT EXT4-D-ROOT-INODE
12 CONSTANT EXT4-D-JOURNAL
13 CONSTANT EXT4-D-ORPHAN-FILE
14 CONSTANT EXT4-D-ATTACHMENT
15 CONSTANT EXT4-D-DIRECTORY
16 CONSTANT EXT4-D-DATA-MAP
17 CONSTANT EXT4-D-XATTR
18 CONSTANT EXT4-D-WRITE-POLICY

\ =====================================================================
\  Binding context
\ =====================================================================
\
\ +0       1024-byte superblock cache
\ +1024    4096-byte filesystem-block cache
\ +5120     256-byte inode cache
\ +5376      64-byte group-descriptor cache
\ +5440      16-byte checksum input scratch
\ +5456      96-byte STATFS staging record
\ +5552     parsed geometry and metadata staging cells
\ +5800      staged special-device identity
\ +5808    second 4096-byte block buffer for directory/tree scans
\ +9904    third 4096-byte block buffer for map-tree validation
\ +14000   recovery and JBD2 scan state
\ +14096   torn-super and recovery-anchor state
\ +14144   journal-inode replay-preservation geometry
\ +14160   designated recovery-witness geometry and validation state
\ +14216   committed primary-super repair proof
\ +14232   persistent journal-workspace pointers and allocation geometry
\ +14272   checksum-valid designated sparse-super witness
\ +15296   persistent revoke-workspace pointer and allocation geometry
\ +15312   committed-revoke scan statistics and build epoch
\ +15384   mount-generation ownership of the persistent writer workspace
\ +15392   persistent unified orphan-plan workspace and union active count
\ +15416   mount-generation authenticated-empty-orphan recovery authority
\ +15424   mount-generation modern/legacy orphan protocol counts
\ +15440   caller-installed trusted write-clock provider and context
\ +15456   mount-scoped protocol-home ownership certificate
\ +15480   persistent caller-bounded mutation-range workspace
\ +15552   opaque CREATE/HTree plan pointer and exact byte span

   0 CONSTANT _EXT4-C.SB
1024 CONSTANT _EXT4-C.BLOCK
5120 CONSTANT _EXT4-C.INODE
5376 CONSTANT _EXT4-C.DESC
5440 CONSTANT _EXT4-C.TMP
5456 CONSTANT _EXT4-C.STAT
5552 CONSTANT _EXT4-C.READY
5560 CONSTANT _EXT4-C.BSIZE
5568 CONSTANT _EXT4-C.SPB
5576 CONSTANT _EXT4-C.BLOCKS
5584 CONSTANT _EXT4-C.INODES
5592 CONSTANT _EXT4-C.BPG
5600 CONSTANT _EXT4-C.IPG
5608 CONSTANT _EXT4-C.GROUPS
5616 CONSTANT _EXT4-C.ISIZE
5624 CONSTANT _EXT4-C.DSIZE
5632 CONSTANT _EXT4-C.FIRST
5640 CONSTANT _EXT4-C.SEED
5648 CONSTANT _EXT4-C.FREE-BLOCKS
5656 CONSTANT _EXT4-C.FREE-INODES
5664 CONSTANT _EXT4-C.RESERVED-BLOCKS
5672 CONSTANT _EXT4-C.ORPHAN-INO
5680 CONSTANT _EXT4-C.R.MODE
5688 CONSTANT _EXT4-C.R.SIZE
5696 CONSTANT _EXT4-C.R.UID
5704 CONSTANT _EXT4-C.R.GID
5712 CONSTANT _EXT4-C.R.NLINK
5720 CONSTANT _EXT4-C.R.ATIME
5728 CONSTANT _EXT4-C.R.MTIME
5736 CONSTANT _EXT4-C.R.CTIME
5744 CONSTANT _EXT4-C.R.ATIME-NS
5752 CONSTANT _EXT4-C.R.MTIME-NS
5760 CONSTANT _EXT4-C.R.CTIME-NS
5768 CONSTANT _EXT4-C.R.BLOCKS
5776 CONSTANT _EXT4-C.R.GEN
5784 CONSTANT _EXT4-C.UUID-LO
5792 CONSTANT _EXT4-C.UUID-HI
5800 CONSTANT _EXT4-C.R.RDEV
5808 CONSTANT _EXT4-C.DIR-BLOCK
9904 CONSTANT _EXT4-C.TREE-BLOCK
14000 CONSTANT _EXT4-C.RECOVERY
14008 CONSTANT _EXT4-C.J.MAXLEN
14016 CONSTANT _EXT4-C.J.FIRST
14024 CONSTANT _EXT4-C.J.START
14032 CONSTANT _EXT4-C.J.SEQUENCE
14040 CONSTANT _EXT4-C.J.FEATURES
14048 CONSTANT _EXT4-C.J.SEED
14056 CONSTANT _EXT4-C.J.COMMITTED
14064 CONSTANT _EXT4-C.J.NEXT-SEQUENCE
14072 CONSTANT _EXT4-C.J.REPLAYED
14080 CONSTANT _EXT4-C.J.HOME-WRITES
14088 CONSTANT _EXT4-C.J.CURSOR
14096 CONSTANT _EXT4-C.SUPER-TORN
14104 CONSTANT _EXT4-C.J.PRIMARY-TORN
14112 CONSTANT _EXT4-C.J.ANCHOR
14120 CONSTANT _EXT4-C.J.WITNESS
14128 CONSTANT _EXT4-C.J.WITNESS-CHECKSUM
14136 CONSTANT _EXT4-C.J.CLEANUP
14144 CONSTANT _EXT4-C.J.INODE-TABLE-BLOCK
14152 CONSTANT _EXT4-C.J.INODE-TABLE-OFF
14160 CONSTANT _EXT4-C.J.INODE-BITMAP-BLOCK
14168 CONSTANT _EXT4-C.J.BLOCK-BITMAP-BLOCK
14176 CONSTANT _EXT4-C.J.INODE-TABLE-BASE
14184 CONSTANT _EXT4-C.J.WITNESS-SUPER-BLOCK
14192 CONSTANT _EXT4-C.J.WITNESS-GDT-BLOCK
14200 CONSTANT _EXT4-C.J.WITNESS-GDT-SPAN
14208 CONSTANT _EXT4-C.J.STRICT
14216 CONSTANT _EXT4-C.J.SUPER-REPAIR-PENDING
14224 CONSTANT _EXT4-C.J.SUPER-REPAIR-SEEN
14232 CONSTANT _EXT4-CTX-RESET-SIZE
14232 CONSTANT _EXT4-C.J.MAP
14240 CONSTANT _EXT4-C.J.MAP-HASH
14248 CONSTANT _EXT4-C.J.MAP-CAPACITY
14256 CONSTANT _EXT4-C.J.MAP-HASH-SLOTS
14264 CONSTANT _EXT4-C.ARENA
14272 CONSTANT _EXT4-C.J.WITNESS-SUPER
15296 CONSTANT _EXT4-C.J.REVOKE-TABLE
15304 CONSTANT _EXT4-C.J.REVOKE-SLOTS
15312 CONSTANT _EXT4-C.J.REVOKE-COUNT
15320 CONSTANT _EXT4-C.J.REVOKE-HITS
15328 CONSTANT _EXT4-C.J.REVOKE-READY
15336 CONSTANT _EXT4-C.J.HEAD
15344 CONSTANT _EXT4-C.J.MAX-TRANSACTION
15352 CONSTANT _EXT4-C.J.MAX-TRANS-DATA
15360 CONSTANT _EXT4-C.J.WRITER
15368 CONSTANT _EXT4-C.J.WITNESS-NEW-CHECKSUM
15376 CONSTANT _EXT4-C.J.WRITE-ACTIVE
15384 CONSTANT _EXT4-C.J.WRITER-CURRENT
15392 CONSTANT _EXT4-C.O.TABLE
15400 CONSTANT _EXT4-C.O.SLOTS
15408 CONSTANT _EXT4-C.O.ACTIVE
15416 CONSTANT _EXT4-C.O.CLEAR-PENDING
15424 CONSTANT _EXT4-C.O.MODERN-ACTIVE
15432 CONSTANT _EXT4-C.O.LEGACY-ACTIVE
15440 CONSTANT _EXT4-C.WCLOCK-XT
15448 CONSTANT _EXT4-C.WCLOCK-CTX
15456 CONSTANT _EXT4-C.J.PROTOCOL-OWNERS
15464 CONSTANT _EXT4-C.J.WRITER-STORE-KIND
15472 CONSTANT _EXT4-C.J.WRITER-ARENA
15480 CONSTANT _EXT4-C.MUTATION-RANGES
15488 CONSTANT _EXT4-C.MUTATION-RANGE-CAP
15496 CONSTANT _EXT4-C.OWNER-CERT-RANGES
15504 CONSTANT _EXT4-C.OWNER-CERT-RANGE-CAP
15512 CONSTANT _EXT4-C.O.RUNTIME-TABLE
15520 CONSTANT _EXT4-C.O.RUNTIME-SLOTS
15528 CONSTANT _EXT4-C.O.RUNTIME-CAPACITY
15536 CONSTANT _EXT4-C.O.RUNTIME-END
15544 CONSTANT _EXT4-C.O.MOUNT-TAIL-MARK
15552 CONSTANT _EXT4-C.XC-PLAN
15560 CONSTANT _EXT4-C.XC-PLAN-SPAN
15568 CONSTANT _EXT4-CTX-SIZE

4 CONSTANT _EXT4-ORPHAN-RECORD-CELLS
_EXT4-ORPHAN-RECORD-CELLS CELLS CONSTANT _EXT4-ORPHAN-RECORD-SIZE
0 CONSTANT _EXT4-OE.INO
1 CELLS CONSTANT _EXT4-OE.KIND
2 CELLS CONSTANT _EXT4-OE.LOCATOR-A
3 CELLS CONSTANT _EXT4-OE.LOCATOR-B
1 CONSTANT _EXT4-OK-LEGACY
2 CONSTANT _EXT4-OK-MODERN

: _EXT4-CTX  ( vfs -- ctx )  V.BCTX @ ;
: _EXT4-READY?  ( vfs -- flag )
    V.BCTX @ DUP 0= IF DROP FALSE EXIT THEN
    _EXT4-C.READY + @ 0<> ;

\ =====================================================================
\  Checked hardware CRC32C adapter
\ =====================================================================

VARIABLE _EXT4-CRC-STATE

: _EXT4-CRC-START  ( seed -- )  0xFFFFFFFF AND _EXT4-CRC-STATE ! ;

: _EXT4-CRC-STATUS>IOR  ( status -- ior )
    DUP 1 = IF
        DROP 1 0 VFS-IOR-D-BINDING VFS-R-UNSUPPORTED VFS-IOR-MAKE EXIT
    THEN
    DUP 2 = IF
        DROP 2 VFS-IOR-F-RETRYABLE VFS-IOR-D-BINDING VFS-R-BUSY
        VFS-IOR-MAKE EXIT
    THEN
    DUP IF 0 VFS-IOR-D-BINDING VFS-R-IO VFS-IOR-MAKE THEN ;

: _EXT4-CRC-CAPABILITY  ( -- ior )
    CRYPTO-CAPS@ 1 AND IF 0 ELSE 1 _EXT4-CRC-STATUS>IOR THEN ;

: _EXT4-CRC-ADD  ( addr len -- ior )
    _EXT4-CRC-STATE @ -ROT CRC32C-RAW?
    DUP IF NIP _EXT4-CRC-STATUS>IOR EXIT THEN
    DROP 0xFFFFFFFF AND _EXT4-CRC-STATE ! 0 ;
: _EXT4-CRC@  ( -- crc )  _EXT4-CRC-STATE @ ;

\ =====================================================================
\  Structured checked volume I/O
\ =====================================================================

VARIABLE _EXT4-IO-VFS
VARIABLE _EXT4-IO-VOL
VARIABLE _EXT4-IO-EXPECTED
VARIABLE _EXT4-IO-COMPLETED
VARIABLE _EXT4-IO-BACKEND
VARIABLE _EXT4-IO-FLAGS
VARIABLE _EXT4-IO-REASON

: _EXT4-LATCH-STALE  ( -- )
    _EXT4-IO-VFS @ ?DUP IF VFS-L-STALE SWAP V.LIFECYCLE ! THEN ;

: _EXT4-MAP-IOR  ( backend-ior -- vfs-ior )
    DUP _EXT4-IO-BACKEND !
    0 _EXT4-IO-FLAGS !
    VFS-R-IO _EXT4-IO-REASON !
    DUP IF
        DUP IOR>FLAGS
        DUP IOR-F-RETRYABLE AND IF
            VFS-IOR-F-RETRYABLE _EXT4-IO-FLAGS +!
        THEN
        DUP IOR-F-PARTIAL AND IF
            VFS-IOR-F-PARTIAL _EXT4-IO-FLAGS +!
        THEN
        DUP IOR-F-CORRUPT AND IF
            VFS-IOR-F-CORRUPT _EXT4-IO-FLAGS +!
            VFS-R-CORRUPT _EXT4-IO-REASON !
        THEN
        DUP IOR-F-UNSUPPORTED AND IF
            VFS-R-UNSUPPORTED _EXT4-IO-REASON !
        THEN
        DUP IOR-F-READONLY AND IF
            VFS-IOR-F-READONLY _EXT4-IO-FLAGS +!
            VFS-R-READONLY _EXT4-IO-REASON !
        THEN
        IOR-F-STALE AND IF
            VFS-IOR-F-STALE _EXT4-IO-FLAGS +!
            VFS-R-STALE _EXT4-IO-REASON !
            _EXT4-LATCH-STALE
        THEN
    THEN
    _EXT4-IO-COMPLETED @ _EXT4-IO-EXPECTED @ <> IF
        VFS-IOR-F-PARTIAL _EXT4-IO-FLAGS DUP @ ROT OR SWAP !
    THEN
    _EXT4-IO-BACKEND @ 0=
    _EXT4-IO-COMPLETED @ _EXT4-IO-EXPECTED @ = AND IF
        DROP 0 EXIT
    THEN
    DROP
    _EXT4-IO-BACKEND @ 0xFFFFFFFF AND
    _EXT4-IO-FLAGS @ VFS-IOR-D-VOLUME _EXT4-IO-REASON @ VFS-IOR-MAKE ;

: _EXT4-READ-SECTORS  ( dma lba count -- ior )
    DUP _EXT4-IO-EXPECTED !
    _EXT4-IO-VOL @ VOL-READ
    SWAP _EXT4-IO-COMPLETED ! _EXT4-MAP-IOR ;

: _EXT4-WRITE-SECTORS  ( dma lba count -- ior )
    DUP _EXT4-IO-EXPECTED !
    _EXT4-IO-VOL @ VOL-WRITE
    SWAP _EXT4-IO-COMPLETED ! _EXT4-MAP-IOR ;

: _EXT4-FLUSH  ( -- ior )
    0 _EXT4-IO-EXPECTED ! 0 _EXT4-IO-COMPLETED !
    _EXT4-IO-VOL @ VOL-FLUSH _EXT4-MAP-IOR ;

: _EXT4-CORRUPT  ( detail -- ior )
    VFS-IOR-F-CORRUPT VFS-IOR-D-FORMAT VFS-R-CORRUPT VFS-IOR-MAKE ;
: _EXT4-UNSUPPORTED  ( detail -- ior )
    0 VFS-IOR-D-FORMAT VFS-R-UNSUPPORTED VFS-IOR-MAKE ;
: _EXT4-READONLY  ( detail -- ior )
    VFS-IOR-F-READONLY VFS-IOR-D-FORMAT VFS-R-READONLY VFS-IOR-MAKE ;

\ =====================================================================
\  Probe
\ =====================================================================

90 CONSTANT EXT4-PROBE-SCORE
CREATE _EXT4-PROBE-BUF _EXT4-SB-SIZE ALLOT
VARIABLE _EXT4-PROBE-VOL

: _EXT4-PROBE  ( volume -- score ior )
    _EXT4-PROBE-VOL !
    _EXT4-CRC-CAPABILITY ?DUP IF 0 SWAP EXIT THEN
    _EXT4-PROBE-VOL @ VOL.SECTOR-SIZE _EXT4-SECTOR <> IF
        0 0 VFS-IOR-D-VOLUME VFS-R-UNSUPPORTED VFS-IOR-MAKE EXIT
    THEN
    0 _EXT4-IO-VFS !
    _EXT4-PROBE-VOL @ _EXT4-IO-VOL !
    _EXT4-PROBE-BUF 2 2 _EXT4-READ-SECTORS
    DUP IF 0 SWAP EXIT THEN DROP
    _EXT4-PROBE-BUF _EXT4-SB.MAGIC + W@ _EXT4-MAGIC = IF
        EXT4-PROBE-SCORE
    ELSE
        0
    THEN 0 ;

\ =====================================================================
\  Generic validation helpers
\ =====================================================================

-1 1 RSHIFT CONSTANT _EXT4-NONNEG-MAX

VARIABLE _EXT4-UA
VARIABLE _EXT4-UB

: _EXT4-UADD?  ( nonnegative-a nonnegative-b -- sum ior )
    _EXT4-UB ! _EXT4-UA !
    _EXT4-UA @ 0< _EXT4-UB @ 0< OR IF
        0 VFS-E-OVERFLOW EXIT
    THEN
    _EXT4-UA @ _EXT4-NONNEG-MAX _EXT4-UB @ - U> IF
        0 VFS-E-OVERFLOW EXIT
    THEN
    _EXT4-UA @ _EXT4-UB @ + 0 ;

: _EXT4-UMUL?  ( nonnegative-a nonnegative-b -- product ior )
    _EXT4-UB ! _EXT4-UA !
    _EXT4-UA @ 0< _EXT4-UB @ 0< OR IF
        0 VFS-E-OVERFLOW EXIT
    THEN
    _EXT4-UA @ 0= _EXT4-UB @ 0= OR IF 0 0 EXIT THEN
    _EXT4-UA @ _EXT4-NONNEG-MAX _EXT4-UB @ / U> IF
        0 VFS-E-OVERFLOW EXIT
    THEN
    _EXT4-UA @ _EXT4-UB @ * 0 ;

VARIABLE _EXT4-RB-BLOCK
VARIABLE _EXT4-RB-CTX

: _EXT4-READ-BLOCK  ( block ctx -- ior )
    _EXT4-RB-CTX ! _EXT4-RB-BLOCK !
    _EXT4-RB-BLOCK @ _EXT4-RB-CTX @ _EXT4-C.BLOCKS + @ >= IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-RB-BLOCK @ _EXT4-RB-CTX @ _EXT4-C.SPB + @ *
    _EXT4-RB-CTX @ _EXT4-C.BLOCK + SWAP
    _EXT4-RB-CTX @ _EXT4-C.SPB + @ _EXT4-READ-SECTORS ;

VARIABLE _EXT4-WB-BUFFER
VARIABLE _EXT4-WB-BLOCK
VARIABLE _EXT4-WB-CTX

: _EXT4-WRITE-BLOCK  ( buffer block ctx -- ior )
    _EXT4-WB-CTX ! _EXT4-WB-BLOCK ! _EXT4-WB-BUFFER !
    \ A caller may use these counters as the certificate for this exact
    \ block attempt.  Clear stale evidence even when validation refuses the
    \ request before VOL-WRITE is dispatched.
    0 _EXT4-IO-EXPECTED ! 0 _EXT4-IO-COMPLETED !
    _EXT4-WB-BLOCK @ _EXT4-WB-CTX @ _EXT4-C.BLOCKS + @ >= IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-WB-BLOCK @ _EXT4-WB-CTX @ _EXT4-C.SPB + @ *
    _EXT4-WB-BUFFER @ SWAP
    _EXT4-WB-CTX @ _EXT4-C.SPB + @ _EXT4-WRITE-SECTORS ;

: _EXT4-BYTES=?  ( a b len -- flag )
    0 ?DO
        2DUP I + C@ SWAP I + C@ <> IF 2DROP FALSE UNLOOP EXIT THEN
    LOOP 2DROP TRUE ;

: _EXT4-BYTES-ZERO?  ( a len -- flag )
    0 ?DO
        DUP I + C@ IF DROP FALSE UNLOOP EXIT THEN
    LOOP DROP TRUE ;

VARIABLE _EXT4-PO-N
VARIABLE _EXT4-PO-B
: _EXT4-POWER-OF?  ( n base -- flag )
    _EXT4-PO-B ! _EXT4-PO-N !
    BEGIN _EXT4-PO-N @ 1 > WHILE
        _EXT4-PO-N @ _EXT4-PO-B @ MOD IF FALSE EXIT THEN
        _EXT4-PO-N @ _EXT4-PO-B @ / _EXT4-PO-N !
    REPEAT
    _EXT4-PO-N @ 1 = ;

: _EXT4-SPARSE-GROUP?  ( group -- flag )
    DUP 0= OVER 1 = OR IF DROP TRUE EXIT THEN
    DUP 3 _EXT4-POWER-OF? IF DROP TRUE EXIT THEN
    DUP 5 _EXT4-POWER-OF? IF DROP TRUE EXIT THEN
    7 _EXT4-POWER-OF? ;

VARIABLE _EXT4-ATT-V
: _EXT4-ATTACHED?  ( vfs -- flag )
    DUP _EXT4-ATT-V ! V.VOLUME @
    DUP 0= IF DROP FALSE EXIT THEN
    DUP VOL-VALID? 0= IF DROP FALSE EXIT THEN
    DUP VOL-STALE? IF DROP FALSE EXIT THEN
    DUP VOL.COOKIE _EXT4-ATT-V @ V.VOL-COOKIE @ =
    SWAP VOL.MEDIA-GEN _EXT4-ATT-V @ V.MEDIA-GEN @ = AND ;

\ =====================================================================
\  Superblock validation and geometry admission
\ =====================================================================

VARIABLE _EXT4-SV-CTX
VARIABLE _EXT4-SV-SB
VARIABLE _EXT4-SV-STORED
VARIABLE _EXT4-SV-LOG
VARIABLE _EXT4-SV-RO
VARIABLE _EXT4-SV-GROUPS
VARIABLE _EXT4-SV-INCOMPAT
VARIABLE _EXT4-SI-SB
VARIABLE _EXT4-SI-INCOMPAT
VARIABLE _EXT4-SI-RO
VARIABLE _EXT4-SI-STATE
VARIABLE _EXT4-SI-STORED
VARIABLE _EXT4-SI-CALC

: _EXT4-STAMP-SUPER-CHECKSUM  ( sb -- ior )
    DUP _EXT4-SB.CHECKSUM + 0 SWAP L!
    0xFFFFFFFF _EXT4-CRC-START
    DUP _EXT4-SB.CHECKSUM _EXT4-CRC-ADD ?DUP IF NIP EXIT THEN
    _EXT4-CRC@ SWAP _EXT4-SB.CHECKSUM + L! 0 ;

: _EXT4-PREPARE-CLEAN-SUPER  ( sb -- ior )
    DUP _EXT4-SB.INCOMPAT + DUP L@
    _EXT4-INCOMPAT-RECOVER INVERT AND SWAP L!
    1 OVER _EXT4-SB.STATE + W!
    _EXT4-STAMP-SUPER-CHECKSUM ;

\ The completed recovery endpoint additionally retires the modern-orphan
\ authority bit.  Keep this distinct from PREPARE-CLEAN-SUPER: AKW1 activation
\ must authenticate the exact old clean image, including ORPHAN_PRESENT.
: _EXT4-PREPARE-RECOVERED-SUPER  ( sb -- ior )
    DUP _EXT4-PREPARE-CLEAN-SUPER ?DUP IF NIP EXIT THEN
    DUP _EXT4-SB.RO-COMPAT + DUP L@
    _EXT4-RO-ORPHAN-PRESENT INVERT AND SWAP L!
    _EXT4-STAMP-SUPER-CHECKSUM ;

: _EXT4-PREPARE-DIRTY-SUPER  ( sb -- ior )
    DUP _EXT4-SB.INCOMPAT + DUP L@
    _EXT4-INCOMPAT-RECOVER OR SWAP L!
    1 OVER _EXT4-SB.STATE + W!
    _EXT4-STAMP-SUPER-CHECKSUM ;

: _EXT4-SUPER-CHECKSUM?  ( sb -- flag ior )
    DUP _EXT4-SB.CHECKSUM + L@ _EXT4-SV-STORED !
    0xFFFFFFFF _EXT4-CRC-START
    _EXT4-SB.CHECKSUM _EXT4-CRC-ADD ?DUP IF 0 SWAP EXIT THEN
    _EXT4-CRC@ _EXT4-SV-STORED @ = 0 ;

: _EXT4-SUPER-SEED?  ( sb -- flag ior )
    DUP _EXT4-SB.CSUM-SEED + L@ >R
    0xFFFFFFFF _EXT4-CRC-START
    _EXT4-SB.UUID + 16 _EXT4-CRC-ADD ?DUP IF
        R> DROP 0 SWAP EXIT
    THEN
    _EXT4-CRC@ R> = 0 ;

\ Return the checksum of the intended post-recovery primary superblock while
\ restoring every temporarily changed byte.  A durable journal anchor records
\ this value before RECOVER can be cleared across its two-sector write.
: _EXT4-INTENDED-SUPER-CHECKSUM  ( sb -- crc ior )
    DUP _EXT4-SI-SB !
    DUP _EXT4-SB.INCOMPAT + L@ _EXT4-SI-INCOMPAT !
    DUP _EXT4-SB.STATE + W@ _EXT4-SI-STATE !
    _EXT4-SB.CHECKSUM + L@ _EXT4-SI-STORED !
    _EXT4-SI-SB @ _EXT4-PREPARE-CLEAN-SUPER
    DUP IF
        _EXT4-SI-INCOMPAT @ _EXT4-SI-SB @ _EXT4-SB.INCOMPAT + L!
        _EXT4-SI-STATE @ _EXT4-SI-SB @ _EXT4-SB.STATE + W!
        _EXT4-SI-STORED @ _EXT4-SI-SB @ _EXT4-SB.CHECKSUM + L!
        0 SWAP EXIT
    THEN DROP
    _EXT4-SI-SB @ _EXT4-SB.CHECKSUM + L@ _EXT4-SI-CALC !
    _EXT4-SI-INCOMPAT @ _EXT4-SI-SB @ _EXT4-SB.INCOMPAT + L!
    _EXT4-SI-STATE @ _EXT4-SI-SB @ _EXT4-SB.STATE + W!
    _EXT4-SI-STORED @ _EXT4-SI-SB @ _EXT4-SB.CHECKSUM + L!
    _EXT4-SI-CALC @ 0 ;

: _EXT4-INTENDED-RECOVERED-SUPER-CHECKSUM  ( sb -- crc ior )
    DUP _EXT4-SI-SB !
    DUP _EXT4-SB.INCOMPAT + L@ _EXT4-SI-INCOMPAT !
    DUP _EXT4-SB.RO-COMPAT + L@ _EXT4-SI-RO !
    DUP _EXT4-SB.STATE + W@ _EXT4-SI-STATE !
    _EXT4-SB.CHECKSUM + L@ _EXT4-SI-STORED !
    _EXT4-SI-SB @ _EXT4-PREPARE-RECOVERED-SUPER
    DUP IF
        _EXT4-SI-INCOMPAT @ _EXT4-SI-SB @ _EXT4-SB.INCOMPAT + L!
        _EXT4-SI-RO @ _EXT4-SI-SB @ _EXT4-SB.RO-COMPAT + L!
        _EXT4-SI-STATE @ _EXT4-SI-SB @ _EXT4-SB.STATE + W!
        _EXT4-SI-STORED @ _EXT4-SI-SB @ _EXT4-SB.CHECKSUM + L!
        0 SWAP EXIT
    THEN DROP
    _EXT4-SI-SB @ _EXT4-SB.CHECKSUM + L@ _EXT4-SI-CALC !
    _EXT4-SI-INCOMPAT @ _EXT4-SI-SB @ _EXT4-SB.INCOMPAT + L!
    _EXT4-SI-RO @ _EXT4-SI-SB @ _EXT4-SB.RO-COMPAT + L!
    _EXT4-SI-STATE @ _EXT4-SI-SB @ _EXT4-SB.STATE + W!
    _EXT4-SI-STORED @ _EXT4-SI-SB @ _EXT4-SB.CHECKSUM + L!
    _EXT4-SI-CALC @ 0 ;

: _EXT4-INTENDED-DIRTY-SUPER-CHECKSUM  ( sb -- crc ior )
    DUP _EXT4-SI-SB !
    DUP _EXT4-SB.INCOMPAT + L@ _EXT4-SI-INCOMPAT !
    DUP _EXT4-SB.STATE + W@ _EXT4-SI-STATE !
    _EXT4-SB.CHECKSUM + L@ _EXT4-SI-STORED !
    _EXT4-SI-SB @ _EXT4-PREPARE-DIRTY-SUPER
    DUP IF
        _EXT4-SI-INCOMPAT @ _EXT4-SI-SB @ _EXT4-SB.INCOMPAT + L!
        _EXT4-SI-STATE @ _EXT4-SI-SB @ _EXT4-SB.STATE + W!
        _EXT4-SI-STORED @ _EXT4-SI-SB @ _EXT4-SB.CHECKSUM + L!
        0 SWAP EXIT
    THEN DROP
    _EXT4-SI-SB @ _EXT4-SB.CHECKSUM + L@ _EXT4-SI-CALC !
    _EXT4-SI-INCOMPAT @ _EXT4-SI-SB @ _EXT4-SB.INCOMPAT + L!
    _EXT4-SI-STATE @ _EXT4-SI-SB @ _EXT4-SB.STATE + W!
    _EXT4-SI-STORED @ _EXT4-SI-SB @ _EXT4-SB.CHECKSUM + L!
    _EXT4-SI-CALC @ 0 ;

VARIABLE _EXT4-SRP-SB
VARIABLE _EXT4-SRP-RECOVERY

\ These fields must let the next mount reach the redundant recovery witness.
\ Keep the ordinary mount and replay-candidate gates on one predicate path.
: _EXT4-VALIDATE-SUPER-RETRY-EARLY  ( sb recovery -- ior )
    _EXT4-SRP-RECOVERY ! _EXT4-SRP-SB !
    _EXT4-SRP-SB @ _EXT4-SB.STATE + W@ DUP 1 INVERT AND IF
        DROP EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    1 <> _EXT4-SRP-RECOVERY @ 0= AND IF
        EXT4-D-RECOVERY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SRP-SB @ _EXT4-SB.ERRORS + W@ 2 <> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    0 ;

: _EXT4-VALIDATE-SUPER-RETRY-LATE  ( sb -- ior )
    _EXT4-SRP-SB !
    _EXT4-SRP-SB @ _EXT4-SB.INODE-SIZE + W@ 256 = IF
        _EXT4-SRP-SB @ _EXT4-SB.MIN-EXTRA + W@ 32 <
        _EXT4-SRP-SB @ _EXT4-SB.WANT-EXTRA + W@ 32 < OR IF
            EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
        THEN
    THEN
    _EXT4-SRP-SB @ _EXT4-SB.LOG-FLEX + C@ 4 <> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SRP-SB @ _EXT4-SB.FIRST-INO + L@ 11 < IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    0 ;

VARIABLE _EXT4-SCB-SB
VARIABLE _EXT4-SCB-CTX

\ A checksum-valid image cannot use the prefix-tear exception for counters.
: _EXT4-VALIDATE-SUPER-COUNTER-BOUNDS  ( sb ctx -- ior )
    _EXT4-SCB-CTX ! _EXT4-SCB-SB !
    _EXT4-SCB-SB @ _EXT4-SB.RBLOCKS-HI + L@
    _EXT4-SCB-SB @ _EXT4-SB.FREE-BLOCKS-HI + L@ OR IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SCB-SB @ _EXT4-SB.RBLOCKS-LO + L@
    _EXT4-SCB-CTX @ _EXT4-C.BLOCKS + @ U> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SCB-SB @ _EXT4-SB.FREE-BLOCKS-LO + L@
    _EXT4-SCB-CTX @ _EXT4-C.BLOCKS + @ U> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SCB-SB @ _EXT4-SB.FREE-INODES + L@
    _EXT4-SCB-CTX @ _EXT4-C.INODES + @ U> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    0 ;

: _EXT4-VALIDATE-SUPER  ( ctx vfs -- ior )
    DROP _EXT4-SV-CTX !
    _EXT4-SV-CTX @ _EXT4-C.SB + _EXT4-SV-SB !
    0 _EXT4-SV-CTX @ _EXT4-C.RECOVERY + !
    0 _EXT4-SV-CTX @ _EXT4-C.SUPER-TORN + !
    _EXT4-SV-SB @ _EXT4-SB.MAGIC + W@ _EXT4-MAGIC <> IF
        EXT4-D-MAGIC _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SUPER-CHECKSUM? ?DUP IF NIP EXIT THEN 0= IF
        -1 _EXT4-SV-CTX @ _EXT4-C.SUPER-TORN + !
    THEN
    _EXT4-SV-SB @ _EXT4-SUPER-SEED? ?DUP IF NIP EXIT THEN 0= IF
        EXT4-D-SUPER-CHECKSUM _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.REVISION + L@ 1 <
    _EXT4-SV-SB @ _EXT4-SB.CREATOR + L@ 0<> OR IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.COMPAT + L@ _EXT4-COMPAT-V1 <> IF
        EXT4-D-FEATURE _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.INCOMPAT + L@ DUP _EXT4-SV-INCOMPAT !
    _EXT4-INCOMPAT-RECOVER AND IF
        -1 _EXT4-SV-CTX @ _EXT4-C.RECOVERY + !
    THEN
    _EXT4-SV-INCOMPAT @ _EXT4-INCOMPAT-RECOVER INVERT AND
    _EXT4-INCOMPAT-V1 <> IF
        EXT4-D-FEATURE _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.RO-COMPAT + L@
    DUP _EXT4-RO-REFUSED AND IF
        DROP EXT4-D-FEATURE _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-RO-READONLY _EXT4-RO-ORPHAN-PRESENT OR INVERT AND
    _EXT4-SV-RO !
    _EXT4-SV-SB @ _EXT4-SB.INODE-SIZE + W@ DUP
    128 = IF
        DROP _EXT4-SV-RO @ _EXT4-RO-I128-V1 AND
        _EXT4-RO-I128-V1 <>
    ELSE
        256 <> _EXT4-SV-RO @ _EXT4-RO-V1 AND
        _EXT4-RO-V1 <> OR
    THEN IF EXT4-D-FEATURE _EXT4-UNSUPPORTED EXIT THEN
    _EXT4-SV-SB @ _EXT4-SV-CTX @ _EXT4-C.RECOVERY + @
    _EXT4-VALIDATE-SUPER-RETRY-EARLY ?DUP IF EXIT THEN
    _EXT4-SV-SB @ _EXT4-SB.LOG-BLOCK + L@ DUP _EXT4-SV-LOG ! 2 > IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.LOG-CLUSTER + L@ _EXT4-SV-LOG @ <> IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    1024 _EXT4-SV-LOG @ LSHIFT DUP
    _EXT4-SV-CTX @ _EXT4-C.BSIZE + !
    512 / _EXT4-SV-CTX @ _EXT4-C.SPB + !
    _EXT4-SV-SB @ _EXT4-SB.BLOCKS-HI + L@ 0<> IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.BLOCKS-LO + L@
    _EXT4-SV-CTX @ _EXT4-C.BLOCKS + !
    _EXT4-SV-SB @ _EXT4-SB.FIRST-DATA + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.FIRST + !
    _EXT4-SV-LOG @ 0= IF 1 <> ELSE 0<> THEN IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-CTX @ _EXT4-C.BLOCKS + @
    _EXT4-SV-CTX @ _EXT4-C.FIRST + @ <= IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-CTX @ _EXT4-C.BLOCKS + @
    _EXT4-SV-CTX @ _EXT4-C.SPB + @ *
    _EXT4-IO-VOL @ VOL.SECTORS U> IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.BPG + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.BPG + !
    _EXT4-SV-CTX @ _EXT4-C.BSIZE + @ 8 * <> IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.CPG + L@
    _EXT4-SV-CTX @ _EXT4-C.BPG + @ <> IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.IPG + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.IPG + !
    _EXT4-SV-CTX @ _EXT4-C.BPG + @
    _EXT4-SV-CTX @ _EXT4-C.BSIZE + @ * 16384 / <> IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-CTX @ _EXT4-C.BLOCKS + @
    _EXT4-SV-CTX @ _EXT4-C.FIRST + @ -
    _EXT4-SV-CTX @ _EXT4-C.BPG + @ 1- +
    _EXT4-SV-CTX @ _EXT4-C.BPG + @ /
    DUP _EXT4-SV-GROUPS ! _EXT4-SV-CTX @ _EXT4-C.GROUPS + !
    _EXT4-SV-GROUPS @ 0= IF EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT THEN
    _EXT4-SV-SB @ _EXT4-SB.INODES + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.INODES + !
    _EXT4-SV-GROUPS @ _EXT4-SV-CTX @ _EXT4-C.IPG + @ * <> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.INODE-SIZE + W@
    _EXT4-SV-CTX @ _EXT4-C.ISIZE + !
    _EXT4-SV-SB @ _EXT4-SB.DESC-SIZE + W@ DUP
    _EXT4-SV-CTX @ _EXT4-C.DSIZE + !
    _EXT4-DESC-SIZE <> IF EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT THEN
    _EXT4-SV-SB @ _EXT4-VALIDATE-SUPER-RETRY-LATE ?DUP IF EXIT THEN
    _EXT4-SV-SB @ _EXT4-SB.CSUM-TYPE + C@ 1 <> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.JOURNAL-INO + L@ 8 <> IF
        EXT4-D-JOURNAL _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.ORPHAN-INO + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.ORPHAN-INO + !
    DUP 0= SWAP _EXT4-SV-CTX @ _EXT4-C.INODES + @ > OR IF
        EXT4-D-ORPHAN-FILE _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.RBLOCKS-LO + L@
    _EXT4-SV-CTX @ _EXT4-C.RESERVED-BLOCKS + !
    _EXT4-SV-SB @ _EXT4-SB.FREE-BLOCKS-LO + L@
    _EXT4-SV-CTX @ _EXT4-C.FREE-BLOCKS + !
    _EXT4-SV-SB @ _EXT4-SB.FREE-INODES + L@
    _EXT4-SV-CTX @ _EXT4-C.FREE-INODES + !
    \ Prefixes of two checksum-valid home-super candidates can transiently
    \ mix mutable counters.  Their bounds become authoritative only after
    \ replay and strict checksum validation; immutable geometry is witnessed
    \ independently by sparse group 1 before any journal read.
    _EXT4-SV-CTX @ _EXT4-C.SUPER-TORN + @ 0= IF
        _EXT4-SV-SB @ _EXT4-SV-CTX @
        _EXT4-VALIDATE-SUPER-COUNTER-BOUNDS ?DUP IF EXIT THEN
    THEN
    _EXT4-SV-SB @ _EXT4-SB.CSUM-SEED + L@
    _EXT4-SV-CTX @ _EXT4-C.SEED + !
    _EXT4-SV-SB @ _EXT4-SB.UUID + @
    _EXT4-SV-CTX @ _EXT4-C.UUID-LO + !
    _EXT4-SV-SB @ _EXT4-SB.UUID 8 + + @
    _EXT4-SV-CTX @ _EXT4-C.UUID-HI + !
    0 ;
