\ Credential-vault dependency doubles for one bounded composition fixture.
\
\ Load this file before the runner-packaged cv-source.f.  That source is the
\ exact production credential-vault body with only its statically qualified
\ REQUIRE directives elided; these doubles supply those dependency contracts.
\
\ The doubles retain the production status values, public geometry, field
\ offsets, and callback ABIs used by credential-vault.f.  They deliberately
\ own one deterministic directory tree and one persistent snapshot record;
\ they qualify vault composition, not cryptography or crash durability.

PROVIDED cv-test-deps
PROVIDED akashic-memory-span
PROVIDED akashic-caller-span
PROVIDED akashic-runtime-identity
PROVIDED akashic-entropy
PROVIDED akashic-guard
PROVIDED akashic-vfs
PROVIDED akashic-sealed-record
PROVIDED akashic-vfs-fixed-snapshot

\ =====================================================================
\  Checked span and caller-span vocabulary
\ =====================================================================

: MSPAN-NONWRAPPING?  ( address length -- flag )
    DUP 0< IF 2DROP 0 EXIT THEN
    >R DUP R@ + SWAP U< 0= R> DROP ;

: MSPAN-OVERLAP?  ( a1 u1 a2 u2 -- flag )
    2OVER MSPAN-NONWRAPPING? 0= IF 2DROP 2DROP 0 EXIT THEN
    2DUP MSPAN-NONWRAPPING? 0= IF 2DROP 2DROP 0 EXIT THEN
    DUP 0= IF 2DROP 2DROP 0 EXIT THEN
    2 PICK 0= IF 2DROP 2DROP 0 EXIT THEN
    2OVER + >R OVER R> U< >R
    + >R DROP R> U< R> AND ;

16 CONSTANT MSPAN-SET-ENTRY-SIZE
16 CONSTANT MSPAN-SET-HEADER-SIZE

: MSPAN-SET-BYTES  ( capacity -- bytes|0 )
    DUP 0< IF DROP 0 EXIT THEN
    DUP -1 5 RSHIFT 1- U> IF DROP 0 EXIT THEN
    MSPAN-SET-ENTRY-SIZE * MSPAN-SET-HEADER-SIZE + ;

: MSPAN-SET.COUNT      ( set -- a ) ;
: _MSPAN-SET.CAPACITY  ( set -- a ) 8 + ;
: _MSPAN-SET.ENTRIES   ( set -- a ) 16 + ;

: _MSPAN-SET-NTH  ( index set -- entry )
    _MSPAN-SET.ENTRIES SWAP MSPAN-SET-ENTRY-SIZE * + ;

: MSPAN-SET-COUNT@  ( set -- count ) MSPAN-SET.COUNT @ ;
: MSPAN-SET-CAPACITY@  ( set -- capacity )
    _MSPAN-SET.CAPACITY @ ;

0 CONSTANT CALLER-SPAN-S-OK
2 CONSTANT CALLER-SPAN-S-RANGE
3 CONSTANT CALLER-SPAN-S-PROTECTED
4 CONSTANT CALLER-SPAN-S-PLATFORM

0x7FFFFFFFFFFF0000 CONSTANT _CVTD-RANGE-SPAN

: CALLER-SPAN-STATUS  ( address length -- status )
    2DUP MSPAN-NONWRAPPING? 0= IF
        2DROP CALLER-SPAN-S-RANGE EXIT
    THEN
    OVER _CVTD-RANGE-SPAN =
    OVER 16 = AND IF
        2DROP CALLER-SPAN-S-RANGE EXIT
    THEN
    2DROP CALLER-SPAN-S-OK ;

\ These model dependency-private regions that the vault must exclude.
: _VFSNAP-DEPENDENCY-ALIASES?  ( address length -- flag )
    2DROP 0 ;

: _S256-LOCAL-RESERVED-OVERLAP?  ( address length -- flag )
    2DROP 0 ;

\ =====================================================================
\  Guard vocabulary
\ =====================================================================

32 CONSTANT GUARD-SPIN-SIZE

: GUARD  ( "name" -- )
    CREATE 0 , 0 , 0 , 0 , DOES> ;

: WITH-GUARD  ( ... xt guard -- ... )
    DROP EXECUTE ;

CREATE _aes-gcm-guard 0 , 0 , 0 , 0 ,

\ =====================================================================
\  RID and deterministic entropy vocabulary
\ =====================================================================

32 CONSTANT RID-SIZE

: RID-CLEAR  ( id -- )
    RID-SIZE 0 FILL ;

: RID-COPY  ( source destination -- )
    2DUP = IF 2DROP EXIT THEN
    RID-SIZE MOVE ;

: RID=  ( first second -- flag )
    2DUP = IF 2DROP -1 EXIT THEN
    DUP 0= IF 2DROP 0 EXIT THEN
    OVER 0= IF 2DROP 0 EXIT THEN
    SWAP RID-SIZE ROT RID-SIZE COMPARE 0= ;

: RID-ZERO?  ( id -- flag )
    DUP 0= IF DROP -1 EXIT THEN
    DUP @ 0=
    OVER 8 + @ 0= AND
    OVER 16 + @ 0= AND
    SWAP 24 + @ 0= AND ;

: RID-PRESENT?  ( id -- flag )
    RID-ZERO? 0= ;

0 CONSTANT ENTROPY-S-OK
1 CONSTANT ENTROPY-S-UNAVAILABLE
2 CONSTANT ENTROPY-S-RANGE
3 CONSTANT ENTROPY-S-PROTECTED

VARIABLE _CVTD-ENTROPY-BYTE

: _CVTD-ENTROPY-WRITE  ( destination length -- )
    BEGIN
        DUP
    WHILE
        _CVTD-ENTROPY-BYTE @ 255 AND 2 PICK C!
        1 _CVTD-ENTROPY-BYTE +!
        1- SWAP 1+ SWAP
    REPEAT
    2DROP ;

: ENTROPY-FILL  ( destination length -- status )
    DUP 0< IF 2DROP ENTROPY-S-RANGE EXIT THEN
    OVER 0= OVER 0> AND IF 2DROP ENTROPY-S-RANGE EXIT THEN
    2DUP _CVTD-ENTROPY-WRITE
    2DROP ENTROPY-S-OK ;

: ENTROPY-READY?  ( -- flag ) -1 ;

\ =====================================================================
\  Minimal VFS topology vocabulary
\ =====================================================================

1 CONSTANT VFS-T-FILE
2 CONSTANT VFS-T-DIR

1 CONSTANT VFS-RP-NOFOLLOW-FINAL

2  CONSTANT VFS-R-NOENT
3  CONSTANT VFS-R-EXISTS
4  CONSTANT VFS-R-NOTDIR
10 CONSTANT VFS-R-CORRUPT
11 CONSTANT VFS-R-UNSUPPORTED
18 CONSTANT VFS-R-LOOP

208 CONSTANT VFS-DESC-SIZE

: V.CWD  ( vfs -- a ) 80 + ;
: IN.TYPE  ( inode -- a ) ;

: VFS-IOR-REASON  ( ior -- reason )
    0xFFFF AND ;

CREATE _CVTD-ROOT-INODE   VFS-T-DIR ,
CREATE _CVTD-SHARD1-INODE VFS-T-DIR ,
CREATE _CVTD-SHARD2-INODE VFS-T-DIR ,

VARIABLE _CVTD-VFS-CURRENT
VARIABLE _CVTD-SHARD1-PRESENT
VARIABLE _CVTD-SHARD2-PRESENT

: VFS-CUR  ( -- vfs )
    _CVTD-VFS-CURRENT @ ;

: VFS-USE  ( vfs -- )
    _CVTD-VFS-CURRENT ! ;

VARIABLE _CVTD-RP-A
VARIABLE _CVTD-RP-U
VARIABLE _CVTD-RP-VFS

: VFS-RESOLVE-POLICY?
  ( path-a path-u policy vfs -- inode ior )
    _CVTD-RP-VFS ! DROP _CVTD-RP-U ! _CVTD-RP-A !
    _CVTD-RP-VFS @ 0= IF 0 VFS-R-NOENT EXIT THEN
    _CVTD-RP-A @ _CVTD-RP-U @ S" /vault" COMPARE 0= IF
        _CVTD-ROOT-INODE 0
    ELSE
        0 VFS-R-NOENT
    THEN ;

VARIABLE _CVTD-LK-A
VARIABLE _CVTD-LK-U
VARIABLE _CVTD-LK-PARENT
VARIABLE _CVTD-LK-VFS

: VFS-LOOKUP
  ( name-a name-u parent vfs -- inode ior )
    _CVTD-LK-VFS ! _CVTD-LK-PARENT !
    _CVTD-LK-U ! _CVTD-LK-A !
    _CVTD-LK-VFS @ 0= IF 0 VFS-R-NOENT EXIT THEN
    _CVTD-LK-PARENT @ _CVTD-ROOT-INODE =
    _CVTD-LK-U @ 20 = AND IF
        _CVTD-SHARD1-PRESENT @ IF
            _CVTD-SHARD1-INODE 0
        ELSE
            0 VFS-R-NOENT
        THEN
        EXIT
    THEN
    _CVTD-LK-PARENT @ _CVTD-SHARD1-INODE =
    _CVTD-LK-U @ 22 = AND IF
        _CVTD-SHARD2-PRESENT @ IF
            _CVTD-SHARD2-INODE 0
        ELSE
            0 VFS-R-NOENT
        THEN
        EXIT
    THEN
    0 VFS-R-NOENT ;

VARIABLE _CVTD-MD-U
VARIABLE _CVTD-MD-VFS

: VFS-MKDIR  ( name-a name-u vfs -- ior )
    _CVTD-MD-VFS ! _CVTD-MD-U ! DROP
    _CVTD-MD-VFS @ 0= IF VFS-R-NOENT EXIT THEN
    _CVTD-MD-VFS @ V.CWD @ _CVTD-ROOT-INODE =
    _CVTD-MD-U @ 20 = AND IF
        _CVTD-SHARD1-PRESENT @ IF VFS-R-EXISTS EXIT THEN
        -1 _CVTD-SHARD1-PRESENT !
        0 EXIT
    THEN
    _CVTD-MD-VFS @ V.CWD @ _CVTD-SHARD1-INODE =
    _CVTD-MD-U @ 22 = AND IF
        _CVTD-SHARD2-PRESENT @ IF VFS-R-EXISTS EXIT THEN
        -1 _CVTD-SHARD2-PRESENT !
        0 EXIT
    THEN
    VFS-R-NOTDIR ;

: VFS-SYNC  ( vfs -- ior )
    DROP 0 ;

: VFS-TRANSACTION  ( ... xt -- ... )
    EXECUTE ;

\ =====================================================================
\  Sealed-record geometry and deterministic record double
\ =====================================================================

0  CONSTANT SEALED-RECORD-S-OK
1  CONSTANT SEALED-RECORD-S-INVALID
2  CONSTANT SEALED-RECORD-S-CAPACITY
3  CONSTANT SEALED-RECORD-S-ALIAS
4  CONSTANT SEALED-RECORD-S-BUSY
5  CONSTANT SEALED-RECORD-S-KEY
6  CONSTANT SEALED-RECORD-S-CALLBACK
7  CONSTANT SEALED-RECORD-S-ENTROPY
8  CONSTANT SEALED-RECORD-S-CRYPTO
9  CONSTANT SEALED-RECORD-S-AUTH
10 CONSTANT SEALED-RECORD-S-FORMAT
11 CONSTANT SEALED-RECORD-S-MISMATCH
12 CONSTANT SEALED-RECORD-S-RANGE
13 CONSTANT SEALED-RECORD-S-PROTECTED
14 CONSTANT SEALED-RECORD-S-PLATFORM
15 CONSTANT SEALED-RECORD-S-INTERNAL

32    CONSTANT SEALED-RECORD-ID-SIZE
32    CONSTANT SEALED-RECORD-ROOT-KEY-SIZE
32    CONSTANT SEALED-RECORD-SALT-SIZE
160   CONSTANT SEALED-RECORD-HEADER-SIZE
16    CONSTANT SEALED-RECORD-TAG-SIZE
176   CONSTANT SEALED-RECORD-OVERHEAD
65536 CONSTANT SEALED-RECORD-DATA-MAX
65712 CONSTANT SEALED-RECORD-SIZE-MAX
66568 CONSTANT SEALED-RECORD-WORKSPACE-SIZE

: SEALED-RECORD-SIZE  ( data-u -- record-u|0 )
    DUP 0> 0= IF DROP 0 EXIT THEN
    DUP SEALED-RECORD-DATA-MAX U> IF DROP 0 EXIT THEN
    SEALED-RECORD-OVERHEAD + ;

 0 CONSTANT _CVTD-SRD-INPUT
 8 CONSTANT _CVTD-SRD-INPUT-U
16 CONSTANT _CVTD-SRD-KEY-ID
24 CONSTANT _CVTD-SRD-RECORD-ID
32 CONSTANT _CVTD-SRD-PURPOSE
40 CONSTANT _CVTD-SRD-REVISION
48 CONSTANT _CVTD-SRD-RESOLVER-XT
56 CONSTANT _CVTD-SRD-RESOLVER-CONTEXT
64 CONSTANT _CVTD-SRD-OUTPUT
72 CONSTANT _CVTD-SRD-OUTPUT-CAP
80 CONSTANT SEALED-RECORD-DESCRIPTOR-SIZE

: SEALED-RECORD-D.INPUT
    _CVTD-SRD-INPUT + ;
: SEALED-RECORD-D.INPUT-U
    _CVTD-SRD-INPUT-U + ;
: SEALED-RECORD-D.KEY-ID
    _CVTD-SRD-KEY-ID + ;
: SEALED-RECORD-D.RECORD-ID
    _CVTD-SRD-RECORD-ID + ;
: SEALED-RECORD-D.PURPOSE
    _CVTD-SRD-PURPOSE + ;
: SEALED-RECORD-D.REVISION
    _CVTD-SRD-REVISION + ;
: SEALED-RECORD-D.RESOLVER-XT
    _CVTD-SRD-RESOLVER-XT + ;
: SEALED-RECORD-D.RESOLVER-CONTEXT
    _CVTD-SRD-RESOLVER-CONTEXT + ;
: SEALED-RECORD-D.OUTPUT
    _CVTD-SRD-OUTPUT + ;
: SEALED-RECORD-D.OUTPUT-CAP
    _CVTD-SRD-OUTPUT-CAP + ;

: SEALED-RECORD-DESCRIPTOR-CLEAR  ( descriptor -- status )
    DUP 0= IF DROP SEALED-RECORD-S-INVALID EXIT THEN
    SEALED-RECORD-DESCRIPTOR-SIZE 0 FILL
    SEALED-RECORD-S-OK ;

: _CVTD-BE64!  ( nonnegative-u destination -- )
    >R
    DUP 56 RSHIFT 255 AND R@      C!
    DUP 48 RSHIFT 255 AND R@ 1+   C!
    DUP 40 RSHIFT 255 AND R@ 2 +  C!
    DUP 32 RSHIFT 255 AND R@ 3 +  C!
    DUP 24 RSHIFT 255 AND R@ 4 +  C!
    DUP 16 RSHIFT 255 AND R@ 5 +  C!
    DUP  8 RSHIFT 255 AND R@ 6 +  C!
        255 AND R@ 7 + C!
    R> DROP ;

: _CVTD-BE64@  ( source -- nonnegative-u )
    >R
    R@     C@ 56 LSHIFT
    R@ 1+  C@ 48 LSHIFT OR
    R@ 2 + C@ 40 LSHIFT OR
    R@ 3 + C@ 32 LSHIFT OR
    R@ 4 + C@ 24 LSHIFT OR
    R@ 5 + C@ 16 LSHIFT OR
    R@ 6 + C@  8 LSHIFT OR
    R> 7 + C@ OR ;

VARIABLE _CVTD-SR-D
VARIABLE _CVTD-SR-W
VARIABLE _CVTD-SR-IN
VARIABLE _CVTD-SR-OUT
VARIABLE _CVTD-SR-DATA-U
VARIABLE _CVTD-SR-TOTAL-U
VARIABLE _CVTD-SR-STATUS

: _CVTD-ROOT-CONSUME  ( root-key root-key-u context -- status )
    DROP
    DUP SEALED-RECORD-ROOT-KEY-SIZE <> IF
        2DROP SEALED-RECORD-S-CALLBACK EXIT
    THEN
    OVER 0= IF 2DROP SEALED-RECORD-S-CALLBACK EXIT THEN
    2DROP SEALED-RECORD-S-OK ;

: _CVTD-RESOLVE-ROOT  ( descriptor -- status )
    >R
    R@ SEALED-RECORD-D.KEY-ID @ SEALED-RECORD-ID-SIZE
    ['] _CVTD-ROOT-CONSUME 0
    R@ SEALED-RECORD-D.RESOLVER-CONTEXT @
    R@ SEALED-RECORD-D.RESOLVER-XT @ EXECUTE
    R> DROP ;

: _CVTD-SR-WIPE  ( -- )
    _CVTD-SR-W @ ?DUP IF
        SEALED-RECORD-WORKSPACE-SIZE 0 FILL
    THEN ;

: _CVTD-SEAL-HEADER  ( -- )
    0x414B535345414C31 _CVTD-SR-OUT @      _CVTD-BE64!
    1                  _CVTD-SR-OUT @ 8 +  _CVTD-BE64!
    SEALED-RECORD-HEADER-SIZE
                       _CVTD-SR-OUT @ 16 + _CVTD-BE64!
    _CVTD-SR-TOTAL-U @ _CVTD-SR-OUT @ 24 + _CVTD-BE64!
    _CVTD-SR-DATA-U @  _CVTD-SR-OUT @ 32 + _CVTD-BE64!
    _CVTD-SR-D @ SEALED-RECORD-D.PURPOSE @
                       _CVTD-SR-OUT @ 40 + _CVTD-BE64!
    _CVTD-SR-D @ SEALED-RECORD-D.REVISION @
                       _CVTD-SR-OUT @ 48 + _CVTD-BE64!
    0                  _CVTD-SR-OUT @ 56 + _CVTD-BE64!
    _CVTD-SR-D @ SEALED-RECORD-D.KEY-ID @
        _CVTD-SR-OUT @ 64 + SEALED-RECORD-ID-SIZE MOVE
    _CVTD-SR-D @ SEALED-RECORD-D.RECORD-ID @
        _CVTD-SR-OUT @ 96 + SEALED-RECORD-ID-SIZE MOVE
    _CVTD-SR-OUT @ 128 + SEALED-RECORD-SALT-SIZE 1 FILL ;

: SEALED-RECORD-SEAL
  ( descriptor workspace -- written status )
    _CVTD-SR-W ! _CVTD-SR-D !
    _CVTD-SR-W @ 0= _CVTD-SR-D @ 0= OR IF
        _CVTD-SR-WIPE 0 SEALED-RECORD-S-INVALID EXIT
    THEN
    _CVTD-SR-W @ SEALED-RECORD-WORKSPACE-SIZE 0 FILL
    _CVTD-SR-D @ SEALED-RECORD-D.INPUT @ DUP 0= IF
        DROP _CVTD-SR-WIPE 0 SEALED-RECORD-S-INVALID EXIT
    THEN
    _CVTD-SR-IN !
    _CVTD-SR-D @ SEALED-RECORD-D.INPUT-U @ DUP
    SEALED-RECORD-SIZE DUP 0= IF
        2DROP _CVTD-SR-WIPE 0 SEALED-RECORD-S-INVALID EXIT
    THEN
    _CVTD-SR-TOTAL-U ! _CVTD-SR-DATA-U !
    _CVTD-SR-D @ SEALED-RECORD-D.OUTPUT @ DUP 0= IF
        DROP _CVTD-SR-WIPE 0 SEALED-RECORD-S-INVALID EXIT
    THEN
    _CVTD-SR-OUT !
    _CVTD-SR-D @ SEALED-RECORD-D.OUTPUT-CAP @
        _CVTD-SR-TOTAL-U @ U< IF
        _CVTD-SR-WIPE 0 SEALED-RECORD-S-CAPACITY EXIT
    THEN
    _CVTD-SR-D @ _CVTD-RESOLVE-ROOT DUP IF
        _CVTD-SR-WIPE 0 SWAP EXIT
    THEN
    DROP
    _CVTD-SR-OUT @ _CVTD-SR-TOTAL-U @ 0 FILL
    _CVTD-SEAL-HEADER
    _CVTD-SR-IN @ _CVTD-SR-OUT @ SEALED-RECORD-HEADER-SIZE +
        _CVTD-SR-DATA-U @ MOVE
    _CVTD-SR-OUT @ SEALED-RECORD-HEADER-SIZE +
        _CVTD-SR-DATA-U @ +
        SEALED-RECORD-TAG-SIZE 0xA5 FILL
    _CVTD-SR-WIPE
    _CVTD-SR-TOTAL-U @ SEALED-RECORD-S-OK ;

: _CVTD-OPEN-SHAPE?  ( -- flag )
    _CVTD-SR-IN @ _CVTD-BE64@ 0x414B535345414C31 =
    _CVTD-SR-IN @ 8 + _CVTD-BE64@ 1 = AND
    _CVTD-SR-IN @ 16 + _CVTD-BE64@
        SEALED-RECORD-HEADER-SIZE = AND
    _CVTD-SR-IN @ 24 + _CVTD-BE64@
        _CVTD-SR-TOTAL-U @ = AND
    _CVTD-SR-IN @ 32 + _CVTD-BE64@
        _CVTD-SR-DATA-U @ = AND ;

: _CVTD-OPEN-IDENTITY?  ( -- flag )
    _CVTD-SR-IN @ 40 + _CVTD-BE64@
        _CVTD-SR-D @ SEALED-RECORD-D.PURPOSE @ =
    _CVTD-SR-IN @ 48 + _CVTD-BE64@
        _CVTD-SR-D @ SEALED-RECORD-D.REVISION @ = AND
    _CVTD-SR-IN @ 64 + SEALED-RECORD-ID-SIZE
        _CVTD-SR-D @ SEALED-RECORD-D.KEY-ID @
        SEALED-RECORD-ID-SIZE COMPARE 0= AND
    _CVTD-SR-IN @ 96 + SEALED-RECORD-ID-SIZE
        _CVTD-SR-D @ SEALED-RECORD-D.RECORD-ID @
        SEALED-RECORD-ID-SIZE COMPARE 0= AND ;

: SEALED-RECORD-OPEN
  ( descriptor workspace -- written status )
    _CVTD-SR-W ! _CVTD-SR-D !
    _CVTD-SR-W @ 0= _CVTD-SR-D @ 0= OR IF
        _CVTD-SR-WIPE 0 SEALED-RECORD-S-INVALID EXIT
    THEN
    _CVTD-SR-W @ SEALED-RECORD-WORKSPACE-SIZE 0 FILL
    _CVTD-SR-D @ SEALED-RECORD-D.INPUT @ DUP 0= IF
        DROP _CVTD-SR-WIPE 0 SEALED-RECORD-S-INVALID EXIT
    THEN
    _CVTD-SR-IN !
    _CVTD-SR-D @ SEALED-RECORD-D.INPUT-U @ DUP
        _CVTD-SR-TOTAL-U !
    SEALED-RECORD-OVERHEAD U> 0= IF
        _CVTD-SR-WIPE 0 SEALED-RECORD-S-FORMAT EXIT
    THEN
    _CVTD-SR-TOTAL-U @ SEALED-RECORD-OVERHEAD -
        _CVTD-SR-DATA-U !
    _CVTD-SR-DATA-U @ SEALED-RECORD-DATA-MAX U> IF
        _CVTD-SR-WIPE 0 SEALED-RECORD-S-FORMAT EXIT
    THEN
    _CVTD-OPEN-SHAPE? 0= IF
        _CVTD-SR-WIPE 0 SEALED-RECORD-S-FORMAT EXIT
    THEN
    _CVTD-OPEN-IDENTITY? 0= IF
        _CVTD-SR-WIPE 0 SEALED-RECORD-S-MISMATCH EXIT
    THEN
    _CVTD-SR-D @ SEALED-RECORD-D.OUTPUT @ DUP 0= IF
        DROP _CVTD-SR-WIPE 0 SEALED-RECORD-S-INVALID EXIT
    THEN
    _CVTD-SR-OUT !
    _CVTD-SR-D @ SEALED-RECORD-D.OUTPUT-CAP @
        _CVTD-SR-DATA-U @ U< IF
        _CVTD-SR-WIPE 0 SEALED-RECORD-S-CAPACITY EXIT
    THEN
    _CVTD-SR-D @ _CVTD-RESOLVE-ROOT DUP IF
        _CVTD-SR-WIPE 0 SWAP EXIT
    THEN
    DROP
    _CVTD-SR-IN @ SEALED-RECORD-HEADER-SIZE +
        _CVTD-SR-OUT @ _CVTD-SR-DATA-U @ MOVE
    _CVTD-SR-WIPE
    _CVTD-SR-DATA-U @ SEALED-RECORD-S-OK ;

\ =====================================================================
\  Fixed-snapshot geometry and one-record persistent double
\ =====================================================================

0 CONSTANT VFSNAP-S-OK
1 CONSTANT VFSNAP-S-ABSENT
2 CONSTANT VFSNAP-S-CORRUPT
3 CONSTANT VFSNAP-S-UNSUPPORTED
4 CONSTANT VFSNAP-S-INVALID
5 CONSTANT VFSNAP-S-CAPACITY
6 CONSTANT VFSNAP-S-IO
7 CONSTANT VFSNAP-S-RECOVERY
8 CONSTANT VFSNAP-S-BUSY
9 CONSTANT VFSNAP-S-CONFLICT

64 CONSTANT VFSNAP-HEADER-SIZE
16 CONSTANT VFSNAP-SPEC-PRIVATE-MAX

0x5646534E53504531 CONSTANT _CVTD-VFSNS-MAGIC
1 CONSTANT _CVTD-VFSNS-F-SEALED

  0 CONSTANT _CVTD-VFSNS-MAGIC-OFF
  8 CONSTANT _CVTD-VFSNS-FLAGS
 16 CONSTANT _CVTD-VFSNS-RECORD-MAGIC
 24 CONSTANT _CVTD-VFSNS-FORMAT
 32 CONSTANT _CVTD-VFSNS-PAYLOAD-U
 40 CONSTANT _CVTD-VFSNS-ENCODE-XT
 48 CONSTANT _CVTD-VFSNS-VALIDATE-XT
 56 CONSTANT _CVTD-VFSNS-PRIVATE-SET
440 CONSTANT VFSNAP-SPEC-SIZE

: VFSNAP-SPEC.MAGIC
    _CVTD-VFSNS-MAGIC-OFF + ;
: VFSNAP-SPEC.FLAGS
    _CVTD-VFSNS-FLAGS + ;
: VFSNAP-SPEC.RECORD-MAGIC
    _CVTD-VFSNS-RECORD-MAGIC + ;
: VFSNAP-SPEC.FORMAT
    _CVTD-VFSNS-FORMAT + ;
: VFSNAP-SPEC.PAYLOAD-U
    _CVTD-VFSNS-PAYLOAD-U + ;
: VFSNAP-SPEC.ENCODE-XT
    _CVTD-VFSNS-ENCODE-XT + ;
: VFSNAP-SPEC.VALIDATE-XT
    _CVTD-VFSNS-VALIDATE-XT + ;
: VFSNAP-SPEC.PRIVATE-SET
    _CVTD-VFSNS-PRIVATE-SET + ;

1152 CONSTANT VREPL-SIZE

: VREPL.VFS  ( replacement -- a )
    8 + ;
: VREPL.TARGET-LEN  ( replacement -- a )
    40 + ;
: VREPL.TARGET  ( replacement -- a )
    128 + ;

0x5646534E53544F31 CONSTANT _CVTD-VFSND-MAGIC-V

1152 CONSTANT _CVTD-VFSND-MAGIC
1160 CONSTANT _CVTD-VFSND-FLAGS
1168 CONSTANT _CVTD-VFSND-LAST-STATUS
1176 CONSTANT _CVTD-VFSND-LAST-VREPL
1184 CONSTANT _CVTD-VFSND-SPEC
1192 CONSTANT _CVTD-VFSND-SCRATCH-A
1200 CONSTANT _CVTD-VFSND-SCRATCH-U
1208 CONSTANT _CVTD-VFSND-VFS
1216 CONSTANT _CVTD-VFSND-CLOSE-XT
1224 CONSTANT _CVTD-VFSND-RESTORE-XT
1424 CONSTANT VFSNAP-STORE-SIZE

: VFSNAP.REPLACE  ( store -- replacement ) ;
: VFSNAP.MAGIC
    _CVTD-VFSND-MAGIC + ;
: VFSNAP.FLAGS
    _CVTD-VFSND-FLAGS + ;
: VFSNAP.LAST-STATUS
    _CVTD-VFSND-LAST-STATUS + ;
: VFSNAP.LAST-VREPL
    _CVTD-VFSND-LAST-VREPL + ;
: VFSNAP.SPEC
    _CVTD-VFSND-SPEC + ;
: VFSNAP.SCRATCH-A
    _CVTD-VFSND-SCRATCH-A + ;
: VFSNAP.SCRATCH-U
    _CVTD-VFSND-SCRATCH-U + ;
: VFSNAP.VFS
    _CVTD-VFSND-VFS + ;
: VFSNAP.CLOSE-XT
    _CVTD-VFSND-CLOSE-XT + ;
: VFSNAP.RESTORE-XT
    _CVTD-VFSND-RESTORE-XT + ;

: VFSNAP-PATH$  ( store -- address length )
    DUP VFSNAP.REPLACE VREPL.TARGET
    SWAP VFSNAP.REPLACE VREPL.TARGET-LEN @ ;

VARIABLE _CVTD-SPI-MAGIC-A
VARIABLE _CVTD-SPI-MAGIC-U
VARIABLE _CVTD-SPI-FORMAT
VARIABLE _CVTD-SPI-PAYLOAD-U
VARIABLE _CVTD-SPI-ENCODE
VARIABLE _CVTD-SPI-VALIDATE
VARIABLE _CVTD-SPI-SPEC

: VFSNAP-SPEC-INIT
  ( magic-a magic-u format payload-u encode-xt validate-xt spec -- status )
    _CVTD-SPI-SPEC ! _CVTD-SPI-VALIDATE ! _CVTD-SPI-ENCODE !
    _CVTD-SPI-PAYLOAD-U ! _CVTD-SPI-FORMAT !
    _CVTD-SPI-MAGIC-U ! _CVTD-SPI-MAGIC-A !
    _CVTD-SPI-SPEC @ 0= _CVTD-SPI-MAGIC-A @ 0= OR IF
        VFSNAP-S-INVALID EXIT
    THEN
    _CVTD-SPI-MAGIC-U @ 8 <> IF VFSNAP-S-INVALID EXIT THEN
    _CVTD-SPI-PAYLOAD-U @ 0> 0= IF VFSNAP-S-INVALID EXIT THEN
    _CVTD-SPI-ENCODE @ 0= _CVTD-SPI-VALIDATE @ 0= OR IF
        VFSNAP-S-INVALID EXIT
    THEN
    _CVTD-SPI-SPEC @ VFSNAP-SPEC-SIZE 0 FILL
    _CVTD-VFSNS-MAGIC
        _CVTD-SPI-SPEC @ VFSNAP-SPEC.MAGIC !
    _CVTD-SPI-MAGIC-A @
        _CVTD-SPI-SPEC @ VFSNAP-SPEC.RECORD-MAGIC 8 MOVE
    _CVTD-SPI-FORMAT @
        _CVTD-SPI-SPEC @ VFSNAP-SPEC.FORMAT !
    _CVTD-SPI-PAYLOAD-U @
        _CVTD-SPI-SPEC @ VFSNAP-SPEC.PAYLOAD-U !
    _CVTD-SPI-ENCODE @
        _CVTD-SPI-SPEC @ VFSNAP-SPEC.ENCODE-XT !
    _CVTD-SPI-VALIDATE @
        _CVTD-SPI-SPEC @ VFSNAP-SPEC.VALIDATE-XT !
    VFSNAP-SPEC-PRIVATE-MAX
        _CVTD-SPI-SPEC @ VFSNAP-SPEC.PRIVATE-SET
        _MSPAN-SET.CAPACITY !
    VFSNAP-S-OK ;

VARIABLE _CVTD-SPA-A
VARIABLE _CVTD-SPA-U
VARIABLE _CVTD-SPA-SPEC

: VFSNAP-SPEC-PRIVATE-ADD
  ( private-a private-u spec -- status )
    _CVTD-SPA-SPEC ! _CVTD-SPA-U ! _CVTD-SPA-A !
    _CVTD-SPA-SPEC @ VFSNAP-SPEC.PRIVATE-SET
        MSPAN-SET-COUNT@ IF VFSNAP-S-CAPACITY EXIT THEN
    _CVTD-SPA-A @
        _CVTD-SPA-SPEC @ VFSNAP-SPEC.PRIVATE-SET
        _MSPAN-SET.ENTRIES !
    _CVTD-SPA-U @
        _CVTD-SPA-SPEC @ VFSNAP-SPEC.PRIVATE-SET
        _MSPAN-SET.ENTRIES 8 + !
    1 _CVTD-SPA-SPEC @ VFSNAP-SPEC.PRIVATE-SET
        MSPAN-SET.COUNT !
    VFSNAP-S-OK ;

: VFSNAP-SPEC-SEAL  ( spec -- status )
    DUP VFSNAP-SPEC.MAGIC @ _CVTD-VFSNS-MAGIC <> IF
        DROP VFSNAP-S-INVALID EXIT
    THEN
    _CVTD-VFSNS-F-SEALED SWAP VFSNAP-SPEC.FLAGS !
    VFSNAP-S-OK ;

: VFSNAP-SPEC-SEALED?  ( spec -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP VFSNAP-SPEC.MAGIC @ _CVTD-VFSNS-MAGIC =
    SWAP VFSNAP-SPEC.FLAGS @
        _CVTD-VFSNS-F-SEALED AND 0<> AND ;

VARIABLE _CVTD-VSI-PATH-A
VARIABLE _CVTD-VSI-PATH-U
VARIABLE _CVTD-VSI-SCRATCH-A
VARIABLE _CVTD-VSI-SCRATCH-U
VARIABLE _CVTD-VSI-VFS
VARIABLE _CVTD-VSI-SPEC
VARIABLE _CVTD-VSI-STORE

: VFSNAP-INIT-AT
  ( path-a path-u scratch-a scratch-u vfs spec store -- status )
    _CVTD-VSI-STORE ! _CVTD-VSI-SPEC ! _CVTD-VSI-VFS !
    _CVTD-VSI-SCRATCH-U ! _CVTD-VSI-SCRATCH-A !
    _CVTD-VSI-PATH-U ! _CVTD-VSI-PATH-A !
    _CVTD-VSI-STORE @ 0= _CVTD-VSI-SPEC @ 0= OR
    _CVTD-VSI-VFS @ 0= OR IF VFSNAP-S-INVALID EXIT THEN
    _CVTD-VSI-SPEC @ VFSNAP-SPEC-SEALED? 0= IF
        VFSNAP-S-INVALID EXIT
    THEN
    _CVTD-VSI-PATH-U @ 0> 0=
    _CVTD-VSI-PATH-U @ 255 U> OR IF VFSNAP-S-INVALID EXIT THEN
    _CVTD-VSI-SCRATCH-U @
        _CVTD-VSI-SPEC @ VFSNAP-SPEC.PAYLOAD-U @
        VFSNAP-HEADER-SIZE + <> IF VFSNAP-S-CAPACITY EXIT THEN
    _CVTD-VSI-STORE @ VFSNAP-STORE-SIZE 0 FILL
    _CVTD-VSI-SCRATCH-A @ _CVTD-VSI-SCRATCH-U @ 0 FILL
    _CVTD-VSI-VFS @
        _CVTD-VSI-STORE @ VFSNAP.REPLACE VREPL.VFS !
    _CVTD-VSI-PATH-A @
        _CVTD-VSI-STORE @ VFSNAP.REPLACE VREPL.TARGET
        _CVTD-VSI-PATH-U @ MOVE
    _CVTD-VSI-PATH-U @
        _CVTD-VSI-STORE @ VFSNAP.REPLACE VREPL.TARGET-LEN !
    _CVTD-VFSND-MAGIC-V
        _CVTD-VSI-STORE @ VFSNAP.MAGIC !
    _CVTD-VSI-SPEC @
        _CVTD-VSI-STORE @ VFSNAP.SPEC !
    _CVTD-VSI-SCRATCH-A @
        _CVTD-VSI-STORE @ VFSNAP.SCRATCH-A !
    _CVTD-VSI-SCRATCH-U @
        _CVTD-VSI-STORE @ VFSNAP.SCRATCH-U !
    _CVTD-VSI-VFS @
        _CVTD-VSI-STORE @ VFSNAP.VFS !
    VFSNAP-S-ABSENT
        _CVTD-VSI-STORE @ VFSNAP.LAST-STATUS !
    VFSNAP-S-OK ;

: VFSNAP-VALID?  ( store -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP VFSNAP.MAGIC @ _CVTD-VFSND-MAGIC-V =
    OVER VFSNAP.SPEC @ VFSNAP-SPEC-SEALED? AND
    OVER VFSNAP.VFS @ 0<> AND
    SWAP VFSNAP.SCRATCH-A @ 0<> AND ;

CREATE _CVTD-PERSIST-PATH 256 ALLOT
CREATE _CVTD-PERSIST-DATA SEALED-RECORD-SIZE-MAX ALLOT
VARIABLE _CVTD-PERSIST-PATH-U
VARIABLE _CVTD-PERSIST-U
VARIABLE _CVTD-PERSIST-GENERATION
VARIABLE _CVTD-PERSIST-PRESENT

: _CVTD-PATH-MATCH?  ( store -- flag )
    VFSNAP-PATH$
    _CVTD-PERSIST-PATH _CVTD-PERSIST-PATH-U @
    COMPARE 0= ;

: _CVTD-CAPTURE-PATH  ( store -- )
    DUP VFSNAP-PATH$
    DUP _CVTD-PERSIST-PATH-U !
    _CVTD-PERSIST-PATH SWAP MOVE
    DROP ;

: VFSNAP-FINI  ( store -- status )
    DUP VFSNAP-VALID? 0= IF DROP VFSNAP-S-INVALID EXIT THEN
    DUP VFSNAP.SCRATCH-A @
    OVER VFSNAP.SCRATCH-U @ 0 FILL
    VFSNAP-STORE-SIZE 0 FILL
    VFSNAP-S-OK ;

VARIABLE _CVTD-VSL-DST
VARIABLE _CVTD-VSL-CAP
VARIABLE _CVTD-VSL-GEN-DST
VARIABLE _CVTD-VSL-STORE

: VFSNAP-LOAD
  ( payload-destination capacity generation-destination store -- status )
    _CVTD-VSL-STORE ! _CVTD-VSL-GEN-DST !
    _CVTD-VSL-CAP ! _CVTD-VSL-DST !
    _CVTD-VSL-STORE @ VFSNAP-VALID? 0= IF
        VFSNAP-S-INVALID EXIT
    THEN
    _CVTD-PERSIST-PRESENT @ 0= IF VFSNAP-S-ABSENT EXIT THEN
    _CVTD-VSL-STORE @ _CVTD-PATH-MATCH? 0= IF
        VFSNAP-S-ABSENT EXIT
    THEN
    _CVTD-VSL-CAP @ _CVTD-PERSIST-U @ U< IF
        VFSNAP-S-CAPACITY EXIT
    THEN
    _CVTD-PERSIST-DATA _CVTD-VSL-DST @
        _CVTD-PERSIST-U @ MOVE
    _CVTD-VSL-DST @ _CVTD-PERSIST-U @
        _CVTD-PERSIST-GENERATION @
        _CVTD-VSL-STORE @ VFSNAP.SPEC @
        VFSNAP-SPEC.VALIDATE-XT @ EXECUTE
    DUP IF EXIT THEN
    DROP
    _CVTD-PERSIST-GENERATION @ _CVTD-VSL-GEN-DST @ !
    VFSNAP-S-OK ;

VARIABLE _CVTD-VSS-CONTEXT
VARIABLE _CVTD-VSS-EXPECTED
VARIABLE _CVTD-VSS-NEXT
VARIABLE _CVTD-VSS-STORE
VARIABLE _CVTD-VSS-PAYLOAD
VARIABLE _CVTD-VSS-PAYLOAD-U

: VFSNAP-SAVE  ( encode-context expected-generation store -- status )
    _CVTD-VSS-STORE ! _CVTD-VSS-EXPECTED ! _CVTD-VSS-CONTEXT !
    _CVTD-VSS-STORE @ VFSNAP-VALID? 0= IF
        VFSNAP-S-INVALID EXIT
    THEN
    _CVTD-VSS-EXPECTED @ 0< IF VFSNAP-S-INVALID EXIT THEN
    _CVTD-PERSIST-PRESENT @ IF
        _CVTD-VSS-STORE @ _CVTD-PATH-MATCH? 0= IF
            VFSNAP-S-CONFLICT EXIT
        THEN
        _CVTD-VSS-EXPECTED @ _CVTD-PERSIST-GENERATION @ <> IF
            VFSNAP-S-CONFLICT EXIT
        THEN
    ELSE
        _CVTD-VSS-EXPECTED @ IF VFSNAP-S-CONFLICT EXIT THEN
    THEN
    _CVTD-VSS-EXPECTED @ 1+ DUP 0> 0= IF
        DROP VFSNAP-S-CAPACITY EXIT
    THEN
    _CVTD-VSS-NEXT !
    _CVTD-VSS-STORE @ VFSNAP.SCRATCH-A @ VFSNAP-HEADER-SIZE +
        _CVTD-VSS-PAYLOAD !
    _CVTD-VSS-STORE @ VFSNAP.SPEC @
        VFSNAP-SPEC.PAYLOAD-U @ _CVTD-VSS-PAYLOAD-U !
    _CVTD-VSS-PAYLOAD @ _CVTD-VSS-PAYLOAD-U @ 0 FILL
    _CVTD-VSS-CONTEXT @
        _CVTD-VSS-PAYLOAD @ _CVTD-VSS-PAYLOAD-U @
        _CVTD-VSS-NEXT @
        _CVTD-VSS-STORE @ VFSNAP.SPEC @
        VFSNAP-SPEC.ENCODE-XT @ EXECUTE
    DUP IF
        _CVTD-VSS-STORE @ VFSNAP.SCRATCH-A @
            _CVTD-VSS-STORE @ VFSNAP.SCRATCH-U @ 0 FILL
        EXIT
    THEN
    DROP
    _CVTD-VSS-PAYLOAD @ _CVTD-PERSIST-DATA
        _CVTD-VSS-PAYLOAD-U @ MOVE
    _CVTD-VSS-PAYLOAD-U @ _CVTD-PERSIST-U !
    _CVTD-VSS-NEXT @ _CVTD-PERSIST-GENERATION !
    -1 _CVTD-PERSIST-PRESENT !
    _CVTD-VSS-STORE @ _CVTD-CAPTURE-PATH
    _CVTD-VSS-STORE @ VFSNAP.SCRATCH-A @
        _CVTD-VSS-STORE @ VFSNAP.SCRATCH-U @ 0 FILL
    VFSNAP-S-OK ;

: VFSNAP-RECOVER  ( store -- status )
    DUP VFSNAP-VALID? IF DROP VFSNAP-S-OK
    ELSE DROP VFSNAP-S-INVALID THEN ;

\ =====================================================================
\  Fixture-visible reset and evidence
\ =====================================================================

VARIABLE _CVTD-RESET-A
VARIABLE _CVTD-RESET-U

: _CVTD-RESET  ( -- )
    0 _CVTD-SHARD1-PRESENT !
    0 _CVTD-SHARD2-PRESENT !
    0 _CVTD-PERSIST-PATH-U !
    0 _CVTD-PERSIST-U !
    0 _CVTD-PERSIST-GENERATION !
    0 _CVTD-PERSIST-PRESENT !
    1 _CVTD-ENTROPY-BYTE !
    _CVTD-PERSIST-PATH 256 0 FILL
    _CVTD-PERSIST-DATA SEALED-RECORD-SIZE-MAX 0 FILL ;
