\ Bounded credential-vault composition lifecycle.
\
\ Load cv-deps.f, then the runner-packaged production vault body, then this
\ file. Invoke _CVTL-RUN from autoexec.

PROVIDED cv-test-life

VARIABLE _CVTL-FAILS
VARIABLE _CVTL-CHECKS
VARIABLE _CVTL-DEPTH

: _CVTL-ASSERT  ( flag -- )
    1 _CVTL-CHECKS +!
    0= IF
        1 _CVTL-FAILS +!
        ." CREDENTIAL VAULT LIFE ASSERT " _CVTL-CHECKS @ . CR
    THEN ;

: _CVTL-STACK  ( -- )
    DEPTH DUP _CVTL-DEPTH @ <> IF
        ." CREDENTIAL VAULT LIFE STACK "
        _CVTL-DEPTH @ . ." -> " DUP . CR .S CR
    THEN
    _CVTL-DEPTH @ = _CVTL-ASSERT ;

: _CVTL-FILLED?  ( address length byte -- flag )
    >R
    BEGIN
        DUP
    WHILE
        OVER C@ R@ <> IF
            2DROP R> DROP 0 EXIT
        THEN
        1- SWAP 1+ SWAP
    REPEAT
    2DROP R> DROP -1 ;

: _CVTL-ZERO?  ( address length -- flag )
    0 _CVTL-FILLED? ;

VARIABLE _CVTL-SEQ-BYTE
VARIABLE _CVTL-SEQ-A
VARIABLE _CVTL-SEQ-U

: _CVTL-SEQUENCE!  ( first-byte destination length -- )
    _CVTL-SEQ-U ! _CVTL-SEQ-A ! _CVTL-SEQ-BYTE !
    BEGIN
        _CVTL-SEQ-U @
    WHILE
        _CVTL-SEQ-BYTE @ 255 AND _CVTL-SEQ-A @ C!
        1 _CVTL-SEQ-BYTE +!
        1 _CVTL-SEQ-A +!
        -1 _CVTL-SEQ-U +!
    REPEAT ;

32 CONSTANT _CVTL-SECRET-CAP
_CVTL-SECRET-CAP CVAULT-BACKING-SIZE CONSTANT _CVTL-BACKING-U

VARIABLE _CVTL-CONFIG
VARIABLE _CVTL-VAULT
VARIABLE _CVTL-BACKING

CREATE _CVTL-VFS VFS-DESC-SIZE ALLOT
CREATE _CVTL-VAULT-ID RID-SIZE ALLOT
CREATE _CVTL-KEY-ID RID-SIZE ALLOT
CREATE _CVTL-RID RID-SIZE ALLOT
CREATE _CVTL-NEW-RID RID-SIZE ALLOT
CREATE _CVTL-ROOT-KEY SEALED-RECORD-ROOT-KEY-SIZE ALLOT
CREATE _CVTL-PATH 256 ALLOT

VARIABLE _CVTL-GENERATION
VARIABLE _CVTL-STATUS
VARIABLE _CVTL-KIND
VARIABLE _CVTL-STATE
VARIABLE _CVTL-SECRET-U
VARIABLE _CVTL-RESULT

: _CVTL-ALLOCATE  ( size variable -- )
    >R ALLOCATE ABORT" CREDENTIAL VAULT LIFE FAIL allocation"
    R> ! ;

: _CVTL-FREE  ( variable -- )
    DUP @ ?DUP IF FREE 0 SWAP ! ELSE DROP THEN ;

\ =====================================================================
\  Resolver and rollback-floor providers
\ =====================================================================

VARIABLE _CVTL-RESOLVER-CALLS
VARIABLE _CVTL-RESOLVER-A
VARIABLE _CVTL-RESOLVER-U
VARIABLE _CVTL-RESOLVER-XT
VARIABLE _CVTL-RESOLVER-CONTEXT
VARIABLE _CVTL-FLOOR
VARIABLE _CVTL-FLOOR-READ-STATUS
VARIABLE _CVTL-FLOOR-SEEN
VARIABLE _CVTL-FLOOR-READS
VARIABLE _CVTL-FLOOR-ADVANCES
VARIABLE _CVTL-LAST-ADV-RESOLVERS

0x4356544C52455331 CONSTANT _CVTL-RESOLVER-TOKEN
0x4356544C464C5231 CONSTANT _CVTL-FLOOR-TOKEN

: _CVTL-RESOLVER
  ( key-id key-id-u consumer-xt consumer-context resolver-context -- status )
    _CVTL-RESOLVER-TOKEN = _CVTL-ASSERT
    _CVTL-RESOLVER-CONTEXT ! _CVTL-RESOLVER-XT !
    _CVTL-RESOLVER-U ! _CVTL-RESOLVER-A !
    _CVTL-RESOLVER-U @ RID-SIZE = _CVTL-ASSERT
    _CVTL-RESOLVER-A @ RID-SIZE
        _CVTL-KEY-ID RID-SIZE COMPARE 0= _CVTL-ASSERT
    _CVTL-FLOOR-SEEN @ _CVTL-ASSERT
    1 _CVTL-RESOLVER-CALLS +!
    _CVTL-ROOT-KEY SEALED-RECORD-ROOT-KEY-SIZE
    _CVTL-RESOLVER-CONTEXT @
    _CVTL-RESOLVER-XT @ EXECUTE ;

VARIABLE _CVTL-FR-VA
VARIABLE _CVTL-FR-VU
VARIABLE _CVTL-FR-RA
VARIABLE _CVTL-FR-RU

: _CVTL-FLOOR-READ
  ( vault-id vault-id-u rid rid-u floor-context -- generation status )
    _CVTL-FLOOR-TOKEN = _CVTL-ASSERT
    _CVTL-FR-RU ! _CVTL-FR-RA !
    _CVTL-FR-VU ! _CVTL-FR-VA !
    _CVTL-FR-VU @ RID-SIZE = _CVTL-ASSERT
    _CVTL-FR-RU @ RID-SIZE = _CVTL-ASSERT
    _CVTL-FR-VA @ RID-SIZE
        _CVTL-VAULT-ID RID-SIZE COMPARE 0= _CVTL-ASSERT
    _CVTL-FR-RA @ RID-SIZE
        _CVTL-RID RID-SIZE COMPARE 0= _CVTL-ASSERT
    -1 _CVTL-FLOOR-SEEN !
    1 _CVTL-FLOOR-READS +!
    _CVTL-FLOOR-READ-STATUS @ DUP IF
        >R 0 R> EXIT
    THEN
    DROP
    _CVTL-FLOOR @ CVAULT-S-OK ;

VARIABLE _CVTL-FA-VA
VARIABLE _CVTL-FA-VU
VARIABLE _CVTL-FA-RA
VARIABLE _CVTL-FA-RU
VARIABLE _CVTL-FA-GENERATION

: _CVTL-FLOOR-ADVANCE
  ( vault-id vault-id-u rid rid-u generation floor-context -- status )
    _CVTL-FLOOR-TOKEN = _CVTL-ASSERT
    _CVTL-FA-GENERATION !
    _CVTL-FA-RU ! _CVTL-FA-RA !
    _CVTL-FA-VU ! _CVTL-FA-VA !
    _CVTL-FA-VU @ RID-SIZE = _CVTL-ASSERT
    _CVTL-FA-RU @ RID-SIZE = _CVTL-ASSERT
    _CVTL-FA-VA @ RID-SIZE
        _CVTL-VAULT-ID RID-SIZE COMPARE 0= _CVTL-ASSERT
    _CVTL-FA-RA @ RID-SIZE
        _CVTL-RID RID-SIZE COMPARE 0= _CVTL-ASSERT
    _CVTL-FA-GENERATION @ _CVTL-FLOOR @ U< 0= _CVTL-ASSERT
    _CVTL-RESOLVER-CALLS @
        _CVTL-LAST-ADV-RESOLVERS @ > _CVTL-ASSERT
    _CVTL-RESOLVER-CALLS @ _CVTL-LAST-ADV-RESOLVERS !
    _CVTL-FA-GENERATION @ _CVTL-FLOOR !
    1 _CVTL-FLOOR-ADVANCES +!
    CVAULT-S-OK ;

\ =====================================================================
\  Configuration and consumer callbacks
\ =====================================================================

: _CVTL-CONFIGURE  ( -- status )
    _CVTL-CONFIG @ CVAULT-CONFIG-CLEAR
    DUP IF EXIT THEN DROP
    S" /vault"
        _CVTL-CONFIG @ CVAULT-C.ROOT-U !
        _CVTL-CONFIG @ CVAULT-C.ROOT !
    _CVTL-SECRET-CAP
        _CVTL-CONFIG @ CVAULT-C.SECRET-CAPACITY !
    _CVTL-BACKING @
        _CVTL-CONFIG @ CVAULT-C.BACKING !
    _CVTL-BACKING-U
        _CVTL-CONFIG @ CVAULT-C.BACKING-U !
    _CVTL-VFS
        _CVTL-CONFIG @ CVAULT-C.VFS !
    _CVTL-VAULT-ID
        _CVTL-CONFIG @ CVAULT-C.VAULT-ID !
    _CVTL-KEY-ID
        _CVTL-CONFIG @ CVAULT-C.KEY-ID !
    ['] _CVTL-RESOLVER
        _CVTL-CONFIG @ CVAULT-C.RESOLVER-XT !
    _CVTL-RESOLVER-TOKEN
        _CVTL-CONFIG @ CVAULT-C.RESOLVER-CONTEXT !
    ['] _CVTL-FLOOR-READ
        _CVTL-CONFIG @ CVAULT-C.FLOOR-READ-XT !
    ['] _CVTL-FLOOR-ADVANCE
        _CVTL-CONFIG @ CVAULT-C.FLOOR-ADVANCE-XT !
    _CVTL-FLOOR-TOKEN
        _CVTL-CONFIG @ CVAULT-C.FLOOR-CONTEXT !
    _CVTL-CONFIG @ _CVTL-VAULT @ CVAULT-INIT ;

VARIABLE _CVTL-EXPECT-A
VARIABLE _CVTL-EXPECT-U
VARIABLE _CVTL-EXPECT-KIND
VARIABLE _CVTL-EXPECT-GENERATION
VARIABLE _CVTL-CONSUMER-CONTEXT
VARIABLE _CVTL-CONSUMER-CALLS

: _CVTL-CONSUME
  ( secret-a secret-u kind generation context -- result )
    _CVTL-CONSUMER-CONTEXT ! _CVTL-GENERATION !
    _CVTL-KIND ! _CVTL-SECRET-U ! _CVTL-RESULT !
    _CVTL-CONSUMER-CONTEXT @ 0xCAFE = _CVTL-ASSERT
    _CVTL-SECRET-U @ _CVTL-EXPECT-U @ = _CVTL-ASSERT
    _CVTL-RESULT @ _CVTL-SECRET-U @
        _CVTL-EXPECT-A @ _CVTL-EXPECT-U @
        COMPARE 0= _CVTL-ASSERT
    _CVTL-KIND @ _CVTL-EXPECT-KIND @ = _CVTL-ASSERT
    _CVTL-GENERATION @
        _CVTL-EXPECT-GENERATION @ = _CVTL-ASSERT
    1 _CVTL-CONSUMER-CALLS +!
    0x5151 ;

: _CVTL-EXTRA-CONSUMER
  ( secret-a secret-u kind generation context -- first second )
    DROP DROP DROP 2DROP
    11 22 ;

: _CVTL-MUTATE-CONSUMER
  ( secret-a secret-u kind generation vault -- result )
    >R DROP DROP 2DROP
    0 R@ _CV.MAGIC !
    R> DROP 0x6161 ;

: _CVTL-EXPECT  ( secret-a secret-u kind generation -- )
    _CVTL-EXPECT-GENERATION ! _CVTL-EXPECT-KIND !
    _CVTL-EXPECT-U ! _CVTL-EXPECT-A ! ;

: _CVTL-WITH  ( secret-a secret-u generation -- )
    >R 17 R> _CVTL-EXPECT
    0 _CVTL-FLOOR-SEEN !
    _CVTL-RID ['] _CVTL-CONSUME 0xCAFE
        _CVTL-VAULT @ CVAULT-WITH
    _CVTL-STATUS ! _CVTL-RESULT !
    _CVTL-KIND ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-OK = _CVTL-ASSERT
    _CVTL-GENERATION @
        _CVTL-EXPECT-GENERATION @ = _CVTL-ASSERT
    _CVTL-KIND @ 17 = _CVTL-ASSERT
    _CVTL-RESULT @ 0x5151 = _CVTL-ASSERT
    _CVTL-BACKING @ _CVTL-BACKING-U _CVTL-ZERO?
        _CVTL-ASSERT ;

\ =====================================================================
\  Lifecycle cases
\ =====================================================================

: _CVTL-SETUP  ( -- )
    CVAULT-CONFIG-SIZE _CVTL-CONFIG _CVTL-ALLOCATE
    CVAULT-SIZE _CVTL-VAULT _CVTL-ALLOCATE
    _CVTL-BACKING-U _CVTL-BACKING _CVTL-ALLOCATE
    _CVTL-CONFIG @ CVAULT-CONFIG-SIZE 0 FILL
    _CVTL-VAULT @ CVAULT-SIZE 0 FILL
    _CVTL-BACKING @ _CVTL-BACKING-U 0 FILL
    _CVTL-VFS VFS-DESC-SIZE 0 FILL
    _CVTD-ROOT-INODE _CVTL-VFS V.CWD !
    _CVTL-VFS VFS-USE
    _CVTD-RESET
    0x10 _CVTL-VAULT-ID RID-SIZE _CVTL-SEQUENCE!
    0x40 _CVTL-KEY-ID RID-SIZE _CVTL-SEQUENCE!
    0 _CVTL-RID RID-SIZE _CVTL-SEQUENCE!
    0x80 _CVTL-ROOT-KEY
        SEALED-RECORD-ROOT-KEY-SIZE _CVTL-SEQUENCE!
    _CVTL-NEW-RID RID-CLEAR
    _CVTL-PATH 256 0 FILL
    0 _CVTL-RESOLVER-CALLS !
    0 _CVTL-FLOOR !
    0 _CVTL-FLOOR-READ-STATUS !
    0 _CVTL-FLOOR-SEEN !
    0 _CVTL-FLOOR-READS !
    0 _CVTL-FLOOR-ADVANCES !
    0 _CVTL-LAST-ADV-RESOLVERS !
    0 _CVTL-CONSUMER-CALLS ! ;

: _CVTL-PATH-CASE  ( -- )
    _CVTL-RID _CVTL-PATH 256 _CVTL-VAULT @ CVAULT-PATH
    _CVTL-STATUS ! _CVTL-SECRET-U !
    _CVTL-STATUS @ CVAULT-S-OK = _CVTL-ASSERT
    _CVTL-SECRET-U @ 73 = _CVTL-ASSERT
    _CVTL-PATH _CVTL-SECRET-U @
    S" /vault/00010203040506070809/0a0b0c0d0e0f1011121314/15161718191a1b1c1d1e1f"
        COMPARE 0= _CVTL-ASSERT
    _CVTL-RID _CVTL-PATH 72 _CVTL-VAULT @ CVAULT-PATH
    _CVTL-STATUS ! _CVTL-SECRET-U !
    _CVTL-STATUS @ CVAULT-S-CAPACITY = _CVTL-ASSERT
    _CVTL-SECRET-U @ 0= _CVTL-ASSERT ;

: _CVTL-CREATE-CASE  ( -- )
    0 _CVTL-FLOOR-SEEN !
    _CVTL-RID 17 S" alpha-token" _CVTL-VAULT @ CVAULT-CREATE
    _CVTL-STATUS ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-OK = _CVTL-ASSERT
    _CVTL-GENERATION @ 1 = _CVTL-ASSERT
    _CVTL-FLOOR @ 1 = _CVTL-ASSERT
    _CVTL-FLOOR-READS @ 1 = _CVTL-ASSERT
    _CVTL-FLOOR-ADVANCES @ 1 = _CVTL-ASSERT
    _CVTD-SHARD1-PRESENT @ _CVTL-ASSERT
    _CVTD-SHARD2-PRESENT @ _CVTL-ASSERT
    _CVTD-PERSIST-PRESENT @ _CVTL-ASSERT
    _CVTD-PERSIST-GENERATION @ 1 = _CVTL-ASSERT
    _CVTL-BACKING @ _CVTL-BACKING-U _CVTL-ZERO?
        _CVTL-ASSERT ;

: _CVTL-REOPEN-CASE  ( -- )
    _CVTL-VAULT @ CVAULT-FINI
        CVAULT-S-OK = _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-SIZE _CVTL-ZERO? _CVTL-ASSERT
    _CVTL-BACKING @ _CVTL-BACKING-U _CVTL-ZERO?
        _CVTL-ASSERT
    _CVTD-PERSIST-PRESENT @ _CVTL-ASSERT
    _CVTL-CONFIGURE CVAULT-S-OK = _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-VALID? _CVTL-ASSERT
    S" alpha-token" 1 _CVTL-WITH ;

: _CVTL-REPLACE-CASE  ( -- )
    0 _CVTL-FLOOR-SEEN !
    _CVTL-RID 2 S" beta-token-2" _CVTL-VAULT @ CVAULT-REPLACE
    _CVTL-STATUS ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-CONFLICT = _CVTL-ASSERT
    _CVTL-GENERATION @ 0= _CVTL-ASSERT
    _CVTD-PERSIST-GENERATION @ 1 = _CVTL-ASSERT
    _CVTL-FLOOR @ 1 = _CVTL-ASSERT
    0 _CVTL-FLOOR-SEEN !
    _CVTL-RID 1 S" beta-token-2" _CVTL-VAULT @ CVAULT-REPLACE
    _CVTL-STATUS ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-OK = _CVTL-ASSERT
    _CVTL-GENERATION @ 2 = _CVTL-ASSERT
    _CVTD-PERSIST-GENERATION @ 2 = _CVTL-ASSERT
    _CVTL-FLOOR @ 2 = _CVTL-ASSERT
    S" beta-token-2" 2 _CVTL-WITH ;

: _CVTL-CALLBACK-CASE  ( -- )
    CVAULT-S-REVOKED _CVTL-FLOOR-READ-STATUS !
    0 _CVTL-FLOOR-SEEN !
    _CVTL-RID _CVTL-VAULT @ CVAULT-METADATA
    _CVTL-STATUS ! _CVTL-SECRET-U !
    _CVTL-KIND ! _CVTL-STATE ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-CALLBACK = _CVTL-ASSERT
    _CVTL-GENERATION @ 0= _CVTL-ASSERT
    _CVTL-STATE @ 0= _CVTL-ASSERT
    _CVTL-KIND @ 0= _CVTL-ASSERT
    _CVTL-SECRET-U @ 0= _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-BLOCKED? 0= _CVTL-ASSERT
    0 _CVTL-FLOOR-READ-STATUS !
    0 _CVTL-FLOOR-SEEN !
    _CVTL-RID ['] _CVTL-EXTRA-CONSUMER 0
        _CVTL-VAULT @ CVAULT-WITH
    _CVTL-STATUS ! _CVTL-RESULT !
    _CVTL-KIND ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-CALLBACK = _CVTL-ASSERT
    _CVTL-GENERATION @ 0= _CVTL-ASSERT
    _CVTL-KIND @ 0= _CVTL-ASSERT
    _CVTL-RESULT @ 0= _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-BLOCKED? 0= _CVTL-ASSERT
    0 _CVTL-FLOOR-SEEN !
    _CVTL-RID ['] _CVTL-MUTATE-CONSUMER _CVTL-VAULT @
        _CVTL-VAULT @ CVAULT-WITH
    _CVTL-STATUS ! _CVTL-RESULT !
    _CVTL-KIND ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-INTERNAL = _CVTL-ASSERT
    _CVTL-GENERATION @ 0= _CVTL-ASSERT
    _CVTL-KIND @ 0= _CVTL-ASSERT
    _CVTL-RESULT @ 0= _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-VALID? _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-BLOCKED? _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-LAST-STATUS@
        CVAULT-S-INTERNAL = _CVTL-ASSERT
    CVAULT-S-REVOKED _CVTL-FLOOR-READ-STATUS !
    0 _CVTL-FLOOR-SEEN !
    _CVTL-VAULT @ CVAULT-RECOVER
    _CVTL-STATUS ! _CVTL-STATE ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-CALLBACK = _CVTL-ASSERT
    _CVTL-GENERATION @ 0= _CVTL-ASSERT
    _CVTL-STATE @ 0= _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-VALID? _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-BLOCKED? _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-LAST-STATUS@
        CVAULT-S-RECOVERY = _CVTL-ASSERT
    0 _CVTL-FLOOR-READ-STATUS !
    0 _CVTL-FLOOR-SEEN !
    _CVTL-VAULT @ CVAULT-RECOVER
    _CVTL-STATUS ! _CVTL-STATE ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-OK = _CVTL-ASSERT
    _CVTL-GENERATION @ 2 = _CVTL-ASSERT
    _CVTL-STATE @ CVAULT-STATE-PRESENT = _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-BLOCKED? 0= _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-VALID? _CVTL-ASSERT ;

: _CVTL-REVOKE-CASE  ( -- )
    0 _CVTL-FLOOR-SEEN !
    _CVTL-RID 2 _CVTL-VAULT @ CVAULT-REVOKE
    _CVTL-STATUS ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-OK = _CVTL-ASSERT
    _CVTL-GENERATION @ 3 = _CVTL-ASSERT
    _CVTD-PERSIST-GENERATION @ 3 = _CVTL-ASSERT
    _CVTL-FLOOR @ 3 = _CVTL-ASSERT
    0 _CVTL-FLOOR-SEEN !
    _CVTL-RID _CVTL-VAULT @ CVAULT-METADATA
    _CVTL-STATUS ! _CVTL-SECRET-U !
    _CVTL-KIND ! _CVTL-STATE ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-REVOKED = _CVTL-ASSERT
    _CVTL-GENERATION @ 3 = _CVTL-ASSERT
    _CVTL-STATE @ CVAULT-STATE-TOMBSTONE = _CVTL-ASSERT
    _CVTL-KIND @ 17 = _CVTL-ASSERT
    _CVTL-SECRET-U @ 0= _CVTL-ASSERT
    _CVTL-CONSUMER-CALLS @ >R
    0 _CVTL-FLOOR-SEEN !
    _CVTL-RID ['] _CVTL-CONSUME 0xCAFE
        _CVTL-VAULT @ CVAULT-WITH
    _CVTL-STATUS ! _CVTL-RESULT !
    _CVTL-KIND ! _CVTL-GENERATION !
    _CVTL-STATUS @ CVAULT-S-REVOKED = _CVTL-ASSERT
    _CVTL-GENERATION @ 0= _CVTL-ASSERT
    _CVTL-KIND @ 0= _CVTL-ASSERT
    _CVTL-RESULT @ 0= _CVTL-ASSERT
    _CVTL-CONSUMER-CALLS @ R> = _CVTL-ASSERT ;

: _CVTL-RID-CASE  ( -- )
    _CVTL-NEW-RID RID-CLEAR
    _CVTL-NEW-RID _CVTL-VAULT @ CVAULT-RID-NEW
        CVAULT-S-OK = _CVTL-ASSERT
    _CVTL-NEW-RID RID-PRESENT? _CVTL-ASSERT
    _CVTL-NEW-RID _CVTL-VAULT-ID RID= 0= _CVTL-ASSERT ;

: _CVTL-CLEANUP  ( -- )
    _CVTL-VAULT @ ?DUP IF
        DUP CVAULT-VALID? IF
            CVAULT-FINI CVAULT-S-OK = _CVTL-ASSERT
        ELSE
            DROP
        THEN
    THEN
    _CVTL-BACKING @ ?DUP IF
        _CVTL-BACKING-U _CVTL-ZERO? _CVTL-ASSERT
    THEN
    _CVTL-VAULT _CVTL-FREE
    _CVTL-BACKING _CVTL-FREE
    _CVTL-CONFIG _CVTL-FREE
    0 VFS-USE
    _CVTD-RESET
    _CVTL-STACK ;

: _CVTL-RUN  ( -- )
    0 _CVTL-FAILS ! 0 _CVTL-CHECKS ! DEPTH _CVTL-DEPTH !
    _CVTL-SETUP
    ." CREDENTIAL VAULT LIFE SETUP" CR TX-FLUSH
    _CVTL-CONFIGURE CVAULT-S-OK = _CVTL-ASSERT
    _CVTL-VAULT @ CVAULT-VALID? _CVTL-ASSERT
    ." CREDENTIAL VAULT LIFE CONFIGURED" CR TX-FLUSH
    _CVTL-PATH-CASE
    ." CREDENTIAL VAULT LIFE PATH" CR TX-FLUSH
    _CVTL-CREATE-CASE
    ." CREDENTIAL VAULT LIFE CREATED" CR TX-FLUSH
    _CVTL-REOPEN-CASE
    ." CREDENTIAL VAULT LIFE REOPENED" CR TX-FLUSH
    _CVTL-REPLACE-CASE
    ." CREDENTIAL VAULT LIFE REPLACED" CR TX-FLUSH
    _CVTL-CALLBACK-CASE
    ." CREDENTIAL VAULT LIFE CALLBACKS" CR TX-FLUSH
    _CVTL-REVOKE-CASE
    ." CREDENTIAL VAULT LIFE REVOKED" CR TX-FLUSH
    _CVTL-RID-CASE
    ." CREDENTIAL VAULT LIFE RID" CR TX-FLUSH
    _CVTL-CLEANUP
    _CVTL-FAILS @ 0= IF
        ." CREDENTIAL VAULT LIFE PASS " _CVTL-CHECKS @ . CR
    ELSE
        ." CREDENTIAL VAULT LIFE FAIL " _CVTL-FAILS @ .
        ." / " _CVTL-CHECKS @ . CR
    THEN ;
