\ Focused lifecycle contracts for the Streams-owned Rabbit connector.

PROVIDED rabbit-connector-test

CREATE _RBT-RCONN-STORE STREAMS-RABBIT-CONNECTOR-SIZE 7 + ALLOT

: _RBT-RCONN  ( -- address ) _RBT-RCONN-STORE 7 + -8 AND ;

VARIABLE _RBT-RCONN-ENTRY
VARIABLE _RBT-RCONN-GENERATION
VARIABLE _RBT-RCONN-STATUS
VARIABLE _RBT-RCONN-ITEM
VARIABLE _RBT-RCONN-SUBJECT
VARIABLE _RBT-RCONN-ITEM-GENERATION
VARIABLE _RBT-RCONN-OP
VARIABLE _RBT-RCONN-OP-GENERATION
VARIABLE _RBT-RCONN-ATTACHMENT-GENERATION
VARIABLE _RBT-RCONN-NEW-OP
VARIABLE _RBT-RCONN-NEW-OP-GENERATION
VARIABLE _RBT-RCONN-NEW-ATTACHMENT-GENERATION
VARIABLE _RBT-RCONN-TXN-A
VARIABLE _RBT-RCONN-TXN-U
VARIABLE _RBT-RCONN-POLL-BEFORE

: _RBT-RCONN-PEER-FINI  ( -- )
    _RBT-CLI-CONN-B RABBIT-CONNECTION-CANCEL
        DUP RCONN-S-CANCELLED = SWAP RCONN-S-OK = OR _RBT-ASSERT
    _RBT-CLI-CONN-B RABBIT-CONNECTION-FINI RCONN-S-OK = _RBT-ASSERT
    _RBT-CLI-PHASE-TEARDOWN-QUEUES
    _RBT-CLI-EPA _RBT-CLI-EPB NMD-PAIR-FINI NIO-S-OK = _RBT-ASSERT
    _RBT-CLI-PUMP-BAD @ 0= _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER ;

: _RBT-RCONN-ASSERT-ENTRY  ( expected-state -- )
    _RBT-RCONN-ENTRY @ _RBT-RCONN-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-STATE@
        RSUB-S-OK = _RBT-ASSERT = _RBT-ASSERT
    _RBT-RCONN-ENTRY @ _RBT-RCONN-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-TARGET$
        RSUB-S-OK = _RBT-ASSERT
        S" /fixture/events" STR-STR= _RBT-ASSERT
    _RBT-RCONN-ENTRY @ _RBT-RCONN-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-CURSOR@
        RSUB-S-OK = _RBT-ASSERT 10 = _RBT-ASSERT ;

: _RBT-RCONN-ASSERT-PENDING-POLL  ( -- )
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-POLL-COUNT@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        _RBT-RCONN-POLL-BEFORE !
    0 0 _RBT-RCONN STREAMS-RABBIT-CONNECTOR-POLL
        STREAMS-RABBIT-CONNECTOR-S-PENDING = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
        RSUB-ITEM-NONE = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-POLL-COUNT@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        _RBT-RCONN-POLL-BEFORE @ 1+ = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-LAST-ACTIVITY@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
        STREAMS-RABBIT-CONNECTOR-ACTIVITY-NONE = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-DETAIL@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        RSUB-S-PENDING = _RBT-ASSERT ;

: _RBT-RCONN-POLL  ( -- )
    ['] _RBT-CLI-DISPATCH 0xC11E _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-POLL
        _RBT-RCONN-STATUS ! _RBT-RCONN-ITEM-GENERATION !
        _RBT-RCONN-SUBJECT ! _RBT-RCONN-ITEM ! ;

: _RBT-RCONN-UNTIL-SERVER-RX  ( -- flag )
    128 0 ?DO
        _RBT-CLI-CONN-B RABBIT-CONNECTION-RX-READY? IF
            -1 UNLOOP EXIT
        THEN
        _RBT-RCONN-POLL
        _RBT-CLI-CONN-B _RBT-CLI-CONNECTION-STEP
    LOOP
    _RBT-CLI-CONN-B RABBIT-CONNECTION-RX-READY? ;

: _RBT-RCONN-UNTIL-CLIENT-ITEM  ( -- flag )
    128 0 ?DO
        _RBT-CLI-CONN-B _RBT-CLI-CONNECTION-STEP
        _RBT-RCONN-POLL
        _RBT-RCONN-ITEM @ RSUB-ITEM-NONE <> IF
            -1 UNLOOP EXIT
        THEN
    LOOP
    _RBT-RCONN-ITEM @ RSUB-ITEM-NONE <> ;

: _RBT-RCONN-SERVER-EXPECT  ( kind txn-a txn-u -- )
    _RBT-RCONN-TXN-U ! _RBT-RCONN-TXN-A ! _RBT-EXPECTED !
    _RBT-RCONN-UNTIL-SERVER-RX _RBT-ASSERT
    _RBT-CLI-SERVER-LOAN
    _RBT-CLI-KIND @ _RBT-EXPECTED @ = _RBT-ASSERT
    _RBT-CLI-LANE @ 1 = _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-TXN$
        RMSG-S-OK = _RBT-ASSERT _RBT-ASSERT
        _RBT-RCONN-TXN-A @ _RBT-RCONN-TXN-U @ STR-STR= _RBT-ASSERT
    _RBT-CLI-SERVER-COMMIT ;

: _RBT-RCONN-PHASE-INIT  ( -- )
    _RBT-CLI-PHASE-INIT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-SIZE 0xA5 FILL
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-SIZE 0xA5 FILL
    _RBT-SUB-ENTRIES RABBIT-SUBSCRIPTION-ENTRY-SIZE 0xA5 FILL
    _RBT-SUB-TARGET-ARENA 32 0xA5 FILL
    _RBT-SUB-EVENT-ARENA 32 0xA5 FILL
    _RBT-SUB-ENTRIES 1 _RBT-SUB-TARGET-ARENA 32
        _RBT-SUB-EVENT-ARENA 32 _RBT-CLI-CLIENT _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTIONS-INIT RSUB-S-OK = _RBT-ASSERT
    S" /fixture/events" 1 10 ['] _RBT-SUB-CALLBACK 0x5A8
        _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-ADD
        _RBT-RCONN-STATUS ! _RBT-RCONN-GENERATION !
        _RBT-RCONN-ENTRY !
    _RBT-RCONN-STATUS @ RSUB-S-OK = _RBT-ASSERT
    _RBT-RCONN-ENTRY @ 0<> _RBT-ASSERT
    _RBT-RCONN-GENERATION @ 0<> _RBT-ASSERT

    _RBT-SUB-OWNER _RBT-CLI-CLIENT _RBT-SUB-OWNER
        STREAMS-RABBIT-CONNECTOR-INIT
        STREAMS-RABBIT-CONNECTOR-S-INVALID = _RBT-ASSERT
    _RBT-SUB-OWNER _RBT-CLI-CLIENT _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-INIT
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-VALID? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-STATE@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        STREAMS-RABBIT-CONNECTOR-ST-ATTACHED = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-CLIENT@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        _RBT-CLI-CLIENT = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-SUBSCRIPTIONS@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        _RBT-SUB-OWNER = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-RECONNECT-COUNT@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-ATTACHMENT-GENERATION@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT 1 = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-SIZE _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-SIZE _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? _RBT-ASSERT
    _RBT-SUB-ENTRIES RABBIT-SUBSCRIPTION-ENTRY-SIZE _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? _RBT-ASSERT
    _RBT-SUB-TARGET-ARENA 32 _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? _RBT-ASSERT
    _RBT-SUB-EVENT-ARENA 32 _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? _RBT-ASSERT
    _RBT-CLI-CLIENT RABBIT-CLIENT-SIZE _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? _RBT-ASSERT
    _RBT-MSGB-BUILDER 12 RMSGB-BUILDER-BYTES _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    0 0 _RBT-RCONN STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP?
        0= _RBT-ASSERT
    0 -1 _RBT-RCONN STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP?
        _RBT-ASSERT
    RSUB-ENTRY-CONFIGURED _RBT-RCONN-ASSERT-ENTRY
    _RBT-RCONN-ASSERT-PENDING-POLL
    _RBT-STACK ;

: _RBT-RCONN-HANDSHAKE  ( -- )
    _RBT-CLI-RESET-BUILDER
    RABBIT-CAPS-LANES-ASYNC _RBT-MSGB-BUILDER RMSGB-BEGIN-HELLO
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER _RBT-RCONN STREAMS-RABBIT-CONNECTOR-HELLO
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT 0<> _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    _RBT-RCONN-UNTIL-SERVER-RX _RBT-ASSERT
    _RBT-CLI-SERVER-LOAN
    _RBT-CLI-KIND @ RMSG-KIND-HELLO = _RBT-ASSERT
    _RBT-CLI-SERVER-COMMIT

    RABBIT-CAPS-LANES-ASYNC S" connector-fixture" _RBT-MSGB-BUILDER
        RMSGB-BEGIN-HELLO-OK RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-ENQUEUE-B
    _RBT-RCONN-UNTIL-CLIENT-ITEM _RBT-ASSERT
    _RBT-RCONN-STATUS @ STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN-ITEM @ RSUB-ITEM-OTHER = _RBT-ASSERT

    1 _RBT-RCONN STREAMS-RABBIT-CONNECTOR-LANE-ENSURE
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    1 _RBT-CLI-SESSB RABBIT-SESSION-APP-LANE-OPEN
        RABBIT-S-OK = _RBT-ASSERT
    1 4 _RBT-MSGB-BUILDER RMSGB-BEGIN-CREDIT
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER _RBT-RCONN STREAMS-RABBIT-CONNECTOR-CONTROL
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT 0<> _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    _RBT-RCONN-UNTIL-SERVER-RX _RBT-ASSERT
    _RBT-CLI-SERVER-LOAN
    _RBT-CLI-KIND @ RMSG-KIND-CREDIT = _RBT-ASSERT
    _RBT-CLI-SERVER-COMMIT ;

: _RBT-RCONN-PHASE-RESULT-OWNERSHIP  ( -- )
    _RBT-RCONN-HANDSHAKE
    RMSG-KIND-FETCH S" /connector" 1 S" RCONN"
        _RBT-MSGB-BUILDER RMSGB-BEGIN-REQUEST
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER _RBT-RCONN STREAMS-RABBIT-CONNECTOR-REQUEST
        _RBT-RCONN-STATUS ! _RBT-RCONN-ATTACHMENT-GENERATION !
        _RBT-RCONN-OP-GENERATION ! _RBT-RCONN-OP !
    _RBT-RCONN-STATUS @ STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN-OP @ 0<> _RBT-ASSERT
    _RBT-RCONN-OP-GENERATION @ 0<> _RBT-ASSERT
    _RBT-RCONN-OP @ _RBT-RCONN-OP-GENERATION @
        _RBT-RCONN-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-STATE@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        RCLIENT-S-PENDING = _RBT-ASSERT
        RCLIENT-OP-PENDING = _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    RMSG-KIND-FETCH S" RCONN" _RBT-RCONN-SERVER-EXPECT

    200 S" RESULT" 1 S" RCONN" _RBT-MSGB-BUILDER
        RMSGB-BEGIN-RESPONSE RMSGB-S-OK = _RBT-ASSERT
    S" application/test" _RBT-MSGB-BUILDER RMSGB-VIEW!
        RMSGB-S-OK = _RBT-ASSERT
    S" connector-result" _RBT-MSGB-BUILDER RMSGB-BODY!
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-ENQUEUE-B
    _RBT-RCONN-UNTIL-CLIENT-ITEM _RBT-ASSERT
    _RBT-RCONN-STATUS @ STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN-ITEM @ RSUB-ITEM-CLIENT-OP = _RBT-ASSERT
    _RBT-RCONN-SUBJECT @ _RBT-RCONN-OP @ = _RBT-ASSERT
    _RBT-RCONN-ITEM-GENERATION @
        _RBT-RCONN-OP-GENERATION @ = _RBT-ASSERT

    _RBT-RCONN-OP @ _RBT-RCONN-OP-GENERATION @
        _RBT-RCONN-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-STATE@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        RCLIENT-S-OK = _RBT-ASSERT
        RCLIENT-OP-COMPLETE = _RBT-ASSERT

    _RBT-RCONN-OP @ _RBT-RCONN-OP-GENERATION @
        _RBT-RCONN-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-RESULT@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        S" connector-result" STR-STR= _RBT-ASSERT
        200 = _RBT-ASSERT
    _RBT-RCONN-OP @ _RBT-RCONN-OP-GENERATION @
        _RBT-RCONN-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-REQUIRED@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        16 = _RBT-ASSERT
    _RBT-RCONN-OP @ _RBT-RCONN-OP-GENERATION @ 1+
        _RBT-RCONN-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-STATE@
        STREAMS-RABBIT-CONNECTOR-S-CLIENT = _RBT-ASSERT
        RCLIENT-S-INVALID = _RBT-ASSERT
        RCLIENT-OP-EMPTY = _RBT-ASSERT
    _RBT-RCONN-OP @ _RBT-RCONN-OP-GENERATION @ 1+
        _RBT-RCONN-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-RESULT@
        STREAMS-RABBIT-CONNECTOR-S-CLIENT = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-DETAIL@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        RCLIENT-S-NOT-FOUND = _RBT-ASSERT
    _RBT-RCONN-OP @ _RBT-RCONN-OP-GENERATION @
        _RBT-RCONN-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-RELEASE
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN-OP @ _RBT-RCONN-OP-GENERATION @
        _RBT-RCONN-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-RELEASE
        STREAMS-RABBIT-CONNECTOR-S-CLIENT = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-VALID? _RBT-ASSERT
    _RBT-STACK ;

: _RBT-RCONN-PHASE-DETACH  ( -- )
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-DETACH
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-VALID? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-STATE@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        STREAMS-RABBIT-CONNECTOR-ST-DETACHED = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-CLIENT@
        STREAMS-RABBIT-CONNECTOR-S-DISCONNECTED = _RBT-ASSERT
        0= _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-STATE@
        RSUB-S-OK = _RBT-ASSERT RSUB-ST-DETACHED = _RBT-ASSERT
    RSUB-ENTRY-NEEDS-REBIND _RBT-RCONN-ASSERT-ENTRY
    _RBT-CLI-CLIENT RABBIT-CLIENT-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-CONN-A RABBIT-CONNECTION-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    0 0 _RBT-RCONN STREAMS-RABBIT-CONNECTOR-POLL
        STREAMS-RABBIT-CONNECTOR-S-DISCONNECTED = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
        RSUB-ITEM-NONE = _RBT-ASSERT
    _RBT-RCONN-PEER-FINI
    _RBT-STACK ;

: _RBT-RCONN-PHASE-ATTACH  ( -- )
    _RBT-CLI-PHASE-INIT
    RABBIT-U64-MAX _RBT-RCONN SRCONN.ATTACHMENT-GENERATION !
    _RBT-CLI-CLIENT _RBT-RCONN STREAMS-RABBIT-CONNECTOR-ATTACH
        STREAMS-RABBIT-CONNECTOR-S-CAPACITY = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-VALID? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-STATE@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        STREAMS-RABBIT-CONNECTOR-ST-DETACHED = _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-STATE@
        RSUB-S-OK = _RBT-ASSERT RSUB-ST-DETACHED = _RBT-ASSERT
    1 _RBT-RCONN SRCONN.ATTACHMENT-GENERATION !
    _RBT-CLI-CLIENT _RBT-RCONN STREAMS-RABBIT-CONNECTOR-ATTACH
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-VALID? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-STATE@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        STREAMS-RABBIT-CONNECTOR-ST-ATTACHED = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-RECONNECT-COUNT@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT 1 = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-ATTACHMENT-GENERATION@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT 2 = _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-STATE@
        RSUB-S-OK = _RBT-ASSERT RSUB-ST-ATTACHED = _RBT-ASSERT
    RSUB-ENTRY-NEEDS-REBIND _RBT-RCONN-ASSERT-ENTRY
    _RBT-RCONN-ASSERT-PENDING-POLL
    _RBT-STACK ;

: _RBT-RCONN-PHASE-RECONNECT-ABA  ( -- )
    _RBT-RCONN-HANDSHAKE
    RMSG-KIND-FETCH S" /connector" 1 S" RCON2"
        _RBT-MSGB-BUILDER RMSGB-BEGIN-REQUEST
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER _RBT-RCONN STREAMS-RABBIT-CONNECTOR-REQUEST
        _RBT-RCONN-STATUS ! _RBT-RCONN-NEW-ATTACHMENT-GENERATION !
        _RBT-RCONN-NEW-OP-GENERATION ! _RBT-RCONN-NEW-OP !
    _RBT-RCONN-STATUS @ STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN-NEW-OP @ _RBT-RCONN-OP @ = _RBT-ASSERT
    _RBT-RCONN-NEW-OP-GENERATION @
        _RBT-RCONN-OP-GENERATION @ = _RBT-ASSERT
    _RBT-RCONN-NEW-ATTACHMENT-GENERATION @
        _RBT-RCONN-ATTACHMENT-GENERATION @ <> _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    RMSG-KIND-FETCH S" RCON2" _RBT-RCONN-SERVER-EXPECT

    200 S" RESULT" 1 S" RCON2" _RBT-MSGB-BUILDER
        RMSGB-BEGIN-RESPONSE RMSGB-S-OK = _RBT-ASSERT
    S" application/test" _RBT-MSGB-BUILDER RMSGB-VIEW!
        RMSGB-S-OK = _RBT-ASSERT
    S" second-attach" _RBT-MSGB-BUILDER RMSGB-BODY!
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-ENQUEUE-B
    _RBT-RCONN-UNTIL-CLIENT-ITEM _RBT-ASSERT
    _RBT-RCONN-ITEM @ RSUB-ITEM-CLIENT-OP = _RBT-ASSERT
    _RBT-RCONN-SUBJECT @ _RBT-RCONN-NEW-OP @ = _RBT-ASSERT
    _RBT-RCONN-ITEM-GENERATION @
        _RBT-RCONN-NEW-OP-GENERATION @ = _RBT-ASSERT

    _RBT-RCONN-OP @ _RBT-RCONN-OP-GENERATION @
        _RBT-RCONN-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-RESULT@
        STREAMS-RABBIT-CONNECTOR-S-CLIENT = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-RCONN-OP @ _RBT-RCONN-OP-GENERATION @
        _RBT-RCONN-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-REQUIRED@
        STREAMS-RABBIT-CONNECTOR-S-CLIENT = _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-RCONN-OP @ _RBT-RCONN-OP-GENERATION @
        _RBT-RCONN-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-RELEASE
        STREAMS-RABBIT-CONNECTOR-S-CLIENT = _RBT-ASSERT

    _RBT-RCONN-NEW-OP @ _RBT-RCONN-NEW-OP-GENERATION @
        _RBT-RCONN-NEW-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-RESULT@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        S" second-attach" STR-STR= _RBT-ASSERT
        200 = _RBT-ASSERT
    _RBT-RCONN-NEW-OP @ _RBT-RCONN-NEW-OP-GENERATION @
        _RBT-RCONN-NEW-ATTACHMENT-GENERATION @ _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-OP-RELEASE
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-VALID? _RBT-ASSERT
    _RBT-STACK ;

: _RBT-RCONN-PHASE-FINI  ( -- )
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-FINI
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-VALID? 0= _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-ENTRIES RABBIT-SUBSCRIPTION-ENTRY-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-TARGET-ARENA 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-EVENT-ARENA 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-CLIENT RABBIT-CLIENT-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-CONN-A RABBIT-CONNECTION-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-FINI
        STREAMS-RABBIT-CONNECTOR-S-INVALID = _RBT-ASSERT
    _RBT-RCONN-PEER-FINI
    _RBT-STACK ;
