\ Stateful contracts for generic Rabbit subscriptions and replay cursors.

PROVIDED rabbit-sub-test

CREATE _RBT-SUB-OWNER-STORE RABBIT-SUBSCRIPTIONS-SIZE 7 + ALLOT
CREATE _RBT-SUB-ZERO-OWNER-STORE RABBIT-SUBSCRIPTIONS-SIZE 7 + ALLOT
CREATE _RBT-SUB-REENTRY-OWNER-STORE RABBIT-SUBSCRIPTIONS-SIZE 7 + ALLOT
CREATE _RBT-SUB-ENTRIES-STORE
    RABBIT-SUBSCRIPTION-ENTRY-SIZE 3 * 7 + ALLOT
CREATE _RBT-SUB-TARGET-ARENA 96 ALLOT
CREATE _RBT-SUB-EVENT-ARENA 96 ALLOT
CREATE _RBT-SUB-TARGET-SOURCE 32 ALLOT

: _RBT-SUB-OWNER  ( -- address )
    _RBT-SUB-OWNER-STORE 7 + -8 AND ;

: _RBT-SUB-ZERO-OWNER  ( -- address )
    _RBT-SUB-ZERO-OWNER-STORE 7 + -8 AND ;

: _RBT-SUB-REENTRY-OWNER  ( -- address )
    _RBT-SUB-REENTRY-OWNER-STORE 7 + -8 AND ;

: _RBT-SUB-ENTRIES  ( -- address )
    _RBT-SUB-ENTRIES-STORE 7 + -8 AND ;

VARIABLE _RBT-SUB-ENTRY
VARIABLE _RBT-SUB-GENERATION
VARIABLE _RBT-SUB-ENTRY2
VARIABLE _RBT-SUB-GENERATION2
VARIABLE _RBT-SUB-OP
VARIABLE _RBT-SUB-OP-GENERATION
VARIABLE _RBT-SUB-PENDING-OP
VARIABLE _RBT-SUB-PENDING-GENERATION
VARIABLE _RBT-SUB-ITEM
VARIABLE _RBT-SUB-SUBJECT
VARIABLE _RBT-SUB-OUT-GENERATION
VARIABLE _RBT-SUB-STATUS
VARIABLE _RBT-SUB-EVENTS
VARIABLE _RBT-SUB-DUPLICATES
VARIABLE _RBT-SUB-CB-ENTRY
VARIABLE _RBT-SUB-CB-GENERATION
VARIABLE _RBT-SUB-CB-LANE-SEQ
VARIABLE _RBT-SUB-CB-EVENT-SEQ
VARIABLE _RBT-SUB-CB-DELIVERY
VARIABLE _RBT-SUB-CB-TARGET-A
VARIABLE _RBT-SUB-CB-TARGET-U
VARIABLE _RBT-SUB-CB-EVENT-A
VARIABLE _RBT-SUB-CB-EVENT-U
VARIABLE _RBT-SUB-CB-CONTEXT
VARIABLE _RBT-SUB-EXPECT-LANE-SEQ
VARIABLE _RBT-SUB-EXPECT-EVENT-SEQ
VARIABLE _RBT-SUB-EXPECT-DELIVERY
VARIABLE _RBT-SUB-EXPECT-A
VARIABLE _RBT-SUB-EXPECT-U
VARIABLE _RBT-SUB-EXPECT-ACK

: _RBT-SUB-CALLBACK
  ( entry generation lane-seq event-seq delivery )
  ( target-a target-u event-a event-u context -- decision )
    _RBT-SUB-CB-CONTEXT !
    _RBT-SUB-CB-EVENT-U ! _RBT-SUB-CB-EVENT-A !
    _RBT-SUB-CB-TARGET-U ! _RBT-SUB-CB-TARGET-A !
    _RBT-SUB-CB-DELIVERY ! _RBT-SUB-CB-EVENT-SEQ !
    _RBT-SUB-CB-LANE-SEQ ! _RBT-SUB-CB-GENERATION !
    _RBT-SUB-CB-ENTRY !
    _RBT-SUB-CB-CONTEXT @ 0x5A8 = _RBT-ASSERT
    _RBT-SUB-CB-ENTRY @ _RBT-SUB-ENTRY @ = _RBT-ASSERT
    _RBT-SUB-CB-GENERATION @ _RBT-SUB-GENERATION @ = _RBT-ASSERT
    _RBT-SUB-CB-LANE-SEQ @ _RBT-SUB-EXPECT-LANE-SEQ @ = _RBT-ASSERT
    _RBT-SUB-CB-EVENT-SEQ @ _RBT-SUB-EXPECT-EVENT-SEQ @ = _RBT-ASSERT
    _RBT-SUB-CB-DELIVERY @ _RBT-SUB-EXPECT-DELIVERY @ = _RBT-ASSERT
    _RBT-SUB-CB-TARGET-A @ _RBT-SUB-CB-TARGET-U @
        S" /world/events" STR-STR= _RBT-ASSERT
    _RBT-SUB-CB-EVENT-A @ _RBT-SUB-CB-EVENT-U @
        _RBT-SUB-EXPECT-A @ _RBT-SUB-EXPECT-U @ STR-STR= _RBT-ASSERT
    0 0 _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-DISPATCH
        RSUB-S-STATE = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
        RSUB-ITEM-NONE = _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-DISCONNECT
        RSUB-S-STATE = _RBT-ASSERT
    0 0 0 0 0 0 _RBT-CLI-CLIENT _RBT-SUB-REENTRY-OWNER
        RABBIT-SUBSCRIPTIONS-INIT RSUB-S-STATE = _RBT-ASSERT
    _RBT-SUB-REENTRY-OWNER RABBIT-SUBSCRIPTIONS-SIZE
        0xA5 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-CB-DELIVERY @ RSUB-DELIVERY-NEW = IF
        1 _RBT-SUB-EVENTS +!
    THEN
    _RBT-SUB-CB-DELIVERY @ RSUB-DELIVERY-DUPLICATE = IF
        1 _RBT-SUB-DUPLICATES +!
    THEN
    RSUB-DISPATCH-COMMIT ;

: _RBT-SUB-BAD-FALLBACK
  ( frame kind lane seq expected disposition context -- decision )
    2DROP 2DROP 2DROP DROP 0xBAD ;

: _RBT-SUB-POLL  ( -- )
    0 0 _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-POLL
    _RBT-SUB-STATUS ! _RBT-SUB-OUT-GENERATION !
    _RBT-SUB-SUBJECT ! _RBT-SUB-ITEM ! ;

: _RBT-SUB-POLL-BAD  ( -- )
    ['] _RBT-SUB-BAD-FALLBACK 0x61 _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTIONS-POLL
    _RBT-SUB-STATUS ! _RBT-SUB-OUT-GENERATION !
    _RBT-SUB-SUBJECT ! _RBT-SUB-ITEM ! ;

: _RBT-SUB-UNTIL-SERVER-RX  ( -- flag )
    128 0 ?DO
        _RBT-CLI-CONN-B RABBIT-CONNECTION-RX-READY? IF
            -1 UNLOOP EXIT
        THEN
        _RBT-SUB-POLL
        _RBT-SUB-ITEM @ RSUB-ITEM-NONE <> IF
            -1 _RBT-CLI-PUMP-BAD !
        THEN
        _RBT-SUB-STATUS @ RSUB-S-PENDING <> IF
            -1 _RBT-CLI-PUMP-BAD !
        THEN
        _RBT-CLI-CONN-B _RBT-CLI-CONNECTION-STEP
    LOOP
    _RBT-CLI-CONN-B RABBIT-CONNECTION-RX-READY? ;

: _RBT-SUB-UNTIL-ITEM  ( -- flag )
    128 0 ?DO
        _RBT-CLI-CONN-B _RBT-CLI-CONNECTION-STEP
        _RBT-SUB-POLL
        _RBT-SUB-ITEM @ RSUB-ITEM-NONE <> IF
            -1 UNLOOP EXIT
        THEN
        _RBT-SUB-STATUS @ RSUB-S-PENDING <> IF
            -1 _RBT-CLI-PUMP-BAD !
        THEN
    LOOP
    _RBT-SUB-ITEM @ RSUB-ITEM-NONE <> ;

: _RBT-SUB-UNTIL-ITEM-BAD  ( -- flag )
    128 0 ?DO
        _RBT-CLI-CONN-B _RBT-CLI-CONNECTION-STEP
        _RBT-SUB-POLL-BAD
        _RBT-SUB-ITEM @ RSUB-ITEM-NONE <> IF
            -1 UNLOOP EXIT
        THEN
        _RBT-SUB-STATUS @ RSUB-S-PENDING <> IF
            -1 _RBT-CLI-PUMP-BAD !
        THEN
    LOOP
    _RBT-SUB-ITEM @ RSUB-ITEM-NONE <> ;

: _RBT-SUB-EXPECT-EVENT  ( body-a body-u lane-seq event-seq delivery -- )
    _RBT-SUB-EXPECT-DELIVERY ! _RBT-SUB-EXPECT-EVENT-SEQ !
    _RBT-SUB-EXPECT-LANE-SEQ !
    _RBT-SUB-EXPECT-U ! _RBT-SUB-EXPECT-A ! ;

: _RBT-SUB-ASSERT-OUTPUT  ( expected-status -- )
    _RBT-SUB-STATUS @ = _RBT-ASSERT
    _RBT-SUB-ITEM @ RSUB-ITEM-EVENT = _RBT-ASSERT
    _RBT-SUB-SUBJECT @ _RBT-SUB-ENTRY @ = _RBT-ASSERT
    _RBT-SUB-OUT-GENERATION @ _RBT-SUB-GENERATION @ = _RBT-ASSERT
    _RBT-SUB-EVENT-ARENA 32 0 _RBT-FILLED? _RBT-ASSERT ;

: _RBT-SUB-SEND-ACK  ( cumulative-lane-seq -- )
    DUP _RBT-SUB-EXPECT-ACK !
    1 SWAP _RBT-MSGB-BUILDER RMSGB-BEGIN-ACK
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER _RBT-CLI-CLIENT RABBIT-CLIENT-CONTROL
        RCLIENT-S-OK = _RBT-ASSERT 0<> _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    _RBT-SUB-UNTIL-SERVER-RX _RBT-ASSERT
    _RBT-CLI-SERVER-LOAN
    _RBT-CLI-KIND @ RMSG-KIND-ACK = _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-ACK@
        RMSG-S-OK = _RBT-ASSERT _RBT-ASSERT
        _RBT-SUB-EXPECT-ACK @ = _RBT-ASSERT
    _RBT-CLI-SERVER-COMMIT
    _RBT-CLI-DQB RCONN-TXQ-COUNT@
        RCONN-S-OK = _RBT-ASSERT 0= _RBT-ASSERT ;

: _RBT-SUB-SEND-CREDIT  ( amount -- )
    1 SWAP _RBT-MSGB-BUILDER RMSGB-BEGIN-CREDIT
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER _RBT-CLI-CLIENT RABBIT-CLIENT-CONTROL
        RCLIENT-S-OK = _RBT-ASSERT 0<> _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    _RBT-SUB-UNTIL-SERVER-RX _RBT-ASSERT
    _RBT-CLI-SERVER-LOAN
    _RBT-CLI-KIND @ RMSG-KIND-CREDIT = _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-CREDIT@
        RMSG-S-OK = _RBT-ASSERT _RBT-ASSERT
        2 = _RBT-ASSERT
    _RBT-CLI-SERVER-COMMIT ;

: _RBT-SUB-CANCELLED-GRAPH-FINI  ( -- )
    _RBT-CLI-CLIENT RABBIT-CLIENT-FINI RCLIENT-S-OK = _RBT-ASSERT
    _RBT-CLI-CLIENT RABBIT-CLIENT-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-CONN-A RABBIT-CONNECTION-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-CONN-B RABBIT-CONNECTION-CANCEL
        DUP RCONN-S-CANCELLED = SWAP RCONN-S-OK = OR _RBT-ASSERT
    _RBT-CLI-CONN-B RABBIT-CONNECTION-FINI RCONN-S-OK = _RBT-ASSERT
    _RBT-CLI-TXNS-A 4 RTXN-SIZE * 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-TXNS-B 4 RTXN-SIZE * 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-PHASE-TEARDOWN-QUEUES
    _RBT-CLI-EPA _RBT-CLI-EPB NMD-PAIR-FINI NIO-S-OK = _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    _RBT-STACK ;

: _RBT-SUB-PHASE-OWNER-INIT  ( -- )
    0 _RBT-SUB-EVENTS ! 0 _RBT-SUB-DUPLICATES !
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-SIZE 0xA5 FILL
    _RBT-SUB-ZERO-OWNER RABBIT-SUBSCRIPTIONS-SIZE 0xA5 FILL
    _RBT-SUB-REENTRY-OWNER RABBIT-SUBSCRIPTIONS-SIZE 0xA5 FILL
    _RBT-SUB-ENTRIES RABBIT-SUBSCRIPTION-ENTRY-SIZE 3 * 0xA5 FILL
    _RBT-SUB-TARGET-ARENA 96 0xA5 FILL
    _RBT-SUB-EVENT-ARENA 96 0xA5 FILL
    _RBT-SUB-ENTRIES 3 _RBT-SUB-TARGET-ARENA 32
        _RBT-SUB-EVENT-ARENA 32 _RBT-CLI-CLIENT _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTIONS-INIT RSUB-S-OK = _RBT-ASSERT
    0 0 0 0 0 0 _RBT-CLI-CLIENT _RBT-SUB-ZERO-OWNER
        RABBIT-SUBSCRIPTIONS-INIT RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-ZERO-OWNER RABBIT-SUBSCRIPTIONS-VALID? _RBT-ASSERT
    _RBT-SUB-ZERO-OWNER RABBIT-SUBSCRIPTIONS-CAPACITY@
        RSUB-S-OK = _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-VALID? _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-COUNT@
        RSUB-S-OK = _RBT-ASSERT 0= _RBT-ASSERT

    S" /world/control" 0 10 ['] _RBT-SUB-CALLBACK 0x5A8
        _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-ADD
        RSUB-S-INVALID = _RBT-ASSERT 0= _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-COUNT@
        RSUB-S-OK = _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-SUB-OWNER RSUB.NEXT-GENERATION @ 1 = _RBT-ASSERT
    _RBT-SUB-ENTRIES RABBIT-SUBSCRIPTION-ENTRY-SIZE 3 *
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-TARGET-ARENA 96 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-EVENT-ARENA 96 0 _RBT-FILLED? _RBT-ASSERT

    S" /world/events" _RBT-SUB-TARGET-SOURCE SWAP MOVE
    _RBT-SUB-TARGET-SOURCE 13 1 10 ['] _RBT-SUB-CALLBACK 0x5A8
        _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-ADD
        _RBT-SUB-STATUS ! _RBT-SUB-GENERATION ! _RBT-SUB-ENTRY !
    _RBT-SUB-STATUS @ RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-ENTRY @ 0<> _RBT-ASSERT
    _RBT-SUB-GENERATION @ 0<> _RBT-ASSERT
    _RBT-SUB-TARGET-SOURCE 32 0 FILL
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-TARGET$
        RSUB-S-OK = _RBT-ASSERT
        S" /world/events" STR-STR= _RBT-ASSERT
    S" /world/events" 1 _RBT-SUB-OWNER RABBIT-SUBSCRIPTION-FIND
        RSUB-S-OK = _RBT-ASSERT
        _RBT-SUB-GENERATION @ = _RBT-ASSERT
        _RBT-SUB-ENTRY @ = _RBT-ASSERT
    S" /world/events" 1 99 ['] _RBT-SUB-CALLBACK 0x7A1
        _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-ADD
        RSUB-S-DUPLICATE = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-COUNT@
        RSUB-S-OK = _RBT-ASSERT 1 = _RBT-ASSERT
    S" /world/terminal" 2 RABBIT-U64-MAX ['] _RBT-SUB-CALLBACK 0x7A2
        _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-ADD
        _RBT-SUB-STATUS ! _RBT-SUB-GENERATION2 ! _RBT-SUB-ENTRY2 !
    _RBT-SUB-STATUS @ RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-ENTRY2 @ _RBT-SUB-GENERATION2 @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-NEXT-EVENT@
        RSUB-S-OVERFLOW = _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-COUNT@
        RSUB-S-OK = _RBT-ASSERT 2 = _RBT-ASSERT
    RABBIT-U64-MAX _RBT-SUB-OWNER RSUB.NEXT-GENERATION !
    S" /world/exhausted" 2 0 ['] _RBT-SUB-CALLBACK 0x7A3
        _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-ADD
        RSUB-S-OVERFLOW = _RBT-ASSERT 0= _RBT-ASSERT 0= _RBT-ASSERT
    3 _RBT-SUB-OWNER RSUB.NEXT-GENERATION !
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-COUNT@
        RSUB-S-OK = _RBT-ASSERT 2 = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-STATE@
        RSUB-S-OK = _RBT-ASSERT RSUB-ENTRY-CONFIGURED = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-SUB-PHASE-FIRST-BIND  ( -- )
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ S" SUB1"
        _RBT-MSGB-BUILDER _RBT-SUB-OWNER RABBIT-SUBSCRIPTION-BIND
        _RBT-SUB-STATUS ! _RBT-SUB-OP-GENERATION ! _RBT-SUB-OP !
    _RBT-SUB-STATUS @ RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-OP @ 0<> _RBT-ASSERT
    _RBT-SUB-OP-GENERATION @ 0<> _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    _RBT-SUB-UNTIL-SERVER-RX _RBT-ASSERT
    _RBT-CLI-SERVER-LOAN
    _RBT-CLI-KIND @ RMSG-KIND-SUBSCRIBE = _RBT-ASSERT
    _RBT-CLI-LANE @ 1 = _RBT-ASSERT
    _RBT-CLI-FRAME @ RBF-ARGS$
        S" /world/events" STR-STR= _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-TXN$
        RMSG-S-OK = _RBT-ASSERT _RBT-ASSERT
        S" SUB1" STR-STR= _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-SINCE@
        RMSG-S-OK = _RBT-ASSERT _RBT-ASSERT 10 = _RBT-ASSERT
    _RBT-CLI-SERVER-COMMIT

    200 S" RESULT" 1 S" SUB1" _RBT-MSGB-BUILDER
        RMSGB-BEGIN-RESPONSE RMSGB-S-OK = _RBT-ASSERT
    S" bound-one" _RBT-MSGB-BUILDER RMSGB-BODY!
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-ENQUEUE-B
    _RBT-SUB-UNTIL-ITEM _RBT-ASSERT
    _RBT-SUB-STATUS @ RSUB-S-BIND-RESULT = _RBT-ASSERT
    _RBT-SUB-ITEM @ RSUB-ITEM-BIND = _RBT-ASSERT
    _RBT-SUB-SUBJECT @ _RBT-SUB-ENTRY @ = _RBT-ASSERT
    _RBT-SUB-OUT-GENERATION @ _RBT-SUB-GENERATION @ = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-BIND-RESULT@
        RSUB-S-OK = _RBT-ASSERT
        S" bound-one" STR-STR= _RBT-ASSERT 200 = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ -1 _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-BIND-RESOLVE RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-STATE@
        RSUB-S-OK = _RBT-ASSERT RSUB-ENTRY-BOUND = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-SUB-PHASE-EVENT-NEW  ( -- )
    S" event-one" 1 11 RSUB-DELIVERY-NEW _RBT-SUB-EXPECT-EVENT
    S" /world/events" 1 1 11 _RBT-MSGB-BUILDER RMSGB-BEGIN-EVENT
        RMSGB-S-OK = _RBT-ASSERT
    S" event-one" _RBT-MSGB-BUILDER RMSGB-BODY!
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-ENQUEUE-B
    _RBT-SUB-UNTIL-ITEM _RBT-ASSERT
    RSUB-S-EVENT _RBT-SUB-ASSERT-OUTPUT
    _RBT-SUB-EVENTS @ 1 = _RBT-ASSERT
    _RBT-CLI-DQB RCONN-TXQ-COUNT@
        RCONN-S-OK = _RBT-ASSERT 1 = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-CURSOR@
        RSUB-S-OK = _RBT-ASSERT 11 = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-SUB-PHASE-FALLBACK-INVALID  ( -- )
    S" FUTURE" S" /future" _RBT-MSGB-BUILDER RMSGB-BEGIN-EXTENSION
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-ENQUEUE-B
    _RBT-SUB-UNTIL-ITEM-BAD _RBT-ASSERT
    _RBT-SUB-STATUS @ RSUB-S-CALLBACK = _RBT-ASSERT
    _RBT-SUB-ITEM @ RSUB-ITEM-OTHER = _RBT-ASSERT
    _RBT-SUB-SUBJECT @ 0= _RBT-ASSERT
    _RBT-SUB-OUT-GENERATION @ 0= _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-DETAIL@
        RSUB-S-OK = _RBT-ASSERT 0xBAD = _RBT-ASSERT
    _RBT-CLI-CLIENT RABBIT-CLIENT-STATE@
        RCLIENT-S-OK = _RBT-ASSERT RCLIENT-ST-READY = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-SUB-PHASE-EVENT-NEW-ACK  ( -- )
    1 _RBT-SUB-SEND-ACK
    _RBT-STACK ;

: _RBT-SUB-PHASE-EVENT-DUPLICATE  ( -- )
    S" event-one" 2 11 RSUB-DELIVERY-DUPLICATE _RBT-SUB-EXPECT-EVENT
    S" /world/events" 1 2 11 _RBT-MSGB-BUILDER RMSGB-BEGIN-EVENT
        RMSGB-S-OK = _RBT-ASSERT
    S" event-one" _RBT-MSGB-BUILDER RMSGB-BODY!
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-ENQUEUE-B
    _RBT-SUB-UNTIL-ITEM _RBT-ASSERT
    RSUB-S-EVENT-DUPLICATE _RBT-SUB-ASSERT-OUTPUT
    _RBT-SUB-DUPLICATES @ 1 = _RBT-ASSERT
    _RBT-CLI-DQB RCONN-TXQ-COUNT@
        RCONN-S-OK = _RBT-ASSERT 1 = _RBT-ASSERT
    2 _RBT-SUB-SEND-ACK
    2 _RBT-SUB-SEND-CREDIT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-LAST-LANE-SEQ@
        RSUB-S-OK = _RBT-ASSERT 2 = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-SUB-PHASE-EVENT-GAP  ( -- )
    S" /world/events" 1 3 13 _RBT-MSGB-BUILDER RMSGB-BEGIN-EVENT
        RMSGB-S-OK = _RBT-ASSERT
    S" event-gap" _RBT-MSGB-BUILDER RMSGB-BODY!
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-ENQUEUE-B
    _RBT-SUB-UNTIL-ITEM _RBT-ASSERT
    RSUB-S-GAP _RBT-SUB-ASSERT-OUTPUT
    _RBT-SUB-EVENTS @ 1 = _RBT-ASSERT
    _RBT-SUB-DUPLICATES @ 1 = _RBT-ASSERT
    _RBT-CLI-DQB RCONN-TXQ-COUNT@
        RCONN-S-OK = _RBT-ASSERT 1 = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-CURSOR@
        RSUB-S-OK = _RBT-ASSERT 11 = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-LAST-DELIVERY@
        RSUB-S-OK = _RBT-ASSERT RSUB-DELIVERY-GAP = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-LAST-OBSERVED-EVENT-SEQ@
        RSUB-S-OK = _RBT-ASSERT 13 = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-SUB-PHASE-DISCONNECT  ( -- )
    _RBT-SUB-ENTRY2 @ _RBT-SUB-GENERATION2 @ S" SUBP"
        _RBT-MSGB-BUILDER _RBT-SUB-OWNER RABBIT-SUBSCRIPTION-BIND
        _RBT-SUB-STATUS ! _RBT-SUB-PENDING-GENERATION !
        _RBT-SUB-PENDING-OP !
    _RBT-SUB-STATUS @ RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-PENDING-OP @ 0<> _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-DISCONNECT
        RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-STATE@
        RSUB-S-OK = _RBT-ASSERT RSUB-ST-DETACHED = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-STATE@
        RSUB-S-OK = _RBT-ASSERT RSUB-ENTRY-NEEDS-REBIND = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-CURSOR@
        RSUB-S-OK = _RBT-ASSERT 11 = _RBT-ASSERT
    _RBT-SUB-ENTRY2 @ _RBT-SUB-GENERATION2 @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-STATE@
        RSUB-S-OK = _RBT-ASSERT RSUB-ENTRY-NEEDS-REBIND = _RBT-ASSERT
    _RBT-SUB-PENDING-OP @ _RBT-SUB-PENDING-GENERATION @
        _RBT-CLI-CLIENT RABBIT-CLIENT-OP-MATCH?
        RCLIENT-S-OK = _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-STACK ;

: _RBT-SUB-PHASE-DISCONNECT-GRAPH-FINI  ( -- )
    _RBT-SUB-CANCELLED-GRAPH-FINI ;

: _RBT-SUB-PHASE-REBIND  ( -- )
    _RBT-CLI-CLIENT _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-ATTACH
        RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ S" SUB2"
        _RBT-MSGB-BUILDER _RBT-SUB-OWNER RABBIT-SUBSCRIPTION-BIND
        _RBT-SUB-STATUS ! _RBT-SUB-OP-GENERATION ! _RBT-SUB-OP !
    _RBT-SUB-STATUS @ RSUB-S-OK = _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    _RBT-SUB-UNTIL-SERVER-RX _RBT-ASSERT
    _RBT-CLI-SERVER-LOAN
    _RBT-CLI-KIND @ RMSG-KIND-SUBSCRIBE = _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-TXN$
        RMSG-S-OK = _RBT-ASSERT _RBT-ASSERT
        S" SUB2" STR-STR= _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-SINCE@
        RMSG-S-OK = _RBT-ASSERT _RBT-ASSERT 11 = _RBT-ASSERT
    _RBT-CLI-SERVER-COMMIT
    200 S" RESULT" 1 S" SUB2" _RBT-MSGB-BUILDER
        RMSGB-BEGIN-RESPONSE RMSGB-S-OK = _RBT-ASSERT
    S" rebound" _RBT-MSGB-BUILDER RMSGB-BODY!
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-ENQUEUE-B
    _RBT-SUB-UNTIL-ITEM _RBT-ASSERT
    _RBT-SUB-STATUS @ RSUB-S-BIND-RESULT = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ -1 _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-BIND-RESOLVE RSUB-S-OK = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-SUB-PHASE-REPLAY  ( -- )
    S" event-two" 1 12 RSUB-DELIVERY-NEW _RBT-SUB-EXPECT-EVENT
    S" /world/events" 1 1 12 _RBT-MSGB-BUILDER RMSGB-BEGIN-EVENT
        RMSGB-S-OK = _RBT-ASSERT
    S" event-two" _RBT-MSGB-BUILDER RMSGB-BODY!
        RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-ENQUEUE-B
    _RBT-SUB-UNTIL-ITEM _RBT-ASSERT
    RSUB-S-EVENT _RBT-SUB-ASSERT-OUTPUT
    _RBT-SUB-EVENTS @ 2 = _RBT-ASSERT
    _RBT-CLI-DQB RCONN-TXQ-COUNT@
        RCONN-S-OK = _RBT-ASSERT 1 = _RBT-ASSERT
    1 _RBT-SUB-SEND-ACK
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-CURSOR@
        RSUB-S-OK = _RBT-ASSERT 12 = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-SUB-PHASE-FINI  ( -- )
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-DISCONNECT
        RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-ZERO-OWNER RABBIT-SUBSCRIPTIONS-DISCONNECT
        RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-ZERO-OWNER RABBIT-SUBSCRIPTIONS-FINI
        RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-ZERO-OWNER RABBIT-SUBSCRIPTIONS-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-RELEASE RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-MATCH?
        RSUB-S-OK = _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-SUB-ENTRY @ _RBT-SUB-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-RELEASE RSUB-S-NOT-FOUND = _RBT-ASSERT
    _RBT-SUB-ENTRY2 @ _RBT-SUB-GENERATION2 @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-RELEASE RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-COUNT@
        RSUB-S-OK = _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-FINI RSUB-S-OK = _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-ENTRIES RABBIT-SUBSCRIPTION-ENTRY-SIZE 3 *
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-TARGET-ARENA 96 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-EVENT-ARENA 96 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-CANCELLED-GRAPH-FINI
    _RBT-STACK ;
