\ Focused lifecycle contracts for the Streams-owned Rabbit connector.

PROVIDED rabbit-connector-test

CREATE _RBT-RCONN-STORE STREAMS-RABBIT-CONNECTOR-SIZE 7 + ALLOT

: _RBT-RCONN  ( -- address ) _RBT-RCONN-STORE 7 + -8 AND ;

VARIABLE _RBT-RCONN-ENTRY
VARIABLE _RBT-RCONN-GENERATION
VARIABLE _RBT-RCONN-STATUS

: _RBT-RCONN-PEER-FINI  ( -- )
    _RBT-CLI-CONN-B RABBIT-CONNECTION-CANCEL
        DUP RCONN-S-CANCELLED = SWAP RCONN-S-OK = OR _RBT-ASSERT
    _RBT-CLI-CONN-B RABBIT-CONNECTION-FINI RCONN-S-OK = _RBT-ASSERT
    _RBT-CLI-PHASE-TEARDOWN-QUEUES
    _RBT-CLI-EPA _RBT-CLI-EPB NMD-PAIR-FINI NIO-S-OK = _RBT-ASSERT
    _RBT-CLI-PUMP-BAD @ 0= _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER ;

: _RBT-RCONN-ASSERT-ENTRY  ( expected-state -- )
    _RBT-RCONN-ENTRY @ _RBT-RCONN-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-STATE@
        RSUB-S-OK = _RBT-ASSERT = _RBT-ASSERT
    _RBT-RCONN-ENTRY @ _RBT-RCONN-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-TARGET$
        RSUB-S-OK = _RBT-ASSERT
        S" /fixture/events" STR-STR= _RBT-ASSERT
    _RBT-RCONN-ENTRY @ _RBT-RCONN-GENERATION @ _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTION-CURSOR@
        RSUB-S-OK = _RBT-ASSERT 10 = _RBT-ASSERT ;

: _RBT-RCONN-ASSERT-PENDING-POLL  ( expected-count -- )
    >R
    0 0 _RBT-RCONN STREAMS-RABBIT-CONNECTOR-POLL
        STREAMS-RABBIT-CONNECTOR-S-PENDING = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
        RSUB-ITEM-NONE = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-POLL-COUNT@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        R> = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-LAST-ACTIVITY@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
        STREAMS-RABBIT-CONNECTOR-ACTIVITY-NONE = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-DETAIL@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        RSUB-S-PENDING = _RBT-ASSERT ;

: _RBT-RCONN-PHASE-INIT  ( -- )
    _RBT-CLI-PHASE-INIT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-SIZE 0xA5 FILL
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-SIZE 0xA5 FILL
    _RBT-SUB-ENTRIES RABBIT-SUBSCRIPTION-ENTRY-SIZE 0xA5 FILL
    _RBT-SUB-TARGET-ARENA 32 0xA5 FILL
    _RBT-SUB-EVENT-ARENA 32 0xA5 FILL
    _RBT-SUB-ENTRIES 1 _RBT-SUB-TARGET-ARENA 32
        _RBT-SUB-EVENT-ARENA 32 _RBT-CLI-CLIENT _RBT-SUB-OWNER
        RABBIT-SUBSCRIPTIONS-INIT RSUB-S-OK = _RBT-ASSERT
    S" /fixture/events" 1 10 ['] _RBT-SUB-CALLBACK 0x5A8
        _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-ADD
        _RBT-RCONN-STATUS ! _RBT-RCONN-GENERATION !
        _RBT-RCONN-ENTRY !
    _RBT-RCONN-STATUS @ RSUB-S-OK = _RBT-ASSERT
    _RBT-RCONN-ENTRY @ 0<> _RBT-ASSERT
    _RBT-RCONN-GENERATION @ 0<> _RBT-ASSERT

    _RBT-SUB-OWNER _RBT-CLI-CLIENT _RBT-SUB-OWNER
        STREAMS-RABBIT-CONNECTOR-INIT
        STREAMS-RABBIT-CONNECTOR-S-INVALID = _RBT-ASSERT
    _RBT-SUB-OWNER _RBT-CLI-CLIENT _RBT-RCONN
        STREAMS-RABBIT-CONNECTOR-INIT
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-VALID? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-STATE@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        STREAMS-RABBIT-CONNECTOR-ST-ATTACHED = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-CLIENT@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        _RBT-CLI-CLIENT = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-SUBSCRIPTIONS@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        _RBT-SUB-OWNER = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-RECONNECT-COUNT@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT 0= _RBT-ASSERT
    RSUB-ENTRY-CONFIGURED _RBT-RCONN-ASSERT-ENTRY
    1 _RBT-RCONN-ASSERT-PENDING-POLL
    _RBT-STACK ;

: _RBT-RCONN-PHASE-DETACH  ( -- )
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-DETACH
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-VALID? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-STATE@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        STREAMS-RABBIT-CONNECTOR-ST-DETACHED = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-CLIENT@
        STREAMS-RABBIT-CONNECTOR-S-DISCONNECTED = _RBT-ASSERT
        0= _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-STATE@
        RSUB-S-OK = _RBT-ASSERT RSUB-ST-DETACHED = _RBT-ASSERT
    RSUB-ENTRY-NEEDS-REBIND _RBT-RCONN-ASSERT-ENTRY
    _RBT-CLI-CLIENT RABBIT-CLIENT-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-CONN-A RABBIT-CONNECTION-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    0 0 _RBT-RCONN STREAMS-RABBIT-CONNECTOR-POLL
        STREAMS-RABBIT-CONNECTOR-S-DISCONNECTED = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
        RSUB-ITEM-NONE = _RBT-ASSERT
    _RBT-RCONN-PEER-FINI
    _RBT-STACK ;

: _RBT-RCONN-PHASE-ATTACH  ( -- )
    _RBT-CLI-PHASE-INIT
    _RBT-CLI-CLIENT _RBT-RCONN STREAMS-RABBIT-CONNECTOR-ATTACH
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-VALID? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-STATE@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
        STREAMS-RABBIT-CONNECTOR-ST-ATTACHED = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-RECONNECT-COUNT@
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT 1 = _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-STATE@
        RSUB-S-OK = _RBT-ASSERT RSUB-ST-ATTACHED = _RBT-ASSERT
    RSUB-ENTRY-NEEDS-REBIND _RBT-RCONN-ASSERT-ENTRY
    2 _RBT-RCONN-ASSERT-PENDING-POLL
    _RBT-STACK ;

: _RBT-RCONN-PHASE-FINI  ( -- )
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-FINI
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-VALID? 0= _RBT-ASSERT
    _RBT-SUB-OWNER RABBIT-SUBSCRIPTIONS-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-ENTRIES RABBIT-SUBSCRIPTION-ENTRY-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-TARGET-ARENA 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SUB-EVENT-ARENA 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-CLIENT RABBIT-CLIENT-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-CONN-A RABBIT-CONNECTION-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-FINI
        STREAMS-RABBIT-CONNECTOR-S-INVALID = _RBT-ASSERT
    _RBT-RCONN-PEER-FINI
    _RBT-STACK ;
