\ Focused lifecycle contracts for the persistent typed Rabbit action owner.

PROVIDED rabbit-remote-action-test

CREATE _RBT-RRA-STORE STREAMS-RABBIT-REMOTE-ACTION-SIZE 7 + ALLOT
CREATE _RBT-RRA-TEMP-STORE STREAMS-RABBIT-REMOTE-ACTION-SIZE 7 + ALLOT
CREATE _RBT-RRA-TARGET 64 ALLOT
CREATE _RBT-RRA-BODY 128 ALLOT
CREATE _RBT-RRA-TXN 32 ALLOT
CREATE _RBT-RRA-IDEM 64 ALLOT
CREATE _RBT-RRA-RECEIPT 128 ALLOT
CREATE _RBT-RRA-ALIAS-BUILDER-STORE 0 RMSGB-BUILDER-BYTES 7 + ALLOT

: _RBT-RRA  ( -- owner ) _RBT-RRA-STORE 7 + -8 AND ;
: _RBT-RRA-TEMP  ( -- owner ) _RBT-RRA-TEMP-STORE 7 + -8 AND ;
: _RBT-RRA-ALIAS-BUILDER  ( -- builder )
    _RBT-RRA-ALIAS-BUILDER-STORE 7 + -8 AND ;

VARIABLE _RBT-RRA-ITEM
VARIABLE _RBT-RRA-SUBJECT
VARIABLE _RBT-RRA-GENERATION
VARIABLE _RBT-RRA-CS
VARIABLE _RBT-RRA-OWNED
VARIABLE _RBT-RRA-CHANGED
VARIABLE _RBT-RRA-STATUS
VARIABLE _RBT-RRA-CODE
VARIABLE _RBT-RRA-TXN-A
VARIABLE _RBT-RRA-TXN-U
VARIABLE _RBT-RRA-VIEW-A
VARIABLE _RBT-RRA-VIEW-U
VARIABLE _RBT-RRA-RAW-A
VARIABLE _RBT-RRA-RAW-U
VARIABLE _RBT-RRA-VALUE
VARIABLE _RBT-RRA-CONTEXT
VARIABLE _RBT-RRA-CLASSIFIER-MODE
VARIABLE _RBT-RRA-CLASSIFIER-CALLS
VARIABLE _RBT-RRA-FALLBACK-CALLS
VARIABLE _RBT-RRA-FALLBACK-MODE
VARIABLE _RBT-RRA-EXPECTED-DECISION
VARIABLE _RBT-RRA-INJECT-CALLBACK-CODE
VARIABLE _RBT-RRA-EXPECTED-CLASS
VARIABLE _RBT-RRA-EXPECTED-CODE
VARIABLE _RBT-RRA-EXPECTED-A
VARIABLE _RBT-RRA-EXPECTED-U
VARIABLE _RBT-RRA-ATTEMPT

: _RBT-RRA-CLASSIFIER
  ( code view-a view-u raw-a raw-u value|0 context -- class status )
    _RBT-RRA-CONTEXT ! _RBT-RRA-VALUE !
    _RBT-RRA-RAW-U ! _RBT-RRA-RAW-A !
    _RBT-RRA-VIEW-U ! _RBT-RRA-VIEW-A ! _RBT-RRA-CODE !
    1 _RBT-RRA-CLASSIFIER-CALLS +!
    _RBT-RRA-CONTEXT @ 0xA671 <> IF
        STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE 81 EXIT
    THEN
    _RBT-RRA-CODE @ DUP 200 = SWAP 412 = OR IF
        _RBT-RRA-VALUE @ 0= IF
            STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE 82 EXIT
        THEN
        _RBT-RRA-VIEW-A @ _RBT-RRA-VIEW-U @
            S" application/akashic-value+json" STR-STR= 0= IF
            STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE 83 EXIT
        THEN
        _RBT-RRA-RAW-U @ 0= IF
            STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE 84 EXIT
        THEN
        _RBT-RRA-VALUE @ CV-TYPE@ DUP CV-T-INT =
        SWAP CV-T-LIST = OR 0= IF
            STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE 85 EXIT
        THEN
    ELSE
        _RBT-RRA-VALUE @ IF
            STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE 86 EXIT
        THEN
        _RBT-RRA-VIEW-U @ _RBT-RRA-RAW-U @ OR IF
            STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE 87 EXIT
        THEN
    THEN
    _RBT-RRA-CLASSIFIER-MODE @ -1 = IF -811 THROW THEN
    _RBT-RRA-CLASSIFIER-MODE @ 2 = IF
        STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-ACCEPTED 0 0 EXIT
    THEN
    _RBT-RRA-CLASSIFIER-MODE @ ?DUP IF
        STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE SWAP EXIT
    THEN
    _RBT-RRA-CODE @ CASE
        200 OF STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-ACCEPTED 0 ENDOF
        412 OF STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NO-EFFECT 0 ENDOF
        403 OF STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-FORBIDDEN 0 ENDOF
        409 OF STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-CONFLICT 0 ENDOF
        429 OF STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-RETRYABLE 0 ENDOF
        503 OF STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-RETRYABLE 0 ENDOF
        STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE 88 ROT
    ENDCASE ;

: _RBT-RRA-FALLBACK
  ( frame kind lane seq expected disposition context -- decision )
    0xFA11 = _RBT-ASSERT
    2DROP 2DROP 2DROP
    1 _RBT-RRA-FALLBACK-CALLS +!
    _RBT-RRA-FALLBACK-MODE @ -1 = IF -812 THROW THEN
    _RBT-RRA-FALLBACK-MODE @ 2 = IF
        RCLIENT-DISPATCH-COMMIT 0 EXIT
    THEN
    RCLIENT-DISPATCH-COMMIT ;

: _RBT-RRA-INIT-OWNER  ( -- )
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-SIZE 0xA5 FILL
    _RBT-RRA-TARGET 64 0xA5 FILL
    _RBT-RRA-BODY 128 0xA5 FILL
    _RBT-RRA-TXN 32 0xA5 FILL
    _RBT-RRA-IDEM 64 0xA5 FILL
    _RBT-RRA-RECEIPT 128 0xA5 FILL
    _RBT-RCONN 1
        _RBT-RRA-TARGET 64 _RBT-RRA-BODY 128 _RBT-RRA-TXN 32
        _RBT-RRA-IDEM 64 _RBT-RRA-RECEIPT 128 _RBT-RRA
        STREAMS-RABBIT-REMOTE-ACTION-INIT
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    S" application/action+json"
    S" application/akashic-value+json"
    ['] _RBT-RRA-CLASSIFIER 0xA671
    ['] _RBT-RRA-FALLBACK 0xFA11 _RBT-RRA
        STREAMS-RABBIT-REMOTE-ACTION-PROFILE!
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    S" /fixture/action" S" [1,2,3]" S" action-idem-7" _RBT-RRA
        STREAMS-RABBIT-REMOTE-ACTION-PREPARE
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT ;

: _RBT-RRA-RESET-OWNER  ( -- )
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-FINI
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    _RBT-RRA-INIT-OWNER ;

: _RBT-RRA-EXPECT-STATE  ( expected -- )
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-STATE@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        = _RBT-ASSERT ;

: _RBT-RRA-EXPECT-EXACT-ACTION  ( -- )
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-ACTION$
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        S" application/action+json" STR-STR= _RBT-ASSERT
        S" [1,2,3]" STR-STR= _RBT-ASSERT
        S" /fixture/action" STR-STR= _RBT-ASSERT
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-IDEM$
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        S" action-idem-7" STR-STR= _RBT-ASSERT ;

: _RBT-RRA-POLL  ( -- )
    ['] STREAMS-RABBIT-REMOTE-ACTION-POLL-CALLBACK _RBT-RRA
        _RBT-RCONN STREAMS-RABBIT-CONNECTOR-POLL
        _RBT-RRA-CS ! _RBT-RRA-GENERATION !
        _RBT-RRA-SUBJECT ! _RBT-RRA-ITEM !
    _RBT-RRA-INJECT-CALLBACK-CODE @ IF
        _RBT-RRA SRRA.CALLBACK-SEEN @ IF
            _RBT-RRA-INJECT-CALLBACK-CODE @
                _RBT-RRA SRRA.CALLBACK-CODE !
            0 _RBT-RRA-INJECT-CALLBACK-CODE !
        THEN
    THEN
    _RBT-RRA-ITEM @ _RBT-RRA-SUBJECT @ _RBT-RRA-GENERATION @
        _RBT-RRA-CS @ _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-CONSUME
        _RBT-RRA-STATUS ! _RBT-RRA-CHANGED ! _RBT-RRA-OWNED ! ;

: _RBT-RRA-UNTIL-OWNED  ( -- flag )
    128 0 ?DO
        _RBT-CLI-CONN-B _RBT-CLI-CONNECTION-STEP
        _RBT-RRA-POLL
        _RBT-RRA-OWNED @ IF -1 UNLOOP EXIT THEN
    LOOP
    _RBT-RRA-OWNED @ ;

: _RBT-RRA-EXPECT-PUBLISH  ( txn-a txn-u -- )
    _RBT-RRA-TXN-U ! _RBT-RRA-TXN-A !
    _RBT-RCONN-UNTIL-SERVER-RX _RBT-ASSERT
    _RBT-CLI-SERVER-LOAN
    _RBT-CLI-KIND @ RMSG-KIND-PUBLISH = _RBT-ASSERT
    _RBT-CLI-LANE @ 1 = _RBT-ASSERT
    _RBT-CLI-FRAME @ RBF-ARGS$
        S" /fixture/action" STR-STR= _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-TXN$
        RMSG-S-OK = _RBT-ASSERT _RBT-ASSERT
        _RBT-RRA-TXN-A @ _RBT-RRA-TXN-U @ STR-STR= _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-IDEM$
        RMSG-S-OK = _RBT-ASSERT _RBT-ASSERT
        S" action-idem-7" STR-STR= _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-VIEW$
        RMSG-S-OK = _RBT-ASSERT _RBT-ASSERT
        S" application/action+json" STR-STR= _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-ACCEPT-VIEW$
        RMSG-S-OK = _RBT-ASSERT _RBT-ASSERT
        S" application/akashic-value+json" STR-STR= _RBT-ASSERT
    _RBT-CLI-FRAME @ RMSG-BODY$
        RMSG-S-OK = _RBT-ASSERT S" [1,2,3]" STR-STR= _RBT-ASSERT
    _RBT-CLI-SERVER-COMMIT ;

: _RBT-RRA-SEND  ( txn-a txn-u -- )
    2DUP _RBT-RRA-TXN-U ! _RBT-RRA-TXN-A !
    _RBT-CLI-RESET-BUILDER
    _RBT-MSGB-BUILDER _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-SEND
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-SENDING _RBT-RRA-EXPECT-STATE
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-RECEIPT@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        0= _RBT-ASSERT DROP DROP DROP DROP DROP DROP
    _RBT-RRA-TXN-A @ _RBT-RRA-TXN-U @ _RBT-RRA-EXPECT-PUBLISH ;

: _RBT-RRA-RETRY  ( txn-a txn-u -- status )
    _RBT-CLI-RESET-BUILDER
    _RBT-MSGB-BUILDER _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-RETRY ;

: _RBT-RRA-LABEL$  ( code -- address bytes )
    CASE
        200 OF S" RESULT" ENDOF
        412 OF S" PRECONDITION FAIL" ENDOF
        403 OF S" FORBIDDEN" ENDOF
        409 OF S" CONFLICT" ENDOF
        429 OF S" FLOW-LIMIT" ENDOF
        503 OF S" BUSY" ENDOF
        S" UNKNOWN" ROT
    ENDCASE ;

: _RBT-RRA-RESPOND
  ( code txn-a txn-u view-a view-u body-a body-u -- )
    _RBT-RRA-RAW-U ! _RBT-RRA-RAW-A !
    _RBT-RRA-VIEW-U ! _RBT-RRA-VIEW-A !
    _RBT-RRA-TXN-U ! _RBT-RRA-TXN-A ! _RBT-RRA-CODE !
    _RBT-CLI-RESET-BUILDER
    _RBT-RRA-CODE @ DUP _RBT-RRA-LABEL$ 1
        _RBT-RRA-TXN-A @ _RBT-RRA-TXN-U @ _RBT-MSGB-BUILDER
        RMSGB-BEGIN-RESPONSE RMSGB-S-OK = _RBT-ASSERT
    _RBT-RRA-VIEW-U @ IF
        _RBT-RRA-VIEW-A @ _RBT-RRA-VIEW-U @
            _RBT-MSGB-BUILDER RMSGB-VIEW! RMSGB-S-OK = _RBT-ASSERT
    THEN
    _RBT-RRA-RAW-U @ IF
        _RBT-RRA-RAW-A @ _RBT-RRA-RAW-U @
            _RBT-MSGB-BUILDER RMSGB-BODY! RMSGB-S-OK = _RBT-ASSERT
    THEN
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-ENQUEUE-B
    _RBT-CLI-RESET-BUILDER
    _RBT-RRA-UNTIL-OWNED _RBT-ASSERT ;

: _RBT-RRA-EXPECT-RECEIPT  ( class code raw-a raw-u attempt -- )
    _RBT-RRA-ATTEMPT ! _RBT-RRA-EXPECTED-U ! _RBT-RRA-EXPECTED-A !
    _RBT-RRA-EXPECTED-CODE ! _RBT-RRA-EXPECTED-CLASS !
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-RECEIPT@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        _RBT-ASSERT
        _RBT-RRA-ATTEMPT @ = _RBT-ASSERT
        _RBT-RRA-EXPECTED-U @ = _RBT-ASSERT
        _RBT-RRA-EXPECTED-A @ _RBT-RRA-EXPECTED-U @ STR-STR=
            _RBT-ASSERT
        _RBT-RRA-EXPECTED-CODE @ = _RBT-ASSERT
        _RBT-RRA-EXPECTED-CLASS @ = _RBT-ASSERT ;

: _RBT-RRA-EXPECT-NO-RECEIPT  ( -- )
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-RECEIPT@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        0= _RBT-ASSERT
        0= _RBT-ASSERT
        0= _RBT-ASSERT
        0= _RBT-ASSERT
        DROP
        0= _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE = _RBT-ASSERT ;

: _RBT-RRA-ROUTE-OTHER  ( fallback-mode expected-decision -- )
    _RBT-RRA-EXPECTED-DECISION ! _RBT-RRA-FALLBACK-MODE !
    _RBT-CLI-RESET-BUILDER
    200 S" RESULT" 2 S" OTHER" _RBT-MSGB-BUILDER
        RMSGB-BEGIN-RESPONSE RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-READY-FRAME@
        RMSG-KIND-RESPONSE 2 0 0 RABBIT-INBOUND-NONE _RBT-RRA
        STREAMS-RABBIT-REMOTE-ACTION-POLL-CALLBACK
        _RBT-RRA-EXPECTED-DECISION @ = _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER ;

: _RBT-RRA-PHASE-DEPENDENCIES  ( -- )
    _RBT-RRES-PHASE-DEPENDENCIES
    0 _RBT-RRA-CLASSIFIER-MODE !
    0 _RBT-RRA-CLASSIFIER-CALLS !
    0 _RBT-RRA-FALLBACK-CALLS !
    0 _RBT-RRA-FALLBACK-MODE !
    0 _RBT-RRA-INJECT-CALLBACK-CODE !
    _RBT-STACK ;

: _RBT-RRA-PHASE-INIT  ( -- )
    _RBT-RRA-TEMP STREAMS-RABBIT-REMOTE-ACTION-SIZE 0xA5 FILL
    _RBT-RCONN 0
        _RBT-RRA-TARGET 64 _RBT-RRA-BODY 128 _RBT-RRA-TXN 32
        _RBT-RRA-IDEM 64 _RBT-RRA-RECEIPT 128 _RBT-RRA-TEMP
        STREAMS-RABBIT-REMOTE-ACTION-INIT
        STREAMS-RABBIT-REMOTE-ACTION-S-INVALID = _RBT-ASSERT
    _RBT-RRA-TEMP C@ 0xA5 = _RBT-ASSERT
    _RBT-RCONN 1
        _RBT-RRA-TEMP STREAMS-RABBIT-REMOTE-ACTION-SIZE
        _RBT-RRA-BODY 128 _RBT-RRA-TXN 32 _RBT-RRA-IDEM 64
        _RBT-RRA-RECEIPT 128 _RBT-RRA-TEMP
        STREAMS-RABBIT-REMOTE-ACTION-INIT
        STREAMS-RABBIT-REMOTE-ACTION-S-ALIAS = _RBT-ASSERT
    _RBT-RRA-INIT-OWNER
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-VALID? _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-READY _RBT-RRA-EXPECT-STATE
    _RBT-RRA-EXPECT-EXACT-ACTION
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-SIZE _RBT-RRA
        STREAMS-RABBIT-REMOTE-ACTION-RETAINED-SPAN-OVERLAP? _RBT-ASSERT
    _RBT-RRA-TARGET 64 _RBT-RRA
        STREAMS-RABBIT-REMOTE-ACTION-RETAINED-SPAN-OVERLAP? _RBT-ASSERT
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-SIZE _RBT-RRA
        STREAMS-RABBIT-REMOTE-ACTION-RETAINED-SPAN-OVERLAP? _RBT-ASSERT
    0 0 _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-RETAINED-SPAN-OVERLAP?
        0= _RBT-ASSERT
    0 -1 _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-RETAINED-SPAN-OVERLAP?
        _RBT-ASSERT
    _RBT-STACK ;

: _RBT-RRA-PHASE-HANDSHAKE  ( -- )
    _RBT-RCONN-HANDSHAKE
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-VALID? _RBT-ASSERT
    _RBT-STACK ;

: _RBT-RRA-PHASE-ROUTING  ( -- )
    RSUB-ITEM-OTHER 0 0 STREAMS-RABBIT-CONNECTOR-S-OK _RBT-RRA
        STREAMS-RABBIT-REMOTE-ACTION-CONSUME
        STREAMS-RABBIT-REMOTE-ACTION-S-STATE = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
    0 RCLIENT-DISPATCH-COMMIT _RBT-RRA-ROUTE-OTHER
    _RBT-RRA-FALLBACK-CALLS @ 1 = _RBT-ASSERT
    _RBT-RRA-TARGET 64 0 _RBT-RRA-ALIAS-BUILDER RMSGB-INIT
        RMSGB-S-OK = _RBT-ASSERT
    S" ALIAS-TXN" _RBT-RRA-ALIAS-BUILDER _RBT-RRA
        STREAMS-RABBIT-REMOTE-ACTION-SEND
        STREAMS-RABBIT-REMOTE-ACTION-S-ALIAS = _RBT-ASSERT
    _RBT-RRA-ALIAS-BUILDER RMSGB-FINI RMSGB-S-OK = _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    S" ARENA-TXN" _RBT-MSGB-ARENA SWAP MOVE
    _RBT-MSGB-ARENA 9 _RBT-MSGB-BUILDER _RBT-RRA
        STREAMS-RABBIT-REMOTE-ACTION-SEND
        STREAMS-RABBIT-REMOTE-ACTION-S-ALIAS = _RBT-ASSERT
    _RBT-CLI-RESET-BUILDER
    STREAMS-RABBIT-REMOTE-ACTION-ST-READY _RBT-RRA-EXPECT-STATE
    _RBT-STACK ;

: _RBT-RRA-PHASE-ACCEPT-SEND  ( -- )
    S" ACT-ONE" _RBT-RRA-SEND
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-SEND-COUNT@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT 1 = _RBT-ASSERT
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-FINI
        STREAMS-RABBIT-REMOTE-ACTION-S-STATE = _RBT-ASSERT
    RSUB-ITEM-CLIENT-OP 0 0 STREAMS-RABBIT-CONNECTOR-S-OK _RBT-RRA
        STREAMS-RABBIT-REMOTE-ACTION-CONSUME
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-SENDING _RBT-RRA-EXPECT-STATE
    _RBT-STACK ;

: _RBT-RRA-PHASE-FALLBACK-FAILURES  ( -- )
    -1 RCLIENT-DISPATCH-DROP _RBT-RRA-ROUTE-OTHER
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-LAST@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        -812 = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-DETAIL-CALLBACK = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-S-CALLBACK = _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-SENDING _RBT-RRA-EXPECT-STATE
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-TXN$
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        S" ACT-ONE" STR-STR= _RBT-ASSERT
    2 RCLIENT-DISPATCH-DROP _RBT-RRA-ROUTE-OTHER
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-LAST@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-E-FALLBACK-STACK = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-DETAIL-CALLBACK = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-S-CALLBACK = _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-SENDING _RBT-RRA-EXPECT-STATE
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-VALID? _RBT-ASSERT
    0 _RBT-RRA-FALLBACK-MODE !
    _RBT-STACK ;

: _RBT-RRA-PHASE-ACCEPT-RESULT  ( -- )
    200 S" ACT-ONE" S" application/akashic-value+json" S" [7]"
        _RBT-RRA-RESPOND
    _RBT-RRA-STATUS @ STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    _RBT-RRA-CHANGED @ _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-TERMINAL _RBT-RRA-EXPECT-STATE
    STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-ACCEPTED
        200 S" [7]" 1 _RBT-RRA-EXPECT-RECEIPT
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-TXN$
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        S" ACT-ONE" STR-STR= _RBT-ASSERT
    _RBT-STACK ;

: _RBT-RRA-PHASE-RETRYABLE-SEND  ( -- )
    _RBT-RRA-RESET-OWNER
    S" ACT-RATE-1" _RBT-RRA-SEND
    _RBT-STACK ;

: _RBT-RRA-PHASE-RETRYABLE-RESULT  ( -- )
    429 S" ACT-RATE-1" 0 0 0 0 _RBT-RRA-RESPOND
    _RBT-RRA-STATUS @ STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-RETRYABLE _RBT-RRA-EXPECT-STATE
    STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-RETRYABLE
        429 0 0 1 _RBT-RRA-EXPECT-RECEIPT
    S" ACT-RATE-1" _RBT-RRA-RETRY
        STREAMS-RABBIT-REMOTE-ACTION-S-STATE = _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-RETRYABLE _RBT-RRA-EXPECT-STATE
    _RBT-RRA-EXPECT-EXACT-ACTION
    _RBT-STACK ;

: _RBT-RRA-PHASE-RETRYABLE-RETRY  ( -- )
    S" ACT-RATE-2" 2DUP _RBT-RRA-RETRY
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    _RBT-RRA-EXPECT-PUBLISH
    _RBT-STACK ;

: _RBT-RRA-PHASE-RETRYABLE-ACCEPT  ( -- )
    200 S" ACT-RATE-2" S" application/akashic-value+json" S" 9"
        _RBT-RRA-RESPOND
    STREAMS-RABBIT-REMOTE-ACTION-ST-TERMINAL _RBT-RRA-EXPECT-STATE
    STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-ACCEPTED
        200 S" 9" 2 _RBT-RRA-EXPECT-RECEIPT
    _RBT-STACK ;

: _RBT-RRA-PHASE-NO-EFFECT  ( -- )
    _RBT-RRA-RESET-OWNER
    S" ACT-OLD" _RBT-RRA-SEND
    412 S" ACT-OLD" S" application/akashic-value+json" S" 12"
        _RBT-RRA-RESPOND
    STREAMS-RABBIT-REMOTE-ACTION-ST-TERMINAL _RBT-RRA-EXPECT-STATE
    STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NO-EFFECT
        412 S" 12" 1 _RBT-RRA-EXPECT-RECEIPT
    _RBT-STACK ;

: _RBT-RRA-PHASE-CLASSIFIER-THROW  ( -- )
    _RBT-RRA-RESET-OWNER
    -1 _RBT-RRA-CLASSIFIER-MODE !
    S" ACT-CLASS-THROW" _RBT-RRA-SEND
    200 S" ACT-CLASS-THROW"
        S" application/akashic-value+json" S" [3]" _RBT-RRA-RESPOND
    _RBT-RRA-STATUS @ STREAMS-RABBIT-REMOTE-ACTION-S-CALLBACK =
        _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-FAILED _RBT-RRA-EXPECT-STATE
    _RBT-RRA-EXPECT-NO-RECEIPT
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-CALLBACK@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE = _RBT-ASSERT
        3 = _RBT-ASSERT
        200 = _RBT-ASSERT
        -811 = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-DETAIL-CLASSIFIER = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-S-CALLBACK = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-RRA-PHASE-CLASSIFIER-STACK  ( -- )
    2 _RBT-RRA-CLASSIFIER-MODE !
    _RBT-RRA-RESET-OWNER
    S" ACT-CLASS-STACK" _RBT-RRA-SEND
    200 S" ACT-CLASS-STACK"
        S" application/akashic-value+json" S" [4]" _RBT-RRA-RESPOND
    _RBT-RRA-STATUS @ STREAMS-RABBIT-REMOTE-ACTION-S-CALLBACK =
        _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-FAILED _RBT-RRA-EXPECT-STATE
    _RBT-RRA-EXPECT-NO-RECEIPT
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-CALLBACK@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE = _RBT-ASSERT
        3 = _RBT-ASSERT
        200 = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-E-CLASSIFIER-STACK = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-DETAIL-CLASSIFIER = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-S-CALLBACK = _RBT-ASSERT
    0 _RBT-RRA-CLASSIFIER-MODE !
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-VALID? _RBT-ASSERT
    _RBT-STACK ;

: _RBT-RRA-PHASE-STRICT-PROFILE  ( -- )
    _RBT-RRA-RESET-OWNER
    S" ACT-BAD" _RBT-RRA-SEND
    409 S" ACT-BAD" S" application/akashic-value+json" S" 4"
        _RBT-RRA-RESPOND
    _RBT-RRA-STATUS @ STREAMS-RABBIT-REMOTE-ACTION-S-RESPONSE =
        _RBT-ASSERT
    _RBT-RRA-CHANGED @ 0= _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-FAILED _RBT-RRA-EXPECT-STATE
    _RBT-RRA-EXPECT-NO-RECEIPT
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-CALLBACK@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-NONE = _RBT-ASSERT
        1 = _RBT-ASSERT
        409 = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-E-BODY = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-DETAIL-RESPONSE = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-S-RESPONSE = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-RRA-PHASE-RESULT-MISMATCH  ( -- )
    _RBT-RRA-RESET-OWNER
    S" ACT-MISMATCH" _RBT-RRA-SEND
    201 _RBT-RRA-INJECT-CALLBACK-CODE !
    200 S" ACT-MISMATCH" S" application/akashic-value+json" S" [5]"
        _RBT-RRA-RESPOND
    _RBT-RRA-STATUS @ STREAMS-RABBIT-REMOTE-ACTION-S-RESPONSE =
        _RBT-ASSERT
    _RBT-RRA-CHANGED @ 0= _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-FAILED _RBT-RRA-EXPECT-STATE
    _RBT-RRA-EXPECT-NO-RECEIPT
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-LAST@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-E-RESULT-MISMATCH = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-DETAIL-RESPONSE = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-S-RESPONSE = _RBT-ASSERT
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-CALLBACK@
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-ACCEPTED = _RBT-ASSERT
        3 = _RBT-ASSERT
        201 = _RBT-ASSERT
        0= _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-DETAIL-NONE = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-RRA-PHASE-DISCONNECT-SEND  ( -- )
    _RBT-RRA-RESET-OWNER
    S" ACT-LOST-1" _RBT-RRA-SEND
    _RBT-STACK ;

: _RBT-RRA-PHASE-DISCONNECT  ( -- )
    _RBT-RCONN STREAMS-RABBIT-CONNECTOR-DETACH
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-RECONCILE
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-RETRYABLE _RBT-RRA-EXPECT-STATE
    _RBT-RRA-EXPECT-EXACT-ACTION
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-TXN$
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
        S" ACT-LOST-1" STR-STR= _RBT-ASSERT
    _RBT-RCONN-PEER-FINI
    _RBT-STACK ;

: _RBT-RRA-PHASE-REATTACH  ( -- )
    _RBT-CLI-PHASE-INIT
    _RBT-CLI-CLIENT _RBT-RCONN STREAMS-RABBIT-CONNECTOR-ATTACH
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-RCONN-HANDSHAKE
    S" ACT-LOST-1" _RBT-RRA-RETRY
        STREAMS-RABBIT-REMOTE-ACTION-S-STATE = _RBT-ASSERT
    S" ACT-LOST-2" 2DUP _RBT-RRA-RETRY
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    _RBT-RRA-EXPECT-PUBLISH
    _RBT-STACK ;

: _RBT-RRA-PHASE-REATTACH-RESULT  ( -- )
    200 S" ACT-LOST-2" S" application/akashic-value+json" S" [10]"
        _RBT-RRA-RESPOND
    STREAMS-RABBIT-REMOTE-ACTION-ST-TERMINAL _RBT-RRA-EXPECT-STATE
    STREAMS-RABBIT-REMOTE-ACTION-RECEIPT-ACCEPTED
        200 S" [10]" 2 _RBT-RRA-EXPECT-RECEIPT
    _RBT-STACK ;

: _RBT-RRA-PHASE-ABANDON-FINI  ( -- )
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-ABANDON
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    STREAMS-RABBIT-REMOTE-ACTION-ST-ABANDONED _RBT-RRA-EXPECT-STATE
    _RBT-RRA-TARGET 64 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-RRA-BODY 128 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-RRA-TXN 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-RRA-IDEM 64 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-RRA-RECEIPT 128 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-FINI
        STREAMS-RABBIT-REMOTE-ACTION-S-OK = _RBT-ASSERT
    _RBT-RRA STREAMS-RABBIT-REMOTE-ACTION-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-RCONN-PHASE-FINI
    _RBT-STACK ;
