\ Two-client Streams composition over one mounted typed Rabbit resource.

PROVIDED rabbit-mounted-test

CREATE _RBT-MREAD-CONNECTOR-A-STORE
    STREAMS-RABBIT-CONNECTOR-SIZE 7 + ALLOT
CREATE _RBT-MREAD-CONNECTOR-B-STORE
    STREAMS-RABBIT-CONNECTOR-SIZE 7 + ALLOT
CREATE _RBT-MREAD-SUBSCRIPTIONS-A-STORE
    RABBIT-SUBSCRIPTIONS-SIZE 7 + ALLOT
CREATE _RBT-MREAD-SUBSCRIPTIONS-B-STORE
    RABBIT-SUBSCRIPTIONS-SIZE 7 + ALLOT
CREATE _RBT-MREAD-RESOURCE-A-STORE
    STREAMS-RABBIT-REMOTE-RESOURCE-SIZE 7 + ALLOT
CREATE _RBT-MREAD-RESOURCE-B-STORE
    STREAMS-RABBIT-REMOTE-RESOURCE-SIZE 7 + ALLOT
CREATE _RBT-MREAD-SELECTOR-A 32 ALLOT
CREATE _RBT-MREAD-SELECTOR-B 32 ALLOT
CREATE _RBT-MREAD-TXN-A 32 ALLOT
CREATE _RBT-MREAD-TXN-B 32 ALLOT
CREATE _RBT-MREAD-SCHEMA-STORE CS-SIZE 7 + ALLOT

: _RBT-MREAD-CONNECTOR-A  ( -- connector )
    _RBT-MREAD-CONNECTOR-A-STORE 7 + -8 AND ;

: _RBT-MREAD-CONNECTOR-B  ( -- connector )
    _RBT-MREAD-CONNECTOR-B-STORE 7 + -8 AND ;

: _RBT-MREAD-SUBSCRIPTIONS-A  ( -- subscriptions )
    _RBT-MREAD-SUBSCRIPTIONS-A-STORE 7 + -8 AND ;

: _RBT-MREAD-SUBSCRIPTIONS-B  ( -- subscriptions )
    _RBT-MREAD-SUBSCRIPTIONS-B-STORE 7 + -8 AND ;

: _RBT-MREAD-RESOURCE-A  ( -- resource )
    _RBT-MREAD-RESOURCE-A-STORE 7 + -8 AND ;

: _RBT-MREAD-RESOURCE-B  ( -- resource )
    _RBT-MREAD-RESOURCE-B-STORE 7 + -8 AND ;

: _RBT-MREAD-SCHEMA  ( -- schema )
    _RBT-MREAD-SCHEMA-STORE 7 + -8 AND ;

VARIABLE _RBT-MREAD-DONE-A
VARIABLE _RBT-MREAD-DONE-B
VARIABLE _RBT-MREAD-OWNED
VARIABLE _RBT-MREAD-CHANGED
VARIABLE _RBT-MREAD-STATUS
VARIABLE _RBT-MREAD-CONNECTOR-STATUS
VARIABLE _RBT-MREAD-EXPECT-REJECTION
VARIABLE _RBT-MREAD-POLL-RESOURCE
VARIABLE _RBT-MREAD-POLL-CONNECTOR
VARIABLE _RBT-MREAD-POLL-DONE
VARIABLE _RBT-MREAD-TXN-SOURCE-A
VARIABLE _RBT-MREAD-TXN-SOURCE-U
VARIABLE _RBT-MREAD-CACHE-A
VARIABLE _RBT-MREAD-CACHE-B
VARIABLE _RBT-MREAD-HOST-FINI-DONE
VARIABLE _RBT-MREAD-SUBSCRIPTIONS-CLIENT
VARIABLE _RBT-MREAD-SUBSCRIPTIONS-OWNER

: _RBT-MREAD-ZERO-SUBSCRIPTIONS  ( client subscriptions -- )
    _RBT-MREAD-SUBSCRIPTIONS-OWNER !
    _RBT-MREAD-SUBSCRIPTIONS-CLIENT !
    0 0 0 0 0 0 _RBT-MREAD-SUBSCRIPTIONS-CLIENT @
        _RBT-MREAD-SUBSCRIPTIONS-OWNER @
        RABBIT-SUBSCRIPTIONS-INIT RSUB-S-OK = _RBT-ASSERT ;

: _RBT-MREAD-INIT-OWNERS  ( -- )
    _RBT-MREAD-CONNECTOR-A STREAMS-RABBIT-CONNECTOR-SIZE 0xA5 FILL
    _RBT-MREAD-CONNECTOR-B STREAMS-RABBIT-CONNECTOR-SIZE 0xA5 FILL
    _RBT-MREAD-SUBSCRIPTIONS-A RABBIT-SUBSCRIPTIONS-SIZE 0xA5 FILL
    _RBT-MREAD-SUBSCRIPTIONS-B RABBIT-SUBSCRIPTIONS-SIZE 0xA5 FILL
    _RBT-MREAD-RESOURCE-A STREAMS-RABBIT-REMOTE-RESOURCE-SIZE 0xA5 FILL
    _RBT-MREAD-RESOURCE-B STREAMS-RABBIT-REMOTE-RESOURCE-SIZE 0xA5 FILL
    _RBT-MREAD-SELECTOR-A 32 0xA5 FILL
    _RBT-MREAD-SELECTOR-B 32 0xA5 FILL
    _RBT-MREAD-TXN-A 32 0xA5 FILL
    _RBT-MREAD-TXN-B 32 0xA5 FILL

    _RBT-CLI-CLIENT _RBT-MREAD-SUBSCRIPTIONS-A
        _RBT-MREAD-ZERO-SUBSCRIPTIONS
    _RBT-CAP-B-CLIENT _RBT-MREAD-SUBSCRIPTIONS-B
        _RBT-MREAD-ZERO-SUBSCRIPTIONS
    _RBT-MREAD-SUBSCRIPTIONS-A _RBT-CLI-CLIENT
        _RBT-MREAD-CONNECTOR-A STREAMS-RABBIT-CONNECTOR-INIT
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-MREAD-SUBSCRIPTIONS-B _RBT-CAP-B-CLIENT
        _RBT-MREAD-CONNECTOR-B STREAMS-RABBIT-CONNECTOR-INIT
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT

    _RBT-MREAD-SCHEMA CS-INIT
    CV-T-INT _RBT-MREAD-SCHEMA CS-ALLOW!
    _RBT-MREAD-CONNECTOR-A S" /fixture" _RBT-MREAD-SELECTOR-A 32
        _RBT-MREAD-TXN-A 32 _RBT-MREAD-SCHEMA _RBT-MREAD-RESOURCE-A
        STREAMS-RABBIT-REMOTE-RESOURCE-INIT
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
    _RBT-MREAD-CONNECTOR-B S" /fixture" _RBT-MREAD-SELECTOR-B 32
        _RBT-MREAD-TXN-B 32 _RBT-MREAD-SCHEMA _RBT-MREAD-RESOURCE-B
        STREAMS-RABBIT-REMOTE-RESOURCE-INIT
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT ;

: _RBT-MREAD-ASSERT-GEOMETRY  ( -- )
    _RBT-CLI-CONN-A _RBT-CONN-A
        RABBIT-CONNECTION-OWNED-GRAPHS-DISJOINT? _RBT-ASSERT
    _RBT-MREAD-CONNECTOR-A STREAMS-RABBIT-CONNECTOR-SIZE
        _RBT-MREAD-CONNECTOR-B
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-MREAD-CONNECTOR-B STREAMS-RABBIT-CONNECTOR-SIZE
        _RBT-MREAD-CONNECTOR-A
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-MREAD-RESOURCE-A STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        _RBT-MREAD-RESOURCE-B STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        MSPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-MREAD-RESOURCE-A STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        _RBT-MREAD-CONNECTOR-B
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-MREAD-RESOURCE-B STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        _RBT-MREAD-CONNECTOR-A
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-CAP-B-CLIENT RABBIT-CLIENT-SIZE _RBT-MREAD-CONNECTOR-A
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-CAP-B-OPS RABBIT-CLIENT-OP-SIZE _RBT-MREAD-CONNECTOR-A
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-CAP-B-TXN-ARENA 16 _RBT-MREAD-CONNECTOR-A
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-CAP-B-RESULT-ARENA 32 _RBT-MREAD-CONNECTOR-A
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-CAP-B-CLIENT-BURROW 64 _RBT-MREAD-CONNECTOR-A
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-CLI-CLIENT RABBIT-CLIENT-SIZE _RBT-MREAD-CONNECTOR-B
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-CLI-OPS 4 RABBIT-CLIENT-OP-SIZE * _RBT-MREAD-CONNECTOR-B
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-CLI-TXN-ARENA 4 16 * _RBT-MREAD-CONNECTOR-B
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-CLI-RESULT-ARENA 4 32 * _RBT-MREAD-CONNECTOR-B
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-CLI-BURROW-ARENA 64 _RBT-MREAD-CONNECTOR-B
        STREAMS-RABBIT-CONNECTOR-OWNED-SPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-MREAD-SELECTOR-A 32 _RBT-MREAD-SELECTOR-B 32
        MSPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-MREAD-TXN-A 32 _RBT-MREAD-TXN-B 32
        MSPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-MREAD-SELECTOR-A 32 _RBT-MREAD-TXN-B 32
        MSPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-MREAD-TXN-A 32 _RBT-MREAD-SELECTOR-B 32
        MSPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-MREAD-RESOURCE-A STREAMS-RABBIT-REMOTE-RESOURCE-VALID? _RBT-ASSERT
    _RBT-MREAD-RESOURCE-B STREAMS-RABBIT-REMOTE-RESOURCE-VALID? _RBT-ASSERT ;

: _RBT-MREAD-PHASE-INIT  ( -- )
    _RBT-MREAD-INIT-OWNERS
    _RBT-MREAD-ASSERT-GEOMETRY
    _RBT-MREAD-RESOURCE-A STREAMS-RABBIT-REMOTE-RESOURCE-CACHE@
        STREAMS-RABBIT-REMOTE-RESOURCE-S-EMPTY = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
    _RBT-MREAD-RESOURCE-B STREAMS-RABBIT-REMOTE-RESOURCE-CACHE@
        STREAMS-RABBIT-REMOTE-RESOURCE-S-EMPTY = _RBT-ASSERT
        0= _RBT-ASSERT 0= _RBT-ASSERT
    0 _RBT-MREAD-DONE-A ! 0 _RBT-MREAD-DONE-B !
    0 _RBT-MREAD-EXPECT-REJECTION !
    _RBT-FM-AUTH-ALLOW _RBT-FM-CASE-BEGIN
    _RBT-STACK ;

: _RBT-MREAD-BUILD-FETCH  ( txn-a txn-u -- )
    _RBT-MREAD-TXN-SOURCE-U ! _RBT-MREAD-TXN-SOURCE-A !
    _RBT-MSGB-BUILDER RMSGB-RESET RMSGB-S-OK = _RBT-ASSERT
    RMSG-KIND-FETCH S" /fixture" 1
        _RBT-MREAD-TXN-SOURCE-A @ _RBT-MREAD-TXN-SOURCE-U @
        _RBT-MSGB-BUILDER RMSGB-BEGIN-REQUEST RMSGB-S-OK = _RBT-ASSERT
    S" application/akashic-value+json" _RBT-MSGB-BUILDER RMSGB-VIEW!
        RMSGB-S-OK = _RBT-ASSERT
    S" application/akashic-value+json"
        _RBT-MSGB-BUILDER RMSGB-ACCEPT-VIEW! RMSGB-S-OK = _RBT-ASSERT
    S" 7" _RBT-MSGB-BUILDER RMSGB-BODY! RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-SEAL RMSGB-S-OK = _RBT-ASSERT ;

: _RBT-MREAD-PHASE-FETCH-START  ( -- )
    S" MREAD-A" _RBT-MREAD-BUILD-FETCH
    _RBT-MSGB-BUILDER _RBT-MREAD-RESOURCE-A
        STREAMS-RABBIT-REMOTE-RESOURCE-FETCH
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
    S" MREAD-B" _RBT-MREAD-BUILD-FETCH
    _RBT-MSGB-BUILDER _RBT-MREAD-RESOURCE-B
        STREAMS-RABBIT-REMOTE-RESOURCE-FETCH
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-RESET RMSGB-S-OK = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-MREAD-POLL  ( resource connector done-variable -- )
    _RBT-MREAD-POLL-DONE ! _RBT-MREAD-POLL-CONNECTOR !
    _RBT-MREAD-POLL-RESOURCE !
    _RBT-MREAD-POLL-DONE @ @ IF EXIT THEN
    ['] STREAMS-RABBIT-REMOTE-RESOURCE-POLL-CALLBACK
        _RBT-MREAD-POLL-RESOURCE @ _RBT-MREAD-POLL-CONNECTOR @
        STREAMS-RABBIT-CONNECTOR-POLL
    DUP _RBT-MREAD-CONNECTOR-STATUS !
    DUP STREAMS-RABBIT-CONNECTOR-S-OK =
        OVER STREAMS-RABBIT-CONNECTOR-S-PENDING = OR _RBT-ASSERT
    _RBT-MREAD-POLL-RESOURCE @ STREAMS-RABBIT-REMOTE-RESOURCE-CONSUME
        _RBT-MREAD-STATUS ! _RBT-MREAD-CHANGED ! _RBT-MREAD-OWNED !
    _RBT-MREAD-OWNED @ IF
        _RBT-MREAD-EXPECT-REJECTION @ IF
            _RBT-MREAD-STATUS @ STREAMS-RABBIT-REMOTE-RESOURCE-S-RESPONSE =
                _RBT-ASSERT
            _RBT-MREAD-CHANGED @ 0= _RBT-ASSERT
        ELSE
            _RBT-MREAD-STATUS @ STREAMS-RABBIT-REMOTE-RESOURCE-S-OK =
                _RBT-ASSERT
            _RBT-MREAD-CHANGED @ _RBT-ASSERT
        THEN
        -1 _RBT-MREAD-POLL-DONE @ !
    ELSE
        _RBT-MREAD-STATUS @ STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
        _RBT-MREAD-CHANGED @ 0= _RBT-ASSERT
    THEN ;

: _RBT-MREAD-STEP  ( -- )
    _RBT-BUR-SERVICE
    _RBT-BUR-SERVICE-STATUS @ DUP STREAMS-RABBIT-BURROW-S-OK =
        SWAP STREAMS-RABBIT-BURROW-S-PENDING = OR
    _RBT-MREAD-EXPECT-REJECTION @ IF
        _RBT-BUR-SERVICE-STATUS @ STREAMS-RABBIT-BURROW-S-SERVER = OR
    THEN _RBT-ASSERT
    _RBT-MREAD-RESOURCE-A _RBT-MREAD-CONNECTOR-A _RBT-MREAD-DONE-A
        _RBT-MREAD-POLL
    _RBT-MREAD-RESOURCE-B _RBT-MREAD-CONNECTOR-B _RBT-MREAD-DONE-B
        _RBT-MREAD-POLL
    _RBT-STACK ;

: _RBT-MREAD-PHASE-STEP-1  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-2  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-3  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-4  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-5  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-6  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-7  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-8  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-9  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-10  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-11  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-12  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-13  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-14  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-15  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-STEP-16  ( -- ) _RBT-MREAD-STEP ;

: _RBT-MREAD-CACHE-A@  ( -- )
    _RBT-MREAD-RESOURCE-A STREAMS-RABBIT-REMOTE-RESOURCE-CACHE@
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
        1 = _RBT-ASSERT DUP _RBT-MREAD-CACHE-A !
    DUP CV-TYPE@ CV-T-INT = _RBT-ASSERT
    CV-DATA@ 8 = _RBT-ASSERT ;

: _RBT-MREAD-CACHE-B@  ( -- )
    _RBT-MREAD-RESOURCE-B STREAMS-RABBIT-REMOTE-RESOURCE-CACHE@
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
        1 = _RBT-ASSERT DUP _RBT-MREAD-CACHE-B !
    DUP CV-TYPE@ CV-T-INT = _RBT-ASSERT
    CV-DATA@ 8 = _RBT-ASSERT ;

: _RBT-MREAD-PHASE-RESULTS  ( -- )
    _RBT-MREAD-DONE-A @ _RBT-ASSERT
    _RBT-MREAD-DONE-B @ _RBT-ASSERT
    _RBT-FM-AUTH-CALLS @ 2 = _RBT-ASSERT
    _RBT-FM-AUTH-CALLS-A @ 1 = _RBT-ASSERT
    _RBT-FM-AUTH-CALLS-B @ 1 = _RBT-ASSERT
    _RBT-FM-HANDLER-CALLS @ 2 = _RBT-ASSERT
    _RBT-MREAD-CACHE-A@
    _RBT-MREAD-CACHE-B@
    _RBT-MREAD-CACHE-A @ _RBT-MREAD-CACHE-B @ <> _RBT-ASSERT
    _RBT-MREAD-CACHE-A @ CV-SIZE _RBT-MREAD-CACHE-B @ CV-SIZE
        MSPAN-OVERLAP? 0= _RBT-ASSERT
    _RBT-MREAD-RESOURCE-A STREAMS-RABBIT-REMOTE-RESOURCE-RESPONSE@
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
        1 = _RBT-ASSERT 200 = _RBT-ASSERT
    _RBT-MREAD-RESOURCE-B STREAMS-RABBIT-REMOTE-RESOURCE-RESPONSE@
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
        1 = _RBT-ASSERT 200 = _RBT-ASSERT
    _RBT-MREAD-CONNECTOR-A STREAMS-RABBIT-CONNECTOR-VALID? _RBT-ASSERT
    _RBT-MREAD-CONNECTOR-B STREAMS-RABBIT-CONNECTOR-VALID? _RBT-ASSERT
    _RBT-BUR-HOST STREAMS-RABBIT-BURROW-VALID? _RBT-ASSERT
    _RBT-STACK ;

: _RBT-MREAD-PHASE-REFUSAL-START  ( -- )
    0 _RBT-MREAD-DONE-A !
    -1 _RBT-MREAD-EXPECT-REJECTION !
    _RBT-FM-AUTH-DENY _RBT-FM-CASE-BEGIN
    S" MREAD-A-DENY" _RBT-MREAD-BUILD-FETCH
    _RBT-MSGB-BUILDER _RBT-MREAD-RESOURCE-A
        STREAMS-RABBIT-REMOTE-RESOURCE-FETCH
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER RMSGB-RESET RMSGB-S-OK = _RBT-ASSERT
    _RBT-STACK ;

: _RBT-MREAD-PHASE-REFUSAL-STEP-1  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-REFUSAL-STEP-2  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-REFUSAL-STEP-3  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-REFUSAL-STEP-4  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-REFUSAL-STEP-5  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-REFUSAL-STEP-6  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-REFUSAL-STEP-7  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-REFUSAL-STEP-8  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-REFUSAL-STEP-9  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-REFUSAL-STEP-10  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-REFUSAL-STEP-11  ( -- ) _RBT-MREAD-STEP ;
: _RBT-MREAD-PHASE-REFUSAL-STEP-12  ( -- ) _RBT-MREAD-STEP ;

: _RBT-MREAD-PHASE-REFUSAL-RESULTS  ( -- )
    _RBT-MREAD-DONE-A @ _RBT-ASSERT
    _RBT-MREAD-DONE-B @ _RBT-ASSERT
    _RBT-FM-AUTH-CALLS @ 1 = _RBT-ASSERT
    _RBT-FM-AUTH-CALLS-A @ 1 = _RBT-ASSERT
    _RBT-FM-AUTH-CALLS-B @ 0= _RBT-ASSERT
    _RBT-FM-HANDLER-CALLS @ 0= _RBT-ASSERT
    _RBT-MREAD-RESOURCE-A STREAMS-RABBIT-REMOTE-RESOURCE-LAST@
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
        403 = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-RESOURCE-DETAIL-RESPONSE = _RBT-ASSERT
        STREAMS-RABBIT-REMOTE-RESOURCE-S-RESPONSE = _RBT-ASSERT
    _RBT-MREAD-RESOURCE-A STREAMS-RABBIT-REMOTE-RESOURCE-RESPONSE@
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
        0= _RBT-ASSERT 403 = _RBT-ASSERT
    _RBT-MREAD-CACHE-A@
    _RBT-MREAD-CACHE-B@
    _RBT-MREAD-CACHE-A @ _RBT-MREAD-CACHE-B @ <> _RBT-ASSERT
    0 _RBT-MREAD-EXPECT-REJECTION !
    _RBT-STACK ;

: _RBT-MREAD-PHASE-REMOTE-FINI  ( -- )
    _RBT-MREAD-RESOURCE-A STREAMS-RABBIT-REMOTE-RESOURCE-FINI
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
    _RBT-MREAD-RESOURCE-B STREAMS-RABBIT-REMOTE-RESOURCE-FINI
        STREAMS-RABBIT-REMOTE-RESOURCE-S-OK = _RBT-ASSERT
    _RBT-MREAD-RESOURCE-A STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-MREAD-RESOURCE-B STREAMS-RABBIT-REMOTE-RESOURCE-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-MREAD-SELECTOR-A 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-MREAD-SELECTOR-B 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-MREAD-TXN-A 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-MREAD-TXN-B 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-STACK ;

: _RBT-MREAD-PHASE-CONNECTOR-FINI  ( -- )
    _RBT-MREAD-CONNECTOR-A STREAMS-RABBIT-CONNECTOR-FINI
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-MREAD-CONNECTOR-B STREAMS-RABBIT-CONNECTOR-FINI
        STREAMS-RABBIT-CONNECTOR-S-OK = _RBT-ASSERT
    _RBT-MREAD-CONNECTOR-A STREAMS-RABBIT-CONNECTOR-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-MREAD-CONNECTOR-B STREAMS-RABBIT-CONNECTOR-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-MREAD-SUBSCRIPTIONS-A RABBIT-SUBSCRIPTIONS-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-MREAD-SUBSCRIPTIONS-B RABBIT-SUBSCRIPTIONS-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-CLIENT RABBIT-CLIENT-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-CLIENT RABBIT-CLIENT-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-OPS 4 RABBIT-CLIENT-OP-SIZE * 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-OPS RABBIT-CLIENT-OP-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-TXN-ARENA 4 16 * 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-TXN-ARENA 16 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-RESULT-ARENA 4 32 * 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-RESULT-ARENA 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-BURROW-ARENA 64 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-CLIENT-BURROW 64 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-CONN-A RABBIT-CONNECTION-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CONN-A RABBIT-CONNECTION-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-STACK ;

: _RBT-MREAD-PHASE-HOST-CANCEL  ( -- )
    _RBT-BUR-HOST STREAMS-RABBIT-BURROW-CANCEL
        DUP STREAMS-RABBIT-BURROW-S-OK =
        SWAP STREAMS-RABBIT-BURROW-S-PENDING = OR _RBT-ASSERT
    0 _RBT-MREAD-HOST-FINI-DONE !
    _RBT-STACK ;

: _RBT-MREAD-HOST-FINI-STEP  ( -- )
    _RBT-MREAD-HOST-FINI-DONE @ IF _RBT-STACK EXIT THEN
    _RBT-BUR-HOST STREAMS-RABBIT-BURROW-FINI DUP
    STREAMS-RABBIT-BURROW-S-OK = IF
        DROP -1 _RBT-MREAD-HOST-FINI-DONE !
    ELSE
        STREAMS-RABBIT-BURROW-S-PENDING = _RBT-ASSERT
    THEN
    _RBT-STACK ;

: _RBT-MREAD-PHASE-HOST-FINI-1  ( -- ) _RBT-MREAD-HOST-FINI-STEP ;
: _RBT-MREAD-PHASE-HOST-FINI-2  ( -- ) _RBT-MREAD-HOST-FINI-STEP ;
: _RBT-MREAD-PHASE-HOST-FINI-3  ( -- ) _RBT-MREAD-HOST-FINI-STEP ;
: _RBT-MREAD-PHASE-HOST-FINI-4  ( -- ) _RBT-MREAD-HOST-FINI-STEP ;

: _RBT-MREAD-PHASE-FINI  ( -- )
    _RBT-MREAD-HOST-FINI-DONE @ _RBT-ASSERT
    _RBT-BUR-HOST STREAMS-RABBIT-BURROW-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-BUR-ROWS 2 STREAMS-RABBIT-BURROW-PEER-SIZE *
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-BUR-ZERO STREAMS-RABBIT-BURROW-FINI
        STREAMS-RABBIT-BURROW-S-OK = _RBT-ASSERT
    _RBT-BUR-ZERO STREAMS-RABBIT-BURROW-SIZE 0 _RBT-FILLED? _RBT-ASSERT

    _RBT-SSRV-OWNER RABBIT-SERVER-SUBSCRIPTIONS-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-OWNER RABBIT-SERVER-SUBSCRIPTIONS-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SSRV-ENTRY RABBIT-SERVER-SUBSCRIPTION-ENTRY-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-SERVER-ENTRY RABBIT-SERVER-SUBSCRIPTION-ENTRY-SIZE
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SSRV-TARGET-ARENA 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-SERVER-TARGET 32 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SRV-SERVER RABBIT-SERVER-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-SERVER RABBIT-SERVER-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SRV-BUILDER 8 RMSGB-BUILDER-BYTES 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-BUILDER 8 RMSGB-BUILDER-BYTES
        0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SRV-BUILDER-ARENA 512 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-BUILDER-ARENA 512 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-SRV-BURROW 64 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-B-SERVER-BURROW 64 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CLI-CONN-B RABBIT-CONNECTION-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CONN-B RABBIT-CONNECTION-SIZE 0 _RBT-FILLED? _RBT-ASSERT

    _RBT-CLI-PHASE-TEARDOWN-QUEUES
    _RBT-CAP-B-QUEUES-TRANSPORT-FINI
    _RBT-CLI-PHASE-TEARDOWN-TRANSPORT
    _RBT-CAP-ROUTER RROUTER-FINI RROUTER-S-OK = _RBT-ASSERT
    _RBT-CAP-ROUTER RROUTER-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-ROUTES 4 RROUTER-ENTRY-SIZE * 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-CAP-ROUTE-ARENA 128 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-FM-PHASE-FINI
    _RBT-BUR-FACET-A CFACET-SIZE 0 FILL
    _RBT-BUR-FACET-B CFACET-SIZE 0 FILL
    _RBT-BUR-FACET-A CFACET-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-BUR-FACET-B CFACET-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    0 _RBT-CAP-APP-TOKEN ! 0 _RBT-CAP-SUB-TOKEN !
    _RBT-MREAD-SCHEMA CS-SIZE 0 FILL
    _RBT-MSGB-BUILDER RMSGB-FINI RMSGB-S-OK = _RBT-ASSERT
    _RBT-MSGB-BUILDER 12 RMSGB-BUILDER-BYTES 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-MSGB-ARENA 512 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-MREAD-SCHEMA CS-SIZE 0 _RBT-FILLED? _RBT-ASSERT
    _RBT-STACK ;
