\ Focused executable contracts for the headless Stage 3 Desk component.

PROVIDED sbox-stage3-desk-component

VARIABLE _S3D-FAILS
VARIABLE _S3D-CHECKS
VARIABLE _S3D-DEPTH
VARIABLE _S3D-PARENT
VARIABLE _S3D-HEAP-BEFORE
VARIABLE _S3D-CANDIDATE-U
VARIABLE _S3D-PLAN-A-U
VARIABLE _S3D-GENERATION-A
\ @profile compose begin
VARIABLE _S3D-GENERATION-B
\ @profile compose end
\ @profile compose begin
VARIABLE _S3D-CHILD-A
VARIABLE _S3D-CHILD-B
\ @profile compose end

136 CONSTANT _S3D-CANDIDATE-CAP
SBOX-PLAN-DESCRIPTOR-SIZE _S3D-CANDIDATE-CAP +
    CONSTANT _S3D-PLAN-CAP

: _S3D-ALIGN8  ( address -- aligned-address ) 7 + -8 AND ;

CREATE _S3D-PROFILE-RAW SBOX-PROFILE-SIZE 7 + ALLOT
_S3D-PROFILE-RAW _S3D-ALIGN8 CONSTANT _S3D-PROFILE
CREATE _S3D-CANDIDATE-RAW _S3D-CANDIDATE-CAP 7 + ALLOT
_S3D-CANDIDATE-RAW _S3D-ALIGN8 CONSTANT _S3D-CANDIDATE
CREATE _S3D-PLAN-A-RAW _S3D-PLAN-CAP 7 + ALLOT
_S3D-PLAN-A-RAW _S3D-ALIGN8 CONSTANT _S3D-PLAN-A
CREATE _S3D-LAYOUT-RAW SBOX-CANDIDATE-LAYOUT-SIZE 7 + ALLOT
_S3D-LAYOUT-RAW _S3D-ALIGN8 CONSTANT _S3D-LAYOUT
CREATE _S3D-VERIFIER-WORK-RAW
    SBOX-VERIFIER-WORKSPACE-SIZE 7 + ALLOT
_S3D-VERIFIER-WORK-RAW _S3D-ALIGN8 CONSTANT _S3D-VERIFIER-WORK

1 SBOX-MODULE-OWNER-MEASURE DROP CONSTANT _S3D-OWNER-U
CREATE _S3D-OWNER-RAW _S3D-OWNER-U 7 + ALLOT
_S3D-OWNER-RAW _S3D-ALIGN8 CONSTANT _S3D-OWNER
CREATE _S3D-RID-A RID-SIZE ALLOT

CREATE _S3D-LIMITS-RAW SBOX-VALUE-LIMITS-SIZE 7 + ALLOT
_S3D-LIMITS-RAW _S3D-ALIGN8 CONSTANT _S3D-LIMITS
CREATE _S3D-INPUT-A-RAW 31 ALLOT
_S3D-INPUT-A-RAW _S3D-ALIGN8 CONSTANT _S3D-INPUT-A
\ @profile compose begin
CREATE _S3D-INPUT-B-RAW 31 ALLOT
_S3D-INPUT-B-RAW _S3D-ALIGN8 CONSTANT _S3D-INPUT-B
\ @profile compose end
\ @profile compose begin
CREATE _S3D-EXPECTED-A-RAW 31 ALLOT
_S3D-EXPECTED-A-RAW _S3D-ALIGN8 CONSTANT _S3D-EXPECTED-A
CREATE _S3D-EXPECTED-B-RAW 31 ALLOT
_S3D-EXPECTED-B-RAW _S3D-ALIGN8 CONSTANT _S3D-EXPECTED-B
\ @profile compose end

CREATE _S3D-COMPONENT-A-RAW DESK-SBOX-COMPONENT-SIZE 7 + ALLOT
_S3D-COMPONENT-A-RAW _S3D-ALIGN8 CONSTANT _S3D-COMPONENT-A
\ @profile compose begin
CREATE _S3D-COMPONENT-B-RAW DESK-SBOX-COMPONENT-SIZE 7 + ALLOT
_S3D-COMPONENT-B-RAW _S3D-ALIGN8 CONSTANT _S3D-COMPONENT-B
\ @profile compose end
\ @profile compose begin
CREATE _S3D-RESULT-A-RAW DESK-SBOX-RESULT-SIZE 7 + ALLOT
_S3D-RESULT-A-RAW _S3D-ALIGN8 CONSTANT _S3D-RESULT-A
CREATE _S3D-RESULT-B-RAW DESK-SBOX-RESULT-SIZE 7 + ALLOT
_S3D-RESULT-B-RAW _S3D-ALIGN8 CONSTANT _S3D-RESULT-B
\ @profile compose end
\ @profile cancel,close begin
CREATE _S3D-RESULT-C-RAW DESK-SBOX-RESULT-SIZE 7 + ALLOT
_S3D-RESULT-C-RAW _S3D-ALIGN8 CONSTANT _S3D-RESULT-C
\ @profile cancel,close end

: _S3D-ASSERT  ( flag -- )
    1 _S3D-CHECKS +!
    0= IF
        1 _S3D-FAILS +!
        ." SBOX STAGE3 DESK ASSERT " _S3D-CHECKS @ . CR TX-FLUSH
    THEN ;

: _S3D-STACK  ( -- )
    DEPTH DUP _S3D-DEPTH @ <> IF
        ." SBOX STAGE3 DESK STACK "
        _S3D-DEPTH @ . ." -> " DUP . CR .S CR TX-FLUSH
    THEN
    _S3D-DEPTH @ = _S3D-ASSERT ;

: _S3D-INSTRUCTION!  ( opcode index -- )
    SBOX-CANDIDATE-INSTRUCTION-SIZE *
    _S3D-CANDIDATE
    _S3D-LAYOUT SBOX-CANDIDATE-LAYOUT-INSTRUCTIONS@ + +
    SBOX-CANDIDATE-U16-LE! ;

: _S3D-BUILD-ECHO-CANDIDATE  ( -- )
    1 0 1 4 0 2 _S3D-LAYOUT SBOX-CANDIDATE-MEASURE
        SBOX-CANDIDATE-S-OK = _S3D-ASSERT
    _S3D-LAYOUT SBOX-CANDIDATE-LAYOUT-TOTAL@
        DUP _S3D-CANDIDATE-U !
        _S3D-CANDIDATE-CAP = _S3D-ASSERT
    _S3D-PROFILE SBOX-PROFILE-TAG@ DROP
    64 _S3D-LAYOUT _S3D-CANDIDATE SBOX-CANDIDATE-HEADER!
        SBOX-CANDIDATE-S-OK = _S3D-ASSERT

    _S3D-CANDIDATE
    _S3D-LAYOUT SBOX-CANDIDATE-LAYOUT-FUNCTIONS@ + >R
    2 R@ SBOX-CANDIDATE-FUNCTION-INSTRUCTION-N-OFFSET +
        SBOX-CANDIDATE-U32-LE!
    1 R@ SBOX-CANDIDATE-FUNCTION-PARAMS-OFFSET +
        SBOX-CANDIDATE-U16-LE!
    1 R@ SBOX-CANDIDATE-FUNCTION-RESULTS-OFFSET +
        SBOX-CANDIDATE-U16-LE!
    R> DROP

    _S3D-CANDIDATE
    _S3D-LAYOUT SBOX-CANDIDATE-LAYOUT-ENTRIES@ + >R
    4 R@ SBOX-CANDIDATE-ENTRY-NAME-U-OFFSET +
        SBOX-CANDIDATE-U16-LE!
    SBOX-ABI-SIGNATURE-VALUE-TO-VALUE
    R@ SBOX-CANDIDATE-ENTRY-SIGNATURE-ID-OFFSET +
        SBOX-CANDIDATE-U32-LE!
    R> DROP

    _S3D-CANDIDATE
    _S3D-LAYOUT SBOX-CANDIDATE-LAYOUT-NAMES@ +
    DUP [CHAR] m SWAP C!
    DUP 1+ [CHAR] a SWAP C!
    DUP 2 + [CHAR] i SWAP C!
    3 + [CHAR] n SWAP C!

    SBOX-MACHINE-OP-NOP 0 _S3D-INSTRUCTION!
    SBOX-MACHINE-OP-RETURN 1 _S3D-INSTRUCTION! ;

: _S3D-VERIFY-INTO  ( plan plan-u-cell -- status )
    _S3D-CANDIDATE-U @ SBOX-PLAN-MEASURE
    DUP IF
        >R DROP 0 OVER ! 2DROP R> EXIT
    THEN
    DROP
    DUP 2 PICK !
    >R DROP >R
    _S3D-CANDIDATE _S3D-CANDIDATE-U @
    _S3D-PROFILE
    R> R>
    _S3D-VERIFIER-WORK
    SBOX-VERIFY ;

: _S3D-LIMIT!  ( value field -- )
    _S3D-LIMITS SBOX-VALUE-LIMIT!
    SBOX-VALUE-S-OK = _S3D-ASSERT ;

: _S3D-LIMITS-INIT  ( -- )
    _S3D-LIMITS SBOX-VALUE-LIMITS-BEGIN
        SBOX-VALUE-S-OK = _S3D-ASSERT
       8 SBOX-VALUE-LIMIT-DEPTH _S3D-LIMIT!
      64 SBOX-VALUE-LIMIT-BLOB-BYTES _S3D-LIMIT!
       8 SBOX-VALUE-LIMIT-LIST-COUNT _S3D-LIMIT!
       4 SBOX-VALUE-LIMIT-MAP-COUNT _S3D-LIMIT!
      32 SBOX-VALUE-LIMIT-INPUT-NODES _S3D-LIMIT!
    4096 SBOX-VALUE-LIMIT-INPUT-BYTES _S3D-LIMIT!
      32 SBOX-VALUE-LIMIT-OUTPUT-ARENA-NODES _S3D-LIMIT!
    4096 SBOX-VALUE-LIMIT-OUTPUT-ARENA-BYTES _S3D-LIMIT!
      64 SBOX-VALUE-LIMIT-OUTPUT-RESULT-NODES _S3D-LIMIT!
    8192 SBOX-VALUE-LIMIT-OUTPUT-RESULT-BYTES _S3D-LIMIT!
    _S3D-LIMITS SBOX-VALUE-LIMITS-SEAL
        SBOX-VALUE-S-OK = _S3D-ASSERT ;

: _S3D-BOOL!  ( flag address -- )
    >R
    R@ 24 0 FILL
    SBOX-VALUE-T-BOOL R@ C!
    8 R@ 8 + SBOX-CANDIDATE-U64-LE!
    R> 16 + SBOX-CANDIDATE-U64-LE! ;

\ @profile compose begin
: _S3D-I64!  ( value address -- )
    >R
    R@ 24 0 FILL
    SBOX-VALUE-T-I64 R@ C!
    8 R@ 8 + SBOX-CANDIDATE-U64-LE!
    R> 16 + SBOX-CANDIDATE-U64-LE! ;
\ @profile compose end

\ @profile compose begin
: _S3D-RESULT=?  ( expected expected-u result-envelope -- flag )
    DESK-SBOX-RESULT-PAYLOAD@
    0= IF 2DROP 2DROP 0 EXIT THEN
    DROP
    SBOX-VM-RESULT-CANDIDATE@
    0= IF 2DROP 2DROP 0 EXIT THEN
    2 PICK OVER <> IF 2DROP 2DROP 0 EXIT THEN
    COMPARE 0= ;
\ @profile compose end

: _S3D-PLANS-INIT  ( -- )
    _S3D-PROFILE SBOX-PROFILE-PURE-INIT
        SBOX-PROFILE-S-OK = _S3D-ASSERT
    _S3D-BUILD-ECHO-CANDIDATE
    _S3D-PLAN-A _S3D-PLAN-CAP 0xA5 FILL
    _S3D-PLAN-A _S3D-PLAN-A-U _S3D-VERIFY-INTO
        SBOX-VERIFIER-S-OK = _S3D-ASSERT
    _S3D-PLAN-A SBOX-PLAN-VALID? _S3D-ASSERT ;

: _S3D-OWNER-INIT  ( -- )
    _S3D-RID-A RID-CLEAR
    0xA3 _S3D-RID-A C!
    1 _S3D-OWNER _S3D-OWNER-U SBOX-MODULE-OWNER-INIT
        SBOX-MODULE-OWNER-S-OK = _S3D-ASSERT
    _S3D-RID-A 11 _S3D-PLAN-A _S3D-OWNER
        SBOX-MODULE-OWNER-ADD
        SBOX-MODULE-OWNER-S-OK = _S3D-ASSERT
    _S3D-OWNER SBOX-MODULE-OWNER-SEAL
        SBOX-MODULE-OWNER-S-OK = _S3D-ASSERT ;

: _S3D-PARENT-COMPONENTS-INIT  ( -- )
    HEAP-FREE-BYTES _S3D-HEAP-BEFORE !
    1 CTX-NEW DUP IF THROW THEN DROP _S3D-PARENT !
    _S3D-PARENT @ DUP CTX.FLAGS @ CTX-F-ACTIVE OR
        OVER CTX.FLAGS !
    CTX-TOUCH
    _S3D-COMPONENT-A DESK-SBOX-COMPONENT-SIZE 0 FILL
\ @profile compose begin
    _S3D-COMPONENT-B DESK-SBOX-COMPONENT-SIZE 0 FILL
\ @profile compose end
\ @profile compose begin
    _S3D-RESULT-A DESK-SBOX-RESULT-SIZE 0 FILL
    _S3D-RESULT-B DESK-SBOX-RESULT-SIZE 0 FILL
\ @profile compose end
\ @profile cancel,close begin
    _S3D-RESULT-C DESK-SBOX-RESULT-SIZE 0 FILL
\ @profile cancel,close end
    _S3D-OWNER _S3D-PARENT @ _S3D-LIMITS
        100 100 1024 _S3D-COMPONENT-A
        DESK-SBOX-COMPONENT-INIT
        DESK-SBOX-S-OK = _S3D-ASSERT
\ @profile compose begin
    _S3D-OWNER _S3D-PARENT @ _S3D-LIMITS
        100 100 1024 _S3D-COMPONENT-B
        DESK-SBOX-COMPONENT-INIT
        DESK-SBOX-S-OK = _S3D-ASSERT
\ @profile compose end
    _S3D-COMPONENT-A DESK-SBOX-COMPONENT-VALID? _S3D-ASSERT
\ @profile compose begin
    _S3D-COMPONENT-B DESK-SBOX-COMPONENT-VALID? _S3D-ASSERT
\ @profile compose end
    ;

: _S3D-VALUES-INIT  ( -- )
    0 _S3D-INPUT-A _S3D-BOOL!
\ @profile compose begin
    42 _S3D-INPUT-B _S3D-I64!
\ @profile compose end
\ @profile compose begin
    0 _S3D-EXPECTED-A _S3D-BOOL!
    42 _S3D-EXPECTED-B _S3D-I64!
\ @profile compose end
    ;

\ @profile compose begin
: _S3D-ADMIT-TWO  ( -- )
    _S3D-RID-A 11 S" main" _S3D-INPUT-A 24 _S3D-COMPONENT-A
        DESK-SBOX-ADMIT
        DESK-SBOX-S-OK = >R _S3D-GENERATION-A ! R> _S3D-ASSERT
    _S3D-RID-A 11 S" main" _S3D-INPUT-B 24 _S3D-COMPONENT-B
        DESK-SBOX-ADMIT
        DESK-SBOX-S-OK = >R _S3D-GENERATION-B ! R> _S3D-ASSERT

    _S3D-GENERATION-A @ _S3D-COMPONENT-A
        DESK-SBOX-CONTEXT-IDENTITY@
        DESK-SBOX-S-OK = >R 2DROP _S3D-CHILD-A ! R> _S3D-ASSERT
    _S3D-GENERATION-B @ _S3D-COMPONENT-B
        DESK-SBOX-CONTEXT-IDENTITY@
        DESK-SBOX-S-OK = >R 2DROP _S3D-CHILD-B ! R> _S3D-ASSERT
    _S3D-CHILD-A @ _S3D-CHILD-B @ <> _S3D-ASSERT

    _S3D-INPUT-A 24 0xA5 FILL
    _S3D-INPUT-B 24 0xA5 FILL ;

: _S3D-RUN-TAKE-TWO  ( -- )
    1 _S3D-GENERATION-A @ _S3D-COMPONENT-A
        DESK-SBOX-RUN-SLICE
        DESK-SBOX-S-OK = SWAP SBOX-VM-RUN-RUNNABLE = AND
        _S3D-ASSERT
    100 _S3D-GENERATION-B @ _S3D-COMPONENT-B
        DESK-SBOX-RUN-SLICE
        DESK-SBOX-S-OK = SWAP SBOX-VM-RUN-COMPLETE = AND
        _S3D-ASSERT
    100 _S3D-GENERATION-A @ _S3D-COMPONENT-A
        DESK-SBOX-RUN-SLICE
        DESK-SBOX-S-OK = SWAP SBOX-VM-RUN-COMPLETE = AND
        _S3D-ASSERT

    _S3D-RESULT-A _S3D-GENERATION-A @ _S3D-COMPONENT-A
        DESK-SBOX-RESULT-TAKE
        DESK-SBOX-S-OK = _S3D-ASSERT
    _S3D-RESULT-B _S3D-GENERATION-B @ _S3D-COMPONENT-B
        DESK-SBOX-RESULT-TAKE
        DESK-SBOX-S-OK = _S3D-ASSERT ;
\ @profile compose end

\ @profile cancel begin
: _S3D-CANCEL-ACTIVE  ( -- )
    0 _S3D-INPUT-A _S3D-BOOL!
    _S3D-RID-A 11 S" main" _S3D-INPUT-A 24 _S3D-COMPONENT-A
        DESK-SBOX-ADMIT
        DESK-SBOX-S-OK = >R _S3D-GENERATION-A ! R> _S3D-ASSERT
    _S3D-GENERATION-A @ _S3D-COMPONENT-A DESK-SBOX-CANCEL
        DESK-SBOX-S-OK = _S3D-ASSERT
    _S3D-GENERATION-A @ _S3D-COMPONENT-A
        DESK-SBOX-RUN-STATE@
        DESK-SBOX-S-OK =
        SWAP SBOX-VM-RUN-CANCELLED = AND _S3D-ASSERT
    _S3D-RESULT-C _S3D-GENERATION-A @ _S3D-COMPONENT-A
        DESK-SBOX-RESULT-TAKE
        DESK-SBOX-S-OK = _S3D-ASSERT
    _S3D-RESULT-C DESK-SBOX-RESULT-PAYLOAD@
        _S3D-ASSERT DROP
    DUP SBOX-VM-RESULT-CLASS@
        SBOX-VM-CLASS-CANCELLED = _S3D-ASSERT
    SBOX-VM-RESULT-DETAIL@
        SBOX-VM-CANCEL-CALLER = _S3D-ASSERT
    _S3D-RESULT-C DESK-SBOX-RESULT-RELEASE
        DESK-SBOX-S-OK = _S3D-ASSERT ;
\ @profile cancel end

\ @profile close begin
: _S3D-CLOSE-ACTIVE  ( -- )
    0 _S3D-INPUT-A _S3D-BOOL!
    _S3D-RID-A 11 S" main" _S3D-INPUT-A 24 _S3D-COMPONENT-A
        DESK-SBOX-ADMIT
        DESK-SBOX-S-OK = >R _S3D-GENERATION-A ! R> _S3D-ASSERT
    _S3D-COMPONENT-A DESK-SBOX-CLOSE
        DESK-SBOX-S-OK = _S3D-ASSERT
    _S3D-GENERATION-A @ _S3D-COMPONENT-A
        DESK-SBOX-RUN-STATE@
        DESK-SBOX-S-OK =
        SWAP SBOX-VM-RUN-CANCELLED = AND _S3D-ASSERT
    _S3D-RID-A 11 S" main" _S3D-INPUT-A 24 _S3D-COMPONENT-A
        DESK-SBOX-ADMIT
        DESK-SBOX-S-STATE = SWAP 0= AND _S3D-ASSERT
    _S3D-RESULT-C _S3D-GENERATION-A @ _S3D-COMPONENT-A
        DESK-SBOX-RESULT-TAKE
        DESK-SBOX-S-OK = _S3D-ASSERT
    _S3D-RESULT-C DESK-SBOX-RESULT-VALID? _S3D-ASSERT
    _S3D-RESULT-C DESK-SBOX-RESULT-PAYLOAD@
        _S3D-ASSERT DROP
    DUP SBOX-VM-RESULT-CLASS@
        SBOX-VM-CLASS-CANCELLED = _S3D-ASSERT
    SBOX-VM-RESULT-DETAIL@
        SBOX-VM-CANCEL-HOST-SHUTDOWN = _S3D-ASSERT
    _S3D-RESULT-C DESK-SBOX-RESULT-RELEASE
        DESK-SBOX-S-OK = _S3D-ASSERT ;
\ @profile close end

\ @profile drain begin
: _S3D-DRAIN-LIVE  ( -- )
    0 _S3D-INPUT-A _S3D-BOOL!
    _S3D-RID-A 11 S" main" _S3D-INPUT-A 24 _S3D-COMPONENT-A
        DESK-SBOX-ADMIT
        DESK-SBOX-S-OK = >R _S3D-GENERATION-A ! R> _S3D-ASSERT
    _S3D-COMPONENT-A DESK-SBOX-DRAIN
        DESK-SBOX-S-OK = _S3D-ASSERT
    _S3D-COMPONENT-A DESK-SBOX-COMPONENT-STATE@
        DESK-SBOX-COMPONENT-STATE-DRAINED = _S3D-ASSERT ;
\ @profile drain end

: _S3D-TEARDOWN-BORROWS  ( -- )
    _S3D-COMPONENT-A DESK-SBOX-COMPONENT-RELEASE
        DESK-SBOX-S-OK = _S3D-ASSERT
\ @profile compose begin
    _S3D-COMPONENT-B DESK-SBOX-COMPONENT-RELEASE
        DESK-SBOX-S-OK = _S3D-ASSERT
\ @profile compose end
    _S3D-OWNER SBOX-MODULE-OWNER-RELEASE
        SBOX-MODULE-OWNER-S-OK = _S3D-ASSERT
    _S3D-PLAN-A SBOX-PLAN-RELEASE
        SBOX-PLAN-S-OK = _S3D-ASSERT
    _S3D-PROFILE SBOX-PROFILE-SIZE 0 FILL
    0 _S3D-PARENT @ CTX.FLAGS !
    _S3D-PARENT @ CTX-FREE
    0 _S3D-PARENT ! ;

\ @profile compose begin
: _S3D-DETACHED-RESULTS  ( -- )
    _S3D-EXPECTED-A 24 _S3D-RESULT-A _S3D-RESULT=? _S3D-ASSERT
    _S3D-EXPECTED-B 24 _S3D-RESULT-B _S3D-RESULT=? _S3D-ASSERT
    _S3D-RESULT-A DESK-SBOX-RESULT-RELEASE
        DESK-SBOX-S-OK = _S3D-ASSERT
    _S3D-RESULT-B DESK-SBOX-RESULT-RELEASE
        DESK-SBOX-S-OK = _S3D-ASSERT
    HEAP-FREE-BYTES _S3D-HEAP-BEFORE @ = _S3D-ASSERT ;
\ @profile compose end

: _S3D-GROUP-BEGIN  ( -- )
    0 _S3D-FAILS !
    0 _S3D-CHECKS !
    DEPTH _S3D-DEPTH !
    _S3D-LIMITS-INIT
    _S3D-VALUES-INIT
    _S3D-PLANS-INIT
    _S3D-OWNER-INIT
    _S3D-PARENT-COMPONENTS-INIT ;

\ @profile compose begin
: _S3D-COMPOSE-RUN  ( -- )
    ." SBOX STAGE3 DESK COMPOSE START" CR TX-FLUSH
    _S3D-GROUP-BEGIN
    _S3D-ADMIT-TWO
    _S3D-RUN-TAKE-TWO
    _S3D-TEARDOWN-BORROWS
    _S3D-DETACHED-RESULTS
    _S3D-STACK
    _S3D-FAILS @ IF
        ." SBOX STAGE3 DESK COMPOSE FAIL "
        _S3D-FAILS @ . ." / " _S3D-CHECKS @ . CR TX-FLUSH
    ELSE
        ." SBOX STAGE3 DESK COMPOSE PASS "
        _S3D-CHECKS @ . CR TX-FLUSH
    THEN ;
\ @profile compose end

\ @profile cancel begin
: _S3D-CANCEL-RUN  ( -- )
    ." SBOX STAGE3 DESK CANCEL START" CR TX-FLUSH
    _S3D-GROUP-BEGIN
    _S3D-CANCEL-ACTIVE
    _S3D-TEARDOWN-BORROWS
    HEAP-FREE-BYTES _S3D-HEAP-BEFORE @ = _S3D-ASSERT
    _S3D-STACK
    _S3D-FAILS @ IF
        ." SBOX STAGE3 DESK CANCEL FAIL "
        _S3D-FAILS @ . ." / " _S3D-CHECKS @ . CR TX-FLUSH
    ELSE
        ." SBOX STAGE3 DESK CANCEL PASS "
        _S3D-CHECKS @ . CR TX-FLUSH
    THEN ;
\ @profile cancel end

\ @profile drain begin
: _S3D-DRAIN-RUN  ( -- )
    ." SBOX STAGE3 DESK DRAIN START" CR TX-FLUSH
    _S3D-GROUP-BEGIN
    _S3D-DRAIN-LIVE
    _S3D-TEARDOWN-BORROWS
    HEAP-FREE-BYTES _S3D-HEAP-BEFORE @ = _S3D-ASSERT
    _S3D-STACK
    _S3D-FAILS @ IF
        ." SBOX STAGE3 DESK DRAIN FAIL "
        _S3D-FAILS @ . ." / " _S3D-CHECKS @ . CR TX-FLUSH
    ELSE
        ." SBOX STAGE3 DESK DRAIN PASS "
        _S3D-CHECKS @ . CR TX-FLUSH
    THEN ;
\ @profile drain end

\ @profile close begin
: _S3D-CLOSE-RUN  ( -- )
    ." SBOX STAGE3 DESK CLOSE START" CR TX-FLUSH
    _S3D-GROUP-BEGIN
    _S3D-CLOSE-ACTIVE
    _S3D-TEARDOWN-BORROWS
    HEAP-FREE-BYTES _S3D-HEAP-BEFORE @ = _S3D-ASSERT
    _S3D-STACK
    _S3D-FAILS @ IF
        ." SBOX STAGE3 DESK CLOSE FAIL "
        _S3D-FAILS @ . ." / " _S3D-CHECKS @ . CR TX-FLUSH
    ELSE
        ." SBOX STAGE3 DESK CLOSE PASS "
        _S3D-CHECKS @ . CR TX-FLUSH
    THEN ;
\ @profile close end

[DEFINED] SBOX-STAGE3-DESK-DEFER-AUTORUN [IF]
[ELSE]
    _S3D-COMPOSE-RUN
[THEN]
