\ Focused contracts for the inert Practice sandbox role-binding boundary.
\ The harness must load sandbox-practice-binding.f first.
\
\ Static companion check:
\   rg -n '^PROVIDED akashic-rt-sbx-pbind$' akashic
\ must report exactly this production module.  The contract below also
\ asserts that the key is exactly 20 bytes and within the loader's 23-byte
\ comparison width.  No production word in the module compiles, resolves,
\ invokes, dispatches, installs, or updates a PHEAD.

PROVIDED sbox-pbind-contracts

VARIABLE _PBCT-FAILS
VARIABLE _PBCT-CHECKS
VARIABLE _PBCT-DEPTH
VARIABLE _PBCT-BUILD-OK
VARIABLE _PBCT-RECORD

: _PBCT-ALIGN8  ( address -- aligned-address )
    7 + -8 AND ;

460  CONSTANT _PBCT-DECL-TOTAL
1216 CONSTANT _PBCT-BINDING-TOTAL

CREATE _PBCT-DECL-RAW 519 ALLOT
_PBCT-DECL-RAW _PBCT-ALIGN8 CONSTANT _PBCT-DECL

CREATE _PBCT-DECL-VIEW-RAW SBOX-DECL-VIEW-SIZE 7 + ALLOT
_PBCT-DECL-VIEW-RAW _PBCT-ALIGN8 CONSTANT _PBCT-DECL-VIEW

CREATE _PBCT-BINDING-RAW _PBCT-BINDING-TOTAL 8 + ALLOT
_PBCT-BINDING-RAW _PBCT-ALIGN8 CONSTANT _PBCT-BINDING

CREATE _PBCT-VIEW-RAW SBOX-PBIND-VIEW-SIZE 7 + ALLOT
_PBCT-VIEW-RAW _PBCT-ALIGN8 CONSTANT _PBCT-VIEW

CREATE _PBCT-VIEW-COPY-RAW SBOX-PBIND-VIEW-SIZE 7 + ALLOT
_PBCT-VIEW-COPY-RAW _PBCT-ALIGN8 CONSTANT _PBCT-VIEW-COPY

CREATE _PBCT-WORK-RAW SBOX-DIGEST-WORKSPACE-SIZE 7 + ALLOT
_PBCT-WORK-RAW _PBCT-ALIGN8 CONSTANT _PBCT-WORK

CREATE _PBCT-HEAD-RAW PHEAD-SIZE 7 + ALLOT
_PBCT-HEAD-RAW _PBCT-ALIGN8 CONSTANT _PBCT-HEAD

CREATE _PBCT-DECL-DIGEST SBOX-DIGEST-SIZE ALLOT
CREATE _PBCT-DIGEST-A SBOX-DIGEST-SIZE ALLOT
CREATE _PBCT-DIGEST-B SBOX-DIGEST-SIZE ALLOT

: _PBCT-DECL-ENTRY  ( -- entry )
    _PBCT-DECL SBOX-DECL-HEADER-SIZE + 8 + ;

: _PBCT-DECL-SCHEMAS  ( -- schemas )
    _PBCT-DECL-ENTRY SBOX-DECL-ENTRY-SIZE + ;

: _PBCT-RECORD0  ( -- record )
    _PBCT-BINDING SBOX-PBIND-HEADER-SIZE + ;

: _PBCT-RECORD1  ( -- record )
    _PBCT-RECORD0 SBOX-PBIND-RECORD-SIZE + ;

: _PBCT-ASSERT  ( flag -- )
    1 _PBCT-CHECKS +!
    0= IF
        1 _PBCT-FAILS +!
        ." SBOX PBIND ASSERT " _PBCT-CHECKS @ . CR
    THEN ;

: _PBCT-STACK  ( -- )
    DEPTH DUP _PBCT-DEPTH @ <> IF
        ." SBOX PBIND STACK " _PBCT-DEPTH @ . ." -> " DUP . CR
        .S CR
    THEN
    _PBCT-DEPTH @ = _PBCT-ASSERT ;

: _PBCT-ZERO?  ( address length -- flag )
    BEGIN DUP 0> WHILE
        OVER C@ IF 2DROP 0 EXIT THEN
        1- SWAP 1+ SWAP
    REPEAT
    2DROP -1 ;

: _PBCT-U16!  ( value address -- )
    >R
    DUP 0xFF AND R@ C!
    8 RSHIFT 0xFF AND R> 1+ C! ;

: _PBCT-U32!  ( value address -- )
    >R
    DUP 0xFFFF AND R@ _PBCT-U16!
    16 RSHIFT 0xFFFF AND R> 2 + _PBCT-U16! ;

: _PBCT-U64!  ( value address -- )
    >R
    DUP 0xFFFFFFFF AND R@ _PBCT-U32!
    32 RSHIFT R> 4 + _PBCT-U32! ;

: _PBCT-FILL32  ( byte address -- )
    SWAP SBOX-DIGEST-SIZE SWAP FILL ;

: _PBCT-ACCEPT  ( status -- )
    0<> IF 0 _PBCT-BUILD-OK ! THEN ;

: _PBCT-WRITE-DECLARATION  ( -- )
    _PBCT-DECL 512 0 FILL
    _PBCT-DECL-VIEW SBOX-DECL-VIEW-SIZE 0 FILL
    _PBCT-WORK SBOX-DIGEST-WORKSPACE-SIZE 0 FILL

    _SDECL-WIRE-MAGIC
        _PBCT-DECL _SDCL-H-MAGIC + _PBCT-U64!
    SBOX-DECL-FORMAT-V1
        _PBCT-DECL _SDCL-H-FORMAT + _PBCT-U16!
    SBOX-DECL-HEADER-SIZE
        _PBCT-DECL _SDCL-H-HEADER-U + _PBCT-U16!
    _PBCT-DECL-TOTAL
        _PBCT-DECL _SDCL-H-TOTAL-U + _PBCT-U64!
    1 _PBCT-DECL _SDCL-H-ENTRY-N + _PBCT-U32!
    0 _PBCT-DECL _SDCL-H-CEILING-N + _PBCT-U16!
    4 _PBCT-DECL _SDCL-H-PROFILE-ID-U + _PBCT-U16!
    SBOX-DECL-PROVENANCE-NONE
        _PBCT-DECL _SDCL-H-PROVENANCE-KIND + _PBCT-U16!
    4 _PBCT-DECL _SDCL-H-SCHEMA-U + _PBCT-U64!
    0xA1 _PBCT-DECL _SDCL-H-OWNER-RID + _PBCT-FILL32
    0xA2 _PBCT-DECL _SDCL-H-MODULE-RID + _PBCT-FILL32
    7 _PBCT-DECL _SDCL-H-MODULE-REVISION + _PBCT-U64!

    S" artifact-fixture"
    _PBCT-DECL _SDCL-H-ARTIFACT-DIGEST +
    _PBCT-WORK SBOX-DIGEST-ARTIFACT _PBCT-ACCEPT

    S" pure"
    _PBCT-DECL _SDCL-H-PROFILE-DIGEST +
    _PBCT-WORK SBOX-DIGEST-PROFILE _PBCT-ACCEPT

    S" pure"
    _PBCT-DECL SBOX-DECL-HEADER-SIZE + SWAP MOVE

    5 _PBCT-DECL-ENTRY _SDCL-E-NAME-U + _PBCT-U16!
    SBOX-DECL-SIGNATURE-PURE-VALUE
        _PBCT-DECL-ENTRY _SDCL-E-SIGNATURE + _PBCT-U16!
    SBOX-DECL-SCHEMA-EMBEDDED
        _PBCT-DECL-ENTRY _SDCL-E-INPUT-STORAGE + C!
    SBOX-DECL-SCHEMA-EMBEDDED
        _PBCT-DECL-ENTRY _SDCL-E-OUTPUT-STORAGE + C!
    S" alpha"
    _PBCT-DECL-ENTRY _SDCL-E-NAME + SWAP MOVE

    2 _PBCT-DECL-ENTRY _SDCL-E-INPUT-U + _PBCT-U64!
    0 _PBCT-DECL-ENTRY _SDCL-E-INPUT-OFFSET + _PBCT-U64!
    2 _PBCT-DECL-ENTRY _SDCL-E-OUTPUT-U + _PBCT-U64!
    2 _PBCT-DECL-ENTRY _SDCL-E-OUTPUT-OFFSET + _PBCT-U64!

    0xA1 _PBCT-DECL-SCHEMAS C!
    0x01 _PBCT-DECL-SCHEMAS 1+ C!
    0xA2 _PBCT-DECL-SCHEMAS 2 + C!
    0x01 _PBCT-DECL-SCHEMAS 3 + C!

    _PBCT-DECL-SCHEMAS 2
    _PBCT-DECL-ENTRY _SDCL-E-INPUT-DIGEST +
    _PBCT-WORK SBOX-DIGEST-SCHEMA _PBCT-ACCEPT

    _PBCT-DECL-SCHEMAS 2 + 2
    _PBCT-DECL-ENTRY _SDCL-E-OUTPUT-DIGEST +
    _PBCT-WORK SBOX-DIGEST-SCHEMA _PBCT-ACCEPT

    _PBCT-DECL _PBCT-DECL-TOTAL
    _PBCT-DECL-VIEW _PBCT-WORK
        SBOX-DECL-VALIDATE _PBCT-ACCEPT

    _PBCT-DECL _PBCT-DECL-TOTAL
    _PBCT-DECL-DIGEST _PBCT-WORK
        SBOX-DECL-DIGEST _PBCT-ACCEPT ;

: _PBCT-WRITE-RECORD-COMMON  ( record -- )
    >R
    5 R@ _PBI-R-ENTRY-U + _PBCT-U16!
    SBOX-DECL-SIGNATURE-PURE-VALUE
        R@ _PBI-R-SIGNATURE + _PBCT-U16!
    SBOX-BUDGET-LIMIT-FIELD-COUNT
        R@ _PBI-R-BUDGET-FIELD-N + _PBCT-U16!
    S" alpha" R@ _PBI-R-ENTRY + SWAP MOVE

    _PBCT-DECL _SDCL-H-OWNER-RID +
        R@ _PBI-R-OWNER-RID + RID-SIZE MOVE
    _PBCT-DECL _SDCL-H-MODULE-RID +
        R@ _PBI-R-MODULE-RID + RID-SIZE MOVE
    7 R@ _PBI-R-MODULE-REVISION + _PBCT-U64!
    _PBCT-DECL-DIGEST
        R@ _PBI-R-DECLARATION-DIGEST + SBOX-DIGEST-SIZE MOVE
    _PBCT-DECL _SDCL-H-ARTIFACT-DIGEST +
        R@ _PBI-R-ARTIFACT-DIGEST + SBOX-DIGEST-SIZE MOVE
    _PBCT-DECL _SDCL-H-PROFILE-DIGEST +
        R@ _PBI-R-PROFILE-DIGEST + SBOX-DIGEST-SIZE MOVE
    _PBCT-DECL-ENTRY _SDCL-E-INPUT-DIGEST +
        R@ _PBI-R-INPUT-SCHEMA-DIGEST + SBOX-DIGEST-SIZE MOVE
    _PBCT-DECL-ENTRY _SDCL-E-OUTPUT-DIGEST +
        R@ _PBI-R-OUTPUT-SCHEMA-DIGEST + SBOX-DIGEST-SIZE MOVE
    R> DROP ;

: _PBCT-WRITE-RECORD0  ( -- )
    _PBCT-RECORD0 >R
    R@ _PBCT-WRITE-RECORD-COMMON
    7 R@ _PBI-R-ROLE-U + _PBCT-U16!
    S" primary" R@ _PBI-R-ROLE + SWAP MOVE
    5000 SBOX-BUDGET-LIMIT-INSTRUCTION-UNITS
        R@ _PBIND-BUDGET _PBCT-U64!
    100 SBOX-BUDGET-LIMIT-OUTER-DEADLINE-MS
        R@ _PBIND-BUDGET _PBCT-U64!
    R> DROP ;

: _PBCT-WRITE-RECORD1  ( -- )
    _PBCT-RECORD1 >R
    R@ _PBCT-WRITE-RECORD-COMMON
    7 R@ _PBI-R-ROLE-U + _PBCT-U16!
    S" summary" R@ _PBI-R-ROLE + SWAP MOVE
    3000 SBOX-BUDGET-LIMIT-INSTRUCTION-UNITS
        R@ _PBIND-BUDGET _PBCT-U64!
    R> DROP ;

: _PBCT-WRITE-BINDING  ( -- )
    _PBCT-BINDING _PBCT-BINDING-TOTAL 1+ 0 FILL
    _PBCT-VIEW SBOX-PBIND-VIEW-SIZE 0 FILL
    _PBCT-WORK SBOX-DIGEST-WORKSPACE-SIZE 0 FILL

    _PBIND-WIRE-MAGIC
        _PBCT-BINDING _PBI-H-MAGIC + _PBCT-U64!
    SBOX-PBIND-FORMAT-V1
        _PBCT-BINDING _PBI-H-FORMAT + _PBCT-U16!
    SBOX-PBIND-HEADER-SIZE
        _PBCT-BINDING _PBI-H-HEADER-U + _PBCT-U16!
    _PBCT-BINDING-TOTAL
        _PBCT-BINDING _PBI-H-TOTAL-U + _PBCT-U64!
    2 _PBCT-BINDING _PBI-H-RECORD-N + _PBCT-U32!
    SBOX-BUDGET-LIMIT-FIELD-COUNT
        _PBCT-BINDING _PBI-H-BUDGET-FIELD-N + _PBCT-U16!
    SBOX-PBIND-NAME-MAX
        _PBCT-BINDING _PBI-H-NAME-MAX + _PBCT-U16!
    0xB1 _PBCT-BINDING _PBI-H-PRACTICE-RID + _PBCT-FILL32

    _PBCT-WRITE-RECORD0
    _PBCT-WRITE-RECORD1 ;

: _PBCT-BUILD  ( -- flag )
    -1 _PBCT-BUILD-OK !
    _PBCT-WRITE-DECLARATION
    _PBCT-WRITE-BINDING
    _PBCT-BUILD-OK @ ;

: _PBCT-VALIDATE  ( -- status )
    _PBCT-BINDING _PBCT-BINDING-TOTAL
    _PBCT-VIEW _PBCT-WORK SBOX-PBIND-VALIDATE ;

: _PBCT-BUILD-PHEAD  ( -- )
    _PBCT-HEAD PHEAD-INIT
    0xB1 _PBCT-HEAD PHEAD.ID _PBCT-FILL32
    0xC1 _PBCT-HEAD PHEAD.CURRENT-ROOT _PBCT-FILL32
    _PBCT-VIEW _PBV.DIGEST
        _PBCT-HEAD PHEAD.BINDING-ROOT RID-SIZE MOVE ;

: _PBCT-FORMAT-AND-ACCESS-CONTRACTS  ( -- )
    S" akashic-rt-sbx-pbind"
        DUP 20 = SWAP 23 <= AND NIP _PBCT-ASSERT
    SBOX-PBIND-HEADER-SIZE 128 = _PBCT-ASSERT
    SBOX-PBIND-RECORD-SIZE 544 = _PBCT-ASSERT
    SBOX-PBIND-VIEW-SIZE 112 = _PBCT-ASSERT
    SBOX-PBIND-BYTES-MAX 34944 = _PBCT-ASSERT

    _PBCT-BUILD _PBCT-ASSERT
    _PBCT-VALIDATE SBOX-PBIND-S-OK = _PBCT-ASSERT
    _PBCT-VIEW SBOX-PBIND-VIEW-VALID? _PBCT-ASSERT
    _PBCT-WORK SBOX-DIGEST-WORKSPACE-SIZE
        _PBCT-ZERO? _PBCT-ASSERT

    _PBCT-VIEW SBOX-PBIND-SOURCE@
        SBOX-PBIND-S-OK = >R
        _PBCT-BINDING-TOTAL = SWAP
        _PBCT-BINDING = AND R> AND _PBCT-ASSERT
    _PBCT-VIEW SBOX-PBIND-PRACTICE-RID@
        SBOX-PBIND-S-OK = SWAP
        _PBCT-BINDING _PBI-H-PRACTICE-RID + RID= AND
        _PBCT-ASSERT
    _PBCT-VIEW SBOX-PBIND-RECORD-COUNT@
        SBOX-PBIND-S-OK = SWAP 2 = AND _PBCT-ASSERT

    0 _PBCT-VIEW SBOX-PBIND-RECORD@
        DUP SBOX-PBIND-S-OK = _PBCT-ASSERT
    DROP _PBCT-RECORD !
    _PBCT-RECORD @ _PBCT-VIEW SBOX-PBIND-RECORD-ROLE@
        SBOX-PBIND-S-OK = >R
        S" primary" COMPARE 0= R> AND _PBCT-ASSERT
    _PBCT-RECORD @ _PBCT-VIEW SBOX-PBIND-RECORD-ENTRY@
        SBOX-PBIND-S-OK = >R
        SBOX-DECL-SIGNATURE-PURE-VALUE = >R
        S" alpha" COMPARE 0=
        R> AND R> AND _PBCT-ASSERT

    _PBCT-RECORD @ _PBCT-VIEW
        SBOX-PBIND-RECORD-DECLARATION-DIGEST@
        SBOX-PBIND-S-OK = >R
        _PBCT-DECL-DIGEST _PBIND-32= R> AND _PBCT-ASSERT
    _PBCT-RECORD @ _PBCT-VIEW
        SBOX-PBIND-RECORD-MODULE-REVISION@
        SBOX-PBIND-S-OK = SWAP 7 = AND _PBCT-ASSERT

    SBOX-BUDGET-LIMIT-INSTRUCTION-UNITS
        _PBCT-RECORD @ _PBCT-VIEW SBOX-PBIND-RECORD-BUDGET@
        SBOX-PBIND-S-OK = >R
        0<> >R 5000 = R> AND R> AND _PBCT-ASSERT
    SBOX-BUDGET-LIMIT-CALL-FRAMES
        _PBCT-RECORD @ _PBCT-VIEW SBOX-PBIND-RECORD-BUDGET@
        SBOX-PBIND-S-OK = >R
        0= >R 0= R> AND R> AND _PBCT-ASSERT

    S" summary" _PBCT-VIEW SBOX-PBIND-ROLE-FIND-EXACT
        SBOX-PBIND-S-OK = SWAP _PBCT-RECORD1 = AND _PBCT-ASSERT
    S" absent" _PBCT-VIEW SBOX-PBIND-ROLE-FIND-EXACT
        SBOX-PBIND-S-NOT-FOUND = SWAP 0= AND _PBCT-ASSERT
    S" Summary" _PBCT-VIEW SBOX-PBIND-ROLE-FIND-EXACT
        SBOX-PBIND-S-ROLE = SWAP 0= AND _PBCT-ASSERT

    _PBCT-VIEW _PBCT-VIEW-COPY SBOX-PBIND-VIEW-SIZE MOVE
    _PBCT-VIEW-COPY SBOX-PBIND-VIEW-VALID? 0= _PBCT-ASSERT
    _PBCT-STACK ;

: _PBCT-DIGEST-AND-SEAM-CONTRACTS  ( -- )
    _PBCT-WRITE-BINDING
    _PBCT-VALIDATE SBOX-PBIND-S-OK = _PBCT-ASSERT
    _PBCT-BINDING _PBCT-BINDING-TOTAL
        _PBCT-DIGEST-A _PBCT-WORK SBOX-PBIND-DIGEST
        SBOX-PBIND-S-OK = _PBCT-ASSERT
    _PBCT-BINDING _PBCT-BINDING-TOTAL
        _PBCT-DIGEST-B _PBCT-WORK SBOX-DIGEST-RAW
        SBOX-DIGEST-S-OK = _PBCT-ASSERT
    _PBCT-DIGEST-A SBOX-DIGEST-SIZE
        _PBCT-DIGEST-B SBOX-DIGEST-SIZE COMPARE 0<>
        _PBCT-ASSERT
    _PBCT-VIEW SBOX-PBIND-DIGEST@
        SBOX-PBIND-S-OK = >R
        _PBCT-DIGEST-A _PBIND-32= R> AND _PBCT-ASSERT

    _PBCT-VIEW _PBV.DIGEST
        _PBCT-DIGEST-A SBOX-DIGEST-SIZE MOVE
    5001 SBOX-BUDGET-LIMIT-INSTRUCTION-UNITS
        _PBCT-RECORD0 _PBIND-BUDGET _PBCT-U64!
    _PBCT-VALIDATE SBOX-PBIND-S-OK = _PBCT-ASSERT
    _PBCT-VIEW SBOX-PBIND-DIGEST@ DROP
        _PBCT-DIGEST-A _PBIND-32= 0= _PBCT-ASSERT

    _PBCT-BUILD-PHEAD
    _PBCT-HEAD PHEAD-VALID? _PBCT-ASSERT
    _PBCT-VIEW _PBCT-HEAD SBOX-PBIND-MATCH-PHEAD
        SBOX-PBIND-S-OK = _PBCT-ASSERT

    _PBCT-BUILD-PHEAD
    _PBCT-HEAD PHEAD.BINDING-ROOT RID-CLEAR
    _PBCT-VIEW _PBCT-HEAD SBOX-PBIND-MATCH-PHEAD
        SBOX-PBIND-S-MISMATCH = _PBCT-ASSERT

    _PBCT-BUILD-PHEAD
    0xB2 _PBCT-HEAD PHEAD.ID _PBCT-FILL32
    _PBCT-VIEW _PBCT-HEAD SBOX-PBIND-MATCH-PHEAD
        SBOX-PBIND-S-MISMATCH = _PBCT-ASSERT

    _PBCT-BUILD-PHEAD
    _PBCT-HEAD PHEAD.CURRENT-ROOT RID-CLEAR
    _PBCT-VIEW _PBCT-HEAD SBOX-PBIND-MATCH-PHEAD
        SBOX-PBIND-S-INVALID = _PBCT-ASSERT
    _PBCT-STACK ;

: _PBCT-DECLARATION-CROSS-CHECK-CONTRACTS  ( -- )
    _PBCT-WRITE-BINDING
    _PBCT-VALIDATE SBOX-PBIND-S-OK = _PBCT-ASSERT
    0 _PBCT-VIEW SBOX-PBIND-RECORD@ DROP _PBCT-RECORD !
    _PBCT-RECORD @ _PBCT-VIEW
        _PBCT-DECL-VIEW _PBCT-DECL-DIGEST
        SBOX-PBIND-RECORD-MATCH-DECLARATION
        SBOX-PBIND-S-OK = _PBCT-ASSERT

    _PBCT-RECORD @ _PBCT-VIEW
        _PBCT-DECL-VIEW _PBCT-DIGEST-B
        SBOX-PBIND-RECORD-MATCH-DECLARATION
        SBOX-PBIND-S-MISMATCH = _PBCT-ASSERT

    _PBCT-WRITE-BINDING
    _PBCT-RECORD0 _PBI-R-ARTIFACT-DIGEST + DUP C@
        1 XOR SWAP C!
    _PBCT-VALIDATE SBOX-PBIND-S-OK = _PBCT-ASSERT
    0 _PBCT-VIEW SBOX-PBIND-RECORD@ DROP _PBCT-RECORD !
    _PBCT-RECORD @ _PBCT-VIEW
        _PBCT-DECL-VIEW _PBCT-DECL-DIGEST
        SBOX-PBIND-RECORD-MATCH-DECLARATION
        SBOX-PBIND-S-MISMATCH = _PBCT-ASSERT
    _PBCT-STACK ;

: _PBCT-REJECTION-CONTRACTS  ( -- )
    _PBCT-WRITE-BINDING
    _PBCT-BINDING _PBCT-BINDING-TOTAL 1+
        _PBCT-VIEW _PBCT-WORK SBOX-PBIND-VALIDATE
        SBOX-PBIND-S-FORMAT = _PBCT-ASSERT

    _PBCT-WRITE-BINDING
    _PBCT-RECORD0 _PBI-R-DECLARATION-DIGEST +
        SBOX-DIGEST-SIZE 0 FILL
    _PBCT-VALIDATE SBOX-PBIND-S-DIGEST = _PBCT-ASSERT

    _PBCT-WRITE-BINDING
    SBOX-BUDGET-HARD-INSTRUCTION-UNITS 1+
        SBOX-BUDGET-LIMIT-INSTRUCTION-UNITS
        _PBCT-RECORD0 _PBIND-BUDGET _PBCT-U64!
    _PBCT-VALIDATE SBOX-PBIND-S-BUDGET = _PBCT-ASSERT

    _PBCT-WRITE-BINDING
    [CHAR] a _PBCT-RECORD1 _PBI-R-ROLE + C!
    _PBCT-VALIDATE SBOX-PBIND-S-ORDER = _PBCT-ASSERT

    _PBCT-WRITE-BINDING
    [CHAR] A _PBCT-RECORD0 _PBI-R-ENTRY + C!
    _PBCT-VALIDATE SBOX-PBIND-S-ENTRY = _PBCT-ASSERT

    _PBCT-WRITE-BINDING
    1 _PBCT-RECORD0 _PBI-R-ROLE + 63 + C!
    _PBCT-VALIDATE SBOX-PBIND-S-ROLE = _PBCT-ASSERT

    _PBCT-WRITE-BINDING
    1 _PBCT-RECORD0 _PBI-R-RESERVED + _PBCT-U32!
    _PBCT-VALIDATE SBOX-PBIND-S-RESERVED = _PBCT-ASSERT

    _PBCT-WRITE-BINDING
    _PBCT-BINDING _PBI-H-PRACTICE-RID + RID-CLEAR
    _PBCT-VALIDATE SBOX-PBIND-S-IDENTITY = _PBCT-ASSERT

    _PBCT-WRITE-BINDING
    _PBCT-BINDING _PBCT-BINDING-TOTAL
        _PBCT-BINDING 8 + _PBCT-WORK SBOX-PBIND-VALIDATE
        SBOX-PBIND-S-ALIAS = _PBCT-ASSERT

    _PBCT-VIEW SBOX-PBIND-VIEW-VALID? 0= _PBCT-ASSERT
    _PBCT-STACK ;

: _PBCT-RUN  ( -- )
    0 _PBCT-FAILS !
    0 _PBCT-CHECKS !
    DEPTH _PBCT-DEPTH !
    ." SBOX PBIND CONTRACTS START" CR
    _PBCT-FORMAT-AND-ACCESS-CONTRACTS
    _PBCT-DIGEST-AND-SEAM-CONTRACTS
    _PBCT-DECLARATION-CROSS-CHECK-CONTRACTS
    _PBCT-REJECTION-CONTRACTS
    _PBCT-STACK
    _PBCT-FAILS @ 0= IF
        ." SBOX PBIND CONTRACTS PASS " _PBCT-CHECKS @ . CR
    ELSE
        ." SBOX PBIND CONTRACTS FAIL " _PBCT-FAILS @ . CR
    THEN ;

[DEFINED] SBOX-PBIND-DEFER-AUTORUN [IF]
[ELSE]
    _PBCT-RUN
[THEN]
