\ Focused contracts for sandbox entry signatures and typed-opcode admission.

PROVIDED sbox-signature-contracts

VARIABLE _SSIG-FAILS
VARIABLE _SSIG-CHECKS
VARIABLE _SSIG-DEPTH
VARIABLE _SSIG-CANDIDATE-U
VARIABLE _SSIG-PLAN-U

8192 CONSTANT _SSIG-CANDIDATE-CAP
8448 CONSTANT _SSIG-PLAN-CAP

: _SSIG-ALIGN8  ( address -- aligned-address ) 7 + -8 AND ;

CREATE _SSIG-PROFILE-RAW SBOX-PROFILE-SIZE 7 + ALLOT
_SSIG-PROFILE-RAW _SSIG-ALIGN8 CONSTANT _SSIG-PROFILE
CREATE _SSIG-CANDIDATE-RAW _SSIG-CANDIDATE-CAP 7 + ALLOT
_SSIG-CANDIDATE-RAW _SSIG-ALIGN8 CONSTANT _SSIG-CANDIDATE
CREATE _SSIG-LAYOUT-RAW SBOX-CANDIDATE-LAYOUT-SIZE 7 + ALLOT
_SSIG-LAYOUT-RAW _SSIG-ALIGN8 CONSTANT _SSIG-LAYOUT
CREATE _SSIG-PLAN-RAW _SSIG-PLAN-CAP 7 + ALLOT
_SSIG-PLAN-RAW _SSIG-ALIGN8 CONSTANT _SSIG-PLAN
CREATE _SSIG-COMPILER-WORK-RAW
    SBOX-COMPILER-WORKSPACE-SIZE 7 + ALLOT
_SSIG-COMPILER-WORK-RAW _SSIG-ALIGN8
    CONSTANT _SSIG-COMPILER-WORK
CREATE _SSIG-VERIFIER-WORK-RAW
    SBOX-VERIFIER-WORKSPACE-SIZE 7 + ALLOT
_SSIG-VERIFIER-WORK-RAW _SSIG-ALIGN8
    CONSTANT _SSIG-VERIFIER-WORK

: _SSIG-ASSERT  ( flag -- )
    1 _SSIG-CHECKS +!
    0= IF
        1 _SSIG-FAILS +!
        ." SBOX SIGNATURE ASSERT " _SSIG-CHECKS @ . CR TX-FLUSH
    THEN ;

: _SSIG-STACK  ( -- )
    DEPTH DUP _SSIG-DEPTH @ <> IF
        ." SBOX SIGNATURE STACK "
        _SSIG-DEPTH @ . ." -> " DUP . CR
        .S CR TX-FLUSH
    THEN
    _SSIG-DEPTH @ = _SSIG-ASSERT ;

: _SSIG-SOURCE-TYPED  ( -- address length )
    S" FUNCTION echo PARAMS 1 RESULTS 1 LOCALS 0 DUP V.TYPE DROP RETURN END ENTRY SIGNATURE 1 main echo" ;

: _SSIG-SOURCE-SCALAR  ( -- address length )
    S" FUNCTION echo PARAMS 1 RESULTS 1 LOCALS 0 DUP DROP RETURN END ENTRY main echo" ;

: _SSIG-SOURCE-TYPED-SCALAR-ENTRY  ( -- address length )
    S" FUNCTION echo PARAMS 1 RESULTS 1 LOCALS 0 DUP V.TYPE DROP RETURN END ENTRY main echo" ;

: _SSIG-SOURCE-MIXED  ( -- address length )
    S" FUNCTION echo PARAMS 1 RESULTS 1 LOCALS 0 DUP DROP RETURN END ENTRY a echo ENTRY SIGNATURE 1 b echo" ;

: _SSIG-SOURCE-WRONG-SHAPE  ( -- address length )
    S" FUNCTION bad PARAMS 0 RESULTS 0 LOCALS 0 RETURN END ENTRY SIGNATURE 1 main bad" ;

: _SSIG-SOURCE-ZERO-SHAPE  ( -- address length )
    S" FUNCTION zero PARAMS 0 RESULTS 0 LOCALS 0 RETURN END ENTRY main zero" ;

: _SSIG-SOURCE-TWO-SCALAR-ENTRIES  ( -- address length )
    S" FUNCTION echo PARAMS 1 RESULTS 1 LOCALS 0 DUP DROP RETURN END ENTRY a echo ENTRY b echo" ;

: _SSIG-COMPILE  ( source source-u -- status )
    _SSIG-CANDIDATE _SSIG-CANDIDATE-CAP 0xA5 FILL
    _SSIG-PROFILE 64
    _SSIG-CANDIDATE _SSIG-CANDIDATE-CAP
    _SSIG-COMPILER-WORK
    SBOX-COMPILE
    SWAP _SSIG-CANDIDATE-U ! ;

: _SSIG-VERIFY  ( -- status )
    _SSIG-CANDIDATE-U @ SBOX-PLAN-MEASURE
    DUP IF
        >R DROP 0 _SSIG-PLAN-U ! R> EXIT
    THEN
    DROP
    DUP _SSIG-PLAN-U !
    >R
    _SSIG-CANDIDATE _SSIG-CANDIDATE-U @
    _SSIG-PROFILE
    _SSIG-PLAN R>
    _SSIG-VERIFIER-WORK
    SBOX-VERIFY ;

: _SSIG-INSPECT  ( -- )
    _SSIG-CANDIDATE _SSIG-CANDIDATE-U @ _SSIG-LAYOUT
    SBOX-CANDIDATE-INSPECT
    SBOX-CANDIDATE-S-OK = _SSIG-ASSERT ;

: _SSIG-ENTRY@  ( index -- record )
    SBOX-CANDIDATE-ENTRY-SIZE *
    _SSIG-CANDIDATE
    _SSIG-LAYOUT SBOX-CANDIDATE-LAYOUT-ENTRIES@ + + ;

: _SSIG-VERIFY-EXPECT  ( expected-status expected-detail expected-index -- )
    >R >R >R
    _SSIG-PLAN _SSIG-PLAN-CAP 0xA5 FILL
    _SSIG-VERIFY R> = _SSIG-ASSERT
    _SSIG-VERIFIER-WORK SBOX-VERIFIER-ERROR-DETAIL@
    SBOX-VERIFIER-S-OK =
    SWAP R> = AND _SSIG-ASSERT
    _SSIG-VERIFIER-WORK SBOX-VERIFIER-ERROR-INDEX@
    SBOX-VERIFIER-S-OK =
    SWAP R> = AND _SSIG-ASSERT ;

: _SSIG-COMPILER-CONTRACTS  ( -- )
    _SSIG-SOURCE-TYPED _SSIG-COMPILE
        SBOX-COMPILER-S-OK = _SSIG-ASSERT
    _SSIG-CANDIDATE-U @ SBOX-CANDIDATE-HEADER-SIZE >
        _SSIG-ASSERT

    _SSIG-SOURCE-SCALAR _SSIG-COMPILE
        SBOX-COMPILER-S-OK = _SSIG-ASSERT

    _SSIG-SOURCE-WRONG-SHAPE _SSIG-COMPILE
        SBOX-COMPILER-S-SOURCE = _SSIG-ASSERT
    _SSIG-CANDIDATE-U @ 0= _SSIG-ASSERT

    _SSIG-SOURCE-TYPED-SCALAR-ENTRY _SSIG-COMPILE
        SBOX-COMPILER-S-SOURCE = _SSIG-ASSERT
    _SSIG-CANDIDATE-U @ 0= _SSIG-ASSERT

    _SSIG-SOURCE-MIXED _SSIG-COMPILE
        SBOX-COMPILER-S-SOURCE = _SSIG-ASSERT
    _SSIG-CANDIDATE-U @ 0= _SSIG-ASSERT
    _SSIG-STACK ;

: _SSIG-PLAN-CONTRACTS  ( -- )
    _SSIG-SOURCE-TYPED _SSIG-COMPILE
        SBOX-COMPILER-S-OK = _SSIG-ASSERT
    _SSIG-VERIFY SBOX-VERIFIER-S-OK = _SSIG-ASSERT
    _SSIG-PLAN SBOX-PLAN-VALID? _SSIG-ASSERT

    0 _SSIG-PLAN SBOX-PLAN-ENTRY-SIGNATURE@
    SWAP SBOX-ABI-SIGNATURE-VALUE-TO-VALUE =
    SWAP AND _SSIG-ASSERT
    0 _SSIG-PLAN SBOX-PLAN-ENTRY-NAME$
    S" main" COMPARE 0= _SSIG-ASSERT

    _SSIG-PLAN SBOX-PLAN-RELEASE
        SBOX-PLAN-S-OK = _SSIG-ASSERT
    _SSIG-STACK ;

: _SSIG-VERIFIER-CONTRACTS  ( -- )
    \ A typed opcode cannot be admitted through the scalar qualification ABI.
    _SSIG-SOURCE-TYPED _SSIG-COMPILE
        SBOX-COMPILER-S-OK = _SSIG-ASSERT
    _SSIG-INSPECT
    0 0 _SSIG-ENTRY@
        SBOX-CANDIDATE-ENTRY-SIGNATURE-ID-OFFSET +
        SBOX-CANDIDATE-U32-LE!
    SBOX-VERIFIER-S-OPCODE
    SBOX-VERIFIER-D-INSTRUCTION-OPCODE 1
        _SSIG-VERIFY-EXPECT

    \ Every exported entry in the current production artifact has one ABI.
    _SSIG-SOURCE-TWO-SCALAR-ENTRIES _SSIG-COMPILE
        SBOX-COMPILER-S-OK = _SSIG-ASSERT
    _SSIG-INSPECT
    SBOX-ABI-SIGNATURE-VALUE-TO-VALUE
    1 _SSIG-ENTRY@
        SBOX-CANDIDATE-ENTRY-SIGNATURE-ID-OFFSET +
        SBOX-CANDIDATE-U32-LE!
    SBOX-VERIFIER-S-ENTRY
    SBOX-VERIFIER-D-ENTRY-SIGNATURE 1
        _SSIG-VERIFY-EXPECT

    \ Entry signature shape is checked independently of compiler output.
    _SSIG-SOURCE-ZERO-SHAPE _SSIG-COMPILE
        SBOX-COMPILER-S-OK = _SSIG-ASSERT
    _SSIG-INSPECT
    SBOX-ABI-SIGNATURE-VALUE-TO-VALUE
    0 _SSIG-ENTRY@
        SBOX-CANDIDATE-ENTRY-SIGNATURE-ID-OFFSET +
        SBOX-CANDIDATE-U32-LE!
    SBOX-VERIFIER-S-ENTRY
    SBOX-VERIFIER-D-FUNCTION-SIGNATURE 0
        _SSIG-VERIFY-EXPECT

    \ Unknown physical signatures remain closed rather than guessed.
    _SSIG-SOURCE-SCALAR _SSIG-COMPILE
        SBOX-COMPILER-S-OK = _SSIG-ASSERT
    _SSIG-INSPECT
    2 0 _SSIG-ENTRY@
        SBOX-CANDIDATE-ENTRY-SIGNATURE-ID-OFFSET +
        SBOX-CANDIDATE-U32-LE!
    SBOX-VERIFIER-S-ENTRY
    SBOX-VERIFIER-D-ENTRY-SIGNATURE 0
        _SSIG-VERIFY-EXPECT
    _SSIG-STACK ;

: _SSIG-RUN  ( -- )
    0 _SSIG-FAILS !
    0 _SSIG-CHECKS !
    DEPTH _SSIG-DEPTH !
    ." SBOX SIGNATURE CONTRACTS START" CR TX-FLUSH
    _SSIG-PROFILE SBOX-PROFILE-PURE-INIT
        SBOX-PROFILE-S-OK = _SSIG-ASSERT
    _SSIG-COMPILER-CONTRACTS
    _SSIG-PLAN-CONTRACTS
    _SSIG-VERIFIER-CONTRACTS
    _SSIG-STACK
    _SSIG-FAILS @ 0= IF
        ." SBOX SIGNATURE CONTRACTS PASS "
        _SSIG-CHECKS @ . CR TX-FLUSH
    ELSE
        ." SBOX SIGNATURE CONTRACTS FAIL "
        _SSIG-FAILS @ . CR TX-FLUSH
    THEN ;

_SSIG-RUN
