\ Focused contracts for the neutral sandbox ABI metadata layer.

PROVIDED sbox-abi-contracts

VARIABLE _SBA-FAILS
VARIABLE _SBA-CHECKS
VARIABLE _SBA-DEPTH
VARIABLE _SBA-I
VARIABLE _SBA-OPERAND
VARIABLE _SBA-EFFECT
VARIABLE _SBA-POP
VARIABLE _SBA-PUSH
VARIABLE _SBA-KIND
VARIABLE _SBA-BASE
VARIABLE _SBA-DIVISOR
VARIABLE _SBA-EXTRA

: _SBA-ASSERT  ( flag -- )
    1 _SBA-CHECKS +!
    0= IF
        1 _SBA-FAILS +!
        ." SBOX ABI ASSERT " _SBA-CHECKS @ . CR
    THEN ;

: _SBA-STACK  ( -- )
    DEPTH DUP _SBA-DEPTH @ <> IF
        ." SBOX ABI STACK " _SBA-DEPTH @ . ." -> " DUP . CR .S CR
    THEN
    _SBA-DEPTH @ = _SBA-ASSERT ;

: _SBA-ROW?
  ( opcode operand effect pop push kind base divisor extra -- flag )
    _SBA-EXTRA !
    _SBA-DIVISOR !
    _SBA-BASE !
    _SBA-KIND !
    _SBA-PUSH !
    _SBA-POP !
    _SBA-EFFECT !
    _SBA-OPERAND !
    SBOX-ABI-METADATA
    SBOX-MACHINE-S-OK = >R
    _SBA-EXTRA @ = R> AND >R
    _SBA-DIVISOR @ = R> AND >R
    _SBA-BASE @ = R> AND >R
    _SBA-KIND @ = R> AND >R
    _SBA-PUSH @ = R> AND >R
    _SBA-POP @ = R> AND >R
    _SBA-EFFECT @ = R> AND >R
    _SBA-OPERAND @ = R> AND ;

: _SBA-TYPED-ROW?
  ( opcode pop push kind base divisor extra -- flag )
    >R >R >R >R >R >R
    SBOX-MACHINE-OPERAND-NONE
    SBOX-MACHINE-EFFECT-FIXED
    R> R> R> R> R> R>
    _SBA-ROW? ;

: _SBA-SCALAR-STATUS-DELEGATED?  ( -- flag )
    0 _SBA-I !
    BEGIN _SBA-I @ 0x60 < WHILE
        _SBA-I @ SBOX-MACHINE-OPCODE-STATUS
        _SBA-I @ SBOX-ABI-OPCODE-STATUS <> IF
            0 EXIT
        THEN
        1 _SBA-I +!
    REPEAT
    -1 ;

: _SBA-QUERY?  ( value status expected -- flag )
    >R SBOX-MACHINE-S-OK = SWAP R> = AND ;

: _SBA-SCALAR-CONTRACTS  ( -- )
    _SBA-SCALAR-STATUS-DELEGATED? _SBA-ASSERT

    SBOX-MACHINE-OP-NOP
    SBOX-MACHINE-OPERAND-NONE SBOX-MACHINE-EFFECT-FIXED
    0 0 SBOX-MACHINE-COST-FIXED 1 0 SBOX-MACHINE-EXTRA-NONE
    _SBA-ROW? _SBA-ASSERT

    SBOX-MACHINE-OP-CALL
    SBOX-MACHINE-OPERAND-FUNCTION SBOX-MACHINE-EFFECT-CALL
    0 0 SBOX-MACHINE-COST-CALL-LOCALS 2 8
    SBOX-MACHINE-EXTRA-NONE _SBA-ROW? _SBA-ASSERT
    _SBA-STACK ;

: _SBA-TYPED-CONTRACTS  ( -- )
    SBOX-ABI-OP-V-TYPE
        1 1 SBOX-ABI-COST-VALUE-FIXED 2 0
        SBOX-ABI-EXTRA-VALUE-OP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-BOOL-GET
        1 1 SBOX-ABI-COST-VALUE-FIXED 2 0
        SBOX-ABI-EXTRA-VALUE-OP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-I64-GET
        1 1 SBOX-ABI-COST-VALUE-FIXED 2 0
        SBOX-ABI-EXTRA-VALUE-OP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-LEN
        1 1 SBOX-ABI-COST-VALUE-FIXED 2 0
        SBOX-ABI-EXTRA-VALUE-OP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-LIST-GET
        2 1 SBOX-ABI-COST-VALUE-FIXED 3 0
        SBOX-ABI-EXTRA-VALUE-OP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-MAP-KEY
        2 1 SBOX-ABI-COST-VALUE-FIXED 3 0
        SBOX-ABI-EXTRA-VALUE-OP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-MAP-VALUE
        2 1 SBOX-ABI-COST-VALUE-FIXED 3 0
        SBOX-ABI-EXTRA-VALUE-OP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-MAP-FIND
        3 2 SBOX-ABI-COST-VALUE-MAP 4 8
        SBOX-ABI-EXTRA-VALUE-MAP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-BLOB-COPY
        4 0 SBOX-ABI-COST-VALUE-LENGTH 4 8
        SBOX-ABI-EXTRA-VALUE-COPY _SBA-TYPED-ROW? _SBA-ASSERT

    SBOX-ABI-OP-V-NEW-NULL
        0 1 SBOX-ABI-COST-VALUE-FIXED 2 0
        SBOX-ABI-EXTRA-VALUE-OP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-NEW-BOOL
        1 1 SBOX-ABI-COST-VALUE-FIXED 2 0
        SBOX-ABI-EXTRA-VALUE-OP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-NEW-I64
        1 1 SBOX-ABI-COST-VALUE-FIXED 2 0
        SBOX-ABI-EXTRA-VALUE-OP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-NEW-BYTES
        2 1 SBOX-ABI-COST-VALUE-LENGTH 4 8
        SBOX-ABI-EXTRA-VALUE-COPY _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-NEW-UTF8
        2 1 SBOX-ABI-COST-VALUE-LENGTH 4 8
        SBOX-ABI-EXTRA-VALUE-COPY _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-NEW-LIST
        2 1 SBOX-ABI-COST-VALUE-LENGTH 4 1
        SBOX-ABI-EXTRA-VALUE-OP _SBA-TYPED-ROW? _SBA-ASSERT
    SBOX-ABI-OP-V-NEW-MAP
        2 1 SBOX-ABI-COST-VALUE-MAP 4 1
        SBOX-ABI-EXTRA-VALUE-MAP _SBA-TYPED-ROW? _SBA-ASSERT
    _SBA-STACK ;

: _SBA-ACCESSOR-CONTRACTS  ( -- )
    SBOX-ABI-OP-V-MAP-FIND SBOX-ABI-OPERAND@
        SBOX-MACHINE-OPERAND-NONE _SBA-QUERY? _SBA-ASSERT
    SBOX-ABI-OP-V-MAP-FIND SBOX-ABI-EFFECT@
        SBOX-MACHINE-EFFECT-FIXED _SBA-QUERY? _SBA-ASSERT
    SBOX-ABI-OP-V-MAP-FIND SBOX-ABI-POP@
        3 _SBA-QUERY? _SBA-ASSERT
    SBOX-ABI-OP-V-MAP-FIND SBOX-ABI-PUSH@
        2 _SBA-QUERY? _SBA-ASSERT
    SBOX-ABI-OP-V-MAP-FIND SBOX-ABI-COST-KIND@
        SBOX-ABI-COST-VALUE-MAP _SBA-QUERY? _SBA-ASSERT
    SBOX-ABI-OP-V-MAP-FIND SBOX-ABI-BASE-COST@
        4 _SBA-QUERY? _SBA-ASSERT
    SBOX-ABI-OP-V-MAP-FIND SBOX-ABI-COST-DIVISOR@
        8 _SBA-QUERY? _SBA-ASSERT
    SBOX-ABI-OP-V-MAP-FIND SBOX-ABI-EXTRA-CHARGE@
        SBOX-ABI-EXTRA-VALUE-MAP _SBA-QUERY? _SBA-ASSERT
    _SBA-STACK ;

: _SBA-UNKNOWN-CONTRACTS  ( -- )
    0x5F SBOX-ABI-OPCODE-SUPPORTED? 0= _SBA-ASSERT
    0x69 SBOX-ABI-OPCODE-SUPPORTED? 0= _SBA-ASSERT
    0x6F SBOX-ABI-OPCODE-SUPPORTED? 0= _SBA-ASSERT
    0x77 SBOX-ABI-OPCODE-SUPPORTED? 0= _SBA-ASSERT
    0xFF SBOX-ABI-OPCODE-STATUS
        SBOX-MACHINE-S-UNKNOWN-OPCODE = _SBA-ASSERT
    -1 SBOX-ABI-OPCODE-STATUS
        SBOX-MACHINE-S-UNKNOWN-OPCODE = _SBA-ASSERT
    0x69 SBOX-ABI-POP@
        SBOX-MACHINE-S-UNKNOWN-OPCODE = SWAP 0= AND _SBA-ASSERT
    SBOX-ABI-SIGNATURE-VALUE-TO-VALUE 1 = _SBA-ASSERT
    _SBA-STACK ;

: _SBA-RUN  ( -- )
    0 _SBA-FAILS !
    0 _SBA-CHECKS !
    DEPTH _SBA-DEPTH !
    ." SBOX ABI CONTRACTS START" CR
    _SBA-SCALAR-CONTRACTS
    _SBA-TYPED-CONTRACTS
    _SBA-ACCESSOR-CONTRACTS
    _SBA-UNKNOWN-CONTRACTS
    _SBA-STACK
    _SBA-FAILS @ 0= IF
        ." SBOX ABI CONTRACTS PASS " _SBA-CHECKS @ . CR
    ELSE
        ." SBOX ABI CONTRACTS FAIL " _SBA-FAILS @ . CR
    THEN ;

_SBA-RUN
