\ Focused contracts for the trusted Stage 2 canonical schema boundary.

PROVIDED sbox-schema-contracts

VARIABLE _SSC-FAILS
VARIABLE _SSC-CHECKS
VARIABLE _SSC-DEPTH

8    CONSTANT _SSC-WORK-DEPTH
1776 CONSTANT _SSC-WORK-BYTES
2    CONSTANT _SSC-SHALLOW-DEPTH
528  CONSTANT _SSC-SHALLOW-WORK-BYTES

: _SSC-ALIGN8  ( address -- aligned-address ) 7 + -8 AND ;

CREATE _SSC-WORK-RAW _SSC-WORK-BYTES 7 + ALLOT
_SSC-WORK-RAW _SSC-ALIGN8 CONSTANT _SSC-WORK
CREATE _SSC-SHALLOW-WORK-RAW _SSC-SHALLOW-WORK-BYTES 7 + ALLOT
_SSC-SHALLOW-WORK-RAW _SSC-ALIGN8 CONSTANT _SSC-SHALLOW-WORK

CREATE _SSC-SCHEMA 256 ALLOT
CREATE _SSC-SCHEMA-COPY 256 ALLOT
CREATE _SSC-VALUE-OK 128 ALLOT
CREATE _SSC-VALUE-MISSING 32 ALLOT
CREATE _SSC-VALUE-WRONG-TYPE 128 ALLOT
CREATE _SSC-VALUE-MALFORMED 128 ALLOT
CREATE _SSC-VALUE-UNKNOWN 128 ALLOT
CREATE _SSC-VALUE-LONG 128 ALLOT
CREATE _SSC-VALUE-DUPLICATE 160 ALLOT
CREATE _SSC-VALUE-LIST 192 ALLOT
CREATE _SSC-VALUE-LIST-TOO-MANY 192 ALLOT

: _SSC-ASSERT  ( flag -- )
    1 _SSC-CHECKS +!
    0= IF
        1 _SSC-FAILS +!
        ." SBOX SCHEMA ASSERT " _SSC-CHECKS @ . CR
    THEN ;

: _SSC-STACK  ( -- )
    DEPTH DUP _SSC-DEPTH @ <> IF
        ." SBOX SCHEMA STACK " _SSC-DEPTH @ . ." -> " DUP . CR
        .S CR
    THEN
    _SSC-DEPTH @ = _SSC-ASSERT ;

: _SSC-U16!  ( value address -- )
    >R
    DUP R@ C!
    8 RSHIFT R@ 1+ C!
    R> DROP ;

: _SSC-U32!  ( value address -- )
    >R
    DUP R@ C!
    DUP 8 RSHIFT R@ 1+ C!
    DUP 16 RSHIFT R@ 2 + C!
    24 RSHIFT R@ 3 + C!
    R> DROP ;

: _SSC-U64!  ( value address -- )
    >R
    DUP R@ C!
    DUP 8 RSHIFT R@ 1+ C!
    DUP 16 RSHIFT R@ 2 + C!
    DUP 24 RSHIFT R@ 3 + C!
    DUP 32 RSHIFT R@ 4 + C!
    DUP 40 RSHIFT R@ 5 + C!
    DUP 48 RSHIFT R@ 6 + C!
    56 RSHIFT R@ 7 + C!
    R> DROP ;

: _SSC-DOCUMENT!
  ( node-count max-depth total-bytes address -- )
    >R
    R@ SBOX-SCHEMA-DOCUMENT-HEADER-SIZE 0 FILL
    SBOX-SCHEMA-DOCUMENT-MAGIC R@ _SSC-U64!
    SBOX-SCHEMA-DOCUMENT-VERSION R@ 8 + _SSC-U16!
    2 PICK R@ 12 + _SSC-U32!
    OVER R@ 16 + _SSC-U32!
    DUP R@ 24 + _SSC-U64!
    2DROP DROP R> DROP ;

: _SSC-SCHEMA-NODE!
  ( tag count lower upper payload-u address -- )
    >R
    R@ SBOX-SCHEMA-NODE-HEADER-SIZE 0 FILL
    4 PICK R@ C!
    3 PICK R@ 4 + _SSC-U32!
    2 PICK R@ 8 + _SSC-U64!
    OVER R@ 16 + _SSC-U64!
    DUP R@ 24 + _SSC-U64!
    2DROP 2DROP DROP R> DROP ;

: _SSC-FIELD!
  ( key-u flags child-schema-u address -- )
    >R
    R@ SBOX-SCHEMA-FIELD-HEADER-SIZE 0 FILL
    2 PICK R@ _SSC-U32!
    OVER R@ 4 + C!
    DUP R@ 8 + _SSC-U64!
    2DROP DROP R> DROP ;

: _SSC-VALUE-HEADER!  ( tag count payload-u address -- )
    >R
    R@ 16 0 FILL
    2 PICK R@ C!
    OVER R@ 4 + _SSC-U32!
    DUP R@ 8 + _SSC-U64!
    2DROP DROP R> DROP ;

: _SSC-BYTES!  ( source source-u target -- )
    SWAP CMOVE ;

: _SSC-BUILD-SCHEMA  ( -- )
    _SSC-SCHEMA 256 0 FILL
    4 3 202 _SSC-SCHEMA _SSC-DOCUMENT!

    \ Closed root MAP:
    \   required "name": UTF8[1,8]
    \   optional "scores": LIST[0,2] of I64
    SBOX-SCHEMA-T-MAP 2 0 0 138
        _SSC-SCHEMA 32 + _SSC-SCHEMA-NODE!

    4 SBOX-SCHEMA-FIELD-F-REQUIRED 32
        _SSC-SCHEMA 64 + _SSC-FIELD!
    S" name" _SSC-SCHEMA 80 + _SSC-BYTES!
    SBOX-SCHEMA-T-UTF8 0 1 8 0
        _SSC-SCHEMA 84 + _SSC-SCHEMA-NODE!

    6 SBOX-SCHEMA-FIELD-F-OPTIONAL 64
        _SSC-SCHEMA 116 + _SSC-FIELD!
    S" scores" _SSC-SCHEMA 132 + _SSC-BYTES!
    SBOX-SCHEMA-T-LIST 1 0 2 32
        _SSC-SCHEMA 138 + _SSC-SCHEMA-NODE!
    SBOX-SCHEMA-T-I64 0 0 0 0
        _SSC-SCHEMA 170 + _SSC-SCHEMA-NODE! ;

: _SSC-WRITE-NAME-KEY  ( address -- )
    >R
    SBOX-SCHEMA-T-UTF8 0 4 R@ _SSC-VALUE-HEADER!
    S" name" R@ 16 + _SSC-BYTES!
    R> DROP ;

: _SSC-BUILD-VALUE-OK  ( -- )
    _SSC-VALUE-OK 128 0 FILL
    SBOX-SCHEMA-T-MAP 1 39 _SSC-VALUE-OK _SSC-VALUE-HEADER!
    _SSC-VALUE-OK 16 + _SSC-WRITE-NAME-KEY
    SBOX-SCHEMA-T-UTF8 0 3
        _SSC-VALUE-OK 36 + _SSC-VALUE-HEADER!
    S" Ada" _SSC-VALUE-OK 52 + _SSC-BYTES! ;

: _SSC-BUILD-VALUE-MISSING  ( -- )
    _SSC-VALUE-MISSING 32 0 FILL
    SBOX-SCHEMA-T-MAP 0 0
        _SSC-VALUE-MISSING _SSC-VALUE-HEADER! ;

: _SSC-BUILD-VALUE-WRONG-TYPE  ( -- )
    _SSC-VALUE-WRONG-TYPE 128 0 FILL
    SBOX-SCHEMA-T-MAP 1 44
        _SSC-VALUE-WRONG-TYPE _SSC-VALUE-HEADER!
    _SSC-VALUE-WRONG-TYPE 16 + _SSC-WRITE-NAME-KEY
    SBOX-SCHEMA-T-BOOL 0 8
        _SSC-VALUE-WRONG-TYPE 36 + _SSC-VALUE-HEADER!
    -1 _SSC-VALUE-WRONG-TYPE 52 + _SSC-U64! ;

: _SSC-BUILD-VALUE-MALFORMED  ( -- )
    _SSC-VALUE-WRONG-TYPE _SSC-VALUE-MALFORMED 60 MOVE
    1 _SSC-VALUE-MALFORMED 52 + _SSC-U64! ;

: _SSC-BUILD-VALUE-UNKNOWN  ( -- )
    _SSC-VALUE-UNKNOWN 128 0 FILL
    SBOX-SCHEMA-T-MAP 1 37
        _SSC-VALUE-UNKNOWN _SSC-VALUE-HEADER!
    SBOX-SCHEMA-T-UTF8 0 5
        _SSC-VALUE-UNKNOWN 16 + _SSC-VALUE-HEADER!
    S" other" _SSC-VALUE-UNKNOWN 32 + _SSC-BYTES!
    SBOX-SCHEMA-T-NULL 0 0
        _SSC-VALUE-UNKNOWN 37 + _SSC-VALUE-HEADER! ;

: _SSC-BUILD-VALUE-LONG  ( -- )
    _SSC-VALUE-LONG 128 0 FILL
    SBOX-SCHEMA-T-MAP 1 45
        _SSC-VALUE-LONG _SSC-VALUE-HEADER!
    _SSC-VALUE-LONG 16 + _SSC-WRITE-NAME-KEY
    SBOX-SCHEMA-T-UTF8 0 9
        _SSC-VALUE-LONG 36 + _SSC-VALUE-HEADER!
    S" Alexander" _SSC-VALUE-LONG 52 + _SSC-BYTES! ;

: _SSC-BUILD-VALUE-DUPLICATE  ( -- )
    _SSC-VALUE-DUPLICATE 160 0 FILL
    SBOX-SCHEMA-T-MAP 2 78
        _SSC-VALUE-DUPLICATE _SSC-VALUE-HEADER!
    _SSC-VALUE-OK 16 + _SSC-VALUE-DUPLICATE 16 + 39 MOVE
    _SSC-VALUE-OK 16 + _SSC-VALUE-DUPLICATE 55 + 39 MOVE ;

: _SSC-WRITE-SCORES-KEY  ( address -- )
    >R
    SBOX-SCHEMA-T-UTF8 0 6 R@ _SSC-VALUE-HEADER!
    S" scores" R@ 16 + _SSC-BYTES!
    R> DROP ;

: _SSC-WRITE-I64  ( value address -- )
    >R
    SBOX-SCHEMA-T-I64 0 8 R@ _SSC-VALUE-HEADER!
    R@ 16 + _SSC-U64!
    R> DROP ;

: _SSC-BUILD-VALUE-LIST  ( -- )
    _SSC-VALUE-LIST 192 0 FILL
    SBOX-SCHEMA-T-MAP 2 125
        _SSC-VALUE-LIST _SSC-VALUE-HEADER!
    _SSC-VALUE-OK 16 + _SSC-VALUE-LIST 16 + 39 MOVE
    _SSC-VALUE-LIST 55 + _SSC-WRITE-SCORES-KEY
    SBOX-SCHEMA-T-LIST 2 48
        _SSC-VALUE-LIST 77 + _SSC-VALUE-HEADER!
    7 _SSC-VALUE-LIST 93 + _SSC-WRITE-I64
    11 _SSC-VALUE-LIST 117 + _SSC-WRITE-I64 ;

: _SSC-BUILD-VALUE-LIST-TOO-MANY  ( -- )
    _SSC-VALUE-LIST-TOO-MANY 192 0 FILL
    SBOX-SCHEMA-T-MAP 2 149
        _SSC-VALUE-LIST-TOO-MANY _SSC-VALUE-HEADER!
    _SSC-VALUE-OK 16 + _SSC-VALUE-LIST-TOO-MANY 16 + 39 MOVE
    _SSC-VALUE-LIST-TOO-MANY 55 + _SSC-WRITE-SCORES-KEY
    SBOX-SCHEMA-T-LIST 3 72
        _SSC-VALUE-LIST-TOO-MANY 77 + _SSC-VALUE-HEADER!
    7 _SSC-VALUE-LIST-TOO-MANY 93 + _SSC-WRITE-I64
    11 _SSC-VALUE-LIST-TOO-MANY 117 + _SSC-WRITE-I64
    13 _SSC-VALUE-LIST-TOO-MANY 141 + _SSC-WRITE-I64 ;

: _SSC-BUILD-FIXTURES  ( -- )
    _SSC-BUILD-SCHEMA
    _SSC-BUILD-VALUE-OK
    _SSC-BUILD-VALUE-MISSING
    _SSC-BUILD-VALUE-WRONG-TYPE
    _SSC-BUILD-VALUE-MALFORMED
    _SSC-BUILD-VALUE-UNKNOWN
    _SSC-BUILD-VALUE-LONG
    _SSC-BUILD-VALUE-DUPLICATE
    _SSC-BUILD-VALUE-LIST
    _SSC-BUILD-VALUE-LIST-TOO-MANY ;

: _SSC-WORKSPACE-CONTRACTS  ( -- )
    _SSC-WORK-DEPTH SBOX-SCHEMA-WORKSPACE-MEASURE
        SBOX-SCHEMA-S-OK =
        SWAP _SSC-WORK-BYTES = AND _SSC-ASSERT
    0 SBOX-SCHEMA-WORKSPACE-MEASURE
        SBOX-SCHEMA-S-INVALID = SWAP 0= AND _SSC-ASSERT

    _SSC-WORK-DEPTH _SSC-WORK _SSC-WORK-BYTES
        SBOX-SCHEMA-WORKSPACE-INIT
        SBOX-SCHEMA-S-OK = _SSC-ASSERT
    _SSC-WORK SBOX-SCHEMA-WORKSPACE-VALID?
        _SSC-ASSERT
    _SSC-WORK SBOX-SCHEMA-WORKSPACE-MAX-DEPTH@
        _SSC-WORK-DEPTH = _SSC-ASSERT

    _SSC-SHALLOW-DEPTH _SSC-SHALLOW-WORK
        _SSC-SHALLOW-WORK-BYTES SBOX-SCHEMA-WORKSPACE-INIT
        SBOX-SCHEMA-S-OK = _SSC-ASSERT
    _SSC-SHALLOW-WORK SBOX-SCHEMA-WORKSPACE-VALID?
        _SSC-ASSERT
    _SSC-STACK ;

: _SSC-SCHEMA-CONTRACTS  ( -- )
    _SSC-SCHEMA 202 _SSC-WORK SBOX-SCHEMA-VALIDATE
        SBOX-SCHEMA-S-OK = _SSC-ASSERT
    _SSC-WORK SBOX-SCHEMA-WORKSPACE-SCHEMA-NODES@
        4 = _SSC-ASSERT
    _SSC-WORK SBOX-SCHEMA-WORKSPACE-SCHEMA-DEPTH@
        3 = _SSC-ASSERT

    \ Canonical bytes are relocatable data, not a self-bound native object.
    _SSC-SCHEMA _SSC-SCHEMA-COPY 202 MOVE
    _SSC-SCHEMA-COPY 202 _SSC-WORK SBOX-SCHEMA-VALIDATE
        SBOX-SCHEMA-S-OK = _SSC-ASSERT

    \ Complete-span validation rejects a trailing byte.
    _SSC-SCHEMA 203 _SSC-WORK SBOX-SCHEMA-VALIDATE
        SBOX-SCHEMA-S-MALFORMED-SCHEMA = _SSC-ASSERT

    \ Required/optional is a closed exact flag, not an extensible bitmap.
    _SSC-SCHEMA _SSC-SCHEMA-COPY 202 MOVE
    3 _SSC-SCHEMA-COPY 120 + C!
    _SSC-SCHEMA-COPY 202 _SSC-WORK SBOX-SCHEMA-VALIDATE
        SBOX-SCHEMA-S-MALFORMED-SCHEMA = _SSC-ASSERT

    \ Field keys must be strictly sorted by raw UTF-8 bytes.
    _SSC-SCHEMA _SSC-SCHEMA-COPY 202 MOVE
    [CHAR] z _SSC-SCHEMA-COPY 80 + C!
    _SSC-SCHEMA-COPY 202 _SSC-WORK SBOX-SCHEMA-VALIDATE
        SBOX-SCHEMA-S-MALFORMED-SCHEMA = _SSC-ASSERT

    \ Declared depth above caller workspace is a capacity result.
    _SSC-SCHEMA 202 _SSC-SHALLOW-WORK SBOX-SCHEMA-VALIDATE
        SBOX-SCHEMA-S-CAPACITY = _SSC-ASSERT
    _SSC-STACK ;

: _SSC-VALUE-CONTRACTS  ( -- )
    _SSC-SCHEMA 202 _SSC-VALUE-OK 55 _SSC-WORK
        SBOX-SCHEMA-VALUE-VALIDATE
        SBOX-SCHEMA-S-OK = _SSC-ASSERT
    _SSC-WORK SBOX-SCHEMA-WORKSPACE-VALUE-NODES@
        3 = _SSC-ASSERT
    _SSC-WORK SBOX-SCHEMA-WORKSPACE-VALUE-DEPTH@
        2 = _SSC-ASSERT

    _SSC-SCHEMA 202 _SSC-VALUE-MISSING 16 _SSC-WORK
        SBOX-SCHEMA-VALUE-VALIDATE
        SBOX-SCHEMA-S-VALUE-MISMATCH = _SSC-ASSERT
    _SSC-SCHEMA 202 _SSC-VALUE-WRONG-TYPE 60 _SSC-WORK
        SBOX-SCHEMA-VALUE-VALIDATE
        SBOX-SCHEMA-S-VALUE-MISMATCH = _SSC-ASSERT
    _SSC-SCHEMA 202 _SSC-VALUE-UNKNOWN 53 _SSC-WORK
        SBOX-SCHEMA-VALUE-VALIDATE
        SBOX-SCHEMA-S-VALUE-MISMATCH = _SSC-ASSERT
    _SSC-SCHEMA 202 _SSC-VALUE-LONG 61 _SSC-WORK
        SBOX-SCHEMA-VALUE-VALIDATE
        SBOX-SCHEMA-S-VALUE-MISMATCH = _SSC-ASSERT
    _SSC-SCHEMA 202 _SSC-VALUE-LIST 141 _SSC-WORK
        SBOX-SCHEMA-VALUE-VALIDATE
        SBOX-SCHEMA-S-OK = _SSC-ASSERT
    _SSC-SCHEMA 202 _SSC-VALUE-LIST-TOO-MANY 165 _SSC-WORK
        SBOX-SCHEMA-VALUE-VALIDATE
        SBOX-SCHEMA-S-VALUE-MISMATCH = _SSC-ASSERT

    \ Independent value validation wins over an obvious schema mismatch.
    _SSC-SCHEMA 202 _SSC-VALUE-MALFORMED 60 _SSC-WORK
        SBOX-SCHEMA-VALUE-VALIDATE
        SBOX-SCHEMA-S-MALFORMED-VALUE = _SSC-ASSERT
    _SSC-SCHEMA 202 _SSC-VALUE-DUPLICATE 94 _SSC-WORK
        SBOX-SCHEMA-VALUE-VALIDATE
        SBOX-SCHEMA-S-MALFORMED-VALUE = _SSC-ASSERT
    _SSC-STACK ;

: _SSC-STATUS-CONTRACTS  ( -- )
    SBOX-SCHEMA-S-OK SBOX-SCHEMA-STATUS-VALID? _SSC-ASSERT
    SBOX-SCHEMA-S-MALFORMED-SCHEMA
        SBOX-SCHEMA-STATUS-VALID? _SSC-ASSERT
    SBOX-SCHEMA-S-MALFORMED-VALUE
        SBOX-SCHEMA-STATUS-VALID? _SSC-ASSERT
    SBOX-SCHEMA-S-VALUE-MISMATCH
        SBOX-SCHEMA-STATUS-VALID? _SSC-ASSERT
    -1 SBOX-SCHEMA-STATUS-VALID? 0= _SSC-ASSERT
    10 SBOX-SCHEMA-STATUS-VALID? 0= _SSC-ASSERT
    _SSC-STACK ;

: _SSC-RUN  ( -- )
    0 _SSC-FAILS !
    0 _SSC-CHECKS !
    DEPTH _SSC-DEPTH !
    ." SBOX SCHEMA CONTRACTS START" CR
    _SSC-BUILD-FIXTURES
    _SSC-WORKSPACE-CONTRACTS
    _SSC-SCHEMA-CONTRACTS
    _SSC-VALUE-CONTRACTS
    _SSC-STATUS-CONTRACTS
    _SSC-STACK
    _SSC-FAILS @ 0= IF
        ." SBOX SCHEMA CONTRACTS PASS " _SSC-CHECKS @ . CR
    ELSE
        ." SBOX SCHEMA CONTRACTS FAIL " _SSC-FAILS @ . CR
    THEN ;

[DEFINED] SBOX-SCHEMA-DEFER-AUTORUN [IF]
[ELSE]
    _SSC-RUN
[THEN]
