\ Focused end-to-end contracts for the pure Stage 1 sandbox runtime.

PROVIDED sbox-stage1-contracts

VARIABLE _S1-FAILS
VARIABLE _S1-CHECKS
VARIABLE _S1-DEPTH
VARIABLE _S1-BYTE
VARIABLE _S1-CANDIDATE-U
VARIABLE _S1-PLAN-U
VARIABLE _S1-INSTANCE-U
VARIABLE _S1-RECORD
VARIABLE _S1-HOT-START

8192 CONSTANT _S1-CANDIDATE-CAP
8448 CONSTANT _S1-PLAN-CAP
65536 CONSTANT _S1-INSTANCE-CAP

: _S1-ALIGN8  ( address -- aligned-address ) 7 + -8 AND ;

CREATE _S1-PROFILE-RAW SBOX-PROFILE-SIZE 7 + ALLOT
_S1-PROFILE-RAW _S1-ALIGN8 CONSTANT _S1-PROFILE
CREATE _S1-CANDIDATE-RAW _S1-CANDIDATE-CAP 7 + ALLOT
_S1-CANDIDATE-RAW _S1-ALIGN8 CONSTANT _S1-CANDIDATE
CREATE _S1-LAYOUT-RAW SBOX-CANDIDATE-LAYOUT-SIZE 7 + ALLOT
_S1-LAYOUT-RAW _S1-ALIGN8 CONSTANT _S1-LAYOUT
CREATE _S1-PLAN-RAW _S1-PLAN-CAP 7 + ALLOT
_S1-PLAN-RAW _S1-ALIGN8 CONSTANT _S1-PLAN
CREATE _S1-BINDING-RAW SBOX-BINDING-SIZE 7 + ALLOT
_S1-BINDING-RAW _S1-ALIGN8 CONSTANT _S1-BINDING
CREATE _S1-COMPILER-WORK-RAW SBOX-COMPILER-WORKSPACE-SIZE 7 + ALLOT
_S1-COMPILER-WORK-RAW _S1-ALIGN8 CONSTANT _S1-COMPILER-WORK
CREATE _S1-VERIFIER-WORK-RAW SBOX-VERIFIER-WORKSPACE-SIZE 7 + ALLOT
_S1-VERIFIER-WORK-RAW _S1-ALIGN8 CONSTANT _S1-VERIFIER-WORK
CREATE _S1-INSTANCE-A-RAW _S1-INSTANCE-CAP 7 + ALLOT
_S1-INSTANCE-A-RAW _S1-ALIGN8 CONSTANT _S1-INSTANCE-A
CREATE _S1-INSTANCE-B-RAW _S1-INSTANCE-CAP 7 + ALLOT
_S1-INSTANCE-B-RAW _S1-ALIGN8 CONSTANT _S1-INSTANCE-B
CREATE _S1-RESULT-A-RAW SBOX-VM-RESULT-SIZE 7 + ALLOT
_S1-RESULT-A-RAW _S1-ALIGN8 CONSTANT _S1-RESULT-A
CREATE _S1-RESULT-B-RAW SBOX-VM-RESULT-SIZE 7 + ALLOT
_S1-RESULT-B-RAW _S1-ALIGN8 CONSTANT _S1-RESULT-B
CREATE _S1-INPUT-A-RAW 23 ALLOT
_S1-INPUT-A-RAW _S1-ALIGN8 CONSTANT _S1-INPUT-A
CREATE _S1-INPUT-B-RAW 23 ALLOT
_S1-INPUT-B-RAW _S1-ALIGN8 CONSTANT _S1-INPUT-B

: _S1-ASSERT  ( flag -- )
    1 _S1-CHECKS +!
    0= IF
        1 _S1-FAILS +!
        ." SBOX STAGE1 ASSERT " _S1-CHECKS @ . CR TX-FLUSH
    THEN ;

: _S1-STACK  ( -- )
    DEPTH DUP _S1-DEPTH @ <> IF
        ." SBOX STAGE1 STACK " _S1-DEPTH @ . ." -> " DUP . CR
        .S CR
        TX-FLUSH
    THEN
    _S1-DEPTH @ = _S1-ASSERT ;

: _S1-FILLED?  ( address length byte -- flag )
    _S1-BYTE !
    0 ?DO
        DUP I + C@ _S1-BYTE @ <> IF
            DROP 0 UNLOOP EXIT
        THEN
    LOOP
    DROP -1 ;

: _S1-ZERO-CELLS?  ( address length -- flag )
    DUP 7 AND IF 2DROP 0 EXIT THEN
    8 / 0 ?DO
        DUP @ IF DROP 0 UNLOOP EXIT THEN
        8 +
    LOOP
    DROP -1 ;

: _S1-SOURCE-ADD  ( -- address length )
    S" FUNCTION add PARAMS 2 RESULTS 1 LOCALS 0 I64.ADD RETURN END ENTRY main add" ;

: _S1-SOURCE-BAD-STACK  ( -- address length )
    S" FUNCTION bad PARAMS 0 RESULTS 0 LOCALS 0 DROP RETURN END ENTRY main bad" ;

: _S1-SOURCE-BAD-TOKEN  ( -- address length )
    S" FUNCTION bad PARAMS 0 RESULTS 0 LOCALS 0 EVALUATE RETURN END ENTRY main bad" ;

: _S1-SOURCE-FORWARD-CALL  ( -- address length )
    S" FUNCTION primary PARAMS 1 RESULTS 1 LOCALS 0 CALL helper RETURN END FUNCTION helper PARAMS 1 RESULTS 1 LOCALS 0 2 I64.MUL RETURN END ENTRY main primary" ;

: _S1-SOURCE-CONTROL  ( -- address length )
    S" FUNCTION control PARAMS 1 RESULTS 1 LOCALS 0 DUP IF 10 I64.ADD ELSE 20 I64.ADD THEN RETURN END ENTRY main control" ;

: _S1-SOURCE-WHILE  ( -- address length )
    S" FUNCTION count PARAMS 0 RESULTS 1 LOCALS 1 0 LOCAL.SET 0 BEGIN LOCAL.GET 0 3 I64.LT.S WHILE LOCAL.GET 0 I64.INC LOCAL.SET 0 REPEAT LOCAL.GET 0 RETURN END ENTRY main count" ;

: _S1-SOURCE-LOOPS  ( -- address length )
    S" FUNCTION loops PARAMS 0 RESULTS 1 LOCALS 1 0 LOCAL.SET 0 3 0 DO 2 0 DO R LOCAL.GET 0 I64.ADD LOCAL.SET 0 LOOP R LOCAL.GET 0 I64.ADD LOCAL.SET 0 LOOP LOCAL.GET 0 RETURN END ENTRY main loops" ;

: _S1-SOURCE-MIN-I64  ( -- address length )
    S" FUNCTION edge PARAMS 0 RESULTS 1 LOCALS 0 -9223372036854775808 RETURN END ENTRY main edge" ;

: _S1-SOURCE-OVERFLOW-I64  ( -- address length )
    S" FUNCTION edge PARAMS 0 RESULTS 1 LOCALS 0 9223372036854775808 RETURN END ENTRY main edge" ;

: _S1-SOURCE-SPIN  ( -- address length )
    S" FUNCTION spin PARAMS 0 RESULTS 0 LOCALS 0 BEGIN NOP AGAIN END ENTRY main spin" ;

: _S1-SOURCE-MEMORY  ( -- address length )
    S" FUNCTION memory PARAMS 0 RESULTS 1 LOCALS 0 42 0 MEM.STORE8 0 MEM.LOAD8.U RETURN END ENTRY main memory" ;

: _S1-SOURCE-DIVIDE-ZERO  ( -- address length )
    S" FUNCTION divide PARAMS 0 RESULTS 1 LOCALS 0 7 0 I64.DIV.S RETURN END ENTRY main divide" ;

: _S1-SOURCE-DEAD-CODE  ( -- address length )
    S" FUNCTION dead PARAMS 0 RESULTS 0 LOCALS 0 NOP NOP RETURN END ENTRY main dead" ;

: _S1-SOURCE-WRONG-RETURN  ( -- address length )
    S" FUNCTION wrong PARAMS 0 RESULTS 1 LOCALS 0 1 RETURN END ENTRY main wrong" ;

: _S1-COMPILE  ( source source-u memory-u -- status )
    >R
    _S1-CANDIDATE _S1-CANDIDATE-CAP 0xA5 FILL
    _S1-PROFILE
    R>
    _S1-CANDIDATE _S1-CANDIDATE-CAP
    _S1-COMPILER-WORK
    SBOX-COMPILE
    SWAP _S1-CANDIDATE-U ! ;

: _S1-VERIFY  ( -- status )
    _S1-CANDIDATE-U @ SBOX-PLAN-MEASURE
    DUP IF
        >R DROP 0 _S1-PLAN-U ! R> EXIT
    THEN
    DROP
    DUP _S1-PLAN-U !
    >R
    _S1-CANDIDATE _S1-CANDIDATE-U @
    _S1-PROFILE
    _S1-PLAN R>
    _S1-VERIFIER-WORK
    SBOX-VERIFY ;

: _S1-COMPILER-FAILURE-CONTRACTS  ( -- )
    _S1-COMPILER-WORK SBOX-COMPILER-WORKSPACE-SIZE 0x5A FILL
    _S1-SOURCE-BAD-TOKEN 64 _S1-COMPILE
        SBOX-COMPILER-S-SOURCE = _S1-ASSERT
    _S1-CANDIDATE-U @ 0= _S1-ASSERT
    _S1-CANDIDATE _S1-CANDIDATE-CAP 0xA5
        _S1-FILLED? _S1-ASSERT
    _S1-COMPILER-WORK SBOX-COMPILER-WORKSPACE-SIZE
        _S1-ZERO-CELLS? _S1-ASSERT

    _S1-SOURCE-OVERFLOW-I64 64 _S1-COMPILE
        SBOX-COMPILER-S-SOURCE = _S1-ASSERT
    _S1-CANDIDATE-U @ 0= _S1-ASSERT
    _S1-CANDIDATE _S1-CANDIDATE-CAP 0xA5
        _S1-FILLED? _S1-ASSERT
    _S1-STACK ;

: _S1-COMPILE-VERIFY-ONE
  ( source source-u memory-u -- )
    _S1-COMPILE SBOX-COMPILER-S-OK = _S1-ASSERT
    _S1-CANDIDATE-U @ SBOX-CANDIDATE-HEADER-SIZE >
        _S1-ASSERT
    _S1-VERIFY SBOX-VERIFIER-S-OK = _S1-ASSERT
    _S1-PLAN SBOX-PLAN-VALID? _S1-ASSERT ;

: _S1-COMPILER-VERIFIER-CONTRACTS  ( -- )
    _S1-COMPILER-WORK SBOX-COMPILER-WORKSPACE-SIZE 0x5A FILL
    _S1-SOURCE-ADD 64 _S1-COMPILE-VERIFY-ONE
    _S1-COMPILER-WORK SBOX-COMPILER-WORKSPACE-SIZE
        _S1-ZERO-CELLS? _S1-ASSERT
    _S1-PLAN SBOX-PLAN-RELEASE
        SBOX-PLAN-S-OK = _S1-ASSERT

    _S1-SOURCE-FORWARD-CALL 64 _S1-COMPILE-VERIFY-ONE
    _S1-PLAN SBOX-PLAN-RELEASE
        SBOX-PLAN-S-OK = _S1-ASSERT

    _S1-SOURCE-CONTROL 64 _S1-COMPILE-VERIFY-ONE
    _S1-PLAN SBOX-PLAN-RELEASE
        SBOX-PLAN-S-OK = _S1-ASSERT

    _S1-SOURCE-WHILE 64 _S1-COMPILE-VERIFY-ONE
    _S1-PLAN SBOX-PLAN-RELEASE
        SBOX-PLAN-S-OK = _S1-ASSERT

    _S1-SOURCE-LOOPS 64 _S1-COMPILE-VERIFY-ONE
    _S1-PLAN SBOX-PLAN-RELEASE
        SBOX-PLAN-S-OK = _S1-ASSERT

    _S1-SOURCE-MIN-I64 64 _S1-COMPILE-VERIFY-ONE
    _S1-PLAN SBOX-PLAN-RELEASE
        SBOX-PLAN-S-OK = _S1-ASSERT

    \ The compiler is deliberately not the semantic verifier.
    _S1-SOURCE-BAD-STACK 64 _S1-COMPILE
        SBOX-COMPILER-S-OK = _S1-ASSERT
    _S1-VERIFY SBOX-VERIFIER-S-STACK = _S1-ASSERT
    _S1-PLAN _S1-PLAN-U @ 0 _S1-FILLED? _S1-ASSERT
    _S1-VERIFIER-WORK SBOX-VERIFIER-ERROR-DETAIL@
        SBOX-VERIFIER-S-OK =
        SWAP SBOX-VERIFIER-D-STACK-UNDERFLOW = AND
        _S1-ASSERT
    _S1-STACK ;

: _S1-CANDIDATE-CAPACITY-CONTRACTS  ( -- )
    _S1-SOURCE-ADD 64 _S1-COMPILE
        SBOX-COMPILER-S-OK = _S1-ASSERT
    _S1-CANDIDATE-U @ DUP 0> _S1-ASSERT
    1- >R
    _S1-CANDIDATE _S1-CANDIDATE-CAP 0xA5 FILL
    _S1-SOURCE-ADD
    _S1-PROFILE 64
    _S1-CANDIDATE R>
    _S1-COMPILER-WORK
    SBOX-COMPILE
    SBOX-COMPILER-S-CAPACITY = SWAP 0= AND _S1-ASSERT
    _S1-CANDIDATE _S1-CANDIDATE-CAP 0xA5
        _S1-FILLED? _S1-ASSERT
    _S1-STACK ;

: _S1-INSPECT  ( -- )
    _S1-CANDIDATE _S1-CANDIDATE-U @ _S1-LAYOUT
    SBOX-CANDIDATE-INSPECT
        SBOX-CANDIDATE-S-OK = _S1-ASSERT ;

: _S1-FUNCTION@  ( index -- record )
    SBOX-CANDIDATE-FUNCTION-SIZE *
    _S1-CANDIDATE
    _S1-LAYOUT SBOX-CANDIDATE-LAYOUT-FUNCTIONS@ +
    + ;

: _S1-INSTRUCTION@  ( index -- record )
    SBOX-CANDIDATE-INSTRUCTION-SIZE *
    _S1-CANDIDATE
    _S1-LAYOUT SBOX-CANDIDATE-LAYOUT-INSTRUCTIONS@ +
    + ;

: _S1-FIND-OPCODE  ( opcode -- record|0 )
    _S1-CANDIDATE SBOX-CANDIDATE-INSTRUCTION-N@ 0 ?DO
        DUP
        I _S1-INSTRUCTION@
        SBOX-CANDIDATE-U16-LE@ = IF
            DROP I _S1-INSTRUCTION@ UNLOOP EXIT
        THEN
    LOOP
    DROP 0 ;

: _S1-VERIFY-EXPECT  ( expected-status expected-detail -- )
    >R >R
    _S1-PLAN _S1-PLAN-CAP 0xA5 FILL
    _S1-VERIFY R> = _S1-ASSERT
    _S1-PLAN _S1-PLAN-U @ 0 _S1-FILLED? _S1-ASSERT
    _S1-VERIFIER-WORK SBOX-VERIFIER-ERROR-DETAIL@
        SBOX-VERIFIER-S-OK =
        SWAP R> = AND _S1-ASSERT ;

: _S1-VERIFIER-RECORD-REJECTIONS  ( -- )
    \ Exact source truncation is rejected as candidate geometry.
    _S1-SOURCE-ADD 64 _S1-COMPILE
        SBOX-COMPILER-S-OK = _S1-ASSERT
    -1 _S1-CANDIDATE-U +!
    SBOX-VERIFIER-S-CANDIDATE
        SBOX-VERIFIER-D-CANDIDATE-GEOMETRY
        _S1-VERIFY-EXPECT

    \ A reserved function flag is a record error, not executable metadata.
    _S1-SOURCE-ADD 64 _S1-COMPILE
        SBOX-COMPILER-S-OK = _S1-ASSERT
    _S1-INSPECT
    1 0 _S1-FUNCTION@
        SBOX-CANDIDATE-FUNCTION-FLAGS-OFFSET +
        SBOX-CANDIDATE-U16-LE!
    SBOX-VERIFIER-S-FUNCTION
        SBOX-VERIFIER-D-FUNCTION-FLAGS
        _S1-VERIFY-EXPECT

    \ Unknown instructions never reach plan publication.
    _S1-SOURCE-ADD 64 _S1-COMPILE
        SBOX-COMPILER-S-OK = _S1-ASSERT
    _S1-INSPECT
    0x0F 0 _S1-INSTRUCTION@
        SBOX-CANDIDATE-INSTRUCTION-OPCODE-OFFSET +
        SBOX-CANDIDATE-U16-LE!
    SBOX-VERIFIER-S-OPCODE
        SBOX-VERIFIER-D-INSTRUCTION-OPCODE
        _S1-VERIFY-EXPECT

    \ A function-local branch target cannot escape its instruction range.
    _S1-SOURCE-CONTROL 64 _S1-COMPILE
        SBOX-COMPILER-S-OK = _S1-ASSERT
    _S1-INSPECT
    999 1 _S1-INSTRUCTION@
        SBOX-CANDIDATE-INSTRUCTION-A-OFFSET +
        SBOX-CANDIDATE-U32-LE!
    SBOX-VERIFIER-S-TARGET
        SBOX-VERIFIER-D-INSTRUCTION-TARGET
        _S1-VERIFY-EXPECT ;

: _S1-VERIFIER-CFG-REJECTIONS  ( -- )
    \ Removing a DO opener while leaving its canonical closer is a typed
    \ loop-structure failure.
    _S1-SOURCE-LOOPS 64 _S1-COMPILE
        SBOX-COMPILER-S-OK = _S1-ASSERT
    _S1-INSPECT
    SBOX-MACHINE-OP-LOOP-ENTER _S1-FIND-OPCODE
    DUP 0<> _S1-ASSERT
    _S1-RECORD !
    SBOX-MACHINE-OP-NOP
        _S1-RECORD @ SBOX-CANDIDATE-U16-LE!
    0 _S1-RECORD @ SBOX-CANDIDATE-INSTRUCTION-A-OFFSET +
        SBOX-CANDIDATE-U32-LE!
    0 _S1-RECORD @ SBOX-CANDIDATE-INSTRUCTION-B-OFFSET +
        SBOX-CANDIDATE-U64-LE!
    SBOX-VERIFIER-S-LOOP
        SBOX-VERIFIER-D-LOOP-INDEX
        _S1-VERIFY-EXPECT

    \ Valid branch geometry can still make an instruction unreachable.
    _S1-SOURCE-DEAD-CODE 64 _S1-COMPILE
        SBOX-COMPILER-S-OK = _S1-ASSERT
    _S1-INSPECT
    SBOX-MACHINE-OP-BR 0 _S1-INSTRUCTION@
        SBOX-CANDIDATE-U16-LE!
    2 0 _S1-INSTRUCTION@
        SBOX-CANDIDATE-INSTRUCTION-A-OFFSET +
        SBOX-CANDIDATE-U32-LE!
    SBOX-VERIFIER-S-UNREACHABLE
        SBOX-VERIFIER-D-UNREACHABLE
        _S1-VERIFY-EXPECT

    \ A structurally valid function must still return its declared height.
    _S1-SOURCE-WRONG-RETURN 64 _S1-COMPILE
        SBOX-COMPILER-S-OK = _S1-ASSERT
    _S1-INSPECT
    SBOX-MACHINE-OP-NOP 0 _S1-INSTRUCTION@
        SBOX-CANDIDATE-U16-LE!
    0 0 _S1-INSTRUCTION@
        SBOX-CANDIDATE-INSTRUCTION-B-OFFSET +
        SBOX-CANDIDATE-U64-LE!
    SBOX-VERIFIER-S-STACK
        SBOX-VERIFIER-D-STACK-RETURN
        _S1-VERIFY-EXPECT ;

: _S1-VERIFIER-REJECTION-CONTRACTS  ( -- )
    _S1-VERIFIER-RECORD-REJECTIONS
    _S1-VERIFIER-CFG-REJECTIONS
    _S1-STACK ;

\ ---------------------------------------------------------------------
\ VM execution and lifecycle contracts
\ ---------------------------------------------------------------------

: _S1-VM-PREPARE  ( source source-u memory-u -- )
    _S1-COMPILE-VERIFY-ONE
    _S1-PLAN _S1-BINDING SBOX-BINDING-PURE-INIT
        SBOX-BINDING-S-OK = _S1-ASSERT
    _S1-PLAN _S1-BINDING SBOX-BINDING-VALID-FOR?
        _S1-ASSERT
    _S1-PLAN SBOX-VM-INSTANCE-MEASURE
    SBOX-VM-S-OK = _S1-ASSERT
    DUP 0> _S1-ASSERT
    DUP _S1-INSTANCE-CAP <= _S1-ASSERT
    _S1-INSTANCE-U ! ;

: _S1-VM-INIT-ONE
  ( input input-n budget instance -- status )
    DUP _S1-INSTANCE-U @ 0xA5 FILL
    >R >R >R >R
    _S1-PLAN _S1-BINDING 0
    R> R> R> R>
    _S1-INSTANCE-U @
    _SVM-SCALAR-INIT ;

: _S1-INSTANCE-RELEASE-ONE  ( instance -- )
    DUP SBOX-VM-RELEASE SBOX-VM-S-OK = _S1-ASSERT
    DUP _S1-INSTANCE-U @ _S1-ZERO-CELLS? _S1-ASSERT
    SBOX-VM-RELEASE SBOX-VM-S-OK = _S1-ASSERT ;

: _S1-RESULT-RELEASE-ONE  ( result -- )
    DUP SBOX-VM-RESULT-RELEASE SBOX-VM-S-OK = _S1-ASSERT
    DUP SBOX-VM-RESULT-SIZE _S1-ZERO-CELLS? _S1-ASSERT
    SBOX-VM-RESULT-RELEASE SBOX-VM-S-OK = _S1-ASSERT ;

: _S1-VM-PREPARED-RELEASE  ( -- )
    _S1-BINDING SBOX-BINDING-RELEASE
        SBOX-BINDING-S-OK = _S1-ASSERT
    _S1-BINDING SBOX-BINDING-SIZE
        _S1-ZERO-CELLS? _S1-ASSERT
    _S1-PLAN SBOX-PLAN-RELEASE
        SBOX-PLAN-S-OK = _S1-ASSERT
    _S1-PLAN _S1-PLAN-U @
        _S1-ZERO-CELLS? _S1-ASSERT ;

: _S1-RESULT-ONE  ( expected result -- )
    >R
    R@ SBOX-VM-RESULT-VALID? _S1-ASSERT
    R@ SBOX-VM-RESULT-CLASS@
        SBOX-VM-CLASS-OK = _S1-ASSERT
    R@ SBOX-VM-RESULT-DETAIL@ 0= _S1-ASSERT
    R@ SBOX-VM-RESULT-AUX@ 0= _S1-ASSERT
    R@ SBOX-VM-RESULT-USAGE@ 0> _S1-ASSERT
    R@ SBOX-VM-RESULT-COUNT@ 1 = _S1-ASSERT
    0 R@ SBOX-VM-RESULT-CELL@
    _S1-ASSERT
    = _S1-ASSERT
    R> DROP ;

: _S1-RESULT-ERROR  ( class detail result -- )
    >R
    R@ SBOX-VM-RESULT-VALID? _S1-ASSERT
    R@ SBOX-VM-RESULT-CLASS@
    2 PICK = _S1-ASSERT
    R@ SBOX-VM-RESULT-DETAIL@
    1 PICK = _S1-ASSERT
    R@ SBOX-VM-RESULT-AUX@ 0= _S1-ASSERT
    R@ SBOX-VM-RESULT-COUNT@ 0= _S1-ASSERT
    2DROP R> DROP ;

: _S1-VM-SUCCESS-A  ( input input-n expected -- )
    >R
    1000 _S1-INSTANCE-A _S1-VM-INIT-ONE
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-INSTANCE-VALID? _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-RUN-STATE@
        SBOX-VM-RUN-RUNNABLE = _S1-ASSERT
    1000 _S1-INSTANCE-A SBOX-VM-RUN-SLICE
        SBOX-VM-RUN-COMPLETE = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-USAGE@ 0> _S1-ASSERT
    _S1-RESULT-A _S1-INSTANCE-A SBOX-VM-FINISH
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-INSTANCE-VALID? _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-RUN-STATE@
        SBOX-VM-RUN-FINISHED = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-USAGE@ 0= _S1-ASSERT
    _S1-INSTANCE-A _S1-INSTANCE-RELEASE-ONE
    R> _S1-RESULT-A _S1-RESULT-ONE
    _S1-RESULT-A _S1-RESULT-RELEASE-ONE
    _S1-STACK ;

: _S1-VM-SUCCESS-SCALAR-CONTRACTS  ( -- )
    _S1-SOURCE-ADD 64 _S1-VM-PREPARE
    20 _S1-INPUT-A !
    22 _S1-INPUT-A 8 + !
    _S1-INPUT-A 2 42 _S1-VM-SUCCESS-A
    _S1-VM-PREPARED-RELEASE

    _S1-SOURCE-FORWARD-CALL 64 _S1-VM-PREPARE
    21 _S1-INPUT-A !
    _S1-INPUT-A 1 42 _S1-VM-SUCCESS-A
    _S1-VM-PREPARED-RELEASE

    \ One verified plan takes both conditional paths in separate invocations.
    _S1-SOURCE-CONTROL 64 _S1-VM-PREPARE
    0 _S1-INPUT-A !
    _S1-INPUT-A 1 20 _S1-VM-SUCCESS-A
    1 _S1-INPUT-A !
    _S1-INPUT-A 1 11 _S1-VM-SUCCESS-A
    _S1-VM-PREPARED-RELEASE
    _S1-STACK ;

: _S1-VM-SUCCESS-STATE-CONTRACTS  ( -- )
    _S1-SOURCE-WHILE 64 _S1-VM-PREPARE
    0 0 3 _S1-VM-SUCCESS-A
    _S1-VM-PREPARED-RELEASE

    \ R is the innermost counted-loop index; the nested sum is six.
    _S1-SOURCE-LOOPS 64 _S1-VM-PREPARE
    0 0 6 _S1-VM-SUCCESS-A
    _S1-VM-PREPARED-RELEASE

    _S1-SOURCE-MEMORY 64 _S1-VM-PREPARE
    0 0 42 _S1-VM-SUCCESS-A
    _S1-VM-PREPARED-RELEASE
    _S1-STACK ;

: _S1-VM-SUCCESS-CONTRACTS  ( -- )
    _S1-VM-SUCCESS-SCALAR-CONTRACTS
    _S1-VM-SUCCESS-STATE-CONTRACTS
    _S1-STACK ;

: _S1-VM-BUDGET-CANCEL-CONTRACTS  ( -- )
    _S1-SOURCE-SPIN 64 _S1-VM-PREPARE

    \ The first unit is admitted exactly; the next instruction cannot
    \ reserve another unit and must not increase reported usage.
    0 0 1 _S1-INSTANCE-A _S1-VM-INIT-ONE
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-STEP
        SBOX-VM-RUN-RUNNABLE = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-USAGE@ 1 = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-STEP
        SBOX-VM-RUN-EXHAUSTED = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-USAGE@ 1 = _S1-ASSERT
    _S1-RESULT-A _S1-INSTANCE-A SBOX-VM-FINISH
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-RESULT-A SBOX-VM-RESULT-USAGE@ 1 = _S1-ASSERT
    SBOX-VM-CLASS-RESOURCE-EXHAUSTED
        SBOX-VM-EXHAUST-INSTRUCTION-UNITS
        _S1-RESULT-A _S1-RESULT-ERROR
    _S1-INSTANCE-A _S1-INSTANCE-RELEASE-ONE
    _S1-RESULT-A _S1-RESULT-RELEASE-ONE

    \ Cancellation is per instance, retains usage, and is stable when
    \ repeated before FINISH transfers the terminal result.
    0 0 100 _S1-INSTANCE-A _S1-VM-INIT-ONE
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-STEP
        SBOX-VM-RUN-RUNNABLE = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-USAGE@ 1 = _S1-ASSERT
    SBOX-VM-CANCEL-CALLER _S1-INSTANCE-A SBOX-VM-CANCEL
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-RUN-STATE@
        SBOX-VM-RUN-CANCELLED = _S1-ASSERT
    SBOX-VM-CANCEL-CALLER _S1-INSTANCE-A SBOX-VM-CANCEL
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-RESULT-A _S1-INSTANCE-A SBOX-VM-FINISH
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-RESULT-A SBOX-VM-RESULT-USAGE@ 1 = _S1-ASSERT
    SBOX-VM-CLASS-CANCELLED SBOX-VM-CANCEL-CALLER
        _S1-RESULT-A _S1-RESULT-ERROR
    _S1-INSTANCE-A _S1-INSTANCE-RELEASE-ONE
    _S1-RESULT-A _S1-RESULT-RELEASE-ONE

    _S1-VM-PREPARED-RELEASE
    _S1-STACK ;

: _S1-VM-TRAP-CONTRACTS  ( -- )
    _S1-SOURCE-DIVIDE-ZERO 64 _S1-VM-PREPARE
    0 0 100 _S1-INSTANCE-A _S1-VM-INIT-ONE
        SBOX-VM-S-OK = _S1-ASSERT
    100 _S1-INSTANCE-A SBOX-VM-RUN-SLICE
        SBOX-VM-RUN-TRAPPED = _S1-ASSERT
    _S1-RESULT-A _S1-INSTANCE-A SBOX-VM-FINISH
        SBOX-VM-S-OK = _S1-ASSERT
    \ Validation traps before reservation, so only the two literals charge.
    _S1-RESULT-A SBOX-VM-RESULT-USAGE@ 2 = _S1-ASSERT
    SBOX-VM-CLASS-GUEST-TRAP SBOX-VM-TRAP-DIVIDE-BY-ZERO
        _S1-RESULT-A _S1-RESULT-ERROR
    _S1-INSTANCE-A _S1-INSTANCE-RELEASE-ONE
    _S1-RESULT-A _S1-RESULT-RELEASE-ONE
    _S1-VM-PREPARED-RELEASE
    _S1-STACK ;

: _S1-VM-ISOLATION-CONTRACTS  ( -- )
    _S1-SOURCE-ADD 64 _S1-VM-PREPARE
    1 _S1-INPUT-A !
    2 _S1-INPUT-A 8 + !
    40 _S1-INPUT-B !
    2 _S1-INPUT-B 8 + !
    _S1-INPUT-A 2 100 _S1-INSTANCE-A _S1-VM-INIT-ONE
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-INPUT-B 2 100 _S1-INSTANCE-B _S1-VM-INIT-ONE
        SBOX-VM-S-OK = _S1-ASSERT

    \ Alternate individual instructions and prove that progress, usage,
    \ state, and final operands stay inside their owning invocation.
    _S1-INSTANCE-A SBOX-VM-STEP
        SBOX-VM-RUN-RUNNABLE = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-USAGE@ 1 = _S1-ASSERT
    _S1-INSTANCE-B SBOX-VM-USAGE@ 0= _S1-ASSERT
    _S1-INSTANCE-B SBOX-VM-STEP
        SBOX-VM-RUN-RUNNABLE = _S1-ASSERT
    _S1-INSTANCE-B SBOX-VM-USAGE@ 1 = _S1-ASSERT
    _S1-INSTANCE-A SBOX-VM-STEP
        SBOX-VM-RUN-COMPLETE = _S1-ASSERT
    _S1-INSTANCE-B SBOX-VM-RUN-STATE@
        SBOX-VM-RUN-RUNNABLE = _S1-ASSERT
    _S1-INSTANCE-B SBOX-VM-STEP
        SBOX-VM-RUN-COMPLETE = _S1-ASSERT

    _S1-RESULT-A _S1-INSTANCE-A SBOX-VM-FINISH
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-RESULT-B _S1-INSTANCE-B SBOX-VM-FINISH
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-INSTANCE-A _S1-INSTANCE-RELEASE-ONE
    _S1-INSTANCE-B _S1-INSTANCE-RELEASE-ONE
    3 _S1-RESULT-A _S1-RESULT-ONE
    42 _S1-RESULT-B _S1-RESULT-ONE
    _S1-RESULT-A _S1-RESULT-RELEASE-ONE
    _S1-RESULT-B _S1-RESULT-RELEASE-ONE
    _S1-VM-PREPARED-RELEASE
    _S1-STACK ;

64 CONSTANT _S1-HOT-BUDGET

: _S1-VM-HOTLOOP-CONTRACTS  ( -- )
    _S1-SOURCE-SPIN 64 _S1-VM-PREPARE
    0 0 _S1-HOT-BUDGET _S1-INSTANCE-A _S1-VM-INIT-ONE
        SBOX-VM-S-OK = _S1-ASSERT
    CYCLES _S1-HOT-START !
    _S1-HOT-BUDGET 1+ _S1-INSTANCE-A SBOX-VM-RUN-SLICE
        SBOX-VM-RUN-EXHAUSTED = _S1-ASSERT
    CYCLES _S1-HOT-START @ -
        ." SBOX STAGE1 VM HOTLOOP CYCLES " . CR TX-FLUSH
    _S1-INSTANCE-A SBOX-VM-USAGE@
        _S1-HOT-BUDGET = _S1-ASSERT
    _S1-RESULT-A _S1-INSTANCE-A SBOX-VM-FINISH
        SBOX-VM-S-OK = _S1-ASSERT
    _S1-RESULT-A SBOX-VM-RESULT-USAGE@
        _S1-HOT-BUDGET = _S1-ASSERT
    SBOX-VM-CLASS-RESOURCE-EXHAUSTED
        SBOX-VM-EXHAUST-INSTRUCTION-UNITS
        _S1-RESULT-A _S1-RESULT-ERROR
    _S1-INSTANCE-A _S1-INSTANCE-RELEASE-ONE
    _S1-RESULT-A _S1-RESULT-RELEASE-ONE
    _S1-VM-PREPARED-RELEASE
    _S1-STACK ;

: _S1-GROUP-BEGIN  ( -- )
    0 _S1-FAILS !
    0 _S1-CHECKS !
    DEPTH _S1-DEPTH !
    _S1-PROFILE SBOX-PROFILE-PURE-INIT
        SBOX-PROFILE-S-OK = _S1-ASSERT ;

: _S1-RUN-VM-SCALAR  ( -- )
    ." SBOX STAGE1 VM SCALAR START" CR TX-FLUSH
    _S1-GROUP-BEGIN
    _S1-VM-SUCCESS-SCALAR-CONTRACTS
    _S1-STACK
    _S1-FAILS @ 0= IF
        ." SBOX STAGE1 VM SCALAR PASS " _S1-CHECKS @ . CR TX-FLUSH
    ELSE
        ." SBOX STAGE1 VM SCALAR FAIL " _S1-FAILS @ . CR TX-FLUSH
    THEN ;

: _S1-RUN-VM-STATE  ( -- )
    ." SBOX STAGE1 VM STATE START" CR TX-FLUSH
    _S1-GROUP-BEGIN
    _S1-VM-SUCCESS-STATE-CONTRACTS
    _S1-STACK
    _S1-FAILS @ 0= IF
        ." SBOX STAGE1 VM STATE PASS " _S1-CHECKS @ . CR TX-FLUSH
    ELSE
        ." SBOX STAGE1 VM STATE FAIL " _S1-FAILS @ . CR TX-FLUSH
    THEN ;

: _S1-RUN-VM-TERMINAL  ( -- )
    ." SBOX STAGE1 VM TERMINAL START" CR TX-FLUSH
    _S1-GROUP-BEGIN
    _S1-VM-BUDGET-CANCEL-CONTRACTS
    _S1-VM-TRAP-CONTRACTS
    _S1-VM-ISOLATION-CONTRACTS
    _S1-STACK
    _S1-FAILS @ 0= IF
        ." SBOX STAGE1 VM TERMINAL PASS " _S1-CHECKS @ . CR TX-FLUSH
    ELSE
        ." SBOX STAGE1 VM TERMINAL FAIL " _S1-FAILS @ . CR TX-FLUSH
    THEN ;

: _S1-RUN-VM-HOTLOOP  ( -- )
    ." SBOX STAGE1 VM HOTLOOP START" CR TX-FLUSH
    _S1-GROUP-BEGIN
    _S1-VM-HOTLOOP-CONTRACTS
    _S1-STACK
    _S1-FAILS @ 0= IF
        ." SBOX STAGE1 VM HOTLOOP PASS " _S1-CHECKS @ . CR TX-FLUSH
    ELSE
        ." SBOX STAGE1 VM HOTLOOP FAIL " _S1-FAILS @ . CR TX-FLUSH
    THEN ;

: _S1-RUN  ( -- )
    0 _S1-FAILS !
    0 _S1-CHECKS !
    DEPTH _S1-DEPTH !
    ." SBOX STAGE1 CONTRACTS START" CR TX-FLUSH
    _S1-PROFILE SBOX-PROFILE-PURE-INIT
        SBOX-PROFILE-S-OK = _S1-ASSERT
    ." SBOX STAGE1 COMPILER FAILURES" CR TX-FLUSH
    _S1-COMPILER-FAILURE-CONTRACTS
    ." SBOX STAGE1 COMPILE VERIFY" CR TX-FLUSH
    _S1-COMPILER-VERIFIER-CONTRACTS
    ." SBOX STAGE1 CAPACITY" CR TX-FLUSH
    _S1-CANDIDATE-CAPACITY-CONTRACTS
    ." SBOX STAGE1 VERIFIER REJECTIONS" CR TX-FLUSH
    _S1-VERIFIER-REJECTION-CONTRACTS
    ." SBOX STAGE1 VM SUCCESS" CR TX-FLUSH
    _S1-VM-SUCCESS-CONTRACTS
    ." SBOX STAGE1 VM BUDGET CANCEL" CR TX-FLUSH
    _S1-VM-BUDGET-CANCEL-CONTRACTS
    ." SBOX STAGE1 VM TRAP" CR TX-FLUSH
    _S1-VM-TRAP-CONTRACTS
    ." SBOX STAGE1 VM ISOLATION" CR TX-FLUSH
    _S1-VM-ISOLATION-CONTRACTS
    _S1-STACK
    _S1-FAILS @ 0= IF
        ." SBOX STAGE1 CONTRACTS PASS " _S1-CHECKS @ . CR TX-FLUSH
    ELSE
        ." SBOX STAGE1 CONTRACTS FAIL " _S1-FAILS @ . CR TX-FLUSH
    THEN ;

[DEFINED] SBOX-STAGE1-DEFER-AUTORUN [IF]
[ELSE]
    _S1-RUN
[THEN]
