"""Owned bank parsing refuses escaped pointers and corrupt ACK frontiers."""
from test_field_model import run_field
from test_shell_family_clone import CLONE
from test_shell_snapshot import PRELUDE as SOURCE

FIXTURE = CLONE + SOURCE + r'''
CREATE _SB-SS 247 ALLOT CREATE _SB-BS 32775 ALLOT CREATE _SB-CS 32775 ALLOT
CREATE _SB-PS RTHP-SIZE 7 + ALLOT CREATE _SB-HS SHSN-SIZE 7 + ALLOT
CREATE _SB-XS RTE-SHELL-FACADE-SIZE 7 + ALLOT CREATE _SB-WS 4103 ALLOT
: _SB-S _SB-SS 7 + -8 AND ; : _SB-B _SB-BS 7 + -8 AND ; : _SB-C _SB-CS 7 + -8 AND ;
: _SB-P _SB-PS 7 + -8 AND ; : _SB-H _SB-HS 7 + -8 AND ; : _SB-X _SB-XS 7 + -8 AND ;
: _SB-W _SB-WS 7 + -8 AND ;
VARIABLE _SB-BO VARIABLE _SB-U VARIABLE _SB-OLD
: _SB-BUILD
    _SS-BUILD
    80 _SS-M SHM.WIDTH ! 24 _SS-M SHM.HEIGHT !
    23 1 _SS-M SHM-ENTRY SHME.ROW ! 23 2 _SS-M SHM-ENTRY SHME.ROW !
    _SS-FREEZE _SS-VALID 0= _RC-A
    _SB-S 240 0 FILL _SB-B 32768 0 FILL
    _SB-B _SB-S _RSHSP.A ! 32768 _SB-S _RSHSP.A-U !
    128 _SB-B RSHSP-BANK.MODEL ! _SS-U @ _SB-B RSHSP-BANK.MODEL-U !
    _SS-F _SB-B 128 + _SS-U @ MOVE
    _SS-U @ 7 + -8 AND 128 + DUP _SB-BO ! _SB-B RSHSP-BANK.BATCH !
    _RC-BATCH _SB-B _SB-BO @ + 32768 _SB-BO @ - RSHFC-COPY 0= _RC-A
    _SB-BO @ + DUP _SB-U ! _SB-B RSHSP-BANK.USED !
    1234 _SB-B RSHSP-BANK.TARGET ! 3 _SB-B RSHSP-BANK.DRAW !
    7 _SB-B RSHSP-BANK.OWNER ! 9 _SB-B RSHSP-BANK.GENERATION !
    21 _SB-B RSHSP-BANK.NEXT-REGION ! 106 _SB-B RSHSP-BANK.NEXT-OBJECT ! ;
: _SB-VALID _SB-B _SB-S _RSHSP-BANK-VALID? ;
: _SB-BAD ( value field -- ) DUP @ >R DUP >R ! _SB-VALID 0= _RC-A R> R> SWAP ! ;
: _SB-BATCH _SB-B _SB-BO @ + ;
: _SB-HEADER
    _SB-S 240 0 FILL
    _RSHSP-MAGIC _SB-S _RSHSP.MAGIC ! 208 _SB-S _RSHSP.SIZE ! _SB-S _SB-S _RSHSP.SELF !
    _SB-P _SB-S _RSHSP.PRODUCER ! _SB-H _SB-S _RSHSP.SOURCE ! _SB-X _SB-S _RSHSP.SHELL !
    _SB-W _SB-S _RSHSP.WORK ! 4096 _SB-S _RSHSP.WORK-U !
    _SB-B _SB-S _RSHSP.A ! 32768 _SB-S _RSHSP.A-U !
    _SB-C _SB-S _RSHSP.B ! 32768 _SB-S _RSHSP.B-U ! ;
'''


def run(program, minimum=1):
    run_field(program, marker="CATALOG", minimum=minimum,
              extra_sources=("tui/rich-terminal/shell-screen-producer.f",))


def test_owned_bank_graph_offsets_frontiers_and_whole_clone_extent():
    run(FIXTURE + r'''
_SB-BUILD _SB-VALID _RC-A
0 _SB-B RSHSP-BANK.NEXT-REGION _SB-BAD
22 _SB-B RSHSP-BANK.NEXT-REGION _SB-BAD
0 _SB-B RSHSP-BANK.NEXT-OBJECT _SB-BAD
107 _SB-B RSHSP-BANK.NEXT-OBJECT _SB-BAD
_SB-U @ 8 + _SB-B RSHSP-BANK.USED _SB-BAD
_SB-BO @ 8 + _SB-B RSHSP-BANK.BATCH _SB-BAD
136 _SB-B RSHSP-BANK.MODEL _SB-BAD
81 _SB-B 128 + SHM.WIDTH _SB-BAD
_RC-CAT _SB-BATCH _RTE-FB.CATALOG-A _SB-BAD
_SB-B 128 + _SB-BATCH _RTE-FB.CATALOG-A _SB-BAD
_RC-FAM _SB-BATCH _RTE-FB.FAMILIES-A _SB-BAD
_SB-BATCH _RTE-FB.FAMILIES-A @ _RTE-FE.PLAN-A DUP @ _SB-OLD !
_RC-CP SWAP ! _SB-VALID 0= _RC-A
_SB-OLD @ _SB-BATCH _RTE-FB.FAMILIES-A @ _RTE-FE.PLAN-A !
_SB-BATCH _RTE-FB.FAMILIES-A @ RTE-FAMILY-ITEMS@ DROP _RTE-CONTROL.ID
0x8000000000000000 SWAP _SB-BAD
_SB-VALID _RC-A
\ A generic valid SERIES-only clone has no regions; shell bank refuses it
\ before computing a last-region pointer below its owned array.
_RC-FAM 256 + _RC-FAM 64 MOVE 64 _RC-BATCH _RTE-FB.FAMILIES-U !
0 _RC-CAT _RTE-RC.REGIONS-A ! 0 _RC-CAT _RTE-RC.REGIONS-U !
0 _RC-YI _RTE-SERIES.SAMPLES-A ! 0 _RC-YI _RTE-SERIES.SAMPLES-U !
0 _RC-FAM _RTE-FE.BYTES-A ! 0 _RC-FAM _RTE-FE.BYTES-U !
_SB-BUILD _SB-VALID 0= _RC-A
_RC-DONE
''', minimum=20)


def test_nested_descriptor_alias_refuses_before_private_scratch_store():
    run(FIXTURE + r'''
_SB-HEADER
31337 _RSHSP-S ! 41414 _RSHSP-P !
_RSHSP-S _SB-S _RSHSP.PRODUCER !
_SB-S RSHSP-VALID? 0= _RC-A _RSHSP-S @ 31337 = _RC-A _RSHSP-P @ 41414 = _RC-A
_SB-HEADER _RSHSP-P _SB-S _RSHSP.SOURCE !
_SB-S RSHSP-VALID? 0= _RC-A _RSHSP-S @ 31337 = _RC-A _RSHSP-P @ 41414 = _RC-A
_SB-HEADER _RSHSP-P _SB-S _RSHSP.SHELL !
_SB-S RSHSP-VALID? 0= _RC-A _RSHSP-S @ 31337 = _RC-A _RSHSP-P @ 41414 = _RC-A
_SB-HEADER 0 _SB-S _RSHSP.PRODUCER !
_SB-S RSHSP-VALID? 0= _RC-A _RSHSP-S @ 31337 = _RC-A
_SB-HEADER _SB-P 1+ _SB-S _RSHSP.PRODUCER !
_SB-S RSHSP-VALID? 0= _RC-A _RSHSP-S @ 31337 = _RC-A
_RC-DONE
''', minimum=13)


def test_pane_geometry_expansion_and_exact_overlap_edges():
    run(FIXTURE + r'''
_SS-BUILD
0 _SS-M SHM-ENTRY _RSHSP-CONTENT-RECT
19 = _RC-A 9 = _RC-A 0= _RC-A 0= _RC-A
0 _SS-M SHM-ENTRY 3 _SS-M SHM-ENTRY SHM-ENTRY-SIZE MOVE
0 _SS-M SHM-ENTRY 3 _SS-M SHM-ENTRY _RSHSP-OVERLAP? _RC-A
19 3 _SS-M SHM-ENTRY SHME.CONTENT-COL !
0 _SS-M SHM-ENTRY 3 _SS-M SHM-ENTRY _RSHSP-OVERLAP? 0= _RC-A
18 3 _SS-M SHM-ENTRY SHME.CONTENT-COL !
0 _SS-M SHM-ENTRY 3 _SS-M SHM-ENTRY _RSHSP-OVERLAP? _RC-A
0 3 _SS-M SHM-ENTRY SHME.CONTENT-COL !
9 3 _SS-M SHM-ENTRY SHME.CONTENT-ROW !
0 _SS-M SHM-ENTRY 3 _SS-M SHM-ENTRY _RSHSP-OVERLAP? 0= _RC-A
8 3 _SS-M SHM-ENTRY SHME.CONTENT-ROW !
0 _SS-M SHM-ENTRY 3 _SS-M SHM-ENTRY _RSHSP-OVERLAP? _RC-A
_RC-DONE
''', minimum=9)
