#!/usr/bin/env python3
"""Focused canonical tabs widget and TABSET observation regression."""

from __future__ import annotations

import re
from pathlib import Path

from test_textarea import _load_forth_lines, _run_forth


ROOT = Path(__file__).resolve().parents[1]
TABS = ROOT / "akashic" / "tui" / "widgets" / "tabs.f"


def _tabs_program() -> list[str]:
    return _load_forth_lines(TABS) + [
        "VARIABLE _T-FAILS",
        "VARIABLE _T-CHECKS",
        "VARIABLE _T-DEPTH",
        "VARIABLE _T-SCR",
        "VARIABLE _T-RGN",
        "VARIABLE _T-RGN2",
        "VARIABLE _T-W",
        "VARIABLE _T-W2",
        "VARIABLE _T-I1",
        "VARIABLE _T-I2",
        "VARIABLE _T-C0",
        "VARIABLE _T-C1",
        "VARIABLE _T-C2",
        "VARIABLE _T-C3",
        "VARIABLE _T-U",
        "VARIABLE _T-CB-N",
        "VARIABLE _T-CB-I",
        "VARIABLE _T-TAB",
        "CREATE _T-EVENT 24 ALLOT",
        "CREATE _T-BUILDER-S USCOL-BUILDER-SIZE 7 + ALLOT",
        "CREATE _T-OUT-S 512 7 + ALLOT",
        "CREATE _T-WORK-S 64 7 + ALLOT",
        "CREATE _T-SUMMARY-S USCOL-SUMMARY-SIZE 7 + ALLOT",
        ": _T-BUILDER _T-BUILDER-S 7 + -8 AND ;",
        ": _T-OUT _T-OUT-S 7 + -8 AND ;",
        ": _T-WORK _T-WORK-S 7 + -8 AND ;",
        ": _T-SUMMARY _T-SUMMARY-S 7 + -8 AND ;",
        ': _T-ALPHA S" Alpha" ;',
        ': _T-BETA S" Beta" ;',
        ': _T-GAMMA S" Gamma" ;',
        ': _T-THIRD S" Third" ;',
        ': _T-DELTA S" Delta" ;',
        ': _T-ASSERT 1 _T-CHECKS +! 0= IF 1 _T-FAILS +! ." TAB ASSERT " _T-CHECKS @ . CR THEN ;',
        ": _T-OK USCOL-S-OK = _T-ASSERT ;",
        ": _T-CB ( index widget -- ) DROP _T-CB-I ! 1 _T-CB-N +! ;",
        "0 _T-FAILS ! 0 _T-CHECKS ! 0 _T-CB-N ! 0 _T-CB-I !",
        "60 12 SCR-NEW DUP _T-SCR ! SCR-USE",
        "1 2 6 40 RGN-NEW DUP _T-RGN ! 12 TAB-NEW-CAP DUP _T-W !",
        "DUP TAB-CAPACITY 12 = _T-ASSERT",
        "DUP TAB-INSTANCE@ DUP 0<> _T-ASSERT _T-I1 !",
        "_T-ALPHA _T-W @ TAB-ADD DUP 0<> _T-ASSERT _T-C0 !",
        "_T-BETA _T-W @ TAB-ADD DUP 0<> _T-ASSERT _T-C1 !",
        "_T-GAMMA _T-W @ TAB-ADD DUP 0<> _T-ASSERT _T-C2 !",
        "_T-W @ TAB-COUNT 3 = _T-ASSERT",
        "0 _T-W @ TAB-KEY@ 1 = _T-ASSERT",
        "1 _T-W @ TAB-KEY@ 2 = _T-ASSERT",
        "2 _T-W @ TAB-KEY@ 3 = _T-ASSERT",
        "1 _T-W @ TAB-REMOVE",
        "_T-W @ TAB-COUNT 2 = _T-ASSERT",
        "0 _T-W @ TAB-KEY@ 1 = _T-ASSERT",
        "1 _T-W @ TAB-KEY@ 3 = _T-ASSERT",
        "_T-THIRD 1 _T-W @ TAB-LABEL!",
        "1 _T-W @ TAB-KEY@ 3 = _T-ASSERT",
        "_T-DELTA _T-W @ TAB-ADD DUP 0<> _T-ASSERT _T-C3 !",
        "2 _T-W @ TAB-KEY@ 4 = _T-ASSERT",
        "1 _T-W @ TAB-SELECT",
        "_T-W @ TAB-ACTIVE 1 = _T-ASSERT",
        "DEPTH _T-DEPTH !",
        "99 _T-BUILDER _T-W @ TAB-TABSET-MEASURE",
        "DUP _T-OK DROP DUP _T-U ! 224 = _T-ASSERT",
        "DEPTH _T-DEPTH @ = _T-ASSERT",
        "99 _T-OUT _T-U @ 1- _T-BUILDER _T-W @ TAB-TABSET-CAPTURE",
        "USCOL-S-CAPACITY = _T-ASSERT 0= _T-ASSERT",
        "DEPTH _T-DEPTH @ = _T-ASSERT",
        "99 _T-OUT _T-U @ _T-BUILDER _T-W @ TAB-TABSET-CAPTURE",
        "DUP _T-OK DROP _T-U @ = _T-ASSERT",
        "DEPTH _T-DEPTH @ = _T-ASSERT",
        "_T-OUT USCOL-ENTRY-FAMILY@ USCOL-F-TABSET = _T-ASSERT",
        "_T-OUT USCOL-ENTRY-KEY@ 99 = _T-ASSERT",
        "_T-OUT USCOL-ROOT-ROW@ 0= _T-ASSERT",
        "_T-OUT USCOL-ROOT-COLUMN@ 0= _T-ASSERT",
        "_T-OUT USCOL-ROOT-HEIGHT@ 2 = _T-ASSERT",
        "_T-OUT USCOL-ROOT-WIDTH@ 40 = _T-ASSERT",
        "_T-OUT USCOL-ROOT-STATE@ 3 = _T-ASSERT",
        "_T-OUT USCOL-TABSET-COUNT@ 3 = _T-ASSERT",
        "_T-OUT USCOL-TABSET-FIRST DUP _T-TAB !",
        "DUP USCOL-TAB-KEY@ 1 = _T-ASSERT",
        "DUP USCOL-TAB-ORDER@ 0= _T-ASSERT",
        "DUP USCOL-TAB-STATE@ 3 = _T-ASSERT",
        "USCOL-TAB-LABEL@ _T-ALPHA STR-STR= _T-ASSERT",
        "_T-TAB @ USCOL-TAB-NEXT DUP _T-TAB !",
        "DUP USCOL-TAB-KEY@ 3 = _T-ASSERT",
        "DUP USCOL-TAB-ORDER@ 1 = _T-ASSERT",
        "DUP USCOL-TAB-STATE@ 7 = _T-ASSERT",
        "USCOL-TAB-LABEL@ _T-THIRD STR-STR= _T-ASSERT",
        "_T-TAB @ USCOL-TAB-NEXT DUP _T-TAB !",
        "DUP USCOL-TAB-KEY@ 4 = _T-ASSERT",
        "DUP USCOL-TAB-ORDER@ 2 = _T-ASSERT",
        "DUP USCOL-TAB-STATE@ 3 = _T-ASSERT",
        "USCOL-TAB-LABEL@ _T-DELTA STR-STR= _T-ASSERT",
        "_T-OUT _T-U @ USCOL-VALIDATION-WORK-BYTES DUP _T-OK DROP 24 = _T-ASSERT",
        "_T-OUT _T-U @ _T-WORK 24 _T-SUMMARY USCOL-ENTRY-VALIDATE _T-OK",
        "_T-SUMMARY USCOL-SUMMARY-CHILD-COUNT@ 3 = _T-ASSERT",
        "_T-OUT 512 _T-W @ TAB-TABSET-STORAGE-DISJOINT? _T-ASSERT",
        "_T-W @ _TAB-DESC-SIZE _T-W @ TAB-TABSET-STORAGE-DISJOINT? 0= _T-ASSERT",
        "_T-ALPHA _T-W @ TAB-TABSET-STORAGE-DISJOINT? 0= _T-ASSERT",
        "_TAB-C-ROOT 8 TAB-STORAGE-DISJOINT? 0= _T-ASSERT",
        "99 _T-ALPHA _T-BUILDER _T-W @ TAB-TABSET-CAPTURE",
        "USCOL-S-INVALID = _T-ASSERT 0= _T-ASSERT",
        "99 _T-OUT 512 _T-W @ _T-W @ TAB-TABSET-CAPTURE",
        "USCOL-S-INVALID = _T-ASSERT 0= _T-ASSERT",
        "' _T-CB _T-W @ TAB-ON-SWITCH",
        "KEY-T-SPECIAL _T-EVENT ! KEY-RIGHT _T-EVENT 8 + ! 0 _T-EVENT 16 + !",
        "_T-EVENT _T-W @ WDG-HANDLE _T-ASSERT",
        "_T-W @ TAB-ACTIVE 2 = _T-ASSERT",
        "_T-CB-N @ 1 = _T-ASSERT _T-CB-I @ 2 = _T-ASSERT",
        "KEY-LEFT _T-EVENT 8 + ! _T-EVENT _T-W @ WDG-HANDLE _T-ASSERT",
        "_T-W @ TAB-ACTIVE 1 = _T-ASSERT",
        "_T-CB-N @ 2 = _T-ASSERT _T-CB-I @ 1 = _T-ASSERT",
        "SCR-CLEAR _T-W @ WDG-DRAW",
        "1 3 SCR-GET CELL-CP@ 65 = _T-ASSERT",
        "1 10 SCR-GET CELL-CP@ 84 = _T-ASSERT",
        "1 17 SCR-GET CELL-CP@ 68 = _T-ASSERT",
        "2 2 SCR-GET CELL-CP@ 0x2500 = _T-ASSERT",
        "1 3 _T-W @ TAB-HIT-INDEX _T-ASSERT 0= _T-ASSERT",
        "1 10 _T-W @ TAB-HIT-INDEX _T-ASSERT 1 = _T-ASSERT",
        "1 17 _T-W @ TAB-HIT-INDEX _T-ASSERT 2 = _T-ASSERT",
        "2 17 _T-W @ TAB-HIT-INDEX NIP 0= _T-ASSERT",
        "KEY-T-MOUSE _T-EVENT ! KEY-MOUSE-LEFT _T-EVENT 8 + !",
        "1 16 LSHIFT 17 OR _T-EVENT 16 + !",
        "_T-EVENT _T-W @ WDG-HANDLE _T-ASSERT",
        "_T-W @ TAB-ACTIVE 2 = _T-ASSERT",
        "_T-CB-N @ 3 = _T-ASSERT _T-CB-I @ 2 = _T-ASSERT",
        "2 16 LSHIFT 17 OR _T-EVENT 16 + !",
        "_T-EVENT _T-W @ WDG-HANDLE 0= _T-ASSERT",
        "_T-CB-N @ 3 = _T-ASSERT",
        "KEY-MOUSE-RIGHT _T-EVENT 8 + ! 1 16 LSHIFT 3 OR _T-EVENT 16 + !",
        "_T-EVENT _T-W @ WDG-HANDLE 0= _T-ASSERT",
        "_T-CB-N @ 3 = _T-ASSERT",
        "0 0 1 20 RGN-NEW DUP _T-RGN2 ! 0 TAB-NEW-CAP DUP _T-W2 !",
        "DUP TAB-CAPACITY 0= _T-ASSERT",
        "DUP TAB-INSTANCE@ DUP 0<> _T-ASSERT DUP _T-I2 ! _T-I1 @ <> _T-ASSERT",
        "100 _T-BUILDER _T-W2 @ TAB-TABSET-MEASURE DUP _T-OK DROP 80 = _T-ASSERT",
        "100 _T-OUT 80 _T-BUILDER _T-W2 @ TAB-TABSET-CAPTURE DUP _T-OK DROP 80 = _T-ASSERT",
        "_T-OUT USCOL-ROOT-HEIGHT@ 1 = _T-ASSERT",
        "_T-OUT USCOL-TABSET-COUNT@ 0= _T-ASSERT",
        "_T-C0 @ RGN-FREE _T-C1 @ RGN-FREE _T-C2 @ RGN-FREE _T-C3 @ RGN-FREE",
        "_T-W @ TAB-FREE _T-RGN @ RGN-FREE",
        "_T-W2 @ TAB-FREE _T-RGN2 @ RGN-FREE _T-SCR @ SCR-FREE",
        '_T-FAILS @ 0= IF ." TABS PASS " ELSE ." TABS FAIL " THEN _T-CHECKS @ . _T-FAILS @ . CR',
    ]


def test_canonical_tabs_keep_identity_draw_switch_and_capture_one_state() -> None:
    output = _run_forth(_tabs_program(), max_steps=250_000_000)
    assert "not found" not in output.lower(), output[-10000:]
    assert "undefined" not in output.lower(), output[-10000:]
    summary = re.search(r"TABS PASS\s+(\d+)\s+0", output)
    assert summary, output[-10000:]
    assert int(summary.group(1)) >= 60
