"""Executable neutral shared-region geometry, bounded authority and pane proofs."""
from test_data_graphics_series import run_series

MODULES = ("tui/rich-terminal/region-catalog.f",)


def _storage():
    sizes = {"CAT": 56, "REG": 288, "BATCH": 72, "FAM": 384,
             "CP": 144, "GP": 144, "IP": 72, "SP": 144, "YP": 48, "PP": 144,
             "CI": 200, "GI": 120, "II": 216, "SI": 176, "YI": 88, "PI": 368,
             "IR": 96, "CT": 8, "GT": 8, "IT": 8, "ST": 8, "YT": 16, "PT": 8,
             "REF": 16, "COPY": 4096}
    return "\n".join(f"CREATE _RC-{key}-S {size + 7} ALLOT : _RC-{key} _RC-{key}-S 7 + -8 AND ;"
                     for key, size in sizes.items())


PRELUDE = _storage() + r'''
VARIABLE _RC-N VARIABLE _RC-FAIL VARIABLE _RC-A0 VARIABLE _RC-A1
: _RC-A 1 _RC-N +! 0= IF 1 _RC-FAIL +! ." CATALOG ASSERT " _RC-N @ . CR THEN ;
: _RC-VALID _RC-BATCH RTE-FAMILY-BATCH-VALID? _RC-A ;
: _RC-INVALID _RC-BATCH RTE-FAMILY-BATCH-VALID? 0= _RC-A ;
: _RC-DONE _RC-FAIL @ 0= IF ." CATALOG PASS " ELSE ." CATALOG FAIL " THEN _RC-N @ . _RC-FAIL @ . CR ;
: _RC-MUTATE ( value address -- ) DUP @ >R DUP >R ! _RC-INVALID R> R> SWAP ! ;
: _RC-REGION ( id x y w h z dst -- )
    >R R@ 96 0 FILL R@ _RTE-IR.Z !
    DUP R@ _RTE-IR.ROWS ! R@ _RTE-IR.CLIP-ROWS !
    DUP R@ _RTE-IR.COLS ! R@ _RTE-IR.CLIP-COLS !
    DUP R@ _RTE-IR.Y ! R@ _RTE-IR.CLIP-Y !
    DUP R@ _RTE-IR.X ! R@ _RTE-IR.CLIP-X ! R@ _RTE-IR.ID !
    3 R> _RTE-IR.FLAGS ! ;
: _RC-PLAN ( item-a item-u region plan -- )
    >R R@ 144 0 FILL R@ 32 + 88 MOVE
    7 R@ ! 9 R@ 8 + ! 80 R@ 16 + ! 24 R@ 24 + !
    R@ _RTE-CP.ITEMS-U ! R> _RTE-CP.ITEMS-A ! ;
: _RC-FAMILY ( kind plan bytes-a bytes-u index -- )
    64 * _RC-FAM + >R R@ 64 0 FILL
    R@ _RTE-FE.BYTES-U ! R@ _RTE-FE.BYTES-A !
    R@ _RTE-FE.PLAN-A ! DUP R@ _RTE-FE.KIND !
    RTE-FAMILY-PLAN-SIZE R> _RTE-FE.PLAN-U ! ;
: _RC-COMMON ( object region root-h root-w item bytes -- )
    2DUP 0 FILL DROP >R R@ 104 + ! R@ 96 + ! R@ 48 + ! R@ 16 + !
    7 R@ ! 9 R@ 8 + ! -1 R@ 32 + ! 1 R@ 80 + ! 1 R> 88 + ! ;
: _RC-BUILD
    _RC-CAT 56 0 FILL _RC-REG 288 0 FILL _RC-FAM 384 0 FILL
    _RC-BATCH 72 0 FILL
    10 0 0 40 10 0 _RC-REG _RC-REGION
    11 1 1 38 8 1 _RC-REG 96 + _RC-REGION
    20 0 11 80 1 2 _RC-REG 192 + _RC-REGION
    7 _RC-CAT ! 9 _RC-CAT 8 + ! 80 _RC-CAT 16 + ! 24 _RC-CAT 24 + !
    _RC-REG _RC-CAT 32 + ! 288 _RC-CAT 40 + !
    1 _RC-BATCH ! _RC-CAT _RC-BATCH 8 + ! 56 _RC-BATCH 16 + !
    _RC-FAM _RC-BATCH 24 + ! 384 _RC-BATCH 32 + !
    1 _RC-BATCH 40 + ! 2 _RC-BATCH 48 + ! 3 _RC-BATCH 56 + !
    \ Real pane chrome references an independent same-owner content region.
    105 10 10 40 _RC-PI 184 _RC-COMMON
    1 _RC-PI _RTE-PANE.KIND ! 10 _RC-PI _RTE-PANE.HEIGHT ! 40 _RC-PI _RTE-PANE.WIDTH !
    11 _RC-PI _RTE-PANE.CONTENT-REGION ! 1 _RC-PI _RTE-PANE.CONTENT-ROW !
    1 _RC-PI _RTE-PANE.CONTENT-COL ! 8 _RC-PI _RTE-PANE.CONTENT-HEIGHT !
    38 _RC-PI _RTE-PANE.CONTENT-WIDTH ! -1 _RC-PI _RTE-PANE.FOCUSED !
    80 _RC-PT C! _RC-PT _RC-PI _RTE-PANE.TITLE-A ! 1 _RC-PI _RTE-PANE.TITLE-U !
    _RC-PI 184 _RC-REG _RC-PP _RC-PLAN
    6 _RC-PP _RC-PT 1 5 _RC-FAMILY
    \ All real content families use the content region, with its own root size.
    _RC-CI 200 0 FILL 7 _RC-CI ! 9 _RC-CI 8 + ! 100 _RC-CI 16 + !
    5 _RC-CI _RTE-CONTROL.KIND ! 3 _RC-CI _RTE-CONTROL.STATE ! 11 _RC-CI 48 + !
    8 _RC-CI 104 + ! 38 _RC-CI 112 + !
    _RC-CI 200 _RC-REG 96 + _RC-CP _RC-PLAN
    67 _RC-CT C! _RC-CT _RC-CI _RTE-CONTROL.LABEL-A ! 1 _RC-CI _RTE-CONTROL.LABEL-U !
    1 _RC-CP _RC-CT 1 0 _RC-FAMILY
    _RC-GI 120 0 FILL 101 _RC-GI ! 8 _RC-GI _RTE-LPI.ROOT-HEIGHT !
    38 _RC-GI _RTE-LPI.ROOT-WIDTH ! 1 _RC-GI _RTE-LPI.TEXT-CAPACITY !
    _RC-GI 120 _RC-REG 96 + _RC-GP _RC-PLAN
    71 _RC-GT C! 2 _RC-GP _RC-GT 1 1 _RC-FAMILY
    0 _RC-REF ! 1 _RC-REF 8 + ! _RC-REF _RC-FAM 64 + _RTE-FE.REFS-A !
    16 _RC-FAM 64 + _RTE-FE.REFS-U !
    102 11 8 38 _RC-II 216 _RC-COMMON
    _RC-IP 72 0 FILL _RC-CAT _RC-IP 32 MOVE
    _RC-REG 96 + _RC-IR 96 MOVE _RC-IR _RC-IP 32 + ! 96 _RC-IP 40 + !
    _RC-II _RC-IP 48 + ! 216 _RC-IP 56 + !
    73 _RC-IT C! _RC-IT _RC-II _RTE-INSTRUMENT.UNIT-A ! 1 _RC-II _RTE-INSTRUMENT.UNIT-U !
    3 _RC-IP _RC-IT 1 2 _RC-FAMILY
    103 20 1 80 _RC-SI 176 _RC-COMMON
    _RC-SI 176 _RC-REG 192 + _RC-SP _RC-PLAN
    83 _RC-ST C! _RC-ST _RC-SI _RTE-STATIC.VALUE-A ! 1 _RC-SI _RTE-STATIC.VALUE-U !
    4 _RC-SP _RC-ST 1 3 _RC-FAMILY
    _RC-YI 88 0 FILL 7 _RC-YI ! 9 _RC-YI 8 + ! 1 _RC-YI 16 + !
    2 _RC-YI _RTE-SERIES.CAPACITY ! 1 _RC-YI _RTE-SERIES.MODE !
    _RC-YT _RC-YI _RTE-SERIES.SAMPLES-A ! 16 _RC-YI _RTE-SERIES.SAMPLES-U !
    _RC-YP 48 0 FILL _RC-CAT _RC-YP 32 MOVE _RC-YI _RC-YP 32 + ! 88 _RC-YP 40 + !
    5 _RC-YP _RC-YT 16 4 _RC-FAMILY ;
_RC-BUILD
'''


def test_shared_catalog_all_family_membership_dense_payload_and_no_orphans():
    run_series(PRELUDE + r'''
_RC-CAT RTE-REGION-CATALOG-VALID? _RC-A _RC-VALID
10 _RC-CAT RTE-REGION-CATALOG-FIND _RC-REG = _RC-A
11 _RC-CAT RTE-REGION-CATALOG-FIND _RC-REG 96 + = _RC-A
999 _RC-CAT RTE-REGION-CATALOG-FIND 0= _RC-A
_RC-PI RTE-PANE-VALID? _RC-A
8 _RC-CAT _RTE-RC.OWNER _RC-MUTATE
8 _RC-CP _RTE-CP.OWNER _RC-MUTATE
8 _RC-GP _RTE-LP.GENERATION _RC-MUTATE
10 _RC-CI _RTE-CONTROL.REGION _RC-MUTATE
40 _RC-GI _RTE-LPI.ROOT-WIDTH _RC-MUTATE
20 _RC-II _RTE-INSTRUMENT.REGION _RC-MUTATE
20 _RC-IR _RTE-IR.ID _RC-MUTATE
8 _RC-SI _RTE-STATIC.GENERATION _RC-MUTATE
8 _RC-YI _RTE-SERIES.OWNER _RC-MUTATE
1 _RC-REF _RC-MUTATE
2 _RC-FAM _RTE-FE.BYTES-U _RC-MUTATE
_RC-CT 1+ _RC-CI _RTE-CONTROL.LABEL-A _RC-MUTATE
_RC-GT _RC-CI _RTE-CONTROL.LABEL-A _RC-MUTATE
-1 _RC-CI _RTE-CONTROL.LABEL-U _RC-MUTATE
2 _RC-YI _RTE-SERIES.MODE _RC-MUTATE
-1 _RC-YI _RTE-SERIES.SAMPLES-U _RC-MUTATE
10 _RC-REG 96 + _RTE-IR.ID _RC-MUTATE
1 _RC-REG _RTE-IR.RESERVED _RC-MUTATE
81 _RC-REG _RTE-IR.CLIP-COLS _RC-MUTATE
1 _RC-CAT _RTE-RC.RESERVED _RC-MUTATE
0 _RC-BATCH _RTE-FB.ATTEMPT _RC-MUTATE
383 _RC-BATCH _RTE-FB.FAMILIES-U _RC-MUTATE
55 _RC-BATCH _RTE-FB.CATALOG-U _RC-MUTATE
1 _RC-FAM _RTE-FE.RESERVED _RC-MUTATE
143 _RC-FAM _RTE-FE.PLAN-U _RC-MUTATE
_RC-VALID _RC-DONE
''', minimum=32, extra_sources=MODULES, marker="CATALOG")


def test_pane_empty_content_geometry_order_title_and_alias_refusal():
    run_series(PRELUDE + r'''
_RC-VALID
10 _RC-PI _RTE-PANE.CONTENT-REGION _RC-MUTATE
999 _RC-PI _RTE-PANE.CONTENT-REGION _RC-MUTATE
-1 _RC-REG 96 + _RTE-IR.Z _RC-MUTATE
1 _RC-REG 96 + _RTE-IR.FLAGS _RC-MUTATE
0 _RC-PI _RTE-PANE.CONTENT-ROW _RC-MUTATE
10 _RC-PI _RTE-PANE.CONTENT-HEIGHT _RC-MUTATE
40 _RC-PI _RTE-PANE.CONTENT-WIDTH _RC-MUTATE
1 _RC-PI _RTE-PANE.PARENT _RC-MUTATE
1 _RC-PI _RTE-PANE.RESERVED _RC-MUTATE
0 _RC-PI _RTE-PANE.VISIBLE _RC-MUTATE
1 _RC-PI _RTE-PANE.FOCUSED _RC-MUTATE
0 _RC-PI _RTE-PANE.KIND _RC-MUTATE
0 _RC-PI _RTE-PANE.ID _RC-MUTATE
0 _RC-PI _RTE-PANE.ROOT-WIDTH _RC-MUTATE
0 _RC-PI _RTE-PANE.CONTENT-HEIGHT _RC-MUTATE
-1 _RC-PI _RTE-PANE.CONTENT-COL _RC-MUTATE
10 _RC-PT C! _RC-INVALID 80 _RC-PT C!
\ A canonical empty content region needs no fake content object.
_RC-FAM 320 + _RC-FAM 64 MOVE 64 _RC-BATCH _RTE-FB.FAMILIES-U !
192 _RC-CAT _RTE-RC.REGIONS-U ! _RC-VALID
_RC-REG 96 + _RTE-IR.CLIP-X 32 0 FILL _RC-VALID
\ An unreferenced third row is an orphan even when its own geometry is valid.
288 _RC-CAT _RTE-RC.REGIONS-U ! _RC-INVALID
192 _RC-CAT _RTE-RC.REGIONS-U !
\ Two pane records cannot name one content region.
_RC-PI _RC-PI 184 + 184 MOVE
0 _RC-PI 184 + _RTE-PANE.TITLE-A ! 0 _RC-PI 184 + _RTE-PANE.TITLE-U !
368 _RC-PP _RTE-CP.ITEMS-U ! _RC-INVALID
184 _RC-PP _RTE-CP.ITEMS-U !
_RC-CAT _RC-FAM _RTE-FE.BYTES-A _RC-MUTATE
_RTE-RC-CATALOG _RC-FAM _RTE-FE.BYTES-A _RC-MUTATE
_RTE-HPV-OWNED-START _RC-FAM _RTE-FE.BYTES-A _RC-MUTATE
_RC-PI _RC-FAM _RTE-FE.PLAN-A _RC-MUTATE
_RC-VALID _RC-DONE
''', minimum=27, extra_sources=MODULES, marker="CATALOG")


def test_prewrite_authority_guards_adjacent_slices_and_series_only_catalog():
    run_series(PRELUDE + r'''
_RC-VALID
\ Same backing allocation is allowed when used display slices are disjoint.
71 _RC-CT 1+ C! _RC-CT 1+ _RC-FAM 64 + _RTE-FE.BYTES-A ! _RC-VALID
_RC-CT _RC-FAM 64 + _RTE-FE.BYTES-A _RC-MUTATE
_RC-GT _RC-FAM 64 + _RTE-FE.BYTES-A !
0 0 RTE-CATALOG-STORAGE-DISJOINT? _RC-A
1 0 RTE-CATALOG-STORAGE-DISJOINT? 0= _RC-A
-4 8 RTE-CATALOG-STORAGE-DISJOINT? 0= _RC-A
_RTE-RC-BATCH 8 RTE-CATALOG-STORAGE-DISJOINT? 0= _RC-A
_RTE-HPV-OWNED-START 8 RTE-CATALOG-STORAGE-DISJOINT? 0= _RC-A
\ Reject nested aliases before the first catalog scratch store.
_RTE-RC-BATCH @ _RC-A0 !
_RTE-RC-CATALOG _RC-FAM _RTE-FE.BYTES-A !
_RC-BATCH RTE-FAMILY-BATCH-VALID? 0= _RC-A
_RTE-RC-BATCH @ _RC-A0 @ = _RC-A
_RC-CT _RC-FAM _RTE-FE.BYTES-A !
_RC-CAT _RC-COPY 56 MOVE _RC-FAM _RC-COPY 56 + 384 MOVE
_RC-PI _RC-COPY 440 + 184 MOVE
_RC-VALID
_RC-CAT 56 _RC-COPY 56 COMPARE 0= _RC-A
_RC-FAM 384 _RC-COPY 56 + 384 COMPARE 0= _RC-A
_RC-PI 184 _RC-COPY 440 + 184 COMPARE 0= _RC-A
\ No region is invented for a standalone immutable SERIES history.
_RC-FAM 256 + _RC-FAM 64 MOVE 64 _RC-BATCH _RTE-FB.FAMILIES-U !
0 _RC-CAT _RTE-RC.REGIONS-A ! 0 _RC-CAT _RTE-RC.REGIONS-U ! _RC-VALID
\ Empty history uses the canonical empty sample pair, no synthetic sample.
0 _RC-YI _RTE-SERIES.SAMPLES-A ! 0 _RC-YI _RTE-SERIES.SAMPLES-U !
0 _RC-FAM _RTE-FE.BYTES-A ! 0 _RC-FAM _RTE-FE.BYTES-U ! _RC-VALID
_RC-YT _RC-FAM _RTE-FE.BYTES-A _RC-MUTATE
_RC-YT _RC-YI _RTE-SERIES.SAMPLES-A _RC-MUTATE
_RC-VALID _RC-DONE
''', minimum=19, extra_sources=MODULES, marker="CATALOG")


def test_pane_signed_geometry_uint32_edges_and_strict_utf8():
    run_series(PRELUDE + r'''
_RC-PI RTE-PANE-VALID? _RC-A
\ All shape checks use i32/u32 domain checks before arithmetic.
2147483648 _RC-PI _RTE-PANE.ROW ! _RC-PI RTE-PANE-VALID? 0= _RC-A
-2147483648 _RC-PI _RTE-PANE.ROW ! _RC-PI RTE-PANE-VALID? _RC-A
-2147483649 _RC-PI _RTE-PANE.ROW ! _RC-PI RTE-PANE-VALID? 0= _RC-A
0 _RC-PI _RTE-PANE.ROW !
4294967295 _RC-PI _RTE-PANE.WIDTH ! _RC-PI RTE-PANE-VALID? _RC-A
4294967296 _RC-PI _RTE-PANE.WIDTH ! _RC-PI RTE-PANE-VALID? 0= _RC-A
40 _RC-PI _RTE-PANE.WIDTH !
128 _RC-PT C! _RC-PI RTE-PANE-VALID? 0= _RC-A
194 _RC-PT C! 133 _RC-PT 1+ C! 2 _RC-PI _RTE-PANE.TITLE-U !
_RC-PI RTE-PANE-VALID? 0= _RC-A
226 _RC-PT C! 128 _RC-PT 1+ C! 168 _RC-PT 2 + C! 3 _RC-PI _RTE-PANE.TITLE-U !
_RC-PI RTE-PANE-VALID? 0= _RC-A
80 _RC-PT C! 1 _RC-PI _RTE-PANE.TITLE-U ! _RC-PI RTE-PANE-VALID? _RC-A
_RTE-RC-REGION _RC-PI _RTE-PANE.TITLE-A ! _RC-PI RTE-PANE-VALID? 0= _RC-A
_RC-PI _RC-PI _RTE-PANE.TITLE-A ! _RC-PI RTE-PANE-VALID? 0= _RC-A
_RC-PT _RC-PI _RTE-PANE.TITLE-A !
0 _RC-PI _RTE-PANE.TITLE-U ! _RC-PI RTE-PANE-VALID? 0= _RC-A
0 _RC-PI _RTE-PANE.TITLE-A ! _RC-PI RTE-PANE-VALID? _RC-A
_RC-DONE
''', minimum=14, extra_sources=MODULES, marker="CATALOG")


def test_public_span_enumeration_is_stack_only_and_exact():
    run_series(PRELUDE + r'''
_RTE-RC-BATCH @ _RC-A0 ! _RTE-RC-FAMILY @ _RC-A1 !
_RC-BATCH RTE-FAMILY-BATCH-FIXED? _RC-A
_RC-BATCH RTE-FAMILY-BATCH-SPAN-COUNT 34 = _RC-A
0 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ 72 = _RC-A _RC-BATCH = _RC-A
1 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ 56 = _RC-A _RC-CAT = _RC-A
2 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ 288 = _RC-A _RC-REG = _RC-A
3 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ 384 = _RC-A _RC-FAM = _RC-A
4 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ 144 = _RC-A _RC-CP = _RC-A
5 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ 200 = _RC-A _RC-CI = _RC-A
6 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ 1 = _RC-A _RC-CT = _RC-A
7 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ OR 0= _RC-A
8 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ OR 0= _RC-A
12 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ 16 = _RC-A _RC-REF = _RC-A
18 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ 96 = _RC-A _RC-IR = _RC-A
31 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ 1 = _RC-A _RC-PT = _RC-A
34 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ OR 0= _RC-A
-1 _RC-BATCH RTE-FAMILY-BATCH-SPAN@ OR 0= _RC-A
_RTE-RC-BATCH @ _RC-A0 @ = _RC-A _RTE-RC-FAMILY @ _RC-A1 @ = _RC-A
_RC-VALID _RC-DONE
''', minimum=28, extra_sources=MODULES, marker="CATALOG")


def test_series_neutral_extent_is_bytes_for_both_timestamp_modes():
    run_series(PRELUDE + r'''
_RC-VALID
8 _RC-YI _RTE-SERIES.SAMPLES-U ! 8 _RC-FAM 256 + _RTE-FE.BYTES-U ! _RC-VALID
0 _RC-YI _RTE-SERIES.MODE ! _RC-INVALID
16 _RC-YI _RTE-SERIES.SAMPLES-U ! 16 _RC-FAM 256 + _RTE-FE.BYTES-U ! _RC-VALID
8 _RC-FAM 256 + _RTE-FE.BYTES-U _RC-MUTATE
2 _RC-YI _RTE-SERIES.SAMPLES-U _RC-MUTATE
1 _RC-YI _RTE-SERIES.MODE ! _RC-VALID
_RC-DONE
''', minimum=7, extra_sources=MODULES, marker="CATALOG")
