"""Production SERIES publisher: complete copied graphs, independent IDs and reuse."""
from test_data_graphics_series import series_runtime
import re

def run_series(program,minimum=1,extra_sources=()):
    runtime=series_runtime(extra_sources)
    runtime.evaluate(program.encode(),source_name='producer-series-proof',step_budget=40_000_000)
    output=runtime.drain_uart_output().decode(errors='replace')
    match=re.search(r'SERIES MODEL PASS\s+(\d+)\s+0',output)
    if not match: print(output)
    assert match and int(match[1])>=minimum, output
    assert runtime.main_context.data.snapshot()==()
    assert runtime.main_context.returns.snapshot()==()
    return runtime

from test_rich_terminal_uidl_series_planner import PRELUDE as GRAPH

PRODUCER=("tui/rich-terminal/hybrid-screen-producer.f",)

PRELUDE=GRAPH+r'''
CREATE _PP-PM RTHP-SIZE 7 + ALLOT : _PP-P _PP-PM 7 + -8 AND ;
VARIABLE _PP-SIZE VARIABLE _PP-ARENA VARIABLE _PP-BANK VARIABLE _PP-OTHER
VARIABLE _PP-REC VARIABLE _PP-X VARIABLE _PP-SAMPLES
CREATE _PP-FM RTE-FACADE-SIZE 7 + ALLOT : _PP-F _PP-FM 7 + -8 AND ;
: _PP-DISJOINT DROP 2DROP -1 ;
: _PP-CALLBACK 2DROP RTE-S-OK ;
: _PP-FACADE
    _PP-F RTE-FACADE-SIZE 0 FILL
    _RTE-MAGIC _PP-F ! RTE-FACADE-SIZE _PP-F _RTE-F.SIZE !
    _PP-F _PP-F _RTE-F.SELF ! 1 _PP-F _RTE-F.CONTEXT !
    RTE-FACADE-SIZE 48 DO ['] _PP-CALLBACK _PP-F I + ! 8 +LOOP
    ['] _PP-DISJOINT _PP-F _RTE-F.DISJOINT-XT !
    _PP-F _PP-P _RTHP.FACADE ! ;
: _PP-INIT
    _PP-P RTHP-SIZE 0 FILL
    1 2 64 256 4096 0 0 80 24 RTHP-STORAGE-BYTES DUP _PP-SIZE !
    HERE 7 + -8 AND DUP _PP-ARENA ! SWAP 7 + ALLOT DROP
    _PP-ARENA @ _PP-SIZE @ 0 FILL
    _PP-ARENA @ _PP-P _RTHP.ARENA-A ! _PP-SIZE @ _PP-P _RTHP.ARENA-U !
    1 _PP-P _RTHP.MAX-DOCUMENTS ! 2 _PP-P _RTHP.MAX-RECORDS !
    64 _PP-P _RTHP.MAX-TEXT ! 6 _PP-P _RTHP.MAX-CONTROLS !
    256 _PP-P _RTHP.MAX-COLLECTION-NATIVE ! 4 _PP-P _RTHP.MAX-COLLECTIONS !
    8 _PP-P _RTHP.MAX-COLLECTION-DESCRIPTORS !
    4096 _PP-P _RTHP.MAX-DGRAPH-NATIVE ! 2 _PP-P _RTHP.MAX-DGRAPH-DESCRIPTORS !
    2 _PP-P _RTHP.MAX-INSTRUMENT-REGIONS ! 32 _PP-P _RTHP.MAX-INSTRUMENTS !
    56 _PP-P _RTHP.MAX-SERIES ! 80 _PP-P _RTHP.MAX-COLS ! 24 _PP-P _RTHP.MAX-ROWS !
    80 _PP-P _RTHP.COLS ! 24 _PP-P _RTHP.ROWS !
    88 _PP-P _RTHP.OWNER ! 99 _PP-P _RTHP.OWNER-GEN !
    999 _PP-P _RTHP.REGION ! 999 _PP-P _RTHP.NEXT-REGION !
    2000 _PP-P _RTHP.FIRST-OBJECT ! 2000 _PP-P _RTHP.NEXT-OBJECT !
    3000 _PP-P _RTHP.FIRST-SERIES ! 3000 _PP-P _RTHP.NEXT-SERIES !
    1 _PP-P _RTHP.DOCUMENT-COUNT !
    _PP-P _RTHP-LAYOUT _PP-FACADE
    1 _PP-P _RTHP.ATTEMPT ! 9 _PP-P _RTHP.SOURCE-GEN !
    9 _PP-P _RTHP.SURFACE-GEN ! 9 _PP-P _RTHP.SOURCE-DRAW !
    _RP-L _PP-P _RTHP.LIMITS RTE-LIMITS-SIZE MOVE
    _PP-P _RTHP.SOURCE-DIR-A @ DUP RUHA-DOCUMENT-SIZE 0 FILL
    77 OVER _RUHA-D.TOKEN ! 1 OVER _RUHA-D.SLOT-ID !
    24 OVER _RUHA-D.HEIGHT ! 80 OVER _RUHA-D.WIDTH !
    320 OVER _RUHA-D.DGRAPH-DESCRIPTOR-U ! _RP-TOTAL @ SWAP _RUHA-D.DGRAPH-NATIVE-U !
    RUHA-DOCUMENT-SIZE _PP-P _RTHP.SOURCE-DIR-USED !
    _RP-D _PP-P _RTHP.DGRAPH-DESCRIPTORS-A @ 320 MOVE
    320 _PP-P _RTHP.DGRAPH-DESCRIPTORS-USED !
    _RP-M _PP-P _RTHP.DGRAPH-NATIVE-A @ _RP-TOTAL @ MOVE
    _RP-TOTAL @ _PP-P _RTHP.DGRAPH-NATIVE-USED !
    2 _PP-P _RTHP.SOURCE-DGRAPH-COUNT ! ;
: _PP-BUILD _PP-P _RTHP-BUILD-INSTRUMENTS _RP-OK ;
: _PP-ADMIT
    _PP-P _RTHP-WRAP-HYBRID
    _PP-P _RTHP.HYBRID _PP-P _RTHP.ADMISSION _PP-F
        RTE-HYBRID-PREFLIGHT _RP-OK
    _PP-P _RTHP-SERIES-FIXED? _RP-A ;
: _PP-PACK
    _PP-P _RTHP.TARGET0-A @ _PP-BANK !
    _PP-P _RTHP.TARGET1-A @ _PP-OTHER !
    80 _PP-BANK @ _RTHP-TB.COLS ! 24 _PP-BANK @ _RTHP-TB.ROWS !
    1 _PP-BANK @ _RTHP-TB.DOCUMENT-COUNT !
    88 _PP-BANK @ _RTHP-TB.OWNER ! 99 _PP-BANK @ _RTHP-TB.GENERATION !
    999 _PP-BANK @ _RTHP-TB.REGION ! 2000 _PP-BANK @ _RTHP-TB.FIRST-OBJECT !
    _PP-P _RTHP.INSTRUMENT-COUNT @ _PP-BANK @ _RTHP-TB.INSTRUMENT-COUNT !
    _PP-P _RTHP.INSTRUMENT-REGION-COUNT @ _PP-BANK @ _RTHP-TB.INSTRUMENT-REGION-COUNT !
    _PP-P _RTHP.INSTRUMENT-UNITS-USED @ _PP-BANK @ _RTHP-TB.INSTRUMENT-UNIT-BYTES !
    _PP-P _RTHP.SERIES-COUNT @ _PP-BANK @ _RTHP-TB.SERIES-COUNT !
    _PP-P _RTHP.FIRST-SERIES @ _PP-BANK @ _RTHP-TB.FIRST-SERIES !
    _PP-P _RTHP.SERIES-SAMPLES-USED @ _PP-BANK @ _RTHP-TB.SERIES-SAMPLE-BYTES !
    _PP-P _RTHP.SERIES-SLOTS @ _PP-BANK @ _RTHP-TB.SERIES-SLOTS !
    _PP-P _RTHP.SERIES-CHUNKS @ _PP-BANK @ _RTHP-TB.SERIES-CHUNKS !
    _PP-P _RTHP.SERIES-HISTORY-MAX @ _PP-BANK @ _RTHP-TB.SERIES-HISTORY-MAX !
    _PP-P _RTHP.SERIES-CHUNK-MAX @ _PP-BANK @ _RTHP-TB.SERIES-CHUNK-MAX !
    _PP-P _RTHP.SERIES-CHUNK-BYTES-MAX @ _PP-BANK @ _RTHP-TB.SERIES-CHUNK-BYTES-MAX !
    _PP-P _RTHP.WAVEFORM-COUNT @ _PP-BANK @ _RTHP-TB.WAVEFORM-COUNT !
    _PP-BANK @ _PP-P _RTHP-PACK-ADMITTED-CANDIDATE _RP-A
    _PP-BANK @ _PP-P _RTHP-PACKED-BANK? _RP-A
    _PP-BANK @ _RTHP-PACK-SERIES-A _PP-REC !
    _PP-BANK @ _RTHP-PACK-SERIES-CORR-A _PP-X !
    _PP-BANK @ _RTHP-PACK-SERIES-SAMPLES-A _PP-SAMPLES ! ;
_PP-INIT
'''


def test_producer_complete_graph_series_summary_packing_and_independent_lifetime():
    run_series(PRELUDE+r'''
_PP-BUILD
_PP-P _RTHP.INSTRUMENT-COUNT @ 5 = _RP-A
_PP-P _RTHP.SERIES-COUNT @ 2 = _RP-A
_PP-P _RTHP.SERIES-SLOTS @ 16 = _RP-A
_PP-P _RTHP.SERIES-CHUNKS @ 4 = _RP-A
_PP-P _RTHP.SERIES-SAMPLES-USED @ 72 = _RP-A
_PP-P _RTHP.WAVEFORM-COUNT @ 2 = _RP-A
_PP-P _RTHP.SERIES-LAST @ 3001 = _RP-A
_PP-P _RTHP.OMITTED-GRAPHS-USED @ 0= _RP-A
_PP-P _RTHP-OMITTED-DISJOINT? _RP-A
_PP-ADMIT _PP-PACK
_PP-REC @ _RTE-SERIES.SAMPLES-A @ 0= _RP-A
_PP-REC @ 88 + _RTE-SERIES.SAMPLES-A @ 24 = _RP-A
_PP-SAMPLES @ 24 _RP-INPUT 24 COMPARE 0= _RP-A
_PP-SAMPLES @ 24 + 48 _RP-INPUT 48 COMPARE 0= _RP-A
_PP-P _RTHP.SERIES-SAMPLES-A @ 72 0 FILL
_PP-P _RTHP.DGRAPH-NATIVE-A @ _RP-TOTAL @ 0 FILL
_PP-SAMPLES @ 24 _RP-INPUT 24 COMPARE 0= _RP-A
_PP-SAMPLES @ 24 + 48 _RP-INPUT 48 COMPARE 0= _RP-A
_RP-DONE
''',minimum=38,extra_sources=PRODUCER)


def test_series_reuse_normalizes_independent_namespace_and_rejects_sample_changes():
    run_series(PRELUDE+r'''
_PP-BUILD _PP-ADMIT _PP-PACK
_PP-BANK @ _PP-OTHER @ _PP-P _RTHP-TARGET-BANK-BYTES? DROP MOVE
4000 _PP-OTHER @ _RTHP-TB.FIRST-SERIES !
1999 _PP-OTHER @ _RTHP-TB.REGION ! 3000 _PP-OTHER @ _RTHP-TB.FIRST-OBJECT !
: _PP-RENUMBER
    2 0 DO
        4000 I + _PP-OTHER @ _RTHP-PACK-SERIES-A I 88 * + _RTE-SERIES.ID !
        4000 I + _PP-OTHER @ _RTHP-PACK-SERIES-CORR-A I 80 * + 64 + !
        2000 _PP-OTHER @ _RTHP-PACK-SERIES-CORR-A I 80 * + 56 + !
        2000 I + _PP-OTHER @ _RTHP-PACK-INSTRUMENT-REGIONS-A I 96 * + !
    LOOP
    5 0 DO
        _PP-OTHER @ _RTHP-PACK-INSTRUMENTS-A I 216 * +
        1000 OVER _RTE-INSTRUMENT.ID +! 1000 OVER _RTE-INSTRUMENT.REGION +!
        DUP _RTE-INSTRUMENT.KIND @ RTE-INSTRUMENT-WAVEFORM = IF
            1000 OVER _RTE-INSTRUMENT.SERIES-ID +!
        THEN DROP
        _PP-OTHER @ _RTHP-PACK-INSTRUMENT-CORR-A I 80 * +
        1000 OVER 56 + +! 1000 SWAP 64 + +!
    LOOP ;
_PP-RENUMBER
_PP-BANK @ _PP-OTHER @ 0 _RTHP-INSTRUMENTS-REUSABLE? _RP-A
_PP-BANK @ _PP-OTHER @ -1 _RTHP-INSTRUMENTS-REUSABLE? 0= _RP-A
_PP-BANK @ _PP-OTHER @ _RTHP-INSTRUMENTS-NORMALIZE
999 _PP-OTHER @ _RTHP-TB.REGION !
_PP-BANK @ _PP-OTHER @ -1 _RTHP-INSTRUMENTS-REUSABLE? _RP-A
_PP-OTHER @ _RTHP-TB.FIRST-SERIES @ 3000 = _RP-A
_PP-OTHER @ _RTHP-PACK-SERIES-SAMPLES-A DUP @ _PP-X ! 1 OVER +!
_PP-BANK @ _PP-OTHER @ -1 _RTHP-INSTRUMENTS-REUSABLE? 0= _RP-A
_PP-X @ SWAP !
_PP-BANK @ _PP-OTHER @ -1 _RTHP-INSTRUMENTS-REUSABLE? _RP-A
1 _PP-OTHER @ _RTHP-PACK-SERIES-CORR-A 24 + +!
_PP-BANK @ _PP-OTHER @ -1 _RTHP-INSTRUMENTS-REUSABLE? 0= _RP-A
_RP-DONE
''',minimum=30,extra_sources=PRODUCER)


def test_series_missing_capability_omits_complete_graph_and_keeps_unrelated_claims():
    run_series(PRELUDE+r'''
9 _PP-P _RTHP.LIMITS _RTE-L.FEATURES !
0 _PP-P _RTHP.LIMITS _RTE-L.SERIES !
0 _PP-P _RTHP.LIMITS _RTE-L.SAMPLES-APPEND !
0 _PP-P _RTHP.LIMITS _RTE-L.SERIES-HISTORY !
0 _PP-P _RTHP.LIMITS _RTE-L.SAMPLE-SLOTS !
_PP-BUILD
_PP-P _RTHP.SERIES-COUNT @ 0= _RP-A
_PP-P _RTHP.SERIES-SAMPLES-USED @ 0= _RP-A
_PP-P _RTHP.INSTRUMENT-COUNT @ 1 = _RP-A
_PP-P _RTHP.INSTRUMENT-LAST @ 2000 = _RP-A
_PP-P _RTHP.CLAIMS-USED @ RUCL-CLAIM-SIZE = _RP-A
_PP-P _RTHP.OMITTED-GRAPHS-USED @ 32 = _RP-A
_PP-P _RTHP.OMITTED-GRAPHS-A @ DUP @ 1 = _RP-A
DUP 8 + @ 2 = _RP-A DUP 16 + @ 6 = _RP-A 24 + @ 19 = _RP-A
_PP-P _RTHP-OMITTED-DISJOINT? _RP-A
1 _PP-P _RTHP.CLAIMS-A @ _RUCL-C.ROW0 !
2 _PP-P _RTHP.CLAIMS-A @ _RUCL-C.COL0 !
3 _PP-P _RTHP.CLAIMS-A @ _RUCL-C.ROW1 !
4 _PP-P _RTHP.CLAIMS-A @ _RUCL-C.COL1 !
_PP-P _RTHP-OMITTED-DISJOINT? 0= _RP-A
_RP-DONE
''',minimum=29,extra_sources=PRODUCER)


def test_complete_16000_sample_history_is_owned_and_payload_chunked_without_decimation():
    prelude = PRELUDE.replace("_RP-MM 4103", "_RP-MM 131079").replace(
        "_RP-INPUTM 55", "_RP-INPUTM 128007").replace("4096", "131072").replace(
        "32 _PP-P _RTHP.MAX-INSTRUMENTS", "1024 _PP-P _RTHP.MAX-INSTRUMENTS").replace(
        "56 _PP-P _RTHP.MAX-SERIES", "1820 _PP-P _RTHP.MAX-SERIES")
    run_series(prelude+r'''
: _PP-FULL
    16000 0 DO I 16000 - _RP-INPUT I 8 * + ! LOOP
    _RP-M 131072 _RP-B UDG-BUILDER-INIT _RP-OK
    100 0 0 5 17 3 _RP-B UDG-BEGIN _RP-OK
    2 16000 1 125 0 _RP-INPUT 16000 _RP-B UDG-SERIES _RP-OK
    3 0 0 5 17 0 1 2 -32768 32767 0x5FD7FFFF 0x4E4E4EFF 0 1 _RP-B UDG-WAVEFORM _RP-OK
    _RP-B UDG-END _RP-OK _RP-B UDG-BUILDER-FINISH _RP-OK _RP-G1 ! ;
_PP-FULL _RP-BUILD2 _RP-DESCRIPTORS
16000 _RP-L _RTE-L.SERIES-HISTORY ! 32000 _RP-L _RTE-L.SAMPLE-SLOTS !
64 _RP-L _RTE-L.SAMPLES-APPEND ! 500000 _RP-L _RTE-L.UPDATE-BYTES !
_PP-INIT _PP-BUILD _PP-ADMIT _PP-PACK
_PP-P _RTHP.SERIES-COUNT @ 1 = _RP-A
_PP-P _RTHP.SERIES-SAMPLES-USED @ 128000 = _RP-A
_PP-P _RTHP.SERIES-SLOTS @ 16000 = _RP-A
_PP-P _RTHP.SERIES-CHUNKS @ 593 = _RP-A
_PP-P _RTHP.SERIES-CHUNK-MAX @ 27 = _RP-A
_PP-P _RTHP.SERIES-CHUNK-BYTES-MAX @ 216 = _RP-A
_PP-P _RTHP.SERIES-A @ _RTE-SERIES.INTERVAL-US @ 125 = _RP-A
_PP-P _RTHP-EMIT-SERIES _RP-OK
_PP-SAMPLES @ 128000 _RP-INPUT 128000 COMPARE 0= _RP-A
_PP-P _RTHP.DGRAPH-NATIVE-A @ _PP-P _RTHP.DGRAPH-NATIVE-USED @ 0 FILL
_PP-P _RTHP.SERIES-SAMPLES-A @ 128000 0 FILL _RP-INPUT 128000 0 FILL
: _PP-COPIED 16000 0 DO _PP-SAMPLES @ I 8 * + @ I 16000 - = _RP-A LOOP ;
_PP-COPIED _RP-DONE
''',minimum=16040,extra_sources=PRODUCER)


def test_empty_history_packs_canonical_zero_spans_and_reuses_without_samples():
    run_series(PRELUDE+r'''
: _PP-EMPTY
    _RP-M 4096 _RP-B UDG-BUILDER-INIT _RP-OK
    100 0 0 5 17 3 _RP-B UDG-BEGIN _RP-OK
    2 8 1 125 0 0 0 _RP-B UDG-SERIES _RP-OK
    _RP-B UDG-END _RP-OK _RP-B UDG-BUILDER-FINISH _RP-OK _RP-G1 ! ;
_PP-EMPTY _RP-BUILD2 _RP-DESCRIPTORS _PP-INIT _PP-BUILD _PP-ADMIT _PP-PACK
_PP-P _RTHP.SERIES-COUNT @ 1 = _RP-A
_PP-P _RTHP.SERIES-SAMPLES-USED @ 0= _RP-A
_PP-P _RTHP.SERIES-CHUNKS @ 0= _RP-A
_PP-P _RTHP.SERIES-SLOTS @ 8 = _RP-A
_PP-REC @ _RTE-SERIES.SAMPLES-A @ 0= _RP-A
_PP-REC @ _RTE-SERIES.SAMPLES-U @ 0= _RP-A
_PP-REC @ _RTE-SERIES.CHUNK-SAMPLES @ 0= _RP-A
_PP-X @ 56 + @ 0= _RP-A
_PP-BANK @ _PP-OTHER @ _PP-P _RTHP-TARGET-BANK-BYTES? DROP MOVE
_PP-BANK @ _PP-OTHER @ -1 _RTHP-INSTRUMENTS-REUSABLE? _RP-A
_PP-P _RTHP-EMIT-SERIES _RP-OK _RP-DONE
''',minimum=40,extra_sources=PRODUCER)


def test_series_identity_frontier_waits_for_accepted_hidden_start_and_survives_reveal_retry():
    run_series(PRELUDE+r'''
VARIABLE _PP-US VARIABLE _PP-UR
: _PP-UPDATE DROP _PP-US @ _PP-UR @ ;
: _PP-CANCEL DROP RTE-S-OK ;
: _PP-START-STEP
    _RTHP-PH-READY-REVEAL _RTHP-PH-READY-START -1 _PP-P _RTHP-STEP-SEALED ;
_PP-BUILD _PP-ADMIT _PP-PACK
' _PP-UPDATE _PP-F _RTE-F.UPDATE-STATE-XT !
' _PP-CANCEL _PP-F _RTE-F.RETAINED-CANCEL-XT !
_PP-BANK @ _PP-P _RTHP.TARGET-PENDING !
1 _PP-BANK @ _RTHP-TB.VALID !
RTE-UPDATE-SEALED _PP-US ! RTE-S-OK _PP-UR !
_PP-START-STEP -1 = _RP-A 0= _RP-A SCB-S-OK = _RP-A
_PP-P _RTHP.NEXT-SERIES @ 3000 = _RP-A
RTE-UPDATE-AWAITING _PP-US !
_PP-START-STEP 0= _RP-A -1 = _RP-A SCB-S-OK = _RP-A
_PP-P _RTHP.NEXT-SERIES @ 3000 = _RP-A
RTE-UPDATE-SEALED _PP-US ! RTE-S-STALE _PP-UR !
_PP-START-STEP -1 = _RP-A 0= _RP-A SCB-S-OK = _RP-A
_PP-P _RTHP.NEXT-SERIES @ 3000 = _RP-A
_PP-P _RTHP.TARGET-PENDING @ 0= _RP-A
RTE-UPDATE-IDLE _PP-US ! RTE-S-OK _PP-UR !
_PP-START-STEP -1 = _RP-A 0= _RP-A SCB-S-OK = _RP-A
_PP-P _RTHP.NEXT-SERIES @ 3002 = _RP-A
_PP-P _RTHP.NEXT-OBJECT @ 2005 = _RP-A
_PP-P _RTHP.NEXT-REGION @ 1002 = _RP-A
RTE-UPDATE-SEALED _PP-US ! RTE-S-STALE _PP-UR !
_RTHP-PH-LIVE _RTHP-PH-READY-REVEAL 0 _PP-P _RTHP-STEP-SEALED
-1 = _RP-A 0= _RP-A SCB-S-OK = _RP-A
_PP-P _RTHP.NEXT-SERIES @ 3002 = _RP-A _RP-DONE
''',minimum=45,extra_sources=PRODUCER)


def test_separate_documents_share_series_frontier_and_reserved_capacity_without_cross_graph_claims():
    prelude=PRELUDE.replace("1 2 64 256 4096", "2 2 64 256 4096").replace(
        "1 _PP-P _RTHP.MAX-DOCUMENTS", "2 _PP-P _RTHP.MAX-DOCUMENTS")
    run_series(prelude+r'''
: _PP-SECOND
    _RP-M _RP-G1 @ + 4096 _RP-G1 @ - _RP-B UDG-BUILDER-INIT _RP-OK
    200 0 0 2 8 3 _RP-B UDG-BEGIN _RP-OK
    2 8 1 125 0 _RP-INPUT 2 _RP-B UDG-SERIES _RP-OK
    3 0 0 2 8 0 1 2 -32768 32767 0x5FD7FFFF 0x4E4E4EFF 0 1 _RP-B UDG-WAVEFORM _RP-OK
    _RP-B UDG-END _RP-OK _RP-B UDG-BUILDER-FINISH _RP-OK _RP-G2 !
    _RP-G1 @ _RP-G2 @ + _RP-TOTAL ! ;
: _PP-TWO-DOCS
    2 _PP-P _RTHP.DOCUMENT-COUNT !
    _PP-P _RTHP.SOURCE-DIR-A @ DUP RUHA-DOCUMENT-SIZE + RUHA-DOCUMENT-SIZE MOVE
    _PP-P _RTHP.SOURCE-DIR-A @ DUP 160 SWAP _RUHA-D.DGRAPH-DESCRIPTOR-U !
    DUP _RP-G1 @ SWAP _RUHA-D.DGRAPH-NATIVE-U !
    RUHA-DOCUMENT-SIZE +
    78 OVER _RUHA-D.TOKEN ! 2 OVER _RUHA-D.SLOT-ID !
    160 OVER _RUHA-D.DGRAPH-DESCRIPTOR-OFF ! 160 OVER _RUHA-D.DGRAPH-DESCRIPTOR-U !
    _RP-G1 @ OVER _RUHA-D.DGRAPH-NATIVE-OFF ! _RP-G2 @ SWAP _RUHA-D.DGRAPH-NATIVE-U !
    2 RUHA-DOCUMENT-SIZE * _PP-P _RTHP.SOURCE-DIR-USED !
    0 _PP-P _RTHP.DGRAPH-DESCRIPTORS-A @ 160 + _UDGSN-D.NATIVE-O ! ;
_PP-SECOND _RP-DESCRIPTORS _PP-INIT _PP-TWO-DOCS _PP-BUILD _PP-ADMIT
_PP-P _RTHP.SERIES-COUNT @ 3 = _RP-A
_PP-P _RTHP.SERIES-SLOTS @ 24 = _RP-A
_PP-P _RTHP.SERIES-SAMPLES-USED @ 88 = _RP-A
_PP-P _RTHP.SERIES-A @ 176 + _RTE-SERIES.ID @ 3002 = _RP-A
_PP-P _RTHP.SERIES-CORR-A @ 160 + DUP @ 78 = _RP-A
DUP 32 + @ 901 = _RP-A 64 + @ 3002 = _RP-A
_PP-P _RTHP.INSTRUMENTS-A @ 864 + _RTE-INSTRUMENT.SERIES-ID @ 3002 = _RP-A
\ Complete first-document reservations omit the second graph at the shared bound.
_PP-INIT _PP-TWO-DOCS 16 _PP-P _RTHP.LIMITS _RTE-L.SAMPLE-SLOTS !
_PP-BUILD _PP-ADMIT
_PP-P _RTHP.SERIES-COUNT @ 2 = _RP-A
_PP-P _RTHP.SERIES-SLOTS @ 16 = _RP-A
_PP-P _RTHP.INSTRUMENT-COUNT @ 4 = _RP-A
_PP-P _RTHP.INSTRUMENT-LAST @ 2003 = _RP-A
_PP-P _RTHP.OMITTED-GRAPHS-USED @ 32 = _RP-A
_PP-P _RTHP.OMITTED-GRAPHS-A @ DUP @ 10 = _RP-A 8 + @ 7 = _RP-A
_PP-P _RTHP-OMITTED-DISJOINT? _RP-A _RP-DONE
''',minimum=48,extra_sources=PRODUCER)
