\ =====================================================================
\  core.f - Common caller-owned persistence types and accounting
\ =====================================================================
\  This module defines values shared by the neutral page, segment, root,
\  and store layers.  It performs no I/O and owns no mutable storage.
\  Every descriptor, counter set, record reference, and root value is
\  allocated by the caller.
\ =====================================================================

PROVIDED akashic-persist-core

REQUIRE ../utils/memory-span.f

\ One exact prototype contract.  These are operation results, not a
\ migration or compatibility namespace.
 0 CONSTANT PERSIST-S-OK
 1 CONSTANT PERSIST-S-ABSENT
 2 CONSTANT PERSIST-S-INVALID
 3 CONSTANT PERSIST-S-CAPACITY
 4 CONSTANT PERSIST-S-IO
 5 CONSTANT PERSIST-S-CORRUPT
 6 CONSTANT PERSIST-S-BUSY
 7 CONSTANT PERSIST-S-CONFLICT
 8 CONSTANT PERSIST-S-UNCERTAIN
 9 CONSTANT PERSIST-S-NOT-FOUND
10 CONSTANT PERSIST-S-FAULT

4096 CONSTANT PERSIST-PAGE-SIZE
64   CONSTANT PERSIST-RECORD-HEADER-SIZE
32   CONSTANT PERSIST-IDENTITY-SIZE
255  CONSTANT PERSIST-PATH-MAX
-1 1 RSHIFT CONSTANT PERSIST-MAX-SIGNED

\ Deterministic fault boundaries.  A configured callback receives
\     ( point ordinal context -- status )
\ and may also THROW.  Point zero means fault injection is disabled.
 0 CONSTANT PERSIST-FAULT-NONE
 1 CONSTANT PERSIST-FAULT-SEGMENT-WRITTEN
 2 CONSTANT PERSIST-FAULT-SEGMENT-VERIFIED
 3 CONSTANT PERSIST-FAULT-PAGE-WRITTEN
 4 CONSTANT PERSIST-FAULT-PAGE-VERIFIED
 5 CONSTANT PERSIST-FAULT-DATA-SYNCED
 6 CONSTANT PERSIST-FAULT-ROOT-WRITTEN
 7 CONSTANT PERSIST-FAULT-ROOT-SIZED
 8 CONSTANT PERSIST-FAULT-ROOT-SYNCED
 9 CONSTANT PERSIST-FAULT-ROOT-VERIFIED
10 CONSTANT PERSIST-FAULT-ROOT-PUBLISHED

\ ---------------------------------------------------------------------
\ Immutable segment-record reference
\ ---------------------------------------------------------------------

 0 CONSTANT _PREF-OFFSET
 8 CONSTANT _PREF-SPAN
16 CONSTANT _PREF-ORDINAL
24 CONSTANT PERSIST-REF-SIZE

: PREF.OFFSET   ( ref -- a ) _PREF-OFFSET + ;
: PREF.SPAN     ( ref -- a ) _PREF-SPAN + ;
: PREF.ORDINAL  ( ref -- a ) _PREF-ORDINAL + ;

: PERSIST-REF-INIT  ( ref -- )
    DUP 0= IF DROP EXIT THEN
    DUP PERSIST-REF-SIZE MSPAN-NONWRAPPING? 0= IF DROP EXIT THEN
    PERSIST-REF-SIZE 0 FILL ;

: PERSIST-REF-COPY  ( source destination -- )
    2DUP 0= SWAP 0= OR IF 2DROP EXIT THEN
    2DUP PERSIST-REF-SIZE MSPAN-NONWRAPPING? SWAP
        PERSIST-REF-SIZE MSPAN-NONWRAPPING? AND 0= IF 2DROP EXIT THEN
    PERSIST-REF-SIZE MOVE ;

: PERSIST-REF-VALID?  ( ref -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP PERSIST-REF-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP PREF.OFFSET @ 0< IF DROP 0 EXIT THEN
    DUP PREF.SPAN @ PERSIST-RECORD-HEADER-SIZE < IF DROP 0 EXIT THEN
    DUP PREF.ORDINAL @ 0> 0= IF DROP 0 EXIT THEN
    DUP PREF.OFFSET @ OVER PREF.SPAN @ +
    DUP 0< IF 2DROP 0 EXIT THEN
    SWAP PREF.OFFSET @ U< 0= ;

\ ---------------------------------------------------------------------
\ Atomic root value
\ ---------------------------------------------------------------------
\  The root knows only committed physical bounds and one opaque application
\  page.  Index, blob, applet, schema, and path policy live above it.

 0 CONSTANT _PROOTV-IDENTITY
32 CONSTANT _PROOTV-PAGE-COUNT
40 CONSTANT _PROOTV-SEGMENT-TAIL
48 CONSTANT _PROOTV-RECORD-COUNT
56 CONSTANT _PROOTV-APPLICATION-ROOT
64 CONSTANT _PROOTV-FLAGS
72 CONSTANT _PROOTV-RESERVED
96 CONSTANT PERSIST-ROOT-VALUE-SIZE

: PROOTV.IDENTITY          ( root -- a ) _PROOTV-IDENTITY + ;
: PROOTV.PAGE-COUNT        ( root -- a ) _PROOTV-PAGE-COUNT + ;
: PROOTV.SEGMENT-TAIL      ( root -- a ) _PROOTV-SEGMENT-TAIL + ;
: PROOTV.RECORD-COUNT      ( root -- a ) _PROOTV-RECORD-COUNT + ;
: PROOTV.APPLICATION-ROOT  ( root -- a ) _PROOTV-APPLICATION-ROOT + ;
: PROOTV.FLAGS             ( root -- a ) _PROOTV-FLAGS + ;
: PROOTV.RESERVED          ( root -- a ) _PROOTV-RESERVED + ;

: PERSIST-ROOT-VALUE-INIT  ( root -- )
    DUP 0= IF DROP EXIT THEN
    DUP PERSIST-ROOT-VALUE-SIZE MSPAN-NONWRAPPING? 0= IF DROP EXIT THEN
    DUP PERSIST-ROOT-VALUE-SIZE 0 FILL
    -1 SWAP PROOTV.APPLICATION-ROOT ! ;

: PERSIST-ROOT-VALUE-COPY  ( source destination -- )
    2DUP 0= SWAP 0= OR IF 2DROP EXIT THEN
    2DUP PERSIST-ROOT-VALUE-SIZE MSPAN-NONWRAPPING? SWAP
        PERSIST-ROOT-VALUE-SIZE MSPAN-NONWRAPPING? AND 0= IF 2DROP EXIT THEN
    PERSIST-ROOT-VALUE-SIZE MOVE ;

: _PERSIST-ZERO?  ( a u -- flag )
    0 ?DO DUP I + C@ IF DROP 0 UNLOOP EXIT THEN LOOP DROP -1 ;

: _PERSIST-IDENTITY-VALID?  ( identity -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    PERSIST-IDENTITY-SIZE _PERSIST-ZERO? 0= ;

: PERSIST-ROOT-VALUE-VALID?  ( root -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP PERSIST-ROOT-VALUE-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP PROOTV.IDENTITY _PERSIST-IDENTITY-VALID? 0= IF DROP 0 EXIT THEN
    DUP PROOTV.PAGE-COUNT @ 0< IF DROP 0 EXIT THEN
    DUP PROOTV.SEGMENT-TAIL @ 0< IF DROP 0 EXIT THEN
    DUP PROOTV.RECORD-COUNT @ 0< IF DROP 0 EXIT THEN
    DUP PROOTV.FLAGS @ IF DROP 0 EXIT THEN
    DUP PROOTV.RESERVED 24 _PERSIST-ZERO? 0= IF DROP 0 EXIT THEN
    DUP PROOTV.RECORD-COUNT @ 0= IF
        DUP PROOTV.SEGMENT-TAIL @ IF DROP 0 EXIT THEN
    ELSE
        DUP PROOTV.SEGMENT-TAIL @ 0> 0= IF DROP 0 EXIT THEN
        DUP PROOTV.RECORD-COUNT @
            OVER PROOTV.SEGMENT-TAIL @ PERSIST-RECORD-HEADER-SIZE /
            > IF DROP 0 EXIT THEN
    THEN
    DUP PROOTV.PAGE-COUNT @ 0= IF
        PROOTV.APPLICATION-ROOT @ -1 = EXIT
    THEN
    DUP PROOTV.APPLICATION-ROOT @ DUP 0< IF 2DROP 0 EXIT THEN
    SWAP PROOTV.PAGE-COUNT @ < ;

\ ---------------------------------------------------------------------
\ Per-store cumulative counters
\ ---------------------------------------------------------------------

  0 CONSTANT _PSTAT-PAGE-READS
  8 CONSTANT _PSTAT-PAGE-WRITES
 16 CONSTANT _PSTAT-ROOT-READS
 24 CONSTANT _PSTAT-ROOT-WRITES
 32 CONSTANT _PSTAT-SEGMENT-READS
 40 CONSTANT _PSTAT-SEGMENT-WRITES
 48 CONSTANT _PSTAT-BYTES-READ
 56 CONSTANT _PSTAT-BYTES-WRITTEN
 64 CONSTANT _PSTAT-VERIFICATIONS
 72 CONSTANT _PSTAT-COMPARISONS
 80 CONSTANT _PSTAT-CACHE-HITS
 88 CONSTANT _PSTAT-CACHE-MISSES
 96 CONSTANT _PSTAT-SYNCS
104 CONSTANT _PSTAT-FAULTS
112 CONSTANT _PSTAT-ALLOCATION-EVENTS
120 CONSTANT _PSTAT-ALLOCATION-LIVE
128 CONSTANT _PSTAT-ALLOCATION-PEAK
136 CONSTANT _PSTAT-WORKING-BYTES
144 CONSTANT PERSIST-STATS-SIZE

: PSTAT.PAGE-READS         ( stats -- a ) _PSTAT-PAGE-READS + ;
: PSTAT.PAGE-WRITES        ( stats -- a ) _PSTAT-PAGE-WRITES + ;
: PSTAT.ROOT-READS         ( stats -- a ) _PSTAT-ROOT-READS + ;
: PSTAT.ROOT-WRITES        ( stats -- a ) _PSTAT-ROOT-WRITES + ;
: PSTAT.SEGMENT-READS      ( stats -- a ) _PSTAT-SEGMENT-READS + ;
: PSTAT.SEGMENT-WRITES     ( stats -- a ) _PSTAT-SEGMENT-WRITES + ;
: PSTAT.BYTES-READ         ( stats -- a ) _PSTAT-BYTES-READ + ;
: PSTAT.BYTES-WRITTEN      ( stats -- a ) _PSTAT-BYTES-WRITTEN + ;
: PSTAT.VERIFICATIONS      ( stats -- a ) _PSTAT-VERIFICATIONS + ;
: PSTAT.COMPARISONS        ( stats -- a ) _PSTAT-COMPARISONS + ;
: PSTAT.CACHE-HITS         ( stats -- a ) _PSTAT-CACHE-HITS + ;
: PSTAT.CACHE-MISSES       ( stats -- a ) _PSTAT-CACHE-MISSES + ;
: PSTAT.SYNCS              ( stats -- a ) _PSTAT-SYNCS + ;
: PSTAT.FAULTS             ( stats -- a ) _PSTAT-FAULTS + ;
: PSTAT.ALLOCATION-EVENTS  ( stats -- a ) _PSTAT-ALLOCATION-EVENTS + ;
: PSTAT.ALLOCATION-LIVE    ( stats -- a ) _PSTAT-ALLOCATION-LIVE + ;
: PSTAT.ALLOCATION-PEAK    ( stats -- a ) _PSTAT-ALLOCATION-PEAK + ;
: PSTAT.WORKING-BYTES      ( stats -- a ) _PSTAT-WORKING-BYTES + ;

: PERSIST-STATS-INIT  ( stats -- )
    DUP 0= IF DROP EXIT THEN
    DUP PERSIST-STATS-SIZE MSPAN-NONWRAPPING? 0= IF DROP EXIT THEN
    PERSIST-STATS-SIZE 0 FILL ;

: PERSIST-STATS-VALID?  ( stats -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    PERSIST-STATS-SIZE MSPAN-NONWRAPPING? ;

: PERSIST-STATS-RESET  ( stats -- )
    PERSIST-STATS-INIT ;

: _PSTAT-ADD  ( u field -- )
    >R
    DUP 0< IF DROP PERSIST-MAX-SIGNED ELSE
        R@ @ DUP 0< IF DROP DROP PERSIST-MAX-SIGNED ELSE
            PERSIST-MAX-SIGNED OVER - 2 PICK < IF
                2DROP PERSIST-MAX-SIGNED
            ELSE
                +
            THEN
        THEN
    THEN
    R> ! ;

: _PSTAT-INC  ( field -- ) 1 SWAP _PSTAT-ADD ;

: _PSTAT-NOTE-PAGE-READ  ( bytes stats -- )
    DUP PSTAT.PAGE-READS _PSTAT-INC PSTAT.BYTES-READ _PSTAT-ADD ;
: _PSTAT-NOTE-PAGE-WRITE  ( bytes stats -- )
    DUP PSTAT.PAGE-WRITES _PSTAT-INC PSTAT.BYTES-WRITTEN _PSTAT-ADD ;
: _PSTAT-NOTE-ROOT-READ  ( bytes stats -- )
    DUP PSTAT.ROOT-READS _PSTAT-INC PSTAT.BYTES-READ _PSTAT-ADD ;
: _PSTAT-NOTE-ROOT-WRITE  ( bytes stats -- )
    DUP PSTAT.ROOT-WRITES _PSTAT-INC PSTAT.BYTES-WRITTEN _PSTAT-ADD ;
: _PSTAT-NOTE-SEGMENT-READ  ( bytes stats -- )
    DUP PSTAT.SEGMENT-READS _PSTAT-INC PSTAT.BYTES-READ _PSTAT-ADD ;
: _PSTAT-NOTE-SEGMENT-WRITE  ( bytes stats -- )
    DUP PSTAT.SEGMENT-WRITES _PSTAT-INC PSTAT.BYTES-WRITTEN _PSTAT-ADD ;
: _PSTAT-NOTE-VERIFY  ( stats -- ) PSTAT.VERIFICATIONS _PSTAT-INC ;
: _PSTAT-NOTE-COMPARE ( stats -- ) PSTAT.COMPARISONS _PSTAT-INC ;
: _PSTAT-NOTE-HIT     ( stats -- ) PSTAT.CACHE-HITS _PSTAT-INC ;
: _PSTAT-NOTE-MISS    ( stats -- ) PSTAT.CACHE-MISSES _PSTAT-INC ;
: _PSTAT-NOTE-SYNC    ( stats -- ) PSTAT.SYNCS _PSTAT-INC ;
: _PSTAT-NOTE-FAULT   ( stats -- ) PSTAT.FAULTS _PSTAT-INC ;
