\ =====================================================================
\  data-graphics.f -- Canonical renderer-neutral instrument widget
\ =====================================================================
\
\  DATA_GRAPHICS is the ordinary widget consumer of one immutable UDG
\  INSTRUMENT graph.  Applets own and rebuild that graph; this widget owns
\  only the representation scratch needed by its selected CELL renderer.
\  Optional rich capture copies the same graph reached through WDG-DRAW.
\
\  Descriptor (80 bytes):
\    +0..+32  common widget header
\    +40      borrowed UDG graph, or 0
\    +48      exact graph bytes
\    +56      renderer-owned formatting scratch, or 0
\    +64      exact scratch capacity
\    +72      nonzero allocation-lifetime instance token
\
\  Prefix: DGRAPH- (public), _DGRAPH- (private)
\ =====================================================================

PROVIDED akashic-tui-data-graphics

REQUIRE ../widget.f
REQUIRE ../draw.f
REQUIRE ../color.f
REQUIRE ../data-graphics-format.f
REQUIRE ../../text/utf8.f
REQUIRE ../../utils/memory-span.f

UDG-S-OK          CONSTANT DGRAPH-S-OK
UDG-S-UNSUPPORTED CONSTANT DGRAPH-S-UNSUPPORTED
UDG-S-CAPACITY    CONSTANT DGRAPH-S-CAPACITY
UDG-S-INVALID     CONSTANT DGRAPH-S-INVALID
4                 CONSTANT DGRAPH-S-ALLOC

CREATE _DGRAPH-OWNED-START
VARIABLE _DGRAPH-OWNED-LIMIT
0 _DGRAPH-OWNED-LIMIT !

40 CONSTANT _DGRAPH-O-MODEL-A
48 CONSTANT _DGRAPH-O-MODEL-U
56 CONSTANT _DGRAPH-O-SCRATCH-A
64 CONSTANT _DGRAPH-O-SCRATCH-U
72 CONSTANT _DGRAPH-O-INSTANCE
80 CONSTANT _DGRAPH-DESC-SIZE

DEFER _DGRAPH-DRAW
DEFER _DGRAPH-HANDLE

VARIABLE _DGRAPH-NEXT-INSTANCE
VARIABLE _DGRAPH-NEW-INSTANCE
0 _DGRAPH-NEXT-INSTANCE !
0 _DGRAPH-NEW-INSTANCE !

: _DGRAPH-CLAIM-INSTANCE  ( -- token )
    _DGRAPH-NEXT-INSTANCE @ DUP -1 =
        IF DROP 1 ELSE 1+ DUP 0= IF DROP 1 THEN THEN
    DUP _DGRAPH-NEXT-INSTANCE ! ;

: _DGRAPH-SPAN?  ( address bytes -- flag )
    DUP 0< IF 2DROP 0 EXIT THEN
    DUP 0= IF DROP 0= EXIT THEN
    OVER 0= IF 2DROP 0 EXIT THEN
    MSPAN-NONWRAPPING? ;

: DGRAPH-STORAGE-DISJOINT?  ( address bytes -- flag )
    DUP 0< IF 2DROP 0 EXIT THEN
    DUP 0= IF DROP 0= EXIT THEN
    OVER 0= IF 2DROP 0 EXIT THEN
    2DUP MSPAN-NONWRAPPING? 0= IF 2DROP 0 EXIT THEN
    _DGRAPH-OWNED-LIMIT @ DUP _DGRAPH-OWNED-START U< IF
        DROP 2DROP 0 EXIT
    THEN
    _DGRAPH-OWNED-START -
    _DGRAPH-OWNED-START SWAP
    MSPAN-OVERLAP? 0= ;

: _DGRAPH-GENUINE?  ( widget -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    DUP _DGRAPH-DESC-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP _WDG-O-TYPE + @ WDG-T-DATA-GRAPHICS <> IF DROP 0 EXIT THEN
    DUP _WDG-O-DRAW-XT + @ ['] _DGRAPH-DRAW <> IF DROP 0 EXIT THEN
    DUP _WDG-O-HANDLE-XT + @ ['] _DGRAPH-HANDLE <> IF DROP 0 EXIT THEN
    DUP _DGRAPH-O-INSTANCE + @ 0= IF DROP 0 EXIT THEN
    WDG-REGION DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    RGN-SIZE MSPAN-NONWRAPPING? ;

VARIABLE _DGRAPH-SD-A
VARIABLE _DGRAPH-SD-U
VARIABLE _DGRAPH-SD-W

: DGRAPH-DATA-GRAPHICS-STORAGE-DISJOINT?
    ( address bytes widget -- flag )
    >R
    2DUP DGRAPH-STORAGE-DISJOINT? 0= IF 2DROP R> DROP 0 EXIT THEN
    _DGRAPH-SD-U ! _DGRAPH-SD-A ! R> _DGRAPH-SD-W !
    _DGRAPH-SD-W @ _DGRAPH-GENUINE? 0= IF 0 EXIT THEN
    _DGRAPH-SD-A @ _DGRAPH-SD-U @
        _DGRAPH-SD-W @ _DGRAPH-DESC-SIZE MSPAN-OVERLAP? IF 0 EXIT THEN
    _DGRAPH-SD-W @ WDG-REGION ?DUP IF
        _DGRAPH-SD-A @ _DGRAPH-SD-U @ ROT RGN-SIZE
            MSPAN-OVERLAP? IF 0 EXIT THEN
    THEN
    _DGRAPH-SD-W @ _DGRAPH-O-MODEL-A + @ ?DUP IF
        _DGRAPH-SD-A @ _DGRAPH-SD-U @ ROT
        _DGRAPH-SD-W @ _DGRAPH-O-MODEL-U + @
            MSPAN-OVERLAP? IF 0 EXIT THEN
    THEN
    _DGRAPH-SD-W @ _DGRAPH-O-SCRATCH-A + @ ?DUP IF
        _DGRAPH-SD-A @ _DGRAPH-SD-U @ ROT
        _DGRAPH-SD-W @ _DGRAPH-O-SCRATCH-U + @
            MSPAN-OVERLAP? IF 0 EXIT THEN
    THEN
    -1 ;

: _DGRAPH-POS-U32?  ( value -- flag )
    DUP 0> SWAP 0x100000000 U< AND ;

: _DGRAPH-REGION-MATCHES?  ( widget -- flag )
    DUP WDG-REGION RGN-H DUP _DGRAPH-POS-U32? 0= IF
        2DROP 0 EXIT
    THEN
    OVER _DGRAPH-O-MODEL-A + @ UDG-ROOT-HEIGHT@ <> IF
        DROP 0 EXIT
    THEN
    DUP WDG-REGION RGN-W DUP _DGRAPH-POS-U32? 0= IF
        2DROP 0 EXIT
    THEN
    SWAP _DGRAPH-O-MODEL-A + @ UDG-ROOT-WIDTH@ = ;

: _DGRAPH-BOUND?  ( widget -- flag )
    DUP _DGRAPH-GENUINE? 0= IF DROP 0 EXIT THEN
    DUP _DGRAPH-O-MODEL-A + @ DUP 0= IF 2DROP 0 EXIT THEN
    OVER _DGRAPH-O-MODEL-U + @ _DGRAPH-SPAN? 0= IF DROP 0 EXIT THEN
    _DGRAPH-REGION-MATCHES? ;

\ =====================================================================
\  Min-safe signed decimal helpers shared by METER scratch sizing/draw
\ =====================================================================

VARIABLE _DGRAPH-N-VALUE
VARIABLE _DGRAPH-N-MAG
VARIABLE _DGRAPH-N-DIGITS
VARIABLE _DGRAPH-N-DST
VARIABLE _DGRAPH-N-CURSOR
VARIABLE _DGRAPH-N-SOURCE
VARIABLE _DGRAPH-N-REM
VARIABLE _DGRAPH-N-QUOT

: _DGRAPH-MAGNITUDE  ( n -- u )
    DUP 0< IF INVERT 1+ THEN ;

: _DGRAPH-U/10  ( u -- remainder quotient )
    _DGRAPH-N-SOURCE ! 0 _DGRAPH-N-REM ! 0 _DGRAPH-N-QUOT !
    64 0 DO
        _DGRAPH-N-QUOT @ 1 LSHIFT _DGRAPH-N-QUOT !
        _DGRAPH-N-REM @ 1 LSHIFT
        _DGRAPH-N-SOURCE @ 63 I - RSHIFT 1 AND OR
        DUP 10 U< IF
            _DGRAPH-N-REM !
        ELSE
            10 - _DGRAPH-N-REM !
            _DGRAPH-N-QUOT @ 1 OR _DGRAPH-N-QUOT !
        THEN
    LOOP
    _DGRAPH-N-REM @ _DGRAPH-N-QUOT @ ;

: _DGRAPH-SIGNED-LENGTH  ( n -- bytes )
    DUP _DGRAPH-N-VALUE ! _DGRAPH-MAGNITUDE _DGRAPH-N-MAG !
    1 _DGRAPH-N-DIGITS !
    BEGIN _DGRAPH-N-MAG @ 10 U< 0= WHILE
        _DGRAPH-N-MAG @ _DGRAPH-U/10 NIP _DGRAPH-N-MAG !
        1 _DGRAPH-N-DIGITS +!
    REPEAT
    _DGRAPH-N-DIGITS @
    _DGRAPH-N-VALUE @ 0< IF 1+ THEN ;

: _DGRAPH-SIGNED-FORMAT  ( value destination -- bytes )
    _DGRAPH-N-DST ! _DGRAPH-N-VALUE !
    _DGRAPH-N-VALUE @ _DGRAPH-SIGNED-LENGTH DUP _DGRAPH-N-CURSOR !
    _DGRAPH-N-DST @ + _DGRAPH-N-CURSOR !
    _DGRAPH-N-VALUE @ _DGRAPH-MAGNITUDE _DGRAPH-N-MAG !
    _DGRAPH-N-DIGITS @ 0 ?DO
        _DGRAPH-N-MAG @ _DGRAPH-U/10 _DGRAPH-N-MAG !
        [CHAR] 0 +
        -1 _DGRAPH-N-CURSOR +!
        _DGRAPH-N-CURSOR @ C!
    LOOP
    _DGRAPH-N-VALUE @ 0< IF
        [CHAR] - _DGRAPH-N-DST @ C!
    THEN
    _DGRAPH-N-DIGITS @
    _DGRAPH-N-VALUE @ 0< IF 1+ THEN ;

\ =====================================================================
\  Exact renderer scratch measurement and atomic binding
\ =====================================================================

VARIABLE _DGRAPH-S-GRAPH
VARIABLE _DGRAPH-S-WIDGET
VARIABLE _DGRAPH-S-CURSOR
VARIABLE _DGRAPH-S-RECORD
VARIABLE _DGRAPH-S-I
VARIABLE _DGRAPH-S-MAX
VARIABLE _DGRAPH-S-STATUS
VARIABLE _DGRAPH-S-BYTES
VARIABLE _DGRAPH-S-CELLS

: _DGRAPH-OBJECT-INTERSECTS?  ( record widget -- flag )
    >R
    DUP UDG-OBJECT-FLAGS@ UDG-OBJECT-VISIBLE AND 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP UDG-OBJECT-ROW@
        R@ WDG-REGION RGN-H < 0= IF DROP R> DROP 0 EXIT THEN
    DUP UDG-OBJECT-ROW@ OVER UDG-OBJECT-HEIGHT@ + 0> 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP UDG-OBJECT-COLUMN@
        R@ WDG-REGION RGN-W < 0= IF DROP R> DROP 0 EXIT THEN
    DUP UDG-OBJECT-COLUMN@ SWAP UDG-OBJECT-WIDTH@ + 0>
    R> DROP ;

: _DGRAPH-SCRATCH-MAX!  ( bytes -- )
    _DGRAPH-S-MAX @ MAX _DGRAPH-S-MAX ! ;

: _DGRAPH-SCAN-READOUT  ( record -- )
    DUP _DGRAPH-S-RECORD ! DGF-READOUT-MEASURE
    DUP DGF-S-OK <> IF
        DROP DROP DGRAPH-S-INVALID _DGRAPH-S-STATUS ! EXIT
    THEN
    DROP DUP _DGRAPH-S-BYTES !
    _DGRAPH-S-RECORD @ UDG-READOUT-UNIT-BYTES@ -
    _DGRAPH-S-RECORD @ UDG-READOUT-UNIT@ UTF8-LEN +
    DUP _DGRAPH-S-CELLS !
    _DGRAPH-S-RECORD @ UDG-OBJECT-WIDTH@ U> IF EXIT THEN
    _DGRAPH-S-BYTES @ _DGRAPH-SCRATCH-MAX! ;

: _DGRAPH-SCAN-METER  ( record -- )
    DUP UDG-METER-FLAGS@ UDG-METER-SHOW-VALUE AND 0= IF DROP EXIT THEN
    DUP _DGRAPH-S-RECORD ! UDG-METER-VALUE@ _DGRAPH-SIGNED-LENGTH
    DUP _DGRAPH-S-BYTES !
    _DGRAPH-S-RECORD @ UDG-OBJECT-WIDTH@ U> IF EXIT THEN
    _DGRAPH-S-BYTES @ _DGRAPH-SCRATCH-MAX! ;

: _DGRAPH-SCRATCH-SCAN  ( graph widget -- bytes status )
    _DGRAPH-S-WIDGET ! DUP _DGRAPH-S-GRAPH !
    UDG-FIRST-RECORD _DGRAPH-S-CURSOR !
    0 _DGRAPH-S-I ! 0 _DGRAPH-S-MAX ! DGRAPH-S-OK _DGRAPH-S-STATUS !
    BEGIN
        _DGRAPH-S-I @ _DGRAPH-S-GRAPH @ UDG-RECORD-COUNT@ U<
        _DGRAPH-S-STATUS @ DGRAPH-S-OK = AND
    WHILE
        _DGRAPH-S-CURSOR @ DUP _DGRAPH-S-RECORD !
        _DGRAPH-S-WIDGET @ _DGRAPH-OBJECT-INTERSECTS? IF
            _DGRAPH-S-RECORD @ UDG-RECORD-KIND@ CASE
                UDG-K-READOUT OF
                    _DGRAPH-S-RECORD @ _DGRAPH-SCAN-READOUT
                ENDOF
                UDG-K-METER OF
                    _DGRAPH-S-RECORD @ _DGRAPH-SCAN-METER
                ENDOF
            ENDCASE
        THEN
        _DGRAPH-S-CURSOR @ UDG-RECORD-NEXT _DGRAPH-S-CURSOR !
        1 _DGRAPH-S-I +!
    REPEAT
    _DGRAPH-S-MAX @ _DGRAPH-S-STATUS @ ;

VARIABLE _DGRAPH-B-GRAPH
VARIABLE _DGRAPH-B-U
VARIABLE _DGRAPH-B-SUMMARY
VARIABLE _DGRAPH-B-WIDGET
VARIABLE _DGRAPH-B-NEED
VARIABLE _DGRAPH-B-NEW-SCRATCH
VARIABLE _DGRAPH-B-OLD-SCRATCH

: _DGRAPH-BIND-PREFLIGHT?  ( graph bytes summary widget -- flag )
    3 PICK 3 PICK DGRAPH-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    1 PICK UDG-SUMMARY-SIZE DGRAPH-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    DUP _DGRAPH-DESC-SIZE DGRAPH-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    3 PICK 3 PICK UDG-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    1 PICK UDG-SUMMARY-SIZE UDG-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    3 PICK 3 PICK DGF-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    1 PICK UDG-SUMMARY-SIZE DGF-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    DUP _DGRAPH-DESC-SIZE DGF-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    DUP _DGRAPH-GENUINE? 0= IF 0 EXIT THEN
    DUP WDG-REGION RGN-SIZE DGF-STORAGE-DISJOINT? ;

: _DGRAPH-BIND-SPANS?  ( -- flag )
    _DGRAPH-B-GRAPH @ _DGRAPH-B-U @ _DGRAPH-SPAN? 0= IF 0 EXIT THEN
    _DGRAPH-B-GRAPH @ 7 AND IF 0 EXIT THEN
    _DGRAPH-B-SUMMARY @ DUP 0= IF DROP 0 EXIT THEN
    DUP 7 AND IF DROP 0 EXIT THEN
    UDG-SUMMARY-SIZE MSPAN-NONWRAPPING? 0= IF 0 EXIT THEN
    _DGRAPH-B-GRAPH @ _DGRAPH-B-U @
        _DGRAPH-B-SUMMARY @ UDG-SUMMARY-SIZE MSPAN-OVERLAP? IF 0 EXIT THEN
    _DGRAPH-B-GRAPH @ _DGRAPH-B-U @
        _DGRAPH-B-WIDGET @ _DGRAPH-DESC-SIZE MSPAN-OVERLAP? IF 0 EXIT THEN
    _DGRAPH-B-GRAPH @ _DGRAPH-B-U @
        _DGRAPH-B-WIDGET @ WDG-REGION RGN-SIZE MSPAN-OVERLAP? IF 0 EXIT THEN
    _DGRAPH-B-WIDGET @ _DGRAPH-O-SCRATCH-A + @ ?DUP IF
        _DGRAPH-B-GRAPH @ _DGRAPH-B-U @ ROT
        _DGRAPH-B-WIDGET @ _DGRAPH-O-SCRATCH-U + @
            MSPAN-OVERLAP? IF 0 EXIT THEN
    THEN
    _DGRAPH-B-SUMMARY @ UDG-SUMMARY-SIZE
        _DGRAPH-B-WIDGET @ _DGRAPH-DESC-SIZE MSPAN-OVERLAP? IF 0 EXIT THEN
    _DGRAPH-B-SUMMARY @ UDG-SUMMARY-SIZE
        _DGRAPH-B-WIDGET @ WDG-REGION RGN-SIZE MSPAN-OVERLAP? IF 0 EXIT THEN
    _DGRAPH-B-WIDGET @ _DGRAPH-O-MODEL-A + @ ?DUP IF
        _DGRAPH-B-SUMMARY @ UDG-SUMMARY-SIZE ROT
        _DGRAPH-B-WIDGET @ _DGRAPH-O-MODEL-U + @
            MSPAN-OVERLAP? IF 0 EXIT THEN
    THEN
    _DGRAPH-B-WIDGET @ _DGRAPH-O-SCRATCH-A + @ ?DUP IF
        _DGRAPH-B-SUMMARY @ UDG-SUMMARY-SIZE ROT
        _DGRAPH-B-WIDGET @ _DGRAPH-O-SCRATCH-U + @
            MSPAN-OVERLAP? IF 0 EXIT THEN
    THEN
    -1 ;

: DGRAPH-NEW  ( region -- widget )
    DUP 0= ABORT" DGRAPH-NEW: region"
    DUP 7 AND ABORT" DGRAPH-NEW: region alignment"
    DUP RGN-SIZE MSPAN-NONWRAPPING? 0= ABORT" DGRAPH-NEW: region span"
    _DGRAPH-CLAIM-INSTANCE _DGRAPH-NEW-INSTANCE !
    _DGRAPH-DESC-SIZE ALLOCATE 0<> ABORT" DGRAPH-NEW: alloc"
    WDG-T-DATA-GRAPHICS OVER _WDG-O-TYPE + !
    SWAP OVER _WDG-O-REGION + !
    ['] _DGRAPH-DRAW OVER _WDG-O-DRAW-XT + !
    ['] _DGRAPH-HANDLE OVER _WDG-O-HANDLE-XT + !
    WDG-F-VISIBLE WDG-F-DIRTY OR OVER _WDG-O-FLAGS + !
    0 OVER _DGRAPH-O-MODEL-A + !
    0 OVER _DGRAPH-O-MODEL-U + !
    0 OVER _DGRAPH-O-SCRATCH-A + !
    0 OVER _DGRAPH-O-SCRATCH-U + !
    _DGRAPH-NEW-INSTANCE @ OVER _DGRAPH-O-INSTANCE + !
    0 _DGRAPH-NEW-INSTANCE ! ;

: DGRAPH-BIND  ( graph bytes summary widget -- status )
    _DGRAPH-BIND-PREFLIGHT? 0= IF
        2DROP 2DROP DGRAPH-S-INVALID EXIT
    THEN
    _DGRAPH-B-WIDGET ! _DGRAPH-B-SUMMARY !
    _DGRAPH-B-U ! _DGRAPH-B-GRAPH !
    _DGRAPH-BIND-SPANS? 0= IF DGRAPH-S-INVALID EXIT THEN
    _DGRAPH-B-GRAPH @ _DGRAPH-B-U @ _DGRAPH-B-SUMMARY @
        UDG-ENTRY-VALIDATE
    DUP UDG-S-OK <> IF EXIT THEN DROP
    _DGRAPH-B-GRAPH @ UDG-ROOT-ROW@ IF DGRAPH-S-INVALID EXIT THEN
    _DGRAPH-B-GRAPH @ UDG-ROOT-COLUMN@ IF DGRAPH-S-INVALID EXIT THEN
    _DGRAPH-B-GRAPH @ UDG-ROOT-HEIGHT@
        _DGRAPH-B-WIDGET @ WDG-REGION RGN-H <> IF
        DGRAPH-S-INVALID EXIT
    THEN
    _DGRAPH-B-GRAPH @ UDG-ROOT-WIDTH@
        _DGRAPH-B-WIDGET @ WDG-REGION RGN-W <> IF
        DGRAPH-S-INVALID EXIT
    THEN
    _DGRAPH-B-GRAPH @ _DGRAPH-B-WIDGET @ _DGRAPH-SCRATCH-SCAN
    DUP DGRAPH-S-OK <> IF NIP EXIT THEN DROP _DGRAPH-B-NEED !
    0 _DGRAPH-B-NEW-SCRATCH !
    _DGRAPH-B-NEED @ ?DUP IF
        ALLOCATE DUP IF
            2DROP DGRAPH-S-ALLOC EXIT
        THEN
        DROP _DGRAPH-B-NEW-SCRATCH !
    THEN
    _DGRAPH-B-WIDGET @ _DGRAPH-O-SCRATCH-A + @
        _DGRAPH-B-OLD-SCRATCH !
    _DGRAPH-B-GRAPH @ _DGRAPH-B-WIDGET @ _DGRAPH-O-MODEL-A + !
    _DGRAPH-B-U @ _DGRAPH-B-WIDGET @ _DGRAPH-O-MODEL-U + !
    _DGRAPH-B-NEW-SCRATCH @
        _DGRAPH-B-WIDGET @ _DGRAPH-O-SCRATCH-A + !
    _DGRAPH-B-NEED @ _DGRAPH-B-WIDGET @ _DGRAPH-O-SCRATCH-U + !
    _DGRAPH-B-WIDGET @ WDG-DIRTY
    _DGRAPH-B-OLD-SCRATCH @ ?DUP IF FREE THEN
    DGRAPH-S-OK ;

: DGRAPH-INSTANCE@  ( widget -- token )
    DUP _DGRAPH-GENUINE? 0= IF DROP 0 EXIT THEN
    _DGRAPH-O-INSTANCE + @ ;

: DGRAPH-FREE  ( widget -- )
    DUP _DGRAPH-O-SCRATCH-A + @ ?DUP IF FREE THEN
    FREE ;

\ =====================================================================
\  CELL fallback
\ =====================================================================

VARIABLE _DGRAPH-D-WIDGET
VARIABLE _DGRAPH-D-GRAPH
VARIABLE _DGRAPH-D-RECORD
VARIABLE _DGRAPH-D-DISABLED
VARIABLE _DGRAPH-D-BYTES
VARIABLE _DGRAPH-D-CELLS
VARIABLE _DGRAPH-D-ROW
VARIABLE _DGRAPH-D-COL
VARIABLE _DGRAPH-D-RGBA

: _DGRAPH-RGBA>PALETTE  ( rgba -- palette )
    DUP _DGRAPH-D-RGBA ! UDG-RGBA-RED@
    _DGRAPH-D-RGBA @ UDG-RGBA-GREEN@
    _DGRAPH-D-RGBA @ UDG-RGBA-BLUE@
    TUI-RESOLVE-COLOR ;

: _DGRAPH-APPLY-FG  ( rgba -- )
    DUP UDG-RGBA-ALPHA@ 0= IF DROP EXIT THEN
    _DGRAPH-RGBA>PALETTE DRW-FG! ;

: _DGRAPH-APPLY-BG  ( rgba -- )
    DUP UDG-RGBA-ALPHA@ 0= IF DROP EXIT THEN
    _DGRAPH-RGBA>PALETTE DRW-BG! ;

: _DGRAPH-APPLY-DIM  ( -- )
    _DGRAPH-D-DISABLED @ IF
        _DRW-ATTRS @ CELL-A-DIM OR DRW-ATTR!
    THEN ;

: _DGRAPH-OBJECT-CENTER  ( record -- row column )
    DUP UDG-OBJECT-ROW@
    OVER UDG-OBJECT-HEIGHT@ 1- 2/ +
    SWAP DUP UDG-OBJECT-COLUMN@
    SWAP UDG-OBJECT-WIDTH@ 1- 2/ + ;

: _DGRAPH-DRAW-MARKER  ( record -- )
    DUP UDG-OBJECT-ROW@ OVER UDG-OBJECT-HEIGHT@ 1- 2/ +
    SWAP DUP UDG-OBJECT-COLUMN@ SWAP UDG-OBJECT-WIDTH@ 1- +
    [CHAR] # -ROT DRW-CHAR ;

: _DGRAPH-READOUT-STYLE  ( record -- )
    DRW-STYLE-RESTORE
    DUP UDG-READOUT-FG@ _DGRAPH-APPLY-FG
    UDG-READOUT-BG@ _DGRAPH-APPLY-BG
    _DGRAPH-APPLY-DIM ;

: _DGRAPH-DRAW-READOUT  ( record -- )
    DUP _DGRAPH-D-RECORD ! _DGRAPH-READOUT-STYLE
    _DGRAPH-D-RECORD @ DGF-READOUT-MEASURE
    DUP DGF-S-OK <> IF
        2DROP _DGRAPH-D-RECORD @ _DGRAPH-DRAW-MARKER EXIT
    THEN
    DROP DUP _DGRAPH-D-BYTES !
    _DGRAPH-D-RECORD @ UDG-READOUT-UNIT-BYTES@ -
    _DGRAPH-D-RECORD @ UDG-READOUT-UNIT@ UTF8-LEN +
    DUP _DGRAPH-D-CELLS !
    _DGRAPH-D-RECORD @ UDG-OBJECT-WIDTH@ U> IF
        _DGRAPH-D-RECORD @ _DGRAPH-DRAW-MARKER EXIT
    THEN
    _DGRAPH-D-RECORD @
        _DGRAPH-D-WIDGET @ _DGRAPH-O-SCRATCH-A + @
        _DGRAPH-D-WIDGET @ _DGRAPH-O-SCRATCH-U + @
        DGF-READOUT-FORMAT
    DUP DGF-S-OK <> IF
        2DROP _DGRAPH-D-RECORD @ _DGRAPH-DRAW-MARKER EXIT
    THEN
    DROP DROP
    _DGRAPH-D-RECORD @ UDG-OBJECT-ROW@
        _DGRAPH-D-RECORD @ UDG-OBJECT-HEIGHT@ 1- 2/ +
        _DGRAPH-D-ROW !
    _DGRAPH-D-RECORD @ UDG-OBJECT-COLUMN@
        _DGRAPH-D-RECORD @ UDG-OBJECT-WIDTH@ +
        _DGRAPH-D-CELLS @ - _DGRAPH-D-COL !
    _DGRAPH-D-WIDGET @ _DGRAPH-O-SCRATCH-A + @ _DGRAPH-D-BYTES @
        _DGRAPH-D-ROW @ _DGRAPH-D-COL @ DRW-TEXT ;

VARIABLE _DGRAPH-Q-N
VARIABLE _DGRAPH-Q-D
VARIABLE _DGRAPH-Q-VALUE
VARIABLE _DGRAPH-Q-MINIMUM
VARIABLE _DGRAPH-Q-MAXIMUM
VARIABLE _DGRAPH-Q-SPAN
VARIABLE _DGRAPH-Q-LO
VARIABLE _DGRAPH-Q-REM
VARIABLE _DGRAPH-Q-QUOT
VARIABLE _DGRAPH-Q-SOURCE
VARIABLE _DGRAPH-Q-CARRY

: _DGRAPH-METER-SCALE  ( value minimum maximum span -- filled )
    _DGRAPH-Q-SPAN ! _DGRAPH-Q-MAXIMUM !
    _DGRAPH-Q-MINIMUM ! _DGRAPH-Q-VALUE !
    _DGRAPH-Q-VALUE @ _DGRAPH-Q-MINIMUM @ <= IF 0 EXIT THEN
    _DGRAPH-Q-VALUE @ _DGRAPH-Q-MAXIMUM @ >= IF
        _DGRAPH-Q-SPAN @ EXIT
    THEN
    _DGRAPH-Q-MAXIMUM @ _DGRAPH-Q-MINIMUM @ - _DGRAPH-Q-D !
    _DGRAPH-Q-VALUE @ _DGRAPH-Q-MINIMUM @ - _DGRAPH-Q-N !
    _DGRAPH-Q-N @ _DGRAPH-Q-SPAN @ UM*
    _DGRAPH-Q-REM ! _DGRAPH-Q-SOURCE !
    0 _DGRAPH-Q-QUOT !
    64 0 DO
        _DGRAPH-Q-QUOT @ 1 LSHIFT _DGRAPH-Q-QUOT !
        _DGRAPH-Q-REM @ 63 RSHIFT _DGRAPH-Q-CARRY !
        _DGRAPH-Q-REM @ 1 LSHIFT
        _DGRAPH-Q-SOURCE @ 63 I - RSHIFT 1 AND OR
        _DGRAPH-Q-REM !
        _DGRAPH-Q-CARRY @
        _DGRAPH-Q-REM @ _DGRAPH-Q-D @ U< 0= OR IF
            _DGRAPH-Q-REM @ _DGRAPH-Q-D @ - _DGRAPH-Q-REM !
            _DGRAPH-Q-QUOT @ 1 OR _DGRAPH-Q-QUOT !
        THEN
    LOOP
    _DGRAPH-Q-QUOT @ ;

VARIABLE _DGRAPH-R-ROW
VARIABLE _DGRAPH-R-COL
VARIABLE _DGRAPH-R-H
VARIABLE _DGRAPH-R-W

: _DGRAPH-DRAW-COLOR-RECT  ( rgba row column height width -- )
    _DGRAPH-R-W ! _DGRAPH-R-H ! _DGRAPH-R-COL ! _DGRAPH-R-ROW !
    DUP UDG-RGBA-ALPHA@ 0= IF DROP EXIT THEN
    DRW-STYLE-RESTORE
    _DGRAPH-RGBA>PALETTE DUP DRW-FG! DRW-BG!
    _DGRAPH-APPLY-DIM
    32 _DGRAPH-R-ROW @ _DGRAPH-R-COL @
        _DGRAPH-R-H @ _DGRAPH-R-W @ DRW-FILL-RECT ;

VARIABLE _DGRAPH-M-FILL
VARIABLE _DGRAPH-M-LENGTH

: _DGRAPH-METER-STYLE  ( record -- )
    DRW-STYLE-RESTORE
    DUP UDG-METER-FG@ _DGRAPH-APPLY-FG
    UDG-METER-BG@ _DGRAPH-APPLY-BG
    _DGRAPH-APPLY-DIM ;

: _DGRAPH-DRAW-METER-VALUE  ( record -- )
    DUP _DGRAPH-D-RECORD ! _DGRAPH-METER-STYLE
    _DGRAPH-D-RECORD @ UDG-METER-VALUE@ _DGRAPH-SIGNED-LENGTH
    DUP _DGRAPH-M-LENGTH !
    _DGRAPH-D-RECORD @ UDG-OBJECT-WIDTH@ U> IF
        _DGRAPH-D-RECORD @ _DGRAPH-DRAW-MARKER EXIT
    THEN
    _DGRAPH-D-RECORD @ UDG-METER-VALUE@
        _DGRAPH-D-WIDGET @ _DGRAPH-O-SCRATCH-A + @
        _DGRAPH-SIGNED-FORMAT DROP
    _DGRAPH-D-RECORD @ UDG-OBJECT-ROW@
        _DGRAPH-D-RECORD @ UDG-OBJECT-HEIGHT@ 1- 2/ +
        _DGRAPH-D-ROW !
    _DGRAPH-D-RECORD @ UDG-OBJECT-COLUMN@
        _DGRAPH-D-RECORD @ UDG-OBJECT-WIDTH@
        _DGRAPH-M-LENGTH @ - 2/ + _DGRAPH-D-COL !
    _DGRAPH-D-WIDGET @ _DGRAPH-O-SCRATCH-A + @ _DGRAPH-M-LENGTH @
        _DGRAPH-D-ROW @ _DGRAPH-D-COL @ DRW-TEXT ;

: _DGRAPH-DRAW-METER  ( record -- )
    _DGRAPH-D-RECORD !
    _DGRAPH-D-RECORD @ UDG-METER-BG@
    _DGRAPH-D-RECORD @ UDG-OBJECT-ROW@
    _DGRAPH-D-RECORD @ UDG-OBJECT-COLUMN@
    _DGRAPH-D-RECORD @ UDG-OBJECT-HEIGHT@
    _DGRAPH-D-RECORD @ UDG-OBJECT-WIDTH@
    _DGRAPH-DRAW-COLOR-RECT
    _DGRAPH-D-RECORD @ UDG-METER-ORIENTATION@
        UDG-METER-HORIZONTAL = IF
        _DGRAPH-D-RECORD @ UDG-METER-VALUE@
        _DGRAPH-D-RECORD @ UDG-METER-MINIMUM@
        _DGRAPH-D-RECORD @ UDG-METER-MAXIMUM@
        _DGRAPH-D-RECORD @ UDG-OBJECT-WIDTH@
        _DGRAPH-METER-SCALE _DGRAPH-M-FILL !
        _DGRAPH-D-RECORD @ UDG-METER-FG@
        _DGRAPH-D-RECORD @ UDG-OBJECT-ROW@
        _DGRAPH-D-RECORD @ UDG-OBJECT-COLUMN@
        _DGRAPH-D-RECORD @ UDG-OBJECT-HEIGHT@
        _DGRAPH-M-FILL @ _DGRAPH-DRAW-COLOR-RECT
    ELSE
        _DGRAPH-D-RECORD @ UDG-METER-VALUE@
        _DGRAPH-D-RECORD @ UDG-METER-MINIMUM@
        _DGRAPH-D-RECORD @ UDG-METER-MAXIMUM@
        _DGRAPH-D-RECORD @ UDG-OBJECT-HEIGHT@
        _DGRAPH-METER-SCALE _DGRAPH-M-FILL !
        _DGRAPH-D-RECORD @ UDG-METER-FG@
        _DGRAPH-D-RECORD @ UDG-OBJECT-ROW@
            _DGRAPH-D-RECORD @ UDG-OBJECT-HEIGHT@ +
            _DGRAPH-M-FILL @ -
        _DGRAPH-D-RECORD @ UDG-OBJECT-COLUMN@
        _DGRAPH-M-FILL @
        _DGRAPH-D-RECORD @ UDG-OBJECT-WIDTH@
        _DGRAPH-DRAW-COLOR-RECT
    THEN
    _DGRAPH-D-RECORD @ UDG-METER-FLAGS@
        UDG-METER-SHOW-VALUE AND IF
        _DGRAPH-D-RECORD @ _DGRAPH-DRAW-METER-VALUE
    THEN ;

: _DGRAPH-STATUS-CP  ( record -- codepoint )
    DUP UDG-STATUS-VALUE@ 0<> IF
        UDG-STATUS-SHAPE@ CASE
            UDG-STATUS-CIRCLE  OF 0x25CF ENDOF
            UDG-STATUS-SQUARE  OF 0x25A0 ENDOF
            UDG-STATUS-DIAMOND OF 0x25C6 ENDOF
        ENDCASE
    ELSE
        UDG-STATUS-SHAPE@ CASE
            UDG-STATUS-CIRCLE  OF 0x25CB ENDOF
            UDG-STATUS-SQUARE  OF 0x25A1 ENDOF
            UDG-STATUS-DIAMOND OF 0x25C7 ENDOF
        ENDCASE
    THEN ;

: _DGRAPH-DRAW-STATUS  ( record -- )
    DUP _DGRAPH-D-RECORD !
    DUP UDG-STATUS-VALUE@ 0<> IF UDG-STATUS-ACTIVE@
        ELSE UDG-STATUS-INACTIVE@ THEN
    DUP UDG-RGBA-ALPHA@ 0= IF DROP EXIT THEN
    DRW-STYLE-RESTORE _DGRAPH-APPLY-FG _DGRAPH-APPLY-DIM
    _DGRAPH-D-RECORD @ _DGRAPH-STATUS-CP
    _DGRAPH-D-RECORD @ _DGRAPH-OBJECT-CENTER DRW-CHAR ;

VARIABLE _DGRAPH-O-CURSOR
VARIABLE _DGRAPH-O-I
VARIABLE _DGRAPH-O-SCAN
VARIABLE _DGRAPH-O-BEST
VARIABLE _DGRAPH-O-BEST-HAVE
VARIABLE _DGRAPH-O-PREV-Z
VARIABLE _DGRAPH-O-PREV-KEY
VARIABLE _DGRAPH-O-PREV-HAVE

: _DGRAPH-AFTER-PREV?  ( record -- flag )
    DUP UDG-OBJECT-FLAGS@ UDG-OBJECT-VISIBLE AND 0= IF DROP 0 EXIT THEN
    _DGRAPH-O-PREV-HAVE @ 0= IF DROP -1 EXIT THEN
    DUP UDG-OBJECT-Z@ _DGRAPH-O-PREV-Z @ > IF DROP -1 EXIT THEN
    DUP UDG-OBJECT-Z@ _DGRAPH-O-PREV-Z @ < IF DROP 0 EXIT THEN
    UDG-RECORD-KEY@ _DGRAPH-O-PREV-KEY @ U> ;

: _DGRAPH-BEFORE-BEST?  ( record -- flag )
    _DGRAPH-O-BEST-HAVE @ 0= IF DROP -1 EXIT THEN
    DUP UDG-OBJECT-Z@ _DGRAPH-O-BEST @ UDG-OBJECT-Z@ < IF DROP -1 EXIT THEN
    DUP UDG-OBJECT-Z@ _DGRAPH-O-BEST @ UDG-OBJECT-Z@ > IF DROP 0 EXIT THEN
    UDG-RECORD-KEY@ _DGRAPH-O-BEST @ UDG-RECORD-KEY@ U< ;

: _DGRAPH-FIND-NEXT  ( -- record|0 )
    _DGRAPH-D-GRAPH @ UDG-FIRST-RECORD _DGRAPH-O-CURSOR !
    0 _DGRAPH-O-I ! 0 _DGRAPH-O-BEST ! 0 _DGRAPH-O-BEST-HAVE !
    BEGIN _DGRAPH-O-I @ _DGRAPH-D-GRAPH @ UDG-RECORD-COUNT@ U< WHILE
        _DGRAPH-O-CURSOR @ DUP _DGRAPH-O-SCAN !
        _DGRAPH-AFTER-PREV? IF
            _DGRAPH-O-SCAN @ _DGRAPH-BEFORE-BEST? IF
                _DGRAPH-O-SCAN @ _DGRAPH-O-BEST !
                -1 _DGRAPH-O-BEST-HAVE !
            THEN
        THEN
        _DGRAPH-O-CURSOR @ UDG-RECORD-NEXT _DGRAPH-O-CURSOR !
        1 _DGRAPH-O-I +!
    REPEAT
    _DGRAPH-O-BEST @ ;

: _DGRAPH-DRAW-OBJECT  ( record -- )
    DUP _DGRAPH-D-WIDGET @ _DGRAPH-OBJECT-INTERSECTS? 0= IF
        DROP EXIT
    THEN
    DUP UDG-RECORD-KIND@ CASE
        UDG-K-READOUT OF _DGRAPH-DRAW-READOUT ENDOF
        UDG-K-METER   OF _DGRAPH-DRAW-METER ENDOF
        UDG-K-STATUS  OF _DGRAPH-DRAW-STATUS ENDOF
        DROP
    ENDCASE ;

: _DGRAPH-DRAW-IMPL  ( widget -- )
    DUP _DGRAPH-D-WIDGET !
    DUP _DGRAPH-BOUND? 0= IF DROP EXIT THEN
    _DGRAPH-O-MODEL-A + @ DUP _DGRAPH-D-GRAPH !
    UDG-ROOT-STATE@ UDG-STATE-VISIBLE AND 0= IF EXIT THEN
    _DGRAPH-D-WIDGET @ WDG-DISABLED?
    _DGRAPH-D-GRAPH @ UDG-ROOT-STATE@ UDG-STATE-ENABLED AND 0= OR
        _DGRAPH-D-DISABLED !
    0 _DGRAPH-O-PREV-HAVE !
    BEGIN _DGRAPH-FIND-NEXT DUP WHILE
        DUP _DGRAPH-DRAW-OBJECT
        DUP UDG-OBJECT-Z@ _DGRAPH-O-PREV-Z !
        UDG-RECORD-KEY@ _DGRAPH-O-PREV-KEY !
        -1 _DGRAPH-O-PREV-HAVE !
    REPEAT
    DROP DRW-STYLE-RESTORE ;

: _DGRAPH-HANDLE-IMPL  ( event widget -- consumed? )
    2DROP 0 ;

' _DGRAPH-DRAW-IMPL IS _DGRAPH-DRAW
' _DGRAPH-HANDLE-IMPL IS _DGRAPH-HANDLE

\ =====================================================================
\  Renderer-neutral capture of the exact graph reached by WDG-DRAW
\ =====================================================================

VARIABLE _DGRAPH-C-ROOT
VARIABLE _DGRAPH-C-DST
VARIABLE _DGRAPH-C-CAP
VARIABLE _DGRAPH-C-BUILDER
VARIABLE _DGRAPH-C-WIDGET
VARIABLE _DGRAPH-C-U
VARIABLE _DGRAPH-C-CURSOR
VARIABLE _DGRAPH-C-I
VARIABLE _DGRAPH-C-STATE

: _DGRAPH-CAPTURE-PREFLIGHT?  ( root dst cap builder widget -- flag )
    3 PICK 3 PICK DGRAPH-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    1 PICK UDG-BUILDER-SIZE DGRAPH-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    DUP _DGRAPH-DESC-SIZE DGRAPH-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    3 PICK 3 PICK UDG-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    1 PICK UDG-BUILDER-SIZE UDG-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    3 PICK 3 PICK DGF-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    1 PICK UDG-BUILDER-SIZE DGF-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    DUP _DGRAPH-DESC-SIZE DGF-STORAGE-DISJOINT? 0= IF 0 EXIT THEN
    DUP _DGRAPH-BOUND? 0= IF 0 EXIT THEN
    DUP WDG-REGION RGN-SIZE DGF-STORAGE-DISJOINT? ;

: _DGRAPH-ROOT-COLLIDES?  ( root-key graph -- flag )
    UDG-FIRST-RECORD _DGRAPH-C-CURSOR !
    _DGRAPH-C-ROOT ! 0 _DGRAPH-C-I !
    BEGIN _DGRAPH-C-I @ _DGRAPH-C-WIDGET @
        _DGRAPH-O-MODEL-A + @ UDG-RECORD-COUNT@ U< WHILE
        _DGRAPH-C-CURSOR @ UDG-RECORD-KEY@ _DGRAPH-C-ROOT @ = IF
            -1 EXIT
        THEN
        _DGRAPH-C-CURSOR @ UDG-RECORD-NEXT _DGRAPH-C-CURSOR !
        1 _DGRAPH-C-I +!
    REPEAT
    0 ;

: DGRAPH-DATA-GRAPHICS-CAPTURE
    ( root-key destination capacity builder widget -- bytes status )
    _DGRAPH-CAPTURE-PREFLIGHT? 0= IF
        2DROP 2DROP DROP 0 DGRAPH-S-INVALID EXIT
    THEN
    _DGRAPH-C-WIDGET ! _DGRAPH-C-BUILDER ! _DGRAPH-C-CAP !
    _DGRAPH-C-DST ! _DGRAPH-C-ROOT !
    _DGRAPH-C-ROOT @ 0= IF 0 DGRAPH-S-INVALID EXIT THEN
    _DGRAPH-C-WIDGET @ _DGRAPH-O-MODEL-U + @ _DGRAPH-C-U !
    _DGRAPH-C-ROOT @ _DGRAPH-C-WIDGET @ _DGRAPH-O-MODEL-A + @
        _DGRAPH-ROOT-COLLIDES? IF 0 DGRAPH-S-INVALID EXIT THEN
    _DGRAPH-C-BUILDER @ DUP 0= IF DROP 0 DGRAPH-S-INVALID EXIT THEN
    DUP 7 AND IF DROP 0 DGRAPH-S-INVALID EXIT THEN
    DUP UDG-BUILDER-SIZE MSPAN-NONWRAPPING? 0= IF
        DROP 0 DGRAPH-S-INVALID EXIT
    THEN
    UDG-BUILDER-SIZE _DGRAPH-C-WIDGET @
        DGRAPH-DATA-GRAPHICS-STORAGE-DISJOINT? 0= IF
        0 DGRAPH-S-INVALID EXIT
    THEN
    _DGRAPH-C-DST @ 0= IF
        _DGRAPH-C-CAP @ IF 0 DGRAPH-S-INVALID EXIT THEN
        _DGRAPH-C-U @ DGRAPH-S-OK EXIT
    THEN
    _DGRAPH-C-DST @ 7 AND IF 0 DGRAPH-S-INVALID EXIT THEN
    _DGRAPH-C-DST @ _DGRAPH-C-CAP @ _DGRAPH-SPAN? 0= IF
        0 DGRAPH-S-INVALID EXIT
    THEN
    _DGRAPH-C-DST @ _DGRAPH-C-CAP @
        _DGRAPH-C-BUILDER @ UDG-BUILDER-SIZE MSPAN-OVERLAP? IF
        0 DGRAPH-S-INVALID EXIT
    THEN
    _DGRAPH-C-DST @ _DGRAPH-C-CAP @ _DGRAPH-C-WIDGET @
        DGRAPH-DATA-GRAPHICS-STORAGE-DISJOINT? 0= IF
        0 DGRAPH-S-INVALID EXIT
    THEN
    _DGRAPH-C-CAP @ _DGRAPH-C-U @ U< IF
        0 DGRAPH-S-CAPACITY EXIT
    THEN
    _DGRAPH-C-WIDGET @ _DGRAPH-O-MODEL-A + @
        _DGRAPH-C-DST @ _DGRAPH-C-U @ MOVE
    _DGRAPH-C-ROOT @ _DGRAPH-C-DST @ UDG-ROOT-KEY-OFFSET + !
    0 _DGRAPH-C-DST @ UDG-ROOT-ROW-OFFSET + !
    0 _DGRAPH-C-DST @ UDG-ROOT-COLUMN-OFFSET + !
    _DGRAPH-C-WIDGET @ WDG-REGION RGN-H
        _DGRAPH-C-DST @ UDG-ROOT-HEIGHT-OFFSET + !
    _DGRAPH-C-WIDGET @ WDG-REGION RGN-W
        _DGRAPH-C-DST @ UDG-ROOT-WIDTH-OFFSET + !
    0 _DGRAPH-C-STATE !
    _DGRAPH-C-WIDGET @ WDG-VISIBLE?
    _DGRAPH-C-WIDGET @ _DGRAPH-O-MODEL-A + @
        UDG-ROOT-STATE@ UDG-STATE-VISIBLE AND 0<> AND IF
        UDG-STATE-VISIBLE _DGRAPH-C-STATE +!
    THEN
    _DGRAPH-C-WIDGET @ WDG-DISABLED? 0=
    _DGRAPH-C-WIDGET @ _DGRAPH-O-MODEL-A + @
        UDG-ROOT-STATE@ UDG-STATE-ENABLED AND 0<> AND IF
        UDG-STATE-ENABLED _DGRAPH-C-STATE +!
    THEN
    _DGRAPH-C-STATE @ _DGRAPH-C-DST @ UDG-ROOT-STATE-OFFSET + !
    _DGRAPH-C-U @ DGRAPH-S-OK ;

: DGRAPH-DATA-GRAPHICS-MEASURE  ( root-key builder widget -- bytes status )
    >R >R 0 0 R> R> DGRAPH-DATA-GRAPHICS-CAPTURE ;

\ =====================================================================
\  Optional guard surface
\ =====================================================================

[DEFINED] GUARDED [IF] GUARDED [IF]
REQUIRE ../../concurrency/guard.f
GUARD _dgraph-guard

' DGRAPH-NEW CONSTANT _dgraph-new-xt
' DGRAPH-BIND CONSTANT _dgraph-bind-xt
' DGRAPH-INSTANCE@ CONSTANT _dgraph-instance-at-xt
' DGRAPH-FREE CONSTANT _dgraph-free-xt
' DGRAPH-DATA-GRAPHICS-CAPTURE CONSTANT _dgraph-capture-xt
' DGRAPH-DATA-GRAPHICS-MEASURE CONSTANT _dgraph-measure-xt
' DGRAPH-DATA-GRAPHICS-STORAGE-DISJOINT? CONSTANT _dgraph-disjoint-q-xt

: DGRAPH-NEW _dgraph-new-xt _dgraph-guard WITH-GUARD ;
: DGRAPH-BIND _dgraph-bind-xt _dgraph-guard WITH-GUARD ;
: DGRAPH-INSTANCE@ _dgraph-instance-at-xt _dgraph-guard WITH-GUARD ;
: DGRAPH-FREE _dgraph-free-xt _dgraph-guard WITH-GUARD ;
: DGRAPH-DATA-GRAPHICS-CAPTURE
    _dgraph-capture-xt _dgraph-guard WITH-GUARD ;
: DGRAPH-DATA-GRAPHICS-MEASURE
    _dgraph-measure-xt _dgraph-guard WITH-GUARD ;
: DGRAPH-DATA-GRAPHICS-STORAGE-DISJOINT?
    _dgraph-disjoint-q-xt _dgraph-guard WITH-GUARD ;
[THEN] [THEN]

CREATE _DGRAPH-OWNED-END
_DGRAPH-OWNED-END _DGRAPH-OWNED-LIMIT !
