\ vfs-ext4.f — bounded read-only ext4 admission for ABI-1 VFS
\
\ This is the first implementation slice of akashic-ext4-rw-v1.  It owns
\ one explicit KDOS volume, validates the clean on-disk format before mount
\ publication, and exposes checksummed canonical namespace/data/xattr reads
\ plus metadata and STATFS through ABI 1.  It does not advertise recovery or
\ mutation operations.
\
\ Prefix: EXT4-  (public API)
\         _EXT4- (internal helpers)
\
\ Load with:   REQUIRE utils/fs/drivers/vfs-ext4.f

PROVIDED akashic-vfs-ext4
REQUIRE ../vfs.f

\ =====================================================================
\  Profile constants and on-disk offsets
\ =====================================================================

512  CONSTANT _EXT4-SECTOR
1024 CONSTANT _EXT4-SB-SIZE
4096 CONSTANT _EXT4-MAX-BLOCK
256  CONSTANT _EXT4-MAX-INODE
64   CONSTANT _EXT4-DESC-SIZE

0xEF53     CONSTANT _EXT4-MAGIC
0xF30A     CONSTANT _EXT4-EXTENT-MAGIC
0x0B10CA04 CONSTANT _EXT4-ORPHAN-MAGIC
0xC03B3998 CONSTANT _EXT4-JBD2-MAGIC
4          CONSTANT _EXT4-JBD2-SUPER-V2

0x0000103C CONSTANT _EXT4-COMPAT-V1
0x0000046B CONSTANT _EXT4-RO-V1
0x0000042B CONSTANT _EXT4-RO-I128-V1
0x00001000 CONSTANT _EXT4-RO-READONLY
0x0000EB94 CONSTANT _EXT4-RO-REFUSED
0x000022C2 CONSTANT _EXT4-INCOMPAT-V1

0x00080000 CONSTANT _EXT4-EXTENTS-FL
0x00001000 CONSTANT _EXT4-INDEX-FL
0x00040000 CONSTANT _EXT4-HUGE-FILE-FL
1 CONSTANT _EXT4-BG-INODE-UNINIT
2 CONSTANT _EXT4-BG-BLOCK-UNINIT
4 CONSTANT _EXT4-BG-INODE-ZEROED

\ Superblock offsets (all ext4 fields are little-endian).
0x000 CONSTANT _EXT4-SB.INODES
0x004 CONSTANT _EXT4-SB.BLOCKS-LO
0x008 CONSTANT _EXT4-SB.RBLOCKS-LO
0x00C CONSTANT _EXT4-SB.FREE-BLOCKS-LO
0x010 CONSTANT _EXT4-SB.FREE-INODES
0x014 CONSTANT _EXT4-SB.FIRST-DATA
0x018 CONSTANT _EXT4-SB.LOG-BLOCK
0x01C CONSTANT _EXT4-SB.LOG-CLUSTER
0x020 CONSTANT _EXT4-SB.BPG
0x024 CONSTANT _EXT4-SB.CPG
0x028 CONSTANT _EXT4-SB.IPG
0x038 CONSTANT _EXT4-SB.MAGIC
0x03A CONSTANT _EXT4-SB.STATE
0x03C CONSTANT _EXT4-SB.ERRORS
0x048 CONSTANT _EXT4-SB.CREATOR
0x04C CONSTANT _EXT4-SB.REVISION
0x054 CONSTANT _EXT4-SB.FIRST-INO
0x058 CONSTANT _EXT4-SB.INODE-SIZE
0x05A CONSTANT _EXT4-SB.GROUP-NR
0x05C CONSTANT _EXT4-SB.COMPAT
0x060 CONSTANT _EXT4-SB.INCOMPAT
0x064 CONSTANT _EXT4-SB.RO-COMPAT
0x068 CONSTANT _EXT4-SB.UUID
0x0E0 CONSTANT _EXT4-SB.JOURNAL-INO
0x0E8 CONSTANT _EXT4-SB.LAST-ORPHAN
0x0FE CONSTANT _EXT4-SB.DESC-SIZE
0x150 CONSTANT _EXT4-SB.BLOCKS-HI
0x154 CONSTANT _EXT4-SB.RBLOCKS-HI
0x158 CONSTANT _EXT4-SB.FREE-BLOCKS-HI
0x15C CONSTANT _EXT4-SB.MIN-EXTRA
0x15E CONSTANT _EXT4-SB.WANT-EXTRA
0x174 CONSTANT _EXT4-SB.LOG-FLEX
0x175 CONSTANT _EXT4-SB.CSUM-TYPE
0x270 CONSTANT _EXT4-SB.CSUM-SEED
0x280 CONSTANT _EXT4-SB.ORPHAN-INO
0x3FC CONSTANT _EXT4-SB.CHECKSUM

\ 64-byte group descriptor offsets.
0x00 CONSTANT _EXT4-GD.BLOCK-BITMAP-LO
0x04 CONSTANT _EXT4-GD.INODE-BITMAP-LO
0x08 CONSTANT _EXT4-GD.INODE-TABLE-LO
0x0C CONSTANT _EXT4-GD.FREE-BLOCKS-LO
0x0E CONSTANT _EXT4-GD.FREE-INODES-LO
0x10 CONSTANT _EXT4-GD.USED-DIRS-LO
0x12 CONSTANT _EXT4-GD.FLAGS
0x18 CONSTANT _EXT4-GD.BLOCK-CSUM-LO
0x1A CONSTANT _EXT4-GD.INODE-CSUM-LO
0x1E CONSTANT _EXT4-GD.CHECKSUM
0x20 CONSTANT _EXT4-GD.BLOCK-BITMAP-HI
0x24 CONSTANT _EXT4-GD.INODE-BITMAP-HI
0x28 CONSTANT _EXT4-GD.INODE-TABLE-HI
0x2C CONSTANT _EXT4-GD.FREE-BLOCKS-HI
0x2E CONSTANT _EXT4-GD.FREE-INODES-HI
0x30 CONSTANT _EXT4-GD.USED-DIRS-HI
0x38 CONSTANT _EXT4-GD.BLOCK-CSUM-HI
0x3A CONSTANT _EXT4-GD.INODE-CSUM-HI

\ Inode offsets.
0x00 CONSTANT _EXT4-I.MODE
0x02 CONSTANT _EXT4-I.UID-LO
0x04 CONSTANT _EXT4-I.SIZE-LO
0x08 CONSTANT _EXT4-I.ATIME
0x0C CONSTANT _EXT4-I.CTIME
0x10 CONSTANT _EXT4-I.MTIME
0x14 CONSTANT _EXT4-I.DTIME
0x18 CONSTANT _EXT4-I.GID-LO
0x1A CONSTANT _EXT4-I.LINKS
0x1C CONSTANT _EXT4-I.BLOCKS-LO
0x20 CONSTANT _EXT4-I.FLAGS
0x28 CONSTANT _EXT4-I.BLOCK
0x64 CONSTANT _EXT4-I.GENERATION
0x68 CONSTANT _EXT4-I.FILE-ACL-LO
0x6C CONSTANT _EXT4-I.SIZE-HI
0x74 CONSTANT _EXT4-I.BLOCKS-HI
0x78 CONSTANT _EXT4-I.UID-HI
0x7A CONSTANT _EXT4-I.GID-HI
0x7C CONSTANT _EXT4-I.CSUM-LO
0x80 CONSTANT _EXT4-I.EXTRA-SIZE
0x82 CONSTANT _EXT4-I.CSUM-HI
0x84 CONSTANT _EXT4-I.CTIME-EXTRA
0x88 CONSTANT _EXT4-I.MTIME-EXTRA
0x8C CONSTANT _EXT4-I.ATIME-EXTRA

\ Mount rejection detail values.  The public reason/domain/flags remain the
\ stable interface; detail identifies the validation stage.
1  CONSTANT EXT4-D-MAGIC
2  CONSTANT EXT4-D-SUPER-CHECKSUM
3  CONSTANT EXT4-D-GEOMETRY
4  CONSTANT EXT4-D-FEATURE
5  CONSTANT EXT4-D-RECOVERY
6  CONSTANT EXT4-D-DESC-CHECKSUM
7  CONSTANT EXT4-D-BITMAP-CHECKSUM
8  CONSTANT EXT4-D-BOUNDS
9  CONSTANT EXT4-D-BACKUP-SUPER
10 CONSTANT EXT4-D-INODE-CHECKSUM
11 CONSTANT EXT4-D-ROOT-INODE
12 CONSTANT EXT4-D-JOURNAL
13 CONSTANT EXT4-D-ORPHAN-FILE
14 CONSTANT EXT4-D-ATTACHMENT
15 CONSTANT EXT4-D-DIRECTORY
16 CONSTANT EXT4-D-DATA-MAP
17 CONSTANT EXT4-D-XATTR

\ =====================================================================
\  Binding context
\ =====================================================================
\
\ +0       1024-byte superblock cache
\ +1024    4096-byte filesystem-block cache
\ +5120     256-byte inode cache
\ +5376      64-byte group-descriptor cache
\ +5440      16-byte checksum input scratch
\ +5456      96-byte STATFS staging record
\ +5552     parsed geometry and metadata staging cells
\ +5800    second 4096-byte block buffer for directory scans

   0 CONSTANT _EXT4-C.SB
1024 CONSTANT _EXT4-C.BLOCK
5120 CONSTANT _EXT4-C.INODE
5376 CONSTANT _EXT4-C.DESC
5440 CONSTANT _EXT4-C.TMP
5456 CONSTANT _EXT4-C.STAT
5552 CONSTANT _EXT4-C.READY
5560 CONSTANT _EXT4-C.BSIZE
5568 CONSTANT _EXT4-C.SPB
5576 CONSTANT _EXT4-C.BLOCKS
5584 CONSTANT _EXT4-C.INODES
5592 CONSTANT _EXT4-C.BPG
5600 CONSTANT _EXT4-C.IPG
5608 CONSTANT _EXT4-C.GROUPS
5616 CONSTANT _EXT4-C.ISIZE
5624 CONSTANT _EXT4-C.DSIZE
5632 CONSTANT _EXT4-C.FIRST
5640 CONSTANT _EXT4-C.SEED
5648 CONSTANT _EXT4-C.FREE-BLOCKS
5656 CONSTANT _EXT4-C.FREE-INODES
5664 CONSTANT _EXT4-C.RESERVED-BLOCKS
5672 CONSTANT _EXT4-C.ORPHAN-INO
5680 CONSTANT _EXT4-C.R.MODE
5688 CONSTANT _EXT4-C.R.SIZE
5696 CONSTANT _EXT4-C.R.UID
5704 CONSTANT _EXT4-C.R.GID
5712 CONSTANT _EXT4-C.R.NLINK
5720 CONSTANT _EXT4-C.R.ATIME
5728 CONSTANT _EXT4-C.R.MTIME
5736 CONSTANT _EXT4-C.R.CTIME
5744 CONSTANT _EXT4-C.R.ATIME-NS
5752 CONSTANT _EXT4-C.R.MTIME-NS
5760 CONSTANT _EXT4-C.R.CTIME-NS
5768 CONSTANT _EXT4-C.R.BLOCKS
5776 CONSTANT _EXT4-C.R.GEN
5784 CONSTANT _EXT4-C.UUID-LO
5792 CONSTANT _EXT4-C.UUID-HI
5800 CONSTANT _EXT4-C.DIR-BLOCK
9896 CONSTANT _EXT4-CTX-SIZE

: _EXT4-CTX  ( vfs -- ctx )  V.BCTX @ ;
: _EXT4-READY?  ( vfs -- flag )
    V.BCTX @ DUP 0= IF DROP FALSE EXIT THEN
    _EXT4-C.READY + @ 0<> ;

\ =====================================================================
\  Private reflected CRC32C (ext4/e2fsprogs semantics)
\ =====================================================================
\
\ The platform CRC32C word is intentionally MSB-first.  ext4 uses the
\ reflected Castagnoli kernel with polynomial 0x82f63b78, seed 0xffffffff,
\ and no final xor.  Keep this implementation private to avoid conflating
\ the two contracts.

CREATE _EXT4-CRC-TABLE 256 CELLS ALLOT
VARIABLE _EXT4-CRC-WORK
VARIABLE _EXT4-CRC-STATE

: _EXT4-CRC-TABLE-INIT  ( -- )
    256 0 DO
        I _EXT4-CRC-WORK !
        8 0 DO
            _EXT4-CRC-WORK @ DUP 1 AND IF
                1 RSHIFT 0x82F63B78 XOR
            ELSE
                1 RSHIFT
            THEN
            0xFFFFFFFF AND _EXT4-CRC-WORK !
        LOOP
        _EXT4-CRC-WORK @ _EXT4-CRC-TABLE I CELLS + !
    LOOP ;

_EXT4-CRC-TABLE-INIT

: _EXT4-CRC-START  ( seed -- )  0xFFFFFFFF AND _EXT4-CRC-STATE ! ;
: _EXT4-CRC-ADD  ( addr len -- )
    0 ?DO
        DUP I + C@ _EXT4-CRC-STATE @ XOR 0xFF AND
        CELLS _EXT4-CRC-TABLE + @
        _EXT4-CRC-STATE @ 8 RSHIFT XOR 0xFFFFFFFF AND
        _EXT4-CRC-STATE !
    LOOP DROP ;
: _EXT4-CRC@  ( -- crc )  _EXT4-CRC-STATE @ ;

\ =====================================================================
\  Structured checked volume I/O
\ =====================================================================

VARIABLE _EXT4-IO-VFS
VARIABLE _EXT4-IO-VOL
VARIABLE _EXT4-IO-EXPECTED
VARIABLE _EXT4-IO-COMPLETED
VARIABLE _EXT4-IO-BACKEND
VARIABLE _EXT4-IO-FLAGS
VARIABLE _EXT4-IO-REASON

: _EXT4-LATCH-STALE  ( -- )
    _EXT4-IO-VFS @ ?DUP IF VFS-L-STALE SWAP V.LIFECYCLE ! THEN ;

: _EXT4-MAP-IOR  ( backend-ior -- vfs-ior )
    DUP _EXT4-IO-BACKEND !
    0 _EXT4-IO-FLAGS !
    VFS-R-IO _EXT4-IO-REASON !
    DUP IF
        DUP IOR>FLAGS
        DUP IOR-F-RETRYABLE AND IF
            VFS-IOR-F-RETRYABLE _EXT4-IO-FLAGS +!
        THEN
        DUP IOR-F-PARTIAL AND IF
            VFS-IOR-F-PARTIAL _EXT4-IO-FLAGS +!
        THEN
        DUP IOR-F-CORRUPT AND IF
            VFS-IOR-F-CORRUPT _EXT4-IO-FLAGS +!
            VFS-R-CORRUPT _EXT4-IO-REASON !
        THEN
        DUP IOR-F-UNSUPPORTED AND IF
            VFS-R-UNSUPPORTED _EXT4-IO-REASON !
        THEN
        DUP IOR-F-READONLY AND IF
            VFS-IOR-F-READONLY _EXT4-IO-FLAGS +!
            VFS-R-READONLY _EXT4-IO-REASON !
        THEN
        IOR-F-STALE AND IF
            VFS-IOR-F-STALE _EXT4-IO-FLAGS +!
            VFS-R-STALE _EXT4-IO-REASON !
            _EXT4-LATCH-STALE
        THEN
    THEN
    _EXT4-IO-COMPLETED @ _EXT4-IO-EXPECTED @ <> IF
        VFS-IOR-F-PARTIAL _EXT4-IO-FLAGS DUP @ ROT OR SWAP !
    THEN
    _EXT4-IO-BACKEND @ 0=
    _EXT4-IO-COMPLETED @ _EXT4-IO-EXPECTED @ = AND IF
        DROP 0 EXIT
    THEN
    DROP
    _EXT4-IO-BACKEND @ 0xFFFFFFFF AND
    _EXT4-IO-FLAGS @ VFS-IOR-D-VOLUME _EXT4-IO-REASON @ VFS-IOR-MAKE ;

: _EXT4-READ-SECTORS  ( dma lba count -- ior )
    DUP _EXT4-IO-EXPECTED !
    _EXT4-IO-VOL @ VOL-READ
    SWAP _EXT4-IO-COMPLETED ! _EXT4-MAP-IOR ;

: _EXT4-CORRUPT  ( detail -- ior )
    VFS-IOR-F-CORRUPT VFS-IOR-D-FORMAT VFS-R-CORRUPT VFS-IOR-MAKE ;
: _EXT4-UNSUPPORTED  ( detail -- ior )
    0 VFS-IOR-D-FORMAT VFS-R-UNSUPPORTED VFS-IOR-MAKE ;

\ =====================================================================
\  Probe
\ =====================================================================

90 CONSTANT EXT4-PROBE-SCORE
CREATE _EXT4-PROBE-BUF _EXT4-SB-SIZE ALLOT
VARIABLE _EXT4-PROBE-VOL

: _EXT4-PROBE  ( volume -- score ior )
    _EXT4-PROBE-VOL !
    _EXT4-PROBE-VOL @ VOL.SECTOR-SIZE _EXT4-SECTOR <> IF
        0 0 VFS-IOR-D-VOLUME VFS-R-UNSUPPORTED VFS-IOR-MAKE EXIT
    THEN
    0 _EXT4-IO-VFS !
    _EXT4-PROBE-VOL @ _EXT4-IO-VOL !
    _EXT4-PROBE-BUF 2 2 _EXT4-READ-SECTORS
    DUP IF 0 SWAP EXIT THEN DROP
    _EXT4-PROBE-BUF _EXT4-SB.MAGIC + W@ _EXT4-MAGIC = IF
        EXT4-PROBE-SCORE
    ELSE
        0
    THEN 0 ;

\ =====================================================================
\  Generic validation helpers
\ =====================================================================

VARIABLE _EXT4-RB-BLOCK
VARIABLE _EXT4-RB-CTX

: _EXT4-READ-BLOCK  ( block ctx -- ior )
    _EXT4-RB-CTX ! _EXT4-RB-BLOCK !
    _EXT4-RB-BLOCK @ _EXT4-RB-CTX @ _EXT4-C.BLOCKS + @ >= IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-RB-BLOCK @ _EXT4-RB-CTX @ _EXT4-C.SPB + @ *
    _EXT4-RB-CTX @ _EXT4-C.BLOCK + SWAP
    _EXT4-RB-CTX @ _EXT4-C.SPB + @ _EXT4-READ-SECTORS ;

: _EXT4-BYTES=?  ( a b len -- flag )
    0 ?DO
        2DUP I + C@ SWAP I + C@ <> IF 2DROP FALSE UNLOOP EXIT THEN
    LOOP 2DROP TRUE ;

VARIABLE _EXT4-PO-N
VARIABLE _EXT4-PO-B
: _EXT4-POWER-OF?  ( n base -- flag )
    _EXT4-PO-B ! _EXT4-PO-N !
    BEGIN _EXT4-PO-N @ 1 > WHILE
        _EXT4-PO-N @ _EXT4-PO-B @ MOD IF FALSE EXIT THEN
        _EXT4-PO-N @ _EXT4-PO-B @ / _EXT4-PO-N !
    REPEAT
    _EXT4-PO-N @ 1 = ;

: _EXT4-SPARSE-GROUP?  ( group -- flag )
    DUP 0= OVER 1 = OR IF DROP TRUE EXIT THEN
    DUP 3 _EXT4-POWER-OF? IF DROP TRUE EXIT THEN
    DUP 5 _EXT4-POWER-OF? IF DROP TRUE EXIT THEN
    7 _EXT4-POWER-OF? ;

VARIABLE _EXT4-ATT-V
: _EXT4-ATTACHED?  ( vfs -- flag )
    DUP _EXT4-ATT-V ! V.VOLUME @
    DUP 0= IF DROP FALSE EXIT THEN
    DUP VOL-VALID? 0= IF DROP FALSE EXIT THEN
    DUP VOL-STALE? IF DROP FALSE EXIT THEN
    DUP VOL.COOKIE _EXT4-ATT-V @ V.VOL-COOKIE @ =
    SWAP VOL.MEDIA-GEN _EXT4-ATT-V @ V.MEDIA-GEN @ = AND ;

\ =====================================================================
\  Superblock validation and geometry admission
\ =====================================================================

VARIABLE _EXT4-SV-CTX
VARIABLE _EXT4-SV-SB
VARIABLE _EXT4-SV-STORED
VARIABLE _EXT4-SV-LOG
VARIABLE _EXT4-SV-RO
VARIABLE _EXT4-SV-GROUPS

: _EXT4-SUPER-CHECKSUM?  ( sb -- flag )
    DUP _EXT4-SB.CHECKSUM + L@ _EXT4-SV-STORED !
    0xFFFFFFFF _EXT4-CRC-START
    _EXT4-SB.CHECKSUM _EXT4-CRC-ADD
    _EXT4-CRC@ _EXT4-SV-STORED @ = ;

: _EXT4-SUPER-SEED?  ( sb -- flag )
    DUP _EXT4-SB.CSUM-SEED + L@ >R
    0xFFFFFFFF _EXT4-CRC-START
    _EXT4-SB.UUID + 16 _EXT4-CRC-ADD
    _EXT4-CRC@ R> = ;

: _EXT4-VALIDATE-SUPER  ( ctx vfs -- ior )
    DROP _EXT4-SV-CTX !
    _EXT4-SV-CTX @ _EXT4-C.SB + _EXT4-SV-SB !
    _EXT4-SV-SB @ _EXT4-SB.MAGIC + W@ _EXT4-MAGIC <> IF
        EXT4-D-MAGIC _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SUPER-CHECKSUM? 0= IF
        EXT4-D-SUPER-CHECKSUM _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SUPER-SEED? 0= IF
        EXT4-D-SUPER-CHECKSUM _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.REVISION + L@ 1 <
    _EXT4-SV-SB @ _EXT4-SB.CREATOR + L@ 0<> OR IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.COMPAT + L@ _EXT4-COMPAT-V1 <> IF
        EXT4-D-FEATURE _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.INCOMPAT + L@ DUP 4 AND IF
        DROP EXT4-D-RECOVERY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-INCOMPAT-V1 <> IF
        EXT4-D-FEATURE _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.RO-COMPAT + L@ DUP 0x10000 AND IF
        DROP EXT4-D-RECOVERY _EXT4-UNSUPPORTED EXIT
    THEN
    DUP _EXT4-RO-REFUSED AND IF
        DROP EXT4-D-FEATURE _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-RO-READONLY INVERT AND _EXT4-SV-RO !
    _EXT4-SV-SB @ _EXT4-SB.INODE-SIZE + W@ DUP
    128 = IF
        DROP _EXT4-SV-RO @ _EXT4-RO-I128-V1 AND
        _EXT4-RO-I128-V1 <>
    ELSE
        256 <> _EXT4-SV-RO @ _EXT4-RO-V1 AND
        _EXT4-RO-V1 <> OR
    THEN IF EXT4-D-FEATURE _EXT4-UNSUPPORTED EXIT THEN
    _EXT4-SV-SB @ _EXT4-SB.STATE + W@ 1 <>
    _EXT4-SV-SB @ _EXT4-SB.LAST-ORPHAN + L@ 0<> OR IF
        EXT4-D-RECOVERY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.ERRORS + W@ 2 <> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.LOG-BLOCK + L@ DUP _EXT4-SV-LOG ! 2 > IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.LOG-CLUSTER + L@ _EXT4-SV-LOG @ <> IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    1024 _EXT4-SV-LOG @ LSHIFT DUP
    _EXT4-SV-CTX @ _EXT4-C.BSIZE + !
    512 / _EXT4-SV-CTX @ _EXT4-C.SPB + !
    _EXT4-SV-SB @ _EXT4-SB.BLOCKS-HI + L@ 0<> IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.BLOCKS-LO + L@
    _EXT4-SV-CTX @ _EXT4-C.BLOCKS + !
    _EXT4-SV-SB @ _EXT4-SB.FIRST-DATA + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.FIRST + !
    _EXT4-SV-LOG @ 0= IF 1 <> ELSE 0<> THEN IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-CTX @ _EXT4-C.BLOCKS + @
    _EXT4-SV-CTX @ _EXT4-C.FIRST + @ <= IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-CTX @ _EXT4-C.BLOCKS + @
    _EXT4-SV-CTX @ _EXT4-C.SPB + @ *
    _EXT4-IO-VOL @ VOL.SECTORS U> IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.BPG + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.BPG + !
    _EXT4-SV-CTX @ _EXT4-C.BSIZE + @ 8 * <> IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.CPG + L@
    _EXT4-SV-CTX @ _EXT4-C.BPG + @ <> IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.IPG + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.IPG + !
    _EXT4-SV-CTX @ _EXT4-C.BPG + @
    _EXT4-SV-CTX @ _EXT4-C.BSIZE + @ * 16384 / <> IF
        EXT4-D-GEOMETRY _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-SV-CTX @ _EXT4-C.BLOCKS + @
    _EXT4-SV-CTX @ _EXT4-C.FIRST + @ -
    _EXT4-SV-CTX @ _EXT4-C.BPG + @ 1- +
    _EXT4-SV-CTX @ _EXT4-C.BPG + @ /
    DUP _EXT4-SV-GROUPS ! _EXT4-SV-CTX @ _EXT4-C.GROUPS + !
    _EXT4-SV-GROUPS @ 0= IF EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT THEN
    _EXT4-SV-SB @ _EXT4-SB.INODES + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.INODES + !
    _EXT4-SV-GROUPS @ _EXT4-SV-CTX @ _EXT4-C.IPG + @ * <> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.INODE-SIZE + W@ DUP
    _EXT4-SV-CTX @ _EXT4-C.ISIZE + !
    256 = IF
        _EXT4-SV-SB @ _EXT4-SB.MIN-EXTRA + W@ 32 <
        _EXT4-SV-SB @ _EXT4-SB.WANT-EXTRA + W@ 32 < OR IF
            EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
        THEN
    THEN
    _EXT4-SV-SB @ _EXT4-SB.DESC-SIZE + W@ DUP
    _EXT4-SV-CTX @ _EXT4-C.DSIZE + !
    _EXT4-DESC-SIZE <> IF EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT THEN
    _EXT4-SV-SB @ _EXT4-SB.LOG-FLEX + C@ 4 <>
    _EXT4-SV-SB @ _EXT4-SB.CSUM-TYPE + C@ 1 <> OR IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.FIRST-INO + L@ 11 < IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.JOURNAL-INO + L@ 8 <> IF
        EXT4-D-JOURNAL _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.ORPHAN-INO + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.ORPHAN-INO + !
    DUP 0= SWAP _EXT4-SV-CTX @ _EXT4-C.INODES + @ > OR IF
        EXT4-D-ORPHAN-FILE _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.RBLOCKS-HI + L@ 0<>
    _EXT4-SV-SB @ _EXT4-SB.FREE-BLOCKS-HI + L@ 0<> OR IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.RBLOCKS-LO + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.RESERVED-BLOCKS + !
    _EXT4-SV-CTX @ _EXT4-C.BLOCKS + @ U> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.FREE-BLOCKS-LO + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.FREE-BLOCKS + !
    _EXT4-SV-CTX @ _EXT4-C.BLOCKS + @ U> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.FREE-INODES + L@ DUP
    _EXT4-SV-CTX @ _EXT4-C.FREE-INODES + !
    _EXT4-SV-CTX @ _EXT4-C.INODES + @ U> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-SV-SB @ _EXT4-SB.CSUM-SEED + L@
    _EXT4-SV-CTX @ _EXT4-C.SEED + !
    _EXT4-SV-SB @ _EXT4-SB.UUID + @
    _EXT4-SV-CTX @ _EXT4-C.UUID-LO + !
    _EXT4-SV-SB @ _EXT4-SB.UUID 8 + + @
    _EXT4-SV-CTX @ _EXT4-C.UUID-HI + !
    0 ;

\ =====================================================================
\  Group descriptors and initialized bitmap checksums
\ =====================================================================

VARIABLE _EXT4-GD-GROUP
VARIABLE _EXT4-GD-BASE
VARIABLE _EXT4-GD-CTX
VARIABLE _EXT4-GD-BYTE
VARIABLE _EXT4-GD-BLOCK
VARIABLE _EXT4-GD-OFF
VARIABLE _EXT4-GD-STORED
VARIABLE _EXT4-GD-FLAGS
VARIABLE _EXT4-GD-PTR
VARIABLE _EXT4-GD-SPAN

: _EXT4-GDT-BASE  ( ctx -- block )
    _EXT4-C.BSIZE + @ 1024 = IF 2 ELSE 1 THEN ;

: _EXT4-LOAD-DESC-AT  ( group gdt-base ctx -- ior )
    _EXT4-GD-CTX ! _EXT4-GD-BASE ! _EXT4-GD-GROUP !
    _EXT4-GD-GROUP @ _EXT4-GD-CTX @ _EXT4-C.GROUPS + @ >= IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-GD-GROUP @ _EXT4-DESC-SIZE * _EXT4-GD-BYTE !
    _EXT4-GD-BASE @
    _EXT4-GD-BYTE @ _EXT4-GD-CTX @ _EXT4-C.BSIZE + @ / +
    DUP _EXT4-GD-BLOCK ! _EXT4-GD-CTX @ _EXT4-READ-BLOCK ?DUP IF EXIT THEN
    _EXT4-GD-BYTE @ _EXT4-GD-CTX @ _EXT4-C.BSIZE + @ MOD
    DUP _EXT4-GD-OFF ! _EXT4-DESC-SIZE +
    _EXT4-GD-CTX @ _EXT4-C.BSIZE + @ > IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-GD-CTX @ _EXT4-C.BLOCK + _EXT4-GD-OFF @ +
    _EXT4-GD-CTX @ _EXT4-C.DESC + _EXT4-DESC-SIZE CMOVE
    _EXT4-GD-CTX @ _EXT4-C.DESC + DUP
    _EXT4-GD.CHECKSUM + W@ _EXT4-GD-STORED !
    0 OVER _EXT4-GD.CHECKSUM + W!
    _EXT4-GD-GROUP @ _EXT4-GD-CTX @ _EXT4-C.TMP + L!
    _EXT4-GD-CTX @ _EXT4-C.SEED + @ _EXT4-CRC-START
    _EXT4-GD-CTX @ _EXT4-C.TMP + 4 _EXT4-CRC-ADD
    _EXT4-DESC-SIZE _EXT4-CRC-ADD
    _EXT4-GD-STORED @ _EXT4-GD-CTX @ _EXT4-C.DESC +
    _EXT4-GD.CHECKSUM + W!
    _EXT4-CRC@ 0xFFFF AND _EXT4-GD-STORED @ <> IF
        EXT4-D-DESC-CHECKSUM _EXT4-CORRUPT EXIT
    THEN
    _EXT4-GD-CTX @ _EXT4-C.DESC + DUP
    _EXT4-GD.BLOCK-BITMAP-HI + L@ 0<>
    OVER _EXT4-GD.INODE-BITMAP-HI + L@ 0<> OR
    OVER _EXT4-GD.INODE-TABLE-HI + L@ 0<> OR IF
        DROP EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    DUP _EXT4-GD.BLOCK-BITMAP-LO + L@ DUP _EXT4-GD-PTR !
    0= _EXT4-GD-PTR @ _EXT4-GD-CTX @ _EXT4-C.BLOCKS + @ >= OR IF
        DROP EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    DUP _EXT4-GD.INODE-BITMAP-LO + L@ DUP _EXT4-GD-PTR !
    0= _EXT4-GD-PTR @ _EXT4-GD-CTX @ _EXT4-C.BLOCKS + @ >= OR IF
        DROP EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    DUP _EXT4-GD.INODE-TABLE-LO + L@ DUP _EXT4-GD-PTR !
    0= IF DROP EXT4-D-BOUNDS _EXT4-CORRUPT EXIT THEN
    _EXT4-GD-CTX @ _EXT4-C.IPG + @
    _EXT4-GD-CTX @ _EXT4-C.ISIZE + @ *
    _EXT4-GD-CTX @ _EXT4-C.BSIZE + @ 1- +
    _EXT4-GD-CTX @ _EXT4-C.BSIZE + @ /
    DUP _EXT4-GD-SPAN !
    _EXT4-GD-PTR @ SWAP
    _EXT4-GD-CTX @ _EXT4-C.BLOCKS + @ BLOCK-RANGE? 0= IF
        DROP EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    DUP _EXT4-GD.FLAGS + W@ DUP _EXT4-GD-FLAGS ! 7 INVERT AND IF
        DROP EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    DUP _EXT4-GD.FREE-BLOCKS-LO + W@
    OVER _EXT4-GD.FREE-BLOCKS-HI + W@ 16 LSHIFT OR
    _EXT4-GD-CTX @ _EXT4-C.BPG + @ U> IF
        DROP EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    DUP _EXT4-GD.FREE-INODES-LO + W@
    OVER _EXT4-GD.FREE-INODES-HI + W@ 16 LSHIFT OR
    _EXT4-GD-CTX @ _EXT4-C.IPG + @ U> IF
        DROP EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    DUP _EXT4-GD.USED-DIRS-LO + W@
    SWAP _EXT4-GD.USED-DIRS-HI + W@ 16 LSHIFT OR
    _EXT4-GD-CTX @ _EXT4-C.IPG + @ U> IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    0 ;

: _EXT4-LOAD-DESC  ( group ctx -- ior )
    DUP _EXT4-GDT-BASE SWAP _EXT4-LOAD-DESC-AT ;

VARIABLE _EXT4-BM-GROUP
VARIABLE _EXT4-BM-CTX
VARIABLE _EXT4-BM-STORED

: _EXT4-VALIDATE-BITMAPS  ( group ctx -- ior )
    _EXT4-BM-CTX ! _EXT4-BM-GROUP !
    _EXT4-BM-GROUP @ _EXT4-BM-CTX @ _EXT4-LOAD-DESC ?DUP IF EXIT THEN
    _EXT4-GD-FLAGS @ _EXT4-BG-BLOCK-UNINIT AND 0= IF
        _EXT4-BM-CTX @ _EXT4-C.DESC + DUP
        _EXT4-GD.BLOCK-CSUM-LO + W@
        SWAP _EXT4-GD.BLOCK-CSUM-HI + W@ 16 LSHIFT OR
        _EXT4-BM-STORED !
        _EXT4-BM-CTX @ _EXT4-C.DESC + _EXT4-GD.BLOCK-BITMAP-LO + L@
        _EXT4-BM-CTX @ _EXT4-READ-BLOCK ?DUP IF EXIT THEN
        _EXT4-BM-CTX @ _EXT4-C.SEED + @ _EXT4-CRC-START
        _EXT4-BM-CTX @ _EXT4-C.BLOCK +
        _EXT4-BM-CTX @ _EXT4-C.BPG + @ 8 / _EXT4-CRC-ADD
        _EXT4-CRC@ _EXT4-BM-STORED @ <> IF
            EXT4-D-BITMAP-CHECKSUM _EXT4-CORRUPT EXIT
        THEN
    THEN
    _EXT4-GD-FLAGS @ _EXT4-BG-INODE-UNINIT AND 0= IF
        _EXT4-BM-CTX @ _EXT4-C.DESC + DUP
        _EXT4-GD.INODE-CSUM-LO + W@
        SWAP _EXT4-GD.INODE-CSUM-HI + W@ 16 LSHIFT OR
        _EXT4-BM-STORED !
        _EXT4-BM-CTX @ _EXT4-C.DESC + _EXT4-GD.INODE-BITMAP-LO + L@
        _EXT4-BM-CTX @ _EXT4-READ-BLOCK ?DUP IF EXIT THEN
        _EXT4-BM-CTX @ _EXT4-C.SEED + @ _EXT4-CRC-START
        _EXT4-BM-CTX @ _EXT4-C.BLOCK +
        _EXT4-BM-CTX @ _EXT4-C.IPG + @ 8 / _EXT4-CRC-ADD
        _EXT4-CRC@ _EXT4-BM-STORED @ <> IF
            EXT4-D-BITMAP-CHECKSUM _EXT4-CORRUPT EXIT
        THEN
    THEN
    0 ;

VARIABLE _EXT4-VG-CTX
VARIABLE _EXT4-VG-FREE-BLOCKS
VARIABLE _EXT4-VG-FREE-INODES
VARIABLE _EXT4-VG-ADD
: _EXT4-VALIDATE-GROUPS  ( ctx -- ior )
    _EXT4-VG-CTX !
    0 _EXT4-VG-FREE-BLOCKS ! 0 _EXT4-VG-FREE-INODES !
    _EXT4-VG-CTX @ _EXT4-C.GROUPS + @ 0 DO
        I _EXT4-VG-CTX @ _EXT4-VALIDATE-BITMAPS ?DUP IF
            UNLOOP EXIT
        THEN
        _EXT4-VG-CTX @ _EXT4-C.DESC + DUP
        _EXT4-GD.FREE-BLOCKS-LO + W@
        SWAP _EXT4-GD.FREE-BLOCKS-HI + W@ 16 LSHIFT OR
        DUP _EXT4-VG-ADD ! _EXT4-VG-FREE-BLOCKS @ +
        DUP _EXT4-VG-ADD @ U< IF
            DROP EXT4-D-GEOMETRY _EXT4-CORRUPT UNLOOP EXIT
        THEN _EXT4-VG-FREE-BLOCKS !
        _EXT4-VG-CTX @ _EXT4-C.DESC + DUP
        _EXT4-GD.FREE-INODES-LO + W@
        SWAP _EXT4-GD.FREE-INODES-HI + W@ 16 LSHIFT OR
        DUP _EXT4-VG-ADD ! _EXT4-VG-FREE-INODES @ +
        DUP _EXT4-VG-ADD @ U< IF
            DROP EXT4-D-GEOMETRY _EXT4-CORRUPT UNLOOP EXIT
        THEN _EXT4-VG-FREE-INODES !
    LOOP
    _EXT4-VG-FREE-BLOCKS @ _EXT4-VG-CTX @ _EXT4-C.FREE-BLOCKS + @ <>
    _EXT4-VG-FREE-INODES @ _EXT4-VG-CTX @ _EXT4-C.FREE-INODES + @ <> OR IF
        EXT4-D-GEOMETRY _EXT4-CORRUPT EXIT
    THEN
    0 ;

\ =====================================================================
\  Sparse-super backup validation
\ =====================================================================

VARIABLE _EXT4-BS-GROUP
VARIABLE _EXT4-BS-CTX
VARIABLE _EXT4-BS-BLOCK
VARIABLE _EXT4-BS-BUF
VARIABLE _EXT4-BS-PRIMARY

VARIABLE _EXT4-BG-BASE
VARIABLE _EXT4-BG-CTX
VARIABLE _EXT4-BG-BLOCK-BITMAP
VARIABLE _EXT4-BG-INODE-BITMAP
VARIABLE _EXT4-BG-INODE-TABLE

\ A backup GDT can lag mutable counters and bitmap checksums after ordinary
\ filesystem activity.  Its own descriptor CRC must nevertheless validate,
\ and the immutable metadata locations must still agree with the primary
\ descriptor.  Reuse the primary descriptor parser so every copy receives
\ the same group-number CRC and bounds checks.
: _EXT4-VALIDATE-BACKUP-GDT  ( gdt-base ctx -- ior )
    _EXT4-BG-CTX ! _EXT4-BG-BASE !
    _EXT4-BG-CTX @ _EXT4-C.GROUPS + @ 0 ?DO
        I _EXT4-BG-CTX @ _EXT4-LOAD-DESC ?DUP IF
            UNLOOP EXIT
        THEN
        _EXT4-BG-CTX @ _EXT4-C.DESC + DUP
            _EXT4-GD.BLOCK-BITMAP-LO + L@ _EXT4-BG-BLOCK-BITMAP !
        DUP _EXT4-GD.INODE-BITMAP-LO + L@ _EXT4-BG-INODE-BITMAP !
        _EXT4-GD.INODE-TABLE-LO + L@ _EXT4-BG-INODE-TABLE !
        I _EXT4-BG-BASE @ _EXT4-BG-CTX @ _EXT4-LOAD-DESC-AT
        ?DUP IF UNLOOP EXIT THEN
        _EXT4-BG-CTX @ _EXT4-C.DESC + DUP
            _EXT4-GD.BLOCK-BITMAP-LO + L@
            _EXT4-BG-BLOCK-BITMAP @ <> IF
                DROP EXT4-D-DESC-CHECKSUM _EXT4-CORRUPT UNLOOP EXIT
            THEN
        DUP _EXT4-GD.INODE-BITMAP-LO + L@
            _EXT4-BG-INODE-BITMAP @ <> IF
                DROP EXT4-D-DESC-CHECKSUM _EXT4-CORRUPT UNLOOP EXIT
            THEN
        _EXT4-GD.INODE-TABLE-LO + L@
            _EXT4-BG-INODE-TABLE @ <> IF
                EXT4-D-DESC-CHECKSUM _EXT4-CORRUPT UNLOOP EXIT
            THEN
    LOOP
    0 ;

: _EXT4-BACKUP-SUPER-FIELDS?  ( backup ctx -- flag )
    _EXT4-BS-CTX ! _EXT4-BS-BUF !
    _EXT4-BS-CTX @ _EXT4-C.SB + _EXT4-BS-PRIMARY !
    _EXT4-BS-BUF @ _EXT4-SB.MAGIC + W@ _EXT4-MAGIC =
    _EXT4-BS-BUF @ _EXT4-SB.GROUP-NR + W@ _EXT4-BS-GROUP @ = AND
    _EXT4-BS-BUF @ _EXT4-SB.INODES + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.INODES + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.BLOCKS-LO + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.BLOCKS-LO + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.BLOCKS-HI + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.BLOCKS-HI + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.FIRST-DATA + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.FIRST-DATA + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.LOG-BLOCK + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.LOG-BLOCK + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.LOG-CLUSTER + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.LOG-CLUSTER + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.BPG + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.BPG + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.CPG + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.CPG + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.IPG + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.IPG + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.REVISION + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.REVISION + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.CREATOR + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.CREATOR + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.INODE-SIZE + W@
        _EXT4-BS-PRIMARY @ _EXT4-SB.INODE-SIZE + W@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.COMPAT + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.COMPAT + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.INCOMPAT + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.INCOMPAT + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.RO-COMPAT + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.RO-COMPAT + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.DESC-SIZE + W@
        _EXT4-BS-PRIMARY @ _EXT4-SB.DESC-SIZE + W@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.CSUM-TYPE + C@
        _EXT4-BS-PRIMARY @ _EXT4-SB.CSUM-TYPE + C@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.CSUM-SEED + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.CSUM-SEED + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.JOURNAL-INO + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.JOURNAL-INO + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.ORPHAN-INO + L@
        _EXT4-BS-PRIMARY @ _EXT4-SB.ORPHAN-INO + L@ = AND
    _EXT4-BS-BUF @ _EXT4-SB.UUID +
        _EXT4-BS-PRIMARY @ _EXT4-SB.UUID + 16 _EXT4-BYTES=? AND ;

: _EXT4-VALIDATE-BACKUP-SUPER  ( group ctx -- ior )
    _EXT4-BS-CTX ! DUP _EXT4-BS-GROUP !
    _EXT4-BS-CTX @ _EXT4-C.BPG + @ *
    _EXT4-BS-CTX @ _EXT4-C.FIRST + @ + DUP _EXT4-BS-BLOCK !
    _EXT4-BS-CTX @ _EXT4-READ-BLOCK ?DUP IF EXIT THEN
    _EXT4-BS-CTX @ _EXT4-C.BLOCK + DUP _EXT4-BS-BUF !
    _EXT4-SUPER-CHECKSUM? 0= IF
        EXT4-D-BACKUP-SUPER _EXT4-CORRUPT EXIT
    THEN
    _EXT4-BS-BUF @ _EXT4-SUPER-SEED? 0= IF
        EXT4-D-BACKUP-SUPER _EXT4-CORRUPT EXIT
    THEN
    _EXT4-BS-BUF @ _EXT4-BS-CTX @ _EXT4-BACKUP-SUPER-FIELDS? 0= IF
        EXT4-D-BACKUP-SUPER _EXT4-CORRUPT EXIT
    THEN
    _EXT4-BS-BLOCK @ 1+ _EXT4-BS-CTX @ _EXT4-VALIDATE-BACKUP-GDT ;

VARIABLE _EXT4-VB-CTX
: _EXT4-VALIDATE-BACKUPS  ( ctx -- ior )
    _EXT4-VB-CTX !
    _EXT4-VB-CTX @ _EXT4-C.GROUPS + @ 1 ?DO
        I _EXT4-SPARSE-GROUP? IF
            I _EXT4-VB-CTX @ _EXT4-VALIDATE-BACKUP-SUPER ?DUP IF
                UNLOOP EXIT
            THEN
        THEN
    LOOP 0 ;

\ =====================================================================
\  Inode loading, checksums, and inline extent validation
\ =====================================================================

VARIABLE _EXT4-IR-INO
VARIABLE _EXT4-IR-CTX
VARIABLE _EXT4-IR-GROUP
VARIABLE _EXT4-IR-INDEX
VARIABLE _EXT4-IR-BYTE
VARIABLE _EXT4-IR-BLOCK
VARIABLE _EXT4-IR-OFF
VARIABLE _EXT4-IR-LO
VARIABLE _EXT4-IR-HI
VARIABLE _EXT4-IR-HAS-HI
VARIABLE _EXT4-IR-CALC
VARIABLE _EXT4-IR-BIT

: _EXT4-LOAD-INODE  ( inode-number ctx -- ior )
    _EXT4-IR-CTX ! DUP _EXT4-IR-INO !
    DUP 0= SWAP _EXT4-IR-CTX @ _EXT4-C.INODES + @ > OR IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-IR-INO @ 1-
    _EXT4-IR-CTX @ _EXT4-C.IPG + @ /MOD
    _EXT4-IR-GROUP ! _EXT4-IR-INDEX !
    _EXT4-IR-GROUP @ _EXT4-IR-CTX @ _EXT4-LOAD-DESC ?DUP IF EXIT THEN
    _EXT4-GD-FLAGS @ _EXT4-BG-INODE-UNINIT AND IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-IR-CTX @ _EXT4-C.DESC + _EXT4-GD.INODE-BITMAP-LO + L@
    _EXT4-IR-CTX @ _EXT4-READ-BLOCK ?DUP IF EXIT THEN
    _EXT4-IR-INDEX @ 8 / _EXT4-IR-CTX @ _EXT4-C.BLOCK + + C@
    1 _EXT4-IR-INDEX @ 8 MOD LSHIFT AND 0= IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-IR-CTX @ _EXT4-C.DESC + _EXT4-GD.INODE-TABLE-LO + L@
    _EXT4-IR-INDEX @ _EXT4-IR-CTX @ _EXT4-C.ISIZE + @ *
    DUP _EXT4-IR-BYTE !
    _EXT4-IR-CTX @ _EXT4-C.BSIZE + @ / + DUP _EXT4-IR-BLOCK !
    _EXT4-IR-CTX @ _EXT4-READ-BLOCK ?DUP IF EXIT THEN
    _EXT4-IR-BYTE @ _EXT4-IR-CTX @ _EXT4-C.BSIZE + @ MOD
    DUP _EXT4-IR-OFF ! _EXT4-IR-CTX @ _EXT4-C.ISIZE + @ +
    _EXT4-IR-CTX @ _EXT4-C.BSIZE + @ > IF
        EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-IR-CTX @ _EXT4-C.BLOCK + _EXT4-IR-OFF @ +
    _EXT4-IR-CTX @ _EXT4-C.INODE +
    _EXT4-IR-CTX @ _EXT4-C.ISIZE + @ CMOVE
    _EXT4-IR-CTX @ _EXT4-C.INODE + DUP
    _EXT4-I.CSUM-LO + W@ _EXT4-IR-LO !
    0 OVER _EXT4-I.CSUM-LO + W!
    0 _EXT4-IR-HAS-HI ! 0 _EXT4-IR-HI !
    _EXT4-IR-CTX @ _EXT4-C.ISIZE + @ 128 > IF
        DUP _EXT4-I.EXTRA-SIZE + W@ DUP 4 < IF
            DROP DROP EXT4-D-INODE-CHECKSUM _EXT4-CORRUPT EXIT
        THEN
        DUP 4 MOD IF DROP DROP EXT4-D-INODE-CHECKSUM _EXT4-CORRUPT EXIT THEN
        128 + _EXT4-IR-CTX @ _EXT4-C.ISIZE + @ > IF
            DROP EXT4-D-INODE-CHECKSUM _EXT4-CORRUPT EXIT
        THEN
        DUP _EXT4-I.CSUM-HI + W@ _EXT4-IR-HI !
        0 OVER _EXT4-I.CSUM-HI + W!
        -1 _EXT4-IR-HAS-HI !
    THEN
    _EXT4-IR-INO @ _EXT4-IR-CTX @ _EXT4-C.TMP + L!
    _EXT4-IR-CTX @ _EXT4-C.SEED + @ _EXT4-CRC-START
    _EXT4-IR-CTX @ _EXT4-C.TMP + 4 _EXT4-CRC-ADD
    DUP _EXT4-I.GENERATION + 4 _EXT4-CRC-ADD
    _EXT4-IR-CTX @ _EXT4-C.ISIZE + @ _EXT4-CRC-ADD
    _EXT4-CRC@ _EXT4-IR-CALC !
    _EXT4-IR-LO @ _EXT4-IR-CTX @ _EXT4-C.INODE +
        _EXT4-I.CSUM-LO + W!
    _EXT4-IR-HAS-HI @ IF
        _EXT4-IR-HI @ _EXT4-IR-CTX @ _EXT4-C.INODE +
            _EXT4-I.CSUM-HI + W!
        _EXT4-IR-HI @ 16 LSHIFT _EXT4-IR-LO @ OR
        _EXT4-IR-CALC @ <>
    ELSE
        _EXT4-IR-CALC @ 0xFFFF AND _EXT4-IR-LO @ <>
    THEN IF EXT4-D-INODE-CHECKSUM _EXT4-CORRUPT EXIT THEN
    _EXT4-IR-CTX @ _EXT4-C.INODE + _EXT4-I.DTIME + L@ IF
        EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
    THEN
    0 ;

VARIABLE _EXT4-EV-CTX
VARIABLE _EXT4-EV-IN
VARIABLE _EXT4-EV-COUNT
VARIABLE _EXT4-EV-MAX
VARIABLE _EXT4-EV-PREV
VARIABLE _EXT4-EV-ENTRY
VARIABLE _EXT4-EV-LOGICAL
VARIABLE _EXT4-EV-LEN
VARIABLE _EXT4-EV-PHYS

: _EXT4-VALIDATE-INLINE-EXTENTS  ( ctx -- ior )
    DUP _EXT4-EV-CTX ! _EXT4-C.INODE + _EXT4-I.BLOCK + _EXT4-EV-IN !
    _EXT4-EV-IN @ W@ _EXT4-EXTENT-MAGIC <> IF
        EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
    THEN
    _EXT4-EV-IN @ 2 + W@ DUP _EXT4-EV-COUNT !
    _EXT4-EV-IN @ 4 + W@ DUP _EXT4-EV-MAX ! U> IF
        EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
    THEN
    _EXT4-EV-MAX @ 4 <> IF EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT THEN
    _EXT4-EV-IN @ 6 + W@ 0<> IF
        EXT4-D-ROOT-INODE _EXT4-UNSUPPORTED EXIT
    THEN
    0 _EXT4-EV-PREV !
    _EXT4-EV-COUNT @ 0 ?DO
        _EXT4-EV-IN @ 12 I 12 * + + _EXT4-EV-ENTRY !
        _EXT4-EV-ENTRY @ L@ DUP _EXT4-EV-LOGICAL !
        _EXT4-EV-PREV @ U< IF EXT4-D-ROOT-INODE _EXT4-CORRUPT UNLOOP EXIT THEN
        _EXT4-EV-ENTRY @ 4 + W@ DUP 0= IF
            DROP EXT4-D-ROOT-INODE _EXT4-CORRUPT UNLOOP EXIT
        THEN
        DUP 32768 > IF 32768 - THEN DUP _EXT4-EV-LEN !
        _EXT4-EV-LOGICAL @ + DUP _EXT4-EV-PREV !
        _EXT4-EV-LOGICAL @ U< IF
            EXT4-D-ROOT-INODE _EXT4-CORRUPT UNLOOP EXIT
        THEN
        _EXT4-EV-ENTRY @ 6 + W@ IF
            EXT4-D-BOUNDS _EXT4-CORRUPT UNLOOP EXIT
        THEN
        _EXT4-EV-ENTRY @ 8 + L@ DUP _EXT4-EV-PHYS !
        0= IF EXT4-D-BOUNDS _EXT4-CORRUPT UNLOOP EXIT THEN
        _EXT4-EV-PHYS @ _EXT4-EV-LEN @
        _EXT4-EV-CTX @ _EXT4-C.BLOCKS + @ BLOCK-RANGE? 0= IF
            EXT4-D-BOUNDS _EXT4-CORRUPT UNLOOP EXIT
        THEN
    LOOP 0 ;

VARIABLE _EXT4-MAP-LBLOCK
VARIABLE _EXT4-MAP-CTX
VARIABLE _EXT4-MAP-IN
VARIABLE _EXT4-MAP-ENTRY
VARIABLE _EXT4-MAP-START
VARIABLE _EXT4-MAP-LEN
VARIABLE _EXT4-MAP-RAWLEN

: _EXT4-MAP-INLINE  ( logical-block ctx -- physical present? ior )
    _EXT4-MAP-CTX ! _EXT4-MAP-LBLOCK !
    _EXT4-MAP-CTX @ _EXT4-C.INODE + _EXT4-I.BLOCK + _EXT4-MAP-IN !
    _EXT4-MAP-IN @ 2 + W@ 0 ?DO
        _EXT4-MAP-IN @ 12 I 12 * + + _EXT4-MAP-ENTRY !
        _EXT4-MAP-ENTRY @ L@ _EXT4-MAP-START !
        _EXT4-MAP-ENTRY @ 4 + W@ DUP _EXT4-MAP-RAWLEN !
        DUP 32768 > IF 32768 - THEN _EXT4-MAP-LEN !
        _EXT4-MAP-LBLOCK @ _EXT4-MAP-START @ >=
        _EXT4-MAP-LBLOCK @ _EXT4-MAP-START @ _EXT4-MAP-LEN @ + < AND IF
            _EXT4-MAP-RAWLEN @ 32768 > IF 0 FALSE 0 UNLOOP EXIT THEN
            _EXT4-MAP-ENTRY @ 8 + L@
            _EXT4-MAP-LBLOCK @ _EXT4-MAP-START @ - + TRUE 0
            UNLOOP EXIT
        THEN
    LOOP
    0 FALSE 0 ;

VARIABLE _EXT4-IB-IN
VARIABLE _EXT4-IB-CTX

: _EXT4-DECODE-I-BLOCKS  ( inode ctx -- blocks-512 ior )
    _EXT4-IB-CTX ! _EXT4-IB-IN !
    _EXT4-IB-IN @ _EXT4-I.BLOCKS-HI + W@ 32 LSHIFT
    _EXT4-IB-IN @ _EXT4-I.BLOCKS-LO + L@ OR
    _EXT4-IB-IN @ _EXT4-I.FLAGS + L@ _EXT4-HUGE-FILE-FL AND IF
        _EXT4-IB-CTX @ _EXT4-C.SPB + @ *
    THEN
    DUP _EXT4-IB-CTX @ _EXT4-C.BLOCKS + @
        _EXT4-IB-CTX @ _EXT4-C.SPB + @ * U> IF
        DROP 0 EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    0 ;

: _EXT4-S32@  ( addr -- n )
    L@ DUP 0x80000000 AND IF 0xFFFFFFFF00000000 OR THEN ;

\ =====================================================================
\  Root metadata staging and publication
\ =====================================================================

VARIABLE _EXT4-RS-CTX
VARIABLE _EXT4-RS-IN
VARIABLE _EXT4-RS-HI
VARIABLE _EXT4-RS-EXTRA

: _EXT4-STAGE-ROOT  ( ctx -- ior )
    DUP _EXT4-RS-CTX ! _EXT4-C.INODE + _EXT4-RS-IN !
    _EXT4-RS-IN @ _EXT4-I.MODE + W@ DUP 0xF000 AND 0x4000 <> IF
        DROP EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
    THEN
    _EXT4-RS-CTX @ _EXT4-C.R.MODE + !
    _EXT4-RS-IN @ _EXT4-I.LINKS + W@ DUP 0= IF
        DROP EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
    THEN
    _EXT4-RS-CTX @ _EXT4-C.R.NLINK + !
    _EXT4-RS-IN @ _EXT4-I.SIZE-HI + L@ DUP _EXT4-RS-HI !
    0x80000000 AND IF EXT4-D-BOUNDS _EXT4-CORRUPT EXIT THEN
    _EXT4-RS-HI @ 32 LSHIFT _EXT4-RS-IN @ _EXT4-I.SIZE-LO + L@ OR
    _EXT4-RS-CTX @ _EXT4-C.R.SIZE + !
    _EXT4-RS-IN @ _EXT4-I.UID-HI + W@ 16 LSHIFT
    _EXT4-RS-IN @ _EXT4-I.UID-LO + W@ OR
    _EXT4-RS-CTX @ _EXT4-C.R.UID + !
    _EXT4-RS-IN @ _EXT4-I.GID-HI + W@ 16 LSHIFT
    _EXT4-RS-IN @ _EXT4-I.GID-LO + W@ OR
    _EXT4-RS-CTX @ _EXT4-C.R.GID + !
    _EXT4-RS-IN @ _EXT4-RS-CTX @ _EXT4-DECODE-I-BLOCKS
    ?DUP IF NIP EXIT THEN
    _EXT4-RS-CTX @ _EXT4-C.R.BLOCKS + !
    _EXT4-RS-IN @ _EXT4-I.GENERATION + L@
    _EXT4-RS-CTX @ _EXT4-C.R.GEN + !
    _EXT4-RS-IN @ _EXT4-I.ATIME + _EXT4-S32@
    _EXT4-RS-CTX @ _EXT4-C.R.ATIME + !
    _EXT4-RS-IN @ _EXT4-I.MTIME + _EXT4-S32@
    _EXT4-RS-CTX @ _EXT4-C.R.MTIME + !
    _EXT4-RS-IN @ _EXT4-I.CTIME + _EXT4-S32@
    _EXT4-RS-CTX @ _EXT4-C.R.CTIME + !
    0 _EXT4-RS-CTX @ _EXT4-C.R.ATIME-NS + !
    0 _EXT4-RS-CTX @ _EXT4-C.R.MTIME-NS + !
    0 _EXT4-RS-CTX @ _EXT4-C.R.CTIME-NS + !
    _EXT4-RS-CTX @ _EXT4-C.ISIZE + @ 128 > IF
        _EXT4-RS-IN @ _EXT4-I.EXTRA-SIZE + W@ 16 < IF
            EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
        THEN
        _EXT4-RS-IN @ _EXT4-I.ATIME-EXTRA + L@ DUP _EXT4-RS-EXTRA !
        2 RSHIFT DUP 1000000000 U< 0= IF
            DROP EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
        THEN _EXT4-RS-CTX @ _EXT4-C.R.ATIME-NS + !
        _EXT4-RS-EXTRA @ 3 AND 32 LSHIFT
        _EXT4-RS-CTX @ _EXT4-C.R.ATIME + +!
        _EXT4-RS-IN @ _EXT4-I.MTIME-EXTRA + L@ DUP _EXT4-RS-EXTRA !
        2 RSHIFT DUP 1000000000 U< 0= IF
            DROP EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
        THEN _EXT4-RS-CTX @ _EXT4-C.R.MTIME-NS + !
        _EXT4-RS-EXTRA @ 3 AND 32 LSHIFT
        _EXT4-RS-CTX @ _EXT4-C.R.MTIME + +!
        _EXT4-RS-IN @ _EXT4-I.CTIME-EXTRA + L@ DUP _EXT4-RS-EXTRA !
        2 RSHIFT DUP 1000000000 U< 0= IF
            DROP EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
        THEN _EXT4-RS-CTX @ _EXT4-C.R.CTIME-NS + !
        _EXT4-RS-EXTRA @ 3 AND 32 LSHIFT
        _EXT4-RS-CTX @ _EXT4-C.R.CTIME + +!
    THEN
    _EXT4-RS-IN @ _EXT4-I.FLAGS + L@ _EXT4-EXTENTS-FL AND 0= IF
        EXT4-D-ROOT-INODE _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-RS-CTX @ _EXT4-VALIDATE-INLINE-EXTENTS ;

VARIABLE _EXT4-RP-V
VARIABLE _EXT4-RP-CTX
VARIABLE _EXT4-RP-D
VARIABLE _EXT4-RP-VN

: _EXT4-PUBLISH-ROOT  ( ctx vfs -- )
    _EXT4-RP-V ! _EXT4-RP-CTX !
    _EXT4-RP-V @ V.ROOT @ DUP _EXT4-RP-D ! D.VNODE @ _EXT4-RP-VN !
    VFS-T-DIR _EXT4-RP-VN @ VN.TYPE !
    _EXT4-RP-CTX @ _EXT4-C.R.SIZE + @ _EXT4-RP-VN @ VN.SIZE-LO !
    0 _EXT4-RP-VN @ VN.SIZE-HI !
    _EXT4-RP-CTX @ _EXT4-C.R.MODE + @ _EXT4-RP-VN @ VN.MODE !
    _EXT4-RP-CTX @ _EXT4-C.R.UID + @ _EXT4-RP-VN @ VN.UID !
    _EXT4-RP-CTX @ _EXT4-C.R.GID + @ _EXT4-RP-VN @ VN.GID !
    _EXT4-RP-CTX @ _EXT4-C.R.NLINK + @ _EXT4-RP-VN @ VN.NLINK !
    2 _EXT4-RP-VN @ VN.BID !
    2 _EXT4-RP-VN @ VN.BDATA !
    0 _EXT4-RP-VN @ VN.BDATA 8 + !
    _EXT4-RP-CTX @ _EXT4-C.R.ATIME + @ _EXT4-RP-VN @ VN.ATIME !
    _EXT4-RP-CTX @ _EXT4-C.R.ATIME-NS + @ _EXT4-RP-VN @ VN.ATIME-NS !
    _EXT4-RP-CTX @ _EXT4-C.R.MTIME + @ _EXT4-RP-VN @ VN.MTIME !
    _EXT4-RP-CTX @ _EXT4-C.R.MTIME-NS + @ _EXT4-RP-VN @ VN.MTIME-NS !
    _EXT4-RP-CTX @ _EXT4-C.R.CTIME + @ _EXT4-RP-VN @ VN.CTIME !
    _EXT4-RP-CTX @ _EXT4-C.R.CTIME-NS + @ _EXT4-RP-VN @ VN.CTIME-NS !
    _EXT4-RP-CTX @ _EXT4-C.R.BLOCKS + @ _EXT4-RP-VN @ VN.BLOCKS !
    _EXT4-RP-CTX @ _EXT4-C.R.GEN + @ _EXT4-RP-VN @ VN.GEN !
    0 _EXT4-RP-VN @ VN.RDEV ! ;

\ Decode the currently cached inode into the same staging cells used for
\ root publication.  The returned VFS type is not published until every
\ checksum, size, flag, and mapping check has succeeded.
VARIABLE _EXT4-MS-CTX
VARIABLE _EXT4-MS-IN
VARIABLE _EXT4-MS-TYPE
VARIABLE _EXT4-MS-MODE
VARIABLE _EXT4-MS-HI
VARIABLE _EXT4-MS-EXTRA
VARIABLE _EXT4-MS-BLOCKS
VARIABLE _EXT4-MS-FLAGS

: _EXT4-STAGE-CURRENT-INODE  ( ctx -- type ior )
    DUP _EXT4-MS-CTX ! _EXT4-C.INODE + _EXT4-MS-IN !
    _EXT4-MS-IN @ _EXT4-I.MODE + W@ DUP _EXT4-MS-MODE !
    0xF000 AND CASE
        0x8000 OF VFS-T-FILE    ENDOF
        0x4000 OF VFS-T-DIR     ENDOF
        0xA000 OF VFS-T-SYMLINK ENDOF
        0x1000 OF VFS-T-SPECIAL ENDOF
        0x2000 OF VFS-T-SPECIAL ENDOF
        0x6000 OF VFS-T-SPECIAL ENDOF
        0xC000 OF VFS-T-SPECIAL ENDOF
        DROP 0 EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
    ENDCASE DUP _EXT4-MS-TYPE ! DROP
    _EXT4-MS-MODE @ _EXT4-MS-CTX @ _EXT4-C.R.MODE + !
    _EXT4-MS-IN @ _EXT4-I.LINKS + W@ DUP 0= IF
        DROP 0 EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
    THEN
    _EXT4-MS-CTX @ _EXT4-C.R.NLINK + !
    _EXT4-MS-IN @ _EXT4-I.SIZE-HI + L@ DUP _EXT4-MS-HI !
    0x80000000 AND IF 0 EXT4-D-BOUNDS _EXT4-CORRUPT EXIT THEN
    _EXT4-MS-HI @ 32 LSHIFT _EXT4-MS-IN @ _EXT4-I.SIZE-LO + L@ OR
    _EXT4-MS-CTX @ _EXT4-C.R.SIZE + !
    _EXT4-MS-IN @ _EXT4-I.UID-HI + W@ 16 LSHIFT
    _EXT4-MS-IN @ _EXT4-I.UID-LO + W@ OR
    _EXT4-MS-CTX @ _EXT4-C.R.UID + !
    _EXT4-MS-IN @ _EXT4-I.GID-HI + W@ 16 LSHIFT
    _EXT4-MS-IN @ _EXT4-I.GID-LO + W@ OR
    _EXT4-MS-CTX @ _EXT4-C.R.GID + !
    _EXT4-MS-IN @ _EXT4-MS-CTX @ _EXT4-DECODE-I-BLOCKS
    ?DUP IF NIP 0 SWAP EXIT THEN DUP _EXT4-MS-BLOCKS !
    _EXT4-MS-CTX @ _EXT4-C.R.BLOCKS + !
    _EXT4-MS-IN @ _EXT4-I.GENERATION + L@
    _EXT4-MS-CTX @ _EXT4-C.R.GEN + !
    _EXT4-MS-IN @ _EXT4-I.ATIME + _EXT4-S32@
    _EXT4-MS-CTX @ _EXT4-C.R.ATIME + !
    _EXT4-MS-IN @ _EXT4-I.MTIME + _EXT4-S32@
    _EXT4-MS-CTX @ _EXT4-C.R.MTIME + !
    _EXT4-MS-IN @ _EXT4-I.CTIME + _EXT4-S32@
    _EXT4-MS-CTX @ _EXT4-C.R.CTIME + !
    0 _EXT4-MS-CTX @ _EXT4-C.R.ATIME-NS + !
    0 _EXT4-MS-CTX @ _EXT4-C.R.MTIME-NS + !
    0 _EXT4-MS-CTX @ _EXT4-C.R.CTIME-NS + !
    _EXT4-MS-CTX @ _EXT4-C.ISIZE + @ 128 > IF
        _EXT4-MS-IN @ _EXT4-I.EXTRA-SIZE + W@ 16 < IF
            0 EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
        THEN
        _EXT4-MS-IN @ _EXT4-I.ATIME-EXTRA + L@ DUP _EXT4-MS-EXTRA !
        2 RSHIFT DUP 1000000000 U< 0= IF
            DROP 0 EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
        THEN _EXT4-MS-CTX @ _EXT4-C.R.ATIME-NS + !
        _EXT4-MS-EXTRA @ 3 AND 32 LSHIFT
        _EXT4-MS-CTX @ _EXT4-C.R.ATIME + +!
        _EXT4-MS-IN @ _EXT4-I.MTIME-EXTRA + L@ DUP _EXT4-MS-EXTRA !
        2 RSHIFT DUP 1000000000 U< 0= IF
            DROP 0 EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
        THEN _EXT4-MS-CTX @ _EXT4-C.R.MTIME-NS + !
        _EXT4-MS-EXTRA @ 3 AND 32 LSHIFT
        _EXT4-MS-CTX @ _EXT4-C.R.MTIME + +!
        _EXT4-MS-IN @ _EXT4-I.CTIME-EXTRA + L@ DUP _EXT4-MS-EXTRA !
        2 RSHIFT DUP 1000000000 U< 0= IF
            DROP 0 EXT4-D-ROOT-INODE _EXT4-CORRUPT EXIT
        THEN _EXT4-MS-CTX @ _EXT4-C.R.CTIME-NS + !
        _EXT4-MS-EXTRA @ 3 AND 32 LSHIFT
        _EXT4-MS-CTX @ _EXT4-C.R.CTIME + +!
    THEN
    _EXT4-MS-IN @ _EXT4-I.FLAGS + L@ DUP _EXT4-MS-FLAGS !
    0x50300800 AND IF 0 EXT4-D-FEATURE _EXT4-UNSUPPORTED EXIT THEN
    _EXT4-MS-FLAGS @ _EXT4-INDEX-FL AND IF
        0 EXT4-D-FEATURE _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-MS-TYPE @ VFS-T-SPECIAL = IF
        0 EXT4-D-DATA-MAP _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-MS-TYPE @ VFS-T-SYMLINK =
    _EXT4-MS-CTX @ _EXT4-C.R.SIZE + @ 60 <= AND
    _EXT4-MS-BLOCKS @ 0= AND IF
        _EXT4-MS-TYPE @ 0 EXIT
    THEN
    _EXT4-MS-FLAGS @ _EXT4-EXTENTS-FL AND 0= IF
        0 EXT4-D-DATA-MAP _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-MS-CTX @ _EXT4-VALIDATE-INLINE-EXTENTS
    DUP IF 0 SWAP EXIT THEN DROP
    _EXT4-MS-TYPE @ 0 ;

VARIABLE _EXT4-MP-CTX
VARIABLE _EXT4-MP-D
VARIABLE _EXT4-MP-TYPE
VARIABLE _EXT4-MP-VN

: _EXT4-PUBLISH-STAGED  ( ctx dentry type -- )
    _EXT4-MP-TYPE ! _EXT4-MP-D ! _EXT4-MP-CTX !
    _EXT4-MP-D @ D.VNODE @ _EXT4-MP-VN !
    _EXT4-MP-TYPE @ _EXT4-MP-VN @ VN.TYPE !
    _EXT4-MP-CTX @ _EXT4-C.R.SIZE + @ _EXT4-MP-VN @ VN.SIZE-LO !
    0 _EXT4-MP-VN @ VN.SIZE-HI !
    _EXT4-MP-CTX @ _EXT4-C.R.MODE + @ _EXT4-MP-VN @ VN.MODE !
    _EXT4-MP-CTX @ _EXT4-C.R.UID + @ _EXT4-MP-VN @ VN.UID !
    _EXT4-MP-CTX @ _EXT4-C.R.GID + @ _EXT4-MP-VN @ VN.GID !
    _EXT4-MP-CTX @ _EXT4-C.R.NLINK + @ _EXT4-MP-VN @ VN.NLINK !
    _EXT4-MP-D @ IN.BID @ _EXT4-MP-VN @ VN.BDATA !
    0 _EXT4-MP-VN @ VN.BDATA 8 + !
    _EXT4-MP-CTX @ _EXT4-C.R.ATIME + @ _EXT4-MP-VN @ VN.ATIME !
    _EXT4-MP-CTX @ _EXT4-C.R.ATIME-NS + @ _EXT4-MP-VN @ VN.ATIME-NS !
    _EXT4-MP-CTX @ _EXT4-C.R.MTIME + @ _EXT4-MP-VN @ VN.MTIME !
    _EXT4-MP-CTX @ _EXT4-C.R.MTIME-NS + @ _EXT4-MP-VN @ VN.MTIME-NS !
    _EXT4-MP-CTX @ _EXT4-C.R.CTIME + @ _EXT4-MP-VN @ VN.CTIME !
    _EXT4-MP-CTX @ _EXT4-C.R.CTIME-NS + @ _EXT4-MP-VN @ VN.CTIME-NS !
    _EXT4-MP-CTX @ _EXT4-C.R.BLOCKS + @ _EXT4-MP-VN @ VN.BLOCKS !
    _EXT4-MP-CTX @ _EXT4-C.R.GEN + @ _EXT4-MP-VN @ VN.GEN !
    0 _EXT4-MP-VN @ VN.RDEV ! ;

\ =====================================================================
\  Checksummed linear directories and cache population
\ =====================================================================

VARIABLE _EXT4-DV-INO
VARIABLE _EXT4-DV-GEN
VARIABLE _EXT4-DV-CTX
VARIABLE _EXT4-DV-TAIL
VARIABLE _EXT4-DV-STORED

: _EXT4-VALIDATE-DIR-BLOCK  ( dir-inum generation ctx -- ior )
    _EXT4-DV-CTX ! _EXT4-DV-GEN ! _EXT4-DV-INO !
    _EXT4-DV-CTX @ _EXT4-C.DIR-BLOCK +
    _EXT4-DV-CTX @ _EXT4-C.BSIZE + @ 12 - + DUP _EXT4-DV-TAIL !
    DUP L@ 0<>
    OVER 4 + W@ 12 <> OR
    OVER 6 + C@ 0<> OR
    OVER 7 + C@ 0xDE <> OR IF
        DROP EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
    THEN
    8 + L@ _EXT4-DV-STORED !
    _EXT4-DV-INO @ _EXT4-DV-CTX @ _EXT4-C.TMP + L!
    _EXT4-DV-GEN @ _EXT4-DV-CTX @ _EXT4-C.TMP 4 + + L!
    _EXT4-DV-CTX @ _EXT4-C.SEED + @ _EXT4-CRC-START
    _EXT4-DV-CTX @ _EXT4-C.TMP + 8 _EXT4-CRC-ADD
    _EXT4-DV-CTX @ _EXT4-C.DIR-BLOCK +
    _EXT4-DV-CTX @ _EXT4-C.BSIZE + @ 12 - _EXT4-CRC-ADD
    _EXT4-CRC@ _EXT4-DV-STORED @ <> IF
        EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
    THEN
    0 ;

VARIABLE _EXT4-DS-PARENT
VARIABLE _EXT4-DS-V
VARIABLE _EXT4-DS-CTX
VARIABLE _EXT4-DS-DIRINO
VARIABLE _EXT4-DS-PARINO
VARIABLE _EXT4-DS-GEN
VARIABLE _EXT4-DS-OFF
VARIABLE _EXT4-DS-LIMIT
VARIABLE _EXT4-DS-DE
VARIABLE _EXT4-DS-REC
VARIABLE _EXT4-DS-NLEN
VARIABLE _EXT4-DS-CINO
VARIABLE _EXT4-DS-DTYPE
VARIABLE _EXT4-DS-TYPE
VARIABLE _EXT4-DS-DENTRY
VARIABLE _EXT4-DS-IOR
VARIABLE _EXT4-DS-DOT
VARIABLE _EXT4-DS-DOTDOT

: _EXT4-DIRENT>TYPE  ( dtype -- type supported? )
    CASE
        0 OF 0 TRUE          ENDOF
        1 OF VFS-T-FILE TRUE ENDOF
        2 OF VFS-T-DIR TRUE  ENDOF
        3 OF VFS-T-SPECIAL TRUE ENDOF
        4 OF VFS-T-SPECIAL TRUE ENDOF
        5 OF VFS-T-SPECIAL TRUE ENDOF
        6 OF VFS-T-SPECIAL TRUE ENDOF
        7 OF VFS-T-SYMLINK TRUE ENDOF
        0 FALSE ROT
    ENDCASE ;

: _EXT4-DIRENT-NAME-VALID?  ( addr len -- flag )
    0 ?DO
        DUP I + C@ DUP 0= SWAP [CHAR] / = OR IF
            DROP FALSE UNLOOP EXIT
        THEN
    LOOP DROP TRUE ;

: _EXT4-SCAN-DIR-BLOCK  ( parent vfs ctx -- ior )
    _EXT4-DS-CTX ! _EXT4-DS-V ! _EXT4-DS-PARENT !
    _EXT4-DS-PARENT @ IN.BID @ _EXT4-DS-DIRINO !
    _EXT4-DS-PARENT @ IN.PARENT @ ?DUP IF IN.BID @ ELSE
        _EXT4-DS-DIRINO @
    THEN _EXT4-DS-PARINO !
    _EXT4-DS-PARENT @ D.VNODE @ VN.GEN @ _EXT4-DS-GEN !
    _EXT4-DS-DIRINO @ _EXT4-DS-GEN @ _EXT4-DS-CTX @
    _EXT4-VALIDATE-DIR-BLOCK ?DUP IF EXIT THEN
    0 _EXT4-DS-OFF !
    _EXT4-DS-CTX @ _EXT4-C.BSIZE + @ 12 - _EXT4-DS-LIMIT !
    BEGIN _EXT4-DS-OFF @ _EXT4-DS-LIMIT @ < WHILE
        _EXT4-DS-CTX @ _EXT4-C.DIR-BLOCK + _EXT4-DS-OFF @ +
        _EXT4-DS-DE !
        _EXT4-DS-DE @ 4 + W@ _EXT4-DS-REC !
        _EXT4-DS-REC @ 8 < _EXT4-DS-REC @ 3 AND 0<> OR IF
            EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
        THEN
        _EXT4-DS-OFF @ _EXT4-DS-REC @ + _EXT4-DS-LIMIT @ > IF
            EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
        THEN
        _EXT4-DS-DE @ 6 + C@ DUP _EXT4-DS-NLEN !
        _EXT4-DS-REC @ 8 - U> IF EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT THEN
        _EXT4-DS-DE @ L@ DUP _EXT4-DS-CINO ! IF
            _EXT4-DS-CINO @ _EXT4-DS-CTX @ _EXT4-C.INODES + @ > IF
                EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
            THEN
            _EXT4-DS-DE @ 8 + _EXT4-DS-NLEN @
            _EXT4-DIRENT-NAME-VALID? 0= IF
                EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
            THEN
            _EXT4-DS-NLEN @ 1 =
            _EXT4-DS-DE @ 8 + C@ [CHAR] . = AND IF
                _EXT4-DS-CINO @ _EXT4-DS-DIRINO @ <> IF
                    EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
                THEN
                _EXT4-DS-DOT @ IF
                    EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
                THEN
                -1 _EXT4-DS-DOT !
            ELSE
                _EXT4-DS-NLEN @ 2 =
                _EXT4-DS-DE @ 8 + C@ [CHAR] . = AND
                _EXT4-DS-DE @ 9 + C@ [CHAR] . = AND IF
                    _EXT4-DS-CINO @ _EXT4-DS-PARINO @ <> IF
                        EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
                    THEN
                    _EXT4-DS-DOTDOT @ IF
                        EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
                    THEN
                    -1 _EXT4-DS-DOTDOT !
                ELSE
                    _EXT4-DS-NLEN @ 0= IF
                        EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
                    THEN
                    _EXT4-DS-DE @ 7 + C@ DUP _EXT4-DS-DTYPE !
                    _EXT4-DIRENT>TYPE 0= IF
                        DROP EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
                    THEN _EXT4-DS-TYPE !
                    _EXT4-DS-CINO @ _EXT4-DS-CTX @ _EXT4-LOAD-INODE
                    ?DUP IF EXIT THEN
                    _EXT4-DS-CTX @ _EXT4-STAGE-CURRENT-INODE
                    _EXT4-DS-IOR ! _EXT4-DS-TYPE !
                    _EXT4-DS-IOR @ ?DUP IF EXIT THEN
                    _EXT4-DS-DTYPE @ IF
                        _EXT4-DS-TYPE @
                        _EXT4-DS-DTYPE @ _EXT4-DIRENT>TYPE DROP <> IF
                            EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
                        THEN
                    THEN
                    _EXT4-DS-DE @ 8 + _EXT4-DS-NLEN @
                    _EXT4-DS-TYPE @ _EXT4-DS-CINO @
                    _EXT4-DS-CTX @ _EXT4-C.R.GEN + @
                    _EXT4-DS-PARENT @ _EXT4-DS-V @ VFS-CACHE-DENTRY
                    _EXT4-DS-IOR ! _EXT4-DS-DENTRY !
                    _EXT4-DS-IOR @ ?DUP IF EXIT THEN
                    _EXT4-DS-CTX @ _EXT4-DS-DENTRY @ _EXT4-DS-TYPE @
                    _EXT4-PUBLISH-STAGED
                THEN
            THEN
        THEN
        _EXT4-DS-REC @ _EXT4-DS-OFF +!
    REPEAT
    _EXT4-DS-OFF @ _EXT4-DS-LIMIT @ <> IF
        EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
    THEN
    0 ;

VARIABLE _EXT4-RD-PARENT
VARIABLE _EXT4-RD-V
VARIABLE _EXT4-RD-CTX
VARIABLE _EXT4-RD-SIZE
VARIABLE _EXT4-RD-BLOCKS
VARIABLE _EXT4-RD-PHYS
VARIABLE _EXT4-RD-PRESENT
VARIABLE _EXT4-RD-IOR
VARIABLE _EXT4-RD-OLD-CHILD
VARIABLE _EXT4-RD-OLD-COUNT
VARIABLE _EXT4-RD-OLD-STR

: _EXT4-RD-ROLLBACK  ( -- )
    BEGIN
        _EXT4-RD-PARENT @ IN.CHILD @ DUP _EXT4-RD-OLD-CHILD @ <>
    WHILE
        DUP _EXT4-RD-PARENT @ _VFS-REMOVE-CHILD
        FALSE _EXT4-RD-V @ _VFS-DENTRY-RELEASE
    REPEAT DROP
    _EXT4-RD-OLD-COUNT @ _EXT4-RD-V @ V.ICOUNT !
    _EXT4-RD-OLD-STR @ _EXT4-RD-V @ V.STR-PTR ! ;

: _EXT4-READDIR-WORK  ( -- ior )
    _EXT4-RD-PARENT @ IN.BID @ _EXT4-RD-CTX @ _EXT4-LOAD-INODE
    ?DUP IF EXIT THEN
    _EXT4-RD-CTX @ _EXT4-STAGE-CURRENT-INODE
    _EXT4-RD-IOR ! DUP VFS-T-DIR <> IF
        DROP _EXT4-RD-IOR @ ?DUP IF EXIT THEN VFS-E-NOTDIR EXIT
    THEN DROP
    _EXT4-RD-IOR @ ?DUP IF EXIT THEN
    _EXT4-RD-CTX @ _EXT4-C.R.SIZE + @ DUP _EXT4-RD-SIZE !
    DUP 0= IF DROP EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT THEN
    DUP 0x7FFFFFFF U> IF
        DROP EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
    THEN
    DUP _EXT4-RD-CTX @ _EXT4-C.BSIZE + @ MOD IF
        DROP EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
    THEN
    _EXT4-RD-CTX @ _EXT4-C.BSIZE + @ 1- +
    _EXT4-RD-CTX @ _EXT4-C.BSIZE + @ / DUP _EXT4-RD-BLOCKS !
    0 _EXT4-DS-DOT ! 0 _EXT4-DS-DOTDOT !
    0 DO
        _EXT4-RD-PARENT @ IN.BID @ _EXT4-RD-CTX @ _EXT4-LOAD-INODE
        ?DUP IF UNLOOP EXIT THEN
        I _EXT4-RD-CTX @ _EXT4-MAP-INLINE
        _EXT4-RD-IOR ! _EXT4-RD-PRESENT ! _EXT4-RD-PHYS !
        _EXT4-RD-IOR @ ?DUP IF UNLOOP EXIT THEN
        _EXT4-RD-PRESENT @ 0= IF
            EXT4-D-DIRECTORY _EXT4-CORRUPT UNLOOP EXIT
        THEN
        _EXT4-RD-PHYS @ _EXT4-RD-CTX @ _EXT4-READ-BLOCK ?DUP IF
            UNLOOP EXIT
        THEN
        _EXT4-RD-CTX @ _EXT4-C.BLOCK +
        _EXT4-RD-CTX @ _EXT4-C.DIR-BLOCK +
        _EXT4-RD-CTX @ _EXT4-C.BSIZE + @ CMOVE
        _EXT4-RD-PARENT @ _EXT4-RD-V @ _EXT4-RD-CTX @
        _EXT4-SCAN-DIR-BLOCK ?DUP IF UNLOOP EXIT THEN
    LOOP
    _EXT4-DS-DOT @ 0= _EXT4-DS-DOTDOT @ 0= OR IF
        EXT4-D-DIRECTORY _EXT4-CORRUPT EXIT
    THEN
    0 ;

: _EXT4-READDIR  ( directory vfs -- ior )
    DUP _EXT4-READY? 0= IF 2DROP VFS-E-BUSY EXIT THEN
    _EXT4-RD-V ! _EXT4-RD-PARENT !
    _EXT4-RD-V @ _EXT4-CTX _EXT4-RD-CTX !
    _EXT4-RD-PARENT @ IN.CHILD @ _EXT4-RD-OLD-CHILD !
    _EXT4-RD-V @ V.ICOUNT @ _EXT4-RD-OLD-COUNT !
    _EXT4-RD-V @ V.STR-PTR @ _EXT4-RD-OLD-STR !
    _EXT4-RD-V @ V.VOLUME @ _EXT4-IO-VOL !
    _EXT4-RD-V @ _EXT4-IO-VFS !
    _EXT4-READDIR-WORK DUP IF _EXT4-RD-ROLLBACK THEN ;

\ =====================================================================
\  Read-only file and symlink data operations
\ =====================================================================

: _EXT4-PARTIAL-IOR  ( actual ior -- actual ior )
    DUP IF OVER 0> IF VFS-IOR-F-PARTIAL 24 LSHIFT OR THEN THEN ;

VARIABLE _EXT4-DR-BUF
VARIABLE _EXT4-DR-LEN
VARIABLE _EXT4-DR-OFF
VARIABLE _EXT4-DR-IN
VARIABLE _EXT4-DR-V
VARIABLE _EXT4-DR-CTX
VARIABLE _EXT4-DR-TYPE
VARIABLE _EXT4-DR-IOR
VARIABLE _EXT4-DR-REM
VARIABLE _EXT4-DR-ACT
VARIABLE _EXT4-DR-LBLOCK
VARIABLE _EXT4-DR-BOFF
VARIABLE _EXT4-DR-CHUNK
VARIABLE _EXT4-DR-PHYS
VARIABLE _EXT4-DR-PRESENT

: _EXT4-READ-DATA-WORK  ( -- ior )
    _EXT4-DR-IN @ IN.BID @ _EXT4-DR-CTX @ _EXT4-LOAD-INODE
    ?DUP IF EXIT THEN
    _EXT4-DR-CTX @ _EXT4-STAGE-CURRENT-INODE
    _EXT4-DR-IOR ! _EXT4-DR-TYPE !
    _EXT4-DR-IOR @ ?DUP IF EXIT THEN
    _EXT4-DR-TYPE @ VFS-T-DIR = IF VFS-E-ISDIR EXIT THEN
    _EXT4-DR-TYPE @ VFS-T-SPECIAL = IF VFS-E-UNSUPPORTED EXIT THEN
    _EXT4-DR-OFF @ _EXT4-DR-CTX @ _EXT4-C.R.SIZE + @ >= IF 0 EXIT THEN
    _EXT4-DR-CTX @ _EXT4-C.R.SIZE + @ _EXT4-DR-OFF @ -
    _EXT4-DR-LEN @ MIN _EXT4-DR-REM !
    _EXT4-DR-TYPE @ VFS-T-SYMLINK =
    _EXT4-DR-CTX @ _EXT4-C.R.SIZE + @ 60 <= AND
    _EXT4-DR-CTX @ _EXT4-C.R.BLOCKS + @ 0= AND IF
        _EXT4-DR-CTX @ _EXT4-C.INODE + _EXT4-I.BLOCK +
        _EXT4-DR-OFF @ + _EXT4-DR-BUF @ _EXT4-DR-REM @ CMOVE
        _EXT4-DR-REM @ _EXT4-DR-ACT +!
        0 EXIT
    THEN
    BEGIN _EXT4-DR-REM @ 0> WHILE
        _EXT4-DR-OFF @ _EXT4-DR-CTX @ _EXT4-C.BSIZE + @ /MOD
        _EXT4-DR-LBLOCK ! _EXT4-DR-BOFF !
        _EXT4-DR-CTX @ _EXT4-C.BSIZE + @ _EXT4-DR-BOFF @ -
        _EXT4-DR-REM @ MIN _EXT4-DR-CHUNK !
        _EXT4-DR-LBLOCK @ _EXT4-DR-CTX @ _EXT4-MAP-INLINE
        _EXT4-DR-IOR ! _EXT4-DR-PRESENT ! _EXT4-DR-PHYS !
        _EXT4-DR-IOR @ ?DUP IF EXIT THEN
        _EXT4-DR-PRESENT @ IF
            _EXT4-DR-PHYS @ _EXT4-DR-CTX @ _EXT4-READ-BLOCK
            ?DUP IF EXIT THEN
            _EXT4-DR-CTX @ _EXT4-C.BLOCK + _EXT4-DR-BOFF @ +
            _EXT4-DR-BUF @ _EXT4-DR-CHUNK @ CMOVE
        ELSE
            _EXT4-DR-BUF @ _EXT4-DR-CHUNK @ 0 FILL
        THEN
        _EXT4-DR-CHUNK @ DUP _EXT4-DR-ACT +!
        DUP _EXT4-DR-BUF +!
        DUP _EXT4-DR-OFF +!
        NEGATE _EXT4-DR-REM +!
    REPEAT
    0 ;

: _EXT4-READ  ( buffer len offset dentry vfs -- actual ior )
    DUP _EXT4-READY? 0= IF 2DROP 2DROP DROP 0 VFS-E-BUSY EXIT THEN
    _EXT4-DR-V ! _EXT4-DR-IN ! _EXT4-DR-OFF !
    _EXT4-DR-LEN ! _EXT4-DR-BUF !
    _EXT4-DR-OFF @ 0< _EXT4-DR-LEN @ 0< OR IF 0 VFS-E-INVALID EXIT THEN
    _EXT4-DR-V @ _EXT4-CTX _EXT4-DR-CTX !
    _EXT4-DR-V @ V.VOLUME @ _EXT4-IO-VOL !
    _EXT4-DR-V @ _EXT4-IO-VFS !
    0 _EXT4-DR-ACT !
    _EXT4-READ-DATA-WORK _EXT4-DR-IOR !
    _EXT4-DR-ACT @ _EXT4-DR-IOR @ _EXT4-PARTIAL-IOR ;

: _EXT4-OPEN  ( dentry vfs -- cookie ior )
    DUP _EXT4-READY? 0= IF 2DROP 0 VFS-E-BUSY EXIT THEN
    DROP DUP IN.TYPE @ VFS-T-SPECIAL = IF DROP 0 VFS-E-UNSUPPORTED EXIT THEN
    DUP D.VNODE @ VN.GEN @ 32 LSHIFT SWAP IN.BID @ OR 0 ;

: _EXT4-RELEASE  ( cookie dentry vfs -- ior )  DROP 2DROP 0 ;

VARIABLE _EXT4-RL-BUF
VARIABLE _EXT4-RL-CAP
VARIABLE _EXT4-RL-IN
VARIABLE _EXT4-RL-V

: _EXT4-READLINK  ( buffer capacity dentry vfs -- actual ior )
    _EXT4-RL-V ! _EXT4-RL-IN ! _EXT4-RL-CAP ! _EXT4-RL-BUF !
    _EXT4-RL-CAP @ 0= IF
        _EXT4-RL-IN @ IN.SIZE-LO @ 0 EXIT
    THEN
    _EXT4-RL-BUF @ _EXT4-RL-CAP @ 0
    _EXT4-RL-IN @ _EXT4-RL-V @ _EXT4-READ ;

: _EXT4-SYNCFS  ( vfs -- ior )  DROP 0 ;
: _EXT4-FSYNC   ( dentry vfs -- ior )  2DROP 0 ;

\ =====================================================================
\  In-inode and external-block user xattrs
\ =====================================================================

0xEA020000 CONSTANT _EXT4-XATTR-MAGIC
0x76 CONSTANT _EXT4-I.FILE-ACL-HI

VARIABLE _EXT4-XB-CTX
VARIABLE _EXT4-XB-BLOCK
VARIABLE _EXT4-XB-BUF
VARIABLE _EXT4-XB-STORED

: _EXT4-LOAD-XATTR-BLOCK  ( physical-block ctx -- ior )
    _EXT4-XB-CTX ! DUP _EXT4-XB-BLOCK !
    _EXT4-XB-CTX @ _EXT4-READ-BLOCK ?DUP IF EXIT THEN
    _EXT4-XB-CTX @ _EXT4-C.BLOCK + DUP _EXT4-XB-BUF !
    DUP L@ _EXT4-XATTR-MAGIC <>
    OVER 4 + L@ 0= OR
    OVER 8 + L@ 1 <> OR
    OVER 0x14 + L@ 0<> OR
    OVER 0x18 + L@ 0<> OR
    OVER 0x1C + L@ 0<> OR IF
        DROP EXT4-D-XATTR _EXT4-CORRUPT EXIT
    THEN
    DUP 0x10 + L@ _EXT4-XB-STORED !
    0 OVER 0x10 + L!
    _EXT4-XB-BLOCK @ _EXT4-XB-CTX @ _EXT4-C.TMP + L!
    0 _EXT4-XB-CTX @ _EXT4-C.TMP 4 + + L!
    _EXT4-XB-CTX @ _EXT4-C.SEED + @ _EXT4-CRC-START
    _EXT4-XB-CTX @ _EXT4-C.TMP + 8 _EXT4-CRC-ADD
    DUP _EXT4-XB-CTX @ _EXT4-C.BSIZE + @ _EXT4-CRC-ADD
    _EXT4-XB-STORED @ SWAP 0x10 + L!
    _EXT4-CRC@ _EXT4-XB-STORED @ <> IF
        EXT4-D-XATTR _EXT4-CORRUPT EXIT
    THEN
    0 ;

1 CONSTANT _EXT4-XOP-LIST
2 CONSTANT _EXT4-XOP-GET

VARIABLE _EXT4-XA-OP
VARIABLE _EXT4-XA-CTX
VARIABLE _EXT4-XA-ENTRY
VARIABLE _EXT4-XA-LIMIT
VARIABLE _EXT4-XA-VBASE
VARIABLE _EXT4-XA-VLIMIT
VARIABLE _EXT4-XA-NLEN
VARIABLE _EXT4-XA-ESIZE
VARIABLE _EXT4-XA-VOFF
VARIABLE _EXT4-XA-VSIZE
VARIABLE _EXT4-XA-TOTAL
VARIABLE _EXT4-XA-OUT
VARIABLE _EXT4-XA-EMIT
VARIABLE _EXT4-XA-FOUND
VARIABLE _EXT4-XA-REQ-A
VARIABLE _EXT4-XA-REQ-U
VARIABLE _EXT4-XA-CAP
VARIABLE _EXT4-XA-IOR

: _EXT4-XA-NAME-MATCH?  ( entry -- flag )
    _EXT4-XA-REQ-U @ _EXT4-XA-NLEN @ 5 + <> IF DROP FALSE EXIT THEN
    _EXT4-XA-REQ-A @ S" user." DROP 5 _EXT4-BYTES=? 0= IF
        DROP FALSE EXIT
    THEN
    16 + _EXT4-XA-REQ-A @ 5 + _EXT4-XA-NLEN @ _EXT4-BYTES=? ;

: _EXT4-XA-EMIT-NAME  ( entry -- )
    S" user." DROP _EXT4-XA-OUT @ 5 CMOVE
    16 + _EXT4-XA-OUT @ 5 + _EXT4-XA-NLEN @ CMOVE
    0 _EXT4-XA-OUT @ 5 _EXT4-XA-NLEN @ + + C!
    6 _EXT4-XA-NLEN @ + _EXT4-XA-OUT +! ;

\ The entry walker is split from the area setup so both LIST passes and GET
\ use one exact structural parser.  A zero u32 terminates the packed entries.
: _EXT4-XA-WALK  ( -- ior )
    BEGIN
        _EXT4-XA-ENTRY @ 4 + _EXT4-XA-LIMIT @ > IF
            EXT4-D-XATTR _EXT4-CORRUPT EXIT
        THEN
        _EXT4-XA-ENTRY @ L@ 0= IF 0 EXIT THEN
        _EXT4-XA-ENTRY @ 16 + _EXT4-XA-LIMIT @ > IF
            EXT4-D-XATTR _EXT4-CORRUPT EXIT
        THEN
        _EXT4-XA-ENTRY @ C@ DUP _EXT4-XA-NLEN ! 0= IF
            EXT4-D-XATTR _EXT4-CORRUPT EXIT
        THEN
        _EXT4-XA-ENTRY @ 1+ C@ 1 <> IF
            EXT4-D-XATTR _EXT4-UNSUPPORTED EXIT
        THEN
        _EXT4-XA-NLEN @ 16 + 3 + 3 INVERT AND DUP _EXT4-XA-ESIZE !
        _EXT4-XA-ENTRY @ + _EXT4-XA-LIMIT @ > IF
            EXT4-D-XATTR _EXT4-CORRUPT EXIT
        THEN
        _EXT4-XA-ENTRY @ 4 + L@ IF
            EXT4-D-XATTR _EXT4-UNSUPPORTED EXIT
        THEN
        _EXT4-XA-ENTRY @ 2 + W@ _EXT4-XA-VOFF !
        _EXT4-XA-ENTRY @ 8 + L@ _EXT4-XA-VSIZE !
        _EXT4-XA-VBASE @ _EXT4-XA-VOFF @ +
        DUP _EXT4-XA-VBASE @ U< IF
            DROP EXT4-D-XATTR _EXT4-CORRUPT EXIT
        THEN
        DUP _EXT4-XA-VLIMIT @ U> IF
            DROP EXT4-D-XATTR _EXT4-CORRUPT EXIT
        THEN
        _EXT4-XA-VSIZE @ + DUP _EXT4-XA-VLIMIT @ U> IF
            DROP EXT4-D-XATTR _EXT4-CORRUPT EXIT
        THEN DROP
        _EXT4-XA-OP @ _EXT4-XOP-LIST = IF
            6 _EXT4-XA-NLEN @ + _EXT4-XA-TOTAL +!
            _EXT4-XA-EMIT @ IF _EXT4-XA-ENTRY @ _EXT4-XA-EMIT-NAME THEN
        ELSE
            _EXT4-XA-ENTRY @ _EXT4-XA-NAME-MATCH? IF
                -1 _EXT4-XA-FOUND !
                _EXT4-XA-CAP @ 0= IF 0 EXIT THEN
                _EXT4-XA-VSIZE @ _EXT4-XA-CAP @ > IF
                    VFS-E-OVERFLOW EXIT
                THEN
                _EXT4-XA-VBASE @ _EXT4-XA-VOFF @ +
                _EXT4-XA-OUT @ _EXT4-XA-VSIZE @ CMOVE
                0 EXIT
            THEN
        THEN
        _EXT4-XA-ESIZE @ _EXT4-XA-ENTRY +!
    AGAIN ;

: _EXT4-XA-INLINE  ( ctx -- ior )
    DUP _EXT4-XA-CTX ! _EXT4-C.ISIZE + @ 128 <= IF 0 EXIT THEN
    _EXT4-XA-CTX @ _EXT4-C.INODE + _EXT4-I.EXTRA-SIZE + W@
    128 + _EXT4-XA-CTX @ _EXT4-C.INODE + +
    DUP 4 + _EXT4-XA-CTX @ _EXT4-C.INODE +
        _EXT4-XA-CTX @ _EXT4-C.ISIZE + @ + > IF
        DROP EXT4-D-XATTR _EXT4-CORRUPT EXIT
    THEN
    DUP L@ 0= IF DROP 0 EXIT THEN
    DUP L@ _EXT4-XATTR-MAGIC <> IF
        DROP EXT4-D-XATTR _EXT4-CORRUPT EXIT
    THEN
    4 + DUP _EXT4-XA-ENTRY ! _EXT4-XA-VBASE !
    _EXT4-XA-CTX @ _EXT4-C.INODE +
    _EXT4-XA-CTX @ _EXT4-C.ISIZE + @ + DUP
    _EXT4-XA-LIMIT ! _EXT4-XA-VLIMIT !
    _EXT4-XA-WALK ;

: _EXT4-XA-EXTERNAL  ( ctx -- ior )
    DUP _EXT4-XA-CTX !
    _EXT4-C.INODE + DUP _EXT4-I.FILE-ACL-HI + W@ IF
        DROP EXT4-D-BOUNDS _EXT4-CORRUPT EXIT
    THEN
    _EXT4-I.FILE-ACL-LO + L@ DUP 0= IF DROP 0 EXIT THEN
    _EXT4-XA-CTX @ _EXT4-LOAD-XATTR-BLOCK ?DUP IF EXIT THEN
    _EXT4-XA-CTX @ _EXT4-C.BLOCK + DUP
    32 + _EXT4-XA-ENTRY !
    DUP _EXT4-XA-VBASE !
    _EXT4-XA-CTX @ _EXT4-C.BSIZE + @ + DUP
    _EXT4-XA-LIMIT ! _EXT4-XA-VLIMIT !
    _EXT4-XA-WALK ;

: _EXT4-XA-SCAN-BOTH  ( ctx -- ior )
    DUP _EXT4-XA-INLINE ?DUP IF NIP EXIT THEN
    _EXT4-XA-OP @ _EXT4-XOP-GET = _EXT4-XA-FOUND @ AND IF DROP 0 EXIT THEN
    _EXT4-XA-EXTERNAL ;

VARIABLE _EXT4-LX-BUF
VARIABLE _EXT4-LX-CAP
VARIABLE _EXT4-LX-IN
VARIABLE _EXT4-LX-V
VARIABLE _EXT4-LX-CTX

: _EXT4-LISTXATTR  ( buffer capacity dentry vfs -- actual ior )
    _EXT4-LX-V ! _EXT4-LX-IN ! _EXT4-LX-CAP ! _EXT4-LX-BUF !
    _EXT4-LX-V @ _EXT4-CTX _EXT4-LX-CTX !
    _EXT4-LX-V @ V.VOLUME @ _EXT4-IO-VOL !
    _EXT4-LX-V @ _EXT4-IO-VFS !
    _EXT4-LX-IN @ IN.BID @ _EXT4-LX-CTX @ _EXT4-LOAD-INODE
    ?DUP IF 0 SWAP EXIT THEN
    _EXT4-XOP-LIST _EXT4-XA-OP !
    0 _EXT4-XA-TOTAL ! 0 _EXT4-XA-EMIT !
    _EXT4-LX-CTX @ _EXT4-XA-SCAN-BOTH ?DUP IF 0 SWAP EXIT THEN
    _EXT4-LX-CAP @ 0= IF _EXT4-XA-TOTAL @ 0 EXIT THEN
    _EXT4-XA-TOTAL @ _EXT4-LX-CAP @ > IF 0 VFS-E-OVERFLOW EXIT THEN
    _EXT4-LX-BUF @ _EXT4-XA-OUT ! -1 _EXT4-XA-EMIT !
    0 _EXT4-XA-TOTAL !
    _EXT4-LX-CTX @ _EXT4-XA-SCAN-BOTH ?DUP IF 0 SWAP EXIT THEN
    _EXT4-XA-TOTAL @ 0 ;

VARIABLE _EXT4-GX-NA
VARIABLE _EXT4-GX-NU
VARIABLE _EXT4-GX-BUF
VARIABLE _EXT4-GX-CAP
VARIABLE _EXT4-GX-IN
VARIABLE _EXT4-GX-V
VARIABLE _EXT4-GX-CTX

: _EXT4-GETXATTR  ( name-a name-u buffer capacity dentry vfs -- actual ior )
    _EXT4-GX-V ! _EXT4-GX-IN ! _EXT4-GX-CAP ! _EXT4-GX-BUF !
    _EXT4-GX-NU ! _EXT4-GX-NA !
    _EXT4-GX-V @ _EXT4-CTX _EXT4-GX-CTX !
    _EXT4-GX-V @ V.VOLUME @ _EXT4-IO-VOL !
    _EXT4-GX-V @ _EXT4-IO-VFS !
    _EXT4-GX-IN @ IN.BID @ _EXT4-GX-CTX @ _EXT4-LOAD-INODE
    ?DUP IF 0 SWAP EXIT THEN
    _EXT4-XOP-GET _EXT4-XA-OP !
    _EXT4-GX-NA @ _EXT4-XA-REQ-A ! _EXT4-GX-NU @ _EXT4-XA-REQ-U !
    _EXT4-GX-BUF @ _EXT4-XA-OUT ! _EXT4-GX-CAP @ _EXT4-XA-CAP !
    0 _EXT4-XA-FOUND !
    _EXT4-GX-CTX @ _EXT4-XA-SCAN-BOTH ?DUP IF 0 SWAP EXIT THEN
    _EXT4-XA-FOUND @ 0= IF 0 VFS-E-NOENT EXIT THEN
    _EXT4-XA-VSIZE @ 0 ;

\ =====================================================================
\  Clean orphan-file validation
\ =====================================================================

VARIABLE _EXT4-OV-CTX
VARIABLE _EXT4-OV-INO
VARIABLE _EXT4-OV-IN
VARIABLE _EXT4-OV-GEN
VARIABLE _EXT4-OV-BLOCKS
VARIABLE _EXT4-OV-PHYS
VARIABLE _EXT4-OV-PRESENT
VARIABLE _EXT4-OV-IOR
VARIABLE _EXT4-OV-TAIL
VARIABLE _EXT4-OV-STORED

4096 CONSTANT _EXT4-MAX-ORPHAN-BLOCKS

: _EXT4-VALIDATE-ORPHAN-FILE  ( ctx -- ior )
    DUP _EXT4-OV-CTX ! _EXT4-C.ORPHAN-INO + @ DUP _EXT4-OV-INO !
    _EXT4-OV-CTX @ _EXT4-LOAD-INODE ?DUP IF EXIT THEN
    _EXT4-OV-CTX @ _EXT4-C.INODE + DUP _EXT4-OV-IN !
    _EXT4-I.MODE + W@ 0xF000 AND 0x8000 <> IF
        EXT4-D-ORPHAN-FILE _EXT4-CORRUPT EXIT
    THEN
    _EXT4-OV-IN @ _EXT4-I.SIZE-HI + L@ IF
        EXT4-D-ORPHAN-FILE _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-OV-IN @ _EXT4-I.SIZE-LO + L@ DUP 0= IF
        DROP EXT4-D-ORPHAN-FILE _EXT4-CORRUPT EXIT
    THEN
    DUP _EXT4-OV-CTX @ _EXT4-C.BSIZE + @ MOD IF
        DROP EXT4-D-ORPHAN-FILE _EXT4-CORRUPT EXIT
    THEN
    _EXT4-OV-CTX @ _EXT4-C.BSIZE + @ / DUP
    _EXT4-MAX-ORPHAN-BLOCKS U> IF
        DROP EXT4-D-ORPHAN-FILE _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-OV-BLOCKS !
    _EXT4-OV-IN @ _EXT4-I.GENERATION + L@ _EXT4-OV-GEN !
    _EXT4-OV-IN @ _EXT4-I.FLAGS + L@ _EXT4-EXTENTS-FL AND 0= IF
        EXT4-D-ORPHAN-FILE _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-OV-CTX @ _EXT4-VALIDATE-INLINE-EXTENTS ?DUP IF EXIT THEN
    _EXT4-OV-BLOCKS @ 0 ?DO
        I _EXT4-OV-CTX @ _EXT4-MAP-INLINE
        _EXT4-OV-IOR ! _EXT4-OV-PRESENT ! _EXT4-OV-PHYS !
        _EXT4-OV-IOR @ ?DUP IF UNLOOP EXIT THEN
        _EXT4-OV-PRESENT @ 0= IF
            EXT4-D-ORPHAN-FILE _EXT4-CORRUPT UNLOOP EXIT
        THEN
        _EXT4-OV-PHYS @ _EXT4-OV-CTX @ _EXT4-READ-BLOCK ?DUP IF
            UNLOOP EXIT
        THEN
        _EXT4-OV-CTX @ _EXT4-C.BLOCK +
        _EXT4-OV-CTX @ _EXT4-C.BSIZE + @ 8 - + DUP _EXT4-OV-TAIL !
        DUP L@ _EXT4-ORPHAN-MAGIC <> IF
            DROP EXT4-D-ORPHAN-FILE _EXT4-CORRUPT UNLOOP EXIT
        THEN
        4 + L@ _EXT4-OV-STORED !
        _EXT4-OV-INO @ _EXT4-OV-CTX @ _EXT4-C.TMP + L!
        _EXT4-OV-GEN @ _EXT4-OV-CTX @ _EXT4-C.TMP 4 + + L!
        _EXT4-OV-PHYS @ _EXT4-OV-CTX @ _EXT4-C.TMP 8 + + L!
        0 _EXT4-OV-CTX @ _EXT4-C.TMP 12 + + L!
        _EXT4-OV-CTX @ _EXT4-C.SEED + @ _EXT4-CRC-START
        _EXT4-OV-CTX @ _EXT4-C.TMP + 16 _EXT4-CRC-ADD
        _EXT4-OV-CTX @ _EXT4-C.BLOCK +
        _EXT4-OV-CTX @ _EXT4-C.BSIZE + @ 8 - _EXT4-CRC-ADD
        _EXT4-CRC@ _EXT4-OV-STORED @ <> IF
            EXT4-D-ORPHAN-FILE _EXT4-CORRUPT UNLOOP EXIT
        THEN
        _EXT4-OV-CTX @ _EXT4-C.BSIZE + @ 8 - 4 / 0 DO
            _EXT4-OV-CTX @ _EXT4-C.BLOCK + J 4 * + L@ IF
                EXT4-D-RECOVERY _EXT4-UNSUPPORTED UNLOOP UNLOOP EXIT
            THEN
        LOOP
    LOOP
    0 ;

\ =====================================================================
\  Clean internal JBD2 journal validation
\ =====================================================================

VARIABLE _EXT4-BE-A
: _EXT4-BE32@  ( addr -- u )
    _EXT4-BE-A !
    _EXT4-BE-A @ C@ 24 LSHIFT
    _EXT4-BE-A @ 1+ C@ 16 LSHIFT OR
    _EXT4-BE-A @ 2 + C@ 8 LSHIFT OR
    _EXT4-BE-A @ 3 + C@ OR ;

VARIABLE _EXT4-JV-CTX
VARIABLE _EXT4-JV-IN
VARIABLE _EXT4-JV-SIZE
VARIABLE _EXT4-JV-PHYS
VARIABLE _EXT4-JV-PRESENT
VARIABLE _EXT4-JV-IOR
VARIABLE _EXT4-JV-JSB

: _EXT4-VALIDATE-JOURNAL  ( ctx -- ior )
    DUP _EXT4-JV-CTX ! 8 SWAP _EXT4-LOAD-INODE ?DUP IF EXIT THEN
    _EXT4-JV-CTX @ _EXT4-C.INODE + DUP _EXT4-JV-IN !
    _EXT4-I.MODE + W@ 0xF000 AND 0x8000 <> IF
        EXT4-D-JOURNAL _EXT4-CORRUPT EXIT
    THEN
    _EXT4-JV-IN @ _EXT4-I.SIZE-HI + L@ 32 LSHIFT
    _EXT4-JV-IN @ _EXT4-I.SIZE-LO + L@ OR DUP _EXT4-JV-SIZE !
    4194304 <> IF EXT4-D-JOURNAL _EXT4-CORRUPT EXIT THEN
    _EXT4-JV-IN @ _EXT4-I.FLAGS + L@ _EXT4-EXTENTS-FL AND 0= IF
        EXT4-D-JOURNAL _EXT4-UNSUPPORTED EXIT
    THEN
    _EXT4-JV-CTX @ _EXT4-VALIDATE-INLINE-EXTENTS ?DUP IF EXIT THEN
    0 _EXT4-JV-CTX @ _EXT4-MAP-INLINE
    _EXT4-JV-IOR ! _EXT4-JV-PRESENT ! _EXT4-JV-PHYS !
    _EXT4-JV-IOR @ ?DUP IF EXIT THEN
    _EXT4-JV-PRESENT @ 0= IF EXT4-D-JOURNAL _EXT4-CORRUPT EXIT THEN
    _EXT4-JV-PHYS @ _EXT4-JV-CTX @ _EXT4-READ-BLOCK ?DUP IF EXIT THEN
    _EXT4-JV-CTX @ _EXT4-C.BLOCK + DUP _EXT4-JV-JSB !
    _EXT4-BE32@ _EXT4-JBD2-MAGIC =
    _EXT4-JV-JSB @ 4 + _EXT4-BE32@ _EXT4-JBD2-SUPER-V2 = AND
    _EXT4-JV-JSB @ 12 + _EXT4-BE32@
        _EXT4-JV-CTX @ _EXT4-C.BSIZE + @ = AND
    _EXT4-JV-JSB @ 16 + _EXT4-BE32@
        _EXT4-JV-SIZE @ _EXT4-JV-CTX @ _EXT4-C.BSIZE + @ / = AND
    _EXT4-JV-JSB @ 20 + _EXT4-BE32@ DUP 0>
    SWAP _EXT4-JV-JSB @ 16 + _EXT4-BE32@ < AND AND
    _EXT4-JV-JSB @ 28 + _EXT4-BE32@ 0= AND
    _EXT4-JV-JSB @ 32 + _EXT4-BE32@ 0= AND
    _EXT4-JV-JSB @ 48 +
        _EXT4-JV-CTX @ _EXT4-C.SB + _EXT4-SB.UUID +
        16 _EXT4-BYTES=? AND
    _EXT4-JV-JSB @ 64 + _EXT4-BE32@ 1 = AND
    _EXT4-JV-JSB @ 68 + _EXT4-BE32@ 0= AND 0= IF
        EXT4-D-JOURNAL _EXT4-CORRUPT EXIT
    THEN
    \ The first read-only landing admits only the clean mke2fs journal
    \ profile.  Other JBD2 feature states are format variants requiring
    \ replay/checksum support, not evidence of structural corruption.
    _EXT4-JV-JSB @ 36 + _EXT4-BE32@
    _EXT4-JV-JSB @ 40 + _EXT4-BE32@ OR
    _EXT4-JV-JSB @ 44 + _EXT4-BE32@ OR IF
        EXT4-D-JOURNAL _EXT4-UNSUPPORTED EXIT
    THEN
    \ With all feature masks clear, checksum_v1/v2/v3 and fast-commit
    \ metadata are absent.  Require their type, padding, count, and stored
    \ checksum fields to remain in that exact unchecksummed state.
    _EXT4-JV-JSB @ 0x50 + C@ 0<>
    _EXT4-JV-JSB @ 0x51 + C@ 0<> OR
    _EXT4-JV-JSB @ 0x52 + C@ 0<> OR
    _EXT4-JV-JSB @ 0x53 + C@ 0<> OR
    _EXT4-JV-JSB @ 0x54 + _EXT4-BE32@ 0<> OR
    _EXT4-JV-JSB @ 0xFC + _EXT4-BE32@ 0<> OR IF
        EXT4-D-JOURNAL _EXT4-CORRUPT EXIT
    THEN
    0 ;

\ =====================================================================
\  Mount, metadata callbacks, and read-only binding descriptor
\ =====================================================================

VARIABLE _EXT4-M-V
VARIABLE _EXT4-M-CTX
VARIABLE _EXT4-M-IOR

: _EXT4-MOUNT  ( vfs -- ior )
    DUP _EXT4-M-V !
    DUP _EXT4-ATTACHED? 0= IF DROP EXT4-D-ATTACHMENT _EXT4-CORRUPT EXIT THEN
    DROP
    _EXT4-M-V @ V.VOLUME @ DUP VOL.SECTOR-SIZE _EXT4-SECTOR <> IF
        DROP 0 0 VFS-IOR-D-VOLUME VFS-R-UNSUPPORTED VFS-IOR-MAKE EXIT
    THEN
    _EXT4-IO-VOL ! _EXT4-M-V @ _EXT4-IO-VFS !
    _EXT4-M-V @ V.BCTX @ ?DUP IF
        _EXT4-M-CTX !
    ELSE
        _EXT4-M-V @ V.ARENA @ _EXT4-CTX-SIZE ARENA-ALLOT?
        IF DROP VFS-E-NOMEM EXIT THEN
        DUP _EXT4-M-CTX ! _EXT4-M-V @ V.BCTX !
    THEN
    _EXT4-M-CTX @ _EXT4-CTX-SIZE 0 FILL
    _EXT4-M-CTX @ _EXT4-C.SB + 2 2 _EXT4-READ-SECTORS
    DUP IF EXIT THEN DROP
    _EXT4-M-CTX @ _EXT4-M-V @ _EXT4-VALIDATE-SUPER
    DUP IF EXIT THEN DROP
    _EXT4-M-CTX @ _EXT4-VALIDATE-GROUPS
    DUP IF EXIT THEN DROP
    _EXT4-M-CTX @ _EXT4-VALIDATE-BACKUPS
    DUP IF EXIT THEN DROP
    _EXT4-M-CTX @ _EXT4-VALIDATE-JOURNAL
    DUP IF EXIT THEN DROP
    _EXT4-M-CTX @ _EXT4-VALIDATE-ORPHAN-FILE
    DUP IF EXIT THEN DROP
    2 _EXT4-M-CTX @ _EXT4-LOAD-INODE
    DUP IF EXIT THEN DROP
    _EXT4-M-CTX @ _EXT4-STAGE-ROOT
    DUP IF EXIT THEN DROP
    _EXT4-M-V @ _EXT4-ATTACHED? 0= IF
        EXT4-D-ATTACHMENT _EXT4-CORRUPT EXIT
    THEN
    _EXT4-M-CTX @ _EXT4-M-V @ _EXT4-PUBLISH-ROOT
    -1 _EXT4-M-CTX @ _EXT4-C.READY + !
    0 ;

VARIABLE _EXT4-GA-D
VARIABLE _EXT4-GA-V
VARIABLE _EXT4-GA-CTX
VARIABLE _EXT4-GA-TYPE
VARIABLE _EXT4-GA-IOR

: _EXT4-GETATTR  ( dentry vfs -- ior )
    _EXT4-GA-V ! _EXT4-GA-D !
    _EXT4-GA-V @ _EXT4-CTX _EXT4-GA-CTX !
    _EXT4-GA-V @ V.VOLUME @ _EXT4-IO-VOL !
    _EXT4-GA-V @ _EXT4-IO-VFS !
    _EXT4-GA-D @ IN.BID @ _EXT4-GA-CTX @ _EXT4-LOAD-INODE ?DUP IF EXIT THEN
    _EXT4-GA-CTX @ _EXT4-STAGE-CURRENT-INODE
    _EXT4-GA-IOR ! _EXT4-GA-TYPE !
    _EXT4-GA-IOR @ ?DUP IF EXIT THEN
    _EXT4-GA-TYPE @ _EXT4-GA-D @ IN.TYPE @ <> IF VFS-E-CORRUPT EXIT THEN
    _EXT4-GA-CTX @ _EXT4-C.R.GEN + @
    _EXT4-GA-D @ D.VNODE @ VN.GEN @ <> IF VFS-E-STALE EXIT THEN
    _EXT4-GA-V @ _EXT4-ATTACHED? 0= IF VFS-E-STALE EXIT THEN
    _EXT4-GA-CTX @ _EXT4-GA-D @ _EXT4-GA-TYPE @ _EXT4-PUBLISH-STAGED
    0 ;

VARIABLE _EXT4-SF-BUF
VARIABLE _EXT4-SF-SIZE
VARIABLE _EXT4-SF-V
VARIABLE _EXT4-SF-CTX
VARIABLE _EXT4-SF-OUT
VARIABLE _EXT4-SF-AVAIL

: _EXT4-STATFS  ( buffer bytes vfs -- ior )
    _EXT4-SF-V ! _EXT4-SF-SIZE ! _EXT4-SF-BUF !
    _EXT4-SF-V @ _EXT4-CTX DUP _EXT4-SF-CTX !
    _EXT4-C.STAT + DUP _EXT4-SF-OUT ! VFS-STATFS-SIZE 0 FILL
    _EXT4-SF-CTX @ _EXT4-C.BSIZE + @ DUP
    _EXT4-SF-OUT @ VSF.BSIZE !
    _EXT4-SF-OUT @ VSF.FRSIZE !
    _EXT4-SF-CTX @ _EXT4-C.BLOCKS + @ _EXT4-SF-OUT @ VSF.BLOCKS !
    _EXT4-SF-CTX @ _EXT4-C.FREE-BLOCKS + @ DUP
    _EXT4-SF-OUT @ VSF.BFREE !
    _EXT4-SF-CTX @ _EXT4-C.RESERVED-BLOCKS + @
    2DUP U< IF 2DROP 0 ELSE - THEN DUP _EXT4-SF-AVAIL !
    _EXT4-SF-OUT @ VSF.BAVAIL !
    _EXT4-SF-CTX @ _EXT4-C.INODES + @ _EXT4-SF-OUT @ VSF.FILES !
    _EXT4-SF-CTX @ _EXT4-C.FREE-INODES + @ _EXT4-SF-OUT @ VSF.FFREE !
    255 _EXT4-SF-OUT @ VSF.NAMEMAX !
    0 _EXT4-SF-OUT @ VSF.FLAGS !
    _EXT4-SF-CTX @ _EXT4-C.UUID-LO + @ _EXT4-SF-OUT @ VSF.FSID-LO !
    _EXT4-SF-CTX @ _EXT4-C.UUID-HI + @ _EXT4-SF-OUT @ VSF.FSID-HI !
    0 _EXT4-SF-OUT @ VSF.RESERVED !
    _EXT4-SF-OUT @ _EXT4-SF-BUF @ VFS-STATFS-SIZE CMOVE
    0 ;

VARIABLE _EXT4-UM-V
: _EXT4-UNMOUNT  ( flags vfs -- ior )
    _EXT4-UM-V ! DROP
    _EXT4-UM-V @ V.BCTX @ ?DUP IF 0 SWAP _EXT4-C.READY + ! THEN
    0 _EXT4-UM-V @ V.BCTX !
    0 ;

VFS-CAP-PROBE VFS-CAP-MOUNT OR VFS-CAP-UNMOUNT OR
VFS-CAP-READDIR OR VFS-CAP-OPEN OR VFS-CAP-RELEASE OR
VFS-CAP-READ OR VFS-CAP-GETATTR OR VFS-CAP-READLINK OR
VFS-CAP-SYNCFS OR VFS-CAP-FSYNC OR VFS-CAP-STATFS OR
VFS-CAP-LISTXATTR OR VFS-CAP-GETXATTR OR
VFS-CAP-SPARSE OR VFS-CAP-STABLE-HANDLES OR CONSTANT EXT4-CAPS

CREATE EXT4-OPS VFS-OPS-SIZE ALLOT
EXT4-OPS VFS-OPS-SIZE 0 FILL
' _EXT4-PROBE   EXT4-OPS VFS-OP-PROBE   CELLS + !
' _EXT4-MOUNT   EXT4-OPS VFS-OP-MOUNT   CELLS + !
' _EXT4-UNMOUNT EXT4-OPS VFS-OP-UNMOUNT CELLS + !
' _EXT4-READDIR EXT4-OPS VFS-OP-READDIR CELLS + !
' _EXT4-OPEN    EXT4-OPS VFS-OP-OPEN    CELLS + !
' _EXT4-RELEASE EXT4-OPS VFS-OP-RELEASE CELLS + !
' _EXT4-READ    EXT4-OPS VFS-OP-READ    CELLS + !
' _EXT4-GETATTR EXT4-OPS VFS-OP-GETATTR CELLS + !
' _EXT4-READLINK EXT4-OPS VFS-OP-READLINK CELLS + !
' _EXT4-SYNCFS  EXT4-OPS VFS-OP-SYNCFS  CELLS + !
' _EXT4-FSYNC   EXT4-OPS VFS-OP-FSYNC   CELLS + !
' _EXT4-LISTXATTR EXT4-OPS VFS-OP-LISTXATTR CELLS + !
' _EXT4-GETXATTR  EXT4-OPS VFS-OP-GETXATTR  CELLS + !
' _EXT4-STATFS  EXT4-OPS VFS-OP-STATFS  CELLS + !

CREATE EXT4-BINDING
VFS-BINDING-MAGIC ,
VFS-BINDING-ABI-MAJOR ,
VFS-BINDING-ABI-MINOR ,
VFS-BINDING-DESC-SIZE ,
VFS-OPS-SIZE ,
EXT4-CAPS ,
VFS-BF-NEEDS-VOLUME VFS-BF-READ-ONLY OR VFS-BF-STABLE-IDS OR ,
EXT4-OPS ,
0 , 0 ,

: EXT4-NEW  ( arena volume -- vfs ior )
    EXT4-BINDING SWAP VFS-NEW ;

: EXT4-BLOCK-SIZE@  ( vfs -- bytes )  _EXT4-CTX _EXT4-C.BSIZE + @ ;
: EXT4-BLOCK-COUNT@ ( vfs -- blocks ) _EXT4-CTX _EXT4-C.BLOCKS + @ ;
: EXT4-GROUP-COUNT@ ( vfs -- groups ) _EXT4-CTX _EXT4-C.GROUPS + @ ;
: EXT4-INODE-SIZE@  ( vfs -- bytes )  _EXT4-CTX _EXT4-C.ISIZE + @ ;
