\ vfs-ext4-jbd2-codec.f — ext4 JBD2 endian and checksum codec
\
\ Internal dependency of the vfs-ext4.f public facade.

PROVIDED akashic-ext4-jbd2-codec
REQUIRE vfs-ext4-admission.f

VARIABLE _EXT4-BE-A
VARIABLE _EXT4-BE-V

: _EXT4-BE32@  ( addr -- u )
    _EXT4-BE-A !
    _EXT4-BE-A @ C@ 24 LSHIFT
    _EXT4-BE-A @ 1+ C@ 16 LSHIFT OR
    _EXT4-BE-A @ 2 + C@ 8 LSHIFT OR
    _EXT4-BE-A @ 3 + C@ OR ;

: _EXT4-BE32!  ( u addr -- )
    _EXT4-BE-A ! 0xFFFFFFFF AND _EXT4-BE-V !
    _EXT4-BE-V @ 24 RSHIFT _EXT4-BE-A @ C!
    _EXT4-BE-V @ 16 RSHIFT _EXT4-BE-A @ 1+ C!
    _EXT4-BE-V @ 8 RSHIFT _EXT4-BE-A @ 2 + C!
    _EXT4-BE-V @ _EXT4-BE-A @ 3 + C! ;

VARIABLE _EXT4-JC-BUF
VARIABLE _EXT4-JC-CTX
VARIABLE _EXT4-JC-FIELD
VARIABLE _EXT4-JC-STORED
VARIABLE _EXT4-JC-CALC

: _EXT4-JBD2-BLOCK-CHECKSUM?  ( buffer ctx -- flag ior )
    _EXT4-JC-CTX ! _EXT4-JC-BUF !
    _EXT4-JC-BUF @ _EXT4-JC-CTX @ _EXT4-C.BSIZE + @ 4 - +
    DUP _EXT4-JC-FIELD ! _EXT4-BE32@ _EXT4-JC-STORED !
    0 _EXT4-JC-FIELD @ _EXT4-BE32!
    _EXT4-JC-CTX @ _EXT4-C.J.SEED + @ _EXT4-CRC-START
    _EXT4-JC-BUF @ _EXT4-JC-CTX @ _EXT4-C.BSIZE + @ _EXT4-CRC-ADD
    ?DUP IF
        _EXT4-JC-STORED @ _EXT4-JC-FIELD @ _EXT4-BE32! 0 SWAP EXIT
    THEN
    _EXT4-CRC@ _EXT4-JC-CALC !
    _EXT4-JC-STORED @ _EXT4-JC-FIELD @ _EXT4-BE32!
    _EXT4-JC-CALC @ _EXT4-JC-STORED @ = 0 ;

: _EXT4-JBD2-SUPER-CHECKSUM?  ( buffer -- flag ior )
    DUP _EXT4-JC-BUF ! _EXT4-JS.CHECKSUM + DUP
    _EXT4-JC-FIELD ! _EXT4-BE32@ _EXT4-JC-STORED !
    0 _EXT4-JC-FIELD @ _EXT4-BE32!
    0xFFFFFFFF _EXT4-CRC-START
    _EXT4-JC-BUF @ 1024 _EXT4-CRC-ADD ?DUP IF
        _EXT4-JC-STORED @ _EXT4-JC-FIELD @ _EXT4-BE32! 0 SWAP EXIT
    THEN
    _EXT4-CRC@ _EXT4-JC-CALC !
    _EXT4-JC-STORED @ _EXT4-JC-FIELD @ _EXT4-BE32!
    _EXT4-JC-CALC @ _EXT4-JC-STORED @ = 0 ;

: _EXT4-JBD2-COMMIT-CHECKSUM?  ( buffer ctx -- flag ior )
    _EXT4-JC-CTX ! DUP _EXT4-JC-BUF !
    DUP 12 + C@ OVER 13 + C@ OR
    OVER 14 + C@ OR SWAP 15 + C@ OR IF FALSE 0 EXIT THEN
    7 0 DO
        _EXT4-JC-BUF @ 20 + I 4 * + _EXT4-BE32@ IF
            FALSE 0 UNLOOP EXIT
        THEN
    LOOP
    _EXT4-JC-BUF @ 56 + _EXT4-BE32@ 1000000000 U< 0= IF
        FALSE 0 EXIT
    THEN
    _EXT4-JC-BUF @ 16 + DUP _EXT4-JC-FIELD !
    _EXT4-BE32@ _EXT4-JC-STORED !
    0 _EXT4-JC-FIELD @ _EXT4-BE32!
    _EXT4-JC-CTX @ _EXT4-C.J.SEED + @ _EXT4-CRC-START
    _EXT4-JC-BUF @ _EXT4-JC-CTX @ _EXT4-C.BSIZE + @ _EXT4-CRC-ADD
    ?DUP IF
        _EXT4-JC-STORED @ _EXT4-JC-FIELD @ _EXT4-BE32! 0 SWAP EXIT
    THEN
    _EXT4-CRC@ _EXT4-JC-CALC !
    _EXT4-JC-STORED @ _EXT4-JC-FIELD @ _EXT4-BE32!
    _EXT4-JC-CALC @ _EXT4-JC-STORED @ = 0 ;

VARIABLE _EXT4-JEC-BUF
VARIABLE _EXT4-JEC-CTX
VARIABLE _EXT4-JEC-FIELD
VARIABLE _EXT4-JEC-TID

: _EXT4-JBD2-STAMP-SUPER-CHECKSUM  ( buffer -- ior )
    DUP _EXT4-JEC-BUF ! _EXT4-JS.CHECKSUM + _EXT4-JEC-FIELD !
    0 _EXT4-JEC-FIELD @ _EXT4-BE32!
    0xFFFFFFFF _EXT4-CRC-START
    _EXT4-JEC-BUF @ 1024 _EXT4-CRC-ADD ?DUP IF EXIT THEN
    _EXT4-CRC@ _EXT4-JEC-FIELD @ _EXT4-BE32! 0 ;

: _EXT4-JBD2-STAMP-BLOCK-CHECKSUM  ( buffer ctx -- ior )
    _EXT4-JEC-CTX ! DUP _EXT4-JEC-BUF !
    _EXT4-JEC-CTX @ _EXT4-C.BSIZE + @ 4 - + _EXT4-JEC-FIELD !
    0 _EXT4-JEC-FIELD @ _EXT4-BE32!
    _EXT4-JEC-CTX @ _EXT4-C.J.SEED + @ _EXT4-CRC-START
    _EXT4-JEC-BUF @ _EXT4-JEC-CTX @ _EXT4-C.BSIZE + @ _EXT4-CRC-ADD
    ?DUP IF EXIT THEN
    _EXT4-CRC@ _EXT4-JEC-FIELD @ _EXT4-BE32! 0 ;

: _EXT4-JBD2-STAMP-COMMIT-CHECKSUM  ( buffer ctx -- ior )
    _EXT4-JEC-CTX ! DUP _EXT4-JEC-BUF !
    16 + _EXT4-JEC-FIELD !
    0 _EXT4-JEC-FIELD @ _EXT4-BE32!
    _EXT4-JEC-CTX @ _EXT4-C.J.SEED + @ _EXT4-CRC-START
    _EXT4-JEC-BUF @ _EXT4-JEC-CTX @ _EXT4-C.BSIZE + @ _EXT4-CRC-ADD
    ?DUP IF EXIT THEN
    _EXT4-CRC@ _EXT4-JEC-FIELD @ _EXT4-BE32! 0 ;

: _EXT4-JBD2-EMIT-TAG-CHECKSUM  ( payload tid ctx -- crc ior )
    _EXT4-JEC-CTX ! _EXT4-JEC-TID ! _EXT4-JEC-BUF !
    _EXT4-JEC-TID @ _EXT4-JEC-CTX @ _EXT4-C.TMP + _EXT4-BE32!
    _EXT4-JEC-CTX @ _EXT4-C.J.SEED + @ _EXT4-CRC-START
    _EXT4-JEC-CTX @ _EXT4-C.TMP + 4 _EXT4-CRC-ADD
    ?DUP IF 0 SWAP EXIT THEN
    _EXT4-JEC-BUF @ _EXT4-JEC-CTX @ _EXT4-C.BSIZE + @ _EXT4-CRC-ADD
    ?DUP IF 0 SWAP EXIT THEN
    _EXT4-CRC@ 0 ;

: _EXT4-JBD2-TAG-CHECKSUM?  ( buffer stored sequence ctx -- flag ior )
    ROT _EXT4-JC-STORED !
    _EXT4-JBD2-EMIT-TAG-CHECKSUM
    ?DUP IF NIP 0 SWAP EXIT THEN
    _EXT4-JC-STORED @ = 0 ;
