\ =====================================================================
\  server.f - Caller-owned generic Rabbit server peer
\ =====================================================================
\  One server owner exclusively operates one server-role Rabbit connection,
\  one EMPTY reply builder, and one copied Burrow identifier.  It borrows one
\  immutable sealed router plus peer-admission evidence and callbacks.  It is
\  deliberately a per-peer protocol owner: listeners, peer pools, scheduling,
\  application state, journals, and product policy remain with its caller.
\
\  The admission callback is synchronous:
\
\    ( hello-frame peer-evidence context -- peer-token decision )
\
\  decision is RSERVER-ADMIT-ALLOW or RSERVER-ADMIT-DENY.  The HELLO frame
\  expires when the callback returns; peer-token is an opaque stable cell
\  retained until finalization.  This checkpoint implements only anonymous
\  fixture negotiation.  DENY or callback failure cancels the peer because
\  the lower minimal handshake cannot honestly transmit a refusal before it
\  establishes the session.
\
\  Exact router handlers are synchronous:
\
\    ( request-frame request-kind peer-token empty-reply-builder context
\      -- outcome )
\
\  RESPONSE means the handler sealed one correlated response.  DENY and
\  FAILED ask the server to synthesize 403 and 500 responses.  A thrown or
\  invalid callback and a malformed/wrong-correlation RESPONSE also become a
\  bounded 500 response when the preflighted builder remains recoverable.
\  Exact route misses become 404; correlated extension verbs become 501.
\
\  The request loan remains live until the encoded response is copied into a
\  connection queue slot.  Only then is the request committed.  The poller
\  pumps TX before dispatch and will not loan a request while its response
\  queue is full, so application code is never repeated merely because a peer
\  is backpressured.  Server-side EVENT/subscription delivery is intentionally
\  a later owner layered on this response boundary.
\
\  All persistent bytes are caller-owned.  Private VARIABLEs are synchronous
\  scratch and callbacks make this module globally non-reentrant; nested
\  POLL/DISPATCH is refused before the outer borrowed frame can be overwritten.
\  Callbacks must not retain slices or the builder, pump either connection,
\  mutate the router, or otherwise bypass the server's exclusive ownership.
\ =====================================================================

PROVIDED akashic-rabbit-server

REQUIRE connection.f
REQUIRE router.f
REQUIRE ../../utils/memory-span.f
REQUIRE ../../text/utf8.f

\ =====================================================================
\  Public vocabularies
\ =====================================================================

0  CONSTANT RSERVER-S-OK
1  CONSTANT RSERVER-S-INVALID
2  CONSTANT RSERVER-S-STATE
3  CONSTANT RSERVER-S-ALIAS
4  CONSTANT RSERVER-S-CONNECTION
5  CONSTANT RSERVER-S-ROUTER
6  CONSTANT RSERVER-S-BUILDER
7  CONSTANT RSERVER-S-MESSAGE
8  CONSTANT RSERVER-S-CAPACITY
9  CONSTANT RSERVER-S-PENDING
10 CONSTANT RSERVER-S-NOT-FOUND
11 CONSTANT RSERVER-S-UNSUPPORTED
12 CONSTANT RSERVER-S-DENIED
13 CONSTANT RSERVER-S-CALLBACK
14 CONSTANT RSERVER-S-PROTOCOL
15 CONSTANT RSERVER-S-CANCELLED
16 CONSTANT RSERVER-S-EOF

0 CONSTANT RSERVER-ST-READY
1 CONSTANT RSERVER-ST-ACTIVE
2 CONSTANT RSERVER-ST-CLOSING
3 CONSTANT RSERVER-ST-CLOSED
4 CONSTANT RSERVER-ST-CANCELLED
5 CONSTANT RSERVER-ST-FAILED

0 CONSTANT RSERVER-ITEM-NONE
1 CONSTANT RSERVER-ITEM-HANDSHAKE
2 CONSTANT RSERVER-ITEM-RESPONSE
3 CONSTANT RSERVER-ITEM-CONTROL
4 CONSTANT RSERVER-ITEM-REFUSAL

0 CONSTANT RSERVER-ADMIT-ALLOW
1 CONSTANT RSERVER-ADMIT-DENY

0 CONSTANT RSERVER-HANDLER-RESPONSE
1 CONSTANT RSERVER-HANDLER-DENY
2 CONSTANT RSERVER-HANDLER-FAILED
3 CONSTANT RSERVER-HANDLER-NONE

0 CONSTANT RSERVER-DETAIL-NONE
1 CONSTANT RSERVER-DETAIL-CONNECTION
2 CONSTANT RSERVER-DETAIL-ROUTER
3 CONSTANT RSERVER-DETAIL-BUILDER
4 CONSTANT RSERVER-DETAIL-MESSAGE
5 CONSTANT RSERVER-DETAIL-ADMISSION
6 CONSTANT RSERVER-DETAIL-CALLBACK

: RSERVER-STATUS-VALID?  ( status -- flag )
    DUP RSERVER-S-OK >= SWAP RSERVER-S-EOF <= AND ;

: RSERVER-STATE-VALID?  ( state -- flag )
    DUP RSERVER-ST-READY >= SWAP RSERVER-ST-FAILED <= AND ;

: RSERVER-ITEM-VALID?  ( item -- flag )
    DUP RSERVER-ITEM-NONE >= SWAP RSERVER-ITEM-REFUSAL <= AND ;

: RSERVER-ADMIT-VALID?  ( decision -- flag )
    DUP RSERVER-ADMIT-ALLOW = SWAP RSERVER-ADMIT-DENY = OR ;

: RSERVER-HANDLER-VALID?  ( outcome -- flag )
    DUP RSERVER-HANDLER-RESPONSE >=
    SWAP RSERVER-HANDLER-FAILED <= AND ;

\ =====================================================================
\  Opaque caller-owned descriptor
\ =====================================================================

0x5253455256455231 CONSTANT _RSERVER-MAGIC-VALUE  \ "RSERVER1"
1                  CONSTANT _RSERVER-ABI-VERSION

  0 CONSTANT _RSERVER-MAGIC
  8 CONSTANT _RSERVER-ABI
 16 CONSTANT _RSERVER-BYTES
 24 CONSTANT _RSERVER-STATE
 32 CONSTANT _RSERVER-LAST-STATUS
 40 CONSTANT _RSERVER-DETAIL-DOMAIN
 48 CONSTANT _RSERVER-DETAIL-STATUS
 56 CONSTANT _RSERVER-CONNECTION
 64 CONSTANT _RSERVER-ROUTER
 72 CONSTANT _RSERVER-BUILDER
 80 CONSTANT _RSERVER-BURROW-A
 88 CONSTANT _RSERVER-BURROW-CAP
 96 CONSTANT _RSERVER-BURROW-U
104 CONSTANT _RSERVER-PEER-EVIDENCE
112 CONSTANT _RSERVER-ADMIT-XT
120 CONSTANT _RSERVER-ADMIT-CONTEXT
128 CONSTANT _RSERVER-PEER-TOKEN
136 CONSTANT _RSERVER-FLAGS
144 CONSTANT _RSERVER-CLEANUP-STATUS
152 CONSTANT _RSERVER-CALLBACK-THROW
160 CONSTANT _RSERVER-LAST-RESPONSE-CODE
168 CONSTANT _RSERVER-LAST-HANDLER-OUTCOME
176 CONSTANT RABBIT-SERVER-SIZE

1 CONSTANT _RSERVER-F-PEER-ADMITTED
2 CONSTANT _RSERVER-F-HELLO-QUEUED
3 CONSTANT _RSERVER-F-KNOWN

: RSERVER.MAGIC                 ( server -- field ) _RSERVER-MAGIC + ;
: RSERVER.ABI                   ( server -- field ) _RSERVER-ABI + ;
: RSERVER.BYTES                 ( server -- field ) _RSERVER-BYTES + ;
: RSERVER.STATE                 ( server -- field ) _RSERVER-STATE + ;
: RSERVER.LAST-STATUS           ( server -- field ) _RSERVER-LAST-STATUS + ;
: RSERVER.DETAIL-DOMAIN         ( server -- field ) _RSERVER-DETAIL-DOMAIN + ;
: RSERVER.DETAIL-STATUS         ( server -- field ) _RSERVER-DETAIL-STATUS + ;
: RSERVER.CONNECTION            ( server -- field ) _RSERVER-CONNECTION + ;
: RSERVER.ROUTER                ( server -- field ) _RSERVER-ROUTER + ;
: RSERVER.BUILDER               ( server -- field ) _RSERVER-BUILDER + ;
: RSERVER.BURROW-A              ( server -- field ) _RSERVER-BURROW-A + ;
: RSERVER.BURROW-CAP            ( server -- field ) _RSERVER-BURROW-CAP + ;
: RSERVER.BURROW-U              ( server -- field ) _RSERVER-BURROW-U + ;
: RSERVER.PEER-EVIDENCE         ( server -- field ) _RSERVER-PEER-EVIDENCE + ;
: RSERVER.ADMIT-XT              ( server -- field ) _RSERVER-ADMIT-XT + ;
: RSERVER.ADMIT-CONTEXT         ( server -- field ) _RSERVER-ADMIT-CONTEXT + ;
: RSERVER.PEER-TOKEN            ( server -- field ) _RSERVER-PEER-TOKEN + ;
: RSERVER.FLAGS                 ( server -- field ) _RSERVER-FLAGS + ;
: RSERVER.CLEANUP-STATUS        ( server -- field ) _RSERVER-CLEANUP-STATUS + ;
: RSERVER.CALLBACK-THROW        ( server -- field ) _RSERVER-CALLBACK-THROW + ;
: RSERVER.LAST-RESPONSE-CODE    ( server -- field ) _RSERVER-LAST-RESPONSE-CODE + ;
: RSERVER.LAST-HANDLER-OUTCOME  ( server -- field ) _RSERVER-LAST-HANDLER-OUTCOME + ;

: _RSERVER-CELL-ALIGNED?  ( address -- flag )
    7 AND 0= ;

: _RSERVER-SPAN?  ( address bytes -- flag )
    DUP 0< IF 2DROP 0 EXIT THEN
    DUP IF OVER 0= IF 2DROP 0 EXIT THEN THEN
    MSPAN-NONWRAPPING? ;

\ =====================================================================
\  Cross-owner geometry
\ =====================================================================

VARIABLE _RSERVERG-A
VARIABLE _RSERVERG-U
VARIABLE _RSERVERG-R
VARIABLE _RSERVERG-B
VARIABLE _RSERVERG-C

: _RSERVER-SPAN-HITS-ROUTER?  ( address bytes router -- flag )
    RROUTER-OWNED-SPAN-OVERLAP? ;

: _RSERVER-ROUTER-HITS-BUILDER?  ( router builder -- flag )
    _RSERVERG-B ! _RSERVERG-R !
    _RSERVERG-R @ RROUTER-SIZE _RSERVERG-B @
        RMSGB-OWNED-SPAN-OVERLAP? IF -1 EXIT THEN
    _RSERVERG-R @ _RROUTER.ENTRIES @
        _RSERVERG-R @ _RROUTER.ENTRY-CAPACITY @ RROUTER-ENTRY-SIZE *
        _RSERVERG-B @ RMSGB-OWNED-SPAN-OVERLAP? IF -1 EXIT THEN
    _RSERVERG-R @ _RROUTER.ARENA-A @
        _RSERVERG-R @ _RROUTER.ARENA-CAPACITY @ _RSERVERG-B @
        RMSGB-OWNED-SPAN-OVERLAP? ;

: _RSERVER-CONNECTION-HITS-ROUTER?  ( connection router -- flag )
    _RSERVERG-R ! _RSERVERG-C !
    _RSERVERG-R @ RROUTER-SIZE _RSERVERG-C @
        RABBIT-CONNECTION-OWNED-SPAN-OVERLAP? IF -1 EXIT THEN
    _RSERVERG-R @ _RROUTER.ENTRIES @
        _RSERVERG-R @ _RROUTER.ENTRY-CAPACITY @ RROUTER-ENTRY-SIZE *
        _RSERVERG-C @ RABBIT-CONNECTION-OWNED-SPAN-OVERLAP? IF
        -1 EXIT
    THEN
    _RSERVERG-R @ _RROUTER.ARENA-A @
        _RSERVERG-R @ _RROUTER.ARENA-CAPACITY @ _RSERVERG-C @
        RABBIT-CONNECTION-OWNED-SPAN-OVERLAP? ;

\ =====================================================================
\  Validation and initialization
\ =====================================================================

VARIABLE _RSERVERV-S

: _RSERVER-LAST-CODE-VALID?  ( code -- flag )
    DUP 0= IF DROP -1 EXIT THEN
    DUP 100 >= SWAP 599 <= AND ;

: RABBIT-SERVER-VALID?  ( server -- flag )
    DUP 0= IF DROP 0 EXIT THEN
    DUP _RSERVER-CELL-ALIGNED? 0= IF DROP 0 EXIT THEN
    DUP RABBIT-SERVER-SIZE MSPAN-NONWRAPPING? 0= IF DROP 0 EXIT THEN
    DUP _RSERVERV-S !
    DUP RSERVER.MAGIC @ _RSERVER-MAGIC-VALUE <> IF DROP 0 EXIT THEN
    DUP RSERVER.ABI @ _RSERVER-ABI-VERSION <> IF DROP 0 EXIT THEN
    DUP RSERVER.BYTES @ RABBIT-SERVER-SIZE <> IF DROP 0 EXIT THEN
    DUP RSERVER.STATE @ RSERVER-STATE-VALID? 0= IF DROP 0 EXIT THEN
    DUP RSERVER.LAST-STATUS @ RSERVER-STATUS-VALID? 0= IF DROP 0 EXIT THEN
    DUP RSERVER.DETAIL-DOMAIN @ DUP RSERVER-DETAIL-NONE <
        SWAP RSERVER-DETAIL-CALLBACK > OR IF DROP 0 EXIT THEN
    DUP RSERVER.CONNECTION @ RABBIT-CONNECTION-VALID? 0= IF
        DROP 0 EXIT
    THEN
    DUP RSERVER.ROUTER @ RROUTER-SEALED? 0= IF DROP 0 EXIT THEN
    DUP RSERVER.BUILDER @ RMSGB-VALID? 0= IF DROP 0 EXIT THEN
    DUP RSERVER.BURROW-A @ OVER RSERVER.BURROW-CAP @
        _RSERVER-SPAN? 0= IF DROP 0 EXIT THEN
    DUP RSERVER.BURROW-U @ DUP 0> 0= IF 2DROP 0 EXIT THEN
    OVER RSERVER.BURROW-CAP @ U> IF DROP 0 EXIT THEN
    DUP RSERVER.BURROW-A @ OVER RSERVER.BURROW-U @
        UTF8-VALID? 0= IF DROP 0 EXIT THEN
    DUP RSERVER.ADMIT-XT @ 0= IF DROP 0 EXIT THEN
    DUP RSERVER.FLAGS @ _RSERVER-F-KNOWN INVERT AND IF DROP 0 EXIT THEN
    DUP RSERVER.LAST-RESPONSE-CODE @
        _RSERVER-LAST-CODE-VALID? 0= IF DROP 0 EXIT THEN
    DUP RSERVER.LAST-HANDLER-OUTCOME @ DUP RSERVER-HANDLER-NONE =
        SWAP RSERVER-HANDLER-VALID? OR 0= IF DROP 0 EXIT THEN
    DROP
    _RSERVERV-S @ RABBIT-SERVER-SIZE
        _RSERVERV-S @ RSERVER.CONNECTION @
        RABBIT-CONNECTION-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERV-S @ RSERVER.BURROW-A @
        _RSERVERV-S @ RSERVER.BURROW-CAP @
        _RSERVERV-S @ RSERVER.CONNECTION @
        RABBIT-CONNECTION-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERV-S @ RSERVER.BUILDER @
        _RSERVERV-S @ RSERVER.CONNECTION @
        RABBIT-CONNECTION-BUILDER-OVERLAP? IF 0 EXIT THEN
    _RSERVERV-S @ RABBIT-SERVER-SIZE _RSERVERV-S @ RSERVER.ROUTER @
        _RSERVER-SPAN-HITS-ROUTER? IF 0 EXIT THEN
    _RSERVERV-S @ RSERVER.BURROW-A @
        _RSERVERV-S @ RSERVER.BURROW-CAP @
        _RSERVERV-S @ RSERVER.ROUTER @
        _RSERVER-SPAN-HITS-ROUTER? IF 0 EXIT THEN
    _RSERVERV-S @ RSERVER.ROUTER @ _RSERVERV-S @ RSERVER.BUILDER @
        _RSERVER-ROUTER-HITS-BUILDER? IF 0 EXIT THEN
    _RSERVERV-S @ RABBIT-SERVER-SIZE _RSERVERV-S @ RSERVER.BUILDER @
        RMSGB-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERV-S @ RSERVER.BURROW-A @
        _RSERVERV-S @ RSERVER.BURROW-CAP @
        _RSERVERV-S @ RSERVER.BUILDER @
        RMSGB-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERV-S @ RABBIT-SERVER-SIZE
        _RSERVERV-S @ RSERVER.BURROW-A @
        _RSERVERV-S @ RSERVER.BURROW-CAP @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERV-S @ RSERVER.CONNECTION @ _RSERVERV-S @ RSERVER.ROUTER @
        _RSERVER-CONNECTION-HITS-ROUTER? 0= ;

VARIABLE _RSERVERI-CONN
VARIABLE _RSERVERI-ROUTER
VARIABLE _RSERVERI-BUILDER
VARIABLE _RSERVERI-SA
VARIABLE _RSERVERI-SU
VARIABLE _RSERVERI-BA
VARIABLE _RSERVERI-BCAP
VARIABLE _RSERVERI-EVIDENCE
VARIABLE _RSERVERI-AXT
VARIABLE _RSERVERI-ACTX
VARIABLE _RSERVERI-S

: _RSERVER-INIT-GEOMETRY?  ( -- flag )
    _RSERVERI-S @ RABBIT-SERVER-SIZE _RSERVERI-CONN @
        RABBIT-CONNECTION-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERI-BA @ _RSERVERI-BCAP @ _RSERVERI-CONN @
        RABBIT-CONNECTION-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERI-SA @ _RSERVERI-SU @ _RSERVERI-CONN @
        RABBIT-CONNECTION-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERI-BUILDER @ _RSERVERI-CONN @
        RABBIT-CONNECTION-BUILDER-OVERLAP? IF 0 EXIT THEN
    _RSERVERI-CONN @ _RSERVERI-ROUTER @
        _RSERVER-CONNECTION-HITS-ROUTER? IF 0 EXIT THEN
    _RSERVERI-S @ RABBIT-SERVER-SIZE _RSERVERI-ROUTER @
        _RSERVER-SPAN-HITS-ROUTER? IF 0 EXIT THEN
    _RSERVERI-BA @ _RSERVERI-BCAP @ _RSERVERI-ROUTER @
        _RSERVER-SPAN-HITS-ROUTER? IF 0 EXIT THEN
    _RSERVERI-ROUTER @ _RSERVERI-BUILDER @
        _RSERVER-ROUTER-HITS-BUILDER? IF 0 EXIT THEN
    _RSERVERI-S @ RABBIT-SERVER-SIZE _RSERVERI-BUILDER @
        RMSGB-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERI-BA @ _RSERVERI-BCAP @ _RSERVERI-BUILDER @
        RMSGB-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERI-SA @ _RSERVERI-SU @ _RSERVERI-BUILDER @
        RMSGB-OWNED-SPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERI-SA @ _RSERVERI-SU @
        _RSERVERI-S @ RABBIT-SERVER-SIZE MSPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERI-SA @ _RSERVERI-SU @
        _RSERVERI-BA @ _RSERVERI-BCAP @ MSPAN-OVERLAP? IF 0 EXIT THEN
    _RSERVERI-S @ RABBIT-SERVER-SIZE
        _RSERVERI-BA @ _RSERVERI-BCAP @ MSPAN-OVERLAP? 0= ;

\ Inputs are connection, sealed router, empty reply builder, Burrow source and
\ destination spans, peer evidence, admission XT/context, and the server.
: RABBIT-SERVER-INIT  ( eleven caller inputs -- status )
    _RSERVERI-S ! _RSERVERI-ACTX ! _RSERVERI-AXT !
    _RSERVERI-EVIDENCE ! _RSERVERI-BCAP ! _RSERVERI-BA !
    _RSERVERI-SU ! _RSERVERI-SA ! _RSERVERI-BUILDER !
    _RSERVERI-ROUTER ! _RSERVERI-CONN !
    _RSERVERI-S @ 0= IF RSERVER-S-INVALID EXIT THEN
    _RSERVERI-S @ _RSERVER-CELL-ALIGNED? 0= IF
        RSERVER-S-INVALID EXIT
    THEN
    _RSERVERI-S @ RABBIT-SERVER-SIZE MSPAN-NONWRAPPING? 0= IF
        RSERVER-S-INVALID EXIT
    THEN
    _RSERVERI-S @ RSERVER.MAGIC @ _RSERVER-MAGIC-VALUE = IF
        RSERVER-S-STATE EXIT
    THEN
    _RSERVERI-CONN @ RABBIT-CONNECTION-VALID? 0= IF
        RSERVER-S-CONNECTION EXIT
    THEN
    _RSERVERI-CONN @ RCONN.STATE @ DUP RCONN-ST-READY =
    SWAP RCONN-ST-OPEN = OR 0= IF
        RSERVER-S-STATE EXIT
    THEN
    _RSERVERI-CONN @ RCONN.SESSION @ DUP RABBIT-SESSION-VALID? 0= IF
        DROP RSERVER-S-CONNECTION EXIT
    THEN
    DUP RSESS.ROLE @ RABBIT-ROLE-SERVER <> IF
        DROP RSERVER-S-CONNECTION EXIT
    THEN
    RABBIT-SESSION-STATE@
    _RSERVERI-CONN @ RCONN.STATE @ RCONN-ST-READY = IF
        RABBIT-ST-READY
    ELSE
        RABBIT-ST-HELLO
    THEN <> IF
        RSERVER-S-STATE EXIT
    THEN
    _RSERVERI-CONN @ RCONN.CONTROL-Q @ RTXQ.CAP @ 0= IF
        RSERVER-S-CAPACITY EXIT
    THEN
    _RSERVERI-CONN @ RCONN.DATA-Q @ RTXQ.CAP @ 0= IF
        RSERVER-S-CAPACITY EXIT
    THEN
    _RSERVERI-CONN @ RABBIT-CONNECTION-TX-COUNTS@
    IF 2DROP RSERVER-S-CONNECTION EXIT THEN
    OR IF RSERVER-S-STATE EXIT THEN
    _RSERVERI-CONN @ RABBIT-CONNECTION-RX-READY? IF
        RSERVER-S-STATE EXIT
    THEN
    _RSERVERI-ROUTER @ RROUTER-SEALED? 0= IF
        RSERVER-S-ROUTER EXIT
    THEN
    _RSERVERI-BUILDER @ RMSGB-VALID? 0= IF
        RSERVER-S-BUILDER EXIT
    THEN
    _RSERVERI-BUILDER @ RMSGB-STATE@ RMSGB-STATE-EMPTY <> IF
        RSERVER-S-BUILDER EXIT
    THEN
    _RSERVERI-SU @ 0> 0= IF RSERVER-S-INVALID EXIT THEN
    _RSERVERI-SA @ _RSERVERI-SU @ _RSERVER-SPAN? 0= IF
        RSERVER-S-INVALID EXIT
    THEN
    _RSERVERI-SA @ _RSERVERI-SU @ UTF8-VALID? 0= IF
        RSERVER-S-MESSAGE EXIT
    THEN
    _RSERVERI-BA @ _RSERVERI-BCAP @ _RSERVER-SPAN? 0= IF
        RSERVER-S-INVALID EXIT
    THEN
    _RSERVERI-SU @ _RSERVERI-BCAP @ U> IF
        RSERVER-S-CAPACITY EXIT
    THEN
    _RSERVERI-AXT @ 0= IF RSERVER-S-INVALID EXIT THEN
    _RSERVER-INIT-GEOMETRY? 0= IF RSERVER-S-ALIAS EXIT THEN

    _RSERVERI-S @ RABBIT-SERVER-SIZE 0 FILL
    _RSERVERI-BA @ _RSERVERI-BCAP @ 0 FILL
    _RSERVERI-SA @ _RSERVERI-BA @ _RSERVERI-SU @ MOVE
    _RSERVER-MAGIC-VALUE _RSERVERI-S @ RSERVER.MAGIC !
    _RSERVER-ABI-VERSION _RSERVERI-S @ RSERVER.ABI !
    RABBIT-SERVER-SIZE _RSERVERI-S @ RSERVER.BYTES !
    _RSERVERI-CONN @ RCONN.STATE @ RCONN-ST-OPEN = IF
        RSERVER-ST-ACTIVE
    ELSE
        RSERVER-ST-READY
    THEN _RSERVERI-S @ RSERVER.STATE !
    RSERVER-S-OK _RSERVERI-S @ RSERVER.LAST-STATUS !
    RSERVER-DETAIL-NONE _RSERVERI-S @ RSERVER.DETAIL-DOMAIN !
    _RSERVERI-CONN @ _RSERVERI-S @ RSERVER.CONNECTION !
    _RSERVERI-ROUTER @ _RSERVERI-S @ RSERVER.ROUTER !
    _RSERVERI-BUILDER @ _RSERVERI-S @ RSERVER.BUILDER !
    _RSERVERI-BA @ _RSERVERI-S @ RSERVER.BURROW-A !
    _RSERVERI-BCAP @ _RSERVERI-S @ RSERVER.BURROW-CAP !
    _RSERVERI-SU @ _RSERVERI-S @ RSERVER.BURROW-U !
    _RSERVERI-EVIDENCE @ _RSERVERI-S @ RSERVER.PEER-EVIDENCE !
    _RSERVERI-AXT @ _RSERVERI-S @ RSERVER.ADMIT-XT !
    _RSERVERI-ACTX @ _RSERVERI-S @ RSERVER.ADMIT-CONTEXT !
    RCONN-S-OK _RSERVERI-S @ RSERVER.CLEANUP-STATUS !
    RSERVER-HANDLER-NONE _RSERVERI-S @ RSERVER.LAST-HANDLER-OUTCOME !
    RSERVER-S-OK ;

\ =====================================================================
\  Inspection and status publication
\ =====================================================================

VARIABLE _RSERVERS-S
VARIABLE _RSERVERP-BUSY

: _RSERVER-STATUS!  ( status domain detail server -- status )
    _RSERVERS-S !
    _RSERVERS-S @ RSERVER.DETAIL-STATUS !
    _RSERVERS-S @ RSERVER.DETAIL-DOMAIN !
    DUP _RSERVERS-S @ RSERVER.LAST-STATUS ! ;

: RABBIT-SERVER-STATE@  ( server -- state status )
    DUP RABBIT-SERVER-VALID? 0= IF
        DROP RSERVER-ST-FAILED RSERVER-S-INVALID EXIT
    THEN
    RSERVER.STATE @ RSERVER-S-OK ;

: RABBIT-SERVER-LAST-STATUS@  ( server -- status )
    DUP RABBIT-SERVER-VALID? 0= IF DROP RSERVER-S-INVALID EXIT THEN
    RSERVER.LAST-STATUS @ ;

: RABBIT-SERVER-DETAIL@  ( server -- domain detail status )
    DUP RABBIT-SERVER-VALID? 0= IF
        DROP RSERVER-DETAIL-NONE 0 RSERVER-S-INVALID EXIT
    THEN
    DUP RSERVER.DETAIL-DOMAIN @ SWAP RSERVER.DETAIL-STATUS @
    RSERVER-S-OK ;

: RABBIT-SERVER-BURROW-ID$  ( server -- address length status )
    DUP RABBIT-SERVER-VALID? 0= IF DROP 0 0 RSERVER-S-INVALID EXIT THEN
    DUP RSERVER.BURROW-A @ SWAP RSERVER.BURROW-U @ RSERVER-S-OK ;

: RABBIT-SERVER-PEER@  ( server -- peer-token admitted status )
    DUP RABBIT-SERVER-VALID? 0= IF
        DROP 0 0 RSERVER-S-INVALID EXIT
    THEN
    DUP RSERVER.PEER-TOKEN @ SWAP RSERVER.FLAGS @
        _RSERVER-F-PEER-ADMITTED AND 0<> RSERVER-S-OK ;

: RABBIT-SERVER-LAST-RESPONSE-CODE@  ( server -- code status )
    DUP RABBIT-SERVER-VALID? 0= IF DROP 0 RSERVER-S-INVALID EXIT THEN
    RSERVER.LAST-RESPONSE-CODE @ RSERVER-S-OK ;

\ =====================================================================
\  Lifecycle
\ =====================================================================

: RABBIT-SERVER-OPEN  ( server -- status )
    _RSERVERP-BUSY @ IF DROP RSERVER-S-STATE EXIT THEN
    DUP RABBIT-SERVER-VALID? 0= IF DROP RSERVER-S-INVALID EXIT THEN
    DUP _RSERVERS-S ! RSERVER.STATE @ DUP RSERVER-ST-ACTIVE = IF
        DROP RSERVER-S-OK RSERVER-DETAIL-NONE 0 _RSERVERS-S @
            _RSERVER-STATUS! EXIT
    THEN
    RSERVER-ST-READY <> IF
        RSERVER-S-STATE RSERVER-DETAIL-NONE 0 _RSERVERS-S @
            _RSERVER-STATUS! EXIT
    THEN
    _RSERVERS-S @ RSERVER.CONNECTION @ RABBIT-CONNECTION-OPEN
    DUP RCONN-S-OK = IF
        DROP RSERVER-ST-ACTIVE _RSERVERS-S @ RSERVER.STATE !
        RSERVER-S-OK RSERVER-DETAIL-NONE 0 _RSERVERS-S @
            _RSERVER-STATUS! EXIT
    THEN
    DUP RCONN-S-PENDING = IF
        DROP RSERVER-S-PENDING RSERVER-DETAIL-NONE 0 _RSERVERS-S @
            _RSERVER-STATUS! EXIT
    THEN
    DUP RCONN-S-CANCELLED = IF
        RSERVER-ST-CANCELLED _RSERVERS-S @ RSERVER.STATE !
        RSERVER-S-CANCELLED RSERVER-DETAIL-CONNECTION ROT _RSERVERS-S @
            _RSERVER-STATUS! EXIT
    THEN
    RSERVER-ST-FAILED _RSERVERS-S @ RSERVER.STATE !
    RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION ROT _RSERVERS-S @
        _RSERVER-STATUS! ;

VARIABLE _RSERVERL-RS

: _RSERVER-BUILDER-RESET  ( server -- builder-status )
    RSERVER.BUILDER @ DUP RMSGB-VALID? 0= IF
        DROP RMSGB-S-INVALID EXIT
    THEN
    RMSGB-RESET ;

: RABBIT-SERVER-CLOSE  ( server -- status )
    _RSERVERP-BUSY @ IF DROP RSERVER-S-STATE EXIT THEN
    DUP RABBIT-SERVER-VALID? 0= IF DROP RSERVER-S-INVALID EXIT THEN
    DUP _RSERVERS-S ! RSERVER.STATE @ DUP RSERVER-ST-CLOSED = IF
        DROP RSERVER-S-OK RSERVER-DETAIL-NONE 0 _RSERVERS-S @
            _RSERVER-STATUS! EXIT
    THEN
    RSERVER-ST-CANCELLED = IF
        RSERVER-S-CANCELLED RSERVER-DETAIL-NONE 0 _RSERVERS-S @
            _RSERVER-STATUS! EXIT
    THEN
    _RSERVERS-S @ _RSERVER-BUILDER-RESET DROP
    _RSERVERS-S @ RSERVER.CONNECTION @ RABBIT-CONNECTION-CLOSE
        DUP _RSERVERL-RS !
    DUP RCONN-S-OK = IF
        DROP RSERVER-ST-CLOSED _RSERVERS-S @ RSERVER.STATE !
        RSERVER-S-OK RSERVER-DETAIL-NONE 0 _RSERVERS-S @
            _RSERVER-STATUS! EXIT
    THEN
    DUP RCONN-S-PENDING = IF
        DROP RSERVER-ST-CLOSING _RSERVERS-S @ RSERVER.STATE !
        RSERVER-S-PENDING RSERVER-DETAIL-NONE 0 _RSERVERS-S @
            _RSERVER-STATUS! EXIT
    THEN
    RCONN-S-CANCELLED = IF
        RSERVER-ST-CANCELLED _RSERVERS-S @ RSERVER.STATE !
        RSERVER-S-CANCELLED RSERVER-DETAIL-CONNECTION _RSERVERL-RS @
            _RSERVERS-S @ _RSERVER-STATUS! EXIT
    THEN
    RSERVER-ST-FAILED _RSERVERS-S @ RSERVER.STATE !
    RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION _RSERVERL-RS @
        _RSERVERS-S @ _RSERVER-STATUS! ;

: RABBIT-SERVER-CLOSE-POLL  ( server -- status )
    RABBIT-SERVER-CLOSE ;

: RABBIT-SERVER-CANCEL  ( server -- status )
    _RSERVERP-BUSY @ IF DROP RSERVER-S-STATE EXIT THEN
    DUP RABBIT-SERVER-VALID? 0= IF DROP RSERVER-S-INVALID EXIT THEN
    DUP _RSERVERS-S ! RSERVER.STATE @ RSERVER-ST-CANCELLED = IF
        RSERVER-S-CANCELLED EXIT
    THEN
    _RSERVERS-S @ _RSERVER-BUILDER-RESET DROP
    _RSERVERS-S @ RSERVER.CONNECTION @ RABBIT-CONNECTION-CANCEL
        DUP _RSERVERL-RS !
    DUP RCONN-S-CANCELLED = SWAP RCONN-S-OK = OR IF
        RSERVER-ST-CANCELLED _RSERVERS-S @ RSERVER.STATE !
        RSERVER-S-CANCELLED RSERVER-DETAIL-NONE 0 _RSERVERS-S @
            _RSERVER-STATUS! EXIT
    THEN
    RSERVER-ST-FAILED _RSERVERS-S @ RSERVER.STATE !
    RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION _RSERVERL-RS @
        _RSERVERS-S @ _RSERVER-STATUS! ;

\ =====================================================================
\  Held-frame dispatch scratch and release paths
\ =====================================================================

VARIABLE _RSERVERP-S
VARIABLE _RSERVERP-C
VARIABLE _RSERVERP-R
VARIABLE _RSERVERP-B
VARIABLE _RSERVERP-F
VARIABLE _RSERVERP-KIND
VARIABLE _RSERVERP-LANE
VARIABLE _RSERVERP-SEQ
VARIABLE _RSERVERP-EXPECTED
VARIABLE _RSERVERP-DISPOSITION
VARIABLE _RSERVERP-RS
VARIABLE _RSERVERP-MSGS
VARIABLE _RSERVERP-PRESENT
VARIABLE _RSERVERP-TA
VARIABLE _RSERVERP-TU
VARIABLE _RSERVERP-VERB-A
VARIABLE _RSERVERP-VERB-U
VARIABLE _RSERVERP-TARGET-A
VARIABLE _RSERVERP-TARGET-U
VARIABLE _RSERVERP-CAPS
VARIABLE _RSERVERP-HANDLER-XT
VARIABLE _RSERVERP-HANDLER-CONTEXT
VARIABLE _RSERVERP-OUTCOME
VARIABLE _RSERVERP-THROW
VARIABLE _RSERVERP-ADMIT-DECISION
VARIABLE _RSERVERP-PEER-TOKEN
VARIABLE _RSERVERP-CODE
VARIABLE _RSERVERP-SEMANTIC-STATUS
VARIABLE _RSERVERP-CONTROL-COUNT
VARIABLE _RSERVERP-DATA-COUNT

: _RSERVER-NO-ITEM  ( status -- item status )
    RSERVER-ITEM-NONE SWAP ;

: _RSERVER-CLEAR-LOAN-SCRATCH  ( -- )
    0 _RSERVERP-F !
    0 _RSERVERP-TA ! 0 _RSERVERP-TU !
    0 _RSERVERP-VERB-A ! 0 _RSERVERP-VERB-U !
    0 _RSERVERP-TARGET-A ! 0 _RSERVERP-TARGET-U !
    0 _RSERVERP-HANDLER-XT ! 0 _RSERVERP-HANDLER-CONTEXT ! ;

: _RSERVER-RX-LOAN  ( -- server-status )
    _RSERVERP-C @ RABBIT-CONNECTION-RX-LOAN
    _RSERVERP-RS ! _RSERVERP-DISPOSITION ! _RSERVERP-EXPECTED !
    _RSERVERP-SEQ ! _RSERVERP-LANE ! _RSERVERP-KIND ! _RSERVERP-F !
    _RSERVERP-RS @ IF RSERVER-S-CONNECTION ELSE RSERVER-S-OK THEN ;

: _RSERVER-DROP-LOAN  ( -- connection-status )
    _RSERVERP-C @ RABBIT-CONNECTION-RX-DROP _RSERVERP-RS !
    _RSERVER-CLEAR-LOAN-SCRATCH _RSERVERP-RS @ ;

: _RSERVER-COMMIT-LOAN  ( -- connection-status )
    _RSERVERP-C @ RABBIT-CONNECTION-RX-COMMIT _RSERVERP-RS !
    _RSERVER-CLEAR-LOAN-SCRATCH _RSERVERP-RS @ ;

: _RSERVER-FAIL-CONNECTION
  ( server-status detail-domain detail -- item status )
    >R >R >R
    _RSERVERP-B @ RMSGB-VALID? IF
        _RSERVERP-B @ RMSGB-RESET DROP
    THEN
    _RSERVERP-C @ RABBIT-CONNECTION-CANCEL
        _RSERVERP-S @ RSERVER.CLEANUP-STATUS !
    RSERVER-ST-FAILED _RSERVERP-S @ RSERVER.STATE !
    R> R> R> _RSERVERP-S @ _RSERVER-STATUS! _RSERVER-NO-ITEM ;

: _RSERVER-ABORT-LOAN
  ( server-status detail-domain detail -- item status )
    >R >R >R
    _RSERVER-DROP-LOAN _RSERVERP-S @ RSERVER.CLEANUP-STATUS !
    R> R> R> _RSERVER-FAIL-CONNECTION ;

: _RSERVER-REJECT-HELLO
  ( server-status detail-domain detail -- item status )
    >R >R >R
    _RSERVER-DROP-LOAN _RSERVERP-S @ RSERVER.CLEANUP-STATUS !
    _RSERVERP-C @ RABBIT-CONNECTION-CANCEL
        _RSERVERP-S @ RSERVER.CLEANUP-STATUS !
    RSERVER-ST-CANCELLED _RSERVERP-S @ RSERVER.STATE !
    R> R> R> _RSERVERP-S @ _RSERVER-STATUS!
    RSERVER-ITEM-REFUSAL SWAP ;

\ =====================================================================
\  Builder and correlation helpers
\ =====================================================================

: _RSERVER-REQUEST-FIELDS  ( -- message-status )
    _RSERVERP-F @ RMSG-LANE@
    _RSERVERP-MSGS ! _RSERVERP-PRESENT ! _RSERVERP-LANE !
    _RSERVERP-MSGS @ IF _RSERVERP-MSGS @ EXIT THEN
    _RSERVERP-PRESENT @ 0= IF RMSG-S-REQUIRED EXIT THEN
    _RSERVERP-F @ RMSG-TXN$
    _RSERVERP-MSGS ! _RSERVERP-PRESENT !
    _RSERVERP-TU ! _RSERVERP-TA !
    _RSERVERP-MSGS @ IF _RSERVERP-MSGS @ EXIT THEN
    _RSERVERP-PRESENT @ 0= IF RMSG-S-REQUIRED EXIT THEN
    _RSERVERP-F @ RBF-VERB$ _RSERVERP-VERB-U ! _RSERVERP-VERB-A !
    _RSERVERP-F @ RBF-ARGS$ _RSERVERP-TARGET-U ! _RSERVERP-TARGET-A !
    RMSG-S-OK ;

: _RSERVER-RESET-BUILDER  ( -- server-status )
    _RSERVERP-B @ RMSGB-VALID? 0= IF RSERVER-S-BUILDER EXIT THEN
    _RSERVERP-B @ RMSGB-RESET
    RMSGB-S-OK = IF RSERVER-S-OK ELSE RSERVER-S-BUILDER THEN ;

: _RSERVER-BEGIN-RESPONSE  ( code label-a label-u -- server-status )
    _RSERVERP-B @ >R
    _RSERVERP-TU @ >R _RSERVERP-TA @ >R _RSERVERP-LANE @ >R
    R> R> R> R> RMSGB-BEGIN-RESPONSE
    RMSGB-S-OK <> IF RSERVER-S-BUILDER EXIT THEN
    _RSERVERP-B @ RMSGB-SEAL
    RMSGB-S-OK = IF RSERVER-S-OK ELSE RSERVER-S-BUILDER THEN ;

: _RSERVER-SYNTHESIZE
  ( code label-a label-u -- server-status )
    _RSERVER-RESET-BUILDER DUP IF
        >R DROP 2DROP R> EXIT
    THEN DROP
    _RSERVER-BEGIN-RESPONSE ;

: _RSERVER-PREFLIGHT-FAILURE  ( -- server-status )
    500 S" HANDLER FAILED" _RSERVER-SYNTHESIZE ?DUP IF EXIT THEN
    _RSERVER-RESET-BUILDER ;

VARIABLE _RSERVERVC-F
VARIABLE _RSERVERVC-A
VARIABLE _RSERVERVC-U

: _RSERVER-RESPONSE-CORRELATED?  ( -- flag )
    _RSERVERP-B @ RMSGB-READY-FRAME@ DUP 0= IF DROP 0 EXIT THEN
    DUP _RSERVERVC-F ! RMSG-KIND@
    DUP IF 2DROP 0 EXIT THEN
    DROP RMSG-KIND-RESPONSE <> IF 0 EXIT THEN
    _RSERVERVC-F @ RMSG-LANE@
    _RSERVERP-MSGS ! _RSERVERP-PRESENT !
    _RSERVERP-MSGS @ IF DROP 0 EXIT THEN
    _RSERVERP-PRESENT @ 0= IF DROP 0 EXIT THEN
    _RSERVERP-LANE @ <> IF 0 EXIT THEN
    _RSERVERVC-F @ RMSG-TXN$
    _RSERVERP-MSGS ! _RSERVERP-PRESENT !
    _RSERVERVC-U ! _RSERVERVC-A !
    _RSERVERP-MSGS @ IF 0 EXIT THEN
    _RSERVERP-PRESENT @ 0= IF 0 EXIT THEN
    _RSERVERVC-U @ _RSERVERP-TU @ <> IF 0 EXIT THEN
    _RSERVERVC-A @ _RSERVERVC-U @
        _RSERVERP-TA @ _RSERVERP-TU @ COMPARE IF 0 EXIT THEN
    _RSERVERVC-F @ RMSG-STATUS@
    _RSERVERP-MSGS ! _RSERVERP-PRESENT ! _RSERVERP-CODE !
    _RSERVERP-MSGS @ 0= _RSERVERP-PRESENT @ AND ;

: _RSERVER-PUBLISH-RESPONSE
  ( semantic-status -- item status )
    _RSERVERP-SEMANTIC-STATUS !
    _RSERVERP-B @ _RSERVERP-C @ RABBIT-CONNECTION-ENQUEUE
    _RSERVERP-RS ! DROP
    _RSERVERP-RS @ IF
        RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION _RSERVERP-RS @
            _RSERVER-ABORT-LOAN EXIT
    THEN
    _RSERVER-RESET-BUILDER DUP IF
        RSERVER-DETAIL-BUILDER RMSGB-S-STATE _RSERVER-ABORT-LOAN EXIT
    THEN DROP
    _RSERVER-COMMIT-LOAN DUP IF
        RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION ROT
            _RSERVER-FAIL-CONNECTION EXIT
    THEN DROP
    _RSERVERP-CODE @ _RSERVERP-S @ RSERVER.LAST-RESPONSE-CODE !
    _RSERVERP-SEMANTIC-STATUS @ RSERVER-DETAIL-NONE 0
        _RSERVERP-S @ _RSERVER-STATUS!
    RSERVER-ITEM-RESPONSE SWAP ;

\ =====================================================================
\  Handshake and control dispatch
\ =====================================================================

: _RSERVER-ADMIT-INNER  ( -- )
    _RSERVERP-F @ _RSERVERP-S @ RSERVER.PEER-EVIDENCE @
    _RSERVERP-S @ RSERVER.ADMIT-CONTEXT @
    _RSERVERP-S @ RSERVER.ADMIT-XT @ EXECUTE
    _RSERVERP-ADMIT-DECISION ! _RSERVERP-PEER-TOKEN ! ;

: _RSERVER-BUILD-HELLO  ( caps -- server-status )
    _RSERVER-RESET-BUILDER DUP IF NIP EXIT THEN DROP
    _RSERVERP-S @ RSERVER.BURROW-A @
    _RSERVERP-S @ RSERVER.BURROW-U @ _RSERVERP-B @
        RMSGB-BEGIN-HELLO-OK
    RMSGB-S-OK <> IF RSERVER-S-BUILDER EXIT THEN
    _RSERVERP-B @ RMSGB-SEAL
    RMSGB-S-OK <> IF RSERVER-S-BUILDER EXIT THEN
    _RSERVERP-B @ RMSGB-READY-FRAME@ DUP 0= IF
        DROP RSERVER-S-BUILDER EXIT
    THEN
    RMSG-HELLO-OK-STATUS
    RMSG-S-OK = IF RSERVER-S-OK ELSE RSERVER-S-BUILDER THEN ;

: _RSERVER-HANDSHAKE  ( -- item status )
    _RSERVERP-F @ RMSG-CAPS@
    _RSERVERP-MSGS ! _RSERVERP-PRESENT ! _RSERVERP-CAPS !
    _RSERVERP-MSGS @ IF
        RSERVER-S-MESSAGE RSERVER-DETAIL-MESSAGE _RSERVERP-MSGS @
            _RSERVER-ABORT-LOAN EXIT
    THEN
    _RSERVERP-PRESENT @ 0= IF 0 _RSERVERP-CAPS ! THEN
    _RSERVERP-CAPS @ _RSERVERP-C @ RCONN.SESSION @
        RSESS.LOCAL-CAPS @ AND _RSERVERP-CAPS !
    _RSERVERP-CAPS @ _RSERVER-BUILD-HELLO DUP IF
        RSERVER-DETAIL-BUILDER RMSGB-S-CAPACITY
            _RSERVER-ABORT-LOAN EXIT
    THEN DROP
    _RSERVER-RESET-BUILDER ?DUP IF
        RSERVER-DETAIL-BUILDER RMSGB-S-STATE _RSERVER-ABORT-LOAN EXIT
    THEN
    0 _RSERVERP-THROW !
    RSERVER-ADMIT-DENY _RSERVERP-ADMIT-DECISION !
    ['] _RSERVER-ADMIT-INNER CATCH DUP _RSERVERP-THROW ! IF
        _RSERVERP-THROW @ _RSERVERP-S @ RSERVER.CALLBACK-THROW !
        RSERVER-S-CALLBACK RSERVER-DETAIL-ADMISSION _RSERVERP-THROW @
            _RSERVER-REJECT-HELLO EXIT
    THEN
    _RSERVERP-ADMIT-DECISION @ RSERVER-ADMIT-VALID? 0= IF
        _RSERVERP-ADMIT-DECISION @
            _RSERVERP-S @ RSERVER.CALLBACK-THROW !
        RSERVER-S-CALLBACK RSERVER-DETAIL-ADMISSION
            _RSERVERP-ADMIT-DECISION @ _RSERVER-REJECT-HELLO EXIT
    THEN
    _RSERVERP-ADMIT-DECISION @ RSERVER-ADMIT-DENY = IF
        RSERVER-S-DENIED RSERVER-DETAIL-ADMISSION 0
            _RSERVER-REJECT-HELLO EXIT
    THEN
    _RSERVERP-CAPS @ _RSERVER-BUILD-HELLO DUP IF
        RSERVER-DETAIL-BUILDER RMSGB-S-CAPACITY
            _RSERVER-ABORT-LOAN EXIT
    THEN DROP
    _RSERVER-COMMIT-LOAN DUP IF
        RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION ROT
            _RSERVER-FAIL-CONNECTION EXIT
    THEN DROP
    _RSERVERP-C @ RCONN.SESSION @ RABBIT-SESSION-AGREED-CAPS@
        _RSERVERP-CAPS @ <> IF
        RSERVER-S-PROTOCOL RSERVER-DETAIL-CONNECTION RABBIT-S-CAPABILITY
            _RSERVER-FAIL-CONNECTION EXIT
    THEN
    _RSERVERP-B @ _RSERVERP-C @ RABBIT-CONNECTION-ENQUEUE
    _RSERVERP-RS ! DROP
    _RSERVERP-RS @ IF
        RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION _RSERVERP-RS @
            _RSERVER-FAIL-CONNECTION EXIT
    THEN
    _RSERVER-RESET-BUILDER DUP IF
        RSERVER-DETAIL-BUILDER RMSGB-S-STATE
            _RSERVER-FAIL-CONNECTION EXIT
    THEN DROP
    _RSERVERP-PEER-TOKEN @ _RSERVERP-S @ RSERVER.PEER-TOKEN !
    _RSERVERP-S @ RSERVER.FLAGS DUP @
        _RSERVER-F-PEER-ADMITTED _RSERVER-F-HELLO-QUEUED OR OR SWAP !
    RSERVER-S-OK RSERVER-DETAIL-NONE 0 _RSERVERP-S @ _RSERVER-STATUS!
    RSERVER-ITEM-HANDSHAKE SWAP ;

: _RSERVER-PING  ( -- item status )
    _RSERVER-RESET-BUILDER ?DUP IF
        RSERVER-DETAIL-BUILDER RMSGB-S-STATE _RSERVER-ABORT-LOAN EXIT
    THEN
    _RSERVERP-B @ RMSGB-BEGIN-PONG RMSGB-S-OK <> IF
        RSERVER-S-BUILDER RSERVER-DETAIL-BUILDER RMSGB-S-CAPACITY
            _RSERVER-ABORT-LOAN EXIT
    THEN
    _RSERVERP-B @ RMSGB-SEAL RMSGB-S-OK <> IF
        RSERVER-S-BUILDER RSERVER-DETAIL-BUILDER RMSGB-S-FRAME
            _RSERVER-ABORT-LOAN EXIT
    THEN
    _RSERVERP-B @ RMSGB-READY-FRAME@ DUP 0= IF
        DROP RSERVER-S-BUILDER RSERVER-DETAIL-BUILDER RMSGB-S-STATE
            _RSERVER-ABORT-LOAN EXIT
    THEN
    RMSG-PONG-STATUS DUP _RSERVERP-MSGS ! RMSG-S-OK <> IF
        RSERVER-S-BUILDER RSERVER-DETAIL-MESSAGE _RSERVERP-MSGS @
            _RSERVER-ABORT-LOAN EXIT
    THEN
    _RSERVERP-B @ _RSERVERP-C @ RABBIT-CONNECTION-ENQUEUE
    _RSERVERP-RS ! DROP
    _RSERVERP-RS @ IF
        RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION _RSERVERP-RS @
            _RSERVER-ABORT-LOAN EXIT
    THEN
    _RSERVER-RESET-BUILDER DUP IF
        RSERVER-DETAIL-BUILDER RMSGB-S-STATE _RSERVER-ABORT-LOAN EXIT
    THEN DROP
    _RSERVER-COMMIT-LOAN DUP IF
        RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION ROT
            _RSERVER-FAIL-CONNECTION EXIT
    THEN DROP
    RSERVER-S-OK RSERVER-DETAIL-NONE 0 _RSERVERP-S @ _RSERVER-STATUS!
    RSERVER-ITEM-CONTROL SWAP ;

: _RSERVER-CONTROL-COMMIT  ( -- item status )
    _RSERVER-COMMIT-LOAN DUP IF
        RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION ROT
            _RSERVER-FAIL-CONNECTION EXIT
    THEN DROP
    RSERVER-S-OK RSERVER-DETAIL-NONE 0 _RSERVERP-S @ _RSERVER-STATUS!
    RSERVER-ITEM-CONTROL SWAP ;

\ =====================================================================
\  Request routing and response synthesis
\ =====================================================================

: _RSERVER-HANDLER-INNER  ( -- )
    _RSERVERP-F @ _RSERVERP-KIND @
    _RSERVERP-S @ RSERVER.PEER-TOKEN @ _RSERVERP-B @
    _RSERVERP-HANDLER-CONTEXT @ _RSERVERP-HANDLER-XT @ EXECUTE
    _RSERVERP-OUTCOME ! ;

: _RSERVER-HANDLER-500  ( -- item status )
    500 _RSERVERP-CODE !
    500 S" HANDLER FAILED" _RSERVER-SYNTHESIZE DUP IF
        RSERVER-DETAIL-BUILDER RMSGB-S-STATE _RSERVER-ABORT-LOAN EXIT
    THEN DROP
    RSERVER-S-CALLBACK _RSERVER-PUBLISH-RESPONSE ;

: _RSERVER-CALL-HANDLER  ( -- item status )
    RSERVER-HANDLER-NONE _RSERVERP-OUTCOME !
    0 _RSERVERP-THROW !
    ['] _RSERVER-HANDLER-INNER CATCH DUP _RSERVERP-THROW ! IF
        _RSERVERP-THROW @ _RSERVERP-S @ RSERVER.CALLBACK-THROW !
        RSERVER-HANDLER-FAILED
            _RSERVERP-S @ RSERVER.LAST-HANDLER-OUTCOME !
        _RSERVER-HANDLER-500 EXIT
    THEN
    _RSERVERP-OUTCOME @ _RSERVERP-S @ RSERVER.LAST-HANDLER-OUTCOME !
    _RSERVERP-OUTCOME @ RSERVER-HANDLER-VALID? 0= IF
        _RSERVERP-OUTCOME @ _RSERVERP-S @ RSERVER.CALLBACK-THROW !
        RSERVER-HANDLER-FAILED
            _RSERVERP-S @ RSERVER.LAST-HANDLER-OUTCOME !
        _RSERVER-HANDLER-500 EXIT
    THEN
    _RSERVERP-OUTCOME @ RSERVER-HANDLER-RESPONSE = IF
        _RSERVER-RESPONSE-CORRELATED? 0= IF
            _RSERVER-HANDLER-500 EXIT
        THEN
        RSERVER-S-OK _RSERVER-PUBLISH-RESPONSE EXIT
    THEN
    _RSERVERP-OUTCOME @ RSERVER-HANDLER-DENY = IF
        403 _RSERVERP-CODE !
        403 S" FORBIDDEN" _RSERVER-SYNTHESIZE DUP IF
            RSERVER-DETAIL-BUILDER RMSGB-S-STATE
                _RSERVER-ABORT-LOAN EXIT
        THEN DROP
        RSERVER-S-DENIED _RSERVER-PUBLISH-RESPONSE EXIT
    THEN
    _RSERVER-HANDLER-500 ;

: _RSERVER-ROUTE-REQUEST  ( -- item status )
    _RSERVER-REQUEST-FIELDS DUP IF
        RSERVER-S-MESSAGE RSERVER-DETAIL-MESSAGE ROT
            _RSERVER-ABORT-LOAN EXIT
    THEN DROP
    _RSERVER-PREFLIGHT-FAILURE DUP IF
        RSERVER-DETAIL-BUILDER RMSGB-S-CAPACITY
            _RSERVER-ABORT-LOAN EXIT
    THEN DROP
    _RSERVERP-VERB-A @ _RSERVERP-VERB-U @
    _RSERVERP-TARGET-A @ _RSERVERP-TARGET-U @ _RSERVERP-R @
        RROUTER-MATCH
    _RSERVERP-RS ! _RSERVERP-HANDLER-CONTEXT !
    _RSERVERP-HANDLER-XT !
    _RSERVERP-RS @ RROUTER-S-OK = IF
        _RSERVER-CALL-HANDLER EXIT
    THEN
    _RSERVERP-RS @ RROUTER-S-NOT-FOUND = IF
        404 _RSERVERP-CODE !
        404 S" NOT FOUND" _RSERVER-SYNTHESIZE DUP IF
            RSERVER-DETAIL-BUILDER RMSGB-S-STATE
                _RSERVER-ABORT-LOAN EXIT
        THEN DROP
        RSERVER-S-NOT-FOUND _RSERVER-PUBLISH-RESPONSE EXIT
    THEN
    _RSERVERP-RS @ DUP RROUTER-S-GRAMMAR =
    SWAP RROUTER-S-UTF8 = OR IF
        400 _RSERVERP-CODE !
        400 S" BAD REQUEST" _RSERVER-SYNTHESIZE DUP IF
            RSERVER-DETAIL-BUILDER RMSGB-S-STATE
                _RSERVER-ABORT-LOAN EXIT
        THEN DROP
        RSERVER-S-MESSAGE _RSERVER-PUBLISH-RESPONSE EXIT
    THEN
    RSERVER-S-ROUTER RSERVER-DETAIL-ROUTER _RSERVERP-RS @
        _RSERVER-ABORT-LOAN ;

: _RSERVER-EXTENSION  ( -- item status )
    _RSERVER-REQUEST-FIELDS DUP IF
        RSERVER-S-PROTOCOL RSERVER-DETAIL-MESSAGE ROT
            _RSERVER-ABORT-LOAN EXIT
    THEN DROP
    _RSERVERP-TARGET-U @ 0= IF
        RSERVER-S-PROTOCOL RSERVER-DETAIL-MESSAGE RMSG-S-REQUIRED
            _RSERVER-ABORT-LOAN EXIT
    THEN
    501 _RSERVERP-CODE !
    501 S" UNSUPPORTED" _RSERVER-SYNTHESIZE DUP IF
        RSERVER-DETAIL-BUILDER RMSGB-S-CAPACITY
            _RSERVER-ABORT-LOAN EXIT
    THEN DROP
    RSERVER-S-UNSUPPORTED _RSERVER-PUBLISH-RESPONSE ;

\ =====================================================================
\  Dispatch and cooperative poll
\ =====================================================================

: _RSERVER-QUEUE-AVAILABLE?  ( queue -- flag )
    DUP RTXQ.COUNT @ SWAP RTXQ.CAP @ U< ;

: _RSERVER-OUTPUT-AVAILABLE?  ( kind -- flag )
    DUP RMSG-KIND-ACK = OVER RMSG-KIND-CREDIT = OR IF DROP -1 EXIT THEN
    DUP RMSG-KIND-HELLO = OVER RMSG-KIND-PING = OR IF
        DROP _RSERVERP-C @ RCONN.CONTROL-Q @
            _RSERVER-QUEUE-AVAILABLE? EXIT
    THEN
    DUP RMSG-KIND-REQUEST? OVER RMSG-KIND-UNKNOWN = OR IF
        DROP _RSERVERP-C @ RCONN.HELD-LANE @ 0= IF
            _RSERVERP-C @ RCONN.CONTROL-Q @
        ELSE
            _RSERVERP-C @ RCONN.DATA-Q @
        THEN
        _RSERVER-QUEUE-AVAILABLE? EXIT
    THEN
    DROP _RSERVERP-C @ RCONN.DATA-Q @ _RSERVER-QUEUE-AVAILABLE? ;

: _RSERVER-HELLO-FLUSHED?  ( -- flag )
    _RSERVERP-S @ RSERVER.FLAGS @ _RSERVER-F-HELLO-QUEUED AND 0= IF
        -1 EXIT
    THEN
    _RSERVERP-C @ RABBIT-CONNECTION-TX-COUNTS@
    _RSERVERP-RS ! _RSERVERP-DATA-COUNT ! _RSERVERP-CONTROL-COUNT !
    _RSERVERP-RS @ IF 0 EXIT THEN
    _RSERVERP-CONTROL-COUNT @ IF 0 EXIT THEN
    _RSERVERP-S @ RSERVER.FLAGS DUP @
        _RSERVER-F-HELLO-QUEUED INVERT AND SWAP !
    -1 ;

: _RSERVER-DISPATCH-HELD  ( -- item status )
    _RSERVERP-C @ RCONN.HELD-KIND @
        _RSERVER-OUTPUT-AVAILABLE? 0= IF
        RSERVER-S-PENDING RSERVER-DETAIL-NONE 0 _RSERVERP-S @
            _RSERVER-STATUS! _RSERVER-NO-ITEM EXIT
    THEN
    _RSERVER-RX-LOAN DUP IF
        RSERVER-DETAIL-CONNECTION _RSERVERP-RS @
            _RSERVERP-S @ _RSERVER-STATUS! _RSERVER-NO-ITEM EXIT
    THEN DROP
    _RSERVERP-KIND @ RMSG-KIND-HELLO = IF
        _RSERVER-HANDSHAKE EXIT
    THEN
    _RSERVERP-S @ RSERVER.FLAGS @ _RSERVER-F-PEER-ADMITTED AND 0= IF
        RSERVER-S-PROTOCOL RSERVER-DETAIL-ADMISSION RABBIT-S-STATE
            _RSERVER-ABORT-LOAN EXIT
    THEN
    _RSERVERP-KIND @ RMSG-KIND-PING = IF _RSERVER-PING EXIT THEN
    _RSERVERP-KIND @ DUP RMSG-KIND-ACK =
    SWAP RMSG-KIND-CREDIT = OR IF _RSERVER-CONTROL-COMMIT EXIT THEN
    _RSERVERP-KIND @ RMSG-KIND-REQUEST? IF
        _RSERVER-ROUTE-REQUEST EXIT
    THEN
    _RSERVERP-KIND @ RMSG-KIND-UNKNOWN = IF
        _RSERVER-EXTENSION EXIT
    THEN
    RSERVER-S-PROTOCOL RSERVER-DETAIL-MESSAGE _RSERVERP-KIND @
        _RSERVER-ABORT-LOAN ;

: _RSERVER-DISPATCH-INNER  ( server -- item status )
    DUP _RSERVERP-S !
    DUP RABBIT-SERVER-VALID? 0= IF
        DROP RSERVER-ITEM-NONE RSERVER-S-INVALID EXIT
    THEN
    RSERVER.STATE @ RSERVER-ST-ACTIVE <> IF
        RSERVER-S-STATE RSERVER-DETAIL-NONE 0 _RSERVERP-S @
            _RSERVER-STATUS! _RSERVER-NO-ITEM EXIT
    THEN
    _RSERVERP-S @ RSERVER.CONNECTION @ _RSERVERP-C !
    _RSERVERP-S @ RSERVER.ROUTER @ _RSERVERP-R !
    _RSERVERP-S @ RSERVER.BUILDER @ _RSERVERP-B !
    _RSERVER-HELLO-FLUSHED? 0= IF
        RSERVER-S-PENDING RSERVER-DETAIL-NONE 0 _RSERVERP-S @
            _RSERVER-STATUS! _RSERVER-NO-ITEM EXIT
    THEN
    _RSERVERP-C @ RABBIT-CONNECTION-RX-READY? 0= IF
        RSERVER-S-PENDING RSERVER-DETAIL-NONE 0 _RSERVERP-S @
            _RSERVER-STATUS! _RSERVER-NO-ITEM EXIT
    THEN
    _RSERVER-DISPATCH-HELD ;

: _RSERVER-POLL-CONNECTION-ERROR  ( connection-status -- item status )
    DUP RCONN-S-CANCELLED = IF
        DROP RSERVER-ST-CANCELLED _RSERVERP-S @ RSERVER.STATE !
        RSERVER-S-CANCELLED RSERVER-DETAIL-CONNECTION RCONN-S-CANCELLED
            _RSERVERP-S @ _RSERVER-STATUS! _RSERVER-NO-ITEM EXIT
    THEN
    RCONN-S-EOF = IF
        RSERVER-ST-CLOSED _RSERVERP-S @ RSERVER.STATE !
        RSERVER-S-EOF RSERVER-DETAIL-CONNECTION RCONN-S-EOF
            _RSERVERP-S @ _RSERVER-STATUS! _RSERVER-NO-ITEM EXIT
    THEN
    RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION _RSERVERP-RS @
        _RSERVER-FAIL-CONNECTION ;

: _RSERVER-POLL-INNER  ( server -- item status )
    DUP _RSERVERP-S !
    DUP RABBIT-SERVER-VALID? 0= IF
        DROP RSERVER-ITEM-NONE RSERVER-S-INVALID EXIT
    THEN
    RSERVER.STATE @ RSERVER-ST-ACTIVE <> IF
        RSERVER-S-STATE RSERVER-DETAIL-NONE 0 _RSERVERP-S @
            _RSERVER-STATUS! _RSERVER-NO-ITEM EXIT
    THEN
    _RSERVERP-S @ RSERVER.CONNECTION @ _RSERVERP-C !
    _RSERVERP-S @ RSERVER.ROUTER @ _RSERVERP-R !
    _RSERVERP-S @ RSERVER.BUILDER @ _RSERVERP-B !
    _RSERVERP-C @ RABBIT-CONNECTION-PUMP DUP _RSERVERP-RS !
    DUP RCONN-S-OK = OVER RCONN-S-PENDING = OR
    OVER RCONN-S-RX-READY = OR 0= IF
        DROP _RSERVERP-RS @ _RSERVER-POLL-CONNECTION-ERROR EXIT
    THEN DROP
    _RSERVER-HELLO-FLUSHED? 0= IF
        RSERVER-S-PENDING RSERVER-DETAIL-NONE 0 _RSERVERP-S @
            _RSERVER-STATUS! _RSERVER-NO-ITEM EXIT
    THEN
    _RSERVERP-C @ RABBIT-CONNECTION-RX-READY? IF
        _RSERVER-DISPATCH-HELD EXIT
    THEN
    RSERVER-S-PENDING RSERVER-DETAIL-NONE 0 _RSERVERP-S @
        _RSERVER-STATUS! _RSERVER-NO-ITEM ;

: RABBIT-SERVER-DISPATCH  ( server -- item status )
    _RSERVERP-BUSY @ IF
        DROP RSERVER-ITEM-NONE RSERVER-S-STATE EXIT
    THEN
    -1 _RSERVERP-BUSY !
    _RSERVER-DISPATCH-INNER
    0 _RSERVERP-BUSY ! ;

: RABBIT-SERVER-POLL  ( server -- item status )
    _RSERVERP-BUSY @ IF
        DROP RSERVER-ITEM-NONE RSERVER-S-STATE EXIT
    THEN
    -1 _RSERVERP-BUSY !
    _RSERVER-POLL-INNER
    0 _RSERVERP-BUSY ! ;

\ =====================================================================
\  Recovering finalization
\ =====================================================================

VARIABLE _RSERVERF-S
VARIABLE _RSERVERF-BA
VARIABLE _RSERVERF-BCAP
VARIABLE _RSERVERF-B

: _RSERVER-CLEAR-SCRATCH  ( -- )
    0 _RSERVERG-A ! 0 _RSERVERG-U ! 0 _RSERVERG-R !
    0 _RSERVERG-B ! 0 _RSERVERG-C !
    0 _RSERVERV-S !
    0 _RSERVERI-CONN ! 0 _RSERVERI-ROUTER ! 0 _RSERVERI-BUILDER !
    0 _RSERVERI-SA ! 0 _RSERVERI-SU ! 0 _RSERVERI-BA !
    0 _RSERVERI-BCAP ! 0 _RSERVERI-EVIDENCE ! 0 _RSERVERI-AXT !
    0 _RSERVERI-ACTX ! 0 _RSERVERI-S ! 0 _RSERVERS-S !
    0 _RSERVERL-RS !
    0 _RSERVERP-BUSY !
    0 _RSERVERP-S ! 0 _RSERVERP-C ! 0 _RSERVERP-R ! 0 _RSERVERP-B !
    _RSERVER-CLEAR-LOAN-SCRATCH
    0 _RSERVERP-KIND ! 0 _RSERVERP-LANE ! 0 _RSERVERP-SEQ !
    0 _RSERVERP-EXPECTED ! 0 _RSERVERP-DISPOSITION ! 0 _RSERVERP-RS !
    0 _RSERVERP-MSGS ! 0 _RSERVERP-PRESENT ! 0 _RSERVERP-CAPS !
    0 _RSERVERP-HANDLER-XT ! 0 _RSERVERP-HANDLER-CONTEXT !
    0 _RSERVERP-OUTCOME ! 0 _RSERVERP-THROW !
    0 _RSERVERP-ADMIT-DECISION ! 0 _RSERVERP-PEER-TOKEN !
    0 _RSERVERP-CODE ! 0 _RSERVERP-SEMANTIC-STATUS !
    0 _RSERVERP-CONTROL-COUNT ! 0 _RSERVERP-DATA-COUNT !
    0 _RSERVERVC-F ! 0 _RSERVERVC-A ! 0 _RSERVERVC-U ! ;

: RABBIT-SERVER-FINI  ( server -- status )
    _RSERVERP-BUSY @ IF DROP RSERVER-S-STATE EXIT THEN
    DUP RABBIT-SERVER-VALID? 0= IF DROP RSERVER-S-INVALID EXIT THEN
    DUP _RSERVERF-S !
    DUP RSERVER.BURROW-A @ _RSERVERF-BA !
    DUP RSERVER.BURROW-CAP @ _RSERVERF-BCAP !
    DUP RSERVER.BUILDER @ _RSERVERF-B !
    RSERVER.CONNECTION @ RABBIT-CONNECTION-FINI DUP _RSERVERL-RS !
    DUP RCONN-S-PENDING = IF
        DROP RSERVER-ST-CLOSING _RSERVERF-S @ RSERVER.STATE !
        RSERVER-S-PENDING RSERVER-DETAIL-NONE 0 _RSERVERF-S @
            _RSERVER-STATUS! EXIT
    THEN
    IF
        RSERVER-ST-FAILED _RSERVERF-S @ RSERVER.STATE !
        RSERVER-S-CONNECTION RSERVER-DETAIL-CONNECTION _RSERVERL-RS @
            _RSERVERF-S @ _RSERVER-STATUS! EXIT
    THEN
    _RSERVERF-B @ RMSGB-FINI DUP IF
        RSERVER-ST-FAILED _RSERVERF-S @ RSERVER.STATE !
        RSERVER-S-BUILDER RSERVER-DETAIL-BUILDER ROT _RSERVERF-S @
            _RSERVER-STATUS! EXIT
    THEN DROP
    _RSERVERF-BA @ _RSERVERF-BCAP @ 0 FILL
    _RSERVERF-S @ RABBIT-SERVER-SIZE 0 FILL
    _RSERVER-CLEAR-SCRATCH
    0 _RSERVERF-S ! 0 _RSERVERF-BA ! 0 _RSERVERF-BCAP ! 0 _RSERVERF-B !
    RSERVER-S-OK ;
