\ =====================================================================
\  runtime.f - Provider-neutral conversation and run orchestration
\ =====================================================================

PROVIDED akashic-agent-runtime

REQUIRE provider.f
REQUIRE conversation.f
REQUIRE conversation-store.f
REQUIRE tool-gateway.f
REQUIRE access-profile.f
REQUIRE ../utils/fmt.f

0 CONSTANT ARUN-S-IDLE
1 CONSTANT ARUN-S-RUNNING
2 CONSTANT ARUN-S-APPROVAL
3 CONSTANT ARUN-S-OFFLINE
4 CONSTANT ARUN-S-ERROR
5 CONSTANT ARUN-S-CANCELLED
6 CONSTANT ARUN-S-EXPIRED

1 CONSTANT ARUNTIME-F-EXPIRED
2 CONSTANT ARUNTIME-F-TERMINATING
4 CONSTANT ARUNTIME-F-DROP-RUN

  0 CONSTANT _AR-PROVIDER
  8 CONSTANT _AR-EVENTS
 16 CONSTANT _AR-CONVERSATION
 24 CONSTANT _AR-NEXT-RUN
 32 CONSTANT _AR-ACTIVE-RUN
 40 CONSTANT _AR-STATUS
 48 CONSTANT _AR-ASSISTANT-MSG
 56 CONSTANT _AR-APPROVAL-MSG
 64 CONSTANT _AR-REVISION
72 CONSTANT _AR-LAST-EVENT
80 CONSTANT _AR-FLAGS
88 CONSTANT _AR-TOOL-GATEWAY
96 CONSTANT _AR-ACCESS-PROFILE
_AR-ACCESS-PROFILE AGENT-ACCESS-PROFILE-SIZE + CONSTANT _AR-DISCLOSURE-CONTEXT
_AR-DISCLOSURE-CONTEXT 8 + CONSTANT _AR-LAST-DISCLOSURE-ITEMS
_AR-LAST-DISCLOSURE-ITEMS 8 + CONSTANT _AR-LAST-DISCLOSURE-BYTES
_AR-LAST-DISCLOSURE-BYTES 8 + CONSTANT _AR-LAST-REMOTE-MS
_AR-LAST-REMOTE-MS 8 + CONSTANT _AR-LAST-REMOTE-RUN
_AR-LAST-REMOTE-RUN 8 + CONSTANT _AR-EVENT-SCRATCH
_AR-EVENT-SCRATCH AGENT-EVENT-SIZE + CONSTANT _AR-TURN-REQUEST
_AR-TURN-REQUEST AGENT-TURN-REQUEST-SIZE + CONSTANT _AR-CONVERSATION-STORE
_AR-CONVERSATION-STORE 8 + CONSTANT _AR-PERSISTED-REVISION
_AR-PERSISTED-REVISION 8 + CONSTANT _AR-LAST-PERSIST-MS
_AR-LAST-PERSIST-MS 8 + CONSTANT _AR-STORE-STATUS
_AR-STORE-STATUS 8 + CONSTANT _AR-MANDATE-FACTORY-XT
_AR-MANDATE-FACTORY-XT 8 + CONSTANT _AR-MANDATE-FACTORY-DATA
_AR-MANDATE-FACTORY-DATA 8 + CONSTANT _AR-MANDATE-RUN
_AR-MANDATE-RUN 8 + CONSTANT AGENT-RUNTIME-SIZE

: ARUNTIME.PROVIDER       ( runtime -- a ) _AR-PROVIDER + ;
: ARUNTIME.EVENTS         ( runtime -- a ) _AR-EVENTS + ;
: ARUNTIME.CONVERSATION   ( runtime -- a ) _AR-CONVERSATION + ;
: ARUNTIME.NEXT-RUN       ( runtime -- a ) _AR-NEXT-RUN + ;
: ARUNTIME.ACTIVE-RUN     ( runtime -- a ) _AR-ACTIVE-RUN + ;
: ARUNTIME.STATUS         ( runtime -- a ) _AR-STATUS + ;
: ARUNTIME.ASSISTANT-MSG  ( runtime -- a ) _AR-ASSISTANT-MSG + ;
: ARUNTIME.APPROVAL-MSG   ( runtime -- a ) _AR-APPROVAL-MSG + ;
: ARUNTIME.REVISION       ( runtime -- a ) _AR-REVISION + ;
: ARUNTIME.LAST-EVENT     ( runtime -- a ) _AR-LAST-EVENT + ;
: ARUNTIME.FLAGS          ( runtime -- a ) _AR-FLAGS + ;
: ARUNTIME.TOOL-GATEWAY   ( runtime -- a ) _AR-TOOL-GATEWAY + ;
: ARUNTIME.EVENT-SCRATCH  ( runtime -- event ) _AR-EVENT-SCRATCH + ;
: ARUNTIME.TURN-REQUEST   ( runtime -- turn ) _AR-TURN-REQUEST + ;
: ARUNTIME.CONVERSATION-STORE ( runtime -- a ) _AR-CONVERSATION-STORE + ;
: ARUNTIME.PERSISTED-REVISION ( runtime -- a ) _AR-PERSISTED-REVISION + ;
: ARUNTIME.LAST-PERSIST-MS ( runtime -- a ) _AR-LAST-PERSIST-MS + ;
: ARUNTIME.STORE-STATUS   ( runtime -- a ) _AR-STORE-STATUS + ;
: ARUNTIME.MANDATE-FACTORY-XT ( runtime -- a ) _AR-MANDATE-FACTORY-XT + ;
: ARUNTIME.MANDATE-FACTORY-DATA ( runtime -- a ) _AR-MANDATE-FACTORY-DATA + ;
: ARUNTIME.MANDATE-RUN    ( runtime -- a ) _AR-MANDATE-RUN + ;
: ARUNTIME.ACCESS-PROFILE ( runtime -- profile ) _AR-ACCESS-PROFILE + ;
: ARUNTIME.DISCLOSURE-CONTEXT ( runtime -- a ) _AR-DISCLOSURE-CONTEXT + ;
: ARUNTIME.LAST-DISCLOSURE-ITEMS ( runtime -- a ) _AR-LAST-DISCLOSURE-ITEMS + ;
: ARUNTIME.LAST-DISCLOSURE-BYTES ( runtime -- a ) _AR-LAST-DISCLOSURE-BYTES + ;
: ARUNTIME.LAST-REMOTE-MS ( runtime -- a ) _AR-LAST-REMOTE-MS + ;
: ARUNTIME.LAST-REMOTE-RUN ( runtime -- a ) _AR-LAST-REMOTE-RUN + ;

: ARUNTIME-MODEL-CONTEXT  ( runtime -- context )
    ARUNTIME.CONVERSATION @ ACONV.MODEL-CONTEXT @ ;

: ARUNTIME-RUN-SETTINGS  ( runtime -- settings | 0 )
    ARUNTIME.PROVIDER @ APROV-RUN-SETTINGS ;

: ARUNTIME-ACCESS-PROFILE  ( runtime -- profile | 0 )
    ARUNTIME.ACCESS-PROFILE DUP AAP-VALID? 0= IF DROP 0 THEN ;

: ARUNTIME-ACCESS-SCOPE$  ( runtime -- addr len )
    ARUNTIME-ACCESS-PROFILE ?DUP IF AAP-LABEL$ ELSE S" Unscoped" THEN ;

: ARUNTIME-ACTIVE-FACET  ( runtime -- facet | 0 )
    ARUNTIME.MANDATE-RUN @ ?DUP IF AMRUN.FACET THEN ;

: ARUNTIME-SCOPE-AVAILABLE?  ( runtime -- flag )
    DUP ARUNTIME.MANDATE-FACTORY-XT @ 0<>
    SWAP ARUNTIME.TOOL-GATEWAY @ 0<> AND ;

: ARUNTIME-LAST-DISCLOSURE-ITEMS  ( runtime -- count )
    ARUNTIME.LAST-DISCLOSURE-ITEMS @ ;

: ARUNTIME-LAST-DISCLOSURE-BYTES  ( runtime -- bytes )
    ARUNTIME.LAST-DISCLOSURE-BYTES @ ;

: ARUNTIME-REMOTE-VERIFIED?  ( runtime -- flag )
    ARUNTIME.LAST-REMOTE-RUN @ 0<> ;

: _ARUNTIME-ACCESS-IDLE?  ( runtime -- flag )
    DUP ARUNTIME.ACTIVE-RUN @ IF DROP 0 EXIT THEN
    DUP ARUNTIME.MANDATE-RUN @ IF DROP 0 EXIT THEN
    ARUNTIME.STATUS @ DUP ARUN-S-RUNNING <>
    SWAP ARUN-S-APPROVAL <> AND ;

VARIABLE _ARAPP-PRESET
VARIABLE _ARAPP-R

: ARUNTIME-ACCESS-PRESET!  ( preset runtime -- status )
    _ARAPP-R ! _ARAPP-PRESET !
    _ARAPP-R @ _ARUNTIME-ACCESS-IDLE? 0= IF AAP-S-BUSY EXIT THEN
    _ARAPP-R @ ARUNTIME-SCOPE-AVAILABLE? 0= IF
        AAP-S-UNAVAILABLE EXIT
    THEN
    _ARAPP-PRESET @ _ARAPP-R @ ARUNTIME.ACCESS-PROFILE AAP-PRESET!
    DUP IF EXIT THEN
    _ARAPP-R @ ARUNTIME.DISCLOSURE-CONTEXT @ ?DUP IF ACTX-CLEAR THEN
    0 _ARAPP-R @ ARUNTIME.LAST-DISCLOSURE-ITEMS !
    0 _ARAPP-R @ ARUNTIME.LAST-DISCLOSURE-BYTES !
    1 _ARAPP-R @ ARUNTIME.REVISION +! ;

: ARUNTIME-TOOL-GATEWAY!  ( gateway runtime -- )
    ARUNTIME.TOOL-GATEWAY ! ;

: ARUNTIME-MANDATE-FACTORY!  ( xt data runtime -- )
    >R
    R@ ARUNTIME.MANDATE-FACTORY-DATA !
    R> ARUNTIME.MANDATE-FACTORY-XT ! ;

VARIABLE _ARM-R
VARIABLE _ARM-RUN
VARIABLE _ARM-STATUS

: _ARUNTIME-MANDATE-END  ( runtime -- status )
    DUP _ARM-R ! ARUNTIME.MANDATE-RUN @ DUP 0= IF
        DROP CBUS-S-OK EXIT
    THEN
    _ARM-RUN !
    _ARM-R @ ARUNTIME.TOOL-GATEWAY @ ?DUP IF
        DUP ATOOLG.STATE @ ATOOLG-S-COMPLETE = IF
            DUP ATOOLG-CLEAR DROP
        THEN
        DUP ATOOLG.STATE @ ATOOLG-S-IDLE <> IF
            DROP CBUS-S-BUSY EXIT
        THEN
        ATOOLG-MANDATE-CLEAR DROP
    THEN
    _ARM-RUN @ AMRUN-CLOSE
    _ARM-RUN @ AMRUN-FREE
    0 _ARM-R @ ARUNTIME.MANDATE-RUN !
    CBUS-S-OK ;

VARIABLE _ARMP-RUN-ID
VARIABLE _ARMP-R
VARIABLE _ARMP-AMRUN

: _ARUNTIME-MANDATE-PREPARE  ( run-id runtime -- status )
    _ARMP-R ! _ARMP-RUN-ID !
    _ARMP-R @ _ARUNTIME-MANDATE-END ?DUP IF EXIT THEN
    _ARMP-R @ ARUNTIME.MANDATE-FACTORY-XT @ DUP 0= IF
        DROP
        _ARMP-R @ ARUNTIME-ACCESS-PROFILE IF
            CBUS-S-DENIED
        ELSE
            CBUS-S-OK
        THEN EXIT
    THEN
    >R _ARMP-RUN-ID @ _ARMP-R @ ARUNTIME.MANDATE-FACTORY-DATA @
        R> EXECUTE
    _ARM-STATUS !
    _ARM-STATUS @ IF
        ?DUP IF AMRUN-FREE THEN _ARM-STATUS @ EXIT
    THEN
    DUP 0= IF DROP CBUS-S-DENIED EXIT THEN
    DUP _ARMP-AMRUN !
    DUP AMRUN-ACTIVE? 0= IF AMRUN-FREE CBUS-S-INVALID EXIT THEN
    DROP
    _ARMP-R @ ARUNTIME.TOOL-GATEWAY @ DUP 0= IF
        DROP _ARMP-AMRUN @ AMRUN-FREE CBUS-S-NO-HANDLER EXIT
    THEN
    _ARMP-AMRUN @ SWAP ATOOLG-MANDATE! DUP IF
        _ARMP-AMRUN @ AMRUN-FREE EXIT
    THEN DROP
    _ARMP-AMRUN @ _ARMP-R @ ARUNTIME.MANDATE-RUN !
    CBUS-S-OK ;

VARIABLE _ARN-RUNTIME
VARIABLE _ARN-PROVIDER
VARIABLE _ARN-EVENTS
VARIABLE _ARN-CONV
VARIABLE _ARN-DISCLOSURE

VARIABLE _ARPC-R
VARIABLE _ARPC-SETTINGS
VARIABLE _ARPC-STATUS

: _ARUNTIME-CONNECT-PROVIDER  ( runtime -- status )
    DUP _ARPC-R ! ARUNTIME.EVENTS @
    _ARPC-R @ ARUNTIME.PROVIDER @ APROV-CONNECT
    DUP IF ARUN-S-ERROR ELSE ARUN-S-OFFLINE THEN
    _ARPC-R @ ARUNTIME.STATUS ! ;

: _ARUNTIME-REFRESH-SETTINGS  ( runtime -- status )
    DUP _ARPC-R ! ARUNTIME-RUN-SETTINGS DUP 0= IF
        DROP ARSET-S-UNSUPPORTED EXIT
    THEN
    DUP _ARPC-SETTINGS ! ARSET-REFRESH DUP _ARPC-STATUS !
    DUP ARSET-S-PENDING = IF
        ARUN-S-OFFLINE _ARPC-R @ ARUNTIME.STATUS ! EXIT
    THEN
    DUP ARSET-S-OK = IF
        DROP _ARPC-SETTINGS @ ARSET.STATE @ ARSET-STATE-READY = IF
            _ARPC-R @ _ARUNTIME-CONNECT-PROVIDER DROP ARSET-S-OK
        ELSE
            ARUN-S-ERROR _ARPC-R @ ARUNTIME.STATUS ! ARSET-S-PROTOCOL
        THEN
        EXIT
    THEN
    ARUN-S-ERROR _ARPC-R @ ARUNTIME.STATUS ! ;

: _ARUNTIME-INITIAL-PROVIDER  ( runtime -- )
    DUP _ARPC-R ! ARUNTIME-RUN-SETTINGS DUP 0= IF
        DROP _ARPC-R @ _ARUNTIME-CONNECT-PROVIDER DROP EXIT
    THEN
    DUP _ARPC-SETTINGS ! ARSET.STATE @ ARSET-STATE-READY = IF
        _ARPC-R @ _ARUNTIME-CONNECT-PROVIDER DROP EXIT
    THEN
    _ARPC-R @ ARUNTIME.PROVIDER @ APROV-AUTH DUP IF
        AAUTH-READY? 0= IF ARUN-S-OFFLINE _ARPC-R @ ARUNTIME.STATUS ! EXIT THEN
    ELSE
        DROP
    THEN
    _ARPC-R @ _ARUNTIME-REFRESH-SETTINGS DROP ;

: _ARUNTIME-NEW-CLEANUP  ( -- )
    _ARN-CONV @ ?DUP IF ACONV-FREE THEN
    _ARN-DISCLOSURE @ ?DUP IF ACTX-FREE THEN
    _ARN-EVENTS @ ?DUP IF AEQ-FREE THEN
    _ARN-RUNTIME @ ?DUP IF FREE THEN
    0 _ARN-CONV ! 0 _ARN-DISCLOSURE ! 0 _ARN-EVENTS ! 0 _ARN-RUNTIME ! ;

: ARUNTIME-NEW  ( provider -- runtime ior )
    _ARN-PROVIDER ! 0 _ARN-RUNTIME ! 0 _ARN-EVENTS ! 0 _ARN-CONV !
    0 _ARN-DISCLOSURE !
    AGENT-RUNTIME-SIZE ALLOCATE DUP IF SWAP DROP 0 SWAP EXIT THEN
    DROP DUP _ARN-RUNTIME ! AGENT-RUNTIME-SIZE 0 FILL
    AEQ-NEW DUP IF 2DROP _ARUNTIME-NEW-CLEANUP 0 1 EXIT THEN
    DROP _ARN-EVENTS !
    ACONV-NEW DUP IF 2DROP _ARUNTIME-NEW-CLEANUP 0 1 EXIT THEN
    DROP _ARN-CONV !
    ACTX-NEW DUP IF 2DROP _ARUNTIME-NEW-CLEANUP 0 1 EXIT THEN
    DROP _ARN-DISCLOSURE !
    _ARN-PROVIDER @ _ARN-RUNTIME @ ARUNTIME.PROVIDER !
    _ARN-EVENTS @ _ARN-RUNTIME @ ARUNTIME.EVENTS !
    _ARN-CONV @ _ARN-RUNTIME @ ARUNTIME.CONVERSATION !
    _ARN-DISCLOSURE @ _ARN-RUNTIME @ ARUNTIME.DISCLOSURE-CONTEXT !
    1 _ARN-RUNTIME @ ARUNTIME.NEXT-RUN !
    1 _ARN-RUNTIME @ ARUNTIME.REVISION !
    ARUN-S-OFFLINE _ARN-RUNTIME @ ARUNTIME.STATUS !
    _ARN-RUNTIME @ _ARUNTIME-INITIAL-PROVIDER
    _ARN-RUNTIME @ 0 ;

VARIABLE _ARPS-R
VARIABLE _ARPS-STATUS

: ARUNTIME-PERSIST-FORCE  ( runtime -- status )
    DUP _ARPS-R ! ARUNTIME.CONVERSATION-STORE @ DUP 0= IF
        DROP ACSTORE-S-OK EXIT
    THEN
    _ARPS-R @ ARUNTIME.STORE-STATUS @ ACSTORE-S-INVALID = IF
        DROP ACSTORE-S-INVALID EXIT
    THEN
    _ARPS-R @ ARUNTIME.CONVERSATION @ SWAP ACSTORE-SAVE
    DUP _ARPS-STATUS ! _ARPS-R @ ARUNTIME.STORE-STATUS !
    _ARPS-STATUS @ ACSTORE-S-OK = IF
        _ARPS-R @ ARUNTIME.CONVERSATION @ ACONV.REVISION @
        _ARPS-R @ ARUNTIME.PERSISTED-REVISION !
        MS@ _ARPS-R @ ARUNTIME.LAST-PERSIST-MS !
    THEN
    _ARPS-STATUS @ ;

500 CONSTANT ARUNTIME-PERSIST-INTERVAL-MS

: ARUNTIME-PERSIST  ( runtime -- status )
    DUP _ARPS-R ! ARUNTIME.CONVERSATION-STORE @ 0= IF
        ACSTORE-S-OK EXIT
    THEN
    _ARPS-R @ ARUNTIME.CONVERSATION @ ACONV.REVISION @
    _ARPS-R @ ARUNTIME.PERSISTED-REVISION @ = IF ACSTORE-S-OK EXIT THEN
    _ARPS-R @ ARUNTIME.STATUS @ ARUN-S-RUNNING =
    _ARPS-R @ ARUNTIME.LAST-PERSIST-MS @ 0<> AND IF
        MS@ _ARPS-R @ ARUNTIME.LAST-PERSIST-MS @ -
        ARUNTIME-PERSIST-INTERVAL-MS < IF ACSTORE-S-OK EXIT THEN
    THEN
    _ARPS-R @ ARUNTIME-PERSIST-FORCE ;

VARIABLE _ARBS-STORE
VARIABLE _ARBS-R
VARIABLE _ARBS-CONV
VARIABLE _ARBS-STATUS
VARIABLE _ARBS-MAX-RUN

: _ARUNTIME-RESET-TRANSIENT  ( runtime -- )
    DUP _ARBS-R !
    0 OVER ARUNTIME.ASSISTANT-MSG !
    0 OVER ARUNTIME.APPROVAL-MSG !
    0 OVER ARUNTIME.ACTIVE-RUN !
    0 SWAP ARUNTIME.CONVERSATION @ ACONV.ACTIVE-RUN !
    0 _ARBS-MAX-RUN !
    _ARBS-R @ ARUNTIME.CONVERSATION @ DUP ACONV.COUNT @ 0 ?DO
        I OVER ACONV-NTH AMSG.RUN-ID @ _ARBS-MAX-RUN @ MAX
        _ARBS-MAX-RUN !
    LOOP
    DROP _ARBS-MAX-RUN @ 1+ 1 MAX _ARBS-R @ ARUNTIME.NEXT-RUN ! ;

: ARUNTIME-CONVERSATION-STORE!  ( store runtime -- status )
    _ARBS-R ! _ARBS-STORE !
    _ARBS-R @ ARUNTIME.CONVERSATION-STORE @ ?DUP IF ACSTORE-FREE THEN
    _ARBS-STORE @ _ARBS-R @ ARUNTIME.CONVERSATION-STORE !
    0 _ARBS-R @ ARUNTIME.PERSISTED-REVISION !
    0 _ARBS-R @ ARUNTIME.LAST-PERSIST-MS !
    ACSTORE-S-OK _ARBS-R @ ARUNTIME.STORE-STATUS !
    _ARBS-STORE @ ACSTORE-LOAD
    _ARBS-STATUS ! _ARBS-CONV !
    _ARBS-STATUS @ ACSTORE-S-NOT-FOUND = IF
        ACSTORE-S-OK _ARBS-R @ ARUNTIME.STORE-STATUS !
        _ARBS-R @ ARUNTIME-PERSIST-FORCE EXIT
    THEN
    _ARBS-STATUS @ ACSTORE-S-OK <> IF
        _ARBS-STATUS @ _ARBS-R @ ARUNTIME.STORE-STATUS !
        _ARBS-R @ ARUNTIME.CONVERSATION @ ACONV.REVISION @
        _ARBS-R @ ARUNTIME.PERSISTED-REVISION !
        _ARBS-STATUS @ EXIT
    THEN
    _ARBS-R @ ARUNTIME.CONVERSATION @ ACONV-FREE
    _ARBS-CONV @ _ARBS-R @ ARUNTIME.CONVERSATION !
    _ARBS-R @ _ARUNTIME-RESET-TRANSIENT
    1 _ARBS-R @ ARUNTIME.REVISION +!
    ACSTORE-S-OK _ARBS-R @ ARUNTIME.STORE-STATUS !
    _ARBS-R @ ARUNTIME-PERSIST-FORCE ;

VARIABLE _ARS-A
VARIABLE _ARS-U
VARIABLE _ARS-R
VARIABLE _ARS-RUN
VARIABLE _ARS-MSG
VARIABLE _ARS-STATUS
VARIABLE _ARS-CONTEXT
VARIABLE _ARS-TURN
VARIABLE _ARS-MANDATE-RUN
VARIABLE _ARBT-A
VARIABLE _ARBT-U
VARIABLE _ARBT-RUN
VARIABLE _ARBT-R
VARIABLE _ARBT-TURN-CONTEXT

VARIABLE _ARHU-RUN
VARIABLE _ARHU-I
VARIABLE _ARHU-C

: _AR-HISTORY-USER-INDEX  ( run-id before-index conversation -- index|-1 )
    _ARHU-C ! _ARHU-I ! _ARHU-RUN !
    BEGIN _ARHU-I @ 0> WHILE
        -1 _ARHU-I +!
        _ARHU-I @ _ARHU-C @ ACONV-NTH
        DUP AMSG.RUN-ID @ _ARHU-RUN @ =
        OVER AMSG.ROLE @ AROLE-USER = AND
        OVER AMSG.STATE @ AMSG-S-COMPLETE = AND
        SWAP AMSG.FLAGS @ AMSG-F-TOOL AMSG-F-AUDIT OR AND 0= AND IF
            _ARHU-I @ EXIT
        THEN
    REPEAT
    -1 ;

VARIABLE _ARHA-RUN
VARIABLE _ARHA-I
VARIABLE _ARHA-C

: _AR-HISTORY-ASSIST-INDEX  ( run-id conversation -- index|-1 )
    DUP _ARHA-C ! ACONV.COUNT @ _ARHA-I ! _ARHA-RUN !
    BEGIN _ARHA-I @ 0> WHILE
        -1 _ARHA-I +!
        _ARHA-I @ _ARHA-C @ ACONV-NTH
        DUP AMSG.RUN-ID @ _ARHA-RUN @ =
        OVER AMSG.ROLE @ AROLE-ASSISTANT = AND
        OVER AMSG.STATE @ AMSG-S-COMPLETE = AND
        SWAP AMSG.FLAGS @ AMSG-F-TOOL AMSG-F-AUDIT OR AND 0= AND IF
            _ARHA-I @ EXIT
        THEN
    REPEAT
    -1 ;

VARIABLE _ARHE-I
VARIABLE _ARHE-C
VARIABLE _ARHE-RUN
VARIABLE _ARHE-AI

: _AR-HISTORY-ELIGIBLE?  ( index conversation -- flag )
    _ARHE-C ! DUP _ARHE-I ! _ARHE-C @ ACONV-NTH
    DUP AMSG.STATE @ AMSG-S-COMPLETE <> IF DROP 0 EXIT THEN
    DUP AMSG.FLAGS @ AMSG-F-TOOL AMSG-F-AUDIT OR AND IF DROP 0 EXIT THEN
    DUP AMSG.RUN-ID @ _ARHE-RUN ! AMSG.ROLE @
    DUP AROLE-USER = IF
        DROP _ARHE-RUN @ _ARHE-C @ _AR-HISTORY-ASSIST-INDEX
        DUP _ARHE-AI ! 0< IF 0 EXIT THEN
        _ARHE-RUN @ _ARHE-AI @ _ARHE-C @ _AR-HISTORY-USER-INDEX
        _ARHE-I @ = EXIT
    THEN
    AROLE-ASSISTANT <> IF 0 EXIT THEN
    _ARHE-RUN @ _ARHE-C @ _AR-HISTORY-ASSIST-INDEX _ARHE-I @ <> IF
        0 EXIT
    THEN
    _ARHE-RUN @ _ARHE-I @ _ARHE-C @ _AR-HISTORY-USER-INDEX 0>= ;

VARIABLE _ARHB-R
VARIABLE _ARHB-P
VARIABLE _ARHB-C
VARIABLE _ARHB-X
VARIABLE _ARHB-I
VARIABLE _ARHB-N
VARIABLE _ARHB-BYTES
VARIABLE _ARHB-PAIR-BYTES
VARIABLE _ARHB-USER-I
VARIABLE _ARHB-KEEP
VARIABLE _ARHB-M
VARIABLE _ARHB-STATUS
VARIABLE _ARHB-PAIRS
VARIABLE _ARHB-J
32 CONSTANT _ARHB-MAX-PAIRS
CREATE _ARHB-USERS _ARHB-MAX-PAIRS CELLS ALLOT
CREATE _ARHB-ASSISTS _ARHB-MAX-PAIRS CELLS ALLOT

: _ARHB-USER!  ( index pair -- ) CELLS _ARHB-USERS + ! ;
: _ARHB-USER@  ( pair -- index ) CELLS _ARHB-USERS + @ ;
: _ARHB-ASSIST!  ( index pair -- ) CELLS _ARHB-ASSISTS + ! ;
: _ARHB-ASSIST@  ( pair -- index ) CELLS _ARHB-ASSISTS + @ ;

: _ARHB-COPY-INDEX  ( index -- )
    _ARHB-C @ ACONV-NTH DUP _ARHB-M !
    DUP AMSG.ROLE @ OVER AMSG.RUN-ID @ ROT AMSG-TEXT
    _ARHB-X @ ACTX-APPEND-MESSAGE _ARHB-STATUS ! DROP ;

\ Build a provider-facing snapshot from the visible transcript rather than
\ exposing the mixed model ledger.  Only complete prior user/assistant turns
\ survive; tool calls, tool results, provider state, audits, failed runs, and
\ the current prompt are excluded.  Selection proceeds newest-first under
\ both item and byte caps.  A completed run's user/assistant pair is selected
\ atomically into an explicit index list, then copied chronologically for
\ provider use.  No contiguous transcript suffix is trusted.
: _ARUNTIME-BUILD-HISTORY  ( runtime -- bytes status )
    DUP _ARHB-R ! ARUNTIME.DISCLOSURE-CONTEXT @ DUP _ARHB-X ! ACTX-CLEAR
    0 _ARHB-R @ ARUNTIME.LAST-DISCLOSURE-ITEMS !
    0 _ARHB-R @ ARUNTIME.LAST-DISCLOSURE-BYTES !
    _ARHB-R @ ARUNTIME-ACCESS-PROFILE DUP _ARHB-P ! 0= IF
        0 ACTX-S-OK EXIT
    THEN
    _ARHB-P @ AAP.FLAGS @ AAP-F-CHAT-HISTORY AND 0= IF
        0 ACTX-S-OK EXIT
    THEN
    _ARHB-R @ ARUNTIME.CONVERSATION @ DUP _ARHB-C !
    ACONV.COUNT @ _ARHB-I !
    0 _ARHB-N ! 0 _ARHB-PAIRS ! 0 _ARHB-BYTES ! -1 _ARHB-KEEP !
    BEGIN _ARHB-I @ 0> _ARHB-KEEP @ AND WHILE
        -1 _ARHB-I +!
        _ARHB-I @ _ARHB-C @ ACONV-NTH _ARHB-M !
        _ARHB-I @ _ARHB-C @ _AR-HISTORY-ELIGIBLE?
        _ARHB-M @ AMSG.ROLE @ AROLE-ASSISTANT = AND IF
            _ARHB-M @ AMSG.RUN-ID @ _ARHB-I @ _ARHB-C @
                _AR-HISTORY-USER-INDEX DUP _ARHB-USER-I ! 0>= IF
                _ARHB-USER-I @ _ARHB-C @ ACONV-NTH AMSG-TEXT NIP
                _ARHB-M @ AMSG-TEXT NIP + _ARHB-PAIR-BYTES !
                _ARHB-N @ 2 + _ARHB-P @ AAP.HISTORY-ITEMS @ >
                _ARHB-BYTES @ _ARHB-PAIR-BYTES @ +
                    _ARHB-P @ AAP.HISTORY-BYTES @ > OR IF
                    0 _ARHB-KEEP !
                ELSE
                    _ARHB-USER-I @ _ARHB-PAIRS @ _ARHB-USER!
                    _ARHB-I @ _ARHB-PAIRS @ _ARHB-ASSIST!
                    1 _ARHB-PAIRS +!
                    2 _ARHB-N +!
                    _ARHB-PAIR-BYTES @ _ARHB-BYTES +!
                    _ARHB-USER-I @ _ARHB-I !
                THEN
            THEN
        THEN
    REPEAT
    ACTX-S-OK _ARHB-STATUS !
    _ARHB-PAIRS @ _ARHB-J !
    BEGIN _ARHB-J @ 0> _ARHB-STATUS @ 0= AND WHILE
        -1 _ARHB-J +!
        _ARHB-J @ _ARHB-USER@ _ARHB-COPY-INDEX
        _ARHB-STATUS @ 0= IF
            _ARHB-J @ _ARHB-ASSIST@ _ARHB-COPY-INDEX
        THEN
    REPEAT
    _ARHB-STATUS @ IF
        _ARHB-X @ ACTX-CLEAR
        0 _ARHB-R @ ARUNTIME.LAST-DISCLOSURE-ITEMS !
        0 _ARHB-R @ ARUNTIME.LAST-DISCLOSURE-BYTES !
        0 _ARHB-STATUS @ EXIT
    THEN
    _ARHB-X @ ACTX.COUNT @ _ARHB-R @ ARUNTIME.LAST-DISCLOSURE-ITEMS !
    _ARHB-BYTES @ _ARHB-R @ ARUNTIME.LAST-DISCLOSURE-BYTES !
    _ARHB-BYTES @ ACTX-S-OK ;

: _ARUNTIME-PREPARE-TURN  ( prompt-a prompt-u run-id runtime -- turn )
    _ARBT-R ! _ARBT-RUN ! _ARBT-U ! _ARBT-A !
    _ARBT-R @ ARUNTIME.TURN-REQUEST DUP _ARS-TURN ! ATURN-INIT
    _ARBT-R @ ARUNTIME.CONVERSATION @ DUP ACONV.ID @ _ARS-TURN @ ATURN.THREAD-ID !
    ACONV.MODEL-CONTEXT @ DUP _ARS-CONTEXT ! DUP _ARBT-TURN-CONTEXT !
    _ARBT-R @ ARUNTIME.MANDATE-RUN @ IF
        DROP
        _ARBT-R @ ARUNTIME.DISCLOSURE-CONTEXT @
            DUP _ARBT-TURN-CONTEXT !
        DUP ACTX.COUNT @ _ARS-TURN @ ATURN.CONTEXT-N !
        ATURN-F-SCOPED-HISTORY _ARS-TURN @ ATURN.FLAGS !
    ELSE
        DUP ACTX.COUNT @ _ARS-TURN @ ATURN.CONTEXT-N !
    THEN
    DROP
    _ARBT-TURN-CONTEXT @ DUP ACTX.REVISION @
        _ARS-TURN @ ATURN.CONTEXT-REVISION !
    _ARS-TURN @ ATURN.CONTEXT !
    _ARBT-R @ ARUNTIME.TOOL-GATEWAY @ _ARS-TURN @ ATURN.TOOL-GATEWAY !
    _ARBT-RUN @ _ARS-TURN @ ATURN.RUN-ID !
    _ARBT-A @ _ARS-TURN @ ATURN.PROMPT-A !
    _ARBT-U @ _ARS-TURN @ ATURN.PROMPT-U !
    _ARBT-R @ ARUNTIME.MANDATE-RUN @ ?DUP IF
        AMRUN.MANDATE MAND.TOKEN-BUDGET @ _ARS-TURN @ ATURN.MAX-OUTPUT !
    THEN
    _ARS-TURN @ ;

: ARUNTIME-SEND  ( prompt-a prompt-u runtime -- ior )
    _ARS-R ! _ARS-U ! _ARS-A !
    _ARS-U @ 0= IF 1 EXIT THEN
    _ARS-R @ ARUNTIME-RUN-SETTINGS ?DUP IF
        ARSET.STATE @ ARSET-STATE-READY <> IF 4 EXIT THEN
    THEN
    _ARS-R @ ARUNTIME.ACTIVE-RUN @ IF 2 EXIT THEN
    _ARS-R @ ARUNTIME.STATUS @ DUP ARUN-S-RUNNING =
    SWAP ARUN-S-APPROVAL = OR IF 2 EXIT THEN
    2 _ARS-R @ ARUNTIME.CONVERSATION @ ACONV-ROOM? 0= IF 3 EXIT THEN
    _ARS-R @ ARUNTIME-MODEL-CONTEXT ACTX.COUNT @
    ACTX-MAX-ITEMS 2 - > IF 3 EXIT THEN
    0 _ARS-R @ ARUNTIME.ASSISTANT-MSG !
    0 _ARS-R @ ARUNTIME.APPROVAL-MSG !
    _ARS-R @ ARUNTIME.NEXT-RUN @ _ARS-RUN !
    0 _ARS-R @ ARUNTIME.FLAGS !
    _ARS-RUN @ _ARS-R @ _ARUNTIME-MANDATE-PREPARE ?DUP IF EXIT THEN
    _ARS-R @ ARUNTIME.MANDATE-RUN @ DUP IF
        _ARS-MANDATE-RUN !
        _ARS-R @ _ARUNTIME-BUILD-HISTORY
        _ARS-STATUS ! _ARS-CONTEXT !
        _ARS-STATUS @ IF
            _ARS-R @ _ARUNTIME-MANDATE-END DROP _ARS-STATUS @ EXIT
        THEN
        _ARS-CONTEXT @ _ARS-U @ + _ARS-MANDATE-RUN @
            AMRUN-DISCLOSE-BYTES ?DUP IF
            _ARS-R @ _ARUNTIME-MANDATE-END DROP EXIT
        THEN
    ELSE
        DROP
    THEN
    0 _ARS-R @ ARUNTIME.LAST-REMOTE-RUN !
    0 _ARS-R @ ARUNTIME.LAST-REMOTE-MS !
    1 _ARS-R @ ARUNTIME.NEXT-RUN +!
    AROLE-USER AMSG-S-COMPLETE _ARS-RUN @ _ARS-A @ _ARS-U @
    _ARS-R @ ARUNTIME.CONVERSATION @ ACONV-APPEND
    DUP IF
        NIP _ARS-STATUS ! _ARS-R @ _ARUNTIME-MANDATE-END DROP
        _ARS-STATUS @ EXIT
    THEN 2DROP
    AROLE-ASSISTANT AMSG-S-STREAMING _ARS-RUN @ 0 0
    _ARS-R @ ARUNTIME.CONVERSATION @ ACONV-APPEND
    DUP IF
        NIP _ARS-STATUS !
        _ARS-R @ ARUNTIME.CONVERSATION @ ACONV-DROP-LAST
        _ARS-R @ _ARUNTIME-MANDATE-END DROP
        _ARS-STATUS @ EXIT
    THEN DROP _ARS-MSG !
    _ARS-MSG @ _ARS-R @ ARUNTIME.ASSISTANT-MSG !
    _ARS-RUN @ _ARS-R @ ARUNTIME.ACTIVE-RUN !
    ARUN-S-RUNNING _ARS-R @ ARUNTIME.STATUS !
    _ARS-RUN @ _ARS-R @ ARUNTIME.CONVERSATION @ ACONV.ACTIVE-RUN !
    1 _ARS-R @ ARUNTIME.REVISION +!
    _ARS-A @ _ARS-U @ _ARS-RUN @ _ARS-R @ _ARUNTIME-PREPARE-TURN DROP
    AROLE-USER _ARS-RUN @ _ARS-A @ _ARS-U @ _ARS-CONTEXT @
    ACTX-APPEND-MESSAGE _ARS-STATUS ! DROP
    _ARS-STATUS @ IF
        ARUN-S-ERROR _ARS-R @ ARUNTIME.STATUS !
        AMSG-S-ERROR _ARS-MSG @ AMSG.STATE !
        0 _ARS-R @ ARUNTIME.ACTIVE-RUN !
        0 _ARS-R @ ARUNTIME.CONVERSATION @ ACONV.ACTIVE-RUN !
        _ARS-R @ ARUNTIME-PERSIST-FORCE DROP
        _ARS-R @ _ARUNTIME-MANDATE-END DROP
        _ARS-STATUS @ EXIT
    THEN
    _ARS-TURN @ _ARS-R @ ARUNTIME.EVENTS @
    _ARS-R @ ARUNTIME.PROVIDER @ APROV-START
    DUP _ARS-STATUS ! IF
        _ARS-CONTEXT @ ACTX-DROP-LAST
        ARUN-S-ERROR _ARS-R @ ARUNTIME.STATUS !
        AMSG-S-ERROR _ARS-MSG @ AMSG.STATE !
        0 _ARS-R @ ARUNTIME.ACTIVE-RUN !
        0 _ARS-R @ ARUNTIME.CONVERSATION @ ACONV.ACTIVE-RUN !
        _ARS-R @ _ARUNTIME-MANDATE-END DROP
    THEN
    _ARS-R @ ARUNTIME-PERSIST-FORCE DROP
    _ARS-STATUS @ ;

VARIABLE _ARH-R
VARIABLE _ARH-E
VARIABLE _ARH-MSG
VARIABLE _ARH-ROLE
VARIABLE _ARH-STATE
VARIABLE _ARH-A
VARIABLE _ARH-U

: _AR-PROVIDER-ID  ( runtime -- addr len )
    ARUNTIME.PROVIDER @ DUP APROV.ID-A @ SWAP APROV.ID-U @ ;

: _AR-EVENT-TEXT  ( event -- addr len flag )
    AEV.DATA DUP CV-TYPE@ CV-T-STRING = IF
        DUP CV-DATA@ SWAP CV-LEN@ -1
    ELSE
        DROP 0 0 0
    THEN ;

: _AR-APPEND-EVENT-MESSAGE  ( role state event runtime -- message | 0 )
    _ARH-R ! _ARH-E ! _ARH-STATE ! _ARH-ROLE !
    _ARH-E @ _AR-EVENT-TEXT IF
        _ARH-U ! _ARH-A !
        _ARH-ROLE @ _ARH-STATE @ _ARH-E @ AEV.RUN-ID @
        _ARH-A @ _ARH-U @
        _ARH-R @ ARUNTIME.CONVERSATION @ ACONV-APPEND
        DUP IF
            2DROP 0
        ELSE
            DROP _ARH-ROLE @ AROLE-TOOL = IF
                AMSG-F-TOOL OVER AMSG.FLAGS !
            THEN
        THEN
    ELSE
        2DROP 0
    THEN ;

VARIABLE _ART-E
VARIABLE _ART-R
VARIABLE _ART-M
VARIABLE _ART-A
VARIABLE _ART-U
VARIABLE _ART-STATUS

: _AR-EVENT-NAME  ( event -- addr len flag )
    AEV.NAME DUP CV-TYPE@ CV-T-STRING = IF
        DUP CV-DATA@ SWAP CV-LEN@ -1
    ELSE
        DROP 0 0 0
    THEN ;

: _AR-EVENT-CALL-ID  ( event -- addr len flag )
    AEV.CALL-ID DUP CV-TYPE@ CV-T-STRING = IF
        DUP CV-DATA@ SWAP CV-LEN@ DUP 0<> IF -1 EXIT THEN
        2DROP 0 0 0
    ELSE
        DROP 0 0 0
    THEN ;

: _AR-APPEND-TOOL-CALL  ( event runtime -- message | 0 )
    _ART-R ! _ART-E !
    _ART-E @ _AR-EVENT-NAME IF
        _ART-U ! _ART-A !
    ELSE
        2DROP S" unnamed.tool" _ART-U ! _ART-A !
    THEN
    AROLE-TOOL AMSG-S-PENDING _ART-E @ AEV.RUN-ID @
    _ART-A @ _ART-U @ _ART-R @ ARUNTIME.CONVERSATION @ ACONV-APPEND
    DUP IF 2DROP 0 EXIT THEN
    DROP _ART-M !
    AMSG-F-TOOL _ART-M @ AMSG.FLAGS !
    S" : " _ART-M @ AMSG-APPEND ?DUP IF
        _ART-R @ ARUNTIME.CONVERSATION @ ACONV-DROP-LAST
        DROP 0 EXIT
    THEN
    _ART-E @ _AR-EVENT-TEXT IF
        _ART-M @ AMSG-APPEND ?DUP IF
            _ART-R @ ARUNTIME.CONVERSATION @ ACONV-DROP-LAST
            DROP 0 EXIT
        THEN
    ELSE
        2DROP
    THEN
    _ART-M @ ;

VARIABLE _ARMC-E
VARIABLE _ARMC-M
VARIABLE _ARMC-A
VARIABLE _ARMC-U

: _AR-MESSAGE-CALL-ID+  ( event message -- status )
    _ARMC-M ! _ARMC-E !
    _ARMC-M @ 0= IF ACTX-S-INVALID EXIT THEN
    _ARMC-E @ AEV.CALL-ID DUP CV-TYPE@ DUP 0= IF
        2DROP ACTX-S-OK EXIT
    THEN
    CV-T-STRING <> IF DROP ACTX-S-INVALID EXIT THEN
    DUP CV-DATA@ SWAP CV-LEN@ DUP 0= IF
        2DROP ACTX-S-OK EXIT
    THEN
    _ARMC-U ! _ARMC-A !
    S"  [call " _ARMC-M @ AMSG-APPEND ?DUP IF EXIT THEN
    _ARMC-A @ _ARMC-U @ _ARMC-M @ AMSG-APPEND ?DUP IF EXIT THEN
    S" ]" _ARMC-M @ AMSG-APPEND ;

VARIABLE _ARCT-E
VARIABLE _ARCT-R
VARIABLE _ARCT-NA
VARIABLE _ARCT-NU
VARIABLE _ARCT-CA
VARIABLE _ARCT-CU

: _AR-CONTEXT-TOOL-CALL  ( event runtime -- status )
    _ARCT-R ! _ARCT-E !
    _ARCT-E @ _AR-EVENT-NAME 0= IF 2DROP ACTX-S-INVALID EXIT THEN
    _ARCT-NU ! _ARCT-NA !
    _ARCT-E @ AEV.CALL-ID DUP CV-TYPE@ CV-T-STRING <> IF
        DROP ACTX-S-INVALID EXIT
    THEN
    DUP CV-DATA@ SWAP CV-LEN@ DUP 0= IF 2DROP ACTX-S-INVALID EXIT THEN
    _ARCT-CU ! _ARCT-CA !
    _ARCT-E @ AEV.RUN-ID @
    _ARCT-R @ _AR-PROVIDER-ID
    _ARCT-NA @ _ARCT-NU @ _ARCT-CA @ _ARCT-CU @
    _ARCT-E @ AEV.DATA _ARCT-R @ ARUNTIME-MODEL-CONTEXT
    ACTX-APPEND-TOOL-CALL-VALUE NIP ;

VARIABLE _ARCP-E
VARIABLE _ARCP-R
VARIABLE _ARCP-NA
VARIABLE _ARCP-NU
VARIABLE _ARCP-DA
VARIABLE _ARCP-DU

: _AR-CONTEXT-PROVIDER-ITEM  ( event runtime -- status )
    _ARCP-R ! _ARCP-E !
    _ARCP-E @ AEV.DATA DUP CV-TYPE@ CV-T-STRING <> IF
        DROP ACTX-S-INVALID EXIT
    THEN
    DUP CV-DATA@ SWAP CV-LEN@ _ARCP-DU ! _ARCP-DA !
    _ARCP-E @ AEV.NAME DUP CV-TYPE@ CV-T-STRING = IF
        DUP CV-DATA@ SWAP CV-LEN@ _ARCP-NU ! _ARCP-NA !
    ELSE
        DROP 0 _ARCP-NA ! 0 _ARCP-NU !
    THEN
    _ARCP-E @ AEV.RUN-ID @ _ARCP-R @ _AR-PROVIDER-ID
    _ARCP-NA @ _ARCP-NU @ _ARCP-DA @ _ARCP-DU @
    _ARCP-R @ ARUNTIME-MODEL-CONTEXT ACTX-APPEND-PROVIDER NIP ;

VARIABLE _ARCA-R
VARIABLE _ARCA-M

: _AR-CONTEXT-ASSISTANT  ( runtime -- status )
    DUP _ARCA-R ! ARUNTIME.ASSISTANT-MSG @ DUP 0= IF
        DROP ACTX-S-INVALID EXIT
    THEN
    DUP _ARCA-M ! AMSG-TEXT
    AROLE-ASSISTANT _ARCA-M @ AMSG.RUN-ID @ 2SWAP
    _ARCA-R @ ARUNTIME-MODEL-CONTEXT ACTX-APPEND-MESSAGE NIP ;

VARIABLE _ARTR-RUN
VARIABLE _ARTR-NA
VARIABLE _ARTR-NU
VARIABLE _ARTR-V
VARIABLE _ARTR-STATUS
VARIABLE _ARTR-R
VARIABLE _ARTR-CALL
VARIABLE _ARTR-SA
VARIABLE _ARTR-SU
VARIABLE _ARTR-CA
VARIABLE _ARTR-CU

: _AR-CONTEXT-TOOL-RESULT  ( run-id name-a name-u value status runtime -- status )
    _ARTR-R ! _ARTR-STATUS ! _ARTR-V ! _ARTR-NU ! _ARTR-NA ! _ARTR-RUN !
    _ARTR-RUN @ _ARTR-NA @ _ARTR-NU @
    _ARTR-R @ ARUNTIME-MODEL-CONTEXT ACTX-LAST-TOOL-CALL
    DUP 0= IF DROP ACTX-S-INVALID EXIT THEN
    DUP _ARTR-CALL ! ACTXI-SOURCE-TEXT _ARTR-SU ! _ARTR-SA !
    _ARTR-CALL @ ACTXI-CALL-ID-TEXT _ARTR-CU ! _ARTR-CA !
    _ARTR-RUN @ _ARTR-SA @ _ARTR-SU @ _ARTR-NA @ _ARTR-NU @
    _ARTR-CA @ _ARTR-CU @ _ARTR-V @ _ARTR-STATUS @
    _ARTR-R @ ARUNTIME-MODEL-CONTEXT
    ACTX-APPEND-TOOL-RESULT-VALUE NIP ;

: _AR-PROVIDER-TOOL-RESULT  ( run-id name-a name-u value status runtime -- ior )
    _ARTR-R ! _ARTR-STATUS ! _ARTR-V ! _ARTR-NU ! _ARTR-NA ! _ARTR-RUN !
    _ARTR-RUN @ _ARTR-NA @ _ARTR-NU @ _ARTR-V @ _ARTR-STATUS @ _ARTR-R @
    _AR-CONTEXT-TOOL-RESULT ?DUP IF EXIT THEN
    _ARTR-RUN @ _ARTR-NA @ _ARTR-NU @ _ARTR-V @ _ARTR-STATUS @
    _ARTR-R @ ARUNTIME.EVENTS @ _ARTR-R @ ARUNTIME.PROVIDER @
    APROV-TOOL-RESULT ;

: _AR-START-TOOL  ( event runtime -- status )
    _ART-R ! _ART-E !
    _ART-R @ ARUNTIME.TOOL-GATEWAY @ 0= IF
        CBUS-S-NO-HANDLER EXIT
    THEN
    _ART-E @ _AR-EVENT-NAME 0= IF
        2DROP CBUS-S-INVALID EXIT
    THEN
    _ART-E @ AEV.DATA
    _ART-E @ AEV.RUN-ID @
    _ART-E @ _AR-EVENT-CALL-ID 0= IF
        2DROP _ART-R @ ARUNTIME.TOOL-GATEWAY @ ATOOLG-CALL EXIT
    THEN
    _ART-R @ ARUNTIME.TOOL-GATEWAY @ ATOOLG-CALL-WITH-ID ;

VARIABLE _ARMR-E
VARIABLE _ARMR-R
VARIABLE _ARMR-RUN

: _AR-MARK-REMOTE-RUN  ( event runtime -- )
    _ARMR-R ! _ARMR-E !
    _ARMR-R @ ARUNTIME.PROVIDER @ APROV.FLAGS @ APROV-PF-REMOTE AND
        0= IF EXIT THEN
    _ARMR-E @ AEV.RUN-ID @ DUP _ARMR-RUN ! 0= IF EXIT THEN
    _ARMR-RUN @ _ARMR-R @ ARUNTIME.ACTIVE-RUN @ <> IF EXIT THEN
    _ARMR-RUN @ _ARMR-R @ ARUNTIME.LAST-REMOTE-RUN !
    MS@ _ARMR-R @ ARUNTIME.LAST-REMOTE-MS ! ;

VARIABLE _ARAE-E
VARIABLE _ARAE-R
VARIABLE _ARAE-KIND

VARIABLE _ARTM-R
VARIABLE _ARTM-RUN
VARIABLE _ARTM-STATUS
VARIABLE _ARTM-DROP
VARIABLE _ARMS-R
VARIABLE _ARMS-M

: _AR-ACTIVE-MESSAGE?  ( message runtime -- flag )
    _ARMS-R ! DUP _ARMS-M ! 0= IF 0 EXIT THEN
    _ARMS-R @ ARUNTIME.ACTIVE-RUN @ DUP 0= IF DROP 0 EXIT THEN
    _ARMS-M @ AMSG.RUN-ID @ = ;

: _AR-ASSISTANT-STATE!  ( state runtime -- )
    DUP _ARMS-R ! ARUNTIME.ASSISTANT-MSG @ DUP _ARMS-M !
    _ARMS-R @ _AR-ACTIVE-MESSAGE? IF
        _ARMS-M @ AMSG.STATE !
    ELSE
        DROP
    THEN ;

: _AR-APPROVAL-STATE!  ( state runtime -- )
    DUP _ARMS-R ! ARUNTIME.APPROVAL-MSG @ DUP _ARMS-M !
    _ARMS-R @ _AR-ACTIVE-MESSAGE? IF
        _ARMS-M @ AMSG.STATE !
    ELSE
        DROP
    THEN ;

: _AR-TERMINAL-MESSAGE-STATE!  ( status runtime -- )
    _ARTM-R !
    DUP ARUN-S-ERROR = IF
        DROP AMSG-S-ERROR
    ELSE
        DUP ARUN-S-CANCELLED = OVER ARUN-S-EXPIRED = OR IF
            DROP AMSG-S-CANCELLED
        ELSE
            DROP EXIT
        THEN
    THEN
    DUP _ARTM-R @ _AR-ASSISTANT-STATE!
    _ARTM-R @ _AR-APPROVAL-STATE! ;

: _AR-GATEWAY-PENDING?  ( runtime -- flag )
    ARUNTIME.TOOL-GATEWAY @ ?DUP IF
        ATOOLG.STATE @ ATOOLG-S-IDLE <>
    ELSE
        0
    THEN ;

\ Complete a terminal transition only after outstanding tool work is no
\ longer queued or awaiting review.  A queued cancellation remains sealed by
\ ACTIVE-RUN and the live AMRUN until the request-bus callback marks it
\ complete; no new turn or access change can race that interval.
: _AR-TERMINAL-FINISH  ( runtime -- status )
    DUP _ARTM-R ! ARUNTIME.FLAGS @ ARUNTIME-F-TERMINATING AND 0= IF
        CBUS-S-OK EXIT
    THEN
    _ARTM-R @ ARUNTIME.TOOL-GATEWAY @ ?DUP IF
        DUP ATOOLG.STATE @ DUP ATOOLG-S-QUEUED =
        SWAP ATOOLG-S-APPROVAL = OR IF
            DROP CBUS-S-BUSY EXIT
        THEN
        ATOOLG-CLEAR ?DUP IF EXIT THEN
    THEN
    _ARTM-R @ _ARUNTIME-MANDATE-END ?DUP IF EXIT THEN
    _ARTM-R @ ARUNTIME.ACTIVE-RUN @ _ARTM-RUN !
    _ARTM-R @ ARUNTIME.FLAGS @ ARUNTIME-F-DROP-RUN AND
    _ARTM-RUN @ 0<> AND IF
        _ARTM-RUN @ _ARTM-R @ ARUNTIME-MODEL-CONTEXT ACTX-DROP-RUN
    THEN
    0 _ARTM-R @ ARUNTIME.ACTIVE-RUN !
    0 _ARTM-R @ ARUNTIME.CONVERSATION @ ACONV.ACTIVE-RUN !
    0 _ARTM-R @ ARUNTIME.ASSISTANT-MSG !
    0 _ARTM-R @ ARUNTIME.APPROVAL-MSG !
    _ARTM-R @ ARUNTIME.FLAGS DUP @
        ARUNTIME-F-TERMINATING ARUNTIME-F-DROP-RUN OR INVERT AND SWAP !
    CBUS-S-OK ;

: _AR-TERMINAL-BEGIN  ( status drop-run? runtime -- status )
    _ARTM-R ! _ARTM-DROP ! _ARTM-STATUS !
    _ARTM-STATUS @ _ARTM-R @ _AR-TERMINAL-MESSAGE-STATE!
    _ARTM-R @ ARUNTIME.FLAGS DUP @ ARUNTIME-F-TERMINATING OR
    _ARTM-DROP @ IF ARUNTIME-F-DROP-RUN OR THEN SWAP !
    _ARTM-STATUS @ _ARTM-R @ ARUNTIME.STATUS !
    1 _ARTM-R @ ARUNTIME.REVISION +!
    1 _ARTM-R @ ARUNTIME.CONVERSATION @ ACONV.REVISION +!
    _ARTM-R @ ARUNTIME.TOOL-GATEWAY @ ?DUP IF
        ATOOLG-CANCEL ?DUP IF
            ARUN-S-ERROR _ARTM-R @ _AR-TERMINAL-MESSAGE-STATE!
            ARUN-S-ERROR _ARTM-R @ ARUNTIME.STATUS ! EXIT
        THEN
    THEN
    _ARTM-R @ _AR-TERMINAL-FINISH ;

VARIABLE _ARFR-R
VARIABLE _ARFR-RUN

: _AR-FAIL-RUN  ( runtime -- )
    DUP _ARFR-R ! ARUNTIME.ACTIVE-RUN @ _ARFR-RUN !
    _ARFR-RUN @ IF
        _ARFR-RUN @ _ARFR-R @ ARUNTIME.EVENTS @
        _ARFR-R @ ARUNTIME.PROVIDER @ APROV-CANCEL DROP
    THEN
    ARUN-S-ERROR -1 _ARFR-R @ _AR-TERMINAL-BEGIN DROP ;

: _AR-FAIL-TOOL  ( status event runtime -- )
    _ART-R ! _ART-E ! _ART-STATUS !
    AMSG-S-ERROR _ART-R @ _AR-APPROVAL-STATE!
    _ART-E @ _AR-EVENT-NAME IF
        _ART-U ! _ART-A !
        _ART-E @ AEV.RUN-ID @ _ART-A @ _ART-U @
        _ART-E @ AEV.DATA _ART-STATUS @ _ART-R @
        _AR-PROVIDER-TOOL-RESULT IF _ART-R @ _AR-FAIL-RUN THEN
    ELSE
        2DROP _ART-R @ _AR-FAIL-RUN
    THEN ;

: _AR-EVENT-ACCEPT?  ( event runtime -- flag )
    _ARAE-R ! DUP _ARAE-E ! AEV.KIND @ DUP _ARAE-KIND !
    \ Once local terminal processing starts, provider events can no longer
    \ change the selected terminal cause.  The gateway completion path alone
    \ releases any queued request and finishes the transition.
    _ARAE-R @ ARUNTIME.FLAGS @ ARUNTIME-F-TERMINATING AND IF
        DROP 0 EXIT
    THEN
    DUP AEV-CONNECTED = OVER AEV-DISCONNECTED = OR IF
        DROP _ARAE-E @ AEV.RUN-ID @ 0=
        _ARAE-R @ ARUNTIME.ACTIVE-RUN @ 0= AND EXIT
    THEN
    DUP AEV-RUN-STARTED < SWAP AEV-CONTEXT-ITEM > OR IF 0 EXIT THEN
    _ARAE-E @ AEV.RUN-ID @ DUP 0= IF
        DROP _ARAE-KIND @ AEV-ERROR = EXIT
    THEN
    DUP 0> SWAP _ARAE-R @ ARUNTIME.ACTIVE-RUN @ = AND
        0= IF 0 EXIT THEN
    -1 ;

: _AR-HANDLE-EVENT  ( event runtime -- )
    _ARH-R ! DUP _ARH-E !
    \ Only connection state and provider-global errors may use run id zero.
    \ All turn, text, tool, approval, context, and terminal events are bound
    \ to the one currently active positive run id.
    _ARH-E @ _ARH-R @ _AR-EVENT-ACCEPT? 0= IF DROP EXIT THEN
    DUP AEV.KIND @ _ARH-R @ ARUNTIME.LAST-EVENT !
    AEV.KIND @ CASE
        AEV-CONNECTED OF
            ARUN-S-IDLE _ARH-R @ ARUNTIME.STATUS !
        ENDOF
        AEV-DISCONNECTED OF
            ARUN-S-OFFLINE _ARH-R @ ARUNTIME.STATUS !
        ENDOF
        AEV-RUN-STARTED OF
            ARUN-S-RUNNING _ARH-R @ ARUNTIME.STATUS !
            _ARH-E @ _ARH-R @ _AR-MARK-REMOTE-RUN
        ENDOF
        AEV-TEXT-DELTA OF
            _ARH-R @ ARUNTIME.ASSISTANT-MSG @ ?DUP IF
                DUP AMSG.STATE @ AMSG-S-STREAMING <> IF
                    DROP _ARH-R @ _AR-FAIL-RUN
                ELSE
                    _ARH-E @ _AR-EVENT-TEXT IF
                        ROT AMSG-APPEND IF _ARH-R @ _AR-FAIL-RUN THEN
                    ELSE
                        2DROP DROP _ARH-R @ _AR-FAIL-RUN
                    THEN
                THEN
            ELSE
                _ARH-R @ _AR-FAIL-RUN
            THEN
        ENDOF
        AEV-MESSAGE-DONE OF
            _ARH-R @ ARUNTIME.ASSISTANT-MSG @ ?DUP IF
                DUP AMSG.STATE @ AMSG-S-STREAMING = IF
                    AMSG-S-COMPLETE OVER AMSG.STATE !
                    _ARH-R @ _AR-CONTEXT-ASSISTANT IF
                        _ARH-R @ _AR-FAIL-RUN
                    THEN
                THEN
                DROP
            ELSE
                _ARH-R @ _AR-FAIL-RUN
            THEN
        ENDOF
        AEV-TOOL-CALL OF
            3 _ARH-R @ ARUNTIME.CONVERSATION @ ACONV-ROOM? 0=
            _ARH-R @ ARUNTIME-MODEL-CONTEXT ACTX.COUNT @
                ACTX-MAX-ITEMS 3 - > OR IF
                _ARH-R @ _AR-FAIL-RUN
            ELSE
                _ARH-E @ _ARH-R @ _AR-APPEND-TOOL-CALL
                DUP 0= IF
                    DROP _ARH-R @ _AR-FAIL-RUN
                ELSE
                    DUP _ARH-R @ ARUNTIME.APPROVAL-MSG !
                    DROP
                    _ARH-E @ _ARH-R @ _AR-CONTEXT-TOOL-CALL DUP IF
                        DROP _ARH-R @ _AR-FAIL-RUN
                    ELSE
                        DROP _ARH-E @ _ARH-R @ _AR-START-TOOL DUP IF
                            _ARH-E @ _ARH-R @ _AR-FAIL-TOOL
                        ELSE
                            DROP ARUN-S-RUNNING _ARH-R @ ARUNTIME.STATUS !
                        THEN
                    THEN
                THEN
            THEN
        ENDOF
        AEV-APPROVAL OF
            2 _ARH-R @ ARUNTIME.CONVERSATION @ ACONV-ROOM? 0= IF
                _ARH-R @ _AR-FAIL-RUN
            ELSE
                AROLE-SYSTEM AMSG-S-APPROVAL _ARH-E @ _ARH-R @
                _AR-APPEND-EVENT-MESSAGE
                DUP IF
                    DUP _ARH-E @ SWAP _AR-MESSAGE-CALL-ID+ IF
                        DROP
                        _ARH-R @ ARUNTIME.CONVERSATION @ ACONV-DROP-LAST
                        _ARH-R @ _AR-FAIL-RUN
                    ELSE
                        DUP _ARH-R @ ARUNTIME.APPROVAL-MSG !
                        DROP ARUN-S-APPROVAL _ARH-R @ ARUNTIME.STATUS !
                    THEN
                ELSE
                    DROP _ARH-R @ _AR-FAIL-RUN
                THEN
            THEN
        ENDOF
        AEV-TOOL-RESULT OF
            AROLE-TOOL AMSG-S-COMPLETE _ARH-E @ _ARH-R @
            _AR-APPEND-EVENT-MESSAGE 0= IF _ARH-R @ _AR-FAIL-RUN THEN
        ENDOF
        AEV-CONTEXT-ITEM OF
            _ARH-E @ _ARH-R @ _AR-CONTEXT-PROVIDER-ITEM IF
                _ARH-R @ _AR-FAIL-RUN
            THEN
        ENDOF
        AEV-RUN-DONE OF
            \ RUN-DONE is valid only after MESSAGE-DONE committed the
            \ assistant item to model context.  Otherwise the transcript and
            \ provider context would diverge permanently.
            _ARH-R @ ARUNTIME.ASSISTANT-MSG @ ?DUP IF
                AMSG.STATE @ AMSG-S-COMPLETE <>
            ELSE
                -1
            THEN IF
                _ARH-R @ _AR-FAIL-RUN
            ELSE
                _ARH-E @ _ARH-R @ _AR-MARK-REMOTE-RUN
                _ARH-R @ ARUNTIME.FLAGS @ ARUNTIME-F-EXPIRED AND IF
                    ARUN-S-EXPIRED -1
                ELSE
                    _ARH-R @ _AR-GATEWAY-PENDING? IF
                        _ARH-E @ AEV.RUN-ID @ _ARH-R @ ARUNTIME.EVENTS @
                        _ARH-R @ ARUNTIME.PROVIDER @ APROV-CANCEL DROP
                        ARUN-S-ERROR -1
                    ELSE
                        ARUN-S-IDLE 0
                    THEN
                THEN
                _ARH-R @ _AR-TERMINAL-BEGIN DROP
            THEN
        ENDOF
        AEV-CANCELLED OF
            _ARH-R @ ARUNTIME.FLAGS @ ARUNTIME-F-EXPIRED AND IF
                ARUN-S-EXPIRED
            ELSE
                ARUN-S-CANCELLED
            THEN -1 _ARH-R @ _AR-TERMINAL-BEGIN DROP
        ENDOF
        AEV-ERROR OF
            AROLE-SYSTEM AMSG-S-ERROR _ARH-E @ _ARH-R @
            _AR-APPEND-EVENT-MESSAGE DROP
            ARUN-S-ERROR -1 _ARH-R @ _AR-TERMINAL-BEGIN DROP
        ENDOF
    ENDCASE
    1 _ARH-R @ ARUNTIME.REVISION +!
    1 _ARH-R @ ARUNTIME.CONVERSATION @ ACONV.REVISION +! ;

VARIABLE _ARP-R
VARIABLE _ARP-N
VARIABLE _ARP-MAX
VARIABLE _ARP-POLL-RUN
VARIABLE _ARPF-R
VARIABLE _ARPF-FOUND
VARIABLE _ARPF-E

: _AR-POLL-FAIL-DRAIN  ( runtime -- diagnostic? )
    _ARPF-R ! 0 _ARPF-FOUND !
    BEGIN
        _ARPF-R @ ARUNTIME.EVENT-SCRATCH
        _ARPF-R @ ARUNTIME.EVENTS @ AEQ-POP
    WHILE
        _ARPF-R @ ARUNTIME.EVENT-SCRATCH DUP _ARPF-E ! AEV.KIND @
        AEV-ERROR =
        _ARPF-E @ AEV.RUN-ID @ DUP 0= SWAP _ARP-POLL-RUN @ = OR AND
        _ARPF-FOUND @ 0= AND IF
            AROLE-SYSTEM AMSG-S-ERROR
            _ARPF-E @ _ARPF-R @
            _AR-APPEND-EVENT-MESSAGE 0<> _ARPF-FOUND !
        THEN
        _ARPF-R @ ARUNTIME.EVENT-SCRATCH AEV-FREE
        1 _ARP-N +!
    REPEAT
    _ARPF-FOUND @ ;

: _AR-POLL-FAIL-GENERIC  ( runtime -- )
    _ARPF-R !
    AROLE-SYSTEM AMSG-S-ERROR _ARP-POLL-RUN @
    S" Provider poll failed."
    _ARPF-R @ ARUNTIME.CONVERSATION @ ACONV-APPEND
    DUP IF 2DROP ELSE DROP DROP THEN ;

: _ARUNTIME-AUTH-READY  ( runtime -- changed? )
    DUP _ARPC-R ! ARUNTIME-RUN-SETTINGS DUP IF
        DUP _ARPC-SETTINGS ! ARSET.STATE @ ARSET-STATE-READY = IF
            _ARPC-R @ ARUNTIME.PROVIDER @ APROV.STATE @ APROV-S-READY <> IF
                _ARPC-R @ _ARUNTIME-CONNECT-PROVIDER DROP
            THEN
        ELSE
            _ARPC-SETTINGS @ ARSET.STATE @ ARSET-STATE-LOADING <> IF
                _ARPC-R @ _ARUNTIME-REFRESH-SETTINGS DROP
            THEN
        THEN
    ELSE
        DROP
        _ARPC-R @ ARUNTIME.PROVIDER @ APROV.STATE @ APROV-S-READY <> IF
            _ARPC-R @ _ARUNTIME-CONNECT-PROVIDER DROP
        THEN
    THEN
    1 _ARPC-R @ ARUNTIME.REVISION +! -1 ;

: _ARUNTIME-PUMP-AUTH  ( runtime -- changed? )
    DUP >R ARUNTIME.PROVIDER @ APROV-AUTH DUP 0= IF
        DROP R> DROP 0 EXIT
    THEN
    DUP AAUTH-PENDING? 0= IF
        DROP R> DROP 0 EXIT
    THEN
    AAUTH-POLL DUP AAUTH-S-PENDING = IF DROP R> DROP -1 EXIT THEN
    DUP AAUTH-S-OK = IF
        DROP R@ ARUNTIME.PROVIDER @ APROV-AUTH AAUTH-READY? IF
            R@ _ARUNTIME-AUTH-READY DROP
        THEN
        R> DROP -1 EXIT
    THEN
    DROP ARUN-S-ERROR R> ARUNTIME.STATUS ! -1 ;

: _ARUNTIME-PUMP-SETTINGS  ( runtime -- changed? )
    DUP _ARPC-R ! ARUNTIME-RUN-SETTINGS DUP 0= IF DROP 0 EXIT THEN
    DUP _ARPC-SETTINGS ! ARSET.STATE @ ARSET-STATE-LOADING <> IF 0 EXIT THEN
    _ARPC-SETTINGS @ ARSET-POLL DUP ARSET-S-PENDING = IF DROP 0 EXIT THEN
    ARSET-S-OK = _ARPC-SETTINGS @ ARSET.STATE @ ARSET-STATE-READY = AND IF
        _ARPC-R @ ARUNTIME.PROVIDER @ APROV.STATE @ APROV-S-READY <> IF
            _ARPC-R @ _ARUNTIME-CONNECT-PROVIDER DROP
        THEN
    ELSE
        ARUN-S-ERROR _ARPC-R @ ARUNTIME.STATUS !
    THEN
    1 _ARPC-R @ ARUNTIME.REVISION +! -1 ;

VARIABLE _ARG-R
VARIABLE _ARG-G
VARIABLE _ARG-REQ
VARIABLE _ARG-STATUS
: _AR-REVIEW-PERSISTED?  ( runtime -- flag )
    DUP ARUNTIME.CONVERSATION-STORE @ 0= IF DROP 0 EXIT THEN
    ARUNTIME-PERSIST-FORCE ACSTORE-S-OK = ;

: _AR-PUMP-GATEWAY  ( runtime -- changed? )
    DUP _ARG-R ! ARUNTIME.TOOL-GATEWAY @ DUP 0= IF DROP 0 EXIT THEN
    DUP _ARG-G ! ATOOLG.STATE @
    _ARG-R @ ARUNTIME.FLAGS @ ARUNTIME-F-TERMINATING AND IF
        DROP
        _ARG-R @ _AR-TERMINAL-FINISH DUP CBUS-S-OK = IF
            DROP
            1 _ARG-R @ ARUNTIME.REVISION +!
            1 _ARG-R @ ARUNTIME.CONVERSATION @ ACONV.REVISION +!
            -1
        ELSE
            DROP 0
        THEN EXIT
    THEN
    DUP ATOOLG-S-APPROVAL = IF
        DROP
        _ARG-R @ ARUNTIME.STATUS @ ARUN-S-APPROVAL = IF 0 EXIT THEN
        \ A reviewed commit is not offered unless the exact pre-review
        \ transcript, including the owned tool request, is durable.
        _ARG-R @ _AR-REVIEW-PERSISTED? 0= IF
            AMSG-S-ERROR _ARG-R @ _AR-APPROVAL-STATE!
            0 _ARG-G @ ATOOLG-RESOLVE DROP
            ARUN-S-RUNNING _ARG-R @ ARUNTIME.STATUS !
            1 _ARG-R @ ARUNTIME.REVISION +!
            1 _ARG-R @ ARUNTIME.CONVERSATION @ ACONV.REVISION +!
            -1 EXIT
        THEN
        _ARG-R @ ARUNTIME.APPROVAL-MSG @ ?DUP IF
            AMSG-S-APPROVAL SWAP AMSG.STATE !
        THEN
        ARUN-S-APPROVAL _ARG-R @ ARUNTIME.STATUS !
        1 _ARG-R @ ARUNTIME.REVISION +!
        1 _ARG-R @ ARUNTIME.CONVERSATION @ ACONV.REVISION +!
        -1 EXIT
    THEN
    ATOOLG-S-COMPLETE <> IF 0 EXIT THEN
    _ARG-G @ ATOOLG.REQUEST @ DUP _ARG-REQ !
    CBR.STATUS @ DUP _ARG-STATUS !
    CBUS-S-CANCELLED = IF
        _ARG-R @ ARUNTIME.APPROVAL-MSG @ ?DUP IF
            AMSG-S-CANCELLED SWAP AMSG.STATE !
        THEN
        _ARG-G @ ATOOLG-CLEAR DROP
        1 _ARG-R @ ARUNTIME.REVISION +!
        1 _ARG-R @ ARUNTIME.CONVERSATION @ ACONV.REVISION +!
        -1 EXIT
    THEN
    _ARG-R @ ARUNTIME.APPROVAL-MSG @ ?DUP IF
        _ARG-STATUS @ CBUS-S-OK = IF
            AMSG-S-COMPLETE
        ELSE
            AMSG-S-ERROR
        THEN
        SWAP AMSG.STATE !
    THEN
    _ARG-G @ ATOOLG.RUN-ID @
    _ARG-G @ ATOOLG.NAME DUP CV-DATA@ SWAP CV-LEN@
    _ARG-REQ @ CBR.RESULT _ARG-STATUS @ _ARG-R @
    _AR-PROVIDER-TOOL-RESULT
    DUP IF
        _ARG-R @ ARUNTIME.ACTIVE-RUN @
        _ARG-R @ ARUNTIME.EVENTS @ _ARG-R @ ARUNTIME.PROVIDER @
            APROV-CANCEL DROP
        ARUN-S-ERROR -1 _ARG-R @ _AR-TERMINAL-BEGIN DROP
    ELSE
        ARUN-S-RUNNING _ARG-R @ ARUNTIME.STATUS !
        _ARG-G @ ATOOLG-CLEAR DROP
    THEN DROP
    1 _ARG-R @ ARUNTIME.REVISION +!
    1 _ARG-R @ ARUNTIME.CONVERSATION @ ACONV.REVISION +!
    -1 ;

VARIABLE _AREX-R
VARIABLE _AREX-RUN

\ Expiry is fail-closed even when no further tool is attempted.  Authority
\ becomes unusable at the AMRUN deadline; the pump proactively cancels both
\ gateway and provider work and refuses another send until a terminal event.
: _ARUNTIME-PUMP-EXPIRY  ( runtime -- changed? )
    DUP _AREX-R ! ARUNTIME.MANDATE-RUN @ DUP 0= IF DROP 0 EXIT THEN
    AMRUN-ACTIVE? IF 0 EXIT THEN
    _AREX-R @ ARUNTIME.FLAGS @ ARUNTIME-F-EXPIRED AND IF 0 EXIT THEN
    _AREX-R @ ARUNTIME.ACTIVE-RUN @ DUP _AREX-RUN ! 0= IF
        _AREX-R @ _ARUNTIME-MANDATE-END DROP 0 EXIT
    THEN
    _AREX-R @ ARUNTIME.FLAGS DUP @ ARUNTIME-F-EXPIRED OR SWAP !
    _AREX-RUN @ _AREX-R @ ARUNTIME.EVENTS @
        _AREX-R @ ARUNTIME.PROVIDER @ APROV-CANCEL DROP
    ARUN-S-EXPIRED -1 _AREX-R @ _AR-TERMINAL-BEGIN DROP
    1 _AREX-R @ ARUNTIME.REVISION +!
    1 _AREX-R @ ARUNTIME.CONVERSATION @ ACONV.REVISION +!
    -1 ;

: ARUNTIME-PUMP  ( max-events runtime -- count )
    _ARP-R ! _ARP-MAX ! 0 _ARP-N !
    0 _ARP-POLL-RUN !
    _ARP-R @ _ARUNTIME-PUMP-EXPIRY IF 1 _ARP-N +! THEN
    _ARP-R @ _ARUNTIME-PUMP-AUTH IF 1 _ARP-N +! THEN
    _ARP-R @ _ARUNTIME-PUMP-SETTINGS IF 1 _ARP-N +! THEN
    _ARP-R @ _AR-PUMP-GATEWAY IF 1 _ARP-N +! THEN
    _ARP-R @ ARUNTIME.FLAGS @ ARUNTIME-F-TERMINATING AND IF
        _ARP-N @ IF _ARP-R @ ARUNTIME-PERSIST DROP THEN
        _ARP-N @ EXIT
    THEN
    _ARP-R @ ARUNTIME.EVENTS @ _ARP-R @ ARUNTIME.PROVIDER @ APROV-POLL
    IF
        _ARP-R @ ARUNTIME.ACTIVE-RUN @ _ARP-POLL-RUN !
        1 _ARP-N +!
        \ Poll failure is already the selected terminal cause.  Preserve one
        \ exact matching diagnostic, discard every other queued provider event
        \ without dispatch, and only then cancel local/provider work.
        _ARP-R @ _AR-POLL-FAIL-DRAIN 0= IF
            _ARP-R @ _AR-POLL-FAIL-GENERIC
        THEN
        _ARP-POLL-RUN @ IF
            _ARP-R @ _AR-FAIL-RUN
        ELSE
            ARUN-S-ERROR _ARP-R @ ARUNTIME.STATUS !
            1 _ARP-R @ ARUNTIME.REVISION +!
        THEN
    ELSE
        _ARP-MAX @ 0 ?DO
            _ARP-R @ ARUNTIME.EVENT-SCRATCH
            _ARP-R @ ARUNTIME.EVENTS @ AEQ-POP 0= IF LEAVE THEN
            _ARP-R @ ARUNTIME.EVENT-SCRATCH _ARP-R @ _AR-HANDLE-EVENT
            _ARP-R @ ARUNTIME.EVENT-SCRATCH AEV-FREE
            1 _ARP-N +!
        LOOP
    THEN
    _ARP-N @ IF _ARP-R @ ARUNTIME-PERSIST DROP THEN
    _ARP-N @ ;

VARIABLE _ARC-R
VARIABLE _ARC-RUN
VARIABLE _ARC-IOR
VARIABLE _ARC-STORE

: ARUNTIME-CANCEL  ( runtime -- ior )
    DUP _ARC-R ! ARUNTIME.ACTIVE-RUN @ DUP 0= IF DROP 0 EXIT THEN
    _ARC-RUN !
    _ARC-RUN @ _ARC-R @ ARUNTIME.EVENTS @
    _ARC-R @ ARUNTIME.PROVIDER @ APROV-CANCEL _ARC-IOR !
    ARUN-S-CANCELLED -1 _ARC-R @ _AR-TERMINAL-BEGIN DROP
    _ARC-R @ ARUNTIME-PERSIST-FORCE _ARC-STORE !
    _ARC-IOR @ ?DUP IF EXIT THEN
    _ARC-STORE @ ;

VARIABLE _ARQ-R
VARIABLE _ARQ-G

: ARUNTIME-QUIESCE  ( runtime -- status )
    DUP _ARQ-R ! ARUNTIME.TOOL-GATEWAY @ _ARQ-G !
    _ARQ-R @ ARUNTIME.ACTIVE-RUN @ IF
        _ARQ-R @ ARUNTIME-CANCEL DROP
    ELSE
        _ARQ-R @ ARUNTIME.MANDATE-RUN @
        _ARQ-R @ _AR-GATEWAY-PENDING? OR IF
            ARUN-S-CANCELLED -1 _ARQ-R @ _AR-TERMINAL-BEGIN DROP
        THEN
    THEN
    CBUS-CAPACITY 1+ 0 DO
        _ARQ-R @ ARUNTIME.FLAGS @ ARUNTIME-F-TERMINATING AND 0= IF
            LEAVE
        THEN
        _ARQ-G @ ?DUP IF
            DUP ATOOLG.STATE @ ATOOLG-S-QUEUED = IF
                DUP ATOOLG.BUS @ 1 SWAP CBUS-PUMP DROP
            THEN
            DROP
        THEN
        _ARQ-R @ _AR-PUMP-GATEWAY DROP
    LOOP
    _ARQ-R @ ARUNTIME.FLAGS @ ARUNTIME-F-TERMINATING AND IF
        CBUS-S-BUSY EXIT
    THEN
    _ARQ-R @ ARUNTIME.ACTIVE-RUN @ IF CBUS-S-BUSY EXIT THEN
    _ARQ-R @ ARUNTIME.MANDATE-RUN @ IF CBUS-S-BUSY EXIT THEN
    _ARQ-G @ ?DUP IF
        ATOOLG.STATE @ ATOOLG-S-IDLE <> IF CBUS-S-BUSY EXIT THEN
    THEN
    CBUS-S-OK ;

: ARUNTIME-FREE  ( runtime -- )
    DUP 0= IF DROP EXIT THEN
    DUP ARUNTIME-QUIESCE
        ABORT" agent runtime could not quiesce outstanding authority"
    >R
    R@ ARUNTIME-PERSIST-FORCE DROP
    R@ ARUNTIME.EVENTS @ R@ ARUNTIME.PROVIDER @ APROV-DISCONNECT
    R@ ARUNTIME.EVENT-SCRATCH AEV-FREE
    R@ ARUNTIME.DISCLOSURE-CONTEXT @ ?DUP IF ACTX-FREE THEN
    R@ ARUNTIME.CONVERSATION @ ACONV-FREE
    R@ ARUNTIME.EVENTS @ AEQ-FREE
    R@ ARUNTIME.CONVERSATION-STORE @ ?DUP IF ACSTORE-FREE THEN
    R> FREE ;

VARIABLE _ARAD-APPROVED
VARIABLE _ARAD-R
VARIABLE _ARAD-M
VARIABLE _ARAD-ACTION?
VARIABLE _ARAD-NA
VARIABLE _ARAD-NU
VARIABLE _ARAD-CALL
VARIABLE _ARAD-STATUS
VARIABLE _ARAD-G
VARIABLE _ARAD-REQ
VARIABLE _ARAD-DA
VARIABLE _ARAD-DU
VARIABLE _ARAD-AU
VARIABLE _ARAD-CA
VARIABLE _ARAD-CU
VARIABLE _ARAD-CSTATUS
VARIABLE _ARAD-LOCAL
CREATE _ARAD-CELL 8 ALLOT
CREATE _ARAD-HEX SHA3-256-LEN 2* ALLOT

: _ARAD-APPEND  ( addr len -- )
    _ARAD-STATUS @ IF 2DROP EXIT THEN
    _ARAD-M @ AMSG-APPEND _ARAD-STATUS ! ;

: _ARAD-APPEND-CELL-LE  ( value -- )
    _ARAD-CELL !
    _ARAD-CELL 8 _ARAD-HEX FMT->HEX
    _ARAD-HEX SWAP _ARAD-APPEND ;

: _ARAD-APPEND-DIGEST  ( digest -- )
    SHA3-256-LEN _ARAD-HEX FMT->HEX
    _ARAD-HEX SWAP _ARAD-APPEND ;

: _ARAD-LOCAL-ENVELOPE  ( -- )
    _ARAD-G @ ATOOLG.REQUEST @ DUP _ARAD-REQ ! 0= IF
        CBUS-S-INVALID _ARAD-STATUS ! EXIT
    THEN
    S" ; target_id_le=" _ARAD-APPEND
    _ARAD-REQ @ CBR.TARGET-ID @ _ARAD-APPEND-CELL-LE
    S" ; target_generation_le=" _ARAD-APPEND
    _ARAD-REQ @ CBR.TARGET-GEN @ _ARAD-APPEND-CELL-LE
    S" ; expected_revision_le=" _ARAD-APPEND
    _ARAD-REQ @ CBR.EXPECT-REV @ _ARAD-APPEND-CELL-LE
    S" ; effects_le=" _ARAD-APPEND
    _ARAD-REQ @ CBR.CAP @ ?DUP IF
        CAP.EFFECTS @ _ARAD-APPEND-CELL-LE
    ELSE
        CBUS-S-INVALID _ARAD-STATUS ! EXIT
    THEN
    _ARAD-G @ ATOOLG-ARGS-FINGERPRINT
    DUP 0= IF 2DROP DROP CBUS-S-INVALID _ARAD-STATUS ! EXIT THEN
    _ARAD-AU ! DROP _ARAD-DA !
    S" ; args_encoding=typed-ivjson-v1; args_length_le=" _ARAD-APPEND
    _ARAD-AU @ _ARAD-APPEND-CELL-LE
    S" ; args_fingerprint_domain=akashic.agent.cbr-args.typed-ivjson.v1"
        _ARAD-APPEND
    S" ; args_fingerprint_sha3_256=" _ARAD-APPEND
    _ARAD-DA @ _ARAD-APPEND-DIGEST
    S" ; args=" _ARAD-APPEND
    _ARAD-STATUS @ IF EXIT THEN
    _ARAD-G @ ATOOLG-ARGS-FINGERPRINT-MATCH? 0= IF
        S" <omitted: operand no longer matches creation fingerprint>"
            _ARAD-APPEND EXIT
    THEN
    _ARAD-G @ ATOOLG-ARGS-CANONICAL-ALLOC
    _ARAD-CSTATUS ! _ARAD-CU ! _ARAD-CA !
    _ARAD-CSTATUS @ IF _ARAD-CSTATUS @ _ARAD-STATUS ! EXIT THEN
    _ARAD-CU @ ATOOLG-ARGS-REVIEW-MAX <= IF
        _ARAD-CA @ _ARAD-CU @ _ARAD-APPEND
    ELSE
        S" <omitted: canonical args exceed inline audit limit>"
            _ARAD-APPEND
    THEN
    _ARAD-CA @ FREE ;

: _ARUNTIME-AUDIT-ACTION  ( -- )
    0 _ARAD-ACTION? !
    _ARAD-R @ ARUNTIME.TOOL-GATEWAY @ ?DUP IF
        DUP _ARAD-G !
        ATOOLG.NAME DUP CV-TYPE@ CV-T-STRING = IF
            DUP CV-DATA@ SWAP CV-LEN@ _ARAD-NU ! _ARAD-NA !
            S" local tool " _ARAD-APPEND
            _ARAD-NA @ _ARAD-NU @ _ARAD-APPEND
            S" ; provider=" _ARAD-APPEND
            _ARAD-R @ _AR-PROVIDER-ID _ARAD-APPEND
            _ARAD-R @ ARUNTIME.ACTIVE-RUN @
            _ARAD-NA @ _ARAD-NU @ _ARAD-R @ ARUNTIME-MODEL-CONTEXT
                ACTX-LAST-TOOL-CALL DUP _ARAD-CALL ! IF
                S"  [call " _ARAD-APPEND
                _ARAD-CALL @ ACTXI-CALL-ID-TEXT _ARAD-APPEND
                S" ]" _ARAD-APPEND
            THEN
            _ARAD-LOCAL-ENVELOPE
            -1 _ARAD-ACTION? !
        ELSE
            DROP
        THEN
    THEN
    _ARAD-ACTION? @ 0= IF
        S" provider " _ARAD-APPEND
        _ARAD-R @ _AR-PROVIDER-ID _ARAD-APPEND
        S" : " _ARAD-APPEND
        _ARAD-R @ ARUNTIME.APPROVAL-MSG @ ?DUP IF
            AMSG-TEXT _ARAD-APPEND
        THEN
    THEN ;

: _ARUNTIME-AUDIT-DECISION  ( approved runtime -- status )
    _ARAD-R ! _ARAD-APPROVED !
    0 _ARAD-STATUS ! 0 _ARAD-LOCAL !
    _ARAD-R @ ARUNTIME.TOOL-GATEWAY @ ?DUP IF
        ATOOLG.STATE @ ATOOLG-S-APPROVAL = IF -1 _ARAD-LOCAL ! THEN
    THEN
    1 _ARAD-R @ ARUNTIME.CONVERSATION @ ACONV-ROOM? 0= IF
        ACSTORE-S-CAPACITY EXIT
    THEN
    _ARAD-LOCAL @ _ARAD-R @ ARUNTIME.CONVERSATION-STORE @ 0= AND IF
        ACSTORE-S-UNAVAILABLE EXIT
    THEN
    AROLE-SYSTEM AMSG-S-COMPLETE
    _ARAD-R @ ARUNTIME.ACTIVE-RUN @
    _ARAD-APPROVED @ IF S" Approved agent action: " ELSE S" Denied agent action: " THEN
    _ARAD-R @ ARUNTIME.CONVERSATION @ ACONV-APPEND
    DUP IF NIP EXIT THEN
    DROP DUP _ARAD-M ! DROP
    AMSG-F-AUDIT
    _ARAD-APPROVED @ IF AMSG-F-APPROVED ELSE AMSG-F-DENIED THEN OR
    _ARAD-M @ AMSG.FLAGS !
    _ARUNTIME-AUDIT-ACTION
    _ARAD-STATUS @ IF
        _ARAD-R @ ARUNTIME.CONVERSATION @ ACONV-DROP-LAST
        _ARAD-STATUS @ EXIT
    THEN
    1 _ARAD-R @ ARUNTIME.REVISION +!
    _ARAD-R @ ARUNTIME-PERSIST-FORCE DUP IF
        \ A failed save must not leave an in-memory APPROVED record that a
        \ later unrelated save could make durable despite denied execution.
        DUP _ARAD-STATUS ! DROP
        _ARAD-R @ ARUNTIME.CONVERSATION @ ACONV-DROP-LAST
        1 _ARAD-R @ ARUNTIME.REVISION +!
        _ARAD-STATUS @
    THEN ;

VARIABLE _ARR-APPROVED
VARIABLE _ARR-R
VARIABLE _ARR-IOR
VARIABLE _ARR-LOCAL
VARIABLE _ARR-FORCED-DENY

: ARUNTIME-RESOLVE  ( approved runtime -- ior )
    _ARR-R ! _ARR-APPROVED !
    0 _ARR-LOCAL ! 0 _ARR-FORCED-DENY !
    _ARR-R @ ARUNTIME.STATUS @ ARUN-S-APPROVAL <> IF 1 EXIT THEN
    \ Never persist an APPROVED audit record for an operand that cannot be
    \ reviewed completely or that no longer matches its owned fingerprint.
    \ Normalize the request to a durable denial before touching authority.
    _ARR-APPROVED @ IF
        _ARR-R @ ARUNTIME.TOOL-GATEWAY @ ?DUP IF
            DUP ATOOLG.STATE @ ATOOLG-S-APPROVAL = IF
                ATOOLG-ARGS-REVIEWABLE? 0= IF
                    0 _ARR-APPROVED ! -1 _ARR-FORCED-DENY !
                THEN
            ELSE
                DROP
            THEN
        THEN
    THEN
    _ARR-APPROVED @ _ARR-R @ _ARUNTIME-AUDIT-DECISION DUP IF
        _ARR-IOR !
        \ No reviewed authority is issued unless the complete audit record
        \ is durable.  Settle the pending request as denied and keep the
        \ failed approval visible as an error.
        _ARR-R @ ARUNTIME.TOOL-GATEWAY @ ?DUP IF
            DUP ATOOLG.STATE @ ATOOLG-S-APPROVAL = IF
                -1 _ARR-LOCAL !
                0 SWAP ATOOLG-RESOLVE DROP
            ELSE
                DROP
            THEN
        THEN
        _ARR-LOCAL @ 0= IF
            0 _ARR-R @ ARUNTIME.ACTIVE-RUN @
            _ARR-R @ ARUNTIME.EVENTS @
            _ARR-R @ ARUNTIME.PROVIDER @ APROV-RESOLVE ?DUP IF
                _ARR-IOR ! _ARR-R @ _AR-FAIL-RUN
                _ARR-R @ ARUNTIME-PERSIST-FORCE DROP
                _ARR-IOR @ EXIT
            THEN
        THEN
        AMSG-S-ERROR _ARR-R @ _AR-APPROVAL-STATE!
        ARUN-S-RUNNING _ARR-R @ ARUNTIME.STATUS !
        _ARR-R @ _AR-PUMP-GATEWAY DROP
        _ARR-IOR @ EXIT
    THEN DROP
    _ARR-R @ ARUNTIME.TOOL-GATEWAY @ ?DUP IF
        DUP ATOOLG.STATE @ ATOOLG-S-APPROVAL = IF
            _ARR-APPROVED @ SWAP ATOOLG-RESOLVE
            DUP 0= IF
                _ARR-APPROVED @ IF AMSG-S-PENDING ELSE AMSG-S-ERROR THEN
                    _ARR-R @ _AR-APPROVAL-STATE!
                ARUN-S-RUNNING _ARR-R @ ARUNTIME.STATUS !
                _ARR-R @ _AR-PUMP-GATEWAY DROP
                8 _ARR-R @ ARUNTIME-PUMP DROP
            ELSE
                \ Grant/post failures must not hide an actionable approval.
                DUP _ARR-IOR ! DROP
                0 _ARR-R @ ARUNTIME.TOOL-GATEWAY @
                    ATOOLG-RESOLVE DROP
                AMSG-S-ERROR _ARR-R @ _AR-APPROVAL-STATE!
                ARUN-S-RUNNING _ARR-R @ ARUNTIME.STATUS !
                _ARR-R @ _AR-PUMP-GATEWAY DROP _ARR-IOR @
            THEN
            _ARR-R @ ARUNTIME-PERSIST-FORCE DROP
            DUP 0= _ARR-FORCED-DENY @ AND IF
                DROP CBUS-S-DENIED
            THEN
            EXIT
        THEN
        DROP
    THEN
    _ARR-APPROVED @ _ARR-R @ ARUNTIME.ACTIVE-RUN @
    _ARR-R @ ARUNTIME.EVENTS @ _ARR-R @ ARUNTIME.PROVIDER @ APROV-RESOLVE
    DUP 0= IF
        AMSG-S-COMPLETE _ARR-R @ _AR-APPROVAL-STATE!
        ARUN-S-RUNNING _ARR-R @ ARUNTIME.STATUS !
    ELSE
        DUP _ARR-IOR ! DROP
        _ARR-R @ _AR-FAIL-RUN
        _ARR-R @ ARUNTIME-PERSIST-FORCE DROP
        _ARR-IOR @
    THEN
    _ARR-R @ ARUNTIME-PERSIST-FORCE DROP ;

: ARUNTIME-CLEAR  ( runtime -- ior )
    DUP ARUNTIME.ACTIVE-RUN @ IF DROP 1 EXIT THEN
    DUP ARUNTIME.STATUS @ DUP ARUN-S-RUNNING =
    SWAP ARUN-S-APPROVAL = OR IF DROP 1 EXIT THEN
    DUP ARUNTIME.CONVERSATION @ ACONV-CLEAR
    DUP _ARUNTIME-MANDATE-END DROP
    DUP ARUNTIME.TOOL-GATEWAY @ ?DUP IF ATOOLG-CLEAR DROP THEN
    DUP ARUNTIME.DISCLOSURE-CONTEXT @ ?DUP IF ACTX-CLEAR THEN
    0 OVER ARUNTIME.ASSISTANT-MSG !
    0 OVER ARUNTIME.APPROVAL-MSG !
    0 OVER ARUNTIME.LAST-DISCLOSURE-ITEMS !
    0 OVER ARUNTIME.LAST-DISCLOSURE-BYTES !
    0 OVER ARUNTIME.LAST-REMOTE-MS !
    0 OVER ARUNTIME.LAST-REMOTE-RUN !
    0 OVER ARUNTIME.FLAGS !
    1 OVER ARUNTIME.REVISION +!
    ARUNTIME-PERSIST-FORCE DROP 0 ;

: ARUNTIME-RECONNECT  ( runtime -- ior )
    DUP ARUNTIME.ACTIVE-RUN @ IF DROP 1 EXIT THEN
    DUP ARUNTIME.MANDATE-RUN @ IF DROP 1 EXIT THEN
    DUP ARUNTIME-RUN-SETTINGS ?DUP IF
        ARSET.STATE @ ARSET-STATE-READY <> IF DROP 1 EXIT THEN
    THEN
    DUP >R ARUNTIME.EVENTS @ R@ ARUNTIME.PROVIDER @ APROV-CONNECT
    DUP IF ARUN-S-ERROR ELSE ARUN-S-OFFLINE THEN
    R@ ARUNTIME.STATUS !
    1 R> ARUNTIME.REVISION +! ;

VARIABLE _ARA-A
VARIABLE _ARA-U
VARIABLE _ARA-R
VARIABLE _ARA-STATUS

: _ARUNTIME-CLEAR-SETTINGS  ( runtime -- )
    ARUNTIME-RUN-SETTINGS ?DUP IF ARSET-CANCEL DROP THEN ;

: ARUNTIME-AUTH  ( runtime -- auth | 0 )
    ARUNTIME.PROVIDER @ APROV-AUTH ;

: ARUNTIME-BUSY?  ( runtime -- flag )
    DUP ARUNTIME.ACTIVE-RUN @ IF DROP -1 EXIT THEN
    ARUNTIME.STATUS @ DUP ARUN-S-RUNNING =
    SWAP ARUN-S-APPROVAL = OR ;

: ARUNTIME-AUTH-SET  ( secret-a secret-u runtime -- status )
    _ARA-R ! _ARA-U ! _ARA-A !
    _ARA-R @ ARUNTIME-BUSY? IF AAUTH-S-BUSY EXIT THEN
    _ARA-A @ _ARA-U @ _ARA-R @ ARUNTIME-AUTH DUP 0= IF
        DROP 2DROP AAUTH-S-UNSUPPORTED EXIT
    THEN
    AAUTH-SECRET-SET
    DUP _ARA-STATUS ! IF _ARA-STATUS @ EXIT THEN
    _ARA-R @ ARUNTIME-RUN-SETTINGS IF
        _ARA-R @ _ARUNTIME-CLEAR-SETTINGS
        _ARA-R @ _ARUNTIME-AUTH-READY DROP
    ELSE
        _ARA-R @ ARUNTIME-RECONNECT DROP
    THEN
    AAUTH-S-OK ;

: ARUNTIME-AUTH-CLEAR  ( runtime -- status )
    DUP _ARA-R ! ARUNTIME-BUSY? IF AAUTH-S-BUSY EXIT THEN
    _ARA-R @ ARUNTIME-AUTH DUP 0= IF DROP AAUTH-S-UNSUPPORTED EXIT THEN
    AAUTH-LOGOUT
    DUP _ARA-STATUS ! IF _ARA-STATUS @ EXIT THEN
    _ARA-R @ ARUNTIME.EVENTS @ _ARA-R @ ARUNTIME.PROVIDER @ APROV-DISCONNECT
    _ARA-R @ _ARUNTIME-CLEAR-SETTINGS
    ARUN-S-OFFLINE _ARA-R @ ARUNTIME.STATUS !
    1 _ARA-R @ ARUNTIME.REVISION +!
    AAUTH-S-OK ;

: ARUNTIME-AUTH-PRESENT?  ( runtime -- flag )
    ARUNTIME-AUTH AAUTH-READY? ;

: ARUNTIME-AUTH-BEGIN  ( runtime -- status )
    DUP _ARA-R ! ARUNTIME-BUSY? IF AAUTH-S-BUSY EXIT THEN
    _ARA-R @ ARUNTIME-AUTH DUP 0= IF DROP AAUTH-S-UNSUPPORTED EXIT THEN
    DUP AAUTH.METHODS @ AAUTH-M-DEVICE AND 0= IF
        DROP AAUTH-S-UNSUPPORTED EXIT
    THEN
    AAUTH-BEGIN DUP _ARA-STATUS !
    _ARA-STATUS @ DUP AAUTH-S-OK = SWAP AAUTH-S-PENDING = OR IF
        _ARA-R @ ARUNTIME.EVENTS @ _ARA-R @ ARUNTIME.PROVIDER @ APROV-DISCONNECT
        _ARA-R @ _ARUNTIME-CLEAR-SETTINGS
        ARUN-S-OFFLINE _ARA-R @ ARUNTIME.STATUS !
        1 _ARA-R @ ARUNTIME.REVISION +!
    THEN
    _ARA-STATUS @ ;

: ARUNTIME-AUTH-CANCEL  ( runtime -- status )
    DUP _ARA-R ! ARUNTIME-AUTH DUP 0= IF DROP AAUTH-S-UNSUPPORTED EXIT THEN
    AAUTH-CANCEL DUP _ARA-STATUS !
    1 _ARA-R @ ARUNTIME.REVISION +!
    _ARA-STATUS @ ;

VARIABLE _ARRS-R
VARIABLE _ARRS-I
VARIABLE _ARRS-STATUS

: ARUNTIME-RUN-SETTINGS-REFRESH  ( runtime -- status )
    DUP _ARRS-R ! ARUNTIME-BUSY? IF ARSET-S-BUSY EXIT THEN
    _ARRS-R @ ARUNTIME-RUN-SETTINGS DUP 0= IF
        DROP ARSET-S-UNSUPPORTED EXIT
    THEN
    _ARRS-R @ ARUNTIME.EVENTS @
    _ARRS-R @ ARUNTIME.PROVIDER @ APROV-DISCONNECT
    DROP _ARRS-R @ _ARUNTIME-REFRESH-SETTINGS DUP _ARRS-STATUS !
    1 _ARRS-R @ ARUNTIME.REVISION +!
    _ARRS-STATUS @ ;

: ARUNTIME-MODEL!  ( index runtime -- status )
    _ARRS-R ! _ARRS-I !
    _ARRS-R @ ARUNTIME-BUSY? IF ARSET-S-BUSY EXIT THEN
    _ARRS-R @ ARUNTIME-RUN-SETTINGS DUP 0= IF
        DROP ARSET-S-UNSUPPORTED EXIT
    THEN
    _ARRS-I @ SWAP ARSET-MODEL! DUP ARSET-S-OK = IF
        1 _ARRS-R @ ARUNTIME.REVISION +!
    THEN ;

: ARUNTIME-EFFORT!  ( index runtime -- status )
    _ARRS-R ! _ARRS-I !
    _ARRS-R @ ARUNTIME-BUSY? IF ARSET-S-BUSY EXIT THEN
    _ARRS-R @ ARUNTIME-RUN-SETTINGS DUP 0= IF
        DROP ARSET-S-UNSUPPORTED EXIT
    THEN
    _ARRS-I @ SWAP ARSET-EFFORT! DUP ARSET-S-OK = IF
        1 _ARRS-R @ ARUNTIME.REVISION +!
    THEN ;

: ARUNTIME-TIER!  ( index runtime -- status )
    _ARRS-R ! _ARRS-I !
    _ARRS-R @ ARUNTIME-BUSY? IF ARSET-S-BUSY EXIT THEN
    _ARRS-R @ ARUNTIME-RUN-SETTINGS DUP 0= IF
        DROP ARSET-S-UNSUPPORTED EXIT
    THEN
    _ARRS-I @ SWAP ARSET-TIER! DUP ARSET-S-OK = IF
        1 _ARRS-R @ ARUNTIME.REVISION +!
    THEN ;

: ARUNTIME-VERBOSITY!  ( verbosity runtime -- status )
    _ARRS-R ! _ARRS-I !
    _ARRS-R @ ARUNTIME-BUSY? IF ARSET-S-BUSY EXIT THEN
    _ARRS-R @ ARUNTIME-RUN-SETTINGS DUP 0= IF
        DROP ARSET-S-UNSUPPORTED EXIT
    THEN
    _ARRS-I @ SWAP ARSET-VERBOSITY! DUP ARSET-S-OK = IF
        1 _ARRS-R @ ARUNTIME.REVISION +!
    THEN ;
